My Project: src/constrain_pot.f90 File Reference
constrain_pot.f90 File Reference
Modules
module xtb_constrainpot
Functions/Subroutines
subroutine xtb_constrainpot::constrain_zaxis (fix, n, at, xyz, g, e)
subroutine xtb_constrainpot::constrain_pos (fix, n, at, xyz, g, e)
pure elemental integer function lin (i1, i2)
subroutine xtb_constrainpot::qpothess2 (fix, n, at, xyz, h)
subroutine xtb_constrainpot::constrain_dist (fix, n, at, xyz, g, e)
subroutine xtb_constrainpot::constrain_angle (fix, n, at, xyz, g, e)
subroutine xtb_constrainpot::constrain_dihedral (fix, n, at, xyz, g, e)
subroutine xtb_constrainpot::constrain_pot (fix, n, at, xyz, g, e)
subroutine xtb_constrainpot::constrain_hess (fix, n, at, xyz0, Hess)
Function/Subroutine Documentation
lin()
pure elemental integer function lin (integer, intent(in) i1, integer, intent(in) i2)
Definition at line 78 of file constrain_pot.f90.
    integer,intent(in) :: i1,i2
    integer :: idum1,idum2
    idum1=max(i1,i2)
    idum2=min(i1,i2)
    lin=idum2+idum1*(idum1-1)/2
Referenced by abcdisp(), xtb_scc_core::addanisotropich1(), xtb_aespot::aniso_electro(), xtb_aespot::aniso_grad(), xtb_gfnff_ini2::bond_hb_ahb_set(), xtb_gfnff_ini2::bond_hb_ahb_set1(), xtb_gfnff_ini2::bond_hbset(), xtb_gfnff_ini2::bond_hbset0(), xtb_xtb_hamiltonian::build_sdqh0(), xtb_xtb_hamiltonian_gpu::build_sdqh0_gpu(), xtb_dtrafo::cao2saop(), xtb_peeq::ccm_build_sh0(), xtb_aespot::checkspars(), xtb_gfnff_gdisp0::d3_gradient(), xtb_aespot::fockelectro(), gdisp(), xtb_gfnff_ini2::getnb(), getsymnum(), xtb_gfnff_ini2::gfnff_hbset(), xtb_gfnff_ini2::gfnff_hbset0(), xtb_gfnff_ini2::gfnff_neigh(), xtb_gfnff_gdisp0::lin(), lin(), xtb_lin::lin(), xtb_aespot::molmom(), xtb_gfnff_ini2::nbondmat(), xtb_peeq::pbc_build_sh0(), esp::propa0(), esp::propa1(), prsymat(), xtb_constrainpot::qpothess2(), xtb_scf::scf(), xtb_aespot::setdvsdq(), xtb_aespot::setvsdq(), shortest_distance(), and xtb_freq_io::wrhess().