My Project: src/define.f90 File Reference
define.f90 File Reference
Functions/Subroutines
subroutine eval_define (verbose)
Function/Subroutine Documentation
eval_define()
subroutine eval_define (logical, intent(in) verbose)
Definition at line 18 of file define.f90.
    use, intrinsic :: iso_fortran_env, only : id => output_unit
    use xtb_mctc_global, only : msgid, name
    implicit none
    logical,intent(in) :: verbose
    integer :: save_i
    if (verbose) then
       name = 'define'
       call definebanner
    endif
    save_i = msgid
    call raise('F','Your input has following faults:')
    call terminate(save_i)
References definebanner(), xtb_mctc_global::msgid, xtb_mctc_global::name, raise(), and terminate().
Referenced by xtb_prog_main::xtbmain().