My Project: src/elem.f90 File Reference
elem.f90 File Reference
Functions/Subroutines
subroutine elem (key1, nat)
Function/Subroutine Documentation
elem()
subroutine elem (character(len=*) key1, nat)
Definition at line 19 of file elem.f90.
    implicit double precision (a-h,o-z)
    character(len=*) :: key1
    character(len=2) :: e
    character(len=2),parameter :: elemnt(118) = (/ &
       & 'h ','he', &
       & 'li','be','b ','c ','n ','o ','f ','ne', &
       & 'na','mg','al','si','p ','s ','cl','ar', &
       & 'k ','ca', &
       & 'sc','ti','v ','cr','mn','fe','co','ni','cu','zn', &
       &           'ga','ge','as','se','br','kr', &
       & 'rb','sr', &
       & 'y ','zr','nb','mo','tc','ru','rh','pd','ag','cd', &
       &           'in','sn','sb','te','i ','xe', &
       & 'cs','ba','la', &
       & 'ce','pr','nd','pm','sm','eu','gd','tb','dy','ho','er','tm','yb', &
       & 'lu','hf','ta','w ','re','os','ir','pt','au','hg', &
       &           'tl','pb','bi','po','at','rn', &
       & 'fr','ra','ac', &
       & 'th','pa','u ','np','pu','am','cm','bk','cf','es','fm','md','no', &
       & 'lr','rf','db','sg','bh','hs','mt','ds','rg','cn', &
       &           'nh','fl','mc','lv','ts','og' /)
    nat=0
    e='  '
    do i=1,len(key1)
       if(key1(i:i).ne.' ') l=i
    enddo
    k=1
    do j=1,l
       if (k.gt.2)exit
       n=ichar(key1(j:j))
       if(len_trim(e).ge.1 .and. n.eq.ichar(' '))exit!break if space after elem. symbol
       if(len_trim(e).ge.1 .and. n.eq.9)exit !break if tab after elem. symbol
       if(n.ge.ichar('A') .and. n.le.ichar('Z') )then
          e(k:k)=char(n+ichar('a')-ichar('A'))
          k=k+1
       endif
       if(n.ge.ichar('a') .and. n.le.ichar('z') )then
          e(k:k)=key1(j:j)
          k=k+1
       endif
    enddo
    do i=1,118
       if(e.eq.elemnt(i))then
          nat=i
          return
       endif
    enddo
Referenced by alloc_symmetry_element(), check_transform_order(), check_transform_quality(), destroy_symmetry_element(), establish_pairs(), eval_optimization_target_function(), get_params(), optimize_transformation_params(), rdatomnumber(), rdcoord(), rdfix(), rdsdf(), xtb_embedding::read_pcem(), refine_symmetry_element(), and set_params().