My Project: src/eqrot.f90 File Reference
eqrot.f90 File Reference
Functions/Subroutines
logical function equalrot (i, j, nall, thr, rot)
logical function equalrot2 (i, j, nall, thr, rot)
real *8 function rotdiff (i, j, nall, rot)
Function/Subroutine Documentation
equalrot()
logical function equalrot (integer i, integer j, integer nall, real*8 thr, real*8, dimension(3,nall) rot)
Definition at line 20 of file eqrot.f90.
    implicit none
    integer i,j,nall
    real*8 rot(3,nall),r,r1,thr
    equalrot=.false.
    r1=rot(1,i)**2+rot(2,i)**2+rot(3,i)**2
    r=(rot(1,i)-rot(1,j))**2&
       & +(rot(2,i)-rot(2,j))**2&
       & +(rot(3,i)-rot(3,j))**2
    if(sqrt(r)/sqrt(r1).lt.thr) equalrot=.true.
References true().
equalrot2()
logical function equalrot2 (integer i, integer j, integer nall, real*8 thr, real*8, dimension(3,0:nall) rot)
Definition at line 36 of file eqrot.f90.
    implicit none
    integer i,j,nall
    real*8 rot(3,0:nall),r,r1,r2,thr
    equalrot2=.false.
    r1=rot(1,i)**2+rot(2,i)**2+rot(3,i)**2
    r2=rot(1,j)**2+rot(2,j)**2+rot(3,j)**2
    r=(rot(1,i)-rot(1,j))**2&
       & +(rot(2,i)-rot(2,j))**2&
       & +(rot(3,i)-rot(3,j))**2
    if(2.*sqrt(r)/(sqrt(r1)+sqrt(r2)).lt.thr) equalrot2=.true.
References true().
Referenced by xtb_screening::screen().
rotdiff()
real*8 function rotdiff (integer i, integer j, integer nall, real*8, dimension(3,nall) rot)
Definition at line 53 of file eqrot.f90.
    implicit none
    integer i,j,nall
    real*8 rot(3,nall),r,r1,r2
    r1=rot(1,i)**2+rot(2,i)**2+rot(3,i)**2
    r2=rot(1,j)**2+rot(2,j)**2+rot(3,j)**2
    r=(rot(1,i)-rot(1,j))**2&
       & +(rot(2,i)-rot(2,j))**2&
       & +(rot(3,i)-rot(3,j))**2
    rotdiff=2.*sqrt(r)/(sqrt(r1)+sqrt(r2))