My Project: src/mctc/error.f90 File Reference
error.f90 File Reference
Functions/Subroutines
subroutine raise (mode, message)
subroutine terminate (signal)
subroutine wsigint
subroutine wsigterm
Function/Subroutine Documentation
raise()
subroutine raise (character, intent(in) mode, character(len=*), intent(in) message)
Definition at line 18 of file error.f90.
    use xtb_mctc_global
    implicit none
    character, intent(in) :: mode
    character(len=*), intent(in) :: message
    select case(mode)
    case('S','s') ! save to message buffer
       if (strict) then
          call persistentenv%error(message)
          call persistentenv%terminate("Global environment terminated")
       else
          call persistentenv%warning(message)
       endif
    case('F','f') ! flush message buffer
       call persistentenv%checkpoint(message)
    case('W','w') ! print warning directly
       if (strict) then
          call persistentenv%error(message)
          call persistentenv%terminate("Global environment terminated")
       else
          call persistentenv%warning(message)
       endif
    case('E','e')
       call persistentenv%error(message)
       call persistentenv%terminate("Global environment terminated")
    end select
References xtb_mctc_global::persistentenv, and xtb_mctc_global::strict.
Referenced by xtb_sphereparam::cavity_egrad(), countfix(), xtb_mctc_la::blckmgs::dblckmgs(), esp::espplot(), eval_define(), extcodeok(), external_turbomole(), xtb_qmdff::ff_ini(), xtb_type_anc::generate_anc_blowup(), xtb_type_anc::generate_anc_packed(), xtb_eeq::goedecker_chrgeq(), xtb_modelhessian::mh_eeq(), xtb_modef::modefollow(), peeq_tester(), xtb_mctc_systools::rdarg(), rdatomnumber(), rdfix(), rdtm(), xtb_mctc_systools::rdvar(), xtb_embedding::read_pcem(), xtb_scanparam::read_reference(), xtb_readin::readlog(), xtb_scan::relaxed_scan(), xtb_dtrafo::sao2cao(), xtb_screening::screen(), xtb_setmod::set_exttyp(), xtb_setmod::set_geopref(), xtb_setmod::set_runtyp(), xtb_sphereparam::set_sphere_radius::set_sphere_radius_aniso(), xtb_sphereparam::set_sphere_radius::set_sphere_radius_iso(), wrgbw(), xtb_setmod::write_set_constrain(), xtb_setmod::write_set_scan(), and xtb_prog_main::xtbmain().
terminate()
subroutine terminate (integer, intent(in) signal)
Definition at line 48 of file error.f90.
    use xtb_mctc_io, only : stderr
    use xtb_mctc_global, only : name
    integer,intent(in) :: signal
    integer,parameter  :: p_exit_success = 0
    integer,parameter  :: p_exit_failure = 1
    integer,parameter  :: p_exit_external = -1
    if (.not.allocated(name)) name = 'program'
    select case(signal)
    case(p_exit_success)
       write(stderr,'(  "normal termination of",1x,a)') name
       stop
    case(p_exit_external)
       write(stderr,'("external termination of",1x,a)') name
       error stop
    case default
       write(stderr,'("abnormal termination of",1x,a)') name
       error stop
    end select
References xtb_mctc_global::name.
Referenced by xtb_basis::dim_basis(), eval_define(), expire(), xtb_prog_thermo::parsearguments(), xtb_prog_main::parsearguments(), xtb_prog_topology::parsearguments(), peeq_tester(), xtb_type_environment::terminaterun(), test_atomlist(), test_axis(), test_class_molecule_axis_trafo(), test_class_molecule_mic_distances(), test_coulomb_gaussian_cluster(), test_coulomb_gaussian_pbc3d(), test_coulomb_gfn1_cluster(), test_coulomb_gfn1_pbc3d(), test_coulomb_gfn2_cluster(), test_coulomb_gfn2_pbc3d(), test_coulomb_point_cluster(), test_coulomb_point_pbc3d(), test_dftd3_pbc3d_latticepoints(), test_dftd3_pbc3d_neighbourlist(), test_dftd3_pbc3d_threebody_latp(), test_dftd3_pbc3d_threebody_neighs(), test_dftd4_pbc3d_latticepoints(), test_dftd4_pbc3d_neighbourlist(), test_dftd4_pbc3d_threebody_latp(), test_dftd4_pbc3d_threebody_neighs(), test_eeq_ewald(), test_eeq_model_gbsa(), test_eeq_model_hbond(), test_eeq_model_salt(), test_eeq_water(), test_geometry_reader_file_coord_caf2_3d(), test_geometry_reader_file_coord_camgco_3d(), test_geometry_reader_file_coord_general_0d(), test_geometry_reader_file_gen(), test_geometry_reader_file_pdb_4qxx(), test_geometry_reader_file_pdb_4qxx_noh(), test_geometry_reader_file_poscar_sio2_3d(), test_geometry_reader_file_sdf_benzen_hquery(), test_geometry_reader_file_sdf_h2o(), test_geometry_reader_file_sdf_h2o_flat(), test_geometry_reader_file_xmol_water_0d(), test_geometry_reader_molfile_benzen(), test_geometry_reader_molfile_benzen_flat(), test_gfn0_api(), test_gfn0_api_srb(), test_gfn0_mindless_basic(), test_gfn0_mindless_solvation(), test_gfn0_sp(), test_gfn1_api(), test_hessian::test_gfn1_hessian(), test_gfn1_mindless_basic(), test_gfn1_mindless_solvation(), test_gfn1_pbc3d(), test_gfn1_pcem_api(), test_gfn1_scc(), test_gfn1_xb(), test_gfn1gbsa_api(), test_gfn2_api(), test_gfn2_dmetal(), test_hessian::test_gfn2_hessian(), test_gfn2_mindless_basic(), test_gfn2_mindless_solvation(), test_gfn2_pcem_api(), test_gfn2_scc(), test_gfn2gbsa_api(), test_gfn2salt_api(), test_gfnff_gbsa(), test_gfnff_hb(), test_gfnff_mindless_basic(), test_gfnff_mindless_solvation(), test_gfnff_pdb(), test_gfnff_scaleup(), test_gfnff_sdf(), test_gfnff_sp(), test_ipea_indole(), test_latticepoint_pbc3d(), test_ncoord_pbc3d_latticepoints(), test_ncoord_pbc3d_neighbourlist(), test_pbc_lancopt(), test_pbc_tools_convert(), test_pbc_tools_cutoff(), test_peeq_api(), test_peeq_api_srb(), test_peeq_sp(), test_print_thermo(), test_repulsion_cluster(), test_repulsion_pbc3d(), test_symmetry_c20(), test_symmetry_li8(), test_symmetry_pcl3(), test_symmetry_water(), test_thermo_calc(), test_wigner_seitz_0d(), test_wigner_seitz_3d(), wsigint(), wsigterm(), xtb_prog_info::xtbinfo(), xtb_prog_main::xtbmain(), xtb_prog_thermo::xtbthermo(), and xtb_prog_topology::xtbtopology().
wsigint()
subroutine wsigint
Definition at line 69 of file error.f90.
    use xtb_mctc_io, only : stderr
    write(stderr,'("recieved SIGINT, terminating...")')
    call terminate(-1)
References terminate().
Referenced by mctc_init().
wsigterm()
subroutine wsigterm
Definition at line 75 of file error.f90.
    use xtb_mctc_io, only : stderr
    write(stderr,'("recieved SIGTERM, terminating...")')
    call terminate(-1)
References terminate().
Referenced by mctc_init().