My Project: src/extern/turbomole.f90 File Reference
turbomole.f90 File Reference
Functions/Subroutines
subroutine external_turbomole (n, at, xyz, nel, nopen, grd, eel, g, dip, lsolv)
subroutine wrtm (n, at, xyz)
subroutine rdtm (n, grd, e, g, xyz)
subroutine rijcheck (extcode)
subroutine extcodeok (extcode)
Function/Subroutine Documentation
extcodeok()
subroutine extcodeok (integer, intent(in) extcode)
Definition at line 199 of file turbomole.f90.
    implicit none
    integer, intent (in) :: extcode
    integer :: ich
    character(len=80) atmp
    ! TM
    if(extcode.le.3)then
       call execute_command_line('exec grep "actual step" control > TmPfIlE')
       open(newunit=ich,file='TmPfIlE',status='old')
       read(ich,'(a)',end=100)atmp
  100  close(ich,status='delete')
       if(index(atmp,'actual').ne.0) call raise('E','external code error: '//&
       &                                            trim(atmp))
    endif
    return
References raise().
Referenced by external_turbomole().
external_turbomole()
subroutine external_turbomole (integer n, integer, dimension(n) at, real(wp), dimension(3,n) xyz, integer nel, integer nopen, logical grd, real(wp) eel, real(wp), dimension (3,n) g, real(wp), dimension(3) dip, logical lsolv)
Definition at line 18 of file turbomole.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_setparam
    implicit none
    integer n, at(n), nel, nopen
    logical grd,lsolv
    real(wp) xyz(3,n)
    real(wp) xyz_cached(3,n)
    real(wp) g  (3,n)
    real(wp) eel
    real(wp) dip(3)
    character(len=255) atmp
    logical :: cache, exist
    cache = .false.
    dip=0
    ! TM (RI)
    if(extcode.eq.1)then
       !$omp critical (turbo_lock)
       inquire(file='gradient', exist=exist)
       if (exist .and. grd) then
          call rdtm(n,grd,eel,g,xyz_cached)
          cache = any(abs(xyz_cached - xyz) < 1.e-10_wp)
       end if
       if (.not.cache) then
          call wrtm(n,at,xyz)
          if(extmode.eq.1)then
             call execute_command_line('exec ridft  >  job.last 2>> /dev/null')
             if(grd)call execute_command_line('exec rdgrad >> job.last 2>> /dev/null')
          endif
          call extcodeok(extcode)
          call rdtm(n,grd,eel,g,xyz_cached)
       end if
       !$omp end critical (turbo_lock)
       return
    endif
    ! TM+d3+gcp
    if(extcode.eq.2)then
       !$omp critical (turbo_lock)
       inquire(file='gradient', exist=exist)
       if (exist .and. grd) then
          call rdtm(n,grd,eel,g,xyz_cached)
          cache = any(abs(xyz_cached - xyz) < 1.e-10_wp)
       end if
       if (.not.cache) then
          call wrtm(n,at,xyz)
          if(extmode.le.2)then
             call execute_command_line('exec ridft  >  job.last 2>> /dev/null')
             call execute_command_line('exec rdgrad >> job.last 2>> /dev/null')
             call execute_command_line('exec dftd3 coord -grad >> job.last 2>> /dev/null')
             call execute_command_line('exec gcp coord -file -grad >>job.last 2>>/dev/null')
          endif
          call extcodeok(extcode)
          call rdtm(n,.true.,eel,g,xyz_cached)
       end if
       !$omp end critical (turbo_lock)
       return
    endif
    ! TM (NORI)
    if(extcode.eq.3)then
       !$omp critical (turbo_lock)
       inquire(file='gradient', exist=exist)
       if (exist .and. grd) then
          call rdtm(n,grd,eel,g,xyz_cached)
          cache = any(abs(xyz_cached - xyz) < 1.e-10_wp)
       end if
       if (.not.cache) then
          call wrtm(n,at,xyz)
          if(extmode.eq.1)then
             call execute_command_line('exec dscf  > job.last 2>> /dev/null')
             if(grd)call execute_command_line('exec grad >> job.last 2>> /dev/null')
          endif
          call extcodeok(extcode)
          call rdtm(n,grd,eel,g,xyz_cached)
       end if
       !$omp end critical (turbo_lock)
       return
    endif
    call raise('E','This external code is not implemented')
References xtb_setparam::extcode, extcodeok(), xtb_setparam::extmode, raise(), rdtm(), true(), xtb_mctc_accuracy::wp, and wrtm().
Referenced by xtb_type_dummycalc::singlepoint().
rdtm()
subroutine rdtm (integer n, logical grd, real(wp) e, real(wp), dimension(3,n) g, real(wp), dimension(3,n) xyz)
Definition at line 131 of file turbomole.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    integer n, iunit, i, nl, j, nn
    logical grd
    real(wp) g(3,n), e, xx(10), x, y, z, xyz(3,n)
    logical ex
    character(len=128) a1
    iunit=33
    if(.not.grd)then
       open(newunit=iunit,file='energy')
       101   read(iunit,'(a)',end=102)a1
       call readl(a1,xx,nn)
       if(nn.ge.4) e=xx(2)
       goto 101
       102   close(iunit)
       return
    endif
    inquire(file='gradient',exist=ex)
    if(.not.ex) then
       call raise('E','no gradient file found!')
    endif
    j=0
    open(newunit=iunit,file='gradient')
 201 read(iunit,'(a)',end=301)a1
    j=j+1
    if(index(a1,'cycle').ne.0)nl=j
    goto 201
    301   continue
    if(nl.lt.2)then
       call raise('E','illegal gradient file!')
    endif
    rewind iunit
    do i=1,nl
       read(iunit,'(a)')a1
    enddo
    call readl(a1,xx,nn)
    e=xx(2)
    do i=1,n
       read(iunit,*)xyz(1,i),xyz(2,i),xyz(3,i)
    enddo
    do i=1,n
       read(iunit,*)g(1,i),g(2,i),g(3,i)
    enddo
    close(iunit)
References raise(), readl(), and xtb_mctc_accuracy::wp.
Referenced by external_turbomole().
rijcheck()
subroutine rijcheck (integer, intent(inout) extcode)
Definition at line 186 of file turbomole.f90.
    implicit none
    integer, intent (inout) :: extcode
    integer icheck,ich
    icheck=1
    call execute_command_line('exec sdg rij | wc -l > TmPfIlE')
    open(newunit=ich,file='TmPfIlE',status='old')
    read(ich,*)icheck
    close(ich,status='delete')
    if(icheck.lt.1) extcode=3
    return
wrtm()
subroutine wrtm (integer n, integer, dimension(n) at, real(wp), dimension(3,n) xyz)
Definition at line 110 of file turbomole.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_symbols, only : tosymbol
    implicit none
    integer n, at(n), iunit, i
    real(wp) xyz(3,n)
    iunit=33
    open(newunit=iunit,file='coord')
    write(iunit,'(a)')'$coord'
    do i=1,n
       write(iunit,'(3F24.14,6x,a2)') &
       &   xyz(1,i),xyz(2,i),xyz(3,i),tosymbol(at(i))
    enddo
    write(iunit,'(a)')'$end'
    close(iunit)
References xtb_mctc_symbols::tosymbol(), and xtb_mctc_accuracy::wp.
Referenced by external_turbomole().