My Project: src/filetools.F90 File Reference
filetools.F90 File Reference
Functions/Subroutines
subroutine print_filelist (iunit)
subroutine delete_file (name)
subroutine touch_file (name)
subroutine open_binary (iunit, name, status)
subroutine open_file (iunit, name, status)
subroutine close_file (unit)
subroutine remove_file (unit)
Function/Subroutine Documentation
close_file()
subroutine close_file (integer, intent(in) unit)
Definition at line 83 of file filetools.F90.
    use xtb_mctc_global, only : persistentenv
    implicit none
    integer,intent(in) :: unit
    logical :: opened
    call persistentenv%io%closeFile(unit)
References xtb_mctc_global::persistentenv.
Referenced by xtb_optimizer::ancopt(), xtb_biaspath::bias_path(), xtb_extern_orca::checkorca(), xtb_topology::checktopology(), xtb_setmod::close_set(), countfix(), xtb_cqpath::cqpath_read_pathfile(), xtb_cqpath::cqpath_read_pathfile_parameter(), xtb_cube::cube(), xtb_hessian::distort(), xtb_freq_io::g98fake(), g98fake(), xtb_freq_io::g98fake2(), xtb_geoopt::geometry_optimization(), xtb_gfnff_ini::gfnff_ini(), xtb_gfnff_setup::gfnff_input(), xtb_local::local(), xtb_propertyoutput::main_freq(), xtb_propertyoutput::main_property(), xtb_dynamic::md(), xtb_mdoptim::mdopt(), xtb_modef::modefollow(), xtb_main_setup::newgffcalculator(), xtb_main_setup::newxtbcalculator(), pocketscan(), printmold(), printumold(), rdatomnumber(), xtb_setmod::rdcontrol(), rdcoord(), rdfix(), xtb_freq_io::rdhess(), xtb_dynamic::rdmdrestart(), rdsdf(), rdxyz(), xtb_restart::read_restart_gff(), xtb_constrain_param::read_userdata(), xtb_readin::readlog(), xtb_restart::readrestart(), xtb_scan::relaxed_scan(), xtb_extern_mopac::runmopac(), xtb_extern_orca::runorca(), xtb_screening::screen(), xtb_xtb_calculator::singlepoint(), symmetry(), test_gfn0_sp(), test_peeq_sp(), xtb_dynamic::wrc(), xtb_freq_io::wrhess(), xtb_restart::write_restart_gff(), xtb_printout::writecosmofile(), xtb_freq_io::writehessianout(), xtb_restart::writerestart(), xtb_io_writer_turbomole::writeresultsturbomole(), xtb_modef::writeuu(), xtb_dynamic::wrmdrestart(), wrmodef(), xtb_prog_main::xtbmain(), and xtb_prog_topology::xtbtopology().
delete_file()
subroutine delete_file (character(len=*), intent(in) name)
Definition at line 28 of file filetools.F90.
    use xtb_mctc_global, only : persistentenv
    implicit none
    character(len=*),intent(in)  :: name
    call persistentenv%io%deleteFile(name)
References xtb_mctc_global::persistentenv.
Referenced by xtb_biaspath::bias_path(), xtb_geoopt::geometry_optimization(), xtb_dynamic::md(), xtb_modef::modefollow(), xtb_screening::screen(), test_gfnff_gbsa(), test_gfnff_hb(), test_gfnff_mindless_basic(), test_gfnff_mindless_solvation(), test_gfnff_pdb(), test_gfnff_scaleup(), test_gfnff_sdf(), test_gfnff_sp(), and xtb_prog_main::xtbmain().
open_binary()
subroutine open_binary (integer, intent(out) iunit, character(len=*), intent(in) name, character(len=1), intent(in) status)
Definition at line 47 of file filetools.F90.
    use xtb_mctc_global, only : persistentenv
    implicit none
    integer, intent(out) :: iunit
    character(len=*),intent(in)  :: name
    character(len=1),intent(in)  :: status
    select case(status)
    case default
       iunit = -1
    case('r','R')
       call persistentenv%io%readBinary(iunit, name)
    case('w','W')
       call persistentenv%io%writeBinary(iunit, name)
    end select
References xtb_mctc_global::persistentenv.
Referenced by xtb_optimizer::ancopt(), xtb_modef::modefollow(), xtb_restart::read_restart_gff(), xtb_restart::readrestart(), symmetry(), xtb_restart::write_restart_gff(), xtb_restart::writerestart(), xtb_modef::writeuu(), and wrmodef().
open_file()
subroutine open_file (integer, intent(out) iunit, character(len=*), intent(in) name, character(len=1), intent(in) status)
Definition at line 65 of file filetools.F90.
    use xtb_mctc_global, only : persistentenv
    implicit none
    character(len=*),intent(in)  :: name
    character(len=1),intent(in)  :: status
    integer,intent(out) :: iunit
    select case(status)
    case default
       iunit = -1
    case('r','R')
       call persistentenv%io%readFile(iunit, name)
    case('w','W')
       call persistentenv%io%writeFile(iunit, name)
    end select
References xtb_mctc_global::persistentenv.
Referenced by xtb_optimizer::ancopt(), xtb_biaspath::bias_path(), xtb_extern_orca::checkorca(), xtb_topology::checktopology(), countfix(), xtb_cqpath::cqpath_read_pathfile(), xtb_cqpath::cqpath_read_pathfile_parameter(), xtb_cube::cube(), xtb_hessian::distort(), xtb_freq_io::g98fake(), g98fake(), xtb_freq_io::g98fake2(), xtb_geoopt::geometry_optimization(), xtb_gfnff_ini::gfnff_ini(), xtb_gfnff_setup::gfnff_input(), xtb_local::local(), xtb_propertyoutput::main_freq(), xtb_propertyoutput::main_property(), xtb_dynamic::md(), xtb_mdoptim::mdopt(), xtb_modef::modefollow(), xtb_main_setup::newgffcalculator(), xtb_main_setup::newxtbcalculator(), xtb_setmod::open_set(), pocketscan(), printmold(), printumold(), xtb_screening::qmdfftoscreen(), rdatomnumber(), xtb_setmod::rdcontrol(), rdcoord(), rdfix(), xtb_freq_io::rdhess(), xtb_dynamic::rdmdrestart(), rdsdf(), rdxyz(), xtb_constrain_param::read_userdata(), xtb_readin::readlog(), xtb_solv_model::readparamfile(), xtb_scan::relaxed_scan(), xtb_extern_mopac::runmopac(), xtb_extern_orca::runorca(), xtb_screening::screen(), xtb_xtb_calculator::singlepoint(), test_gfn0_sp(), test_peeq_sp(), xtb_dynamic::wrc(), xtb_freq_io::wrhess(), xtb_printout::writecosmofile(), xtb_freq_io::writehessianout(), xtb_io_writer_turbomole::writeresultsturbomole(), xtb_dynamic::wrmdrestart(), wrmodef(), xtb_prog_main::xtbmain(), xtb_prog_topology::xtbtopology(), and zmatpr().
print_filelist()
subroutine print_filelist (integer, intent(in) iunit)
Definition at line 18 of file filetools.F90.
    use xtb_mctc_global, only : persistentenv
    use xtb_readin
    implicit none
    integer,intent(in) :: iunit
    call persistentenv%io%list(iunit)
References xtb_mctc_global::persistentenv.
Referenced by xtb_prog_main::xtbmain().
remove_file()
subroutine remove_file (integer, intent(in) unit)
Definition at line 93 of file filetools.F90.
    use xtb_mctc_global, only : persistentenv
    implicit none
    integer,intent(in) :: unit
    call persistentenv%io%closeFile(unit, remove=.true.)
References xtb_mctc_global::persistentenv, and true().
Referenced by xtb_screening::qmdfftoscreen(), and xtb_screening::screen().
touch_file()
subroutine touch_file (character(len=*), intent(in) name)
Definition at line 37 of file filetools.F90.
    use xtb_mctc_global, only : persistentenv
    use xtb_setparam
    implicit none
    character(len=*),intent(in)  :: name
    call persistentenv%io%touchFile(name)
References xtb_mctc_global::persistentenv.
Referenced by xtb_geoopt::geometry_optimization(), xtb_dynamic::md(), xtb_modef::modefollow(), xtb_scf::scf(), and xtb_prog_main::xtbmain().