My Project: src/fragment.f90 File Reference
fragment.f90 File Reference
Functions/Subroutines
subroutine mrec (molcount, xyz, cn, bond, nat, at, molvec)
recursive subroutine neighbours (i, xyz, cn, iat, taken, nat, bond, molvec, molcnt)
subroutine cutcov (n, at, xyz, cn, wb, bond)
Function/Subroutine Documentation
cutcov()
subroutine cutcov (integer n, integer, dimension(n) at, real(wp), dimension(3,n) xyz, real(wp), dimension(n) cn, real(wp), dimension(n,n) wb, real(wp), dimension(n,n) bond)
Definition at line 72 of file fragment.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    integer i,n,j,at(n),k,nb(20,n),iring,c(8,n),s(n)
    real(wp) bond(n,n)
    real(wp) wb(n,n),cn(n),xyz(3,n)
    logical samering
    bond = 0
    call neighborh(n,at,xyz,nb)
    do i=1,n
       call getring(n,nb,i,c(1,i),s(i))
    enddo
    do i=1,n
       do j=1,n
          if(wb(j,i).lt.0.5)  cycle
          if(wb(j,i).gt.1.3)               bond(j,i)=1
          if(cn(i).lt.1.2.or.cn(j).lt.1.2) bond(j,i)=1
          if(samering(n,i,j,c,s))          bond(j,i)=1
       enddo
    enddo
References getring(), neighborh(), and xtb_mctc_accuracy::wp.
Referenced by xtb_propertyoutput::main_freq().
mrec()
subroutine mrec (integer, intent(inout) molcount, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(in) cn, real(wp), dimension(nat,nat), intent(in) bond, integer, intent(in) nat, integer, dimension(nat), intent(in) at, integer, dimension(nat), intent(inout) molvec)
Definition at line 18 of file fragment.f90.
    ! molcount: number of total fragments (increased during search)
    ! xyz: overall Cart. coordinates
    ! nat: overall number of atoms
    ! at: atomic number array
    ! molvec: assignment vector of atom to fragment
    use xtb_mctc_accuracy, only : wp
    implicit none
    real(wp),intent(in)    :: xyz(3,nat),cn(nat)
    integer, intent(in)    :: nat,at(nat)
    integer, intent(inout) :: molvec(nat),molcount
    real(wp),intent(in)    :: bond(nat,nat)
    logical, allocatable   :: taken(:)
    integer :: i
    allocate( taken(nat) )
    molvec=0
    molcount=1
    taken=.false.
    do i=1,nat
       if(.not.taken(i)) then
          molvec(i)=molcount
          taken(i)=.true.
          call neighbours(i,xyz,cn,at,taken,nat,bond,molvec,molcount)
          molcount=molcount+1
       endif
    enddo
    molcount=molcount-1
References neighbours(), true(), and xtb_mctc_accuracy::wp.
Referenced by xtb_biaspath::bias_path(), xtb_propertyoutput::main_freq(), xtb_propertyoutput::print_wbo_fragment(), and xtb_splitparam::splitm().
neighbours()
recursive subroutine neighbours (integer i, real(wp), dimension(3,nat) xyz, real(wp), dimension(nat) cn, integer, dimension(nat) iat, logical, dimension(nat) taken, integer nat, real(wp), dimension(nat,nat) bond, integer, dimension(nat) molvec, integer molcnt)
Definition at line 48 of file fragment.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    real(wp) xyz(3,nat),cn(nat)
    real(wp)  bond(nat,nat)
    integer i,nat, molcnt,molvec(nat),j,iat(nat),icn,k
    logical taken(nat)
    icn=nint(cn(i))
    do k=1,icn
       j=maxloc(bond(:,i),1)
       bond(j,i)=0
       if (i .eq. j) cycle
       if (.not.taken(j)) then
          molvec(j)=molcnt
          taken(j)=.true.
          call neighbours(j,xyz,cn,iat,taken,nat,bond,molvec,molcnt)
       endif
    enddo
References true(), and xtb_mctc_accuracy::wp.
Referenced by mrec(), neighbours(), and shortest_distance().