My Project: src/gfnff/frag_hess.f90 File Reference
frag_hess.f90 File Reference
Data Types
interface xtb_gfnff_fraghess::shortest_distance
interface xtb_gfnff_fraghess::eigsort4
Modules
module xtb_gfnff_fraghess
Functions/Subroutines
subroutine xtb_gfnff_fraghess::fragmentize (nspin, at, xyz, maxsystem, maxmagnat, jab, neigh, ispinsyst, nspinsyst, nsystem)
subroutine xtb_gfnff_fraghess::frag_hess_diag (nat, hess, eig_calc, ispinsyst, nspinsyst, nsystem)
real(wp) function shortest_distance (nspin, start, goal, neighbours, input_distances, visited, precessor)
subroutine eigsort4 (lab, u, ew)
pure subroutine com (n, at, xyz, sum3)
Function/Subroutine Documentation
com()
pure subroutine com (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension(3), intent(out) sum3)
Definition at line 524 of file frag_hess.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    !Dummy
    integer, intent(in)   :: n
    integer, intent(in)   :: at(n)
    real(wp), intent(in)  :: xyz(3,n)
    real(wp), intent(out) :: sum3(3)
    !Stack
    integer               :: i
    real(wp)              :: sumw
    real(wp)              :: sumwx,sumwy,sumwz
    sumw=0
    sumwx=0.d0
    sumwy=0.d0
    sumwz=0.d0
    do i = 1, n
       sumw = sumw + 1
       sumwx = sumwx + xyz(1,i)
       sumwy = sumwy + xyz(2,i)
       sumwz = sumwz + xyz(3,i)
    end do
    sum3(1) = sumwx / sumw
    sum3(2) = sumwy / sumw
    sum3(3) = sumwz / sumw
References xtb_mctc_accuracy::wp.
Referenced by centerofmass(), xtb_gfnff_fraghess::fragmentize(), and rmrottr().
eigsort4()
subroutine eigsort4 (integer, intent(in) lab, real(sp), dimension(lab,lab), intent(inout) u, real(sp), dimension(lab), intent(inout) ew)
Definition at line 493 of file frag_hess.f90.
    use xtb_mctc_accuracy, only : wp, sp
    implicit none
    integer  :: ii,k, j, i
    real(sp) :: pp, hilf
    integer, intent(in)    :: lab
    real(sp), intent(inout) :: ew(lab)
    real(sp), intent(inout) :: u(lab,lab)
    do ii = 2, lab
       i = ii - 1
       k = i
       pp= ew(i)
       do j = ii, lab
          if (ew(j) .gt. pp) cycle
          k = j
          pp= ew(j)
       end do
       if (k .eq. i) cycle
       ew(k) = ew(i)
       ew(i) = pp
       do j=1,lab
          hilf=u(j,i)
          u(j,i)=u(j,k)
          u(j,k)=hilf
       end do
    end do
References xtb_mctc_accuracy::sp, and xtb_mctc_accuracy::wp.
shortest_distance()
real(wp) function shortest_distance (integer, intent(in) nspin, integer, intent(in) start, integer, intent(in) goal, integer, dimension(20, nspin), intent(in) neighbours, real(wp), dimension(nspin, nspin), intent(in) input_distances, logical, dimension(nspin), intent(out) visited, integer, dimension(nspin), intent(out) precessor)
Definition at line 426 of file frag_hess.f90.
    use xtb_mctc_accuracy, only : wp, sp
    implicit none
    !Dummy Arguments:
    real(wp)             :: shortest_distance
    integer, intent(in)  :: nspin
    integer, intent(in)  :: start
    integer, intent(in)  :: goal
    integer, intent(in)  :: neighbours(20, nspin)
    real(wp), intent(in) :: input_distances(nspin, nspin)
    logical, intent(out) :: visited(nspin)
    integer, intent(out) :: precessor(nspin)
    !Stack:
    integer  :: current
    integer  :: neighbour
    integer  :: i_neighbours
    integer  :: bonds
    real(wp) :: alt_dist
    real(wp) :: distance(nspin)
    !logical:: visited(nspin)
    bonds = 0
    precessor = 0
    distance = huge(distance)
    distance(start) = 0
    visited = .false.
    do while (.not.all(visited)) !as long there are unvisited nodes
       current = minloc(distance, 1,.not. visited)
       !Abort if Fragments are not connected:
       if (distance(current) == huge(distance)) then
          shortest_distance = huge(distance)
          return
       end if ! distance(current) == huge(distance)
       visited(current) = .true.
       if (current == goal) then
          shortest_distance = distance(goal)
          !route to target found
          do while (precessor(current) /= 0)
             bonds = bonds + 1
             current = precessor(current)
          end do ! End loop: while precessor(current) /= 0
          exit
       else
          !loop over all neighbours of current atom
          do i_neighbours = 1, neighbours(20, current)
             neighbour = neighbours(i_neighbours, current)
             if (.not.visited(neighbour)) then
                !distanzupdate
                alt_dist = distance(current) + input_distances(current, neighbour)
                !write( *, * ) alt_dist, distance(current),
                if ((alt_dist < distance(neighbour))) then
                   distance(neighbour) = alt_dist
                   precessor(neighbour) = current
                end if ! (alt_dist < distance(neighbour))
             endif !(visited(neighbour))
          end do ! End Loop over  i_neighbours from 1 to all_Atoms(current)%n_neighbours
       endif
    end do ! End loop: while sum(visited) /= 0
    !initialize
    shortest_distance = distance(goal)
References neighbours(), xtb_mctc_accuracy::sp, true(), and xtb_mctc_accuracy::wp.
Referenced by shortest_distance().