My Project: src/main/geometry.f90 File Reference
geometry.f90 File Reference
Functions/Subroutines
subroutine main_geometry (iunit, mol)
subroutine print_pbcsum (iunit, mol)
subroutine print_geosum (iunit, n, at, sym, xyz)
subroutine print_elem_dist (iunit, n, nbond, bond, dist, maxd, mind)
subroutine print_distances (iunit, n, at, sym, ndist, dist, id)
subroutine print_angles (iunit, n, at, sym, nbend, bend, ib)
subroutine print_torsions (iunit, n, at, sym, ntrsn, trsn, it)
subroutine calc_distances (n, at, xyz, bond, maxdist, ndist, dist, id, maxelem, nelem, ndel, distel, maxdel, mindel)
subroutine calc_angles (n, at, xyz, bond, maxbend, nbend, bend, ib)
subroutine calc_torsions (n, at, xyz, bond, maxtrsn, ntrsn, trsn, it)
subroutine get_bonds (n, at, xyz, bond)
subroutine print_moments (iunit, n, atmass, xyz)
pure real(wp) function, dimension(3) moments_of_inertia (n, atmass, xyz)
pure real(wp) function, dimension(3) center_of_mass (n, atmass, xyz)
pure real(wp) function molecular_mass (n, atmass)
subroutine check_cold_fusion (env, mol, cold_fusion)
Function/Subroutine Documentation
calc_angles()
subroutine calc_angles (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, integer, dimension(n,n), intent(in) bond, integer, intent(in) maxbend, integer, intent(out) nbend, real(wp), dimension(maxbend), intent(out) bend, integer, dimension(3,maxbend), intent(out) ib)
Definition at line 419 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    real(wp),intent(in)  :: xyz(3,n)
    integer, intent(in)  :: bond(n,n)
    integer, intent(in)  :: maxbend
    integer, intent(out) :: nbend
    real(wp),intent(out) :: bend(maxbend)
    integer, intent(out) :: ib(3,maxbend)
    integer  :: i,j,k,m
    real(wp) :: phi
    nbend = 0
    ib = 0
    bend = 0.0_wp
    m = 0
    get_bend: do i = 1, n
       if (bond(i,i).lt.2) cycle
       do j = 1, i-1
          if (i.eq.j) cycle
          if (bond(i,i).lt.2) cycle
          if (bond(j,i).lt.1) cycle
          do k = 1, j-1
             if (i.eq.k .or. j.eq.k) cycle
             if (bond(k,j).lt.1) cycle
             call bangl(xyz,k,j,i,phi)
             if (m.ge.maxbend) exit get_bend
             m = m+1
             ib(1,m) = k
             ib(2,m) = j
             ib(3,m) = i
             bend(m) = phi
          enddo
       enddo
    enddo get_bend
    nbend = m
References bangl(), and xtb_mctc_accuracy::wp.
Referenced by print_geosum().
calc_distances()
subroutine calc_distances (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, integer, dimension(n,n), intent(in) bond, integer, intent(in) maxdist, integer, intent(out) ndist, real(wp), dimension(maxdist), intent(out) dist, integer, dimension(2,maxdist), intent(out) id, integer, intent(in) maxelem, integer, intent(out) nelem, integer, dimension(maxelem,maxelem), intent(out) ndel, real(wp), dimension(maxelem,maxelem), intent(out) distel, real(wp), dimension(maxelem,maxelem), intent(out) maxdel, real(wp), dimension(maxelem,maxelem), intent(out) mindel)
Definition at line 344 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    real(wp),intent(in)  :: xyz(3,n)
    integer, intent(in)  :: bond(n,n)
    integer, intent(in)  :: maxdist
    integer, intent(out) :: ndist
    real(wp),intent(out) :: dist(maxdist)
    integer, intent(out) :: id(2,maxdist)
    integer, intent(in)  :: maxelem
    integer, intent(out) :: nelem
    integer, intent(out) :: ndel(maxelem,maxelem)
    real(wp),intent(out) :: distel(maxelem,maxelem)
    real(wp),intent(out) :: maxdel(maxelem,maxelem)
    real(wp),intent(out) :: mindel(maxelem,maxelem)
    integer  :: i,j,m
    integer  :: iat,jat
    real(wp) :: r
    ndist = 0
    nelem = 0
    id = 0
    dist = 0.0_wp
    ndel = 0
    distel = 0.0_wp
    maxdel = -1.0e42_wp
    mindel = +1.0e42_wp
    m = 0
    get_dist: do i = 1, n
       iat = at(i)
       do j = 1, i-1
          jat = at(j)
          r  = sqrt(sum((xyz(:,i)-xyz(:,j))**2))
          if (bond(j,i).gt.0) then
             m = m+1
             if (m.ge.maxdist) exit get_dist
             ndel(iat,jat) = ndel(iat,jat)+1
             maxdel(iat,jat) = max(maxdel(iat,jat),r)
             mindel(iat,jat) = min(mindel(iat,jat),r)
             distel(iat,jat) = distel(iat,jat)+r
             id(1,m) = j
             id(2,m) = i
             dist(m) = r
          endif
       enddo
    enddo get_dist
    ndist = m
    m = 0
    do iat = 1, maxelem
       do jat = 1, iat
          if (iat.ne.jat) then
             ndel(jat,iat) = ndel(jat,iat)+ndel(iat,jat)
             ndel(iat,jat) = ndel(jat,iat)
          endif
          if (ndel(jat,iat).lt.1) cycle
          m = m+1
          distel(jat,iat) = (distel(iat,jat)+distel(jat,iat)) &
             /real(ndel(jat,iat),wp)
          if (iat.eq.jat) distel(jat,iat) = distel(jat,iat)*0.5_wp
          distel(iat,jat) = distel(jat,iat)
          maxdel(jat,iat) = max(maxdel(iat,jat),maxdel(jat,iat))
          maxdel(iat,jat) = maxdel(jat,iat)
          mindel(jat,iat) = min(mindel(iat,jat),mindel(jat,iat))
          mindel(iat,jat) = mindel(jat,iat)
       enddo
    enddo
    nelem = m
References xtb_mctc_accuracy::wp.
Referenced by print_geosum().
calc_torsions()
subroutine calc_torsions (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, integer, dimension(n,n), intent(in) bond, integer, intent(in) maxtrsn, integer, intent(out) ntrsn, real(wp), dimension(maxtrsn), intent(out) trsn, integer, dimension(4,maxtrsn), intent(out) it)
Definition at line 462 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    real(wp),intent(in)  :: xyz(3,n)
    integer, intent(in)  :: bond(n,n)
    integer, intent(in)  :: maxtrsn
    integer, intent(out) :: ntrsn
    real(wp),intent(out) :: trsn(maxtrsn)
    integer, intent(out) :: it(4,maxtrsn)
    integer  :: i,j,k,l,m
    real(wp) :: phi
    real(wp),external :: valijkl
    m = 0
    get_trsn: do i = 1, n
       if (bond(i,i).lt.2) cycle
       do j = 1, n
          if (i.eq.j) cycle
          if (bond(j,i).lt.1 .or. bond(j,j).lt.2) cycle
          do k = 1, n
             if (i.eq.k .or. j.eq.k) cycle
             if (bond(k,j).lt.1 .or. bond(k,k).lt.2) cycle
             do l = 1, n
                if (bond(l,k).lt.1) cycle
                if (i.eq.l .or. j.eq.l .or. k.eq.l) cycle
                phi = valijkl(n,xyz,l,k,j,i)
                if (m.ge.maxtrsn) exit get_trsn
                m = m+1
                it(1,m) = l
                it(2,m) = k
                it(3,m) = j
                it(4,m) = i
                trsn(m) = phi
             enddo
          enddo
       enddo
    enddo get_trsn
    ntrsn = m
References valijkl(), and xtb_mctc_accuracy::wp.
Referenced by print_geosum().
center_of_mass()
pure real(wp) function, dimension(3) print_moments::center_of_mass (integer, intent(in) n, real(wp), dimension(n), intent(in) atmass, real(wp), dimension(3,n), intent(in) xyz)
Definition at line 599 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: atmass(n)
    real(wp),intent(in)  :: xyz(3,n)
    real(wp) :: center(3)
    integer  :: idir
    center = 0.0_wp
    do idir = 1, 3
       center(idir) = sum(atmass*xyz(idir,:))
    enddo
    center = center/sum(atmass)
Referenced by moments_of_inertia(), and print_moments().
check_cold_fusion()
subroutine check_cold_fusion (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, logical, intent(out) cold_fusion)
Definition at line 627 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_type_environment
    use xtb_type_molecule
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    logical, intent(out) :: cold_fusion
    integer :: iat, jat
    character(len=10) :: a10
    character(len=20) :: a20
    cold_fusion = .false.
    do iat = 1, len(mol)
       do jat = 1, iat-1
          if (mol%dist(jat, iat) < 1.0e-9_wp) then
             cold_fusion = .true.
             write(a20, '(a,i0,"-",a,i0)') &
                &  trim(mol%sym(jat)), jat, trim(mol%sym(iat)), iat
             write(a10, '(es10.3)') mol%dist(jat, iat)
             call env%error("Found *very* short distance of "//a10//" for "//&
                &           trim(a20))
          endif
       enddo
    enddo
References true(), and xtb_mctc_accuracy::wp.
Referenced by xtb_prog_info::xtbinfo(), and xtb_prog_main::xtbmain().
get_bonds()
subroutine get_bonds (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, integer, dimension(n,n), intent(out) bond)
Definition at line 506 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_param, only: rad => covalent_radius_2009
    implicit none
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    real(wp),intent(in)  :: xyz(3,n)
    integer, intent(out) :: bond(n,n)
    integer  :: i,j,k
    real(wp) :: r,f,r0
    bond = 0
    do i = 1, n
       f = 1.3_wp
       k = 0
       do while(k.eq.0 .and. f.lt.1.5_wp)
          do j = 1, i-1
             r = sqrt(sum((xyz(:,j)-xyz(:,i))**2))
             r0 = rad(at(i))+rad(at(j))
             if (r.lt.f*r0) then
                k = k+1
                bond(j,i) = 1
                bond(i,j) = 1
             endif
          enddo
          f = f*1.1_wp
       enddo
       bond(i,i) = k
    enddo
References xtb_mctc_accuracy::wp.
Referenced by xtb_scanparam::constrain_all_angles(), and xtb_scanparam::constrain_all_torsions().
main_geometry()
subroutine main_geometry (integer, intent(in) iunit, type(tmolecule), intent(in) mol)
Definition at line 18 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_type_molecule
    implicit none
    integer, intent(in)  :: iunit
    type(TMolecule), intent(in) :: mol
    if (mol%npbc == 0) then
       call print_geosum(iunit,mol%n,mol%at,mol%sym,mol%xyz)
    else
       call print_pbcsum(iunit,mol)
    endif
References print_geosum(), print_pbcsum(), and xtb_mctc_accuracy::wp.
Referenced by xtb_prog_info::xtbinfo(), and xtb_prog_main::xtbmain().
molecular_mass()
pure real(wp) function print_moments::molecular_mass (integer, intent(in) n, real(wp), dimension(n), intent(in) atmass)
Definition at line 614 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_convert
    implicit none
    integer, intent(in) :: n
    real(wp),intent(in) :: atmass(n)
    real(wp) :: molmass
    molmass = sum(atmass)*amutoau
References xtb_mctc_convert::amutoau.
Referenced by print_moments().
moments_of_inertia()
pure real(wp) function, dimension(3) print_moments::moments_of_inertia (integer, intent(in) n, real(wp), dimension(n), intent(in) atmass, real(wp), dimension(3,n), intent(in) xyz)
Definition at line 564 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_lapack, only : lapack_spev
    use xtb_mctc_convert
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: atmass(n)
    real(wp),intent(in)  :: xyz(3,n)
    real(wp) :: moments(3)
    real(wp) :: center(3),mass,t(6),work(9),tmp(3,3)
    real(wp) :: x,x2,y,y2,z,z2
    integer  :: iat,info
    center = center_of_mass(n,atmass,xyz)
    t = 0.0_wp
    do iat = 1, n
       mass = atmass(iat)*amutoau
       x = xyz(1,iat)-center(1); x2 = x**2
       y = xyz(2,iat)-center(2); y2 = y**2
       z = xyz(3,iat)-center(3); z2 = z**2
       t(1) = t(1) + mass * (y2+z2)
       t(2) = t(2) - mass * x*y
       t(3) = t(3) + mass * (x2+z2)
       t(4) = t(4) - mass * x*z
       t(5) = t(5) - mass * y*z
       t(6) = t(6) + mass * (x2+y2)
    enddo
    call lapack_spev('N','U',3,t,moments,tmp,3,work,info)
    if (info.ne.0) moments = -1.0_wp
References xtb_mctc_convert::amutoau, and center_of_mass().
Referenced by print_moments().
print_angles()
subroutine print_angles (integer, intent(in) iunit, integer, intent(in) n, integer, dimension(n), intent(in) at, character(len=*), dimension(n), intent(in) sym, integer, intent(in) nbend, real(wp), dimension(nbend), intent(in) bend, integer, dimension(3,nbend), intent(in) ib)
Definition at line 276 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_constants
    use xtb_mctc_symbols, only : tosymbol
    implicit none
    integer, intent(in)  :: iunit
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    character(len=*), intent(in) :: sym(n)
    integer, intent(in)  :: nbend
    real(wp),intent(in)  :: bend(nbend)
    integer, intent(in)  :: ib(3,nbend)
    integer :: i,j,k,m
    integer :: imax,imin
    write(iunit,'(1x,"*",1x,i0,1x,a)') nbend,"selected angles"
    write(iunit,'(a)')
    write(iunit,'(3(5x,"#",3x,"Z",5x),13x,10x,"value/")')
    do m = 1, nbend
       i = ib(1,m)
       j = ib(2,m)
       k = ib(3,m)
       write(iunit,'(3(i6,1x,i3,1x,a4),13x,1x,f14.7)') &
          i,at(i),sym(i), &
          j,at(j),sym(j), &
          k,at(k),sym(k), &
          bend(m)*180.0_wp/pi
    enddo
    write(iunit,'(a)')
References xtb_mctc_constants::pi, xtb_mctc_symbols::tosymbol(), and xtb_mctc_accuracy::wp.
Referenced by print_geosum().
print_distances()
subroutine print_distances (integer, intent(in) iunit, integer, intent(in) n, integer, dimension(n), intent(in) at, character(len=*), dimension(n), intent(in) sym, integer, intent(in) ndist, real(wp), dimension(ndist), intent(in) dist, integer, dimension(2,ndist), intent(in) id)
Definition at line 236 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_convert
    use xtb_mctc_symbols, only : tosymbol
    implicit none
    integer, intent(in)  :: iunit
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    character(len=*), intent(in) :: sym(n)
    integer, intent(in)  :: ndist
    real(wp),intent(in)  :: dist(ndist)
    integer, intent(in)  :: id(2,ndist)
    integer :: i,j,m
    integer :: imax,imin
    write(iunit,'(1x,"*",1x,i0,1x,a)') ndist,"selected distances"
    write(iunit,'(a)')
    write(iunit,'(2(5x,"#",3x,"Z",5x),30x,8x,"value/")')
    imax = maxloc(dist,1)
    imin = minloc(dist,1)
    do m = 1, ndist
       i = id(1,m)
       j = id(2,m)
       write(iunit,'(2(i6,1x,i3,1x,a4),30x,1x,f14.7)',advance='no') &
          i,at(i),sym(i), &
          j,at(j),sym(j), &
          dist(m)*autoaa
       if (imax.eq.m) then
          write(iunit,'(1x,"(max)")')
       elseif (imin.eq.m) then
          write(iunit,'(1x,"(min)")')
       else
          write(iunit,'(a)')
       endif
    enddo
    write(iunit,'(a)')
References xtb_mctc_convert::autoaa, xtb_mctc_symbols::tosymbol(), and xtb_mctc_accuracy::wp.
Referenced by print_geosum().
print_elem_dist()
subroutine print_elem_dist (integer, intent(in) iunit, integer, intent(in) n, integer, intent(in) nbond, integer, dimension(n,n), intent(in) bond, real(wp), dimension(n,n), intent(in) dist, real(wp), dimension(n,n), intent(in) maxd, real(wp), dimension(n,n), intent(in) mind)
Definition at line 206 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_convert
    use xtb_mctc_symbols, only : tosymbol
    implicit none
    integer, intent(in)  :: iunit
    integer, intent(in)  :: n
    integer, intent(in)  :: nbond
    integer, intent(in)  :: bond(n,n)
    real(wp),intent(in)  :: dist(n,n)
    real(wp),intent(in)  :: maxd(n,n)
    real(wp),intent(in)  :: mind(n,n)
    integer :: iat,jat
    write(iunit,'(1x,"*",1x,i0,1x,a)') nbond,"distinct bonds (by element types)"
    write(iunit,'(a)')
    write(iunit,'(2(3x,"Z",3x),10x,"#",3x,"av. dist./",8x,"max./",8x,"min./")')
    do iat = 1, n
       do jat = 1, iat
          if (bond(jat,iat).lt.1) cycle
          write(iunit,'(2(1x,i3,1x,a2),i11,3f14.7)') &
             jat,tosymbol(jat),iat,tosymbol(iat),bond(jat,iat),dist(jat,iat)*autoaa, &
             maxd(jat,iat)*autoaa,mind(jat,iat)*autoaa
       enddo
    enddo
    write(iunit,'(a)')
References xtb_mctc_convert::autoaa, xtb_mctc_symbols::tosymbol(), and xtb_mctc_accuracy::wp.
Referenced by print_geosum().
print_geosum()
subroutine print_geosum (integer, intent(in) iunit, integer, intent(in) n, integer, dimension(n), intent(in) at, character(len=*), dimension(n), intent(in) sym, real(wp), dimension(3,n), intent(in) xyz)
Definition at line 116 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_constants
    use xtb_mctc_convert
    use xtb_setparam
    use xtb_splitparam
    use xtb_disp_ncoord
    use xtb_approxrab
    implicit none
    integer, intent(in)  :: iunit
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    character(len=*), intent(in) :: sym(n)
    real(wp),intent(in)  :: xyz(3,n)
    integer  :: i,j,k,l,m
    integer  :: iat,jat
    integer  :: imax,imin
    integer  :: maxdist,maxbend,maxtrsn,maxelem
    integer  :: ndist,nbend,ntrsn,nelem
    integer, allocatable :: bond(:,:)
    integer, allocatable :: id(:,:)
    real(wp),allocatable :: dist(:)
    integer, allocatable :: ndel(:,:)
    real(wp),allocatable :: distel(:,:)
    real(wp),allocatable :: maxdel(:,:)
    real(wp),allocatable :: mindel(:,:)
    integer, allocatable :: ib(:,:)
    real(wp),allocatable :: bend(:)
    integer, allocatable :: it(:,:)
    real(wp),allocatable :: trsn(:)
    real(wp),allocatable :: cn(:)
    real(wp) :: moments(3)
    maxdist = n*(n-1)/2
    maxbend = n*(n-1)*(n-2)/6
    maxtrsn = n*(n-1)*(n-2)*(n-3)/24
    maxelem = min(maxval(at),118)
    allocate( cn(n), source = 0.0_wp )
    allocate( bond(n,n), source = 0 )
    call ncoord_erf(n,at,xyz,cn,900.0_wp)
    call approx_bonds(n,at,xyz,cn,bond,0.0537_wp)
    !call get_bonds(n,at,xyz,bond)
    if (pr_moments.or.pr_distances.or.pr_angles.or.pr_torsions) then
       call generic_header(iunit,"Geometry Summary",49,10)
       write(iunit,'(a)')
    endif
    if (pr_moments) then
       call print_moments(iunit,n,atmass,xyz)
    endif
    if (pr_distances) then
       allocate( dist(maxdist),distel(maxelem,maxelem), &
          maxdel(maxelem,maxelem),mindel(maxelem,maxelem), source = 0.0_wp )
       allocate( id(2,maxdist),ndel(maxelem,maxelem), source = 0 )
       call calc_distances(n,at,xyz,bond,maxdist,ndist,dist,id, &
          maxelem,nelem,ndel,distel,maxdel,mindel)
       if (ndist.gt.0) then
          call print_distances(iunit,n,at,sym,ndist,dist,id)
          call print_elem_dist(iunit,maxelem,nelem,ndel,distel,maxdel,mindel)
       endif
       deallocate( dist,distel,maxdel,mindel,id,ndel)
    endif
    if (pr_angles) then
       allocate( bend(maxbend), source = 0.0_wp )
       allocate( ib(3,maxbend), source = 0 )
       call calc_angles(n,at,xyz,bond,maxbend,nbend,bend,ib)
       if (nbend.gt.0) then
          call print_angles(iunit,n,at,sym,nbend,bend,ib)
       endif
       deallocate( bend,ib )
    endif
    if (pr_torsions) then
       allocate( trsn(maxtrsn), source = 0.0_wp )
       allocate( it(4,maxtrsn), source = 0 )
       call calc_torsions(n,at,xyz,bond,maxtrsn,ntrsn,trsn,it)
       if (ntrsn.gt.0) then
          call print_torsions(iunit,n,at,sym,ntrsn,trsn,it)
       endif
       deallocate( trsn,it )
    endif
References xtb_approxrab::approx_bonds(), xtb_splitparam::atmass, calc_angles(), calc_distances(), calc_torsions(), generic_header(), xtb_disp_ncoord::ncoord_erf(), xtb_setparam::pr_angles, xtb_setparam::pr_distances, xtb_setparam::pr_moments, xtb_setparam::pr_torsions, print_angles(), print_distances(), print_elem_dist(), print_moments(), print_torsions(), and xtb_mctc_accuracy::wp.
Referenced by main_geometry().
print_moments()
subroutine print_moments (integer, intent(in) iunit, integer, intent(in) n, real(wp), dimension(n), intent(in) atmass, real(wp), dimension(3,n), intent(in) xyz)
Definition at line 540 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_convert
    implicit none
    integer, intent(in)  :: iunit
    integer, intent(in)  :: n
    real(wp),intent(in)  :: atmass(n)
    real(wp),intent(in)  :: xyz(3,n)
    real(wp) :: molmass
    real(wp) :: cma(3)
    real(wp) :: moments(3)
    molmass = molecular_mass(n,atmass)
    cma = center_of_mass(n,atmass,xyz)
    moments = moments_of_inertia(n,atmass,xyz)
    write(iunit,'(a," : ", f16.7)') "      molecular mass/u   ", molmass*autoamu
    write(iunit,'(a," : ",3f16.7)') "   center of mass at/   ", cma*autoaa
    write(iunit,'(a," : ",4x,3e16.7)') "  moments of inertia/u", moments*autoaa**2*autoamu
    write(iunit,'(a," : ",4x,3e16.7)') "rotational constants/cm", 0.5_wp*autorcm/moments
    write(iunit,'(a)')
 contains
 pure function moments_of_inertia(n,atmass,xyz) result(moments)
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_lapack, only : lapack_spev
    use xtb_mctc_convert
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: atmass(n)
    real(wp),intent(in)  :: xyz(3,n)
    real(wp) :: moments(3)
    real(wp) :: center(3),mass,t(6),work(9),tmp(3,3)
    real(wp) :: x,x2,y,y2,z,z2
    integer  :: iat,info
    center = center_of_mass(n,atmass,xyz)
    t = 0.0_wp
    do iat = 1, n
       mass = atmass(iat)*amutoau
       x = xyz(1,iat)-center(1); x2 = x**2
       y = xyz(2,iat)-center(2); y2 = y**2
       z = xyz(3,iat)-center(3); z2 = z**2
       t(1) = t(1) + mass * (y2+z2)
       t(2) = t(2) - mass * x*y
       t(3) = t(3) + mass * (x2+z2)
       t(4) = t(4) - mass * x*z
       t(5) = t(5) - mass * y*z
       t(6) = t(6) + mass * (x2+y2)
    enddo
    call lapack_spev('N','U',3,t,moments,tmp,3,work,info)
    if (info.ne.0) moments = -1.0_wp
 end function moments_of_inertia
 pure function center_of_mass(n,atmass,xyz) result(center)
    use xtb_mctc_accuracy, only : wp
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: atmass(n)
    real(wp),intent(in)  :: xyz(3,n)
    real(wp) :: center(3)
    integer  :: idir
    center = 0.0_wp
    do idir = 1, 3
       center(idir) = sum(atmass*xyz(idir,:))
    enddo
    center = center/sum(atmass)
 end function center_of_mass
 pure function molecular_mass(n,atmass) result(molmass)
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_convert
    implicit none
    integer, intent(in) :: n
    real(wp),intent(in) :: atmass(n)
    real(wp) :: molmass
    molmass = sum(atmass)*amutoau
 end function molecular_mass
References xtb_mctc_convert::autoaa, xtb_mctc_convert::autoamu, xtb_mctc_convert::autorcm, center_of_mass(), molecular_mass(), moments_of_inertia(), and xtb_mctc_accuracy::wp.
Referenced by print_geosum().
print_pbcsum()
subroutine print_pbcsum (integer, intent(in) iunit, type(tmolecule), intent(in) mol)
Definition at line 33 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_constants
    use xtb_mctc_convert
    use xtb_type_molecule
    implicit none
    integer, intent(in)  :: iunit
    type(TMolecule),intent(in) :: mol
    integer  :: i
    real(wp) :: conv
    conv = autoaa
    call generic_header(iunit,"Geometry Summary",49,10)
    write(iunit,'(a)')
    ! atomic coordinates
    write(iunit,'(1x,"*",1x,i0,1x,a)') mol%n,"atoms in unit cell"
    write(iunit,'(a)')
    write(iunit,'(5x,"#",3x,"Z",5x,32x,"position/",8x,"charge")')
    do i = 1, mol%n
       write(iunit,'(i6,1x,i3,1x,a4)',advance='no') i,mol%at(i),mol%sym(i)
       write(iunit,'(3f14.7)',advance='no') mol%xyz(:,i)*conv
       write(iunit,'(f14.7)') mol%z(i)
    enddo
    write(iunit,'(a)')
    ! periodicity
    write(iunit,'(1x,"*",1x,i0,a)') mol%npbc,"D periodic system"
    write(iunit,'(a)')
    if (mol%npbc > 0) then
       ! cell parameters
       write(iunit,'(1x,"*",1x,a)') "cell parameter"
       write(iunit,'(a)')
       write(iunit,'(a12,2a15,2x,3a11)') &
          "|a|/", "|b|/", "|c|/", "/", "/", "/"
       write(iunit,'(f13.7,2f14.7,1x,3f9.3)') &
          mol%cellpar(:3)*conv,mol%cellpar(4:)*180.0_wp/pi
       write(iunit,'(a)')
       ! direct lattice (transformation abc -> xyz)
       write(iunit,'(1x,"*",1x,a)') "direct lattice/"
       write(iunit,'(a)')
       write(iunit,'(12x,a,3f14.7)') "a",mol%lattice(:,1)*conv
       write(iunit,'(12x,a,3f14.7)') "b",mol%lattice(:,2)*conv
       write(iunit,'(12x,a,3f14.7)') "c",mol%lattice(:,3)*conv
       write(iunit,'(a)')
       ! reciprocal lattice
       write(iunit,'(1x,"*",1x,a)') "reciprocal lattice/"
       write(iunit,'(a)')
       write(iunit,'(11x,a,3f14.7)') "a*",mol%rec_lat(:,1)/conv
       write(iunit,'(11x,a,3f14.7)') "b*",mol%rec_lat(:,2)/conv
       write(iunit,'(11x,a,3f14.7)') "c*",mol%rec_lat(:,3)/conv
       write(iunit,'(a)')
       ! geometry in fractional coordinates
       write(iunit,'(1x,"*",1x,a)') "geometry in fractional coordinates"
       write(iunit,'(a)')
       write(iunit,'(5x,"#",3x,"Z",5x,20x,"fractional coordinates")')
       do i = 1, mol%n
          write(iunit,'(i6,1x,i3,1x,a4)',advance='no') i,mol%at(i),mol%sym(i)
          write(iunit,'(3f14.7)',advance='no') mol%abc(:,i)
          write(iunit,'(a)')
       enddo
       write(iunit,'(a)')
       ! volume of unit cell
       write(iunit,'(1x,"*",1x,a,1x,"=",f14.7)') "volume of direct unit cell/", &
          mol%volume*conv**3
       write(iunit,'(a)')
       ! mass density of unit cell
       write(iunit,'(1x,"*",1x,a,1x,"=",f14.7)') "mass density of direct unit cell/gcm", &
          sum(mol%atmass)*metokg*1.0e27_wp/(mol%volume*conv**3)
       write(iunit,'(a)')
    endif
References xtb_mctc_convert::autoaa, generic_header(), xtb_mctc_convert::metokg, xtb_mctc_constants::pi, and xtb_mctc_accuracy::wp.
Referenced by main_geometry(), and test_peeq_sp().
print_torsions()
subroutine print_torsions (integer, intent(in) iunit, integer, intent(in) n, integer, dimension(n), intent(in) at, character(len=*), dimension(n), intent(in) sym, integer, intent(in) ntrsn, real(wp), dimension(ntrsn), intent(in) trsn, integer, dimension(4,ntrsn), intent(in) it)
Definition at line 309 of file geometry.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_constants
    use xtb_mctc_symbols, only : tosymbol
    implicit none
    integer, intent(in)  :: iunit
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    character(len=*), intent(in) :: sym(n)
    integer, intent(in)  :: ntrsn
    real(wp),intent(in)  :: trsn(ntrsn)
    integer, intent(in)  :: it(4,ntrsn)
    integer :: i,j,k,l,m
    integer :: imax,imin
    write(iunit,'(1x,"*",1x,i0,1x,a)') ntrsn, "selected dihedral angles"
    write(iunit,'(a)')
    write(iunit,'(4(5x,"#",3x,"Z",5x),8x,"value/")')
    do m = 1, ntrsn
       i = it(1,m)
       j = it(2,m)
       k = it(3,m)
       l = it(4,m)
       write(iunit,'(4(i6,1x,i3,1x,a4),1x,f14.7)') &
          i,at(i),sym(i), &
          j,at(j),sym(j), &
          k,at(k),sym(k), &
          l,at(l),sym(l), &
          trsn(m)*180.0_wp/pi
    enddo
    write(iunit,'(a)')
References xtb_mctc_constants::pi, xtb_mctc_symbols::tosymbol(), and xtb_mctc_accuracy::wp.
Referenced by print_geosum().