My Project: TESTSUITE/gfnff.f90 File Reference
gfnff.f90 File Reference
Functions/Subroutines
subroutine test_gfnff_sp
subroutine test_gfnff_hb
subroutine test_gfnff_gbsa
subroutine test_gfnff_mindless_basic
subroutine test_gfnff_mindless_solvation
subroutine test_gfnff_scaleup
subroutine test_gfnff_pdb
subroutine test_gfnff_sdf
Function/Subroutine Documentation
test_gfnff_gbsa()
subroutine test_gfnff_gbsa
Definition at line 170 of file gfnff.f90.
    use xtb_mctc_accuracy, only : wp
    use assertion
    use xtb_mctc_systools
    use xtb_solv_input
    use xtb_type_environment
    use xtb_type_options
    use xtb_type_molecule
    use xtb_type_restart
    use xtb_type_data
    use xtb_gfnff_param
    use xtb_gfnff_setup
    use xtb_gfnff_eg
    use xtb_gfnff_ini
    use xtb_setparam
    use xtb_setmod
    use xtb_disp_dftd3param
    use xtb_disp_dftd4
    use xtb_gfnff_calculator, only : tgffcalculator
    use xtb_main_setup, only : newgffcalculator, addsolvationmodel
    implicit none
    real(wp),parameter :: thr = 1.0e-10_wp
    integer, parameter :: nat = 7
    integer, parameter :: at(nat) = [6,8,1,1,8,1,1]
    real(wp),parameter :: xyz(3,nat) = reshape(&
       &[-5.78520874132429_wp,-1.92328475821000_wp,-0.02944611115854_wp, &
       & -5.57801768832583_wp, 0.17912532844037_wp, 0.72444143178660_wp, &
       & -4.27822256938673_wp,-2.74845397256109_wp,-1.13038073598642_wp, &
       & -7.47879539136783_wp,-2.97570121473211_wp, 0.39488815557786_wp, &
       & -0.83005338399036_wp, 2.43458470560665_wp,-0.78566331969245_wp, &
       & -0.74201439536855_wp, 4.04199055249898_wp, 0.09144422329636_wp, &
       & -2.44679415487233_wp, 1.69392751177087_wp,-0.27417668699116_wp],&
       & shape(xyz))
    type(scc_options),parameter :: opt = scc_options( &
       &  prlevel = 2, maxiter = 30, acc = 1.0_wp, etemp = 300.0_wp, grad = .true.,&
       &  solvent = "h2o")
    logical, parameter :: restart = .false.
    type(TMolecule)     :: mol
    type(TEnvironment)  :: env
    type(TRestart)      :: chk
    type(scc_results)   :: res_gff
    type(TGFFCalculator) :: calc
    real(wp) :: etot, sigma(3,3), gap
    real(wp), allocatable :: g(:,:)
    character(len=:),allocatable :: fnv
    integer  :: ipar
    logical  :: exist
    call init(env)
    call init(mol,at,xyz)
    call delete_file('charges')
    call newgffcalculator(env, mol, calc, '---', .false.)
    call addsolvationmodel(env, calc, tsolvinput(solvent=opt%solvent, alpb=.false., kernel=gbkernel%still))
    call env%checkpoint("GFN-FF parameter setup failed")
    allocate( g(3,mol%n), source = 0.0_wp )
    call assert_eq(calc%topo%nbond,5)
    call assert_eq(calc%topo%nangl,4)
    call assert_eq(calc%topo%ntors,1)
    g = 0.0_wp
    gff_print=.true.
    call calc%singlepoint(env, mol, chk, 1, .false., etot, g, sigma, gap, res_gff)
    call assert_close(res_gff%e_total,-0.964158677062_wp,thr)
    call assert_close(res_gff%gnorm,   0.013624276205_wp,thr)
    call assert_close(res_gff%e_bond, -0.856707643513_wp,thr)
    call assert_close(res_gff%e_angl,  0.000579711773_wp,thr)
    call assert_close(res_gff%e_tors,  0.000000008811_wp,thr)
    call assert_close(res_gff%e_es,   -0.150043166563_wp,thr*10)
    call assert_close(res_gff%e_disp, -0.001251669186_wp,thr)
    call assert_close(res_gff%e_rep,   0.066881023899_wp,thr)
    call assert_close(res_gff%e_hb,   -0.006894292337_wp,thr)
    call assert_close(res_gff%e_xb,   -0.000000000000_wp,thr)
    call assert_close(res_gff%e_batm, -0.000000000000_wp,thr)
    call assert_close(res_gff%g_solv, -0.016722649876_wp,thr)
    call assert_close(res_gff%g_sasa,  0.000126368690_wp,thr)
    call assert_close(res_gff%g_hb,   -0.009238122476_wp,thr)
    call assert_close(res_gff%g_born, -0.009468339217_wp,thr)
    call assert_close(res_gff%g_shift, 0.001857443126_wp,thr)
    call mol%deallocate
    call terminate(afail)
References xtb_main_setup::addsolvationmodel(), assertion::afail, delete_file(), xtb_setparam::etemp, xtb_gfnff_param::gff_print, xtb_main_setup::newgffcalculator(), terminate(), true(), and xtb_mctc_accuracy::wp.
Referenced by peeq_tester().
test_gfnff_hb()
subroutine test_gfnff_hb
Definition at line 87 of file gfnff.f90.
    use xtb_mctc_accuracy, only : wp
    use assertion
    use xtb_mctc_systools
    use xtb_type_environment
    use xtb_type_options
    use xtb_type_molecule
    use xtb_type_restart
    use xtb_type_data
    use xtb_gfnff_param
    use xtb_gfnff_setup
    use xtb_gfnff_eg
    use xtb_gfnff_ini
    use xtb_setparam
    use xtb_setmod
    use xtb_disp_dftd3param
    use xtb_disp_dftd4
    use xtb_gfnff_calculator, only : tgffcalculator
    use xtb_main_setup, only : newgffcalculator
    implicit none
    real(wp),parameter :: thr = 1.0e-10_wp
    integer, parameter :: nat = 7
    integer, parameter :: at(nat) = [6,8,1,1,8,1,1]
    real(wp),parameter :: xyz(3,nat) = reshape(&
       &[-5.78520874132429_wp,-1.92328475821000_wp,-0.02944611115854_wp, &
       & -5.57801768832583_wp, 0.17912532844037_wp, 0.72444143178660_wp, &
       & -4.27822256938673_wp,-2.74845397256109_wp,-1.13038073598642_wp, &
       & -7.47879539136783_wp,-2.97570121473211_wp, 0.39488815557786_wp, &
       & -0.83005338399036_wp, 2.43458470560665_wp,-0.78566331969245_wp, &
       & -0.74201439536855_wp, 4.04199055249898_wp, 0.09144422329636_wp, &
       & -2.44679415487233_wp, 1.69392751177087_wp,-0.27417668699116_wp],&
       & shape(xyz))
    logical, parameter :: restart = .false.
    type(TMolecule)     :: mol
    type(TEnvironment)  :: env
    type(TRestart)      :: chk
    type(scc_results)   :: res_gff
    type(TGFFCalculator) :: calc
    real(wp) :: etot, sigma(3,3), gap
    real(wp), allocatable :: g(:,:)
    character(len=:),allocatable :: fnv
    integer  :: ipar
    logical  :: exist
    call init(env)
    call init(mol,at,xyz)
    call delete_file('charges')
    call newgffcalculator(env, mol, calc, '---', .false.)
    call env%checkpoint("GFN-FF parameter setup failed")
    allocate( g(3,mol%n), source = 0.0_wp )
    call assert_eq(calc%topo%nbond,5)
    call assert_eq(calc%topo%nangl,4)
    call assert_eq(calc%topo%ntors,1)
    g = 0.0_wp
    gff_print=.true.
    call calc%singlepoint(env, mol, chk, 1, .false., etot, g, sigma, gap, res_gff)
    call assert_close(res_gff%e_total,-0.949706677118_wp,thr)
    call assert_close(res_gff%gnorm,   0.001152720923_wp,thr)
    call assert_close(res_gff%e_bond, -0.856707643513_wp,thr)
    call assert_close(res_gff%e_angl,  0.000579711773_wp,thr)
    call assert_close(res_gff%e_tors,  0.000000008811_wp,thr)
    call assert_close(res_gff%e_es,   -0.152313816530_wp,thr*10)
    call assert_close(res_gff%e_disp, -0.001251669186_wp,thr)
    call assert_close(res_gff%e_rep,   0.066881023899_wp,thr)
    call assert_close(res_gff%e_hb,   -0.006894292337_wp,thr)
    call assert_close(res_gff%e_xb,   -0.000000000000_wp,thr)
    call assert_close(res_gff%e_batm, -0.000000000000_wp,thr)
    call mol%deallocate
    call terminate(afail)
References assertion::afail, delete_file(), xtb_gfnff_param::gff_print, xtb_main_setup::newgffcalculator(), terminate(), true(), and xtb_mctc_accuracy::wp.
Referenced by peeq_tester().
test_gfnff_mindless_basic()
subroutine test_gfnff_mindless_basic
Definition at line 264 of file gfnff.f90.
    use assertion
    use xtb_mctc_accuracy, only : wp
    use xtb_test_molstock, only : getmolecule
    use xtb_type_molecule
    use xtb_type_param
    use xtb_type_pcem
    use xtb_type_data, only : scc_results
    use xtb_type_environment, only : tenvironment, init
    use xtb_type_restart, only : trestart
    use xtb_gfnff_calculator, only : tgffcalculator
    use xtb_main_setup, only : newgffcalculator
    implicit none
    real(wp), parameter :: thr = 1.0e-8_wp
    type(TEnvironment) :: env
    type(TMolecule) :: mol
    type(TRestart) :: chk
    type(TGFFCalculator) :: calc
    type(scc_results) :: res
    integer :: iMol
    logical :: exitRun
    real(wp) :: energy, hl_gap, sigma(3, 3)
    real(wp), allocatable :: gradient(:, :)
    character(len=*), parameter :: mindless(10) = [&
       & "mindless01", "mindless02", "mindless03", "mindless04", "mindless05", &
       & "mindless06", "mindless07", "mindless08", "mindless09", "mindless10"]
    real(wp), parameter :: ref_energies(10) = &
       &[-1.6235670601725_wp, -1.2974060907872_wp, -1.5825072926857_wp, &
       & -1.6086171378897_wp, -1.5093596077875_wp, -1.6076220027918_wp, &
       & -1.7328634195448_wp, -1.8875339867396_wp, -1.3924035489143_wp, &
       & -1.9583702712389_wp]
    real(wp), parameter :: ref_gnorms(10) = &
       &[0.11714711890640_wp, 0.08933168067298_wp, 0.15687133018871_wp, &
       & 0.09820451651462_wp, 0.08460010429134_wp, 0.08787739425161_wp, &
       & 0.12463658172704_wp, 0.10062734775717_wp, 0.06347506656236_wp, &
       & 0.09445561400996_wp]
    call init(env)
    do imol = 1, 10
       if (afail > 0) exit
       call getmolecule(mol, mindless(imol))
       if (allocated(gradient)) deallocate(gradient)
       allocate(gradient(3, len(mol)))
       call delete_file('charges')
       call newgffcalculator(env, mol, calc, '.param_gfnff.xtb', .false.)
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call calc%singlepoint(env, mol, chk, 2, .false., energy, gradient, sigma, &
          & hl_gap, res)
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call assert_close(energy, ref_energies(imol), thr)
       call assert_close(norm2(gradient), ref_gnorms(imol), thr)
    end do
    call terminate(afail)
References assertion::afail, assertion::assert(), delete_file(), xtb_test_molstock::getmolecule(), xtb_main_setup::newgffcalculator(), terminate(), and xtb_mctc_accuracy::wp.
Referenced by peeq_tester().
test_gfnff_mindless_solvation()
subroutine test_gfnff_mindless_solvation
Definition at line 341 of file gfnff.f90.
    use assertion
    use xtb_mctc_accuracy, only : wp
    use xtb_test_molstock, only : getmolecule
    use xtb_type_molecule
    use xtb_type_param
    use xtb_type_pcem
    use xtb_type_data, only : scc_results
    use xtb_type_environment, only : tenvironment, init
    use xtb_type_restart, only : trestart
    use xtb_gfnff_calculator, only : tgffcalculator
    use xtb_main_setup, only : newgffcalculator, addsolvationmodel
    use xtb_solv_input, only : tsolvinput
    use xtb_solv_kernel, only : gbkernel
    implicit none
    real(wp), parameter :: thr = 1.0e-8_wp
    type(TEnvironment) :: env
    type(TMolecule) :: mol
    type(TRestart) :: chk
    type(TGFFCalculator) :: calc
    type(scc_results) :: res
    integer :: iMol
    logical :: exitRun
    real(wp) :: energy, hl_gap, sigma(3, 3)
    real(wp), allocatable :: gradient(:, :)
    character(len=*), parameter :: mindless(10) = [&
       & "mindless01", "mindless02", "mindless03", "mindless04", "mindless05", &
       & "mindless06", "mindless07", "mindless08", "mindless09", "mindless10"]
    character(len=*), parameter :: solvents(10) = [character(len=20) ::&
       & "h2o", "chcl3", "thf", "acetonitrile", "toluene", &
       & "ch2cl2", "ether", "methanol", "cs2", "dmso"]
    real(wp), parameter :: ref_energies(10) = &
       &[-1.6540916426629_wp, -1.3143056510098_wp, -1.6141899469716_wp, &
       & -1.6204572392623_wp, -1.5288738676799_wp, -1.6293089943213_wp, &
       & -1.7562513711414_wp, -1.9034123090085_wp, -1.4068010735061_wp, &
       & -1.9722601751413_wp]
    real(wp), parameter :: ref_gnorms(10) = &
       &[0.11594122130461_wp, 0.08871796411903_wp, 0.15190830479600_wp, &
       & 0.09873901233954_wp, 0.08427306878219_wp, 0.08670875610818_wp, &
       & 0.11948602245812_wp, 0.10022284156198_wp, 0.06288313258789_wp, &
       & 0.09564569352042_wp]
    call init(env)
    do imol = 1, 10
       if (afail > 0) exit
       call getmolecule(mol, mindless(imol))
       if (allocated(gradient)) deallocate(gradient)
       allocate(gradient(3, len(mol)))
       call delete_file('charges')
       call newgffcalculator(env, mol, calc, '.param_gfnff.xtb', .false.)
       call addsolvationmodel(env, calc, tsolvinput(solvent=trim(solvents(imol)), &
          & alpb=mod(imol, 2)==0, kernel=gbkernel%still))
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call calc%singlepoint(env, mol, chk, 2, .false., energy, gradient, sigma, &
          & hl_gap, res)
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call assert_close(energy, ref_energies(imol), thr)
       call assert_close(norm2(gradient), ref_gnorms(imol), thr)
    end do
    call terminate(afail)
References xtb_main_setup::addsolvationmodel(), assertion::afail, assertion::assert(), delete_file(), xtb_solv_kernel::gbkernel, xtb_test_molstock::getmolecule(), xtb_main_setup::newgffcalculator(), terminate(), and xtb_mctc_accuracy::wp.
Referenced by peeq_tester().
test_gfnff_pdb()
subroutine test_gfnff_pdb
Definition at line 504 of file gfnff.f90.
    use assertion
    use xtb_mctc_accuracy, only : wp
    use xtb_test_molstock, only : getmolecule
    use xtb_type_molecule
    use xtb_type_param
    use xtb_type_pcem
    use xtb_type_data, only : scc_results
    use xtb_type_environment, only : tenvironment, init
    use xtb_type_restart, only : trestart
    use xtb_gfnff_calculator, only : tgffcalculator
    use xtb_main_setup, only : newgffcalculator, addsolvationmodel
    use xtb_solv_input, only : tsolvinput
    use xtb_solv_kernel, only : gbkernel
    implicit none
    real(wp), parameter :: thr = 1.0e-8_wp
    type(TEnvironment) :: env
    type(TMolecule) :: mol
    type(TRestart) :: chk
    type(TGFFCalculator) :: calc
    type(scc_results) :: res
    integer :: iMol
    logical :: exitRun
    real(wp) :: energy, hl_gap, sigma(3, 3)
    real(wp), allocatable :: gradient(:, :)
    real(wp), parameter :: ref_energies(3) = &
       &[-12.358885277947_wp, -12.442589851697_wp, -12.442131341448_wp]
    real(wp), parameter :: ref_gnorms(3) = &
       &[0.15855661051730_wp, 0.15148957207346_wp, 0.15151167424491_wp]
    call init(env)
    do imol = 1, 3
       if (afail > 0) exit
       call getmolecule(mol, 'pdb-4qxx')
       if (allocated(gradient)) deallocate(gradient)
       allocate(gradient(3, len(mol)))
       call delete_file('charges')
       call newgffcalculator(env, mol, calc, '.param_gfnff.xtb', .false.)
       if (imol > 1) then
          call addsolvationmodel(env, calc, tsolvinput(solvent='h2o', &
             & alpb=imol==3, kernel=gbkernel%still))
       end if
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call calc%singlepoint(env, mol, chk, 2, .false., energy, gradient, sigma, &
          & hl_gap, res)
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call assert_close(energy, ref_energies(imol), thr)
       call assert_close(norm2(gradient), ref_gnorms(imol), thr)
    end do
    call terminate(afail)
References xtb_main_setup::addsolvationmodel(), assertion::afail, assertion::assert(), delete_file(), xtb_solv_kernel::gbkernel, xtb_test_molstock::getmolecule(), xtb_main_setup::newgffcalculator(), terminate(), and xtb_mctc_accuracy::wp.
Referenced by peeq_tester().
test_gfnff_scaleup()
subroutine test_gfnff_scaleup
Definition at line 425 of file gfnff.f90.
    use assertion
    use xtb_mctc_accuracy, only : wp
    use xtb_test_molstock, only : getmolecule
    use xtb_type_molecule
    use xtb_type_param
    use xtb_type_pcem
    use xtb_type_data, only : scc_results
    use xtb_type_environment, only : tenvironment, init
    use xtb_type_restart, only : trestart
    use xtb_gfnff_calculator, only : tgffcalculator
    use xtb_main_setup, only : newgffcalculator, addsolvationmodel
    use xtb_solv_input, only : tsolvinput
    use xtb_solv_kernel, only : gbkernel
    implicit none
    real(wp), parameter :: thr = 1.0e-8_wp
    type(TEnvironment) :: env
    type(TMolecule) :: mol
    type(TRestart) :: chk
    type(TGFFCalculator) :: calc
    type(scc_results) :: res
    integer :: iMol
    logical :: exitRun
    real(wp) :: energy, hl_gap, sigma(3, 3)
    real(wp), allocatable :: gradient(:, :)
    character(len=*), parameter :: molecules(5) = [character(len=20) ::&
       & "caffeine", "rivaroxaban", "grubbs", "remdesivir", "taxol"]
    character(len=*), parameter :: solvents(5) = [character(len=20) ::&
       & "h2o", "acetonitrile", "toluene", "ether", "dmso"]
    real(wp), parameter :: ref_energies(5) = &
       &[-4.6919926039901_wp, -8.8807760138817_wp, -13.311107073100_wp, &
       & -13.822994859730_wp, -20.577952329212_wp]
    real(wp), parameter :: ref_gnorms(5) = &
       &[0.05947676640487_wp, 0.09522104624089_wp, 0.16195989065950_wp, &
       & 0.12496592222660_wp, 0.19366599743810_wp]
    call init(env)
    do imol = 1, 5
       if (afail > 0) exit
       call getmolecule(mol, trim(molecules(imol)))
       if (allocated(gradient)) deallocate(gradient)
       allocate(gradient(3, len(mol)))
       call delete_file('charges')
       call newgffcalculator(env, mol, calc, '.param_gfnff.xtb', .false.)
       call addsolvationmodel(env, calc, tsolvinput(solvent=trim(solvents(imol)), &
          & alpb=mod(imol, 2)==0, kernel=gbkernel%still))
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call calc%singlepoint(env, mol, chk, 2, .false., energy, gradient, sigma, &
          & hl_gap, res)
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call assert_close(energy, ref_energies(imol), thr)
       call assert_close(norm2(gradient), ref_gnorms(imol), thr)
    end do
    call terminate(afail)
References xtb_main_setup::addsolvationmodel(), assertion::afail, assertion::assert(), delete_file(), xtb_solv_kernel::gbkernel, xtb_test_molstock::getmolecule(), xtb_main_setup::newgffcalculator(), terminate(), and xtb_mctc_accuracy::wp.
Referenced by peeq_tester().
test_gfnff_sdf()
subroutine test_gfnff_sdf
Definition at line 577 of file gfnff.f90.
    use assertion
    use xtb_mctc_accuracy, only : wp
    use xtb_test_molstock, only : getmolecule
    use xtb_type_molecule
    use xtb_type_param
    use xtb_type_pcem
    use xtb_type_data, only : scc_results
    use xtb_type_environment, only : tenvironment, init
    use xtb_type_restart, only : trestart
    use xtb_gfnff_calculator, only : tgffcalculator
    use xtb_main_setup, only : newgffcalculator, addsolvationmodel
    use xtb_solv_input, only : tsolvinput
    use xtb_solv_kernel, only : gbkernel
    use xtb_setparam, only : ichrg
    implicit none
    real(wp), parameter :: thr = 1.0e-8_wp
    type(TEnvironment) :: env
    type(TMolecule) :: mol
    type(TRestart) :: chk
    type(TGFFCalculator) :: calc
    type(scc_results) :: res
    integer :: iMol
    logical :: exitRun
    real(wp) :: energy, hl_gap, sigma(3, 3)
    real(wp), allocatable :: gradient(:, :)
    real(wp), parameter :: ref_energies(3) = &
       &[-0.98330642628373_wp, -1.0826001974262_wp, -1.0826319137928_wp]
    real(wp), parameter :: ref_gnorms(3) = &
       &[0.11515550863614e-2_wp, 0.59760221346330e-2_wp, 0.59645861418074e-2_wp]
    call init(env)
    do imol = 1, 3
       if (afail > 0) exit
       call getmolecule(mol, 'bug332')
       ichrg = nint(mol%chrg)
       if (allocated(gradient)) deallocate(gradient)
       allocate(gradient(3, len(mol)))
       call delete_file('charges')
       call newgffcalculator(env, mol, calc, '.param_gfnff.xtb', .false.)
       if (imol > 1) then
          call addsolvationmodel(env, calc, tsolvinput(solvent='h2o', &
             & alpb=imol==3, kernel=gbkernel%p16))
       end if
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call calc%singlepoint(env, mol, chk, 2, .false., energy, gradient, sigma, &
          & hl_gap, res)
       call env%check(exitrun)
       call assert(.not.exitrun)
       if (exitrun) exit
       call assert_close(energy, ref_energies(imol), thr)
       call assert_close(norm2(gradient), ref_gnorms(imol), thr)
    end do
    call terminate(afail)
References xtb_main_setup::addsolvationmodel(), assertion::afail, assertion::assert(), delete_file(), xtb_solv_kernel::gbkernel, xtb_test_molstock::getmolecule(), xtb_setparam::ichrg, xtb_main_setup::newgffcalculator(), terminate(), and xtb_mctc_accuracy::wp.
Referenced by peeq_tester().
test_gfnff_sp()
subroutine test_gfnff_sp
Definition at line 1 of file gfnff.f90.
    use xtb_mctc_accuracy, only : wp
    use assertion
    use xtb_mctc_systools
    use xtb_solv_gbsa
    use xtb_type_environment
    use xtb_type_options
    use xtb_type_molecule
    use xtb_type_data
    use xtb_gfnff_param
    use xtb_gfnff_setup
    use xtb_gfnff_eg
    use xtb_gfnff_ini
    use xtb_setparam
    use xtb_setmod
    use xtb_disp_dftd3param
    use xtb_disp_dftd4
    use xtb_gfnff_calculator, only : tgffcalculator
    use xtb_main_setup, only : newgffcalculator
    implicit none
    real(wp),parameter :: thr = 1.0e-10_wp
    integer, parameter :: nat = 8
    integer, parameter :: at(nat) = [7,15,9,9,1,1,1,1]
    real(wp),parameter :: xyz(3,nat) = reshape(&
       &[1.50040286526241_wp,-2.88219140061585_wp, 0.00000000000000_wp, &
       & 0.00000000000000_wp, 1.90142164792207_wp, 0.00000000000000_wp, &
       &-0.02649585010919_wp,-5.05651406856634_wp, 0.00000000000000_wp, &
       &-1.39762821979929_wp, 4.65236211997835_wp, 0.00000000000000_wp, &
       & 2.62205170116282_wp,-3.14316635901963_wp, 1.53958066744940_wp, &
       &-1.46489869067775_wp, 0.78885483581631_wp, 1.94964934855945_wp, &
       & 2.62205170116282_wp,-3.14316635901963_wp,-1.53958066744940_wp, &
       &-1.46489869067775_wp, 0.78885483581631_wp,-1.94964934855945_wp],&
       & shape(xyz))
    logical, parameter :: restart = .false.
    type(TMolecule)     :: mol
    type(TEnvironment)  :: env
    type(scc_results)   :: res_gff
    type(TGFFCalculator) :: calc
    type(TBorn), allocatable :: solvation
    real(wp) :: etot
    real(wp), allocatable :: g(:,:)
    character(len=:),allocatable :: fnv
    integer  :: ipar
    logical  :: exist
    call init(env)
    call init(mol,at,xyz)
    call delete_file('charges')
    call newgffcalculator(env, mol, calc, '.param_gfnff.xtb', .false.)
    call env%checkpoint("GFN-FF parameter setup failed")
    allocate( g(3,mol%n), source = 0.0_wp )
    call assert_eq(calc%topo%nbond,6)
    call assert_eq(calc%topo%nangl,6)
    call assert_eq(calc%topo%ntors,1)
    g = 0.0_wp
    gff_print=.true.
    call gfnff_eg(env,gff_print,mol%n,nint(mol%chrg),mol%at,mol%xyz,make_chrg, &
       & g,etot,res_gff,calc%param,calc%topo,solvation,.true.,calc%version, &
       & calc%accuracy)
    call assert_close(res_gff%e_total,-0.76480130317838_wp,thr)
    call assert_close(res_gff%gnorm,   0.06237477492373_wp,thr)
    call assert_close(res_gff%e_bond, -0.74131049663951_wp,thr)
    call assert_close(res_gff%e_angl,  0.00633910404059_wp,thr)
    call assert_close(res_gff%e_tors,  0.00004724445432_wp,thr)
    call assert_close(res_gff%e_es,   -0.05070333390156_wp,thr*10)
    call assert_close(res_gff%e_disp, -0.00224146422313_wp,thr)
    call assert_close(res_gff%e_rep,   0.03086605590295_wp,thr)
    call assert_close(res_gff%e_hb,   -0.00003142616658_wp,thr)
    call assert_close(res_gff%e_xb,   -0.00776698664545_wp,thr)
    call assert_close(res_gff%e_batm, -0.00000000000000_wp,thr)
    call mol%deallocate
    call terminate(afail)
References assertion::afail, delete_file(), xtb_gfnff_param::gff_print, xtb_gfnff_eg::gfnff_eg(), xtb_gfnff_param::make_chrg, xtb_main_setup::newgffcalculator(), terminate(), true(), and xtb_mctc_accuracy::wp.
Referenced by peeq_tester().