My Project: src/gfnff/gfnff_eg.f90 File Reference
gfnff_eg.f90 File Reference
Modules
module xtb_gfnff_eg
Functions/Subroutines
subroutine, public xtb_gfnff_eg::gfnff_eg (env, pr, n, ichrg, at, xyz, makeq, g, etot, res_gff, param, topo, solvation, update, version, accuracy)
subroutine xtb_gfnff_eg::egbond (i, iat, jat, rab, rij, drij, n, at, xyz, e, g, topo)
subroutine xtb_gfnff_eg::egbond_hb (i, iat, jat, rab, rij, drij, hb_cn, hb_dcn, n, at, xyz, e, g, param, topo)
subroutine xtb_gfnff_eg::dncoord_erf (nat, at, xyz, rcov, cn, dcn, thr, topo)
subroutine xtb_gfnff_eg::egbend (m, j, i, k, n, at, xyz, e, g, param, topo)
subroutine xtb_gfnff_eg::egbend_nci_mul (j, i, k, c0, fc, n, at, xyz, e, g)
subroutine xtb_gfnff_eg::egbend_nci (j, i, k, c0, kijk, n, at, xyz, e, g, param)
subroutine xtb_gfnff_eg::egtors (m, i, j, k, l, n, at, xyz, e, g, param, topo)
subroutine xtb_gfnff_eg::egtors_nci_mul (i, j, k, l, rn, phi0, tshift, n, at, xyz, e, g)
subroutine xtb_gfnff_eg::egtors_nci (i, j, k, l, rn, phi0, fc, n, at, xyz, e, g, param)
subroutine xtb_gfnff_eg::gfnffdampa (ati, atj, r2, damp, ddamp, param)
subroutine xtb_gfnff_eg::gfnffdampt (ati, atj, r2, damp, ddamp, param)
subroutine xtb_gfnff_eg::gfnffdampa_nci (ati, atj, r2, damp, ddamp, param)
subroutine xtb_gfnff_eg::gfnffdampt_nci (ati, atj, r2, damp, ddamp, param)
subroutine xtb_gfnff_eg::goed_gfnff (env, single, n, at, sqrab, r, chrg, eeqtmp, cn, q, es, gbsa, param, topo)
subroutine xtb_gfnff_eg::abhgfnff_eg1 (n, A, B, H, at, xyz, q, sqrab, srab, energy, gdr, param, topo)
subroutine xtb_gfnff_eg::abhgfnff_eg2new (n, A, B, H, at, xyz, q, sqrab, srab, energy, gdr, param, topo)
subroutine xtb_gfnff_eg::abhgfnff_eg2_rnr (n, A, B, H, at, xyz, q, sqrab, srab, energy, gdr, param, topo)
subroutine xtb_gfnff_eg::abhgfnff_eg3 (n, A, B, H, at, xyz, q, sqrab, srab, energy, gdr, param, topo)
subroutine xtb_gfnff_eg::abhgfnff_eg3_mul (n, A, B, H, at, xyz, q, sqrab, srab, energy, gdr, param, topo)
subroutine xtb_gfnff_eg::abhgfnff_eg3_add (n, A, B, H, at, xyz, q, sqrab, srab, energy, gdr, param, topo)
subroutine xtb_gfnff_eg::rbxgfnff_eg (n, A, B, X, at, xyz, q, energy, gdr, param)
subroutine xtb_gfnff_eg::batmgfnff_eg (n, iat, jat, kat, at, xyz, q, sqrab, srab, energy, g, param)
subroutine, public xtb_gfnff_eg::gfnff_dlogcoord (n, at, xyz, rab, logCN, dlogCN, thr2, param)
logCN derivative saved in dlogCN array
pure elemental real(wp) function create_logcn (cn, param)
pure elemental real(wp) function create_dlogcn (cn, param)
pure elemental real(wp) function create_erfcn (k, r, r0)
pure elemental real(wp) function create_derfcn (k, r, r0)
pure elemental real(wp) function create_expcn (k, r, r0)
pure elemental real(wp) function create_dexpcn (k, r, r0)
Function/Subroutine Documentation
create_derfcn()
pure elemental real(wp) function gfnff_dlogcoord::create_derfcn (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0)
Definition at line 3171 of file gfnff_eg.f90.
 use xtb_mctc_accuracy, only : wp
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp), parameter :: sqrtpi = 1.77245385091_wp
    real(wp) :: count
    real(wp) :: dr
    dr = (r -r0)/r0
    count = k/sqrtpi*exp(-k**2*dr*dr)/r0
References xtb_mctc_accuracy::wp.
Referenced by xtb_gfnff_eg::gfnff_dlogcoord().
create_dexpcn()
pure elemental real(wp) function gfnff_dlogcoord::create_dexpcn (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0) private
Definition at line 3191 of file gfnff_eg.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    real(wp) :: expterm
    expterm=exp(-k*(r0/r-1._wp))
    count = (-k*r0*expterm)/(r**2*((expterm+1._wp)**2))
create_dlogcn()
pure elemental real(wp) function gfnff_dlogcoord::create_dlogcn (real(wp), intent(in) cn, type(tgffdata), intent(in) param)
Definition at line 3152 of file gfnff_eg.f90.
 use xtb_mctc_accuracy, only : wp
       type(TGFFData), intent(in) :: param
    real(wp), intent(in) :: cn
    real(wp) :: count
    count = exp(param%cnmax)/(exp(param%cnmax) + exp(cn))
References xtb_mctc_accuracy::wp.
Referenced by xtb_gfnff_eg::gfnff_dlogcoord().
create_erfcn()
pure elemental real(wp) function gfnff_dlogcoord::create_erfcn (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0)
Definition at line 3160 of file gfnff_eg.f90.
 use xtb_mctc_accuracy, only : wp
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    real(wp) :: dr
    dr = (r -r0)/r0
    count = 0.5_wp * (1.0_wp + erf(kn*dr))
References xtb_mctc_accuracy::wp.
create_expcn()
pure elemental real(wp) function gfnff_dlogcoord::create_expcn (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0)
Definition at line 3183 of file gfnff_eg.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    count =1.0_wp/(1.0_wp+exp(-k*(r0/r-1.0_wp)))
create_logcn()
pure elemental real(wp) function gfnff_dlogcoord::create_logcn (real(wp), intent(in) cn, type(tgffdata), intent(in) param)
Definition at line 3144 of file gfnff_eg.f90.
 use xtb_mctc_accuracy, only : wp
       type(TGFFData), intent(in) :: param
    real(wp), intent(in) :: cn
    real(wp) :: count
    count = log(1 + exp(param%cnmax)) - log(1 + exp(param%cnmax - cn) )
References xtb_mctc_accuracy::wp.
Referenced by xtb_gfnff_eg::gfnff_dlogcoord().