My Project: src/gfnff/gfnff_ini.f90 File Reference
gfnff_ini.f90 File Reference
Modules
module xtb_gfnff_ini
Functions/Subroutines
subroutine xtb_gfnff_ini::gfnff_ini (env, pr, makeneighbor, mol, ichrg, gen, param, topo, accuracy)
pure elemental real(wp) function zeta (at, q)
zeta(g_a,gam(ia)*g_c,refq(ii,ia)+iz,q(i)+iz)
Function/Subroutine Documentation
zeta()
pure elemental real(wp) function gfnff_ini::zeta (integer, intent(in) at, real(wp), intent(in) q)
zeta(g_a,gam(ia)*g_c,refq(ii,ia)+iz,q(i)+iz)
charge scaling function
Definition at line 1861 of file gfnff_ini.f90.
 use xtb_mctc_accuracy, only : wp
    implicit none
    integer ,intent(in) :: at
    real(wp),intent(in) :: q
    real(wp)           :: zeta,qmod
    real(wp),parameter :: zeff(86) = (/ &
    &   1,                                                 2,  & ! H-He
    &   3, 4,                               5, 6, 7, 8, 9,10,  & ! Li-Ne
    &  11,12,                              13,14,15,16,17,18,  & ! Na-Ar
    &  19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,  & ! K-Kr
    &   9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,  & ! Rb-Xe
    &   9,10,11,30,31,32,33,34,35,36,37,38,39,40,41,42,43,  & ! Cs-Lu
    &  12,13,14,15,16,17,18,19,20,21,22,23,24,25,26/)  ! Hf-Rn
 !! Semiempirical Evaluation of the GlobalHardness of the Atoms of 103
 !! Elements of the Periodic Table Using the Most Probable Radii as
 !! their Size Descriptors DULAL C. GHOSH, NAZMUL ISLAM 2009 in
 !! Wiley InterScience (www.inte"rscience.wiley.com).
 !! DOI 10.1002/qua.22202
 !! values in the paper multiplied by two because
 !! (ii:ii)=(IP-EA)=d^2 E/dN^2 but the hardness
 !! definition they use is 1/2d^2 E/dN^2 (in Eh)
    real(wp),parameter :: c(1:86) = (/ &
   &0.47259288_wp,0.92203391_wp,0.17452888_wp,0.25700733_wp,0.33949086_wp,0.42195412_wp, & ! H-C
   &0.50438193_wp,0.58691863_wp,0.66931351_wp,0.75191607_wp,0.17964105_wp,0.22157276_wp, & ! N-Mg
   &0.26348578_wp,0.30539645_wp,0.34734014_wp,0.38924725_wp,0.43115670_wp,0.47308269_wp, & ! Al-Ar
   &0.17105469_wp,0.20276244_wp,0.21007322_wp,0.21739647_wp,0.22471039_wp,0.23201501_wp, & ! Ca-Cr
   &0.23933969_wp,0.24665638_wp,0.25398255_wp,0.26128863_wp,0.26859476_wp,0.27592565_wp, & ! Mn-Zn
   &0.30762999_wp,0.33931580_wp,0.37235985_wp,0.40273549_wp,0.43445776_wp,0.46611708_wp, & ! Ga-Kr
   &0.15585079_wp,0.18649324_wp,0.19356210_wp,0.20063311_wp,0.20770522_wp,0.21477254_wp, & ! Rb-Mo
   &0.22184614_wp,0.22891872_wp,0.23598621_wp,0.24305612_wp,0.25013018_wp,0.25719937_wp, & ! Tc-Cd
   &0.28784780_wp,0.31848673_wp,0.34912431_wp,0.37976593_wp,0.41040808_wp,0.44105777_wp, & ! In-Xe
   &0.05019332_wp,0.06762570_wp,0.08504445_wp,0.10247736_wp,0.11991105_wp,0.13732772_wp, & ! Cs-Nd
   &0.15476297_wp,0.17218265_wp,0.18961288_wp,0.20704760_wp,0.22446752_wp,0.24189645_wp, & ! Pm-Dy
   &0.25932503_wp,0.27676094_wp,0.29418231_wp,0.31159587_wp,0.32902274_wp,0.34592298_wp, & ! Ho-Hf
   &0.36388048_wp,0.38130586_wp,0.39877476_wp,0.41614298_wp,0.43364510_wp,0.45104014_wp, & ! Ta-Pt
   &0.46848986_wp,0.48584550_wp,0.12526730_wp,0.14268677_wp,0.16011615_wp,0.17755889_wp, & ! Au-Po
   &0.19497557_wp,0.21240778_wp/)
    intrinsic :: exp
    qmod = zeff(at) + q
    if (qmod.lt.0._wp) then
       zeta = exp( 3.0d0 )
    else
       zeta = exp( 3.0d0  * ( 1._wp - exp( c(at) * ( 1._wp - zeff(at) / qmod ) ) ) )
    endif
Referenced by xtb_gfnff_ini::gfnff_ini(), xtb_basis::newbasisset(), and xtb_slater::slatertogauss().