My Project: src/header.f90 File Reference
header.f90 File Reference
Functions/Subroutines
subroutine xtb_header (iunit)
subroutine xtb_version (iunit)
subroutine disclamer (iunit)
subroutine gfn0_header (iunit)
subroutine peeq_header (iunit)
subroutine gfn1_header (iunit)
subroutine gfn2_header (iunit)
subroutine gfnff_header (iunit, version)
subroutine struc_convert_header (iunit)
subroutine ipea_header (iunit)
subroutine stda_header (iunit)
subroutine qmdff_header (iunit)
subroutine driver_header (iunit)
subroutine eht_header (iunit)
subroutine scc_header (iunit)
subroutine vip_header (iunit)
subroutine vea_header (iunit)
subroutine ancopt_header (iunit, verbose)
subroutine numhess_header (iunit)
subroutine md_header (iunit)
subroutine metadyn_header (iunit)
subroutine rmsdpath_header (iunit)
subroutine reactor_header (iunit)
subroutine siman_header (iunit)
subroutine generic_header (iunit, string, width, offset)
Function/Subroutine Documentation
ancopt_header()
subroutine ancopt_header (integer, intent(in) iunit, logical, intent(in) verbose)
Parameters
[in] verbose < < < < < < < < < < < < < < < < < > > > > > > > > > > > > > > > > > >!
Definition at line 225 of file header.f90.
 integer,intent(in) :: iunit
 logical,intent(in) :: verbose
 if (verbose) then
 write(iunit,'(a)') &
    "                    ___    _   _ _____             _              ",&
    "                   / _ \  | \ | /  __ \ ___  _ __ | |_            ",&
    "                  / /_\ \ |  \| | /  \// _ \| '_ \|  _|           ",&
    "      -----------/ _____ \| . ` | |---| (_) | |_) | |_----------- ",&
    "     |          / /     \ | |\  | \__/\\___/| .__/ \__|          |",&
    "     |         / /       \\_| \_/\____/     | |                  |",&
    "     |         |/ ==========================|_|=======           |"
 else
 write(iunit,'(a)') &
    "      ----------------------------------------------------------- ",&
    "     |                   =====================                   |",&
    "     |                        A N C O P T                        |",&
    "     |                   =====================                   |"
 endif
 write(iunit,'(a)') &
    "     |               Approximate Normal Coordinate               |",&
    "     |                Rational Function Optimizer                |",&
    "      ----------------------------------------------------------- "
Referenced by xtb_prog_main::xtbmain().
disclamer()
subroutine disclamer (integer, intent(in) iunit)
Definition at line 43 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(3x,a)') &
    "xtb is free software: you can redistribute it and/or modify it under", &
    "the terms of the GNU Lesser General Public License as published by", &
    "the Free Software Foundation, either version 3 of the License, or", &
    "(at your option) any later version.", &
    "", &
    "xtb is distributed in the hope that it will be useful,", &
    "but WITHOUT ANY WARRANTY; without even the implied warranty of", &
    "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the", &
    "GNU Lesser General Public License for more details.", &
    ""
Referenced by xtb_prog_main::parsearguments(), and xtb_prog_main::xtbmain().
driver_header()
subroutine driver_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 174 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                   D R I V E R                   |",&
    "|     running other programs in this program      |",&
    " ------------------------------------------------- "
Referenced by xtb_type_dummycalc::writeinfo().
eht_header()
subroutine eht_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 185 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|        Valence Tight Binding Calculation        |",&
    " ------------------------------------------------- "
generic_header()
subroutine generic_header (integer, intent(in) iunit, character(len=*), intent(in) string, integer, intent(in) width, integer, intent(in) offset)
Definition at line 317 of file header.f90.
 implicit none
 integer,intent(in) :: iunit
 integer,intent(in) :: offset
 integer,intent(in) :: width
 character(len=*),intent(in) :: string
 character(len=width) :: dum1,dum2
 character(len=2*width) :: outstring
 character(len=width) :: formatstr
 integer :: strlen,ifront,iback
 strlen = len(string)
 ifront = (width - strlen)/2
 iback  = width - ifront - strlen
 write(dum1,*) width
 write(dum2,*) offset
 write(formatstr,'(i0,"x,a,",i0,"x")') ifront,iback
 write(outstring,'("|",'//formatstr//',"|")') string
 write(iunit,'('//dum2//'x,1x,'//dum1//'("-"),1x)')
 write(iunit,'('//dum2//'x,a)') trim(outstring)
 write(iunit,'('//dum2//'x,1x,'//dum1//'("-"),1x)')
Referenced by xtb_fixparam::fix_info(), xtb_geoopt::geometry_optimization(), xtb_kopt::get_kopt(), xtb_propertyoutput::main_freq(), xtb_scanparam::pot_info(), print_geosum(), print_pbcsum(), xtb_printout::setup_summary(), xtb_xtb_data::writeinfo(), xtb_prog_info::xtbinfo(), and xtb_prog_main::xtbmain().
gfn0_header()
subroutine gfn0_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 59 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                 G F N 0 - x T B                 |",&
    "| Geometry, Frequencies, Noncovalent interactions |",&
    "|           preliminary parametrisation           |",&
    " ------------------------------------------------- "
gfn1_header()
subroutine gfn1_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 83 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                  G F N - x T B                  |",&
    "| Geometry, Frequencies, Noncovalent interactions |",&
    "|            JCTC 2017 parametrisation            |",&
    " ------------------------------------------------- "
gfn2_header()
subroutine gfn2_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 95 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                 G F N 2 - x T B                 |",&
    "| Geometry, Frequencies, Noncovalent interactions |",&
    "|            JCTC 2019 parametrisation            |",&
    " ------------------------------------------------- "
gfnff_header()
subroutine gfnff_header (integer, intent(in) iunit, integer, intent(in) version)
Definition at line 107 of file header.f90.
 use xtb_gfnff_param, only : gffversion
 integer,intent(in) :: iunit
 integer,intent(in) :: version
 character(len=52)  :: nr
 select case(version)
 case(gffversion%angewChem2020, gffversion%harmonic2020)
   nr="|                  Version 1.0.0                  |"
 case(gffversion%angewChem2020_1)
   nr="|                  Version 1.0.2                  |"
 end select
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                   G F N - F F                   |",&
    "|          A general generic force-field          |",nr,&
    !|                  Version 1.0.x                  |
    " ------------------------------------------------- "
References xtb_gfnff_param::gffversion.
Referenced by xtb_gfnff_calculator::writeinfo().
ipea_header()
subroutine ipea_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 141 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                 I P E A - x T B                 |",&
    "|  Ionisation Potentials and Electron Affinities  |",&
    " ------------------------------------------------- "
md_header()
subroutine md_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 263 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|               Molecular Dynamics                |",&
    " ------------------------------------------------- "
Referenced by xtb_prog_main::xtbmain().
metadyn_header()
subroutine metadyn_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 273 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                  Meta Dynamics                  |",&
    " ------------------------------------------------- "
Referenced by xtb_prog_main::xtbmain().
numhess_header()
subroutine numhess_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 253 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                Numerical Hessian                |",&
    " ------------------------------------------------- "
Referenced by xtb_prog_main::xtbmain().
peeq_header()
subroutine peeq_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 71 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                   P E E Q                       |",&
    "|  Periodic Electronegativity Equilibration Model |",&
    "|              based on GFN0-xTB                  |",&
    " ------------------------------------------------- "
qmdff_header()
subroutine qmdff_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 163 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                    Q M D F F                    |",&
    "|     quantum mechanical derived force field      |",&
    " ------------------------------------------------- "
Referenced by xtb_type_dummycalc::writeinfo().
reactor_header()
subroutine reactor_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 294 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                  R E A C T O R                  |",&
    "|        RMSD-biased meta-dynamic reactions       |",&
    " ------------------------------------------------- "
rmsdpath_header()
subroutine rmsdpath_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 283 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                     P A T H                     |",&
    "|            RMSD-Push/Pull Path Finder           |",&
    " ------------------------------------------------- "
Referenced by xtb_prog_main::xtbmain().
scc_header()
subroutine scc_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 195 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|        Self-Consistent Charge Iterations        |",&
    " ------------------------------------------------- "
siman_header()
subroutine siman_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 305 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                    S I M A N                    |",&
    "|               Simulated Annealing               |",&
    "|              conformational search              |",&
    " ------------------------------------------------- "
stda_header()
subroutine stda_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 152 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                 s T D A - x T B                 |",&
    "|      simplified Tamm-Dancoff Approximation      |",&
    " ------------------------------------------------- "
struc_convert_header()
subroutine struc_convert_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 129 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|                     2D => 3D                    |",&
    "|          A structure converter based on         |",&
    "|                   G F N - F F                   |",&
    " ------------------------------------------------- "
Referenced by xtb_gfnff_convert::struc_convert().
vea_header()
subroutine vea_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 215 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|        vertical delta SCC EA calculation        |",&
    " ------------------------------------------------- "
Referenced by xtb_prog_main::xtbmain().
vip_header()
subroutine vip_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < > > > > > > > > > > > > >!
Definition at line 205 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(10x,a)') &
    " ------------------------------------------------- ",&
    "|        vertical delta SCC IP calculation        |",&
    " ------------------------------------------------- "
Referenced by xtb_prog_main::xtbmain().
xtb_header()
subroutine xtb_header (integer, intent(in) iunit)
Parameters
[in] iunit < < < < < < < < < < < < < < < < < > > > > > > > > > > > > > > > > > >!
Definition at line 18 of file header.f90.
 integer,intent(in) :: iunit
 write(iunit,'(a)') &
    "      -----------------------------------------------------------      ",&
    "     |                   =====================                   |     ",&
    "     |                           x T B                           |     ",&
    "     |                   =====================                   |     ",&
    "     |                         S. Grimme                         |     ",&
    "     |          Mulliken Center for Theoretical Chemistry        |     ",&
    "     |                    University of Bonn                     |     ",&
    !     |  Version number by <major>.<minor>.<rev> (<author><date>) |     !
    "      -----------------------------------------------------------      ",""
    call xtb_version(iunit)
References xtb_version().
Referenced by xtb_prog_main::parsearguments(), and xtb_prog_main::xtbmain().
xtb_version()
subroutine xtb_version (integer, intent(in) iunit)
Definition at line 35 of file header.f90.
 integer,intent(in) :: iunit
 include 'xtb_version.fh'
 write(iunit,'(3x,"*",*(1x,a))') &
    & "xtb version", version, "compiled by", author, "on", date
 write(iunit,'(a)')
Referenced by xtb_header().