My Project: xtb_disp_coordinationnumber::getcoordinationnumber Interface Reference
xtb_disp_coordinationnumber::getcoordinationnumber Interface Reference
Private Member Functions
subroutine getcoordinationnumberwrap (env, mol, cf, cn, dcndr, dcndL, cutoff)
Geometric fractional coordination number, supports both error function.
subroutine getcoordinationnumbernl (mol, neighs, neighlist, cf, cn, dcndr, dcndL)
Geometric fractional coordination number, supports both error function.
subroutine getcoordinationnumberlp (mol, trans, cutoff, cf, cn, dcndr, dcndL)
Geometric fractional coordination number, supports both error function.
Detailed Description
Definition at line 34 of file coordinationnumber.f90.
Member Function/Subroutine Documentation
getcoordinationnumberlp()
subroutine xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp (type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) trans, real(wp), intent(in) cutoff, integer, intent(in) cf, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:, :, :), intent(out) dcndr, real(wp), dimension(:, :, :), intent(out) dcndL) private
Geometric fractional coordination number, supports both error function.
Parameters
[in] mol Molecular structure information
[in] trans Lattice points
[in] cutoff Real space cutoff
[in] cf Coordination number type (by counting function)
[out] cn Error function coordination number
[out] dcndr Derivative of the CN with respect to the Cartesian coordinates
[out] dcndl Derivative of the CN with respect to strain deformations
Definition at line 302 of file coordinationnumber.f90.
    type(TMolecule), intent(in) :: mol
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(in) :: cutoff
    integer, intent(in) :: cf
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out) :: dcndr(:, :, :)
    real(wp), intent(out) :: dcndL(:, :, :)
    real(wp), parameter :: kcn_exp = 16.0_wp
    real(wp), parameter :: kcn_erf = 7.5_wp
    real(wp), parameter :: kcn_gfn = 10.0_wp
    select case(cf)
    case(cntype%exp)
       call ncoordlatp(mol, trans, cutoff, kcn_exp, expcount, dexpcount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%erf)
       call ncoordlatp(mol, trans, cutoff, kcn_erf, erfcount, derfcount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%cov)
       call ncoordlatp(mol, trans, cutoff, kcn_erf, erfcount, derfcount, &
          & .true., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%gfn)
       call ncoordlatp(mol, trans, cutoff, kcn_gfn, gfncount, dgfncount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    end select
References xtb_disp_coordinationnumber::cntype, xtb_param_covalentradd3::covalentradd3, xtb_disp_coordinationnumber::derfcount(), xtb_disp_coordinationnumber::dexpcount(), xtb_disp_coordinationnumber::dgfncount(), xtb_disp_coordinationnumber::erfcount(), xtb_disp_coordinationnumber::expcount(), xtb_disp_coordinationnumber::gfncount(), xtb_disp_coordinationnumber::ncoordlatp(), xtb_param_paulingen::paulingen, and true().
getcoordinationnumbernl()
subroutine xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl (type(tmolecule), intent(in) mol, integer, dimension(:), intent(in) neighs, type(tneighbourlist), intent(in) neighlist, integer, intent(in) cf, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:, :, :), intent(out) dcndr, real(wp), dimension(:, :, :), intent(out) dcndL) private
Geometric fractional coordination number, supports both error function.
Parameters
[in] mol Molecular structure information
[in] neighs Number of interacting neighbours
[in] neighlist Neighbourlist
[in] cf Coordination number type (by counting function)
[out] cn Error function coordination number
[out] dcndr Derivative of the CN with respect to the Cartesian coordinates
[out] dcndl Derivative of the CN with respect to strain deformations
Definition at line 159 of file coordinationnumber.f90.
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: neighs(:)
    type(TNeighbourList), intent(in) :: neighlist
    integer, intent(in) :: cf
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out) :: dcndr(:, :, :)
    real(wp), intent(out) :: dcndL(:, :, :)
    real(wp), parameter :: kcn_exp = 16.0_wp
    real(wp), parameter :: kcn_erf = 7.5_wp
    real(wp), parameter :: kcn_gfn = 10.0_wp
    select case(cf)
    case(cntype%exp)
       call ncoordneighs(mol, neighs, neighlist, kcn_exp, expcount, dexpcount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%erf)
       call ncoordneighs(mol, neighs, neighlist, kcn_erf, erfcount, derfcount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%cov)
       call ncoordneighs(mol, neighs, neighlist, kcn_erf, erfcount, derfcount, &
          & .true., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%gfn)
       call ncoordneighs(mol, neighs, neighlist, kcn_gfn, gfncount, dgfncount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    end select
References xtb_disp_coordinationnumber::cntype, xtb_param_covalentradd3::covalentradd3, xtb_disp_coordinationnumber::derfcount(), xtb_disp_coordinationnumber::dexpcount(), xtb_disp_coordinationnumber::dgfncount(), xtb_disp_coordinationnumber::erfcount(), xtb_disp_coordinationnumber::expcount(), xtb_disp_coordinationnumber::gfncount(), xtb_disp_coordinationnumber::ncoordneighs(), xtb_param_paulingen::paulingen, and true().
getcoordinationnumberwrap()
subroutine xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberwrap (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, integer, intent(in) cf, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:, :, :), intent(out) dcndr, real(wp), dimension(:, :, :), intent(out) dcndL, real(wp), intent(in), optional cutoff) private
Geometric fractional coordination number, supports both error function.
Parameters
[in,out] env Computational Environment
[in] mol Molecular structure information
[in] cf Coordination number type (by counting function)
[out] cn Error function coordination number
[out] dcndr Derivative of the CN with respect to the Cartesian coordinates
[out] dcndl Derivative of the CN with respect to strain deformations
[in] cutoff Real space cutoff for the coordination number
Definition at line 101 of file coordinationnumber.f90.
    character(len=*), parameter :: source = &
       & 'disp_coordinationnumber_getCoordinationNumberWrap'
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: cf
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out) :: dcndr(:, :, :)
    real(wp), intent(out) :: dcndL(:, :, :)
    real(wp), intent(in), optional :: cutoff
    logical :: exitRun
    real(wp) :: rCutoff
    real(wp), allocatable :: trans(:, :)
    type(TLatticePoint) :: latp
    if (present(cutoff)) then
       rcutoff = cutoff
    else
       rcutoff = 40.0_wp
    end if
    call init_(latp, env, mol, rcutoff)
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Setup of lattice point generator failed", source)
       return
    end if
    call latp%getLatticePoints(trans, rcutoff)
    call getcoordinationnumber(mol, trans, rcutoff, cf, cn, dcndr, dcndl)
The documentation for this interface was generated from the following file:
src/disp/coordinationnumber.f90