My Project: xtb_disp_ncoord::get_erf_cn Interface Reference
xtb_disp_ncoord::get_erf_cn Interface Reference
Public Member Functions
pure subroutine ncoord_erf_driver (mol, cn, dcndr, dcndL, thr)
pure subroutine ncoord_erf (nat, at, xyz, cn, thr)
pure subroutine dncoord_erf (nat, at, xyz, cn, dcndr, thr)
Detailed Description
Definition at line 118 of file ncoord.f90.
Member Function/Subroutine Documentation
dncoord_erf()
pure subroutine xtb_disp_ncoord::get_erf_cn::dncoord_erf (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), intent(in), optional thr)
Definition at line 519 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: r,r2,rij(3)
    real(wp) :: rcovij
    real(wp) :: dtmp,tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0._wp
    dcndr = 0._wp
    do i = 1, nat
       do j = 1, i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(at(i))+rcov(at(j)))
          tmp = erf_count(kn,r,rcovij)
          dtmp = derf_count(kn,r,rcovij)
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
          dcndr(:,i,i)= dtmp*rij/r + dcndr(:,i,i)
          dcndr(:,j,j)=-dtmp*rij/r + dcndr(:,j,j)
          dcndr(:,i,j)= dtmp*rij/r
          dcndr(:,j,i)=-dtmp*rij/r
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::derf_count(), xtb_disp_ncoord::erf_count(), xtb_disp_ncoord::kn, and xtb_disp_ncoord::rcov.
ncoord_erf()
pure subroutine xtb_disp_ncoord::get_erf_cn::ncoord_erf (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
Definition at line 469 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, rr, r2, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn = 0.0_wp
    do i = 1, nat
       do j = 1, i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
 !        covalent distance in bohr
          rco=rcov(at(j)) + rcov(at(i))
 !        error function has an even better long range behavior
          tmp = erf_count(kn,r,rco)
          cn(i)=cn(i)+tmp
          cn(j)=cn(j)+tmp
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::erf_count(), xtb_disp_ncoord::kn, and xtb_disp_ncoord::rcov.
ncoord_erf_driver()
pure subroutine xtb_disp_ncoord::get_erf_cn::ncoord_erf_driver (type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:,:,:), intent(out), optional dcndr, real(wp), dimension(:,:,:), intent(out), optional dcndL, real(wp), intent(in), optional thr)
Parameters
[in] mol molecular structure information
[out] cn coordination number
[out] dcndr derivative of coordination number w.r.t. nuclear positions
[out] dcndl derivative of coordination number w.r.t. lattice vectors
[in] thr quadratic distance threshold for sum termination
Definition at line 204 of file ncoord.f90.
    use xtb_type_molecule
    implicit none
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out), optional :: dcndr(:,:,:)
    real(wp), intent(out), optional :: dcndL(:,:,:)
    real(wp), intent(in), optional :: thr
    real(wp) :: cn_thr
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    if (mol%npbc > 0) then
       if (present(dcndr).and.present(dcndl)) then
          call pbc_derfcoord(mol%n,mol%at,mol%xyz,mol%lattice,cn,dcndr,dcndl,cn_thr)
       else
          call pbc_erfcoord(mol%n,mol%at,mol%xyz,mol%lattice,cn,cn_thr)
       endif
    else
       if (present(dcndr)) then
          call dncoord_erf(mol%n,mol%at,mol%xyz,cn,dcndr,cn_thr)
       else
          call ncoord_erf(mol%n,mol%at,mol%xyz,cn,cn_thr)
       endif
    endif
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::dncoord_erf(), xtb_disp_ncoord::ncoord_erf(), xtb_disp_ncoord::pbc_derfcoord(), and xtb_disp_ncoord::pbc_erfcoord().
The documentation for this interface was generated from the following file:
src/disp/ncoord.f90