My Project: xtb_coulomb_klopmanohno::init Interface Reference
xtb_coulomb_klopmanohno::init Interface Reference
Private Member Functions
subroutine initfrommolecule (self, env, mol, gav, hardness, gExp, num, nshell, alpha, tolerance)
subroutine initklopmanohno (self, env, id, lattice, boundaryCond, gav, hardness, gExp, num, nshell, alpha, tolerance)
Detailed Description
Definition at line 77 of file klopmanohno.f90.
Member Function/Subroutine Documentation
initfrommolecule()
subroutine xtb_coulomb_klopmanohno::init::initfrommolecule (type(tklopmanohno), intent(out) self, type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, integer, intent(in) gav, real(wp), dimension(:, :), intent(in) hardness, real(wp), intent(in) gExp, integer, dimension(:), intent(in), optional num, integer, dimension(:), intent(in), optional nshell, real(wp), intent(in), optional alpha, real(wp), intent(in), optional tolerance) private
Parameters
[out] self Instance of the Coulomb evaluator
[in,out] env Calculation environment
[in] mol Molecular structure data
[in] gav Averaging function
[in] hardness Shell/Atomic hardnesses for each species
[in] gexp Generalized exponent
[in] num Atomic number for each id
[in] nshell Number of shell for each species
[in] alpha Convergence factor
[in] tolerance Tolerance for the Ewald sum
Definition at line 103 of file klopmanohno.f90.
    character(len=*), parameter :: source = 'type_coulomb_initFromMolecule'
    type(TKlopmanOhno), intent(out) :: self
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: gav
    real(wp), intent(in) :: hardness(:, :)
    real(wp), intent(in) :: gExp
    integer, intent(in), optional :: num(:)
    integer, intent(in), optional :: nshell(:)
    real(wp), intent(in), optional :: alpha
    real(wp), intent(in), optional :: tolerance
    logical :: exitRun
    call init(self, env, mol%id, mol%lattice, mol%boundaryCondition, gav, &
       & hardness, gexp, num, nshell, alpha, tolerance)
    call env%check(exitrun)
    if (exitrun) return
    call self%update(env, mol)
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Initializing internal state of evaluator failed", source)
    end if
initklopmanohno()
subroutine xtb_coulomb_klopmanohno::init::initklopmanohno (type(tklopmanohno), intent(out) self, type(tenvironment), intent(inout) env, integer, dimension(:), intent(in) id, real(wp), dimension(:, :), intent(in) lattice, integer, intent(in) boundaryCond, integer, intent(in) gav, real(wp), dimension(:, :), intent(in) hardness, real(wp), intent(in) gExp, integer, dimension(:), intent(in), optional num, integer, dimension(:), intent(in), optional nshell, real(wp), intent(in), optional alpha, real(wp), intent(in), optional tolerance) private
Parameters
[out] self Instance of the Coulomb evaluator
[in] id Identity of each atom
[in,out] env Calculation environment
[in] lattice Lattice parameters
[in] boundarycond Boundary conditions for this evaluator
[in] gav Averaging function
[in] hardness Shell/Atomic hardnesses for each species
[in] gexp Generalized exponent
[in] num Atomic number for each id
[in] nshell Number of shell for each species
[in] alpha Convergence factor
[in] tolerance Tolerance for the Ewald sum
Definition at line 156 of file klopmanohno.f90.
    character(len=*), parameter :: source = 'type_coulomb_initCoulomb'
    type(TKlopmanOhno), intent(out) :: self
    integer, intent(in) :: id(:)
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: lattice(:, :)
    integer, intent(in) :: boundaryCond
    integer, intent(in) :: gav
    real(wp), intent(in) :: hardness(:, :)
    real(wp), intent(in) :: gExp
    integer, intent(in), optional :: num(:)
    integer, intent(in), optional :: nshell(:)
    real(wp), intent(in), optional :: alpha
    real(wp), intent(in), optional :: tolerance
    logical :: exitRun
    integer :: ii
    self%boundaryCondition = boundarycond
    self%gExp = gexp
    self%natom = size(id, dim=1)
    call setupindextable(self%natom, self%itbl, id, num, nshell)
    if (present(num)) then
       allocate(self%hardness(size(hardness, dim=1), size(num)))
       do ii = 1, size(num)
          self%hardness(:, ii) = hardness(:, num(ii))
       end do
    else
       self%hardness = hardness
    end if
    select case(gav)
    case default
       call env%error("Unknown averaging function specified", source)
       return
    case(gamaverage%harmonic)
       self%gamAverage => harmonicaverage
    case(gamaverage%arithmetic)
       self%gamAverage => arithmeticaverage
    case(gamaverage%geometric)
       self%gamAverage => geometricaverage
    end select
    call setupboundaryconditions(self, env, lattice, alpha, tolerance)
References xtb_coulomb_klopmanohno::arithmeticaverage(), xtb_coulomb_klopmanohno::gamaverage, xtb_coulomb_klopmanohno::geometricaverage(), xtb_coulomb_klopmanohno::harmonicaverage(), xtb_type_coulomb::setupboundaryconditions(), and xtb_type_coulomb::setupindextable().
The documentation for this interface was generated from the following file:
src/coulomb/klopmanohno.f90