My Project: xtb_type_atomlist::assignment(=) Interface Reference
xtb_type_atomlist::assignment(=) Interface Reference
Private Member Functions
pure subroutine atomlist_assign_logicals (self, list)
pure subroutine atomlist_assign_integers (self, list)
pure subroutine atomlist_assign_string (self, string)
pure subroutine string_assign_atomlist (string, self)
pure subroutine list_assign_atomlist (list, self)
Detailed Description
Definition at line 83 of file atomlist.f90.
Member Function/Subroutine Documentation
atomlist_assign_integers()
pure subroutine xtb_type_atomlist::assignment(=)::atomlist_assign_integers (class(tatomlist), intent(inout) self, integer, dimension(:), intent(in) list) private
Definition at line 335 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    integer, intent(in) :: list(:)
    integer :: i
    call self%resize(maxval(list))
    do i = 1, size(list)
       self%list(list(i)) = .not.self%default
    enddo
References list().
atomlist_assign_logicals()
pure subroutine xtb_type_atomlist::assignment(=)::atomlist_assign_logicals (class(tatomlist), intent(inout) self, logical, dimension(:), intent(in) list) private
Definition at line 328 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    logical, intent(in) :: list(:)
    call self%resize(size(list))
    self%list = list
References list().
atomlist_assign_string()
pure subroutine xtb_type_atomlist::assignment(=)::atomlist_assign_string (class(tatomlist), intent(inout) self, character(len=*), intent(in) string) private
Definition at line 345 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    character(len=*), intent(in) :: string
    character(len=:), allocatable :: buffer
    integer, allocatable :: list(:)
    integer :: pos, last, n
    last = 0
    do
       pos = index(string(last+1:), self%delimiter)
       if (pos > 0) then
          call self%parse(string(last+1:last+pos-1))
          if (self%error) exit
          last = last+pos
       else
          call self%parse(string(last+1:))
          exit
       endif
    enddo
list_assign_atomlist()
pure subroutine xtb_type_atomlist::assignment(=)::list_assign_atomlist (integer, dimension(:), intent(out), allocatable list, class(tatomlist), intent(in) self) private
Definition at line 279 of file atomlist.f90.
    integer, allocatable, intent(out) :: list(:)
    class(TAtomList), intent(in) :: self
    integer :: i, j
    allocate(list(len(self)), source=0)
    j = 0
    do i = 1, size(self)
       if (self%list(i).neqv.self%default) then
          j = j+1
          list(j) = i
       endif
    enddo
References list().
string_assign_atomlist()
pure subroutine xtb_type_atomlist::assignment(=)::string_assign_atomlist (character(len=:), intent(out), allocatable string, class(tatomlist), intent(in) self) private
Definition at line 293 of file atomlist.f90.
    character(len=:), allocatable, intent(out) :: string
    class(TAtomList), intent(in) :: self
    character(len=10) :: buffer
    integer :: i, last
    logical :: state, first
    last = -1
    first = .true.
    state = .not.self%default
    do i = 1, size(self)
       if (state.eqv.self%list(i)) then
          state = .not.state
          if (state.eqv.self%default) then
             last = i
             write(buffer,'(i0)') i
             if (first) then
                first = .false.
                string = trim(buffer)
             else
                string = string // self%delimiter // trim(buffer)
             endif
          else
             if (i-1 .ne. last) then
                write(buffer,'(i0)') i-1
                string = string // self%skip // trim(buffer)
             endif
          endif
       endif
    enddo
    if (state.eqv.self%default .and.last.ne.size(self)) then
       write(buffer,'(i0)') size(self)
       string = string // self%skip // trim(buffer)
    endif
References true().
The documentation for this interface was generated from the following file:
src/type/atomlist.f90