My Project: xtb_disp_ncoord::get_gfn_cn Interface Reference
xtb_disp_ncoord::get_gfn_cn Interface Reference
Public Member Functions
pure subroutine ncoord_gfn_driver (mol, cn, dcndr, thr)
pure subroutine ncoord_gfn (nat, at, xyz, cn, thr)
pure subroutine dncoord_gfn (nat, at, xyz, cn, dcndr, thr)
Detailed Description
Definition at line 130 of file ncoord.f90.
Member Function/Subroutine Documentation
dncoord_gfn()
pure subroutine xtb_disp_ncoord::get_gfn_cn::dncoord_gfn (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), intent(in), optional thr)
Definition at line 900 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i, j, ia, ja
    real(wp) :: r, r2, rij(3)
    real(wp) :: rcovij
    real(wp) :: expterm1, expterm2
    real(wp) :: dtmp, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0._wp
    dcndr = 0._wp
    do i = 1, nat
       ia = at(i)
       do j = 1, i-1
          ja = at(j)
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(ia)+rcov(ja))
          expterm1=exp(-ka*(rcovij/r-1._wp))
          expterm2=exp(-kb*((rcovij+r_shift)/r-1._wp))
          tmp = 1._wp/(1._wp+expterm1)/(1._wp+expterm2)
          dtmp = (-ka*rcovij*expterm1) &
          &  /(r2*((expterm1+1._wp)**2))/(1._wp+expterm2) &
          &  + (-kb*(rcovij+r_shift)*expterm2) &
          &  /(r2*((expterm2+1._wp)**2))/(1._wp+expterm1)
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
          dcndr(:,i,i)=-dtmp*rij/r + dcndr(:,i,i)
          dcndr(:,j,j)= dtmp*rij/r + dcndr(:,j,j)
          dcndr(:,i,j)= dtmp*rij/r
          dcndr(:,j,i)=-dtmp*rij/r
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::ka, xtb_disp_ncoord::kb, xtb_disp_ncoord::r_shift, and xtb_disp_ncoord::rcov.
ncoord_gfn()
pure subroutine xtb_disp_ncoord::get_gfn_cn::ncoord_gfn (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
Definition at line 843 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i, j, ia, ja
    real(wp) :: r, r2, rij(3)
    real(wp) :: rcovij
    real(wp) :: expterm1, expterm2
    real(wp) :: tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0.0_wp
    do i = 1, nat
       ia = at(i)
       do j = 1, i-1
          ja = at(j)
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(ia)+rcov(ja))
          expterm1=exp_count(ka,r,rcovij)
          expterm2=exp_count(kb,r,rcovij+r_shift)
          tmp = expterm1*expterm2
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::exp_count(), xtb_disp_ncoord::ka, xtb_disp_ncoord::kb, xtb_disp_ncoord::r_shift, and xtb_disp_ncoord::rcov.
ncoord_gfn_driver()
pure subroutine xtb_disp_ncoord::get_gfn_cn::ncoord_gfn_driver (type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:,:,:), intent(out), optional dcndr, real(wp), intent(in), optional thr)
Parameters
[in] mol molecular structure information
[out] cn coordination number
[out] dcndr derivative of coordination number w.r.t. nuclear positions
[in] thr quadratic distance threshold for sum termination
Definition at line 171 of file ncoord.f90.
    use xtb_type_molecule
    implicit none
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out), optional :: dcndr(:,:,:)
    real(wp), intent(in), optional :: thr
    real(wp) :: cn_thr
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
 !   if (mol%npbc > 0) then
 !      if (present(dcndr).and.present(dcndL)) then
 !      else
 !      endif
 !   else
       if (present(dcndr)) then
          call dncoord_gfn(mol%n,mol%at,mol%xyz,cn,dcndr,cn_thr)
       else
          call ncoord_gfn(mol%n,mol%at,mol%xyz,cn,cn_thr)
       endif
 !   endif
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::dncoord_gfn(), and xtb_disp_ncoord::ncoord_gfn().
The documentation for this interface was generated from the following file:
src/disp/ncoord.f90