My Project: xtb_xtb_gfn1::initgfn1 Interface Reference
xtb_xtb_gfn1::initgfn1 Interface Reference
Private Member Functions
subroutine initdata (self)
subroutine initrepulsion (self)
subroutine initdispersion (self)
subroutine initcoulomb (self, nShell)
subroutine inithamiltonian (self, nShell)
subroutine inithalogen (self)
Detailed Description
Definition at line 34 of file gfn1.f90.
Member Function/Subroutine Documentation
initcoulomb()
subroutine xtb_xtb_gfn1::initgfn1::initcoulomb (type(tcoulombdata), intent(out) self, integer, dimension(:), intent(in) nShell) private
Parameters
[out] self Data instance
[in] nshell Number of shells
Definition at line 609 of file gfn1.f90.
    type(TCoulombData), intent(out) :: self
    integer, intent(in) :: nShell(:)
    self%gExp = gfn1globals%alphaj
    self%chemicalHardness = chemicalhardness
    self%thirdOrderAtom = thirdorderatom
    allocate(self%shellHardness(maxval(nshell), size(nshell)))
    call setgfn1shellhardness(self%shellHardness, nshell, angshell, &
       & chemicalhardness, shellhardness)
References xtb_xtb_gfn1::angshell, xtb_xtb_gfn1::chemicalhardness, xtb_xtb_gfn1::gfn1globals, xtb_xtb_gfn1::setgfn1shellhardness(), xtb_xtb_gfn1::shellhardness, and xtb_xtb_gfn1::thirdorderatom.
initdata()
subroutine xtb_xtb_gfn1::initgfn1::initdata (type(txtbdata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 563 of file gfn1.f90.
    type(TxTBData), intent(out) :: self
    self%name = 'GFN1-xTB'
    self%doi = '10.1021/acs.jctc.7b00118'
    self%level = 1
    self%nShell = nshell(:maxelem)
    self%ipeashift = gfn1globals%ipeashift * 0.1_wp
    call initgfn1(self%repulsion)
    call initgfn1(self%dispersion)
    call initgfn1(self%coulomb, self%nShell)
    call initgfn1(self%hamiltonian, self%nShell)
    allocate(self%halogen)
    call initgfn1(self%halogen)
References xtb_xtb_gfn1::gfn1globals, xtb_xtb_gfn1::maxelem, and xtb_xtb_gfn1::nshell.
initdispersion()
subroutine xtb_xtb_gfn1::initgfn1::initdispersion (type(tdispersiondata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 594 of file gfn1.f90.
    type(TDispersionData), intent(out) :: self
    self%dpar = gfn1disp
    self%g_a = 0.0_wp
    self%g_c = 0.0_wp
    self%wf  = 4.0_wp
    if (.not.allocated(reference_c6)) call copy_c6(reference_c6)
References xtb_disp_dftd3param::copy_c6(), xtb_xtb_gfn1::gfn1disp, and xtb_disp_dftd3param::reference_c6.
inithalogen()
subroutine xtb_xtb_gfn1::initgfn1::inithalogen (type(thalogendata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 874 of file gfn1.f90.
    type(THalogenData), intent(out) :: self
    call init(self, halogenradscale, halogendamping, halogenbond)
References xtb_xtb_gfn1::halogenbond, xtb_xtb_gfn1::halogendamping, and xtb_xtb_gfn1::halogenradscale.
inithamiltonian()
subroutine xtb_xtb_gfn1::initgfn1::inithamiltonian (type(thamiltoniandata), intent(out) self, integer, dimension(:), intent(in) nShell) private
Parameters
[out] self Data instance
[in] nshell Number of shells
Definition at line 627 of file gfn1.f90.
    type(THamiltonianData), intent(out) :: self
    integer, intent(in) :: nShell(:)
    integer :: mShell, nPrim, lAng
    integer :: iZp, iSh, jSh
    logical :: valShell(0:3)
    mshell = maxval(nshell)
    self%angShell = angshell(:mshell, :maxelem)
    do ish = 0, 3
       do jsh = 0, 3
          self%kScale(jsh, ish) = 0.5_wp * (gfn1globals%kShell(ish) &
             & + gfn1globals%kShell(jsh))
       end do
    end do
    self%kScale(0,1) = gfn1globals%ksp
    self%kScale(1,0) = gfn1globals%ksp
    self%kDiff = gfn1globals%kDiff
    do ish = 0, 3
       do jsh = 0, 3
          self%enScale(jsh, ish) = 0.005_wp * (gfn1globals%enshell(ish) &
             & + gfn1globals%enshell(jsh))
       end do
    end do
    self%enScale4 = gfn1globals%enscale4
    self%wExp = 0.0_wp
    self%electronegativity = paulingen(:maxelem)
    self%atomicRad = atomicrad(:maxelem)
    self%shellPoly = shellpoly(:, :maxelem)
    self%selfEnergy = selfenergy(:mshell, :maxelem)
    self%slaterExponent = slaterexponent(:mshell, :maxelem)
    self%principalQuantumNumber = principalquantumnumber(:mshell, :maxelem)
    allocate(self%kCN(mshell, maxelem))
    call setgfn1kcn(self%kCN, nshell, self%angShell, self%selfEnergy, &
       & gfn1globals%cnshell)
    allocate(self%valenceShell(mshell, maxelem))
    call generatevalenceshelldata(self%valenceShell, nshell, self%angShell)
    allocate(self%referenceOcc(mshell, maxelem))
    call setgfn1referenceocc(self, nshell)
    allocate(self%numberOfPrimitives(mshell, maxelem))
    call setgfn1numberofprimitives(self, nshell)
    allocate(self%pairParam(maxelem, maxelem))
    call setgfn1pairparam(self%pairParam)
    self%pairParam( 1, 1) = 0.96_wp
    self%pairParam( 5, 1) = 0.95_wp
    self%pairParam( 7, 1) = 1.04_wp
    self%pairParam(28, 1) = 0.90_wp
    self%pairParam(75, 1) = 0.80_wp
    self%pairParam(78, 1) = 0.80_wp
    self%pairParam( 1, 5) = 0.95_wp
    self%pairParam(15, 5) = 0.97_wp
    self%pairParam( 1, 7) = 1.04_wp
    self%pairParam(14, 7) = 1.01_wp
    self%pairParam( 7,14) = 1.01_wp
    self%pairParam( 5,15) = 0.97_wp
    self%pairParam( 1,28) = 0.90_wp
    self%pairParam( 1,75) = 0.80_wp
    self%pairParam( 1,78) = 0.80_wp
References xtb_xtb_gfn1::angshell, xtb_param_atomicrad::atomicrad, xtb_xtb_data::generatevalenceshelldata(), xtb_xtb_gfn1::gfn1globals, xtb_xtb_gfn1::maxelem, xtb_param_paulingen::paulingen, xtb_xtb_gfn1::principalquantumnumber, xtb_xtb_gfn1::selfenergy, xtb_xtb_gfn1::setgfn1kcn(), xtb_xtb_gfn1::setgfn1numberofprimitives(), xtb_xtb_gfn1::setgfn1pairparam(), xtb_xtb_gfn1::setgfn1referenceocc(), xtb_xtb_gfn1::shellpoly, and xtb_xtb_gfn1::slaterexponent.
initrepulsion()
subroutine xtb_xtb_gfn1::initgfn1::initrepulsion (type(trepulsiondata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 584 of file gfn1.f90.
    type(TRepulsionData), intent(out) :: self
    call init(self, kexp, kexplight, rexp, 0.0_wp, repalpha, repzeff)
References xtb_xtb_gfn1::kexp, xtb_xtb_gfn1::kexplight, xtb_xtb_gfn1::repalpha, xtb_xtb_gfn1::repzeff, and xtb_xtb_gfn1::rexp.
The documentation for this interface was generated from the following file:
src/xtb/gfn1.f90