My Project: xtb_disp_ncoord::get_d3_cn Interface Reference
xtb_disp_ncoord::get_d3_cn Interface Reference
Public Member Functions
pure subroutine ncoord_d3_driver (mol, cn, dcndr, thr)
pure subroutine ncoord_d3 (nat, at, xyz, cn, thr)
original D3 type coordination number from 2010
pure subroutine dncoord_d3 (nat, at, xyz, cn, dcndr, thr)
Detailed Description
Definition at line 113 of file ncoord.f90.
Member Function/Subroutine Documentation
dncoord_d3()
pure subroutine xtb_disp_ncoord::get_d3_cn::dncoord_d3 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), intent(in), optional thr)
Definition at line 331 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i, j
    real(wp) :: r, r2, rij(3)
    real(wp) :: rcovij
    real(wp) :: expterm
    real(wp) :: dtmp, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0._wp
    dcndr = 0._wp
    do i = 1, nat
       do j = 1, i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(at(i))+rcov(at(j)))
          tmp = exp_count(k1,r,rcovij)
          dtmp = dexp_count(k1,r,rcovij)
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
          dcndr(:,i,i)=-dtmp*rij/r + dcndr(:,i,i) ! FIXME
          dcndr(:,j,j)= dtmp*rij/r + dcndr(:,j,j) ! FIXME
          dcndr(:,i,j)= dtmp*rij/r
          dcndr(:,j,i)=-dtmp*rij/r
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::dexp_count(), xtb_disp_ncoord::exp_count(), xtb_disp_ncoord::k1, and xtb_disp_ncoord::rcov.
ncoord_d3()
pure subroutine xtb_disp_ncoord::get_d3_cn::ncoord_d3 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
original D3 type coordination number from 2010
Definition at line 280 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, tmp, r2
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn = 0.0_wp
    do i = 1, nat
       do j = 1, i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
 !        covalent distance in bohr
          rco=rcov(at(j)) + rcov(at(i))
 !        counting function exponential has a better long-range
 !        behavior than MHGs inverse damping
          tmp=exp_count(k1,r,rco)
          cn(i)=cn(i)+tmp
          cn(j)=cn(j)+tmp
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::exp_count(), xtb_disp_ncoord::k1, and xtb_disp_ncoord::rcov.
ncoord_d3_driver()
pure subroutine xtb_disp_ncoord::get_d3_cn::ncoord_d3_driver (type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:,:,:), intent(out), optional dcndr, real(wp), intent(in), optional thr)
Parameters
[in] mol molecular structure information
[out] cn coordination number
[out] dcndr derivative of coordination number w.r.t. nuclear positions
[in] thr quadratic distance threshold for sum termination
Definition at line 138 of file ncoord.f90.
    use xtb_type_molecule
    implicit none
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out), optional :: dcndr(:,:,:)
    real(wp), intent(in), optional :: thr
    real(wp) :: cn_thr
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
 !   if (mol%npbc > 0) then
 !      if (present(dcndr).and.present(dcndL)) then
 !      else
 !      endif
 !   else
       if (present(dcndr)) then
          call dncoord_d3(mol%n,mol%at,mol%xyz,cn,dcndr,cn_thr)
       else
          call ncoord_d3(mol%n,mol%at,mol%xyz,cn,cn_thr)
       endif
 !   endif
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::dncoord_d3(), and xtb_disp_ncoord::ncoord_d3().
The documentation for this interface was generated from the following file:
src/disp/ncoord.f90