My Project: xtb_xtb_gfn2::initgfn2 Interface Reference
xtb_xtb_gfn2::initgfn2 Interface Reference
Private Member Functions
subroutine initdata (self)
subroutine initrepulsion (self)
subroutine initdispersion (self)
subroutine initcoulomb (self, nShell)
subroutine initmultipole (self)
subroutine inithamiltonian (self, nShell)
Detailed Description
Definition at line 34 of file gfn2.f90.
Member Function/Subroutine Documentation
initcoulomb()
subroutine xtb_xtb_gfn2::initgfn2::initcoulomb (type(tcoulombdata), intent(out) self, integer, dimension(:), intent(in) nShell) private
Parameters
[out] self Data instance
[in] nshell Number of shells
Definition at line 777 of file gfn2.f90.
    type(TCoulombData), intent(out) :: self
    integer, intent(in) :: nShell(:)
    self%gExp = gfn2globals%alphaj
    self%chemicalHardness = chemicalhardness
    self%thirdOrderAtom = thirdorderatom
    allocate(self%thirdOrderShell(maxval(nshell), size(nshell)))
    call setgfn2thirdordershell(self%thirdOrderShell, nshell, angshell, &
       & thirdorderatom, gfn2globals%gam3shell)
    allocate(self%shellHardness(maxval(nshell), maxelem))
    call setgfn1shellhardness(self%shellHardness, nshell, angshell, &
       & chemicalhardness, shellhardness)
References xtb_xtb_gfn2::angshell, xtb_xtb_gfn2::chemicalhardness, xtb_xtb_gfn2::gfn2globals, xtb_xtb_gfn2::maxelem, xtb_xtb_gfn1::setgfn1shellhardness(), xtb_xtb_gfn2::setgfn2thirdordershell(), xtb_xtb_gfn2::shellhardness, and xtb_xtb_gfn2::thirdorderatom.
initdata()
subroutine xtb_xtb_gfn2::initgfn2::initdata (type(txtbdata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 731 of file gfn2.f90.
    type(TxTBData), intent(out) :: self
    self%name = 'GFN2-xTB'
    self%doi = '10.1021/acs.jctc.8b01176'
    self%level = 2
    self%nShell = nshell(:maxelem)
    self%ipeashift = gfn2globals%ipeashift * 0.1_wp
    call initgfn2(self%repulsion)
    call initgfn2(self%dispersion)
    call initgfn2(self%coulomb, self%nShell)
    allocate(self%multipole)
    call initgfn2(self%multipole)
    call initgfn2(self%hamiltonian, self%nShell)
References xtb_xtb_gfn2::gfn2globals, xtb_xtb_gfn2::maxelem, and xtb_xtb_gfn2::nshell.
initdispersion()
subroutine xtb_xtb_gfn2::initgfn2::initdispersion (type(tdispersiondata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 762 of file gfn2.f90.
    type(TDispersionData), intent(out) :: self
    self%dpar = gfn2disp
    self%g_a = 3.0_wp
    self%g_c = 2.0_wp
    self%wf  = 6.0_wp
    call newd4model(self%dispm,self%g_a, self%g_c, p_refq_gfn2xtb)
References xtb_xtb_gfn2::gfn2disp, and xtb_disp_dftd4::newd4model().
inithamiltonian()
subroutine xtb_xtb_gfn2::initgfn2::inithamiltonian (type(thamiltoniandata), intent(out) self, integer, dimension(:), intent(in) nShell) private
Parameters
[out] self Data instance
[in] nshell Number of shells
Definition at line 809 of file gfn2.f90.
    type(THamiltonianData), intent(out) :: self
    integer, intent(in) :: nShell(:)
    integer :: mShell, nPrim, lAng
    integer :: iZp, iSh, jSh
    logical :: valShell(0:3)
    mshell = maxval(nshell)
    self%angShell = angshell(:mshell, :maxelem)
    do ish = 0, 3
       do jsh = 0, 3
          self%kScale(jsh, ish) = 0.5_wp * (gfn2globals%kShell(ish) &
             & + gfn2globals%kShell(jsh))
       end do
    end do
    self%kScale(0,2) = gfn2globals%ksd
    self%kScale(2,0) = gfn2globals%ksd
    self%kScale(1,2) = gfn2globals%kpd
    self%kScale(2,1) = gfn2globals%kpd
    self%kDiff = gfn2globals%kDiff
    do ish = 0, 3
       do jsh = 0, 3
          self%enScale(jsh, ish) = 0.005_wp * (gfn2globals%enshell(ish) &
             & + gfn2globals%enshell(jsh))
       end do
    end do
    self%enScale4 = gfn2globals%enscale4
    self%wExp = 0.5_wp
    self%electronegativity = paulingen(:maxelem)
    self%atomicRad = atomicrad(:maxelem)
    self%shellPoly = shellpoly(:, :maxelem)
    self%selfEnergy = selfenergy(:mshell, :maxelem)
    self%slaterExponent = slaterexponent(:mshell, :maxelem)
    self%principalQuantumNumber = principalquantumnumber(:mshell, :maxelem)
    allocate(self%kCN(mshell, maxelem))
    call angtoshelldata(self%kCN, nshell, self%angShell, kcn)
    allocate(self%pairParam(maxelem, maxelem))
    self%pairParam = 1.0_wp
    allocate(self%valenceShell(mshell, maxelem))
    call generatevalenceshelldata(self%valenceShell, nshell, self%angShell)
    allocate(self%referenceOcc(mshell, maxelem))
    call setgfn2referenceocc(self, nshell)
    allocate(self%numberOfPrimitives(mshell, maxelem))
    call setgfn2numberofprimitives(self, nshell)
References xtb_xtb_gfn2::angshell, xtb_xtb_data::angtoshelldata(), xtb_param_atomicrad::atomicrad, xtb_xtb_data::generatevalenceshelldata(), xtb_xtb_gfn2::gfn2globals, xtb_xtb_gfn2::kcn, xtb_xtb_gfn2::maxelem, xtb_param_paulingen::paulingen, xtb_xtb_gfn2::principalquantumnumber, xtb_xtb_gfn2::selfenergy, xtb_xtb_gfn2::setgfn2numberofprimitives(), xtb_xtb_gfn2::setgfn2referenceocc(), xtb_xtb_gfn2::shellpoly, and xtb_xtb_gfn2::slaterexponent.
initmultipole()
subroutine xtb_xtb_gfn2::initgfn2::initmultipole (type(tmultipoledata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 798 of file gfn2.f90.
    type(TMultipoleData), intent(out) :: self
    call init(self, cnshift, cnexp, cnrmax, dipdamp, quaddamp, &
       & dipkernel, quadkernel)
References xtb_xtb_gfn2::cnexp, xtb_xtb_gfn2::cnrmax, xtb_xtb_gfn2::cnshift, xtb_xtb_gfn2::dipdamp, xtb_xtb_gfn2::dipkernel, xtb_xtb_gfn2::quaddamp, and xtb_xtb_gfn2::quadkernel.
initrepulsion()
subroutine xtb_xtb_gfn2::initgfn2::initrepulsion (type(trepulsiondata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 752 of file gfn2.f90.
    type(TRepulsionData), intent(out) :: self
    call init(self, kexp, kexplight, rexp, 0.0_wp, repalpha, repzeff)
References xtb_xtb_gfn2::kexp, xtb_xtb_gfn2::kexplight, xtb_xtb_gfn2::repalpha, xtb_xtb_gfn2::repzeff, and xtb_xtb_gfn2::rexp.
The documentation for this interface was generated from the following file:
src/xtb/gfn2.f90