My Project: xtb_type_molecule::init Interface Reference
xtb_type_molecule::init Interface Reference
Private Member Functions
subroutine initmolecule (mol, at, sym, xyz, chrg, uhf, lattice, pbc)
Constructor for the molecular structure type.
subroutine initmoleculesymbols (mol, sym, xyz, chrg, uhf, lattice, pbc)
Constructor for the molecular structure type.
subroutine initmoleculenumbers (mol, at, xyz, chrg, uhf, lattice, pbc)
Constructor for the molecular structure type.
Detailed Description
Definition at line 175 of file molecule.f90.
Member Function/Subroutine Documentation
initmolecule()
subroutine xtb_type_molecule::init::initmolecule (type(tmolecule), intent(out) mol, integer, dimension(:), intent(in) at, character(len=*), dimension(:), intent(in) sym, real(wp), dimension(:, :), intent(in) xyz, real(wp), intent(in), optional chrg, integer, intent(in), optional uhf, real(wp), dimension(3, 3), intent(in), optional lattice, logical, dimension(3), intent(in), optional pbc) private
Constructor for the molecular structure type.
Definition at line 196 of file molecule.f90.
    interface
       subroutine generate_wsc(mol,wsc)
          import :: tmolecule, tb_wsc
          type(TMolecule), intent(inout) :: mol
          type(tb_wsc),    intent(inout) :: wsc
       end subroutine generate_wsc
    end interface
    type(TMolecule), intent(out) :: mol
    integer, intent(in) :: at(:)
    character(len=*), intent(in) :: sym(:)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in), optional :: chrg
    integer, intent(in), optional :: uhf
    real(wp), intent(in), optional :: lattice(3, 3)
    logical, intent(in), optional :: pbc(3)
    integer, allocatable :: id(:)
    character(len=symbolLength), allocatable :: sTmp(:)
    integer :: nAt, nId, iAt, iId
    nat = min(size(at, dim=1), size(xyz, dim=2), size(sym, dim=1))
    call mol%allocate(nat)
    if (present(lattice)) then
       mol%lattice = lattice
    else
       mol%lattice = 0.0_wp
    end if
    if (present(pbc)) then
       mol%pbc = pbc
       mol%npbc = count(pbc)
       if (any(pbc)) then
          mol%boundaryCondition = boundarycondition%pbc3d
       else
          mol%boundaryCondition = boundarycondition%cluster
       end if
    else
       if (present(lattice)) then
          mol%boundaryCondition = boundarycondition%pbc3d
          mol%pbc = .true.
          mol%npbc = 3
       else
          mol%boundaryCondition = boundarycondition%cluster
          mol%pbc = .false.
          mol%npbc = 0
       end if
    end if
    call getidentity(mol%nId, mol%id, sym)
    mol%at(:) = at(:nat)
    mol%sym(:) = sym(:nat)
    mol%xyz(:, :) = xyz(:, :nat)
    if (present(chrg)) then
       mol%chrg = chrg
    else
       mol%chrg = 0
    end if
    if (present(uhf)) then
       mol%uhf = uhf
    else
       mol%uhf = 0
    end if
    call mol%set_nuclear_charge
    call mol%set_atomic_masses
    call mol%update
    call generate_wsc(mol, mol%wsc)
References xtb_mctc_boundaryconditions::boundarycondition, generate_wsc(), and true().
initmoleculenumbers()
subroutine xtb_type_molecule::init::initmoleculenumbers (type(tmolecule), intent(out) mol, integer, dimension(:), intent(in) at, real(wp), dimension(:, :), intent(in) xyz, real(wp), intent(in), optional chrg, integer, intent(in), optional uhf, real(wp), dimension(3, 3), intent(in), optional lattice, logical, dimension(3), intent(in), optional pbc) private
Constructor for the molecular structure type.
Definition at line 277 of file molecule.f90.
    type(TMolecule), intent(out) :: mol
    integer, intent(in) :: at(:)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in), optional :: chrg
    integer, intent(in), optional :: uhf
    real(wp), intent(in), optional :: lattice(3, 3)
    logical, intent(in), optional :: pbc(3)
    character(len=4), allocatable :: sym(:)
    integer :: nAt
    nat = min(size(at, dim=1), size(xyz, dim=2))
    allocate(sym(nat))
    sym(:) = tosymbol(at(:nat))
    call init(mol, at, sym, xyz, chrg, uhf, lattice, pbc)
References xtb_mctc_symbols::tosymbol().
initmoleculesymbols()
subroutine xtb_type_molecule::init::initmoleculesymbols (type(tmolecule), intent(out) mol, character(len=*), dimension(:), intent(in) sym, real(wp), dimension(:, :), intent(in) xyz, real(wp), intent(in), optional chrg, integer, intent(in), optional uhf, real(wp), dimension(3, 3), intent(in), optional lattice, logical, dimension(3), intent(in), optional pbc) private
Constructor for the molecular structure type.
Definition at line 300 of file molecule.f90.
    type(TMolecule), intent(out) :: mol
    character(len=*), intent(in) :: sym(:)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in), optional :: chrg
    integer, intent(in), optional :: uhf
    real(wp), intent(in), optional :: lattice(3, 3)
    logical, intent(in), optional :: pbc(3)
    integer, allocatable :: at(:)
    integer :: nAt
    nat = min(size(sym, dim=1), size(xyz, dim=2))
    allocate(at(nat))
    at(:) = tonumber(sym(:nat))
    call init(mol, at, sym, xyz, chrg, uhf, lattice, pbc)
References xtb_mctc_symbols::tonumber().
The documentation for this interface was generated from the following file:
src/type/molecule.f90