My Project: xtb_mctc_strings::value Interface Reference
xtb_mctc_strings::value Interface Reference
Generic operator for converting a number string to a number. Calling syntax is 'call value(numstring,number,ios)' where 'numstring' is a number string and 'number' is a real number or an integer (single or double precision).
Public Member Functions
pure subroutine value_dr (str, rnum, iostat)
Converts number string to a double precision real number.
pure subroutine value_sr (str, rnum, iostat)
Converts number string to a single precision real number.
pure subroutine value_di (str, inum, iostat)
Converts number string to a double precision integer value.
pure subroutine value_si (str, inum, iostat)
Converts number string to a single precision integer value.
Detailed Description
Generic operator for converting a number string to a number. Calling syntax is 'call value(numstring,number,ios)' where 'numstring' is a number string and 'number' is a real number or an integer (single or double precision).
Definition at line 51 of file mctc_strings.f90.
Member Function/Subroutine Documentation
value_di()
pure subroutine xtb_mctc_strings::value::value_di (character(len=*), intent(in) str, integer(ki8), intent(out) inum, integer, intent(out), optional iostat)
Converts number string to a double precision integer value.
Definition at line 270 of file mctc_strings.f90.
 character(len=*), intent(in) ::str
 integer(ki8), intent(out) :: inum
 real(kr8) :: rnum
 integer, intent(out), optional :: iostat
 integer :: ios
 call value_dr(str,rnum,ios)
 if (present(iostat)) iostat = ios
 if(abs(rnum)>huge(inum)) then
    if (present(iostat)) iostat = 15
    return
 end if
 inum=nint(rnum,ki8)
References xtb_mctc_strings::ki8, and xtb_mctc_strings::value_dr().
value_dr()
pure subroutine xtb_mctc_strings::value::value_dr (character(len=*), intent(in) str, real(kr8), intent(out) rnum, integer, intent(out), optional iostat)
Converts number string to a double precision real number.
Definition at line 225 of file mctc_strings.f90.
 character(len=*), intent(in) ::str
 real(kr8), intent(out) ::rnum
 integer, intent(out), optional :: iostat
 integer :: ilen,ipos,ios
 ilen=len_trim(str)
 ipos=scan(str,'Ee')
 if(.not.is_digit(str(ilen:ilen)) .and. ipos/=0) then
    if (present(iostat)) iostat=3
    return
 end if
 read(str,*,iostat=ios) rnum
 if (present(iostat)) iostat = ios
References xtb_mctc_strings::is_digit().
value_si()
pure subroutine xtb_mctc_strings::value::value_si (character(len=*), intent(in) str, integer(ki4), intent(out) inum, integer, intent(out), optional iostat)
Converts number string to a single precision integer value.
Definition at line 293 of file mctc_strings.f90.
 character(len=*), intent(in) ::str
 integer(ki4), intent(out) :: inum
 real(kr8) :: rnum
 integer, intent(out), optional :: iostat
 integer :: ios
 call value_dr(str,rnum,ios)
 if (present(iostat)) iostat = ios
 if(abs(rnum)>huge(inum)) then
    if (present(iostat)) iostat=15
    return
 end if
 inum=nint(rnum,ki4)
References xtb_mctc_strings::ki4, and xtb_mctc_strings::value_dr().
value_sr()
pure subroutine xtb_mctc_strings::value::value_sr (character(len=*), intent(in) str, real(kr4), intent(out) rnum, integer, intent(out), optional iostat)
Converts number string to a single precision real number.
Definition at line 247 of file mctc_strings.f90.
 character(len=*), intent(in) ::str
 real(kr4), intent(out) :: rnum
 real(kr8) :: rnumd
 integer, intent(out), optional :: iostat
 integer :: ios
 call value_dr(str,rnumd,ios)
 if (present(iostat)) iostat = ios
 if( abs(rnumd) > huge(rnum) ) then
    if (present(iostat)) iostat = 15
    return
 end if
 if( abs(rnumd) < tiny(rnum) ) rnum=0.0_kr4
 rnum=rnumd
References xtb_mctc_strings::value_dr().
The documentation for this interface was generated from the following file:
src/mctc/mctc_strings.f90