My Project: xtb_disp_dftd4::d4_gradient Interface Reference
xtb_disp_dftd4::d4_gradient Interface Reference
Public Member Functions
subroutine d4_full_gradient_neigh (mol, dispm, neighs, neighs3, neighlist, par, g_a, g_c, wf, cn, dcndr, dcndL, q, dqdr, dqdL, energy, gradient, sigma, e2, e3)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
subroutine d4_full_gradient_latp (mol, dispm, trans, par, g_a, g_c, wf, cutoff, cutoff3, cn, dcndr, dcndL, q, dqdr, dqdL, energy, gradient, sigma, e2, e3)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
subroutine d4_gradient_neigh (mol, dispm, neighs, neighlist, par, g_a, g_c, wf, cn, dcndr, dcndL, q, dqdr, dqdL, energy, gradient, sigma)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
subroutine d4_gradient_latp (mol, dispm, trans, par, g_a, g_c, wf, cutoff, cn, dcndr, dcndL, q, dqdr, dqdL, energy, gradient, sigma)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
Detailed Description
Definition at line 38 of file dftd4.F90.
Member Function/Subroutine Documentation
d4_full_gradient_latp()
subroutine xtb_disp_dftd4::d4_gradient::d4_full_gradient_latp (type(tmolecule), intent(in) mol, type(tdispersionmodel), intent(in) dispm, real(wp), dimension(:, :), intent(in) trans, type(dftd_parameter), intent(in) par, real(wp), intent(in) g_a, real(wp), intent(in) g_c, real(wp), intent(in) wf, real(wp), intent(in) cutoff, real(wp), intent(in) cutoff3, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), dimension(:), intent(in) q, real(wp), dimension(:, :, :), intent(in), optional dqdr, real(wp), dimension(:, :, :), intent(in), optional dqdL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma, real(wp), intent(out), optional e2, real(wp), intent(out), optional e3)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
Parameters
[in] mol Molecular Structure information.
[in] par Becke–Johnson damping parameters.
[in] trans Translation vectors
[in] g_a Charge scaling height.
[in] g_c Charge scaling steepness.
[in] wf Exponent for the Gaussian weighting.
[in] cutoff Cutoff for pairwise interactions
[in] cutoff3 Cutoff for threebody interactions
[in] cn Coordination number of every atom.
[in] dcndr Derivative of CN w.r.t. atomic coordinates.
[in] dcndl Derivative of CN w.r.t. strain deformations
[in] q Partial charge of every atom.
[in] dqdr Derivative of partial charges w.r.t. atomic coordinates.
[in] dqdl Derivative of partial charges w.r.t. strain deformations
[in,out] energy Dispersion energy.
[in,out] gradient Derivative of the dispersion energy w.r.t. atomic positions.
[in,out] sigma Stress tensor resulting from dispersion interactions.
Definition at line 1609 of file dftd4.F90.
    use xtb_type_molecule
    use xtb_type_neighbourlist
    use xtb_type_param
    type(TDispersionModel), intent(in) :: dispm
    type(TMolecule), intent(in) :: mol
    type(dftd_parameter), intent(in) :: par
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(in) :: g_a
    real(wp), intent(in) :: g_c
    real(wp), intent(in) :: wf
    real(wp), intent(in) :: cutoff
    real(wp), intent(in) :: cutoff3
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(in) :: q(:)
    real(wp), intent(in), optional :: dqdr(:, :, :)
    real(wp), intent(in), optional :: dqdL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    real(wp), intent(out), optional :: e2
    real(wp), intent(out), optional :: e3
    integer :: nat, max_ref
    real(wp), allocatable :: zetavec(:, :), zetadcn(:, :), zetadq(:, :)
    real(wp), allocatable :: zerovec(:, :), zerodcn(:, :), zerodq(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :), dc6dq(:, :)
    real(wp), allocatable :: energies(:), energies3(:), dEdcn(:), dEdq(:)
    nat = len(mol)
    max_ref = maxval(dispm%nref(mol%at))
    allocate(zetavec(max_ref, nat), zetadcn(max_ref, nat), zetadq(max_ref, nat), &
       &     zerovec(max_ref, nat), zerodcn(max_ref, nat), zerodq(max_ref, nat), &
       &     c6(nat, nat), dc6dcn(nat, nat), dc6dq(nat, nat), &
       &     energies(nat), energies3(nat), dedcn(nat), dedq(nat), source=0.0_wp)
    call weight_references(dispm, nat, mol%at, g_a, g_c, wf, q, cn, zeff, gam, &
       & zetavec, zerovec, zetadcn, zerodcn, zetadq)
    call get_atomic_c6(dispm, nat, mol%at, zetavec, zetadcn, zetadq, &
       & c6, dc6dcn, dc6dq)
    call disp_gradient_latp(mol, trans, cutoff, par, sqrtzr4r2, c6, dc6dcn, dc6dq, &
       &  energies, gradient, sigma, dedcn, dedq)
    if (present(e2)) e2 = sum(energies)
    if (par%s9 /= 0.0_wp) then
       call get_atomic_c6(dispm, nat, mol%at, zerovec, zerodcn, zerodq, &
          & c6, dc6dcn, dc6dq)
 #ifdef XTB_GPU
       call atm_gradient_latp_gpu(mol, trans, cutoff3, par, sqrtzr4r2, c6, dc6dcn, &
          & energies3, gradient, sigma, dedcn)
 #else
       call atm_gradient_latp(mol, trans, cutoff3, par, sqrtzr4r2, c6, dc6dcn, &
          & energies3, gradient, sigma, dedcn)
 #endif
    end if
    if (present(e3)) e3 = sum(energies3)
    call mctc_gemv(dcndr, dedcn, gradient, beta=1.0_wp)
    if (present(dqdr)) then
       call mctc_gemv(dqdr, dedq, gradient, beta=1.0_wp)
    end if
    call mctc_gemv(dcndl, dedcn, sigma, beta=1.0_wp)
    if (present(dqdl)) then
       call mctc_gemv(dqdl, dedq, sigma, beta=1.0_wp)
    end if
    energy = energy + sum(energies) + sum(energies3)
References xtb_disp_dftd4::atm_gradient_latp(), xtb_disp_dftd4::atm_gradient_latp_gpu(), xtb_disp_dftd4::disp_gradient_latp(), xtb_disp_dftd4::get_atomic_c6(), xtb_param_sqrtzr4r2::sqrtzr4r2, xtb_disp_dftd4::weight_references(), and xtb_disp_dftd4param::zeff.
d4_full_gradient_neigh()
subroutine xtb_disp_dftd4::d4_gradient::d4_full_gradient_neigh (type(tmolecule), intent(in) mol, type(tdispersionmodel), intent(in) dispm, integer, dimension(:), intent(in) neighs, integer, dimension(:), intent(in) neighs3, type(tneighbourlist), intent(in) neighlist, type(dftd_parameter), intent(in) par, real(wp), intent(in) g_a, real(wp), intent(in) g_c, real(wp), intent(in) wf, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), dimension(:), intent(in) q, real(wp), dimension(:, :, :), intent(in), optional dqdr, real(wp), dimension(:, :, :), intent(in), optional dqdL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma, real(wp), intent(out), optional e2, real(wp), intent(out), optional e3)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
Parameters
[in] mol Molecular Structure information.
[in] neighlist Static neighbourlist.
[in] par Becke–Johnson damping parameters.
[in] neighs Number of neighbours for each atom.
[in] neighs3 Number of neighbours for each atom.
[in] g_a Charge scaling height.
[in] g_c Charge scaling steepness.
[in] wf Exponent for the Gaussian weighting.
[in] cn Coordination number of every atom.
[in] dcndr Derivative of CN w.r.t. atomic coordinates.
[in] dcndl Derivative of CN w.r.t. strain deformations
[in] q Partial charge of every atom.
[in] dqdr Derivative of partial charges w.r.t. atomic coordinates.
[in] dqdl Derivative of partial charges w.r.t. strain deformations
[in,out] energy Dispersion energy.
[in,out] gradient Derivative of the dispersion energy w.r.t. atomic positions.
[in,out] sigma Stress tensor resulting from dispersion interactions.
Definition at line 1139 of file dftd4.F90.
    use xtb_type_molecule
    use xtb_type_neighbourlist
    use xtb_type_param
    type(TDispersionModel), intent(in) :: dispm
    type(TMolecule), intent(in) :: mol
    type(TNeighbourList), intent(in) :: neighlist
    type(dftd_parameter), intent(in) :: par
    integer, intent(in) :: neighs(:)
    integer, intent(in) :: neighs3(:)
    real(wp), intent(in) :: g_a
    real(wp), intent(in) :: g_c
    real(wp), intent(in) :: wf
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(in) :: q(:)
    real(wp), intent(in), optional :: dqdr(:, :, :)
    real(wp), intent(in), optional :: dqdL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    real(wp), intent(out), optional :: e2
    real(wp), intent(out), optional :: e3
    integer :: nat, max_ref
    real(wp), allocatable :: zetavec(:, :), zetadcn(:, :), zetadq(:, :)
    real(wp), allocatable :: zerovec(:, :), zerodcn(:, :), zerodq(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :), dc6dq(:, :)
    real(wp), allocatable :: energies(:), energies3(:), dEdcn(:), dEdq(:)
    nat = len(mol)
    max_ref = maxval(dispm%nref(mol%at))
    allocate(zetavec(max_ref, nat), zetadcn(max_ref, nat), zetadq(max_ref, nat), &
       &     zerovec(max_ref, nat), zerodcn(max_ref, nat), zerodq(max_ref, nat), &
       &     c6(nat, nat), dc6dcn(nat, nat), dc6dq(nat, nat), &
       &     energies(nat), energies3(nat), dedcn(nat), dedq(nat), source=0.0_wp)
    call weight_references(dispm, nat, mol%at, g_a, g_c, wf, q, cn, zeff, gam, &
       & zetavec, zerovec, zetadcn, zerodcn, zetadq)
    call get_atomic_c6(dispm, nat, mol%at, zetavec, zetadcn, zetadq, &
       & c6, dc6dcn, dc6dq)
    call disp_gradient_neigh(mol, neighs, neighlist, par, sqrtzr4r2, &
       & c6, dc6dcn, dc6dq, energies, gradient, sigma, dedcn, dedq)
    if (present(e2)) e2 = sum(energies)
    if (par%s9 /= 0.0_wp) then
       call get_atomic_c6(dispm, nat, mol%at, zerovec, zerodcn, zerodq, &
          & c6, dc6dcn, dc6dq)
       call atm_gradient_neigh(mol, neighs3, neighlist, par, sqrtzr4r2, c6, dc6dcn, &
          & energies3, gradient, sigma, dedcn)
    end if
    if (present(e3)) e3 = sum(energies3)
    call mctc_gemv(dcndr, dedcn, gradient, beta=1.0_wp)
    if (present(dqdr)) then
       call mctc_gemv(dqdr, dedq, gradient, beta=1.0_wp)
    end if
    call mctc_gemv(dcndl, dedcn, sigma, beta=1.0_wp)
    if (present(dqdl)) then
       call mctc_gemv(dqdl, dedq, sigma, beta=1.0_wp)
    end if
    energy = energy + sum(energies) + sum(energies3)
References xtb_disp_dftd4::atm_gradient_neigh(), xtb_disp_dftd4::disp_gradient_neigh(), xtb_disp_dftd4::get_atomic_c6(), xtb_param_sqrtzr4r2::sqrtzr4r2, xtb_disp_dftd4::weight_references(), and xtb_disp_dftd4param::zeff.
d4_gradient_latp()
subroutine xtb_disp_dftd4::d4_gradient::d4_gradient_latp (type(tmolecule), intent(in) mol, type(tdispersionmodel), intent(in) dispm, real(wp), dimension(:, :), intent(in) trans, type(dftd_parameter), intent(in) par, real(wp), intent(in) g_a, real(wp), intent(in) g_c, real(wp), intent(in) wf, real(wp), intent(in) cutoff, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), dimension(:), intent(in) q, real(wp), dimension(:, :, :), intent(in), optional dqdr, real(wp), dimension(:, :, :), intent(in), optional dqdL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
Parameters
[in] mol Molecular Structure information.
[in] par Becke–Johnson damping parameters.
[in] trans Translation vectors
[in] g_a Charge scaling height.
[in] g_c Charge scaling steepness.
[in] wf Exponent for the Gaussian weighting.
[in] cutoff Cutoff for pairwise interactions
[in] cn Coordination number of every atom.
[in] dcndr Derivative of CN w.r.t. atomic coordinates.
[in] dcndl Derivative of CN w.r.t. strain deformations
[in] q Partial charge of every atom.
[in] dqdr Derivative of partial charges w.r.t. atomic coordinates.
[in] dqdl Derivative of partial charges w.r.t. strain deformations
[in,out] energy Dispersion energy.
[in,out] gradient Derivative of the dispersion energy w.r.t. atomic positions.
[in,out] sigma Stress tensor resulting from dispersion interactions.
Definition at line 1724 of file dftd4.F90.
    use xtb_type_molecule
    use xtb_type_neighbourlist
    use xtb_type_param
    type(TDispersionModel), intent(in) :: dispm
    type(TMolecule), intent(in) :: mol
    type(dftd_parameter), intent(in) :: par
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(in) :: g_a
    real(wp), intent(in) :: g_c
    real(wp), intent(in) :: wf
    real(wp), intent(in) :: cutoff
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(in) :: q(:)
    real(wp), intent(in), optional :: dqdr(:, :, :)
    real(wp), intent(in), optional :: dqdL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    integer :: nat, max_ref
    real(wp), allocatable :: zetavec(:, :), zetadcn(:, :), zetadq(:, :)
    real(wp), allocatable :: zerovec(:, :), zerodcn(:, :), zerodq(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :), dc6dq(:, :)
    real(wp), allocatable :: energies(:), energies3(:), dEdcn(:), dEdq(:)
    nat = len(mol)
    max_ref = maxval(dispm%nref(mol%at))
    allocate(zetavec(max_ref, nat), zetadcn(max_ref, nat), zetadq(max_ref, nat), &
       &     zerovec(max_ref, nat), zerodcn(max_ref, nat), zerodq(max_ref, nat), &
       &     c6(nat, nat), dc6dcn(nat, nat), dc6dq(nat, nat), &
       &     energies(nat), dedcn(nat), dedq(nat), source=0.0_wp)
    call weight_references(dispm, nat, mol%at, g_a, g_c, wf, q, cn, zeff, gam, &
       & zetavec, zerovec, zetadcn, zerodcn, zetadq)
    call get_atomic_c6(dispm, nat, mol%at, zetavec, zetadcn, zetadq, &
       & c6, dc6dcn, dc6dq)
    call disp_gradient_latp(mol, trans, cutoff, par, sqrtzr4r2, c6, dc6dcn, dc6dq, &
       & energies, gradient, sigma, dedcn, dedq)
    call mctc_gemv(dcndr, dedcn, gradient, beta=1.0_wp)
    if (present(dqdr)) then
       call mctc_gemv(dqdr, dedq, gradient, beta=1.0_wp)
    end if
    call mctc_gemv(dcndl, dedcn, sigma, beta=1.0_wp)
    if (present(dqdl)) then
       call mctc_gemv(dqdl, dedq, sigma, beta=1.0_wp)
    end if
    energy = energy + sum(energies)
References xtb_disp_dftd4::disp_gradient_latp(), xtb_disp_dftd4::get_atomic_c6(), xtb_param_sqrtzr4r2::sqrtzr4r2, xtb_disp_dftd4::weight_references(), and xtb_disp_dftd4param::zeff.
d4_gradient_neigh()
subroutine xtb_disp_dftd4::d4_gradient::d4_gradient_neigh (type(tmolecule), intent(in) mol, type(tdispersionmodel), intent(in) dispm, integer, dimension(:), intent(in) neighs, type(tneighbourlist), intent(in) neighlist, type(dftd_parameter), intent(in) par, real(wp), intent(in) g_a, real(wp), intent(in) g_c, real(wp), intent(in) wf, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), dimension(:), intent(in) q, real(wp), dimension(:, :, :), intent(in), optional dqdr, real(wp), dimension(:, :, :), intent(in), optional dqdL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
Parameters
[in] mol Molecular Structure information.
[in] neighlist Static neighbourlist.
[in] par Becke–Johnson damping parameters.
[in] neighs Number of neighbours for each atom.
[in] g_a Charge scaling height.
[in] g_c Charge scaling steepness.
[in] wf Exponent for the Gaussian weighting.
[in] cn Coordination number of every atom.
[in] dcndr Derivative of CN w.r.t. atomic coordinates.
[in] dcndl Derivative of CN w.r.t. strain deformations
[in] q Partial charge of every atom.
[in] dqdr Derivative of partial charges w.r.t. atomic coordinates.
[in] dqdl Derivative of partial charges w.r.t. strain deformations
[in,out] energy Dispersion energy.
[in,out] gradient Derivative of the dispersion energy w.r.t. atomic positions.
[in,out] sigma Stress tensor resulting from dispersion interactions.
Definition at line 1249 of file dftd4.F90.
    use xtb_type_molecule
    use xtb_type_neighbourlist
    use xtb_type_param
    type(TDispersionModel), intent(in) :: dispm
    type(TMolecule), intent(in) :: mol
    type(TNeighbourList), intent(in) :: neighlist
    type(dftd_parameter), intent(in) :: par
    integer, intent(in) :: neighs(:)
    real(wp), intent(in) :: g_a
    real(wp), intent(in) :: g_c
    real(wp), intent(in) :: wf
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(in) :: q(:)
    real(wp), intent(in), optional :: dqdr(:, :, :)
    real(wp), intent(in), optional :: dqdL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    integer :: nat, max_ref
    real(wp), allocatable :: zetavec(:, :), zetadcn(:, :), zetadq(:, :)
    real(wp), allocatable :: zerovec(:, :), zerodcn(:, :), zerodq(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :), dc6dq(:, :)
    real(wp), allocatable :: energies(:), dEdcn(:), dEdq(:)
    nat = len(mol)
    max_ref = maxval(dispm%nref(mol%at))
    allocate(zetavec(max_ref, nat), zetadcn(max_ref, nat), zetadq(max_ref, nat), &
       &     zerovec(max_ref, nat), zerodcn(max_ref, nat), zerodq(max_ref, nat), &
       &     c6(nat, nat), dc6dcn(nat, nat), dc6dq(nat, nat), &
       &     energies(nat), dedcn(nat), dedq(nat), source=0.0_wp)
    call weight_references(dispm, nat, mol%at, g_a, g_c, wf, q, cn, zeff, gam, &
       & zetavec, zerovec, zetadcn, zerodcn, zetadq)
    call get_atomic_c6(dispm, nat, mol%at, zetavec, zetadcn, zetadq, &
       & c6, dc6dcn, dc6dq)
    call disp_gradient_neigh(mol, neighs, neighlist, par, sqrtzr4r2, &
       & c6, dc6dcn, dc6dq, energies, gradient, sigma, dedcn, dedq)
    call mctc_gemv(dcndr, dedcn, gradient, beta=1.0_wp)
    if (present(dqdr)) then
       call mctc_gemv(dqdr, dedq, gradient, beta=1.0_wp)
    end if
    call mctc_gemv(dcndl, dedcn, sigma, beta=1.0_wp)
    if (present(dqdl)) then
       call mctc_gemv(dqdl, dedq, sigma, beta=1.0_wp)
    end if
    energy = energy + sum(energies)
References xtb_disp_dftd4::disp_gradient_neigh(), xtb_disp_dftd4::get_atomic_c6(), xtb_param_sqrtzr4r2::sqrtzr4r2, xtb_disp_dftd4::weight_references(), and xtb_disp_dftd4param::zeff.
The documentation for this interface was generated from the following file:
src/disp/dftd4.F90