My Project: xtb_xtb_dispersion::init Interface Reference
xtb_xtb_dispersion::init Interface Reference
Private Member Functions
subroutine initdispersion (self, input, mol)
Detailed Description
Definition at line 61 of file dispersion.f90.
Member Function/Subroutine Documentation
initdispersion()
subroutine xtb_xtb_dispersion::init::initdispersion (type(txtbdispersion), intent(out) self, type(tdispersiondata), intent(in), target input, type(tmolecule), intent(in) mol) private
Definition at line 69 of file dispersion.f90.
    type(TxTBDispersion), intent(out) :: self
    type(TDispersionData), intent(in), target :: input
    type(TMolecule), intent(in) :: mol
    real(wp), allocatable :: cn(:)
    integer :: k, iat
    integer, allocatable :: itbl(:)
    self%g_a = input%g_a
    self%g_c = input%g_c
    self%wf = input%wf
    self%dispm => input%dispm
    call d4dim(self%dispm, mol%n, mol%at, self%ndim)
    allocate(self%gweight(self%ndim))
    allocate(self%refC6(self%ndim, self%ndim))
    allocate(self%dispmat(self%ndim, self%ndim))
    allocate(self%itbl(mol%n))
    allocate(cn(mol%n))
    k = 0
    do iat = 1, mol%n
       self%itbl(iat) = k
       k = k + self%dispm%nref(mol%at(iat))
    enddo
    call ncoord_d4(mol%n, mol%at, mol%xyz, cn, thr=1600.0_wp)
    call d4(self%dispm, mol%n, self%ndim, mol%at, self%wf, self%g_a, &
       & self%g_c, cn, self%gweight, self%refC6)
    call build_wdispmat(self%dispm, mol%n, self%ndim, mol%at, self%itbl, mol%xyz, &
       & input%dpar, self%refC6, self%gweight, self%dispmat)
References xtb_disp_dftd4::build_wdispmat(), xtb_disp_dftd4::d4(), xtb_disp_dftd4::d4dim(), and xtb_disp_ncoord::ncoord_d4().
The documentation for this interface was generated from the following file:
src/xtb/dispersion.f90