My Project: xtb_xtb_gfn0::initgfn0 Interface Reference
xtb_xtb_gfn0::initgfn0 Interface Reference
Private Member Functions
subroutine initdata (self)
subroutine initrepulsion (self)
subroutine initcoulomb (self, nShell)
subroutine inithamiltonian (self, nShell)
Detailed Description
Definition at line 32 of file gfn0.f90.
Member Function/Subroutine Documentation
initcoulomb()
subroutine xtb_xtb_gfn0::initgfn0::initcoulomb (type(tcoulombdata), intent(out) self, integer, dimension(:), intent(in) nShell) private
Parameters
[out] self Data instance
Definition at line 767 of file gfn0.f90.
    type(TCoulombData), intent(out) :: self
    integer, intent(in) :: nShell(:)
    self%electronegativity = eeqchi(1:maxelem)
    self%chemicalHardness = eeqgam(1:maxelem)
    self%kCN = eeqkcn(1:maxelem)
    self%chargeWidth = eeqalp(1:maxelem)
References xtb_xtb_gfn0::eeqalp, xtb_xtb_gfn0::eeqchi, xtb_xtb_gfn0::eeqgam, xtb_xtb_gfn0::eeqkcn, and xtb_xtb_gfn0::maxelem.
initdata()
subroutine xtb_xtb_gfn0::initgfn0::initdata (type(txtbdata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 740 of file gfn0.f90.
    type(TxTBData), intent(out) :: self
    self%name = 'GFN0-xTB'
    self%level = 0
    self%nShell = nshell(:maxelem)
    call initgfn0(self%repulsion)
    call initgfn0(self%coulomb, self%nShell)
    call initgfn0(self%hamiltonian, self%nShell)
References xtb_xtb_gfn0::maxelem, and xtb_xtb_gfn0::nshell.
inithamiltonian()
subroutine xtb_xtb_gfn0::initgfn0::inithamiltonian (type(thamiltoniandata), intent(out) self, integer, dimension(:), intent(in) nShell) private
Parameters
[out] self Data instance
Definition at line 783 of file gfn0.f90.
    type(THamiltonianData), intent(out) :: self
    integer, intent(in) :: nShell(:)
    integer :: mShell, nPrim, lAng
    integer :: iZp, iSh
    logical :: valShell(0:3)
    mshell = maxval(nshell)
    self%angShell = angshell(:mshell, :maxelem)
    self%kScale = 0.5_wp*(spread(gfn0globals%kShell,1,4)+spread(gfn0globals%kShell,2,4))
    self%kDiff = gfn0globals%kDiff
    self%enScale = 0.005_wp * (spread(gfn0globals%enshell, 1, 4) &
       & + spread(gfn0globals%enshell, 2, 4))
    self%enScale4 = gfn0globals%enscale4
    self%electronegativity = electronegativity(:maxelem)
    self%atomicRad = atomicrad(:maxelem)
    self%shellPoly = shellpoly(:, :maxelem)
    self%selfEnergy = selfenergy(:mshell, :maxelem)
    self%slaterExponent = slaterexponent(:mshell, :maxelem)
    self%principalQuantumNumber = principalquantumnumber(:mshell, :maxelem)
    self%kQAtom = kqatom(:maxelem)
    allocate(self%kCN(mshell, maxelem))
    call angtoshelldata(self%kCN, nshell, self%angShell, kcn)
    allocate(self%kQShell(mshell, maxelem))
    call angtoshelldata(self%kQShell, nshell, self%angShell, kqshell)
    allocate(self%pairParam(maxelem, maxelem))
    call setgfn0pairparam(self%pairParam)
    allocate(self%valenceShell(mshell, maxelem))
    call generatevalenceshelldata(self%valenceShell, nshell, self%angShell)
    allocate(self%referenceOcc(mshell, maxelem))
    call setgfn2referenceocc(self, nshell)
    allocate(self%numberOfPrimitives(mshell, maxelem))
    call setgfn0numberofprimitives(self, nshell)
References xtb_xtb_gfn0::angshell, xtb_xtb_data::angtoshelldata(), xtb_param_atomicrad::atomicrad, xtb_xtb_gfn0::electronegativity, xtb_xtb_data::generatevalenceshelldata(), xtb_xtb_gfn0::gfn0globals, xtb_xtb_gfn0::kcn, xtb_xtb_gfn0::kqatom, xtb_xtb_gfn0::kqshell, xtb_xtb_gfn0::maxelem, xtb_xtb_gfn0::principalquantumnumber, xtb_xtb_gfn0::selfenergy, xtb_xtb_gfn0::setgfn0numberofprimitives(), xtb_xtb_gfn0::setgfn0pairparam(), xtb_xtb_gfn2::setgfn2referenceocc(), xtb_xtb_gfn0::shellpoly, and xtb_xtb_gfn0::slaterexponent.
initrepulsion()
subroutine xtb_xtb_gfn0::initgfn0::initrepulsion (type(trepulsiondata), intent(out) self) private
Parameters
[out] self Data instance
Definition at line 756 of file gfn0.f90.
    type(TRepulsionData), intent(out) :: self
    call init(self, kexp, kexplight, rexp, 0.0_wp, repalpha, repzeff, &
       & electronegativity)
References xtb_xtb_gfn0::electronegativity, xtb_xtb_gfn0::kexp, xtb_xtb_gfn0::kexplight, xtb_xtb_gfn0::repalpha, xtb_xtb_gfn0::repzeff, and xtb_xtb_gfn0::rexp.
The documentation for this interface was generated from the following file:
src/xtb/gfn0.f90