My Project: xtb_disp_dftd3::d3_gradient Interface Reference
xtb_disp_dftd3::d3_gradient Interface Reference
Private Member Functions
subroutine d3_full_gradient_neigh (mol, neighs, neighs3, neighlist, par, weighting_factor, cn, dcndr, dcndL, energy, gradient, sigma, e2, e3)
subroutine d3_full_gradient_latp (mol, trans, par, weighting_factor, cutoff, cutoff3, cn, dcndr, dcndL, energy, gradient, sigma, e2, e3)
subroutine d3_gradient_neigh (mol, neighs, neighlist, par, weighting_factor, cn, dcndr, dcndL, energy, gradient, sigma)
subroutine d3_gradient_latp (mol, trans, par, weighting_factor, cutoff, cn, dcndr, dcndL, energy, gradient, sigma)
Detailed Description
Definition at line 33 of file dftd3.f90.
Member Function/Subroutine Documentation
d3_full_gradient_latp()
subroutine xtb_disp_dftd3::d3_gradient::d3_full_gradient_latp (type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) trans, type(dftd_parameter), intent(in) par, real(wp), intent(in) weighting_factor, real(wp), intent(in) cutoff, real(wp), intent(in) cutoff3, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma, real(wp), intent(out), optional e2, real(wp), intent(out), optional e3) private
Parameters
[in] mol Molecular structure data
[in] par Damping parameters
Definition at line 161 of file dftd3.f90.
    type(TMolecule), intent(in) :: mol
    type(dftd_parameter), intent(in) :: par
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(in) :: weighting_factor
    real(wp), intent(in) :: cutoff
    real(wp), intent(in) :: cutoff3
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    real(wp), intent(out), optional :: e2
    real(wp), intent(out), optional :: e3
    integer :: nat, max_ref
    real(wp), allocatable :: gw(:, :), dgwdcn(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :)
    real(wp), allocatable :: energies(:), energies3(:), dEdcn(:)
    nat = len(mol)
    max_ref = maxval(number_of_references(mol%at))
    allocate(gw(max_ref, nat), dgwdcn(max_ref, nat), c6(nat, nat), &
       & dc6dcn(nat, nat), energies(nat), energies3(nat), &
       & dedcn(nat), source=0.0_wp)
    call weight_references(nat, mol%at, weighting_factor, cn, gw, dgwdcn)
    call get_atomic_c6(nat, mol%at, gw, dgwdcn, c6, dc6dcn)
    call disp_gradient_latp(mol, trans, cutoff, par, sqrtzr4r2, c6, dc6dcn, &
       &  energies, gradient, sigma, dedcn)
    if (present(e2)) e2 = sum(energies)
    if (par%s9 /= 0.0_wp) then
       call atm_gradient_latp(mol, trans, cutoff3, par, sqrtzr4r2, c6, dc6dcn, &
          &  energies3, gradient, sigma, dedcn)
    end if
    if (present(e3)) e3 = sum(energies3)
    call contract(dcndr, dedcn, gradient, beta=1.0_wp)
    call contract(dcndl, dedcn, sigma, beta=1.0_wp)
    energy = energy + sum(energies) + sum(energies3)
References xtb_disp_dftd3::atm_gradient_latp(), xtb_disp_dftd3::disp_gradient_latp(), xtb_disp_dftd3::get_atomic_c6(), xtb_disp_dftd3param::number_of_references, xtb_param_sqrtzr4r2::sqrtzr4r2, and xtb_disp_dftd3::weight_references().
d3_full_gradient_neigh()
subroutine xtb_disp_dftd3::d3_gradient::d3_full_gradient_neigh (type(tmolecule), intent(in) mol, integer, dimension(:), intent(in) neighs, integer, dimension(:), intent(in) neighs3, type(tneighbourlist), intent(in) neighlist, type(dftd_parameter), intent(in) par, real(wp), intent(in) weighting_factor, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma, real(wp), intent(out), optional e2, real(wp), intent(out), optional e3) private
Parameters
[in] mol Molecular structure data
[in] neighlist Neighbour list
[in] par Damping parameters
Definition at line 483 of file dftd3.f90.
    type(TMolecule), intent(in) :: mol
    type(TNeighbourList), intent(in) :: neighlist
    type(dftd_parameter), intent(in) :: par
    integer, intent(in) :: neighs(:)
    integer, intent(in) :: neighs3(:)
    real(wp), intent(in) :: weighting_factor
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    real(wp), intent(out), optional :: e2
    real(wp), intent(out), optional :: e3
    integer :: nat, max_ref
    real(wp), allocatable :: gw(:, :), dgwdcn(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :)
    real(wp), allocatable :: energies(:), energies3(:), dEdcn(:)
    nat = len(mol)
    max_ref = maxval(number_of_references(mol%at))
    allocate(gw(max_ref, nat), dgwdcn(max_ref, nat), c6(nat, nat), &
       & dc6dcn(nat, nat), energies(nat), energies3(nat), &
       & dedcn(nat), source=0.0_wp)
    call weight_references(nat, mol%at, weighting_factor, cn, gw, dgwdcn)
    call get_atomic_c6(nat, mol%at, gw, dgwdcn, c6, dc6dcn)
    call disp_gradient_neigh(mol, neighs, neighlist, par, sqrtzr4r2, c6, dc6dcn, &
       &  energies, gradient, sigma, dedcn)
    if (present(e2)) e2 = sum(energies)
    if (par%s9 /= 0.0_wp) then
       call atm_gradient_neigh(mol, neighs, neighlist, par, sqrtzr4r2, c6, dc6dcn, &
          & energies3, gradient, sigma, dedcn)
    end if
    if (present(e3)) e3 = sum(energies3)
    call contract(dcndr, dedcn, gradient, beta=1.0_wp)
    call contract(dcndl, dedcn, sigma, beta=1.0_wp)
    energy = energy + sum(energies) + sum(energies3)
References xtb_disp_dftd3::atm_gradient_neigh(), xtb_disp_dftd3::disp_gradient_neigh(), xtb_disp_dftd3::get_atomic_c6(), xtb_disp_dftd3param::number_of_references, xtb_param_sqrtzr4r2::sqrtzr4r2, and xtb_disp_dftd3::weight_references().
d3_gradient_latp()
subroutine xtb_disp_dftd3::d3_gradient::d3_gradient_latp (type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) trans, type(dftd_parameter), intent(in) par, real(wp), intent(in) weighting_factor, real(wp), intent(in) cutoff, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma) private
Parameters
[in] mol Molecular structure data
[in] par Damping parameters
Definition at line 218 of file dftd3.f90.
    type(TMolecule), intent(in) :: mol
    type(dftd_parameter), intent(in) :: par
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(in) :: weighting_factor
    real(wp), intent(in) :: cutoff
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    integer :: nat, max_ref
    real(wp), allocatable :: gw(:, :), dgwdcn(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :)
    real(wp), allocatable :: energies(:), dEdcn(:)
    nat = len(mol)
    max_ref = maxval(number_of_references(mol%at))
    allocate(gw(max_ref, nat), dgwdcn(max_ref, nat), c6(nat, nat), &
       &     dc6dcn(nat, nat), energies(nat), dedcn(nat), source=0.0_wp)
    call weight_references(nat, mol%at, weighting_factor, cn, gw, dgwdcn)
    call get_atomic_c6(nat, mol%at, gw, dgwdcn, c6, dc6dcn)
    call disp_gradient_latp(mol, trans, cutoff, par, sqrtzr4r2, c6, dc6dcn, &
       &  energies, gradient, sigma, dedcn)
    call contract(dcndr, dedcn, gradient, beta=1.0_wp)
    call contract(dcndl, dedcn, sigma, beta=1.0_wp)
    energy = energy + sum(energies)
References xtb_disp_dftd3::disp_gradient_latp(), xtb_disp_dftd3::get_atomic_c6(), xtb_disp_dftd3param::number_of_references, xtb_param_sqrtzr4r2::sqrtzr4r2, and xtb_disp_dftd3::weight_references().
d3_gradient_neigh()
subroutine xtb_disp_dftd3::d3_gradient::d3_gradient_neigh (type(tmolecule), intent(in) mol, integer, dimension(:), intent(in) neighs, type(tneighbourlist), intent(in) neighlist, type(dftd_parameter), intent(in) par, real(wp), intent(in) weighting_factor, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma) private
Parameters
[in] mol Molecular structure data
[in] neighlist Neighbour list
[in] par Damping parameters
Definition at line 542 of file dftd3.f90.
    type(TMolecule), intent(in) :: mol
    type(TNeighbourList), intent(in) :: neighlist
    type(dftd_parameter), intent(in) :: par
    integer, intent(in) :: neighs(:)
    real(wp), intent(in) :: weighting_factor
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    integer :: nat, max_ref
    real(wp), allocatable :: gw(:, :), dgwdcn(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :)
    real(wp), allocatable :: energies(:), dEdcn(:)
    nat = len(mol)
    max_ref = maxval(number_of_references(mol%at))
    allocate(gw(max_ref, nat), dgwdcn(max_ref, nat), c6(nat, nat), &
       &     dc6dcn(nat, nat), energies(nat), dedcn(nat), source=0.0_wp)
    call weight_references(nat, mol%at, weighting_factor, cn, gw, dgwdcn)
    call get_atomic_c6(nat, mol%at, gw, dgwdcn, c6, dc6dcn)
    call disp_gradient_neigh(mol, neighs, neighlist, par, sqrtzr4r2, c6, dc6dcn, &
       &  energies, gradient, sigma, dedcn)
    call contract(dcndr, dedcn, gradient, beta=1.0_wp)
    call contract(dcndl, dedcn, sigma, beta=1.0_wp)
    energy = energy + sum(energies)
References xtb_disp_dftd3::disp_gradient_neigh(), xtb_disp_dftd3::get_atomic_c6(), xtb_disp_dftd3param::number_of_references, xtb_param_sqrtzr4r2::sqrtzr4r2, and xtb_disp_dftd3::weight_references().
The documentation for this interface was generated from the following file:
src/disp/dftd3.f90