My Project: xtb_solv_model::init Interface Reference
xtb_solv_model::init Interface Reference
Initialize solvation model from input.
Private Member Functions
subroutine initsolvmodel (self, env, input, level)
Initialize solvation model from input.
Detailed Description
Initialize solvation model from input.
Definition at line 84 of file model.f90.
Member Function/Subroutine Documentation
initsolvmodel()
subroutine xtb_solv_model::init::initsolvmodel (type(tsolvmodel), intent(out) self, type(tenvironment), intent(inout) env, type(tsolvinput), intent(in) input, integer, intent(in) level) private
Initialize solvation model from input.
Parameters
[in,out] env Computation environment
[out] self Data structure
[in] input Input data
[in] level Method level for solvation model
Definition at line 162 of file model.f90.
    character(len=*), parameter :: source = 'solv_model_initSolvModel'
    type(TEnvironment), intent(inout) :: env
    type(TSolvModel), intent(out) :: self
    type(TSolvInput), intent(in) :: input
    integer, intent(in) :: level
    character(len=:), allocatable :: solvent
    logical :: exist
    self%TSolvInput = input
    call normalizesolventname(solvent, input%solvent)
    if (input%alpb) then
       call getparamfile(env, solvent, 'alpb', level, self%paramFile)
    end if
    if (.not.allocated(self%paramFile)) then
       call getparamfile(env, solvent, 'gbsa', level, self%paramFile)
    end if
    if (allocated(self%paramFile)) then
       call readparamfile(self, env)
    else
       call loadinternalparam(self, env, solvent, level)
    end if
    self%freeEnergyShift = self%freeEnergyShift + getstateshift(self%state, &
       & self%temperature, self%density, self%molarMass)
References xtb_solv_model::getparamfile(), xtb_solv_state::getstateshift(), xtb_solv_model::loadinternalparam(), xtb_solv_model::normalizesolventname(), and xtb_solv_model::readparamfile().
The documentation for this interface was generated from the following file:
src/solv/model.f90