My Project: xtb_disp_dftd3::d3_atm_gradient Interface Reference
xtb_disp_dftd3::d3_atm_gradient Interface Reference
Private Member Functions
subroutine d3_atm_gradient_neigh (mol, neighs, neighlist, par, weighting_factor, cn, dcndr, dcndL, energy, gradient, sigma)
subroutine d3_atm_gradient_latp (mol, trans, par, weighting_factor, cutoff, cn, dcndr, dcndL, energy, gradient, sigma)
Detailed Description
Definition at line 41 of file dftd3.f90.
Member Function/Subroutine Documentation
d3_atm_gradient_latp()
subroutine xtb_disp_dftd3::d3_atm_gradient::d3_atm_gradient_latp (type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) trans, type(dftd_parameter), intent(in) par, real(wp), intent(in) weighting_factor, real(wp), intent(in) cutoff, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma) private
Parameters
[in] mol Molecular structure data
[in] par Damping parameters
Definition at line 346 of file dftd3.f90.
    type(TMolecule), intent(in) :: mol
    type(dftd_parameter), intent(in) :: par
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(in) :: weighting_factor
    real(wp), intent(in) :: cutoff
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    integer :: nat, max_ref
    real(wp), allocatable :: gw(:, :), dgwdcn(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :)
    real(wp), allocatable :: energies(:), dEdcn(:)
    nat = len(mol)
    max_ref = maxval(number_of_references(mol%at))
    allocate(gw(max_ref, nat), dgwdcn(max_ref, nat), c6(nat, nat), &
       &     dc6dcn(nat, nat), energies(nat), dedcn(nat), source=0.0_wp)
    call weight_references(nat, mol%at, weighting_factor, cn, gw, dgwdcn)
    call get_atomic_c6(nat, mol%at, gw, dgwdcn, c6, dc6dcn)
    call atm_gradient_latp(mol, trans, cutoff, par, sqrtzr4r2, c6, dc6dcn, &
       &  energies, gradient, sigma, dedcn)
    call contract(dcndr, dedcn, gradient, beta=1.0_wp)
    call contract(dcndl, dedcn, sigma, beta=1.0_wp)
    energy = energy + sum(energies)
References xtb_disp_dftd3::atm_gradient_latp(), xtb_disp_dftd3::get_atomic_c6(), xtb_disp_dftd3param::number_of_references, xtb_param_sqrtzr4r2::sqrtzr4r2, and xtb_disp_dftd3::weight_references().
d3_atm_gradient_neigh()
subroutine xtb_disp_dftd3::d3_atm_gradient::d3_atm_gradient_neigh (type(tmolecule), intent(in) mol, integer, dimension(:), intent(in) neighs, type(tneighbourlist), intent(in) neighlist, type(dftd_parameter), intent(in) par, real(wp), intent(in) weighting_factor, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma) private
Parameters
[in] mol Molecular structure data
[in] neighlist Neighbour list
[in] par Damping parameters
Definition at line 669 of file dftd3.f90.
    type(TMolecule), intent(in) :: mol
    type(TNeighbourList), intent(in) :: neighlist
    type(dftd_parameter), intent(in) :: par
    integer, intent(in) :: neighs(:)
    real(wp), intent(in) :: weighting_factor
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    integer :: nat, max_ref
    integer :: iat, jat, ati, atj, ij, img
    real(wp) :: r4r2ij, r0, rij(3), r2, t6, t8, t10, d6, d8, d10
    real(wp) :: dE, dG(3), dS(3, 3), disp, ddisp
    real(wp), allocatable :: gw(:, :), dgwdcn(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :)
    real(wp), allocatable :: energies(:), dEdcn(:)
    nat = len(mol)
    max_ref = maxval(number_of_references(mol%at))
    allocate(gw(max_ref, nat), dgwdcn(max_ref, nat), c6(nat, nat), &
       &     dc6dcn(nat, nat), energies(nat), dedcn(nat), source=0.0_wp)
    call weight_references(nat, mol%at, weighting_factor, cn, gw, dgwdcn)
    call get_atomic_c6(nat, mol%at, gw, dgwdcn, c6, dc6dcn)
    call atm_gradient_neigh(mol, neighs, neighlist, par, sqrtzr4r2, c6, dc6dcn, &
       & energies, gradient, sigma, dedcn)
    call contract(dcndr, dedcn, gradient, beta=1.0_wp)
    call contract(dcndl, dedcn, sigma, beta=1.0_wp)
    energy = energy + sum(energies)
References xtb_disp_dftd3::atm_gradient_neigh(), xtb_disp_dftd3::get_atomic_c6(), xtb_disp_dftd3param::number_of_references, xtb_param_sqrtzr4r2::sqrtzr4r2, and xtb_disp_dftd3::weight_references().
The documentation for this interface was generated from the following file:
src/disp/dftd3.f90