My Project: xtb_sphereparam::get_sphere_radius Interface Reference
xtb_sphereparam::get_sphere_radius Interface Reference
Public Member Functions
subroutine get_sphere_radius_list (nat, at, xyz, nlist, list, center, radius, do_trafo)
subroutine get_sphere_radius_fragment (nat, at, xyz, center, fragment, radius, do_trafo)
subroutine get_sphere_radius_all (nat, at, xyz, center, radius, do_trafo)
Detailed Description
Definition at line 66 of file sphereparam.f90.
Member Function/Subroutine Documentation
get_sphere_radius_all()
subroutine xtb_sphereparam::get_sphere_radius::get_sphere_radius_all (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3), intent(out) center, real(wp), intent(out) radius, logical, intent(in), optional do_trafo)
Definition at line 289 of file sphereparam.f90.
    use xtb_axis, only : axis3
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: center(3)
    real(wp),intent(out) :: radius
    logical, intent(in)  :: do_trafo
    integer  :: i,j
    real(wp) :: max_distance,distance,dum(3)
    real(wp),allocatable :: coord(:,:)
    logical  :: trafo
    optional :: do_trafo
    center = 0.0_wp
    if (present(do_trafo)) then
       trafo = do_trafo
    else
       trafo = .false.
    endif
    if (trafo) then
       allocate( coord(3,nat), source = 0.0_wp )
       call axis3(0,nat,at,xyz,coord,dum)
    else
       allocate( coord(3,nat), source = xyz )
    endif
    max_distance = 0.0_wp ! ~equals diameter of sphere
    do i = 1, nat
       do j = 1, i-1
          distance = sqrt(sum((coord(:,j)-coord(:,i))**2))
          max_distance = max(max_distance,distance)
       enddo
    enddo
    select case(spherepot_type)
    case(p_type_polynomial)
       radius = (0.5_wp/0.7_wp * max_distance) * sphere_autoscale
    case(p_type_logfermi)
       radius = (0.5_wp * max_distance + sphere_shift) * sphere_autoscale
    end select
References xtb_axis::axis3(), xtb_sphereparam::p_type_logfermi, xtb_sphereparam::p_type_polynomial, xtb_sphereparam::sphere_autoscale, xtb_sphereparam::sphere_shift, and xtb_sphereparam::spherepot_type.
get_sphere_radius_fragment()
subroutine xtb_sphereparam::get_sphere_radius::get_sphere_radius_fragment (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3), intent(out) center, integer, intent(in) fragment, real(wp), intent(out) radius, logical, intent(in), optional do_trafo)
Definition at line 238 of file sphereparam.f90.
    use xtb_axis, only : axis3
    use xtb_splitparam
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: fragment
    real(wp),intent(out) :: center(3)
    real(wp),intent(out) :: radius
    logical, intent(in)  :: do_trafo
    integer  :: i,j
    real(wp) :: max_distance,distance,dum(3)
    real(wp),allocatable :: coord(:,:)
    logical  :: trafo
    optional :: do_trafo
    center = 0.0_wp
    if (present(do_trafo)) then
       trafo = do_trafo
    else
       trafo = .false.
    endif
    if (trafo) then
       allocate( coord(3,nat), source = 0.0_wp )
       call axis3(0,nat,at,xyz,coord,dum)
    else
       allocate( coord(3,nat), source = xyz )
    endif
    max_distance = 0.0_wp ! ~equals diameter of sphere
    do i = 1, nat
       do j = 1, i-1
          if (splitlist(i).ne.fragment.or.fragment.ne.splitlist(j)) cycle
          distance = sqrt(sum((coord(:,j)-coord(:,i))**2))
          max_distance = max(max_distance,distance)
       enddo
    enddo
    select case(spherepot_type)
    case(p_type_polynomial)
       radius = (0.5_wp/0.7_wp * max_distance) * sphere_autoscale
    case(p_type_logfermi)
       radius = (0.5_wp * max_distance + sphere_shift) * sphere_autoscale
    end select
References xtb_axis::axis3(), xtb_sphereparam::p_type_logfermi, xtb_sphereparam::p_type_polynomial, xtb_sphereparam::sphere_autoscale, xtb_sphereparam::sphere_shift, xtb_sphereparam::spherepot_type, and xtb_splitparam::splitlist.
get_sphere_radius_list()
subroutine xtb_sphereparam::get_sphere_radius::get_sphere_radius_list (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) nlist, integer, dimension(nlist), intent(in) list, real(wp), dimension(3), intent(out) center, real(wp), intent(out) radius, logical, intent(in), optional do_trafo)
Definition at line 188 of file sphereparam.f90.
    use xtb_axis, only : axis3
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: nlist
    integer, intent(in)  :: list(nlist)
    real(wp),intent(out) :: center(3)
    real(wp),intent(out) :: radius
    logical, intent(in)  :: do_trafo
    integer  :: i,j
    real(wp) :: max_distance,distance,dum(3)
    real(wp),allocatable :: coord(:,:)
    logical  :: trafo
    optional :: do_trafo
    center = 0.0_wp
    if (present(do_trafo)) then
       trafo = do_trafo
    else
       trafo = .false.
    endif
    if (trafo) then
       allocate( coord(3,nat), source = 0.0_wp )
       call axis3(0,nat,at,xyz,coord,dum)
    else
       allocate( coord(3,nat), source = xyz )
    endif
    max_distance = 0.0_wp ! ~equals diameter of sphere
    do i = 1, nlist
       do j = 1, i-1
          distance = sqrt(sum((coord(:,list(j))-coord(:,list(i)))**2))
          max_distance = max(max_distance,distance)
       enddo
    enddo
    select case(spherepot_type)
    case(p_type_polynomial)
       radius = (0.5_wp/0.7_wp * max_distance) * sphere_autoscale
    case(p_type_logfermi)
       radius = (0.5_wp * max_distance + sphere_shift) * sphere_autoscale
    end select
References xtb_axis::axis3(), xtb_sphereparam::p_type_logfermi, xtb_sphereparam::p_type_polynomial, xtb_sphereparam::sphere_autoscale, xtb_sphereparam::sphere_shift, and xtb_sphereparam::spherepot_type.
The documentation for this interface was generated from the following file:
src/sphereparam.f90