My Project: xtb_disp_dftd4::d4_atm_gradient Interface Reference
xtb_disp_dftd4::d4_atm_gradient Interface Reference
Public Member Functions
subroutine d4_atm_gradient_neigh (mol, dispm, neighs, neighlist, par, g_a, g_c, wf, cn, dcndr, dcndL, energy, gradient, sigma)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
subroutine d4_atm_gradient_latp (mol, dispm, trans, par, g_a, g_c, wf, cutoff, cn, dcndr, dcndL, energy, gradient, sigma)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
Detailed Description
Definition at line 46 of file dftd4.F90.
Member Function/Subroutine Documentation
d4_atm_gradient_latp()
subroutine xtb_disp_dftd4::d4_atm_gradient::d4_atm_gradient_latp (type(tmolecule), intent(in) mol, type(tdispersionmodel), intent(in) dispm, real(wp), dimension(:, :), intent(in) trans, type(dftd_parameter), intent(in) par, real(wp), intent(in) g_a, real(wp), intent(in) g_c, real(wp), intent(in) wf, real(wp), intent(in) cutoff, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
Parameters
[in] mol Molecular Structure information.
[in] par Becke–Johnson damping parameters.
[in] trans Translation vectors
[in] g_a Charge scaling height.
[in] g_c Charge scaling steepness.
[in] wf Exponent for the Gaussian weighting.
[in] cutoff Cutoff for pairwise interactions
[in] cn Coordination number of every atom.
[in] dcndr Derivative of CN w.r.t. atomic coordinates.
[in] dcndl Derivative of CN w.r.t. strain deformations
[in,out] energy Dispersion energy.
[in,out] gradient Derivative of the dispersion energy w.r.t. atomic positions.
[in,out] sigma Stress tensor resulting from dispersion interactions.
Definition at line 1918 of file dftd4.F90.
    use xtb_type_molecule
    use xtb_type_neighbourlist
    use xtb_type_param
    type(TDispersionModel), intent(in) :: dispm
    type(TMolecule), intent(in) :: mol
    type(dftd_parameter), intent(in) :: par
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(in) :: g_a
    real(wp), intent(in) :: g_c
    real(wp), intent(in) :: wf
    real(wp), intent(in) :: cutoff
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    integer :: nat, max_ref
    real(wp), allocatable :: q(:)
    real(wp), allocatable :: zetavec(:, :), zetadcn(:, :), zetadq(:, :)
    real(wp), allocatable :: zerovec(:, :), zerodcn(:, :), zerodq(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :), dc6dq(:, :)
    real(wp), allocatable :: energies(:), energies3(:), dEdcn(:), dEdq(:)
    nat = len(mol)
    max_ref = maxval(dispm%nref(mol%at))
    allocate(zetavec(max_ref, nat), zetadcn(max_ref, nat), zetadq(max_ref, nat), &
       &     zerovec(max_ref, nat), zerodcn(max_ref, nat), zerodq(max_ref, nat), &
       &     q(nat), c6(nat, nat), dc6dcn(nat, nat), dc6dq(nat, nat), &
       &     energies(nat), dedcn(nat), source=0.0_wp)
    call weight_references(dispm, nat, mol%at, g_a, g_c, wf, q, cn, zeff, gam, &
       & zetavec, zerovec, zetadcn, zerodcn, zetadq)
    call get_atomic_c6(dispm, nat, mol%at, zerovec, zerodcn, zerodq, &
       & c6, dc6dcn, dc6dq)
 #ifdef XTB_GPU
    call atm_gradient_latp_gpu &
       & (mol, trans, cutoff, par, sqrtzr4r2, c6, dc6dcn, &
       &  energies, gradient, sigma, dedcn)
 #else
    call atm_gradient_latp &
       & (mol, trans, cutoff, par, sqrtzr4r2, c6, dc6dcn, &
       &  energies, gradient, sigma, dedcn)
 #endif
    call mctc_gemv(dcndr, dedcn, gradient, beta=1.0_wp)
    call mctc_gemv(dcndl, dedcn, sigma, beta=1.0_wp)
    energy = energy + sum(energies)
References xtb_disp_dftd4::atm_gradient_latp(), xtb_disp_dftd4::atm_gradient_latp_gpu(), xtb_disp_dftd4::get_atomic_c6(), xtb_param_sqrtzr4r2::sqrtzr4r2, xtb_disp_dftd4::weight_references(), and xtb_disp_dftd4param::zeff.
d4_atm_gradient_neigh()
subroutine xtb_disp_dftd4::d4_atm_gradient::d4_atm_gradient_neigh (type(tmolecule), intent(in) mol, type(tdispersionmodel), intent(in) dispm, integer, dimension(:), intent(in) neighs, type(tneighbourlist), intent(in) neighlist, type(dftd_parameter), intent(in) par, real(wp), intent(in) g_a, real(wp), intent(in) g_c, real(wp), intent(in) wf, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), intent(inout) energy, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma)
Evaluate gradient of DFT-D4, this routine can handle systems of arbitrary.
Parameters
[in] mol Molecular Structure information.
[in] neighlist Static neighbourlist.
[in] par Becke–Johnson damping parameters.
[in] neighs Number of neighbours for each atom.
[in] g_a Charge scaling height.
[in] g_c Charge scaling steepness.
[in] wf Exponent for the Gaussian weighting.
[in] cn Coordination number of every atom.
[in] dcndr Derivative of CN w.r.t. atomic coordinates.
[in] dcndl Derivative of CN w.r.t. strain deformations
[in,out] energy Dispersion energy.
[in,out] gradient Derivative of the dispersion energy w.r.t. atomic positions.
[in,out] sigma Stress tensor resulting from dispersion interactions.
Definition at line 1442 of file dftd4.F90.
    use xtb_type_molecule
    use xtb_type_neighbourlist
    use xtb_type_param
    type(TDispersionModel), intent(in) :: dispm
    type(TMolecule), intent(in) :: mol
    type(TNeighbourList), intent(in) :: neighlist
    type(dftd_parameter), intent(in) :: par
    integer, intent(in) :: neighs(:)
    real(wp), intent(in) :: g_a
    real(wp), intent(in) :: g_c
    real(wp), intent(in) :: wf
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(inout) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    integer :: nat, max_ref
    real(wp), allocatable :: q(:)
    real(wp), allocatable :: zetavec(:, :), zetadcn(:, :), zetadq(:, :)
    real(wp), allocatable :: zerovec(:, :), zerodcn(:, :), zerodq(:, :)
    real(wp), allocatable :: c6(:, :), dc6dcn(:, :), dc6dq(:, :)
    real(wp), allocatable :: energies(:), dEdcn(:)
    nat = len(mol)
    max_ref = maxval(dispm%nref(mol%at))
    allocate(zetavec(max_ref, nat), zetadcn(max_ref, nat), zetadq(max_ref, nat), &
       &     zerovec(max_ref, nat), zerodcn(max_ref, nat), zerodq(max_ref, nat), &
       &     q(nat), c6(nat, nat), dc6dcn(nat, nat), dc6dq(nat, nat), &
       &     energies(nat), dedcn(nat), source=0.0_wp)
    call weight_references(dispm, nat, mol%at, g_a, g_c, wf, q, cn, zeff, gam, &
       & zetavec, zerovec, zetadcn, zerodcn, zetadq)
    call get_atomic_c6(dispm, nat, mol%at, zerovec, zerodcn, zerodq, &
       & c6, dc6dcn, dc6dq)
    call atm_gradient_neigh &
       & (mol, neighs, neighlist, par, sqrtzr4r2, c6, dc6dcn, &
       &  energies, gradient, sigma, dedcn)
    call mctc_gemv(dcndr, dedcn, gradient, beta=1.0_wp)
    call mctc_gemv(dcndl, dedcn, sigma, beta=1.0_wp)
    energy = energy + sum(energies)
References xtb_disp_dftd4::atm_gradient_neigh(), xtb_disp_dftd4::get_atomic_c6(), xtb_param_sqrtzr4r2::sqrtzr4r2, xtb_disp_dftd4::weight_references(), and xtb_disp_dftd4param::zeff.
The documentation for this interface was generated from the following file:
src/disp/dftd4.F90