My Project: xtb_mctc_symbols::getidentity Interface Reference
xtb_mctc_symbols::getidentity Interface Reference
Get chemical identity.
Private Member Functions
subroutine getidentitynumber (nId, identity, number)
Get chemical identity from a list of atomic numbers.
subroutine getidentitysymbol (nId, identity, symbol)
Get chemical identity from a list of element symbols.
Detailed Description
Get chemical identity.
Definition at line 30 of file symbols.f90.
Member Function/Subroutine Documentation
getidentitynumber()
subroutine xtb_mctc_symbols::getidentity::getidentitynumber (integer, intent(out) nId, integer, dimension(:), intent(out) identity, integer, dimension(:), intent(in) number) private
Get chemical identity from a list of atomic numbers.
Parameters
[out] nid Number of unique species
[in] number Ordinal numbers
[out] identity Chemical identity
Definition at line 213 of file symbols.f90.
    integer, intent(out) :: nId
    integer, intent(in) :: number(:)
    integer, intent(out) :: identity(:)
    integer, allocatable :: iTmp(:)
    integer :: nAt, iAt, iId
    nat = size(identity)
    allocate(itmp(nat))
    nid = 0
    do iat = 1, nat
       iid = findnumber(itmp(:nid), number(iat))
       if (iid == 0) then
          call appendnumber(itmp, nid, number(iat))
          iid = nid
       end if
       identity(iat) = iid
    end do
References xtb_mctc_symbols::appendnumber(), and xtb_mctc_symbols::findnumber().
getidentitysymbol()
subroutine xtb_mctc_symbols::getidentity::getidentitysymbol (integer, intent(out) nId, integer, dimension(:), intent(out) identity, character(len=symbollength), dimension(:), intent(in) symbol) private
Get chemical identity from a list of element symbols.
Parameters
[out] nid Number of unique species
[in] symbol Element symbols
[out] identity Chemical identity
Definition at line 243 of file symbols.f90.
    integer, intent(out) :: nId
    character(len=symbolLength), intent(in) :: symbol(:)
    integer, intent(out) :: identity(:)
    character(len=symbolLength), allocatable :: sTmp(:)
    integer :: nAt, iAt, iId
    nat = size(identity)
    allocate(stmp(nat))
    nid = 0
    do iat = 1, nat
       iid = findsymbol(stmp(:nid), symbol(iat))
       if (iid == 0) then
          call appendsymbol(stmp, nid, symbol(iat))
          iid = nid
       end if
       identity(iat) = iid
    end do
References xtb_mctc_symbols::appendsymbol(), and xtb_mctc_symbols::findsymbol().
The documentation for this interface was generated from the following file:
src/mctc/symbols.f90