My Project: xtb_xtb_eeq::init Interface Reference
xtb_xtb_eeq::init Interface Reference
Initialize equilibration model.
Private Member Functions
subroutine initenequilibration (self, env, chi, kcn, gam, num)
Initialize equilibration model form parameters.
subroutine initenequilibrationatomic (self, env, chi, kcn, gam, num)
Initialize equilibration model form parameters.
Detailed Description
Initialize equilibration model.
Definition at line 60 of file eeq.f90.
Member Function/Subroutine Documentation
initenequilibration()
subroutine xtb_xtb_eeq::init::initenequilibration (type(tenequilibration), intent(out) self, type(tenvironment), intent(inout) env, real(wp), dimension(:, :), intent(in) chi, real(wp), dimension(:, :), intent(in), optional kcn, real(wp), dimension(:, :), intent(in), optional gam, integer, dimension(:), intent(in), optional num) private
Initialize equilibration model form parameters.
Parameters
[out] self Instance of the equilibration model
[in,out] env Calculation environment
[in] chi Electronegativity of each species
[in] kcn Coordination number dependence of each species
[in] gam Chemical hardness of each species
[in] num Atomic number for each id
Definition at line 166 of file eeq.f90.
    character(len=*), parameter :: source = 'xtb_eeq_initENEquilibration'
    type(TENEquilibration), intent(out) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: chi(:, :)
    real(wp), intent(in), optional :: kcn(:, :)
    real(wp), intent(in), optional :: gam(:, :)
    integer, intent(in), optional :: num(:)
    integer :: ii
    if (present(num)) then
       allocate(self%chi(size(chi, dim=1), size(num)))
       do ii = 1, size(num)
          self%chi(:, ii) = chi(:, num(ii))
       end do
    else
       self%chi = chi
    end if
    self%solve_lineq => solve_sysv
    self%invert_lineq => solve_sytri
    if (present(kcn)) then
       if (any(shape(kcn) /= shape(chi))) then
          call env%error("Cannot initialize CN dependence of EN", source)
          allocate(self%kcn(size(self%chi, 1), size(self%chi, 2)))
          self%kcn(:, :) = 0.0_wp
       else
          if (present(num)) then
             allocate(self%kcn(size(kcn, dim=1), size(num)))
             do ii = 1, size(num)
                self%kcn(:, ii) = kcn(:, num(ii))
             end do
          else
             self%kcn = kcn
          end if
       end if
    end if
    if (present(gam)) then
       if (any(shape(gam) /= shape(chi))) then
          call env%error("Cannot initialize chemical hardness", source)
          allocate(self%gam(size(self%chi, 1), size(self%chi, 2)))
          self%gam(:, :) = 0.0_wp
       else
          if (present(num)) then
             allocate(self%gam(size(gam, dim=1), size(num)))
             do ii = 1, size(num)
                self%gam(:, ii) = gam(:, num(ii))
             end do
          else
             self%gam = gam
          end if
       end if
    end if
References xtb_xtb_eeq::solve_sysv(), and xtb_xtb_eeq::solve_sytri().
initenequilibrationatomic()
subroutine xtb_xtb_eeq::init::initenequilibrationatomic (type(tenequilibration), intent(out) self, type(tenvironment), intent(inout) env, real(wp), dimension(:), intent(in) chi, real(wp), dimension(:), intent(in), optional kcn, real(wp), dimension(:), intent(in), optional gam, integer, dimension(:), intent(in), optional num) private
Initialize equilibration model form parameters.
Parameters
[out] self Instance of the equilibration model
[in,out] env Calculation environment
[in] chi Electronegativity of each species
[in] kcn Coordination number dependence of each species
[in] gam Chemical hardness of each species
[in] num Atomic number for each id
Definition at line 91 of file eeq.f90.
    character(len=*), parameter :: source = 'xtb_eeq_initENEquilibrationAtomic'
    type(TENEquilibration), intent(out) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: chi(:)
    real(wp), intent(in), optional :: kcn(:)
    real(wp), intent(in), optional :: gam(:)
    integer, intent(in), optional :: num(:)
    integer :: ii
    if (present(num)) then
       allocate(self%chi(1, size(num)))
       do ii = 1, size(num)
          self%chi(1, ii) = chi(num(ii))
       end do
    else
       self%chi = reshape(chi, [1, size(chi)])
    end if
    self%solve_lineq => solve_sysv
    self%invert_lineq => solve_sytri
    if (present(kcn)) then
       if (any(shape(kcn) /= shape(chi))) then
          call env%error("Cannot initialize CN dependence of EN", source)
          allocate(self%kcn(1, size(self%chi)))
          self%kcn(:, :) = 0.0_wp
       else
          if (present(num)) then
             allocate(self%kcn(1, size(num)))
             do ii = 1, size(num)
                self%kcn(1, ii) = kcn(num(ii))
             end do
          else
             self%kcn = reshape(kcn, [1, size(kcn)])
          end if
       end if
    end if
    if (present(gam)) then
       if (any(shape(gam) /= shape(chi))) then
          call env%error("Cannot initialize chemical hardness", source)
          allocate(self%gam(1, size(self%chi)))
          self%gam(:, :) = 0.0_wp
       else
          if (present(num)) then
             allocate(self%gam(1, size(num)))
             do ii = 1, size(num)
                self%gam(1, ii) = gam(num(ii))
             end do
          else
             self%gam = reshape(gam, [1, size(gam)])
          end if
       end if
    end if
References xtb_xtb_eeq::solve_sysv(), and xtb_xtb_eeq::solve_sytri().
The documentation for this interface was generated from the following file:
src/xtb/eeq.f90