My Project: xtb_disp_ncoord::get_d4_cn Interface Reference
xtb_disp_ncoord::get_d4_cn Interface Reference
Public Member Functions
pure subroutine ncoord_d4_driver (mol, cn, dcndr, dcndL, thr)
pure subroutine ncoord_d4 (nat, at, xyz, cn, thr)
pure subroutine dncoord_d4 (nat, at, xyz, cn, dcndr, thr)
pure subroutine pbc_ncoord_d4 (nat, at, xyz, lat, cn, thr)
pure subroutine pbc_dncoord_d4 (nat, at, xyz, lat, cn, dcndr, dcndL, thr)
Detailed Description
Definition at line 123 of file ncoord.f90.
Member Function/Subroutine Documentation
dncoord_d4()
pure subroutine xtb_disp_ncoord::get_d4_cn::dncoord_d4 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), intent(in), optional thr)
Definition at line 631 of file ncoord.f90.
    use xtb_mctc_constants
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i, j, ia, ja
    real(wp) :: r, r2, rij(3)
    real(wp) :: rcovij,den
    real(wp) :: dtmp, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0._wp
    dcndr = 0._wp
    do i = 1, nat
       ia = at(i)
       do j = 1, i-1
          ja = at(j)
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(ia)+rcov(ja))
          den=k4*exp(-(abs((en(ia)-en(ja)))+ k5)**2/k6 )
          tmp = den * erf_count(kn,r,rcovij)
          dtmp = den * derf_count(kn,r,rcovij)
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
          dcndr(:,i,i)=-dtmp*rij/r + dcndr(:,i,i)
          dcndr(:,j,j)= dtmp*rij/r + dcndr(:,j,j)
          dcndr(:,i,j)=-dtmp*rij/r
          dcndr(:,j,i)= dtmp*rij/r
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::derf_count(), xtb_disp_ncoord::en, xtb_disp_ncoord::erf_count(), xtb_disp_ncoord::k4, xtb_disp_ncoord::k5, xtb_disp_ncoord::k6, xtb_disp_ncoord::kn, and xtb_disp_ncoord::rcov.
ncoord_d4()
pure subroutine xtb_disp_ncoord::get_d4_cn::ncoord_d4 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
Definition at line 575 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, rr, r2, xn, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn = 0._wp
    do i=1,nat
       do j=1,i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
 !        covalent distance in bohr
          rco=rcov(at(j)) + rcov(at(i))
          rr=rco/r
          den=k4*exp(-(abs((en(at(i))-en(at(j))))+ k5)**2/k6 )
 !        counting function exponential has a better long-range
 !        behavior than MHGs inverse damping
          !tmp = den/(1.d0+exp(-k1*(rr-1.0d0)))
 !        error function has an even better long range behavior
          tmp = den * erf_count(kn,r,rco)
          cn(i)=cn(i)+tmp
          cn(j)=cn(j)+tmp
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::en, xtb_disp_ncoord::erf_count(), xtb_disp_ncoord::k4, xtb_disp_ncoord::k5, xtb_disp_ncoord::k6, xtb_disp_ncoord::kn, and xtb_disp_ncoord::rcov.
ncoord_d4_driver()
pure subroutine xtb_disp_ncoord::get_d4_cn::ncoord_d4_driver (type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:,:,:), intent(out), optional dcndr, real(wp), dimension(:,:,:), intent(out), optional dcndL, real(wp), intent(in), optional thr)
Parameters
[in] mol molecular structure information
[out] cn coordination number
[out] dcndr derivative of coordination number w.r.t. nuclear positions
[out] dcndl derivative of coordination number w.r.t. lattice vectors
[in] thr quadratic distance threshold for sum termination
Definition at line 241 of file ncoord.f90.
    use xtb_type_molecule
    implicit none
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out), optional :: dcndr(:,:,:)
    real(wp), intent(out), optional :: dcndL(:,:,:)
    real(wp), intent(in), optional :: thr
    real(wp) :: cn_thr
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    if (mol%npbc > 0) then
       if (present(dcndr).and.present(dcndl)) then
          call pbc_dncoord_d4(mol%n,mol%at,mol%xyz,mol%lattice,cn,dcndr,dcndl,cn_thr)
       else
          call pbc_ncoord_d4(mol%n,mol%at,mol%xyz,mol%lattice,cn,cn_thr)
       endif
    else
       if (present(dcndr)) then
          call dncoord_d4(mol%n,mol%at,mol%xyz,cn,dcndr,cn_thr)
       else
          call ncoord_d4(mol%n,mol%at,mol%xyz,cn,cn_thr)
       endif
    endif
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::dncoord_d4(), xtb_disp_ncoord::ncoord_d4(), xtb_disp_ncoord::pbc_dncoord_d4(), and xtb_disp_ncoord::pbc_ncoord_d4().
pbc_dncoord_d4()
pure subroutine xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3,3), intent(in) lat, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), dimension(3,3,nat), intent(out) dcndL, real(wp), intent(in), optional thr)
Definition at line 750 of file ncoord.f90.
    use xtb_mctc_constants
    use xtb_pbc_tools
    use xtb_pbc, only : get_realspace_cutoff
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer              :: rep_cn(3)
    integer              :: tx,ty,tz
    real(wp)             :: t(3)
    real(wp),intent(in)  :: lat(3,3)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(out) :: dcndL(3,3,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, r2, xn, tmp, dtmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0.0_wp
    dcndr = 0.0_wp
    dcndl = 0.0_wp
    call get_realspace_cutoff(lat,cn_thr,rep_cn)
    do i=1,nat
       do j=1,i-1
          do concurrent(tx = -rep_cn(1):rep_cn(1), &
                &       ty = -rep_cn(2):rep_cn(2), &
                &       tz = -rep_cn(3):rep_cn(3))
             t = [tx,ty,tz]
             rij = xyz(:,j) - xyz(:,i) + matmul(lat,t)
             r2  = sum(rij**2)
             if (r2.gt.cn_thr) cycle
             r=sqrt(r2)
             ! covalent distance in bohr
             rco=rcov(at(j)) + rcov(at(i))
             den=k4*exp(-(abs((en(at(i))-en(at(j))))+ k5)**2/k6 )
             tmp = den * erf_count(kn,r,rco)
             dtmp = den * derf_count(kn,r,rco)
             cn(i)=cn(i)+tmp
             cn(j)=cn(j)+tmp
             dcndr(:,i,i)=-dtmp*rij/r + dcndr(:,i,i)
             dcndr(:,j,j)= dtmp*rij/r + dcndr(:,j,j)
             dcndr(:,i,j)=-dtmp*rij/r + dcndr(:,i,j)
             dcndr(:,j,i)= dtmp*rij/r + dcndr(:,j,i)
             dcndl(:,:,j)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,j)
             dcndl(:,:,i)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,i)
          enddo
       enddo
       do concurrent(tx = -rep_cn(1):rep_cn(1), &
             &       ty = -rep_cn(2):rep_cn(2), &
             &       tz = -rep_cn(3):rep_cn(3))
          ! avoid self interaction
          if ((tx.eq.0).and.(ty.eq.0).and.(tz.eq.0)) cycle
          t = [tx,ty,tz]
          rij = matmul(lat,t)
          r2  = sum(rij**2)
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
          ! covalent distance in bohr
          rco=2*rcov(at(i))
          den=k4*exp(-k5**2/k6)
          tmp = den * erf_count(kn,r,rco)
          dtmp = den * derf_count(kn,r,rco)
          cn(i)=cn(i)+tmp
          dcndl(:,:,i)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,i)
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::derf_count(), xtb_disp_ncoord::en, xtb_disp_ncoord::erf_count(), xtb_pbc::get_realspace_cutoff(), xtb_disp_ncoord::k4, xtb_disp_ncoord::k5, xtb_disp_ncoord::k6, xtb_disp_ncoord::kn, xtb_pbc_tools::outer_prod_3x3(), and xtb_disp_ncoord::rcov.
pbc_ncoord_d4()
pure subroutine xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3,3), intent(in) lat, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
Definition at line 682 of file ncoord.f90.
    use xtb_mctc_constants
    use xtb_pbc_tools
    use xtb_pbc, only : get_realspace_cutoff
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer              :: rep_cn(3)
    integer              :: tx,ty,tz
    real(wp)             :: t(3)
    real(wp),intent(in)  :: lat(3,3)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, r2, xn, tmp, dtmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0.0_wp
    call get_realspace_cutoff(lat,cn_thr,rep_cn)
    do i=1,nat
       do j=1,i-1
          do concurrent(tx = -rep_cn(1):rep_cn(1), &
                &       ty = -rep_cn(2):rep_cn(2), &
                &       tz = -rep_cn(3):rep_cn(3))
             t = [tx,ty,tz]
             rij = xyz(:,j) - xyz(:,i) + matmul(lat,t)
             r2  = sum(rij**2)
             if (r2.gt.cn_thr) cycle
             r=sqrt(r2)
             ! covalent distance in bohr
             rco=rcov(at(j)) + rcov(at(i))
             den=k4*exp(-(abs((en(at(i))-en(at(j))))+ k5)**2/k6 )
             tmp = den * erf_count(kn,r,rco)
             cn(i)=cn(i)+tmp
             cn(j)=cn(j)+tmp
          enddo
       enddo
       do concurrent(tx = -rep_cn(1):rep_cn(1), &
             &       ty = -rep_cn(2):rep_cn(2), &
             &       tz = -rep_cn(3):rep_cn(3), &
             &       tx.ne.0 .or. ty.ne.0 .or. tz.ne.0)
          t = [tx,ty,tz]
          rij = matmul(lat,t)
          r2  = sum(rij**2)
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
          ! covalent distance in bohr
          rco=2*rcov(at(i))
          den=k4*exp(-k5**2/k6 )
          tmp = den * erf_count(kn,r,rco)
          cn(i)=cn(i)+tmp
       enddo
    enddo
References xtb_disp_ncoord::cnthr, xtb_disp_ncoord::en, xtb_disp_ncoord::erf_count(), xtb_pbc::get_realspace_cutoff(), xtb_disp_ncoord::k4, xtb_disp_ncoord::k5, xtb_disp_ncoord::k6, xtb_disp_ncoord::kn, and xtb_disp_ncoord::rcov.
The documentation for this interface was generated from the following file:
src/disp/ncoord.f90