My Project: xtb_mctc_strings::writeq Interface Reference
xtb_mctc_strings::writeq Interface Reference
Generic interface equating a name to a numerical value. The calling syntax is 'call writeq(unit,name,value,format)' where unit is the integer output unit number, 'name' is the variable name, 'value' is the real or integer value of the variable, and 'format' is the format of the value. The result written to the output unit has the form <name> = .
Public Member Functions
subroutine writeq_dr (unit, namestr, value, fmt)
Writes a string of the form <name> = value to unit.
subroutine writeq_sr (unit, namestr, value, fmt)
Writes a string of the form <name> = value to unit.
subroutine writeq_di (unit, namestr, ivalue, fmt)
Writes a string of the form <name> = ivalue to unit.
subroutine writeq_si (unit, namestr, ivalue, fmt)
Writes a string of the form <name> = ivalue to unit.
Detailed Description
Generic interface equating a name to a numerical value. The calling syntax is 'call writeq(unit,name,value,format)' where unit is the integer output unit number, 'name' is the variable name, 'value' is the real or integer value of the variable, and 'format' is the format of the value. The result written to the output unit has the form <name> =
.
Definition at line 77 of file mctc_strings.f90.
Member Function/Subroutine Documentation
writeq_di()
subroutine xtb_mctc_strings::writeq::writeq_di (integer unit, character(len=*) namestr, integer(ki8) ivalue, character(len=*) fmt)
Writes a string of the form <name> = ivalue to unit.
Definition at line 733 of file mctc_strings.f90.
 integer(ki8) :: ivalue
 integer :: unit
 character(len=*) :: namestr,fmt
 character(len=32) :: tempstr
 call writenum(ivalue,tempstr,fmt)
 call trimzero(tempstr)
 write(unit,*) trim(namestr)//' = '//trim(tempstr)
References xtb_mctc_strings::trimzero().
writeq_dr()
subroutine xtb_mctc_strings::writeq::writeq_dr (integer unit, character(len=*) namestr, real(kr8) value, character(len=*) fmt)
Writes a string of the form <name> = value to unit.
Definition at line 700 of file mctc_strings.f90.
 real(kr8) :: value
 integer :: unit
 character(len=*) :: namestr,fmt
 character(len=32) :: tempstr
 call writenum(value,tempstr,fmt)
 call trimzero(tempstr)
 write(unit,*) trim(namestr)//' = '//trim(tempstr)
References xtb_mctc_strings::trimzero().
writeq_si()
subroutine xtb_mctc_strings::writeq::writeq_si (integer unit, character(len=*) namestr, integer(ki4) ivalue, character(len=*) fmt)
Writes a string of the form <name> = ivalue to unit.
Definition at line 749 of file mctc_strings.f90.
 integer(ki4) :: ivalue
 integer :: unit
 character(len=*) :: namestr,fmt
 character(len=32) :: tempstr
 call writenum(ivalue,tempstr,fmt)
 call trimzero(tempstr)
 write(unit,*) trim(namestr)//' = '//trim(tempstr)
References xtb_mctc_strings::trimzero().
writeq_sr()
subroutine xtb_mctc_strings::writeq::writeq_sr (integer unit, character(len=*) namestr, real(kr4) value, character(len=*) fmt)
Writes a string of the form <name> = value to unit.
Definition at line 716 of file mctc_strings.f90.
 real(kr4) :: value
 integer :: unit
 character(len=*) :: namestr,fmt
 character(len=32) :: tempstr
 call writenum(value,tempstr,fmt)
 call trimzero(tempstr)
 write(unit,*) trim(namestr)//' = '//trim(tempstr)
References xtb_mctc_strings::trimzero().
The documentation for this interface was generated from the following file:
src/mctc/mctc_strings.f90