My Project: src/lin.f90 File Reference
lin.f90 File Reference
Functions/Subroutines
pure elemental integer function lin (i1, i2)
pure elemental integer function lina (i1, i2)
Function/Subroutine Documentation
lin()
pure elemental integer function lin (integer, intent(in) i1, integer, intent(in) i2)
Definition at line 22 of file lin.f90.
    integer,intent(in) :: i1,i2
    integer :: idum1,idum2
    idum1=max(i1,i2)
    idum2=min(i1,i2)
    lin=idum2+idum1*(idum1-1)/2
    return
References lin().
lina()
pure elemental integer function lina (integer, intent(in) i1, integer, intent(in) i2)
Definition at line 31 of file lin.f90.
    integer,intent(in) :: i1,i2
    integer :: idum1,idum2
    idum1=max(i1,i2)
    idum2=min(i1,i2)
    lina=idum2+idum1*(idum1-1)/2
    return
Referenced by gff_ddvopt(), and xtb_lin::lina().