My Project: src/gfnff/math.f File Reference
math.f File Reference
Functions/Subroutines
subroutine vsub (a, b, c, n)
real *8 function vlen (a)
real *8 function valijklff (natoms, xyz, i, j, k, l)
Function/Subroutine Documentation
valijklff()
real*8 function valijklff (integer natoms, real*8, dimension(3,natoms) xyz, integer i, integer j, integer k, integer l)
Definition at line 48 of file math.f.
       implicit none
       external
      ,     vecnorm,valijk
       integer
      ,     ic,i,j,k,l,natoms
       real*8
      ,     xyz(3,natoms),
      ,     eps,ra(3),rb(3),rc(3),na(3),nb(3),
      ,     rab,rbc,thab,thbc,valijk,
      ,     vecnorm,nan,nbn,rcn,snanb,deter,pi
       parameter(eps=1.0d-14)
       data pi/3.1415926535897932384626433832795029d0/
 c ... get torsion coordinate
       do ic=1,3
         ra(ic)=xyz(ic,j)-xyz(ic,i)
         rb(ic)=xyz(ic,k)-xyz(ic,j)
         rc(ic)=xyz(ic,l)-xyz(ic,k)
       end do
 c ... determinante of rb,ra,rc
       deter= ra(1)*(rb(2)*rc(3)-rb(3)*rc(2))
      ,      -ra(2)*(rb(1)*rc(3)-rb(3)*rc(1))
      ,      +ra(3)*(rb(1)*rc(2)-rb(2)*rc(1))
       thab=valijk(natoms,xyz,i,k,j)
       thbc=valijk(natoms,xyz,j,l,k)
       call crossprod(ra,rb,na)
       call crossprod(rb,rc,nb)
       nan=vecnorm(na,3,1)
       nbn=vecnorm(nb,3,1)
       snanb=0.0d0
       do ic=1,3
         snanb=snanb+na(ic)*nb(ic)
       end do
       if (abs(abs(snanb)-1.d0).lt.eps) then
         snanb=sign(1.d0,snanb)
       end if
       valijklff=acos(snanb)
References crossprod(), valijk(), and vecnorm().
Referenced by xtb_gfnff_eg::abhgfnff_eg3(), xtb_gfnff_eg::abhgfnff_eg3_add(), xtb_gfnff_eg::abhgfnff_eg3_mul(), xtb_gfnff_eg::egbend(), xtb_gfnff_eg::egbend_nci(), xtb_gfnff_eg::egbend_nci_mul(), xtb_gfnff_eg::egtors(), xtb_gfnff_eg::egtors_nci(), xtb_gfnff_eg::egtors_nci_mul(), xtb_qmdff::ff_eg(), xtb_gfnff_eg::gfnff_eg(), and xtb_qmdff::valijklff().
vlen()
real*8 function vlen (real*8, dimension(3) a)
Definition at line 34 of file math.f.
       implicit none !double precision (a-h,o-z)
       real*8 a(3)
       real*8 tot
       tot = a(1)*a(1)+a(2)*a(2)+a(3)*a(3)
       vlen = 0.0d0
       if (tot.gt.0.0d0) vlen = dsqrt(tot)
       return
Referenced by xtb_gfnff_eg::egbend(), xtb_gfnff_eg::egbend_nci(), xtb_gfnff_eg::egbend_nci_mul(), xtb_gfnff_eg::egtors(), xtb_gfnff_eg::egtors_nci(), and xtb_gfnff_eg::egtors_nci_mul().
vsub()
subroutine vsub (real*8, dimension(n) a, real*8, dimension(n) b, real*8, dimension(n) c, integer n)
Definition at line 19 of file math.f.
       implicit none
       integer n
       real*8 a(n),b(n),c(n)
       integer i
       do i=1,n
          c(i) = a(i) - b(i)
       end do
       return
Referenced by xtb_gfnff_eg::egbend(), xtb_gfnff_eg::egbend_nci(), and xtb_gfnff_eg::egbend_nci_mul().