My Project: src/mctc/mctc_init.F90 File Reference
mctc_init.F90 File Reference
Functions/Subroutines
subroutine mctc_init (progname, ntimer, verbose)
subroutine mctc_sanity (sane)
subroutine mctc_strict
subroutine mctc_mute
Function/Subroutine Documentation
mctc_init()
subroutine mctc_init (character(len=*), intent(in) progname, integer, intent(in) ntimer, logical, intent(in) verbose)
Definition at line 18 of file mctc_init.F90.
    use xtb_mctc_global
    use xtb_mctc_timings
    use xtb_mctc_filetools
    use xtb_type_environment, only : init
    implicit none
    character(len=*),intent(in) :: progname
    integer,         intent(in) :: ntimer
    logical,         intent(in) :: verbose
 #ifdef USE_CUSOLVER
    integer :: err
 #endif
 !! ========================================================================
 !  signal processing
    external :: wSIGTERM
    external :: wSIGINT
 !  here two important signal handlers are installed, it seems that
 !  FORTRAN by itself cannot handle signals in the way I expected it
 !  to do, but this will force it to die when I hit CTRL^C.
 !  UPDATE: Since the FORTRAN standard does not specify which signals
 !          are handled by the language, some compilers may handle no
 !          signals at all. This is *non-standard* so it will break
 !          your program on some platforms with some compilers!
    call signal(2,wsigint)
    call signal(15,wsigterm)
 !  initialize the timing system
    call start_timing_run
    call init_timing(ntimer,verb=verbose) ! verbosity allows printing of cputime
    call start_timing(1)
 !  initialize the messagebuffer for the error handler
    call init_errorbuffer
 !  initialize the filelist
    call init_filelist(20)
 !  set this for xtb_mctc_global
    name = progname
    allocate(persistentenv)
    call init(persistentenv)
 #ifdef USE_CUSOLVER
    err = cusolverdncreate(cusolverdnh)
    if (err /= 0) then
       call persistentenv%error("failed to create cusolver handle", "mctc_init")
    end if
 #endif
References xtb_mctc_global::init_errorbuffer(), xtb_mctc_filetools::init_filelist(), xtb_mctc_timings::init_timing(), xtb_mctc_global::name, xtb_mctc_global::persistentenv, xtb_mctc_timings::start_timing(), xtb_mctc_timings::start_timing_run(), wsigint(), and wsigterm().
Referenced by peeq_tester(), and xtb_prog_primary().
mctc_mute()
subroutine mctc_mute
Definition at line 81 of file mctc_init.F90.
    use xtb_mctc_global
    mute = .true.
References xtb_mctc_global::mute, and true().
Referenced by test_gfn1_pbc3d(), test_peeq_api(), test_peeq_api_srb(), and test_peeq_sp().
mctc_sanity()
subroutine mctc_sanity (logical, intent(out) sane)
Definition at line 70 of file mctc_init.F90.
    use xtb_mctc_global
    logical,intent(out) :: sane
    sane = good
References xtb_mctc_global::good.
mctc_strict()
subroutine mctc_strict
Definition at line 76 of file mctc_init.F90.
    use xtb_mctc_global
    strict = .true.
References xtb_mctc_global::strict, and true().
Referenced by xtb_prog_main::xtbmain().