My Project: src/model_hessian.f90 File Reference
model_hessian.f90 File Reference
Modules
module xtb_modelhessian
Functions/Subroutines
subroutine, public xtb_modelhessian::mh_swart (xyz, n, hess, at, modh)
pure subroutine xtb_modelhessian::mh_swart_stretch (n, at, xyz, hess, kr, kd, s6, rcov, rvdw, lcutoff, rcut)
pure subroutine xtb_modelhessian::mh_swart_bend (n, at, xyz, hess, kf, kd, rcov, rvdw, lcutoff)
pure subroutine xtb_modelhessian::mh_swart_torsion (n, at, xyz, hess, kt, kd, rcov, rvdw, lcutoff)
pure subroutine xtb_modelhessian::mh_swart_outofp (n, at, xyz, hess, ko, kd, rcov, rvdw, lcutoff)
subroutine, public xtb_modelhessian::mh_lindh_d2 (xyz, n, hess, at, modh)
subroutine, public xtb_modelhessian::mh_lindh (xyz, n, hess, at, modh)
pure subroutine xtb_modelhessian::mh_lindh_stretch (n, at, xyz, hess, kr, kd, s6, aav, rav, dav, lcutoff, rcut)
pure subroutine xtb_modelhessian::mh_lindh_bend (n, at, xyz, hess, kf, kd, aav, rav, dav, lcutoff)
subroutine xtb_modelhessian::mh_lindh_torsion (n, at, xyz, hess, kt, kd, aav, rav, dav, lcutoff)
pure subroutine xtb_modelhessian::mh_lindh_outofp (n, at, xyz, hess, ko, kd, aav, rav, dav, lcutoff)
pure elemental integer function xtb_modelhessian::ixyz (i, iatom)
pure elemental integer function xtb_modelhessian::jnd (i, j)
pure elemental integer function xtb_modelhessian::ind (i, iatom, j, jatom)
pure logical function xtb_modelhessian::rcutoff (xyz, katom, latom, rcut)
pure elemental integer function xtb_modelhessian::itabrow (i)
pure subroutine xtb_modelhessian::outofp2 (xyz, teta, bt)
pure subroutine xtb_modelhessian::trsn2 (xyz, tau, bt)
pure subroutine xtb_modelhessian::strtch2 (xyz, avst, b)
pure subroutine xtb_modelhessian::bend2 (xyz, fir, bf)
pure elemental subroutine xtb_modelhessian::getvdwxy (rx, ry, rz, c66, s6, r0, vdw)
pure elemental subroutine xtb_modelhessian::getvdwxx (rx, ry, rz, c66, s6, r0, vdw)
pure elemental real(wp) function xtb_modelhessian::fk_lindh (alpha, r0, r2)
pure elemental real(wp) function xtb_modelhessian::fk_swart (alpha, r0, r2)
pure elemental real(wp) function xtb_modelhessian::fk_vdw (alpha, r0, r2)
subroutine xtb_modelhessian::mh_eeq (n, at, xyz, chrg, chrgeq, kq, hess)
subroutine ddvopt (Cart, nAtoms, Hess, iANr, s6)
subroutine gff_ddvopt (Cart, nAtoms, Hess, at, s6, param, topo)
subroutine getqqxx (dx, qq, c6, r, r2, r3, rpa, r02, d2)
subroutine getqqxy (dx, dy, qq, c6, r, r2, r3, rpa, r02, d2)
Variables
real(wp), dimension(86), parameter xtb_modelhessian::vander = aatoau * (/ 0.91_wp,0.92_wp, 0.75_wp,1.28_wp,1.35_wp,1.32_wp,1.27_wp,1.22_wp,1.17_wp,1.13_wp, 1.04_wp,1.24_wp,1.49_wp,1.56_wp,1.55_wp,1.53_wp,1.49_wp,1.45_wp, 1.35_wp,1.34_wp, 1.42_wp,1.42_wp,1.42_wp,1.42_wp,1.42_wp, 1.42_wp,1.42_wp,1.42_wp,1.42_wp,1.42_wp, 1.50_wp,1.57_wp,1.60_wp,1.61_wp,1.59_wp,1.57_wp, 1.48_wp,1.46_wp, 1.49_wp,1.49_wp,1.49_wp,1.49_wp,1.49_wp, 1.49_wp,1.49_wp,1.49_wp,1.49_wp,1.49_wp, 1.52_wp,1.64_wp,1.71_wp,1.72_wp,1.72_wp,1.71_wp, 2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp /)
real(wp), dimension(86), parameter xtb_modelhessian::c6 = (/ 0.14_wp, 0.08_wp, 1.61_wp, 1.61_wp, 3.13_wp, 1.75_wp, 1.23_wp, 0.70_wp, 0.75_wp, 0.63_wp, 5.71_wp, 5.71_wp,10.79_wp, 9.23_wp, 7.84_wp, 5.57_wp, 5.07_wp, 4.61_wp, 10.80_wp,10.80_wp, 10.80_wp,10.80_wp,10.80_wp,10.80_wp,10.80_wp, 10.80_wp,10.80_wp,10.80_wp,10.80_wp,10.80_wp, 16.99_wp,17.10_wp,16.37_wp,12.64_wp,12.47_wp,12.01_wp, 24.67_wp,24.67_wp, 24.67_wp,24.67_wp,24.67_wp,24.67_wp,24.67_wp, 24.67_wp,24.67_wp,24.67_wp,24.67_wp,24.67_wp, 37.32_wp,38.71_wp,38.44_wp,31.74_wp,31.50_wp,29.99_wp, 50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp /)
real(wp), parameter xtb_modelhessian::min_fk = 1.0e-3_wp
Function/Subroutine Documentation
ddvopt()
subroutine ddvopt (real*8, dimension(3,natoms) Cart, nAtoms, real*8, dimension((3*natoms)*(3*natoms+1)/2) Hess, integer, dimension(natoms) iANr, s6)
Definition at line 2084 of file model_hessian.f90.
       Implicit Integer(i-n)
       Implicit Real*8 (a-h, o-z)
 ! include "common/real.inc" (molpro 2002.6)
       real*8 zero, one, two, three, four, five, six, seven, &
      &       eight, rnine, ten, half, pi, sqrtp2, twop34, &
      &       twop54, one2c2
       parameter(zero =0.0d0, one  =1.0d0, two=2.0d0, three=3.0d0, &
      &          four =4.0d0, five =5.0d0, six=6.0d0, seven=7.0d0, &
      &          eight=8.0d0, rnine=9.0d0, ten=1.0d1, half=0.5d0, &
      &          pi    =3.141592653589793d0, &
      &          sqrtp2=0.8862269254527579d0, &
      &          twop34=0.2519794355383808d0, &
      &          twop54=5.914967172795612d0, &
      &          one2c2=0.2662567690426443d-04)
 ! end: common/real.inc
       real*8 cart(3,natoms),rij(3),rjk(3),rkl(3), &
      &       hess((3*natoms)*(3*natoms+1)/2),si(3),sj(3),sk(3), &
      &       sl(3),sm(3),x(2),y(2),z(2), &
      &       xyz(3,4), c(3,4), dum(3,4,3,4)
       Integer   iANr(nAtoms)
       logical rcutoff
 ! include  "common/ddvdt.inc" (molpro 2002.6)
       real*8 rav(3,3), aav(3,3), &
      &       b_str(6), a_bend(2), a_trsn(2), a_strh(2), &
      &       rkr, rkf, a_str, rf_const, &
      &       wthr
       Data rav/1.3500d+00,2.1000d+00,2.5300d+00, &
      &         2.1000d+00,2.8700d+00,3.4000d+00, &
      &         2.5300d+00,3.4000d+00,3.4000d+00/
       Data aav/1.0000d+00,0.3949d+00,0.3949d+00, &
      &         0.3949d+00,0.2800d+00,0.2800d+00, &
      &         0.3949d+00,0.2800d+00,0.2800d+00/
 !org  Data rkr,rkf,rkt/0.4500D+00,0.1500D+00,0.5000D-02/
       Data rkr,rkf,rkt/0.4000d+00,0.1300d+00,0.7500d-02/
       Data a_str/1.734d0/
       Data b_str/-.244d0,0.352d0,1.085d0,0.660d0,1.522d0,2.068d0/
       Data a_bend/0.160d0,0.250d0/
       Data a_trsn/0.0023d0,0.07d0/
       Data a_strh/0.3601d0,1.944d0/
       Data rf_const/1.0d-2/
       Data wthr/0.2/
 ! end: "common/ddvdt.inc"
 !cc VDWx-Parameters (Grimme) used for vdw-correction of model hessian
       real*8 alphavdw, damp, c6(100), c6k, c6l, c66, vander(100), &
      &   vdw(3,3), dr(3)
       integer kxyz, lxyz
       data vander &
 ! H, He
      &     /0.91d0,0.92d0, &
 ! Li-Ne
      &      0.75d0,1.28d0,1.35d0,1.32d0,1.27d0,1.22d0,1.17d0,1.13d0, &
 ! Na-Ar
      &      1.04d0,1.24d0,1.49d0,1.56d0,1.55d0,1.53d0,1.49d0,1.45d0, &
 ! K, Ca
      &      1.35d0,1.34d0, &
 ! Sc-Zn
      &      1.42d0,1.42d0,1.42d0,1.42d0,1.42d0, &
      &      1.42d0,1.42d0,1.42d0,1.42d0,1.42d0, &
 ! Ga-Kr
      &      1.50d0,1.57d0,1.60d0,1.61d0,1.59d0,1.57d0, &
 ! Rb, Sr
      &      1.48d0,1.46d0, &
 ! Y-Cd
      &      1.49d0,1.49d0,1.49d0,1.49d0,1.49d0, &
      &      1.49d0,1.49d0,1.49d0,1.49d0,1.49d0, &
 ! In, Sn, Sb, Te, I, Xe
      &      1.52d0,1.64d0,1.71d0,1.72d0,1.72d0,1.71d0, &
      &      46*2.d0/
 !cc End: VDWx ccccccccccccccccc
 !
 !------- Statement functions
 !
       ixyz(i,iatom) = (iatom-1)*3 + i
       jnd(i,j) = i*(i-1)/2 +j
       ind(i,iatom,j,jatom)=jnd(max(ixyz(i,iatom),ixyz(j,jatom)), &
      &                         min(ixyz(i,iatom),ixyz(j,jatom)))
 !end
 !cc VDWx cccccccccccccccccccc
        c6 =   50.0
        c6( 1)=0.14
        c6( 2)=0.08
        c6( 3)=1.61
        c6( 4)=1.61
        c6( 5)=3.13
        c6( 6)=1.75
        c6( 7)=1.23
        c6( 8)=0.70
        c6( 9)=0.75
        c6(10)=0.63
        c6(11)=5.71
        c6(12)=5.71
        c6(13)=10.79
        c6(14)=9.23
        c6(15)=7.84
        c6(16)=5.57
        c6(17)=5.07
        c6(18)=4.61
        c6(19:30)=10.8
        c6(31)=16.99
        c6(32)=17.10
        c6(33)=16.37
        c6(34)=12.64
        c6(35)=12.47
        c6(36)=12.01
        c6(37:48)=24.67
        c6(49)=37.32
        c6(50)=38.71
        c6(51)=38.44
        c6(52)=31.74
        c6(53)=31.50
        c6(54)=29.99
 !cc ENDE VDWx cccccccccccccccc
       bohr=0.52917726d0
       fact=one
 !hjw threshold reduced
       rzero=1.0d-10
       n3=3*natoms
       hess = 0.0d0
 !
 !     Hessian for tension
 !
  777  Do katom = 1, natoms
          kr=itabrow(ianr(katom))
 !        If (kr.eq.0) Go To 5
          Do latom = 1, katom-1
             lr=itabrow(ianr(latom))
 !           If (lr.eq.0) Go To 10
             xkl=cart(1,katom)-cart(1,latom)
             ykl=cart(2,katom)-cart(2,latom)
             zkl=cart(3,katom)-cart(3,latom)
             rkl2 = xkl**2 + ykl**2 + zkl**2
             r0=rav(kr,lr)
             alpha=aav(kr,lr)
 !cccccc VDWx ccccccccccccccccccccccccccccccccc
             c6k=c6(ianr(katom))
             c6l=c6(ianr(latom))
             c66=sqrt(c6k*c6l)
             rv=(vander(ianr(katom))+vander(ianr(latom)))/0.52917721
             call getvdwxx(xkl, ykl, zkl, c66, s6, rv, vdw(1,1))
             call getvdwxy(xkl, ykl, zkl, c66, s6, rv, vdw(1,2))
             call getvdwxy(xkl, zkl, ykl, c66, s6, rv, vdw(1,3))
             call getvdwxx(ykl, xkl, zkl, c66, s6, rv, vdw(2,2))
             call getvdwxy(ykl, zkl, xkl, c66, s6, rv, vdw(2,3))
             call getvdwxx(zkl, xkl, ykl, c66, s6, rv, vdw(3,3))
 !cccccc Ende VDWx ccccccccccccccccccccccccccccccc
             gamma=rkr*exp(alpha*r0**2)
 ! not better: *sqrt(abs(wb(kAtom,lAtom)))
             gmm=gamma*exp(-alpha*rkl2)
             hxx=gmm*xkl*xkl/rkl2-vdw(1,1)
             hxy=gmm*xkl*ykl/rkl2-vdw(1,2)
             hxz=gmm*xkl*zkl/rkl2-vdw(1,3)
             hyy=gmm*ykl*ykl/rkl2-vdw(2,2)
             hyz=gmm*ykl*zkl/rkl2-vdw(2,3)
             hzz=gmm*zkl*zkl/rkl2-vdw(3,3)
 !
             hess(ind(1,katom,1,katom))=hess(ind(1,katom,1,katom))+hxx
             hess(ind(2,katom,1,katom))=hess(ind(2,katom,1,katom))+hxy
             hess(ind(2,katom,2,katom))=hess(ind(2,katom,2,katom))+hyy
             hess(ind(3,katom,1,katom))=hess(ind(3,katom,1,katom))+hxz
             hess(ind(3,katom,2,katom))=hess(ind(3,katom,2,katom))+hyz
             hess(ind(3,katom,3,katom))=hess(ind(3,katom,3,katom))+hzz
 !
             hess(ind(1,katom,1,latom))=hess(ind(1,katom,1,latom))-hxx
             hess(ind(1,katom,2,latom))=hess(ind(1,katom,2,latom))-hxy
             hess(ind(1,katom,3,latom))=hess(ind(1,katom,3,latom))-hxz
             hess(ind(2,katom,1,latom))=hess(ind(2,katom,1,latom))-hxy
             hess(ind(2,katom,2,latom))=hess(ind(2,katom,2,latom))-hyy
             hess(ind(2,katom,3,latom))=hess(ind(2,katom,3,latom))-hyz
             hess(ind(3,katom,1,latom))=hess(ind(3,katom,1,latom))-hxz
             hess(ind(3,katom,2,latom))=hess(ind(3,katom,2,latom))-hyz
             hess(ind(3,katom,3,latom))=hess(ind(3,katom,3,latom))-hzz
 !
             hess(ind(1,latom,1,latom))=hess(ind(1,latom,1,latom))+hxx
             hess(ind(2,latom,1,latom))=hess(ind(2,latom,1,latom))+hxy
             hess(ind(2,latom,2,latom))=hess(ind(2,latom,2,latom))+hyy
             hess(ind(3,latom,1,latom))=hess(ind(3,latom,1,latom))+hxz
             hess(ind(3,latom,2,latom))=hess(ind(3,latom,2,latom))+hyz
             hess(ind(3,latom,3,latom))=hess(ind(3,latom,3,latom))+hzz
 !
  10         Continue
          End Do
  5       Continue
       End Do
 !
 !     Hessian for bending
 !
       Do matom = 1, natoms
          mr=itabrow(ianr(matom))
 !        If (mr.eq.0) Go To 20
          Do iatom = 1, natoms
            If (iatom.eq.matom) Go To 30
            ir=itabrow(ianr(iatom))
 !          If (ir.eq.0) Go To 30
            if(rcutoff(cart,iatom,matom)) cycle
 !          if(wb(iatom,matom).lt.wthr) cycle
            Do jatom = 1, iatom-1
             If (jatom.eq.matom) Go To 40
             jr=itabrow(ianr(jatom))
 !           If (jr.eq.0) Go To 40
             if(rcutoff(cart,jatom,iatom)) cycle
             if(rcutoff(cart,jatom,matom)) cycle
 !           if(wb(jatom,iatom).lt.wthr) cycle
 !           if(wb(jatom,matom).lt.wthr) cycle
             xmi=(cart(1,iatom)-cart(1,matom))
             ymi=(cart(2,iatom)-cart(2,matom))
             zmi=(cart(3,iatom)-cart(3,matom))
             rmi2 = xmi**2 + ymi**2 + zmi**2
             rmi=sqrt(rmi2)
             r0mi=rav(mr,ir)
             ami=aav(mr,ir)
 !
             xmj=(cart(1,jatom)-cart(1,matom))
             ymj=(cart(2,jatom)-cart(2,matom))
             zmj=(cart(3,jatom)-cart(3,matom))
             rmj2 = xmj**2 + ymj**2 + zmj**2
             rmj=sqrt(rmj2)
             r0mj=rav(mr,jr)
             amj=aav(mr,jr)
 !
 !---------- Test if zero angle
 !
             test=xmi*xmj+ymi*ymj+zmi*zmj
             test=test/(rmi*rmj)
             If (test.eq.one) Go To 40
 !
             xij=(cart(1,jatom)-cart(1,iatom))
             yij=(cart(2,jatom)-cart(2,iatom))
             zij=(cart(3,jatom)-cart(3,iatom))
             rij2 = xij**2 + yij**2 + zij**2
             rrij=sqrt(rij2)
 !
             alpha=rkf*exp((ami*r0mi**2+amj*r0mj**2))
 !
             r=sqrt(rmj2+rmi2)
             gij=alpha*exp(-(ami*rmi2+amj*rmj2))
 !           Write (*,*) ' gij=',gij
             rl2=(ymi*zmj-zmi*ymj)**2+(zmi*xmj-xmi*zmj)**2+ &
      &         (xmi*ymj-ymi*xmj)**2
 !hjw modified
             if(rl2.lt.1.d-14) then
               rl=0
             else
               rl=sqrt(rl2)
             end if
 !
             if ((rmj.gt.rzero).and.(rmi.gt.rzero).and. &
      &                                (rrij.gt.rzero)) Then
               sinphi=rl/(rmj*rmi)
               rmidotrmj=xmi*xmj+ymi*ymj+zmi*zmj
               cosphi=rmidotrmj/(rmj*rmi)
 !
 !-------------None linear case
 !
               If (sinphi.gt.rzero) Then
 !               Write (*,*) ' None linear case'
                 si(1)=(xmi/rmi*cosphi-xmj/rmj)/(rmi*sinphi)
                 si(2)=(ymi/rmi*cosphi-ymj/rmj)/(rmi*sinphi)
                 si(3)=(zmi/rmi*cosphi-zmj/rmj)/(rmi*sinphi)
                 sj(1)=(cosphi*xmj/rmj-xmi/rmi)/(rmj*sinphi)
                 sj(2)=(cosphi*ymj/rmj-ymi/rmi)/(rmj*sinphi)
                 sj(3)=(cosphi*zmj/rmj-zmi/rmi)/(rmj*sinphi)
                 sm(1)=-si(1)-sj(1)
                 sm(2)=-si(2)-sj(2)
                 sm(3)=-si(3)-sj(3)
                 Do icoor=1,3
                    Do jcoor=1,3
                     If (matom.gt.iatom) Then
                        hess(ind(icoor,matom,jcoor,iatom))= &
      &                        hess(ind(icoor,matom,jcoor,iatom)) &
      &                        +gij*sm(icoor)*si(jcoor)
                     else
                       hess(ind(icoor,iatom,jcoor,matom))= &
      &                        hess(ind(icoor,iatom,jcoor,matom)) &
      &                        +gij*si(icoor)*sm(jcoor)
                     End If
                     If (matom.gt.jatom) Then
                         hess(ind(icoor,matom,jcoor,jatom))= &
      &                        hess(ind(icoor,matom,jcoor,jatom)) &
      &                        +gij*sm(icoor)*sj(jcoor)
                     else
                       hess(ind(icoor,jatom,jcoor,matom))= &
      &                        hess(ind(icoor,jatom,jcoor,matom)) &
      &                        +gij*sj(icoor)*sm(jcoor)
                     End If
                     If (iatom.gt.jatom) Then
                         hess(ind(icoor,iatom,jcoor,jatom))= &
      &                        hess(ind(icoor,iatom,jcoor,jatom)) &
      &                        +gij*si(icoor)*sj(jcoor)
                      else
                         hess(ind(icoor,jatom,jcoor,iatom))= &
      &                        hess(ind(icoor,jatom,jcoor,iatom)) &
      &                        +gij*sj(icoor)*si(jcoor)
                      End If
                    End Do
                 End Do
                 Do icoor=1,3
                   Do jcoor=1,icoor
                     hess(ind(icoor,iatom,jcoor,iatom))= &
      &                        hess(ind(icoor,iatom,jcoor,iatom)) &
      &                        +gij*si(icoor)*si(jcoor)
                     hess(ind(icoor,matom,jcoor,matom))= &
      &                        hess(ind(icoor,matom,jcoor,matom)) &
      &                        +gij*sm(icoor)*sm(jcoor)
                     hess(ind(icoor,jatom,jcoor,jatom))= &
      &                        hess(ind(icoor,jatom,jcoor,jatom)) &
      &                        +gij*sj(icoor)*sj(jcoor)
 !
                   End Do
                 End Do
               Else
 !
 !----------------Linear case
 !
 !               Write (*,*) 'linear case'
                     if ((abs(ymi).gt.rzero).or. &
      &                 (abs(xmi).gt.rzero)) Then
                       x(1)=-ymi
                       y(1)=xmi
                       z(1)=zero
                       x(2)=-xmi*zmi
                       y(2)=-ymi*zmi
                       z(2)=xmi*xmi+ymi*ymi
                     Else
                       x(1)=one
                       y(1)=zero
                       z(1)=zero
                       x(2)=zero
                       y(2)=one
                       z(2)=zero
                     End If
                     Do i=1,2
                      r1=sqrt(x(i)**2+y(i)**2+z(i)**2)
                      costhetax=x(i)/r1
                      costhetay=y(i)/r1
                      costhetaz=z(i)/r1
                      si(1)=-costhetax/rmi
                      si(2)=-costhetay/rmi
                      si(3)=-costhetaz/rmi
                      sj(1)=-costhetax/rmj
                      sj(2)=-costhetay/rmj
                      sj(3)=-costhetaz/rmj
                      sm(1)=-(si(1)+sj(1))
                      sm(2)=-(si(2)+sj(2))
                      sm(3)=-(si(3)+sj(3))
 !
                      Do icoor=1,3
                        Do jcoor=1,3
                         If (matom.gt.iatom) Then
                           hess(ind(icoor,matom,jcoor,iatom))= &
      &                        hess(ind(icoor,matom,jcoor,iatom)) &
      &                         +gij*sm(icoor)*si(jcoor)
                         else
                            hess(ind(icoor,iatom,jcoor,matom))= &
      &                        hess(ind(icoor,iatom,jcoor,matom)) &
      &                         +gij*si(icoor)*sm(jcoor)
                         End If
                         If (matom.gt.jatom) Then
                           hess(ind(icoor,matom,jcoor,jatom))= &
      &                        hess(ind(icoor,matom,jcoor,jatom)) &
      &                         +gij*sm(icoor)*sj(jcoor)
                         else
                           hess(ind(icoor,jatom,jcoor,matom))= &
      &                        hess(ind(icoor,jatom,jcoor,matom)) &
      &                         +gij*sj(icoor)*sm(jcoor)
                         End If
                         If (iatom.gt.jatom) Then
                            hess(ind(icoor,iatom,jcoor,jatom))= &
      &                        hess(ind(icoor,iatom,jcoor,jatom)) &
      &                         +gij*si(icoor)*sj(jcoor)
                         else
                            hess(ind(icoor,jatom,jcoor,iatom))= &
      &                        hess(ind(icoor,jatom,jcoor,iatom)) &
      &                         +gij*sj(icoor)*si(jcoor)
                         End If
                        End Do
                      End Do
                      Do icoor=1,3
                        Do jcoor=1,icoor
                          hess(ind(icoor,iatom,jcoor,iatom))= &
      &                        hess(ind(icoor,iatom,jcoor,iatom)) &
      &                         +gij*si(icoor)*si(jcoor)
                          hess(ind(icoor,matom,jcoor,matom))= &
      &                        hess(ind(icoor,matom,jcoor,matom)) &
      &                         +gij*sm(icoor)*sm(jcoor)
                          hess(ind(icoor,jatom,jcoor,jatom))= &
      &                         hess(ind(icoor,jatom,jcoor,jatom)) &
      &                         +gij*sj(icoor)*sj(jcoor)
                        End Do
                      End Do
                  End Do
               End If
             End If
 !
  40         Continue
         End Do
  30     Continue
        End Do
  20    Continue
       End Do
 !
 !     Hessian for torsion
 !
       Do jatom = 1,natoms
         jr=itabrow(ianr(jatom))
 !       If (jr.eq.0) Go To 444
 !
         Call dcopy(3,cart(1,jatom),1,xyz(1,2),1)
 !
         Do katom = 1, natoms
            If (katom.eq.jatom) Go To 111
            kr=itabrow(ianr(katom))
 !          If (kr.eq.0) Go To 111
            if(rcutoff(cart,katom,jatom)) cycle
 !          if(wb(katom,jatom).lt.wthr) cycle
 !
            Call dcopy(3,cart(1,katom),1,xyz(1,3),1)
 !
            Do iatom = 1, natoms
               ij_=natoms*(jatom-1)+iatom
               If (iatom.eq.jatom) Go To 333
               If (iatom.eq.katom) Go To 333
               ir=itabrow(ianr(iatom))
 !             If (ir.eq.0) Go To 333
 !
               if(rcutoff(cart,iatom,katom)) cycle
               if(rcutoff(cart,iatom,jatom)) cycle
 !             if(wb(iatom,katom).lt.wthr) cycle
 !             if(wb(iatom,jatom).lt.wthr) cycle
               Call dcopy(3,cart(1,iatom),1,xyz(1,1),1)
 !
               Do latom = 1, natoms
                  lk_=natoms*(katom-1)+latom
                  If (ij_.le.lk_) Go To 222
                  If (latom.eq.iatom) Go To 222
                  If (latom.eq.jatom) Go To 222
                  If (latom.eq.katom) Go To 222
                  lr=itabrow(ianr(latom))
 !                If (lr.eq.0) Go To 222
 !
                  if(rcutoff(cart,latom,iatom)) cycle
                  if(rcutoff(cart,latom,katom)) cycle
                  if(rcutoff(cart,latom,jatom)) cycle
 !                if(wb(latom,iatom).lt.wthr) cycle
 !                if(wb(latom,katom).lt.wthr) cycle
 !                if(wb(latom,jatom).lt.wthr) cycle
                  Call dcopy(3,cart(1,latom),1,xyz(1,4),1)
 !
                  rij(1)=cart(1,iatom)-cart(1,jatom)
                  rij(2)=cart(2,iatom)-cart(2,jatom)
                  rij(3)=cart(3,iatom)-cart(3,jatom)
                  rij0=rav(ir,jr)**2
                  aij =aav(ir,jr)
 !
                  rjk(1)=cart(1,jatom)-cart(1,katom)
                  rjk(2)=cart(2,jatom)-cart(2,katom)
                  rjk(3)=cart(3,jatom)-cart(3,katom)
                  rjk0=rav(jr,kr)**2
                  ajk =aav(jr,kr)
 !
                  rkl(1)=cart(1,katom)-cart(1,latom)
                  rkl(2)=cart(2,katom)-cart(2,latom)
                  rkl(3)=cart(3,katom)-cart(3,latom)
                  rkl0=rav(kr,lr)**2
                  akl =aav(kr,lr)
 !
                  rij2=rij(1)**2+rij(2)**2+rij(3)**2
                  rjk2=rjk(1)**2+rjk(2)**2+rjk(3)**2
                  rkl2=rkl(1)**2+rkl(2)**2+rkl(3)**2
 !              Allow only angles in the range of 35-145
                a35 = (35.0d0/180.d0)* pi
                cosfi_max=cos(a35)
                cosfi2=(rij(1)*rjk(1)+rij(2)*rjk(2)+rij(3)*rjk(3)) &
      &               /sqrt(rij2*rjk2)
                If (abs(cosfi2).gt.cosfi_max) Go To 222
                cosfi3=(rkl(1)*rjk(1)+rkl(2)*rjk(2)+rkl(3)*rjk(3)) &
      &               /sqrt(rkl2*rjk2)
                If (abs(cosfi3).gt.cosfi_max) Go To 222
                beta=rkt* &
      &                       exp( (aij*rij0+ajk*rjk0+akl*rkl0))
                tij=beta*exp(-(aij*rij2+ajk*rjk2+akl*rkl2))
                Call trsn(xyz,4,tau,c,.false.,.false.,'        ', &
      &                  dum,.false.)
                Call dcopy(3,c(1,1),1,si,1)
                Call dcopy(3,c(1,2),1,sj,1)
                Call dcopy(3,c(1,3),1,sk,1)
                Call dcopy(3,c(1,4),1,sl,1)
 !
 !-------------Off diagonal block
 !
               Do icoor=1,3
                 Do jcoor=1,3
                  hess(ind(icoor,iatom,jcoor,jatom))= &
      &           hess(ind(icoor,iatom,jcoor,jatom)) &
      &            +tij*si(icoor) * sj(jcoor)
                  hess(ind(icoor,iatom,jcoor,katom))= &
      &           hess(ind(icoor,iatom,jcoor,katom)) &
      &            +tij*si(icoor) * sk(jcoor)
                  hess(ind(icoor,iatom,jcoor,latom))= &
      &           hess(ind(icoor,iatom,jcoor,latom)) &
      &            +tij*si(icoor) * sl(jcoor)
                  hess(ind(icoor,jatom,jcoor,katom))= &
      &           hess(ind(icoor,jatom,jcoor,katom)) &
      &            +tij*sj(icoor) * sk(jcoor)
                  hess(ind(icoor,jatom,jcoor,latom))= &
      &           hess(ind(icoor,jatom,jcoor,latom)) &
      &            +tij*sj(icoor) * sl(jcoor)
                  hess(ind(icoor,katom,jcoor,latom))= &
      &           hess(ind(icoor,katom,jcoor,latom)) &
      &            +tij*sk(icoor) * sl(jcoor)
                 End Do
               End Do
 !
 !-------------Diagonal block
 !
               Do icoor=1,3
                 Do jcoor=1,icoor
                  hess(ind(icoor,iatom,jcoor,iatom))= &
      &           hess(ind(icoor,iatom,jcoor,iatom)) &
      &            +tij*si(icoor) * si(jcoor)
                  hess(ind(icoor,jatom,jcoor,jatom))= &
      &           hess(ind(icoor,jatom,jcoor,jatom)) &
      &            +tij*sj(icoor) * sj(jcoor)
                  hess(ind(icoor,katom,jcoor,katom))= &
      &           hess(ind(icoor,katom,jcoor,katom)) &
      &            +tij*sk(icoor) * sk(jcoor)
                  hess(ind(icoor,latom,jcoor,latom))= &
      &           hess(ind(icoor,latom,jcoor,latom)) &
      &            +tij*sl(icoor) * sl(jcoor)
 !
                  End Do
                End Do
 222            Continue
              End Do        ! lAtom
 333          Continue
            End Do          ! iAtom
 111        Continue
         End Do             ! kAtom
 444     Continue
       End Do               ! jAtom
       Return
References getvdwxx(), getvdwxy(), itabrow(), and trsn().
Referenced by xtb_optimizer::modhes().
getqqxx()
subroutine getqqxx (real*8 dx, real*8 qq, real*8 c6, real*8 r, real*8 r2, real*8 r3, real*8 rpa, real*8 r02, real*8 d2)
Definition at line 3134 of file model_hessian.f90.
       implicit none
       real*8 dx,qq,c6,r,r2,r3,rpa,r02,d2
       real*8 rpa2,dx2,ar6,r6,r8
 !     Coulomb part
       rpa2=rpa**2
       dx2 = dx**2
       d2  = qq*(2.d0*dx2/(r2*rpa*rpa2) + dx2/(r3*rpa2) - 1.d0/(r*rpa2))
 !     disp part
       r6  = r3*r3
       r8  = r6*r2
       ar6 = r02**3+r6
       d2  = d2 + c6*(dx2*72.d0*r8/ar6**3 - dx2*24.d0*r2/ar6**2 &
      &         - 6.d0*r2*r2/ar6**2)
Referenced by gff_ddvopt().
getqqxy()
subroutine getqqxy (real*8 dx, real*8 dy, real*8 qq, real*8 c6, real*8 r, real*8 r2, real*8 r3, real*8 rpa, real*8 r02, real*8 d2)
Definition at line 3153 of file model_hessian.f90.
       implicit none
       real*8 dx,dy,qq,c6,r,r2,r3,rpa,r02,d2
       real*8 rpa2,r6,r8,ar6
 !     Coulomb part
       rpa2=rpa**2
       d2  =qq*(2.d0*dx*dy/(r2*rpa*rpa2) + dx*dy/(r3*rpa2))
 !     disp part
       r6  = r3*r3
       r8  = r6*r2
       ar6 = r02**3+r6
       d2  = d2 + c6*(dx*dy*72.d0*r8/ar6**3 - dx*dy*24.d0*r2/ar6**2)
Referenced by gff_ddvopt().
gff_ddvopt()
subroutine gff_ddvopt (real*8, dimension(3,natoms) Cart, nAtoms, real*8, dimension((3*natoms)*(3*natoms+1)/2) Hess, integer, dimension(natoms) at, real*8 s6, type(tgffdata), intent(in) param, type(tgfftopology), intent(in) topo)
Definition at line 2655 of file model_hessian.f90.
       use xtb_gfnff_data, only : tgffdata
       use xtb_gfnff_topology, only : tgfftopology
       use xtb_type_timer
       Implicit Real*8 (a-h, o-z)
       type(TGFFData), intent(in) :: param
       type(TGFFTopology), intent(in) :: topo
       Integer at(nAtoms)
       real*8 cart(3,natoms)
       real*8 hess((3*natoms)*(3*natoms+1)/2)
       real*8 s6
 !     charges qa taken from gffcom
       real*8 rij(3),rjk(3),rkl(3),&
      &       si(3),sj(3),sk(3),&
      &       sl(3),sm(3),x(2),y(2),z(2),&
      &       xyz(3,4), c(3,4), dum(3,4,3,4)
       real*8 rav(3,3), aav(3,3),rkr, rkf
       Integer iANr(nAtoms)
       logical profile
       Data rav/1.3500d+00,2.1000d+00,2.5300d+00,&
      &         2.1000d+00,2.8700d+00,3.4000d+00,&
      &         2.5300d+00,3.4000d+00,3.4000d+00/
       Data aav/1.0000d+00,0.3949d+00,0.3949d+00,&
      &         0.3949d+00,0.2800d+00,0.2800d+00,&
      &         0.3949d+00,0.2800d+00,0.2800d+00/
 !     Data rkr,rkf,rkt/0.4500D+00,0.1500D+00,0.5000D-02/ ! org
       Data rkr,rkf,rkt/0.4500d+00,0.3000d+00,0.75000  /  ! adjusted to account for redundant angles in old version
 !cc VDWx-Parameters (Grimme) used for vdw-correction of model hessian
       real*8 c6(54),c66
 ! NOT USED ANYMORE (BJ instead)
 !     data vander &
 ! H, He
 !    &     /0.91d0,0.92d0,&
 ! Li-Ne
 !    &      0.75d0,1.28d0,1.35d0,1.32d0,1.27d0,1.22d0,1.17d0,1.13d0,&
 ! Na-Ar
 !    &      1.04d0,1.24d0,1.49d0,1.56d0,1.55d0,1.53d0,1.49d0,1.45d0,&
 ! K, Ca
 !    &      1.35d0,1.34d0,&
 ! Sc-Zn
 !    &      1.42d0,1.42d0,1.42d0,1.42d0,1.42d0,&
 !    &      1.42d0,1.42d0,1.42d0,1.42d0,1.42d0,&
 ! Ga-Kr
 !    &      1.50d0,1.57d0,1.60d0,1.61d0,1.59d0,1.57d0,&
 ! Rb, Sr
 !    &      1.48d0,1.46d0,&
 ! Y-Cd
 !    &      1.49d0,1.49d0,1.49d0,1.49d0,1.49d0,&
 !    &      1.49d0,1.49d0,1.49d0,1.49d0,1.49d0,&
 ! In, Sn, Sb, Te, I, Xe
 !    &      1.52d0,1.64d0,1.71d0,1.72d0,1.72d0,1.71d0/
       real*8 zero, one, two, three, four, five, six, seven,&
      &       eight, rnine, ten, half, pi, sqrtp2, twop34,&
      &       twop54, one2c2
       parameter(zero =0.0d0, one  =1.0d0, two=2.0d0, three=3.0d0,&
      &          four =4.0d0, five =5.0d0, six=6.0d0, seven=7.0d0,&
      &          eight=8.0d0, rnine=9.0d0, ten=1.0d1, half=0.5d0,&
      &          pi    =3.141592653589793d0,&
      &          sqrtp2=0.8862269254527579d0,&
      &          twop34=0.2519794355383808d0,&
      &          twop54=5.914967172795612d0,&
      &          one2c2=0.2662567690426443d-04)
       type(tb_timer) :: timer
 !     inline fct
       lina(i,j)=min(i,j)+max(i,j)*(max(i,j)-1)/2
       ixyz(i,iatom) = (iatom-1)*3 + i
       jnd(i,j) = i*(i-1)/2 +j
       ind(i,iatom,j,jatom)=jnd(max(ixyz(i,iatom),ixyz(j,jatom)),&
      &                         min(ixyz(i,iatom),ixyz(j,jatom)))
 !     map heavy atoms to Z<=54
       do i=1,natoms
          ianr(i)=at(i)
          if(at(i).gt.54) ianr(i)=at(i) - 18
          if(at(i).gt.72) ianr(i)=at(i) - 32
          if(at(i).gt.56.and.at(i).lt.72) ianr(i)=39 ! set LNs to Y
       enddo
       profile=.false.
       if (profile) call timer%new(3,.false.)
       if (profile) call timer%measure(1,'bond/vdw/qq')
 !     D2 C6
       c6( 1)=0.14; c6( 2)=0.08; c6( 3)=1.61; c6( 4)=1.61; c6( 5)=3.13
       c6( 6)=1.75; c6( 7)=1.23; c6( 8)=0.70; c6( 9)=0.75; c6(10)=0.63
       c6(11)=5.71; c6(12)=5.71; c6(13)=10.79; c6(14)=9.23; c6(15)=7.84
       c6(16)=5.57; c6(17)=5.07; c6(18)=4.61; c6(19:30)=10.8; c6(31)=16.99
       c6(32)=17.10; c6(33)=16.37; c6(34)=12.64; c6(35)=12.47; c6(36)=12.01
       c6(37:48)=24.67; c6(49)=37.32; c6(50)=38.71; c6(51)=38.44
       c6(52)=31.74; c6(53)=31.50; c6(54)=29.99
 !hjw threshold reduced
       rzero=1.0d-10
       n3=3*natoms
 !     Hess = 0.0d0
 !
 !     Hessian for tension
 !
       do ibond=1,topo%nbond
          katom=topo%blist(1,ibond)
          latom=topo%blist(2,ibond)
          kr=itabrow(ianr(katom))
          lr=itabrow(ianr(latom))
             xkl=cart(1,katom)-cart(1,latom)
             ykl=cart(2,katom)-cart(2,latom)
             zkl=cart(3,katom)-cart(3,latom)
             rkl2 = xkl**2 + ykl**2 + zkl**2
             r0=rav(kr,lr)
             alpha=aav(kr,lr)
             gmm=exp(-alpha*rkl2)*rkr*exp(alpha*r0**2)
             hxx=gmm*xkl*xkl/rkl2
             hxy=gmm*xkl*ykl/rkl2
             hxz=gmm*xkl*zkl/rkl2
             hyy=gmm*ykl*ykl/rkl2
             hyz=gmm*ykl*zkl/rkl2
             hzz=gmm*zkl*zkl/rkl2
             hess(ind(1,katom,1,katom))=hess(ind(1,katom,1,katom))+hxx
             hess(ind(2,katom,1,katom))=hess(ind(2,katom,1,katom))+hxy
             hess(ind(2,katom,2,katom))=hess(ind(2,katom,2,katom))+hyy
             hess(ind(3,katom,1,katom))=hess(ind(3,katom,1,katom))+hxz
             hess(ind(3,katom,2,katom))=hess(ind(3,katom,2,katom))+hyz
             hess(ind(3,katom,3,katom))=hess(ind(3,katom,3,katom))+hzz
             hess(ind(1,katom,1,latom))=hess(ind(1,katom,1,latom))-hxx
             hess(ind(1,katom,2,latom))=hess(ind(1,katom,2,latom))-hxy
             hess(ind(1,katom,3,latom))=hess(ind(1,katom,3,latom))-hxz
             hess(ind(2,katom,1,latom))=hess(ind(2,katom,1,latom))-hxy
             hess(ind(2,katom,2,latom))=hess(ind(2,katom,2,latom))-hyy
             hess(ind(2,katom,3,latom))=hess(ind(2,katom,3,latom))-hyz
             hess(ind(3,katom,1,latom))=hess(ind(3,katom,1,latom))-hxz
             hess(ind(3,katom,2,latom))=hess(ind(3,katom,2,latom))-hyz
             hess(ind(3,katom,3,latom))=hess(ind(3,katom,3,latom))-hzz
             hess(ind(1,latom,1,latom))=hess(ind(1,latom,1,latom))+hxx
             hess(ind(2,latom,1,latom))=hess(ind(2,latom,1,latom))+hxy
             hess(ind(2,latom,2,latom))=hess(ind(2,latom,2,latom))+hyy
             hess(ind(3,latom,1,latom))=hess(ind(3,latom,1,latom))+hxz
             hess(ind(3,latom,2,latom))=hess(ind(3,latom,2,latom))+hyz
             hess(ind(3,latom,3,latom))=hess(ind(3,latom,3,latom))+hzz
       End do
 !
 !     Hessian for Coulomb+dispersion
 !
       do katom=1,natoms
          do latom=1,katom-1
             xkl=cart(1,katom)-cart(1,latom)
             ykl=cart(2,katom)-cart(2,latom)
             zkl=cart(3,katom)-cart(3,latom)
             rkl2 = xkl**2 + ykl**2 + zkl**2
             if(rkl2.gt.1600.d0) cycle
             c66=-s6*sqrt(c6(ianr(katom))*c6(ianr(latom))) ! D2 value
             rr=sqrt(rkl2)
             rr3=rr*rkl2
             r02=param%d3r0(lina(at(katom),at(latom)))
             rrpa=rr+sqrt(r02) ! qq damping with BJ radius
             cqq=2.0d0*topo%qa(katom)*topo%qa(latom) ! a bit upscaled
             call getqqxx(xkl,    cqq,c66,rr,rkl2,rr3,rrpa,r02,hxx)
             call getqqxy(xkl,ykl,cqq,c66,rr,rkl2,rr3,rrpa,r02,hxy)
             call getqqxy(xkl,zkl,cqq,c66,rr,rkl2,rr3,rrpa,r02,hxz)
             call getqqxx(ykl,    cqq,c66,rr,rkl2,rr3,rrpa,r02,hyy)
             call getqqxy(ykl,zkl,cqq,c66,rr,rkl2,rr3,rrpa,r02,hyz)
             call getqqxx(zkl,    cqq,c66,rr,rkl2,rr3,rrpa,r02,hzz)
             hess(ind(1,katom,1,katom))=hess(ind(1,katom,1,katom))+hxx
             hess(ind(2,katom,1,katom))=hess(ind(2,katom,1,katom))+hxy
             hess(ind(2,katom,2,katom))=hess(ind(2,katom,2,katom))+hyy
             hess(ind(3,katom,1,katom))=hess(ind(3,katom,1,katom))+hxz
             hess(ind(3,katom,2,katom))=hess(ind(3,katom,2,katom))+hyz
             hess(ind(3,katom,3,katom))=hess(ind(3,katom,3,katom))+hzz
             hess(ind(1,katom,1,latom))=hess(ind(1,katom,1,latom))-hxx
             hess(ind(1,katom,2,latom))=hess(ind(1,katom,2,latom))-hxy
             hess(ind(1,katom,3,latom))=hess(ind(1,katom,3,latom))-hxz
             hess(ind(2,katom,1,latom))=hess(ind(2,katom,1,latom))-hxy
             hess(ind(2,katom,2,latom))=hess(ind(2,katom,2,latom))-hyy
             hess(ind(2,katom,3,latom))=hess(ind(2,katom,3,latom))-hyz
             hess(ind(3,katom,1,latom))=hess(ind(3,katom,1,latom))-hxz
             hess(ind(3,katom,2,latom))=hess(ind(3,katom,2,latom))-hyz
             hess(ind(3,katom,3,latom))=hess(ind(3,katom,3,latom))-hzz
             hess(ind(1,latom,1,latom))=hess(ind(1,latom,1,latom))+hxx
             hess(ind(2,latom,1,latom))=hess(ind(2,latom,1,latom))+hxy
             hess(ind(2,latom,2,latom))=hess(ind(2,latom,2,latom))+hyy
             hess(ind(3,latom,1,latom))=hess(ind(3,latom,1,latom))+hxz
             hess(ind(3,latom,2,latom))=hess(ind(3,latom,2,latom))+hyz
             hess(ind(3,latom,3,latom))=hess(ind(3,latom,3,latom))+hzz
          End Do
       End Do
       if (profile) call timer%measure(1)
 !
 !     Hessian for bending
 !
       if (profile) call timer%measure(2,'bend')
       do iangl=1,topo%nangl
          matom=topo%alist(1,iangl)
          iatom=topo%alist(2,iangl)
          jatom=topo%alist(3,iangl)
          mr=itabrow(ianr(matom))
          ir=itabrow(ianr(iatom))
          jr=itabrow(ianr(jatom))
             xmi=(cart(1,iatom)-cart(1,matom))
             ymi=(cart(2,iatom)-cart(2,matom))
             zmi=(cart(3,iatom)-cart(3,matom))
             rmi2 = xmi**2 + ymi**2 + zmi**2
             rmi=sqrt(rmi2)
             r0mi=rav(mr,ir)
             ami=aav(mr,ir)
             xmj=(cart(1,jatom)-cart(1,matom))
             ymj=(cart(2,jatom)-cart(2,matom))
             zmj=(cart(3,jatom)-cart(3,matom))
             rmj2 = xmj**2 + ymj**2 + zmj**2
             rmj=sqrt(rmj2)
             r0mj=rav(mr,jr)
             amj=aav(mr,jr)
             xij=(cart(1,jatom)-cart(1,iatom))
             yij=(cart(2,jatom)-cart(2,iatom))
             zij=(cart(3,jatom)-cart(3,iatom))
             rij2 = xij**2 + yij**2 + zij**2
             rrij=sqrt(rij2)
             alpha=rkf*exp((ami*r0mi**2+amj*r0mj**2))
             r=sqrt(rmj2+rmi2)
             gij=alpha*exp(-(ami*rmi2+amj*rmj2))
             rl2=(ymi*zmj-zmi*ymj)**2+(zmi*xmj-xmi*zmj)**2+&
      &         (xmi*ymj-ymi*xmj)**2
 !hjw modified
             if(rl2.lt.1.d-14) then
               rl=0
             else
               rl=sqrt(rl2)
             end if
             if ((rmj.gt.rzero).and.(rmi.gt.rzero).and.&
      &                                (rrij.gt.rzero)) Then
               sinphi=rl/(rmj*rmi)
               rmidotrmj=xmi*xmj+ymi*ymj+zmi*zmj
               cosphi=rmidotrmj/(rmj*rmi)
 !-------------None linear case
               If (sinphi.gt.rzero) Then
                 si(1)=(xmi/rmi*cosphi-xmj/rmj)/(rmi*sinphi)
                 si(2)=(ymi/rmi*cosphi-ymj/rmj)/(rmi*sinphi)
                 si(3)=(zmi/rmi*cosphi-zmj/rmj)/(rmi*sinphi)
                 sj(1)=(cosphi*xmj/rmj-xmi/rmi)/(rmj*sinphi)
                 sj(2)=(cosphi*ymj/rmj-ymi/rmi)/(rmj*sinphi)
                 sj(3)=(cosphi*zmj/rmj-zmi/rmi)/(rmj*sinphi)
                 sm(1)=-si(1)-sj(1)
                 sm(2)=-si(2)-sj(2)
                 sm(3)=-si(3)-sj(3)
                 Do icoor=1,3
                    Do jcoor=1,3
                     If (matom.gt.iatom) Then
                        hess(ind(icoor,matom,jcoor,iatom))=&
      &                        hess(ind(icoor,matom,jcoor,iatom))&
      &                        +gij*sm(icoor)*si(jcoor)
                     else
                       hess(ind(icoor,iatom,jcoor,matom))=&
      &                        hess(ind(icoor,iatom,jcoor,matom))&
      &                        +gij*si(icoor)*sm(jcoor)
                     End If
                     If (matom.gt.jatom) Then
                         hess(ind(icoor,matom,jcoor,jatom))=&
      &                        hess(ind(icoor,matom,jcoor,jatom))&
      &                        +gij*sm(icoor)*sj(jcoor)
                     else
                       hess(ind(icoor,jatom,jcoor,matom))=&
      &                        hess(ind(icoor,jatom,jcoor,matom))&
      &                        +gij*sj(icoor)*sm(jcoor)
                     End If
                     If (iatom.gt.jatom) Then
                         hess(ind(icoor,iatom,jcoor,jatom))=&
      &                        hess(ind(icoor,iatom,jcoor,jatom))&
      &                        +gij*si(icoor)*sj(jcoor)
                      else
                         hess(ind(icoor,jatom,jcoor,iatom))=&
      &                        hess(ind(icoor,jatom,jcoor,iatom))&
      &                        +gij*sj(icoor)*si(jcoor)
                      End If
                    End Do
                 End Do
                 Do icoor=1,3
                   Do jcoor=1,icoor
                     hess(ind(icoor,iatom,jcoor,iatom))=&
      &                        hess(ind(icoor,iatom,jcoor,iatom))&
      &                        +gij*si(icoor)*si(jcoor)
                     hess(ind(icoor,matom,jcoor,matom))=&
      &                        hess(ind(icoor,matom,jcoor,matom))&
      &                        +gij*sm(icoor)*sm(jcoor)
                     hess(ind(icoor,jatom,jcoor,jatom))=&
      &                        hess(ind(icoor,jatom,jcoor,jatom))&
      &                        +gij*sj(icoor)*sj(jcoor)
                   End Do
                 End Do
               Else
 !----------------Linear case
                     if ((abs(ymi).gt.rzero).or.(abs(xmi).gt.rzero)) Then
                       x(1)=-ymi
                       y(1)=xmi
                       z(1)=zero
                       x(2)=-xmi*zmi
                       y(2)=-ymi*zmi
                       z(2)=xmi*xmi+ymi*ymi
                     Else
                       x(1)=one
                       y(1)=zero
                       z(1)=zero
                       x(2)=zero
                       y(2)=one
                       z(2)=zero
                     End If
                     Do i=1,2
                      r1=sqrt(x(i)**2+y(i)**2+z(i)**2)
                      costhetax=x(i)/r1
                      costhetay=y(i)/r1
                      costhetaz=z(i)/r1
                      si(1)=-costhetax/rmi
                      si(2)=-costhetay/rmi
                      si(3)=-costhetaz/rmi
                      sj(1)=-costhetax/rmj
                      sj(2)=-costhetay/rmj
                      sj(3)=-costhetaz/rmj
                      sm(1)=-(si(1)+sj(1))
                      sm(2)=-(si(2)+sj(2))
                      sm(3)=-(si(3)+sj(3))
                      Do icoor=1,3
                        Do jcoor=1,3
                         If (matom.gt.iatom) Then
                           hess(ind(icoor,matom,jcoor,iatom))=&
      &                        hess(ind(icoor,matom,jcoor,iatom))&
      &                         +gij*sm(icoor)*si(jcoor)
                         else
                            hess(ind(icoor,iatom,jcoor,matom))=&
      &                        hess(ind(icoor,iatom,jcoor,matom))&
      &                         +gij*si(icoor)*sm(jcoor)
                         End If
                         If (matom.gt.jatom) Then
                           hess(ind(icoor,matom,jcoor,jatom))=&
      &                        hess(ind(icoor,matom,jcoor,jatom))&
      &                         +gij*sm(icoor)*sj(jcoor)
                         else
                           hess(ind(icoor,jatom,jcoor,matom))=&
      &                        hess(ind(icoor,jatom,jcoor,matom))&
      &                         +gij*sj(icoor)*sm(jcoor)
                         End If
                         If (iatom.gt.jatom) Then
                            hess(ind(icoor,iatom,jcoor,jatom))=&
      &                        hess(ind(icoor,iatom,jcoor,jatom))&
      &                         +gij*si(icoor)*sj(jcoor)
                         else
                            hess(ind(icoor,jatom,jcoor,iatom))=&
      &                        hess(ind(icoor,jatom,jcoor,iatom))&
      &                         +gij*sj(icoor)*si(jcoor)
                         End If
                        End Do
                      End Do
                      Do icoor=1,3
                        Do jcoor=1,icoor
                          hess(ind(icoor,iatom,jcoor,iatom))=&
      &                        hess(ind(icoor,iatom,jcoor,iatom))&
      &                         +gij*si(icoor)*si(jcoor)
                          hess(ind(icoor,matom,jcoor,matom))=&
      &                        hess(ind(icoor,matom,jcoor,matom))&
      &                         +gij*sm(icoor)*sm(jcoor)
                          hess(ind(icoor,jatom,jcoor,jatom))=&
      &                         hess(ind(icoor,jatom,jcoor,jatom))&
      &                         +gij*sj(icoor)*sj(jcoor)
                        End Do
                      End Do
                  End Do
               End If
             End If
       End Do ! bend list
       if (profile) call timer%measure(2)
 !
 !     Hessian for torsion
 !
       if (profile) call timer%measure(3,'torsion')
       do itors=1,topo%ntors
          iatom=topo%tlist(3,itors)
          jatom=topo%tlist(1,itors)
          katom=topo%tlist(2,itors)
          latom=topo%tlist(4,itors)
                  ir=itabrow(ianr(iatom))
                  jr=itabrow(ianr(jatom))
                  kr=itabrow(ianr(katom))
                  lr=itabrow(ianr(latom))
                  Call dcopy(3,cart(1,iatom),1,xyz(1,1),1)
                  Call dcopy(3,cart(1,jatom),1,xyz(1,2),1)
                  Call dcopy(3,cart(1,katom),1,xyz(1,3),1)
                  Call dcopy(3,cart(1,latom),1,xyz(1,4),1)
                  rij(1)=cart(1,iatom)-cart(1,jatom)
                  rij(2)=cart(2,iatom)-cart(2,jatom)
                  rij(3)=cart(3,iatom)-cart(3,jatom)
                  rij0=rav(ir,jr)**2
                  aij =aav(ir,jr)
                  rjk(1)=cart(1,jatom)-cart(1,katom)
                  rjk(2)=cart(2,jatom)-cart(2,katom)
                  rjk(3)=cart(3,jatom)-cart(3,katom)
                  rjk0=rav(jr,kr)**2
                  ajk =aav(jr,kr)
                  rkl(1)=cart(1,katom)-cart(1,latom)
                  rkl(2)=cart(2,katom)-cart(2,latom)
                  rkl(3)=cart(3,katom)-cart(3,latom)
                  rkl0=rav(kr,lr)**2
                  akl =aav(kr,lr)
                  rij2=rij(1)**2+rij(2)**2+rij(3)**2
                  rjk2=rjk(1)**2+rjk(2)**2+rjk(3)**2
                  rkl2=rkl(1)**2+rkl(2)**2+rkl(3)**2
                beta=rkt*exp( (aij*rij0+ajk*rjk0+akl*rkl0))
                tij=beta*exp(-(aij*rij2+ajk*rjk2+akl*rkl2))
                Call trsn(xyz,4,tau,c,.false.,.false.,'        ',dum,.false.)
                Call dcopy(3,c(1,1),1,si,1)
                Call dcopy(3,c(1,2),1,sj,1)
                Call dcopy(3,c(1,3),1,sk,1)
                Call dcopy(3,c(1,4),1,sl,1)
 !-------------Off diagonal block
               Do icoor=1,3
                 Do jcoor=1,3
                  hess(ind(icoor,iatom,jcoor,jatom))=&
      &           hess(ind(icoor,iatom,jcoor,jatom))&
      &            +tij*si(icoor) * sj(jcoor)
                  hess(ind(icoor,iatom,jcoor,katom))=&
      &           hess(ind(icoor,iatom,jcoor,katom))&
      &            +tij*si(icoor) * sk(jcoor)
                  hess(ind(icoor,iatom,jcoor,latom))=&
      &           hess(ind(icoor,iatom,jcoor,latom))&
      &            +tij*si(icoor) * sl(jcoor)
                  hess(ind(icoor,jatom,jcoor,katom))=&
      &           hess(ind(icoor,jatom,jcoor,katom))&
      &            +tij*sj(icoor) * sk(jcoor)
                  hess(ind(icoor,jatom,jcoor,latom))=&
      &           hess(ind(icoor,jatom,jcoor,latom))&
      &            +tij*sj(icoor) * sl(jcoor)
                  hess(ind(icoor,katom,jcoor,latom))=&
      &           hess(ind(icoor,katom,jcoor,latom))&
      &            +tij*sk(icoor) * sl(jcoor)
                 End Do
               End Do
 !-------------Diagonal block
               Do icoor=1,3
                 Do jcoor=1,icoor
                  hess(ind(icoor,iatom,jcoor,iatom))=&
      &           hess(ind(icoor,iatom,jcoor,iatom))&
      &            +tij*si(icoor) * si(jcoor)
                  hess(ind(icoor,jatom,jcoor,jatom))=&
      &           hess(ind(icoor,jatom,jcoor,jatom))&
      &            +tij*sj(icoor) * sj(jcoor)
                  hess(ind(icoor,katom,jcoor,katom))=&
      &           hess(ind(icoor,katom,jcoor,katom))&
      &            +tij*sk(icoor) * sk(jcoor)
                  hess(ind(icoor,latom,jcoor,latom))=&
      &           hess(ind(icoor,latom,jcoor,latom))&
      &            +tij*sl(icoor) * sl(jcoor)
                  End Do
                End Do
       enddo ! tors list
       if (profile) call timer%measure(3)
       if (profile) call timer%write(6,'modhes')
       Return
References getqqxx(), getqqxy(), itabrow(), lina(), and trsn().
Referenced by xtb_optimizer::modhes().