My Project: xtb_modelhessian Module Reference
xtb_modelhessian Module Reference
Functions/Subroutines
subroutine, public mh_swart (xyz, n, hess, at, modh)
pure subroutine mh_swart_stretch (n, at, xyz, hess, kr, kd, s6, rcov, rvdw, lcutoff, rcut)
pure subroutine mh_swart_bend (n, at, xyz, hess, kf, kd, rcov, rvdw, lcutoff)
pure subroutine mh_swart_torsion (n, at, xyz, hess, kt, kd, rcov, rvdw, lcutoff)
pure subroutine mh_swart_outofp (n, at, xyz, hess, ko, kd, rcov, rvdw, lcutoff)
subroutine, public mh_lindh_d2 (xyz, n, hess, at, modh)
subroutine, public mh_lindh (xyz, n, hess, at, modh)
pure subroutine mh_lindh_stretch (n, at, xyz, hess, kr, kd, s6, aav, rav, dav, lcutoff, rcut)
pure subroutine mh_lindh_bend (n, at, xyz, hess, kf, kd, aav, rav, dav, lcutoff)
subroutine mh_lindh_torsion (n, at, xyz, hess, kt, kd, aav, rav, dav, lcutoff)
pure subroutine mh_lindh_outofp (n, at, xyz, hess, ko, kd, aav, rav, dav, lcutoff)
pure elemental integer function ixyz (i, iatom)
pure elemental integer function jnd (i, j)
pure elemental integer function ind (i, iatom, j, jatom)
pure logical function rcutoff (xyz, katom, latom, rcut)
pure elemental integer function itabrow (i)
pure subroutine outofp2 (xyz, teta, bt)
pure subroutine trsn2 (xyz, tau, bt)
pure subroutine strtch2 (xyz, avst, b)
pure subroutine bend2 (xyz, fir, bf)
pure elemental subroutine getvdwxy (rx, ry, rz, c66, s6, r0, vdw)
pure elemental subroutine getvdwxx (rx, ry, rz, c66, s6, r0, vdw)
pure elemental real(wp) function fk_lindh (alpha, r0, r2)
pure elemental real(wp) function fk_swart (alpha, r0, r2)
pure elemental real(wp) function fk_vdw (alpha, r0, r2)
subroutine mh_eeq (n, at, xyz, chrg, chrgeq, kq, hess)
Variables
real(wp), dimension(86), parameter vander = aatoau * (/ 0.91_wp,0.92_wp, 0.75_wp,1.28_wp,1.35_wp,1.32_wp,1.27_wp,1.22_wp,1.17_wp,1.13_wp, 1.04_wp,1.24_wp,1.49_wp,1.56_wp,1.55_wp,1.53_wp,1.49_wp,1.45_wp, 1.35_wp,1.34_wp, 1.42_wp,1.42_wp,1.42_wp,1.42_wp,1.42_wp, 1.42_wp,1.42_wp,1.42_wp,1.42_wp,1.42_wp, 1.50_wp,1.57_wp,1.60_wp,1.61_wp,1.59_wp,1.57_wp, 1.48_wp,1.46_wp, 1.49_wp,1.49_wp,1.49_wp,1.49_wp,1.49_wp, 1.49_wp,1.49_wp,1.49_wp,1.49_wp,1.49_wp, 1.52_wp,1.64_wp,1.71_wp,1.72_wp,1.72_wp,1.71_wp, 2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp /)
real(wp), dimension(86), parameter c6 = (/ 0.14_wp, 0.08_wp, 1.61_wp, 1.61_wp, 3.13_wp, 1.75_wp, 1.23_wp, 0.70_wp, 0.75_wp, 0.63_wp, 5.71_wp, 5.71_wp,10.79_wp, 9.23_wp, 7.84_wp, 5.57_wp, 5.07_wp, 4.61_wp, 10.80_wp,10.80_wp, 10.80_wp,10.80_wp,10.80_wp,10.80_wp,10.80_wp, 10.80_wp,10.80_wp,10.80_wp,10.80_wp,10.80_wp, 16.99_wp,17.10_wp,16.37_wp,12.64_wp,12.47_wp,12.01_wp, 24.67_wp,24.67_wp, 24.67_wp,24.67_wp,24.67_wp,24.67_wp,24.67_wp, 24.67_wp,24.67_wp,24.67_wp,24.67_wp,24.67_wp, 37.32_wp,38.71_wp,38.44_wp,31.74_wp,31.50_wp,29.99_wp, 50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp /)
real(wp), parameter min_fk = 1.0e-3_wp
Function/Subroutine Documentation
bend2()
pure subroutine xtb_modelhessian::bend2 (real(wp), dimension(3,3), intent(in) xyz, real(wp), intent(out) fir, real(wp), dimension(3,3), intent(out) bf) private
Definition at line 1645 of file model_hessian.f90.
    use xtb_mctc_constants
    implicit none
    real(wp),intent(out) :: bf(3,3)
    real(wp),intent(in)  :: xyz(3,3)
    real(wp) :: brij(3,2)
    real(wp) :: brjk(3,2)
    real(wp) :: co,crap
    real(wp),intent(out) :: fir
    real(wp) :: si
    real(wp) :: rij1,rjk1
    integer  :: i
    call strtch2(xyz(1,1),rij1,brij)
    call strtch2(xyz(1,2),rjk1,brjk)
    co=0.0_wp
    crap=0.0_wp
    do i = 1, 3
       co=co+brij(i,1)*brjk(i,2)
       crap=crap+(brjk(i,2)+brij(i,1))**2
    end do
    if (sqrt(crap).lt.1.0d-6) then
       fir=pi-asin(sqrt(crap))
       si=sqrt(crap)
    else
       fir=acos(co)
       si=sqrt(1.0_wp-co**2)
    end if
    if (abs(fir-pi).lt.1.0d-13) then
       fir=pi
       return
    end if
    do i = 1, 3
       bf(i,1)= (co*brij(i,1)-brjk(i,2))/(si*rij1)
       bf(i,3)= (co*brjk(i,2)-brij(i,1))/(si*rjk1)
       bf(i,2)=-(bf(i,1)+bf(i,3))
    end do
References xtb_mctc_constants::pi, and strtch2().
Referenced by outofp2(), and trsn2().
fk_lindh()
pure elemental real(wp) function xtb_modelhessian::fk_lindh (real(wp), intent(in) alpha, real(wp), intent(in) r0, real(wp), intent(in) r2) private
Definition at line 1752 of file model_hessian.f90.
    implicit none
    real(wp),intent(in) :: alpha,r0,r2
    real(wp) :: gmm
    gmm = exp(alpha*(r0**2 - r2))
Referenced by mh_lindh_bend(), mh_lindh_outofp(), mh_lindh_stretch(), and mh_lindh_torsion().
fk_swart()
pure elemental real(wp) function xtb_modelhessian::fk_swart (real(wp), intent(in) alpha, real(wp), intent(in) r0, real(wp), intent(in) r2) private
Definition at line 1759 of file model_hessian.f90.
    implicit none
    real(wp),intent(in) :: alpha,r0,r2
    real(wp) :: gmm
    gmm = exp(-alpha*(sqrt(r2)/r0 - 1.0_wp))
Referenced by mh_swart_bend(), mh_swart_outofp(), mh_swart_stretch(), and mh_swart_torsion().
fk_vdw()
pure elemental real(wp) function xtb_modelhessian::fk_vdw (real(wp), intent(in) alpha, real(wp), intent(in) r0, real(wp), intent(in) r2) private
Definition at line 1766 of file model_hessian.f90.
    implicit none
    real(wp),intent(in) :: alpha,r0,r2
    real(wp) :: gmm
    gmm = exp(-alpha*(r0 - sqrt(r2))**2)
Referenced by mh_lindh_bend(), mh_lindh_outofp(), mh_lindh_stretch(), mh_lindh_torsion(), mh_swart_bend(), mh_swart_outofp(), mh_swart_stretch(), and mh_swart_torsion().
getvdwxx()
pure elemental subroutine xtb_modelhessian::getvdwxx (real(wp), intent(in) rx, real(wp), intent(in) ry, real(wp), intent(in) rz, real(wp), intent(in) c66, real(wp), intent(in) s6, real(wp), intent(in) r0, real(wp), intent(out) vdw) private
Definition at line 1716 of file model_hessian.f90.
    !cc Ableitung nach rx und rx
    implicit none
    real(wp),intent(in)  :: rx,ry,rz,c66,s6,r0
    real(wp),intent(out) :: vdw
    real(wp) :: t1,t2,t3,t4,t5,t6,t7,t10,t11,t15,t16,t17,t24,t25,t29
    real(wp) :: t33,t41,t42,t44,t45,t62,avdw
    avdw=20.0
    ! write(*,*) 's6:', s6
    t1 = s6 * c66
    t2 = rx ** 2
    t3 = ry ** 2
    t4 = rz ** 2
    t5 = t2 + t3 + t4
    t6 = t5 ** 2
    t7 = t6 ** 2
    t10 = sqrt(t5)
    t11 = 0.1d1 / r0
    t15 = exp(-avdw * (t10 * t11 - 0.1d1))
    t16 = 0.1d1 + t15
    t17 = 0.1d1 / t16
    t24 = t16 ** 2
    t25 = 0.1d1 / t24
    t29 = t11 * t15
    t33 = 0.1d1 / t7
    t41 = avdw ** 2
    t42 = r0 ** 2
    t44 = t41 / t42
    t45 = t15 ** 2
    t62 = -0.48d2 * t1 / t7 / t5 * t17 * t2 + 0.13d2 * t1 / t10 / t7 * &
       t25 * t2 * avdw * t29 + 0.6d1 * t1 * t33 * t17 - 0.2d1 * t1 * t33 &
       / t24 / t16 * t44 * t2 * t45 - t1 / t10 / t6 / t5 * t25 * avdw * &
       t29 + t1 * t33 * t25 * t44 * t2 * t15
    vdw=t62
getvdwxy()
pure elemental subroutine xtb_modelhessian::getvdwxy (real(wp), intent(in) rx, real(wp), intent(in) ry, real(wp), intent(in) rz, real(wp), intent(in) c66, real(wp), intent(in) s6, real(wp), intent(in) r0, real(wp), intent(out) vdw)
Definition at line 1683 of file model_hessian.f90.
    !cc Ableitung nach rx und ry
    implicit none
    real(wp),intent(in)  :: rx,ry,rz,c66,s6,r0
    real(wp),intent(out) :: vdw
    real(wp) :: t1,t2,t3,t4,t5,t6,t7,t11,t12,t16,t17,t25,t26,t35
    real(wp) :: t40,t41,t43,t44,t56,avdw
    ! write(*,*) 's6:', s6
    avdw=20.0
    t1 = s6 * c66
    t2 = rx ** 2
    t3 = ry ** 2
    t4 = rz ** 2
    t5 = t2 + t3 + t4
    t6 = t5 ** 2
    t7 = t6 ** 2
    t11 = sqrt(t5)
    t12 = 0.1d1 / r0
    t16 = exp(-avdw * (t11 * t12 - 0.1d1))
    t17 = 0.1d1 + t16
    t25 = t17 ** 2
    t26 = 0.1d1 / t25
    t35 = 0.1d1 / t7
    t40 = avdw ** 2
    t41 = r0 ** 2
    t43 = t40 / t41
    t44 = t16 ** 2
    t56 = -0.48d2 * t1 / t7 / t5 / t17 * rx * ry + 0.13d2 * t1 / t11 / &
       t7 * t26 * rx * avdw * t12 * ry * t16 - 0.2d1 * t1 * t35 / t25 / &
       t17 * t43 * rx * t44 * ry + t1 * t35 * t26 * t43 * rx * ry * t16
    vdw=t56
ind()
pure elemental integer function xtb_modelhessian::ind (integer, intent(in) i, integer, intent(in) iatom, integer, intent(in) j, integer, intent(in) jatom) private
Definition at line 1440 of file model_hessian.f90.
    integer :: ind
    integer,intent(in) :: i,iatom,j,jatom
    ind=jnd(max(ixyz(i,iatom),ixyz(j,jatom)),min(ixyz(i,iatom),ixyz(j,jatom)))
References ixyz(), and jnd().
Referenced by mh_eeq(), mh_lindh_bend(), mh_lindh_outofp(), mh_lindh_stretch(), mh_lindh_torsion(), mh_swart_bend(), mh_swart_outofp(), mh_swart_stretch(), and mh_swart_torsion().
itabrow()
pure elemental integer function xtb_modelhessian::itabrow (integer, intent(in) i) private
Definition at line 1459 of file model_hessian.f90.
    integer :: itabrow
    integer,intent(in) :: i
    itabrow=0
    if (i.gt. 0 .and. i.le. 2) then
       itabrow=1
    else if (i.gt. 2 .and. i.le.10) then
       itabrow=2
    else if (i.gt.10 .and. i.le.18) then
       itabrow=3
    else if (i.gt.18 .and. i.le.36) then
       itabrow=3
    else if (i.gt.36 .and. i.le.54) then
       itabrow=3
    else if (i.gt.54 .and. i.le.86) then
       itabrow=3
    else if (i.gt.86) then
       itabrow=3
    end if
    return
References itabrow().
ixyz()
pure elemental integer function xtb_modelhessian::ixyz (integer, intent(in) i, integer, intent(in) iatom)
Definition at line 1430 of file model_hessian.f90.
    integer :: ixyz
    integer,intent(in) :: i,iatom
    ixyz = (iatom-1)*3 + i
Referenced by ind().
jnd()
pure elemental integer function xtb_modelhessian::jnd (integer, intent(in) i, integer, intent(in) j) private
Definition at line 1435 of file model_hessian.f90.
    integer :: jnd
    integer,intent(in) :: i,j
    jnd = i*(i-1)/2 +j
Referenced by ind().
mh_eeq()
subroutine xtb_modelhessian::mh_eeq (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), intent(in) chrg, type(chrg_parameter), intent(in) chrgeq, real(wp), intent(in) kq, real(wp), dimension((3*n)*(3*n+1)/2), intent(out) hess) private
Definition at line 1773 of file model_hessian.f90.
    use xtb_type_param
    implicit none
 !! ------------------------------------------------------------------------
 !  Input
 !! ------------------------------------------------------------------------
    integer, intent(in)    :: n                ! number of atoms
    integer, intent(in)    :: at(n)            ! ordinal numbers
    real(wp),intent(in)    :: xyz(3,n)         ! geometry
    real(wp),intent(in)    :: chrg             ! total charge
    real(wp),intent(in)    :: kq               ! scaling parameter
    type(chrg_parameter),intent(in) :: chrgeq  ! charge model
 !! ------------------------------------------------------------------------
 !  Output
 !! ------------------------------------------------------------------------
    real(wp),intent(out)   :: hess((3*n)*(3*n+1)/2)
    real(wp),allocatable   :: hessian(:,:,:,:) ! molecular hessian of IES
 !   itself
    real(wp),parameter :: pi = 3.1415926535897932384626433832795029_wp
 !
    real(wp),parameter :: sqrtpi = sqrt(pi)
 !  (2/)
    real(wp),parameter :: sqrt2pi = sqrt(2.0_wp/pi)
 !
 !! ------------------------------------------------------------------------
 !  charge model
 !! ------------------------------------------------------------------------
    integer  :: m ! dimension of the Lagrangian
    real(wp),allocatable :: Amat(:,:)
    real(wp),allocatable :: Xvec(:)
    real(wp),allocatable :: Ainv(:,:)
    real(wp),allocatable :: dAmat(:,:,:)
    real(wp),allocatable :: dqdr(:,:,:)
 !! ------------------------------------------------------------------------
 !  local variables
 !! ------------------------------------------------------------------------
    integer  :: i,j,k,l
    real(wp) :: r,rij(3),r2
    real(wp) :: gamij,gamij2
    real(wp) :: arg,arg2,tmp,dtmp
    real(wp) :: lambda
    real(wp) :: es,expterm,erfterm
    real(wp) :: htmp,rxr(3,3)
    real(wp) :: rcovij,rr
 !! ------------------------------------------------------------------------
 !  scratch variables
 !! ------------------------------------------------------------------------
    real(wp),allocatable :: alpha(:)
    real(wp),allocatable :: xtmp(:)
    real(wp),allocatable :: atmp(:,:)
 !! ------------------------------------------------------------------------
 !  Lapack work variables
 !! ------------------------------------------------------------------------
    integer, allocatable :: ipiv(:)
    real(wp),allocatable :: temp(:)
    real(wp),allocatable :: work(:)
    integer  :: lwork
    integer  :: info
    real(wp) :: test(1)
 !! ------------------------------------------------------------------------
 !  initizialization
 !! ------------------------------------------------------------------------
    m    = n+1
    allocate( ipiv(m), source = 0 )
    allocate( amat(m,m), xvec(m), alpha(n), dqdr(3,n,m), source = 0.0_wp )
 !! ------------------------------------------------------------------------
 !  set up the A matrix and X vector
 !! ------------------------------------------------------------------------
 !  i -> alpha(i), ENi -> xi(i), i -> kappa(i), Jii -> gam(i)
 !  ij = 1/(i+j)
 !  Xi  = -ENi + iCNi
 !  Aii = Jii + 2/ii
 !  Aij = erf(ijRij)/Rij = 2/F0(ijRij)
 !! ------------------------------------------------------------------------
 !  prepare some arrays
 !$omp parallel default(none) &
 !$omp shared(n,at,chrgeq) &
 !$omp private(i) &
 !$omp shared(Xvec,alpha)
 !$omp do schedule(dynamic)
    do i = 1, n
       xvec(i) = -chrgeq%en(i)
       alpha(i) = chrgeq%alpha(i)**2
    enddo
 !$omp enddo
 !$omp endparallel
 !$omp parallel default(none) &
 !$omp shared(n,at,xyz,chrgeq,alpha) &
 !$omp private(i,j,r,gamij) &
 !$omp shared(Amat)
 !$omp do schedule(dynamic)
    ! prepare A matrix
    do i = 1, n
       ! EN of atom i
       do j = 1, i-1
          r = sqrt(sum((xyz(:,j) - xyz(:,i))**2))
          gamij = 1.0_wp/sqrt(alpha(i)+alpha(j))
          amat(j,i) = erf(gamij*r)/r
          amat(i,j) = amat(j,i)
       enddo
       amat(i,i) = chrgeq%gam(i) + sqrt2pi/sqrt(alpha(i))
    enddo
 !$omp enddo
 !$omp endparallel
 !! ------------------------------------------------------------------------
 !  solve the linear equations to obtain partial charges
 !! ------------------------------------------------------------------------
    amat(m,1:m) = 1.0_wp
    amat(1:m,m) = 1.0_wp
    amat(m,m  ) = 0.0_wp
    xvec(m)     = chrg
    ! generate temporary copy
    allocate( atmp(m,m), source = amat )
    allocate( xtmp(m),   source = xvec )
    ! assume work space query, set best value to test after first dsysv call
    call dsysv('u', m, 1, atmp, m, ipiv, xtmp, m, test, -1, info)
    lwork = int(test(1))
    allocate( work(lwork), source = 0.0_wp )
    call dsysv('u',m,1,atmp,m,ipiv,xtmp,m,work,lwork,info)
    if(info > 0) call raise('E','(goedecker_solve) DSYSV failed')
    if(abs(sum(xtmp(:n))-chrg) > 1.e-6_wp) &
       call raise('E','(goedecker_solve) charge constrain error')
    !print'(3f20.14)',Xtmp
 !! ------------------------------------------------------------------------
 !  calculate isotropic electrostatic (IES) energy
 !! ------------------------------------------------------------------------
 !  E = i (ENi - iCNi)qi + i (Jii + 2/ii)qi
 !      +  i j,ji qiqj2/F0(ijRij)
 !    = q(Aq - X)
 !! ------------------------------------------------------------------------
 !   work(:m) = Xvec
 !   call dsymv('u',m,0.5_wp,Amat,m,Xtmp,1,-1.0_wp,work,1)
 !   es = dot_product(Xtmp,work(:m))
 !   energy = es + energy
 !! ------------------------------------------------------------------------
 !  calculate molecular gradient of the IES energy
 !! ------------------------------------------------------------------------
 !  dE/dRj -> g(:,j), Xi/Rj -> -dcn(:,i,j), Aij/Rj -> dAmat(:,j,i)
 !  dE/dR = (A/Rq - X/R)q
 !  Aij/Rj = Aij/Ri
 !! ------------------------------------------------------------------------
    allocate( damat(3,n,m), source = 0.0_wp )
 !$omp parallel default(none) &
 !$omp shared(n,xyz,alpha,Amat,Xtmp) &
 !$omp private(i,j,rij,r2,gamij,arg,dtmp) &
 !$omp reduction(+:dAmat)
 !$omp do schedule(dynamic)
    do i = 1, n
       do j = 1, i-1
          rij = xyz(:,i) - xyz(:,j)
          r2 = sum(rij**2)
          gamij = 1.0_wp/sqrt(alpha(i) + alpha(j))
          arg = gamij**2*r2
          dtmp = 2.0_wp*gamij*exp(-arg)/(sqrtpi*r2)-amat(j,i)/r2
          damat(:,i,i) = +dtmp*rij*xtmp(j) + damat(:,i,i)
          damat(:,j,j) = -dtmp*rij*xtmp(i) + damat(:,j,j)
          damat(:,i,j) = +dtmp*rij*xtmp(i)
          damat(:,j,i) = -dtmp*rij*xtmp(j)
       enddo
    enddo
 !$omp enddo
 !$omp endparallel
 !! ------------------------------------------------------------------------
 !  invert the A matrix using a Bunch-Kaufman factorization
 !  A = (LDL^T) = L^TDL
 !! ------------------------------------------------------------------------
    allocate( ainv(m,m), source = amat )
    ! assume work space query, set best value to test after first dsytrf call
    call dsytrf('L',m,ainv,m,ipiv,test,-1,info)
    if (int(test(1)) > lwork) then
       deallocate(work)
       lwork=int(test(1))
       allocate( work(lwork), source = 0.0_wp )
    endif
    ! Bunch-Kaufman factorization A = L*D*L**T
    call dsytrf('L',m,ainv,m,ipiv,work,lwork,info)
    if(info > 0)then
       call raise('E', '(goedecker_inversion) DSYTRF failed')
    endif
    ! A from factorized L matrix, save lower part of A in Ainv matrix
    ! Ainv matrix is overwritten with lower triangular part of A
    call dsytri('L',m,ainv,m,ipiv,work,info)
    if (info > 0) then
       call raise('E', '(goedecker_inversion) DSYTRI failed')
    endif
    ! symmetrizes A matrix from lower triangular part of inverse matrix
    do i = 1, m
       do j = i+1, m
          ainv(i,j)=ainv(j,i)
       enddo
    enddo
 !! ------------------------------------------------------------------------
 !  calculate gradient of the partial charge w.r.t. the nuclear coordinates
 !! ------------------------------------------------------------------------
    !call dsymm('r','l',3*n,m,-1.0_wp,Ainv,m,dAmat,3*n,1.0_wp,dqdr,3*n)
    call dgemm('n','n',3*n,m,m,-1.0_wp,damat,3*n,ainv,m,1.0_wp,dqdr,3*n)
    !print'(/,"analytical gradient")'
    !print'(3f20.14)',dqdr(:,:,:n)
 !! ------------------------------------------------------------------------
 !  molecular Hessian calculation
 !! ------------------------------------------------------------------------
    do i = 1, n
       do j = 1, i-1
          rij = xyz(:,j) - xyz(:,i)
          r2 = sum(rij**2)
          r = sqrt(r2)
          gamij = 1.0_wp/sqrt(alpha(i)+alpha(j))
          gamij2 = gamij**2
          arg2 = gamij2 * r2
          arg = sqrt(arg2)
          erfterm = xtmp(i)*xtmp(j)*erf(arg)/r
          expterm = xtmp(i)*xtmp(j)*2*gamij*exp(-arg2)/sqrtpi
          ! (qAq)/(RiRj):
          ! (qAq)/(XiXi) = (1-3Xij/Rij-2ijXij) 2ij/ exp[-ijRij]/Rij
          !                  - (Rij-3Xij) erf[ijRij]/Rij
          ! (qAq)/(XiXj) = (Rij-3Xij) erf[ijRij]/Rij
          !                  - (1-3Xij/Rij-2ijXij) 2ij/ exp[-ijRij]/Rij
          ! (qAq)/(XiYi) = 3Xij erf[ijRij]/Rij
          !                  - (3Xij/Rij+2ijXij) 2ij/ exp[-ijRij]/Rij
          ! (qAq)/(XiYj) = (3Xij/Rij+2ijXij) 2ij/ exp[-ijRij]/Rij
          !                  - 3Xij erf[ijRij]/Rij
          rxr(1,1) = erfterm * ( 3*rij(1)**2/r2**2 - 1.0_wp/r2 ) &
                   - expterm * ( 3*rij(1)**2/r2**2 + 2*gamij2*rij(1)**2/r2 - 1/r2 )
          rxr(2,2) = erfterm * ( 3*rij(2)**2/r2**2 - 1.0_wp/r2 ) &
                   - expterm * ( 3*rij(2)**2/r2**2 + 2*gamij2*rij(2)**2/r2 - 1/r2 )
          rxr(3,3) = erfterm * ( 3*rij(3)**2/r2**2 - 1.0_wp/r2 ) &
                   - expterm * ( 3*rij(3)**2/r2**2 + 2*gamij2*rij(3)**2/r2 - 1/r2 )
          rxr(2,1) = erfterm * 3*rij(2)*rij(1)/r2**2 &
                   - expterm * ( 3*rij(2)*rij(1)/r2**2 + 2*gamij2*rij(2)*rij(1)/r2 )
          rxr(3,1) = erfterm * 3*rij(3)*rij(1)/r2**2 &
                   - expterm * ( 3*rij(3)*rij(1)/r2**2 + 2*gamij2*rij(3)*rij(1)/r2 )
          rxr(3,2) = erfterm * 3*rij(3)*rij(2)/r2**2 &
                   - expterm * ( 3*rij(3)*rij(2)/r2**2 + 2*gamij2*rij(3)*rij(2)/r2 )
          do k = 1, m
             rxr(1,1) = rxr(1,1) + 0.5_wp*dqdr(1,i,k)*damat(1,j,k) &
                                 + 0.5_wp*dqdr(1,j,k)*damat(1,i,k)
             rxr(2,1) = rxr(2,1) + 0.5_wp*dqdr(2,i,k)*damat(1,j,k) &
                                 + 0.5_wp*dqdr(2,j,k)*damat(1,i,k)
             rxr(3,1) = rxr(3,1) + 0.5_wp*dqdr(3,i,k)*damat(1,j,k) &
                                 + 0.5_wp*dqdr(3,j,k)*damat(1,i,k)
             rxr(2,2) = rxr(2,2) + 0.5_wp*dqdr(2,i,k)*damat(2,j,k) &
                                 + 0.5_wp*dqdr(2,j,k)*damat(2,i,k)
             rxr(3,2) = rxr(3,2) + 0.5_wp*dqdr(3,i,k)*damat(2,j,k) &
                                 + 0.5_wp*dqdr(3,j,k)*damat(2,i,k)
             rxr(3,3) = rxr(3,3) + 0.5_wp*dqdr(3,i,k)*damat(3,j,k) &
                                 + 0.5_wp*dqdr(3,j,k)*damat(3,i,k)
          enddo
          ! symmetrize
          rxr(1,2) = rxr(2,1)
          rxr(1,3) = rxr(3,1)
          rxr(2,3) = rxr(3,2)
          ! save diagonal elements for atom i
          hess(ind(1,i,1,i))=hess(ind(1,i,1,i)) + kq*rxr(1,1)
          hess(ind(2,i,1,i))=hess(ind(2,i,1,i)) + kq*rxr(2,1)
          hess(ind(2,i,2,i))=hess(ind(2,i,2,i)) + kq*rxr(2,2)
          hess(ind(3,i,1,i))=hess(ind(3,i,1,i)) + kq*rxr(3,1)
          hess(ind(3,i,2,i))=hess(ind(3,i,2,i)) + kq*rxr(3,2)
          hess(ind(3,i,3,i))=hess(ind(3,i,3,i)) + kq*rxr(3,3)
          ! save elements between atom i and atom j
          hess(ind(1,i,1,j))=hess(ind(1,i,1,j)) - kq*rxr(1,1)
          hess(ind(1,i,2,j))=hess(ind(1,i,2,j)) - kq*rxr(2,1)
          hess(ind(1,i,3,j))=hess(ind(1,i,3,j)) - kq*rxr(3,1)
          hess(ind(2,i,1,j))=hess(ind(2,i,1,j)) - kq*rxr(2,1)
          hess(ind(2,i,2,j))=hess(ind(2,i,2,j)) - kq*rxr(2,2)
          hess(ind(2,i,3,j))=hess(ind(2,i,3,j)) - kq*rxr(3,2)
          hess(ind(3,i,1,j))=hess(ind(3,i,1,j)) - kq*rxr(3,1)
          hess(ind(3,i,2,j))=hess(ind(3,i,2,j)) - kq*rxr(3,2)
          hess(ind(3,i,3,j))=hess(ind(3,i,3,j)) - kq*rxr(3,3)
          ! save diagonal elements for atom j
          hess(ind(1,j,1,j))=hess(ind(1,j,1,j)) + kq*rxr(1,1)
          hess(ind(2,j,1,j))=hess(ind(2,j,1,j)) + kq*rxr(2,1)
          hess(ind(2,j,2,j))=hess(ind(2,j,2,j)) + kq*rxr(2,2)
          hess(ind(3,j,1,j))=hess(ind(3,j,1,j)) + kq*rxr(3,1)
          hess(ind(3,j,2,j))=hess(ind(3,j,2,j)) + kq*rxr(3,2)
          hess(ind(3,j,3,j))=hess(ind(3,j,3,j)) + kq*rxr(3,3)
       enddo
    enddo
    ! (qA)/(Riq)q/Rj
   ! hessian = hessian + reshape(matmul(reshape(dqdr,(/3*n,m/)),&
   !    transpose(reshape(dAmat,(/3*n,m/)))),(/3,n,3,n/))
    !call dgemm('n','t',3*n,m,3*n,+1.0_wp,dqdr,3*n,dAmat,3*n,1.0_wp,hessian,3*n)
    !call dgemm('n','t',3*n,m,3*n,+1.0_wp,dAmat,3*n,dqdr,3*n,1.0_wp,hessian,3*n)
References ind(), and raise().
Referenced by mh_lindh(), mh_lindh_d2(), and mh_swart().
mh_lindh()
subroutine, public xtb_modelhessian::mh_lindh (real(wp), dimension(3,n), intent(in) xyz, integer, intent(in) n, real(wp), dimension((3*n)*(3*n+1)/2), intent(out) hess, integer, dimension(n), intent(in) at, type(modhess_setvar), intent(in) modh)
Definition at line 798 of file model_hessian.f90.
    use xtb_mctc_constants
    use xtb_mctc_convert
    use xtb_type_setvar
    use xtb_type_param
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: xyz(3,n)
    real(wp),intent(out) :: hess((3*n)*(3*n+1)/2)
    integer, intent(in)  :: at(n)
    type(modhess_setvar),intent(in) :: modh
    real(wp),parameter :: rAv(3,3) = reshape( &
      (/1.3500_wp,2.1000_wp,2.5300_wp, &
        2.1000_wp,2.8700_wp,3.8000_wp, &
        2.5300_wp,3.8000_wp,4.5000_wp/), shape(rav) )
    real(wp),parameter :: aAv(3,3) = reshape ( &
      (/1.0000_wp,0.3949_wp,0.3949_wp, &
        0.3949_wp,0.2800_wp,0.1200_wp, &
        0.3949_wp,0.1200_wp,0.0600_wp/), shape(aav) )
    real(wp),parameter :: dAv(3,3) = reshape ( &
      (/0.0000_wp,3.6000_wp,3.6000_wp, &
        3.6000_wp,5.3000_wp,5.3000_wp, &
        3.6000_wp,5.3000_wp,5.3000_wp/), shape(aav) )
    integer  :: n3
    real(wp) :: kd
    logical, allocatable :: lcutoff(:,:)
    type(chrg_parameter) :: chrgeq
    allocate( lcutoff(n,n), source=.false.)
    n3=3*n
    hess = 0.0d0
 !  the dispersion force constant is used relative to the stretch force constant
    kd = modh%kd/modh%kr
    call mh_lindh_stretch(n,at,xyz,hess,modh%kr,kd,modh%s6,aav,rav,dav,lcutoff,modh%rcut)
    if (modh%kf.ne.0.0_wp) &
    call mh_lindh_bend   (n,at,xyz,hess,modh%kf,kd,        aav,rav,dav,lcutoff)
    if (modh%kt.ne.0.0_wp) &
    call mh_lindh_torsion(n,at,xyz,hess,modh%kt,kd,        aav,rav,dav,lcutoff)
    if (modh%ko.ne.0.0_wp) &
    call mh_lindh_outofp (n,at,xyz,hess,modh%ko,0.0_wp,    aav,rav,dav,lcutoff)
    if (modh%kq.ne.0.0_wp) then
       call new_charge_model_2019(chrgeq,n,at)
       call mh_eeq(n,at,xyz,0.0_wp,chrgeq,modh%kq,hess)
    endif
References mh_eeq(), mh_lindh_bend(), mh_lindh_outofp(), mh_lindh_stretch(), mh_lindh_torsion(), and xtb_chargemodel::new_charge_model_2019().
Referenced by xtb_optimizer::modhes().
mh_lindh_bend()
pure subroutine xtb_modelhessian::mh_lindh_bend (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension((3*n)*(3*n+1)/2), intent(inout) hess, real(wp), intent(in) kf, real(wp), intent(in) kd, real(wp), dimension(3,3), intent(in) aav, real(wp), dimension(3,3), intent(in) rav, real(wp), dimension(3,3), intent(in) dav, logical, dimension(n,n), intent(in) lcutoff)
Definition at line 956 of file model_hessian.f90.
    use xtb_mctc_constants
    implicit none
    integer, intent(in)    :: n
    integer, intent(in)    :: at(n)
    real(wp),intent(in)    :: xyz(3,n)
    real(wp),intent(inout) :: hess((3*n)*(3*n+1)/2)
    real(wp),intent(in)    :: kf
    real(wp),intent(in)    :: kd
    real(wp),intent(in)    :: aav(3,3)
    real(wp),intent(in)    :: rav(3,3)
    real(wp),intent(in)    :: dav(3,3)
    logical, intent(in)    :: lcutoff(n,n)
    integer  :: i,ir,j,jr,m,mr,ic,jc,ii
    real(wp),parameter :: rzero = 1.0e-10_wp
    real(wp) :: xij,yij,zij,rij2,rrij,r1
    real(wp) :: xmi,ymi,zmi,rmi2,rmi,r0mi,ami,d0mj,gmi
    real(wp) :: xmj,ymj,zmj,rmj2,rmj,r0mj,amj,d0mi,gmj
    real(wp) :: test,gij,rl2,rl,rmidotrmj
    real(wp) :: sinphi,cosphi,costhetax,costhetay,costhetaz
    real(wp) :: alpha
    real(wp) :: si(3),sj(3),sm(3),x(2),y(2),z(2)
 !! ------------------------------------------------------------------------
 !  Hessian for bending
 !! ------------------------------------------------------------------------
    bend_mat: do m = 1, n
       mr=itabrow(at(m))
       bend_iat: do i = 1, n
          if (i.eq.m) cycle bend_iat
          ir=itabrow(at(i))
          if(lcutoff(i,m)) cycle bend_iat
          xmi=(xyz(1,i)-xyz(1,m))
          ymi=(xyz(2,i)-xyz(2,m))
          zmi=(xyz(3,i)-xyz(3,m))
          rmi2 = xmi**2 + ymi**2 + zmi**2
          rmi=sqrt(rmi2)
          r0mi=rav(mr,ir)
          d0mi=dav(mr,ir)
          ami=aav(mr,ir)
          bend_jat: do j = 1, i-1
             if (j.eq.m) cycle bend_jat
             jr=itabrow(at(j))
             if(lcutoff(j,i)) cycle bend_jat
             if(lcutoff(j,m)) cycle bend_jat
             xmj=(xyz(1,j)-xyz(1,m))
             ymj=(xyz(2,j)-xyz(2,m))
             zmj=(xyz(3,j)-xyz(3,m))
             rmj2 = xmj**2 + ymj**2 + zmj**2
             rmj=sqrt(rmj2)
             r0mj=rav(mr,jr)
             d0mj=dav(mr,jr)
             amj=aav(mr,jr)
             ! test if zero angle
             test=xmi*xmj+ymi*ymj+zmi*zmj
             test=test/(rmi*rmj)
             if (abs(test-1.0_wp).lt.1.0e-12_wp) cycle bend_jat
             xij=(xyz(1,j)-xyz(1,i))
             yij=(xyz(2,j)-xyz(2,i))
             zij=(xyz(3,j)-xyz(3,i))
             rij2 = xij**2 + yij**2 + zij**2
             rrij=sqrt(rij2)
             gmi = fk_lindh(ami,r0mi,rmi2) &
                 + 0.5_wp*kd * fk_vdw(4.0_wp,d0mi,rmi2)
             gmj = fk_lindh(amj,r0mj,rmj2) &
                 + 0.5_wp*kd * fk_vdw(4.0_wp,d0mj,rmj2)
             gij = kf*gmi*gmj
             rl2=(ymi*zmj-zmi*ymj)**2+(zmi*xmj-xmi*zmj)**2+(xmi*ymj-ymi*xmj)**2
             if(rl2.lt.1.e-14_wp) then
                rl=0.0_wp
             else
                rl=sqrt(rl2)
             end if
             !gij = max(gij,min_fk)
             if ((rmj.gt.rzero).and.(rmi.gt.rzero).and.(rrij.gt.rzero)) then
                sinphi=rl/(rmj*rmi)
                rmidotrmj=xmi*xmj+ymi*ymj+zmi*zmj
                cosphi=rmidotrmj/(rmj*rmi)
                ! none linear case
                if (sinphi.gt.rzero) then
                   si(1)=(xmi/rmi*cosphi-xmj/rmj)/(rmi*sinphi)
                   si(2)=(ymi/rmi*cosphi-ymj/rmj)/(rmi*sinphi)
                   si(3)=(zmi/rmi*cosphi-zmj/rmj)/(rmi*sinphi)
                   sj(1)=(cosphi*xmj/rmj-xmi/rmi)/(rmj*sinphi)
                   sj(2)=(cosphi*ymj/rmj-ymi/rmi)/(rmj*sinphi)
                   sj(3)=(cosphi*zmj/rmj-zmi/rmi)/(rmj*sinphi)
                   sm(1)=-si(1)-sj(1)
                   sm(2)=-si(2)-sj(2)
                   sm(3)=-si(3)-sj(3)
                   do ic=1,3
                      do jc=1,3
                         if (m.gt.i) then
                            hess(ind(ic,m,jc,i))=hess(ind(ic,m,jc,i)) &
                               +gij*sm(ic)*si(jc)
                         else
                            hess(ind(ic,i,jc,m))=hess(ind(ic,i,jc,m)) &
                               +gij*si(ic)*sm(jc)
                         end if
                         if (m.gt.j) then
                            hess(ind(ic,m,jc,j))=hess(ind(ic,m,jc,j)) &
                               +gij*sm(ic)*sj(jc)
                         else
                            hess(ind(ic,j,jc,m))=hess(ind(ic,j,jc,m)) &
                               +gij*sj(ic)*sm(jc)
                         end if
                         if (i.gt.j) then
                            hess(ind(ic,i,jc,j))=hess(ind(ic,i,jc,j)) &
                               +gij*si(ic)*sj(jc)
                         else
                            hess(ind(ic,j,jc,i))=hess(ind(ic,j,jc,i)) &
                               +gij*sj(ic)*si(jc)
                         end if
                      end do
                   end do
                   do ic=1,3
                      do jc=1,ic
                         hess(ind(ic,i,jc,i))=hess(ind(ic,i,jc,i))+gij*si(ic)*si(jc)
                         hess(ind(ic,m,jc,m))=hess(ind(ic,m,jc,m))+gij*sm(ic)*sm(jc)
                         hess(ind(ic,j,jc,j))=hess(ind(ic,j,jc,j))+gij*sj(ic)*sj(jc)
                      end do
                   end do
                else
                   ! linear case
                   if ((abs(ymi).gt.rzero).or.(abs(xmi).gt.rzero)) then
                      x(1)=-ymi
                      y(1)=xmi
                      z(1)=0.0_wp
                      x(2)=-xmi*zmi
                      y(2)=-ymi*zmi
                      z(2)=xmi*xmi+ymi*ymi
                   else
                      x(1)=1.0_wp
                      y(1)=0.0_wp
                      z(1)=0.0_wp
                      x(2)=0.0_wp
                      y(2)=1.0_wp
                      z(2)=0.0_wp
                   end if
                   do ii=1,2
                      r1=sqrt(x(ii)**2+y(ii)**2+z(ii)**2)
                      costhetax=x(ii)/r1
                      costhetay=y(ii)/r1
                      costhetaz=z(ii)/r1
                      si(1)=-costhetax/rmi
                      si(2)=-costhetay/rmi
                      si(3)=-costhetaz/rmi
                      sj(1)=-costhetax/rmj
                      sj(2)=-costhetay/rmj
                      sj(3)=-costhetaz/rmj
                      sm(1)=-(si(1)+sj(1))
                      sm(2)=-(si(2)+sj(2))
                      sm(3)=-(si(3)+sj(3))
                      !
                      do ic=1,3
                         do jc=1,3
                            if (m.gt.i) then
                               hess(ind(ic,m,jc,i))=hess(ind(ic,m,jc,i)) &
                                  +gij*sm(ic)*si(jc)
                            else
                               hess(ind(ic,i,jc,m))=hess(ind(ic,i,jc,m)) &
                                  +gij*si(ic)*sm(jc)
                            end if
                            if (m.gt.j) then
                               hess(ind(ic,m,jc,j))=hess(ind(ic,m,jc,j)) &
                                  +gij*sm(ic)*sj(jc)
                            else
                               hess(ind(ic,j,jc,m))=hess(ind(ic,j,jc,m)) &
                                  +gij*sj(ic)*sm(jc)
                            end if
                            if (i.gt.j) then
                               hess(ind(ic,i,jc,j))=hess(ind(ic,i,jc,j)) &
                                  +gij*si(ic)*sj(jc)
                            else
                               hess(ind(ic,j,jc,i))=hess(ind(ic,j,jc,i)) &
                                  +gij*sj(ic)*si(jc)
                            end if
                         end do
                      end do
                      do ic=1,3
                         do jc=1,ic
                            hess(ind(ic,i,jc,i))=hess(ind(ic,i,jc,i)) &
                               +gij*si(ic)*si(jc)
                            hess(ind(ic,m,jc,m))=hess(ind(ic,m,jc,m)) &
                               +gij*sm(ic)*sm(jc)
                            hess(ind(ic,j,jc,j))=hess(ind(ic,j,jc,j)) &
                               +gij*sj(ic)*sj(jc)
                         end do
                      end do
                   end do
                end if
             end if
          end do bend_jat
       end do bend_iat
    end do bend_mat
References fk_lindh(), fk_vdw(), ind(), and itabrow().
Referenced by mh_lindh(), and mh_lindh_d2().
mh_lindh_d2()
subroutine, public xtb_modelhessian::mh_lindh_d2 (real(wp), dimension(3,n), intent(in) xyz, integer, intent(in) n, real(wp), dimension((3*n)*(3*n+1)/2), intent(out) hess, integer, dimension(n), intent(in) at, type(modhess_setvar), intent(in) modh)
Definition at line 717 of file model_hessian.f90.
    use xtb_mctc_constants
    use xtb_mctc_convert
    use xtb_type_setvar
    use xtb_type_param
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: xyz(3,n)
    real(wp),intent(out) :: hess((3*n)*(3*n+1)/2)
    integer, intent(in)  :: at(n)
    type(modhess_setvar),intent(in) :: modh
    real(wp),parameter :: rAv(3,3) = reshape( &
      (/1.3500_wp,2.1000_wp,2.5300_wp, &
        2.1000_wp,2.8700_wp,3.4000_wp, &
        2.5300_wp,3.4000_wp,3.4000_wp/), shape(rav) )
    real(wp),parameter :: aAv(3,3) = reshape ( &
      (/1.0000_wp,0.3949_wp,0.3949_wp, &
        0.3949_wp,0.2800_wp,0.2800_wp, &
        0.3949_wp,0.2800_wp,0.2800_wp/), shape(aav) )
    real(wp),parameter :: dAv(3,3) = reshape ( &
      (/0.0000_wp,0.0000_wp,0.0000_wp, &
        0.0000_wp,0.0000_wp,0.0000_wp, &
        0.0000_wp,0.0000_wp,0.0000_wp/), shape(aav) )
    integer  :: n3
    real(wp) :: kd
    logical, allocatable :: lcutoff(:,:)
    type(chrg_parameter) :: chrgeq
    allocate( lcutoff(n,n), source=.false.)
    n3=3*n
    hess = 0.0d0
 !  the dispersion force constant is used relative to the stretch force constant
    kd = modh%kd/modh%kr
    call mh_lindh_stretch(n,at,xyz,hess,modh%kr,kd,modh%s6,aav,rav,dav,lcutoff,modh%rcut)
    if (modh%kf.ne.0.0_wp) &
    call mh_lindh_bend   (n,at,xyz,hess,modh%kf,kd,        aav,rav,dav,lcutoff)
    if (modh%kt.ne.0.0_wp) &
    call mh_lindh_torsion(n,at,xyz,hess,modh%kt,kd,        aav,rav,dav,lcutoff)
    if (modh%ko.ne.0.0_wp) &
    call mh_lindh_outofp (n,at,xyz,hess,modh%ko,kd,        aav,rav,dav,lcutoff)
    if (modh%kq.ne.0.0_wp) then
       call new_charge_model_2019(chrgeq,n,at)
       call mh_eeq(n,at,xyz,0.0_wp,chrgeq,modh%kq,hess)
    endif
References mh_eeq(), mh_lindh_bend(), mh_lindh_outofp(), mh_lindh_stretch(), mh_lindh_torsion(), and xtb_chargemodel::new_charge_model_2019().
Referenced by xtb_optimizer::modhes().
mh_lindh_outofp()
pure subroutine xtb_modelhessian::mh_lindh_outofp (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension((3*n)*(3*n+1)/2), intent(inout) hess, real(wp), intent(in) ko, real(wp), intent(in) kd, real(wp), dimension(3,3), intent(in) aav, real(wp), dimension(3,3), intent(in) rav, real(wp), dimension(3,3), intent(in) dav, logical, dimension(n,n), intent(in) lcutoff)
Definition at line 1303 of file model_hessian.f90.
    use xtb_mctc_constants
    implicit none
    integer, intent(in)    :: n
    integer, intent(in)    :: at(n)
    real(wp),intent(in)    :: xyz(3,n)
    real(wp),intent(inout) :: hess((3*n)*(3*n+1)/2)
    real(wp),intent(in)    :: ko
    real(wp),intent(in)    :: kd
    real(wp),intent(in)    :: aav(3,3)
    real(wp),intent(in)    :: rav(3,3)
    real(wp),intent(in)    :: dav(3,3)
    logical, intent(in)    :: lcutoff(n,n)
    integer  :: i,ir,j,jr,k,kr,l,lr,ic,jc
    real(wp) :: txyz(3,4),c(3,4)
    real(wp) :: rij(3),rij0,aij,rij2,gij,d0ij
    real(wp) :: rik(3),rik0,aik,rik2,gik,d0ik
    real(wp) :: ril(3),ril0,ail,ril2,gil,d0il
    real(wp) :: cosfi2,cosfi3,cosfi4
    real(wp) :: beta,tij,tau
    real(wp) :: si(3),sj(3),sk(3),sl(3)
 !! ------------------------------------------------------------------------
 !  Hessian for out-of-plane
 !! ------------------------------------------------------------------------
    outofplane_iat: do i = 1, n
       ir = itabrow(at(i))
       txyz(:,4) = xyz(:,i)
       outofplane_jat: do j = 1, n
          if (j.eq.i) cycle outofplane_jat
          if(lcutoff(j,i)) cycle outofplane_jat
          jr = itabrow(at(j))
          txyz(:,1) = xyz(:,j)
          outofplane_kat: do k = 1, n
             if (i.eq.k) cycle outofplane_kat
             if (j.eq.k) cycle outofplane_kat
             if(lcutoff(k,i)) cycle outofplane_kat
             if(lcutoff(k,j)) cycle outofplane_kat
             kr = itabrow(at(k))
             txyz(:,2) = xyz(:,k)
             outofplane_lat: do l = 1, n
                lr = itabrow(at(l))
                txyz(:,3) = xyz(:,l)
                if (l.eq.i) cycle outofplane_lat
                if (l.eq.j) cycle outofplane_lat
                if (l.eq.k) cycle outofplane_lat
                if(lcutoff(l,i)) cycle outofplane_lat
                if(lcutoff(l,k)) cycle outofplane_lat
                if(lcutoff(l,j)) cycle outofplane_lat
                rij=xyz(:,i)-xyz(:,j)
                d0ij=dav(ir,jr)
                rij0=rav(ir,jr)
                aij =aav(ir,jr)
                rik=xyz(:,i)-xyz(:,k)
                d0ik=dav(ir,kr)
                rik0=rav(ir,kr)
                aik =aav(ir,kr)
                ril=xyz(:,i)-xyz(:,l)
                d0il=dav(ir,lr)
                ril0=rav(ir,lr)
                ail =aav(ir,lr)
                rij2=sum(rij**2)
                rik2=sum(rik**2)
                ril2=sum(ril**2)
                cosfi2=dot_product(rij,rik)/sqrt(rij2*rik2)
                if (abs(abs(cosfi2)-1.0_wp).lt.1.0e-1_wp) cycle
                cosfi3=dot_product(rij,ril)/sqrt(rij2*ril2)
                if (abs(abs(cosfi3)-1.0_wp).lt.1.0e-1_wp) cycle
                cosfi4=dot_product(rik,ril)/sqrt(rik2*ril2)
                if (abs(abs(cosfi4)-1.0_wp).lt.1.0e-1_wp) cycle
                gij = fk_lindh(aij,rij0,rij2) &
                   + 0.5_wp*kd * fk_vdw(4.0_wp,d0ij,rij2)
                gik = fk_lindh(aik,rik0,rik2) &
                   + 0.5_wp*kd * fk_vdw(4.0_wp,d0ik,rik2)
                gil = fk_lindh(ail,ril0,ril2) &
                   + 0.5_wp*kd * fk_vdw(4.0_wp,d0il,ril2)
                tij = ko * gij*gik*gil
                !tij = max(tij,10*min_fk)
                call outofp2(xyz,tau,c)
                If (abs(tau).gt.45.0d0*(pi/180.d0)) cycle
                si = c(:,4)
                sj = c(:,1)
                sk = c(:,2)
                sl = c(:,3)
                ! off diagonal block
                do ic=1,3
                   do jc=1,3
                      hess(ind(ic,i,jc,j))=hess(ind(ic,i,jc,j))+tij*si(ic) * sj(jc)
                      hess(ind(ic,i,jc,k))=hess(ind(ic,i,jc,k))+tij*si(ic) * sk(jc)
                      hess(ind(ic,i,jc,l))=hess(ind(ic,i,jc,l))+tij*si(ic) * sl(jc)
                      hess(ind(ic,j,jc,k))=hess(ind(ic,j,jc,k))+tij*sj(ic) * sk(jc)
                      hess(ind(ic,j,jc,l))=hess(ind(ic,j,jc,l))+tij*sj(ic) * sl(jc)
                      hess(ind(ic,k,jc,l))=hess(ind(ic,k,jc,l))+tij*sk(ic) * sl(jc)
                   end do
                end do
                ! diagonal block
                do ic=1,3
                   do jc=1,ic
                      hess(ind(ic,i,jc,i))=hess(ind(ic,i,jc,i))+tij*si(ic) * si(jc)
                      hess(ind(ic,j,jc,j))=hess(ind(ic,j,jc,j))+tij*sj(ic) * sj(jc)
                      hess(ind(ic,k,jc,k))=hess(ind(ic,k,jc,k))+tij*sk(ic) * sk(jc)
                      hess(ind(ic,l,jc,l))=hess(ind(ic,l,jc,l))+tij*sl(ic) * sl(jc)
                   end do
                end do
             enddo outofplane_lat
          enddo outofplane_kat
       enddo outofplane_jat
    enddo outofplane_iat
References fk_lindh(), fk_vdw(), ind(), itabrow(), outofp2(), and xtb_mctc_constants::pi.
Referenced by mh_lindh(), and mh_lindh_d2().
mh_lindh_stretch()
pure subroutine xtb_modelhessian::mh_lindh_stretch (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension((3*n)*(3*n+1)/2), intent(inout) hess, real(wp), intent(in) kr, real(wp), intent(in) kd, real(wp), intent(in) s6, real(wp), dimension(3,3), intent(in) aav, real(wp), dimension(3,3), intent(in) rav, real(wp), dimension(3,3), intent(in) dav, logical, dimension(n,n), intent(out) lcutoff, real(wp), intent(in) rcut)
Definition at line 853 of file model_hessian.f90.
    use xtb_mctc_constants
    use xtb_mctc_convert
    implicit none
    integer, intent(in)    :: n
    integer, intent(in)    :: at(n)
    real(wp),intent(in)    :: xyz(3,n)
    real(wp),intent(inout) :: hess((3*n)*(3*n+1)/2)
    real(wp),intent(in)    :: kr
    real(wp),intent(in)    :: kd
    real(wp),intent(in)    :: s6
    real(wp),intent(in)    :: aav(3,3)
    real(wp),intent(in)    :: rav(3,3)
    real(wp),intent(in)    :: dav(3,3)
    logical, intent(out)   :: lcutoff(n,n)
    real(wp),intent(in)    :: rcut
    integer  :: i,ir,j,jr
    real(wp) :: xij,yij,zij,rij2,r0,d0
    real(wp) :: alpha,gmm
    real(wp) :: c6i,c6j,c6ij,rv
    real(wp) :: hxx,hxy,hxz,hyy,hyz,hzz
    real(wp) :: vdw(3,3)
 !! ------------------------------------------------------------------------
 !  Hessian for stretch
 !! ------------------------------------------------------------------------
    stretch_iat: do i = 1, n
       ir = itabrow(at(i))
       stretch_jat: do j = 1, i-1
          jr=itabrow(at(j))
          ! save for later
          lcutoff(i,j) = rcutoff(xyz,i,j,rcut)
          lcutoff(j,i) = lcutoff(i,j)
          xij=xyz(1,i)-xyz(1,j)
          yij=xyz(2,i)-xyz(2,j)
          zij=xyz(3,i)-xyz(3,j)
          rij2 = xij**2 + yij**2 + zij**2
          r0 = rav(ir,jr)
          d0 = dav(ir,jr)
          alpha=aav(ir,jr)
          !cccccc vdwx ccccccccccccccccccccccccccccccccc
          c6i=c6(at(i))
          c6j=c6(at(j))
          c6ij=sqrt(c6i*c6j)
          rv=(vander(at(i))+vander(at(j)))*aatoau
          call getvdwxx(xij, yij, zij, c6ij, s6, rv, vdw(1,1))
          call getvdwxy(xij, yij, zij, c6ij, s6, rv, vdw(1,2))
          call getvdwxy(xij, zij, yij, c6ij, s6, rv, vdw(1,3))
          call getvdwxx(yij, xij, zij, c6ij, s6, rv, vdw(2,2))
          call getvdwxy(yij, zij, xij, c6ij, s6, rv, vdw(2,3))
          call getvdwxx(zij, xij, yij, c6ij, s6, rv, vdw(3,3))
          !cccccc ende vdwx ccccccccccccccccccccccccccccccc
          gmm = kr*fk_lindh(alpha,r0,rij2) &
             + kr*kd * fk_vdw(4.0_wp,d0,rij2)
          !gmm = max(gmm,min_fk)
          hxx=gmm*xij*xij/rij2-vdw(1,1)
          hxy=gmm*xij*yij/rij2-vdw(1,2)
          hxz=gmm*xij*zij/rij2-vdw(1,3)
          hyy=gmm*yij*yij/rij2-vdw(2,2)
          hyz=gmm*yij*zij/rij2-vdw(2,3)
          hzz=gmm*zij*zij/rij2-vdw(3,3)
          ! save diagonal elements for atom i
          hess(ind(1,i,1,i))=hess(ind(1,i,1,i))+hxx
          hess(ind(2,i,1,i))=hess(ind(2,i,1,i))+hxy
          hess(ind(2,i,2,i))=hess(ind(2,i,2,i))+hyy
          hess(ind(3,i,1,i))=hess(ind(3,i,1,i))+hxz
          hess(ind(3,i,2,i))=hess(ind(3,i,2,i))+hyz
          hess(ind(3,i,3,i))=hess(ind(3,i,3,i))+hzz
          ! save elements between atom i and atom j
          hess(ind(1,i,1,j))=hess(ind(1,i,1,j))-hxx
          hess(ind(1,i,2,j))=hess(ind(1,i,2,j))-hxy
          hess(ind(1,i,3,j))=hess(ind(1,i,3,j))-hxz
          hess(ind(2,i,1,j))=hess(ind(2,i,1,j))-hxy
          hess(ind(2,i,2,j))=hess(ind(2,i,2,j))-hyy
          hess(ind(2,i,3,j))=hess(ind(2,i,3,j))-hyz
          hess(ind(3,i,1,j))=hess(ind(3,i,1,j))-hxz
          hess(ind(3,i,2,j))=hess(ind(3,i,2,j))-hyz
          hess(ind(3,i,3,j))=hess(ind(3,i,3,j))-hzz
          ! save diagonal elements for atom j
          hess(ind(1,j,1,j))=hess(ind(1,j,1,j))+hxx
          hess(ind(2,j,1,j))=hess(ind(2,j,1,j))+hxy
          hess(ind(2,j,2,j))=hess(ind(2,j,2,j))+hyy
          hess(ind(3,j,1,j))=hess(ind(3,j,1,j))+hxz
          hess(ind(3,j,2,j))=hess(ind(3,j,2,j))+hyz
          hess(ind(3,j,3,j))=hess(ind(3,j,3,j))+hzz
       end do stretch_jat
    end do stretch_iat
References xtb_mctc_convert::aatoau, c6, fk_lindh(), fk_vdw(), getvdwxx(), getvdwxy(), ind(), itabrow(), rcutoff(), and vander.
Referenced by mh_lindh(), and mh_lindh_d2().
mh_lindh_torsion()
subroutine xtb_modelhessian::mh_lindh_torsion (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension((3*n)*(3*n+1)/2), intent(inout) hess, real(wp), intent(in) kt, real(wp), intent(in) kd, real(wp), dimension(3,3), intent(in) aav, real(wp), dimension(3,3), intent(in) rav, real(wp), dimension(3,3), intent(in) dav, logical, dimension(n,n), intent(in) lcutoff)
Definition at line 1169 of file model_hessian.f90.
    use xtb_mctc_constants
    implicit none
    integer, intent(in)    :: n
    integer, intent(in)    :: at(n)
    real(wp),intent(in)    :: xyz(3,n)
    real(wp),intent(inout) :: hess((3*n)*(3*n+1)/2)
    real(wp),intent(in)    :: kt
    real(wp),intent(in)    :: kd
    real(wp),intent(in)    :: aav(3,3)
    real(wp),intent(in)    :: rav(3,3)
    real(wp),intent(in)    :: dav(3,3)
    logical, intent(in)    :: lcutoff(n,n)
    integer  :: i,ir,j,jr,k,kr,l,lr,ic,jc,ij,kl
 !  allow only angles in the range of 35-145
    real(wp),parameter :: a35 = (35.0d0/180.d0)* pi
    real(wp),parameter :: cosfi_max=cos(a35)
    real(wp) :: txyz(3,4),c(3,4)
    real(wp) :: rij(3),rij0,aij,rij2,d0ij,gij
    real(wp) :: rjk(3),rjk0,ajk,rjk2,d0jk,gjk
    real(wp) :: rkl(3),rkl0,akl,rkl2,d0kl,gkl
    real(wp) :: cosfi2,cosfi3,cosfi4
    real(wp) :: beta,tij,tau,dum(3,4,3,4)
    real(wp) :: si(3),sj(3),sk(3),sl(3)
 !! ------------------------------------------------------------------------
 !  Hessian for torsion
 !! ------------------------------------------------------------------------
    torsion_jat: do j = 1,n
       jr=itabrow(at(j))
       txyz(:,2)=xyz(:,j)
       torsion_kat: do k = 1, n
          if (k.eq.j) cycle torsion_kat
          kr=itabrow(at(k))
          if(lcutoff(k,j)) cycle torsion_kat
          txyz(:,3) = xyz(:,k)
          torsion_iat: do i = 1, n
             ij=n*(j-1)+i
             if (i.eq.j) cycle torsion_iat
             if (i.eq.k) cycle torsion_iat
             ir=itabrow(at(i))
             if(lcutoff(i,k)) cycle torsion_iat
             if(lcutoff(i,j)) cycle torsion_iat
             txyz(:,1)=xyz(:,i)
             torsion_lat: do l = 1, n
                kl=n*(k-1)+l
                if (ij.le.kl) cycle torsion_lat
                if (l.eq.i)   cycle torsion_lat
                if (l.eq.j)   cycle torsion_lat
                if (l.eq.k)   cycle torsion_lat
                lr=itabrow(at(l))
 !
                if(lcutoff(l,i)) cycle torsion_lat
                if(lcutoff(l,k)) cycle torsion_lat
                if(lcutoff(l,j)) cycle torsion_lat
                txyz(:,4)=xyz(:,l)
                rij=xyz(:,i)-xyz(:,j)
                d0ij=dav(ir,jr)
                rij0=rav(ir,jr)
                aij =aav(ir,jr)
                rjk=xyz(:,j)-xyz(:,k)
                d0jk=dav(jr,kr)
                rjk0=rav(jr,kr)
                ajk =aav(jr,kr)
                rkl=xyz(:,k)-xyz(:,l)
                d0kl=dav(kr,lr)
                rkl0=rav(kr,lr)
                akl =aav(kr,lr)
                rij2=sum(rij**2)
                rjk2=sum(rjk**2)
                rkl2=sum(rjk**2)
                cosfi2=dot_product(rij,rjk)/sqrt(rij2*rjk2)
                if (abs(cosfi2).gt.cosfi_max) cycle
                cosfi3=dot_product(rkl,rjk)/sqrt(rkl2*rjk2)
                if (abs(cosfi3).gt.cosfi_max) cycle
                gij = fk_lindh(aij,rij0,rij2) &
                   + 0.5_wp*kd * fk_vdw(4.0_wp,d0ij,rij2)
                gjk = fk_lindh(ajk,rjk0,rjk2) &
                   + 0.5_wp*kd * fk_vdw(4.0_wp,d0jk,rjk2)
                gkl = fk_lindh(akl,rkl0,rkl2) &
                   + 0.5_wp*kd * fk_vdw(4.0_wp,d0kl,rkl2)
                tij = kt * gij*gjk*gkl
                !tij = max(tij,10*min_fk)
                !call trsn2(txyz,tau,c)
                Call trsn(txyz,4,tau,c,.false.,.false.,'        ', &
       &                  dum,.false.)
                si = c(:,1)
                sj = c(:,2)
                sk = c(:,3)
                sl = c(:,4)
                ! off diagonal block
                do ic=1,3
                   do jc=1,3
                      hess(ind(ic,i,jc,j))=hess(ind(ic,i,jc,j))+tij*si(ic) * sj(jc)
                      hess(ind(ic,i,jc,k))=hess(ind(ic,i,jc,k))+tij*si(ic) * sk(jc)
                      hess(ind(ic,i,jc,l))=hess(ind(ic,i,jc,l))+tij*si(ic) * sl(jc)
                      hess(ind(ic,j,jc,k))=hess(ind(ic,j,jc,k))+tij*sj(ic) * sk(jc)
                      hess(ind(ic,j,jc,l))=hess(ind(ic,j,jc,l))+tij*sj(ic) * sl(jc)
                      hess(ind(ic,k,jc,l))=hess(ind(ic,k,jc,l))+tij*sk(ic) * sl(jc)
                   end do
                end do
                ! diagonal block
                do ic=1,3
                   do jc=1,ic
                      hess(ind(ic,i,jc,i))=hess(ind(ic,i,jc,i))+tij*si(ic) * si(jc)
                      hess(ind(ic,j,jc,j))=hess(ind(ic,j,jc,j))+tij*sj(ic) * sj(jc)
                      hess(ind(ic,k,jc,k))=hess(ind(ic,k,jc,k))+tij*sk(ic) * sk(jc)
                      hess(ind(ic,l,jc,l))=hess(ind(ic,l,jc,l))+tij*sl(ic) * sl(jc)
                   end do
                end do
             end do torsion_lat
          end do torsion_iat
       end do torsion_kat
    end do torsion_jat
References fk_lindh(), fk_vdw(), ind(), itabrow(), xtb_mctc_constants::pi, and trsn().
Referenced by mh_lindh(), and mh_lindh_d2().
mh_swart()
subroutine, public xtb_modelhessian::mh_swart (real(wp), dimension(3,n), intent(in) xyz, integer, intent(in) n, real(wp), dimension((3*n)*(3*n+1)/2), intent(out) hess, integer, dimension(n), intent(in) at, type(modhess_setvar), intent(in) modh)
Definition at line 99 of file model_hessian.f90.
    use xtb_mctc_constants
    use xtb_mctc_convert
    use xtb_mctc_param, only: rad => covalent_radius_2009
    use xtb_type_setvar
    use xtb_type_param
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: xyz(3,n)
    real(wp),intent(out) :: hess((3*n)*(3*n+1)/2)
    integer, intent(in)  :: at(n)
    type(modhess_setvar),intent(in) :: modh
    integer  :: n3
    real(wp),parameter :: rzero = 1.0e-10_wp
    logical, allocatable :: lcutoff(:,:)
    type(chrg_parameter) :: chrgeq
    real(wp) :: kd
    allocate( lcutoff(n,n), source=.false.)
    n3=3*n
    hess = 0.0d0
 !  the dispersion force constant is used relative to the stretch force constant
    kd = modh%kd/modh%kr
    call mh_swart_stretch(n,at,xyz,hess,modh%kr,kd,modh%s6,rad,rad,lcutoff,modh%rcut)
    if (modh%kf.ne.0.0_wp) &
    call mh_swart_bend   (n,at,xyz,hess,modh%kf,kd,        rad,rad,lcutoff)
    if (modh%kt.ne.0.0_wp) &
    call mh_swart_torsion(n,at,xyz,hess,modh%kt,kd,        rad,rad,lcutoff)
    if (modh%ko.ne.0.0_wp) &
    call mh_swart_outofp (n,at,xyz,hess,modh%ko,kd,        rad,rad,lcutoff)
    if (modh%kq.ne.0.0_wp) then
       call new_charge_model_2019(chrgeq,n,at)
       call mh_eeq(n,at,xyz,0.0_wp,chrgeq,modh%kq,hess)
    endif
References mh_eeq(), mh_swart_bend(), mh_swart_outofp(), mh_swart_stretch(), mh_swart_torsion(), and xtb_chargemodel::new_charge_model_2019().
Referenced by xtb_optimizer::modhes().
mh_swart_bend()
pure subroutine xtb_modelhessian::mh_swart_bend (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension((3*n)*(3*n+1)/2), intent(inout) hess, real(wp), intent(in) kf, real(wp), intent(in) kd, real(wp), dimension(:), intent(in) rcov, real(wp), dimension(:), intent(in) rvdw, logical, dimension(n,n), intent(in) lcutoff)
Definition at line 242 of file model_hessian.f90.
    use xtb_mctc_constants
    implicit none
    integer, intent(in)    :: n
    integer, intent(in)    :: at(n)
    real(wp),intent(in)    :: xyz(3,n)
    real(wp),intent(inout) :: hess((3*n)*(3*n+1)/2)
    real(wp),intent(in)    :: kf
    real(wp),intent(in)    :: kd
    real(wp),intent(in)    :: rcov(:)
    real(wp),intent(in)    :: rvdw(:)
    logical, intent(in)    :: lcutoff(n,n)
    integer  :: i,j,m,ic,jc,ii
    real(wp),parameter :: rzero = 1.0e-10_wp
    real(wp) :: xij,yij,zij,rij2,rrij,r1
    real(wp) :: xmi,ymi,zmi,rmi2,rmi,r0mi,d0mj,gmi
    real(wp) :: xmj,ymj,zmj,rmj2,rmj,r0mj,d0mi,gmj
    real(wp) :: test,gij,rl2,rl,rmidotrmj
    real(wp) :: sinphi,cosphi,costhetax,costhetay,costhetaz
    real(wp) :: alpha
    real(wp) :: si(3),sj(3),sm(3),x(2),y(2),z(2)
 !! ------------------------------------------------------------------------
 !  Hessian for bending
 !! ------------------------------------------------------------------------
    bend_mat: do m = 1, n
       bend_iat: do i = 1, n
          if (i.eq.m) cycle bend_iat
          if(lcutoff(i,m)) cycle bend_iat
          xmi=(xyz(1,i)-xyz(1,m))
          ymi=(xyz(2,i)-xyz(2,m))
          zmi=(xyz(3,i)-xyz(3,m))
          rmi2 = xmi**2 + ymi**2 + zmi**2
          rmi=sqrt(rmi2)
          r0mi=rcov(at(m))+rcov(at(i))
          d0mi=rvdw(at(m))+rvdw(at(i))
          bend_jat: do j = 1, i-1
             if (j.eq.m) cycle bend_jat
             if(lcutoff(j,i)) cycle bend_jat
             if(lcutoff(j,m)) cycle bend_jat
             xmj=(xyz(1,j)-xyz(1,m))
             ymj=(xyz(2,j)-xyz(2,m))
             zmj=(xyz(3,j)-xyz(3,m))
             rmj2 = xmj**2 + ymj**2 + zmj**2
             rmj=sqrt(rmj2)
             r0mj=rcov(at(m))+rcov(at(j))
             d0mj=rvdw(at(m))+rvdw(at(j))
             ! test if zero angle
             test=xmi*xmj+ymi*ymj+zmi*zmj
             test=test/(rmi*rmj)
             if (abs(test-1.0_wp).lt.1.0e-12_wp) cycle bend_jat
             xij=(xyz(1,j)-xyz(1,i))
             yij=(xyz(2,j)-xyz(2,i))
             zij=(xyz(3,j)-xyz(3,i))
             rij2 = xij**2 + yij**2 + zij**2
             rrij=sqrt(rij2)
             gmi = fk_swart(1.0_wp,r0mi,rmi2) &
                 + 0.5_wp*kd * fk_vdw(5.0_wp,d0mi,rmi2)
             gmj = fk_swart(1.0_wp,r0mj,rmj2) &
                 + 0.5_wp*kd * fk_vdw(5.0_wp,d0mj,rmj2)
             gij = kf*gmi*gmj
             rl2=(ymi*zmj-zmi*ymj)**2+(zmi*xmj-xmi*zmj)**2+(xmi*ymj-ymi*xmj)**2
             if(rl2.lt.1.e-14_wp) then
                rl=0.0_wp
             else
                rl=sqrt(rl2)
             end if
             !gij = max(gij,min_fk)
             if ((rmj.gt.rzero).and.(rmi.gt.rzero).and.(rrij.gt.rzero)) then
                sinphi=rl/(rmj*rmi)
                rmidotrmj=xmi*xmj+ymi*ymj+zmi*zmj
                cosphi=rmidotrmj/(rmj*rmi)
                ! none linear case
                if (sinphi.gt.rzero) then
                   si(1)=(xmi/rmi*cosphi-xmj/rmj)/(rmi*sinphi)
                   si(2)=(ymi/rmi*cosphi-ymj/rmj)/(rmi*sinphi)
                   si(3)=(zmi/rmi*cosphi-zmj/rmj)/(rmi*sinphi)
                   sj(1)=(cosphi*xmj/rmj-xmi/rmi)/(rmj*sinphi)
                   sj(2)=(cosphi*ymj/rmj-ymi/rmi)/(rmj*sinphi)
                   sj(3)=(cosphi*zmj/rmj-zmi/rmi)/(rmj*sinphi)
                   sm(1)=-si(1)-sj(1)
                   sm(2)=-si(2)-sj(2)
                   sm(3)=-si(3)-sj(3)
                   do ic=1,3
                      do jc=1,3
                         if (m.gt.i) then
                            hess(ind(ic,m,jc,i))=hess(ind(ic,m,jc,i)) &
                               +gij*sm(ic)*si(jc)
                         else
                            hess(ind(ic,i,jc,m))=hess(ind(ic,i,jc,m)) &
                               +gij*si(ic)*sm(jc)
                         end if
                         if (m.gt.j) then
                            hess(ind(ic,m,jc,j))=hess(ind(ic,m,jc,j)) &
                               +gij*sm(ic)*sj(jc)
                         else
                            hess(ind(ic,j,jc,m))=hess(ind(ic,j,jc,m)) &
                               +gij*sj(ic)*sm(jc)
                         end if
                         if (i.gt.j) then
                            hess(ind(ic,i,jc,j))=hess(ind(ic,i,jc,j)) &
                               +gij*si(ic)*sj(jc)
                         else
                            hess(ind(ic,j,jc,i))=hess(ind(ic,j,jc,i)) &
                               +gij*sj(ic)*si(jc)
                         end if
                      end do
                   end do
                   do ic=1,3
                      do jc=1,ic
                         hess(ind(ic,i,jc,i))=hess(ind(ic,i,jc,i))+gij*si(ic)*si(jc)
                         hess(ind(ic,m,jc,m))=hess(ind(ic,m,jc,m))+gij*sm(ic)*sm(jc)
                         hess(ind(ic,j,jc,j))=hess(ind(ic,j,jc,j))+gij*sj(ic)*sj(jc)
                      end do
                   end do
                else
                   ! linear case
                   if ((abs(ymi).gt.rzero).or.(abs(xmi).gt.rzero)) then
                      x(1)=-ymi
                      y(1)=xmi
                      z(1)=0.0_wp
                      x(2)=-xmi*zmi
                      y(2)=-ymi*zmi
                      z(2)=xmi*xmi+ymi*ymi
                   else
                      x(1)=1.0_wp
                      y(1)=0.0_wp
                      z(1)=0.0_wp
                      x(2)=0.0_wp
                      y(2)=1.0_wp
                      z(2)=0.0_wp
                   end if
                   do ii=1,2
                      r1=sqrt(x(ii)**2+y(ii)**2+z(ii)**2)
                      costhetax=x(ii)/r1
                      costhetay=y(ii)/r1
                      costhetaz=z(ii)/r1
                      si(1)=-costhetax/rmi
                      si(2)=-costhetay/rmi
                      si(3)=-costhetaz/rmi
                      sj(1)=-costhetax/rmj
                      sj(2)=-costhetay/rmj
                      sj(3)=-costhetaz/rmj
                      sm(1)=-(si(1)+sj(1))
                      sm(2)=-(si(2)+sj(2))
                      sm(3)=-(si(3)+sj(3))
                      !
                      do ic=1,3
                         do jc=1,3
                            if (m.gt.i) then
                               hess(ind(ic,m,jc,i))=hess(ind(ic,m,jc,i)) &
                                  +gij*sm(ic)*si(jc)
                            else
                               hess(ind(ic,i,jc,m))=hess(ind(ic,i,jc,m)) &
                                  +gij*si(ic)*sm(jc)
                            end if
                            if (m.gt.j) then
                               hess(ind(ic,m,jc,j))=hess(ind(ic,m,jc,j)) &
                                  +gij*sm(ic)*sj(jc)
                            else
                               hess(ind(ic,j,jc,m))=hess(ind(ic,j,jc,m)) &
                                  +gij*sj(ic)*sm(jc)
                            end if
                            if (i.gt.j) then
                               hess(ind(ic,i,jc,j))=hess(ind(ic,i,jc,j)) &
                                  +gij*si(ic)*sj(jc)
                            else
                               hess(ind(ic,j,jc,i))=hess(ind(ic,j,jc,i)) &
                                  +gij*sj(ic)*si(jc)
                            end if
                         end do
                      end do
                      do ic=1,3
                         do jc=1,ic
                            hess(ind(ic,i,jc,i))=hess(ind(ic,i,jc,i)) &
                               +gij*si(ic)*si(jc)
                            hess(ind(ic,m,jc,m))=hess(ind(ic,m,jc,m)) &
                               +gij*sm(ic)*sm(jc)
                            hess(ind(ic,j,jc,j))=hess(ind(ic,j,jc,j)) &
                               +gij*sj(ic)*sj(jc)
                         end do
                      end do
                   end do
                end if
             end if
          end do bend_jat
       end do bend_iat
    end do bend_mat
References fk_swart(), fk_vdw(), and ind().
Referenced by mh_swart().
mh_swart_outofp()
pure subroutine xtb_modelhessian::mh_swart_outofp (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension((3*n)*(3*n+1)/2), intent(inout) hess, real(wp), intent(in) ko, real(wp), intent(in) kd, real(wp), dimension(:), intent(in) rcov, real(wp), dimension(:), intent(in) rvdw, logical, dimension(n,n), intent(in) lcutoff)
Definition at line 572 of file model_hessian.f90.
    use xtb_mctc_constants
    implicit none
    integer, intent(in)    :: n
    integer, intent(in)    :: at(n)
    real(wp),intent(in)    :: xyz(3,n)
    real(wp),intent(inout) :: hess((3*n)*(3*n+1)/2)
    real(wp),intent(in)    :: ko
    real(wp),intent(in)    :: kd
    real(wp),intent(in)    :: rcov(:)
    real(wp),intent(in)    :: rvdw(:)
    logical, intent(in)    :: lcutoff(n,n)
    integer  :: i,ir,j,jr,k,kr,l,lr,ic,jc
    real(wp) :: txyz(3,4),c(3,4)
    real(wp) :: rij(3),rij0,d0ij,rij2,gij
    real(wp) :: rik(3),rik0,d0ik,rik2,gik
    real(wp) :: ril(3),ril0,d0il,ril2,gil
    real(wp) :: cosfi2,cosfi3,cosfi4
    real(wp) :: beta,tij,tau
    real(wp) :: si(3),sj(3),sk(3),sl(3)
 !! ------------------------------------------------------------------------
 !  Hessian for out-of-plane
 !! ------------------------------------------------------------------------
    outofplane_iat: do i = 1, n
       txyz(:,4) = xyz(:,i)
       outofplane_jat: do j = 1, n
          if (j.eq.i) cycle outofplane_jat
          if(lcutoff(j,i)) cycle outofplane_jat
          txyz(:,1) = xyz(:,j)
          outofplane_kat: do k = 1, n
             if (i.eq.k) cycle outofplane_kat
             if (j.eq.k) cycle outofplane_kat
             if(lcutoff(k,i)) cycle outofplane_kat
             if(lcutoff(k,j)) cycle outofplane_kat
             txyz(:,2) = xyz(:,k)
             outofplane_lat: do l = 1, n
                txyz(:,3) = xyz(:,l)
                if (l.eq.i)   cycle outofplane_lat
                if (l.eq.j)   cycle outofplane_lat
                if (l.eq.k)   cycle outofplane_lat
                if(lcutoff(l,i)) cycle outofplane_lat
                if(lcutoff(l,k)) cycle outofplane_lat
                if(lcutoff(l,j)) cycle outofplane_lat
                rij=xyz(:,i)-xyz(:,j)
                rij0=rcov(at(i))+rcov(at(j))
                d0ij=rvdw(at(i))+rvdw(at(j))
                rik=xyz(:,i)-xyz(:,k)
                rik0=rcov(at(i))+rcov(at(k))
                d0ik=rvdw(at(i))+rvdw(at(k))
                ril=xyz(:,i)-xyz(:,l)
                ril0=rcov(at(i))+rcov(at(l))
                d0il=rvdw(at(i))+rvdw(at(l))
                rij2=sum(rij**2)
                rik2=sum(rik**2)
                ril2=sum(ril**2)
                cosfi2=dot_product(rij,rik)/sqrt(rij2*rik2)
                if (abs(abs(cosfi2)-1.0_wp).lt.1.0e-1_wp) cycle
                cosfi3=dot_product(rij,ril)/sqrt(rij2*ril2)
                if (abs(abs(cosfi3)-1.0_wp).lt.1.0e-1_wp) cycle
                cosfi4=dot_product(rik,ril)/sqrt(rik2*ril2)
                if (abs(abs(cosfi4)-1.0_wp).lt.1.0e-1_wp) cycle
                gij = fk_swart(1.0_wp,rij0,rij2) &
                   + 0.5_wp*kd * fk_vdw(5.0_wp,d0ij,rij2)
                gik = fk_swart(1.0_wp,rik0,rik2) &
                   + 0.5_wp*kd * fk_vdw(5.0_wp,d0ik,rik2)
                gil = fk_swart(1.0_wp,ril0,ril2) &
                   + 0.5_wp*kd * fk_vdw(5.0_wp,d0il,ril2)
                tij = ko * gij*gik*gil
                !tij = max(tij,10*min_fk)
                call outofp2(xyz,tau,c)
                If (abs(tau).gt.45.0d0*(pi/180.d0)) cycle
                si = c(:,4)
                sj = c(:,1)
                sk = c(:,2)
                sl = c(:,3)
                ! off diagonal block
                do ic=1,3
                   do jc=1,3
                      hess(ind(ic,i,jc,j))=hess(ind(ic,i,jc,j))+tij*si(ic) * sj(jc)
                      hess(ind(ic,i,jc,k))=hess(ind(ic,i,jc,k))+tij*si(ic) * sk(jc)
                      hess(ind(ic,i,jc,l))=hess(ind(ic,i,jc,l))+tij*si(ic) * sl(jc)
                      hess(ind(ic,j,jc,k))=hess(ind(ic,j,jc,k))+tij*sj(ic) * sk(jc)
                      hess(ind(ic,j,jc,l))=hess(ind(ic,j,jc,l))+tij*sj(ic) * sl(jc)
                      hess(ind(ic,k,jc,l))=hess(ind(ic,k,jc,l))+tij*sk(ic) * sl(jc)
                   end do
                end do
                ! diagonal block
                do ic=1,3
                   do jc=1,ic
                      hess(ind(ic,i,jc,i))=hess(ind(ic,i,jc,i))+tij*si(ic) * si(jc)
                      hess(ind(ic,j,jc,j))=hess(ind(ic,j,jc,j))+tij*sj(ic) * sj(jc)
                      hess(ind(ic,k,jc,k))=hess(ind(ic,k,jc,k))+tij*sk(ic) * sk(jc)
                      hess(ind(ic,l,jc,l))=hess(ind(ic,l,jc,l))+tij*sl(ic) * sl(jc)
                   end do
                end do
             enddo outofplane_lat
          enddo outofplane_kat
       enddo outofplane_jat
    enddo outofplane_iat
References fk_swart(), fk_vdw(), ind(), outofp2(), and xtb_mctc_constants::pi.
Referenced by mh_swart().
mh_swart_stretch()
pure subroutine xtb_modelhessian::mh_swart_stretch (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension((3*n)*(3*n+1)/2), intent(inout) hess, real(wp), intent(in) kr, real(wp), intent(in) kd, real(wp), intent(in) s6, real(wp), dimension(:), intent(in) rcov, real(wp), dimension(:), intent(in) rvdw, logical, dimension(n,n), intent(out) lcutoff, real(wp), intent(in) rcut)
Definition at line 143 of file model_hessian.f90.
    use xtb_mctc_constants
    use xtb_mctc_convert
    implicit none
    integer, intent(in)    :: n
    integer, intent(in)    :: at(n)
    real(wp),intent(in)    :: xyz(3,n)
    real(wp),intent(inout) :: hess((3*n)*(3*n+1)/2)
    real(wp),intent(in)    :: kr
    real(wp),intent(in)    :: kd
    real(wp),intent(in)    :: s6
    real(wp),intent(in)    :: rcov(:)
    real(wp),intent(in)    :: rvdw(:)
    logical, intent(out)   :: lcutoff(n,n)
    real(wp),intent(in)    :: rcut
    integer  :: i,j
    real(wp) :: xij,yij,zij,rij2,r0,d0
    real(wp) :: gmm
    real(wp) :: c6i,c6j,c6ij,rv
    real(wp) :: hxx,hxy,hxz,hyy,hyz,hzz
    real(wp) :: vdw(3,3)
 !! ------------------------------------------------------------------------
 !  Hessian for stretch
 !! ------------------------------------------------------------------------
    stretch_iat: do i = 1, n
       stretch_jat: do j = 1, i-1
          ! save for later
          lcutoff(i,j) = rcutoff(xyz,i,j,rcut)
          lcutoff(j,i) = lcutoff(i,j)
          xij=xyz(1,i)-xyz(1,j)
          yij=xyz(2,i)-xyz(2,j)
          zij=xyz(3,i)-xyz(3,j)
          rij2 = xij**2 + yij**2 + zij**2
          r0 = rcov(at(i))+rcov(at(j))
          d0 = rvdw(at(i))+rvdw(at(j))
          !cccccc vdwx ccccccccccccccccccccccccccccccccc
          c6i=c6(at(i))
          c6j=c6(at(j))
          c6ij=sqrt(c6i*c6j)
          rv=(vander(at(i))+vander(at(j)))*aatoau
          call getvdwxx(xij, yij, zij, c6ij, s6, rv, vdw(1,1))
          call getvdwxy(xij, yij, zij, c6ij, s6, rv, vdw(1,2))
          call getvdwxy(xij, zij, yij, c6ij, s6, rv, vdw(1,3))
          call getvdwxx(yij, xij, zij, c6ij, s6, rv, vdw(2,2))
          call getvdwxy(yij, zij, xij, c6ij, s6, rv, vdw(2,3))
          call getvdwxx(zij, xij, yij, c6ij, s6, rv, vdw(3,3))
          !cccccc ende vdwx ccccccccccccccccccccccccccccccc
          gmm = kr*fk_swart(1.0_wp,  r0,rij2) &
             + kr*kd * fk_vdw(5.0_wp,d0,rij2)
          !gmm = max(gmm,min_fk)
          hxx=gmm*xij*xij/rij2-vdw(1,1)
          hxy=gmm*xij*yij/rij2-vdw(1,2)
          hxz=gmm*xij*zij/rij2-vdw(1,3)
          hyy=gmm*yij*yij/rij2-vdw(2,2)
          hyz=gmm*yij*zij/rij2-vdw(2,3)
          hzz=gmm*zij*zij/rij2-vdw(3,3)
          ! save diagonal elements for atom i
          hess(ind(1,i,1,i))=hess(ind(1,i,1,i))+hxx
          hess(ind(2,i,1,i))=hess(ind(2,i,1,i))+hxy
          hess(ind(2,i,2,i))=hess(ind(2,i,2,i))+hyy
          hess(ind(3,i,1,i))=hess(ind(3,i,1,i))+hxz
          hess(ind(3,i,2,i))=hess(ind(3,i,2,i))+hyz
          hess(ind(3,i,3,i))=hess(ind(3,i,3,i))+hzz
          ! save elements between atom i and atom j
          hess(ind(1,i,1,j))=hess(ind(1,i,1,j))-hxx
          hess(ind(1,i,2,j))=hess(ind(1,i,2,j))-hxy
          hess(ind(1,i,3,j))=hess(ind(1,i,3,j))-hxz
          hess(ind(2,i,1,j))=hess(ind(2,i,1,j))-hxy
          hess(ind(2,i,2,j))=hess(ind(2,i,2,j))-hyy
          hess(ind(2,i,3,j))=hess(ind(2,i,3,j))-hyz
          hess(ind(3,i,1,j))=hess(ind(3,i,1,j))-hxz
          hess(ind(3,i,2,j))=hess(ind(3,i,2,j))-hyz
          hess(ind(3,i,3,j))=hess(ind(3,i,3,j))-hzz
          ! save diagonal elements for atom j
          hess(ind(1,j,1,j))=hess(ind(1,j,1,j))+hxx
          hess(ind(2,j,1,j))=hess(ind(2,j,1,j))+hxy
          hess(ind(2,j,2,j))=hess(ind(2,j,2,j))+hyy
          hess(ind(3,j,1,j))=hess(ind(3,j,1,j))+hxz
          hess(ind(3,j,2,j))=hess(ind(3,j,2,j))+hyz
          hess(ind(3,j,3,j))=hess(ind(3,j,3,j))+hzz
       end do stretch_jat
    end do stretch_iat
References xtb_mctc_convert::aatoau, c6, fk_swart(), fk_vdw(), getvdwxx(), getvdwxy(), ind(), rcutoff(), and vander.
Referenced by mh_swart().
mh_swart_torsion()
pure subroutine xtb_modelhessian::mh_swart_torsion (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension((3*n)*(3*n+1)/2), intent(inout) hess, real(wp), intent(in) kt, real(wp), intent(in) kd, real(wp), dimension(:), intent(in) rcov, real(wp), dimension(:), intent(in) rvdw, logical, dimension(n,n), intent(in) lcutoff)
Definition at line 449 of file model_hessian.f90.
    use xtb_mctc_constants
    implicit none
    integer, intent(in)    :: n
    integer, intent(in)    :: at(n)
    real(wp),intent(in)    :: xyz(3,n)
    real(wp),intent(inout) :: hess((3*n)*(3*n+1)/2)
    real(wp),intent(in)    :: kt
    real(wp),intent(in)    :: kd
    real(wp),intent(in)    :: rcov(:)
    real(wp),intent(in)    :: rvdw(:)
    logical, intent(in)    :: lcutoff(n,n)
    integer  :: i,j,k,l,ic,jc,ij,kl
 !  allow only angles in the range of 35-145
    real(wp),parameter :: a35 = (35.0d0/180.d0)* pi
    real(wp),parameter :: cosfi_max=cos(a35)
    real(wp) :: txyz(3,4),c(3,4)
    real(wp) :: rij(3),rij0,aij,rij2,d0ij,gij
    real(wp) :: rjk(3),rjk0,ajk,rjk2,d0jk,gjk
    real(wp) :: rkl(3),rkl0,akl,rkl2,d0kl,gkl
    real(wp) :: cosfi2,cosfi3,cosfi4
    real(wp) :: beta,tij,tau
    real(wp) :: si(3),sj(3),sk(3),sl(3)
 !! ------------------------------------------------------------------------
 !  Hessian for torsion
 !! ------------------------------------------------------------------------
    torsion_jat: do j = 1,n
       txyz(:,2)=xyz(:,j)
       torsion_kat: do k = 1, n
          if (k.eq.j) cycle torsion_kat
          if(lcutoff(k,j)) cycle torsion_kat
          txyz(:,3) = xyz(:,k)
          torsion_iat: do i = 1, n
             ij=n*(j-1)+i
             if (i.eq.j) cycle torsion_iat
             if (i.eq.k) cycle torsion_iat
             if(lcutoff(i,k)) cycle torsion_iat
             if(lcutoff(i,j)) cycle torsion_iat
             txyz(:,1)=xyz(:,i)
             torsion_lat: do l = 1, n
                if (ij.le.kl) cycle torsion_lat
                if (l.eq.i)   cycle torsion_lat
                if (l.eq.j)   cycle torsion_lat
                if (l.eq.k)   cycle torsion_lat
 !
                if(lcutoff(l,i)) cycle torsion_lat
                if(lcutoff(l,k)) cycle torsion_lat
                if(lcutoff(l,j)) cycle torsion_lat
                txyz(:,4)=xyz(:,l)
                rij=xyz(:,i)-xyz(:,j)
                d0ij=rvdw(at(i))+rvdw(at(j))
                rij0=rcov(at(i))+rcov(at(j))
                rjk=xyz(:,j)-xyz(:,k)
                d0jk=rvdw(at(j))+rvdw(at(k))
                rjk0=rcov(at(j))+rcov(at(k))
                rkl=xyz(:,k)-xyz(:,l)
                d0kl=rvdw(at(k))+rvdw(at(l))
                rkl0=rcov(at(k))+rcov(at(l))
                rij2=sum(rij**2)
                rjk2=sum(rjk**2)
                rkl2=sum(rjk**2)
                cosfi2=dot_product(rij,rjk)/sqrt(rij2*rjk2)
                if (abs(cosfi2).gt.cosfi_max) cycle
                cosfi3=dot_product(rkl,rjk)/sqrt(rkl2*rjk2)
                if (abs(cosfi3).gt.cosfi_max) cycle
                gij = fk_swart(1.0_wp,rij0,rij2) &
                   + 0.5_wp*kd * fk_vdw(5.0_wp,d0ij,rij2)
                gjk = fk_swart(1.0_wp,rjk0,rjk2) &
                   + 0.5_wp*kd * fk_vdw(5.0_wp,d0jk,rjk2)
                gkl = fk_swart(1.0_wp,rkl0,rkl2) &
                   + 0.5_wp*kd * fk_vdw(5.0_wp,d0kl,rkl2)
                tij = kt * gij*gjk*gkl
                !tij = max(tij,10*min_fk)
                call trsn2(txyz,tau,c)
                si = c(:,1)
                sj = c(:,2)
                sk = c(:,3)
                sl = c(:,4)
                ! off diagonal block
                do ic=1,3
                   do jc=1,3
                      hess(ind(ic,i,jc,j))=hess(ind(ic,i,jc,j))+tij*si(ic) * sj(jc)
                      hess(ind(ic,i,jc,k))=hess(ind(ic,i,jc,k))+tij*si(ic) * sk(jc)
                      hess(ind(ic,i,jc,l))=hess(ind(ic,i,jc,l))+tij*si(ic) * sl(jc)
                      hess(ind(ic,j,jc,k))=hess(ind(ic,j,jc,k))+tij*sj(ic) * sk(jc)
                      hess(ind(ic,j,jc,l))=hess(ind(ic,j,jc,l))+tij*sj(ic) * sl(jc)
                      hess(ind(ic,k,jc,l))=hess(ind(ic,k,jc,l))+tij*sk(ic) * sl(jc)
                   end do
                end do
                ! diagonal block
                do ic=1,3
                   do jc=1,ic
                      hess(ind(ic,i,jc,i))=hess(ind(ic,i,jc,i))+tij*si(ic) * si(jc)
                      hess(ind(ic,j,jc,j))=hess(ind(ic,j,jc,j))+tij*sj(ic) * sj(jc)
                      hess(ind(ic,k,jc,k))=hess(ind(ic,k,jc,k))+tij*sk(ic) * sk(jc)
                      hess(ind(ic,l,jc,l))=hess(ind(ic,l,jc,l))+tij*sl(ic) * sl(jc)
                   end do
                end do
             end do torsion_lat
          end do torsion_iat
       end do torsion_kat
    end do torsion_jat
References fk_swart(), fk_vdw(), ind(), xtb_mctc_constants::pi, and trsn2().
Referenced by mh_swart().
outofp2()
pure subroutine xtb_modelhessian::outofp2 (real(wp), dimension(3,4), intent(in) xyz, real(wp), intent(out) teta, real(wp), dimension(3,4), intent(out) bt) private
Definition at line 1483 of file model_hessian.f90.
    use xtb_mctc_constants
    implicit none
    real(wp),intent(out) :: teta
    real(wp),intent(out) :: bt(3,4)
    real(wp),intent(in)  :: xyz(3,4)
    real(wp) :: r1(3),r2(3),r3(3)
    real(wp) :: q41,q42,q43,e41(3),e42(3),e43(3)
    real(wp) :: cosfi1,fi1,dfi1,cosfi2,fi2,dfi2,cosfi3,fi3,dfi3
    real(wp) :: c14(3,3),br14(3,3)
    real(wp) :: r42(3),r43(3)
    integer  :: ix,iy,iz
 !  4 -> 1 (bond)
    r1=xyz(:,1)-xyz(:,4)
    q41=norm2(r1)
    e41 = r1 / q41
 !  4 -> 2 (bond in plane)
    r2=xyz(:,2)-xyz(:,4)
    q42=norm2(r2)
    e42 = r2 / q42
 !  4 -> 3 (bond in plane)
    r3=xyz(:,3)-xyz(:,4)
    q43=norm2(r3)
    e43 = r3 / q43
 !
 !  get the angle between e43 and e42
 !
    cosfi1 = dot_product(e43,e42)
    fi1=acos(cosfi1)
    dfi1 = 180.d0 * fi1 / pi
 !
 !  dirty exit! this happens when an earlier structure is ill defined.
 !
    if (abs(fi1-pi).lt.1.0d-13) then
       teta=0.0_wp
       bt = 0.0_wp
       return
    end if
 !
 !  get the angle between e41 and e43
 !
    cosfi2 = dot_product(e41,e43)
    fi2=acos(cosfi2)
    dfi2 = 180.d0 * fi2 / pi
 !
 !  get the angle between e41 and e42
 !
    cosfi3 = dot_product(e41,e42)
    fi3=acos(cosfi3)
    dfi3 = 180.d0 * fi3 / pi
 !
 !  the first two centers are trivially
 !
    c14(:,1) = xyz(:,1)
    c14(:,2) = xyz(:,4)
 !
 !  the 3rd is
 !
    r42=xyz(:,2)-xyz(:,4)
    r43=xyz(:,3)-xyz(:,4)
    c14(1,3)=r42(2)*r43(3)-r42(3)*r43(2)
    c14(2,3)=r42(3)*r43(1)-r42(1)*r43(3)
    c14(3,3)=r42(1)*r43(2)-r42(2)*r43(1)
 !
 !  exit if 2-3-4 are collinear
 !  (equivalent to the above check, but this is more concrete)
 !
    if ((c14(1,3)**2+c14(2,3)**2+c14(3,3)**2).lt.1.0d-10) then
       teta=0.0d0
       bt = 0.0_wp
       return
    end if
    c14(1,3)=c14(1,3)+xyz(1,4)
    c14(2,3)=c14(2,3)+xyz(2,4)
    c14(3,3)=c14(3,3)+xyz(3,4)
    call bend2(c14,teta,br14)
    teta = teta - 0.5_wp*pi
 !
 !--compute the wdc matrix
 !
    do ix = 1, 3
       iy = mod(ix+1, 4)+(ix+1)/4
       iz = mod(iy+1, 4)+(iy+1)/4
       bt(ix,1) = - br14(ix,1)
       bt(ix,2) =   r43(iz)*br14(iy,3) - r43(iy)*br14(iz,3)
       bt(ix,3) = - r42(iz)*br14(iy,3) + r42(iy)*br14(iz,3)
       bt(ix,4) = - (bt(ix,1)+bt(ix,2)+bt(ix,3))
    end do
    bt = -bt
References bend2(), and xtb_mctc_constants::pi.
Referenced by mh_lindh_outofp(), and mh_swart_outofp().
rcutoff()
pure logical function xtb_modelhessian::rcutoff (real(wp), dimension(3,*), intent(in) xyz, integer, intent(in) katom, integer, intent(in) latom, real(wp), intent(in) rcut) private
Definition at line 1446 of file model_hessian.f90.
    implicit none
    logical  :: rcutoff
    real(wp),intent(in) :: xyz(3,*)
    real(wp),intent(in) :: rcut
    real(wp) :: rkl(3),rkl2
    integer, intent(in) :: katom,latom
    rcutoff=.false.
    rkl=xyz(:,katom)-xyz(:,latom)
    rkl2 = sum(rkl**2)
    if(rkl2.gt.rcut) rcutoff=.true.
References rcutoff(), and true().
strtch2()
pure subroutine xtb_modelhessian::strtch2 (real(wp), dimension(3,2), intent(in) xyz, real(wp), intent(out) avst, real(wp), dimension(3,2), intent(out) b)
Definition at line 1632 of file model_hessian.f90.
    implicit none
    real(wp),intent(out) :: b(3,2)
    real(wp),intent(in)  :: xyz(3,2)
    real(wp) :: r(3)
    real(wp) :: rr
    real(wp),intent(out) :: avst
    r=xyz(:,2)-xyz(:,1)
    rr=norm2(r)
    avst=rr
    b(:,1)=-r/rr
    b(:,2)=-b(:,1)
Referenced by bend2(), and trsn2().
trsn2()
pure subroutine xtb_modelhessian::trsn2 (real(wp), dimension(3,4), intent(in) xyz, real(wp), intent(out) tau, real(wp), dimension(3,4), intent(out) bt)
Definition at line 1583 of file model_hessian.f90.
    use xtb_mctc_constants
    implicit none
    real(wp),intent(out) :: bt(3,4)
    real(wp),intent(out) :: tau
    real(wp),intent(in)  :: xyz(3,4)
    real(wp) :: rij(3),rij1,brij(3,2)
    real(wp) :: rjk(3),rjk1,brjk(3,2)
    real(wp) :: rkl(3),rkl1,brkl(3,2)
    real(wp) :: bf2(3,3),fi2,sinfi2,cosfi2
    real(wp) :: bf3(3,3),fi3,sinfi3,cosfi3
    real(wp) :: costau,sintau
    integer  :: ix,iy,iz
    call strtch2(xyz(1,1),rij1,brij)
    call strtch2(xyz(1,2),rjk1,brjk)
    call strtch2(xyz(1,3),rkl1,brkl)
    call bend2(xyz(1,1),fi2,bf2)
    sinfi2=sin(fi2)
    cosfi2=cos(fi2)
    call bend2(xyz(1,2),fi3,bf3)
    sinfi3=sin(fi3)
    cosfi3=cos(fi3)
    costau = ( ( brij(2,1)*brjk(3,2) - brij(3,1)*brjk(2,2) ) * &
                ( brjk(2,1)*brkl(3,2) - brjk(3,1)*brkl(2,2) ) + &
                ( brij(3,1)*brjk(1,2) - brij(1,1)*brjk(3,2) ) * &
                ( brjk(3,1)*brkl(1,2) - brjk(1,1)*brkl(3,2) ) + &
                ( brij(1,1)*brjk(2,2) - brij(2,1)*brjk(1,2) ) * &
                ( brjk(1,1)*brkl(2,2) - brjk(2,1)*brkl(1,2) ) ) &
              / (sinfi2*sinfi3)
    sintau = ( brij(1,2) * (brjk(2,1)*brkl(3,2)-brjk(3,1)*brkl(2,2)) &
              + brij(2,2) * (brjk(3,1)*brkl(1,2)-brjk(1,1)*brkl(3,2)) &
              + brij(3,2) * (brjk(1,1)*brkl(2,2)-brjk(2,1)*brkl(1,2)) ) &
              / (sinfi2*sinfi3)
    tau = atan2(sintau,costau)
    if (abs(tau).eq.pi) tau=pi
    do ix = 1, 3
       iy=ix+1
       if (iy.gt.3) iy=iy-3
       iz=iy+1
       if (iz.gt.3) iz=iz-3
       bt(ix,1) = (brij(iy,2)*brjk(iz,2)-brij(iz,2)*brjk(iy,2)) &
          &           / (rij1*sinfi2**2)
       bt(ix,4) = (brkl(iy,1)*brjk(iz,1)-brkl(iz,1)*brjk(iy,1)) &
          &           / (rkl1*sinfi3**2)
       bt(ix,2) = -( (rjk1-rij1*cosfi2) * bt(ix,1) &
          &             +         rkl1*cosfi3  * bt(ix,4))/rjk1
       bt(ix,3) = - ( bt(ix,1)+bt(ix,2)+bt(ix,4))
    end do
References bend2(), xtb_mctc_constants::pi, and strtch2().
Referenced by mh_swart_torsion().
Variable Documentation
c6
real(wp), dimension(86), parameter xtb_modelhessian::c6 = (/ 0.14_wp, 0.08_wp, 1.61_wp, 1.61_wp, 3.13_wp, 1.75_wp, 1.23_wp, 0.70_wp, 0.75_wp, 0.63_wp, 5.71_wp, 5.71_wp,10.79_wp, 9.23_wp, 7.84_wp, 5.57_wp, 5.07_wp, 4.61_wp, 10.80_wp,10.80_wp, 10.80_wp,10.80_wp,10.80_wp,10.80_wp,10.80_wp, 10.80_wp,10.80_wp,10.80_wp,10.80_wp,10.80_wp, 16.99_wp,17.10_wp,16.37_wp,12.64_wp,12.47_wp,12.01_wp, 24.67_wp,24.67_wp, 24.67_wp,24.67_wp,24.67_wp,24.67_wp,24.67_wp, 24.67_wp,24.67_wp,24.67_wp,24.67_wp,24.67_wp, 37.32_wp,38.71_wp,38.44_wp,31.74_wp,31.50_wp,29.99_wp, 50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, 50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp /) private
Definition at line 57 of file model_hessian.f90.
    real(wp),parameter :: c6(86) = (/&
       0.14_wp, 0.08_wp, & ! H,He
       1.61_wp, 1.61_wp, 3.13_wp, 1.75_wp, 1.23_wp, 0.70_wp, 0.75_wp, 0.63_wp, &
       5.71_wp, 5.71_wp,10.79_wp, 9.23_wp, 7.84_wp, 5.57_wp, 5.07_wp, 4.61_wp, &
      10.80_wp,10.80_wp, & ! K,Ca
      10.80_wp,10.80_wp,10.80_wp,10.80_wp,10.80_wp, & ! Sc-Zn
      10.80_wp,10.80_wp,10.80_wp,10.80_wp,10.80_wp, &
      16.99_wp,17.10_wp,16.37_wp,12.64_wp,12.47_wp,12.01_wp, & ! Ga-Kr
      24.67_wp,24.67_wp, & ! Rb,Sr
      24.67_wp,24.67_wp,24.67_wp,24.67_wp,24.67_wp, & ! Y-Cd
      24.67_wp,24.67_wp,24.67_wp,24.67_wp,24.67_wp, &
      37.32_wp,38.71_wp,38.44_wp,31.74_wp,31.50_wp,29.99_wp, & ! In-Xe
      50.00_wp,50.00_wp, & ! Cs,Ba
      50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, & ! La-Yb
      50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, &
      50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, & ! Lu-Hg
      50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp, &
      50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp,50.00_wp /) ! Tl-Rn
Referenced by mh_lindh_stretch(), and mh_swart_stretch().
min_fk
real(wp), parameter xtb_modelhessian::min_fk = 1.0e-3_wp private
Definition at line 76 of file model_hessian.f90.
    real(wp),parameter :: min_fk = 1.0e-3_wp
vander
real(wp), dimension(86), parameter xtb_modelhessian::vander = aatoau * (/ 0.91_wp,0.92_wp, 0.75_wp,1.28_wp,1.35_wp,1.32_wp,1.27_wp,1.22_wp,1.17_wp,1.13_wp, 1.04_wp,1.24_wp,1.49_wp,1.56_wp,1.55_wp,1.53_wp,1.49_wp,1.45_wp, 1.35_wp,1.34_wp, 1.42_wp,1.42_wp,1.42_wp,1.42_wp,1.42_wp, 1.42_wp,1.42_wp,1.42_wp,1.42_wp,1.42_wp, 1.50_wp,1.57_wp,1.60_wp,1.61_wp,1.59_wp,1.57_wp, 1.48_wp,1.46_wp, 1.49_wp,1.49_wp,1.49_wp,1.49_wp,1.49_wp, 1.49_wp,1.49_wp,1.49_wp,1.49_wp,1.49_wp, 1.52_wp,1.64_wp,1.71_wp,1.72_wp,1.72_wp,1.71_wp, 2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, 2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp /) private
Definition at line 38 of file model_hessian.f90.
    real(wp),parameter :: vander(86) = aatoau * (/ &
      0.91_wp,0.92_wp, & ! H, He
      0.75_wp,1.28_wp,1.35_wp,1.32_wp,1.27_wp,1.22_wp,1.17_wp,1.13_wp, & ! Li-Ne
      1.04_wp,1.24_wp,1.49_wp,1.56_wp,1.55_wp,1.53_wp,1.49_wp,1.45_wp, & ! Na-Ar
      1.35_wp,1.34_wp, & ! K, Ca
      1.42_wp,1.42_wp,1.42_wp,1.42_wp,1.42_wp, & ! Sc-Zn
      1.42_wp,1.42_wp,1.42_wp,1.42_wp,1.42_wp, &
      1.50_wp,1.57_wp,1.60_wp,1.61_wp,1.59_wp,1.57_wp, & ! Ga-Kr
      1.48_wp,1.46_wp, & ! Rb, Sr
      1.49_wp,1.49_wp,1.49_wp,1.49_wp,1.49_wp, & ! Y-Cd
      1.49_wp,1.49_wp,1.49_wp,1.49_wp,1.49_wp, &
      1.52_wp,1.64_wp,1.71_wp,1.72_wp,1.72_wp,1.71_wp, & ! In-Xe
      2.00_wp,2.00_wp, &
      2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, & ! La-Yb
      2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, &
      2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, & ! Lu-Hg
      2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp, &
      2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp,2.00_wp /) ! Tl-Rn
Referenced by mh_lindh_stretch(), and mh_swart_stretch().