My Project: xtb_type_coulomb Module Reference
xtb_type_coulomb Module Reference
Implementation of coulombic interaction evaluator.
Data Types
type tcoulomb
Base point charge electrostatics evaluator.
interface init
Functions/Subroutines
subroutine initfrommolecule (self, env, mol, num, nshell, alpha, tolerance)
subroutine initcoulomb (self, env, id, lattice, boundaryCond, num, nshell, alpha, tolerance)
subroutine, public setupindextable (natom, itbl, id, num, nshell)
subroutine, public setupboundaryconditions (self, env, lattice, alpha, tolerance)
subroutine update (self, env, mol)
Update internal state of the Coulomb evaluator.
subroutine getcoulombmatrix (self, mol, jmat)
subroutine getcoulombmatrixcluster (mol, itbl, jmat)
subroutine getcoulombmatrixpbc3d (wsCell, itbl, alpha, volume, rTrans, gTrans, jmat)
pure real(wp) function getrterm (vec, rTrans, alpha, scale)
subroutine getcoulombderivs (self, mol, qvec, djdr, djdtr, djdL)
subroutine getcoulombderivscluster (mol, itbl, qvec, djdr, djdtr, djdL)
subroutine getcoulombderivspbc3d (wsCell, itbl, alpha, volume, rTrans, gTrans, qvec, djdr, djdtr, djdL)
pure subroutine getrderiv (vec, rTrans, alpha, scale, dG, dS)
Detailed Description
Implementation of coulombic interaction evaluator.
Function/Subroutine Documentation
getcoulombderivs()
subroutine xtb_type_coulomb::getcoulombderivs (class(tcoulomb), intent(inout) self, type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(in) qvec, real(wp), dimension(:, :, :), intent(out) djdr, real(wp), dimension(:, :), intent(out) djdtr, real(wp), dimension(:, :, :), intent(out) djdL) private
Parameters
[in,out] self Instance of the Coulomb evaluator
[in] mol Molecular structure data
[in] qvec Charges
[out] djdr Derivative of Coulomb matrix w.r.t. Cartesian coordinates
[out] djdtr Trace derivative of Coulomb matrix
[out] djdl Derivative of Coulomb matrix w.r.t. strain deformations
Definition at line 497 of file coulomb.f90.
    class(TCoulomb), intent(inout) :: self
    type(TMolecule), intent(in) :: mol
    real(wp), intent(in) :: qvec(:)
    real(wp), intent(out) :: djdr(:, :, :)
    real(wp), intent(out) :: djdtr(:, :)
    real(wp), intent(out) :: djdL(:, :, :)
    select case(self%boundaryCondition)
    case(boundarycondition%cluster)
       call getcoulombderivscluster(mol, self%itbl, qvec, djdr, djdtr, djdl)
    case(boundarycondition%pbc3d)
       call getcoulombderivspbc3d(self%wsCell, self%itbl, self%alpha, mol%volume, &
          & self%rTrans, self%gTrans(:, 2:), qvec, djdr, djdtr, djdl)
    end select
References xtb_mctc_boundaryconditions::boundarycondition, getcoulombderivscluster(), and getcoulombderivspbc3d().
getcoulombderivscluster()
subroutine xtb_type_coulomb::getcoulombderivscluster (type(tmolecule), intent(in) mol, integer, dimension(:, :), intent(in) itbl, real(wp), dimension(:), intent(in) qvec, real(wp), dimension(:, :, :), intent(out) djdr, real(wp), dimension(:, :), intent(out) djdtr, real(wp), dimension(:, :, :), intent(out) djdL) private
Parameters
[in] mol Molecular structure data
[in] itbl Index table
[in] qvec Charges
[out] djdr Derivative of Coulomb matrix w.r.t. Cartesian coordinates
[out] djdtr Trace derivative of Coulomb matrix
[out] djdl Derivative of Coulomb matrix w.r.t. strain deformations
Definition at line 528 of file coulomb.f90.
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: itbl(:, :)
    real(wp), intent(in) :: qvec(:)
    real(wp), intent(out) :: djdr(:, :, :)
    real(wp), intent(out) :: djdtr(:, :)
    real(wp), intent(out) :: djdL(:, :, :)
    integer :: iat, jat, ish, jsh, ii, jj
    real(wp) :: r1, vec(3), dG(3), dS(3, 3)
    djdr(:, :, :) = 0.0_wp
    djdtr(:, :) = 0.0_wp
    djdl(:, :, :) = 0.0_wp
    !$omp parallel do default(none) reduction(+:djdr, djdtr, djdL) &
    !$omp shared(mol, itbl, qvec) &
    !$omp private(iat, jat, ish, jsh, ii, jj, r1, vec, dG, dS)
    do iat = 1, len(mol)
       ii = itbl(1, iat)
       do jat = 1, iat-1
          jj = itbl(1, jat)
          vec(:) = mol%xyz(:, jat) - mol%xyz(:, iat)
          r1 = norm2(vec)
          dg(:) = -vec/r1**3
          ds(:, :) = 0.5_wp * spread(dg, 1, 3) * spread(vec, 2, 3)
          do ish = 1, itbl(2, iat)
             do jsh = 1, itbl(2, jat)
                djdr(:, iat, jj+jsh) = djdr(:, iat, jj+jsh) - dg*qvec(ii+ish)
                djdr(:, jat, ii+ish) = djdr(:, jat, ii+ish) + dg*qvec(jj+jsh)
                djdtr(:, jj+jsh) = djdtr(:, jj+jsh) + dg*qvec(ii+ish)
                djdtr(:, ii+ish) = djdtr(:, ii+ish) - dg*qvec(jj+jsh)
                djdl(:, :, jj+jsh) = djdl(:, :, jj+jsh) + ds*qvec(ii+ish)
                djdl(:, :, ii+ish) = djdl(:, :, ii+ish) + ds*qvec(jj+jsh)
             end do
          end do
       end do
    end do
    !$omp end parallel do
Referenced by getcoulombderivs().
getcoulombderivspbc3d()
subroutine xtb_type_coulomb::getcoulombderivspbc3d (type(twignerseitzcell), intent(in) wsCell, integer, dimension(:, :), intent(in) itbl, real(wp), intent(in) alpha, real(wp), intent(in) volume, real(wp), dimension(:, :), intent(in) rTrans, real(wp), dimension(:, :), intent(in) gTrans, real(wp), dimension(:), intent(in) qvec, real(wp), dimension(:, :, :), intent(out) djdr, real(wp), dimension(:, :), intent(out) djdtr, real(wp), dimension(:, :, :), intent(out) djdL) private
Parameters
[in] wscell Wigner-Seitz cell
[in] volume Cell volume
[in] alpha Convergence factor
[in] rtrans Real space lattice translations
[in] gtrans Reciprocal space lattice translations
[in] itbl Index table
[in] qvec Charges
[out] djdr Derivative of Coulomb matrix w.r.t. Cartesian coordinates
[out] djdtr Trace derivative of Coulomb matrix
[out] djdl Derivative of Coulomb matrix w.r.t. strain deformations
Definition at line 583 of file coulomb.f90.
    type(TWignerSeitzCell), intent(in) :: wsCell
    real(wp), intent(in) :: volume
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: rTrans(:, :)
    real(wp), intent(in) :: gTrans(:, :)
    integer, intent(in) :: itbl(:, :)
    real(wp), intent(in) :: qvec(:)
    real(wp), intent(out) :: djdr(:, :, :)
    real(wp), intent(out) :: djdtr(:, :)
    real(wp), intent(out) :: djdL(:, :, :)
    integer :: iat, jat, ish, jsh, ii, jj, ineigh, img
    real(wp) :: weight, vec(3), dG(3), dS(3, 3), dGg(3), dGr(3), dSg(3, 3), dSr(3, 3)
    real(wp), parameter :: unity(3, 3) = reshape(&
       & [1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp], &
       & [3, 3])
    djdr(:, :, :) = 0.0_wp
    djdtr(:, :) = 0.0_wp
    djdl(:, :, :) = 0.0_wp
    !$omp parallel do default(none) reduction(+:djdr, djdtr, djdL) &
    !$omp shared(wsCell, itbl, qvec, alpha, volume, gTrans, rTrans) &
    !$omp private(iat, ineigh, img, jat, ish, jsh, ii, jj, vec, weight, dG, dS,&
    !$omp& dGg, dGr, dSg, dSr)
    do iat = 1, size(wscell%neighs)
       ii = itbl(1, iat)
       do ineigh = 1, wscell%neighs(iat)
          img = wscell%ineigh(ineigh, iat)
          jat = wscell%image(img)
          jj = itbl(1, jat)
          weight = wscell%weight(ineigh, iat)
          vec(:) = wscell%coords(:, img) - wscell%coords(:, iat)
          call ewaldderivpbc3d(vec, gtrans, 0.0_wp, volume, alpha, weight, dgg, dsg)
          call getrderiv(vec, rtrans, alpha, weight, dgr, dsr)
          dg(:) = dgg + dgr
          ds(:, :) = dsg + dsr + pi / (volume * alpha**2) * weight * unity
          if (iat /= jat) then
             do ish = 1, itbl(2, iat)
                do jsh = 1, itbl(2, jat)
                   djdr(:, iat, jj+jsh) = djdr(:, iat, jj+jsh) - dg*qvec(ii+ish)
                   djdr(:, jat, ii+ish) = djdr(:, jat, ii+ish) + dg*qvec(jj+jsh)
                   djdtr(:, jj+jsh) = djdtr(:, jj+jsh) + dg*qvec(ii+ish)
                   djdtr(:, ii+ish) = djdtr(:, ii+ish) - dg*qvec(jj+jsh)
                   djdl(:, :, jj+jsh) = djdl(:, :, jj+jsh) + ds*qvec(ii+ish)
                   djdl(:, :, ii+ish) = djdl(:, :, ii+ish) + ds*qvec(jj+jsh)
                end do
             end do
          else
             do ish = 1, itbl(2, iat)
                do jsh = 1, ish-1
                   djdl(:, :, ii+jsh) = djdl(:, :, ii+jsh) + ds*qvec(ii+ish)
                   djdl(:, :, ii+ish) = djdl(:, :, ii+ish) + ds*qvec(ii+jsh)
                end do
                djdl(:, :, ii+ish) = djdl(:, :, ii+ish) + ds*qvec(ii+ish)
             end do
          end if
       end do
    end do
    !$omp end parallel do
References xtb_coulomb_ewald::ewaldderivpbc3d(), getrderiv(), and xtb_mctc_constants::pi.
Referenced by getcoulombderivs().
getcoulombmatrix()
subroutine xtb_type_coulomb::getcoulombmatrix (class(tcoulomb), intent(inout) self, type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(out) jmat) private
Parameters
[in,out] self Instance of the Coulomb evaluator
[in] mol Molecular structure data
[out] jmat Coulomb matrix
Definition at line 347 of file coulomb.f90.
    class(TCoulomb), intent(inout) :: self
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: jmat(:, :)
    select case(self%boundaryCondition)
    case(boundarycondition%cluster)
       call getcoulombmatrixcluster(mol, self%itbl, jmat)
    case(boundarycondition%pbc3d)
       call getcoulombmatrixpbc3d(self%wsCell, self%itbl, self%alpha, &
          & mol%volume, self%rTrans, self%gTrans(:, 2:), jmat)
    end select
References xtb_mctc_boundaryconditions::boundarycondition, getcoulombmatrixcluster(), and getcoulombmatrixpbc3d().
getcoulombmatrixcluster()
subroutine xtb_type_coulomb::getcoulombmatrixcluster (type(tmolecule), intent(in) mol, integer, dimension(:, :), intent(in) itbl, real(wp), dimension(:, :), intent(out) jmat) private
Parameters
[in] mol Molecular structure data
[in] itbl Index table
[out] jmat Coulomb matrix
Definition at line 369 of file coulomb.f90.
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: itbl(:, :)
    real(wp), intent(out) :: jmat(:, :)
    integer :: iat, jat, ish, jsh, ii, jj
    real(wp) :: r1, rterm
    jmat(:, :) = 0.0_wp
    !$omp parallel do default(none) shared(mol, itbl, jmat) &
    !$omp private(iat, jat, ish, jsh, ii, jj, r1, rterm)
    do iat = 1, len(mol)
       ii = itbl(1, iat)
       do jat = 1, iat-1
          jj = itbl(1, jat)
          r1 = sqrt(sum((mol%xyz(:, jat) - mol%xyz(:, iat))**2))
          rterm = 1.0_wp/r1
          do ish = 1, itbl(2, iat)
             do jsh = 1, itbl(2, jat)
                jmat(jj+jsh, ii+ish) = rterm
                jmat(ii+ish, jj+jsh) = rterm
             end do
          end do
       end do
    end do
    !$omp end parallel do
Referenced by getcoulombmatrix().
getcoulombmatrixpbc3d()
subroutine xtb_type_coulomb::getcoulombmatrixpbc3d (type(twignerseitzcell), intent(in) wsCell, integer, dimension(:, :), intent(in) itbl, real(wp), intent(in) alpha, real(wp), intent(in) volume, real(wp), dimension(:, :), intent(in) rTrans, real(wp), dimension(:, :), intent(in) gTrans, real(wp), dimension(:, :), intent(out) jmat) private
Parameters
[in] wscell Wigner-Seitz cell
[in] itbl Index table
[in] volume Cell volume
[in] alpha Convergence factor
[in] rtrans Real space lattice translations
[in] gtrans Reciprocal space lattice translations
[out] jmat Coulomb matrix
Definition at line 406 of file coulomb.f90.
    type(TWignerSeitzCell), intent(in) :: wsCell
    integer, intent(in) :: itbl(:, :)
    real(wp), intent(in) :: volume
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: rTrans(:, :)
    real(wp), intent(in) :: gTrans(:, :)
    real(wp), intent(out) :: jmat(:, :)
    integer :: iat, ineigh, img, jat, ish, jsh, ii, jj
    real(wp) :: vec(3), rterm, weight
    real(wp), parameter :: zero(3) = 0.0_wp
    jmat(:, :) = 0.0_wp
    !$omp parallel do default(none) reduction(+:jmat) &
    !$omp shared(wsCell, itbl, alpha, volume, gTrans, rTrans) &
    !$omp private(iat, ineigh, img, jat, ish, jsh, ii, jj, rterm, vec, weight)
    do iat = 1, size(wscell%neighs)
       ii = itbl(1, iat)
       do ineigh = 1, wscell%neighs(iat)
          img = wscell%ineigh(ineigh, iat)
          jat = wscell%image(img)
          jj = itbl(1, jat)
          weight = wscell%weight(ineigh, iat)
          vec(:) = wscell%coords(:, img) - wscell%coords(:, iat)
          rterm = ewaldmatpbc3d(vec, gtrans, 0.0_wp, volume, alpha, weight) &
             &  + getrterm(vec, rtrans, alpha, weight) &
             &  - pi / (volume * alpha**2) * weight
          if (iat /= jat) then
             do ish = 1, itbl(2, iat)
                do jsh = 1, itbl(2, jat)
                   jmat(jj+jsh, ii+ish) = jmat(jj+jsh, ii+ish) + rterm
                   jmat(ii+ish, jj+jsh) = jmat(ii+ish, jj+jsh) + rterm
                end do
             end do
          else
             do ish = 1, itbl(2, iat)
                do jsh = 1, ish-1
                   jmat(ii+jsh, ii+ish) = jmat(ii+jsh, ii+ish) + rterm
                   jmat(ii+ish, ii+jsh) = jmat(ii+ish, ii+jsh) + rterm
                end do
                jmat(ii+ish, ii+ish) = jmat(ii+ish, ii+ish) + rterm
             end do
          end if
       end do
    end do
    !$omp end parallel do
References xtb_coulomb_ewald::ewaldmatpbc3d(), xtb_coulomb_ewald::getrterm(), and xtb_mctc_constants::pi.
Referenced by getcoulombmatrix().
getrderiv()
pure subroutine xtb_type_coulomb::getrderiv (real(wp), dimension(:), intent(in) vec, real(wp), dimension(:,:), intent(in) rTrans, real(wp), intent(in) alpha, real(wp), intent(in) scale, real(wp), dimension(:), intent(out) dG, real(wp), dimension(:,:), intent(out) dS) private
Definition at line 669 of file coulomb.f90.
    real(wp), intent(in) :: vec(:)
    real(wp), intent(in) :: rTrans(:,:)
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: scale
    real(wp), intent(out) :: dG(:)
    real(wp), intent(out) :: dS(:,:)
    real(wp), parameter :: eps = 1.0e-9_wp
    integer :: itr
    real(wp) :: r1, rij(3), arg, dd
    real(wp), parameter :: unity(3, 3) = reshape(&
       & [1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp], &
       & [3, 3])
    dg = 0.0_wp
    ds = 0.0_wp
    do itr = 1, size(rtrans, dim=2)
       ! real contributions
       rij = vec + rtrans(:, itr)
       r1 = norm2(rij)
       if (r1 < eps) cycle
       arg = alpha**2*r1**2
       dd = - 2*alpha*exp(-arg)/(sqrtpi*r1**2) - erfc(alpha*r1)/(r1**3)
       dg = dg + rij*dd
       ds = ds + 0.5_wp*dd*spread(rij, 1, 3)*spread(rij, 2, 3)
    enddo
    dg = dg * scale
    ds = ds * scale
References xtb_mctc_constants::sqrtpi.
Referenced by getcoulombderivspbc3d().
getrterm()
pure real(wp) function xtb_type_coulomb::getrterm (real(wp), dimension(3), intent(in) vec, real(wp), dimension(:,:), intent(in) rTrans, real(wp), intent(in) alpha, real(wp), intent(in) scale) private
Definition at line 473 of file coulomb.f90.
    real(wp),intent(in) :: vec(3)
    real(wp),intent(in) :: rTrans(:,:)
    real(wp),intent(in) :: alpha
    real(wp),intent(in) :: scale
    real(wp) :: rTerm
    real(wp),parameter :: eps = 1.0e-9_wp
    integer  :: itr
    real(wp) :: r1, rij(3)
    rterm = 0.0_wp
    do itr = 1, size(rtrans, dim=2)
       rij = vec + rtrans(:, itr)
       r1 = norm2(rij)
       ! self-interaction correction
       if(r1 < eps) then
          rterm = rterm - 2.0_wp*alpha/sqrtpi
       else
          rterm = rterm + erfc(alpha*r1)/r1
       end if
    end do
    rterm = rterm * scale
References xtb_mctc_constants::sqrtpi.
initcoulomb()
subroutine xtb_type_coulomb::initcoulomb (type(tcoulomb), intent(out) self, type(tenvironment), intent(inout) env, integer, dimension(:), intent(in) id, real(wp), dimension(:, :), intent(in) lattice, integer, intent(in) boundaryCond, integer, dimension(:), intent(in), optional num, integer, dimension(:), intent(in), optional nshell, real(wp), intent(in), optional alpha, real(wp), intent(in), optional tolerance) private
Parameters
[out] self Instance of the Coulomb evaluator
[in] id Identity of each atom
[in,out] env Calculation environment
[in] lattice Lattice parameters
[in] boundarycond Boundary conditions for this evaluator
[in] num Atomic number for each id
[in] nshell Number of shell for each species
[in] alpha Convergence factor
[in] tolerance Tolerance for the Ewald sum
Definition at line 144 of file coulomb.f90.
    character(len=*), parameter :: source = 'type_coulomb_initCoulomb'
    type(TCoulomb), intent(out) :: self
    integer, intent(in) :: id(:)
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: lattice(:, :)
    integer, intent(in) :: boundaryCond
    integer, intent(in), optional :: num(:)
    integer, intent(in), optional :: nshell(:)
    real(wp), intent(in), optional :: alpha
    real(wp), intent(in), optional :: tolerance
    logical :: exitRun
    self%boundaryCondition = boundarycond
    self%natom = size(id, dim=1)
    call setupindextable(self%natom, self%itbl, id, num, nshell)
    call setupboundaryconditions(self, env, lattice, alpha, tolerance)
initfrommolecule()
subroutine xtb_type_coulomb::initfrommolecule (type(tcoulomb), intent(out) self, type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, integer, dimension(:), intent(in), optional num, integer, dimension(:), intent(in), optional nshell, real(wp), intent(in), optional alpha, real(wp), intent(in), optional tolerance) private
Parameters
[out] self Instance of the Coulomb evaluator
[in,out] env Calculation environment
[in] mol Molecular structure data
[in] num Atomic number for each id
[in] nshell Number of shell for each species
[in] alpha Convergence factor
[in] tolerance Tolerance for the Ewald sum
Definition at line 101 of file coulomb.f90.
    character(len=*), parameter :: source = 'type_coulomb_initFromMolecule'
    type(TCoulomb), intent(out) :: self
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    integer, intent(in), optional :: num(:)
    integer, intent(in), optional :: nshell(:)
    real(wp), intent(in), optional :: alpha
    real(wp), intent(in), optional :: tolerance
    logical :: exitRun
    call init(self, env, mol%id, mol%lattice, mol%boundaryCondition, num, nshell, &
       & alpha, tolerance)
    call env%check(exitrun)
    if (exitrun) return
    call self%update(env, mol)
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Initializing internal state of evaluator failed", source)
    end if
setupboundaryconditions()
subroutine, public xtb_type_coulomb::setupboundaryconditions (class(tcoulomb), intent(inout) self, type(tenvironment), intent(inout) env, real(wp), dimension(:, :), intent(in) lattice, real(wp), intent(in), optional alpha, real(wp), intent(in), optional tolerance)
Parameters
[in,out] self Instance of the Coulomb evaluator
[in,out] env Calculation environment
[in] lattice Lattice parameters
[in] alpha Convergence factor
[in] tolerance Tolerance for the Ewald sum
Definition at line 233 of file coulomb.f90.
    character(len=*), parameter :: source = 'type_coulomb_setupBoundaryConditions'
    class(TCoulomb), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: lattice(:, :)
    real(wp), intent(in), optional :: alpha
    real(wp), intent(in), optional :: tolerance
    logical :: exitRun
    real(wp) :: volume, recLat(3, 3)
    select case(self%boundaryCondition)
    case default
       call env%error("Boundary condition not supported", source)
    case(boundarycondition%cluster)
       ! nothing to do
    case(boundarycondition%pbc3d)
       volume = abs(matdet3x3(lattice))
       reclat(:, :) = 2*pi*transpose(matinv3x3(lattice))
       if (present(tolerance)) then
          self%tolerance = tolerance
       else
          self%tolerance = 1.0e-8_wp
       end if
       if (present(alpha)) then
          self%alpha = alpha
       else
          call getoptimalalpha(env, lattice, reclat, volume, self%tolerance, &
             & self%alpha)
       end if
       call getmaxr(env, self%alpha, self%tolerance, self%rCutoff)
       call getmaxg(env, self%alpha, volume, self%tolerance, self%gCutoff)
       call env%check(exitrun)
       if (exitrun) then
          call env%error("Could not setup numerical thresholds", source)
          return
       end if
       call init(self%rLatPoint, env, lattice, self%boundaryCondition, self%rCutoff)
       call init(self%gLatPoint, env, reclat, self%boundaryCondition, self%gCutoff)
       call init(self%wsCell, self%natom)
    end select
References xtb_mctc_boundaryconditions::boundarycondition, xtb_coulomb_ewald::getmaxg(), xtb_coulomb_ewald::getmaxr(), xtb_coulomb_ewald::getoptimalalpha(), xtb_mctc_math::matdet3x3(), xtb_mctc_math::matinv3x3(), and xtb_mctc_constants::pi.
Referenced by xtb_type_coulomb::init::initcoulomb(), xtb_coulomb_gaussian::init::initgaussiansmeared(), and xtb_coulomb_klopmanohno::init::initklopmanohno().
setupindextable()
subroutine, public xtb_type_coulomb::setupindextable (integer, intent(in) natom, integer, dimension(:, :), intent(out), allocatable itbl, integer, dimension(:), intent(in) id, integer, dimension(:), intent(in), optional num, integer, dimension(:), intent(in), optional nshell)
Parameters
[in] natom Number of atoms
[out] itbl Index table
[in] id Identity of each atom
[in] num Atomic number for each id
[in] nshell Number of shell for each species
Definition at line 189 of file coulomb.f90.
    integer, intent(in) :: natom
    integer, allocatable, intent(out) :: itbl(:, :)
    integer, intent(in) :: id(:)
    integer, intent(in), optional :: num(:)
    integer, intent(in), optional :: nshell(:)
    integer :: ind, iat, ish
    allocate(itbl(2, natom))
    if (present(nshell)) then
       ind = 0
       if (present(num)) then
          do iat = 1, natom
             ish = nshell(num(id(iat)))
             itbl(:, iat) = [ind, ish]
             ind = ind + ish
          end do
       else
          do iat = 1, natom
             ish = nshell(id(iat))
             itbl(:, iat) = [ind, ish]
             ind = ind + ish
          end do
       end if
    else
       do iat = 1, natom
          itbl(:, iat) = [iat-1, 1]
       end do
    end if
Referenced by xtb_type_coulomb::init::initcoulomb(), xtb_coulomb_gaussian::init::initgaussiansmeared(), and xtb_coulomb_klopmanohno::init::initklopmanohno().
update()
subroutine xtb_type_coulomb::update (class(tcoulomb), intent(inout) self, type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol) private
Update internal state of the Coulomb evaluator.
Parameters
[in,out] self Instance of the Coulomb evaluator
[in,out] env Calculation environment
[in] mol Molecular structure data
No need for updates in case of cluster calculations
Definition at line 296 of file coulomb.f90.
    character(len=*), parameter :: source = 'type_coulomb_update'
    class(TCoulomb), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    integer :: nTransOld
    logical :: exitRun
    if (self%boundaryCondition == boundarycondition%cluster) return
    call self%rLatPoint%update(env, mol%lattice)
    call self%gLatPoint%update(env, mol%rec_lat)
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Could not update lattice points", source)
       return
    end if
    if (allocated(self%rTrans)) then
       ntransold = size(self%rTrans)
    else
       ntransold = 0
    end if
    call self%rLatPoint%getLatticePoints(self%rTrans)
    call self%gLatPoint%getLatticePoints(self%gTrans)
    if (size(self%rTrans) /= ntransold) then
       call self%wsCell%generate(env, mol%xyz, self%rCutoff, self%rTrans, .false.)
       call env%check(exitrun)
       if (exitrun) then
          call env%error("Failed to generate Wigner-Seitz cell", source)
          return
       end if
    else
       call self%wsCell%update(mol%xyz, self%rTrans)
    end if
References xtb_mctc_boundaryconditions::boundarycondition.