My Project: xtb_type_reader Module Reference
xtb_type_reader Module Reference
Wrapper to read from Fortran units.
Data Types
type treader
Wrapper for reading from Fortran units.
Functions/Subroutines
subroutine openunit (self, unit)
Connect reader to unit.
subroutine openfile (self, file)
Connect reader to unit.
subroutine readline (self, line, iostat)
Read from unit.
subroutine readinteger (self, val, iostat)
subroutine closeunit (self)
Close unit in reader.
Detailed Description
Wrapper to read from Fortran units.
Function/Subroutine Documentation
closeunit()
subroutine xtb_type_reader::closeunit (class(treader), intent(inout) self) private
Close unit in reader.
Parameters
[in,out] self Instance of reader
Definition at line 164 of file reader.F90.
    class(TReader), intent(inout) :: self
 #ifdef HAS_GCC_BUG_84412
    close(self%unit)
 #else
    logical :: opened
    inquire(opened=opened, unit=self%unit)
    if (opened) then
       close(self%unit)
    end if
 #endif
Referenced by xtb_type_reader::treader::close().
openfile()
subroutine xtb_type_reader::openfile (class(treader), intent(inout) self, character(len=*), intent(in) file) private
Connect reader to unit.
Parameters
[in,out] self Instance of reader
[in] file IO unit connect t
Definition at line 95 of file reader.F90.
    class(TReader), intent(inout) :: self
    character(len=*), intent(in) :: file
    logical :: exist
    inquire(exist=exist, file=file)
    if (exist) then
       open(file=file, newunit=self%unit, status='old')
    end if
Referenced by xtb_type_reader::treader::open().
openunit()
subroutine xtb_type_reader::openunit (class(treader), intent(inout) self, integer, intent(in) unit) private
Connect reader to unit.
Parameters
[in,out] self Instance of reader
[in] unit IO unit connect to
Definition at line 72 of file reader.F90.
    class(TReader), intent(inout) :: self
    integer, intent(in) :: unit
 #ifdef HAS_GCC_BUG_84412
    self%unit = unit
 #else
    logical :: opened
    inquire(opened=opened, unit=unit)
    if (opened) then
       self%unit = unit
    end if
 #endif
Referenced by xtb_type_reader::treader::open().
readinteger()
subroutine xtb_type_reader::readinteger (class(treader), intent(inout) self, integer, intent(out) val, integer, intent(out) iostat) private
Parameters
[in,out] self Instance of reader
[out] val Value of integer read
[out] iostat Status of read
Definition at line 147 of file reader.F90.
    class(TReader), intent(inout) :: self
    integer, intent(out) :: val
    integer, intent(out) :: iostat
    read(self%unit, *, iostat=iostat) val
Referenced by xtb_type_reader::treader::read().
readline()
subroutine xtb_type_reader::readline (class(treader), intent(inout) self, character(len=:), intent(out), allocatable line, integer, intent(out) iostat) private
Read from unit.
Parameters
[in,out] self Instance of reader
[out] line Character buffer to read into
[out] iostat Status of read
Definition at line 114 of file reader.F90.
    class(TReader), intent(inout) :: self
    character(len=:), allocatable, intent(out) :: line
    integer, intent(out) :: iostat
    integer, parameter :: bufferSize = 512
    character(len=bufferSize) :: buffer
    integer :: size
    line = ''
    do
       read(self%unit, '(a)', advance='no', iostat=iostat, size=size) buffer
       if (iostat > 0) then
          exit
       end if
       line = line // buffer(:size)
       if (iostat < 0) then
          if (is_iostat_eor(iostat)) then
             iostat = 0
          end if
          exit
       end if
    end do