My Project: xtb_solv_kernel Module Reference
xtb_solv_kernel Module Reference
Generalized Born interaction kernels.
Data Types
type tgbkernelenum
Possible kernels for the generalized Born model.
Functions/Subroutines
subroutine, public addgradientsaltstill (nat, ntpair, ppind, ddpair, qat, kappa, brad, brdr, ionscr, discr, energy, gradient)
subroutine, public addgradientstill (nat, ntpair, ppind, ddpair, qat, keps, brad, brdr, energy, gradient)
subroutine, public addgradientp16 (nat, ntpair, ppind, ddpair, qat, keps, brad, brdr, energy, gradient)
pure subroutine, public addbornderivsaltstill (nat, ntpair, ppind, ddpair, qat, kappa, brad, brdr, ionscr, discr, gborn, dAmatdr, Afac)
pure subroutine, public addbornderivstill (nat, ntpair, ppind, ddpair, qat, keps, brad, brdr, gborn, dAmatdr, Afac)
pure subroutine, public addbornmatsaltstill (nat, ntpair, ppind, ddpair, kappa, brad, ionscr, Amat)
pure subroutine, public addbornmatstill (nat, ntpair, ppind, ddpair, keps, brad, Amat)
subroutine, public addbornmatp16 (nat, ntpair, ppind, ddpair, keps, brad, Amat)
Variables
type(tgbkernelenum), parameter, public gbkernel = TGBKernelEnum()
Actual enumerator for the generalized Born kernels.
real(wp), parameter zetap16 = 1.028_wp
P16 zeta parameter.
real(wp), parameter zetap16o16 = zetaP16 / 16.0_wp
P16 zeta parameter over 16.
Detailed Description
Generalized Born interaction kernels.
Function/Subroutine Documentation
addbornderivsaltstill()
pure subroutine, public xtb_solv_kernel::addbornderivsaltstill (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) ddpair, real(wp), dimension(:), intent(in) qat, real(wp), intent(in) kappa, real(wp), dimension(:), intent(in) brad, real(wp), dimension(:, :, :), intent(in) brdr, real(wp), dimension(:), intent(in) ionscr, real(wp), dimension(:), intent(in) discr, real(wp), intent(out) gborn, real(wp), dimension(:, :, :), intent(inout) dAmatdr, real(wp), dimension(:, :), intent(inout) Afac)
Parameters
[in] nat Number of atoms
[in] ntpair Number of all interacting pairs
[in] ppind Index list
[in] ddpair Distances of all pairs
[in] qat Atomic partial charges
[in] kappa Debye screening length
[in] brad Born radii
[in] brdr Derivative of Born radii w.r.t. cartesian coordinates
[in] ionscr Ion screening
[in] discr Derivative of ion screening w.r.t. Born radii
Definition at line 379 of file kernel.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: ddpair(:, :)
    real(wp), intent(in) :: qat(:)
    real(wp), intent(in) :: kappa
    real(wp), intent(in) :: brad(:)
    real(wp), intent(in) :: brdr(:, :, :)
    real(wp), intent(in) :: ionscr(:)
    real(wp), intent(in) :: discr(:)
    real(wp), intent(inout) :: dAmatdr(:, :, :)
    real(wp), intent(inout) :: Afac(:, :)
    real(wp), intent(out)   :: gborn
    integer :: i,j,k,nnj
    integer :: kk
    real(wp), parameter :: a13=1._wp/3._wp
    real(wp), parameter :: a4=0.25_wp
    real(wp), parameter :: sqrt2pi = sqrt(2.0_wp/pi)
    real(wp) :: aa,r2,fgb,fgb2,br3
    real(wp) :: qq,dd,expd,dfgb,dfgb2,dfgb3,ap,bp,qfg
    real(wp) :: gg,expa,aii,egb
    real(wp) :: r0vdw,r01,r02,ar02
    real(wp) :: grddbi,grddbj
    real(wp) :: dr(3),r
    egb = 0._wp
    ! GB-SE energy and dAmatdr
    ! compute energy and fgb direct and radii derivatives
    do kk = 1, ntpair
       r = ddpair(1,kk)
       r2 = r*r
       i = ppind(1,kk)
       j = ppind(2,kk)
       qq = qat(i)*qat(j)
       aa = brad(i)*brad(j)
       dd = a4*r2/aa
       expd = exp(-dd)
       fgb2 = r2+aa*expd
       fgb = sqrt(fgb2)
       dfgb2 = 1._wp/fgb2
       dfgb = sqrt(dfgb2)
       aa = kappa*fgb
       expa = exp(-aa)
       gg = (ionscr(i)+ionscr(j))*expa
       egb = egb + qq*dfgb*(gg-1.0_wp)
       dfgb3 = (gg*(1._wp+aa)-1.0_wp)*dfgb*dfgb2
       ap = (1._wp-a4*expd)*dfgb3
       dr = ap*ddpair(2:4,kk)
       damatdr(:,i,j) = damatdr(:,i,j) - dr*qat(i)
       damatdr(:,j,i) = damatdr(:,j,i) + dr*qat(j)
       afac(:,i) = afac(:,i) - dr*qat(j)
       afac(:,j) = afac(:,j) + dr*qat(i)
       qfg = dfgb*expa
       bp = -0.5_wp*expd*(1._wp+dd)*dfgb3
       grddbi = (brad(j)*bp+qfg*discr(i))*qat(j)
       grddbj = (brad(i)*bp+qfg*discr(j))*qat(i)
       damatdr(:,:,i) = damatdr(:,:,i) + brdr(:,:,i)*grddbi
       damatdr(:,:,j) = damatdr(:,:,j) + brdr(:,:,j)*grddbj
    enddo
    ! self-energy part
    do i = 1, nat
       gg = exp(-kappa*brad(i))
       aa = 2._wp*ionscr(i)*gg-1.0_wp
       qq = qat(i)/brad(i)
       egb = egb + 0.5_wp*qq*qat(i)*aa
       ap = aa-brad(i)*2._wp*(discr(i)+ionscr(i)*kappa)*gg
       grddbi = -0.5_wp*qq*ap/brad(i)
       damatdr(:,:,i) = damatdr(:,:,i) + brdr(:,:,i)*grddbi
    enddo
    gborn = egb
References xtb_mctc_constants::pi.
Referenced by xtb_solv_gbsa::addbornderiv().
addbornderivstill()
pure subroutine, public xtb_solv_kernel::addbornderivstill (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) ddpair, real(wp), dimension(:), intent(in) qat, real(wp), intent(in) keps, real(wp), dimension(:), intent(in) brad, real(wp), dimension(:, :, :), intent(in) brdr, real(wp), intent(out) gborn, real(wp), dimension(:, :, :), intent(inout) dAmatdr, real(wp), dimension(:, :), intent(inout) Afac)
Parameters
[in] nat Number of atoms
[in] ntpair Number of all interacting pairs
[in] ppind Index list
[in] ddpair Distances of all pairs
[in] qat Atomic partial charges
[in] keps Dielectric screening
[in] brad Born radii
[in] brdr Derivative of Born radii w.r.t. cartesian coordinates
Definition at line 489 of file kernel.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: ddpair(:, :)
    real(wp), intent(in) :: qat(:)
    real(wp), intent(in) :: keps
    real(wp), intent(in) :: brad(:)
    real(wp), intent(in) :: brdr(:, :, :)
    real(wp), intent(inout) :: dAmatdr(:, :, :)
    real(wp), intent(inout) :: Afac(:, :)
    real(wp), intent(out)   :: gborn
    integer :: i,j,k,nnj
    integer :: kk
    real(wp), parameter :: a13=1._wp/3._wp
    real(wp), parameter :: a4=0.25_wp
    real(wp), parameter :: sqrt2pi = sqrt(2.0_wp/pi)
    real(wp) :: aa,r2,fgb,fgb2,br3
    real(wp) :: qq,dd,expd,dfgb,dfgb2,dfgb3,ap,bp,qfg
    real(wp) :: gg,expa,aii,egb
    real(wp) :: r0vdw,r01,r02,ar02
    real(wp) :: grddbi,grddbj
    real(wp) :: dr(3),r
    egb = 0._wp
    ! GB energy and gradient
    ! compute energy and fgb direct and radii derivatives
    do kk = 1, ntpair
       r = ddpair(1,kk)
       r2 = r*r
       i = ppind(1,kk)
       j = ppind(2,kk)
       ! dielectric scaling of the charges
       qq = qat(i)*qat(j)*keps
       aa = brad(i)*brad(j)
       dd = a4*r2/aa
       expd = exp(-dd)
       fgb2 = r2+aa*expd
       dfgb2 = 1._wp/fgb2
       dfgb = sqrt(dfgb2)
       dfgb3 = dfgb2*dfgb*keps
       egb = egb + qq*dfgb
       ap = (1._wp-a4*expd)*dfgb3
       dr = ap*ddpair(2:4,kk)
       damatdr(:,i,j) = damatdr(:,i,j) - dr*qat(i)
       damatdr(:,j,i) = damatdr(:,j,i) + dr*qat(j)
       afac(:,i) = afac(:,i) - dr*qat(j)
       afac(:,j) = afac(:,j) + dr*qat(i)
       bp = -0.5_wp*expd*(1._wp+dd)*dfgb3
       grddbi = brad(j)*bp
       grddbj = brad(i)*bp
       damatdr(:,:,j) = damatdr(:,:,j) + brdr(:,:,j)*grddbj*qat(i)
       damatdr(:,:,i) = damatdr(:,:,i) + brdr(:,:,i)*grddbi*qat(j)
    enddo
    ! self-energy part
    do i = 1, nat
       bp = 1._wp/brad(i)
       qq = qat(i)*bp
       egb = egb + 0.5_wp*qat(i)*qq*keps
       grddbi = -keps*bp*bp*0.5_wp
       damatdr(:,:,i) = damatdr(:,:,i) + brdr(:,:,i)*grddbi*qat(i)
    enddo
    gborn = egb
References xtb_mctc_constants::pi.
Referenced by xtb_solv_gbsa::addbornderiv().
addbornmatp16()
subroutine, public xtb_solv_kernel::addbornmatp16 (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) ddpair, real(wp), intent(in) keps, real(wp), dimension(:), intent(in) brad, real(wp), dimension(:, :), intent(inout) Amat)
Parameters
[in] nat Number of atoms
[in] ntpair Number of all interacting pairs
[in] ppind Index list
[in] ddpair Distances of all pairs
[in] keps Dielectric screening
[in] brad Born radii
[in,out] amat Interaction matrix
Definition at line 706 of file kernel.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: ddpair(:, :)
    real(wp), intent(in) :: keps
    real(wp), intent(in) :: brad(:)
    real(wp), intent(inout) :: Amat(:, :)
    integer :: kk
    integer :: iat, jat
    real(wp) :: r1, ab, arg, eab, fgb, dfgb, bp
    ! omp parallel do default(none) shared(Amat, ntpair, ppind, ddpair, brad, keps) &
    ! omp private(kk, iat, jat, r1, ab, arg, fgb, dfgb)
    do kk = 1, ntpair
       r1 = ddpair(1, kk)
       iat = ppind(1, kk)
       jat = ppind(2, kk)
       ab = sqrt(brad(iat) * brad(jat))
       arg = ab / (ab + zetap16o16*r1) ! ab / (1 + R/(16ab))
       arg = arg * arg ! ab / (1 + R/(16ab))
       arg = arg * arg ! ab / (1 + R/(16ab))
       arg = arg * arg ! ab / (1 + R/(16ab))
       arg = arg * arg ! ab / (1 + R/(16ab))
       fgb = r1 + ab*arg
       dfgb = 1.0_wp / fgb
       amat(iat, jat) = keps*dfgb + amat(iat, jat)
       amat(jat, iat) = keps*dfgb + amat(jat, iat)
    enddo
    ! self-energy part
    do iat = 1, nat
       bp = 1.0_wp/brad(iat)
       amat(iat, iat) = amat(iat, iat) + keps*bp
    enddo
References zetap16o16.
Referenced by xtb_solv_gbsa::addbornmatrix().
addbornmatsaltstill()
pure subroutine, public xtb_solv_kernel::addbornmatsaltstill (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) ddpair, real(wp), intent(in) kappa, real(wp), dimension(:), intent(in) brad, real(wp), dimension(:), intent(in) ionscr, real(wp), dimension(:, :), intent(inout) Amat)
Parameters
[in] nat Number of atoms
[in] ntpair Number of all interacting pairs
[in] ppind Index list
[in] ddpair Distances of all pairs
[in] kappa Debye screening length
[in] brad Born radii
[in] ionscr Ion screening
[in,out] amat Interaction matrix
Definition at line 586 of file kernel.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: ddpair(:, :)
    real(wp), intent(in) :: kappa
    real(wp), intent(in) :: brad(:)
    real(wp), intent(in) :: ionscr(:)
    real(wp), intent(inout) :: Amat(:, :)
    integer  :: i, j, nnj
    integer  :: kk
    real(wp), parameter :: a13=1.0_wp/3.0_wp
    real(wp), parameter :: a4=0.25_wp
    real(wp), parameter :: sqrt2pi = sqrt(2.0_wp/pi)
    real(wp) :: aa, r2, gg, arg, bp
    real(wp) :: dd, expd, fgb, fgb2, dfgb
    ! compute energy and Amat direct and radii derivatives
    do kk = 1, ntpair
       r2=ddpair(1, kk)
       r2=r2*r2
       i=ppind(1, kk)
       j=ppind(2, kk)
       aa=brad(i)*brad(j)
       dd=a4*r2/aa
       expd=exp(-dd)
       fgb2=r2+aa*expd
       fgb=sqrt(r2+aa*expd)
       dfgb=1._wp/fgb
       gg=ionscr(i)+ionscr(j)
       amat(i, j)=(exp(-kappa*fgb)*gg-1.0_wp)*dfgb + amat(i, j)
       amat(j, i)=(exp(-kappa*fgb)*gg-1.0_wp)*dfgb + amat(j, i)
    enddo
    ! self-energy part
    do i = 1, nat
       gg=ionscr(i)*2.0_wp
       amat(i, i)= amat(i, i) + (exp(-kappa*brad(i))*gg-1.0_wp)/brad(i)
    enddo
References xtb_mctc_constants::pi.
Referenced by xtb_solv_gbsa::addbornmatrix().
addbornmatstill()
pure subroutine, public xtb_solv_kernel::addbornmatstill (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) ddpair, real(wp), intent(in) keps, real(wp), dimension(:), intent(in) brad, real(wp), dimension(:, :), intent(inout) Amat)
Parameters
[in] nat Number of atoms
[in] ntpair Number of all interacting pairs
[in] ppind Index list
[in] ddpair Distances of all pairs
[in] keps Dielectric screening
[in] brad Born radii
[in,out] amat Interaction matrix
Definition at line 649 of file kernel.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: ddpair(:, :)
    real(wp), intent(in) :: keps
    real(wp), intent(in) :: brad(:)
    real(wp), intent(inout) :: Amat(:, :)
    integer  :: i, j, nnj
    integer  :: kk
    real(wp), parameter :: a13=1.0_wp/3.0_wp
    real(wp), parameter :: a4=0.25_wp
    real(wp), parameter :: sqrt2pi = sqrt(2.0_wp/pi)
    real(wp) :: aa, r2, gg, arg, bp
    real(wp) :: dd, expd, fgb, fgb2, dfgb
    ! compute energy and Amat direct and radii derivatives
    do kk = 1, ntpair
       r2 = ddpair(1, kk)
       r2 = r2*r2
       i = ppind(1, kk)
       j = ppind(2, kk)
       aa = brad(i)*brad(j)
       dd = a4*r2/aa
       expd = exp(-dd)
       fgb2 = r2+aa*expd
       dfgb = 1.0_wp/sqrt(fgb2)
       amat(i, j) = keps*dfgb + amat(i, j)
       amat(j, i) = keps*dfgb + amat(j, i)
    enddo
    ! self-energy part
    do i = 1, nat
       bp = 1._wp/brad(i)
       amat(i, i) = amat(i, i) + keps*bp
    enddo
References xtb_mctc_constants::pi.
Referenced by xtb_solv_gbsa::addbornmatrix().
addgradientp16()
subroutine, public xtb_solv_kernel::addgradientp16 (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) ddpair, real(wp), dimension(:), intent(in) qat, real(wp), intent(in) keps, real(wp), dimension(:), intent(in) brad, real(wp), dimension(:, :, :), intent(in) brdr, real(wp), intent(out) energy, real(wp), dimension(:, :), intent(inout) gradient)
Parameters
[in] nat Number of atoms
[in] ntpair Number of all interacting pairs
[in] ppind Index list
[in] ddpair Distances of all pairs
[in] qat Atomic partial charges
[in] keps Dielectric screening
[in] brad Born radii
[in] brdr Derivative of Born radii w.r.t. cartesian coordinates
[out] energy Total Born solvation energy
[in,out] gradient Deriatives of Born solvation energy
Definition at line 276 of file kernel.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: ddpair(:, :)
    real(wp), intent(in) :: qat(:)
    real(wp), intent(in) :: keps
    real(wp), intent(in) :: brad(:)
    real(wp), intent(in) :: brdr(:, :, :)
    real(wp), intent(out) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    integer :: iat, jat, kk
    real(wp) :: vec(3), r2, r1, ab, arg1, arg16, qq, fgb, fgb2, dfgb, dfgb2, egb
    real(wp) :: dEdbri, dEdbrj, dG(3), ap, bp, dS(3, 3)
    real(wp), allocatable :: dEdbr(:)
    allocate(dedbr(nat), source = 0.0_wp )
    egb = 0._wp
    dedbr(:) = 0._wp
    ! GB energy and gradient
    ! omp parallel do default(none) reduction(+:egb, gradient, dEdbr) &
    ! omp private(iat, jat, vec, r1, r2, ab, arg1, arg16, fgb, dfgb, dfgb2, ap, &
    ! omp& bp, qq, dEdbri, dEdbrj, dG, dS) &
    ! omp shared(keps, qat, ntpair, ddpair, ppind, brad)
    do kk = 1, ntpair
       vec(:) = ddpair(2:4, kk)
       r1 = ddpair(1, kk)
       r2 = r1*r1
       iat = ppind(1, kk)
       jat = ppind(2, kk)
       qq = qat(iat)*qat(jat)
       ab = sqrt(brad(iat) * brad(jat))
       arg1 = ab / (ab + zetap16o16*r1) ! 1 / (1 + R/(16ab))
       arg16 = arg1 * arg1 ! 1 / (1 + R/(16ab))
       arg16 = arg16 * arg16 ! 1 / (1 + R/(16ab))
       arg16 = arg16 * arg16 ! 1 / (1 + R/(16ab))
       arg16 = arg16 * arg16 ! 1 / (1 + R/(16ab))
       fgb = r1 + ab*arg16
       dfgb = 1.0_wp / fgb
       dfgb2 = dfgb * dfgb
       egb = egb + qq*keps*dfgb
       ! (1 - /(1 + R/(16 ab))^17)/(R + ab/(1 + R/(16 ab)))
       ap = (1.0_wp - zetap16 * arg1 * arg16) * dfgb2
       dg(:) = ap * vec * keps / r1 * qq
       gradient(:, iat) = gradient(:, iat) - dg
       gradient(:, jat) = gradient(:, jat) + dg
       ! -(R/(2ab(1 + R/(16ab))) + 1/(2ab(1 + R/(16ab))))/(R + ab/(1 + R/(16ab)))
       bp = -0.5_wp*(r1 * zetap16 / ab * arg1 + 1.0_wp) / ab * arg16 * dfgb2
       dedbri = brad(jat) * bp * keps * qq
       dedbrj = brad(iat) * bp * keps * qq
       dedbr(iat) = dedbr(iat) + dedbri
       dedbr(jat) = dedbr(jat) + dedbrj
    end do
    ! self-energy part
    do iat = 1, nat
       bp = 1._wp/brad(iat)
       qq = qat(iat)*bp
       egb = egb + 0.5_wp*qat(iat)*qq*keps
       dedbri = -0.5_wp*keps*qq*bp
       dedbr(iat) = dedbr(iat) + dedbri*qat(iat)
       !gradient = gradient + brdr(:, :, i) * dEdbri*qat(i)
    enddo
    ! contract with the Born radii derivatives
    call mctc_gemv(brdr, dedbr, gradient, beta=1.0_wp)
    energy = egb
References zetap16, and zetap16o16.
Referenced by xtb_solv_gbsa::addgradient().
addgradientsaltstill()
subroutine, public xtb_solv_kernel::addgradientsaltstill (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) ddpair, real(wp), dimension(:), intent(in) qat, real(wp), intent(in) kappa, real(wp), dimension(:), intent(in) brad, real(wp), dimension(:, :, :), intent(in) brdr, real(wp), dimension(:), intent(in) ionscr, real(wp), dimension(:), intent(in) discr, real(wp), intent(out) energy, real(wp), dimension(:, :), intent(inout) gradient)
Parameters
[in] nat Number of atoms
[in] ntpair Number of all interacting pairs
[in] ppind Index list
[in] ddpair Distances of all pairs
[in] qat Atomic partial charges
[in] kappa Debye screening length
[in] brad Born radii
[in] brdr Derivative of Born radii w.r.t. cartesian coordinates
[in] ionscr Ion screening
[in] discr Derivative of ion screening w.r.t. Born radii
[out] energy Total Born solvation energy
[in,out] gradient Deriatives of Born solvation energy
Definition at line 57 of file kernel.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: ddpair(:, :)
    real(wp), intent(in) :: qat(:)
    real(wp), intent(in) :: kappa
    real(wp), intent(in) :: brad(:)
    real(wp), intent(in) :: brdr(:, :, :)
    real(wp), intent(in) :: ionscr(:)
    real(wp), intent(in) :: discr(:)
    real(wp), intent(out) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    integer :: i, j, k, nnj
    integer :: kk
    real(wp), parameter :: a13=1._wp/3._wp
    real(wp), parameter :: a4=0.25_wp
    real(wp) :: aa, r2, fgb, fgb2, br3
    real(wp) :: qq, dd, expd, dfgb, dfgb2, dfgb3, egb, ap, bp, qfg
    real(wp) :: gg, expa
    real(wp) :: r0vdw, r01, r02, ar02
    real(wp) :: grddbi, grddbj
    real(wp) :: dr(3), r
    real(wp), allocatable :: grddb(:)
    allocate(grddb(nat), source = 0.0_wp )
    egb = 0._wp
    grddb(:) = 0._wp
    ! GB-SE energy and gradient
    ! compute energy and fgb direct and radii derivatives
    do kk = 1, ntpair
       r = ddpair(1, kk)
       r2 = r*r
       i = ppind(1, kk)
       j = ppind(2, kk)
       qq = qat(i)*qat(j)
       aa = brad(i)*brad(j)
       dd = a4*r2/aa
       expd = exp(-dd)
       dfgb = r2+aa*expd
       fgb = sqrt(dfgb)
       aa = kappa*fgb
       expa = exp(-aa)
       gg = (ionscr(i)+ionscr(j))*expa
       qfg = qq/fgb
       egb = egb + qfg*(gg-1.0_wp)
       dfgb3 = qfg*(gg*(1._wp+aa)-1.0_wp)/dfgb
       ap = (1._wp-a4*expd)*dfgb3
       dr = ap*ddpair(2:4, kk)
       gradient(:, i) = gradient(:, i) - dr
       gradient(:, j) = gradient(:, j) + dr
       qfg = qfg*expa
       bp = -0.5_wp*expd*(1._wp+dd)*dfgb3
       grddbi = (brad(j)*bp+qfg*discr(i))
       grddbj = (brad(i)*bp+qfg*discr(j))
       grddb(i) = grddb(i) + grddbi
       grddb(j) = grddb(j) + grddbj
    enddo
    ! self-energy part
    do i = 1, nat
       gg = exp(-kappa*brad(i))
       aa = 2._wp*ionscr(i)*gg-1.0_wp
       qq = qat(i)/brad(i)
       egb = egb + 0.5_wp*qq*qat(i)*aa
       ap = aa-brad(i)*2._wp*(discr(i)+ionscr(i)*kappa)*gg
       grddbi = -0.5_wp*qq*qq*ap
       grddb(i) = grddb(i) + grddbi
    enddo
    ! contract with the Born radii derivatives
    call mctc_gemv(brdr, grddb, gradient, beta=1.0_wp)
    energy = egb
Referenced by xtb_solv_gbsa::addgradient().
addgradientstill()
subroutine, public xtb_solv_kernel::addgradientstill (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) ddpair, real(wp), dimension(:), intent(in) qat, real(wp), intent(in) keps, real(wp), dimension(:), intent(in) brad, real(wp), dimension(:, :, :), intent(in) brdr, real(wp), intent(out) energy, real(wp), dimension(:, :), intent(inout) gradient)
Parameters
[in] nat Number of atoms
[in] ntpair Number of all interacting pairs
[in] ppind Index list
[in] ddpair Distances of all pairs
[in] qat Atomic partial charges
[in] keps Dielectric screening
[in] brad Born radii
[in] brdr Derivative of Born radii w.r.t. cartesian coordinates
[out] energy Total Born solvation energy
[in,out] gradient Deriatives of Born solvation energy
Definition at line 171 of file kernel.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: ddpair(:, :)
    real(wp), intent(in) :: qat(:)
    real(wp), intent(in) :: keps
    real(wp), intent(in) :: brad(:)
    real(wp), intent(in) :: brdr(:, :, :)
    real(wp), intent(out) :: energy
    real(wp), intent(inout) :: gradient(:, :)
    integer :: i, j, k, nnj
    integer :: kk
    real(wp), parameter :: a13=1._wp/3._wp
    real(wp), parameter :: a4=0.25_wp
    real(wp) :: aa, r2, fgb, fgb2, br3
    real(wp) :: qq, dd, expd, dfgb, dfgb2, dfgb3, egb, ap, bp, qfg
    real(wp) :: gg, expa
    real(wp) :: r0vdw, r01, r02, ar02
    real(wp) :: grddbi, grddbj
    real(wp) :: dr(3), r
    real(wp), allocatable :: grddb(:)
    allocate(grddb(nat), source = 0.0_wp )
    egb = 0._wp
    grddb(:) = 0._wp
    ! GB energy and gradient
    ! compute energy and fgb direct and radii derivatives
    do kk = 1, ntpair
       r = ddpair(1, kk)
       r2 = r*r
       i = ppind(1, kk)
       j = ppind(2, kk)
       ! dielectric scaling of the charges
       qq = qat(i)*qat(j)
       aa = brad(i)*brad(j)
       dd = a4*r2/aa
       expd = exp(-dd)
       fgb2 = r2+aa*expd
       dfgb2 = 1._wp/fgb2
       dfgb = sqrt(dfgb2)
       dfgb3 = dfgb2*dfgb*keps
       egb = egb + qq*keps*dfgb
       ap = (1._wp-a4*expd)*dfgb3
       dr = ap*ddpair(2:4, kk)
       gradient(:, i) = gradient(:, i) - dr*qq
       gradient(:, j) = gradient(:, j) + dr*qq
       bp = -0.5_wp*expd*(1._wp+dd)*dfgb3
       grddbi = brad(j)*bp
       grddbj = brad(i)*bp
       grddb(i) = grddb(i) + grddbi*qq
       !gradient = gradient + brdr(:, :, i) * grddbi*qq
       grddb(j) = grddb(j) + grddbj*qq
       !gradient = gradient + brdr(:, :, j) * grddbj*qq
    enddo
    ! self-energy part
    do i = 1, nat
       bp = 1._wp/brad(i)
       qq = qat(i)*bp
       egb = egb + 0.5_wp*qat(i)*qq*keps
       grddbi = -0.5_wp*keps*qq*bp
       grddb(i) = grddb(i) + grddbi*qat(i)
       !gradient = gradient + brdr(:, :, i) * grddbi*qat(i)
    enddo
    ! contract with the Born radii derivatives
    call mctc_gemv(brdr, grddb, gradient, beta=1.0_wp)
    energy = egb
Referenced by xtb_solv_gbsa::addgradient().
Variable Documentation
gbkernel
type(tgbkernelenum), parameter, public xtb_solv_kernel::gbkernel = TGBKernelEnum()
Actual enumerator for the generalized Born kernels.
Definition at line 44 of file kernel.f90.
    type(TGBKernelEnum), parameter :: gbKernel = tgbkernelenum()
Referenced by xtb_solv_gbsa::addbornderiv(), xtb_solv_gbsa::addbornmatrix(), xtb_solv_gbsa::addgradient(), xtb_solv_model::info(), xtb_solv_model::loadinternalparam(), xtb_api_calculator::setsolvent_api(), test_eeq_model_gbsa(), test_eeq_model_salt(), test_gfn0_mindless_solvation(), test_gfn1_mindless_solvation(), test_gfn1gbsa_api(), test_gfn2_dmetal(), test_gfn2_mindless_solvation(), test_gfn2gbsa_api(), test_gfn2salt_api(), test_gfnff_mindless_solvation(), test_gfnff_pdb(), test_gfnff_scaleup(), test_gfnff_sdf(), and test_ipea_indole().
zetap16
real(wp), parameter xtb_solv_kernel::zetap16 = 1.028_wp private
P16 zeta parameter.
Definition at line 48 of file kernel.f90.
    real(wp), parameter :: zetaP16 = 1.028_wp
Referenced by addgradientp16().
zetap16o16
real(wp), parameter xtb_solv_kernel::zetap16o16 = zetaP16 / 16.0_wp private
P16 zeta parameter over 16.
Definition at line 51 of file kernel.f90.
    real(wp), parameter :: zetaP16o16 = zetap16 / 16.0_wp
Referenced by addbornmatp16(), and addgradientp16().