My Project: xtb_eeq Module Reference
xtb_eeq Module Reference
Data Types
interface eeq_chrgeq
interface get_coulomb_matrix
interface get_coulomb_derivs
Functions/Subroutines
subroutine get_coulomb_matrix_0d (mol, chrgeq, amat)
subroutine get_coulomb_matrix_3d (mol, chrgeq, rTrans, gTrans, cf, amat)
subroutine get_coulomb_derivs_0d (mol, chrgeq, qvec, amatdr, atrace)
subroutine get_coulomb_derivs_3d (mol, chrgeq, qvec, rTrans, gTrans, cf, amatdr, amatdL, atrace)
pure real(wp) function eeq_ewald_3d_dir (riw, rTrans, gamij, cf, scale)
pure subroutine eeq_ewald_dx_3d_dir (riw, rTrans, gamij, cf, scale, dAmat, sigma)
subroutine, public goedecker_chrgeq (n, at, xyz, chrg, cn, dcndr, q, dqdr, energy, gradient, lverbose, lgrad, lcpq)
subroutine eeq_chrgeq_qonly (mol, env, chrgeq, cn, q, lverbose)
subroutine eeq_chrgeq_core (mol, env, chrgeq, cn, dcndr, dcndL, q, dqdr, dqdL, energy, gradient, sigma, lverbose, lgrad, lcpq)
subroutine eeq_chrgeq_gbsa (mol, env, chrgeq, gbsa, cn, dcndr, q, dqdr, energy, gsolv, gradient, lverbose, lgrad, lcpq)
Variables
real(wp), parameter sqrt2pi = sqrt(2.0_wp/pi)
Function/Subroutine Documentation
eeq_chrgeq_core()
subroutine xtb_eeq::eeq_chrgeq_core (type(tmolecule), intent(in) mol, type(tenvironment), intent(inout) env, type(chrg_parameter), intent(in) chrgeq, real(wp), dimension(mol%n), intent(in) cn, real(wp), dimension(3,mol%n,mol%n), intent(in) dcndr, real(wp), dimension(3,3,mol%n), intent(in) dcndL, real(wp), dimension(mol%n), intent(out) q, real(wp), dimension(3,mol%n,mol%n), intent(out) dqdr, real(wp), dimension(3,3,mol%n), intent(out) dqdL, real(wp), intent(inout) energy, real(wp), dimension(3,mol%n), intent(inout) gradient, real(wp), dimension(3,3), intent(inout) sigma, logical, intent(in) lverbose, logical, intent(in) lgrad, logical, intent(in) lcpq)
Parameters
[in] mol molecular structure information
Definition at line 675 of file eeq_model.f90.
    use xtb_mctc_convert
    use xtb_type_molecule
    use xtb_type_param
    use xtb_disp_ncoord
    use xtb_pbc_tools
    implicit none
    character(len=*), parameter :: source = 'eeq_chrgeq'
 ! ------------------------------------------------------------------------
 !  Input
 ! ------------------------------------------------------------------------
    type(TMolecule),intent(in) :: mol
    real(wp),intent(in)    :: cn(mol%n)     ! erf-CN
    real(wp),intent(in)    :: dcndr(3,mol%n,mol%n) ! derivative of erf-CN
    real(wp),intent(in)    :: dcndL(3,3,mol%n) ! derivative of erf-CN
    logical, intent(in)    :: lverbose      ! toggles printout
    logical, intent(in)    :: lgrad         ! flag for gradient calculation
    logical, intent(in)    :: lcpq          ! do partial charge derivative
    type(chrg_parameter),intent(in) :: chrgeq
    type(TEnvironment), intent(inout) :: env
 ! ------------------------------------------------------------------------
 !  Output
 ! ------------------------------------------------------------------------
    real(wp),intent(out)   :: q(mol%n)          ! partial charges
    real(wp),intent(out)   :: dqdr(3,mol%n,mol%n) ! derivative of partial charges
    real(wp),intent(out)   :: dqdL(3,3,mol%n) ! derivative of partial charges
    real(wp),intent(inout) :: energy        ! electrostatic energy
    real(wp),intent(inout) :: gradient(3,mol%n) ! molecular gradient of IES
    real(wp),intent(inout) :: sigma(3,3) ! molecular gradient of IES
 !
 ! ------------------------------------------------------------------------
 !  charge model
 ! ------------------------------------------------------------------------
    integer  :: m ! dimension of the Lagrangian
    real(wp),allocatable :: Amat(:,:)
    real(wp),allocatable :: Xvec(:)
    real(wp),allocatable :: Ainv(:,:)
    real(wp),allocatable :: dAmatdr(:,:,:)
    real(wp),allocatable :: dAmatdL(:,:,:)
    real(wp),allocatable :: dXvecdr(:,:,:)
    real(wp),allocatable :: dXvecdL(:,:,:)
 ! ------------------------------------------------------------------------
 !  local variables
 ! ------------------------------------------------------------------------
    integer  :: i,j,k,l
    real(wp) :: r,rij(3),r2
    real(wp) :: gamij,gamij2
    real(wp) :: arg,tmp,dtmp
    real(wp) :: lambda
    real(wp) :: es
 ! ------------------------------------------------------------------------
 !  for periodic case
 ! ------------------------------------------------------------------------
    integer  :: wscAt
    real(wp) :: gamii,riw(3),dAtmp(3),stmp(3,3),vec(3)
    real(wp) :: cf ! convergence factor
    integer, parameter :: ewaldCutD(3) = 2
    integer, parameter :: ewaldCutR(3) = 2
    real(wp), allocatable :: gTrans(:, :)
    real(wp), allocatable :: rTrans(:, :)
    integer :: iG1, iG2, iG3, iT1, iT2, iT3, iRp
 ! ------------------------------------------------------------------------
 !  scratch variables
 ! ------------------------------------------------------------------------
    real(wp),allocatable :: xtmp(:)
    real(wp),allocatable :: atmp(:,:)
    real(wp),allocatable :: Xfac(:)
    real(wp),allocatable :: Afac(:,:)
 ! ------------------------------------------------------------------------
 !  Lapack work variables
 ! ------------------------------------------------------------------------
    integer, allocatable :: ipiv(:)
    real(wp),allocatable :: temp(:)
    real(wp),allocatable :: work(:)
    integer  :: lwork
    integer  :: info
    real(wp) :: test(1)
 ! ------------------------------------------------------------------------
 !  initizialization
 ! ------------------------------------------------------------------------
    m    = mol%n+1
    q    = 0.0_wp
    allocate( ipiv(m), source = 0 )
    allocate( amat(m,m), xvec(m), xfac(m), source = 0.0_wp )
 ! ------------------------------------------------------------------------
 !  set up the A matrix and X vector
 ! ------------------------------------------------------------------------
 !  αi -> alpha(i), ENi -> xi(i), κi -> kappa(i), Jii -> gam(i)
 !  γij = 1/√(αi+αj)
 !  Xi  = -ENi + κi·√CNi
 !  Aii = Jii + 2/√π·γii
 !  Aij = erf(γij·Rij)/Rij = 2/√π·F0(γ²ij·R²ij)
 ! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "Setup of the A matrix and the RHS X vector"
    ! prepare some arrays
    !$omp parallel do default(none) schedule(runtime) &
    !$omp shared(mol,cn,chrgeq) private(i,tmp) shared(Xvec,Xfac)
    do i = 1, mol%n
       tmp = chrgeq%kappa(i)/(sqrt(cn(i))+1e-14_wp)
       xvec(i) = -chrgeq%en(i) + tmp*cn(i)
       xfac(i) = 0.5_wp*tmp
    enddo
    !$omp end parallel do
    if (mol%npbc > 0) then
       irp = 0
       allocate(gtrans(3, product(2*ewaldcutr+1)-1))
       do ig1 = -ewaldcutr(1), ewaldcutr(1)
          do ig2 = -ewaldcutr(2), ewaldcutr(2)
             do ig3 = -ewaldcutr(3), ewaldcutr(3)
                if (ig1 == 0 .and. ig2 == 0 .and. ig3 == 0) cycle
                irp = irp + 1
                vec(:) = [ig1, ig2, ig3]
                gtrans(:, irp) = matmul(mol%rec_lat, vec)
             end do
          end do
       end do
       irp = 0
       allocate(rtrans(3, product(2*ewaldcutd+1)))
       do it1 = -ewaldcutd(1), ewaldcutd(1)
          do it2 = -ewaldcutd(2), ewaldcutd(2)
             do it3 = -ewaldcutd(3), ewaldcutd(3)
                irp = irp + 1
                vec(:) = [it1, it2, it3]
                rtrans(:, irp) = matmul(mol%lattice, vec)
             end do
          end do
       end do
       cf = sqrtpi/mol%volume**(1.0_wp/3.0_wp)
       ! build Ewald matrix
       call get_coulomb_matrix(mol, chrgeq, rtrans, gtrans, cf, amat)
    else
       call get_coulomb_matrix(mol, chrgeq, amat)
    endif
 ! ------------------------------------------------------------------------
 !  solve the linear equations to obtain partial charges
 ! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "Solve the linear equations to obtain partial charges"
    amat(m,1:m) = 1.0_wp
    amat(1:m,m) = 1.0_wp
    amat(m,m  ) = 0.0_wp
    xvec(m)     = mol%chrg
    ! generate temporary copy
    allocate( atmp(m,m), source = amat )
    allocate( xtmp(m),   source = xvec )
    ! assume work space query, set best value to test after first dsysv call
    call dsysv('u', m, 1, atmp, m, ipiv, xtmp, m, test, -1, info)
    lwork = int(test(1))
    allocate( work(lwork), source = 0.0_wp )
    call dsysv('u',m,1,atmp,m,ipiv,xtmp,m,work,lwork,info)
    if(info > 0) then
       call env%error("Coulomb matrix is singular, cannot solve lin. eq.", source)
       return
    end if
    q = xtmp(:mol%n)
    if(abs(sum(q)-mol%chrg) > 1.e-6_wp) then
       call env%error("Charge constraint is not satisfied", source)
       return
    end if
    !print'(3f20.14)',Xtmp
    lambda = xtmp(m)
    if (lverbose) then
       write(istdout,'(72("-"))')
       write(istdout,'(1x,a,1x,f20.14)') &
          "lambda       :",lambda,&
          "total charge :",sum(q)
    endif
 ! ------------------------------------------------------------------------
 !  calculate isotropic electrostatic (IES) energy
 ! ------------------------------------------------------------------------
 !  E = ∑i (ENi - κi·√CNi)·qi + ∑i (Jii + 2/√π·γii)·q²i
 !      + ½ ∑i ∑j,j≠i qi·qj·2/√π·F0(γ²ij·R²ij)
 !    = q·(½A·q - X)
 ! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "Isotropic electrostatic (IES) energy calculation"
    call mctc_copy(xvec, work)
    call mctc_symv(amat, xtmp, work, alpha=0.5_wp, beta=-1.0_wp)
    es = mctc_dot(xtmp, work)
    energy = es + energy
    if (lverbose) then
       write(istdout,'(72("-"))')
       write(istdout,'(1x,a,1x,f20.14)') &
          "energy",es
    endif
 ! ------------------------------------------------------------------------
 !  calculate molecular gradient of the IES energy
 ! ------------------------------------------------------------------------
 !  dE/dRj -> g(:,j), ∂Xi/∂Rj -> -dcn(:,i,j), ½∂Aij/∂Rj -> dAmat(:,j,i)
 !  dE/dR = (½∂A/∂R·q - ∂X/∂R)·q
 !  ∂Aij/∂Rj = ∂Aij/∂Ri
 ! ------------------------------------------------------------------------
 do_molecular_gradient: if (lgrad .or. lcpq) then
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "molecular gradient calculation"
    allocate( damatdr(3,mol%n,m), dxvecdr(3,mol%n,m), afac(3,mol%n), source = 0.0_wp )
    if (mol%npbc > 0) then
       allocate( damatdl(3,3,m), dxvecdl(3,3,m), source = 0.0_wp )
       call get_coulomb_derivs(mol, chrgeq, xtmp, rtrans, gtrans, cf, &
          & damatdr, damatdl, afac)
       do i = 1, mol%n
          dxvecdr(:,:,i) = -dcndr(:,:,i)*xfac(i)
          dxvecdl(:,:,i) = -dcndl(:,:,i)*xfac(i)
       enddo
    else
       call get_coulomb_derivs(mol, chrgeq, xtmp, damatdr, afac)
       do i = 1, mol%n
          dxvecdr(:,:,i) = -dcndr(:,:,i)*xfac(i) ! merge dX and dA for speedup
       enddo
    endif
 endif do_molecular_gradient
    if (lgrad) then
    call mctc_gemv(damatdr, xtmp, gradient, alpha=+1.0_wp, beta=1.0_wp)
    call mctc_gemv(dxvecdr, xtmp, gradient, alpha=+1.0_wp, beta=1.0_wp)
    if (mol%npbc > 0) then
       call mctc_gemv(damatdl, xtmp, sigma, alpha=+0.5_wp, beta=1.0_wp)
       call mctc_gemv(dxvecdl, xtmp, sigma, alpha=+1.0_wp, beta=1.0_wp)
    endif
    endif
 ! ------------------------------------------------------------------------
 !  invert the A matrix using a Bunch-Kaufman factorization
 !  A⁻¹ = (L·D·L^T)⁻¹ = L^T·D⁻¹·L
 ! ------------------------------------------------------------------------
 do_partial_charge_derivative: if (lcpq) then
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "A matrix inversion by Bunch-Kaufman factorization"
    allocate( ainv(m,m), source = amat )
    ! assume work space query, set best value to test after first dsytrf call
    call lapack_sytrf('L',m,ainv,m,ipiv,test,-1,info)
    if (int(test(1)) > lwork) then
       deallocate(work)
       lwork=int(test(1))
       allocate( work(lwork), source = 0.0_wp )
    endif
    ! Bunch-Kaufman factorization A = L*D*L**T
    call lapack_sytrf('L',m,ainv,m,ipiv,work,lwork,info)
    if(info > 0)then
       call env%error("Could not factorize Coulomb matrix", source)
       return
    endif
    ! A⁻¹ from factorized L matrix, save lower part of A⁻¹ in Ainv matrix
    ! Ainv matrix is overwritten with lower triangular part of A⁻¹
    call lapack_sytri('L',m,ainv,m,ipiv,work,info)
    if (info > 0) then
       call env%error("Coulomb Matrix is singular, cannot invert", source)
       return
    endif
    ! symmetrizes A⁻¹ matrix from lower triangular part of inverse matrix
    do i = 1, m
       do j = i+1, m
          ainv(i,j)=ainv(j,i)
       enddo
    enddo
 ! ------------------------------------------------------------------------
 !  calculate gradient of the partial charge w.r.t. the nuclear coordinates
 ! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "calculating the derivative of the partial charges"
    dqdr = 0.0_wp
    if (mol%npbc > 0) then
       dqdl = 0.0_wp
    endif
    do i = 1, mol%n
       damatdr(:,i,i) = afac(:,i) + damatdr(:,i,i)
    enddo
    !call dsymm('r','l',3*n,m,-1.0_wp,Ainv,m,dAmatdr,3*n,1.0_wp,dqdr,3*n)
    call mctc_gemm(damatdr, ainv, dqdr, alpha=-1.0_wp, beta=1.0_wp)
    call mctc_gemm(dxvecdr, ainv, dqdr, alpha=-1.0_wp, beta=1.0_wp)
    if (mol%npbc > 0) then
       call mctc_gemm(damatdl, ainv, dqdl, alpha=-1.0_wp, beta=1.0_wp)
       call mctc_gemm(dxvecdl, ainv, dqdl, alpha=-1.0_wp, beta=1.0_wp)
    endif
    !print'(/,"analytical gradient")'
    !print'(3f20.14)',dqdr(:,:,:n)
 endif do_partial_charge_derivative
 ! ------------------------------------------------------------------------
 !  Clean up
 ! ------------------------------------------------------------------------
    if (allocated(amat))  deallocate(amat)
    if (allocated(damatdr)) deallocate(damatdr)
    if (allocated(afac))  deallocate(afac)
    if (allocated(xvec))  deallocate(xvec)
    if (allocated(xfac))  deallocate(xfac)
    if (allocated(xtmp))  deallocate(xtmp)
    if (allocated(atmp))  deallocate(atmp)
    if (allocated(temp))  deallocate(temp)
    if (allocated(work))  deallocate(work)
    if (allocated(ipiv))  deallocate(ipiv)
Referenced by xtb_eeq::eeq_chrgeq::eeq_chrgeq_qonly().
eeq_chrgeq_gbsa()
subroutine xtb_eeq::eeq_chrgeq_gbsa (type(tmolecule), intent(in) mol, type(tenvironment), intent(inout) env, type(chrg_parameter), intent(in) chrgeq, type(tborn), intent(in) gbsa, real(wp), dimension(mol%n), intent(in) cn, real(wp), dimension(3,mol%n,mol%n), intent(in) dcndr, real(wp), dimension(mol%n), intent(out) q, real(wp), dimension(3,mol%n,mol%n), intent(out) dqdr, real(wp), intent(inout) energy, real(wp), intent(inout) gsolv, real(wp), dimension(3,mol%n), intent(inout) gradient, logical, intent(in) lverbose, logical, intent(in) lgrad, logical, intent(in) lcpq)
Parameters
[in] mol molecular structure information
Definition at line 1007 of file eeq_model.f90.
    use xtb_mctc_convert
    use xtb_type_molecule
    use xtb_type_param
    use xtb_disp_ncoord
    use xtb_solv_gbsa, only : tborn
    use xtb_pbc_tools
    implicit none
    character(len=*), parameter :: source = "eeq_chrgeq_gbsa"
 ! ------------------------------------------------------------------------
 !  Input
 ! ------------------------------------------------------------------------
    type(TMolecule),intent(in) :: mol
    type(TBorn), intent(in) :: gbsa
    real(wp),intent(in)    :: cn(mol%n)     ! erf-CN
    real(wp),intent(in)    :: dcndr(3,mol%n,mol%n) ! derivative of erf-CN
    logical, intent(in)    :: lverbose      ! toggles printout
    logical, intent(in)    :: lgrad         ! flag for gradient calculation
    logical, intent(in)    :: lcpq          ! do partial charge derivative
    type(chrg_parameter),intent(in) :: chrgeq
    type(TEnvironment), intent(inout) :: env
 ! ------------------------------------------------------------------------
 !  Output
 ! ------------------------------------------------------------------------
    real(wp),intent(out)   :: q(mol%n)          ! partial charges
    real(wp),intent(out)   :: dqdr(3,mol%n,mol%n) ! derivative of partial charges
    real(wp),intent(inout) :: gsolv        ! electrostatic energy
    real(wp),intent(inout) :: energy        ! electrostatic energy
    real(wp),intent(inout) :: gradient(3,mol%n) ! molecular gradient of IES
 !
 ! ------------------------------------------------------------------------
 !  charge model
 ! ------------------------------------------------------------------------
    integer  :: m ! dimension of the Lagrangian
    real(wp),allocatable :: Amat(:,:)
    real(wp),allocatable :: Xvec(:)
    real(wp),allocatable :: Ainv(:,:)
    real(wp),allocatable :: dAmatdr(:,:,:)
    real(wp),allocatable :: dAmatdL(:,:,:)
    real(wp),allocatable :: dXvecdr(:,:,:)
    real(wp),allocatable :: dXvecdL(:,:,:)
 ! ------------------------------------------------------------------------
 !  local variables
 ! ------------------------------------------------------------------------
    integer  :: i,j,k,l
    real(wp) :: r,rij(3),r2
    real(wp) :: gamij,gamij2
    real(wp) :: arg,tmp,dtmp
    real(wp) :: lambda
    real(wp) :: es
 ! ------------------------------------------------------------------------
 !  for periodic case
 ! ------------------------------------------------------------------------
    integer  :: wscAt
    real(wp) :: gamii,riw(3),dAtmp(3),stmp(3,3)
    real(wp) :: cf ! convergence factor
    real(wp),parameter   :: zero(3) = [0.0_wp,0.0_wp,0.0_wp]
    integer              :: rep_cn(3)
    integer, parameter   :: ewaldCutD(3) = [2,2,2]
    integer, parameter   :: ewaldCutR(3) = [2,2,2]
 ! ------------------------------------------------------------------------
 !  scratch variables
 ! ------------------------------------------------------------------------
    real(wp),allocatable :: xtmp(:)
    real(wp),allocatable :: atmp(:,:)
    real(wp),allocatable :: Xfac(:)
    real(wp),allocatable :: Afac(:,:)
 ! ------------------------------------------------------------------------
 !  Lapack work variables
 ! ------------------------------------------------------------------------
    integer, allocatable :: ipiv(:)
    real(wp),allocatable :: temp(:)
    real(wp),allocatable :: work(:)
    integer  :: lwork
    integer  :: info
    real(wp) :: test(1)
    real(wp) :: gborn, ghb, r3, erft
    ! quick return if possible
    if (mol%n.eq.1) then
       q = mol%chrg
       ! should always hold, even for extendend systems
       es = 0.0_wp
       return
    endif
    gborn = 0.0_wp
    ghb   = 0.0_wp
 ! ------------------------------------------------------------------------
 !  initizialization
 ! ------------------------------------------------------------------------
    m    = mol%n+1
    q    = 0.0_wp
    allocate( ipiv(m), source = 0 )
    allocate( amat(m,m), xvec(m), xfac(m), source = 0.0_wp )
 ! ------------------------------------------------------------------------
 !  set up the A matrix and X vector
 ! ------------------------------------------------------------------------
 !  αi -> alpha(i), ENi -> xi(i), κi -> kappa(i), Jii -> gam(i)
 !  γij = 1/√(αi+αj)
 !  Xi  = -ENi + κi·√CNi
 !  Aii = Jii + 2/√π·γii
 !  Aij = erf(γij·Rij)/Rij = 2/√π·F0(γ²ij·R²ij)
 ! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "Setup of the A matrix and the RHS X vector"
    ! prepare some arrays
    !$omp parallel do default(none) schedule(runtime) &
    !$omp shared(mol,cn,chrgeq) private(i,tmp) shared(Xvec,Xfac)
    do i = 1, mol%n
       tmp = chrgeq%kappa(i)/(sqrt(cn(i))+1e-14_wp)
       xvec(i) = -chrgeq%en(i) + tmp*cn(i)
       xfac(i) = 0.5_wp*tmp
    enddo
    !$omp end parallel do
    call get_coulomb_matrix(mol, chrgeq, amat)
    amat(:mol%n, :mol%n) = amat(:mol%n, :mol%n) + gbsa%bornMat
 ! ------------------------------------------------------------------------
 !  solve the linear equations to obtain partial charges
 ! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "Solve the linear equations to obtain partial charges"
    amat(m,1:m) = 1.0_wp
    amat(1:m,m) = 1.0_wp
    amat(m,m  ) = 0.0_wp
    xvec(m)     = mol%chrg
    ! generate temporary copy
    allocate( atmp(m,m), source = amat )
    allocate( xtmp(m),   source = xvec )
    ! assume work space query, set best value to test after first dsysv call
    call dsysv('u', m, 1, atmp, m, ipiv, xtmp, m, test, -1, info)
    lwork = int(test(1))
    allocate( work(lwork), source = 0.0_wp )
    call dsysv('u',m,1,atmp,m,ipiv,xtmp,m,work,lwork,info)
    if(info > 0) then
       call env%error("Coulomb matrix is singular, cannot solve lin. eq.", source)
       return
    end if
    q = xtmp(:mol%n)
    if(abs(sum(q)-mol%chrg) > 1.e-6_wp) then
       call env%error("Charge constraint is not satisfied", source)
       return
    end if
    !print'(3f20.14)',Xtmp
    lambda = xtmp(m)
    if (lverbose) then
       write(istdout,'(72("-"))')
       write(istdout,'(1x,a,1x,f20.14)') &
          "lambda       :",lambda,&
          "total charge :",sum(q)
    endif
 ! ------------------------------------------------------------------------
 !  calculate isotropic electrostatic (IES) energy
 ! ------------------------------------------------------------------------
 !  E = ∑i (ENi - κi·√CNi)·qi + ∑i (Jii + 2/√π·γii)·q²i
 !      + ½ ∑i ∑j,j≠i qi·qj·2/√π·F0(γ²ij·R²ij)
 !    = q·(½A·q - X)
 ! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "Isotropic electrostatic (IES) energy calculation"
    call mctc_copy(xvec, work)
    call mctc_symv(amat, xtmp, work, alpha=0.5_wp, beta=-1.0_wp)
    es = mctc_dot(xtmp, work)
    energy = es + energy
    if (lverbose) then
       write(istdout,'(72("-"))')
       write(istdout,'(1x,a,1x,f20.14)') &
          "energy",es
    endif
 ! ------------------------------------------------------------------------
 !  calculate molecular gradient of the IES energy
 ! ------------------------------------------------------------------------
 !  dE/dRj -> g(:,j), ∂Xi/∂Rj -> -dcn(:,i,j), ½∂Aij/∂Rj -> dAmat(:,j,i)
 !  dE/dR = (½∂A/∂R·q - ∂X/∂R)·q
 !  ∂Aij/∂Rj = ∂Aij/∂Ri
 ! ------------------------------------------------------------------------
 do_molecular_gradient: if (lgrad .or. lcpq) then
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "molecular gradient calculation"
    allocate( damatdr(3,mol%n,m), dxvecdr(3,mol%n,m), afac(3,mol%n), source = 0.0_wp )
    call get_coulomb_derivs(mol, chrgeq, xtmp, damatdr, afac)
    do i = 1, mol%n
       damatdr(:,:,i) = damatdr(:,:,i) - dcndr(:,:,i)*xfac(i)
    enddo
    call gbsa%addBornDeriv(xtmp, gborn, ghb, damatdr, afac)
    gsolv = gsolv + gborn + ghb + gbsa%gshift
 endif do_molecular_gradient
    if (lgrad) then
    call mctc_gemv(damatdr, xtmp, gradient, alpha=1.0_wp, beta=1.0_wp)
    endif
 ! ------------------------------------------------------------------------
 !  invert the A matrix using a Bunch-Kaufman factorization
 !  A⁻¹ = (L·D·L^T)⁻¹ = L^T·D⁻¹·L
 ! ------------------------------------------------------------------------
 do_partial_charge_derivative: if (lcpq) then
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "A matrix inversion by Bunch-Kaufman factorization"
    allocate( ainv(m,m), source = amat )
    ! assume work space query, set best value to test after first dsytrf call
    call lapack_sytrf('L',m,ainv,m,ipiv,test,-1,info)
    if (int(test(1)) > lwork) then
       deallocate(work)
       lwork=int(test(1))
       allocate( work(lwork), source = 0.0_wp )
    endif
    ! Bunch-Kaufman factorization A = L*D*L**T
    call lapack_sytrf('L',m,ainv,m,ipiv,work,lwork,info)
    if(info > 0)then
       call env%error("Could not factorize Coulomb matrix", source)
       return
    endif
    ! A⁻¹ from factorized L matrix, save lower part of A⁻¹ in Ainv matrix
    ! Ainv matrix is overwritten with lower triangular part of A⁻¹
    call lapack_sytri('L',m,ainv,m,ipiv,work,info)
    if (info > 0) then
       call env%error("Coulomb Matrix is singular, cannot invert", source)
       return
    endif
    ! symmetrizes A⁻¹ matrix from lower triangular part of inverse matrix
    do i = 1, m
       do j = i+1, m
          ainv(i,j)=ainv(j,i)
       enddo
    enddo
 ! ------------------------------------------------------------------------
 !  calculate gradient of the partial charge w.r.t. the nuclear coordinates
 ! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "calculating the derivative of the partial charges"
    dqdr = 0.0_wp
    do i = 1, mol%n
       damatdr(:,i,i) = afac(:,i) + damatdr(:,i,i)
    enddo
    !call dsymm('r','l',3*n,m,-1.0_wp,Ainv,m,dAmatdr,3*n,1.0_wp,dqdr,3*n)
    call dgemm('n','n',3*mol%n,mol%n,m,-1.0_wp,damatdr,3*mol%n,ainv,m, &
       &       1.0_wp,dqdr,3*mol%n)
    !print'(/,"analytical gradient")'
    !print'(3f20.14)',dqdr(:,:,:n)
 endif do_partial_charge_derivative
 ! ------------------------------------------------------------------------
 !  Clean up
 ! ------------------------------------------------------------------------
    if (allocated(amat))  deallocate(amat)
    if (allocated(damatdr)) deallocate(damatdr)
    if (allocated(afac))  deallocate(afac)
    if (allocated(xvec))  deallocate(xvec)
    if (allocated(xfac))  deallocate(xfac)
    if (allocated(xtmp))  deallocate(xtmp)
    if (allocated(atmp))  deallocate(atmp)
    if (allocated(temp))  deallocate(temp)
    if (allocated(work))  deallocate(work)
    if (allocated(ipiv))  deallocate(ipiv)
eeq_chrgeq_qonly()
subroutine xtb_eeq::eeq_chrgeq_qonly (type(tmolecule), intent(in) mol, type(tenvironment), intent(inout) env, type(chrg_parameter), intent(in) chrgeq, real(wp), dimension(mol%n), intent(in) cn, real(wp), dimension(mol%n), intent(out) q, logical, intent(in), optional lverbose) private
Parameters
[in] mol molecular structure information
Definition at line 632 of file eeq_model.f90.
    use xtb_type_molecule
    use xtb_type_param
    implicit none
 ! ------------------------------------------------------------------------
 !  Input
 ! ------------------------------------------------------------------------
    type(TMolecule),intent(in) :: mol
    real(wp),intent(in)    :: cn(mol%n)     ! erf-CN
    type(chrg_parameter),intent(in) :: chrgeq
    real(wp),allocatable   :: dcndr(:,:,:)
    real(wp),allocatable   :: dcndL(:,:,:)
    logical, intent(in), optional :: lverbose
    logical :: verbose
    type(TEnvironment), intent(inout) :: env
 ! ------------------------------------------------------------------------
 !  Output
 ! ------------------------------------------------------------------------
    real(wp),intent(out)   :: q(mol%n)
    real(wp),allocatable   :: dqdr(:,:,:)
    real(wp),allocatable   :: dqdL(:,:,:)
    real(wp)               :: energy
    real(wp),allocatable   :: gradient(:,:)
    real(wp),allocatable   :: sigma(:,:)
    if (present(lverbose)) then
       verbose = lverbose
    else
       verbose = .false.
    endif
    call eeq_chrgeq_core(mol,env,chrgeq,cn,dcndr,dcndl,q,dqdr,dqdl, &
       &                 energy,gradient,sigma,verbose,.false.,.false.)
eeq_ewald_3d_dir()
pure real(wp) function xtb_eeq::eeq_ewald_3d_dir (real(wp), dimension(3), intent(in) riw, real(wp), dimension(:,:), intent(in) rTrans, real(wp), intent(in) gamij, real(wp), intent(in) cf, real(wp), intent(in) scale)
Parameters
[in] riw distance from i to WSC atom
[in] rtrans direct lattice
[in] gamij interaction radius
[in] cf convergence factor
Returns
element of interaction matrix
Definition at line 232 of file eeq_model.f90.
    use xtb_mctc_constants
    implicit none
    real(wp),intent(in) :: riw(3)
    real(wp),intent(in) :: rTrans(:,:)
    real(wp),intent(in) :: gamij
    real(wp),intent(in) :: cf
    real(wp),intent(in) :: scale
    real(wp) :: Amat
    real(wp),parameter :: eps = 1.0e-9_wp
    integer  :: dx,dy,dz,itr
    real(wp) :: distiw,rij(3)
    real(wp) :: t(3)
    amat = 0.0_wp
    do itr = 1, size(rtrans, dim=2)
       rij = riw + rtrans(:, itr)
       distiw = sqrt(sum(rij**2))
       ! self-interaction correction
       if(distiw < eps) then
          amat = amat - cf/sqrtpi
       else
          amat = amat - erf(   cf*distiw)/distiw &
             &        + erf(gamij*distiw)/distiw
       end if
    end do
    amat = amat * scale
References xtb_mctc_constants::sqrtpi.
Referenced by xtb_eeq::get_coulomb_matrix::get_coulomb_matrix_3d().
eeq_ewald_dx_3d_dir()
pure subroutine xtb_eeq::eeq_ewald_dx_3d_dir (real(wp), dimension(3), intent(in) riw, real(wp), dimension(:,:), intent(in) rTrans, real(wp), intent(in) gamij, real(wp), intent(in) cf, real(wp), intent(in) scale, real(wp), dimension(3), intent(out) dAmat, real(wp), dimension(3,3), intent(out) sigma)
Parameters
[in] riw distance from i to WSC atom
[in] gamij interaction radius
[in] cf convergence factor
[out] damat element of interaction matrix
Definition at line 260 of file eeq_model.f90.
    use xtb_mctc_constants
    use xtb_pbc_tools
    implicit none
    real(wp),intent(in) :: riw(3)
    real(wp),intent(in) :: rTrans(:,:)
    real(wp),intent(in) :: gamij
    real(wp),intent(in) :: cf
    real(wp),intent(in) :: scale
    real(wp),intent(out) :: dAmat(3)
    real(wp),intent(out) :: sigma(3,3)
    real(wp),parameter :: eps = 1.0e-9_wp
    integer  :: dx,dy,dz,i,itr
    real(wp) :: distiw,rij(3),arga,argb
    real(wp) :: t(3),dtmp,stmp(3)
    damat = 0.0_wp
    sigma = 0.0_wp
    do itr = 1, size(rtrans, dim=2)
       ! real contributions
       rij = riw + rtrans(:, itr)
       distiw = sqrt(sum(rij**2))
       if(distiw < eps) cycle
       arga = cf**2   *distiw**2
       stmp = + exp(-arga)/sqrtpi * cf * 2.0_wp / 3.0_wp
       do i = 1, 3
          sigma(i,i) = sigma(i,i) + stmp(i)! * rij(i)**2
       enddo
       argb = gamij**2*distiw**2
       dtmp = - 2*cf*exp(-arga)/(sqrtpi*distiw**2) &
          &   + erf(cf*distiw)/(distiw**3)           &
          &   + 2*gamij*exp(-argb)/(sqrtpi*distiw**2) &
          &   - erf(gamij*distiw)/(distiw**3)
       damat = damat + rij*dtmp
       sigma = sigma + dtmp*outer_prod_3x3(rij,rij)
    enddo
    damat = damat * scale
    sigma = sigma * scale
References xtb_pbc_tools::outer_prod_3x3(), and xtb_mctc_constants::sqrtpi.
Referenced by xtb_eeq::get_coulomb_derivs::get_coulomb_derivs_3d().
get_coulomb_derivs_0d()
subroutine xtb_eeq::get_coulomb_derivs_0d (type(tmolecule), intent(in) mol, type(chrg_parameter), intent(in) chrgeq, real(wp), dimension(:), intent(in) qvec, real(wp), dimension(:, :, :), intent(out) amatdr, real(wp), dimension(:, :), intent(out) atrace)
Definition at line 129 of file eeq_model.f90.
    use xtb_type_molecule
    use xtb_type_param
    type(TMolecule), intent(in) :: mol
    type(chrg_parameter), intent(in) :: chrgeq
    real(wp), intent(in) :: qvec(:)
    real(wp), intent(out) :: amatdr(:, :, :)
    real(wp), intent(out) :: atrace(:, :)
    integer :: iat, jat
    real(wp) :: rij(3), r2, gamij2, arg2
    real(wp) :: dE, dG(3)
    amatdr = 0.0_wp
    atrace = 0.0_wp
    !$omp parallel do default(none) schedule(runtime) reduction(+:atrace, amatdr) &
    !$omp shared(mol,chrgeq, qvec) private(jat, rij, r2, gamij2, arg2, dE, dG)
    do iat = 1, len(mol)
       ! EN of atom i
       do jat = 1, iat-1
          rij = mol%xyz(:,iat) - mol%xyz(:,jat)
          r2 = sum(rij**2)
          gamij2 = 1.0_wp/(chrgeq%alpha(iat)**2+chrgeq%alpha(jat)**2)
          arg2 = gamij2*r2
          de = erf(sqrt(arg2))/sqrt(r2)
          dg = (2*sqrt(gamij2)*exp(-arg2)/sqrtpi - de) * rij/r2
          amatdr(:, iat, jat) = amatdr(:, iat, jat) + dg*qvec(iat)
          amatdr(:, jat, iat) = amatdr(:, jat, iat) - dg*qvec(jat)
          atrace(:, iat) = atrace(:, iat) + dg*qvec(jat)
          atrace(:, jat) = atrace(:, jat) - dg*qvec(iat)
       enddo
    enddo
    !$omp end parallel do
get_coulomb_derivs_3d()
subroutine xtb_eeq::get_coulomb_derivs_3d (type(tmolecule), intent(in) mol, type(chrg_parameter), intent(in) chrgeq, real(wp), dimension(:), intent(in) qvec, real(wp), dimension(:, :), intent(in) rTrans, real(wp), dimension(:, :), intent(in) gTrans, real(wp), intent(in) cf, real(wp), dimension(:, :, :), intent(out) amatdr, real(wp), dimension(:, :, :), intent(out) amatdL, real(wp), dimension(:, :), intent(out) atrace)
Definition at line 162 of file eeq_model.f90.
    use xtb_type_molecule
    use xtb_type_param
    type(TMolecule), intent(in) :: mol
    type(chrg_parameter), intent(in) :: chrgeq
    real(wp), intent(in) :: cf
    real(wp), intent(in) :: qvec(:)
    real(wp), intent(in) :: gTrans(:, :)
    real(wp), intent(in) :: rTrans(:, :)
    real(wp), intent(out) :: amatdr(:, :, :)
    real(wp), intent(out) :: amatdL(:, :, :)
    real(wp), intent(out) :: atrace(:, :)
    integer, parameter :: ewaldCutD(3) = 2
    integer, parameter :: ewaldCutR(3) = 2
    real(wp), parameter :: zero(3) = 0.0_wp
    integer :: iat, jat, wscAt, ii
    real(wp) :: gamij, dG(3), dS(3, 3), riw(3)
    integer :: iG1, iG2, iG3, iRp
    real(wp) :: gVec(3)
    real(wp), parameter :: unity(3, 3) = reshape(&
       & [1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp], &
       & [3, 3])
    amatdr = 0.0_wp
    amatdl = 0.0_wp
    atrace = 0.0_wp
    !$omp parallel do default(none) schedule(runtime) &
    !$omp reduction(+:atrace,amatdr,amatdL) &
    !$omp shared(mol, chrgeq, qvec, cf, gTrans, rTrans) &
    !$omp private(iat, jat, ii, wscAt, riw, gamij, dG, dS)
    do iat = 1, len(mol)
       do jat = 1, iat-1
          ! over WSC partner
          gamij = 1.0_wp/sqrt(chrgeq%alpha(iat)**2 + chrgeq%alpha(jat)**2)
          do wscat = 1, mol%wsc%itbl(jat,iat)
             ! PGI 20.7 fails with `ICE: Errors in Lowering' for
             ! - matmul(mol%lattice,mol%wsc%lattr(:,wscAt,jat,iat))
             riw = mol%xyz(:,iat) - mol%xyz(:,jat) &
                & - (mol%lattice(:,1) * mol%wsc%lattr(1,wscat,jat,iat) &
                &  + mol%lattice(:,2) * mol%wsc%lattr(2,wscat,jat,iat) &
                &  + mol%lattice(:,3) * mol%wsc%lattr(3,wscat,jat,iat))
             call ewaldderivpbc3d(riw, gtrans, 0.0_wp, mol%volume, cf, &
                & mol%wsc%w(jat,iat), dg, ds)
             amatdr(:, iat, jat) = amatdr(:, iat, jat) + dg*qvec(iat)
             amatdr(:, jat, iat) = amatdr(:, jat, iat) - dg*qvec(jat)
             atrace(:, iat) = atrace(:, iat) + dg*qvec(jat)
             atrace(:, jat) = atrace(:, jat) - dg*qvec(iat)
             amatdl(:, :, iat) = amatdl(:, :, iat) + ds*qvec(jat)
             amatdl(:, :, jat) = amatdl(:, :, jat) + ds*qvec(iat)
             call eeq_ewald_dx_3d_dir(riw, rtrans, gamij, cf, mol%wsc%w(jat,iat), &
                &                     dg,ds)
             amatdr(:, iat, jat) = amatdr(:, iat, jat) + dg*qvec(iat)
             amatdr(:, jat, iat) = amatdr(:, jat, iat) - dg*qvec(jat)
             atrace(:, iat) = atrace(:, iat) + dg*qvec(jat)
             atrace(:, jat) = atrace(:, jat) - dg*qvec(iat)
             amatdl(:, :, iat) = amatdl(:, :, iat) + ds*qvec(jat)
             amatdl(:, :, jat) = amatdl(:, :, jat) + ds*qvec(iat)
          enddo  ! k WSC partner
       enddo     ! jat
       gamij = 1.0_wp/(sqrt(2.0_wp)*chrgeq%alpha(iat))
       call ewaldderivpbc3d(zero, gtrans, 0.0_wp, mol%volume, cf, 1.0_wp, dg, ds)
       amatdl(:, :, iat) = amatdl(:, :, iat) + ds*qvec(iat)
       call eeq_ewald_dx_3d_dir(zero, rtrans, gamij, cf, 1.0_wp, dg, ds)
       amatdl(:, :, iat) = amatdl(:, :, iat) + (ds+unity*cf/sqrtpi/3.0_wp)*qvec(iat)
    enddo
    !$omp end parallel do
get_coulomb_matrix_0d()
subroutine xtb_eeq::get_coulomb_matrix_0d (type(tmolecule), intent(in) mol, type(chrg_parameter), intent(in) chrgeq, real(wp), dimension(:, :), intent(out) amat) private
Definition at line 59 of file eeq_model.f90.
    type(TMolecule), intent(in) :: mol
    type(chrg_parameter), intent(in) :: chrgeq
    real(wp), intent(out) :: amat(:, :)
    integer :: iat, jat
    real(wp) :: r1, gamij
    amat = 0.0_wp
    !$omp parallel do default(none) schedule(runtime) shared(mol,chrgeq, amat) &
    !$omp private(jat, r1, gamij)
    do iat = 1, len(mol)
       ! EN of atom i
       do jat = 1, iat-1
          r1 = sqrt(sum((mol%xyz(:,jat) - mol%xyz(:,iat))**2))
          gamij = 1.0_wp/sqrt(chrgeq%alpha(iat)**2+chrgeq%alpha(jat)**2)
          amat(jat, iat) = erf(gamij*r1)/r1
          amat(iat, jat) = amat(jat,iat)
       enddo
       amat(iat, iat) = chrgeq%gam(iat) + sqrt2pi/chrgeq%alpha(iat)
    enddo
    !$omp end parallel do
get_coulomb_matrix_3d()
subroutine xtb_eeq::get_coulomb_matrix_3d (type(tmolecule), intent(in) mol, type(chrg_parameter), intent(in) chrgeq, real(wp), dimension(:, :), intent(in) rTrans, real(wp), dimension(:, :), intent(in) gTrans, real(wp), intent(in) cf, real(wp), dimension(:, :), intent(out) amat) private
Definition at line 81 of file eeq_model.f90.
    use xtb_type_molecule
    use xtb_type_param
    type(TMolecule), intent(in) :: mol
    type(chrg_parameter), intent(in) :: chrgeq
    real(wp), intent(in) :: rTrans(:, :)
    real(wp), intent(in) :: gTrans(:, :)
    real(wp), intent(in) :: cf
    real(wp), intent(out) :: amat(:, :)
    integer, parameter :: ewaldCutD(3) = 2
    integer, parameter :: ewaldCutR(3) = 2
    real(wp), parameter :: zero(3) = 0.0_wp
    integer :: iat, jat, wscAt, iG1, iG2, iG3, iRp
    real(wp) :: gamii, gamij, riw(3), gVec(3)
    amat = 0.0_wp
    !$omp parallel do default(none) reduction(+:amat) &
    !$omp shared(mol, chrgeq, cf, gTrans, rTrans) &
    !$omp private(iat, jat, wscAt, gamii, gamij, riw)
    do iat = 1, len(mol)
       gamii = 1.0_wp/(sqrt(2.0_wp)*chrgeq%alpha(iat))
       amat(iat, iat) = chrgeq%gam(iat) + sqrt2pi/chrgeq%alpha(iat) &
          ! reciprocal for 0th atom
          + ewaldmatpbc3d(zero, gtrans, 0.0_wp, mol%volume, cf, 1.0_wp) &
          ! direct for 0th atom
          + eeq_ewald_3d_dir(zero, rtrans, gamii, cf, 1.0_wp)
       do jat = 1, iat-1
          gamij = 1.0_wp/sqrt(chrgeq%alpha(iat)**2+chrgeq%alpha(jat)**2)
          do wscat = 1, mol%wsc%itbl(jat,iat)
             ! PGI 20.7 fails with `ICE: Errors in Lowering' for
             ! - matmul(mol%lattice,mol%wsc%lattr(:,wscAt,jat,iat))
             riw = mol%xyz(:,iat) - mol%xyz(:,jat) &
                & - (mol%lattice(:,1) * mol%wsc%lattr(1,wscat,jat,iat) &
                &  + mol%lattice(:,2) * mol%wsc%lattr(2,wscat,jat,iat) &
                &  + mol%lattice(:,3) * mol%wsc%lattr(3,wscat,jat,iat))
             amat(iat,jat) = amat(iat,jat) &
                ! reciprocal lattice sums
                + ewaldmatpbc3d(riw, gtrans, 0.0_wp, mol%volume, cf, &
                   & mol%wsc%w(jat,iat)) &
                ! direct lattice sums
                + eeq_ewald_3d_dir(riw, rtrans, gamij, cf, mol%wsc%w(jat,iat))
          end do
          amat(jat,iat) = amat(iat,jat)
       end do
    end do
    !$omp end parallel do
goedecker_chrgeq()
subroutine, public xtb_eeq::goedecker_chrgeq (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), intent(in) chrg, real(wp), dimension(n), intent(in) cn, real(wp), dimension(3,n,n), intent(in) dcndr, real(wp), dimension(n), intent(out) q, real(wp), dimension(3,n,n), intent(out) dqdr, real(wp), intent(inout) energy, real(wp), dimension(3,n), intent(inout) gradient, logical, intent(in) lverbose, logical, intent(in) lgrad, logical, intent(in) lcpq)
Definition at line 341 of file eeq_model.f90.
    implicit none
 !! ------------------------------------------------------------------------
 !  Input
 !! ------------------------------------------------------------------------
    integer, intent(in)    :: n             ! number of atoms
    integer, intent(in)    :: at(n)         ! ordinal numbers
    real(wp),intent(in)    :: xyz(3,n)      ! geometry
    real(wp),intent(in)    :: chrg          ! total charge
    real(wp),intent(in)    :: cn(n)         ! erf-CN
    real(wp),intent(in)    :: dcndr(3,n,n)  ! derivative of erf-CN
    logical, intent(in)    :: lverbose      ! toggles printout
    logical, intent(in)    :: lgrad         ! flag for gradient calculation
    logical, intent(in)    :: lcpq          ! do partial charge derivative
 !! ------------------------------------------------------------------------
 !  Output
 !! ------------------------------------------------------------------------
    real(wp),intent(out)   :: q(n)          ! partial charges
    real(wp),intent(out)   :: dqdr(3,n,n) ! derivative of partial charges
    real(wp),intent(inout) :: energy        ! electrostatic energy
    real(wp),intent(inout) :: gradient(3,n) ! molecular gradient of IES
 !
 !! ------------------------------------------------------------------------
 !  charge model
 !! ------------------------------------------------------------------------
    integer  :: m ! dimension of the Lagrangian
    real(wp),allocatable :: Amat(:,:)
    real(wp),allocatable :: Xvec(:)
    real(wp),allocatable :: Ainv(:,:)
    real(wp),allocatable :: dAmat(:,:,:)
    real(wp),allocatable :: dXvec(:,:,:)
 !! ------------------------------------------------------------------------
 !  local variables
 !! ------------------------------------------------------------------------
    integer  :: i,j,k,l
    real(wp) :: r,rij(3),r2
    real(wp) :: gamij,gamij2
    real(wp) :: arg,tmp,dtmp
    real(wp) :: lambda
    real(wp) :: es
 !! ------------------------------------------------------------------------
 !  scratch variables
 !! ------------------------------------------------------------------------
    real(wp),allocatable :: alpha(:)
    real(wp),allocatable :: xtmp(:)
    real(wp),allocatable :: atmp(:,:)
    real(wp),allocatable :: Xfac(:)
    real(wp),allocatable :: Afac(:,:)
 !! ------------------------------------------------------------------------
 !  Lapack work variables
 !! ------------------------------------------------------------------------
    integer, allocatable :: ipiv(:)
    real(wp),allocatable :: temp(:)
    real(wp),allocatable :: work(:)
    integer  :: lwork
    integer  :: info
    real(wp) :: test(1)
 !! ------------------------------------------------------------------------
 !  initial banner if verbose
 !! ------------------------------------------------------------------------
    if (lverbose) then
       write(istdout,'(72("="),/,1x,a,/,72("="),/)') &
          "GOEDECKER CHARGE MODEL USING GFN0-xTB PARAMETRIZATION"
    endif
 !! ------------------------------------------------------------------------
 !  initizialization
 !! ------------------------------------------------------------------------
    m    = n+1
    q    = 0.0_wp
    allocate( ipiv(m), source = 0 )
    allocate( amat(m,m), xvec(m), xfac(m), alpha(n), source = 0.0_wp )
 !! ------------------------------------------------------------------------
 !  set up the A matrix and X vector
 !! ------------------------------------------------------------------------
 !  αi -> alpha(i), ENi -> xi(i), κi -> kappa(i), Jii -> gam(i)
 !  γij = 1/√(αi+αj)
 !  Xi  = -ENi + κi·√CNi
 !  Aii = Jii + 2/√π·γii
 !  Aij = erf(γij·Rij)/Rij = 2/√π·F0(γ²ij·R²ij)
 !! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "Setup of the A matrix and the RHS X vector"
 !  prepare some arrays
 !$omp parallel default(none) &
 !$omp shared(n,at,cn,xi,cnfak,alp,gamm) &
 !$omp private(i,tmp) &
 !$omp shared(Xvec,Xfac,alpha)
 !$omp do schedule(runtime)
    do i = 1, n
       tmp = cnfak(at(i))/(sqrt(cn(i))+1e-14_wp)
       xvec(i) = -xi(at(i)) + tmp*cn(i)
       xfac(i) = 0.5_wp*tmp
       alpha(i) = alp(at(i))**2
    enddo
 !$omp enddo
 !$omp endparallel
 !$omp parallel default(none) &
 !$omp shared(n,at,xyz,gamm,alpha) &
 !$omp private(i,j,r,gamij) &
 !$omp shared(Xvec,Xfac,Amat)
 !$omp do schedule(runtime)
    ! prepare A matrix
    do i = 1, n
       ! EN of atom i
       do j = 1, i-1
          r = sqrt(sum((xyz(:,j) - xyz(:,i))**2))
          gamij = 1.0_wp/sqrt(alpha(i)+alpha(j))
          amat(j,i) = erf(gamij*r)/r
          amat(i,j) = amat(j,i)
       enddo
       amat(i,i) = gamm(at(i)) + sqrt2pi/sqrt(alpha(i))
    enddo
 !$omp enddo
 !$omp endparallel
 !! ------------------------------------------------------------------------
 !  solve the linear equations to obtain partial charges
 !! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "Solve the linear equations to obtain partial charges"
    amat(m,1:m) = 1.0_wp
    amat(1:m,m) = 1.0_wp
    amat(m,m  ) = 0.0_wp
    xvec(m)     = chrg
    ! generate temporary copy
    allocate( atmp(m,m), source = amat )
    allocate( xtmp(m),   source = xvec )
    ! assume work space query, set best value to test after first dsysv call
    call dsysv('u', m, 1, atmp, m, ipiv, xtmp, m, test, -1, info)
    lwork = int(test(1))
    allocate( work(lwork), source = 0.0_wp )
    call dsysv('u',m,1,atmp,m,ipiv,xtmp,m,work,lwork,info)
    if(info > 0) call raise('E','(goedecker_solve) DSYSV failed')
    q = xtmp(:n)
    if(abs(sum(q)-chrg) > 1.e-6_wp) &
       call raise('E','(goedecker_solve) charge constrain error')
    !print'(3f20.14)',Xtmp
    lambda = xtmp(m)
    if (lverbose) then
       write(istdout,'(72("-"))')
       write(istdout,'(1x,a,1x,f20.14)') &
          "lambda       :",lambda,&
          "total charge :",sum(q)
    endif
 !! ------------------------------------------------------------------------
 !  calculate isotropic electrostatic (IES) energy
 !! ------------------------------------------------------------------------
 !  E = ∑i (ENi - κi·√CNi)·qi + ∑i (Jii + 2/√π·γii)·q²i
 !      + ½ ∑i ∑j,j≠i qi·qj·2/√π·F0(γ²ij·R²ij)
 !    = q·(½A·q - X)
 !! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "Isotropic electrostatic (IES) energy calculation"
    call mctc_copy(xvec, work)
    call mctc_symv(amat, xtmp, work, alpha=0.5_wp, beta=-1.0_wp)
    es = mctc_dot(xtmp, work)
    energy = es + energy
    if (lverbose) then
       write(istdout,'(72("-"))')
       write(istdout,'(1x,a,1x,f20.14)') &
          "energy",es
    endif
 !! ------------------------------------------------------------------------
 !  calculate molecular gradient of the IES energy
 !! ------------------------------------------------------------------------
 !  dE/dRj -> g(:,j), ∂Xi/∂Rj -> -dcn(:,i,j), ½∂Aij/∂Rj -> dAmat(:,j,i)
 !  dE/dR = (½∂A/∂R·q - ∂X/∂R)·q
 !  ∂Aij/∂Rj = ∂Aij/∂Ri
 !! ------------------------------------------------------------------------
 do_molecular_gradient: if (lgrad .or. lcpq) then
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "molecular gradient calculation"
    allocate( damat(3,n,m), dxvec(3,n,m), afac(3,n), source = 0.0_wp )
    !allocate( dAmat(3,n,m), Afac(3,n), source = 0.0_wp )
 !$omp parallel default(none) &
 !$omp shared(n,dcndr,xyz,alpha,Amat,Xfac,Xtmp) &
 !$omp private(i,j,rij,r2,gamij,arg,dtmp) &
 !$omp shared(dXvec,dAmat) &
 !$omp reduction(+:Afac)
 !$omp do schedule(runtime)
    do i = 1, n
       dxvec(:,i,i) = +dcndr(:,i,i)*xfac(i) ! merge dX and dA for speedup
       do j = 1, i-1
          dxvec(:,j,i) = dcndr(:,i,j)*xfac(i)
          dxvec(:,i,j) = dcndr(:,j,i)*xfac(j)
          rij = xyz(:,i) - xyz(:,j)
          r2 = sum(rij**2)
          gamij = 1.0_wp/sqrt(alpha(i) + alpha(j))
          arg = gamij**2*r2
          dtmp = 2.0_wp*gamij*exp(-arg)/(sqrtpi*r2)-amat(j,i)/r2
          afac(:,i) = +dtmp*rij*xtmp(j) + afac(:,i)
          afac(:,j) = -dtmp*rij*xtmp(i) + afac(:,j)
          damat(:,i,j) = +dtmp*rij*xtmp(i) !+ dcndr(:,i,j)*Xfac(i)
          damat(:,j,i) = -dtmp*rij*xtmp(j) !+ dcndr(:,j,i)*Xfac(j)
       enddo
       !dAmat(:,i,i) = +dcndr(:,i,i)*Xfac(i)
    enddo
 !$omp enddo
 !$omp endparallel
 endif do_molecular_gradient
    if (lgrad) then
    call mctc_gemv(damat,xtmp,gradient,alpha=+1.0_wp,beta=1.0_wp)
    call mctc_gemv(dxvec,xtmp,gradient,alpha=-1.0_wp,beta=1.0_wp)
    endif
 !! ------------------------------------------------------------------------
 !  invert the A matrix using a Bunch-Kaufman factorization
 !  A⁻¹ = (L·D·L^T)⁻¹ = L^T·D⁻¹·L
 !! ------------------------------------------------------------------------
 do_partial_charge_derivative: if (lcpq) then
    dqdr = 0.0_wp
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "A matrix inversion by Bunch-Kaufman factorization"
    allocate( ainv(m,m), source = amat )
    ! assume work space query, set best value to test after first dsytrf call
    call lapack_sytrf('L',m,ainv,m,ipiv,test,-1,info)
    if (int(test(1)) > lwork) then
       deallocate(work)
       lwork=int(test(1))
       allocate( work(lwork), source = 0.0_wp )
    endif
    ! Bunch-Kaufman factorization A = L*D*L**T
    call lapack_sytrf('L',m,ainv,m,ipiv,work,lwork,info)
    if(info > 0)then
       call raise('E', '(goedecker_inversion) DSYTRF failed')
    endif
    ! A⁻¹ from factorized L matrix, save lower part of A⁻¹ in Ainv matrix
    ! Ainv matrix is overwritten with lower triangular part of A⁻¹
    call lapack_sytri('L',m,ainv,m,ipiv,work,info)
    if (info > 0) then
       call raise('E', '(goedecker_inversion) DSYTRI failed')
    endif
    ! symmetrizes A⁻¹ matrix from lower triangular part of inverse matrix
    do i = 1, m
       do j = i+1, m
          ainv(i,j)=ainv(j,i)
       enddo
    enddo
 !! ------------------------------------------------------------------------
 !  calculate gradient of the partial charge w.r.t. the nuclear coordinates
 !! ------------------------------------------------------------------------
    if (lverbose) write(istdout,'(72("="),/,1x,a)') &
       "calculating the derivative of the partial charges"
    do i = 1, n
       damat(:,i,i) = afac(:,i) + damat(:,i,i)
    enddo
    call mctc_gemm(damat, ainv, dqdr, alpha=-1.0_wp, beta=1.0_wp)
    call mctc_gemm(dxvec, ainv, dqdr, alpha=+1.0_wp, beta=1.0_wp)
    !print'(/,"analytical gradient")'
    !print'(3f20.14)',dqdr(:,:,:n)
 endif do_partial_charge_derivative
 !! ------------------------------------------------------------------------
 !  Clean up
 !! ------------------------------------------------------------------------
    if (allocated(alpha)) deallocate(alpha)
    if (allocated(amat))  deallocate(amat)
    if (allocated(damat)) deallocate(damat)
    if (allocated(afac))  deallocate(afac)
    if (allocated(xvec))  deallocate(xvec)
    if (allocated(xfac))  deallocate(xfac)
    if (allocated(xtmp))  deallocate(xtmp)
    if (allocated(atmp))  deallocate(atmp)
    if (allocated(temp))  deallocate(temp)
    if (allocated(work))  deallocate(work)
    if (allocated(ipiv))  deallocate(ipiv)
References xtb_gfn0param::cnfak, xtb_gfn0param::gamm, raise(), sqrt2pi, xtb_mctc_constants::sqrtpi, and xtb_gfn0param::xi.
Referenced by xtb_prog_main::xtbmain().
Variable Documentation
sqrt2pi
real(wp), parameter xtb_eeq::sqrt2pi = sqrt(2.0_wp/pi) private
Definition at line 36 of file eeq_model.f90.
    real(wp),parameter :: sqrt2pi = sqrt(2.0_wp/pi)
Referenced by xtb_eeq::get_coulomb_matrix::get_coulomb_matrix_0d(), xtb_eeq::get_coulomb_matrix::get_coulomb_matrix_3d(), and goedecker_chrgeq().