My Project: xtb_mctc_boundaryconditions Module Reference
xtb_mctc_boundaryconditions Module Reference
Available boundary conditions in this program.
Data Types
type tboundarycondenum
Possible boundary conditions.
Variables
type(tboundarycondenum), parameter, public boundarycondition = TBoundaryCondEnum()
Boundary condition enumerator.
Detailed Description
Available boundary conditions in this program.
Variable Documentation
boundarycondition
type(tboundarycondenum), parameter, public xtb_mctc_boundaryconditions::boundarycondition = TBoundaryCondEnum()
Boundary condition enumerator.
Definition at line 38 of file boundaryconditions.f90.
    type(TBoundaryCondEnum), parameter :: boundaryCondition = tboundarycondenum()
Referenced by xtb_type_latticepoint::generate(), xtb_coulomb_gaussian::getcoulombderivs(), xtb_coulomb_klopmanohno::getcoulombderivs(), xtb_type_coulomb::getcoulombderivs(), xtb_coulomb_gaussian::getcoulombmatrix(), xtb_coulomb_klopmanohno::getcoulombmatrix(), xtb_type_coulomb::getcoulombmatrix(), xtb_type_latticepoint::getlatticepoints(), xtb_type_latticepoint::init::initlatticepoint(), xtb_type_molecule::init::initmolecule(), xtb_type_molecule::tmolecule::new_molecule_api(), xtb_type_coulomb::setupboundaryconditions(), test_latticepoint_pbc3d(), xtb_type_latticepoint::update(), and xtb_type_coulomb::update().