My Project: xtb_mctc_convert Module Reference
xtb_mctc_convert Module Reference
Variables
real(wp), parameter, public autoaa = 0.52917726_wp
real(wp), parameter, public aatoau = 1.0_wp/autoaa
real(wp), parameter, public autoev = 27.21138505_wp
real(wp), parameter, public evtoau = 1.0_wp/autoev
real(wp), parameter, public autokcal = 627.50947428_wp
real(wp), parameter, public kcaltoau = 1.0_wp/autokcal
real(wp), parameter, public autokj = 2625.49964038_wp
real(wp), parameter, public kjtoau = 1.0_wp/autokj
real(wp), parameter, public autorcm = 219474.63067_wp
real(wp), parameter, public autowav = autorcm
real(wp), parameter, public rcmtoau = 1.0_wp/autorcm
real(wp), parameter, public wavtoau = 1.0_wp/autowav
real(wp), parameter, public autonm = 45.56335266_wp
real(wp), parameter, public nmtoau = 1.0_wp/autonm
real(wp), parameter, public amutokg = 1.660539040e-27_wp
real(wp), parameter, public kgtoamu = 1.0_wp/amutokg
real(wp), parameter, public metokg = 9.10938356e-31_wp
real(wp), parameter, public kgtome = 1.0_wp/metokg
real(wp), parameter, public amutoau = amutokg*kgtome
real(wp), parameter, public autoamu = kgtoamu*metokg
real(wp), parameter, public fstoau = 41.3413733365614_wp
real(wp), parameter, public autofs = 1.0_wp/fstoau
real(wp), parameter, public autoc = 1.6021766208e-19_wp
real(wp), parameter, public ctoau = 1.0_wp/autoc
real(wp), parameter, public autod = autoc * lightspeed * autoaa**2 * fstoau * 1.0e+16_wp
real(wp), parameter, public dtoau = 1.0_wp/autod
real(wp), parameter, public autokmmol = 1.7770969e+6_wp
Variable Documentation
aatoau
real(wp), parameter, public xtb_mctc_convert::aatoau = 1.0_wp/autoaa
Definition at line 25 of file convert.f90.
    real(wp),public,parameter :: aatoau = 1.0_wp/autoaa
Referenced by xtb_solv_cm5::calc_cm5(), xtb_solv_gbsa::init::initborn(), xtb_metadynamic::load_rmsdbias(), xtb_dynamic::md(), xtb_modelhessian::mh_lindh_stretch(), xtb_modelhessian::mh_swart_stretch(), xtb_modef::modefollow(), xtb_solv_model::paramtomodel(), xtb_propertyoutput::print_thermo_sthr_ts(), rdatomnumber(), rdsdf(), rdxyz(), xtb_embedding::read_pcem(), xtb_readin::readlog(), xtb_io_reader_turbomole::readmoleculecoord(), xtb_io_reader_genformat::readmoleculegenformat(), xtb_io_reader_ctfile::readmoleculemolfile(), xtb_io_reader_pdb::readmoleculepdb(), xtb_io_reader_vasp::readmoleculevasp(), xtb_io_reader_xyz::readmoleculexyz(), xtb_extern_mopac::runmopac(), xtb_screening::screen(), xtb_constrain_param::set_constr(), xtb_setmod::set_gbsa(), xtb_constrain_param::set_scan(), xtb_scc_core::shellpoly(), test_coulomb_gaussian_pbc3d(), test_coulomb_gfn1_pbc3d(), test_coulomb_gfn2_pbc3d(), test_coulomb_point_pbc3d(), test_dftd3_pbc3d_latticepoints(), test_dftd3_pbc3d_neighbourlist(), test_dftd3_pbc3d_threebody_latp(), test_dftd3_pbc3d_threebody_neighs(), test_dftd4_pbc3d_latticepoints(), test_dftd4_pbc3d_neighbourlist(), test_dftd4_pbc3d_threebody_latp(), test_dftd4_pbc3d_threebody_neighs(), test_eeq_model_salt(), test_gfn2salt_api(), test_latticepoint_pbc3d(), test_ncoord_pbc3d_latticepoints(), test_ncoord_pbc3d_neighbourlist(), test_peeq_api_srb(), test_repulsion_pbc3d(), and xtb_thermo::thermodyn().
amutoau
real(wp), parameter, public xtb_mctc_convert::amutoau = amutokg*kgtome
Definition at line 51 of file convert.f90.
    real(wp),public,parameter :: amutoau = amutokg*kgtome
Referenced by xtb_dynamic::md(), xtb_modef::modefollow(), molecular_mass(), moments_of_inertia(), xtb_hessian::numhess(), and test_axis().
amutokg
real(wp), parameter, public xtb_mctc_convert::amutokg = 1.660539040e-27_wp
Definition at line 47 of file convert.f90.
    real(wp),public,parameter :: amutokg = 1.660539040e-27_wp
Referenced by xtb_dynamic::md().
autoaa
real(wp), parameter, public xtb_mctc_convert::autoaa = 0.52917726_wp
Definition at line 24 of file convert.f90.
    real(wp),public,parameter :: autoaa = 0.52917726_wp
Referenced by abcdisp(), xtb_qmdff::abdamp(), xtb_optimizer::ancopt(), xtb_biaspath::bias_path(), constrallbonds(), xtb_relaxation_engine::fire(), xtb_fixparam::fix_info(), gdisp(), geosum(), xtb_kopt::get_rmsd(), xtb_solv_model::info(), xtb_shake::init_shake(), xtb_relaxation_engine::l_ancopt(), xtb_local::local(), xtb_scanparam::pot_info(), print_distances(), print_elem_dist(), xtb_propertyoutput::print_gbsa_info(), print_moments(), print_pbcsum(), xtb_disp_dftd4::prmolc6(), xtb_extern_mopac::runmopac(), xtb_extern_orca::runorca(), xtb_constrain_param::set_constr(), xtb_constrain_param::set_wall(), xtb_splitparam::splitm(), xtb_setmod::write_set_constrain(), xtb_setmod::write_set_gbsa(), xtb_setmod::write_set_scan(), xtb_printout::writecosmofile(), xtb_io_writer_genformat::writemoleculegenformat(), xtb_io_writer_ctfile::writemoleculemolfile(), xtb_io_writer_pdb::writemoleculepdb(), xtb_io_writer_vasp::writemoleculevasp(), and xtb_io_writer_xyz::writemoleculexyz().
autoamu
real(wp), parameter, public xtb_mctc_convert::autoamu = kgtoamu*metokg
Definition at line 52 of file convert.f90.
    real(wp),public,parameter :: autoamu = kgtoamu*metokg
Referenced by print_moments(), xtb_prog_info::xtbinfo(), xtb_prog_main::xtbmain(), and xtb_prog_thermo::xtbthermo().
autoc
real(wp), parameter, public xtb_mctc_convert::autoc = 1.6021766208e-19_wp
Definition at line 57 of file convert.f90.
    real(wp),public,parameter :: autoc = 1.6021766208e-19_wp
autod
real(wp), parameter, public xtb_mctc_convert::autod = autoc * lightspeed * autoaa**2 * fstoau * 1.0e+16_wp
Definition at line 60 of file convert.f90.
    real(wp),public,parameter :: autod = autoc * lightspeed * autoaa**2 * fstoau * 1.0e+16_wp
Referenced by xtb_aespot::molmom(), and xtb_propertyoutput::print_dipole().
autoev
real(wp), parameter, public xtb_mctc_convert::autoev = 27.21138505_wp
Definition at line 27 of file convert.f90.
    real(wp),public,parameter :: autoev = 27.21138505_wp
Referenced by xtb_scc_core::addanisotropich1(), xtb_scc_core::buildisotropich1(), xtb_scc_core::fermismear(), fodenmak(), xtb_hlex::hlex(), xtb_local::local(), xtb_scc_core::scc(), and xtb_prog_main::xtbmain().
autofs
real(wp), parameter, public xtb_mctc_convert::autofs = 1.0_wp/fstoau
Definition at line 55 of file convert.f90.
    real(wp),public,parameter :: autofs = 1.0_wp/fstoau
Referenced by xtb_relaxation_engine::fire(), and xtb_relaxation_engine::inertial_relax().
autokcal
real(wp), parameter, public xtb_mctc_convert::autokcal = 627.50947428_wp
Definition at line 30 of file convert.f90.
    real(wp),public,parameter :: autokcal = 627.50947428_wp
Referenced by abcdisp(), xtb_optimizer::ancopt(), xtb_biaspath::bias_path(), xtb_relaxation_engine::fire(), gdisp(), xtb_solv_model::info(), xtb_relaxation_engine::l_ancopt(), xtb_dynamic::md(), xtb_modef::modefollow(), xtb_thermo::oldthermo(), xtb_propertyoutput::print_thermo_sthr_ts(), xtb_screening::screen(), and xtb_thermo::thermodyn().
autokj
real(wp), parameter, public xtb_mctc_convert::autokj = 2625.49964038_wp
Definition at line 33 of file convert.f90.
    real(wp),public,parameter :: autokj = 2625.49964038_wp
Referenced by xtb_optimizer::ancopt(), xtb_relaxation_engine::fire(), xtb_relaxation_engine::l_ancopt(), xtb_thermo::lnqrot(), and xtb_thermo::oldthermo().
autokmmol
real(wp), parameter, public xtb_mctc_convert::autokmmol = 1.7770969e+6_wp
Definition at line 63 of file convert.f90.
    real(wp),public,parameter :: autokmmol = 1.7770969e+6_wp
Referenced by xtb_hessian::numhess().
autonm
real(wp), parameter, public xtb_mctc_convert::autonm = 45.56335266_wp
Definition at line 41 of file convert.f90.
    real(wp),public,parameter :: autonm = 45.56335266_wp
autorcm
real(wp), parameter, public xtb_mctc_convert::autorcm = 219474.63067_wp
Definition at line 36 of file convert.f90.
    real(wp),public,parameter :: autorcm = 219474.63067_wp
Referenced by xtb_modef::modefollow(), xtb_hessian::numhess(), xtb_thermo::oldthermo(), print_moments(), xtb_propertyoutput::print_thermo_sthr_lnq(), xtb_propertyoutput::print_thermo_sthr_ts(), test_axis(), test_thermo_calc(), and xtb_prog_thermo::xtbthermo().
autowav
real(wp), parameter, public xtb_mctc_convert::autowav = autorcm
Definition at line 37 of file convert.f90.
    real(wp),public,parameter :: autowav = autorcm
ctoau
real(wp), parameter, public xtb_mctc_convert::ctoau = 1.0_wp/autoc
Definition at line 58 of file convert.f90.
    real(wp),public,parameter :: ctoau = 1.0_wp/autoc
dtoau
real(wp), parameter, public xtb_mctc_convert::dtoau = 1.0_wp/autod
Definition at line 61 of file convert.f90.
    real(wp),public,parameter :: dtoau = 1.0_wp/autod
Referenced by xtb_extern_mopac::runmopac().
evtoau
real(wp), parameter, public xtb_mctc_convert::evtoau = 1.0_wp/autoev
Definition at line 28 of file convert.f90.
    real(wp),public,parameter :: evtoau = 1.0_wp/autoev
Referenced by xtb_scc_core::addanisotropich1(), xtb_xtb_hamiltonian::build_dsdqh0(), xtb_xtb_hamiltonian_gpu::build_dsdqh0_gpu(), xtb_xtb_hamiltonian::build_dsdqh0_noreset(), xtb_scc_core::buildisotropich1(), xtb_peeq::ccm_build_dsh0(), xtb_scc_core::electro(), xtb_embedding::electro_pcem(), xtb_api_results::getorbitaleigenvalues_api(), xtb_hlex::hlex(), xtb_propertyoutput::main_cube(), xtb_propertyoutput::main_property(), xtb_peeq::pbc_build_dsh0(), xtb_peeq::peeq(), xtb_propertyoutput::print_fod_population(), print_orbital_eigenvalues(), xtb_scc_core::scc(), xtb_scf::scf(), write_line(), and write_tm_mos().
fstoau
real(wp), parameter, public xtb_mctc_convert::fstoau = 41.3413733365614_wp
Definition at line 54 of file convert.f90.
    real(wp),public,parameter :: fstoau = 41.3413733365614_wp
Referenced by xtb_relaxation_engine::fire(), and xtb_dynamic::md().
kcaltoau
real(wp), parameter, public xtb_mctc_convert::kcaltoau = 1.0_wp/autokcal
Definition at line 31 of file convert.f90.
    real(wp),public,parameter :: kcaltoau = 1.0_wp/autokcal
Referenced by xtb_thermo::oldthermo(), xtb_solv_model::paramtomodel(), xtb_extern_mopac::runmopac(), and xtb_thermo::thermodyn().
kgtoamu
real(wp), parameter, public xtb_mctc_convert::kgtoamu = 1.0_wp/amutokg
Definition at line 48 of file convert.f90.
    real(wp),public,parameter :: kgtoamu = 1.0_wp/amutokg
kgtome
real(wp), parameter, public xtb_mctc_convert::kgtome = 1.0_wp/metokg
Definition at line 50 of file convert.f90.
    real(wp),public,parameter :: kgtome  = 1.0_wp/metokg
Referenced by xtb_propertyoutput::print_thermo_sthr_ts(), and xtb_thermo::thermodyn().
kjtoau
real(wp), parameter, public xtb_mctc_convert::kjtoau = 1.0_wp/autokj
Definition at line 34 of file convert.f90.
    real(wp),public,parameter :: kjtoau = 1.0_wp/autokj
metokg
real(wp), parameter, public xtb_mctc_convert::metokg = 9.10938356e-31_wp
Definition at line 49 of file convert.f90.
    real(wp),public,parameter :: metokg  = 9.10938356e-31_wp
Referenced by print_pbcsum().
nmtoau
real(wp), parameter, public xtb_mctc_convert::nmtoau = 1.0_wp/autonm
Definition at line 42 of file convert.f90.
    real(wp),public,parameter :: nmtoau = 1.0_wp/autonm
rcmtoau
real(wp), parameter, public xtb_mctc_convert::rcmtoau = 1.0_wp/autorcm
Definition at line 38 of file convert.f90.
    real(wp),public,parameter :: rcmtoau = 1.0_wp/autorcm
Referenced by xtb_thermo::oldthermo(), xtb_propertyoutput::print_thermo(), xtb_propertyoutput::print_thermo_sthr_ts(), test_thermo_calc(), and xtb_thermo::thermodyn().
wavtoau
real(wp), parameter, public xtb_mctc_convert::wavtoau = 1.0_wp/autowav
Definition at line 39 of file convert.f90.
    real(wp),public,parameter :: wavtoau = 1.0_wp/autowav