My Project: xtb_prog_topology Module Reference
xtb_prog_topology Module Reference
Force field topology generator.
Functions/Subroutines
subroutine, public xtbtopology (env, argParser)
Main program of the topology submodule.
subroutine parsearguments (env, args, param)
Parse command line arguments.
subroutine topologyheader (unit)
Header for this submodule.
subroutine topologyhelp (unit)
Detailed Description
Force field topology generator.
Function/Subroutine Documentation
parsearguments()
subroutine xtb_prog_topology::parsearguments (type(tenvironment) env, type(targparser) args, character(len=:), intent(out), allocatable param) private
Parse command line arguments.
Parameters
env Calculation environment
args Command line argument parser
[out] param Parameter file
Definition at line 134 of file topology.f90.
    use xtb_mctc_global, only : persistentenv
    character(len=*), parameter :: source = "prog_topology_parseArguments"
    type(TEnvironment) :: env
    type(TArgParser) :: args
    character(len=:), allocatable, intent(out) :: param
    integer :: nFlags
    character(len=:), allocatable :: flag, sec
    logical :: exist
    nflags = args%countFlags()
    call args%nextFlag(flag)
    do while(allocated(flag))
       if (len(flag) > 2 .and. flag(1:1) == '-' .and. flag(1:2) /= '--') then
          call env%warning("the use of '"//flag//"' is discouraged, "// &
             & "please use '-"//flag//"' next time", source)
          flag = '-'//flag
       end if
       select case(flag)
       case default
          call env%warning("Unknown option '"//flag//"' provided", source)
       case('--help', '-h')
          call topologyhelp(env%unit)
          call terminate(0)
       case('--param')
          call args%nextArg(param)
          if (.not.allocated(param)) then
             call env%error("Missing argument for parameter file", source)
          else
             inquire(exist=exist, file=param)
             if (.not.exist) then
                call env%error("Parameter file does not exist", source)
             end if
          end if
       case('--namespace')
          call args%nextArg(persistentenv%io%namespace)
          if (.not.allocated(persistentenv%io%namespace)) then
             call env%error("Namespace argument is missing", source)
          end if
       end select
       call args%nextFlag(flag)
    end do
References xtb_mctc_global::persistentenv, terminate(), and topologyhelp().
Referenced by xtbtopology().
topologyheader()
subroutine xtb_prog_topology::topologyheader (integer, intent(in) unit)
Header for this submodule.
Parameters
[in] unit IO unit
Definition at line 194 of file topology.f90.
    integer, intent(in) :: unit
    write(unit,'(a)') &
       "      -----------------------------------------------------------",&
       "     |                   =====================                   |",&
       "     |                      x t b - t o p o                      |",&
       "     |                   =====================                   |",&
       "     |                         S. Grimme                         |",&
       "     |          Mulliken Center for Theoretical Chemistry        |",&
       "     |                    University of Bonn                     |",&
       "      -----------------------------------------------------------",""
    write(unit,'(3x,"*",*(1x,a))') &
       & "xtb-topology version", version, "compiled by", author, "on", date
    write(unit,'(a)')
Referenced by xtbtopology().
topologyhelp()
subroutine xtb_prog_topology::topologyhelp (integer, intent(in) unit) private
Parameters
[in] unit IO unit
Definition at line 215 of file topology.f90.
    integer, intent(in) :: unit
    write(unit, '(a)') &
    "Usage: xtb topology [options] <geometry>", &
    "",&
    "<geometry> may be provided as any valid input to xtb", &
    "",&
    "Options",&
    "",&
    "   --namespace STRING   Set a namespace for the calculation",&
    "",&
    "   --param FILE         Use alternative parameter file for the generator",&
    "",&
    "More information can be obtained at https://xtb-docs.readthedocs.io/",&
    ""
Referenced by parsearguments(), and xtbtopology().
xtbtopology()
subroutine, public xtb_prog_topology::xtbtopology (type(tenvironment), intent(inout) env, type(targparser), intent(inout) argParser)
Main program of the topology submodule.
Parameters
[in,out] env Calculation environment
[in,out] argparser Commandline argument parser
Molecular structure data
Force field instance
Determine the file type for processing in the reader
Generate the reader by connecting the file to the instance
Process the file to obtain the molecular structure data
Close the file, we are done with it here
Print an informative banner
print current time
Definition at line 44 of file topology.f90.
    character(len=*), parameter :: source = "prog_topology"
    type(TEnvironment), intent(inout) :: env
    type(TArgParser), intent(inout) :: argParser
    type(TMolecule) :: mol
    type(TGFFCalculator) :: calc
    type(TReader) :: reader
    character(len=:), allocatable :: file, param, line
    integer :: nFiles, ftype, unit, err
    logical :: exist
    call parsearguments(env, argparser, param)
    nfiles = argparser%countFiles()
    if (nfiles == 0) then
       call env%error("No input file given, so there is nothing to do", source)
       call topologyhelp(env%unit)
    end if
    if (nfiles > 1) then
       call env%error("Multiple input files present, aborting", source)
    end if
    call env%checkpoint("Command line argument parsing failed")
    call argparser%nextFile(file)
    ftype = getfiletype(file)
    call reader%open(file)
    call readmolecule(env, mol, reader%unit, ftype)
    call reader%close
    call open_file(unit, '.CHRG', 'r')
    if (unit /= -1) then
       call getline(unit, line, iostat=err)
       if (err /= 0) then
          call env%error('.CHRG is empty!', source)
       else
          call set_chrg(env, line)
          mol%chrg = ichrg
          call close_file(unit)
       end if
    end if
    call env%checkpoint("Could not read geometry from '"//file//"'")
    call topologyheader(env%unit)
    call prdate('S')
    if (.not.allocated(param)) then
       call rdpath(env%xtbpath, '.param_gfnff.xtb', param, exist)
       if (.not.exist) param = '.param_gfnff.xtb'
    end if
    call newgffcalculator(env, mol, calc, param, .false.)
    call env%checkpoint("Could not setup force field topology")
    write(env%unit,'(a)')
    write(env%unit,'(72("-"))')
    call stop_timing_run
    call stop_timing(1)
    call prdate('E')
    write(env%unit,'(72("-"))')
    call prtiming(1,'total')
    write(env%unit,'(a)')
    call terminate(0)
References close_file(), xtb_mctc_systools::getline(), xtb_setparam::ichrg, xtb_main_setup::newgffcalculator(), open_file(), parsearguments(), xtb_mctc_timings::prdate(), xtb_mctc_timings::prtiming(), xtb_mctc_systools::rdpath(), xtb_io_reader::readmolecule(), xtb_setmod::set_chrg(), xtb_mctc_timings::stop_timing(), xtb_mctc_timings::stop_timing_run(), terminate(), topologyheader(), and topologyhelp().
Referenced by xtb_prog_primary().