My Project: xtb_mctc_strings Module Reference
xtb_mctc_strings Module Reference
Data Types
interface value
Generic operator for converting a number string to a number. Calling syntax is 'call value(numstring,number,ios)' where 'numstring' is a number string and 'number' is a real number or an integer (single or double precision).
interface writenum
Generic interface for writing a number to a string. The number is left justified in the string. The calling syntax is 'call writenum(number,string,format)' where 'number' is a real number or an integer, 'string' is a character string containing the result, and 'format' is the format desired, e.g., 'e15.6' or 'i5'.
interface writeq
Generic interface equating a name to a numerical value. The calling syntax is 'call writeq(unit,name,value,format)' where unit is the integer output unit number, 'name' is the variable name, 'value' is the real or integer value of the variable, and 'format' is the format of the value. The result written to the output unit has the form <name> = .
Functions/Subroutines
pure character(len=len(str)) function capitalize (str)
pure subroutine parse (str, delims, args, nargs)
Parses the string 'str' into arguments args(1), ..., args(nargs) based on the delimiters contained in the string 'delims'. Preceding a delimiter in 'str' by a backslash () makes this particular instance not a delimiter. The integer output variable nargs contains the number of arguments found.
pure subroutine compact (str)
Converts multiple spaces and tabs to single spaces; deletes control characters; removes initial spaces.
pure subroutine removesp (str)
Removes spaces, tabs, and control characters in string str.
pure subroutine, private value_dr (str, rnum, iostat)
Converts number string to a double precision real number.
pure subroutine, private value_sr (str, rnum, iostat)
Converts number string to a single precision real number.
pure subroutine, private value_di (str, inum, iostat)
Converts number string to a double precision integer value.
pure subroutine, private value_si (str, inum, iostat)
Converts number string to a single precision integer value.
pure subroutine shiftstr (str, n)
Shifts characters in in the string 'str' n positions (positive values denote a right shift and negative values denote a left shift). Characters that are shifted off the end are lost. Positions opened up by the shift are replaced by spaces.
pure subroutine insertstr (str, strins, loc)
Inserts the string 'strins' into the string 'str' at position 'loc'. Characters in 'str' starting at position 'loc' are shifted right to make room for the inserted string. Trailing spaces of 'strins' are removed prior to insertion.
pure subroutine delsubstr (str, substr)
Deletes first occurrence of substring 'substr' from string 'str' and shifts characters left to fill hole. Trailing spaces or blanks are not considered part of 'substr'.
pure subroutine delall (str, substr)
Deletes all occurrences of substring 'substr' from string 'str' and shifts characters left to fill holes.
character(len=len_trim(str)) function uppercase (str)
convert string to upper case
character(len=len_trim(str)) function lowercase (str)
convert string to lower case
subroutine readline (nunitr, line, ios)
Reads line from unit=nunitr, ignoring blank lines and deleting comments beginning with an exclamation point(!)
pure subroutine match (str, ipos, imatch, status)
Sets imatch to the position in string of the delimiter matching the delimiter in position ipos. Allowable delimiters are (), [], {}, <>.
pure subroutine, private write_dr (rnum, str, fmt)
Writes double precision real number rnum to string str using format fmt.
pure subroutine, private write_sr (rnum, str, fmt)
Writes single precision real number rnum to string str using format fmt.
pure subroutine, private write_di (inum, str, fmt)
Writes double precision integer inum to string str using format fmt.
pure subroutine, private write_si (inum, str, fmt)
Writes single precision integer inum to string str using format fmt.
pure subroutine trimzero (str)
Deletes nonsignificant trailing zeroes from number string str. If number string ends in a decimal point, one trailing zero is added.
subroutine, private writeq_dr (unit, namestr, value, fmt)
Writes a string of the form <name> = value to unit.
subroutine, private writeq_sr (unit, namestr, value, fmt)
Writes a string of the form <name> = value to unit.
subroutine, private writeq_di (unit, namestr, ivalue, fmt)
Writes a string of the form <name> = ivalue to unit.
subroutine, private writeq_si (unit, namestr, ivalue, fmt)
Writes a string of the form <name> = ivalue to unit.
logical function is_letter (ch)
Returns .true. if ch is a letter and .false. otherwise.
pure elemental logical function is_digit (ch)
Returns .true. if ch is a digit (0,1,...,9) and .false. otherwise.
pure subroutine split (str, delims, before, sep)
Routine finds the first instance of a character from 'delims' in the the string 'str'. The characters before the found delimiter are output in 'before'. The characters after the found delimiter are output in 'str'. The optional output character 'sep' contains the found delimiter. A delimiter in 'str' is treated like an ordinary character if it is preceded by a backslash (). If the backslash character is desired in 'str', then precede it with another backslash.
pure subroutine removebksl (str)
Removes backslash () characters. Double backslashes (\) are replaced by a single backslash.
Variables
integer, parameter, private kr4 = selected_real_kind(6, 37)
single precision real
integer, parameter, private kr8 = selected_real_kind(15, 307)
double precision real
integer, parameter, private ki4 = selected_int_kind(9)
single precision integer
integer, parameter, private ki8 = selected_int_kind(18)
double precision integer
integer, parameter, private kc4 = kr4
single precision complex
integer, parameter, private kc8 = kr8
double precision complex
Function/Subroutine Documentation
capitalize()
pure character(len=len(str)) function xtb_mctc_strings::capitalize (character(len=*), intent(in) str)
Definition at line 91 of file mctc_strings.f90.
 integer :: il,i
 character(len=*),intent(in) :: str
 character(len=len(str))     :: capitalize
 character(len=26),parameter :: cap = &
 &       'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
 character(len=26),parameter :: low = &
 &       'abcdefghijklmnopqrstuvwxyz'
 capitalize = str
 il = index(low, str(1:1))
 if (il.gt.0) capitalize(1:1) = cap(il:il)
 do i = 2, len_trim(str)
    il = index(cap, str(i:i))
    if (il.gt.0) capitalize(i:i) = low(il:il)
 enddo
compact()
pure subroutine xtb_mctc_strings::compact (character(len=*), intent(inout) str)
Converts multiple spaces and tabs to single spaces; deletes control characters; removes initial spaces.
Definition at line 149 of file mctc_strings.f90.
 character(len=*), intent(inout) :: str
 character(len=1) :: ch
 character(len=len_trim(str)) :: outstr
 integer :: lenstr,isp,k,i,ich
 str=adjustl(str)
 lenstr=len_trim(str)
 outstr=' '
 isp=0
 k=0
 do i=1,lenstr
   ch=str(i:i)
   ich=iachar(ch)
   select case(ich)
     case(9,32)     ! space or tab character
       if(isp==0) then
         k=k+1
         outstr(k:k)=' '
       end if
       isp=1
     case(33:)      ! not a space, quote, or control character
       k=k+1
       outstr(k:k)=ch
       isp=0
   end select
 end do
 str=adjustl(outstr)
Referenced by parse(), and split().
delall()
pure subroutine xtb_mctc_strings::delall (character(len=*), intent(inout) str, character(len=*), intent(in) substr)
Deletes all occurrences of substring 'substr' from string 'str' and shifts characters left to fill holes.
Definition at line 390 of file mctc_strings.f90.
 character(len=*), intent(inout) :: str
 character(len=*), intent(in) :: substr
 integer :: lensubstr
 integer :: ipos
 lensubstr=len_trim(substr)
 do
    ipos=index(str,substr)
    if(ipos == 0) exit
    if(ipos == 1) then
       str=str(lensubstr+1:)
    else
       str=str(:ipos-1)//str(ipos+lensubstr:)
    end if
 end do
 return
delsubstr()
pure subroutine xtb_mctc_strings::delsubstr (character(len=*), intent(inout) str, character(len=*), intent(in) substr)
Deletes first occurrence of substring 'substr' from string 'str' and shifts characters left to fill hole. Trailing spaces or blanks are not considered part of 'substr'.
Definition at line 367 of file mctc_strings.f90.
 character(len=*), intent(inout) :: str
 character(len=*), intent(in) :: substr
 integer :: lensubstr,ipos
 lensubstr=len_trim(substr)
 ipos=index(str,substr)
 if(ipos==0) return
 if(ipos == 1) then
    str=str(lensubstr+1:)
 else
    str=str(:ipos-1)//str(ipos+lensubstr:)
 end if
 return
insertstr()
pure subroutine xtb_mctc_strings::insertstr (character(len=*), intent(inout) str, character(len=*), intent(in) strins, integer, intent(in) loc)
Inserts the string 'strins' into the string 'str' at position 'loc'. Characters in 'str' starting at position 'loc' are shifted right to make room for the inserted string. Trailing spaces of 'strins' are removed prior to insertion.
Definition at line 343 of file mctc_strings.f90.
 character(len=*), intent(inout) :: str
 character(len=*), intent(in) :: strins
 character(len=len(str)) :: tempstr
 integer, intent(in) :: loc
 integer :: lenstrins
 lenstrins=len_trim(strins)
 tempstr=str(loc:)
 call shiftstr(tempstr,lenstrins)
 tempstr(1:lenstrins)=strins(1:lenstrins)
 str(loc:)=tempstr
 return
References shiftstr().
is_digit()
pure elemental logical function xtb_mctc_strings::is_digit (character, intent(in) ch)
Returns .true. if ch is a digit (0,1,...,9) and .false. otherwise.
Definition at line 784 of file mctc_strings.f90.
 character, intent(in) :: ch
 logical :: res
 select case(ch)
 case('0':'9')
   res=.true.
 case default
   res=.false.
 end select
 return
References true().
Referenced by xtb_mctc_strings::value::value_dr().
is_letter()
logical function xtb_mctc_strings::is_letter (character ch)
Returns .true. if ch is a letter and .false. otherwise.
Definition at line 765 of file mctc_strings.f90.
 character :: ch
 logical :: res
 select case(ch)
 case('A':'Z','a':'z')
   res=.true.
 case default
   res=.false.
 end select
 return
References true().
lowercase()
character (len=len_trim(str)) function xtb_mctc_strings::lowercase (character (len=*) str)
convert string to lower case
Definition at line 453 of file mctc_strings.f90.
 character (len=*):: str
 character (len=len_trim(str)):: lcstr
 integer :: ilen,ioffset,iquote,i,iav,iqc
 ilen=len_trim(str)
 ioffset=iachar('A')-iachar('a')
 iquote=0
 lcstr=str
 do i=1,ilen
   iav=iachar(str(i:i))
   if(iquote==0 .and. (iav==34 .or.iav==39)) then
     iquote=1
     iqc=iav
     cycle
   end if
   if(iquote==1 .and. iav==iqc) then
     iquote=0
     cycle
   end if
   if (iquote==1) cycle
   if(iav >= iachar('A') .and. iav <= iachar('Z')) then
     lcstr(i:i)=achar(iav-ioffset)
   else
     lcstr(i:i)=str(i:i)
   end if
 end do
 return
Referenced by xtb_extern_orca::checkorca(), countfix(), xtb_solv_model::normalizesolventname(), rdfix(), read_elempar(), xtb_setmod::set_gfn(), and xtb_setmod::set_opt().
match()
pure subroutine xtb_mctc_strings::match (character(len=*), intent(in) str, integer, intent(in) ipos, integer, intent(out) imatch, integer, intent(out), optional status)
Sets imatch to the position in string of the delimiter matching the delimiter in position ipos. Allowable delimiters are (), [], {}, <>.
Definition at line 513 of file mctc_strings.f90.
 character(len=*), intent(in) :: str
 character :: delim1,delim2,ch
 integer, intent(out), optional :: status
 integer :: stat
 integer, intent(in) :: ipos
 integer, intent(out) :: imatch
 integer :: lenstr,idelim2,istart,inc,iend,isum,i
 lenstr=len_trim(str)
 delim1=str(ipos:ipos)
 select case(delim1)
    case('(')
       idelim2=iachar(delim1)+1
       istart=ipos+1
       iend=lenstr
       inc=1
    case(')')
       idelim2=iachar(delim1)-1
       istart=ipos-1
       iend=1
       inc=-1
    case('[','{','<')
       idelim2=iachar(delim1)+2
       istart=ipos+1
       iend=lenstr
       inc=1
    case(']','}','>')
       idelim2=iachar(delim1)-2
       istart=ipos-1
       iend=1
       inc=-1
    case default
       stat = 1
       if (present(status)) status = stat
       !write(*,*) delim1,' is not a valid delimiter'
       return
 end select
 if(istart < 1 .or. istart > lenstr) then
    stat = 2
    if (present(status)) status = stat
    !write(*,*) delim1,' has no matching delimiter'
    return
 end if
 delim2=achar(idelim2) ! matching delimiter
 isum=1
 do i=istart,iend,inc
    ch=str(i:i)
    if(ch /= delim1 .and. ch /= delim2) cycle
    if(ch == delim1) isum=isum+1
    if(ch == delim2) isum=isum-1
    if(isum == 0) exit
 end do
 if(isum /= 0) then
    stat = 3
    if (present(status)) status = stat
    !write(*,*) delim1,' has no matching delimiter'
    return
 end if
 imatch=i
 if (present(status)) status = 0
 return
parse()
pure subroutine xtb_mctc_strings::parse (character(len=*), intent(in) str, character(len=*), intent(in) delims, character(len=*), dimension(:), intent(out) args, integer, intent(out) nargs)
Parses the string 'str' into arguments args(1), ..., args(nargs) based on the delimiters contained in the string 'delims'. Preceding a delimiter in 'str' by a backslash () makes this particular instance not a delimiter. The integer output variable nargs contains the number of arguments found.
Definition at line 114 of file mctc_strings.f90.
 character(len=*), intent(in) :: str
 character(len=*), intent(in) :: delims
 character(len=len_trim(str)) :: tmpstr
 character(len=*), dimension(:), intent(out) :: args
 integer, intent(out) :: nargs
 integer :: na,i,lenstr,k
 tmpstr=str
 call compact(tmpstr)
 na=size(args)
 do i=1,na
   args(i)=' '
 end do
 nargs=0
 lenstr=len_trim(tmpstr)
 if(lenstr==0) return
 k=0
 do
    if(len_trim(tmpstr) == 0) exit
    nargs=nargs+1
    if (nargs > size(args)) exit
    call split(tmpstr,delims,args(nargs))
    call removebksl(args(nargs))
 end do
References compact(), removebksl(), and split().
Referenced by gfn_elempar(), read_pairpar(), xtb_embedding::read_pcem(), xtb_io_reader_genformat::readmoleculegenformat(), xtb_io_reader_vasp::readmoleculevasp(), xtb_constrain_param::set_constr(), xtb_constrain_param::set_fix(), xtb_constrain_param::set_freeze(), xtb_constrain_param::set_hess(), xtb_setmod::set_legacy(), xtb_constrain_param::set_metadyn(), xtb_constrain_param::set_path(), xtb_constrain_param::set_reactor(), xtb_constrain_param::set_scan(), xtb_constrain_param::set_split(), xtb_setmod::set_thermo(), and xtb_constrain_param::set_wall().
readline()
subroutine xtb_mctc_strings::readline (integer nunitr, character (len=*) line, integer ios)
Reads line from unit=nunitr, ignoring blank lines and deleting comments beginning with an exclamation point(!)
Definition at line 490 of file mctc_strings.f90.
 character (len=*):: line
 integer :: nunitr,ios,ipos
 do
   read(nunitr,'(a)', iostat=ios) line      ! read input line
   if(ios /= 0) return
   line=adjustl(line)
   ipos=index(line,'!')
   if(ipos == 1) cycle
   if(ipos /= 0) line=line(:ipos-1)
   if(len_trim(line) /= 0) exit
 end do
 return
removebksl()
pure subroutine xtb_mctc_strings::removebksl (character(len=*), intent(inout) str)
Removes backslash () characters. Double backslashes (\) are replaced by a single backslash.
Definition at line 874 of file mctc_strings.f90.
 character(len=*), intent(inout) :: str
 character(len=1) :: ch
 character(len=len_trim(str)) :: outstr
 integer :: lenstr,k,ibsl,i
 str=adjustl(str)
 lenstr=len_trim(str)
 outstr=' '
 k=0
 ibsl=0                        ! backslash initially inactive
 do i=1,lenstr
   ch=str(i:i)
   if(ibsl == 1) then          ! backslash active
    k=k+1
    outstr(k:k)=ch
    ibsl=0
    cycle
   end if
   if(ch == '\') then          ! backslash with backslash inactive
    ibsl=1
    cycle
   end if
   k=k+1
   outstr(k:k)=ch              ! non-backslash with backslash inactive
 end do
 str=adjustl(outstr)
Referenced by parse().
removesp()
pure subroutine xtb_mctc_strings::removesp (character(len=*), intent(inout) str)
Removes spaces, tabs, and control characters in string str.
Definition at line 193 of file mctc_strings.f90.
 character(len=*), intent(inout) :: str
 character(len=1) :: ch
 character(len=len_trim(str)) :: outstr
 integer :: lenstr,k,i,ich
 str=adjustl(str)
 lenstr=len_trim(str)
 outstr=' '
 k=0
 do i=1,lenstr
   ch=str(i:i)
   ich=iachar(ch)
   select case(ich)
     case(0:32)  ! space, tab, or control character
          cycle
     case(33:)
       k=k+1
       outstr(k:k)=ch
   end select
 end do
 str=adjustl(outstr)
shiftstr()
pure subroutine xtb_mctc_strings::shiftstr (character(len=*), intent(inout) str, integer, intent(in) n)
Shifts characters in in the string 'str' n positions (positive values denote a right shift and negative values denote a left shift). Characters that are shifted off the end are lost. Positions opened up by the shift are replaced by spaces.
Definition at line 318 of file mctc_strings.f90.
 character(len=*), intent(inout) :: str
 integer, intent(in) :: n
 integer :: lenstr,nabs
 lenstr=len(str)
 nabs=iabs(n)
 if(nabs>=lenstr) then
   str=repeat(' ',lenstr)
   return
 end if
 if(n<0) str=str(nabs+1:)//repeat(' ',nabs)  ! shift left
 if(n>0) str=repeat(' ',nabs)//str(:lenstr-nabs)  ! shift right
 return
Referenced by insertstr().
split()
pure subroutine xtb_mctc_strings::split (character(len=*), intent(inout) str, character(len=*), intent(in) delims, character(len=*), intent(out) before, character, intent(out), optional sep)
Routine finds the first instance of a character from 'delims' in the the string 'str'. The characters before the found delimiter are output in 'before'. The characters after the found delimiter are output in 'str'. The optional output character 'sep' contains the found delimiter. A delimiter in 'str' is treated like an ordinary character if it is preceded by a backslash (). If the backslash character is desired in 'str', then precede it with another backslash.
Definition at line 808 of file mctc_strings.f90.
 character(len=*), intent(inout) :: str
 character(len=*), intent(in) :: delims
 character(len=*), intent(out) :: before
 character, intent(out), optional :: sep
 logical :: pres
 character :: ch,cha
 integer :: lenstr,k,ibsl,i,ipos,iposa
 pres=present(sep)
 str=adjustl(str)
 call compact(str)
 lenstr=len_trim(str)
 if(lenstr == 0) return        ! string str is empty
 k=0
 ibsl=0                        ! backslash initially inactive
 before=' '
 do i=1,lenstr
    ch=str(i:i)
    if(ibsl == 1) then          ! backslash active
       k=k+1
       before(k:k)=ch
       ibsl=0
       cycle
    end if
    if(ch == '\') then          ! backslash with backslash inactive
       k=k+1
       before(k:k)=ch
       ibsl=1
       cycle
    end if
    ipos=index(delims,ch)
    if(ipos == 0) then          ! character is not a delimiter
       k=k+1
       before(k:k)=ch
       cycle
    end if
    if(ch /= ' ') then          ! character is a delimiter that is not a space
       str=str(i+1:)
       if(pres) sep=ch
       exit
    end if
    cha=str(i+1:i+1)            ! character is a space delimiter
    iposa=index(delims,cha)
    if(iposa > 0) then          ! next character is a delimiter
       str=str(i+2:)
       if(pres) sep=cha
       exit
    else
       str=str(i+1:)
       if(pres) sep=ch
       exit
    end if
 end do
 if(i >= lenstr) str=''
 str=adjustl(str)              ! remove initial spaces
 return
References compact().
Referenced by parse().
trimzero()
pure subroutine xtb_mctc_strings::trimzero (character(len=*), intent(inout) str)
Deletes nonsignificant trailing zeroes from number string str. If number string ends in a decimal point, one trailing zero is added.
Definition at line 668 of file mctc_strings.f90.
 character(len=*), intent(inout) :: str
 character :: ch
 character(len=10) :: exp
 integer :: ipos,i,lstr
 ipos=scan(str,'eE')
 if(ipos>0) then
    exp=str(ipos:)
    str=str(1:ipos-1)
 endif
 lstr=len_trim(str)
 do i=lstr,1,-1
    ch=str(i:i)
    if(ch=='0') cycle
    if(ch=='.') then
       str=str(1:i)//'0'
       if(ipos>0) str=trim(str)//trim(exp)
       exit
    endif
    str=str(1:i)
    exit
 end do
 if(ipos>0) str=trim(str)//trim(exp)
Referenced by xtb_mctc_strings::writeq::writeq_di(), xtb_mctc_strings::writeq::writeq_dr(), xtb_mctc_strings::writeq::writeq_si(), and xtb_mctc_strings::writeq::writeq_sr().
uppercase()
character (len=len_trim(str)) function xtb_mctc_strings::uppercase (character (len=*) str)
convert string to upper case
Definition at line 416 of file mctc_strings.f90.
 character (len=*):: str
 character (len=len_trim(str)):: ucstr
 integer :: ilen,ioffset,iquote,i,iav,iqc
 ilen=len_trim(str)
 ioffset=iachar('A')-iachar('a')
 iquote=0
 ucstr=str
 do i=1,ilen
   iav=iachar(str(i:i))
   if(iquote==0 .and. (iav==34 .or.iav==39)) then
     iquote=1
     iqc=iav
     cycle
   end if
   if(iquote==1 .and. iav==iqc) then
     iquote=0
     cycle
   end if
   if (iquote==1) cycle
   if(iav >= iachar('a') .and. iav <= iachar('z')) then
     ucstr(i:i)=achar(iav+ioffset)
   else
     ucstr(i:i)=str(i:i)
   end if
 end do
 return
value_di()
pure subroutine, private xtb_mctc_strings::value_di (character(len=*), intent(in) str, integer(ki8), intent(out) inum, integer, intent(out), optional iostat) private
Converts number string to a double precision integer value.
Definition at line 270 of file mctc_strings.f90.
 character(len=*), intent(in) ::str
 integer(ki8), intent(out) :: inum
 real(kr8) :: rnum
 integer, intent(out), optional :: iostat
 integer :: ios
 call value_dr(str,rnum,ios)
 if (present(iostat)) iostat = ios
 if(abs(rnum)>huge(inum)) then
    if (present(iostat)) iostat = 15
    return
 end if
 inum=nint(rnum,ki8)
value_dr()
pure subroutine, private xtb_mctc_strings::value_dr (character(len=*), intent(in) str, real(kr8), intent(out) rnum, integer, intent(out), optional iostat) private
Converts number string to a double precision real number.
Definition at line 225 of file mctc_strings.f90.
 character(len=*), intent(in) ::str
 real(kr8), intent(out) ::rnum
 integer, intent(out), optional :: iostat
 integer :: ilen,ipos,ios
 ilen=len_trim(str)
 ipos=scan(str,'Ee')
 if(.not.is_digit(str(ilen:ilen)) .and. ipos/=0) then
    if (present(iostat)) iostat=3
    return
 end if
 read(str,*,iostat=ios) rnum
 if (present(iostat)) iostat = ios
Referenced by xtb_mctc_strings::value::value_di(), xtb_mctc_strings::value::value_si(), and xtb_mctc_strings::value::value_sr().
value_si()
pure subroutine, private xtb_mctc_strings::value_si (character(len=*), intent(in) str, integer(ki4), intent(out) inum, integer, intent(out), optional iostat) private
Converts number string to a single precision integer value.
Definition at line 293 of file mctc_strings.f90.
 character(len=*), intent(in) ::str
 integer(ki4), intent(out) :: inum
 real(kr8) :: rnum
 integer, intent(out), optional :: iostat
 integer :: ios
 call value_dr(str,rnum,ios)
 if (present(iostat)) iostat = ios
 if(abs(rnum)>huge(inum)) then
    if (present(iostat)) iostat=15
    return
 end if
 inum=nint(rnum,ki4)
value_sr()
pure subroutine, private xtb_mctc_strings::value_sr (character(len=*), intent(in) str, real(kr4), intent(out) rnum, integer, intent(out), optional iostat) private
Converts number string to a single precision real number.
Definition at line 247 of file mctc_strings.f90.
 character(len=*), intent(in) ::str
 real(kr4), intent(out) :: rnum
 real(kr8) :: rnumd
 integer, intent(out), optional :: iostat
 integer :: ios
 call value_dr(str,rnumd,ios)
 if (present(iostat)) iostat = ios
 if( abs(rnumd) > huge(rnum) ) then
    if (present(iostat)) iostat = 15
    return
 end if
 if( abs(rnumd) < tiny(rnum) ) rnum=0.0_kr4
 rnum=rnumd
write_di()
pure subroutine, private xtb_mctc_strings::write_di (integer(ki8), intent(in) inum, character(len=*), intent(out) str, character(len=*), intent(in), optional fmt) private
Writes double precision integer inum to string str using format fmt.
Definition at line 626 of file mctc_strings.f90.
 integer(ki8), intent(in) :: inum
 character(len=*), intent(out) :: str
 character(len=*), intent(in), optional :: fmt
 character(len=80) :: formt
 if (present(fmt)) then
    formt='('//trim(fmt)//')'
 else
    formt='(g0)'
 endif
 write(str,formt) inum
 str=adjustl(str)
write_dr()
pure subroutine, private xtb_mctc_strings::write_dr (real(kr8), intent(in) rnum, character(len=*), intent(out) str, character(len=*), intent(in), optional fmt) private
Writes double precision real number rnum to string str using format fmt.
Definition at line 586 of file mctc_strings.f90.
 real(kr8), intent(in) :: rnum
 character(len=*), intent(out) :: str
 character(len=*), intent(in), optional :: fmt
 character(len=80) :: formt
 if (present(fmt)) then
    formt='('//trim(fmt)//')'
 else
    formt='(g0)'
 endif
 write(str,formt) rnum
 str=adjustl(str)
write_si()
pure subroutine, private xtb_mctc_strings::write_si (integer(ki4), intent(in) inum, character(len=*), intent(out) str, character(len=*), intent(in), optional fmt) private
Writes single precision integer inum to string str using format fmt.
Definition at line 646 of file mctc_strings.f90.
 integer(ki4), intent(in) :: inum
 character(len=*), intent(out) :: str
 character(len=*), intent(in), optional :: fmt
 character(len=80) :: formt
 if (present(fmt)) then
    formt='('//trim(fmt)//')'
 else
    formt='(g0)'
 endif
 write(str,formt) inum
 str=adjustl(str)
write_sr()
pure subroutine, private xtb_mctc_strings::write_sr (real(kr4), intent(in) rnum, character(len=*), intent(out) str, character(len=*), intent(in), optional fmt) private
Writes single precision real number rnum to string str using format fmt.
Definition at line 606 of file mctc_strings.f90.
 real(kr4), intent(in) :: rnum
 character(len=*), intent(out) :: str
 character(len=*), intent(in), optional :: fmt
 character(len=80) :: formt
 if (present(fmt)) then
    formt='('//trim(fmt)//')'
 else
    formt='(g0)'
 endif
 write(str,formt) rnum
 str=adjustl(str)
writeq_di()
subroutine, private xtb_mctc_strings::writeq_di (integer unit, character(len=*) namestr, integer(ki8) ivalue, character(len=*) fmt) private
Writes a string of the form <name> = ivalue to unit.
Definition at line 733 of file mctc_strings.f90.
 integer(ki8) :: ivalue
 integer :: unit
 character(len=*) :: namestr,fmt
 character(len=32) :: tempstr
 call writenum(ivalue,tempstr,fmt)
 call trimzero(tempstr)
 write(unit,*) trim(namestr)//' = '//trim(tempstr)
writeq_dr()
subroutine, private xtb_mctc_strings::writeq_dr (integer unit, character(len=*) namestr, real(kr8) value, character(len=*) fmt) private
Writes a string of the form <name> = value to unit.
Definition at line 700 of file mctc_strings.f90.
 real(kr8) :: value
 integer :: unit
 character(len=*) :: namestr,fmt
 character(len=32) :: tempstr
 call writenum(value,tempstr,fmt)
 call trimzero(tempstr)
 write(unit,*) trim(namestr)//' = '//trim(tempstr)
writeq_si()
subroutine, private xtb_mctc_strings::writeq_si (integer unit, character(len=*) namestr, integer(ki4) ivalue, character(len=*) fmt) private
Writes a string of the form <name> = ivalue to unit.
Definition at line 749 of file mctc_strings.f90.
 integer(ki4) :: ivalue
 integer :: unit
 character(len=*) :: namestr,fmt
 character(len=32) :: tempstr
 call writenum(ivalue,tempstr,fmt)
 call trimzero(tempstr)
 write(unit,*) trim(namestr)//' = '//trim(tempstr)
writeq_sr()
subroutine, private xtb_mctc_strings::writeq_sr (integer unit, character(len=*) namestr, real(kr4) value, character(len=*) fmt) private
Writes a string of the form <name> = value to unit.
Definition at line 716 of file mctc_strings.f90.
 real(kr4) :: value
 integer :: unit
 character(len=*) :: namestr,fmt
 character(len=32) :: tempstr
 call writenum(value,tempstr,fmt)
 call trimzero(tempstr)
 write(unit,*) trim(namestr)//' = '//trim(tempstr)
Variable Documentation
kc4
integer, parameter, private xtb_mctc_strings::kc4 = kr4 private
single precision complex
Definition at line 37 of file mctc_strings.f90.
 integer, parameter :: kc4 = kr4
kc8
integer, parameter, private xtb_mctc_strings::kc8 = kr8 private
double precision complex
Definition at line 39 of file mctc_strings.f90.
 integer, parameter :: kc8 = kr8
ki4
integer, parameter, private xtb_mctc_strings::ki4 = selected_int_kind(9) private
single precision integer
Definition at line 31 of file mctc_strings.f90.
 integer, parameter :: ki4 = selected_int_kind(9)
Referenced by xtb_mctc_strings::value::value_si().
ki8
integer, parameter, private xtb_mctc_strings::ki8 = selected_int_kind(18) private
double precision integer
Definition at line 33 of file mctc_strings.f90.
 integer, parameter :: ki8 = selected_int_kind(18)
Referenced by xtb_mctc_strings::value::value_di().
kr4
integer, parameter, private xtb_mctc_strings::kr4 = selected_real_kind(6, 37) private
single precision real
Definition at line 25 of file mctc_strings.f90.
 integer, parameter :: kr4 = selected_real_kind(6,37)
kr8
integer, parameter, private xtb_mctc_strings::kr8 = selected_real_kind(15, 307) private
double precision real
Definition at line 27 of file mctc_strings.f90.
 integer, parameter :: kr8 = selected_real_kind(15,307)