My Project: xtb_mctc_systools Module Reference
xtb_mctc_systools Module Reference
Functions/Subroutines
subroutine getline (unit, line, iostat)
subroutine rdpath (path, arg, fname, ex)
subroutine rdarg (i, arg, iostat)
subroutine rdvar (name, var, iostat)
Variables
character, parameter space = ' '
character, parameter pathdel = ':'
character, parameter pathsep = '/'
Function/Subroutine Documentation
getline()
subroutine xtb_mctc_systools::getline (integer, intent(in) unit, character(len=:), intent(out), allocatable line, integer, intent(out), optional iostat)
Definition at line 32 of file systools.F90.
    use, intrinsic :: iso_fortran_env, only : iostat_eor
    integer,intent(in) :: unit
    character(len=:),allocatable,intent(out) :: line
    integer,intent(out),optional :: iostat
    integer,parameter  :: buffersize=144
    character(len=buffersize) :: buffer
    integer :: size
    integer :: err
    line = ''
    do
       read(unit,'(a)',advance='no',iostat=err,size=size)  &
       &    buffer
       if (err.gt.0) then
          if (present(iostat)) iostat=err
          return ! an error occurred
       endif
       line = line // buffer(:size)
       if (err.lt.0) then
          if (err.eq.iostat_eor) err = 0
          if (present(iostat)) iostat=err
          return
       endif
    enddo
Referenced by xtb_metadynamic::load_rmsdbias(), xtb_optimizer::load_turbomole_log(), xtb_readin::mirror_line(), next_line(), rdsdf(), xtb_optimizer::read_hessian(), xtb_readin::readlog(), xtb_io_reader_ctfile::readmoleculemolfile(), xtb_io_reader_pdb::readmoleculepdb(), xtb_io_reader_ctfile::readmoleculesdf(), xtb_io_reader_vasp::readmoleculevasp(), xtb_extern_mopac::runmopac(), xtb_readin::strip_line(), xtb_prog_main::xtbmain(), and xtb_prog_topology::xtbtopology().
rdarg()
subroutine xtb_mctc_systools::rdarg (integer, intent(in) i, character(len=:), intent(out), allocatable arg, integer, intent(out), optional iostat)
Definition at line 98 of file systools.F90.
    integer,intent(in) :: i
    character(len=:),allocatable,intent(out) :: arg
    integer,intent(out),optional :: iostat
    integer :: l,err
    if (allocated(arg)) deallocate(arg)
    call get_command_argument(i,length=l,status=err)
    if (err.ne.0) then
       if (present(iostat)) then
          iostat = err
          return
       else
          call raise('E','Command argument corrupted')
       endif
    endif
    allocate( character(len=l) :: arg, stat=err )
    if (err.ne.0) then
       if (present(iostat)) then
          iostat = err
          return
       else
          call raise('E','could not be allocated')
       endif
    endif
    call get_command_argument(i,arg,status=err)
    if (err.ne.0) then
       if (present(iostat)) then
          iostat = err
          return
       else
          call raise('E','Command argument corrupted')
       endif
    endif
    if (present(iostat)) iostat=0
References raise().
Referenced by xtb_type_environment::init::initenvironment(), and peeq_tester().
rdpath()
subroutine xtb_mctc_systools::rdpath (character(len=*), intent(in) path, character(len=*), intent(in) arg, character(len=:), intent(out), allocatable fname, logical, intent(out), optional ex)
Definition at line 61 of file systools.F90.
    implicit none
    character(len=*),intent(in)  :: arg
    character(len=*),intent(in)  :: path
    character(len=:),allocatable,intent(out) :: fname
    logical,intent(out),optional :: ex
 !* temporary variables
    character(len=:),allocatable :: scratch1
    character(len=:),allocatable :: scratch2
    character(len=:),allocatable :: fpath
    logical :: exist
    integer :: i
    scratch1 = path
    do
       i = index(scratch1,pathdel)
       if (i.eq.0) then
          scratch2 = scratch1
       else
          scratch2 = scratch1(:i-1)
          scratch1 = scratch1(i+1:)
       endif
       fpath = scratch2//pathsep//arg
       inquire(file=fpath,exist=exist)
       if (exist) exit
 !     print*,fpath,space,scratch1,exist
       if (i.eq.0) exit
    enddo
 !  print*,fpath,exist
    if (exist) fname = fpath
    if (present(ex)) ex = exist
References pathdel, and pathsep.
Referenced by xtb_extern_mopac::checkmopac(), xtb_extern_orca::checkorca(), xtb_solv_model::getparamfile(), xtb_api_calculator::loadgfn0xtb_api(), xtb_api_calculator::loadgfn1xtb_api(), xtb_api_calculator::loadgfn2xtb_api(), xtb_api_calculator::loadgfnff_api(), xtb_main_setup::newxtbcalculator(), test_gfn0_sp(), test_ipea_indole(), test_peeq_sp(), xtb_readin::xfind(), xtb_prog_main::xtbmain(), and xtb_prog_topology::xtbtopology().
rdvar()
subroutine xtb_mctc_systools::rdvar (character(len=*), intent(in) name, character(len=:), intent(out), allocatable var, integer, intent(out), optional iostat)
Definition at line 134 of file systools.F90.
    character(len=*),intent(in) :: name
    character(len=:),allocatable,intent(out) :: var
    integer,intent(out),optional :: iostat
    integer :: l,err
    if (allocated(var)) deallocate(var)
    call get_environment_variable(name,length=l,status=err)
    if (err.ne.0) then
       if (present(iostat)) then
          iostat = err
          return
       else
          call raise('E','System variable unassigned')
       endif
    endif
    allocate( character(len=l) :: var, stat=err )
    if (err.ne.0) then
       if (present(iostat)) then
          iostat = err
          return
       else
          call raise('E','could not be allocated')
       endif
    endif
    ! If the environment variable has not been set, l=0, and the
    ! following get_environment_variable call crashes.
    if (l.gt.0) then
       call get_environment_variable(name,var,status=err)
       if (err.ne.0) then
          if (present(iostat)) then
             iostat = err
             return
          else
             call raise('E','System variable corrupted')
          endif
       endif
    endif
    if (present(iostat)) iostat=0
References raise().
Referenced by xtb_extern_mopac::checkmopac(), xtb_extern_orca::checkorca(), xtb_type_environment::init::initenvironment(), xtb_printout::setup_summary(), and xtb_prog_main::xtbmain().
Variable Documentation
pathdel
character, parameter xtb_mctc_systools::pathdel = ':'
Definition at line 26 of file systools.F90.
    character,parameter :: pathdel = ':'
Referenced by rdpath().
pathsep
character, parameter xtb_mctc_systools::pathsep = '/'
Definition at line 27 of file systools.F90.
    character,parameter :: pathsep = '/'
Referenced by rdpath().
space
character, parameter xtb_mctc_systools::space = ' '
Definition at line 21 of file systools.F90.
    character,parameter :: space = ' '