My Project: xtb_prog_info Module Reference
xtb_prog_info Module Reference
Information on the current input geometry.
Functions/Subroutines
subroutine, public xtbinfo (env, argParser)
Main program of the info submodule.
subroutine runheader (unit, file, iRun, nRun, nAtom)
Print a header for each new run.
subroutine infoheader (unit)
Header for this submodule.
Detailed Description
Information on the current input geometry.
Function/Subroutine Documentation
infoheader()
subroutine xtb_prog_info::infoheader (integer, intent(in) unit) private
Header for this submodule.
Parameters
[in] unit IO unit
Definition at line 190 of file info.f90.
    integer, intent(in) :: unit
    write(unit,'(a)') &
       "      -----------------------------------------------------------",&
       "     |                   =====================                   |",&
       "     |                      x t b - i n f o                      |",&
       "     |                   =====================                   |",&
       "     |                         S. Ehlert                         |",&
       "     |          Mulliken Center for Theoretical Chemistry        |",&
       "     |                    University of Bonn                     |",&
       "      -----------------------------------------------------------",""
    write(unit,'(3x,"*",*(1x,a))') &
       & "xtb version", version, "compiled by", author, "on", date
    write(unit,'(a)')
Referenced by xtbinfo().
runheader()
subroutine xtb_prog_info::runheader (integer, intent(in) unit, character(len=*), intent(in) file, integer, intent(in) iRun, integer, intent(in) nRun, integer, intent(in) nAtom) private
Print a header for each new run.
Parameters
[in] unit IO unit
[in] file Read in file name
[in] irun Current run
[in] nrun Number of total runs
[in] natom Number of atoms in this structure
Definition at line 161 of file info.f90.
    integer, intent(in) :: unit
    character(len=*), intent(in) :: file
    integer, intent(in) :: iRun
    integer, intent(in) :: nRun
    integer, intent(in) :: nAtom
    if (nrun > 1) then
       write(unit, '(72("~"))')
       write(unit, '(1x, "Run:", t66, i0, "/", i0)') irun, nrun
       write(unit, '(72("~"))')
    end if
    write(unit, '(1x, "Input:", 1x, a)') file
    write(unit, '(1x, "Number of atoms:", 1x, i0, /)') natom
Referenced by xtbinfo().
xtbinfo()
subroutine, public xtb_prog_info::xtbinfo (type(tenvironment), intent(inout) env, type(targparser), intent(inout) argParser)
Main program of the info submodule.
Parameters
[in,out] env Calculation environment
[in,out] argparser Commandline argument parser
Molecular structure data
Reader for input files
Identity map for unique species in molecular structure
Read in file name
File type
Current run
Number of total runs
Signal from environment to terminate the program
Check for very close distances
Determine the number of runs from the files in the command line
No input files are an error
Print an informative banner
Save status of each run
Execute runs in order
Pop the first file from the parser
Determine the file type for processing in the reader
Generate the reader by connecting the file to the instance
Process the file to obtain the molecular structure data
Close the file, we are done with it here
Print an informative header for this run
make sure the geometry summery does not error on splitparam globals
Intialize and print the identity map
Check for very small distances in the input geometry
Geometry summary
Definition at line 42 of file info.f90.
    character(len=*), parameter :: source = "prog_info"
    type(TEnvironment), intent(inout) :: env
    type(TArgParser), intent(inout) :: argParser
    type(TMolecule) :: mol
    type(TReader) :: reader
    type(TIdentityMap) :: idMap
    character(len=:), allocatable :: file
    integer :: ftype
    integer :: iRun
    integer :: nRun
    logical, allocatable :: exitRun(:)
    logical :: coldFusion
    nrun = argparser%countFiles()
    if (nrun == 0) then
       call env%terminate("No geometry input provided")
    end if
    call infoheader(env%unit)
    allocate(exitrun(nrun))
    do irun = 1, nrun
       call argparser%nextFile(file)
       ftype = getfiletype(file)
       call reader%open(file)
       call readmolecule(env, mol, reader%unit, ftype)
       call reader%close
       call runheader(env%unit, file, irun, nrun, len(mol))
       call env%check(exitrun(irun))
       if (exitrun(irun)) then
          call env%show('Could not read geometry due to')
          cycle
       end if
       atmass = getatomicmass(mol%at) * autoamu ! from splitparam.f90
       call init(idmap, mol)
       call generic_header(env%unit, 'Identifiers', 49, 10)
       write(env%unit, '(a)')
       call idmap%writeInfo(env%unit)
       write(env%unit, '(a)')
       call check_cold_fusion(env, mol, coldfusion)
       if (coldfusion) then
          call env%error("Some atoms in the geometry are very close", source)
       else
          call main_geometry(env%unit, mol)
       end if
       call env%check(exitrun(irun))
       call env%show('Following warnings occurred with this input')
    end do
    if (nrun > 1) then
       write(env%unit, '(72("~"))')
       write(env%unit, '(1x, a, 1x, i0, 1x, a)') "Processed", nrun, "individual inputs"
       if (count(exitrun) > 0) then
          write(env%unit, '(1x, i0, "/", i0, 1x, a, "(", f5.1, "%)")') &
             & count(exitrun), nrun, "inputs failed info check", &
             & real(count(exitrun)*100, wp)/real(nrun, wp)
       end if
       write(env%unit, '(72("~"), /)')
    end if
    if (any(exitrun)) then
       call terminate(1)
    else
       call terminate(0)
    end if
References xtb_splitparam::atmass, xtb_mctc_convert::autoamu, check_cold_fusion(), generic_header(), infoheader(), main_geometry(), xtb_io_reader::readmolecule(), runheader(), terminate(), and xtb_mctc_accuracy::wp.
Referenced by xtb_prog_primary().