My Project: xtb_constrain_param Module Reference
xtb_constrain_param Module Reference
$constrain
Data Types
interface handlerInterface
Functions/Subroutines
subroutine read_userdata (fname, env, mol)
subroutine rdsetbl (env, handler, line, id, nat, at, idMap, xyz, err)
subroutine rdblock (env, handler, line, id, nat, at, idMap, xyz, err)
subroutine set_fix (env, key, val, nat, at, idMap, xyz)
subroutine set_constr (env, key, val, nat, at, idMap, xyz)
subroutine set_scan (env, key, val, nat, at, idMap, xyz)
subroutine set_wall (env, key, val, nat, at, idMap, xyz)
subroutine set_split (env, key, val, nat, at, idMap, xyz)
subroutine set_hess (env, key, val, nat, at, idMap, xyz)
subroutine set_reactor (env, key, val, nat, at, idMap, xyz)
subroutine set_path (env, key, val, nat, at, idMap, xyz)
subroutine set_metadyn (env, key, val, nat, at, idMap, xyz)
subroutine set_freeze (env, key, val, nat, at, idMap, xyz)
subroutine set_legacy (env, key, val, nat, at, idMap, xyz)
Variables
character, parameter, private flag = '$'
character, parameter, private colon = ':'
character, parameter, private space = ' '
character, parameter, private equal = '='
character, parameter, private hash = '#'
character, parameter, private comma = ','
character, parameter, private semicolon = ';'
character, parameter, private dot = '.'
character(len= *), parameter, private flag_end = flag//'end'
integer, parameter, private p_str_length = 48
integer, parameter, private p_arg_length = 24
Detailed Description
$constrain
this part is read by setparam.f90
force constant=<real> all bonds=<bool> all angles=<bool> all torsions=<bool>
this part is read in this module
distance: ,<j>, auto distance: ,<j>, <real> angle: ,<j>,<k>, auto angle: ,<j>,<k>, <real> dihedral: ,<j>,<k>,<l>,auto dihedral: ,<j>,<k>,<l>,<real> center: <int>,<real> $fix force constant=<real> spring exponent=<int> atoms:
fragment1:
sphere: auto,all sphere: auto,
<real>,all sphere: <real>,
auto,all ellipsoid: auto,
<real>,<real>,<real>,all ellipsoid: <real>,<real>,<real>,
...
$end
Function/Subroutine Documentation
rdblock()
subroutine xtb_constrain_param::rdblock (type(tenvironment), intent(inout) env, procedure(handlerinterface) handler, character(len=:), intent(out), allocatable line, integer, intent(in) id, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(out) err)
Definition at line 231 of file constrain_param.f90.
    implicit none
    character(len=*), parameter :: source = 'userdata_rdblock'
    type(TEnvironment), intent(inout) :: env
    integer,intent(in) :: id
    procedure(handlerInterface) :: handler
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    integer,intent(out) :: err
    character(len=:),allocatable,intent(out) :: line
    character(len=:),allocatable :: key
    character(len=:),allocatable :: val
    integer :: ie
    logical :: exitRun
    do
       call getline(id,line,err)
       if (is_iostat_end(err)) exit
       if (index(line,flag).ne.0) exit
       if (verbose) write(env%unit,'("->",1x,a)') line
       ! find the first colon
       ie = index(line,colon)
       if ((line.eq.'').or.(ie.eq.0)) cycle
       key = trim(line(:ie-1))
       val = trim(adjustl(line(ie+1:)))
       call handler(env,key,val,nat,at,idmap,xyz)
       call env%check(exitrun)
       if (exitrun) then
          call env%error("handler could not process input", source)
          return
       end if
    enddo
References colon, flag, and xtb_setparam::verbose.
Referenced by read_userdata().
rdsetbl()
subroutine xtb_constrain_param::rdsetbl (type(tenvironment), intent(inout) env, procedure(handlerinterface) handler, character(len=:), intent(out), allocatable line, integer, intent(in) id, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(out) err)
Definition at line 194 of file constrain_param.f90.
    implicit none
    character(len=*), parameter :: source = 'userdata_rdsetbl'
    type(TEnvironment), intent(inout) :: env
    integer,intent(in) :: id
    procedure(handlerInterface) :: handler
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    integer,intent(out) :: err
    character(len=:),allocatable,intent(out) :: line
    character(len=:),allocatable :: key
    character(len=:),allocatable :: val
    integer :: ie
    logical :: exitRun
    do
       call getline(id,line,err)
       if (is_iostat_end(err)) exit
       if (index(line,flag).ne.0) exit
       if (verbose) write(env%unit,'("->",1x,a)') line
       ! find the first colon
       ie = index(line,space)
       if ((line.eq.'').or.(ie.eq.0)) cycle
       key = trim(line(:ie-1))
       val = trim(adjustl(line(ie+1:)))
       call handler(env,key,val,nat,at,idmap,xyz)
       call env%check(exitrun)
       if (exitrun) then
          call env%error("handler could not process input", source)
          return
       end if
    enddo
References flag, space, and xtb_setparam::verbose.
Referenced by read_userdata().
read_userdata()
subroutine xtb_constrain_param::read_userdata (character(len=*), intent(in) fname, type(tenvironment), intent(inout) env, type(tmolecule), intent(inout) mol)
Definition at line 103 of file constrain_param.f90.
    use xtb_readin, only : find_new_name
    use xtb_scanparam
    implicit none
    character(len=*), parameter :: source = 'userdata_read'
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(inout) :: mol
    character(len=*),intent(in)  :: fname
    character(len=:),allocatable :: line
    character(len=:),allocatable :: key
    character(len=:),allocatable :: val
    character(len=:),allocatable :: newname
    type(TIdentityMap) :: idMap
    integer :: i
    integer :: id
    integer :: ic
    integer :: ie
    integer :: err
    logical :: exist
    if (verbose) then
       write(env%unit,'(72("$"))')
       write(env%unit,'(1x,"CONSTRAINTS & SCANS: DEBUG SECTION")')
       write(env%unit,'(72("$"))')
    endif
    call open_file(id,fname,'r')
    if (id.eq.-1) then
       call env%warning("could not find '"//fname//"'",source)
       return
    endif
    rewind(id) ! not sure if this is necessary
    call init(idmap, mol)
    call idmap%writeInfo(env%unit)
 !  read first line before the readloop starts, I have to do this
 !  to avoid using backspace on id (dammit Turbomole format)
    call getline(id,line,err)
    readflags: do
       !  check if there is a $ in the *first* column
       if (index(line,flag).eq.1) then
          select case(line(2:))
          case('fix'      )
             if (verbose) write(env%unit,'(">",1x,a)') line(2:)
             call rdblock(env,set_fix,    line,id,mol%n,mol%at,idmap,mol%xyz,err)
          case('split'    )
             if (verbose) write(env%unit,'(">",1x,a)') line(2:)
             call rdblock(env,set_split,  line,id,mol%n,mol%at,idmap,mol%xyz,err)
          case('constrain')
             if (verbose) write(env%unit,'(">",1x,a)') line(2:)
             if (allocated(potset%xyz)) then
                call rdblock(env,set_constr, line,id,mol%n,mol%at,idmap,potset%xyz,err)
             else
                call rdblock(env,set_constr, line,id,mol%n,mol%at,idmap,mol%xyz,err)
             endif
          case('scan'     )
             if (verbose) write(env%unit,'(">",1x,a)') line(2:)
             call rdblock(env,set_scan,   line,id,mol%n,mol%at,idmap,mol%xyz,err)
          case('wall'     )
             if (verbose) write(env%unit,'(">",1x,a)') line(2:)
             call rdblock(env,set_wall,   line,id,mol%n,mol%at,idmap,mol%xyz,err)
          case('metadyn'  )
             if (verbose) write(env%unit,'(">",1x,a)') line(2:)
             call rdblock(env,set_metadyn,line,id,mol%n,mol%at,idmap,mol%xyz,err)
          case('hess'     )
             if (verbose) write(env%unit,'(">",1x,a)') line(2:)
             call rdblock(env,set_hess,   line,id,mol%n,mol%at,idmap,mol%xyz,err)
          case('path'     )
             if (verbose) write(env%unit,'(">",1x,a)') line(2:)
             call rdblock(env,set_path,   line,id,mol%n,mol%at,idmap,mol%xyz,err)
          case('reactor'  )
             if (verbose) write(env%unit,'(">",1x,a)') line(2:)
             call rdblock(env,set_reactor,line,id,mol%n,mol%at,idmap,mol%xyz,err)
          case('set'      ); call rdsetbl(env,set_legacy,line,id,mol%n,mol%at,idmap,mol%xyz,err)
          case default ! unknown keyword -> ignore, we don't raise them
             call getline(id,line,err)
          end select
       else ! not a keyword -> ignore
          call getline(id,line,err)
       endif
    !  check for end of file, which I will tolerate as alternative to $end
       if (is_iostat_end(err)) exit readflags
 !     if (index(line,flag_end).ne.0) exit readflags ! compatibility reasons
    enddo readflags
    if (verbose) write(env%unit,'(72("$"))')
    call close_file(id)
References close_file(), xtb_readin::find_new_name(), flag, open_file(), xtb_scanparam::potset, rdblock(), rdsetbl(), set_constr(), set_fix(), set_hess(), set_legacy(), set_metadyn(), set_path(), set_reactor(), set_scan(), set_split(), set_wall(), and xtb_setparam::verbose.
Referenced by xtb_prog_main::xtbmain().
set_constr()
subroutine xtb_constrain_param::set_constr (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 382 of file constrain_param.f90.
    use xtb_mctc_constants
    use xtb_mctc_convert
    use xtb_type_atomlist
    use xtb_scanparam
    use xtb_splitparam
    implicit none
    character(len=*), parameter :: source = 'userdata_constr'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    type(TAtomList) :: atl
    integer  :: iat
    integer  :: ioffset
    integer  :: idum
    real(wp) :: ddum
    integer  :: nlist
    integer, allocatable :: list(:)
    logical  :: ldum
    integer  :: i,j,k,l
    real(wp) :: phi,dist,ra(3),rb(3)
    real(wp),external :: valijkl
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    call atl%resize(nat)
    call parse(val,comma,argv,narg)
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    select case(key)
    case default ! ignore, don't even think about raising them
    case('elements')
       call atl%new
       do idum = 1, narg
          ! get element by symbol
          if (idmap%has(argv(idum))) then
             call idmap%get(list, argv(idum))
             if (allocated(list)) then
                call atl%add(list)
             else
                call env%warning("Unknown element: '"//trim(argv(idum))//"'",source)
                cycle
             end if
          else
             ldum = getvalue(env,trim(argv(idum)),iat)
             if (.not.ldum) cycle ! skip garbage input
             ! check for unreasonable input
             if (iat > 0) then
                call atl%add(at.eq.iat)
             else
                call env%warning("Unknown element: '"//trim(argv(idum))//"'",source)
                cycle
             endif
          endif
       enddo
       if (potset%pos%n > 0) call atl%add(potset%pos%atoms(:potset%pos%n))
       call atl%to_list(list)
       potset%pos%atoms = list
       potset%pos%n = size(list)
    case('atoms')
       call atl%new(val)
       if (atl%get_error()) then
          call env%warning('something is wrong in the fixing list',source)
          return
       endif
       if (potset%pos%n > 0) call atl%add(potset%pos%atoms(:potset%pos%n))
       call atl%to_list(list)
       potset%pos%atoms = list
       potset%pos%n = size(list)
    case('DISTANCE')
       if (narg.lt.3 .or. narg.gt.4) then
          call env%error('not enough arguments to constrain a distance',source)
          return
       endif
       ioffset = 2*potset%dist%n
       potset%dist%n = potset%dist%n+1
    !  part 1: get the constrained atoms
       do i = 1, 2
          if (getvalue(env,trim(argv(i)),idum)) then
             potset%dist%atoms(ioffset+i) = idum
          else
             call env%warning("Something went wrong in set_constr_ 'distance'. (1)",source)
             potset%dist%n = potset%dist%n-1 ! remove invalid contrain
             return
          endif
       enddo
    !  part 2: get the distance between those atoms
       i = potset%dist%atoms(ioffset+1)
       j = potset%dist%atoms(ioffset+2)
       dist = sqrt(sum((xyz(:,i)-xyz(:,j))**2))
       if (trim(argv(3)).eq.'auto') then
          potset%dist%val(potset%dist%n) = dist
       else
          if (getvalue(env,trim(argv(3)),ddum)) then
             potset%dist%val(potset%dist%n) = ddum * aatoau
          else
             call env%warning("Something went wrong in set_constr_ 'distance'. (2)",source)
             potset%dist%n = potset%dist%n-1 ! remove invalid contrain
             return
          endif
       endif
       if (narg.eq.4) then
          if (getvalue(env,trim(argv(4)),idum)) then
             if (idum < 2 .or. mod(idum, 2).ne.0) then
                call env%warning("Invalid spring exponent given", source)
                potset%dist%n = potset%dist%n-1 ! remove invalid contrain
                return
             end if
             potset%dist%expo(potset%dist%n) = real(idum, wp)
          else
             call env%warning("Something went wrong in set_constr_ 'distance'. (3)",source)
             potset%dist%n = potset%dist%n-1 ! remove invalid contrain
             return
          end if
          write(env%unit,'("constraining bond",2(1x,i0),1x,"to",'//&
             '1x,f12.7,1x,", actual value:",1x,f12.7,1x,"",1x,"with expo",1x,i0)') &
             i,j, potset%dist%val(potset%dist%n)*autoaa, dist*autoaa, &
             nint(potset%dist%expo(potset%dist%n))
       else
          write(env%unit,'("constraining bond",2(1x,i0),1x,"to",'//&
             '1x,f12.7,1x,", actual value:",1x,f12.7,1x,"")') &
             i,j, potset%dist%val(potset%dist%n)*autoaa, dist*autoaa
       end if
    case('ANGLE')
       if (narg.ne.4) then
          call env%error('not enough arguments to constrain an angle',source)
          return
       endif
       ioffset = 3*potset%angle%n
       potset%angle%n = potset%angle%n+1
    !  part 1: get the constrained atoms
       do i = 1, narg-1
          if (getvalue(env,trim(argv(i)),idum)) then
             potset%angle%atoms(ioffset+i) = idum
          else
             call env%warning("Something went wrong in set_constr_ 'angle'. (1)",source)
             potset%angle%n = potset%angle%n-1 ! remove invalid contrain
             return
          endif
       enddo
    !  part 2: get the angle between the constrained atoms
       i = potset%angle%atoms(ioffset+1)
       j = potset%angle%atoms(ioffset+2)
       k = potset%angle%atoms(ioffset+3)
       call bangl(xyz,i,j,k,phi)
       if (trim(argv(narg)).eq.'auto') then
          potset%angle%val(potset%angle%n) = phi
       else
          if (getvalue(env,trim(argv(narg)),ddum)) then
             potset%angle%val(potset%angle%n) = pi/180.0_wp * ddum
          else
             call env%warning("Something went wrong in set_constr_ 'angle'. (2)",source)
             potset%angle%n = potset%angle%n-1 ! remove invalid contrain
             return
          endif
       endif
    case('DIHEDRAL')
       if (narg.ne.5) then
          call env%error('not enough arguments to constrain a dihedral',source)
          return
       endif
       ioffset = 4*potset%dihedral%n
       potset%dihedral%n = potset%dihedral%n+1
       if (nconstr.gt.maxconstr) then ! double check this
          call env%error('This should never happen! Let somebody check set_constr',source)
          return
       end if
    !  part 1: get the constrained atoms
       do i = 1, narg-1
          if (getvalue(env,trim(argv(i)),idum)) then
             potset%dihedral%atoms(ioffset+i) = idum
          else
             call env%warning("Something went wrong in set_constr_ 'dihedral'. (1)",source)
             potset%dihedral%n = potset%dihedral%n-1 ! remove invalid contrain
             return
          endif
       enddo
    !  part 2: get the angle between the constrained atoms
       i = potset%dihedral%atoms(ioffset+1)
       j = potset%dihedral%atoms(ioffset+2)
       k = potset%dihedral%atoms(ioffset+3)
       l = potset%dihedral%atoms(ioffset+4)
       phi=valijkl(nat,xyz,i,j,k,l)
       if (trim(argv(narg)).eq.'auto') then
          potset%dihedral%val(potset%dihedral%n) = phi
       else
          if (getvalue(env,trim(argv(narg)),ddum)) then
             potset%dihedral%val(potset%dihedral%n) = pi/180.0_wp * ddum
          else
             call env%warning("Something went wrong in set_constr_ 'dihedral'. (2)",source)
             potset%dihedral%n = potset%dihedral%n-1 ! remove invalid contrain
             return
          endif
       endif
    case('distance')
       if (narg.ne.3) then
          call env%error('not enough arguments to constrain a distance',source)
          return
       endif
       nconstr = nconstr+1
       if (nconstr.gt.maxconstr) then ! double check this
          call env%error('This should never happen! Let somebody check set_constr',source)
          return
       end if
    !  part 1: get the constrained atoms
       do i = 1, narg-1
          if (getvalue(env,trim(argv(i)),idum)) then
             atconstr(i,nconstr) = idum
          else
             call env%warning("Something went wrong in set_constr_ 'distance'. (1)",source)
             nconstr = nconstr-1 ! remove invalid contrain
             return
          endif
       enddo
    !  part 2: get the distance between those atoms
       i = atconstr(1,nconstr)
       j = atconstr(2,nconstr)
       dist = sqrt(sum((xyz(:,i)-xyz(:,j))**2))
       if (trim(argv(narg)).eq.'auto') then
          valconstr(nconstr) = dist
       else
          if (getvalue(env,trim(argv(narg)),ddum)) then
             valconstr(nconstr) = ddum * aatoau
          else
             call env%warning("Something went wrong in set_constr_ 'distance'. (2)",source)
             nconstr = nconstr-1 ! remove invalid contrain
             return
          endif
       endif
       write(env%unit,'("constraining bond",2(1x,i0),1x,"to",'//&
          '1x,f12.7,1x,", actual value:",1x,f12.7,1x,"")') &
          i,j, valconstr(nconstr)*autoaa, dist*autoaa
    case('angle')
       if (narg.ne.4) then
          call env%error('not enough arguments to constrain an angle',source)
          return
       endif
       nconstr = nconstr+1
       if (nconstr.gt.maxconstr) then ! double check this
          call env%error('This should never happen! Let somebody check set_constr',source)
          return
       end if
    !  part 1: get the constrained atoms
       do i = 1, narg-1
          if (getvalue(env,trim(argv(i)),idum)) then
             atconstr(i,nconstr) = idum
          else
             call env%warning("Something went wrong in set_constr_ 'angle'. (1)",source)
             nconstr = nconstr-1 ! remove invalid contrain
             return
          endif
       enddo
    !  part 2: get the angle between the constrained atoms
       i = atconstr(1,nconstr)
       j = atconstr(2,nconstr)
       k = atconstr(3,nconstr)
       call bangl(xyz,i,j,k,phi)
       if (trim(argv(narg)).eq.'auto') then
          valconstr(nconstr) = phi
       else
          if (getvalue(env,trim(argv(narg)),ddum)) then
             valconstr(nconstr) = pi/180.0_wp * ddum
          else
             call env%warning("Something went wrong in set_constr_ 'angle'. (2)",source)
             nconstr = nconstr-1 ! remove invalid contrain
             return
          endif
       endif
       write(env%unit,'("constraining angle",3(1x,i0),1x,"to",'//&
          '1x,f12.7,", actual value:",1x,f12.7,"")') &
          i,j,k,180.0_wp/pi * valconstr(nconstr),180.0_wp/pi * phi
    case('dihedral')
       if (narg.ne.5) then
          call env%error('not enough arguments to constrain a dihedral',source)
          return
       endif
       nconstr = nconstr+1
       if (nconstr.gt.maxconstr) then ! double check this
          call env%error('This should never happen! Let somebody check set_constr',source)
          return
       end if
    !  part 1: get the constrained atoms
       do i = 1, narg-1
          if (getvalue(env,trim(argv(i)),idum)) then
             atconstr(i,nconstr) = idum
          else
             call env%warning("Something went wrong in set_constr_ 'dihedral'. (1)",source)
             nconstr = nconstr-1 ! remove invalid contrain
             return
          endif
       enddo
    !  part 2: get the angle between the constrained atoms
       i = atconstr(1,nconstr)
       j = atconstr(2,nconstr)
       k = atconstr(3,nconstr)
       l = atconstr(4,nconstr)
       phi=valijkl(nat,xyz,i,j,k,l)
       if (trim(argv(narg)).eq.'auto') then
          valconstr(nconstr) = phi
       else
          if (getvalue(env,trim(argv(narg)),ddum)) then
             valconstr(nconstr) = pi/180.0_wp * ddum
          else
             call env%warning("Something went wrong in set_constr_ 'dihedral'. (2)",source)
             nconstr = nconstr-1 ! remove invalid contrain
             return
          endif
       endif
       write(env%unit,'("constraining angle",4(1x,i0),1x,"to",'//&
          '1x,f12.7,", actual value:",1x,f12.7,"")') &
          i,j,k,l,180.0_wp/pi * valconstr(nconstr),180.0_wp/pi * phi
    case('center')
       ! copied from molbld.f without modification (except for error handling)
       if (narg.ne.2) then
          call env%error('not enough argument to constrain center',source)
          return
       endif
       nconstr = nconstr+1
       atconstr(1,nconstr) = -2
       if (getvalue(env,trim(argv(2)),ddum)) then
          valconstr(nconstr) = ddum
       else
          call env%warning("Something went wrong in set_constr_ 'center'. (1)",source)
          nconstr = nconstr-1
          return
       endif
       if (getvalue(env,trim(argv(1)),idum)) then
          iatf1 = idum
       else
          call env%warning("Something went wrong in set_constr_ 'center'. (2)",source)
          nconstr = nconstr-1
          return
       endif
       massf1 = 0.0_wp
       do i = 1, iatf1
          massf1 = massf1 + atmass(i)
       enddo
    case('cma','cma interface')
       ! copied from molbld.f without modification (except for error handling)
       if (narg.ne.1) then
          call env%error('not enough argument to constrain cma',source)
          return
       endif
       if (key.eq.'cma interface') call cmaiface(nat,at,xyz)
       nconstr = nconstr+1
       atconstr(1,nconstr) = 0
       if (trim(argv(1)).eq.'auto') then
          massf1 = 0.0_wp
          massf2 = 0.0_wp
          do i = 1, nat
             if (splitlist(i).eq.1) then
                massf1 = massf1 + atmass(i)
             else
                massf2 = massf2 + atmass(i)
             endif
          enddo
          call cmafrag(nat,at,xyz,ra,rb)
          valconstr(nconstr) = rcma
          write(env%unit,'("constraining fragment CMA to initial R(Ang.)=",f8.3)')&
             valconstr(nconstr)*autoaa
       else
          if (getvalue(env,trim(argv(1)),ddum)) then
             valconstr(nconstr) = ddum*aatoau
          else
             call env%warning("Something went wrong in set_constr_ 'cma'.",source)
             nconstr = nconstr-1
             return
          endif
       endif
 !   case('x','y','z')
 !      idum = index('xyz',key)
    case('z')
       ! copied from molbld.f without modification (except for error handling)
       if (narg.ne.1) then
          call env%error('not enough argument to constrain z coordinate',source)
          return
       endif
       zconstr = 1
       nconstr = nconstr+1
       atconstr(1,nconstr) = -1
       if (getvalue(env,trim(argv(1)),ddum)) then
          valconstr(nconstr) = ddum*aatoau
       else
          call env%warning("Something went wrong in set_constr_ 'z'.",source)
          nconstr = nconstr-1
          return
       endif
       if (sum(abs(xyz(3,1:iatf1))).gt.1.d-3) then
          call env%warning('z-coordinates of fragment 1 must be 0!',source)
          nconstr = nconstr-1
          return
       endif
       write(env%unit,'("constraining fragment 2 to Z=0 plane at (Ang.)=",f8.3)') &
          valconstr(nconstr)*autoaa
    end select
References xtb_mctc_convert::aatoau, xtb_scanparam::atconstr, xtb_splitparam::atmass, xtb_mctc_convert::autoaa, bangl(), xtb_splitparam::cmafrag(), xtb_splitparam::cmaiface(), comma, xtb_splitparam::iatf1, xtb_splitparam::massf1, xtb_splitparam::massf2, xtb_scanparam::maxconstr, xtb_scanparam::nconstr, xtb_mctc_strings::parse(), xtb_mctc_constants::pi, xtb_scanparam::potset, xtb_splitparam::rcma, xtb_splitparam::splitlist, xtb_scanparam::valconstr, valijkl(), xtb_setparam::verbose, and xtb_scanparam::zconstr.
Referenced by read_userdata(), and set_scan().
set_fix()
subroutine xtb_constrain_param::set_fix (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 268 of file constrain_param.f90.
    use xtb_type_atomlist
    use xtb_fixparam
    use xtb_setparam
    implicit none
    character(len=*), parameter :: source = 'userdata_fix'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    type(TAtomList) :: atl
    integer  :: i
    integer  :: iat
    integer  :: idum
    integer  :: nlist
    integer, allocatable :: list(:)
    real(wp) :: ddum
    logical  :: ldum
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    call atl%resize(nat)
    call parse(val,comma,argv,narg)
 !  some debug xtb_printout
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    select case(key)
    case default ! ignore, don't even think about raising them
    case('elements')
       call atl%new
       do idum = 1, narg
          ! get element by symbol
          if (idmap%has(argv(idum))) then
             call idmap%get(list, argv(idum))
             if (allocated(list)) then
                call atl%add(list)
             else
                call env%warning("Unknown element: '"//trim(argv(idum))//"'",source)
                cycle
             end if
          else
             ldum = getvalue(env,trim(argv(idum)),iat)
             if (.not.ldum) cycle ! skip garbage input
             ! check for unreasonable input
             if (iat > 0) then
                call atl%add(at.eq.iat)
             else
                call env%warning("Unknown element: '"//trim(argv(idum))//"'",source)
                cycle
             endif
          endif
       enddo
       if (fixset%n > 0) call atl%add(fixset%atoms(:fixset%n))
       call atl%to_list(list)
       fixset%atoms = list
       fixset%n = size(list)
    case('atoms')
       call atl%new(val)
       if (atl%get_error()) then
          call env%warning('something is wrong in the fixing list',source)
          return
       endif
       if (fixset%n > 0) call atl%add(fixset%atoms(:fixset%n))
       call atl%to_list(list)
       fixset%atoms = list
       fixset%n = size(list)
    case('freeze')
       call atl%new(val)
       if (atl%get_error()) then
          call env%warning('something is wrong in the freezing list',source)
          return
       endif
       if (freezeset%n > 0) call atl%add(freezeset%atoms(:freezeset%n))
       call atl%to_list(list)
       freezeset%atoms = list
       freezeset%n = size(list)
    case('shake')
       allocate(list(nat*(nat+1)/2), source=0)
       if (mod(narg,2).ne.0) then
          call env%warning("could not read input for user defined shake!",source)
          return
       endif
          if (narg+shakeset%n > nat*(nat+1)/2) then
          call env%warning("too many SHAKE constraints!",source)
          return
       endif
       if (.not.shake_md) shake_md = .true.
       do idum = 1, narg
          if (getvalue(env,trim(argv(idum)),iat)) then
             if (iat.gt.nat) then
                call env%warning('Attempted constrain atom not present in molecule.',source)
                cycle
             endif
             shakeset%n = shakeset%n+1
             shakeset%atoms(shakeset%n) = iat
          else
             call env%warning("Something went wrong in set_fix_ 'shake'.",source)
             return ! you screwed it, let's get out of here
          endif
       enddo
    end select
References comma, xtb_fixparam::fixset, xtb_fixparam::freezeset, xtb_mctc_strings::parse(), xtb_setparam::shake_md, xtb_fixparam::shakeset, true(), and xtb_setparam::verbose.
Referenced by read_userdata(), and set_legacy().
set_freeze()
subroutine xtb_constrain_param::set_freeze (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 1418 of file constrain_param.f90.
    implicit none
    character(len=*), parameter :: source = 'userdata_freeze'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    integer  :: idum
    real(wp) :: ddum
    logical  :: ldum
    integer  :: list(nat),nlist
    integer  :: i,j
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    call parse(val,comma,argv,narg)
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    select case(key)
    case default ! ignore, don't even think about raising them
    case('hessf')
    case('hessa')
    end select
References comma, xtb_mctc_strings::parse(), and xtb_setparam::verbose.
set_hess()
subroutine xtb_constrain_param::set_hess (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 1124 of file constrain_param.f90.
    use xtb_splitparam
    implicit none
    character(len=*), parameter :: source = 'userdata_hess'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    integer  :: idum
    real(wp) :: ddum
    logical  :: ldum
    integer  :: i,j
    integer, allocatable :: list(:)
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    call parse(val,comma,argv,narg)
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    select case(key)
    case default ! ignore, don't even think about raising them
    case('element mass')
       if (mod(narg,2).ne.0) then
          call env%warning("Something went wrong in set_mass_ 'element'.",source)
       endif
       do i = 1, narg, 2
          j = i+1
          if (getvalue(env,trim(argv(j)),ddum)) then
             if (idmap%has(argv(i))) then
                call idmap%set(atmass, argv(i), ddum)
                write(env%unit,'(a,a,a,1x,g0)') &
                   "mass of elements '",trim(argv(i)),"' changed to", ddum
             else if (getvalue(env,trim(argv(i)),idum)) then
                where(at.eq.idum) atmass = ddum
                write(env%unit,'(a,i0,a,1x,g0)') &
                   "mass of elements with Z=",idum," changed to", ddum
             end if
          end if
       enddo
    case('modify mass','isotope')
       if (mod(narg,2).ne.0) then
          call env%warning("Something went wrong in set_mass_ 'modify'.",source)
       endif
       do i = 1, narg, 2
          j = i+1
          if (getvalue(env,trim(argv(i)),idum).and.&
              getvalue(env,trim(argv(j)),ddum)) then
             if (idum.gt.nat) then
                call env%warning('Attempted setting atom mass not present in system.',source)
                cycle
             endif
             atmass(idum) = ddum
             write(env%unit,'(a,1x,i0,1x,a,1x,g0)') &
                'mass of atom ',idum,' changed to',atmass(idum)
          endif
       enddo
    case('scale mass')
       if (mod(narg,2).ne.0) then
          call env%warning("Something went wrong in set_mass_ 'scale'.",source)
       endif
       do i = 1, narg, 2
          j = i+1
          if (getvalue(env,trim(argv(i)),idum).and.&
              getvalue(env,trim(argv(j)),ddum)) then
             if (idum.gt.nat) then
                call env%warning('Attempted scaling atom not present in system.',source)
                cycle
             endif
             atmass(idum) = atmass(idum)*ddum
             write(env%unit,'(a,1x,i0,1x,a,1x,g0)') &
                'mass of atom ',idum,' changed to',atmass(idum)
          endif
       enddo
    end select
References xtb_splitparam::atmass, comma, xtb_mctc_strings::parse(), and xtb_setparam::verbose.
Referenced by read_userdata().
set_legacy()
subroutine xtb_constrain_param::set_legacy (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 1452 of file constrain_param.f90.
    implicit none
    character(len=*), parameter :: source = 'userdata_legacy'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    integer  :: err
    integer  :: idum
    real(wp) :: ddum
    logical  :: ldum
    select case(key)
    case default ! complaining about unknown keywords should already be done
       continue  ! so we do nothing here
    case('hessf');       call set_fix(env,'freeze',val,nat,at,idmap,xyz)
 !   case('hessa');       call set_frozh('hessa',val)
    case('fragment1'); call set_split(env,'fragment1',val,nat,at,idmap,xyz)
    case('fragment2'); call set_split(env,'fragment1',val,nat,at,idmap,xyz)
    case('constrxyz'); call set_fix(env,'atoms',val,nat,at,idmap,xyz)
 !   case('constrainel')
 !   case('constrain')
 !   case('scan')
    case('ellips'); call set_wall(env,'ellipsoid',val,nat,at,idmap,xyz)
    case('sphere'); call set_wall(env,'sphere',val,nat,at,idmap,xyz)
    case('fix'); call set_fix(env,'atoms',val,nat,at,idmap,xyz)
    case('atomlist+'); call set_metadyn(env,'atoms',val,nat,at,idmap,xyz)
    end select
References set_fix(), set_metadyn(), set_split(), and set_wall().
Referenced by read_userdata().
set_metadyn()
subroutine xtb_constrain_param::set_metadyn (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 1303 of file constrain_param.f90.
    use xtb_type_atomlist
    use xtb_fixparam
    implicit none
    character(len=*), parameter :: source = 'userdata_metadyn'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    type(TAtomList) :: atl
    integer  :: idum
    real(wp) :: ddum
    logical  :: ldum
    integer  :: nlist
    integer, allocatable :: list(:)
    integer  :: i,j,iat
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    call parse(val,comma,argv,narg)
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    select case(key)
    case default ! ignore, don't even think about raising them
    case('bias atoms')
       call atl%new(val)
       if (atl%get_error()) then
          call env%warning('something is wrong in the metadynamic atom list',source)
          return
       endif
       if (rmsdset%nat > 0) call atl%add(rmsdset%atoms(:rmsdset%nat))
       call atl%to_list(list)
       rmsdset%atoms = list
       rmsdset%nat = size(list)
    case('bias elements')
       call atl%new
       do idum = 1, narg
          ! get element by symbol
          if (idmap%has(argv(idum))) then
             call idmap%get(list, argv(idum))
             if (allocated(list)) then
                call atl%add(list)
             else
                call env%warning("Unknown element: '"//trim(argv(idum))//"'",source)
                cycle
             end if
          else
             ldum = getvalue(env,trim(argv(idum)),iat)
             if (.not.ldum) cycle ! skip garbage input
             ! check for unreasonable input
             if (iat > 0) then
                call atl%add(at.eq.iat)
             else
                call env%warning("Unknown element: '"//trim(argv(idum))//"'",source)
                cycle
             endif
          endif
       enddo
       if (rmsdset%nat > 0) call atl%add(rmsdset%atoms(:rmsdset%nat))
       call atl%to_list(list)
       rmsdset%atoms = list
       rmsdset%nat = size(list)
    case('atoms')
       call atl%new(val)
       if (atl%get_error()) then
          call env%warning('something is wrong in the metadynamic atom list',source)
          return
       endif
       if (metaset%nat > 0) call atl%add(metaset%atoms(:metaset%nat))
       call atl%to_list(list)
       metaset%atoms = list
       metaset%nat = size(list)
    case('modify factor')
       if (mod(narg,2).ne.0) then
          call env%warning("Something went wrong in set_metadyn_ 'modify'.",source)
       endif
       do i = 1, narg, 2
          j = i+1
          if (getvalue(env,trim(argv(i)),idum).and.&
              getvalue(env,trim(argv(j)),ddum)) then
             if (idum.gt.metaset%maxsave) then
                call env%warning('Attempted using factor not present in system.',source)
                cycle
             endif
             metaset%factor(idum) = ddum
          endif
       enddo
    case('scale factor')
       if (mod(narg,2).ne.0) then
          call env%warning("Something went wrong in set_metadyn_ 'scale'.",source)
       endif
       do i = 1, narg, 2
          j = i+1
          if (getvalue(env,trim(argv(i)),idum).and.&
              getvalue(env,trim(argv(j)),ddum)) then
             if (idum.gt.metaset%maxsave) then
                call env%warning('Attempted scaling factor not present in system.',source)
                cycle
             endif
             metaset%factor(idum) = metaset%factor(idum)*ddum
          endif
       enddo
    end select
References comma, xtb_fixparam::metaset, xtb_mctc_strings::parse(), xtb_fixparam::rmsdset, and xtb_setparam::verbose.
Referenced by read_userdata(), and set_legacy().
set_path()
subroutine xtb_constrain_param::set_path (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 1256 of file constrain_param.f90.
    use xtb_type_atomlist
    use xtb_setparam
    implicit none
    character(len=*), parameter :: source = 'userdata_path'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    type(TAtomList) :: atl
    integer  :: idum
    real(wp) :: ddum
    logical  :: ldum
    integer  :: nlist
    integer, allocatable :: list(:)
    integer  :: i,j
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    call parse(val,comma,argv,narg)
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    select case(key)
    case default ! ignore, don't even think about raising them
    case('atoms')
       call atl%new(val)
       if (atl%get_error()) then
          call env%warning('something is wrong in the bias path atom list',source)
          return
       endif
       if (pathset%nat > 0) call atl%add(pathset%atoms(:pathset%nat))
       call atl%to_list(list)
       pathset%atoms = list
       pathset%nat = size(list)
    end select
References comma, xtb_mctc_strings::parse(), xtb_setparam::pathset, and xtb_setparam::verbose.
Referenced by read_userdata().
set_reactor()
subroutine xtb_constrain_param::set_reactor (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 1209 of file constrain_param.f90.
    use xtb_type_atomlist
    use xtb_setparam
    implicit none
    character(len=*), parameter :: source = 'userdata_reactor'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    type(TAtomList) :: atl
    integer  :: idum
    real(wp) :: ddum
    logical  :: ldum
    integer  :: nlist
    integer, allocatable :: list(:)
    integer  :: i,j
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    call parse(val,comma,argv,narg)
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    select case(key)
    case default ! ignore, don't even think about raising them
    case('atoms')
       call atl%new(val)
       if (atl%get_error()) then
          call env%warning('something is wrong in the reactor atom list',source)
          return
       endif
       if (reactset%nat > 0) call atl%add(reactset%atoms(:reactset%nat))
       call atl%to_list(list)
       reactset%atoms = list
       reactset%nat = size(list)
    end select
References comma, xtb_mctc_strings::parse(), xtb_setparam::reactset, and xtb_setparam::verbose.
Referenced by read_userdata().
set_scan()
subroutine xtb_constrain_param::set_scan (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 803 of file constrain_param.f90.
    use xtb_scanparam
    use xtb_mctc_convert, only : aatoau
    use xtb_mctc_constants, only : pi
    implicit none
    character(len=*), parameter :: source = 'userdata_scan'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    integer  :: idum
    real(wp) :: ddum
    logical  :: ldum
    integer  :: i,ie
    real(wp) :: start_value,end_value
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    character(len=:),allocatable :: temp
    nscan = nscan+1 ! make a new scan
    ie = index(val,semicolon)
    if (ie.ne.0) then
       temp = val(:ie-1)
       idum = nconstr
       call set_constr(env,key,temp,nat,at,idmap,xyz) ! generate a new constraint
       scan_list(nscan)%iconstr = nconstr ! new generated
       if (idum.eq.nconstr) then
          call env%error('Failed to generate constraint',source)
          return
       end if
       temp = val(1+ie:)
    else
       if (getvalue(env,key,idum)) then
          if (idum.gt.nconstr) then
             call env%error('Constraint '''//key//''' is not defined',source)
             return
          endif
          scan_list(nscan)%iconstr = idum
       else
          call env%error('Constraint '''//key//''' is invalid in this context',source)
          return
       endif
       temp = val
    endif
    call parse(temp,comma,argv,narg)
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    ! get back the constraint number which should be scanned
    i = scan_list(nscan)%iconstr
    ! instead of simply saving the kind of constraint while reading,
    ! we used some really obvious integer code system depending on
    ! the number of elements in the atconstr-Array.
    ! Expected to break at some point, add a FIXME and wait for complaints...
    idum = atconstr(1,i)
    if (atconstr(2,i).gt.0) idum = 1
    if (atconstr(3,i).gt.0) idum = 2
    if (atconstr(4,i).gt.0) idum = 3
    if (getvalue(env,trim(argv(1)),ddum)) then
       if (idum.le.1) then
          start_value = ddum * aatoau
       else
          start_value = ddum * pi/180.0_wp
       endif
    else
       call env%error('Invalid start value for scan',source)
       return
    endif
    if (getvalue(env,trim(argv(2)),ddum)) then
       if (idum.le.1) then
          end_value = ddum * aatoau
       else
          end_value = ddum * pi/180.0_wp
       endif
    else
       call env%error('Invalid end value for scan',source)
       return
    endif
    if (getvalue(env,trim(argv(3)),idum)) then
       scan_list(nscan)%nscan = idum
       allocate( scan_list(nscan)%valscan(idum), source = 0.0_wp )
    else
       call env%error('Invalid step number for scan',source)
       return
    endif
    do i = 1, scan_list(nscan)%nscan
       scan_list(nscan)%valscan(i) = start_value + (end_value-start_value) &
          &                       * real(i-1,wp)/real(scan_list(nscan)%nscan-1,wp)
       if (verbose) write(env%unit,'(i5,1x,f12.8)') i,scan_list(nscan)%valscan(i)
    enddo
References xtb_mctc_convert::aatoau, xtb_scanparam::atconstr, comma, xtb_scanparam::nconstr, xtb_scanparam::nscan, xtb_mctc_strings::parse(), xtb_mctc_constants::pi, xtb_scanparam::scan_list, semicolon, set_constr(), and xtb_setparam::verbose.
Referenced by read_userdata().
set_split()
subroutine xtb_constrain_param::set_split (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 1046 of file constrain_param.f90.
    use xtb_splitparam
    implicit none
    character(len=*), parameter :: source = 'userdata_split'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    integer  :: idum
    real(wp) :: ddum
    logical  :: ldum
    integer  :: list(nat),nlist
    integer  :: i,j
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    call parse(val,comma,argv,narg)
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    select case(key)
    case default ! ignore, don't even think about raising them
    case('fragment1')
       do i = 1, narg
          if (getlistvalue(env,trim(argv(i)),list,nlist)) then
             do j = 1, nlist
                splitlist(list(j)) = 1
             enddo
             iatf1 = iatf1 + nlist ! compatibility stuff, as usual
             iatf(1) = iatf(1) + nlist
          else
             return ! you screwed it, let's get out of here
          endif
       enddo
    case('fragment2')
       do i = 1, narg
          if (getlistvalue(env,trim(argv(i)),list,nlist)) then
             do j = 1, nlist
                splitlist(list(j)) = 2
             enddo
             iatf2 = iatf2 + nlist ! compatibility stuff, as usual
             iatf(2) = iatf(2) + nlist
          else
             return ! you screwed it, let's get out of here
          endif
       enddo
    case('fragment')
       if (getvalue(env,trim(argv(1)),idum)) then
          if (idum.gt.nat) then
             call env%warning("rejecting fragment number greater than number of atoms",source)
             return ! doesn't really make sense, sorry, your problem
          endif
          do i = 2, narg
             if (getlistvalue(env,trim(argv(i)),list,nlist)) then
                do j = 1, nlist
                   splitlist(list(j)) = idum
                enddo
                iatf(idum) = iatf(idum) + nlist
                if (idum.eq.1) then ! legacy, don't remove or something breaks
                   iatf1 = iatf1 + nlist
                else if (idum.eq.2) then
                   iatf2 = iatf2 + nlist
                endif
             else
                return ! you screwed it, let's get out of here
             endif
          enddo
       endif
    end select
References comma, xtb_readin::getlistvalue(), xtb_splitparam::iatf, xtb_splitparam::iatf1, xtb_splitparam::iatf2, xtb_mctc_strings::parse(), xtb_splitparam::splitlist, and xtb_setparam::verbose.
Referenced by read_userdata(), and set_legacy().
set_wall()
subroutine xtb_constrain_param::set_wall (type(tenvironment), intent(inout) env, character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tidentitymap), intent(in) idMap, real(wp), dimension(3,nat), intent(in) xyz)
Definition at line 908 of file constrain_param.f90.
    use xtb_mctc_convert, only : autoaa
    use xtb_sphereparam
    implicit none
    character(len=*), parameter :: source = 'userdata_wall'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: key
    character(len=*),intent(in) :: val
    integer, intent(in) :: nat
    integer, intent(in) :: at(nat)
    type(TIdentityMap), intent(in) :: idMap
    real(wp),intent(in) :: xyz(3,nat)
    integer  :: idum
    real(wp) :: ddum,darray(3)
    logical  :: ldum
    integer  :: list(nat),nlist
    integer  :: tlist(nat),ntlist
    integer  :: iarg,iaxis
    real(wp) :: radius,radii(3),center(3)
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    nlist = 0
    ntlist = 0
    list = 0
    tlist = 0
    radius = 0.0_wp
    radii  = 0.0_wp
    center = 0.0_wp
    call parse(val,comma,argv,narg)
    if (verbose) then
       do idum = 1, narg
          write(env%unit,'("-->",1x,i0,":",1x,a)') idum, trim(argv(idum))
       enddo
    endif
    select case(key)
    case default ! ignore, don't even think about raising them
    case('sphere')
       if (narg.lt.2) then
          call env%warning("Not enough arguments to set up a spherical wall",source)
          return
       endif
    !  part 1: get the sphere radius
       if (trim(argv(1)).eq.'auto') then
          call get_sphere_radius(nat,at,xyz,center,radius,do_trafo=.false.)
       else
          if (getvalue(env,trim(argv(1)),ddum)) then
             radius = ddum
             center = 0.0_wp
          else
             ! warning already generated by get_value
             return ! something went wrong
          endif
       endif
    !  part 2: get atoms
       if (trim(argv(2)).eq.'all') then
          call set_sphere_radius(radius,center)
       else
          do iarg = 2, narg
             if (getlistvalue(env,trim(argv(iarg)),tlist,ntlist)) then
                if (nlist+ntlist.gt.nat) then
                   call env%warning("Too many atoms in list for spherical wall.",source)
                   return ! something went wrong
                endif
                if (maxval(tlist(:ntlist)).gt.nat) then
                   call env%warning("Attempted to wall in a non-existing atom",source)
                   cycle ! skip crappy input
                endif
                list(nlist+1:nlist+ntlist) = tlist
                nlist = nlist + ntlist
             else
                ! warning already generated by get_list_value
                return ! something went wrong
             endif
          enddo
          call set_sphere_radius(radius,center,nlist,list)
       endif
       write(env%unit,'("spherical wallpotenial with radius",'//&
          '1x,f12.7,1x,"")') radius*autoaa
    case('ellipsoid')
       if (narg.lt.4) then
          call env%warning("Not enough arguments to set up an ellipsoidal wall",source)
          return
       endif
    !  part 1: get ellipsoid axis
       if ((trim(argv(1)).eq.'auto').or.(trim(argv(2)).eq.'auto').or. &
           (trim(argv(3)).eq.'auto')) then
          ! use get_ellipsoid_radius if you manage to implement it
          call get_sphere_radius(nat,at,xyz,center,radius,do_trafo=.false.)
       endif
       do iaxis = 1, 3
          if (trim(argv(iaxis)).eq.'auto') then
             radii(iaxis) = radius
          else
             if (getvalue(env,trim(argv(iaxis)),ddum)) then
                radii(iaxis) = ddum
                center(iaxis) = 0.0_wp
             else
                ! warning already generated by get_value
                return ! something went wrong
             endif
          endif
       enddo
    !  part 2: get atoms
       if (trim(argv(4)).eq.'all') then
          call set_sphere_radius(radii,center)
       else
          do iarg = 4, narg
             if (getlistvalue(env,trim(argv(iarg)),tlist,ntlist)) then
                if (nlist+ntlist.gt.nat) then
                   call env%warning("Too many atoms in list for spherical wall.",source)
                   return ! something went wrong
                endif
                if (maxval(tlist(:ntlist)).gt.nat) then
                   call env%warning("Attempted to wall in a non-existing atom",source)
                   cycle ! skip crappy input
                endif
                list(nlist+1:nlist+ntlist) = tlist
                nlist = nlist + ntlist
             else
                ! warning already generated by get_list_value
                return ! something went wrong
             endif
          enddo
          call set_sphere_radius(radii,center,nlist,list)
       endif
       write(env%unit,'("ellipsoidal wallpotenial with radii",'//&
          '3(1x,f12.7,1x,""))') radii*autoaa
    end select
References xtb_mctc_convert::autoaa, comma, xtb_readin::getlistvalue(), xtb_mctc_strings::parse(), and xtb_setparam::verbose.
Referenced by read_userdata(), and set_legacy().
Variable Documentation
colon
character, parameter, private xtb_constrain_param::colon = ':' private
Definition at line 70 of file constrain_param.f90.
    character,private,parameter :: colon = ':'
Referenced by rdblock().
comma
character, parameter, private xtb_constrain_param::comma = ',' private
Definition at line 74 of file constrain_param.f90.
    character,private,parameter :: comma = ','
Referenced by set_constr(), set_fix(), set_freeze(), set_hess(), set_metadyn(), set_path(), set_reactor(), set_scan(), set_split(), and set_wall().
dot
character, parameter, private xtb_constrain_param::dot = '.' private
Definition at line 76 of file constrain_param.f90.
    character,private,parameter :: dot = '.'
equal
character, parameter, private xtb_constrain_param::equal = '=' private
Definition at line 72 of file constrain_param.f90.
    character,private,parameter :: equal = '='
flag
character, parameter, private xtb_constrain_param::flag = '$' private
Definition at line 69 of file constrain_param.f90.
    character,private,parameter :: flag = '$'
Referenced by rdblock(), rdsetbl(), and read_userdata().
flag_end
character(len=*), parameter, private xtb_constrain_param::flag_end = flag//'end' private
Definition at line 77 of file constrain_param.f90.
    character(len=*),private,parameter :: flag_end = flag//'end'
hash
character, parameter, private xtb_constrain_param::hash = '#' private
Definition at line 73 of file constrain_param.f90.
    character,private,parameter :: hash = '#'
p_arg_length
integer, parameter, private xtb_constrain_param::p_arg_length = 24 private
Definition at line 84 of file constrain_param.f90.
    integer,private,parameter :: p_arg_length = 24
p_str_length
integer, parameter, private xtb_constrain_param::p_str_length = 48 private
Definition at line 83 of file constrain_param.f90.
    integer,private,parameter :: p_str_length = 48
semicolon
character, parameter, private xtb_constrain_param::semicolon = ';' private
Definition at line 75 of file constrain_param.f90.
    character,private,parameter :: semicolon = ';'
Referenced by set_scan().
space
character, parameter, private xtb_constrain_param::space = ' ' private
Definition at line 71 of file constrain_param.f90.
    character,private,parameter :: space = ' '
Referenced by rdsetbl().