My Project: xtb_io_reader_ctfile Module Reference
xtb_io_reader_ctfile Module Reference
Functions/Subroutines
subroutine, public readmoleculesdf (mol, unit, status, iomsg)
subroutine, public readmoleculemolfile (mol, unit, status, iomsg)
Function/Subroutine Documentation
readmoleculemolfile()
subroutine, public xtb_io_reader_ctfile::readmoleculemolfile (class(tmolecule), intent(out) mol, integer, intent(in) unit, logical, intent(out) status, character(len=:), intent(out), allocatable iomsg)
Element symbols
SDF specific information about atom types
Cartesian coordinates in bohr
Definition at line 62 of file ctfile.f90.
    class(TMolecule), intent(out) :: mol
    integer, intent(in) :: unit
    logical, intent(out) :: status
    character(len=:), allocatable, intent(out) :: iomsg
    character(len=:), allocatable :: line
    character(len=:), allocatable :: name
    integer :: i, iatom, jatom, ibond, btype, atomtype
    integer :: error, length, charge(2,15)
    integer :: number_of_atoms, number_of_bonds, number_of_atom_lists, &
       &       chiral_flag, number_of_stext_entries, i999
    integer :: list4(4), list12(12)
    real(wp) :: x, y, z
    character(len=2) :: sdf_dim
    character(len=3) :: symbol
    character(len=5) :: v2000
    integer, parameter :: ccc_to_charge(0:7) = [0, +3, +2, +1, 0, -1, -2, -3]
    logical :: two_dim
    character(len=symbolLength),allocatable :: sym(:)
    type(sdf_data), allocatable :: sdf(:)
    real(wp),allocatable :: xyz(:,:)
    status = .false.
    two_dim = .false.
    call getline(unit, name, error)
    call getline(unit, line, error)
    read(line, '(20x,a2)', iostat=error) sdf_dim
    if (error == 0) then
       two_dim = sdf_dim == '2D' .or. sdf_dim == '2d'
    endif
    call getline(unit, line, error)
    call getline(unit, line, error)
    read(line, '(3i3,3x,2i3,12x,i3,1x,a5)', iostat=error) &
       & number_of_atoms, number_of_bonds, number_of_atom_lists, &
       & chiral_flag, number_of_stext_entries, i999, v2000
    if (error /= 0) then
       iomsg = "could not read header of molfile"
       return
    endif
    allocate(sdf(number_of_atoms), source=sdf_data())
    allocate(xyz(3, number_of_atoms))
    allocate(sym(number_of_atoms))
    do iatom = 1, number_of_atoms
       call getline(unit, line, error)
       read(line, '(3f10.4,1x,a3,i2,11i3)', iostat=error) &
          & x, y, z, symbol, list12
       if (error /= 0) then
          iomsg = "could not coordinates from connection table"
          return
       endif
       atomtype = tonumber(symbol)
       if (atomtype == 0) then
          iomsg = "unknown atom type '"//trim(symbol)//"' in connection table"
          return
       end if
       xyz(:, iatom) = [x, y, z] * aatoau
       sym(iatom) = trim(symbol)
       sdf(iatom)%isotope = list12(1)
       sdf(iatom)%charge = ccc_to_charge(list12(2)) ! drop doublet radical
       sdf(iatom)%hydrogens = list12(4)
       sdf(iatom)%valence = list12(6)
    enddo
    call init(mol, sym, xyz)
    call move_alloc(sdf, mol%sdf)
    if (len(name) > 0) mol%name = name
    if (two_dim) mol%struc%two_dimensional = .true.
    call mol%bonds%allocate(size=number_of_bonds, order=3)
    do ibond = 1, number_of_bonds
       call getline(unit, line, error)
       read(line, '(7i3)', iostat=error) &
          & iatom, jatom, btype, list4
       if (error /= 0) then
          iomsg = "could not topology from connection table"
          return
       endif
       call mol%bonds%push_back([iatom, jatom, btype])
    enddo
    do while(error == 0)
       call getline(unit, line, error)
       if (index(line, 'M  END') == 1) exit
       if (index(line, 'M  CHG') == 1) then
          read(line(7:9), *) length
          read(line(10:), '(*(1x,i3,1x,i3))') (charge(:, i), i=1, length)
          do i = 1, length
             mol%sdf(charge(1, i))%charge = charge(2, i)
          enddo
       endif
    enddo
    if (error /= 0) then
       iomsg = "could not read connection table"
       return
    endif
    mol%chrg = sum(mol%sdf%charge)
    if (any(mol%sdf%hydrogens > 1)) then
       iomsg = "explicit hydrogen atoms are required"
       return
    endif
    status = .true.
References xtb_mctc_convert::aatoau, xtb_mctc_systools::getline(), xtb_mctc_symbols::tonumber(), and true().
Referenced by xtb_io_reader::readmolecule(), and readmoleculesdf().
readmoleculesdf()
subroutine, public xtb_io_reader_ctfile::readmoleculesdf (class(tmolecule), intent(out) mol, integer, intent(in) unit, logical, intent(out) status, character(len=:), intent(out), allocatable iomsg)
Definition at line 34 of file ctfile.f90.
    class(TMolecule), intent(out) :: mol
    integer, intent(in) :: unit
    logical, intent(out) :: status
    character(len=:), allocatable, intent(out) :: iomsg
    character(len=:), allocatable :: line
    integer :: error
    call readmoleculemolfile(mol, unit, status, iomsg)
    if (.not.status) return
    status = .false.
    error = 0
    do while(error == 0)
       call getline(unit, line, error)
       if (index(line, '$$$$') == 1) exit
       call mol%info%push_back(line)
    enddo
    if (error /= 0) then
       iomsg = "failed while reading SDF key-value pairs"
       return
    endif
    status = .true.
References xtb_mctc_systools::getline(), readmoleculemolfile(), and true().
Referenced by xtb_io_reader::readmolecule().