My Project: xtb_gfn0param Module Reference
xtb_gfn0param Module Reference
Variables
integer, parameter, private max_elem = 86
integer, parameter, private max_elem2 = 118
real(wp), parameter, public hbthr = 400.0_wp
real(wp), parameter, public hbthr3 = 800.0_wp
real(wp), parameter, public hbthr2 = 150.0_wp
real(wp), parameter, public longcut =56.0_wp
real(wp), parameter, public hbalp =6.0_wp
real(wp), parameter, public hbalp1 =4.0_wp
real(wp), parameter, public hbalp2 =1.5_wp
real(wp), parameter, public sf_ab =5.0_wp
real(wp), parameter, public st_ab =15.0_wp
real(wp), parameter, public sf_h =15.0_wp
real(wp), parameter, public st_h =15.0_wp
real(wp), dimension(max_elem), public xi
real(wp), dimension(max_elem), public gamm
real(wp), dimension(max_elem), public cnfak
real(wp), dimension(max_elem), public alpg
Variable Documentation
alpg
real(wp), dimension(max_elem), public xtb_gfn0param::alpg
Definition at line 42 of file gfn0param.f90.
    real(wp),public :: alpg(max_elem)
cnfak
real(wp), dimension(max_elem), public xtb_gfn0param::cnfak
Definition at line 41 of file gfn0param.f90.
    real(wp),public :: cnfak(max_elem)
Referenced by xtb_eeq::goedecker_chrgeq().
gamm
real(wp), dimension(max_elem), public xtb_gfn0param::gamm
Definition at line 40 of file gfn0param.f90.
    real(wp),public :: gamm(max_elem)
Referenced by xtb_eeq::goedecker_chrgeq().
hbalp
real(wp), parameter, public xtb_gfn0param::hbalp =6.0_wp
Definition at line 31 of file gfn0param.f90.
    real(wp),public,parameter :: hbalp=6.0_wp      ! smoothness of damping long range
hbalp1
real(wp), parameter, public xtb_gfn0param::hbalp1 =4.0_wp
Definition at line 32 of file gfn0param.f90.
    real(wp),public,parameter :: hbalp1=4.0_wp     ! smoothness of damping short range
hbalp2
real(wp), parameter, public xtb_gfn0param::hbalp2 =1.5_wp
Definition at line 33 of file gfn0param.f90.
    real(wp),public,parameter :: hbalp2=1.5_wp     ! smoothness of damping out-of-lin
hbthr
real(wp), parameter, public xtb_gfn0param::hbthr = 400.0_wp
Definition at line 26 of file gfn0param.f90.
    real(wp),public,parameter :: hbthr  = 400.0_wp ! save R^2 ABH triangle cut-off
hbthr2
real(wp), parameter, public xtb_gfn0param::hbthr2 = 150.0_wp
Definition at line 28 of file gfn0param.f90.
    real(wp),public,parameter :: hbthr2 = 150.0_wp ! neighbor list R^2 cut-off for LP grad part
hbthr3
real(wp), parameter, public xtb_gfn0param::hbthr3 = 800.0_wp
Definition at line 27 of file gfn0param.f90.
    real(wp),public,parameter :: hbthr3 = 800.0_wp ! hbthr*2
longcut
real(wp), parameter, public xtb_gfn0param::longcut =56.0_wp
Definition at line 30 of file gfn0param.f90.
    real(wp),public,parameter :: longcut=56.0_wp   ! about 8 Bohr smooth cut-off in rAB
max_elem
integer, parameter, private xtb_gfn0param::max_elem = 86 private
Definition at line 21 of file gfn0param.f90.
    integer,private,parameter :: max_elem = 86
max_elem2
integer, parameter, private xtb_gfn0param::max_elem2 = 118 private
Definition at line 22 of file gfn0param.f90.
    integer,private,parameter :: max_elem2 = 118
sf_ab
real(wp), parameter, public xtb_gfn0param::sf_ab =5.0_wp
Definition at line 34 of file gfn0param.f90.
    real(wp),public,parameter :: sf_ab=5.0_wp      ! shift of A,B charge scaling fct
sf_h
real(wp), parameter, public xtb_gfn0param::sf_h =15.0_wp
Definition at line 36 of file gfn0param.f90.
    real(wp),public,parameter :: sf_h=15.0_wp      ! shift of H charge scaling fct
st_ab
real(wp), parameter, public xtb_gfn0param::st_ab =15.0_wp
Definition at line 35 of file gfn0param.f90.
    real(wp),public,parameter :: st_ab=15.0_wp     ! steepness of A,B charge scaling fct
st_h
real(wp), parameter, public xtb_gfn0param::st_h =15.0_wp
Definition at line 37 of file gfn0param.f90.
    real(wp),public,parameter :: st_h=15.0_wp      ! steepness of H charge scaling fct
xi
real(wp), dimension(max_elem), public xtb_gfn0param::xi
Definition at line 39 of file gfn0param.f90.
    real(wp),public :: xi(max_elem)
Referenced by xtb_eeq::goedecker_chrgeq().