My Project: xtb_disp_dftd4param Module Reference
xtb_disp_dftd4param Module Reference
Variables
real(wp) thopi
real(wp) ootpi
integer, parameter p_refq_gfn2xtb = 0
integer, parameter p_refq_gasteiger = 1
integer, parameter p_refq_hirshfeld = 2
integer, parameter p_refq_periodic = 3
integer, parameter p_refq_gfn2xtb_gbsa_h2o = 4
integer, parameter p_refq_goedecker = 5
integer, parameter p_mbd_none = 0
integer, parameter p_mbd_rpalike = 1
integer, parameter p_mbd_exact_atm = 2
integer, parameter p_mbd_approx_atm = 3
integer, parameter, private max_elem = 118
real(wp), dimension(max_elem), parameter zeff = [ 1, 2, 3, 4, 5, 6, 7, 8, 9,10, 11,12, 13,14,15,16,17,18, 19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36, 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26, 9,10,11,30,31,32,33,34,35,36,37,38,39,40,41,42,43, 12,13,14,15,16,17,18,19,20,21,22,23,24,25,26, 9,10,11,30,31,32,33,34,35,36,37,38,39,40,41,42,43, 12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 ]
integer, dimension(max_elem) refn
real(wp), dimension(7, max_elem) refq
real(wp), dimension(7, max_elem) refh
real(wp), dimension(7, max_elem) dftq
real(wp), dimension(7, max_elem) pbcq
real(wp), dimension(7, max_elem) gffq
real(wp), dimension(7, max_elem) solq
real(wp), dimension(7, max_elem) clsq
real(wp), dimension(7, max_elem) dfth
real(wp), dimension(7, max_elem) pbch
real(wp), dimension(7, max_elem) gffh
real(wp), dimension(7, max_elem) solh
real(wp), dimension(7, max_elem) clsh
real(wp), dimension(7, max_elem) hcount
real(wp), dimension(7, max_elem) ascale
real(wp), dimension(7, max_elem) refcovcn
real(wp), dimension(7, max_elem) refcn
integer, dimension(7, max_elem) refsys
real(wp), dimension(23, 7, max_elem) alphaiw
real(wp), dimension(17) secq
real(wp), dimension(17) dfts
real(wp), dimension(17) pbcs
real(wp), dimension(17) gffs
real(wp), dimension(17) sols
real(wp), dimension(17) clss
real(wp), dimension(17) sscale
real(wp), dimension(17) seccn
real(wp), dimension(17) seccnd3
real(wp), dimension(23, 17) secaiw
Variable Documentation
alphaiw
real(wp), dimension(23,7,max_elem) xtb_disp_dftd4param::alphaiw
Definition at line 63 of file dftd4_parameters.f90.
    real(wp),dimension(23,7,max_elem) :: alphaiw
Referenced by xtb_disp_dftd4::newd3model(), and xtb_disp_dftd4::newd4model().
ascale
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::ascale
Definition at line 59 of file dftd4_parameters.f90.
    real(wp),dimension(7,max_elem)    :: ascale
Referenced by xtb_disp_dftd4::newd3model(), and xtb_disp_dftd4::newd4model().
clsh
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::clsh
Definition at line 57 of file dftd4_parameters.f90.
Referenced by xtb_disp_dftd4::newd4model().
clsq
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::clsq
Definition at line 56 of file dftd4_parameters.f90.
Referenced by xtb_disp_dftd4::newd4model().
clss
real(wp), dimension(17) xtb_disp_dftd4param::clss
Definition at line 65 of file dftd4_parameters.f90.
Referenced by xtb_disp_dftd4::newd4model().
dfth
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::dfth
Definition at line 57 of file dftd4_parameters.f90.
    real(wp),dimension(7,max_elem)    :: dfth,pbch,gffh,solh,clsh
Referenced by xtb_disp_dftd4::newd4model().
dftq
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::dftq
Definition at line 56 of file dftd4_parameters.f90.
    real(wp),dimension(7,max_elem)    :: dftq,pbcq,gffq,solq,clsq
Referenced by xtb_disp_dftd4::newd4model().
dfts
real(wp), dimension(17) xtb_disp_dftd4param::dfts
Definition at line 65 of file dftd4_parameters.f90.
    real(wp),dimension(17)       :: dfts,pbcs,gffs,sols,clss
Referenced by xtb_disp_dftd4::newd4model().
gffh
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::gffh
Definition at line 57 of file dftd4_parameters.f90.
Referenced by xtb_disp_dftd4::newd4model().
gffq
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::gffq
Definition at line 56 of file dftd4_parameters.f90.
Referenced by xtb_disp_dftd4::newd4model().
gffs
real(wp), dimension(17) xtb_disp_dftd4param::gffs
Definition at line 65 of file dftd4_parameters.f90.
Referenced by xtb_disp_dftd4::newd4model().
hcount
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::hcount
Definition at line 58 of file dftd4_parameters.f90.
    real(wp),dimension(7,max_elem)    :: hcount
Referenced by xtb_disp_dftd4::newd3model(), and xtb_disp_dftd4::newd4model().
max_elem
integer, parameter, private xtb_disp_dftd4param::max_elem = 118 private
Definition at line 40 of file dftd4_parameters.f90.
    integer, private, parameter :: max_elem = 118
ootpi
real(wp) xtb_disp_dftd4param::ootpi
Definition at line 24 of file dftd4_parameters.f90.
p_mbd_approx_atm
integer, parameter xtb_disp_dftd4param::p_mbd_approx_atm = 3
Definition at line 38 of file dftd4_parameters.f90.
    integer, parameter :: p_mbd_approx_atm = 3
p_mbd_exact_atm
integer, parameter xtb_disp_dftd4param::p_mbd_exact_atm = 2
Definition at line 37 of file dftd4_parameters.f90.
    integer, parameter :: p_mbd_exact_atm  = 2
p_mbd_none
integer, parameter xtb_disp_dftd4param::p_mbd_none = 0
Definition at line 35 of file dftd4_parameters.f90.
    integer, parameter :: p_mbd_none       = 0
p_mbd_rpalike
integer, parameter xtb_disp_dftd4param::p_mbd_rpalike = 1
Definition at line 36 of file dftd4_parameters.f90.
    integer, parameter :: p_mbd_rpalike    = 1
p_refq_gasteiger
integer, parameter xtb_disp_dftd4param::p_refq_gasteiger = 1
Definition at line 29 of file dftd4_parameters.f90.
    integer, parameter :: p_refq_gasteiger        = 1
Referenced by xtb_disp_dftd4::newd4model().
p_refq_gfn2xtb
integer, parameter xtb_disp_dftd4param::p_refq_gfn2xtb = 0
Definition at line 28 of file dftd4_parameters.f90.
    integer, parameter :: p_refq_gfn2xtb          = 0
p_refq_gfn2xtb_gbsa_h2o
integer, parameter xtb_disp_dftd4param::p_refq_gfn2xtb_gbsa_h2o = 4
Definition at line 32 of file dftd4_parameters.f90.
    integer, parameter :: p_refq_gfn2xtb_gbsa_h2o = 4
Referenced by xtb_disp_dftd4::newd4model().
p_refq_goedecker
integer, parameter xtb_disp_dftd4param::p_refq_goedecker = 5
Definition at line 33 of file dftd4_parameters.f90.
    integer, parameter :: p_refq_goedecker        = 5
Referenced by xtb_disp_dftd4::newd4model().
p_refq_hirshfeld
integer, parameter xtb_disp_dftd4param::p_refq_hirshfeld = 2
Definition at line 30 of file dftd4_parameters.f90.
    integer, parameter :: p_refq_hirshfeld        = 2
Referenced by xtb_disp_dftd4::newd4model().
p_refq_periodic
integer, parameter xtb_disp_dftd4param::p_refq_periodic = 3
Definition at line 31 of file dftd4_parameters.f90.
    integer, parameter :: p_refq_periodic         = 3
Referenced by xtb_disp_dftd4::newd4model().
pbch
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::pbch
Definition at line 57 of file dftd4_parameters.f90.
pbcq
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::pbcq
Definition at line 56 of file dftd4_parameters.f90.
pbcs
real(wp), dimension(17) xtb_disp_dftd4param::pbcs
Definition at line 65 of file dftd4_parameters.f90.
refcn
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::refcn
Definition at line 61 of file dftd4_parameters.f90.
    real(wp),dimension(7,max_elem)    :: refcn
Referenced by xtb_disp_dftd4::newd3model(), and xtb_disp_dftd4::newd4model().
refcovcn
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::refcovcn
Definition at line 60 of file dftd4_parameters.f90.
    real(wp),dimension(7,max_elem)    :: refcovcn
Referenced by xtb_disp_dftd4::newd4model().
refh
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::refh
Definition at line 55 of file dftd4_parameters.f90.
    real(wp),dimension(7,max_elem)    :: refh
Referenced by xtb_disp_dftd4::newd4model().
refn
integer, dimension(max_elem) xtb_disp_dftd4param::refn
Definition at line 53 of file dftd4_parameters.f90.
    integer, dimension(max_elem)      :: refn ! for D4
Referenced by xtb_disp_dftd4::newd3model(), and xtb_disp_dftd4::newd4model().
refq
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::refq
Definition at line 54 of file dftd4_parameters.f90.
    real(wp),dimension(7,max_elem)    :: refq
Referenced by xtb_disp_dftd4::newd4model().
refsys
integer, dimension(7,max_elem) xtb_disp_dftd4param::refsys
Definition at line 62 of file dftd4_parameters.f90.
    integer, dimension(7,max_elem)    :: refsys
Referenced by xtb_disp_dftd4::newd3model(), and xtb_disp_dftd4::newd4model().
secaiw
real(wp), dimension(23,17) xtb_disp_dftd4param::secaiw
Definition at line 69 of file dftd4_parameters.f90.
    real(wp),dimension(23,17)    :: secaiw
Referenced by xtb_disp_dftd4::newd3model(), and xtb_disp_dftd4::newd4model().
seccn
real(wp), dimension(17) xtb_disp_dftd4param::seccn
Definition at line 67 of file dftd4_parameters.f90.
    real(wp),dimension(17)       :: seccn
seccnd3
real(wp), dimension(17) xtb_disp_dftd4param::seccnd3
Definition at line 68 of file dftd4_parameters.f90.
    real(wp),dimension(17)       :: seccnd3
secq
real(wp), dimension(17) xtb_disp_dftd4param::secq
Definition at line 64 of file dftd4_parameters.f90.
    real(wp),dimension(17)       :: secq
Referenced by xtb_disp_dftd4::newd4model().
solh
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::solh
Definition at line 57 of file dftd4_parameters.f90.
Referenced by xtb_disp_dftd4::newd4model().
solq
real(wp), dimension(7,max_elem) xtb_disp_dftd4param::solq
Definition at line 56 of file dftd4_parameters.f90.
Referenced by xtb_disp_dftd4::newd4model().
sols
real(wp), dimension(17) xtb_disp_dftd4param::sols
Definition at line 65 of file dftd4_parameters.f90.
Referenced by xtb_disp_dftd4::newd4model().
sscale
real(wp), dimension(17) xtb_disp_dftd4param::sscale
Definition at line 66 of file dftd4_parameters.f90.
    real(wp),dimension(17)       :: sscale
Referenced by xtb_disp_dftd4::newd3model(), and xtb_disp_dftd4::newd4model().
thopi
real(wp) xtb_disp_dftd4param::thopi
Definition at line 24 of file dftd4_parameters.f90.
    real(wp) :: thopi,ootpi
Referenced by xtb_disp_dftd4::mdisp(), xtb_disp_dftd4::newd3model(), and xtb_disp_dftd4::newd4model().
zeff
real(wp), dimension(max_elem), parameter xtb_disp_dftd4param::zeff = [ 1, 2, 3, 4, 5, 6, 7, 8, 9,10, 11,12, 13,14,15,16,17,18, 19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36, 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26, 9,10,11,30,31,32,33,34,35,36,37,38,39,40,41,42,43, 12,13,14,15,16,17,18,19,20,21,22,23,24,25,26, 9,10,11,30,31,32,33,34,35,36,37,38,39,40,41,42,43, 12,13,14,15,16,17,18,19,20,21,22,23,24,25,26 ]
Definition at line 41 of file dftd4_parameters.f90.
    real(wp), parameter :: zeff(max_elem) = [ &
       &   1,                                                 2,  & ! H-He
       &   3, 4,                               5, 6, 7, 8, 9,10,  & ! Li-Ne
       &  11,12,                              13,14,15,16,17,18,  & ! Na-Ar
       &  19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,  & ! K-Kr
       &   9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,  & ! Rb-Xe
       &   9,10,11,30,31,32,33,34,35,36,37,38,39,40,41,42,43,  & ! Cs-Lu
       &  12,13,14,15,16,17,18,19,20,21,22,23,24,25,26, & ! Hf-Rn
       !  just copy & paste from above
       &   9,10,11,30,31,32,33,34,35,36,37,38,39,40,41,42,43,  & ! Fr-Lr
       &  12,13,14,15,16,17,18,19,20,21,22,23,24,25,26  ] ! Rf-Og
Referenced by xtb_disp_dftd4::d4_atm_gradient::d4_atm_gradient_latp(), xtb_disp_dftd4::d4_atm_gradient::d4_atm_gradient_neigh(), xtb_disp_dftd4::d4_gradient::d4_full_gradient_latp(), xtb_disp_dftd4::d4_gradient::d4_full_gradient_neigh(), xtb_disp_dftd4::d4_gradient::d4_gradient_latp(), xtb_disp_dftd4::d4_gradient::d4_gradient_neigh(), xtb_disp_dftd4::disppot(), xtb_disp_dftd4::edisp_scc(), xtb_disp_dftd4::mdisp(), and xtb_disp_dftd4::newd4model().