My Project: xtb_mctc_namegen Module Reference
xtb_mctc_namegen Module Reference
Generate a new random name.
Functions/Subroutines
subroutine, public generatename (name)
Generate a new random name.
Variables
character(len=1), parameter delimiter = '-'
character(len= *), dimension(61), parameter tword = [ "talkative ", "tall ", "tame ", "tan ", "tangible ", "tart ", "tasty ", "tattered ", "taut ", "tedious ", "teeming ", "tempting ", "tender ", "tense ", "tepid ", "terrible ", "terrific ", "testy ", "thankful ", "that ", "these ", "thick ", "thin ", "third ", "thirsty ", "this ", "thorny ", "thorough ", "those ", "thoughtful ", "threadbare ", "thrifty ", "thunderous ", "tidy ", "tight ", "timely ", "tinted ", "tiny ", "tired ", "torn ", "total ", "tough ", "tragic ", "trained ", "traumatic ", "treasured ", "tremendous ", "triangular ", "tricky ", "trifling ", "trim ", "trivial ", "troubled ", "true ", "trusting ", "trustworthy", "trusty ", "truthful ", "tubby ", "turbulent ", "twin "]
character(len= *), dimension(53), parameter bword = [ "back ", "backs ", "bail ", "balance ", "balances ", "balloon ", "balloons ", "ban ", "bans ", "bandage ", "bandages ", "bank ", "bare ", "bargain ", "battle ", "battles ", "beam ", "bear ", "beat ", "beats ", "bend ", "bends ", "benefit ", "benefits ", "blame ", "blast ", "blasts ", "bleach ", "block ", "bloom ", "blow ", "board ", "boards ", "bother ", "bounce ", "bounces ", "bow ", "bows ", "box ", "boxes ", "bread ", "break ", "breaks ", "breed ", "broadcast ", "broadcasts", "brush ", "brushes ", "bump ", "bumps ", "burn ", "burns ", "buy "]
Detailed Description
Generate a new random name.
Function/Subroutine Documentation
generatename()
subroutine, public xtb_mctc_namegen::generatename (character(len=:), intent(out), allocatable name)
Generate a new random name.
Parameters
[out] name Generated name
Definition at line 62 of file namegen.f90.
    character(len=:), allocatable, intent(out) :: name
    real :: rNum(2)
    integer :: idx(2)
    call random_number(rnum)
    idx = int([size(tword), size(bword)] * rnum) + 1
    name = trim(tword(idx(1))) // delimiter // trim(bword(idx(2)))
References bword, delimiter, and tword.
Variable Documentation
bword
character(len=*), dimension(53), parameter xtb_mctc_namegen::bword = [ "back ", "backs ", "bail ", "balance ", "balances ", "balloon ", "balloons ", "ban ", "bans ", "bandage ", "bandages ", "bank ", "bare ", "bargain ", "battle ", "battles ", "beam ", "bear ", "beat ", "beats ", "bend ", "bends ", "benefit ", "benefits ", "blame ", "blast ", "blasts ", "bleach ", "block ", "bloom ", "blow ", "board ", "boards ", "bother ", "bounce ", "bounces ", "bow ", "bows ", "box ", "boxes ", "bread ", "break ", "breaks ", "breed ", "broadcast ", "broadcasts", "brush ", "brushes ", "bump ", "bumps ", "burn ", "burns ", "buy "] private
Definition at line 44 of file namegen.f90.
    character(len=*), parameter :: bWord(53) = [ &
       & "back      ", "backs     ", "bail      ", "balance   ", "balances  ", &
       & "balloon   ", "balloons  ", "ban       ", "bans      ", "bandage   ", &
       & "bandages  ", "bank      ", "bare      ", "bargain   ", "battle    ", &
       & "battles   ", "beam      ", "bear      ", "beat      ", "beats     ", &
       & "bend      ", "bends     ", "benefit   ", "benefits  ", "blame     ", &
       & "blast     ", "blasts    ", "bleach    ", "block     ", "bloom     ", &
       & "blow      ", "board     ", "boards    ", "bother    ", "bounce    ", &
       & "bounces   ", "bow       ", "bows      ", "box       ", "boxes     ", &
       & "bread     ", "break     ", "breaks    ", "breed     ", "broadcast ", &
       & "broadcasts", "brush     ", "brushes   ", "bump      ", "bumps     ", &
       & "burn      ", "burns     ", "buy       "]
Referenced by generatename().
delimiter
character(len=1), parameter xtb_mctc_namegen::delimiter = '-' private
Definition at line 27 of file namegen.f90.
    character(len=1), parameter :: delimiter = '-'
Referenced by generatename().
tword
character(len=*), dimension(61), parameter xtb_mctc_namegen::tword = [ "talkative ", "tall ", "tame ", "tan ", "tangible ", "tart ", "tasty ", "tattered ", "taut ", "tedious ", "teeming ", "tempting ", "tender ", "tense ", "tepid ", "terrible ", "terrific ", "testy ", "thankful ", "that ", "these ", "thick ", "thin ", "third ", "thirsty ", "this ", "thorny ", "thorough ", "those ", "thoughtful ", "threadbare ", "thrifty ", "thunderous ", "tidy ", "tight ", "timely ", "tinted ", "tiny ", "tired ", "torn ", "total ", "tough ", "tragic ", "trained ", "traumatic ", "treasured ", "tremendous ", "triangular ", "tricky ", "trifling ", "trim ", "trivial ", "troubled ", "true ", "trusting ", "trustworthy", "trusty ", "truthful ", "tubby ", "turbulent ", "twin "] private
Definition at line 29 of file namegen.f90.
    character(len=*), parameter :: tWord(61) = [ &
       &"talkative  ", "tall       ", "tame       ", "tan        ", "tangible   ", &
       &"tart       ", "tasty      ", "tattered   ", "taut       ", "tedious    ", &
       &"teeming    ", "tempting   ", "tender     ", "tense      ", "tepid      ", &
       &"terrible   ", "terrific   ", "testy      ", "thankful   ", "that       ", &
       &"these      ", "thick      ", "thin       ", "third      ", "thirsty    ", &
       &"this       ", "thorny     ", "thorough   ", "those      ", "thoughtful ", &
       &"threadbare ", "thrifty    ", "thunderous ", "tidy       ", "tight      ", &
       &"timely     ", "tinted     ", "tiny       ", "tired      ", "torn       ", &
       &"total      ", "tough      ", "tragic     ", "trained    ", "traumatic  ", &
       &"treasured  ", "tremendous ", "triangular ", "tricky     ", "trifling   ", &
       &"trim       ", "trivial    ", "troubled   ", "true       ", "trusting   ", &
       &"trustworthy", "trusty     ", "truthful   ", "tubby      ", "turbulent  ", &
       &"twin       "]
Referenced by generatename().