My Project: xtb_fixparam Module Reference
xtb_fixparam Module Reference
Functions/Subroutines
subroutine init_fix (nfix)
subroutine clear_fix
subroutine init_metadyn (nat, nstruc)
subroutine init_bhess (nat)
subroutine clear_metadyn
subroutine fix_info (iunit, n, at, xyz)
Variables
type(fix_setvar) fixset
type(fix_setvar) shakeset
type(fix_setvar) freezeset
type(metadyn_setvar) metaset
type(metadyn_setvar) rmsdset
Function/Subroutine Documentation
clear_fix()
subroutine xtb_fixparam::clear_fix
Definition at line 49 of file fixparam.f90.
    call fixset%deallocate
    call shakeset%deallocate
    call freezeset%deallocate
References fixset, freezeset, and shakeset.
Referenced by init_fix().
clear_metadyn()
subroutine xtb_fixparam::clear_metadyn
Definition at line 72 of file fixparam.f90.
    call metaset%deallocate
References metaset.
fix_info()
subroutine xtb_fixparam::fix_info (integer, intent(in) iunit, integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz)
Definition at line 76 of file fixparam.f90.
    use xtb_mctc_constants
    use xtb_mctc_convert
    use xtb_mctc_symbols, only : tosymbol
    implicit none
    integer, intent(in)  :: iunit
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    real(wp),intent(in)  :: xyz(3,n)
    integer  :: i,ii,j,k,l,m,mm
    real(wp) :: val
    if (fixset%n.gt.0 .or. freezeset%n.gt.0 .or. shakeset%n.gt.0) then
       call generic_header(iunit,"Fixed Atoms",49,10)
       write(iunit,'(a)')
    endif
    if (fixset%n.gt.0) then
       write(iunit,'(1x,"*",1x,i0,1x,a)') fixset%n, &
          "fixed atom positions, i.e. in gradient"
       write(iunit,'(a)')
       write(iunit,Å'(5x,"#",3x,"Z",3x,32x,"position/")')
       do i = 1, fixset%n
          ii = fixset%atoms(i)
          write(iunit,'(i6,1x,i3,1x,a2,3f14.7)') &
             ii,at(ii),tosymbol(at(ii)),xyz(:,ii)*autoaa
       enddo
       write(iunit,'(a)')
    endif
    if (freezeset%n.gt.0) then
       write(iunit,'(1x,"*",1x,i0,1x,a)') freezeset%n, &
          "frozen atom positions, i.e. in hessian"
       write(iunit,'(a)')
       write(iunit,Å'(5x,"#",3x,"Z",3x,32x,"position/")')
       do i = 1, freezeset%n
          ii = freezeset%atoms(i)
          write(iunit,'(i6,1x,i3,1x,a2,3f14.7)') &
             ii,at(ii),tosymbol(at(ii)),xyz(:,ii)*autoaa
       enddo
       write(iunit,'(a)')
    endif
    if (shakeset%n.gt.0) then
       write(iunit,'(1x,"*",1x,i0,1x,a)') shakeset%n/2, &
          "constrained distances for dynamics (SHAKE)"
       write(iunit,'(a)')
       write(iunit,Å'(2(5x,"#",3x,"Z",3x),8x,"value/")')
       do m = 1, shakeset%n, 2
          i = shakeset%atoms(m)
          j = shakeset%atoms(m+1)
          val = sqrt(sum((xyz(:,i)-xyz(:,j))**2))
          write(iunit,'(2(i6,1x,i3,1x,a2),1x,f14.7)') &
             i,at(i),tosymbol(at(i)), &
             j,at(j),tosymbol(at(j)), &
             val*autoaa
       enddo
       write(iunit,'(a)')
    endif
References xtb_mctc_convert::autoaa, fixset, freezeset, generic_header(), shakeset, and xtb_mctc_symbols::tosymbol().
Referenced by xtb_prog_main::xtbmain().
init_bhess()
subroutine xtb_fixparam::init_bhess (integer, intent(in) nat)
Definition at line 64 of file fixparam.f90.
    implicit none
    integer, intent(in) :: nat
    call metaset%allocate(nat,1)
    metaset%maxsave= 1
    metaset%factor = metaset%global_factor
References metaset.
Referenced by xtb_prog_main::xtbmain().
init_fix()
subroutine xtb_fixparam::init_fix (integer, intent(in) nfix)
Definition at line 40 of file fixparam.f90.
    implicit none
    integer, intent(in) :: nfix
    call clear_fix
    call fixset%allocate(nfix)
    call shakeset%allocate(nfix*(nfix+1)/2)
    call freezeset%allocate(nfix)
References clear_fix(), fixset, freezeset, and shakeset.
Referenced by xtb_prog_main::xtbmain().
init_metadyn()
subroutine xtb_fixparam::init_metadyn (integer, intent(in) nat, integer, intent(in) nstruc)
Definition at line 55 of file fixparam.f90.
    implicit none
    integer, intent(in) :: nat
    integer, intent(in) :: nstruc
    call metaset%allocate(nat,nstruc)
    metaset%factor = metaset%global_factor
    metaset%width = metaset%global_width
References metaset.
Referenced by xtb_prog_main::xtbmain().
Variable Documentation
fixset
type(fix_setvar) xtb_fixparam::fixset
Definition at line 28 of file fixparam.f90.
    type(fix_setvar) :: fixset
Referenced by xtb_optimizer::ancopt(), clear_fix(), fix_info(), fixmetal(), xtb_freq_project::gtrprojm(), init_fix(), qpotini(), xtb_constrain_param::set_fix(), xtb_gfnff_calculator::singlepoint(), xtb_type_dummycalc::singlepoint(), xtb_xtb_calculator::singlepoint(), xtb_setmod::write_set_fix(), and xtb_prog_main::xtbmain().
freezeset
type(fix_setvar) xtb_fixparam::freezeset
Definition at line 30 of file fixparam.f90.
    type(fix_setvar) :: freezeset
Referenced by clear_fix(), fix_info(), init_fix(), xtb_hessian::numhess(), xtb_setmod::set_fix(), xtb_constrain_param::set_fix(), and xtb_setmod::write_set_fix().
metaset
type(metadyn_setvar) xtb_fixparam::metaset
Definition at line 35 of file fixparam.f90.
    type(metadyn_setvar) :: metaset
Referenced by xtb_biaspath::bias_path(), clear_metadyn(), constrhess(), init_bhess(), init_metadyn(), xtb_dynamic::md(), xtb_biaspath::metadyn_tsmode(), xtb_hessian::numhess(), xtb_hessian::numhess_rmsd(), xtb_setmod::set_metadyn(), xtb_constrain_param::set_metadyn(), xtb_gfnff_calculator::singlepoint(), xtb_type_dummycalc::singlepoint(), xtb_xtb_calculator::singlepoint(), xtb_setmod::write_set_metadyn(), and xtb_prog_main::xtbmain().
rmsdset
type(metadyn_setvar) xtb_fixparam::rmsdset
Definition at line 36 of file fixparam.f90.
    type(metadyn_setvar) :: rmsdset
Referenced by xtb_setmod::set_metadyn(), xtb_constrain_param::set_metadyn(), xtb_gfnff_calculator::singlepoint(), xtb_type_dummycalc::singlepoint(), xtb_xtb_calculator::singlepoint(), and xtb_prog_main::xtbmain().
shakeset
type(fix_setvar) xtb_fixparam::shakeset
Definition at line 29 of file fixparam.f90.
    type(fix_setvar) :: shakeset
Referenced by clear_fix(), fix_info(), init_fix(), xtb_shake::init_shake(), and xtb_constrain_param::set_fix().