My Project: xtb_solv_gbsa Module Reference
xtb_solv_gbsa Module Reference
Implementation for generalized Born and related solvation models.
Data Types
type tborn
interface init
Initialize data straucture.
Functions/Subroutines
subroutine initborn (self, env, num, vdwRad, dielectricConst, freeEnergyShift, descreening, bornScale, bornOffset, surfaceTension, probeRad, rCutoff, rOffset, nAng, hBondStrength, temperature, kernel, alpb, ionSt, ionRad)
Initialize data straucture.
subroutine update (self, env, num, xyz)
subroutine addbornmatrix (self, env, num, xyz, bornMat)
subroutine addshift (self, env, qat, qsh, atomicShift, shellShift)
Add potential shift.
subroutine getenergy (self, env, qat, qsh, energy)
Calculate solvation energy.
subroutine getenergyparts (self, env, qat, qsh, gborn, ghb, gsasa, gshift)
Calculate solvation energy.
subroutine addgradient (self, env, num, xyz, qat, qsh, gradient)
Calculate derivatives of solvation energy.
subroutine, public getadet (nAtom, xyz, rad, aDet)
subroutine, public addadetderiv (nAtom, xyz, rad, kEps, qvec, gradient)
pure subroutine, public getdebyehueckel (nat, dielectricConst, kappa, ionRad, brad, ionscr, discr)
compute the Debye-Hueckel ion exclusion term
subroutine, public update_nnlist_gbsa (nat, ntpair, ppind, xyz, lrcut, srcut, nnsas, nnlists, nnrad, nnlistr, ddpair, parallel)
setup a pairlist and compute pair distances of all neighbors
subroutine update_nnlist_gbsa_parallel (nat, ntpair, ppind, xyz, lrcut, srcut, nnsas, nnlists, nnrad, nnlistr, ddpair)
setup a pairlist and compute pair distances of all neighbors
pure subroutine update_nnlist_gbsa_sequential (nat, ntpair, ppind, xyz, lrcut, srcut, nnsas, nnlists, nnrad, nnlistr, ddpair)
setup a pairlist and compute pair distances of all neighbors
pure subroutine, public compute_fhb (nat, hbmag, vdwsa, sasa, hbw, dhbdw)
Compute contributions to potential for hydrogen bonding correction.
pure subroutine, public addgradienthbond (nat, at, q, hbw, dhbdw, dsdrt, ghb, gradient)
Compute contributions to energy and gradient for hydrogen bonding correction.
pure subroutine addbornderiv (self, q, gborn, ghb, dAmatdr, Afac)
pure subroutine, public addhbondderiv (nat, q, hbw, dhbdw, dsdrt, ghb, dAmatdr)
Variables
real(wp), parameter w = 0.3_wp*aatoau
Smoothing dielectric function parameters.
real(wp), parameter w3 = w*(w*w)
real(wp), parameter ah0 = 0.5_wp
real(wp), parameter ah1 = 3._wp/(4.0_wp*w)
real(wp), parameter ah3 = -1._wp/(4.0_wp*w3)
real(wp), parameter gammas = 1.0e-5_wp
Surface tension (in au)
real(wp), parameter kappaconst = 0.7897e-3_wp
Salt screening.
Detailed Description
Implementation for generalized Born and related solvation models.
Function/Subroutine Documentation
addadetderiv()
subroutine, public xtb_solv_gbsa::addadetderiv (integer, intent(in) nAtom, real(wp), dimension(:, :), intent(in) xyz, real(wp), dimension(:), intent(in) rad, real(wp), intent(in) kEps, real(wp), dimension(:), intent(in) qvec, real(wp), dimension(:, :), intent(inout) gradient)
Parameters
[in] natom Number of atoms
[in] xyz Cartesian coordinates
[in] rad Atomic radii
[in,out] gradient Molecular gradient
Definition at line 709 of file gbsa.f90.
    integer, intent(in) :: nAtom
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in) :: rad(:)
    real(wp), intent(in) :: kEps
    real(wp), intent(in) :: qvec(:)
    real(wp), intent(inout) :: gradient(:, :)
    integer :: iat
    real(wp) :: r2, rad2, rad3, totRad3, vec(3), center(3), inertia(3, 3), aDet
    real(wp) :: aDeriv(3, 3), qtotal
    real(wp), parameter :: tof = 2.0_wp/5.0_wp, unity(3, 3) = reshape(&
       & [1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp], &
       & [3, 3])
    qtotal = 0.0_wp
    totrad3 = 0.0_wp
    center(:) = 0.0_wp
    do iat = 1, natom
       rad2 = rad(iat) * rad(iat)
       rad3 = rad2 * rad(iat)
       totrad3 = totrad3 + rad3
       center(:) = center + xyz(:, iat) * rad3
       qtotal = qtotal + qvec(iat)
    end do
    center = center / totrad3
    inertia(:, :) = 0.0_wp
    do iat = 1, natom
       rad2 = rad(iat) * rad(iat)
       rad3 = rad2 * rad(iat)
       vec(:) = xyz(:, iat) - center
       r2 = sum(vec**2)
       inertia(:, :) = inertia + rad3 * ((r2 + tof*rad2) * unity &
          & - spread(vec, 1, 3) * spread(vec, 2, 3))
    end do
    adet = sqrt(matdet3x3(inertia)**(1.0_wp/3.0_wp)/(tof*totrad3))
    aderiv(:, :) = reshape([&
       & inertia(1,1)*(inertia(2,2)+inertia(3,3))-inertia(1,2)**2-inertia(1,3)**2, &
       & inertia(1,2)*inertia(3,3)-inertia(1,3)*inertia(2,3), & ! xy
       & inertia(1,3)*inertia(2,2)-inertia(1,2)*inertia(3,2), & ! xz
       & inertia(1,2)*inertia(3,3)-inertia(1,3)*inertia(2,3), & ! xy
       & inertia(2,2)*(inertia(1,1)+inertia(3,3))-inertia(1,2)**2-inertia(2,3)**2, &
       & inertia(1,1)*inertia(2,3)-inertia(1,2)*inertia(1,3), & ! yz
       & inertia(1,3)*inertia(2,2)-inertia(1,2)*inertia(3,2), & ! xz
       & inertia(1,1)*inertia(2,3)-inertia(1,2)*inertia(1,3), & ! yz
       & inertia(3,3)*(inertia(1,1)+inertia(2,2))-inertia(1,3)**2-inertia(2,3)**2],&
       & shape=[3, 3]) * (250.0_wp / (48.0_wp * totrad3**3 * adet**5)) &
       & * (-0.5_wp * keps * qtotal**2 / adet**2)
    do iat = 1, natom
       rad2 = rad(iat) * rad(iat)
       rad3 = rad2 * rad(iat)
       vec(:) = xyz(:, iat) - center
       gradient(:, iat) = gradient(:, iat) + rad3 * matmul(aderiv, vec)
    end do
References xtb_mctc_math::matdet3x3().
Referenced by addgradient().
addbornderiv()
pure subroutine xtb_solv_gbsa::addbornderiv (class(tborn), intent(in) self, real(wp), dimension(self%nat), intent(in) q, real(wp), intent(out) gborn, real(wp), intent(out) ghb, real(wp), dimension(3,self%nat,self%nat), intent(inout) dAmatdr, real(wp), dimension(3,self%nat), intent(inout) Afac) private
Definition at line 1095 of file gbsa.f90.
    implicit none
    class(TBorn), intent(in) :: self
    real(wp), intent(in)    :: q(self%nat)
    real(wp), intent(inout) :: dAmatdr(3,self%nat,self%nat)
    real(wp), intent(inout) :: Afac(3,self%nat)
    real(wp), intent(out)   :: gborn
    real(wp), intent(out)   :: ghb
    integer :: i,j,k,nnj
    integer :: kk
    real(wp), parameter :: a13=1._wp/3._wp
    real(wp), parameter :: a4=0.25_wp
    real(wp), parameter :: sqrt2pi = sqrt(2.0_wp/pi)
    real(wp) :: aa,r2,fgb,fgb2,br3
    real(wp) :: qq,dd,expd,dfgb,dfgb2,dfgb3,ap,bp,qfg
    real(wp) :: gg,expa,aii,egb
    real(wp) :: r0vdw,r01,r02,ar02
    real(wp) :: grddbi,grddbj
    real(wp) :: dr(3),r
    egb = 0._wp
    select case(self%kernel)
    case(gbkernel%still)
       if (self%lsalt) then
          call addbornderivsaltstill(self%nat, self%ntpair, self%ppind, &
             & self%ddpair, q, self%kappa, self%brad, self%brdr, self%ionscr, &
             & self%discr, gborn, damatdr, afac)
       else
          call addbornderivstill(self%nat, self%ntpair, self%ppind, self%ddpair, &
             & q, self%keps, self%brad, self%brdr, gborn, damatdr, afac)
       endif
    case(gbkernel%p16)
    end select
    if (self%lhb) then
       call addhbondderiv(self%nat, q, self%hbw, self%dhbdw, self%dsdrt, &
          & ghb, damatdr)
    endif
References xtb_solv_kernel::addbornderivsaltstill(), xtb_solv_kernel::addbornderivstill(), addhbondderiv(), xtb_solv_kernel::gbkernel, and xtb_mctc_constants::pi.
addbornmatrix()
subroutine xtb_solv_gbsa::addbornmatrix (class(tborn), intent(inout) self, type(tenvironment), intent(inout) env, integer, dimension(:), intent(in) num, real(wp), dimension(:, :), intent(in) xyz, real(wp), dimension(:, :), intent(inout) bornMat) private
Parameters
[in,out] self Instance of the solvation model
[in,out] env Computation environment
[in] num Atomic numbers
[in] xyz Cartesian coordinates
[in,out] bornmat Born interaction matrix
Definition at line 448 of file gbsa.f90.
    class(TBorn), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    integer, intent(in) :: num(:)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(inout) :: bornMat(:, :)
    integer :: iat
    select case(self%kernel)
    case(gbkernel%still)
       if (self%lsalt) then
          call addbornmatsaltstill(self%nat, self%ntpair, self%ppind, self%ddpair, &
             & self%kappa, self%brad, self%ionscr, bornmat)
       else
          call addbornmatstill(self%nat, self%ntpair, self%ppind, self%ddpair, &
             & self%keps, self%brad, bornmat)
       end if
    case(gbkernel%p16)
       call addbornmatp16(self%nat, self%ntpair, self%ppind, self%ddpair, &
          & self%keps, self%brad, bornmat)
    end select
    ! compute the HB term
    if (self%lhb) then
       do iat = 1, self%nat
          bornmat(iat, iat) = bornmat(iat, iat) + 2*self%hbw(iat)
       enddo
    endif
    ! ALPB shape dependent correction for charged systems
    if (self%alpbet > 0.0_wp) then
       bornmat(:self%nat, :self%nat) = bornmat(:self%nat, :self%nat) &
          & + self%keps * self%alpbet / self%aDet
    end if
References xtb_solv_kernel::addbornmatp16(), xtb_solv_kernel::addbornmatsaltstill(), xtb_solv_kernel::addbornmatstill(), and xtb_solv_kernel::gbkernel.
addgradient()
subroutine xtb_solv_gbsa::addgradient (class(tborn), intent(inout) self, type(tenvironment), intent(inout) env, integer, dimension(:), intent(in) num, real(wp), dimension(:, :), intent(in) xyz, real(wp), dimension(:), intent(in) qat, real(wp), dimension(:), intent(in) qsh, real(wp), dimension(:, :), intent(inout) gradient) private
Calculate derivatives of solvation energy.
Parameters
[in,out] self Instance of the solvation model
[in,out] env Computation environment
[in] num Atomic numbers
[in] xyz Cartesian coordinates
[in] qat Atomic partial charges
[in] qsh Shell-resolved partial charges
[in,out] gradient Molecular gradient
Definition at line 603 of file gbsa.f90.
    character(len=*), parameter :: source = 'solv_gbsa_addGradient'
    class(TBorn), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    integer, intent(in) :: num(:)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in) :: qat(:)
    real(wp), intent(in) :: qsh(:)
    real(wp), intent(inout) :: gradient(:, :)
    real(wp) :: gborn, ghb
    select case(self%kernel)
    case(gbkernel%still)
       if (self%lsalt) then
          call addgradientsaltstill(self%nat, self%ntpair, self%ppind, self%ddpair, &
             & qat, self%kappa, self%brad, self%brdr, self%ionscr, self%discr, &
             & gborn, gradient)
       else
          call addgradientstill(self%nat, self%ntpair, self%ppind, self%ddpair, &
             & qat, self%keps, self%brad, self%brdr, gborn, gradient)
       end if
    case(gbkernel%p16)
       call addgradientp16(self%nat, self%ntpair, self%ppind, self%ddpair, &
          & qat, self%keps, self%brad, self%brdr, gborn, gradient)
    end select
    gradient = gradient + self%dsdr
    if (self%lhb) then
       call addgradienthbond(self%nat, self%at, qat, self%hbw, self%dhbdw, &
          & self%dsdrt, ghb, gradient)
    else
       ghb = 0.0_wp
    endif
    if (self%alpbet > 0.0_wp) then
       gborn = gborn + sum(qat)**2 * self%alpbet / self%aDet * self%kEps
       call addadetderiv(self%nat, xyz, self%vdwr, self%kEps*self%alpbet, &
          & qat, gradient)
    end if
References addadetderiv(), addgradienthbond(), xtb_solv_kernel::addgradientp16(), xtb_solv_kernel::addgradientsaltstill(), xtb_solv_kernel::addgradientstill(), and xtb_solv_kernel::gbkernel.
addgradienthbond()
pure subroutine, public xtb_solv_gbsa::addgradienthbond (integer, intent(in) nat, integer, dimension(:), intent(in) at, real(wp), dimension(:), intent(in) q, real(wp), dimension(:), intent(in) hbw, real(wp), dimension(:), intent(in) dhbdw, real(wp), dimension(:, :, :), intent(in) dsdrt, real(wp), intent(out) ghb, real(wp), dimension(:, :), intent(inout) gradient)
Compute contributions to energy and gradient for hydrogen bonding correction.
Parameters
[in] nat Number of atoms
[in] at Atomic numbers
[in] q Partial charges
[in] hbw Actual hydrogen bonding contribution
[in] dhbdw Actual hydrogen bonding contribution
[in] dsdrt Derivative of the surface area w.r.t. to cartesian coordinates
[out] ghb Hydrogen bonding energy
[in,out] gradient Gradient of hydrogen bonding energy
Definition at line 1047 of file gbsa.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: at(:)
    real(wp), intent(in) :: q(:)
    real(wp), intent(in) :: hbw(:)
    real(wp), intent(in) :: dhbdw(:)
    real(wp), intent(in) :: dsdrt(:, :, :)
    real(wp), intent(out)   :: ghb
    real(wp), intent(inout) :: gradient(:, :)
    integer  :: i, j
    real(wp) :: dhbed
    real(wp) :: qq
    ghb=0.0_wp
    do i = 1, nat
       qq = q(i)*q(i)
       ghb = ghb + hbw(i)*qq
    enddo
    do i = 1, nat
       dhbed = dhbdw(i)
       if(abs(dhbed).le.0.0_wp) cycle
       dhbed=dhbed*q(i)*q(i)
       do j = 1, nat
          gradient(:, j) = gradient(:, j) + dsdrt(:, j, i)*dhbed
       enddo
    enddo
Referenced by addgradient().
addhbondderiv()
pure subroutine, public xtb_solv_gbsa::addhbondderiv (integer, intent(in) nat, real(wp), dimension(:), intent(in) q, real(wp), dimension(:), intent(in) hbw, real(wp), dimension(:), intent(in) dhbdw, real(wp), dimension(:, :, :), intent(in) dsdrt, real(wp), intent(out) ghb, real(wp), dimension(:, :, :), intent(inout) dAmatdr)
Definition at line 1140 of file gbsa.f90.
    integer, intent(in) :: nat
    real(wp), intent(in) :: q(:)
    real(wp), intent(in) :: hbw(:)
    real(wp), intent(in) :: dhbdw(:)
    real(wp), intent(in) :: dsdrt(:, :, :)
    real(wp), intent(out) :: ghb
    real(wp), intent(inout) :: dAmatdr(:, :, :)
    integer  :: i,j
    real(wp) :: dhbed
    real(wp) :: qq
    ghb=0.0_wp
    do i = 1, nat
       qq = q(i)*q(i)
       ghb = ghb + hbw(i)*qq
    enddo
    do i = 1, nat
       dhbed=dhbdw(i)
       if(abs(dhbed).le.0.0_wp) cycle
       dhbed=dhbed*q(i)
       damatdr(:,:,i) = damatdr(:,:,i) + dsdrt(:,:,i)*dhbed
    enddo
Referenced by addbornderiv().
addshift()
subroutine xtb_solv_gbsa::addshift (class(tborn), intent(inout) self, type(tenvironment), intent(inout) env, real(wp), dimension(:), intent(in) qat, real(wp), dimension(:), intent(in) qsh, real(wp), dimension(:), intent(inout) atomicShift, real(wp), dimension(:), intent(inout) shellShift) private
Add potential shift.
Parameters
[in,out] self Instance of the solvation model
[in,out] env Computation environment
[in] qat Atomic partial charges
[in] qsh Shell-resolved partial charges
[in,out] atomicshift Atomic potential shift
[in,out] shellshift Shell-resolved potential shift
Definition at line 498 of file gbsa.f90.
    character(len=*), parameter :: source = 'solv_gbsa_addShift'
    class(TBorn), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: qat(:)
    real(wp), intent(in) :: qsh(:)
    real(wp), intent(inout) :: atomicShift(:)
    real(wp), intent(inout) :: shellShift(:)
    call mctc_symv(self%bornMat, qat, self%shift)
    atomicshift(:) = atomicshift + self%shift
compute_fhb()
pure subroutine, public xtb_solv_gbsa::compute_fhb (integer, intent(in) nat, real(wp), dimension(:), intent(in) hbmag, real(wp), dimension(:), intent(in) vdwsa, real(wp), dimension(:), intent(in) sasa, real(wp), dimension(:), intent(out) hbw, real(wp), dimension(:), intent(out) dhbdw)
Compute contributions to potential for hydrogen bonding correction.
Parameters
[in] nat Number of atoms
[in] hbmag Hydrogen bonding strength
[in] vdwsa Van-der-Waals radius
[in] sasa Surface area including surface tension
[out] hbw Actual hydrogen bonding contribution
[out] dhbdw Actual hydrogen bonding contribution
Definition at line 1004 of file gbsa.f90.
    integer, intent(in) :: nat
    real(wp), intent(in) :: hbmag(:)
    real(wp), intent(in) :: vdwsa(:)
    real(wp), intent(in) :: sasa(:)
    real(wp), intent(out) :: hbw(:)
    real(wp), intent(out) :: dhbdw(:)
    integer  :: i
    integer  :: iz, nhb
    real(wp) :: hbed, dhbed
    real(wp) :: smaxd, sasad, sasaw
    real(wp) :: sfw, dsfw, w3, w2, w1
    integer  :: j
    real(wp) :: wbh, wah
    hbw(:) = 0.0_wp
    dhbdw(:) = 0.0_wp
    do i = 1, nat
       ! SASA-D for HB
       smaxd = 1.0_wp/(vdwsa(i)*vdwsa(i))
       sasad = sasa(i)*smaxd
       hbw(i) = hbmag(i)*sasad
       dhbdw(i) = hbmag(i)*smaxd
    enddo
Referenced by update().
getadet()
subroutine, public xtb_solv_gbsa::getadet (integer, intent(in) nAtom, real(wp), dimension(:, :), intent(in) xyz, real(wp), dimension(:), intent(in) rad, real(wp), intent(out) aDet)
Parameters
[in] natom Number of atoms
[in] xyz Cartesian coordinates
[in] rad Atomic radii
[out] adet Shape descriptor of the structure
Definition at line 664 of file gbsa.f90.
    integer, intent(in) :: nAtom
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in) :: rad(:)
    real(wp), intent(out) :: aDet
    integer :: iat
    real(wp) :: r2, rad2, rad3, totRad3, vec(3), center(3), inertia(3, 3)
    real(wp), parameter :: tof = 2.0_wp/5.0_wp, unity(3, 3) = reshape(&
       & [1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp], &
       & [3, 3])
    totrad3 = 0.0_wp
    center(:) = 0.0_wp
    do iat = 1, natom
       rad2 = rad(iat) * rad(iat)
       rad3 = rad2 * rad(iat)
       totrad3 = totrad3 + rad3
       center(:) = center + xyz(:, iat) * rad3
    end do
    center = center / totrad3
    inertia(:, :) = 0.0_wp
    do iat = 1, natom
       rad2 = rad(iat) * rad(iat)
       rad3 = rad2 * rad(iat)
       vec(:) = xyz(:, iat) - center
       r2 = sum(vec**2)
       inertia(:, :) = inertia + rad3 * ((r2 + tof*rad2) * unity &
          & - spread(vec, 1, 3) * spread(vec, 2, 3))
    end do
    adet = sqrt(matdet3x3(inertia)**(1.0_wp/3.0_wp)/(tof*totrad3))
References xtb_mctc_math::matdet3x3().
Referenced by update().
getdebyehueckel()
pure subroutine, public xtb_solv_gbsa::getdebyehueckel (integer, intent(in) nat, real(wp), intent(in) dielectricConst, real(wp), intent(in) kappa, real(wp), intent(in) ionRad, real(wp), dimension(:), intent(in) brad, real(wp), dimension(:), intent(out) ionscr, real(wp), dimension(:), intent(out) discr)
compute the Debye-Hueckel ion exclusion term
Definition at line 780 of file gbsa.f90.
    integer, intent(in) :: nat
    real(wp), intent(in) :: kappa
    real(wp), intent(in) :: dielectricConst
    real(wp), intent(in) :: brad(:)
    real(wp), intent(in) :: ionRad
    real(wp), intent(out) :: ionscr(:)
    real(wp), intent(out) :: discr(:)
    integer :: i
    real(wp) :: aa, gg
    aa=0.5_wp/dielectricconst
    do i = 1, nat
       gg=kappa*(brad(i)+ionrad)
       ionscr(i)=aa*exp(gg)/(1.0_wp+gg)
       discr(i)=ionscr(i)*kappa*gg/(1.0_wp+gg)
    enddo
Referenced by update().
getenergy()
subroutine xtb_solv_gbsa::getenergy (class(tborn), intent(inout) self, type(tenvironment), intent(inout) env, real(wp), dimension(:), intent(in) qat, real(wp), dimension(:), intent(in) qsh, real(wp), intent(out) energy) private
Calculate solvation energy.
Parameters
[in,out] self Instance of the solvation model
[in,out] env Computation environment
[in] qat Atomic partial charges
[in] qsh Shell-resolved partial charges
[out] energy Total solvation energy
Definition at line 528 of file gbsa.f90.
    character(len=*), parameter :: source = 'solv_gbsa_getEnergy'
    class(TBorn), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: qat(:)
    real(wp), intent(in) :: qsh(:)
    real(wp), intent(out) :: energy
    call mctc_symv(self%bornMat, qat, self%shift, alpha=0.5_wp)
    energy = mctc_dot(qat, self%shift) + self%gsasa + self%gshift
getenergyparts()
subroutine xtb_solv_gbsa::getenergyparts (class(tborn), intent(inout) self, type(tenvironment), intent(inout) env, real(wp), dimension(:), intent(in) qat, real(wp), dimension(:), intent(in) qsh, real(wp), intent(out) gborn, real(wp), intent(out) ghb, real(wp), intent(out) gsasa, real(wp), intent(out) gshift) private
Calculate solvation energy.
Parameters
[in,out] self Instance of the solvation model
[in,out] env Computation environment
[in] qat Atomic partial charges
[in] qsh Shell-resolved partial charges
[out] gborn Born solvation energy
[out] ghb Hydrogen bonding energy
[out] gsasa Non-polar surface energy
[out] gshift State specific shift
Definition at line 555 of file gbsa.f90.
    character(len=*), parameter :: source = 'solv_gbsa_getEnergy'
    class(TBorn), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: qat(:)
    real(wp), intent(in) :: qsh(:)
    real(wp), intent(out) :: gborn
    real(wp), intent(out) :: ghb
    real(wp), intent(out) :: gsasa
    real(wp), intent(out) :: gshift
    integer :: iat
    ghb = 0.0_wp
    if (self%lhb) then
       do iat = 1, self%nat
          ghb = ghb + self%hbw(iat) * qat(iat)**2
       end do
    end if
    call mctc_symv(self%bornMat, qat, self%shift, alpha=0.5_wp)
    gborn = mctc_dot(qat, self%shift) - ghb
    gsasa = self%gsasa
    gshift = self%gshift
initborn()
subroutine xtb_solv_gbsa::initborn (type(tborn), intent(out) self, type(tenvironment), intent(inout) env, integer, dimension(:), intent(in) num, real(wp), dimension(:), intent(in) vdwRad, real(wp), intent(in) dielectricConst, real(wp), intent(in) freeEnergyShift, real(wp), dimension(:), intent(in) descreening, real(wp), intent(in) bornScale, real(wp), intent(in) bornOffset, real(wp), dimension(:), intent(in) surfaceTension, real(wp), intent(in) probeRad, real(wp), intent(in) rCutoff, real(wp), intent(in) rOffset, integer, intent(in) nAng, real(wp), dimension(:), intent(in) hBondStrength, real(wp), intent(in) temperature, integer, intent(in) kernel, logical, intent(in) alpb, real(wp), intent(in), optional ionSt, real(wp), intent(in), optional ionRad) private
Initialize data straucture.
Parameters
[out] self Instance of the solvation model
[in,out] env Computation environment
[in] num Atomic numbers
[in] vdwrad Van-der-Waals Radii
[in] dielectricconst Dielectric constant of the solvent
[in] freeenergyshift State specific free energy offset
[in] descreening Dielectric descreening parameter
[in] bornscale Scaling factor for Born radii
[in] bornoffset Offset parameter for Born radii integration
[in] surfacetension Surface tension scaling
[in] proberad Probe radius of the solvent
[in] rcutoff Real-space cutoff for Born radii integration
[in] roffset Offset for surface integration cutoff
[in] nang Number of angular grid points for integration
[in] hbondstrength Hydrogen bond magnitude
[in] kernel Generalized Born interaction kernel
[in] alpb Use analytical linearized Poisson-Boltzmann model instead of GB
[in] ionst Ion strength
[in] ionrad Ion radius
Definition at line 220 of file gbsa.f90.
    character(len=*), parameter :: source = 'solv_gbsa_initBorn'
    type(TBorn), intent(out) :: self
    type(TEnvironment), intent(inout) :: env
    integer, intent(in) :: num(:)
    real(wp), intent(in) :: vdwRad(:)
    real(wp), intent(in) :: dielectricConst
    real(wp), intent(in) :: freeEnergyShift
    real(wp), intent(in) :: descreening(:)
    real(wp), intent(in) :: bornScale
    real(wp), intent(in) :: bornOffset
    real(wp), intent(in) :: surfaceTension(:)
    real(wp), intent(in) :: probeRad
    real(wp), intent(in) :: rCutoff
    real(wp), intent(in) :: rOffset
    integer, intent(in) :: nAng
    real(wp), intent(in) :: hBondStrength(:)
    real(wp), intent(in) :: temperature
    integer, intent(in) :: kernel
    logical, intent(in) :: alpb
    real(wp), intent(in), optional :: ionSt
    real(wp), intent(in), optional :: ionRad
    integer :: iat, izp, jat, ij, iang, ierr
    real(wp) :: r
    self%kernel = kernel
    self%gshift = freeenergyshift
    self%dielectricConst = dielectricconst
    if (alpb) then
       self%alpbet = 0.571412_wp / self%dielectricConst
    else
       self%alpbet = 0.0_wp
    end if
    self%keps = (1.0_wp/self%dielectricConst - 1.0_wp) / (1.0_wp + self%alpbet)
    self%nat = size(num)
    self%at = num
    self%ntpair = self%nat*(self%nat-1)/2
    allocate(self%ppind(2, self%ntpair))
    allocate(self%nnsas(self%nat))
    allocate(self%nnlistr(3, self%ntpair))
    allocate(self%nnlists(self%nat, self%nat))
    allocate(self%ddpair(4, self%ntpair))
    ij = 0
    do iat = 1, self%nat
       do jat = 1, iat-1
          ij = ij+1
          self%ppind(1, ij) = iat
          self%ppind(2, ij) = jat
       enddo
    enddo
    if (present(ionst)) then
       self%lsalt = ionst > 0.0_wp
    else
       self%lsalt = .false.
    end if
    if (self%lsalt) then
       allocate(self%ionscr(self%nat))
       allocate(self%discr(self%nat))
       if (present(ionrad)) then
          self%ionRad = ionrad
       else
          self%ionRad = 0.0_wp
       end if
       self%kappa = sqrt(self%dielectricConst*temperature*kappaconst/ionst)*aatoau
       self%kappa = 1.0_wp/self%kappa
    end if
    self%lrcut = rcutoff
    self%bornScale = bornscale
    allocate(self%vdwr(self%nat))
    allocate(self%rho(self%nat))
    allocate(self%svdw(self%nat))
    allocate(self%brad(self%nat))
    allocate(self%brdr(3, self%nat, self%nat))
    do iat = 1, self%nat
       izp = num(iat)
       self%vdwr(iat) = vdwrad(izp)
       self%rho(iat) = self%vdwr(iat) * descreening(izp)
       self%svdw(iat) = self%vdwr(iat) - bornoffset
    end do
    allocate(self%vdwsa(self%nat))
    allocate(self%trj2(2, self%nat))
    allocate(self%wrp(self%nat))
    allocate(self%gamsasa(self%nat))
    allocate(self%sasa(self%nat))
    allocate(self%dsdr(3, self%nat))
    allocate(self%dsdrt(3, self%nat, self%nat))
    do iat = 1, self%nat
       izp = num(iat)
       self%vdwsa(iat) = vdwrad(izp) + proberad
       self%trj2(1, iat) = (self%vdwsa(iat)-w)**2
       self%trj2(2, iat) = (self%vdwsa(iat)+w)**2
       r=self%vdwsa(iat)+w
       self%wrp(iat)=(0.25_wp/w+ &
          &            3.0_wp*ah3*(0.2_wp*r*r-0.5_wp*r*self%vdwsa(iat)+ &
          &            self%vdwsa(iat)*self%vdwsa(iat)/3.0_wp))*r*r*r
       r=self%vdwsa(iat)-w
       self%wrp(iat)=self%wrp(iat)-(0.25/w+ &
          &    3.0_wp*ah3*(0.2_wp*r*r-0.5_wp*r*self%vdwsa(iat)+ &
          &            self%vdwsa(iat)*self%vdwsa(iat)/3.0_wp))*r*r*r
       self%gamsasa(iat) = surfacetension(izp)
    end do
    self%srcut = 2 * (w + maxval(self%vdwsa)) + roffset
    call bisectsearch(iang, gridsize, nang)
    allocate(self%angGrid(3, gridsize(iang)))
    allocate(self%angWeight(gridsize(iang)))
    call getanggrid(iang, self%angGrid, self%angWeight, ierr)
    allocate(self%hbmag(self%nat))
    do iat = 1, self%nat
       izp = num(iat)
       self%hbmag(iat) = hbondstrength(izp)
    end do
    self%lhb = any(self%hbmag < 0.0_wp)
    if (self%lhb) then
       allocate(self%hbw(self%nat))
       allocate(self%dhbdw(self%nat))
    end if
    allocate(self%shift(self%nat))
    allocate(self%bornMat(self%nat, self%nat))
update()
subroutine xtb_solv_gbsa::update (class(tborn), intent(inout) self, type(tenvironment), intent(inout) env, integer, dimension(:), intent(in) num, real(wp), dimension(:, :), intent(in) xyz) private
Parameters
[in,out] self Instance of the solvation model
[in,out] env Computation environment
[in] num Atomic numbers
[in] xyz Cartesian coordinates
Definition at line 395 of file gbsa.f90.
    class(TBorn), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    integer, intent(in) :: num(:)
    real(wp), intent(in) :: xyz(:, :)
    ! initialize the neighbor list
    call update_nnlist_gbsa(self%nat, self%ntpair, self%ppind, xyz, &
       & self%lrcut, self%srcut, self%nnsas, self%nnlists, self%nnrad, &
       & self%nnlistr, self%ddpair, .false.)
    call compute_bornr(self%nat, self%nnrad, self%nnlistr, self%ddpair, &
       & self%vdwr, self%rho, self%svdw, self%bornScale, self%brad, self%brdr)
    ! compute solvent accessible surface and its derivatives
    call compute_numsa(self%nat, self%nnsas, self%nnlists, xyz, self%vdwsa, &
       & self%wrp, self%trj2, self%angWeight, self%angGrid, &
       & self%sasa, self%dsdrt)
    ! contract surface gradient
    call mctc_gemv(self%dsdrt, self%gamsasa, self%dsdr)
    self%gsasa = mctc_dot(self%sasa, self%gamsasa)
    ! compute the Debye-Hueckel ion exclusion term
    if (self%lsalt) then
       call getdebyehueckel(self%nat, self%dielectricConst, self%kappa, &
          & self%ionRad, self%brad, self%ionscr, self%discr)
    end if
    ! compute the HB term
    if (self%lhb) then
       call compute_fhb(self%nat, self%hbmag, self%vdwsa, self%sasa, &
          & self%hbw, self%dhbdw)
    end if
    if (self%alpbet > 0.0_wp) then
       call getadet(self%nat, xyz, self%vdwr, self%aDet)
    end if
    self%bornMat(:, :) = 0.0_wp
    call self%addBornMatrix(env, num, xyz, self%bornMat)
References xtb_solv_born::compute_bornr(), compute_fhb(), xtb_solv_sasa::compute_numsa(), getadet(), getdebyehueckel(), and update_nnlist_gbsa().
update_nnlist_gbsa()
subroutine, public xtb_solv_gbsa::update_nnlist_gbsa (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) xyz, real(wp), intent(in) lrcut, real(wp), intent(in) srcut, integer, dimension(:), intent(out) nnsas, integer, dimension(:, :), intent(out) nnlists, integer, intent(out) nnrad, integer, dimension(:, :), intent(out) nnlistr, real(wp), dimension(:, :), intent(out) ddpair, logical, intent(in) parallel)
setup a pairlist and compute pair distances of all neighbors
Definition at line 806 of file gbsa.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in) :: lrcut
    real(wp), intent(in) :: srcut
    integer, intent(out) :: nnsas(:)
    integer, intent(out) :: nnlists(:, :)
    integer, intent(out) :: nnrad
    integer, intent(out) :: nnlistr(:, :)
    real(wp), intent(out) :: ddpair(:, :)
    logical, intent(in) :: parallel
    if (parallel) then
       call update_nnlist_gbsa_parallel(nat, ntpair, ppind, xyz, &
          & lrcut, srcut, nnsas, nnlists, nnrad, nnlistr, ddpair)
    else
       call update_nnlist_gbsa_sequential(nat, ntpair, ppind, xyz, &
          & lrcut, srcut, nnsas, nnlists, nnrad, nnlistr, ddpair)
    endif
References update_nnlist_gbsa_parallel(), and update_nnlist_gbsa_sequential().
Referenced by update().
update_nnlist_gbsa_parallel()
subroutine xtb_solv_gbsa::update_nnlist_gbsa_parallel (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) xyz, real(wp), intent(in) lrcut, real(wp), intent(in) srcut, integer, dimension(:), intent(out) nnsas, integer, dimension(:, :), intent(out) nnlists, integer, intent(out) nnrad, integer, dimension(:, :), intent(out) nnlistr, real(wp), dimension(:, :), intent(out) ddpair) private
setup a pairlist and compute pair distances of all neighbors
Definition at line 834 of file gbsa.f90.
 !$ use omp_lib
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in) :: lrcut
    real(wp), intent(in) :: srcut
    integer, intent(out) :: nnsas(:)
    integer, intent(out) :: nnlists(:, :)
    integer, intent(out) :: nnrad
    integer, intent(out) :: nnlistr(:, :)
    real(wp), intent(out) :: ddpair(:, :)
    integer kk, i1, i2
    real(wp) rcutn2, lrcut2, srcut2
    real(wp) x, y, z, dr2
    integer ip, ip2, thrid, nproc
    integer, allocatable :: npid(:)
    integer, allocatable :: plisttr(:, :, :)
    integer, allocatable :: nntmp(:)
    integer, allocatable :: nnls(:, :)
    nproc=1
 !$ nproc=omp_get_max_threads()
    allocate(plisttr(3, ntpair, nproc), nnls(nat, nat))
    allocate(nntmp(nat), npid(nproc))
    npid = 0
    lrcut2 = lrcut*lrcut
    srcut2 = srcut*srcut
    nnsas=0
    nnlists=0
 !$omp parallel default(none) &
 !$omp&         shared ( xyz,lrcut2,srcut2,ntpair,ppind,nat,nnlists,nnsas,ddpair ) &
 !$omp&         private( i1,i2,x,y,z,dr2,ip,ip2,thrid,nntmp,nnls ) &
 !$omp&         shared ( plisttr, npid )
    ip=0
    ip2=0
    nntmp=0
    nnls=0
    thrid=1
 !$ thrid=omp_get_thread_num() + 1
 !$omp do
    do kk=1,ntpair
       i1=ppind(1,kk)
       i2=ppind(2,kk)
       x=xyz(1,i1)-xyz(1,i2)
       y=xyz(2,i1)-xyz(2,i2)
       z=xyz(3,i1)-xyz(3,i2)
       dr2=x**2+y**2+z**2
       ddpair(2,kk)=x
       ddpair(3,kk)=y
       ddpair(4,kk)=z
       ddpair(1,kk)=sqrt(dr2)
       if(dr2.lt.lrcut2) then
          ip = ip + 1
          plisttr(1,ip,thrid)=i1
          plisttr(2,ip,thrid)=i2
          plisttr(3,ip,thrid)=kk
          if(dr2.lt.srcut2) then
             nntmp(i1) = nntmp(i1) + 1
             nntmp(i2) = nntmp(i2) + 1
             nnls(nntmp(i1),i1)=i2
             nnls(nntmp(i2),i2)=i1
          endif
       endif
    enddo
 !$omp end do
    npid(thrid)=ip
 !$omp critical
    do i1=1,nat
       do i2=1,nntmp(i1)
          nnlists(nnsas(i1)+i2,i1)=nnls(i2,i1)
       enddo
       nnsas(i1)=nnsas(i1)+nntmp(i1)
    enddo
 !$omp end critical
 !$omp end parallel
    nnrad=0
    do thrid=1,nproc
       do kk = nnrad+1,nnrad+npid(thrid)
          nnlistr(1:3,kk)=plisttr(1:3,kk-nnrad,thrid)
       enddo
       nnrad = nnrad + npid(thrid)
    enddo
    deallocate(nntmp,nnls)
Referenced by update_nnlist_gbsa().
update_nnlist_gbsa_sequential()
pure subroutine xtb_solv_gbsa::update_nnlist_gbsa_sequential (integer, intent(in) nat, integer, intent(in) ntpair, integer, dimension(:, :), intent(in) ppind, real(wp), dimension(:, :), intent(in) xyz, real(wp), intent(in) lrcut, real(wp), intent(in) srcut, integer, dimension(:), intent(out) nnsas, integer, dimension(:, :), intent(out) nnlists, integer, intent(out) nnrad, integer, dimension(:, :), intent(out) nnlistr, real(wp), dimension(:, :), intent(out) ddpair) private
setup a pairlist and compute pair distances of all neighbors
Definition at line 932 of file gbsa.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: ntpair
    integer, intent(in) :: ppind(:, :)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in) :: lrcut
    real(wp), intent(in) :: srcut
    integer, intent(out) :: nnsas(:)
    integer, intent(out) :: nnlists(:, :)
    integer, intent(out) :: nnrad
    integer, intent(out) :: nnlistr(:, :)
    real(wp), intent(out) :: ddpair(:, :)
    integer kk, i1, i2
    real(wp) rcutn2, lrcut2, srcut2
    real(wp) x, y, z, dr2
    integer ip, ip2
    integer, allocatable :: nntmp(:)
    integer, allocatable :: nnls(:, :)
    allocate(nnls(nat, nat))
    allocate(nntmp(nat))
    lrcut2 = lrcut*lrcut
    srcut2 = srcut*srcut
    nnsas=0
    nnlists=0
    ip=0
    ip2=0
    nntmp=0
    nnls=0
    do kk=1,ntpair
       i1=ppind(1,kk)
       i2=ppind(2,kk)
       x=xyz(1,i1)-xyz(1,i2)
       y=xyz(2,i1)-xyz(2,i2)
       z=xyz(3,i1)-xyz(3,i2)
       dr2=x**2+y**2+z**2
       ddpair(2,kk)=x
       ddpair(3,kk)=y
       ddpair(4,kk)=z
       ddpair(1,kk)=sqrt(dr2)
       if(dr2.lt.lrcut2) then
          ip = ip + 1
          nnlistr(1,ip)=i1
          nnlistr(2,ip)=i2
          nnlistr(3,ip)=kk
          if(dr2.lt.srcut2) then
             nntmp(i1) = nntmp(i1) + 1
             nntmp(i2) = nntmp(i2) + 1
             nnls(nntmp(i1),i1)=i2
             nnls(nntmp(i2),i2)=i1
          endif
       endif
    enddo
    nnrad = ip
    do i1=1,nat
       do i2=1,nntmp(i1)
          nnlists(nnsas(i1)+i2,i1)=nnls(i2,i1)
       enddo
       nnsas(i1)=nnsas(i1)+nntmp(i1)
    enddo
    deallocate(nntmp,nnls)
Referenced by update_nnlist_gbsa().
Variable Documentation
ah0
real(wp), parameter xtb_solv_gbsa::ah0 = 0.5_wp private
Definition at line 205 of file gbsa.f90.
    real(wp), parameter :: ah0 = 0.5_wp
ah1
real(wp), parameter xtb_solv_gbsa::ah1 = 3._wp/(4.0_wp*w) private
Definition at line 206 of file gbsa.f90.
    real(wp), parameter :: ah1 = 3._wp/(4.0_wp*w)
ah3
real(wp), parameter xtb_solv_gbsa::ah3 = -1._wp/(4.0_wp*w3) private
Definition at line 207 of file gbsa.f90.
    real(wp), parameter :: ah3 = -1._wp/(4.0_wp*w3)
Referenced by xtb_solv_gbsa::init::initborn().
gammas
real(wp), parameter xtb_solv_gbsa::gammas = 1.0e-5_wp private
Surface tension (in au)
Definition at line 210 of file gbsa.f90.
    real(wp), parameter :: gammas = 1.0e-5_wp
kappaconst
real(wp), parameter xtb_solv_gbsa::kappaconst = 0.7897e-3_wp private
Salt screening.
Definition at line 213 of file gbsa.f90.
    real(wp), parameter :: kappaConst = 0.7897e-3_wp
Referenced by xtb_solv_gbsa::init::initborn().
w
real(wp), parameter xtb_solv_gbsa::w = 0.3_wp*aatoau private
Smoothing dielectric function parameters.
Definition at line 203 of file gbsa.f90.
    real(wp), parameter :: w = 0.3_wp*aatoau
Referenced by xtb_solv_gbsa::init::initborn().
w3
real(wp), parameter xtb_solv_gbsa::w3 = w*(w*w) private
Definition at line 204 of file gbsa.f90.
    real(wp), parameter :: w3 = w*(w*w)