My Project: xtb_mctc_timings Module Reference
xtb_mctc_timings Module Reference
Functions/Subroutines
subroutine, public prtiming (i, inmsg)
character(len=31) function prtimestring (mode)
subroutine, public prdate (mode)
subroutine, public init_timing (i, verb)
subroutine, public start_timing_run
subroutine, public stop_timing_run
subroutine, public start_timing (i)
subroutine, public stop_timing (i)
subroutine, private timing (time_cpu, time_wall)
Variables
real(wp), dimension(:), allocatable, private timing_wall
real(wp), dimension(:), allocatable, private timing_cpu
integer, private timing_max
logical, private verbose = .false.
character(len=8), private start_date
character(len=8), private stop_date
character(len=10), private start_time
character(len=10), private stop_time
character(len=5), private start_zone
character(len=5), private stop_zone
integer(int64), dimension(8), private start_values
integer(int64), dimension(8), private stop_values
Function/Subroutine Documentation
init_timing()
subroutine, public xtb_mctc_timings::init_timing (integer, intent(in) i, logical, intent(in), optional verb)
Definition at line 153 of file mctc_timings.f90.
    implicit none
    integer,intent(in) :: i
    logical,intent(in),optional :: verb
    if (allocated(timing_wall)) deallocate(timing_wall)
    if (allocated(timing_cpu))  deallocate(timing_cpu)
    if (present(verb)) verbose = verb
    timing_max = i
    allocate( timing_wall(i),  &
    &         timing_cpu(i),  &
    &         source=0.0_wp )
References timing_cpu, timing_max, timing_wall, and verbose.
Referenced by mctc_init().
prdate()
subroutine, public xtb_mctc_timings::prdate (character, intent(in) mode)
Definition at line 134 of file mctc_timings.f90.
    implicit none
    character,intent(in) :: mode
    character(len=*),parameter :: outfmt = '('' * '',a,1x,a)'
    character(len=8)  :: date
    character(len=10) :: time
    character(len=5)  :: zone
    character(len=31) :: timestring
    integer(int64) :: values(8)
    select case(mode)
    case('S','s')
    write(output_unit,outfmt) 'started run on', prtimestring(mode)
    case('E','e')
    write(output_unit,outfmt) 'finished run on', prtimestring(mode)
    case default
    write(output_unit,outfmt) 'current time:', prtimestring(mode)
    end select
References prtimestring().
Referenced by xtb_prog_main::xtbmain(), xtb_prog_thermo::xtbthermo(), and xtb_prog_topology::xtbtopology().
prtimestring()
character(len=31) function xtb_mctc_timings::prtimestring (character, intent(in) mode)
Definition at line 109 of file mctc_timings.f90.
    character,intent(in) :: mode
    character(len=*),parameter :: timefmt = &
    &  '(a,''/'',a,''/'',a,1x,''at'',1x,a,'':'',a,'':'',a)'
    character(len=8)  :: date
    character(len=10) :: time
    character(len=5)  :: zone
    character(len=31) :: timestring
    select case(mode)
    case('S','s')
    write(timestring,timefmt) &
    &   start_date(:4),start_date(5:6),start_date(7:), &
    &   start_time(:2),start_time(3:4),start_time(5:)
    case('E','e')
    write(timestring,timefmt) &
    &   stop_date(:4),stop_date(5:6),stop_date(7:), &
    &   stop_time(:2),stop_time(3:4),stop_time(5:)
    case default
    call date_and_time(date,time,zone)
    write(timestring,timefmt) &
    &   date(:4),date(5:6),date(7:), &
    &   time(:2),time(3:4),time(5:)
    end select
References start_date, start_time, stop_date, and stop_time.
Referenced by xtb_setmod::open_set(), prdate(), and xtb_prog_main::xtbmain().
prtiming()
subroutine, public xtb_mctc_timings::prtiming (integer, intent(in) i, character(len=*), intent(in), optional inmsg)
Definition at line 47 of file mctc_timings.f90.
    implicit none
    integer,intent(in) :: i
    character(len=*),intent(in),optional :: inmsg
    character(len=:),allocatable :: msg
    real(wp) :: cputime,walltime
    integer(int64) ::  cpudays, cpuhours, cpumins
    integer(int64) :: walldays,wallhours,wallmins
 !                      <7-------> <5---------> <7-----------> <10------------>
 !  '(1x,a,1x,"time:",1x,5i,1x,"d",1x,2i,1x,"h",1x,2i,1x,"min",1x,f5.2,1x,"sec")'
 !                     '(5i,1x,"d")'
 !                             '(a,1x,2i,1x,"h")'
 !                                            '(1x,2i,1x,"min")'
 !                                                           '(1x,f5.2,1x,"sec")'
 !  '(1x,a,1x,"time:",1x,a)'
    if (present(inmsg)) then
       msg = inmsg
    else
       msg = '*'
    endif
    !           DAYS   HOURS   MINUTES   SECONDS
    ! DAYS        1     1/24    1/1440   1/86400
    ! HOURS      24      1       1/60     1/3600
    ! MINUTES   1440    60        1        1/60
    ! SECONDS  86400   3600      60         1
    cputime = timing_cpu(i)
 !  if (cputime.ge.86400._wp) then
       cpudays = int(cputime/86400._wp)
       cputime = cputime - cpudays*86400._wp
 !  endif
 !  if (cputime.ge.3600._wp) then
       cpuhours = int(cputime/3600._wp)
       cputime = cputime - cpuhours*3600._wp
 !  endif
 !  if (cputime.ge.60._wp) then
       cpumins = int(cputime/60._wp)
       cputime = cputime - cpumins*60._wp
 !  endif
    walltime = timing_wall(i)
 !  if (walltime.ge.86400._wp) then
       walldays = int(walltime/86400._wp)
       walltime = walltime - walldays*86400._wp
 !  endif
 !  if (walltime.ge.3600._wp) then
       wallhours = int(walltime/3600._wp)
       walltime = walltime - wallhours*3600._wp
 !  endif
 !  if (walltime.ge.60._wp) then
       wallmins = int(walltime/60._wp)
       walltime = walltime - wallmins*60._wp
 !  endif
    if (verbose) then
       write(output_unit,'(1x,a,":")') msg
       write(output_unit,'(" * wall-time: ",i5," d, ",i2," h, ",i2," min, ",f6.3," sec")') walldays,wallhours,wallmins,walltime
       write(output_unit,'(" *  cpu-time: ",i5," d, ",i2," h, ",i2," min, ",f6.3," sec")')  cpudays, cpuhours, cpumins, cputime
       write(output_unit,'(1x,"*",1x,"ratio c/w:",1x,f9.3,1x,"speedup")') timing_cpu(i)/timing_wall(i)
    else
       write(output_unit,'(1x,a,1x,"time: ",i5," d, ",i2," h, ",i2," min, ",f6.3," sec")') msg,walldays,wallhours,wallmins,walltime
    endif
References timing_cpu, timing_wall, and verbose.
Referenced by xtb_prog_main::xtbmain(), xtb_prog_thermo::xtbthermo(), and xtb_prog_topology::xtbtopology().
start_timing()
subroutine, public xtb_mctc_timings::start_timing (integer, intent(in) i)
Definition at line 174 of file mctc_timings.f90.
    implicit none
    integer,intent(in) :: i
    real(wp) :: time_cpu
    real(wp) :: time_wall
    call timing(time_cpu,time_wall)
    timing_cpu(i) = timing_cpu(i) - time_cpu
    timing_wall(i) = timing_wall(i) - time_wall
References timing(), timing_cpu, and timing_wall.
Referenced by mctc_init(), and xtb_prog_main::xtbmain().
start_timing_run()
subroutine, public xtb_mctc_timings::start_timing_run
Definition at line 166 of file mctc_timings.f90.
    call date_and_time(start_date,start_time,start_zone,start_values)
References start_date, start_time, start_values, and start_zone.
Referenced by mctc_init().
stop_timing()
subroutine, public xtb_mctc_timings::stop_timing (integer, intent(in) i)
Definition at line 184 of file mctc_timings.f90.
    implicit none
    integer,intent(in) :: i
    real(wp) :: time_cpu
    real(wp) :: time_wall
    call timing(time_cpu,time_wall)
    timing_cpu(i) = timing_cpu(i) + time_cpu
    timing_wall(i) = timing_wall(i) + time_wall
References timing(), timing_cpu, and timing_wall.
Referenced by xtb_prog_main::xtbmain(), xtb_prog_thermo::xtbthermo(), and xtb_prog_topology::xtbtopology().
stop_timing_run()
subroutine, public xtb_mctc_timings::stop_timing_run
Definition at line 170 of file mctc_timings.f90.
    call date_and_time(stop_date,stop_time,stop_zone,stop_values)
References stop_date, stop_time, stop_values, and stop_zone.
Referenced by xtb_prog_main::xtbmain(), xtb_prog_thermo::xtbthermo(), and xtb_prog_topology::xtbtopology().
timing()
subroutine, private xtb_mctc_timings::timing (real(wp), intent(out) time_cpu, real(wp), intent(out) time_wall) private
Definition at line 194 of file mctc_timings.f90.
    implicit none
    real(wp),intent(out) :: time_cpu
    real(wp),intent(out) :: time_wall
    integer(int64) :: time_count,time_rate,time_max
    call system_clock(time_count,time_rate,time_max)
    call cpu_time(time_cpu)
    time_wall = real(time_count,wp)/real(time_rate,wp)
References xtb_mctc_accuracy::wp.
Referenced by start_timing(), and stop_timing().
Variable Documentation
start_date
character(len=8), private xtb_mctc_timings::start_date private
Definition at line 38 of file mctc_timings.f90.
    character(len=8)  :: start_date,stop_date
Referenced by prtimestring(), and start_timing_run().
start_time
character(len=10), private xtb_mctc_timings::start_time private
Definition at line 39 of file mctc_timings.f90.
    character(len=10) :: start_time,stop_time
Referenced by prtimestring(), and start_timing_run().
start_values
integer(int64), dimension(8), private xtb_mctc_timings::start_values private
Definition at line 41 of file mctc_timings.f90.
    integer(int64) :: start_values(8),stop_values(8)
Referenced by start_timing_run().
start_zone
character(len=5), private xtb_mctc_timings::start_zone private
Definition at line 40 of file mctc_timings.f90.
    character(len=5)  :: start_zone,stop_zone
Referenced by start_timing_run().
stop_date
character(len=8), private xtb_mctc_timings::stop_date private
Definition at line 38 of file mctc_timings.f90.
Referenced by prtimestring(), and stop_timing_run().
stop_time
character(len=10), private xtb_mctc_timings::stop_time private
Definition at line 39 of file mctc_timings.f90.
Referenced by prtimestring(), and stop_timing_run().
stop_values
integer(int64), dimension(8), private xtb_mctc_timings::stop_values private
Definition at line 41 of file mctc_timings.f90.
Referenced by stop_timing_run().
stop_zone
character(len=5), private xtb_mctc_timings::stop_zone private
Definition at line 40 of file mctc_timings.f90.
Referenced by stop_timing_run().
timing_cpu
real(wp), dimension(:), allocatable, private xtb_mctc_timings::timing_cpu private
Definition at line 34 of file mctc_timings.f90.
    real(wp),allocatable :: timing_cpu(:)
Referenced by init_timing(), prtiming(), start_timing(), and stop_timing().
timing_max
integer, private xtb_mctc_timings::timing_max private
Definition at line 35 of file mctc_timings.f90.
    integer :: timing_max
Referenced by init_timing().
timing_wall
real(wp), dimension(:), allocatable, private xtb_mctc_timings::timing_wall private
Definition at line 33 of file mctc_timings.f90.
    real(wp),allocatable :: timing_wall(:)
Referenced by init_timing(), prtiming(), start_timing(), and stop_timing().
verbose
logical, private xtb_mctc_timings::verbose = .false. private
Definition at line 36 of file mctc_timings.f90.
    logical  :: verbose = .false.
Referenced by init_timing(), xtb_prog_main::parsearguments(), prtiming(), and xtb_prog_main::xtbmain().