My Project: xtb_param_paulingen Module Reference
xtb_param_paulingen Module Reference
Pauling electronegativities.
Data Types
interface getpaulingen
Get electronegativity for a species.
Functions/Subroutines
elemental real(wp) function getpaulingensymbol (symbol)
Get electronegativity for species with a given symbol.
elemental real(wp) function getpaulingennumber (number)
Get electronegativity for species with a given atomic number.
Variables
real(wp), dimension(1:118), parameter, public paulingen = [ 2.20_wp,3.00_wp, 0.98_wp,1.57_wp,2.04_wp,2.55_wp,3.04_wp,3.44_wp,3.98_wp,4.50_wp, 0.93_wp,1.31_wp,1.61_wp,1.90_wp,2.19_wp,2.58_wp,3.16_wp,3.50_wp, 0.82_wp,1.00_wp, 1.36_wp,1.54_wp,1.63_wp,1.66_wp,1.55_wp, 1.83_wp,1.88_wp,1.91_wp,1.90_wp,1.65_wp, 1.81_wp,2.01_wp,2.18_wp,2.55_wp,2.96_wp,3.00_wp, 0.82_wp,0.95_wp, 1.22_wp,1.33_wp,1.60_wp,2.16_wp,1.90_wp, 2.20_wp,2.28_wp,2.20_wp,1.93_wp,1.69_wp, 1.78_wp,1.96_wp,2.05_wp,2.10_wp,2.66_wp,2.60_wp, 0.79_wp,0.89_wp, 1.10_wp,1.12_wp,1.13_wp,1.14_wp,1.15_wp,1.17_wp,1.18_wp, 1.20_wp,1.21_wp,1.22_wp,1.23_wp,1.24_wp,1.25_wp,1.26_wp, 1.27_wp,1.30_wp,1.50_wp,2.36_wp,1.90_wp, 2.20_wp,2.20_wp,2.28_wp,2.54_wp,2.00_wp, 1.62_wp,2.33_wp,2.02_wp,2.00_wp,2.20_wp,2.20_wp, 1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp ]
Pauling electronegativities, used for the covalent coordination number.
Detailed Description
Pauling electronegativities.
Function/Subroutine Documentation
getpaulingennumber()
elemental real(wp) function xtb_param_paulingen::getpaulingennumber (integer, intent(in) number) private
Get electronegativity for species with a given atomic number.
Parameters
[in] number Atomic number
Returns
atomic EN
Definition at line 81 of file paulingen.f90.
    integer, intent(in) :: number
    real(wp) :: en
    if (number > 0 .and. number <= size(paulingen, dim=1)) then
       en = paulingen(number)
    else
       en = -1.0_wp
    end if
getpaulingensymbol()
elemental real(wp) function xtb_param_paulingen::getpaulingensymbol (character(len=*), intent(in) symbol) private
Get electronegativity for species with a given symbol.
Parameters
[in] symbol Element symbol
Returns
atomic EN
Definition at line 67 of file paulingen.f90.
    character(len=*), intent(in) :: symbol
    real(wp) :: en
    en = getpaulingen(tonumber(symbol))
Variable Documentation
paulingen
real(wp), dimension(1:118), parameter, public xtb_param_paulingen::paulingen = [ 2.20_wp,3.00_wp, 0.98_wp,1.57_wp,2.04_wp,2.55_wp,3.04_wp,3.44_wp,3.98_wp,4.50_wp, 0.93_wp,1.31_wp,1.61_wp,1.90_wp,2.19_wp,2.58_wp,3.16_wp,3.50_wp, 0.82_wp,1.00_wp, 1.36_wp,1.54_wp,1.63_wp,1.66_wp,1.55_wp, 1.83_wp,1.88_wp,1.91_wp,1.90_wp,1.65_wp, 1.81_wp,2.01_wp,2.18_wp,2.55_wp,2.96_wp,3.00_wp, 0.82_wp,0.95_wp, 1.22_wp,1.33_wp,1.60_wp,2.16_wp,1.90_wp, 2.20_wp,2.28_wp,2.20_wp,1.93_wp,1.69_wp, 1.78_wp,1.96_wp,2.05_wp,2.10_wp,2.66_wp,2.60_wp, 0.79_wp,0.89_wp, 1.10_wp,1.12_wp,1.13_wp,1.14_wp,1.15_wp,1.17_wp,1.18_wp, 1.20_wp,1.21_wp,1.22_wp,1.23_wp,1.24_wp,1.25_wp,1.26_wp, 1.27_wp,1.30_wp,1.50_wp,2.36_wp,1.90_wp, 2.20_wp,2.20_wp,2.28_wp,2.54_wp,2.00_wp, 1.62_wp,2.33_wp,2.02_wp,2.00_wp,2.20_wp,2.20_wp, 1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp ]
Pauling electronegativities, used for the covalent coordination number.
Definition at line 36 of file paulingen.f90.
    real(wp), parameter :: paulingEN(1:118) = [ &
       & 2.20_wp,3.00_wp, & ! H,He
       & 0.98_wp,1.57_wp,2.04_wp,2.55_wp,3.04_wp,3.44_wp,3.98_wp,4.50_wp, & ! Li-Ne
       & 0.93_wp,1.31_wp,1.61_wp,1.90_wp,2.19_wp,2.58_wp,3.16_wp,3.50_wp, & ! Na-Ar
       & 0.82_wp,1.00_wp, & ! K,Ca
       &                 1.36_wp,1.54_wp,1.63_wp,1.66_wp,1.55_wp, & ! Sc-
       &                 1.83_wp,1.88_wp,1.91_wp,1.90_wp,1.65_wp, & ! -Zn
       &                 1.81_wp,2.01_wp,2.18_wp,2.55_wp,2.96_wp,3.00_wp, & ! Ga-Kr
       & 0.82_wp,0.95_wp, & ! Rb,Sr
       &                 1.22_wp,1.33_wp,1.60_wp,2.16_wp,1.90_wp, & ! Y-
       &                 2.20_wp,2.28_wp,2.20_wp,1.93_wp,1.69_wp, & ! -Cd
       &                 1.78_wp,1.96_wp,2.05_wp,2.10_wp,2.66_wp,2.60_wp, & ! In-Xe
       & 0.79_wp,0.89_wp, & ! Cs,Ba
       &         1.10_wp,1.12_wp,1.13_wp,1.14_wp,1.15_wp,1.17_wp,1.18_wp, & ! La-Eu
       &         1.20_wp,1.21_wp,1.22_wp,1.23_wp,1.24_wp,1.25_wp,1.26_wp, & ! Gd-Yb
       &                 1.27_wp,1.30_wp,1.50_wp,2.36_wp,1.90_wp, & ! Lu-
       &                 2.20_wp,2.20_wp,2.28_wp,2.54_wp,2.00_wp, & ! -Hg
       &                 1.62_wp,2.33_wp,2.02_wp,2.00_wp,2.20_wp,2.20_wp, & ! Tl-Rn
       ! only dummies below
       & 1.50_wp,1.50_wp, & ! Fr,Ra
       &         1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, & ! Ac-Am
       &         1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, & ! Cm-No
       &                 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, & ! Rf-
       &                 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp, & ! Rf-Cn
       &                 1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp,1.50_wp ] ! Nh-Og
Referenced by xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp(), xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl(), xtb_param_paulingen::getpaulingen::getpaulingennumber(), xtb_iniq::iniqcn_gfn1(), xtb_iniq::iniqcn_gfn2(), xtb_iniq::iniqcn_vtb(), xtb_xtb_gfn1::initgfn1::inithamiltonian(), xtb_xtb_gfn2::initgfn2::inithamiltonian(), xtb_xtb_data::init::initrepulsion(), and xtb_readparam::readparam().