My Project: xtb_type_dummycalc Module Reference
xtb_type_dummycalc Module Reference
Mock interface for all methods that not yet have their own calculator.
Data Types
interface generate_wsc
type tdummycalculator
Base calculator.
Functions/Subroutines
subroutine singlepoint (self, env, mol, chk, printlevel, restart, energy, gradient, sigma, hlgap, results)
subroutine writeinfo (self, unit, mol)
Variables
character(len= *), parameter, private outfmt = '(9x,"::",1x,a,f23.12,1x,a,1x,"::")'
Detailed Description
Mock interface for all methods that not yet have their own calculator.
Function/Subroutine Documentation
singlepoint()
subroutine xtb_type_dummycalc::singlepoint (class(tdummycalculator), intent(inout) self, type(tenvironment), intent(inout) env, type(tmolecule), intent(inout) mol, type(trestart), intent(inout) chk, integer, intent(in) printlevel, logical, intent(in) restart, real(wp), intent(out) energy, real(wp), dimension(:, :), intent(out) gradient, real(wp), dimension(:, :), intent(out) sigma, real(wp), intent(out) hlgap, type(scc_results), intent(out) results) private
Parameters
[in,out] self Calculator instance
[in,out] env Computational environment
[in,out] mol Molecular structure data
[in,out] chk Wavefunction data
[in] printlevel Print level for IO
[in] restart Restart from previous results
[out] energy Total energy
[out] gradient Molecular gradient
[out] sigma Strain derivatives
[out] hlgap HOMO-LUMO gap
[out] results Detailed results
Definition at line 73 of file dummycalc.f90.
    character(len=*), parameter :: source = 'type_calculator_singlepoint'
    class(TDummyCalculator), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(inout) :: mol
    type(TRestart), intent(inout) :: chk
    integer, intent(in) :: printlevel
    logical, intent(in) :: restart
    real(wp), intent(out) :: energy
    real(wp), intent(out) :: gradient(:, :)
    real(wp), intent(out) :: sigma(:, :)
    real(wp), intent(out) :: hlgap
    type(scc_results), intent(out) :: results
    integer :: i,ich
    integer :: mode_sp_run = 1
    real(wp) :: efix
    real(wp) :: dipole(3)
    logical :: inmol
    logical, parameter :: ccm = .true.
    logical :: exitRun
    call mol%update
    if (mol%npbc > 0) call generate_wsc(mol,mol%wsc)
    energy = 0.0_wp
    gradient(:, :) = 0.0_wp
    sigma(:, :) = 0.0_wp
    hlgap = 0.0_wp
    efix = 0.0_wp
    dipole(:) = 0.0_wp
    ! ------------------------------------------------------------------------
    !  actual calculation
    select case(mode_extrun)
    case(p_ext_qmdff)
       call ff_eg  (mol%n,mol%at,mol%xyz,energy,gradient)
       call ff_nonb(mol%n,mol%at,mol%xyz,energy,gradient)
       call ff_hb  (mol%n,mol%at,mol%xyz,energy,gradient)
    case(p_ext_orca)
       call runorca(env,mol,energy,gradient)
    case(p_ext_turbomole)
       call external_turbomole(mol%n,mol%at,mol%xyz,chk%wfn%nel,chk%wfn%nopen, &
          & .true.,energy,gradient,results%dipole,self%lSolv)
    case(p_ext_mopac)
       call runmopac(env,mol%n,mol%at,mol%xyz,energy,gradient,dipole)
    end select
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Electronic structure method terminated", source)
       return
    end if
    ! ------------------------------------------------------------------------
    !  various external potentials
    call constrain_pot(potset,mol%n,mol%at,mol%xyz,gradient,efix)
    call constrpot   (mol%n,mol%at,mol%xyz,gradient,efix)
    call cavity_egrad(mol%n,mol%at,mol%xyz,efix,gradient)
    if (prob_flag) then ! prob_module code
       call prob_metadynamic (metaset,mol%n,mol%at,mol%xyz,efix,gradient)
       call prob_metadynamic (rmsdset,mol%n,mol%at,mol%xyz,efix,gradient)
    else
       call metadynamic (metaset,mol%n,mol%at,mol%xyz,efix,gradient)
       call metadynamic (rmsdset,mol%n,mol%at,mol%xyz,efix,gradient)
    end if
    ! ------------------------------------------------------------------------
    !  fixing of certain atoms
    !  print*,abs(efix/etot)
    energy = energy + efix
    results%e_total = energy
    results%gnorm = norm2(gradient)
    results%dipole = dipole
    if (fixset%n.gt.0) then
       do i=1, fixset%n
          !print*,i,fixset%atoms(i)
          gradient(1:3,fixset%atoms(i))=0
       enddo
    endif
    if (printlevel.ge.2) then
       ! start with summary header
       if (.not.silent) then
          write(env%unit,'(9x,53(":"))')
          write(env%unit,'(9x,"::",21x,a,21x,"::")') "SUMMARY"
       endif
       write(env%unit,'(9x,53(":"))')
       write(env%unit,outfmt) "total energy      ", results%e_total,"Eh   "
       write(env%unit,outfmt) "gradient norm     ", results%gnorm,  "Eh/a0"
       write(env%unit,outfmt) "HOMO-LUMO gap     ", results%hl_gap, "eV   "
       write(env%unit,'(9x,53(":"))')
       write(env%unit,'(a)')
    endif
References xtb_sphereparam::cavity_egrad(), xtb_constrainpot::constrain_pot(), constrpot(), external_turbomole(), xtb_qmdff::ff_eg(), xtb_qmdff::ff_hb(), xtb_qmdff::ff_nonb(), xtb_fixparam::fixset, xtb_metadynamic::metadynamic(), xtb_fixparam::metaset, xtb_setparam::mode_extrun, outfmt, xtb_setparam::p_ext_mopac, xtb_setparam::p_ext_orca, xtb_setparam::p_ext_qmdff, xtb_setparam::p_ext_turbomole, xtb_scanparam::potset, prob_module::prob_flag, prob_module::prob_metadynamic(), xtb_fixparam::rmsdset, xtb_extern_mopac::runmopac(), xtb_extern_orca::runorca(), xtb_setparam::silent, and true().
writeinfo()
subroutine xtb_type_dummycalc::writeinfo (class(tdummycalculator), intent(in) self, integer, intent(in) unit, type(tmolecule), intent(in) mol) private
Parameters
[in] self Calculator instance
[in] unit Unit for I/O
[in] mol Molecular structure data
Definition at line 202 of file dummycalc.f90.
    class(TDummyCalculator), intent(in) :: self
    integer, intent(in) :: unit
    type(TMolecule), intent(in) :: mol
    select case(mode_extrun)
    case(p_ext_qmdff)
       call qmdff_header(unit)
    case(p_ext_orca, p_ext_mopac, p_ext_turbomole)
       call driver_header(unit)
    end select
References driver_header(), xtb_setparam::mode_extrun, xtb_setparam::p_ext_mopac, xtb_setparam::p_ext_orca, xtb_setparam::p_ext_qmdff, xtb_setparam::p_ext_turbomole, and qmdff_header().
Variable Documentation
outfmt
character(len=*), parameter, private xtb_type_dummycalc::outfmt = '(9x,"::",1x,a,f23.12,1x,a,1x,"::")' private
Definition at line 66 of file dummycalc.f90.
    character(len=*),private,parameter :: outfmt = &
       '(9x,"::",1x,a,f23.12,1x,a,1x,"::")'
Referenced by singlepoint().