My Project: xtb_sphereparam Module Reference
xtb_sphereparam Module Reference
Data Types
type tb_wall
interface set_sphere_radius
interface get_sphere_radius
interface polynomial_cavity
interface logfermi_cavity
Functions/Subroutines
subroutine init_walls
subroutine clear_walls
subroutine set_sphere_radius_iso (radius, center, nlist, list, fragment)
subroutine set_sphere_radius_aniso (radius, center, nlist, list, fragment)
subroutine getsphererad (n, at, xyz)
subroutine get_sphere_radius_list (nat, at, xyz, nlist, list, center, radius, do_trafo)
subroutine get_sphere_radius_fragment (nat, at, xyz, center, fragment, radius, do_trafo)
subroutine get_sphere_radius_all (nat, at, xyz, center, radius, do_trafo)
subroutine logfermi_cavity_list (nat, at, xyz, nlist, list, temp, alpha, center, radius, efix, gfix)
subroutine logfermi_cavity_frag (nat, at, xyz, fragment, temp, alpha, center, radius, efix, gfix)
subroutine logfermi_cavity_all (nat, at, xyz, temp, alpha, center, radius, efix, gfix)
subroutine polynomial_cavity_list (nat, at, xyz, nlist, list, alpha, center, radius, efix, gfix)
subroutine polynomial_cavity_frag (nat, at, xyz, fragment, alpha, center, radius, efix, gfix)
subroutine polynomial_cavity_all (nat, at, xyz, alpha, center, radius, efix, gfix)
subroutine cavity_egrad (nat, at, xyz, efix, gfix)
subroutine cavityeg (n, xyz, e, g)
subroutine cavitye (n, xyz, e)
Variables
integer, parameter p_type_polynomial = 1
integer, parameter p_type_logfermi = 2
integer spherepot_type = p_type_polynomial
integer, parameter p_cent_zero = 1
integer, parameter p_cent_com = 2
integer, parameter p_cent_cog = 3
integer spherecent = p_cent_zero
integer, parameter p_auto_dist = 1
integer, parameter p_auto_dens = 2
integer, parameter p_auto_force = 3
integer sphereauto = p_auto_dist
integer maxwalls = 0
real(wp) boxr = -1.0_wp
real(wp), dimension(3) rabc = (/-1.0_wp,-1.0_wp,-1.0_wp/)
integer sphere = -1
integer sphere_alpha = 30
real(wp) sphere_beta = 6.0_wp
real(wp) sphere_temp = 300.0_wp
real(wp) sphere_autoscale = 1.0_wp
real(wp) sphere_shift = 3.5_wp
integer number_walls
type(tb_wall), dimension(:), allocatable wpot
Function/Subroutine Documentation
cavity_egrad()
subroutine xtb_sphereparam::cavity_egrad (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), intent(inout) efix, real(wp), dimension(3,nat), intent(inout) gfix)
Definition at line 545 of file sphereparam.f90.
    use xtb_mctc_constants, only : kb
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(inout) :: efix
    real(wp),intent(inout) :: gfix(3,nat)
    integer :: i,nlist
    if (.not.allocated(wpot)) return
    do i = 1, number_walls
       select case(spherepot_type)
       case default ! make sure that this never happens, REALLY!
          call raise('E','Internal error in sphereparam.f90, please report this.')
       case(p_type_polynomial)
          if (wpot(i)%fragment.gt.0) then
             call polynomial_cavity(nat,at,xyz,wpot(i)%fragment,sphere_alpha, &
                  wpot(i)%center,wpot(i)%radius,efix,gfix)
          else if (allocated(wpot(i)%list)) then
             nlist = size(wpot(i)%list,1)
             call polynomial_cavity(nat,at,xyz,nlist,wpot(i)%list,sphere_alpha, &
                  wpot(i)%center,wpot(i)%radius,efix,gfix)
          else
             call polynomial_cavity(nat,at,xyz,sphere_alpha, &
                  wpot(i)%center,wpot(i)%radius,efix,gfix)
          endif
       case(p_type_logfermi)
          if (wpot(i)%fragment.gt.0) then
             call logfermi_cavity(nat,at,xyz,wpot(i)%fragment,sphere_temp, &
                  sphere_beta,wpot(i)%center,wpot(i)%radius,efix,gfix)
          else if (allocated(wpot(i)%list)) then
             nlist = size(wpot(i)%list,1)
             call logfermi_cavity(nat,at,xyz,nlist,wpot(i)%list,sphere_temp, &
                  sphere_beta,wpot(i)%center,wpot(i)%radius,efix,gfix)
          else
             call logfermi_cavity(nat,at,xyz,sphere_temp,sphere_beta, &
                  wpot(i)%center,wpot(i)%radius,efix,gfix)
          endif
       end select
    end do
References xtb_mctc_constants::kb, number_walls, p_type_logfermi, p_type_polynomial, raise(), sphere_alpha, sphere_beta, sphere_temp, spherepot_type, and wpot.
Referenced by xtb_gfnff_calculator::singlepoint(), xtb_type_dummycalc::singlepoint(), and xtb_xtb_calculator::singlepoint().
cavitye()
subroutine xtb_sphereparam::cavitye (integer n, real(wp), dimension(3,n) xyz, real(wp) e)
Definition at line 650 of file sphereparam.f90.
    implicit none
    real(wp) :: xyz(3,n)
    real(wp) :: e
    integer n,i,a
    real(wp) :: rij(3),dr,r,term,dum,r0,r2,rx,ry,rz
    if(sphere.lt.1) return
    if(sphere.eq.2) then
       a=15
       do i=1,n
          rx=(xyz(1,i)/rabc(1))**2
          ry=(xyz(2,i)/rabc(2))**2
          rz=(xyz(3,i)/rabc(3))**2
          term=(rx+ry+rz)**a
          e=e+term
       enddo
       return
    endif
    if(sphere.eq.1) then
       a=30
       do i=1,n
          rij=xyz(:,i)
          r2=sum(rij*rij)
          r=sqrt(r2)
          term=(r/boxr)**a
          e=e+term
       enddo
       return
    endif
References boxr, rabc, and sphere.
cavityeg()
subroutine xtb_sphereparam::cavityeg (integer n, real(wp), dimension(3,n) xyz, real(wp) e, real(wp), dimension (3,n) g)
Definition at line 600 of file sphereparam.f90.
    implicit none
    real(wp) :: xyz(3,n)
    real(wp) :: g  (3,n)
    real(wp) :: e
    integer n,i,a
    real(wp) :: rij(3),dr,r,term,dum,r0,r2,rx,ry,rz,term1,term3,a2,am1
    if(sphere.lt.1) return
    if(sphere.eq.2) then
       a  =15
       am1=14
       a2=2.0d0*a
       do i=1,n
          rx=(xyz(1,i)/rabc(1))**2
          ry=(xyz(2,i)/rabc(2))**2
          rz=(xyz(3,i)/rabc(3))**2
          term1=rx+ry+rz
          term =term1**a
          term3=a2*term1**am1
          e=e+term
          g(1,i)=g(1,i)+xyz(1,i)*term3/rabc(1)**2
          g(2,i)=g(2,i)+xyz(2,i)*term3/rabc(2)**2
          g(3,i)=g(3,i)+xyz(3,i)*term3/rabc(3)**2
       enddo
       return
    endif
    if(sphere.eq.1) then
       a=30
       do i=1,n
          rij=xyz(:,i)
          r2=sum(rij*rij)
          r=sqrt(r2)
          term=(r/boxr)**a
          e=e+term
          dum=term*a/r2
          g(1,i)=g(1,i)+rij(1)*dum
          g(2,i)=g(2,i)+rij(2)*dum
          g(3,i)=g(3,i)+rij(3)*dum
       enddo
    endif
References boxr, rabc, and sphere.
clear_walls()
subroutine xtb_sphereparam::clear_walls
Definition at line 111 of file sphereparam.f90.
    if (allocated(wpot)) deallocate(wpot)
References wpot.
Referenced by init_walls().
get_sphere_radius_all()
subroutine xtb_sphereparam::get_sphere_radius_all (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3), intent(out) center, real(wp), intent(out) radius, logical, intent(in), optional do_trafo)
Definition at line 289 of file sphereparam.f90.
    use xtb_axis, only : axis3
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: center(3)
    real(wp),intent(out) :: radius
    logical, intent(in)  :: do_trafo
    integer  :: i,j
    real(wp) :: max_distance,distance,dum(3)
    real(wp),allocatable :: coord(:,:)
    logical  :: trafo
    optional :: do_trafo
    center = 0.0_wp
    if (present(do_trafo)) then
       trafo = do_trafo
    else
       trafo = .false.
    endif
    if (trafo) then
       allocate( coord(3,nat), source = 0.0_wp )
       call axis3(0,nat,at,xyz,coord,dum)
    else
       allocate( coord(3,nat), source = xyz )
    endif
    max_distance = 0.0_wp ! ~equals diameter of sphere
    do i = 1, nat
       do j = 1, i-1
          distance = sqrt(sum((coord(:,j)-coord(:,i))**2))
          max_distance = max(max_distance,distance)
       enddo
    enddo
    select case(spherepot_type)
    case(p_type_polynomial)
       radius = (0.5_wp/0.7_wp * max_distance) * sphere_autoscale
    case(p_type_logfermi)
       radius = (0.5_wp * max_distance + sphere_shift) * sphere_autoscale
    end select
get_sphere_radius_fragment()
subroutine xtb_sphereparam::get_sphere_radius_fragment (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3), intent(out) center, integer, intent(in) fragment, real(wp), intent(out) radius, logical, intent(in), optional do_trafo)
Definition at line 238 of file sphereparam.f90.
    use xtb_axis, only : axis3
    use xtb_splitparam
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: fragment
    real(wp),intent(out) :: center(3)
    real(wp),intent(out) :: radius
    logical, intent(in)  :: do_trafo
    integer  :: i,j
    real(wp) :: max_distance,distance,dum(3)
    real(wp),allocatable :: coord(:,:)
    logical  :: trafo
    optional :: do_trafo
    center = 0.0_wp
    if (present(do_trafo)) then
       trafo = do_trafo
    else
       trafo = .false.
    endif
    if (trafo) then
       allocate( coord(3,nat), source = 0.0_wp )
       call axis3(0,nat,at,xyz,coord,dum)
    else
       allocate( coord(3,nat), source = xyz )
    endif
    max_distance = 0.0_wp ! ~equals diameter of sphere
    do i = 1, nat
       do j = 1, i-1
          if (splitlist(i).ne.fragment.or.fragment.ne.splitlist(j)) cycle
          distance = sqrt(sum((coord(:,j)-coord(:,i))**2))
          max_distance = max(max_distance,distance)
       enddo
    enddo
    select case(spherepot_type)
    case(p_type_polynomial)
       radius = (0.5_wp/0.7_wp * max_distance) * sphere_autoscale
    case(p_type_logfermi)
       radius = (0.5_wp * max_distance + sphere_shift) * sphere_autoscale
    end select
get_sphere_radius_list()
subroutine xtb_sphereparam::get_sphere_radius_list (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) nlist, integer, dimension(nlist), intent(in) list, real(wp), dimension(3), intent(out) center, real(wp), intent(out) radius, logical, intent(in), optional do_trafo)
Definition at line 188 of file sphereparam.f90.
    use xtb_axis, only : axis3
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: nlist
    integer, intent(in)  :: list(nlist)
    real(wp),intent(out) :: center(3)
    real(wp),intent(out) :: radius
    logical, intent(in)  :: do_trafo
    integer  :: i,j
    real(wp) :: max_distance,distance,dum(3)
    real(wp),allocatable :: coord(:,:)
    logical  :: trafo
    optional :: do_trafo
    center = 0.0_wp
    if (present(do_trafo)) then
       trafo = do_trafo
    else
       trafo = .false.
    endif
    if (trafo) then
       allocate( coord(3,nat), source = 0.0_wp )
       call axis3(0,nat,at,xyz,coord,dum)
    else
       allocate( coord(3,nat), source = xyz )
    endif
    max_distance = 0.0_wp ! ~equals diameter of sphere
    do i = 1, nlist
       do j = 1, i-1
          distance = sqrt(sum((coord(:,list(j))-coord(:,list(i)))**2))
          max_distance = max(max_distance,distance)
       enddo
    enddo
    select case(spherepot_type)
    case(p_type_polynomial)
       radius = (0.5_wp/0.7_wp * max_distance) * sphere_autoscale
    case(p_type_logfermi)
       radius = (0.5_wp * max_distance + sphere_shift) * sphere_autoscale
    end select
getsphererad()
subroutine xtb_sphereparam::getsphererad (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz)
Definition at line 154 of file sphereparam.f90.
    implicit none
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    real(wp),intent(in)  :: xyz(3,n)
    real(wp) :: dum(3),rx,ry,rz
    real(wp) :: x,y,z,f,rr,r
    integer  :: i,j
 !  call axis3(0,n,at,xyz,xyz2,dum)
 !  xyz = xyz2
    r=0.0_wp
    do i=1,n-1
       do j=i+1,n
          rx=xyz(1,i)-xyz(1,j)
          ry=xyz(2,i)-xyz(2,j)
          rz=xyz(3,i)-xyz(3,j)
          rr=sqrt(rx**2+ry**2+rz**2)
          if(rr.gt.r) r=rr
       enddo
    enddo
    boxr=0.5*r+3.5d0 ! assume some vdW radius
 !  this is wrong, because the cavity uses a relative measure for the constrain,
 !  but here it is treated as an absolute measure, using this routine will
 !  artifically compress larger molecules. I should fix this, dunno how.
References boxr.
init_walls()
subroutine xtb_sphereparam::init_walls
Definition at line 104 of file sphereparam.f90.
    call clear_walls
    allocate ( wpot(maxwalls) )
References clear_walls(), maxwalls, and wpot.
Referenced by xtb_prog_main::xtbmain().
logfermi_cavity_all()
subroutine xtb_sphereparam::logfermi_cavity_all (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), intent(in) temp, real(wp), intent(in) alpha, real(wp), dimension(3), intent(in) center, real(wp), dimension(3), intent(in) radius, real(wp), intent(inout) efix, real(wp), dimension(3,nat), intent(inout) gfix)
Definition at line 410 of file sphereparam.f90.
    use xtb_mctc_constants, only : kb
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(in)  :: temp      ! temperature
    real(wp),intent(in)  :: alpha     ! potential steepness
    real(wp),intent(in)  :: center(3) ! aufpunkt of wall potential
    real(wp),intent(in)  :: radius(3) ! radius of the sphere (anisotropic)
    integer  :: i
    real(wp) :: r(3),w(3),dist,R0,expterm,fermi
    real(wp),intent(inout) :: efix
    real(wp),intent(inout) :: gfix(3,nat)
    r0 = maxval(radius)
    w  = r0/radius ! for anisotropy
    do i = 1, nat
       r = w*(xyz(:,i) - center)
       dist = sqrt(sum(r**2))
       expterm = exp(alpha*(dist-r0))
       fermi = 1.0_wp/(1.0_wp+expterm)
       efix = efix + kb*temp * log( 1.0_wp+expterm )
       gfix(:,i) = gfix(:,i) + kb*temp * alpha*expterm*fermi * (r*w)/(dist+1.0e-14_wp)
    enddo
logfermi_cavity_frag()
subroutine xtb_sphereparam::logfermi_cavity_frag (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) fragment, real(wp), intent(in) temp, real(wp), intent(in) alpha, real(wp), dimension(3), intent(in) center, real(wp), dimension(3), intent(in) radius, real(wp), intent(inout) efix, real(wp), dimension(3,nat), intent(inout) gfix)
Definition at line 374 of file sphereparam.f90.
    use xtb_mctc_constants, only : kb
    use xtb_splitparam
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: fragment
    real(wp),intent(in)  :: temp      ! temperature
    real(wp),intent(in)  :: alpha     ! potential steepness
    real(wp),intent(in)  :: center(3) ! aufpunkt of wall potential
    real(wp),intent(in)  :: radius(3) ! radius of the sphere (anisotropic)
    integer  :: i
    real(wp) :: r(3),w(3),dist,R0,expterm,fermi
    real(wp),intent(inout) :: efix
    real(wp),intent(inout) :: gfix(3,nat)
    r0 = maxval(radius)
    w  = r0/radius ! for anisotropy
    do i = 1, nat
       if (splitlist(i).ne.fragment) cycle
       r = w*(xyz(:,i) - center)
       dist = sqrt(sum(r**2))
       expterm = exp(alpha*(dist-r0))
       fermi = 1.0_wp/(1.0_wp+expterm)
       efix = efix + kb*temp * log( 1.0_wp+expterm )
       gfix(:,i) = gfix(:,i) + kb*temp * alpha*expterm*fermi * (r*w)/(dist+1.0e-14_wp)
    enddo
logfermi_cavity_list()
subroutine xtb_sphereparam::logfermi_cavity_list (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) nlist, integer, dimension(nlist), intent(in) list, real(wp), intent(in) temp, real(wp), intent(in) alpha, real(wp), dimension(3), intent(in) center, real(wp), dimension(3), intent(in) radius, real(wp), intent(inout) efix, real(wp), dimension(3,nat), intent(inout) gfix)
Definition at line 338 of file sphereparam.f90.
    use xtb_mctc_constants, only : kb
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: nlist
    integer, intent(in)  :: list(nlist)
    real(wp),intent(in)  :: temp      ! temperature
    real(wp),intent(in)  :: alpha     ! potential steepness
    real(wp),intent(in)  :: center(3) ! aufpunkt of wall potential
    real(wp),intent(in)  :: radius(3) ! radius of the sphere (anisotropic)
    integer  :: i,iat
    real(wp) :: r(3),w(3),dist,R0,expterm,fermi
    real(wp),intent(inout) :: efix
    real(wp),intent(inout) :: gfix(3,nat)
    r0 = maxval(radius)
    w  = r0/radius ! for anisotropy
    do i = 1, nlist
       iat = list(i)
       r = w*(xyz(:,iat) - center)
       dist = sqrt(sum(r**2))
       expterm = exp(alpha*(dist-r0))
       fermi = 1.0_wp/(1.0_wp+expterm)
       efix = efix + kb*temp * log( 1.0_wp+expterm )
       gfix(:,iat) = gfix(:,iat) + kb*temp * alpha*expterm*fermi * (r*w)/(dist+1.0e-14_wp)
    enddo
polynomial_cavity_all()
subroutine xtb_sphereparam::polynomial_cavity_all (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) alpha, real(wp), dimension(3), intent(in) center, real(wp), dimension(3), intent(in) radius, real(wp), intent(inout) efix, real(wp), dimension(3,nat), intent(inout) gfix)
Definition at line 512 of file sphereparam.f90.
    use xtb_mctc_constants, only : kb
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: alpha     ! potential steepness
    real(wp),intent(in)  :: center(3) ! aufpunkt of wall potential
    real(wp),intent(in)  :: radius(3) ! radius of the sphere (anisotropic)
    integer  :: i
    real(wp) :: r(3),w(3),dist,R0,polyterm
    real(wp),intent(inout) :: efix
    real(wp),intent(inout) :: gfix(3,nat)
    r0 = maxval(radius)
    w  = r0/radius ! for anisotropy
    do i = 1, nat
       r = w*(xyz(:,i) - center)
       dist = sqrt(sum(r**2))
       polyterm = (dist/r0)**alpha
       efix = efix + polyterm
       gfix(:,i) = gfix(:,i) + alpha*polyterm * (r*w)/(dist**2+1.0e-14_wp)
    enddo
polynomial_cavity_frag()
subroutine xtb_sphereparam::polynomial_cavity_frag (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) fragment, integer, intent(in) alpha, real(wp), dimension(3), intent(in) center, real(wp), dimension(3), intent(in) radius, real(wp), intent(inout) efix, real(wp), dimension(3,nat), intent(inout) gfix)
Definition at line 478 of file sphereparam.f90.
    use xtb_mctc_constants, only : kb
    use xtb_splitparam
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: fragment
    integer, intent(in)  :: alpha     ! potential steepness
    real(wp),intent(in)  :: center(3) ! aufpunkt of wall potential
    real(wp),intent(in)  :: radius(3) ! radius of the sphere (anisotropic)
    integer  :: i
    real(wp) :: r(3),w(3),dist,R0,polyterm
    real(wp),intent(inout) :: efix
    real(wp),intent(inout) :: gfix(3,nat)
    r0 = maxval(radius)
    w  = r0/radius ! for anisotropy
    do i = 1, nat
       if (splitlist(i).ne.fragment) cycle
       r = w*(xyz(:,i) - center)
       dist = sqrt(sum(r**2))
       polyterm = (dist/r0)**alpha
       efix = efix + polyterm
       gfix(:,i) = gfix(:,i) + alpha*polyterm * (r*w)/(dist**2+1.0e-14_wp)
    enddo
polynomial_cavity_list()
subroutine xtb_sphereparam::polynomial_cavity_list (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) nlist, integer, dimension(nlist), intent(in) list, integer, intent(in) alpha, real(wp), dimension(3), intent(in) center, real(wp), dimension(3), intent(in) radius, real(wp), intent(inout) efix, real(wp), dimension(3,nat), intent(inout) gfix)
Definition at line 444 of file sphereparam.f90.
    use xtb_mctc_constants, only : kb
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: nlist
    integer, intent(in)  :: list(nlist)
    integer, intent(in)  :: alpha     ! potential steepness
    real(wp),intent(in)  :: center(3) ! aufpunkt of wall potential
    real(wp),intent(in)  :: radius(3) ! radius of the sphere (anisotropic)
    integer  :: i,iat
    real(wp) :: r(3),w(3),dist,R0,polyterm
    real(wp),intent(inout) :: efix
    real(wp),intent(inout) :: gfix(3,nat)
    r0 = maxval(radius)
    w  = r0/radius ! for anisotropy
    do i = 1, nlist
       iat = list(i)
       r = w*(xyz(:,iat) - center)
       dist = sqrt(sum(r**2))
       polyterm = (dist/r0)**alpha
       efix = efix + polyterm
       gfix(:,iat) = gfix(:,iat) + alpha*polyterm * (r*w)/(dist**2+1.0e-14_wp)
    enddo
set_sphere_radius_aniso()
subroutine xtb_sphereparam::set_sphere_radius_aniso (real(wp), dimension(3), intent(in) radius, real(wp), dimension(3), intent(in), optional center, integer, intent(in), optional nlist, integer, dimension(:), intent(in), optional list, integer, intent(in), optional fragment)
Definition at line 133 of file sphereparam.f90.
    implicit none
    real(wp), intent(in) :: radius(3)
    real(wp),intent(in),optional :: center(3)
    integer, intent(in),optional :: nlist,list(:)
    integer, intent(in),optional :: fragment
    number_walls = number_walls + 1
    if (number_walls.gt.maxwalls) & ! If this happens, you used it wrong!
    &  call raise('E','Number of wall potentials exceeded provided array size')
    wpot(number_walls)%radius = radius
    if (present(center)) wpot(number_walls)%center = center
    if (present(list).and.present(nlist)) &
    &  allocate( wpot(number_walls)%list(nlist), source = list(1:nlist) )
    if (present(fragment)) wpot(number_walls)%fragment = fragment
set_sphere_radius_iso()
subroutine xtb_sphereparam::set_sphere_radius_iso (real(wp), intent(in) radius, real(wp), dimension(3), intent(in), optional center, integer, intent(in), optional nlist, integer, dimension(:), intent(in), optional list, integer, intent(in), optional fragment)
Definition at line 118 of file sphereparam.f90.
    implicit none
    real(wp),intent(in) :: radius
    real(wp),intent(in),optional :: center(3)
    integer, intent(in),optional :: nlist,list(:)
    integer, intent(in),optional :: fragment
    number_walls = number_walls + 1
    if (number_walls.gt.maxwalls) & ! This should never happen
    &  call raise('E','Number of wall potentials exceeded provided array size')
    wpot(number_walls)%radius = radius
    if (present(center)) wpot(number_walls)%center = center
    if (present(list).and.present(nlist)) &
    &  allocate( wpot(number_walls)%list(nlist), source = list(1:nlist) )
    if (present(fragment)) wpot(number_walls)%fragment = fragment
Variable Documentation
boxr
real(wp) xtb_sphereparam::boxr = -1.0_wp
Definition at line 41 of file sphereparam.f90.
    real(wp) :: boxr = -1.0_wp
Referenced by cavitye(), cavityeg(), and getsphererad().
maxwalls
integer xtb_sphereparam::maxwalls = 0
Definition at line 38 of file sphereparam.f90.
    integer  :: maxwalls = 0
Referenced by init_walls(), xtb_setmod::rdcontrol(), xtb_setmod::set_legacy(), xtb_sphereparam::set_sphere_radius::set_sphere_radius_aniso(), and xtb_sphereparam::set_sphere_radius::set_sphere_radius_iso().
number_walls
integer xtb_sphereparam::number_walls
Definition at line 58 of file sphereparam.f90.
    integer :: number_walls
Referenced by cavity_egrad(), xtb_sphereparam::set_sphere_radius::set_sphere_radius_aniso(), xtb_sphereparam::set_sphere_radius::set_sphere_radius_iso(), and xtb_setmod::write_set_wall().
p_auto_dens
integer, parameter xtb_sphereparam::p_auto_dens = 2
Definition at line 34 of file sphereparam.f90.
    integer,parameter :: p_auto_dens = 2
Referenced by xtb_setmod::set_wall().
p_auto_dist
integer, parameter xtb_sphereparam::p_auto_dist = 1
Definition at line 33 of file sphereparam.f90.
    integer,parameter :: p_auto_dist = 1
Referenced by xtb_setmod::set_wall().
p_auto_force
integer, parameter xtb_sphereparam::p_auto_force = 3
Definition at line 35 of file sphereparam.f90.
    integer,parameter :: p_auto_force  = 3
Referenced by xtb_setmod::set_wall().
p_cent_cog
integer, parameter xtb_sphereparam::p_cent_cog = 3
Definition at line 30 of file sphereparam.f90.
    integer,parameter :: p_cent_cog  = 3
Referenced by xtb_setmod::set_wall().
p_cent_com
integer, parameter xtb_sphereparam::p_cent_com = 2
Definition at line 29 of file sphereparam.f90.
    integer,parameter :: p_cent_com  = 2
Referenced by xtb_setmod::set_wall().
p_cent_zero
integer, parameter xtb_sphereparam::p_cent_zero = 1
Definition at line 28 of file sphereparam.f90.
    integer,parameter :: p_cent_zero = 1
Referenced by xtb_setmod::set_wall().
p_type_logfermi
integer, parameter xtb_sphereparam::p_type_logfermi = 2
Definition at line 25 of file sphereparam.f90.
    integer,parameter :: p_type_logfermi   = 2
Referenced by cavity_egrad(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_all(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_fragment(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_list(), and xtb_setmod::set_wall().
p_type_polynomial
integer, parameter xtb_sphereparam::p_type_polynomial = 1
Definition at line 24 of file sphereparam.f90.
    integer,parameter :: p_type_polynomial = 1
Referenced by cavity_egrad(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_all(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_fragment(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_list(), xtb_setmod::set_wall(), and xtb_setmod::write_set_wall().
rabc
real(wp), dimension(3) xtb_sphereparam::rabc = (/-1.0_wp,-1.0_wp,-1.0_wp/)
Definition at line 42 of file sphereparam.f90.
    real(wp) :: rabc(3) = (/-1.0_wp,-1.0_wp,-1.0_wp/)
Referenced by cavitye(), and cavityeg().
sphere
integer xtb_sphereparam::sphere = -1
Definition at line 43 of file sphereparam.f90.
    integer  :: sphere = -1
Referenced by cavitye(), and cavityeg().
sphere_alpha
integer xtb_sphereparam::sphere_alpha = 30
Definition at line 45 of file sphereparam.f90.
    integer  :: sphere_alpha = 30
Referenced by cavity_egrad(), xtb_setmod::set_wall(), and xtb_setmod::write_set_wall().
sphere_autoscale
real(wp) xtb_sphereparam::sphere_autoscale = 1.0_wp
Definition at line 48 of file sphereparam.f90.
    real(wp) :: sphere_autoscale = 1.0_wp
Referenced by xtb_sphereparam::get_sphere_radius::get_sphere_radius_all(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_fragment(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_list(), xtb_setmod::set_wall(), and xtb_setmod::write_set_wall().
sphere_beta
real(wp) xtb_sphereparam::sphere_beta = 6.0_wp
Definition at line 46 of file sphereparam.f90.
    real(wp) :: sphere_beta  = 6.0_wp
Referenced by cavity_egrad(), xtb_setmod::set_wall(), and xtb_setmod::write_set_wall().
sphere_shift
real(wp) xtb_sphereparam::sphere_shift = 3.5_wp
Definition at line 49 of file sphereparam.f90.
    real(wp) :: sphere_shift = 3.5_wp
Referenced by xtb_sphereparam::get_sphere_radius::get_sphere_radius_all(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_fragment(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_list(), xtb_setmod::set_wall(), and xtb_setmod::write_set_wall().
sphere_temp
real(wp) xtb_sphereparam::sphere_temp = 300.0_wp
Definition at line 47 of file sphereparam.f90.
    real(wp) :: sphere_temp  = 300.0_wp
Referenced by cavity_egrad(), xtb_setmod::set_wall(), and xtb_setmod::write_set_wall().
sphereauto
integer xtb_sphereparam::sphereauto = p_auto_dist
Definition at line 36 of file sphereparam.f90.
    integer  :: sphereauto = p_auto_dist
Referenced by xtb_setmod::set_wall().
spherecent
integer xtb_sphereparam::spherecent = p_cent_zero
Definition at line 31 of file sphereparam.f90.
    integer  :: spherecent = p_cent_zero
Referenced by xtb_setmod::set_wall().
spherepot_type
integer xtb_sphereparam::spherepot_type = p_type_polynomial
Definition at line 26 of file sphereparam.f90.
    integer  :: spherepot_type = p_type_polynomial
Referenced by cavity_egrad(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_all(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_fragment(), xtb_sphereparam::get_sphere_radius::get_sphere_radius_list(), xtb_setmod::set_wall(), and xtb_setmod::write_set_wall().
wpot
type(tb_wall), dimension(:), allocatable xtb_sphereparam::wpot
Definition at line 59 of file sphereparam.f90.
    type(tb_wall),allocatable :: wpot(:)
Referenced by cavity_egrad(), clear_walls(), init_walls(), xtb_sphereparam::set_sphere_radius::set_sphere_radius_aniso(), xtb_sphereparam::set_sphere_radius::set_sphere_radius_iso(), and xtb_setmod::write_set_wall().