My Project: xtb_peeq Module Reference
xtb_peeq Module Reference
Functions/Subroutines
subroutine, public peeq (env, mol, wfn, basis, xtbData, gbsa, egap, et, prlevel, grd, ccm, acc, etot, gradient, sigma, res)
pure subroutine drep_grad (repData, mol, trans, erep, gradient, sigma)
subroutine dsrb_grad (mol, srb, cn, dcndr, dcndL, trans, esrb, gradient, sigma)
pure subroutine build_srblist (mol, nsrb, srblist)
subroutine ccm_build_sh0 (nShell, hData, selfEnergy, nat, at, basis, nbf, nao, xyz, lattice, intcut, sint, h0, wsc)
subroutine pbc_build_sh0 (nShell, hData, selfEnergy, nat, at, basis, nbf, nao, xyz, trans, intcut, sint, h0)
subroutine ccm_build_dsh0 (nShell, hData, selfEnergy, dSEdcn, dSEdq, nat, basis, thr, nao, nbf, at, xyz, lattice, P, Pew, g, sigma, dHdcn, dHdq, wsc)
subroutine pbc_build_dsh0 (nShell, hData, selfEnergy, dSEdcn, dSEdq, nat, basis, thr, nao, nbf, at, xyz, trans, P, Pew, g, sigma, dHdcn, dHdq)
Variables
logical, parameter, private gpr =.false.
print the different gradient contributions (for debugging)
logical, parameter, private profile = .true.
profiling
Function/Subroutine Documentation
build_srblist()
pure subroutine xtb_peeq::build_srblist (type(tmolecule), intent(in) mol, integer, intent(out) nsrb, integer, dimension(:,:), intent(out), allocatable srblist)
Definition at line 755 of file peeq_module.f90.
    use xtb_type_molecule
    implicit none
    type(TMolecule), intent(in) :: mol
    integer, intent(out) :: nsrb
    integer, allocatable, intent(out) :: srblist(:,:)
    integer  :: i,j,k
    real(wp) :: r2
    ! cutoff
    real(wp), parameter    :: srb_cut = 200.0_wp
    nsrb = 0
    do i = 1, mol%n-1
       if (srbatom(mol%at(i))) cycle    ! i i case
       do j = i+1, mol%n
          if (srbatom(mol%at(j))) cycle ! j j case
          if (mol%at(i).eq.mol%at(j)) cycle ! hetero only
          r2  = mol%dist(j,i)**2 ! get minimum image distance
          ! increment array size according to SRB cutoff criterium
          ! default: srb_cut = 200.0_wp
          if(r2.lt.srb_cut) nsrb=nsrb+1
       enddo ! j
    enddo ! i
    ! nsrb = 0: no pairs for SRB correction, nothing to do here
    if(nsrb.eq.0) return
    ! get memory
    allocate( srblist(2,nsrb), source = 0 )
    ! setup srblist
    k=0
    do i = 1, mol%n-1
       if (srbatom(mol%at(i))) cycle    ! i i case
       do j = i+1, mol%n
          if (srbatom(mol%at(j))) cycle ! j j case
          if (mol%at(i).eq.mol%at(j)) cycle ! hetero only
          r2  = mol%dist(j,i)**2 ! get minimum image distance
          if(r2.gt.srb_cut) cycle
          k = k + 1
          srblist(1,k) = i
          srblist(2,k) = j
       enddo ! j
    enddo ! i
    nsrb = k
 contains
 pure elemental function srbatom(iat) result(lsrb)
    integer, intent(in) :: iat
    logical :: lsrb
    lsrb = iat < 5 .or. iat > 9
 end function srbatom
References srbatom().
Referenced by dsrb_grad().
ccm_build_dsh0()
subroutine xtb_peeq::ccm_build_dsh0 (integer, dimension(:), intent(in) nShell, type(thamiltoniandata), intent(in) hData, real(wp), dimension(:, :), intent(in) selfEnergy, real(wp), dimension(:, :), intent(in) dSEdcn, real(wp), dimension(:, :), intent(in) dSEdq, integer, intent(in) nat, type(tbasisset), intent(in) basis, real(wp), intent(in) thr, integer, intent(in) nao, integer, intent(in) nbf, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3,3), intent(in) lattice, real(wp), dimension(nao,nao), intent(in) P, real(wp), dimension(nao,nao), intent(in) Pew, real(wp), dimension(3,nat), intent(inout) g, real(wp), dimension(3,3), intent(inout) sigma, real(wp), dimension(nat), intent(inout) dHdcn, real(wp), dimension(nat), intent(inout) dHdq, type(tb_wsc), intent(in) wsc)
Definition at line 1194 of file peeq_module.f90.
    use xtb_mctc_constants, only : pi
    use xtb_mctc_convert
    use xtb_type_wsc
    use xtb_type_basisset
    use xtb_intgrad
    use xtb_grad_core
    implicit none
    ! intent in
    integer, intent(in) :: nShell(:)
    type(THamiltonianData), intent(in) :: hData
    real(wp), intent(in) :: selfEnergy(:, :)
    real(wp), intent(in) :: dSEdcn(:, :)
    real(wp), intent(in) :: dSEdq(:, :)
    integer, intent(in)      :: nat
    type(tb_wsc), intent(in) :: wsc
    type(TBasisset), intent(in) :: basis
    real(wp),intent(in)      :: thr
    integer, intent(in)      :: nao
    integer, intent(in)      :: nbf
    integer, intent(in) :: at(nat)
    real(wp),intent(in) :: xyz(3,nat)
    real(wp),intent(in) :: lattice(3,3)
    real(wp),intent(in) :: P(nao,nao)
    real(wp),intent(in) :: Pew(nao,nao)
    ! intent inout
    real(wp),intent(inout) :: dHdq(nat)
    real(wp),intent(inout) :: dHdcn(nat)
    real(wp),intent(inout) :: g(3,nat)
    real(wp),intent(inout) :: sigma(3,3)
    integer, parameter :: llao (0:3) = (/ 1, 3, 6,10/)
    integer, parameter :: llao2(0:3) = (/ 1, 3, 5, 7/)
    integer itt(0:3)
    parameter(itt=(/0,1,4,10/))
    real(wp) tmp1,tmp2,tmp3,step,step2,step3,s00r,s00l,s00,alpj
    real(wp) skj,r1,r2,tt,t1,t2,t3,t4
    real(wp) thr2,f,ci,cc,cj,alpi,rab2,ab,est
    real(wp) f1,f2,tmp(6,6),rij(3),ri(3),rj(3),rij2,t(3)
    real(wp) stmp,ral(3,3),rar(3,3),rbl(3,3),pre
    real(wp) dtmp,qtmp,rbr(3,3),r2l(3),r2r(3),qqa(6,6,6,3)
    real(wp)  ss(6,6,3),ddc(3,6,6,3),qqc(6,6,6,3),dda(3,6,6,3)
    integer i,j,k,l,m,ii,jj,ll,mm,kk,ki,kj,kl,mi,mj,ij,lin,jshmax
    integer ip,jp,iat,jat,kat,ati,atj,ish,jsh,icao,jcao,iao,jao,ixyz,jxyz
    integer ishtyp,jshtyp,iptyp,jptyp,naoi,naoj,mli,mlj,iprim,jprim
    real(wp) :: dumdum(3),dum,sdq(6,6),sdqg(3,6,6)
    real(wp),parameter :: point(3) = 0.0_wp
    integer  :: il,jl
    real(wp) :: Hij,Pii,Pij,HPij,H0sr
    real(wp) :: den,den2,den4,enpoly
    real(wp) :: zi,zj,zetaij
    real(wp) :: hii,hjj,hav
    real(wp) :: shpoly,dshpoly(3),km
    logical  :: valaoi,valaoj
    real(wp) :: g_xyz(3)
    !$omp parallel default(none) &
    !$omp private(iat,jat,ixyz,ati,cc,ci,rab2,atj,ish,ishtyp,valaoi,valaoj,g_xyz, &
    !$omp&        ri,rj,icao,naoi,iptyp,jsh,jshmax,jshtyp,jcao,naoj,jptyp,rij2, &
    !$omp&        sdq,sdqg,est,alpi,alpj,ab,iprim,jprim,ip,jp,km,shpoly,dshpoly, &
    !$omp&        mli,mlj,dum,dumdum,tmp,stmp,rij,zi,zj,zetaij,enpoly,iao,jao,t, &
    !$omp&        ii,jj,k,den,den2,den4,i,j,il,jl,hii,hjj,hav,Pij,Hij,HPij,H0sr) &
    !$omp reduction (+:g,sigma,dhdcn,dhdq) &
    !$omp shared(wsc,basis,at,nShell,hData,xyz,lattice,thr,nat,selfEnergy, &
    !$omp        dSEdcn,dSEdq,P,Pew)
    !$omp do schedule(runtime)
    do iat = 1, nat
       ri  = xyz(:,iat)
       ati = at(iat)
       do jat = 1, iat-1
          atj = at(jat)
          den = hdata%electronegativity(ati) - hdata%electronegativity(atj)
          den2 =  den**2
          den4 = den2**2
          ishells: do ish = 1, nshell(ati)
             ishtyp = hdata%angShell(ish,ati)
             icao = basis%caoshell(ish,iat)
             naoi = llao(ishtyp)
             iptyp = itt(ishtyp)
             jshmax = nshell(atj)
             if(iat == jat) jshmax = ish
             jshells: do jsh = 1, jshmax
                jshtyp = hdata%angShell(jsh,atj)
                jcao = basis%caoshell(jsh,jat)
                naoj = llao(jshtyp)
                jptyp = itt(jshtyp)
                il = ishtyp+1
                jl = jshtyp+1
                ! diagonals are the same for all H0 elements
                hii = selfenergy(ish, iat)
                hjj = selfenergy(jsh, jat)
                ! evaluate the EN polynom for this shells
                enpoly = (1.0_wp + hdata%enScale(jl-1,il-1)*den2 &
                   & + hdata%enScale4*hdata%enScale(jl-1,il-1)*den4)
                ! we scale the two shells depending on their exponent
                zi = hdata%slaterExponent(ish, ati)
                zj = hdata%slaterExponent(jsh, atj)
                zetaij = 2 * sqrt(zi*zj)/(zi+zj)
                ! now do the real magic (called EHT enhancement factor)
                km = hdata%kScale(jl-1,il-1) * hdata%pairParam(ati,atj) * zetaij * enpoly
                ! check for valence orbitals
                valaoi = hdata%valenceShell(ish, ati).eq.0
                valaoj = hdata%valenceShell(jsh, atj).eq.0
                ! and scale appropiately
                if (valaoi) then
                   if (valaoj) then
                      km = 0.0_wp
                   else
                      km = km * hdata%kDiff
                   endif
                else
                   if (valaoj) km = km * hdata%kDiff
                endif
                ! averaged H0 element (without overlap contribution!)
                hav = 0.5_wp * km * (hii + hjj)
                wscat: do kat = 1,wsc%itbl(jat,iat)
                   t = wsc%lattr(:,kat,jat,iat)
                   rj = xyz(:,jat) + matmul(lattice,t)
                   rij = ri - rj
                   rij2 = sum(rij**2)
                   ! distance dependent polynomial
                   call dshellpoly(hdata%shellPoly(il,ati),hdata%shellPoly(jl,atj),&
                      & hdata%atomicRad(ati),hdata%atomicRad(atj),rij2,ri,rj,&
                      & shpoly,dshpoly)
                   call get_grad_overlap(icao,jcao,naoi,naoj,ishtyp,jshtyp,ri,rj, &
                      &                  point,thr,basis%nprim,basis%primcount, &
                      &                  basis%alp,basis%cont,sdq,sdqg)
                   call dtrf2(sdq,ishtyp,jshtyp)
                   do ixyz = 1, 3
                      ! transform from CAO to SAO, only transform the gradient
                      tmp = sdqg(ixyz,:,:)
                      call dtrf2(tmp,ishtyp,jshtyp)
                      sdqg(ixyz,:,:) = tmp
                   enddo
                   do ii = 1, llao2(ishtyp)
                      iao = ii+basis%saoshell(ish,iat)
                      do jj = 1, llao2(jshtyp)
                         jao = jj+basis%saoshell(jsh,jat)
                         pij = p(jao,iao) * evtoau
                         ! Hamiltonian element without overlap
                         hij  = hav * shpoly
                         hpij = hij * pij
                         ! overlap contribution
                         stmp = 2*wsc%w(jat,iat) * (hpij - pew(jao,iao))
                         ! distance dependent polynomial contribution
                         h0sr = 2*hpij*sdq(jj,ii)*wsc%w(jat,iat)
                         g_xyz = stmp*sdqg(:,jj,ii) + h0sr*dshpoly/shpoly
                         ! distribute to atom i
                         g(:,iat) = g(:,iat) + g_xyz
                         ! distribute to atom j
                         g(:,jat) = g(:,jat) - g_xyz
                         ! reduce to strain
                         sigma(:,1) = sigma(:,1) + g_xyz*rij(1)
                         sigma(:,2) = sigma(:,2) + g_xyz*rij(2)
                         sigma(:,3) = sigma(:,3) + g_xyz*rij(3)
                         ! Hamiltonian without Hav
                         hpij = km * shpoly * pij * sdq(jj,ii) * wsc%w(jat,iat)
                         ! save dE/dCN for CNi
                         dhdcn(iat) = dhdcn(iat) + hpij*dsedcn(ish, iat)
                         ! save dE/dCN for CNj
                         dhdcn(jat) = dhdcn(jat) + hpij*dsedcn(jsh, jat)
                         ! save dE/dq for qi
                         dhdq(iat) = dhdq(iat) + hpij*dsedq(ish, iat)
                         ! save dE/dq for qj
                         dhdq(jat) = dhdq(jat) + hpij*dsedq(jsh, jat)
                      enddo
                   enddo
                enddo wscat
             enddo jshells
          enddo  ishells
       enddo ! jat
    enddo  ! iat
    !$omp end do
    !$omp end parallel
    ! diagonal contributions
    do iat = 1, nat
       ati = at(iat)
       do ish = 1, nshell(ati)
          iao = 1+basis%saoshell(ish,iat)
          ishtyp = hdata%angShell(ish,ati)
          il = ishtyp + 1
          do iao = 1, llao2(ishtyp)
             i = iao+basis%saoshell(ish,iat)
             ii = i*(1+i)/2 ! H0 is packed, note i*(i-1)/2+i = i*(1+i)/2
             pii = p(i,i)*evtoau
             ! save dE/dCN for CNi
             dhdcn(iat) = dhdcn(iat) + pii*dsedcn(ish, iat)
             ! save dE/dq for qi
             dhdq(iat) = dhdq(iat) + pii*dsedq(ish, iat)
          end do
       end do
    end do
References xtb_grad_core::dshellpoly(), xtb_intgrad::dtrf2(), xtb_mctc_convert::evtoau, xtb_intgrad::get_grad_overlap(), and xtb_mctc_constants::pi.
Referenced by peeq().
ccm_build_sh0()
subroutine xtb_peeq::ccm_build_sh0 (integer, dimension(:), intent(in) nShell, type(thamiltoniandata), intent(in) hData, real(wp), dimension(:, :), intent(in) selfEnergy, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tbasisset), intent(in) basis, integer, intent(in) nbf, integer, intent(in) nao, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3,3), intent(in) lattice, real(wp), intent(in) intcut, real(wp), dimension(nao,nao), intent(out) sint, real(wp), dimension(nao*(1+nao)/2), intent(out) h0, type(tb_wsc), intent(in) wsc) private
Definition at line 810 of file peeq_module.f90.
    use xtb_type_basisset
    use xtb_type_wsc
    use xtb_lin, only : lin
    use xtb_intgrad
    use xtb_scc_core
    implicit none
    integer, intent(in) :: nShell(:)
    type(THamiltonianData), intent(in) :: hData
    type(tb_wsc), intent(in) :: wsc
    type(TBasisset), intent(in) :: basis
    real(wp), intent(in) :: selfEnergy(:, :)
    integer, intent(in)  :: nat
    integer, intent(in)  :: nbf
    integer, intent(in)  :: nao
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(in)  :: lattice(3,3)
    real(wp),intent(in)  :: intcut
    real(wp),intent(out) :: sint(nao,nao)  ! overlap matrix S
    real(wp),intent(out) :: h0(nao*(1+nao)/2)
    integer, parameter :: llao (0:3) = (/ 1, 3, 6,10/)
    integer, parameter :: llao2(0:3) = (/ 1, 3, 5, 7/)
    integer i,j,k,l,m,ii,jj,ll,mm,kk,ki,kj,kl,mi,mj,ij
    real(wp) tmp1,tmp2,tmp3,tmp4,step,step2
    real(wp) dx,dy,dz,s00r,s00l,s00,alpj
    real(wp) skj,r1,r2,tt,t1,t2,t3,t4,f,ci,cc,cj,alpi,rab2,ab,est
    real(wp) :: den,den2,den4,enpoly
    real(wp) :: zi,zj,zetaij
    real(wp) :: hii,hjj,hav
    real(wp) :: shpoly,km
    logical  :: valaoi,valaoj
    real(wp)  ri(3),rj(3),t(3),f1,f2
    real(wp),parameter ::point(3) = 0.0_wp
    real(wp) dtmp(3),qtmp(6),ss(6,6),dd(3,6,6),qq(6,6,6),tmp(6,6)
    real(wp) sstmp(6,6) !TESTST
    integer ip,jp,iat,jat,ati,atj,ish,jsh,icao,jcao,iao,jao,jshmax,il,jl
    integer ishtyp,jshtyp,iptyp,jptyp,naoi,naoj,mli,mlj,iprim,jprim
    integer itt(0:3)
    integer kat
    parameter(itt  =(/0,1,4,10/))
    real(wp) :: saw(10)
    sint = 0.0_wp
    h0   = 0.0_wp
    !$omp parallel default(none) &
    !$omp private(iat,jat,ij,ati,cc,ci,rab2,atj,ish,ishtyp,valaoi,valaoj, &
    !$omp&        ri,rj,icao,naoi,iptyp,jsh,jshmax,jshtyp,jcao,naoj,jptyp, &
    !$omp&        ss,saw,est,alpi,alpj,ab,iprim,jprim,ip,jp,km,shpoly, &
    !$omp&        mli,mlj,tmp,zi,zj,zetaij,enpoly,iao,jao, &
    !$omp&        ii,jj,k,den,den2,den4,i,j,il,jl,hii,hjj,hav,t) &
    !$omp reduction (+:sint,h0) &
    !$omp shared(wsc,basis,at,nShell,hData,xyz,lattice,intcut,nat,selfEnergy)
    !$omp do schedule(runtime)
    do iat = 1, nat
       ri  = xyz(:,iat)
       ati = at(iat)
       do jat = 1, iat-1
          atj = at(jat)
          den = hdata%electronegativity(ati) - hdata%electronegativity(atj)
          den2 =  den**2
          den4 = den2**2
          ishells: do ish = 1, nshell(ati)
             ishtyp = hdata%angShell(ish,ati)
             icao = basis%caoshell(ish,iat)
             naoi = llao(ishtyp)
             iptyp = itt(ishtyp)
             jshmax = nshell(atj)
             if (iat == jat) jshmax = ish
             jshells: do jsh = 1, jshmax
                jshtyp = hdata%angShell(jsh,atj)
                jcao = basis%caoshell(jsh,jat)
                naoj = llao(jshtyp)
                jptyp = itt(jshtyp)
                il = ishtyp+1
                jl = jshtyp+1
                ! diagonals are the same for all H0 elements
                hii = selfenergy(ish, iat)
                hjj = selfenergy(jsh, jat)
                ! evaluate the EN polynom for this shells
                enpoly = (1.0_wp + hdata%enScale(jl-1,il-1)*den2 &
                   & + hdata%enScale4*hdata%enScale(jl-1,il-1)*den4)
                ! we scale the two shells depending on their exponent
                zi = hdata%slaterExponent(ish, ati)
                zj = hdata%slaterExponent(jsh, atj)
                zetaij = 2 * sqrt(zi*zj)/(zi+zj)
                ! now do the real magic (called EHT enhancement factor)
                km = hdata%kScale(jl-1,il-1) * hdata%pairParam(ati,atj) * zetaij * enpoly
                ! check for valence orbitals
                valaoi = hdata%valenceShell(ish, ati).eq.0
                valaoj = hdata%valenceShell(jsh, atj).eq.0
                ! and scale appropiately
                if (valaoi) then
                   if (valaoj) then
                      km = 0.0_wp
                   else
                      km = km * hdata%kDiff
                   endif
                else
                   if (valaoj) km = km * hdata%kDiff
                endif
                ! averaged H0 element (without overlap contribution!)
                hav = 0.5_wp * km * (hii + hjj)
                wscat: do kat = 1, wsc%itbl(jat,iat)
                   ss = 0.0_wp
                   t = wsc%lattr(:,kat,jat,iat)
                   rj = xyz(:,jat) + matmul(lattice,t)
                   ! distance dependent polynomial
                   shpoly = shellpoly(hdata%shellPoly(il,ati),hdata%shellPoly(jl,atj),&
                      &               hdata%atomicRad(ati),hdata%atomicRad(atj),ri,rj)
                   ! get overlap integral
                   call get_overlap(icao,jcao,naoi,naoj,ishtyp,jshtyp,ri,rj,point, &
                      &             intcut,basis%nprim,basis%primcount, &
                      &             basis%alp,basis%cont,ss)
                   !transform from CAO to SAO
                   call dtrf2(ss,ishtyp,jshtyp)
                   do ii = 1, llao2(ishtyp)
                      iao = ii+basis%saoshell(ish,iat)
                      do jj = 1, llao2(jshtyp)
                         jao = jj+basis%saoshell(jsh,jat)
                         if (jao > iao) cycle
                         ij = lin(iao,jao)
                         ! add all WSC images
                         sint(iao,jao) = sint(iao,jao) + ss(jj,ii)*wsc%w(jat,iat)
                         sint(jao,iao) = sint(jao,iao) + ss(jj,ii)*wsc%w(jat,iat)
                         ! Hamiltonian
                         h0(ij) = h0(ij) + hav * shpoly * ss(jj,ii) * wsc%w(jat,iat)
                      enddo
                   enddo
                enddo wscat
             enddo jshells
          enddo ishells
       enddo
    enddo
    !$OMP END DO
    !$OMP END PARALLEL
    ! diagonal elements
    do iat = 1, nat
       ati = at(iat)
       do ish = 1, nshell(ati)
          iao = 1+basis%saoshell(ish,iat)
          ishtyp = hdata%angShell(ish,ati)
          il = ishtyp + 1
          do iao = 1, llao2(ishtyp)
             i = iao+basis%saoshell(ish,iat)
             sint(i,i)=1.0_wp+sint(i,i)
             ii  = i*(1+i)/2 ! H0 is packed, note i*(i-1)/2+i = i*(1+i)/2
             ! calculate environment dependent shift
             hii = selfenergy(ish, iat)
             h0(ii) = hii
          end do
       end do
    end do
References xtb_intgrad::dtrf2(), xtb_intgrad::get_overlap(), lin(), and xtb_scc_core::shellpoly().
Referenced by peeq().
drep_grad()
pure subroutine xtb_peeq::drep_grad (type(trepulsiondata), intent(in) repData, type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) trans, real(wp), intent(out) erep, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma)
Definition at line 611 of file peeq_module.f90.
    use xtb_type_molecule
    use xtb_type_param
    use xtb_pbc_tools
    use xtb_pbc
    implicit none
    type(TRepulsionData), intent(in) :: repData
    type(TMolecule), intent(in) :: mol
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    real(wp), intent(out) :: erep
    integer :: i,j,k,lin
    integer :: iat,jat,ati,atj
    real(wp) :: ri(3),dr(3)
    real(wp) :: rij(3)
    real(wp) :: r2,r,r2top34,r2top34top2
    real(wp) :: den2,den4
    real(wp) :: alpha
    real(wp) :: repab
    real(wp) :: expterm
    real(wp) :: dtmp
    real(wp), parameter :: rthr = 1600.0_wp
    real(wp) :: w,t(3)
    integer  :: latrep(3),tx,ty,tz,itr
    call get_realspace_cutoff(mol%lattice,rthr,latrep)
    w = 1.0_wp
    ! initialize
    erep = 0.0_wp
    do i = 1, mol%n
       ati=mol%at(i)
       do j = 1, i
          do itr = 1, size(trans, dim=2)
             t = trans(:, itr)
             rij = mol%xyz(:,i) - mol%xyz(:,j) + t
             r2 = sum(rij**2)
             if(r2.gt.rthr .or. r2.lt.1.0e-6_wp) cycle
             atj=mol%at(j)
             r = sqrt(r2)
             den2 = (repdata%electronegativity(ati) - repdata%electronegativity(atj))**2
             den4 = den2**2
             alpha=sqrt(repdata%alpha(ati)*repdata%alpha(atj))&
                *(1.0_wp+(0.01_wp*den2+0.01_wp*den4)*repdata%enScale)
             repab = repdata%zeff(ati)*repdata%zeff(atj)
             r2top34 = r2**0.75_wp
             r2top34top2 = r2top34**2
             expterm = exp(-alpha*r2top34)*repab
             ! save repulsion energy
             erep = erep + expterm/r * w
             ! save repulsion gradient
             dtmp = expterm*(1.5_wp*alpha*r2top34 + 1)/r2top34top2 * w
             gradient(:,i) = gradient(:,i) - dtmp*rij
             gradient(:,j) = gradient(:,j) + dtmp*rij
             sigma = sigma - dtmp*outer_prod_3x3(rij,rij)
          enddo ! k WSC partner
       enddo ! j atom
    enddo ! i atom
References xtb_pbc::get_realspace_cutoff(), and xtb_pbc_tools::outer_prod_3x3().
Referenced by peeq().
dsrb_grad()
subroutine xtb_peeq::dsrb_grad (type(tmolecule), intent(in) mol, type(tshortrangedata), intent(in) srb, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:,:,:), intent(in) dcndr, real(wp), dimension(:,:,:), intent(in) dcndL, real(wp), dimension(:, :), intent(in) trans, real(wp), intent(out) esrb, real(wp), dimension(:, :), intent(inout) gradient, real(wp), dimension(:, :), intent(inout) sigma)
Definition at line 672 of file peeq_module.f90.
    use xtb_type_param
    use xtb_type_molecule
    use xtb_approxrab
    use xtb_disp_ncoord
    use xtb_pbc_tools
    use xtb_pbc
    implicit none
    type(TMolecule), intent(in) :: mol
    type(TShortRangeData), intent(in) :: srb
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(inout) :: gradient(:, :)
    real(wp), intent(inout) :: sigma(:, :)
    real(wp), intent(out) :: esrb
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:,:,:)
    real(wp), intent(in) :: dcndL(:,:,:)
    integer :: i,j,k,wsAt
    integer :: iat,jat,ati,atj
    integer :: nsrb,itr
    real(wp) :: den
    real(wp) :: expterm
    ! distances
    real(wp) :: rij(3)
    real(wp) :: r2,r,dr,rab
    real(wp) :: dtmp,pre
    real(wp) :: w
    ! allocatables
    real(wp), allocatable :: dEdr0(:)
    real(wp), allocatable :: drab0dr(:,:,:)
    real(wp), allocatable :: drab0dL(:,:,:)
    real(wp), allocatable :: rab0(:)
    integer,  allocatable :: srblist(:,:)
    ! initialize
    esrb = 0.0_wp
    w = 1.0_wp
    call build_srblist(mol,nsrb,srblist)
    if (nsrb.eq.0) return
    ! get memory
    allocate( dedr0(nsrb), source = 0.0_wp )
    allocate( drab0dr(3,mol%n,nsrb), source = 0.0_wp )
    allocate( drab0dl(3,3,nsrb),     source = 0.0_wp )
    allocate( rab0(nsrb),            source = 0.0_wp )
    ! get approximated distances rab and gradients
    call pbc_approx_rab(mol%n,mol%at,mol%xyz,cn,dcndr,dcndl,nsrb,srblist,srb%shift, &
       &                rab0,drab0dr,drab0dl)
    do i = 1, nsrb
       iat = srblist(1,i)
       jat = srblist(2,i)
       ati = mol%at(iat)
       atj = mol%at(jat)
       den = en(ati) - en(atj)
       pre = srb%steepness*(1.0_wp + srb%enScale*den**2)
       do itr = 1, size(trans, dim=2)
          rij = mol%xyz(:,iat) - (mol%xyz(:,jat) + trans(:, itr))
          rab = norm2(rij)
          dr = rab - rab0(i)
          expterm = srb%prefactor*exp(-pre*dr**2)
          ! save SRB energy
          esrb = esrb + expterm * w
          dtmp = 2.0_wp*pre*dr*expterm * w
          gradient(:,iat) = gradient(:,iat) - dtmp*rij/rab
          gradient(:,jat) = gradient(:,jat) + dtmp*rij/rab
          ! three body gradient
          dedr0(i) = dedr0(i) + dtmp
          sigma = sigma - dtmp*spread(rij, 1, 3)*spread(rij, 2, 3)/rab
       enddo ! rep
    enddo ! i
    call contract(drab0dr, dedr0, gradient, beta=1.0_wp)
    call contract(drab0dl, dedr0, sigma, beta=1.0_wp)
References build_srblist(), xtb_approxrab::en, and xtb_approxrab::pbc_approx_rab().
Referenced by peeq().
pbc_build_dsh0()
subroutine xtb_peeq::pbc_build_dsh0 (integer, dimension(:), intent(in) nShell, type(thamiltoniandata), intent(in) hData, real(wp), dimension(:, :), intent(in) selfEnergy, real(wp), dimension(:, :), intent(in) dSEdcn, real(wp), dimension(:, :), intent(in) dSEdq, integer, intent(in) nat, type(tbasisset), intent(in) basis, real(wp), intent(in) thr, integer, intent(in) nao, integer, intent(in) nbf, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(:,:), intent(in) trans, real(wp), dimension(nao,nao), intent(in) P, real(wp), dimension(nao,nao), intent(in) Pew, real(wp), dimension(3,nat), intent(inout) g, real(wp), dimension(3,3), intent(inout) sigma, real(wp), dimension(nat), intent(inout) dHdcn, real(wp), dimension(nat), intent(inout) dHdq)
Definition at line 1429 of file peeq_module.f90.
    use xtb_mctc_constants, only : pi
    use xtb_mctc_convert
    use xtb_type_wsc
    use xtb_type_basisset
    use xtb_intgrad
    use xtb_grad_core
    implicit none
    ! intent in
    integer, intent(in) :: nShell(:)
    type(THamiltonianData), intent(in) :: hData
    real(wp), intent(in) :: selfEnergy(:, :)
    real(wp), intent(in) :: dSEdcn(:, :)
    real(wp), intent(in) :: dSEdq(:, :)
    integer, intent(in)      :: nat
    type(TBasisset), intent(in) :: basis
    real(wp),intent(in)      :: thr
    integer, intent(in)      :: nao
    integer, intent(in)      :: nbf
    integer, intent(in) :: at(nat)
    real(wp),intent(in) :: xyz(3,nat)
    real(wp),intent(in) :: trans(:,:)
    real(wp),intent(in) :: P(nao,nao)
    real(wp),intent(in) :: Pew(nao,nao)
    ! intent inout
    real(wp),intent(inout) :: dHdq(nat)
    real(wp),intent(inout) :: dHdcn(nat)
    real(wp),intent(inout) :: g(3,nat)
    real(wp),intent(inout) :: sigma(3,3)
    integer, parameter :: llao (0:3) = (/ 1, 3, 6,10/)
    integer, parameter :: llao2(0:3) = (/ 1, 3, 5, 7/)
    integer itt(0:3)
    parameter(itt=(/0,1,4,10/))
    real(wp) tmp1,tmp2,tmp3,step,step2,step3,s00r,s00l,s00,alpj
    real(wp) skj,r1,r2,tt,t1,t2,t3,t4
    real(wp) thr2,f,ci,cc,cj,alpi,rab2,ab,est
    real(wp) f1,f2,tmp(6,6),rij(3),ri(3),rj(3),rij2
    real(wp) stmp,ral(3,3),rar(3,3),rbl(3,3),pre
    real(wp) dtmp,qtmp,rbr(3,3),r2l(3),r2r(3),qqa(6,6,6,3)
    real(wp)  ss(6,6,3),ddc(3,6,6,3),qqc(6,6,6,3),dda(3,6,6,3)
    integer i,j,k,l,m,ii,jj,ll,mm,kk,ki,kj,kl,mi,mj,ij,lin,jshmax
    integer ip,jp,iat,jat,kat,ati,atj,ish,jsh,icao,jcao,iao,jao,ixyz,jxyz
    integer ishtyp,jshtyp,iptyp,jptyp,naoi,naoj,mli,mlj,iprim,jprim
    real(wp) :: dumdum(3),dum,sdq(6,6),sdqg(3,6,6)
    real(wp),parameter :: point(3) = 0.0_wp
    integer  :: il,jl,itr
    real(wp) :: Hij,Pii,Pij,HPij,H0sr
    real(wp) :: den,den2,den4,enpoly
    real(wp) :: zi,zj,zetaij
    real(wp) :: hii,hjj,hav
    real(wp) :: shpoly,dshpoly(3),km
    logical  :: valaoi,valaoj
    real(wp) :: g_xyz(3)
    integer  :: tx,ty,tz
    real(wp) :: t(3),w
    w = 1.0_wp !/ real(product(2*latrep+1),wp)
    !$omp parallel default(none) &
    !$omp private(iat,jat,ixyz,ati,cc,ci,rab2,atj,ish,ishtyp,valaoi,valaoj,g_xyz, &
    !$omp&        ri,rj,icao,naoi,iptyp,jsh,jshmax,jshtyp,jcao,naoj,jptyp,rij2, &
    !$omp&        sdq,sdqg,est,alpi,alpj,ab,iprim,jprim,ip,jp,km,shpoly,dshpoly, &
    !$omp&        mli,mlj,dum,dumdum,tmp,stmp,rij,zi,zj,zetaij,enpoly,iao,jao, &
    !$omp&        ii,jj,k,den,den2,den4,i,j,il,jl,hii,hjj,hav,Pij,Hij,HPij,H0sr, &
    !$omp&        itr,t) &
    !$omp reduction (+:g,sigma,dhdcn,dhdq) &
    !$omp shared(basis,at,nShell,hData,xyz,thr,nat,trans,P,Pew,w,selfEnergy, &
    !$omp& dSEdcn,dSEdq)
    !$omp do schedule(runtime)
    do iat = 1, nat
       ri  = xyz(:,iat)
       ati = at(iat)
       do jat = 1, iat-1
          atj = at(jat)
          den = hdata%electronegativity(ati) - hdata%electronegativity(atj)
          den2 =  den**2
          den4 = den2**2
          ishells: do ish = 1, nshell(ati)
             ishtyp = hdata%angShell(ish,ati)
             icao = basis%caoshell(ish,iat)
             naoi = llao(ishtyp)
             iptyp = itt(ishtyp)
             jshmax = nshell(atj)
             if(iat == jat) jshmax = ish
             jshells: do jsh = 1, jshmax
                jshtyp = hdata%angShell(jsh,atj)
                jcao = basis%caoshell(jsh,jat)
                naoj = llao(jshtyp)
                jptyp = itt(jshtyp)
                il = ishtyp+1
                jl = jshtyp+1
                ! diagonals are the same for all H0 elements
                hii = selfenergy(ish, iat)
                hjj = selfenergy(jsh, jat)
                ! evaluate the EN polynom for this shells
                enpoly = (1.0_wp + hdata%enScale(jl-1,il-1)*den2 &
                   & + hdata%enScale4*hdata%enScale(jl-1,il-1)*den4)
                ! we scale the two shells depending on their exponent
                zi = hdata%slaterExponent(ish, ati)
                zj = hdata%slaterExponent(jsh, atj)
                zetaij = 2 * sqrt(zi*zj)/(zi+zj)
                ! now do the real magic (called EHT enhancement factor)
                km = hdata%kScale(jl-1,il-1) * hdata%pairParam(ati,atj) * zetaij * enpoly
                ! check for valence orbitals
                valaoi = hdata%valenceShell(ish, ati).eq.0
                valaoj = hdata%valenceShell(jsh, atj).eq.0
                ! and scale appropiately
                if (valaoi) then
                   if (valaoj) then
                      km = 0.0_wp
                   else
                      km = km * hdata%kDiff
                   endif
                else
                   if (valaoj) km = km * hdata%kDiff
                endif
                ! averaged H0 element (without overlap contribution!)
                hav = 0.5_wp * km * (hii + hjj)
                do itr = 1, size(trans, dim=2)
                   t = trans(:, itr)
                   rj = xyz(:,jat) + t
                   rij = ri - rj
                   rij2 = sum(rij**2)
                   ! distance dependent polynomial
                   call dshellpoly(hdata%shellPoly(il,ati),hdata%shellPoly(jl,atj),&
                      & hdata%atomicRad(ati),hdata%atomicRad(atj),rij2,ri,rj,&
                      & shpoly,dshpoly)
                   call get_grad_overlap(icao,jcao,naoi,naoj,ishtyp,jshtyp,ri,rj, &
                      &                  point,thr,basis%nprim,basis%primcount, &
                      &                  basis%alp,basis%cont,sdq,sdqg)
                   call dtrf2(sdq,ishtyp,jshtyp)
                   do ixyz = 1, 3
                      ! transform from CAO to SAO, only transform the gradient
                      tmp = sdqg(ixyz,:,:)
                      call dtrf2(tmp,ishtyp,jshtyp)
                      sdqg(ixyz,:,:) = tmp
                   enddo
                   do ii = 1, llao2(ishtyp)
                      iao = ii+basis%saoshell(ish,iat)
                      do jj = 1, llao2(jshtyp)
                         jao = jj+basis%saoshell(jsh,jat)
                         pij = p(jao,iao) * evtoau
                         ! Hamiltonian element without overlap
                         hij  = hav * shpoly
                         hpij = hij * pij
                         ! overlap contribution
                         stmp = 2*w * (hpij - pew(jao,iao))
                         ! distance dependent polynomial contribution
                         h0sr = 2*hpij*sdq(jj,ii)*w
                         g_xyz = stmp*sdqg(:,jj,ii) + h0sr*dshpoly/shpoly
                         ! distribute to atom i
                         g(:,iat) = g(:,iat) + g_xyz
                         ! distribute to atom j
                         g(:,jat) = g(:,jat) - g_xyz
                         ! reduce to strain
                         sigma(:,1) = sigma(:,1) + g_xyz*rij(1)
                         sigma(:,2) = sigma(:,2) + g_xyz*rij(2)
                         sigma(:,3) = sigma(:,3) + g_xyz*rij(3)
                         ! Hamiltonian without Hav
                         hpij = km * shpoly * pij * sdq(jj,ii) * w
                         ! save dE/dCN for CNi
                         dhdcn(iat) = dhdcn(iat) + hpij*dsedcn(ish, iat)
                         ! save dE/dCN for CNj
                         dhdcn(jat) = dhdcn(jat) + hpij*dsedcn(jsh, jat)
                         ! save dE/dq for qi
                         dhdq(iat) = dhdq(iat) + hpij*dsedq(ish, iat)
                         ! save dE/dq for qj
                         dhdq(jat) = dhdq(jat) + hpij*dsedq(jsh, jat)
                      enddo
                   enddo
                enddo
             enddo jshells
          enddo  ishells
       enddo ! jat
    enddo  ! iat
    !$omp end do
    !$omp end parallel
    ! diagonal contributions
    do iat = 1, nat
       ati = at(iat)
       do ish = 1, nshell(ati)
          iao = 1+basis%saoshell(ish,iat)
          ishtyp = hdata%angShell(ish,ati)
          il = ishtyp + 1
          do iao = 1, llao2(ishtyp)
             i = iao+basis%saoshell(ish,iat)
             ii = i*(1+i)/2 ! H0 is packed, note i*(i-1)/2+i = i*(1+i)/2
             pii = p(i,i)*evtoau
             ! save dE/dCN for CNi
             dhdcn(iat) = dhdcn(iat) + pii*dsedcn(ish, iat)
             ! save dE/dq for qi
             dhdq(iat) = dhdq(iat) + pii*dsedq(ish, iat)
          end do
       end do
    end do
References xtb_grad_core::dshellpoly(), xtb_intgrad::dtrf2(), xtb_mctc_convert::evtoau, xtb_intgrad::get_grad_overlap(), and xtb_mctc_constants::pi.
Referenced by peeq().
pbc_build_sh0()
subroutine xtb_peeq::pbc_build_sh0 (integer, dimension(:), intent(in) nShell, type(thamiltoniandata), intent(in) hData, real(wp), dimension(:, :), intent(in) selfEnergy, integer, intent(in) nat, integer, dimension(nat), intent(in) at, type(tbasisset), intent(in) basis, integer, intent(in) nbf, integer, intent(in) nao, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(:,:), intent(in) trans, real(wp), intent(in) intcut, real(wp), dimension(nao,nao), intent(out) sint, real(wp), dimension(nao*(1+nao)/2), intent(out) h0)
Definition at line 1001 of file peeq_module.f90.
    use xtb_type_basisset
    use xtb_lin, only : lin
    use xtb_intgrad
    use xtb_scc_core
    implicit none
    integer, intent(in) :: nShell(:)
    type(THamiltonianData), intent(in) :: hData
    type(TBasisset), intent(in) :: basis
    real(wp), intent(in) :: selfEnergy(:, :)
    integer, intent(in)  :: nat
    integer, intent(in)  :: nbf
    integer, intent(in)  :: nao
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(in)  :: trans(:,:)
    real(wp),intent(in)  :: intcut
    real(wp),intent(out) :: sint(nao,nao)  ! overlap matrix S
    real(wp),intent(out) :: h0(nao*(1+nao)/2)
    integer, parameter :: llao (0:3) = (/ 1, 3, 6,10/)
    integer, parameter :: llao2(0:3) = (/ 1, 3, 5, 7/)
    integer i,j,k,l,m,ii,jj,ll,mm,kk,ki,kj,kl,mi,mj,ij
    real(wp) tmp1,tmp2,tmp3,tmp4,step,step2
    real(wp) dx,dy,dz,s00r,s00l,s00,alpj
    real(wp) skj,r1,r2,tt,t1,t2,t3,t4,f,ci,cc,cj,alpi,rab2,ab,est
    real(wp) :: den,den2,den4,enpoly
    real(wp) :: zi,zj,zetaij
    real(wp) :: hii,hjj,hav
    real(wp) :: shpoly,km
    logical  :: valaoi,valaoj
    real(wp)  ri(3),rj(3),f1,f2
    real(wp), parameter :: point(3) = 0.0_wp
    real(wp) dtmp(3),qtmp(6),ss(6,6),dd(3,6,6),qq(6,6,6),tmp(6,6)
    real(wp) sstmp(6,6) !TESTST
    integer ip,jp,iat,jat,ati,atj,ish,jsh,icao,jcao,iao,jao,jshmax,il,jl
    integer ishtyp,jshtyp,iptyp,jptyp,naoi,naoj,mli,mlj,iprim,jprim
    integer itt(0:3)
    integer kat
    parameter(itt  =(/0,1,4,10/))
    real(wp) :: saw(10)
    integer  :: itr
    real(wp) :: t(3),w
    w = 1.0_wp !/ real(product(2*latrep+1),wp)
    sint = 0.0_wp
    h0   = 0.0_wp
    !$omp parallel default(none) &
    !$omp private(iat,jat,ij,ati,cc,ci,rab2,atj,ish,ishtyp,valaoi,valaoj, &
    !$omp&        ri,rj,icao,naoi,iptyp,jsh,jshmax,jshtyp,jcao,naoj,jptyp, &
    !$omp&        ss,saw,est,alpi,alpj,ab,iprim,jprim,ip,jp,km,shpoly, &
    !$omp&        mli,mlj,tmp,zi,zj,zetaij,enpoly,iao,jao, &
    !$omp&        ii,jj,k,den,den2,den4,i,j,il,jl,hii,hjj,hav,itr,t) &
    !$omp reduction (+:sint,h0) &
    !$omp shared(basis,at,nShell,hData,xyz,intcut,nat,trans,w,selfEnergy)
    !$omp do schedule(runtime)
    do iat = 1, nat
       ri  = xyz(:,iat)
       ati = at(iat)
       do jat = 1, iat-1
          atj = at(jat)
          den = hdata%electronegativity(ati) - hdata%electronegativity(atj)
          den2 =  den**2
          den4 = den2**2
          ishells: do ish = 1, nshell(ati)
             ishtyp = hdata%angShell(ish,ati)
             icao = basis%caoshell(ish,iat)
             naoi = llao(ishtyp)
             iptyp = itt(ishtyp)
             jshmax = nshell(atj)
             if (iat == jat) jshmax = ish
             jshells: do jsh = 1, jshmax
                jshtyp = hdata%angShell(jsh,atj)
                jcao = basis%caoshell(jsh,jat)
                naoj = llao(jshtyp)
                jptyp = itt(jshtyp)
                il = ishtyp+1
                jl = jshtyp+1
                ! diagonals are the same for all H0 elements
                hii = selfenergy(ish, iat)
                hjj = selfenergy(jsh, jat)
                ! evaluate the EN polynom for this shells
                enpoly = (1.0_wp + hdata%enScale(jl-1,il-1)*den2 &
                   & + hdata%enScale4*hdata%enScale(jl-1,il-1)*den4)
                ! we scale the two shells depending on their exponent
                zi = hdata%slaterExponent(ish, ati)
                zj = hdata%slaterExponent(jsh, atj)
                zetaij = 2 * sqrt(zi*zj)/(zi+zj)
                ! now do the real magic (called EHT enhancement factor)
                km = hdata%kScale(jl-1,il-1) * hdata%pairParam(ati,atj) * zetaij * enpoly
                ! check for valence orbitals
                valaoi = hdata%valenceShell(ish, ati).eq.0
                valaoj = hdata%valenceShell(jsh, atj).eq.0
                ! and scale appropiately
                if (valaoi) then
                   if (valaoj) then
                      km = 0.0_wp
                   else
                      km = km * hdata%kDiff
                   endif
                else
                   if (valaoj) km = km * hdata%kDiff
                endif
                ! averaged H0 element (without overlap contribution!)
                hav = 0.5_wp * km * (hii + hjj)
                do itr = 1, size(trans, dim=2)
                   t = trans(:, itr)
                   rj = xyz(:,jat) + t
                   ss = 0.0_wp
                   ! distance dependent polynomial
                   shpoly = shellpoly(hdata%shellPoly(il,ati),hdata%shellPoly(jl,atj),&
                      &               hdata%atomicRad(ati),hdata%atomicRad(atj),ri,rj)
                   ! get overlap integral
                   call get_overlap(icao,jcao,naoi,naoj,ishtyp,jshtyp,ri,rj,point, &
                      &             intcut,basis%nprim,basis%primcount, &
                      &             basis%alp,basis%cont,ss)
                   !transform from CAO to SAO
                   call dtrf2(ss,ishtyp,jshtyp)
                   do ii = 1, llao2(ishtyp)
                      iao = ii+basis%saoshell(ish,iat)
                      do jj = 1, llao2(jshtyp)
                         jao = jj+basis%saoshell(jsh,jat)
                         if (jao > iao) cycle
                         ij = lin(iao,jao)
                         ! add all WSC images
                         sint(iao,jao) = sint(iao,jao) + ss(jj,ii)*w
                         sint(jao,iao) = sint(jao,iao) + ss(jj,ii)*w
                         ! Hamiltonian
                         h0(ij) = h0(ij) + hav * shpoly * ss(jj,ii)*w
                      enddo
                   enddo
                enddo
             enddo jshells
          enddo ishells
       enddo
    enddo
    !$OMP END DO
    !$OMP END PARALLEL
    ! diagonal elements
    do iat = 1, nat
       ati = at(iat)
       do ish = 1, nshell(ati)
          iao = 1+basis%saoshell(ish,iat)
          ishtyp = hdata%angShell(ish,ati)
          il = ishtyp + 1
          do iao = 1, llao2(ishtyp)
             i = iao+basis%saoshell(ish,iat)
             sint(i,i)=1.0_wp+sint(i,i)
             ii  = i*(1+i)/2 ! H0 is packed, note i*(i-1)/2+i = i*(1+i)/2
             ! calculate environment dependent shift
             hii = selfenergy(ish, iat)
             h0(ii) = hii
          end do
       end do
    end do
References xtb_intgrad::dtrf2(), xtb_intgrad::get_overlap(), lin(), and xtb_scc_core::shellpoly().
Referenced by peeq().
peeq()
subroutine, public xtb_peeq::peeq (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, type(twavefunction), intent(inout) wfn, type(tbasisset), intent(in) basis, type(txtbdata), intent(in) xtbData, type(tborn), intent(inout), allocatable gbsa, real(wp), intent(inout) egap, real(wp), intent(in) et, integer, intent(in) prlevel, logical, intent(in) grd, logical, intent(in) ccm, real(wp), intent(in) acc, real(wp), intent(inout) etot, real(wp), dimension(3,mol%n), intent(inout) gradient, real(wp), dimension(3,3), intent(inout) sigma, type(scc_results), intent(out) res)
Parameters
[in] mol molecular structure infomation
[in] basis basis set
[in] et electronic temperature
[in] prlevel amount of printout
[in] grd toggles gradient calculation
[in] acc numerical accuracy
[in] ccm use cyclic cluster model
[in,out] etot total energy
[in,out] egap HOMO-LUMO gap
[in,out] gradient molecular gradient
[in,out] wfn TB-wavefunction
[out] res bundles all calculation informations
Definition at line 46 of file peeq_module.f90.
 ! ------------------------------------------------------------------------
 !  Class definitions
 ! ------------------------------------------------------------------------
    use xtb_solv_gbsa, only : tborn
    use xtb_type_environment
    use xtb_type_molecule
    use xtb_type_wavefunction
    use xtb_type_basisset
    use xtb_type_param
    use xtb_type_data
    use xtb_type_timer
 ! ------------------------------------------------------------------------
 !  Get interfaces
 ! ------------------------------------------------------------------------
    use xtb_readin
    use xtb_aespot
    use xtb_scc_core
    use xtb_grad_core
    use xtb_eeq
    use xtb_disp_ncoord
    use xtb_lineardep
    use xtb_pbc
    implicit none
    character(len=*), parameter :: source = 'peeq'
 ! ------------------------------------------------------------------------
 !  INPUT
 ! ------------------------------------------------------------------------
    type(TEnvironment), intent(inout)    :: env
    type(TMolecule),  intent(in) :: mol
    type(TBasisset),  intent(in) :: basis
    type(TxTBData), intent(in) :: xtbData
    real(wp),intent(in)            :: et
    integer, intent(in)            :: prlevel
    logical, intent(in)            :: grd
    real(wp),intent(in)            :: acc
    logical, intent(in)            :: ccm
 ! ------------------------------------------------------------------------
 !  INPUT/OUTPUT
 ! ------------------------------------------------------------------------
    real(wp),intent(inout)                    :: etot
    real(wp),intent(inout)                    :: egap
    real(wp),intent(inout),dimension(3,mol%n) :: gradient
    type(TWavefunction),intent(inout)       :: wfn
    type(TBorn),allocatable,intent(inout) :: gbsa
 ! ------------------------------------------------------------------------
 !  OUTPUT
 ! ------------------------------------------------------------------------
    type(scc_results),intent(out) :: res
 ! ------------------------------------------------------------------------
    type(chrg_parameter) :: chrgeq
    real(wp), allocatable :: cn(:), dcndr(:,:,:), dcndL(:,:,:)
    real(wp), allocatable :: ccn(:), dccndr(:,:,:), dccndL(:,:,:)
    real(wp), allocatable :: X    (:,:)
    real(wp), allocatable :: S    (:,:)
    real(wp), allocatable :: H    (:,:)
    real(wp), allocatable :: H0   (:)
    real(wp), allocatable :: H1   (:)
    real(wp), allocatable :: zsh  (:)
    real(wp), allocatable :: kcnao(:)
    real(wp), allocatable :: kqao (:)
    real(wp), allocatable :: selfEnergy(:, :)
    real(wp), allocatable :: dSEdcn(:, :)
    real(wp), allocatable :: dSEdq(:, :)
    integer :: rep_cn(3)
    integer :: nid
    integer, allocatable :: idnum(:)
    real(wp),allocatable :: chargeWidth(:, :)
    type(TGaussianSmeared) :: coulomb
    type(TENEquilibration) :: eeq
 ! ------------------------------------------------------------------------
    ! local variable (without comment)
    integer :: ii,jj,i,j,k,m,iat,jat,ati,atj,kk
    integer :: il,jl
    integer,parameter :: lladr(4)    = [1,3,6,10]
    integer,parameter :: lladr2(0:3) = [1,3,5,7 ]
    real(wp) :: dipol(3)
    real(wp) :: eatoms,eat
    real(wp) :: dum
    logical :: ex
    logical :: minpr
    logical :: pr
    logical :: fail
    ! timer
    type(tb_timer) :: timer
    ! Fermi smearing variables
    real(wp) :: efa,efb,nfoda,nfodb,ga,gb
    ! numerical thresholds
    real(wp) :: intcut,neglect,neglect2,scfconv
    ! energies
    real(wp) :: eel,ed,ees,exb,ep
 ! ---------------------------------------
 !  PEEQ information
 ! ---------------------------------------
    real(wp) , allocatable, dimension(:)     :: rab0
    real(wp) , allocatable, dimension(:,:,:) :: grab0
    real(wp) , allocatable, dimension(:)     :: lcn
    real(wp) , allocatable, dimension(:,:,:) :: dlcn
    real(wp),               dimension(2)     :: hbpi
    real(wp),               dimension(2)     :: hbpj
    real(wp) :: esrb
    real(wp) :: ehb
    real(wp) :: den2
    real(wp) :: den4
    real(wp) :: ken2
    real(wp) :: ken4
    integer  :: nhb
    integer  :: nh
    integer  :: ich
    logical :: debug
    logical :: exitRun
 ! ---------------------------------------
 !  PEEQ q dependent H0
 ! ---------------------------------------
    real(wp),allocatable, dimension(:)     :: qeeq
    real(wp),allocatable, dimension(:,:,:) :: dqdr
    real(wp),allocatable, dimension(:,:,:) :: dqdL
    real(wp),allocatable, dimension(:)     :: dHdq
    real(wp),allocatable, dimension(:)     :: dHdcn
    real(wp),allocatable, dimension(:,:)   :: pew
    real(wp),allocatable, dimension(:)     :: tmp
 ! ---------------------------------------
 !  PEEQ WSC information
 ! ---------------------------------------
    real(wp),dimension(3,3),intent(inout)     :: sigma
    type(TLatticePoint) :: latp
    real(wp), allocatable :: trans(:, :)
 ! For eigenvalues of S via dsyev routine
    real(wp),allocatable,dimension(:,:)       :: Stmp
    real(wp),allocatable,dimension(:)         :: ev_s
    integer                                   :: info
    integer                                   :: lwork
    real(wp),allocatable,dimension(:)         :: aux
    real(wp) :: test(1)
    integer :: xdim ! new dimension of the cut Overlap (lin.depend.)
    character(len=*),parameter :: scifmt = &
       '(10x,":",2x,a,e22.7,1x,a,1x,":")'
    character(len=*),parameter :: dblfmt = &
       '(10x,":",2x,a,f18.7,5x,a,1x,":")'
    character(len=*),parameter :: intfmt = &
       '(10x,":",2x,a,i18,      10x,":")'
    character(len=*),parameter :: chrfmt = &
       '(10x,":",2x,a,a18,      10x,":")'
 ! ---------------------------------------
 !  EEQ/GBSA information
 ! ---------------------------------------
    real(wp) :: gsolv
    associate( nao => basis%nao, &
          &    nbf => basis%nbf, &
          &    nshell => basis%nshell, &
          &    naop => basis%nao*(basis%nao+1)/2, &
          &    nbfp => basis%nbf*(basis%nbf+1)/2)
    if (profile) then
       if (allocated(gbsa)) then
          call timer%new(9,.false.)
       else
          call timer%new(8,.false.)
       endif
    endif
    if (profile) call timer%measure(1,"EHT setup")
    etot  = 0.0_wp
    dipol = 0.0_wp
    exb   = 0.0_wp
    ga    = 0.0_wp
    gb    = 0.0_wp
    eel   = 0.0_wp
    ep    = 0.0_wp
    ehb   = 0.0_wp
    esrb  = 0.0_wp
    ed    = 0.0_wp
    ees   = 0.0_wp
    gradient = 0.0_wp
    !debug = prlevel.gt.2
    debug =.false.
    pr    = prlevel.gt.1
    minpr = prlevel.gt.0
 ! ---------------------------------------
 !  Numerical stuff and cutoffs
 ! ---------------------------------------
    intcut=25.0_wp-10.0_wp*log10(acc)
    intcut=max(20.0_wp,intcut)
    neglect =10.0e-9_wp*acc
    neglect2=neglect*10.0_wp
    scfconv=1.e-6_wp*acc
    call init(latp, env, mol, 60.0_wp)
 ! ---------------------------------------
 !  IMPORTANT FACT: H is given in eV
 ! ---------------------------------------
 ! ---------------------------------------
 !  Get memory
 ! ---------------------------------------
    allocate(cn(mol%n));                     cn = 0.0_wp
    allocate(dcndr(3,mol%n,mol%n));       dcndr = 0.0_wp
    allocate(dcndl(3,3,mol%n));           dcndl = 0.0_wp
    allocate(ccn(mol%n));                   ccn = 0.0_wp
    allocate(dccndr(3,mol%n,mol%n));     dccndr = 0.0_wp
    allocate(dccndl(3,3,mol%n));         dccndl = 0.0_wp
    allocate(h(nao,nao));                     h = 0.0_wp
    allocate(x(nao,nao));                     x = 0.0_wp
    allocate(h0(naop));                      h0 = 0.0_wp
    allocate(s(nao,nao));                     s = 0.0_wp
    allocate(h1(naop));                      h1 = 0.0_wp
    allocate(kcnao(nao));                 kcnao = 0.0_wp
    allocate(kqao(nao));                   kqao = 0.0_wp
    allocate(zsh(nshell));                  zsh = 0.0_wp
    allocate(selfenergy(maxval(xtbdata%nshell), mol%n))
    allocate(dsedcn(maxval(xtbdata%nshell), mol%n))
    allocate(dsedq(maxval(xtbdata%nshell), mol%n))
    allocate(qeeq(mol%n));           qeeq = 0.0_wp
    allocate(dqdr(3,mol%n,mol%n)); dqdr = 0.0_wp
    allocate(dqdl(3,3,mol%n));     dqdl = 0.0_wp
 ! ---------------------------------------
 !  Fill levels
 ! ---------------------------------------
    call setzshell(xtbdata,mol%n,mol%at,nshell,mol%z,zsh,eatoms,0)
    if(wfn%nel.ne.0) then
       call occu(nao,wfn%nel,wfn%nopen,wfn%ihomoa,wfn%ihomob,wfn%focca,wfn%foccb)
       wfn%focc = wfn%focca + wfn%foccb
       wfn%ihomo=wfn%ihomoa
    else
       wfn%focc=0.0_wp
       wfn%ihomo=0
       wfn%ihomoa=0
       wfn%nopen=0
    endif
    if (prlevel > 1) then
       write(env%unit,'(/,10x,51("."))')
       write(env%unit,'(10x,":",22x,a,22x,":")') "SETUP"
       write(env%unit,'(10x,":",49("."),":")')
       write(env%unit,intfmt) "# basis functions  ",basis%nbf
       write(env%unit,intfmt) "# atomic orbitals  ",basis%nao
       write(env%unit,intfmt) "# shells           ",basis%nshell
       write(env%unit,intfmt) "# electrons        ",wfn%nel
       if (mol%npbc > 0) &
       write(env%unit,chrfmt) "PBC by CCM         ",bool2string(ccm)
       write(env%unit,dblfmt) "electronic temp.   ",et,      "K   "
       write(env%unit,dblfmt) "accuracy           ",acc,     "    "
       write(env%unit,scifmt) "-> integral cutoff ",intcut,  "    "
       write(env%unit,scifmt) "-> integral neglect",neglect, "    "
       write(env%unit,'(10x,51("."))')
    endif
    if (profile) call timer%measure(1)
    if (profile) call timer%measure(2,"Coordination number")
 ! ---------------------------------------
 !  Get CN(1:n) + dcndr(3,1:n,1:n) under pbc
 ! ---------------------------------------
    call latp%getLatticePoints(trans, 40.0_wp)
    call getcoordinationnumber(mol, trans, 40.0_wp, cntype%erf, &
       & cn, dcndr, dcndl)
    call cutcoordinationnumber(mol%n, cn, dcndr, dcndl, maxcn=8.0_wp)
    if (profile) call timer%measure(2)
    if (profile) call timer%measure(4,"D4 Dispersion")
 ! ----------------------------------------
 !  D4 dispersion energy + gradient (2B) under pbc
 ! ----------------------------------------
    call getencharges(env, mol, cn, dcndr, dcndl, qeeq, dqdr, dqdl)
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Could not get EN charges for D4 dispersion", source)
       return
    end if
    call getcoordinationnumber(mol, trans, 40.0_wp, cntype%cov, &
       & ccn, dccndr, dccndl)
    call latp%getLatticePoints(trans, 60.0_wp)
    call d4_gradient(mol, xtbdata%dispersion%dispm, trans, xtbdata%dispersion%dpar, &
       & xtbdata%dispersion%g_a, xtbdata%dispersion%g_c, xtbdata%dispersion%wf, &
       & 60.0_wp, ccn, dccndr, dccndl, qeeq, dqdr, dqdl, ed, gradient, sigma)
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Evaluation of dispersion energy failed", source)
       return
    end if
    ! better save than sorry, delete the D4-EEQ charges
    qeeq(:) = 0.0_wp
    dqdr(:, :, :) = 0.0_wp
    dqdl(:, :, :) = 0.0_wp
    if (profile) call timer%measure(4)
 ! ---------------------------------------
 !  Get EEQ charges q(1:n) + dqdr(3,1:n,1:n) under pbc
 ! ---------------------------------------
    if (allocated(gbsa)) then
       if (profile) call timer%measure(9,"GBSA setup")
       ! compute Born radii
       call gbsa%update(env, mol%at, mol%xyz)
       ! add SASA term to energy and gradient
       ees = gbsa%gsasa + gbsa%gshift
       gsolv = gbsa%gsasa
       gradient = gradient + gbsa%dsdr
       if (profile) call timer%measure(9)
    endif
    if (profile) call timer%measure(3,"EEQ model density")
    ! names DO NOT corresponds to content of variables, obviously...
    call gfn0_charge_model(chrgeq,mol%n,mol%at,xtbdata%coulomb)
    ! initialize electrostatic energy
    if (allocated(gbsa)) then
       call eeq_chrgeq(mol,env,chrgeq,gbsa,cn,dcndr,qeeq,dqdr, &
          &            ees,gsolv,gradient,.false.,.true.,.true.)
    else
       nid = maxval(mol%id)
       allocate(idnum(nid))
       do ii = 1, nid
          jat = 0
          do iat = 1, mol%n
             if (mol%id(iat) == ii) then
                jat = iat
                exit
             end if
          end do
          idnum(ii) = mol%at(jat)
       end do
       allocate(chargewidth(1, nid))
       do ii = 1, nid
          ati = idnum(ii)
          chargewidth(1, ii) = xtbdata%coulomb%chargeWidth(ati)
       end do
       call init(coulomb, env, mol, chargewidth)
       call init(eeq, env, xtbdata%coulomb%electronegativity, &
          & xtbdata%coulomb%kcn, xtbdata%coulomb%chemicalHardness, num=idnum)
       call eeq%chargeEquilibration(env, mol, coulomb, cn, dcndr, dcndl, &
          & ees, gradient, sigma, qat=qeeq, dqdr=dqdr, dqdl=dqdl)
    endif
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Electronegativity equilibration failed", source)
       return
    end if
    wfn%q = qeeq
    if (profile) call timer%measure(3)
    if (profile) call timer%measure(5,"Integral evaluation")
 ! ---------------------------------------
 !  Build AO overlap S and H0 integrals under pbc
 ! ---------------------------------------
    call getselfenergy(xtbdata%hamiltonian, xtbdata%nShell, mol%at, cn, wfn%q, &
       & selfenergy, dsedcn, dsedq)
    if (ccm) then
       call ccm_build_sh0(xtbdata%nShell, xtbdata%hamiltonian, selfenergy, &
          & mol%n, mol%at, basis, nbf, nao, mol%xyz, mol%lattice, intcut, &
          & s, h0, mol%wsc)
    else
       call latp%getLatticePoints(trans, sqrt(800.0_wp))
       call pbc_build_sh0(xtbdata%nShell, xtbdata%hamiltonian, selfenergy, &
          & mol%n, mol%at, basis, nbf, nao, mol%xyz, trans, intcut, s, h0)
    endif
    if (profile) call timer%measure(5)
    if (profile) call timer%measure(6,"Cholesky factorization")
 ! ---------------------------------------
 !  Check for near linear dependencies via Cholesky decomposition
 ! ---------------------------------------
    call cholesky(env%unit,pr,nao,s,orthog) ! S is not modified
    if(orthog)then
       !if (profile) call timer%measure(7,"Canonical orthogonalization")
       call renorm(nao,s) ! S is renormalized
       call canorthog(env%unit,nao,s,x,xdim,pr,fail)
       !if (profile) call timer%measure(7)
    endif
    if (profile) call timer%measure(6)
    if (profile) call timer%measure(7,"Zeroth order Hamiltonian")
 ! ---------------------------------------
 !  Setup H0 under pbc
 ! ---------------------------------------
 !  H0 already initialized
    do i = 1, nao
       do j = 1, i
          k = j+i*(i-1)/2
          h(j,i) = h0(k)
          h(i,j) = h(j,i)
       enddo
    enddo
    if(.not.orthog)then
       call solve(.true.,nao,wfn%ihomo,scfconv,h,s,x,wfn%P,wfn%emo,fail)
    else
       call orthgsolve2(.true.,nao,xdim,wfn%ihomo,scfconv,h,s,x,wfn%P,wfn%emo,fail)
    endif
    ! for geometry optimization
    res % converged = .not. fail
    ! save eigenvectors
    wfn%C = h
    if (fail) then
       call env%error("Diagonalization of Hamiltonian failed", source)
       return
    end if
 ! ---------------------------------------
 !  Fermi smearing
 ! ---------------------------------------
    if(et.gt.0.1_wp)then
       if (wfn%ihomoa+1.le.nao) then
          call fermismear(.false.,nao,wfn%ihomoa,et,wfn%emo,wfn%focca,nfoda,efa,ga)
       endif
       if (wfn%ihomob+1.le.nao) then
          call fermismear(.false.,nao,wfn%ihomob,et,wfn%emo,wfn%foccb,nfodb,efb,gb)
       endif
       wfn%focc = wfn%focca + wfn%foccb
    endif
    ! create density matrix = save in wfn%P
    call dmat(nao,wfn%focc,wfn%C,wfn%P)
    call mpopsh(mol%n,nao,nshell,basis%ao2sh,s,wfn%P,wfn%qsh)
 ! ---------------------------------------
 !  emo: Eigenvalues from H0
 ! ---------------------------------------
    eel = sum(wfn%focc*wfn%emo)*evtoau + ga + gb
    if (profile) call timer%measure(7)
    if (.not.pr.and.profile.and.minpr) &
       call timer%write_timing(env%unit,7,"Diagonalization")
    if (profile) call timer%measure(8,"Gradient calculation")
 ! ======================================================================
 !  GRADIENT (100% analytical)
 ! ======================================================================
    ! repulsion energy + gradient
    !gradient = 0.0_wp; sigma = 0.0_wp
    call latp%getLatticePoints(trans, 40.0_wp)
    call drep_grad(xtbdata%repulsion,mol,trans,ep,gradient,sigma)
    ! short ranged bond energy + gradient
    if (allocated(xtbdata%srb)) then
       call latp%getLatticePoints(trans, sqrt(200.0_wp))
       call dsrb_grad(mol,xtbdata%srb,cn,dcndr,dcndl,trans,esrb,gradient,sigma)
    end if
    !etot = ep + esrb; return
    ! h0 gradient
    allocate( dhdcn(mol%n), dhdq(mol%n), pew(nao,nao), tmp(nao), &
       &      source = 0.0_wp )
    tmp = wfn%focc*wfn%emo*evtoau
    ! setup energy weighted density matrix = pew
    call dmat(nao,tmp,wfn%C,pew)
    if (ccm) then
       call ccm_build_dsh0(xtbdata%nShell, xtbdata%hamiltonian, selfenergy, &
          & dsedcn, dsedq, mol%n, basis, intcut, nao, nbf, mol%at, mol%xyz, &
          & mol%lattice, wfn%P, pew, gradient, sigma, dhdcn, dhdq, mol%wsc)
    else
       call latp%getLatticePoints(trans, sqrt(800.0_wp))
       call pbc_build_dsh0(xtbdata%nShell, xtbdata%hamiltonian, selfenergy, &
          & dsedcn, dsedq, mol%n, basis, intcut, nao, nbf, mol%at, mol%xyz, &
          & trans, wfn%P, pew, gradient, sigma, dhdcn, dhdq)
    endif
    if (mol%npbc > 0) then
       ! setup CN sigma
       call dgemv('n',9,mol%n,1.0_wp,dcndl,9,dhdcn,1,1.0_wp,sigma,1)
       ! setup  q sigma
       call dgemv('n',9,mol%n,1.0_wp,dqdl, 9, dhdq,1,1.0_wp,sigma,1)
    endif
    ! setup CN gradient
    call dgemv('n',3*mol%n,mol%n, 1.0_wp,dcndr,3*mol%n,dhdcn,1,1.0_wp,gradient,1)
    ! setup  q gradient
    call dgemv('n',3*mol%n,mol%n, 1.0_wp,dqdr, 3*mol%n, dhdq,1,1.0_wp,gradient,1)
    if (profile) call timer%measure(8)
 !  calculate the norm for printout
    res%gnorm = sqrt(sum( gradient**2 ))
 ! ---------------------------------------
 !  Properties + printout
 ! ---------------------------------------
    printing: if (pr) then
       ! print orbital energies and occupation numbers
       !call preig(6,wfn%focc,1.0_wp,wfn%emo, &
       !     max(wfn%ihomoa-12,1),min(wfn%ihomoa+11,nao))
       if(.not.orthog)then
         call print_orbital_eigenvalues(env%unit,wfn,5)
         if ((wfn%ihomo+1.le.nao).and.(wfn%ihomo.ge.1)) &
            egap = wfn%emo(wfn%ihomo+1)-wfn%emo(wfn%ihomo)
       else
         wfn%nao = xdim
         call print_orbital_eigenvalues(env%unit,wfn,5)
         if ((wfn%ihomo+1.le.xdim).and.(wfn%ihomo.ge.1)) &
            egap = wfn%emo(wfn%ihomo+1)-wfn%emo(wfn%ihomo)
         wfn%nao = nao
       endif
    endif printing
 ! ------------------------------------------------------------------------
 !  get Wiberg bond orders
    call get_wiberg(mol%n,basis%nao,mol%at,mol%xyz,wfn%P,s,wfn%wbo,basis%fila2)
 ! ---------------------------------------
 !  Save all the energy contributions
 ! ---------------------------------------
    etot = eel + ees + ep + exb + esrb
    eat = eatoms*evtoau - etot
    etot = etot + ed
    res%e_elec  = eel
    res%e_atom  = eat
    res%e_rep   = ep
    res%e_es    = ees
    res%e_aes   = 0.0_wp
    res%e_axc   = 0.0_wp
    res%e_xb    = esrb
    res%e_disp  = ed
    res%g_hb    = ehb
    res%e_total = etot
    res%hl_gap  = egap
    if (allocated(gbsa)) then
       res%g_solv  = gsolv
       !res%g_born  = gborn    ! not returned
       res%g_sasa  = gbsa%gsasa
       !res%g_hb    = gbsa%ghb ! not returned
       res%g_shift = gbsa%gshift
    endif
    ! do NOT calculate the dipole moment from the density, because it's really bad
    res%dipole  = matmul(mol%xyz,wfn%q)
    res%g_solv  = 0.0_wp
    if (profile.and.pr) call timer%write(env%unit,'EHT')
 end associate
    if (profile) call timer%deallocate
References xtb_readin::bool2string(), xtb_lineardep::canorthog(), ccm_build_dsh0(), ccm_build_sh0(), xtb_lineardep::cholesky(), xtb_disp_coordinationnumber::cntype, xtb_disp_coordinationnumber::cutcoordinationnumber(), xtb_scc_core::dmat(), drep_grad(), dsrb_grad(), xtb_mctc_convert::evtoau, xtb_scc_core::fermismear(), xtb_scc_core::get_wiberg(), xtb_chargemodel::gfn0_charge_model(), xtb_scc_core::mpopsh(), xtb_scc_core::occu(), xtb_lineardep::orthgsolve2(), xtb_lineardep::orthog, pbc_build_dsh0(), pbc_build_sh0(), print_orbital_eigenvalues(), profile, xtb_lineardep::renorm(), xtb_scc_core::setzshell(), xtb_type_timer::timer(), and true().
Referenced by xtb_xtb_calculator::singlepoint(), test_gfn0_sp(), and test_peeq_sp().
Variable Documentation
gpr
logical, parameter, private xtb_peeq::gpr =.false. private
print the different gradient contributions (for debugging)
Definition at line 39 of file peeq_module.f90.
    logical,parameter,private :: gpr =.false.
profile
logical, parameter, private xtb_peeq::profile = .true. private
profiling
Definition at line 42 of file peeq_module.f90.
    logical,parameter,private :: profile = .true.
Referenced by peeq().