My Project: xtb_lsrmsd Module Reference
xtb_lsrmsd Module Reference
Functions/Subroutines
subroutine rmsd (n, coord1, coord2, option, U, x_center, y_center, error, calc_g, g)
subroutine rotation_matrix (q, U)
subroutine dstmev (A, lambda, evec)
subroutine givens4 (S, T, V)
subroutine svdcmp (mmax, a, m, n, w, v, rv1)
real(dp) function pythag (a, b)
Variables
integer, parameter dp = kind(1.d0)
Function/Subroutine Documentation
dstmev()
subroutine xtb_lsrmsd::dstmev (real(dp), dimension(4,4) A, real(dp) lambda, real(dp), dimension(4) evec)
Definition at line 179 of file ls_rmsd.f90.
 !-----------------------------------------------------------------------
 ! a simple subroutine to compute the leading eigenvalue and eigenvector
 ! of a symmetric, traceless 4x4 matrix A by an inverse power iteration:
 ! (1) the matrix is converted to tridiagonal form by 3 Givens
 ! rotations;  V*A*V' = T
 ! (2) Gershgorin's theorem is used to estimate a lower
 ! bound for the leading negative eigenvalue:
 ! lambda_1 > g=min(T11-t12,-t21+T22-t23,-t32+T33-t34,-t43+T44)
 !          =
 ! where tij=abs(Tij)
 ! (3) Form the positive definite matrix
 !     B = T-gI
 ! (4) Use svd (algorithm svdcmp from "Numerical Recipes")
 !     to compute eigenvalues and eigenvectors for SPD matrix B
 ! (5) Shift spectrum back and keep leading singular vector
 !     and largest eigenvalue.
 ! (6) Convert eigenvector to original matrix A, through
 !     multiplication by V'.
 !-----------------------------------------------------------------------
   real(dp), dimension(4,4) :: A, T, V, SV
   integer :: i
   integer, dimension(1) :: max_loc ! must be an array
   real(dp), dimension(4) :: evec, SW
   real(dp), dimension(8) :: rv1
   real(dp) :: lambda
   !-----------------------------------------------------------------------
   !(I).   Convert to tridiagonal form, keeping similarity transform
   ! (a product of 3 Givens rotations)
   call givens4(a,t,v)
   !-----------------------------------------------------------------------
   !(II)Estimate lower bound of smallest eigenvalue by Gershgorin's theorem
   lambda=min(t(1,1)-abs(t(1,2)),-abs(t(2,1))+t(2,2)-abs(t(2,3)),&
        -abs(t(3,2))+t(3,3)-abs(t(3,4)),-abs(t(4,3))+t(4,4))
   !-----------------------------------------------------------------------
   !(III). Form positive definite matrix     T <== lambda*I - T
   do i = 1,4
      t(i,i) = t(i,i)-lambda
   enddo
   !-----------------------------------------------------------------------
   !(IV). Compute singular values/vectors of SPD matrix B
   call svdcmp(4,t,4,4,sw,sv,rv1)
   !-----------------------------------------------------------------------
   !(V). Shift spectrum back
   max_loc = maxloc(sw)
   lambda = sw(max_loc(1)) + lambda
   !lambda = SW(1) + lambda
   !-----------------------------------------------------------------------
   !(VI). Convert eigenvector to original coordinates: (V is transposed!)
   evec = matmul(v,sv(:,max_loc(1)))
   !write(*,*)'-----------------------------------------------------------'
   !write(*,*) 'lambda = ', lambda,'  eigenvector:  '
   !write(*,99) evec
   !write(*,*)'-----------------------------------------------------------'
   !-----------------------------------------------------------------------
   !99 format(1x,4(d19.13,1x))
References givens4(), and svdcmp().
Referenced by rmsd().
givens4()
subroutine xtb_lsrmsd::givens4 (real(dp), dimension(4,4), intent(in) S, real(dp), dimension(4,4), intent(out) T, real(dp), dimension(4,4), intent(out) V)
Definition at line 240 of file ls_rmsd.f90.
 !-----------------------------------------------------------------------
   real(dp), dimension(4,4), intent(in)  :: S
   real(dp), dimension(4,4), intent(out) :: T,V
   real(dp)  :: c1,c2,c3, s1,s2,s3, r1,r2,r3, c1c2, s1c2
   !double precision :: pythag
   ! external        pythag
   !performs givens rotations to reduce symmetric 4x4 matrix to tridiagonal
   t=s; v = 0.d0
   !-----------------------------------------------------------------------
   !Zero out entries T(4,1) and T(1,4)
   ! compute cos and sin of rotation angle in the 3-4 plane
   r1 = pythag(t(3,1),t(4,1))
   if(r1 .ne. 0.d0) then
      c1 = t(3,1)/r1; s1 = t(4,1)/r1
      v(3,3) = c1  ; v(3,4) = s1
      v(4,3) =-s1  ; v(4,4) = c1
      t(3,1) = r1  ; t(4,1) = 0.d0
      t(3:4,2:4) = matmul(v(3:4,3:4),t(3:4,2:4))
      t(1:2,3:4) = transpose(t(3:4,1:2))
      t(3:4,3:4) = matmul(t(3:4,3:4),transpose(v(3:4,3:4)))
   else
      c1 = 1.d0; s1 = 0.d0
   endif
   !-----------------------------------------------------------------------
   !Zero out entries T(3,1) and T(1,3)
   ! compute cos and sin of rotation angle in the 2-3 plane
   r2 = pythag(t(3,1), t(2,1))
   if(r2 .ne. 0.d0) then
      c2 = t(2,1)/r2; s2 = t(3,1)/r2
      v(2,2) = c2  ; v(2,3) = s2
      v(3,2) =-s2  ; v(3,3) = c2
      t(2,1) = r2  ; t(3,1) = 0.d0
      t(2:3,2:4) = matmul(v(2:3,2:3),t(2:3,2:4))
      t(1,2:3)   = t(2:3,1);  t(4,2:3) = t(2:3,4)
      t(2:3,2:3) = matmul(t(2:3,2:3),transpose(v(2:3,2:3)))
   else
      c2 = 1.d0; s2 = 0.d0
   endif
   !-----------------------------------------------------------------------
   !Zero out entries T(4,2) and T(2,4)
   ! compute cos and sin of rotation angle in the 3-4 plane
   r3 = pythag(t(4,2), t(3,2))
   if(r3 .ne. 0.d0) then
      c3 = t(3,2)/r3; s3 = t(4,2)/r3
      v(3,3) = c3  ; v(3,4) = s3
      v(4,3) =-s3  ; v(4,4) = c3
      t(3,2) = r3  ; t(4,2) = 0.d0
      t(3:4,3:4) = matmul(v(3:4,3:4),t(3:4,3:4))
      t(1:2,3:4) = transpose(t(3:4,1:2))
      t(3:4,3:4) = matmul(t(3:4,3:4),transpose(v(3:4,3:4)))
   else
      c3 = 1.d0; s3 = 0.d0
   endif
   !-----------------------------------------------------------------------
   !Compute net rotation matrix (accumulate similarity for evec. computation)
   ! To save transposing later, This is the transpose!
   v(1,1)=1.d0; v(1,2:4) = 0.d0; v(2:4,1) = 0.d0
   v(2,2) = c2;  v(3,2) = c1*s2 ; v(4,2) = s1*s2; c1c2 = c1*c2; s1c2=s1*c2
   v(2,3) = -s2*c3 ; v(3,3) = c1c2*c3-s1*s3 ; v(4,3) =  s1c2*c3+c1*s3
   v(2,4) =  s2*s3 ; v(3,4) =-c1c2*s3-s1*c3 ; v(4,4) = -s1c2*s3+c1*c3
   !-----------------------------------------------------------------------
   !write(*,*) (V(1:4,i) - W(1:4,i),i=1,4)
References pythag().
Referenced by dstmev().
pythag()
real(dp) function xtb_lsrmsd::pythag (real(dp) a, real(dp) b)
Definition at line 538 of file ls_rmsd.f90.
 !-----------------------------------------------------------------------
   real(dp) :: pythag, a, b
   real(dp) :: absa,absb
   absa=abs(a)
   absb=abs(b)
   if(absa.gt.absb)then
      pythag=absa*dsqrt(1.0d0+(absb/absa)**2)
   else
      if(absb.eq.0.0d0)then
         pythag=0.0d0
      else
         pythag=absb*dsqrt(1.0d0+(absa/absb)**2)
      endif
   endif
Referenced by givens4(), and svdcmp().
rmsd()
subroutine xtb_lsrmsd::rmsd (integer, intent(in) n, real(dp), dimension(:,:), intent(in) coord1, real(dp), dimension(:,:), intent(in) coord2, integer, intent(in) option, real(dp), dimension(:,:), intent(out) U, real(dp), dimension(3), intent(out) x_center, real(dp), dimension(3), intent(out) y_center, real(dp), intent(out) error, logical, intent(in) calc_g, real(dp), dimension(:,:), intent(out) g)
Definition at line 33 of file ls_rmsd.f90.
 !-----------------------------------------------------------------------
 !  This subroutine calculates the least square rmsd of two coordinate
 !  sets coord1(3,n) and coord2(3,n) using a method based on quaternion.
 !  If option=1, then the rotation matrix U and the centers of coord are
 !  returned.
 !-----------------------------------------------------------------------
 ! if calc_g == .true., derivative of RMSD with respect to coord1
 ! is returned (and option must be 1, SG 12/18)
 !-----------------------------------------------------------------------
   integer, intent(in) :: n, option
   real(dp), dimension(:,:), intent(in) :: coord1, coord2
   real(dp), dimension(:,:), intent(out) :: U
   real(dp), dimension(3), intent(out) :: x_center, y_center
   real(dp), intent(out) :: error
   logical, intent(in) :: calc_g
   real(dp), intent(out) :: g(:,:)
   integer :: i, j
   real(dp), dimension(3,n) :: x, y
   real(dp), dimension(n) :: xi, yi
   real(dp) :: x_norm, y_norm, lambda, y1, y2, y3
   real(dp), dimension(3,3) :: Rmatrix
   real(dp), dimension(4,4) :: S, dS
   real(dp), dimension(4) :: q
   real(dp) :: tmp(3)
   ! make copies of the original coordinates
   x(:,1:n) = coord1(:,1:n)
   y(:,1:n) = coord2(:,1:n)
   ! calculate the barycenters, centroidal coordinates, and the norms
   x_norm = 0.0d0
   y_norm = 0.0d0
   do i = 1, 3
      xi(:) = x(i,:)
      yi(:) = y(i,:)
      x_center(i) = sum(xi(1:n))/dble(n)
      y_center(i) = sum(yi(1:n))/dble(n)
      xi(:) = xi(:) - x_center(i)
      yi(:) = yi(:) - y_center(i)
      x(i,:) = xi(:)
      y(i,:) = yi(:)
      x_norm = x_norm + dot_product(xi, xi)
      y_norm = y_norm + dot_product(yi, yi)
   end do
   ! calculate the R matrix
   do i = 1, 3
      do j = 1, 3
         rmatrix(i,j) = dot_product(x(i,:),y(j,:))
      end do
   end do
   ! S matrix
   s(1, 1) = rmatrix(1, 1) + rmatrix(2, 2) + rmatrix(3, 3)
   s(2, 1) = rmatrix(2, 3) - rmatrix(3, 2)
   s(3, 1) = rmatrix(3, 1) - rmatrix(1, 3)
   s(4, 1) = rmatrix(1, 2) - rmatrix(2, 1)
   s(1, 2) = s(2, 1)
   s(2, 2) = rmatrix(1, 1) - rmatrix(2, 2) - rmatrix(3, 3)
   s(3, 2) = rmatrix(1, 2) + rmatrix(2, 1)
   s(4, 2) = rmatrix(1, 3) + rmatrix(3, 1)
   s(1, 3) = s(3, 1)
   s(2, 3) = s(3, 2)
   s(3, 3) =-rmatrix(1, 1) + rmatrix(2, 2) - rmatrix(3, 3)
   s(4, 3) = rmatrix(2, 3) + rmatrix(3, 2)
   s(1, 4) = s(4, 1)
   s(2, 4) = s(4, 2)
   s(3, 4) = s(4, 3)
   s(4, 4) =-rmatrix(1, 1) - rmatrix(2, 2) + rmatrix(3, 3)
   ! Calculate eigenvalues and eigenvectors, and
   ! take the maximum eigenvalue lambda and the corresponding eigenvector q.
   call dstmev(s, lambda, q)
   if (option == 1) then
      ! convert quaternion q to rotation matrix U
      call rotation_matrix(q, u)
   end if
   ! RMS Deviation, small number added to avoid NAN in gradient, SG 12/18
   error = sqrt(max(0.0d0,((x_norm+y_norm)-2.0d0*lambda))/dble(n))+1.d-9
   if (calc_g) then
      do i = 1, n
         do j = 1, 3
            tmp(:) = matmul(transpose(u(:,:)), y(:,i))
            g(j,i) = (x(j,i) - tmp(j))/(error*dble(n))
         end do
      end do
   end if
References dstmev(), and rotation_matrix().
Referenced by xtb_optimizer::ancopt(), xtb_biaspath::bias_path(), xtb_relaxation_engine::fire(), xtb_kopt::get_rmsd(), heavyrmsd(), heavyrmsdfile(), xtb_relaxation_engine::l_ancopt(), xtb_metadynamic::metadynamic(), and prob_module::prob_metadynamic().
rotation_matrix()
subroutine xtb_lsrmsd::rotation_matrix (real(dp), dimension(:), intent(in) q, real(dp), dimension(:,:), intent(out) U)
Definition at line 132 of file ls_rmsd.f90.
 !-----------------------------------------------------------------------
 ! This subroutine constructs rotation matrix U from quaternion q.
 !-----------------------------------------------------------------------
   real(dp), dimension(:), intent(in) :: q
   real(dp), dimension(:,:), intent(out) :: U
   real(dp)::q0,q1,q2,q3,b0,b1,b2,b3,q00,q01,q02,q03,q11,q12,q13,q22,q23,q33
   q0 = q(1)
   q1 = q(2)
   q2 = q(3)
   q3 = q(4)
   b0 = 2.0d0*q0
   b1 = 2.0d0*q1
   b2 = 2.0d0*q2
   b3 = 2.0d0*q3
   q00 = b0*q0-1.0d0
   q01 = b0*q1
   q02 = b0*q2
   q03 = b0*q3
   q11 = b1*q1
   q12 = b1*q2
   q13 = b1*q3
   q22 = b2*q2
   q23 = b2*q3
   q33 = b3*q3
   u(1,1) = q00+q11
   u(1,2) = q12-q03
   u(1,3) = q13+q02
   u(2,1) = q12+q03
   u(2,2) = q00+q22
   u(2,3) = q23-q01
   u(3,1) = q13-q02
   u(3,2) = q23+q01
   u(3,3) = q00+q33
Referenced by rmsd().
svdcmp()
subroutine xtb_lsrmsd::svdcmp (integer mmax, real(dp), dimension(mmax,*) a, integer m, integer n, real(dp), dimension(*) w, real(dp), dimension(mmax,*) v, real(dp), dimension(*) rv1)
Definition at line 305 of file ls_rmsd.f90.
 !-----------------------------------------------------------------------
   integer :: mmax
   INTEGER :: m,n
   real(dp) :: a(mmax,*),v(mmax,*),w(*),rv1(*)
   INTEGER :: i,its,j,jj,k,l,nm
   real(dp) :: anorm,c,f,g,h,s,scale,x,y,z!,pythag
   g = 0.0d0
   scale = 0.0d0
   anorm = 0.0d0
   do i = 1, n
      l=i+1
      rv1(i)=scale*g
      g=0.0d0
      s=0.0d0
      scale=0.0d0
      if(i.le.m)then
         do k=i,m
            scale=scale+abs(a(k,i))
         end do
         if(scale.ne.0.0d0)then
            do k=i,m
               a(k,i)=a(k,i)/scale
               s=s+a(k,i)*a(k,i)
            end do
            f=a(i,i)
            g=-sign(sqrt(s),f)
            h=f*g-s
            a(i,i)=f-g
            do j=l,n
               s=0.0d0
               do k=i,m
                  s=s+a(k,i)*a(k,j)
               end do
               f=s/h
               do k=i,m
                  a(k,j)=a(k,j)+f*a(k,i)
               end do
            end do
            do k=i,m
               a(k,i)=scale*a(k,i)
            end do
         endif
      endif
      w(i)=scale *g
      g=0.0d0
      s=0.0d0
      scale=0.0d0
      if((i.le.m).and.(i.ne.n))then
         do k=l,n
            scale=scale+abs(a(i,k))
         end do
         if(scale.ne.0.0d0)then
            do k=l,n
               a(i,k)=a(i,k)/scale
               s=s+a(i,k)*a(i,k)
            end do
            f=a(i,l)
            g=-sign(sqrt(s),f)
            h=f*g-s
            a(i,l)=f-g
            do k=l,n
               rv1(k)=a(i,k)/h
            end do
            do j=l,m
               s=0.0d0
               do k=l,n
                  s=s+a(j,k)*a(i,k)
               end do
               do k=l,n
                  a(j,k)=a(j,k)+s*rv1(k)
               end do
            end do
            do k=l,n
               a(i,k)=scale*a(i,k)
            end do
         endif
      endif
      anorm=max(anorm,(abs(w(i))+abs(rv1(i))))
   end do
   do i = n, 1, -1
      if(i .lt. n) then
         if(g.ne.0.0d0)then
            do j=l,n
               v(j,i)=(a(i,j)/a(i,l))/g
            end do
            do j=l,n
               s=0.0d0
               do k=l,n
                  s=s+a(i,k)*v(k,j)
               end do
               do k=l,n
                  v(k,j)=v(k,j)+s*v(k,i)
               end do
            end do
         endif
         do j=l,n
            v(i,j)=0.0d0
            v(j,i)=0.0d0
         end do
      endif
      v(i,i)=1.0d0
      g=rv1(i)
      l=i
   end do
 !-----------------------------------------------------------------------
   do i = min(m,n), 1, -1
      l=i+1
      g=w(i)
      do j=l,n
         a(i,j)=0.0d0
      end do
      if(g.ne.0.0d0)then
         g=1.0d0/g
         do j=l,n
            s=0.0d0
            do k=l,m
               s=s+a(k,i)*a(k,j)
            end do
            f=(s/a(i,i))*g
            do k=i,m
               a(k,j)=a(k,j)+f*a(k,i)
            end do
         end do
         do j=i,m
            a(j,i)=a(j,i)*g
         end do
      else
         do j= i,m
            a(j,i)=0.0d0
         end do
      endif
      a(i,i)=a(i,i)+1.0d0
   end do
 !-----------------------------------------------------------------------
   do k=n,1,-1
      do its=1,30
         do l=k,1,-1
            nm=l-1
            if((abs(rv1(l))+anorm).eq.anorm)  goto 2
            if((abs(w(nm))+anorm).eq.anorm)  goto 1
         end do
 1       c=0.0d0
         s=1.0d0
         do i=l,k
            f=s*rv1(i)
            rv1(i)=c*rv1(i)
            if((abs(f)+anorm).eq.anorm) goto 2
            g=w(i)
            h=pythag(f,g)
            w(i)=h
            h=1.0d0/h
            c= (g*h)
            s=-(f*h)
            do j=1,m
               y=a(j,nm)
               z=a(j,i)
               a(j,nm)=(y*c)+(z*s)
               a(j,i)=-(y*s)+(z*c)
            end do
         end do
 2       z=w(k)
         if(l .eq. k)then
            if(z.lt.0.0d0)then
               w(k)=-z
               do j=1,n
                  v(j,k)=-v(j,k)
               end do
            endif
            goto 3
         endif
         if(its.eq.30) then
            write(*,*) 'no convergence in svdcmp'
            stop
         endif
         x=w(l)
         nm=k-1
         y=w(nm)
         g=rv1(nm)
         h=rv1(k)
         f=((y-z)*(y+z)+(g-h)*(g+h))/(2.0d0*h*y)
         g=pythag(f,1.0d0)
         f=((x-z)*(x+z)+h*((y/(f+sign(g,f)))-h))/x
         c=1.0d0
         s=1.0d0
         do j=l,nm
            i=j+1
            g=rv1(i)
            y=w(i)
            h=s*g
            g=c*g
            z=pythag(f,h)
            rv1(j)=z
            c=f/z
            s=h/z
            f= (x*c)+(g*s)
            g=-(x*s)+(g*c)
            h=y*s
            y=y*c
            do jj=1,n
               x=v(jj,j)
               z=v(jj,i)
               v(jj,j)= (x*c)+(z*s)
               v(jj,i)=-(x*s)+(z*c)
            end do
            z=pythag(f,h)
            w(j)=z
            if(z.ne.0.0d0)then
               z=1.0d0/z
               c=f*z
               s=h*z
            endif
            f= (c*g)+(s*y)
            x=-(s*g)+(c*y)
            do jj=1,m
               y=a(jj,j)
               z=a(jj,i)
               a(jj,j)= (y*c)+(z*s)
               a(jj,i)=-(y*s)+(z*c)
            end do
         end do
         rv1(l)=0.0d0
         rv1(k)=f
         w(k)=x
      end do
 3    continue
   end do
 !-----------------------------------------------------------------------
References pythag().
Referenced by dstmev().
Variable Documentation
dp
integer, parameter xtb_lsrmsd::dp = kind(1.d0)
Definition at line 28 of file ls_rmsd.f90.
   integer, parameter :: dp = kind(1.d0)