My Project: xtb_solv_model Module Reference
xtb_solv_model Module Reference
Generic solvation model used to create actual solvation calculators.
Data Types
type tsolvmodel
Payload to create actual solvation models.
interface init
Initialize solvation model from input.
type gbsa_parameter
Define the local data structure for the parameters.
Functions/Subroutines
subroutine initsolvmodel (self, env, input, level)
Initialize solvation model from input.
subroutine normalizesolventname (solvent, input)
Try to find a normalized version of an input solvent name.
subroutine loadinternalparam (self, env, solvent, level)
Load internal parameters, if no parameter file is present.
subroutine readparamfile (self, env)
subroutine paramtomodel (self, param)
subroutine getparamfile (env, solvent, model, level, pfile)
Try to find a suitable parameter file for parsing.
subroutine, public info (self, unit)
Print information on the solvation model.
subroutine, public newsolvationmodel (self, env, model, num)
subroutine, public newbornmodel (self, env, model, num)
Variables
real(wp), parameter molcm3toau = 8.92388e-2_wp
Solvent density (g/cm^3) and molar mass (g/mol)
real(wp), parameter surfacetension = 1.0e-5_wp
Surface tension (mN/m=dyn/cm)
real(wp), parameter mnmtokcal = 4.0305201015221386e-4_wp
real(wp), parameter kcaltomnm = 1.0_wp/mNmtokcal
real(wp), parameter automnm = autokcal * kcaltomNm
real(wp), parameter lrcut = 35.0_wp * aatoau
real(wp), parameter srcut = 2.0_wp * aatoau
Detailed Description
Generic solvation model used to create actual solvation calculators.
Function/Subroutine Documentation
getparamfile()
subroutine xtb_solv_model::getparamfile (type(tenvironment), intent(inout) env, character(len=*), intent(in) solvent, character(len=*), intent(in) model, integer, intent(in) level, character(len=:), intent(out), allocatable pfile) private
Try to find a suitable parameter file for parsing.
Parameters
[in,out] env Computation environment
[in] solvent Name of the solvent (normalized)
[in] model Name of the solvation model
[in] level Method level for solvation model
[out] pfile Parameter file, unallocated if nothing was found
Definition at line 473 of file model.f90.
    character(len=*), parameter :: source = 'solv_model_getParamFile'
    type(TEnvironment), intent(inout) :: env
    character(len=*), intent(in) :: solvent
    character(len=*), intent(in) :: model
    integer, intent(in) :: level
    character(len=:), allocatable, intent(out) :: pfile
    character(len=:), allocatable :: fname
    ! try "param_<model>[level]_<solvent>.txt" first
    select case(level)
    case(2)
       fname = 'param_' // model // '2_' // solvent // '.txt'
    case(1)
       fname = 'param_' // model // '1_' // solvent // '.txt'
    case(0)
       fname = 'param_' // model // '0_' // solvent // '.txt'
    end select
    if (allocated(fname)) then
       call rdpath(env%xtbpath, fname, pfile)
    end if
    if (.not.allocated(pfile)) then
       ! try "param_<model>_<solvent>.txt" next
       fname = 'param_' // model // '_' // solvent // '.txt'
       call rdpath(env%xtbpath, fname, pfile)
    end if
    ! finally try ".param_<model>_<solvent>" which is the old default
    if (.not.allocated(pfile)) then
       select case(level)
       case default
          fname = '.param_' // model // '_' // solvent
       case(2)
          fname = '.param_' // model // '2_' // solvent
       case(0)
          fname = '.param_' // model // '0_' // solvent
       end select
       call rdpath(env%xtbpath, fname, pfile)
    end if
References xtb_mctc_systools::rdpath().
Referenced by xtb_solv_model::init::initsolvmodel().
info()
subroutine, public xtb_solv_model::info (class(tsolvmodel), intent(in) self, integer, intent(in) unit)
Print information on the solvation model.
Parameters
[in] self Data structure
[in] unit Unit for IO
Definition at line 532 of file model.f90.
    class(TSolvModel), intent(in) :: self
    integer, intent(in) :: unit
    write(unit, '(6x, "*", 1x, a, ":", t40)', advance='no') "Solvation model"
    if (self%alpb) then
       write(unit, '(a)') "ALPB"
    else
       write(unit, '(a)') "GBSA"
    end if
    write(unit, '(8x, a, t40, a)') "Solvent", self%solvent
    write(unit, '(8x, a, t40, a)') "Parameter file", self%paramFile
    write(unit, '(8x, a, t40, es14.4)') &
       & "Dielectric constant", self%dielectricConst
    write(unit, '(8x, a, t40)', advance='no') "Reference state"
    select case(self%state)
    case default
       write(unit, '(a)') 'gsolv [1 M gas/solution]'
    case(solutionstate%reference)
       write(unit, '(a)') 'gsolv=reference [X=1]'
    case(solutionstate%mol1bar)
       write(unit, '(a)') 'gsolv [1 bar gas/1 M solution]'
    end select
    write(unit, '(8x, a, t40, es14.4, 1x, a, t60, es14.4, 1x, a)') &
       & "Free energy shift", self%freeEnergyShift, "Eh", &
       & self%freeEnergyShift * autokcal, "kcal/mol"
    write(unit, '(8x, a, t40, es14.4, 1x, a)') &
       & "Temperature", self%temperature, "K"
    write(unit, '(8x, a, t40, es14.4, 1x, a)') &
       & "Density", self%density / (molcm3toau/self%molarMass), "kg/L"
    write(unit, '(8x, a, t40, es14.4, 1x, a)') &
       & "Solvent mass", self%molarMass, "g/mol"
    write(unit, '(8x, a, t40)', advance='no') "Interaction kernel"
    select case(self%kernel)
    case default
       write(unit, '(i0, 1x, a)') self%kernel, '(internal error)'
    case(gbkernel%still)
       write(unit, '(a)') 'Still'
    case(gbkernel%p16)
       write(unit, '(a)') 'P16'
    end select
    write(unit, '(8x, a, t40, es14.4)') &
       "Born radius scaling (c1)", self%bornScale
    write(unit, '(8x, a, t40, a)') "Born radii integrator", "GBOBC"
    write(unit, '(8x, a, t40, es14.4, 1x, a, t60, es14.4, 1x, a)') &
       "Born offset", self%bornOffset, "a0", self%bornOffset/autoaa, "AA"
    write(unit, '(8x, a, t40)', advance='no') "H-bond correction"
    if (any(self%hBondStrength < 0.0_wp)) then
       write(unit, '(a)') "true"
    else
       write(unit, '(a)') "false"
    end if
    write(unit, '(8x, a, t40)', advance='no') "Ion screening"
    if (self%ionStrength > 0.0_wp) then
       write(unit, '(a)') "true"
    else
       write(unit, '(a)') "false"
    end if
    if (allocated(self%surfaceTension)) then
       write(unit, '(8x, a, t40, es14.4, 1x, a, t60, es14.4, 1x, a)') &
          "Surface tension", surfacetension, "Eh", surfacetension*automnm, "dyn/cm"
    end if
    write(unit, '(8x, a, t40, i14, 1x, a)') &
       "Grid points", self%nAng, "per atom"
References xtb_mctc_convert::autoaa, xtb_mctc_convert::autokcal, automnm, xtb_solv_kernel::gbkernel, molcm3toau, xtb_solv_state::solutionstate, and surfacetension.
Referenced by xtb_gfnff_calculator::writeinfo(), and xtb_xtb_calculator::writeinfo().
initsolvmodel()
subroutine xtb_solv_model::initsolvmodel (type(tsolvmodel), intent(out) self, type(tenvironment), intent(inout) env, type(tsolvinput), intent(in) input, integer, intent(in) level) private
Initialize solvation model from input.
Parameters
[in,out] env Computation environment
[out] self Data structure
[in] input Input data
[in] level Method level for solvation model
Definition at line 162 of file model.f90.
    character(len=*), parameter :: source = 'solv_model_initSolvModel'
    type(TEnvironment), intent(inout) :: env
    type(TSolvModel), intent(out) :: self
    type(TSolvInput), intent(in) :: input
    integer, intent(in) :: level
    character(len=:), allocatable :: solvent
    logical :: exist
    self%TSolvInput = input
    call normalizesolventname(solvent, input%solvent)
    if (input%alpb) then
       call getparamfile(env, solvent, 'alpb', level, self%paramFile)
    end if
    if (.not.allocated(self%paramFile)) then
       call getparamfile(env, solvent, 'gbsa', level, self%paramFile)
    end if
    if (allocated(self%paramFile)) then
       call readparamfile(self, env)
    else
       call loadinternalparam(self, env, solvent, level)
    end if
    self%freeEnergyShift = self%freeEnergyShift + getstateshift(self%state, &
       & self%temperature, self%density, self%molarMass)
loadinternalparam()
subroutine xtb_solv_model::loadinternalparam (type(tsolvmodel), intent(inout) self, type(tenvironment), intent(inout) env, character(len=*), intent(in) solvent, integer, intent(in) level) private
Load internal parameters, if no parameter file is present.
Parameters
[in,out] env Computation environment
[in,out] self Data structure
[in] solvent Name of the solvent (normalized)
[in] level Method level for solvation model
Definition at line 219 of file model.f90.
    character(len=*), parameter :: source = 'solv_model_loadInternalParam'
    type(TEnvironment), intent(inout) :: env
    type(TSolvModel), intent(inout) :: self
    character(len=*), intent(in) :: solvent
    integer, intent(in) :: level
    type(gbsa_parameter), allocatable :: param
    select case(self%kernel)
    case (gbkernel%still)
       if (any(level == [2, 0])) then
          self%paramFile = 'internal GFN2-xTB/GBSA'
          select case(solvent)
          case('acetone');      param = gfn2_acetone
          case('acetonitrile'); param = gfn2_acetonitrile
          case('benzene');      param = gfn2_benzene
          case('ch2cl2','dichlormethane'); param = gfn2_ch2cl2
          case('chcl3','chloroform');      param = gfn2_chcl3
          case('cs2');          param = gfn2_cs2
          case('dmso');         param = gfn2_dmso
          case('ether');        param = gfn2_ether
          case('h2o','water');  param = gfn2_h2o
          case('methanol');     param = gfn2_methanol
          case('thf');          param = gfn2_thf
          case('toluene');      param = gfn2_toluene
          case('dmf');          param = gfn2_dmf
          case('nhexan','n-hexan','nhexane','n-hexane');
             param = gfn2_nhexan
          end select
       else
          self%paramFile = 'internal GFN1-xTB/GBSA'
          select case(solvent)
          case('acetone');      param = gfn1_acetone
          case('acetonitrile'); param = gfn1_acetonitrile
          case('benzene');      param = gfn1_benzene
          case('ch2cl2','dichlormethane'); param = gfn1_ch2cl2
          case('chcl3','chloroform');      param = gfn1_chcl3
          case('cs2');          param = gfn1_cs2
          case('dmso');         param = gfn1_dmso
          case('ether');        param = gfn1_ether
          case('h2o','water');  param = gfn1_h2o
          case('methanol');     param = gfn1_methanol
          case('thf');          param = gfn1_thf
          case('toluene');      param = gfn1_toluene
          end select
       end if
       if (.not.allocated(param)) then
          call env%error("solvent: '"//solvent//"' is not parametrized", source)
          return
       end if
    case (gbkernel%p16)
       if (level == 2) then
          self%paramFile = 'internal GFN2-xTB/ALPB'
          select case(solvent)
          case('acetone');      param = gfn2_alpb_acetone
          case('acetonitrile'); param = gfn2_alpb_acetonitrile
          case('aniline');      param = gfn2_alpb_aniline
          case('benzaldehyde');      param = gfn2_alpb_benzaldehyde
          case('benzene');      param = gfn2_alpb_benzene
          case('dioxane');      param = gfn2_alpb_dioxane
          case('ethylacetate');      param = gfn2_alpb_ethylacetate
          case('furane');      param = gfn2_alpb_furane
          case('hexadecane');      param = gfn2_alpb_hexadecane
          case('nitromethane');      param = gfn2_alpb_nitromethane
          case('octanol');      param = gfn2_alpb_octanol
          case('woctanol');      param = gfn2_alpb_woctanol
          case('phenol');      param = gfn2_alpb_phenol
          case('ch2cl2','dichlormethane'); param = gfn2_alpb_ch2cl2
          case('chcl3','chloroform');      param = gfn2_alpb_chcl3
          case('cs2');          param = gfn2_alpb_cs2
          case('dmso');         param = gfn2_alpb_dmso
          case('ether');        param = gfn2_alpb_ether
          case('h2o','water');  param = gfn2_alpb_water
          case('methanol');     param = gfn2_alpb_methanol
          case('thf');          param = gfn2_alpb_thf
          case('toluene');      param = gfn2_alpb_toluene
          case('dmf');          param = gfn2_alpb_dmf
          case('ethanol');      param = gfn2_alpb_ethanol
          case('nhexan','n-hexan','nhexane','n-hexane');
             param = gfn2_alpb_hexane
          end select
       elseif (level == 0) then
          self%paramFile = 'internal GFN-FF/ALPB'
          select case(solvent)
          case('acetone');      param = gfnff_alpb_acetone
          case('acetonitrile'); param = gfnff_alpb_acetonitrile
          case('aniline');      param = gfnff_alpb_aniline
          case('benzaldehyde');      param = gfnff_alpb_benzaldehyde
          case('benzene');      param = gfnff_alpb_benzene
          case('dioxane');      param = gfnff_alpb_dioxane
          case('ethylacetate');      param = gfnff_alpb_ethylacetate
          case('furane');      param = gfnff_alpb_furane
          case('hexadecane');      param = gfnff_alpb_hexadecane
          case('nitromethane');      param = gfnff_alpb_nitromethane
          case('octanol');      param = gfnff_alpb_octanol
          case('woctanol');      param = gfnff_alpb_woctanol
          case('phenol');      param = gfnff_alpb_phenol
          case('ch2cl2','dichlormethane'); param = gfnff_alpb_ch2cl2
          case('chcl3','chloroform');      param = gfnff_alpb_chcl3
          case('cs2');          param = gfnff_alpb_cs2
          case('dmso');         param = gfnff_alpb_dmso
          case('ether');        param = gfnff_alpb_ether
          case('h2o','water');  param = gfnff_alpb_water
          case('methanol');     param = gfnff_alpb_methanol
          case('ethanol');      param = gfnff_alpb_ethanol
          case('thf');          param = gfnff_alpb_thf
          case('toluene');      param = gfnff_alpb_toluene
          case('dmf');          param = gfnff_alpb_dmf
          case('nhexan','n-hexan','nhexane','n-hexane');
             param = gfnff_alpb_hexane
       end select
       else
          self%paramFile = 'internal GFN1-xTB/ALPB'
          select case(solvent)
          case('acetone');      param = gfn1_alpb_acetone
          case('acetonitrile'); param = gfn1_alpb_acetonitrile
          case('aniline');      param = gfn1_alpb_aniline
          case('benzaldehyde');      param = gfn1_alpb_benzaldehyde
          case('benzene');      param = gfn1_alpb_benzene
          case('dioxane');      param = gfn1_alpb_dioxane
          case('ethylacetate');      param = gfn1_alpb_ethylacetate
          case('furane');      param = gfn1_alpb_furane
          case('hexadecane');      param = gfn1_alpb_hexadecane
          case('nitromethane');      param = gfn1_alpb_nitromethane
          case('octanol');      param = gfn1_alpb_octanol
          case('woctanol');      param = gfn1_alpb_woctanol
          case('phenol');      param = gfn1_alpb_phenol
          case('ch2cl2','dichlormethane'); param = gfn1_alpb_ch2cl2
          case('chcl3','chloroform');      param = gfn1_alpb_chcl3
          case('cs2');          param = gfn1_alpb_cs2
          case('dmso');         param = gfn1_alpb_dmso
          case('ether');        param = gfn1_alpb_ether
          case('h2o','water');  param = gfn1_alpb_water
          case('methanol');     param = gfn1_alpb_methanol
          case('ethanol');      param = gfn1_alpb_ethanol
          case('thf');          param = gfn1_alpb_thf
          case('toluene');      param = gfn1_alpb_toluene
          case('dmf');          param = gfn1_alpb_dmf
          case('nhexan','n-hexan','nhexane','n-hexane');
             param = gfn1_alpb_hexane
          end select
       end if
       if (.not.allocated(param)) then
          call env%error("solvent: '"//solvent//"' is not parametrized", source)
          return
       end if
    end select
    call paramtomodel(self, param)
References xtb_solv_kernel::gbkernel, and paramtomodel().
Referenced by xtb_solv_model::init::initsolvmodel().
newbornmodel()
subroutine, public xtb_solv_model::newbornmodel (class(tsolvmodel), intent(in) self, type(tenvironment), intent(inout) env, type(tborn), intent(out) model, integer, dimension(:), intent(in) num)
Parameters
[in,out] env Computation environment
[in] self Data structure
[out] model Solvation model to create
[in] num Atomic numbers
Definition at line 643 of file model.f90.
    character(len=*), parameter :: source = 'solv_model_newSolvationModel'
    type(TEnvironment), intent(inout) :: env
    class(TSolvModel), intent(in) :: self
    type(TBorn), intent(out) :: model
    integer, intent(in) :: num(:)
    call init_(model, env, num, self%vdwRad, self%dielectricConst, &
       & self%freeEnergyShift, self%descreening, self%bornScale, &
       & self%bornOffset, self%surfaceTension, self%probeRad, lrcut, srcut, &
       & self%nAng, self%hBondStrength, self%temperature, self%kernel, &
       & self%alpb, self%ionStrength, self%ionRad)
References lrcut, and srcut.
Referenced by xtb_propertyoutput::main_property(), xtb_gfnff_calculator::singlepoint(), xtb_xtb_calculator::singlepoint(), test_eeq_model_gbsa(), and test_eeq_model_salt().
newsolvationmodel()
subroutine, public xtb_solv_model::newsolvationmodel (class(tsolvmodel), intent(in) self, type(tenvironment), intent(inout) env, class(tsolvation), intent(out), allocatable model, integer, dimension(:), intent(in) num)
Parameters
[in,out] env Computation environment
[in] self Data structure
[out] model Solvation model to create
[in] num Atomic numbers
Definition at line 613 of file model.f90.
    character(len=*), parameter :: source = 'solv_model_newSolvationModel'
    type(TEnvironment), intent(inout) :: env
    class(TSolvModel), intent(in) :: self
    class(TSolvation), allocatable, intent(out) :: model
    integer, intent(in) :: num(:)
    type(TBorn), allocatable :: born
    allocate(born)
    call init_(born, env, num, self%vdwRad, self%dielectricConst, &
       & self%freeEnergyShift, self%descreening, self%bornScale, &
       & self%bornOffset, self%surfaceTension, self%probeRad, lrcut, srcut, &
       & self%nAng, self%hBondStrength, self%temperature, self%kernel, &
       & self%alpb, self%ionStrength, self%ionRad)
    call move_alloc(born, model)
References lrcut, and srcut.
Referenced by xtb_xtb_calculator::singlepoint().
normalizesolventname()
subroutine xtb_solv_model::normalizesolventname (character(len=:), intent(out), allocatable solvent, character(len=*), intent(in) input) private
Try to find a normalized version of an input solvent name.
Parameters
[out] solvent Name of the solvent (normalized)
[in] input Name of the solvent (unnormalized)
Definition at line 205 of file model.f90.
    character(len=:), allocatable, intent(out) :: solvent
    character(len=*), intent(in) :: input
    solvent = lowercase(input)
References xtb_mctc_strings::lowercase().
Referenced by xtb_solv_model::init::initsolvmodel().
paramtomodel()
subroutine xtb_solv_model::paramtomodel (type(tsolvmodel), intent(inout) self, type(gbsa_parameter), intent(in) param) private
Parameters
[in,out] self Data structure
Definition at line 440 of file model.f90.
    type(TSolvModel), intent(inout) :: self
    type(gbsa_parameter), intent(in) :: param
    integer :: ii
    self%dielectricConst = param%epsv
    self%molarMass = param%smass
    self%density = param%rhos/param%smass * molcm3toau
    self%freeEnergyShift = param%gshift * kcaltoau
    self%bornScale = param%c1
    self%bornOffset = param%soset * 0.1_wp*aatoau
    self%probeRad = param%rprobe * aatoau
    self%vdwRad = vanderwaalsradd3
    self%surfaceTension = param%gamscale * fourpi*surfacetension
    self%descreening = param%sx
    allocate(self%hBondStrength(size(param%tmp)))
    if (any(abs(param%tmp).gt.1.e-3_wp)) then
       do ii = 1, size(param%tmp)
          self%hBondStrength(ii) = -(param%tmp(ii)**2) * kcaltoau
       end do
    else
       self%hBondStrength(:) = 0.0_wp
    end if
References xtb_mctc_convert::aatoau, xtb_mctc_constants::fourpi, xtb_mctc_convert::kcaltoau, molcm3toau, surfacetension, and xtb_param_vdwradd3::vanderwaalsradd3.
Referenced by loadinternalparam(), and readparamfile().
readparamfile()
subroutine xtb_solv_model::readparamfile (type(tsolvmodel), intent(inout) self, type(tenvironment), intent(inout) env) private
Parameters
[in,out] env Computation environment
[in,out] self Data structure
Definition at line 386 of file model.f90.
    character(len=*), parameter :: source = 'solv_model_readParamFile'
    type(TEnvironment), intent(inout) :: env
    type(TSolvModel), intent(inout) :: self
    type(gbsa_parameter) :: param
    integer :: unit, stat, statc, ii
    statc = 0
    call open_file(unit, self%paramFile, 'r')
    if (unit == -1) then
       call env%error("Could not open parameter file '"//self%paramFile//"'", &
          & source)
       return
    end if
    read(unit,*,iostat=stat) param%epsv
    if (stat /= 0) statc = statc + 1
    read(unit,*,iostat=stat) param%smass
    if (stat /= 0) statc = statc + 1
    read(unit,*,iostat=stat) param%rhos
    if (stat /= 0) statc = statc + 1
    read(unit,*,iostat=stat) param%c1
    if (stat /= 0) statc = statc + 1
    read(unit,*,iostat=stat) param%rprobe
    if (stat /= 0) statc = statc + 1
    read(unit,*,iostat=stat) param%gshift
    if (stat /= 0) statc = statc + 1
    read(unit,*,iostat=stat) param%soset
    if (stat /= 0) statc = statc + 1
    read(unit,*,iostat=stat) param%alpha
    if (stat /= 0) statc = statc + 1
    do ii = 1, 94
       read(unit,*,iostat=stat) param%gamscale(ii), param%sx(ii), param%tmp(ii)
       if (stat /= 0) statc = statc + 1
    enddo
    if (statc /= 0) then
       call env%error("Could not read parameters from '"//self%paramFile//"'", &
          & source)
       return
    end if
    call paramtomodel(self, param)
References open_file(), and paramtomodel().
Referenced by xtb_solv_model::init::initsolvmodel().
Variable Documentation
automnm
real(wp), parameter xtb_solv_model::automnm = autokcal * kcaltomNm private
Definition at line 152 of file model.f90.
    real(wp), parameter :: automNm = autokcal * kcaltomnm
Referenced by info().
kcaltomnm
real(wp), parameter xtb_solv_model::kcaltomnm = 1.0_wp/mNmtokcal private
Definition at line 151 of file model.f90.
    real(wp), parameter :: kcaltomNm = 1.0_wp/mnmtokcal
lrcut
real(wp), parameter xtb_solv_model::lrcut = 35.0_wp * aatoau private
Definition at line 154 of file model.f90.
    real(wp),parameter :: lrcut = 35.0_wp * aatoau
Referenced by newbornmodel(), and newsolvationmodel().
mnmtokcal
real(wp), parameter xtb_solv_model::mnmtokcal = 4.0305201015221386e-4_wp private
Definition at line 150 of file model.f90.
    real(wp), parameter :: mNmtokcal = 4.0305201015221386e-4_wp
molcm3toau
real(wp), parameter xtb_solv_model::molcm3toau = 8.92388e-2_wp private
Solvent density (g/cm^3) and molar mass (g/mol)
Definition at line 146 of file model.f90.
    real(wp), parameter :: molcm3toau = 8.92388e-2_wp
Referenced by info(), and paramtomodel().
srcut
real(wp), parameter xtb_solv_model::srcut = 2.0_wp * aatoau private
Definition at line 155 of file model.f90.
    real(wp),parameter :: srcut = 2.0_wp * aatoau
Referenced by newbornmodel(), and newsolvationmodel().
surfacetension
real(wp), parameter xtb_solv_model::surfacetension = 1.0e-5_wp private
Surface tension (mN/m=dyn/cm)
Definition at line 149 of file model.f90.
    real(wp), parameter :: surfaceTension = 1.0e-5_wp
Referenced by info(), and paramtomodel().