My Project: xtb_type_wignerseitzcell Module Reference
xtb_type_wignerseitzcell Module Reference
Wigner-Seitz cell based on a neighbour list.
Data Types
type twignerseitzcell
Wigner-Seitz cell based on the infrastructure for the neighbour list.
interface init
Initialize Wigner-Seitz cell.
Functions/Subroutines
subroutine initwignerseitzcell (self, nAtom)
Initialize Wigner-Seitz cell.
subroutine generate (self, env, coords0, cutoff, latPoint, symmetric)
Generate Wigner-Seitz cell.
Variables
real(wp), parameter wstol2 = 0.01_wp**2
Tolerance for including images in the Wigner-Seitz cell.
Detailed Description
Wigner-Seitz cell based on a neighbour list.
Function/Subroutine Documentation
generate()
subroutine xtb_type_wignerseitzcell::generate (class(twignerseitzcell), intent(inout) self, type(tenvironment), intent(inout) env, real(wp), dimension(:, :), intent(in) coords0, real(wp), intent(in) cutoff, real(wp), dimension(:, :), intent(in) latPoint, logical, intent(in) symmetric) private
Generate Wigner-Seitz cell.
Parameters
[in,out] self Instance of the Wigner-Seitz cell
[in,out] env Computation environment
[in] coords0 Folded coordinates of the atoms inside the unit cell
[in] cutoff Realspace cutoff for the generation of neighbours
[in] latpoint Lattice points for all supercells within the cutoff
[in] symmetric Generate a symmetric map
Number of atoms in the central cell
Number of translations to consider
Capacity of the atom related arrays
Capacity of the neighbour related arrays
Index of the current image
Quadratic cutoff
Get dimensions for the generator loop
Get initial capacities
Set the value of the cutoff
Initialize neighbour list with distances from every atom to itself
Allocate scratch space for Wigner-Seitz neighbours
Start with images in the central cell already generated
Generate position of image
Small distances between the atom and itself are okay
Sort the neighbours in the Wigner-Seitz cell
Drop all but the closest neighbours
Make sure the capacity of the arrays is large enough
Store the Wigner-Seitz cell
Definition at line 80 of file wignerseitzcell.f90.
    character(len=*), parameter :: source = 'type_wignerseitzcell_generate'
    class(TWignerSeitzCell), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: coords0(:, :)
    real(wp), intent(in) :: cutoff
    real(wp), intent(in) :: latPoint(:, :)
    logical, intent(in) :: symmetric
    integer :: nAtom
    integer :: nTrans
    integer :: mImage
    integer :: mNeigh
    integer :: nImage
    real(wp) :: cutoff2
    integer :: iTr, iAt, iAtOld, jAt, jAtEnd, iWs, nWs
    real(wp) :: ri(3), dist2, trans(3), wsWeight
    integer, allocatable :: wsTrans(:), indx(:)
    real(wp), allocatable :: wsDist2(:)
    natom = size(self%neighs, dim=1)
    ntrans = size(latpoint, dim=2)
    nimage = natom*ntrans
    mimage = size(self%coords, dim=2)
    mneigh = ubound(self%iNeigh, dim=1)
    if (nimage > mimage) then
       call resizeimage(nimage, self%image, self%trans, self%coords)
    end if
    self%cutoff = cutoff
    cutoff2 = cutoff**2
    self%neighs(:) = 0
    self%iNeigh(:, :) = 0
    self%dist2(:, :) = 0.0_wp
    self%weight(:, :) = 0.0_wp
    do iat = 1, natom
       self%iNeigh(0, iat) = iat
       self%weight(0, iat) = 1.0_wp
       self%coords(:, iat) = coords0(:, iat)
       self%image(iat) = iat
       self%trans(iat) = 1
    end do
    allocate(wsdist2(ntrans))
    allocate(wstrans(ntrans))
    allocate(indx(ntrans))
    nimage = natom
    lpiat: do iat = 1, natom
       if (symmetric) then
          jatend = natom
       else
          jatend = iat
       end if
       lpjat: do jat = 1, jatend
          nws = 0
          lptrans: do itr = 1, ntrans
             ri(:) = coords0(:, iat) + latpoint(:, itr)
             dist2 = sum((ri - coords0(:, jat))**2)
             if (dist2 > cutoff2) then
                cycle lptrans
             end if
             if (dist2 < minneighdist2) then
                if (itr == 1 .and. iat == jat) then
                   cycle lptrans
                else
                   call env%error("Very close distance found", source)
                end if
             end if
             nws = nws + 1
             wsdist2(nws) = dist2
             wstrans(nws) = itr
          end do lptrans
          if (nws == 0) cycle lpjat
          call indexheapsort(indx(1:nws), wsdist2(1:nws), tolsamedist2)
          wsdist2(1:nws) = wsdist2(indx(1:nws))
          wstrans(1:nws) = wstrans(indx(1:nws))
          call bisectsearch(nws, wsdist2(1:nws), wsdist2(1)+wstol2, tolsamedist2)
          wsweight = 1.0_wp/real(nws, wp)
          if (nimage + nws > mimage) then
             mimage = max(2*mimage, mimage + 2*nws)
             call resizeimage(mimage, self%image, self%trans, self%coords)
          end if
          if (self%neighs(jat) + nws > mneigh) then
             mneigh = max(2*mneigh, mneigh + 2*nws)
             call resizeneigh(mneigh, self%iNeigh, self%dist2, self%weight)
          end if
          do iws = 1, nws
             itr = wstrans(iws)
             if (itr /= 1) then
                nimage = nimage + 1
                self%coords(:, nimage) = coords0(:, iat) + latpoint(:, wstrans(iws))
                self%image(nimage) = iat
                self%trans(nimage) = itr
                self%iNeigh(self%neighs(jat)+iws, jat) = nimage
             else
                self%iNeigh(self%neighs(jat)+iws, jat) = iat
             end if
             self%dist2(self%neighs(jat)+iws, jat) = wsdist2(iws)
             self%weight(self%neighs(jat)+iws, jat) = wsweight
          end do
          self%neighs(jat) = self%neighs(jat) + nws
       end do lpjat
    end do lpiat
    call resizeimage(nimage, self%image, self%trans, self%coords)
    call self%sort
References xtb_mctc_sort::indexheapsort(), xtb_mctc_thresholds::minneighdist2, xtb_type_neighbourlist::resizeimage(), xtb_type_neighbourlist::resizeneigh(), xtb_mctc_thresholds::tolsamedist2, and wstol2.
initwignerseitzcell()
subroutine xtb_type_wignerseitzcell::initwignerseitzcell (type(twignerseitzcell), intent(out) self, integer, intent(in) nAtom) private
Initialize Wigner-Seitz cell.
Parameters
[out] self Instance of the Wigner-Seitz cell
[in] natom Number of atoms in the system
Definition at line 57 of file wignerseitzcell.f90.
    type(TWignerSeitzCell), intent(out) :: self
    integer, intent(in) :: nAtom
    allocate(self%neighs(natom))
    allocate(self%image(natom))
    allocate(self%coords(3, natom))
    allocate(self%trans(natom))
    allocate(self%iNeigh(0:initialnumberofneighbours, natom))
    allocate(self%dist2(0:initialnumberofneighbours, natom))
    allocate(self%weight(0:initialnumberofneighbours, natom))
    self%cutoff = -1.0_wp
Variable Documentation
wstol2
real(wp), parameter xtb_type_wignerseitzcell::wstol2 = 0.01_wp**2 private
Tolerance for including images in the Wigner-Seitz cell.
Definition at line 50 of file wignerseitzcell.f90.
    real(wp), parameter :: wsTol2 = 0.01_wp**2
Referenced by generate().