My Project: xtb_io_reader Module Reference
xtb_io_reader Module Reference
Generic wrappers for all the readers implemented.
Functions/Subroutines
subroutine, public readmolecule (env, mol, unit, ftype)
Generic reader for molecules from input files.
subroutine, public readhessian (env, mol, hessian, reader, format)
Detailed Description
Generic wrappers for all the readers implemented.
Function/Subroutine Documentation
readhessian()
subroutine, public xtb_io_reader::readhessian (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(out) hessian, type(treader), intent(inout) reader, integer, intent(in) format)
Definition at line 98 of file reader.f90.
    character(len=*), parameter :: source = 'io_reader_readHessian'
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    type(TReader), intent(inout) :: reader
    integer, intent(in) :: format
    real(wp), intent(out) :: hessian(:, :)
    character(len=:), allocatable :: message
    logical :: status
    if (any(shape(hessian) /= [3*mol%n, 3*mol%n])) then
       call env%error("Shape of hessian array does not match geometry", source)
       return
    end if
    select case(format)
    case default
       message = "Unknown hessian format"
       status = .false.
    case(filetype%tmol)
       call readhessianturbomole(hessian, reader, mol, status, message)
    case(filetype%gen)
       call readhessiandftbplus(hessian, reader, mol, status, message)
    end select
    if (.not.status) then
       call env%error(message, source)
       return
    end if
References xtb_mctc_filetypes::filetype, xtb_io_reader_genformat::readhessiandftbplus(), and xtb_io_reader_turbomole::readhessianturbomole().
Referenced by xtb_prog_thermo::xtbthermo().
readmolecule()
subroutine, public xtb_io_reader::readmolecule (class(tenvironment), intent(inout) env, class(tmolecule), intent(out) mol, integer, intent(in) unit, integer, intent(in) ftype)
Generic reader for molecules from input files.
Parameters
[in,out] env Calculation environment
[out] mol Instance of molecular structure data
[in] unit File reader
[in] ftype Idenitifier for file type
Definition at line 43 of file reader.f90.
    character(len=*), parameter :: source = "io_reader_readMolecule"
    class(TEnvironment), intent(inout) :: env
    class(TMolecule), intent(out) :: mol
    !class(TReader), intent(inout) :: reader
    integer, intent(in) :: unit
    integer, intent(in) :: ftype
    character(len=:), allocatable :: message
    logical :: status
    select case(ftype)
    case(filetype%xyz)
       call readmoleculexyz(mol, unit, status, iomsg=message)
    case(filetype%tmol)
       call readmoleculecoord(mol, unit, status, iomsg=message)
    case(filetype%molfile)
       call readmoleculemolfile(mol, unit, status, iomsg=message)
    case(filetype%sdf)
       call readmoleculesdf(mol, unit, status, iomsg=message)
    case(filetype%vasp)
       call readmoleculevasp(mol, unit, status, iomsg=message)
    case(filetype%pdb)
       call readmoleculepdb(mol, unit, status, iomsg=message)
    case(filetype%gen)
       call readmoleculegenformat(mol, unit, status, iomsg=message)
    case(filetype%gaussian)
       call readmoleculegaussianexternal(mol, unit, status, iomsg=message)
    case default
       status = .false.
       message = "coordinate format not known"
    end select
    if (.not.status) then
       call env%error(message, source)
       return
    end if
    call mol%update
    mol%ftype = ftype
References xtb_mctc_filetypes::filetype, xtb_io_reader_turbomole::readmoleculecoord(), xtb_io_reader_gaussian::readmoleculegaussianexternal(), xtb_io_reader_genformat::readmoleculegenformat(), xtb_io_reader_ctfile::readmoleculemolfile(), xtb_io_reader_pdb::readmoleculepdb(), xtb_io_reader_ctfile::readmoleculesdf(), xtb_io_reader_vasp::readmoleculevasp(), and xtb_io_reader_xyz::readmoleculexyz().
Referenced by test_geometry_reader_file_coord_caf2_3d(), test_geometry_reader_file_coord_camgco_3d(), test_geometry_reader_file_coord_general_0d(), test_geometry_reader_file_gen(), test_geometry_reader_file_pdb_4qxx(), test_geometry_reader_file_pdb_4qxx_noh(), test_geometry_reader_file_poscar_sio2_3d(), test_geometry_reader_file_sdf_benzen_hquery(), test_geometry_reader_file_sdf_h2o(), test_geometry_reader_file_sdf_h2o_flat(), test_geometry_reader_file_xmol_water_0d(), test_geometry_reader_molfile_benzen(), test_geometry_reader_molfile_benzen_flat(), xtb_prog_info::xtbinfo(), xtb_prog_main::xtbmain(), xtb_prog_thermo::xtbthermo(), and xtb_prog_topology::xtbtopology().