My Project: xtb_prog_submodules Module Reference
xtb_prog_submodules Module Reference
Available submodule in this program.
Data Types
type tsubmoduleenum
Possible submodules for xtb.
Functions/Subroutines
integer function, public getsubmodule (argument)
Translate a string in a submodule enumerator.
Variables
type(tsubmoduleenum), parameter, public xtbsubmodule = TSubmoduleEnum()
Actual enumerator for the submodules.
Detailed Description
Available submodule in this program.
Function/Subroutine Documentation
getsubmodule()
integer function, public xtb_prog_submodules::getsubmodule (character(len=*), intent(in) argument)
Translate a string in a submodule enumerator.
Parameters
[in] argument String identifying the submodule name
Returns
Identifier of the submodule
Definition at line 55 of file submodules.f90.
    character(len=*), intent(in) :: argument
    integer :: submod
    select case(argument)
    case default
       submod = xtbsubmodule%invalid
    case('info')
       submod = xtbsubmodule%info
    case('thermo')
       submod = xtbsubmodule%thermo
    case('topo')
       submod = xtbsubmodule%topo
    end select
References xtbsubmodule.
Referenced by getrunmode().
Variable Documentation
xtbsubmodule
type(tsubmoduleenum), parameter, public xtb_prog_submodules::xtbsubmodule = TSubmoduleEnum()
Actual enumerator for the submodules.
Definition at line 48 of file submodules.f90.
    type(TSubmoduleEnum), parameter :: xtbSubmodule = tsubmoduleenum()
Referenced by getrunmode(), getsubmodule(), and xtb_prog_primary().