My Project: xtb_mctc_global Module Reference
xtb_mctc_global Module Reference
Data Types
type errormsg
Functions/Subroutines
subroutine init_errorbuffer
Variables
character(len=:), allocatable name
name of the currently running program
character(len=:), allocatable, target msgbuffer
error message buffer
integer msgid
number of generated errors
integer maxmsg = 100
size of error buffer
logical is_release = .false.
logical strict = .false.
logical mute = .false.
logical good = .true.
type(tenvironment), allocatable persistentenv
Global environment.
type(errormsg), dimension(:), allocatable errorbuffer
Function/Subroutine Documentation
init_errorbuffer()
subroutine xtb_mctc_global::init_errorbuffer
Definition at line 51 of file mctc_global.F90.
    implicit none
    if (allocated(errorbuffer)) deallocate ( errorbuffer )
    allocate ( errorbuffer(maxmsg) )
    msgid = 0
    msgbuffer = ' '
References errorbuffer, maxmsg, msgbuffer, and msgid.
Referenced by mctc_init().
Variable Documentation
errorbuffer
type(errormsg), dimension(:), allocatable xtb_mctc_global::errorbuffer
Definition at line 47 of file mctc_global.F90.
    type(errormsg),allocatable :: errorbuffer(:)
Referenced by init_errorbuffer().
good
logical xtb_mctc_global::good = .true.
Definition at line 34 of file mctc_global.F90.
    logical :: good = .true.
Referenced by mctc_sanity().
is_release
logical xtb_mctc_global::is_release = .false.
Definition at line 28 of file mctc_global.F90.
    logical :: is_release = .false.
maxmsg
integer xtb_mctc_global::maxmsg = 100
size of error buffer
Definition at line 27 of file mctc_global.F90.
    integer :: maxmsg = 100
Referenced by init_errorbuffer().
msgbuffer
character(len=:), allocatable, target xtb_mctc_global::msgbuffer
error message buffer
Definition at line 25 of file mctc_global.F90.
    character(len=:),allocatable,target :: msgbuffer
Referenced by init_errorbuffer().
msgid
integer xtb_mctc_global::msgid
number of generated errors
Definition at line 26 of file mctc_global.F90.
    integer :: msgid
Referenced by eval_define(), and init_errorbuffer().
mute
logical xtb_mctc_global::mute = .false.
Definition at line 32 of file mctc_global.F90.
    logical :: mute = .false.
Referenced by mctc_mute().
name
character(len=:), allocatable xtb_mctc_global::name
name of the currently running program
Definition at line 24 of file mctc_global.F90.
    character(len=:),allocatable :: name
Referenced by eval_define(), mctc_init(), and terminate().
persistentenv
type(tenvironment), allocatable xtb_mctc_global::persistentenv
Global environment.
Definition at line 37 of file mctc_global.F90.
    type(TEnvironment), allocatable :: persistentEnv
Referenced by xtb_api_utils::checkglobalenv(), close_file(), delete_file(), xtb_setparam::get_namespace(), mctc_init(), open_binary(), open_file(), xtb_prog_main::parsearguments(), xtb_prog_topology::parsearguments(), print_filelist(), raise(), rdcoord(), rdsdf(), remove_file(), xtb_printout::setup_summary(), and touch_file().
strict
logical xtb_mctc_global::strict = .false.
Definition at line 30 of file mctc_global.F90.
    logical :: strict = .false.
Referenced by mctc_strict(), and raise().