My Project: xtb_mctc_accuracy Module Reference
xtb_mctc_accuracy Module Reference
Numerical storage size parameters.
Variables
integer, parameter sp = selected_real_kind(6)
Single precision real numbers.
integer, parameter dp = selected_real_kind(15)
Double precision real numbers.
integer, parameter wp = dp
Wanted precision.
integer, parameter i1 = selected_int_kind(2)
Char length for integers.
integer, parameter i2 = selected_int_kind(4)
Short length for integers.
integer, parameter i4 = selected_int_kind(9)
Length of default integers.
integer, parameter i8 = selected_int_kind(18)
Long length for integers.
Detailed Description
Numerical storage size parameters.
Variable Documentation
dp
integer, parameter xtb_mctc_accuracy::dp = selected_real_kind(15)
Double precision real numbers.
Definition at line 28 of file accuracy.f90.
    integer, parameter :: dp = selected_real_kind(15)
Referenced by xtb_mctc_blas_level1::blas_asum::dasum(), xtb_mctc_blas_level1::blas_axpy::daxpy(), xtb_mctc_blas_level1::blas_cabs1::dcabs1(), xtb_mctc_blas_level1::blas_copy::dcopy(), xtb_mctc_blas_level1::blas_dot::ddot(), xtb_mctc_blas_level2::blas_gbmv::dgbmv(), xtb_mctc_blas_level3::blas_gemm::dgemm(), xtb_mctc_blas_level2::blas_gemv::dgemv(), xtb_mctc_blas_level2::blas_ger::dger(), xtb_mctc_lapack_trf::lapack_getrf::dgetrf(), xtb_mctc_lapack_tri::lapack_getri::dgetri(), xtb_mctc_lapack_trs::lapack_getrs::dgetrs(), xtb_mctc_blas_level1::blas_nrm2::dnrm2(), xtb_mctc_lapack_trf::lapack_potrf::dpotrf(), xtb_mctc_lapack_tri::lapack_potri::dpotri(), xtb_mctc_lapack_trs::lapack_potrs::dpotrs(), xtb_mctc_lapack_trf::lapack_pptrf::dpptrf(), xtb_mctc_lapack_tri::lapack_pptri::dpptri(), xtb_mctc_lapack_trs::lapack_pptrs::dpptrs(), xtb_mctc_blas_level1::blas_rot::drot(), xtb_mctc_blas_level2::blas_sbmv::dsbmv(), xtb_mctc_blas_level1::blas_scal::dscal(), xtb_mctc_lapack_stdeigval::lapack_spev::dspev(), xtb_mctc_lapack_stdeigval::lapack_spevd::dspevd(), xtb_mctc_lapack_stdeigval::lapack_spevx::dspevx(), xtb_mctc_lapack_gst::lapack_spgst::dspgst(), xtb_mctc_lapack_geneigval::lapack_spgv::dspgv(), xtb_mctc_lapack_geneigval::lapack_spgvd::dspgvd(), xtb_mctc_lapack_geneigval::lapack_spgvx::dspgvx(), xtb_mctc_blas_level2::blas_spmv::dspmv(), xtb_mctc_blas_level2::blas_spr::dspr(), xtb_mctc_blas_level2::blas_spr2::dspr2(), xtb_mctc_lapack_trf::lapack_sptrf::dsptrf(), xtb_mctc_lapack_tri::lapack_sptri::dsptri(), xtb_mctc_lapack_trs::lapack_sptrs::dsptrs(), xtb_mctc_blas_level1::blas_swap::dswap(), xtb_mctc_lapack_stdeigval::lapack_syev::dsyev(), xtb_mctc_lapack_stdeigval::lapack_syevd::dsyevd(), xtb_mctc_lapack_stdeigval::lapack_syevr::dsyevr(), xtb_mctc_lapack_stdeigval::lapack_syevx::dsyevx(), xtb_mctc_lapack_gst::lapack_sygst::dsygst(), xtb_mctc_lapack_geneigval::lapack_sygv::dsygv(), xtb_mctc_lapack_geneigval::lapack_sygvd::dsygvd(), xtb_mctc_lapack_geneigval::lapack_sygvx::dsygvx(), xtb_mctc_blas_level3::blas_symm::dsymm(), xtb_mctc_blas_level2::blas_symv::dsymv(), xtb_mctc_blas_level2::blas_syr::dsyr(), xtb_mctc_blas_level2::blas_syr2::dsyr2(), xtb_mctc_blas_level3::blas_syr2k::dsyr2k(), xtb_mctc_blas_level3::blas_syrk::dsyrk(), xtb_mctc_lapack_trf::lapack_sytrf::dsytrf(), xtb_mctc_lapack_tri::lapack_sytri::dsytri(), xtb_mctc_lapack_trs::lapack_sytrs::dsytrs(), xtb_mctc_blas_level2::blas_tbmv::dtbmv(), xtb_mctc_blas_level2::blas_tbsv::dtbsv(), xtb_mctc_blas_level2::blas_tpmv::dtpmv(), xtb_mctc_blas_level2::blas_tpsv::dtpsv(), xtb_mctc_blas_level3::blas_trmm::dtrmm(), xtb_mctc_blas_level2::blas_trmv::dtrmv(), xtb_mctc_blas_level3::blas_trsm::dtrsm(), xtb_mctc_blas_level2::blas_trsv::dtrsv(), xtb_mctc_blas_level1::blas_asum::dzasum(), xtb_mctc_blas_level3::blas_gemm::dzgemm(), xtb_mctc_blas_level2::blas_gemv::dzgemv(), xtb_mctc_blas_level1::blas_nrm2::dznrm2(), xtb_mctc_blas_level1::blas_iamax::idamax(), xtb_mctc_blas_level1::blas_iamax::izamax(), xtb_mctc_blas_level1::blas_axpy::zaxpy(), xtb_mctc_blas_level1::blas_copy::zcopy(), xtb_mctc_blas_level1::blas_dotc::zdotc(), xtb_mctc_blas_level1::blas_dotu::zdotu(), xtb_mctc_blas_level1::blas_rot::zdrot(), xtb_mctc_blas_level1::blas_scal::zdscal(), xtb_mctc_blas_level2::blas_gbmv::zgbmv(), xtb_mctc_blas_level3::blas_gemm::zgemm(), xtb_mctc_blas_level2::blas_gemv::zgemv(), xtb_mctc_blas_level2::blas_gerc::zgerc(), xtb_mctc_blas_level2::blas_geru::zgeru(), xtb_mctc_lapack_trf::lapack_getrf::zgetrf(), xtb_mctc_lapack_tri::lapack_getri::zgetri(), xtb_mctc_lapack_trs::lapack_getrs::zgetrs(), xtb_mctc_blas_level2::blas_hbmv::zhbmv(), xtb_mctc_lapack_stdeigval::lapack_heev::zheev(), xtb_mctc_lapack_stdeigval::lapack_heevd::zheevd(), xtb_mctc_lapack_stdeigval::lapack_heevr::zheevr(), xtb_mctc_lapack_stdeigval::lapack_heevx::zheevx(), xtb_mctc_lapack_gst::lapack_hegst::zhegst(), xtb_mctc_lapack_geneigval::lapack_hegv::zhegv(), xtb_mctc_lapack_geneigval::lapack_hegvd::zhegvd(), xtb_mctc_lapack_geneigval::lapack_hegvx::zhegvx(), xtb_mctc_blas_level3::blas_hemm::zhemm(), xtb_mctc_blas_level2::blas_hemv::zhemv(), xtb_mctc_blas_level2::blas_her::zher(), xtb_mctc_blas_level2::blas_her2::zher2(), xtb_mctc_blas_level3::blas_her2k::zher2k(), xtb_mctc_blas_level3::blas_herk::zherk(), xtb_mctc_lapack_stdeigval::lapack_hpev::zhpev(), xtb_mctc_lapack_stdeigval::lapack_hpevd::zhpevd(), xtb_mctc_lapack_stdeigval::lapack_hpevx::zhpevx(), xtb_mctc_lapack_gst::lapack_hpgst::zhpgst(), xtb_mctc_lapack_geneigval::lapack_hpgv::zhpgv(), xtb_mctc_lapack_geneigval::lapack_hpgvd::zhpgvd(), xtb_mctc_lapack_geneigval::lapack_hpgvx::zhpgvx(), xtb_mctc_blas_level2::blas_hpmv::zhpmv(), xtb_mctc_blas_level2::blas_hpr::zhpr(), xtb_mctc_blas_level2::blas_hpr2::zhpr2(), xtb_mctc_lapack_trf::lapack_potrf::zpotrf(), xtb_mctc_lapack_tri::lapack_potri::zpotri(), xtb_mctc_lapack_trs::lapack_potrs::zpotrs(), xtb_mctc_lapack_trf::lapack_pptrf::zpptrf(), xtb_mctc_lapack_tri::lapack_pptri::zpptri(), xtb_mctc_lapack_trs::lapack_pptrs::zpptrs(), xtb_mctc_blas_level1::blas_scal::zscal(), xtb_mctc_lapack_trf::lapack_sptrf::zsptrf(), xtb_mctc_lapack_tri::lapack_sptri::zsptri(), xtb_mctc_lapack_trs::lapack_sptrs::zsptrs(), xtb_mctc_blas_level1::blas_swap::zswap(), xtb_mctc_blas_level3::blas_symm::zsymm(), xtb_mctc_blas_level3::blas_syr2k::zsyr2k(), xtb_mctc_blas_level3::blas_syrk::zsyrk(), xtb_mctc_lapack_trf::lapack_sytrf::zsytrf(), xtb_mctc_lapack_tri::lapack_sytri::zsytri(), xtb_mctc_lapack_trs::lapack_sytrs::zsytrs(), xtb_mctc_blas_level2::blas_tbmv::ztbmv(), xtb_mctc_blas_level2::blas_tbsv::ztbsv(), xtb_mctc_blas_level2::blas_tpmv::ztpmv(), xtb_mctc_blas_level2::blas_tpsv::ztpsv(), xtb_mctc_blas_level3::blas_trmm::ztrmm(), xtb_mctc_blas_level2::blas_trmv::ztrmv(), xtb_mctc_blas_level3::blas_trsm::ztrsm(), and xtb_mctc_blas_level2::blas_trsv::ztrsv().
i1
integer, parameter xtb_mctc_accuracy::i1 = selected_int_kind(2)
Char length for integers.
Definition at line 34 of file accuracy.f90.
    integer, parameter :: i1 = selected_int_kind(2)
i2
integer, parameter xtb_mctc_accuracy::i2 = selected_int_kind(4)
Short length for integers.
Definition at line 37 of file accuracy.f90.
    integer, parameter :: i2 = selected_int_kind(4)
i4
integer, parameter xtb_mctc_accuracy::i4 = selected_int_kind(9)
Length of default integers.
Definition at line 40 of file accuracy.f90.
    integer, parameter :: i4 = selected_int_kind(9)
i8
integer, parameter xtb_mctc_accuracy::i8 = selected_int_kind(18)
Long length for integers.
Definition at line 43 of file accuracy.f90.
    integer, parameter :: i8 = selected_int_kind(18)
Referenced by xtb_restart::read_restart_gff(), xtb_restart::readrestart(), wrgbw(), xtb_restart::write_restart_gff(), and xtb_restart::writerestart().
sp
integer, parameter xtb_mctc_accuracy::sp = selected_real_kind(6)
Single precision real numbers.
Definition at line 25 of file accuracy.f90.
    integer, parameter :: sp = selected_real_kind(6)
Referenced by xtb_mctc_blas_level1::blas_axpy::caxpy(), xtb_mctc_blas_level1::blas_copy::ccopy(), xtb_mctc_blas_level1::blas_dotc::cdotc(), xtb_mctc_blas_level1::blas_dotu::cdotu(), xtb_mctc_blas_level2::blas_gbmv::cgbmv(), xtb_mctc_blas_level3::blas_gemm::cgemm(), xtb_mctc_blas_level2::blas_gemv::cgemv(), xtb_mctc_blas_level2::blas_gerc::cgerc(), xtb_mctc_blas_level2::blas_geru::cgeru(), xtb_mctc_lapack_trf::lapack_getrf::cgetrf(), xtb_mctc_lapack_tri::lapack_getri::cgetri(), xtb_mctc_lapack_trs::lapack_getrs::cgetrs(), xtb_mctc_blas_level2::blas_hbmv::chbmv(), xtb_mctc_lapack_stdeigval::lapack_heev::cheev(), xtb_mctc_lapack_stdeigval::lapack_heevd::cheevd(), xtb_mctc_lapack_stdeigval::lapack_heevr::cheevr(), xtb_mctc_lapack_stdeigval::lapack_heevx::cheevx(), xtb_mctc_lapack_gst::lapack_hegst::chegst(), xtb_mctc_lapack_geneigval::lapack_hegv::chegv(), xtb_mctc_lapack_geneigval::lapack_hegvd::chegvd(), xtb_mctc_lapack_geneigval::lapack_hegvx::chegvx(), xtb_mctc_blas_level3::blas_hemm::chemm(), xtb_mctc_blas_level2::blas_hemv::chemv(), xtb_mctc_blas_level2::blas_her::cher(), xtb_mctc_blas_level2::blas_her2::cher2(), xtb_mctc_blas_level3::blas_her2k::cher2k(), xtb_mctc_blas_level3::blas_herk::cherk(), xtb_mctc_lapack_stdeigval::lapack_hpev::chpev(), xtb_mctc_lapack_stdeigval::lapack_hpevd::chpevd(), xtb_mctc_lapack_stdeigval::lapack_hpevx::chpevx(), xtb_mctc_lapack_gst::lapack_hpgst::chpgst(), xtb_mctc_lapack_geneigval::lapack_hpgv::chpgv(), xtb_mctc_lapack_geneigval::lapack_hpgvd::chpgvd(), xtb_mctc_lapack_geneigval::lapack_hpgvx::chpgvx(), xtb_mctc_blas_level2::blas_hpmv::chpmv(), xtb_mctc_blas_level2::blas_hpr::chpr(), xtb_mctc_blas_level2::blas_hpr2::chpr2(), xtb_mctc_lapack_trf::lapack_potrf::cpotrf(), xtb_mctc_lapack_tri::lapack_potri::cpotri(), xtb_mctc_lapack_trs::lapack_potrs::cpotrs(), xtb_mctc_lapack_trf::lapack_pptrf::cpptrf(), xtb_mctc_lapack_tri::lapack_pptri::cpptri(), xtb_mctc_lapack_trs::lapack_pptrs::cpptrs(), xtb_mctc_blas_level1::blas_scal::cscal(), xtb_mctc_lapack_trf::lapack_sptrf::csptrf(), xtb_mctc_lapack_tri::lapack_sptri::csptri(), xtb_mctc_lapack_trs::lapack_sptrs::csptrs(), xtb_mctc_blas_level1::blas_rot::csrot(), xtb_mctc_blas_level1::blas_scal::csscal(), xtb_mctc_blas_level1::blas_swap::cswap(), xtb_mctc_blas_level3::blas_symm::csymm(), xtb_mctc_blas_level3::blas_syr2k::csyr2k(), xtb_mctc_blas_level3::blas_syrk::csyrk(), xtb_mctc_lapack_trf::lapack_sytrf::csytrf(), xtb_mctc_lapack_tri::lapack_sytri::csytri(), xtb_mctc_lapack_trs::lapack_sytrs::csytrs(), xtb_mctc_blas_level2::blas_tbmv::ctbmv(), xtb_mctc_blas_level2::blas_tbsv::ctbsv(), xtb_mctc_blas_level2::blas_tpmv::ctpmv(), xtb_mctc_blas_level2::blas_tpsv::ctpsv(), xtb_mctc_blas_level3::blas_trmm::ctrmm(), xtb_mctc_blas_level2::blas_trmv::ctrmv(), xtb_mctc_blas_level3::blas_trsm::ctrsm(), xtb_mctc_blas_level2::blas_trsv::ctrsv(), xtb_detrotra::detrotra4(), xtb_gfnff_fraghess::eigsort4::eigsort4(), eigsort4(), xtb_gfnff_fraghess::frag_hess_diag(), xtb_gfnff_fraghess::fragmentize(), xtb_gfnff_ini::gfnff_ini(), xtb_gfnff_eg::goed_gfnff(), xtb_mctc_blas_level1::blas_iamax::icamax(), xtb_local::irand3(), xtb_mctc_blas_level1::blas_iamax::isamax(), xtb_local::local(), xtb_mctc_blas_level1::blas_asum::sasum(), xtb_mctc_blas_level1::blas_axpy::saxpy(), xtb_mctc_blas_level1::blas_cabs1::scabs1(), xtb_mctc_blas_level1::blas_asum::scasum(), xtb_mctc_blas_level3::blas_gemm::scgemm(), xtb_mctc_blas_level2::blas_gemv::scgemv(), xtb_mctc_blas_level1::blas_nrm2::scnrm2(), xtb_mctc_blas_level1::blas_copy::scopy(), xtb_david2::sdavid2(), xtb_mctc_blas_level1::blas_dot::sdot(), xtb_mctc_blas_level2::blas_gbmv::sgbmv(), xtb_mctc_blas_level3::blas_gemm::sgemm(), xtb_mctc_blas_level2::blas_gemv::sgemv(), xtb_mctc_blas_level2::blas_ger::sger(), xtb_mctc_lapack_trf::lapack_getrf::sgetrf(), xtb_mctc_lapack_tri::lapack_getri::sgetri(), xtb_mctc_lapack_trs::lapack_getrs::sgetrs(), shortest_distance(), xtb_mctc_blas_level1::blas_nrm2::snrm2(), xtb_scc_core::solve4(), xtb_david2::solver_sdavidson(), xtb_mctc_lapack_trf::lapack_potrf::spotrf(), xtb_mctc_lapack_tri::lapack_potri::spotri(), xtb_mctc_lapack_trs::lapack_potrs::spotrs(), xtb_mctc_lapack_trf::lapack_pptrf::spptrf(), xtb_mctc_lapack_tri::lapack_pptri::spptri(), xtb_mctc_lapack_trs::lapack_pptrs::spptrs(), xtb_mctc_blas_level1::blas_rot::srot(), xtb_mctc_blas_level2::blas_sbmv::ssbmv(), xtb_mctc_blas_level1::blas_scal::sscal(), xtb_mctc_lapack_stdeigval::lapack_spev::sspev(), xtb_mctc_lapack_stdeigval::lapack_spevd::sspevd(), xtb_mctc_lapack_stdeigval::lapack_spevx::sspevx(), xtb_mctc_lapack_gst::lapack_spgst::sspgst(), xtb_mctc_lapack_geneigval::lapack_spgv::sspgv(), xtb_mctc_lapack_geneigval::lapack_spgvd::sspgvd(), xtb_mctc_lapack_geneigval::lapack_spgvx::sspgvx(), xtb_mctc_blas_level2::blas_spmv::sspmv(), xtb_mctc_blas_level2::blas_spr::sspr(), xtb_mctc_blas_level2::blas_spr2::sspr2(), xtb_mctc_lapack_trf::lapack_sptrf::ssptrf(), xtb_mctc_lapack_tri::lapack_sptri::ssptri(), xtb_mctc_lapack_trs::lapack_sptrs::ssptrs(), xtb_mctc_blas_level1::blas_swap::sswap(), xtb_mctc_lapack_stdeigval::lapack_syev::ssyev(), xtb_mctc_lapack_stdeigval::lapack_syevd::ssyevd(), xtb_mctc_lapack_stdeigval::lapack_syevr::ssyevr(), xtb_mctc_lapack_stdeigval::lapack_syevx::ssyevx(), xtb_mctc_lapack_gst::lapack_sygst::ssygst(), xtb_mctc_lapack_geneigval::lapack_sygv::ssygv(), xtb_mctc_lapack_geneigval::lapack_sygvd::ssygvd(), xtb_mctc_lapack_geneigval::lapack_sygvx::ssygvx(), xtb_mctc_blas_level3::blas_symm::ssymm(), xtb_mctc_blas_level2::blas_symv::ssymv(), xtb_mctc_blas_level2::blas_syr::ssyr(), xtb_mctc_blas_level2::blas_syr2::ssyr2(), xtb_mctc_blas_level3::blas_syr2k::ssyr2k(), xtb_mctc_blas_level3::blas_syrk::ssyrk(), xtb_mctc_lapack_trf::lapack_sytrf::ssytrf(), xtb_mctc_lapack_tri::lapack_sytri::ssytri(), xtb_mctc_lapack_trs::lapack_sytrs::ssytrs(), xtb_mctc_blas_level2::blas_tbmv::stbmv(), xtb_mctc_blas_level2::blas_tbsv::stbsv(), xtb_mctc_blas_level2::blas_tpmv::stpmv(), xtb_mctc_blas_level2::blas_tpsv::stpsv(), xtb_mctc_blas_level3::blas_trmm::strmm(), xtb_mctc_blas_level2::blas_trmv::strmv(), xtb_mctc_blas_level3::blas_trsm::strsm(), and xtb_mctc_blas_level2::blas_trsv::strsv().
wp
integer, parameter xtb_mctc_accuracy::wp = dp
Wanted precision.
Definition at line 31 of file accuracy.f90.
    integer, parameter :: wp = dp
Referenced by abcdisp(), xtb_type_solvation::addGradient::addgradient(), xtb_type_solvation::addShift::addshift(), xtb_type_molecule::align_to_principal_axes(), xtb_local::atomneigh(), xtb_basic_geo::bangl(), bangl(), xtb_intmodes::bangle(), xtb_bfgs::bfgs(), xtb_biaspath::bias_path(), xtb_blowsy::blowsy(), xtb_gfnff_ini2::bond_hbset(), xtb_gfnff_ini2::bond_hbset0(), xtb_intmodes::bonded(), xtb_broyden::broyden(), xtb_intmodes::bzmat(), calc_angles(), xtb_dipole::calc_dipole(), calc_distances(), calc_torsions(), xtb_local::calcrotation(), xtb_intmodes::cart2zmat(), xtb_type_molecule::center_of_geometry(), xtb_type_molecule::center_of_mass(), check_cold_fusion(), checksym(), checktype(), xtb_intmodes::cma(), com(), xtb_constrainpot::constrain_angle(), xtb_constrainpot::constrain_dihedral(), xtb_constrainpot::constrain_dist(), xtb_constrainpot::constrain_hess(), xtb_constrainpot::constrain_pos(), xtb_constrainpot::constrain_pot(), xtb_constrainpot::constrain_zaxis(), constrallangles(), constrallbonds(), constralltors(), constrhess(), constrpot(), countfix(), xtb_disp_coordinationnumber::countingFunction::countingfunction(), create_derfcn(), create_dlogcn(), create_erfcn(), create_logcn(), xtb_basic_geo::crossprod(), crossprod(), xtb_basic_geo::crprod(), crprod(), xtb_anharmlib::curveanal(), cutcov(), cutline(), xtb_disp_dftd4::d4(), xtb_intmodes::dang(), stm::densints(), xtb_detrotra::detrotra4(), xtb_detrotra::detrotra8(), dif(), xtb_intmodes::dihed(), xtb_dipole::dints(), xtb_hessian::distort(), xtb_gfnff_eg::dncoord_erf(), xtb_basic_geo::domegadr(), domegadr(), xtb_basic_geo::dphidr(), dphidr(), xtb_basic_geo::dthetadr(), dthetadr(), eigsort4(), enso_printout(), external_turbomole(), fixmetal(), xtb_gfnff_fraghess::frag_hess_diag(), xtb_gfnff_fraghess::fragmentize(), xtb_coulomb_klopmanohno::funcAverage::funcaverage(), g98fake(), gdisp(), xtb_type_anc::generate_anc_blowup(), xtb_type_anc::generate_anc_packed(), generate_wsc(), xtb_geoopt::geometry_optimization(), get_bonds(), xtb_type_anc::get_cartesian(), xtb_coffee::get_coffee(), get_dc6_dcnij(), getc6(), xtb_type_solvation::getEnergy::getenergy(), getgen(), xtb_coulomb_ewald::getGTermGen::getgtermgen(), xtb_thermo::getsymmetry(), getsymnum(), xtb_chargemodel::gfn0_charge_model(), gfn0_prparam(), gfn1_prparam(), gfn2_prparam(), xtb_gfnff_eg::gfnff_dlogcoord(), xtb_gfnff_eg::gfnff_eg(), xtb_gfnff_ini2::gfnff_hbset(), xtb_gfnff_ini2::gfnff_hbset0(), xtb_gfnff_ini::gfnff_ini(), xtb_gfnff_setup::gfnff_input(), xtb_gfnff_param::gfnff_load_param(), xtb_gfnff_param::gfnff_param_alloc(), xtb_gfnff_param::gfnff_param_dealloc(), xtb_gfnff_param::gfnff_read_param(), xtb_gfnff_param::gfnff_set_param(), gfnffqmsolve(), xtb_intmodes::gmetry(), xtb_gfnff_eg::goed_gfnff(), xtb_gfnff_ini2::goedeckera(), grdsym(), group(), grpsmb(), xtb_biaspath::guess_tsmode(), xtb_constrain_param::handlerInterface::handlerinterface(), xtb_bfgs::hdamp(), xtb_hlex::hlex(), xtb_basic_geo::impsc(), impsc(), xtb_iniq::iniqcn_gfn1(), xtb_iniq::iniqcn_gfn2(), xtb_iniq::iniqcn_vtb(), xtb_intmodes::intmodestep(), xtb_local::lmotype(), xtb_metadynamic::load_metadynamic(), xtb_metadynamic::load_rmsdbias(), xtb_local::local(), locmode(), lopt(), main_geometry(), main_json(), xtb_intmodes::makenabc(), xtb_broyden::matinv(), xtb_dynamic::md(), xtb_biaspath::metadyn_tsmode(), xtb_metadynamic::metadynamic(), xtb_modef::modefollow(), xtb_intmodes::modetyp(), xtb_type_molecule::mol_calculate_distances(), xtb_type_molecule::mol_set_atomic_masses(), xtb_type_molecule::mol_set_nuclear_charge(), xtb_type_molecule::molecular_mass(), xtb_type_molecule::moments_of_inertia(), mrec(), mult3(), neighbor(), neighborh(), neighborhi(), neighbours(), xtb_chargemodel::new_charge_model_2018(), xtb_chargemodel::new_charge_model_2019(), xtb_chargemodel::new_multieq_model_2019(), nucex(), xtb_hessian::numhess(), xtb_hessian::numhess_rmsd(), xtb_intpack::olap(), xtb_thermo::oldthermo(), xtb_basic_geo::omega(), omega(), outg(), peeq_tester(), xtb_local::piorient(), xtb_bfgs::powell(), preig(), preig2(), prgemat(), print_angles(), print_distances(), print_elem_dist(), print_geosum(), print_moments(), print_orbital_eigenvalues(), print_pbcsum(), print_torsions(), prob_module::prob_func(), prob_module::prob_metadynamic(), prsymat(), prtime(), xtb_constrainpot::qpothess2(), qpotini(), qqsort(), qsort(), rattle(), rdatomnumber(), rdcoord(), rdfix(), rdsdf(), rdtm(), rdxyz(), xtb_chargemodel::read_charge_model(), readaa(), readl(), readline(), xtb_io_reader_gaussian::readmoleculegaussianexternal(), xtb_readparam::readparam(), xtb_scan::relaxed_scan(), xtb_type_molecule::rotational_constants(), xtb_hessian::rotmol(), rsp(), xtb_biaspath::screenpath(), xtb_david2::sdavid2(), xtb_paramset::set_gfn0_parameter(), xtb_paramset::set_gfn2_parameter(), xtb_metadynamic::set_metadynamic(), setr0ab(), xtb_printout::setup_summary(), xtb_type_molecule::shift_to_center_of_geometry(), xtb_type_molecule::shift_to_center_of_mass(), shiftlp(), xtb_gfnff_fraghess::shortest_distance::shortest_distance(), shortest_distance(), xtb_type_calculator::singlepoint::singlepoint(), xtb_xtb_eeq::solve::solve(), xtb_david2::solver_sdavidson(), stm::stmpic(), xtb_gfnff_convert::struc_convert(), surfac(), symmetry(), symtrans(), test_atomlist(), test_axis(), test_class_molecule_axis_trafo(), test_class_molecule_mic_distances(), test_coulomb_gaussian_cluster(), test_coulomb_gaussian_pbc3d(), test_coulomb_gfn1_cluster(), test_coulomb_gfn1_pbc3d(), test_coulomb_gfn2_cluster(), test_coulomb_gfn2_pbc3d(), test_coulomb_point_cluster(), test_coulomb_point_pbc3d(), test_dftd3_pbc3d_latticepoints(), test_dftd3_pbc3d_neighbourlist(), test_dftd3_pbc3d_threebody_latp(), test_dftd3_pbc3d_threebody_neighs(), test_dftd4_pbc3d_latticepoints(), test_dftd4_pbc3d_neighbourlist(), test_dftd4_pbc3d_threebody_latp(), test_dftd4_pbc3d_threebody_neighs(), test_eeq_ewald(), test_eeq_model_gbsa(), test_eeq_model_hbond(), test_eeq_model_salt(), test_eeq_water(), test_geometry_reader_file_coord_c_1d(), test_geometry_reader_file_coord_c_2d(), test_geometry_reader_file_coord_caf2_3d(), test_geometry_reader_file_coord_camgco_3d(), test_geometry_reader_file_coord_general_0d(), test_geometry_reader_file_gen(), test_geometry_reader_file_pdb_4qxx(), test_geometry_reader_file_pdb_4qxx_noh(), test_geometry_reader_file_poscar_sio2_3d(), test_geometry_reader_file_sdf_benzen_hquery(), test_geometry_reader_file_sdf_h2o(), test_geometry_reader_file_sdf_h2o_flat(), test_geometry_reader_file_xmol_water_0d(), test_geometry_reader_molfile_benzen(), test_geometry_reader_molfile_benzen_flat(), test_gfn0_api(), test_gfn0_api_srb(), test_gfn0_mindless_basic(), test_gfn0_mindless_solvation(), test_gfn0_sp(), test_gfn1_api(), test_gfn1_mindless_basic(), test_gfn1_mindless_solvation(), test_gfn1_pbc3d(), test_gfn1_pcem_api(), test_gfn1_scc(), test_gfn1_xb(), test_gfn1gbsa_api(), test_gfn2_api(), test_gfn2_dmetal(), test_gfn2_mindless_basic(), test_gfn2_mindless_solvation(), test_gfn2_pcem_api(), test_gfn2_scc(), test_gfn2gbsa_api(), test_gfn2salt_api(), test_gfnff_gbsa(), test_gfnff_hb(), test_gfnff_mindless_basic(), test_gfnff_mindless_solvation(), test_gfnff_pdb(), test_gfnff_scaleup(), test_gfnff_sdf(), test_gfnff_sp(), test_ipea_indole(), test_latticepoint_pbc3d(), test_ncoord_pbc3d_latticepoints(), test_ncoord_pbc3d_neighbourlist(), test_pbc_lancopt(), test_pbc_tools_convert(), test_pbc_tools_cutoff(), test_peeq_api(), test_peeq_api_srb(), test_peeq_sp(), test_print_thermo(), test_repulsion_cluster(), test_repulsion_pbc3d(), test_symmetry_c20(), test_symmetry_li8(), test_symmetry_pcl3(), test_symmetry_water(), test_thermo_calc(), test_wigner_seitz_0d(), test_wigner_seitz_3d(), xtb_thermo::thermodyn(), timing(), xtb_mctc_timings::timing(), xtb_type_molecule::update(), xtb_type_solvation::update::update(), xtb_basic_geo::valijk(), valijk(), xtb_basic_geo::valijkl(), valijkl(), xtb_basic_geo::vecnorm(), vecnorm(), xtb_basic_geo::vsc1(), vsc1(), xtb_type_molecule::wrap_back(), wrgbw(), write_tm_basis(), write_tm_mos(), xtb_printout::writecosmofile(), wrmodef(), wrtm(), xtb_prog_info::xtbinfo(), xtb_prog_main::xtbmain(), xtb_intmodes::xyzgeo(), xtb_intmodes::xyzint(), xtb_intmodes::zmat2cart(), and zmatpr().