My Project: xtb_xtb_data Module Reference
xtb_xtb_data Module Reference
Parametrisation data for xTB methods.
Data Types
interface newdata
interface getdata
type tdispersiondata
Data for the dispersion contribution.
type trepulsiondata
Data for the repulsion contribution.
type thamiltoniandata
Data for the evaluation of the xTB core Hamiltonian.
type tcoulombdata
Data for the evalutation of the Coulomb interactions.
type tmultipoledata
Data for the evaluation of the multipole electrostatics.
type thalogendata
Data for halogen bond correction.
type tshortrangedata
Short range basis correction.
type txtbdata
Parametrisation data for the xTB method.
interface init
Default constructor for the data types.
Functions/Subroutines
subroutine writeinfo (self, unit, num)
subroutine, public generatevalenceshelldata (valenceShell, nShell, angShell)
Generator for valence shell data from the angular momenta of the shells.
subroutine inithalogen (self, radScale, dampingPar, halogenBond)
Initialize halogen bond data.
subroutine initmultipole (self, cnShift, cnExp, cnRMax, dipDamp, quadDamp, dipKernel, quadKernel)
subroutine initrepulsion (self, kExp, kExpLight, rExp, enScale, alpha, zeff, electronegativity)
subroutine initcoulomb (self, nShell, chemicalHardness, shellHardness, thirdOrderAtom, electronegativity, kCN, chargeWidth)
subroutine, public angtoshelldata (kDat, nShell, angShell, angDat)
Transform a data array from angular momenta to shell number references.
subroutine newatomicdata (vec, num, data)
subroutine getatomicdata (vec, num, data)
subroutine newshelldata (vec, num, nshell, data)
subroutine getshelldata (vec, num, nshell, data)
Variables
real(wp), dimension(1:118), parameter valencecn = [ 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 2.0_wp, 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 4.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, 4.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 4.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, 4.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, 4.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp]
Valence coordination number for radii.
real(wp), dimension(1:118), parameter multirad = [ 1.4_wp, 3.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 3.0_wp, 1.9_wp, 1.8_wp, 2.4_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 3.9_wp, 2.1_wp, 3.1_wp, 2.5_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 3.9_wp, 4.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp]
Cutoff radii for multipole electrostatics.
Detailed Description
Parametrisation data for xTB methods.
Function/Subroutine Documentation
angtoshelldata()
subroutine, public xtb_xtb_data::angtoshelldata (real(wp), dimension(:, :), intent(out) kDat, integer, dimension(:), intent(in) nShell, integer, dimension(:, :), intent(in) angShell, real(wp), dimension(0:, :), intent(in) angDat)
Transform a data array from angular momenta to shell number references.
Parameters
[out] kdat Data in terms of shell number of each species
[in] nshell Number of shells for each species
[in] angshell Angular momenta of each shell
[in] angdat Data in terms of angular momenta of each shell
Definition at line 676 of file data.f90.
    real(wp), intent(out) :: kDat(:, :)
    integer, intent(in) :: nShell(:)
    integer, intent(in) :: angShell(:, :)
    real(wp), intent(in) :: angDat(0:, :)
    integer :: nElem, iZp, iSh, lAng, iKind
    nelem = min(size(kdat, dim=2), size(nshell), size(angshell, dim=2), &
       & size(angdat, dim=2))
    kdat(:, :) = 0.0_wp
    do izp = 1, nelem
       do ish = 1, nshell(izp)
          lang = angshell(ish, izp)
          kdat(ish, izp) = angdat(lang, izp)
       end do
    end do
Referenced by xtb_xtb_gfn0::initgfn0::inithamiltonian(), xtb_xtb_gfn2::initgfn2::inithamiltonian(), and xtb_readparam::readparam().
generatevalenceshelldata()
subroutine, public xtb_xtb_data::generatevalenceshelldata (integer, dimension(:, :), intent(out) valenceShell, integer, dimension(:), intent(in) nShell, integer, dimension(:, :), intent(in) angShell)
Generator for valence shell data from the angular momenta of the shells.
Parameters
[out] valenceshell Valency character of each shell
[in] nshell Number of shells for each atom
[in] angshell Angular momenta of each shell
Definition at line 469 of file data.f90.
    integer, intent(out) :: valenceShell(:, :)
    integer, intent(in) :: nShell(:)
    integer, intent(in) :: angShell(:, :)
    integer :: lAng, iZp, iSh
    logical :: valShell(0:3)
    valenceshell(:, :) = 0
    do izp = 1, size(nshell, dim=1)
       valshell(:) = .true.
       do ish = 1, nshell(izp)
          lang = angshell(ish, izp)
          if (valshell(lang)) then
             valshell(lang) = .false.
             valenceshell(ish, izp) = 1
          end if
       end do
    end do
References true().
Referenced by xtb_xtb_gfn0::initgfn0::inithamiltonian(), xtb_xtb_gfn1::initgfn1::inithamiltonian(), xtb_xtb_gfn2::initgfn2::inithamiltonian(), and xtb_readparam::readparam().
getatomicdata()
subroutine xtb_xtb_data::getatomicdata (real(wp), dimension(:), intent(out) vec, integer, dimension(:), intent(in) num, real(wp), dimension(:), intent(in) data) private
Definition at line 720 of file data.f90.
    real(wp), intent(out) :: vec(:)
    integer, intent(in) :: num(:)
    real(wp), intent(in) :: data(:)
    integer :: ii, izp
    do ii = 1, size(vec, dim=1)
       izp = num(ii)
       vec(ii) = data(izp)
    end do
Referenced by xtb_xtb_data::newdata::newatomicdata().
getshelldata()
subroutine xtb_xtb_data::getshelldata (real(wp), dimension(:, :), intent(out) vec, integer, dimension(:), intent(in) num, integer, dimension(:), intent(in) nshell, real(wp), dimension(:, :), intent(in) data) private
Definition at line 754 of file data.f90.
    real(wp), intent(out) :: vec(:, :)
    integer, intent(in) :: num(:)
    integer, intent(in) :: nshell(:)
    real(wp), intent(in) :: data(:, :)
    integer :: ii, ish, izp
    vec(:, :) = 0.0_wp
    do ii = 1, size(vec, dim=2)
       izp = num(ii)
       do ish = 1, nshell(izp)
          vec(ish, ii) = data(ish, izp)
       end do
    end do
Referenced by xtb_xtb_data::newdata::newshelldata().
initcoulomb()
subroutine xtb_xtb_data::initcoulomb (type(tcoulombdata), intent(out) self, integer, dimension(:), intent(in) nShell, real(wp), dimension(:), intent(in) chemicalHardness, real(wp), dimension(:, :), intent(in), optional shellHardness, real(wp), dimension(:), intent(in), optional thirdOrderAtom, real(wp), dimension(:), intent(in), optional electronegativity, real(wp), dimension(:), intent(in), optional kCN, real(wp), dimension(:), intent(in), optional chargeWidth) private
Parameters
[out] self Data instance
Definition at line 619 of file data.f90.
    type(TCoulombData), intent(out) :: self
    integer, intent(in) :: nShell(:)
    real(wp), intent(in) :: chemicalHardness(:)
    real(wp), intent(in), optional :: shellHardness(:, :)
    real(wp), intent(in), optional :: thirdOrderAtom(:)
    real(wp), intent(in), optional :: electronegativity(:)
    real(wp), intent(in), optional :: kCN(:)
    real(wp), intent(in), optional :: chargeWidth(:)
    integer :: maxElem
    maxelem = size(chemicalhardness)
    if (present(shellhardness)) then
       maxelem = min(maxelem, size(shellhardness, dim=2))
    end if
    if (present(thirdorderatom)) then
       maxelem = min(maxelem, size(thirdorderatom))
    end if
    if (present(electronegativity).and.present(kcn).and.present(chargewidth)) then
       maxelem = min(maxelem, size(electronegativity), size(kcn), size(chargewidth))
    end if
    self%chemicalHardness = chemicalhardness(:maxelem)
    if (present(shellhardness)) then
       self%shellHardness = shellhardness(:, :maxelem)
    end if
    if (present(thirdorderatom)) then
       self%thirdOrderAtom = thirdorderatom(:maxelem)
    end if
    if (present(electronegativity).and.present(kcn).and.present(chargewidth)) then
       self%electronegativity = electronegativity(:maxelem)
       self%kCN = kcn(:maxelem)
       self%chargeWidth = chargewidth(:maxelem)
    end if
inithalogen()
subroutine xtb_xtb_data::inithalogen (type(thalogendata), intent(out) self, real(wp), intent(in) radScale, real(wp), intent(in) dampingPar, real(wp), dimension(:), intent(in) halogenBond) private
Initialize halogen bond data.
Parameters
[out] self Data instance
[in] radscale Scaling parameter for the atomic radii
[in] dampingpar Damping parameter
[in] halogenbond Halogen bond strength
Definition at line 499 of file data.f90.
    type(THalogenData), intent(out) :: self
    real(wp), intent(in) :: radScale
    real(wp), intent(in) :: dampingPar
    real(wp), intent(in) :: halogenBond(:)
    integer :: maxElem
    maxelem = size(halogenbond)
    self%radScale = radscale
    self%dampingPar = dampingpar
    self%atomicRad = atomicrad(:maxelem)
    self%bondStrength = halogenbond(:maxelem)
initmultipole()
subroutine xtb_xtb_data::initmultipole (type(tmultipoledata), intent(out) self, real(wp), intent(in) cnShift, real(wp), intent(in) cnExp, real(wp), intent(in) cnRMax, real(wp), intent(in) dipDamp, real(wp), intent(in) quadDamp, real(wp), dimension(:), intent(in) dipKernel, real(wp), dimension(:), intent(in) quadKernel) private
Parameters
[out] self Data instance
Definition at line 525 of file data.f90.
    type(TMultipoleData), intent(out) :: self
    real(wp), intent(in) :: cnShift
    real(wp), intent(in) :: cnExp
    real(wp), intent(in) :: cnRMax
    real(wp), intent(in) :: dipDamp
    real(wp), intent(in) :: quadDamp
    real(wp), intent(in) :: dipKernel(:)
    real(wp), intent(in) :: quadKernel(:)
    integer :: maxElem
    maxelem = min(size(dipkernel), size(quadkernel))
    self%cnShift = cnshift
    self%cnExp = cnexp
    self%cnRMax = cnrmax
    self%dipDamp = dipdamp
    self%quadDamp = quaddamp
    self%dipKernel = dipkernel(:maxelem)
    self%quadKernel = quadkernel(:maxelem)
    self%valenceCN = valencecn(:maxelem)
    self%multiRad = multirad(:maxelem)
initrepulsion()
subroutine xtb_xtb_data::initrepulsion (type(trepulsiondata), intent(out) self, real(wp), intent(in) kExp, real(wp), intent(in) kExpLight, real(wp), intent(in) rExp, real(wp), intent(in) enScale, real(wp), dimension(:), intent(in) alpha, real(wp), dimension(:), intent(in) zeff, real(wp), dimension(:), intent(in), optional electronegativity) private
Parameters
[out] self Data instance
Definition at line 569 of file data.f90.
    type(TRepulsionData), intent(out) :: self
    real(wp), intent(in) :: kExp
    real(wp), intent(in) :: kExpLight
    real(wp), intent(in) :: rExp
    real(wp), intent(in) :: enScale
    real(wp), intent(in) :: alpha(:)
    real(wp), intent(in) :: zeff(:)
    real(wp), intent(in), optional :: electronegativity(:)
    integer :: maxElem
    maxelem = min(size(alpha), size(zeff))
    if (present(electronegativity)) then
       maxelem = min(maxelem, size(electronegativity))
    end if
    self%cutoff = 40.0_wp
    self%kExp = kexp
    self%kExpLight = kexplight
    self%rExp = rexp
    self%enScale = enscale
    self%alpha = alpha(:maxelem)
    self%zeff = zeff(:maxelem)
    if (present(electronegativity)) then
       self%electronegativity = electronegativity(:maxelem)
    else
       self%electronegativity = paulingen(:maxelem)
    end if
newatomicdata()
subroutine xtb_xtb_data::newatomicdata (real(wp), dimension(:), intent(out), allocatable vec, integer, dimension(:), intent(in) num, real(wp), dimension(:), intent(in) data) private
Definition at line 706 of file data.f90.
    real(wp), allocatable, intent(out) :: vec(:)
    integer, intent(in) :: num(:)
    real(wp), intent(in) :: data(:)
    allocate(vec(size(num)))
    call getatomicdata(vec, num, data)
newshelldata()
subroutine xtb_xtb_data::newshelldata (real(wp), dimension(:, :), intent(out), allocatable vec, integer, dimension(:), intent(in) num, integer, dimension(:), intent(in) nshell, real(wp), dimension(:, :), intent(in) data) private
Definition at line 738 of file data.f90.
    real(wp), allocatable, intent(out) :: vec(:, :)
    integer, intent(in) :: num(:)
    integer, intent(in) :: nshell(:)
    real(wp), intent(in) :: data(:, :)
    allocate(vec(maxval(nshell), size(num)))
    call getshelldata(vec, num, nshell, data)
writeinfo()
subroutine xtb_xtb_data::writeinfo (class(txtbdata), intent(in) self, integer, intent(in) unit, integer, dimension(:), intent(in), optional num) private
Parameters
[in] self Instance of the parametrisation data
[in] unit Unit for I/O
[in] num Atomic numbers
Definition at line 368 of file data.f90.
    class(TxTBData), intent(in) :: self
    integer, intent(in) :: unit
    integer, intent(in), optional :: num(:)
    character(len=*), parameter :: rnum = '(f12.6)'
    character(len=*), parameter :: offset = '(8x)'
    character(len=*), parameter :: head = '(6x,"*",1x,a,":")'
    character(len=*), parameter :: rfmt = '('//offset//',a,t36,'//rnum//')'
    character(len=*), parameter :: afmt = '('//offset//',a,t36,4x,a)'
    character(len=:), allocatable :: name
    integer :: ii, jj
    write(unit, '(a)')
    if (allocated(self%name)) then
       allocate(character(len=2*len(self%name)-1) :: name)
       name = repeat(' ', len(name))
       do ii = 1, len(self%name)
          jj = 2*ii-1
          name(jj:jj) = self%name(ii:ii)
       end do
    else
       name = repeat(' ', 10)
       write(name, '(i0)') self%level
       name = 'xTB level '//trim(name)
    end if
    call generic_header(unit, name, 49, 10)
    write(unit, '(a)')
    if (allocated(self%doi)) then
       write(unit, afmt) "Reference", self%doi
    end if
    write(unit, head) "Hamiltonian"
    write(unit, rfmt, advance='no') "H0-scaling (s, p, d)"
    do ii = 0, 2
       write(unit, rnum, advance='no') self%hamiltonian%kScale(ii, ii)
    end do
    write(unit, '(a)')
    write(unit, rfmt) "zeta-weighting", self%hamiltonian%wExp
    write(unit, head) "Dispersion"
    write(unit, rfmt) "s8", self%dispersion%dpar%s8
    write(unit, rfmt) "a1", self%dispersion%dpar%a1
    write(unit, rfmt) "a2", self%dispersion%dpar%a2
    write(unit, rfmt) "s9", self%dispersion%dpar%s9
    write(unit, head) "Repulsion"
    write(unit, rfmt, advance='no') "kExp", self%repulsion%kExp
    if (self%repulsion%kExpLight /= self%repulsion%kExp) then
       write(unit, rnum, advance='no') self%repulsion%kExpLight
    end if
    write(unit, '(a)')
    write(unit, rfmt) "rExp", self%repulsion%rExp
    write(unit, head) "Coulomb"
    write(unit, rfmt) "alpha", self%coulomb%gExp
    if (allocated(self%coulomb%thirdOrderShell)) then
       write(unit, afmt) "third order", "shell-resolved"
    else if (allocated(self%coulomb%thirdOrderAtom)) then
       write(unit, afmt) "third order", "atomic"
    else
       write(unit, afmt) "third order", "false"
    end if
    if (allocated(self%multipole)) then
       write(unit, afmt) "anisotropic", "true"
       write(unit, rfmt) "a3", self%multipole%dipDamp
       write(unit, rfmt) "a5", self%multipole%quadDamp
       write(unit, rfmt) "cn-shift", self%multipole%cnShift
       write(unit, rfmt) "cn-exp", self%multipole%cnExp
       write(unit, rfmt) "max-rad", self%multipole%cnRMax
    else
       write(unit, afmt) "anisotropic", "false"
    end if
    if (allocated(self%halogen)) then
       write(unit, head) "Halogen bond correction"
       write(unit, rfmt) "rad-scale", self%halogen%radScale
       write(unit, rfmt) "damping", self%halogen%dampingPar
    end if
    if (allocated(self%srb)) then
       write(unit, head) "Polar bond correction"
       write(unit, rfmt) "rad-shift", self%srb%shift
       write(unit, rfmt) "strength", self%srb%prefactor
       write(unit, rfmt) "en-exp", self%srb%steepness
       write(unit, rfmt) "en-scale", self%srb%enScale
    end if
    write(unit, '(a)')
References generic_header().
Variable Documentation
multirad
real(wp), dimension(1:118), parameter xtb_xtb_data::multirad = [ 1.4_wp, 3.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 3.0_wp, 1.9_wp, 1.8_wp, 2.4_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 3.9_wp, 2.1_wp, 3.1_wp, 2.5_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 3.9_wp, 4.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp] private
Cutoff radii for multipole electrostatics.
Definition at line 348 of file data.f90.
    real(wp), parameter :: multiRad(1:118) = [&
       & 1.4_wp, 3.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 3.0_wp, 1.9_wp, 1.8_wp, 2.4_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 3.9_wp, 2.1_wp, 3.1_wp, 2.5_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 3.9_wp, 4.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, 5.0_wp, &
       & 5.0_wp]
Referenced by xtb_xtb_data::init::initmultipole().
valencecn
real(wp), dimension(1:118), parameter xtb_xtb_data::valencecn = [ 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 2.0_wp, 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 4.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, 4.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 4.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, 4.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, 4.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp] private
Valence coordination number for radii.
Definition at line 331 of file data.f90.
    real(wp), parameter :: valenceCN(1:118) = [&
       & 1.0_wp, 1.0_wp, 1.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 2.0_wp, 1.0_wp, &
       & 1.0_wp, 1.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, &
       & 1.0_wp, 2.0_wp, 4.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, &
       & 4.0_wp, 4.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, &
       & 1.0_wp, 2.0_wp, 4.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, &
       & 4.0_wp, 4.0_wp, 2.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, &
       & 1.0_wp, 2.0_wp, 4.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, &
       & 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, &
       & 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 6.0_wp, 4.0_wp, 4.0_wp, 2.0_wp, 3.0_wp, &
       & 3.0_wp, 3.0_wp, 3.0_wp, 1.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
       & 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
       & 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
       & 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, &
       & 0.0_wp]
Referenced by xtb_xtb_data::init::initmultipole().