My Project: xtb_param_covalentradd3 Module Reference
xtb_param_covalentradd3 Module Reference
DFT-D3 Covalent radii for coordination number.
Data Types
interface getcovalentradd3
Get atomic radius for a species.
Functions/Subroutines
elemental real(wp) function getcovalentradd3symbol (symbol)
Get covalent radius for species with a given symbol.
elemental real(wp) function getcovalentradd3number (number)
Get covalent radius for species with a given atomic number.
Variables
real(wp), dimension(1:118), parameter, public covalentradd3 = [ 0.32_wp,0.46_wp, 1.20_wp,0.94_wp,0.77_wp,0.75_wp,0.71_wp,0.63_wp,0.64_wp,0.67_wp, 1.40_wp,1.25_wp,1.13_wp,1.04_wp,1.10_wp,1.02_wp,0.99_wp,0.96_wp, 1.76_wp,1.54_wp, 1.33_wp,1.22_wp,1.21_wp,1.10_wp,1.07_wp, 1.04_wp,1.00_wp,0.99_wp,1.01_wp,1.09_wp, 1.12_wp,1.09_wp,1.15_wp,1.10_wp,1.14_wp,1.17_wp, 1.89_wp,1.67_wp, 1.47_wp,1.39_wp,1.32_wp,1.24_wp,1.15_wp, 1.13_wp,1.13_wp,1.08_wp,1.15_wp,1.23_wp, 1.28_wp,1.26_wp,1.26_wp,1.23_wp,1.32_wp,1.31_wp, 2.09_wp,1.76_wp, 1.62_wp,1.47_wp,1.58_wp,1.57_wp,1.56_wp,1.55_wp,1.51_wp, 1.52_wp,1.51_wp,1.50_wp,1.49_wp,1.49_wp,1.48_wp,1.53_wp, 1.46_wp,1.37_wp,1.31_wp,1.23_wp,1.18_wp, 1.16_wp,1.11_wp,1.12_wp,1.13_wp,1.32_wp, 1.30_wp,1.30_wp,1.36_wp,1.31_wp,1.38_wp,1.42_wp, 2.01_wp,1.81_wp, 1.67_wp,1.58_wp,1.52_wp,1.53_wp,1.54_wp,1.55_wp,1.49_wp, 1.49_wp,1.51_wp,1.51_wp,1.48_wp,1.50_wp,1.56_wp,1.58_wp, 1.45_wp,1.41_wp,1.34_wp,1.29_wp,1.27_wp, 1.21_wp,1.16_wp,1.15_wp,1.09_wp,1.22_wp, 1.36_wp,1.43_wp,1.46_wp,1.58_wp,1.48_wp,1.57_wp] * aatoau * 4.0_wp / 3.0_wp
Covalent radii (taken from Pyykko and Atsumi, Chem. Eur. J. 15, 2009, 188-197), values for metals decreased by 10%.
Detailed Description
DFT-D3 Covalent radii for coordination number.
Function/Subroutine Documentation
getcovalentradd3number()
elemental real(wp) function xtb_param_covalentradd3::getcovalentradd3number (integer, intent(in) number) private
Get covalent radius for species with a given atomic number.
Parameters
[in] number Atomic number
Returns
atomic radius
Definition at line 83 of file covalentradd3.f90.
    integer, intent(in) :: number
    real(wp) :: rad
    if (number > 0 .and. number <= size(covalentradd3, dim=1)) then
       rad = covalentradd3(number)
    else
       rad = -1.0_wp
    end if
getcovalentradd3symbol()
elemental real(wp) function xtb_param_covalentradd3::getcovalentradd3symbol (character(len=*), intent(in) symbol) private
Get covalent radius for species with a given symbol.
Parameters
[in] symbol Element symbol
Returns
atomic radius
Definition at line 69 of file covalentradd3.f90.
    character(len=*), intent(in) :: symbol
    real(wp) :: rad
    rad = getcovalentradd3(tonumber(symbol))
Variable Documentation
covalentradd3
real(wp), dimension(1:118), parameter, public xtb_param_covalentradd3::covalentradd3 = [ 0.32_wp,0.46_wp, 1.20_wp,0.94_wp,0.77_wp,0.75_wp,0.71_wp,0.63_wp,0.64_wp,0.67_wp, 1.40_wp,1.25_wp,1.13_wp,1.04_wp,1.10_wp,1.02_wp,0.99_wp,0.96_wp, 1.76_wp,1.54_wp, 1.33_wp,1.22_wp,1.21_wp,1.10_wp,1.07_wp, 1.04_wp,1.00_wp,0.99_wp,1.01_wp,1.09_wp, 1.12_wp,1.09_wp,1.15_wp,1.10_wp,1.14_wp,1.17_wp, 1.89_wp,1.67_wp, 1.47_wp,1.39_wp,1.32_wp,1.24_wp,1.15_wp, 1.13_wp,1.13_wp,1.08_wp,1.15_wp,1.23_wp, 1.28_wp,1.26_wp,1.26_wp,1.23_wp,1.32_wp,1.31_wp, 2.09_wp,1.76_wp, 1.62_wp,1.47_wp,1.58_wp,1.57_wp,1.56_wp,1.55_wp,1.51_wp, 1.52_wp,1.51_wp,1.50_wp,1.49_wp,1.49_wp,1.48_wp,1.53_wp, 1.46_wp,1.37_wp,1.31_wp,1.23_wp,1.18_wp, 1.16_wp,1.11_wp,1.12_wp,1.13_wp,1.32_wp, 1.30_wp,1.30_wp,1.36_wp,1.31_wp,1.38_wp,1.42_wp, 2.01_wp,1.81_wp, 1.67_wp,1.58_wp,1.52_wp,1.53_wp,1.54_wp,1.55_wp,1.49_wp, 1.49_wp,1.51_wp,1.51_wp,1.48_wp,1.50_wp,1.56_wp,1.58_wp, 1.45_wp,1.41_wp,1.34_wp,1.29_wp,1.27_wp, 1.21_wp,1.16_wp,1.15_wp,1.09_wp,1.22_wp, 1.36_wp,1.43_wp,1.46_wp,1.58_wp,1.48_wp,1.57_wp] * aatoau * 4.0_wp / 3.0_wp
Covalent radii (taken from Pyykko and Atsumi, Chem. Eur. J. 15, 2009, 188-197), values for metals decreased by 10%.
Definition at line 38 of file covalentradd3.f90.
    real(wp), parameter :: covalentRadD3(1:118) = [ &
       & 0.32_wp,0.46_wp, & ! H,He
       & 1.20_wp,0.94_wp,0.77_wp,0.75_wp,0.71_wp,0.63_wp,0.64_wp,0.67_wp, & ! Li-Ne
       & 1.40_wp,1.25_wp,1.13_wp,1.04_wp,1.10_wp,1.02_wp,0.99_wp,0.96_wp, & ! Na-Ar
       & 1.76_wp,1.54_wp, & ! K,Ca
       &                 1.33_wp,1.22_wp,1.21_wp,1.10_wp,1.07_wp, & ! Sc-
       &                 1.04_wp,1.00_wp,0.99_wp,1.01_wp,1.09_wp, & ! -Zn
       &                 1.12_wp,1.09_wp,1.15_wp,1.10_wp,1.14_wp,1.17_wp, & ! Ga-Kr
       & 1.89_wp,1.67_wp, & ! Rb,Sr
       &                 1.47_wp,1.39_wp,1.32_wp,1.24_wp,1.15_wp, & ! Y-
       &                 1.13_wp,1.13_wp,1.08_wp,1.15_wp,1.23_wp, & ! -Cd
       &                 1.28_wp,1.26_wp,1.26_wp,1.23_wp,1.32_wp,1.31_wp, & ! In-Xe
       & 2.09_wp,1.76_wp, & ! Cs,Ba
       &         1.62_wp,1.47_wp,1.58_wp,1.57_wp,1.56_wp,1.55_wp,1.51_wp, & ! La-Eu
       &         1.52_wp,1.51_wp,1.50_wp,1.49_wp,1.49_wp,1.48_wp,1.53_wp, & ! Gd-Yb
       &                 1.46_wp,1.37_wp,1.31_wp,1.23_wp,1.18_wp, & ! Lu-
       &                 1.16_wp,1.11_wp,1.12_wp,1.13_wp,1.32_wp, & ! -Hg
       &                 1.30_wp,1.30_wp,1.36_wp,1.31_wp,1.38_wp,1.42_wp, & ! Tl-Rn
       & 2.01_wp,1.81_wp, & ! Fr,Ra
       &         1.67_wp,1.58_wp,1.52_wp,1.53_wp,1.54_wp,1.55_wp,1.49_wp, & ! Ac-Am
       &         1.49_wp,1.51_wp,1.51_wp,1.48_wp,1.50_wp,1.56_wp,1.58_wp, & ! Cm-No
       &                 1.45_wp,1.41_wp,1.34_wp,1.29_wp,1.27_wp, & ! Lr-
       &                 1.21_wp,1.16_wp,1.15_wp,1.09_wp,1.22_wp, & ! -Cn
       &                 1.36_wp,1.43_wp,1.46_wp,1.58_wp,1.48_wp,1.57_wp] & ! Nh-Og
       & * aatoau * 4.0_wp / 3.0_wp
Referenced by xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp(), xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl(), xtb_param_covalentradd3::getcovalentradd3::getcovalentradd3number(), xtb_gfnff_param::gfnff_load_param(), and xtb_gfnff_param::gfnff_read_param().