My Project: xtb_coulomb_gaussian Module Reference
xtb_coulomb_gaussian Module Reference
TODO.
Data Types
type tgaussiansmeared
interface init
Functions/Subroutines
subroutine initfrommolecule (self, env, mol, rad, num, nshell, alpha, tolerance)
subroutine initgaussiansmeared (self, env, id, lattice, boundaryCond, rad, num, nshell, alpha, tolerance)
subroutine getcoulombmatrix (self, mol, jmat)
subroutine getcoulombmatrixcluster (mol, itbl, rad, jmat)
subroutine getcoulombmatrixpbc3d (wsCell, id, itbl, rad, alpha, volume, rTrans, gTrans, jmat)
pure real(wp) function getrterm (vec, gam, rTrans, alpha, scale)
subroutine getcoulombderivs (self, mol, qvec, djdr, djdtr, djdL)
subroutine getcoulombderivscluster (mol, itbl, rad, qvec, djdr, djdtr, djdL)
subroutine getcoulombderivspbc3d (wsCell, id, itbl, rad, alpha, volume, rTrans, gTrans, qvec, djdr, djdtr, djdL)
pure subroutine getrderiv (vec, gij, rTrans, alpha, scale, dG, dS)
Detailed Description
TODO.
Function/Subroutine Documentation
getcoulombderivs()
subroutine xtb_coulomb_gaussian::getcoulombderivs (class(tgaussiansmeared), intent(inout) self, type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(in) qvec, real(wp), dimension(:, :, :), intent(out) djdr, real(wp), dimension(:, :), intent(out) djdtr, real(wp), dimension(:, :, :), intent(out) djdL) private
Parameters
[in,out] self Instance of the Coulomb evaluator
[in] mol Molecular structure data
[in] qvec Charges
[out] djdr Derivative of Coulomb matrix w.r.t. Cartesian coordinates
[out] djdtr Trace derivative of Coulomb matrix
[out] djdl Derivative of Coulomb matrix w.r.t. strain deformations
Definition at line 356 of file gaussian.f90.
    class(TGaussianSmeared), intent(inout) :: self
    type(TMolecule), intent(in) :: mol
    real(wp), intent(in) :: qvec(:)
    real(wp), intent(out) :: djdr(:, :, :)
    real(wp), intent(out) :: djdtr(:, :)
    real(wp), intent(out) :: djdL(:, :, :)
    select case(self%boundaryCondition)
    case(boundarycondition%cluster)
       call getcoulombderivscluster(mol, self%itbl, self%rad, qvec, djdr, &
          & djdtr, djdl)
    case(boundarycondition%pbc3d)
       call getcoulombderivspbc3d(self%wsCell, mol%id, self%itbl, self%rad, &
          & self%alpha, mol%volume, self%rTrans, self%gTrans(:, 2:), qvec, &
          & djdr, djdtr, djdl)
    end select
References xtb_mctc_boundaryconditions::boundarycondition, getcoulombderivscluster(), and getcoulombderivspbc3d().
getcoulombderivscluster()
subroutine xtb_coulomb_gaussian::getcoulombderivscluster (type(tmolecule), intent(in) mol, integer, dimension(:, :), intent(in) itbl, real(wp), dimension(:, :), intent(in) rad, real(wp), dimension(:), intent(in) qvec, real(wp), dimension(:, :, :), intent(out) djdr, real(wp), dimension(:, :), intent(out) djdtr, real(wp), dimension(:, :, :), intent(out) djdL) private
Parameters
[in] mol Molecular structure data
[in] itbl Index table
[in] rad Shell/Atomic hardnesses for each species
[in] qvec Charges
[out] djdr Derivative of Coulomb matrix w.r.t. Cartesian coordinates
[out] djdtr Trace derivative of Coulomb matrix
[out] djdl Derivative of Coulomb matrix w.r.t. strain deformations
Definition at line 389 of file gaussian.f90.
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: itbl(:, :)
    real(wp), intent(in) :: rad(:, :)
    real(wp), intent(in) :: qvec(:)
    real(wp), intent(out) :: djdr(:, :, :)
    real(wp), intent(out) :: djdtr(:, :)
    real(wp), intent(out) :: djdL(:, :, :)
    integer :: iat, jat, ish, jsh, ii, jj, iid, jid
    real(wp) :: r2, g1, gij, vec(3), dG(3), dS(3, 3)
    djdr(:, :, :) = 0.0_wp
    djdtr(:, :) = 0.0_wp
    djdl(:, :, :) = 0.0_wp
    !$omp parallel do default(none) reduction(+:djdr, djdtr, djdL) &
    !$omp shared(mol, itbl, qvec, rad) &
    !$omp private(iat, jat, ish, jsh, ii, jj, iid, jid, r2, g1, gij, vec, dG, dS)
    do iat = 1, len(mol)
       ii = itbl(1, iat)
       iid = mol%id(iat)
       do jat = 1, iat-1
          jj = itbl(1, jat)
          jid = mol%id(jat)
          vec(:) = mol%xyz(:, jat) - mol%xyz(:, iat)
          r2 = sum(vec**2)
          do ish = 1, itbl(2, iat)
             do jsh = 1, itbl(2, jat)
                gij = 1.0_wp/(rad(ish, iid)**2 + rad(jsh, jid)**2)
                g1 = erf(sqrt(gij*r2))/sqrt(r2)
                dg(:) = (2*sqrt(gij)*exp(-gij*r2)/sqrtpi - g1) * vec/r2
                ds(:, :) = 0.5_wp * spread(dg, 1, 3) * spread(vec, 2, 3)
                djdr(:, iat, jj+jsh) = djdr(:, iat, jj+jsh) - dg*qvec(ii+ish)
                djdr(:, jat, ii+ish) = djdr(:, jat, ii+ish) + dg*qvec(jj+jsh)
                djdtr(:, jj+jsh) = djdtr(:, jj+jsh) + dg*qvec(ii+ish)
                djdtr(:, ii+ish) = djdtr(:, ii+ish) - dg*qvec(jj+jsh)
                djdl(:, :, jj+jsh) = djdl(:, :, jj+jsh) + ds*qvec(ii+ish)
                djdl(:, :, ii+ish) = djdl(:, :, ii+ish) + ds*qvec(jj+jsh)
             end do
          end do
       end do
    end do
    !$omp end parallel do
References xtb_mctc_constants::sqrtpi.
Referenced by getcoulombderivs().
getcoulombderivspbc3d()
subroutine xtb_coulomb_gaussian::getcoulombderivspbc3d (type(twignerseitzcell), intent(in) wsCell, integer, dimension(:), intent(in) id, integer, dimension(:, :), intent(in) itbl, real(wp), dimension(:, :), intent(in) rad, real(wp), intent(in) alpha, real(wp), intent(in) volume, real(wp), dimension(:, :), intent(in) rTrans, real(wp), dimension(:, :), intent(in) gTrans, real(wp), dimension(:), intent(in) qvec, real(wp), dimension(:, :, :), intent(out) djdr, real(wp), dimension(:, :), intent(out) djdtr, real(wp), dimension(:, :, :), intent(out) djdL) private
Parameters
[in] wscell Wigner-Seitz cell
[in] id Identity
[in] rad Radii of charge densities
[in] volume Cell volume
[in] alpha Convergence factor
[in] rtrans Real space lattice translations
[in] gtrans Reciprocal space lattice translations
[in] itbl Index table
[in] qvec Charges
[out] djdr Derivative of Coulomb matrix w.r.t. Cartesian coordinates
[out] djdtr Trace derivative of Coulomb matrix
[out] djdl Derivative of Coulomb matrix w.r.t. strain deformations
Definition at line 451 of file gaussian.f90.
    type(TWignerSeitzCell), intent(in) :: wsCell
    integer, intent(in) :: id(:)
    real(wp), intent(in) :: rad(:, :)
    real(wp), intent(in) :: volume
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: rTrans(:, :)
    real(wp), intent(in) :: gTrans(:, :)
    integer, intent(in) :: itbl(:, :)
    real(wp), intent(in) :: qvec(:)
    real(wp), intent(out) :: djdr(:, :, :)
    real(wp), intent(out) :: djdtr(:, :)
    real(wp), intent(out) :: djdL(:, :, :)
    integer :: iat, jat, ish, jsh, ii, jj, ineigh, img, iid, jid
    real(wp) :: weight, gij, vec(3), dG(3), dS(3, 3), dGg(3), dGr(3), dSg(3, 3)
    real(wp) :: dSr(3, 3)
    real(wp), parameter :: unity(3, 3) = reshape(&
       & [1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp], &
       & [3, 3])
    djdr(:, :, :) = 0.0_wp
    djdtr(:, :) = 0.0_wp
    djdl(:, :, :) = 0.0_wp
    dgr = 0.0_wp
    dsr = 0.0_wp
    !$omp parallel do default(none) reduction(+:djdr, djdtr, djdL) &
    !$omp shared(wsCell, id, itbl, rad, qvec, alpha, volume, gTrans, rTrans) &
    !$omp private(iat, ineigh, img, jat, ish, jsh, ii, jj, iid, jid, vec, weight, &
    !$omp& gij, dG, dS, dGg, dGr, dSg, dSr)
    do iat = 1, size(wscell%neighs)
       ii = itbl(1, iat)
       iid = id(iat)
       do ineigh = 1, wscell%neighs(iat)
          img = wscell%ineigh(ineigh, iat)
          jat = wscell%image(img)
          jj = itbl(1, jat)
          jid = id(jat)
          weight = wscell%weight(ineigh, iat)
          vec(:) = wscell%coords(:, img) - wscell%coords(:, iat)
          call ewaldderivpbc3d(vec, gtrans, 0.0_wp, volume, alpha, weight, dgg, dsg)
          if (iat /= jat) then
             do ish = 1, itbl(2, iat)
                do jsh = 1, itbl(2, jat)
                   gij = 1.0_wp/sqrt(rad(ish, iid)**2 + rad(jsh, jid)**2)
                   call getrderiv(vec, gij, rtrans, alpha, weight, dgr, dsr)
                   dg(:) = dgg + dgr
                   ds(:, :) = dsg + dsr + pi / (volume * alpha**2) * weight * unity
                   djdr(:, iat, jj+jsh) = djdr(:, iat, jj+jsh) - dg*qvec(ii+ish)
                   djdr(:, jat, ii+ish) = djdr(:, jat, ii+ish) + dg*qvec(jj+jsh)
                   djdtr(:, jj+jsh) = djdtr(:, jj+jsh) + dg*qvec(ii+ish)
                   djdtr(:, ii+ish) = djdtr(:, ii+ish) - dg*qvec(jj+jsh)
                   djdl(:, :, jj+jsh) = djdl(:, :, jj+jsh) + ds*qvec(ii+ish)
                   djdl(:, :, ii+ish) = djdl(:, :, ii+ish) + ds*qvec(jj+jsh)
                end do
             end do
          else
             do ish = 1, itbl(2, iat)
                do jsh = 1, ish-1
                   gij = 1.0_wp/sqrt(rad(ish, iid)**2 + rad(jsh, iid)**2)
                   call getrderiv(vec, gij, rtrans, alpha, weight, dgr, dsr)
                   ds(:, :) = dsg + dsr + pi / (volume * alpha**2) * weight * unity
                   djdl(:, :, ii+jsh) = djdl(:, :, ii+jsh) + ds*qvec(ii+ish)
                   djdl(:, :, ii+ish) = djdl(:, :, ii+ish) + ds*qvec(ii+jsh)
                end do
                gij = sqrt(0.5_wp)/rad(ish, iid)
                call getrderiv(vec, gij, rtrans, alpha, weight, dgr, dsr)
                ds(:, :) = dsg + dsr + pi / (volume * alpha**2) * weight * unity
                djdl(:, :, ii+ish) = djdl(:, :, ii+ish) + ds*qvec(ii+ish)
             end do
          end if
       end do
    end do
    !$omp end parallel do
References xtb_coulomb_ewald::ewaldderivpbc3d(), getrderiv(), and xtb_mctc_constants::pi.
Referenced by getcoulombderivs().
getcoulombmatrix()
subroutine xtb_coulomb_gaussian::getcoulombmatrix (class(tgaussiansmeared), intent(inout) self, type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(out) jmat) private
Parameters
[in,out] self Instance of the Coulomb evaluator
[in] mol Molecular structure data
[out] jmat Coulomb matrix
Definition at line 167 of file gaussian.f90.
    class(TGaussianSmeared), intent(inout) :: self
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: jmat(:, :)
    select case(self%boundaryCondition)
    case(boundarycondition%cluster)
       call getcoulombmatrixcluster(mol, self%itbl, self%rad, jmat)
    case(boundarycondition%pbc3d)
       call getcoulombmatrixpbc3d(self%wsCell, mol%id, self%itbl, self%rad, &
          & self%alpha, mol%volume, self%rTrans, self%gTrans(:, 2:), jmat)
    end select
References xtb_mctc_boundaryconditions::boundarycondition, getcoulombmatrixcluster(), and getcoulombmatrixpbc3d().
getcoulombmatrixcluster()
subroutine xtb_coulomb_gaussian::getcoulombmatrixcluster (type(tmolecule), intent(in) mol, integer, dimension(:, :), intent(in) itbl, real(wp), dimension(:, :), intent(in) rad, real(wp), dimension(:, :), intent(out) jmat) private
Parameters
[in] mol Molecular structure data
[in] itbl Index table
[in] rad Shell/Atomic hardnesses for each species
[out] jmat Coulomb matrix
Definition at line 189 of file gaussian.f90.
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: itbl(:, :)
    real(wp), intent(in) :: rad(:, :)
    real(wp), intent(out) :: jmat(:, :)
    integer :: iat, jat, ish, jsh, ii, jj, iid, jid
    real(wp) :: r1, rterm, gij
    jmat(:, :) = 0.0_wp
    !$omp parallel do default(none) shared(mol, itbl, rad, jmat) &
    !$omp private(iat, jat, ish, jsh, ii, jj, iid, jid, r1, rterm, gij)
    do iat = 1, len(mol)
       ii = itbl(1, iat)
       iid = mol%id(iat)
       do jat = 1, iat-1
          jj = itbl(1, jat)
          jid = mol%id(jat)
          r1 = sqrt(sum((mol%xyz(:, jat) - mol%xyz(:, iat))**2))
          do ish = 1, itbl(2, iat)
             do jsh = 1, itbl(2, jat)
                gij = 1.0_wp/sqrt(rad(ish, iid)**2 + rad(jsh, jid)**2)
                rterm = erf(gij*r1)/r1
                jmat(jj+jsh, ii+ish) = rterm
                jmat(ii+ish, jj+jsh) = rterm
             end do
          end do
       end do
       do ish = 1, itbl(2, iat)
          do jsh = 1, ish-1
             gij = 1.0_wp/sqrt(rad(ish, iid)**2 + rad(jsh, iid)**2)
             jmat(ii+jsh, ii+ish) = 2.0_wp/sqrtpi*gij
             jmat(ii+ish, ii+jsh) = 2.0_wp/sqrtpi*gij
          end do
          gij = sqrt(0.5_wp)/rad(ish, iid)
          jmat(ii+ish, ii+ish) = 2.0_wp/sqrtpi*gij
       end do
    end do
    !$omp end parallel do
References xtb_mctc_constants::sqrtpi.
Referenced by getcoulombmatrix().
getcoulombmatrixpbc3d()
subroutine xtb_coulomb_gaussian::getcoulombmatrixpbc3d (type(twignerseitzcell), intent(in) wsCell, integer, dimension(:), intent(in) id, integer, dimension(:, :), intent(in) itbl, real(wp), dimension(:, :), intent(in) rad, real(wp), intent(in) alpha, real(wp), intent(in) volume, real(wp), dimension(:, :), intent(in) rTrans, real(wp), dimension(:, :), intent(in) gTrans, real(wp), dimension(:, :), intent(out) jmat) private
Parameters
[in] wscell Wigner-Seitz cell
[in] id Identity
[in] itbl Index table
[in] rad Shell/Atomic hardnesses for each species
[in] volume Cell volume
[in] alpha Convergence factor
[in] rtrans Real space lattice translations
[in] gtrans Reciprocal space lattice translations
[out] jmat Coulomb matrix
Definition at line 241 of file gaussian.f90.
    type(TWignerSeitzCell), intent(in) :: wsCell
    integer, intent(in) :: id(:)
    integer, intent(in) :: itbl(:, :)
    real(wp), intent(in) :: rad(:, :)
    real(wp), intent(in) :: volume
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: rTrans(:, :)
    real(wp), intent(in) :: gTrans(:, :)
    real(wp), intent(out) :: jmat(:, :)
    integer :: iat, ineigh, img, jat, ish, jsh, ii, jj, iid, jid
    real(wp) :: vec(3), rterm, gterm, weight, gij
    real(wp), parameter :: zero(3) = 0.0_wp
    jmat(:, :) = 0.0_wp
    !$omp parallel do default(none) reduction(+:jmat) &
    !$omp shared(wsCell, id, itbl, alpha, volume, gTrans, rTrans, rad) &
    !$omp private(iat, ineigh, img, jat, ish, jsh, ii, jj, iid, jid, rterm, &
    !$omp& gterm, vec, weight, gij)
    do iat = 1, size(wscell%neighs)
       ii = itbl(1, iat)
       iid = id(iat)
       do ineigh = 1, wscell%neighs(iat)
          img = wscell%ineigh(ineigh, iat)
          jat = wscell%image(img)
          jj = itbl(1, jat)
          jid = id(jat)
          weight = wscell%weight(ineigh, iat)
          vec(:) = wscell%coords(:, img) - wscell%coords(:, iat)
          gterm = ewaldmatpbc3d(vec, gtrans, 0.0_wp, volume, alpha, weight) &
             &  - pi / (volume * alpha**2) * weight
          if (iat /= jat) then
             do ish = 1, itbl(2, iat)
                do jsh = 1, itbl(2, jat)
                   gij = 1.0_wp/sqrt(rad(ish, iid)**2 + rad(jsh, jid)**2)
                   rterm = gterm + getrterm(vec, gij, rtrans, alpha, weight)
                   jmat(jj+jsh, ii+ish) = jmat(jj+jsh, ii+ish) + rterm
                   jmat(ii+ish, jj+jsh) = jmat(ii+ish, jj+jsh) + rterm
                end do
             end do
          else
             do ish = 1, itbl(2, iat)
                do jsh = 1, ish-1
                   gij = 1.0_wp/sqrt(rad(ish, iid)**2 + rad(jsh, iid)**2)
                   rterm = gterm + getrterm(vec, gij, rtrans, alpha, weight)
                   jmat(ii+jsh, ii+ish) = jmat(ii+jsh, ii+ish) + rterm
                   jmat(ii+ish, ii+jsh) = jmat(ii+ish, ii+jsh) + rterm
                end do
                gij = sqrt(0.5_wp)/rad(ish, iid)
                rterm = gterm + getrterm(vec, gij, rtrans, alpha, weight)
                jmat(ii+ish, ii+ish) = jmat(ii+ish, ii+ish) + rterm
             end do
          end if
       end do
       do ish = 1, itbl(2, iat)
          do jsh = 1, ish-1
             gij = 1.0_wp/sqrt(rad(ish, iid)**2 + rad(jsh, iid)**2)
             jmat(ii+jsh, ii+ish) = jmat(ii+jsh, ii+ish) + 2.0_wp/sqrtpi*gij
             jmat(ii+ish, ii+jsh) = jmat(ii+ish, ii+jsh) + 2.0_wp/sqrtpi*gij
          end do
          gij = sqrt(0.5_wp)/rad(ish, iid)
          jmat(ii+ish, ii+ish) = jmat(ii+ish, ii+ish) + 2.0_wp/sqrtpi*gij
       end do
    end do
    !$omp end parallel do
References xtb_coulomb_ewald::ewaldmatpbc3d(), xtb_coulomb_ewald::getrterm(), xtb_mctc_constants::pi, and xtb_mctc_constants::sqrtpi.
Referenced by getcoulombmatrix().
getrderiv()
pure subroutine xtb_coulomb_gaussian::getrderiv (real(wp), dimension(:), intent(in) vec, real(wp), intent(in) gij, real(wp), dimension(:,:), intent(in) rTrans, real(wp), intent(in) alpha, real(wp), intent(in) scale, real(wp), dimension(:), intent(out) dG, real(wp), dimension(:,:), intent(out) dS) private
Definition at line 555 of file gaussian.f90.
    real(wp), intent(in) :: vec(:)
    real(wp), intent(in) :: gij
    real(wp), intent(in) :: rTrans(:,:)
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: scale
    real(wp), intent(out) :: dG(:)
    real(wp), intent(out) :: dS(:,:)
    real(wp), parameter :: eps = 1.0e-9_wp
    integer :: itr
    real(wp) :: r1, rij(3), arg, dd
    real(wp), parameter :: unity(3, 3) = reshape(&
       & [1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp], &
       & [3, 3])
    dg = 0.0_wp
    ds = 0.0_wp
    do itr = 1, size(rtrans, dim=2)
       ! real contributions
       rij = vec + rtrans(:, itr)
       r1 = sqrt(sum(rij**2))
       if (r1 < eps) cycle
       arg = alpha**2*r1**2
       dd = + 2*gij*exp(-gij**2*r1**2)/(sqrtpi*r1**2) - erf(gij*r1)/(r1**3) &
          & - 2*alpha*exp(-arg)/(sqrtpi*r1**2) + erf(alpha*r1)/(r1**3)
       dg = dg + rij*dd
       ds = ds + 0.5_wp * dd*spread(rij, 1, 3)*spread(rij, 2, 3)
    enddo
    dg = dg * scale
    ds = ds * scale
References xtb_mctc_constants::sqrtpi.
Referenced by getcoulombderivspbc3d().
getrterm()
pure real(wp) function xtb_coulomb_gaussian::getrterm (real(wp), dimension(3), intent(in) vec, real(wp), intent(in) gam, real(wp), dimension(:,:), intent(in) rTrans, real(wp), intent(in) alpha, real(wp), intent(in) scale) private
Definition at line 331 of file gaussian.f90.
    real(wp),intent(in) :: vec(3)
    real(wp),intent(in) :: gam
    real(wp),intent(in) :: rTrans(:,:)
    real(wp),intent(in) :: alpha
    real(wp),intent(in) :: scale
    real(wp) :: rTerm
    real(wp),parameter :: eps = 1.0e-9_wp
    integer  :: itr
    real(wp) :: r1, rij(3)
    rterm = 0.0_wp
    do itr = 1, size(rtrans, dim=2)
       rij = vec + rtrans(:, itr)
       r1 = sqrt(sum(rij**2))
       ! self-interaction correction
       if(r1 < eps) then
          rterm = rterm - 2.0_wp*alpha/sqrtpi
       else
          rterm = rterm + erf(gam*r1)/r1 - erf(alpha*r1)/r1
       end if
    end do
    rterm = rterm * scale
References xtb_mctc_constants::sqrtpi.
initfrommolecule()
subroutine xtb_coulomb_gaussian::initfrommolecule (type(tgaussiansmeared), intent(out) self, type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) rad, integer, dimension(:), intent(in), optional num, integer, dimension(:), intent(in), optional nshell, real(wp), intent(in), optional alpha, real(wp), intent(in), optional tolerance) private
Parameters
[out] self Instance of the Coulomb evaluator
[in,out] env Calculation environment
[in] mol Molecular structure data
[in] rad Shell/Atomic hardnesses for each species
[in] num Atomic number for each id
[in] nshell Number of shell for each species
[in] alpha Convergence factor
[in] tolerance Tolerance for the Ewald sum
Definition at line 62 of file gaussian.f90.
    character(len=*), parameter :: source = 'coulomb_gaussian_initFromMolecule'
    type(TGaussianSmeared), intent(out) :: self
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    real(wp), intent(in) :: rad(:, :)
    integer, intent(in), optional :: num(:)
    integer, intent(in), optional :: nshell(:)
    real(wp), intent(in), optional :: alpha
    real(wp), intent(in), optional :: tolerance
    logical :: exitRun
    call init(self, env, mol%id, mol%lattice, mol%boundaryCondition, &
       & rad, num, nshell, alpha, tolerance)
    call env%check(exitrun)
    if (exitrun) return
    call self%update(env, mol)
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Initializing internal state of evaluator failed", source)
    end if
initgaussiansmeared()
subroutine xtb_coulomb_gaussian::initgaussiansmeared (type(tgaussiansmeared), intent(out) self, type(tenvironment), intent(inout) env, integer, dimension(:), intent(in) id, real(wp), dimension(:, :), intent(in) lattice, integer, intent(in) boundaryCond, real(wp), dimension(:, :), intent(in) rad, integer, dimension(:), intent(in), optional num, integer, dimension(:), intent(in), optional nshell, real(wp), intent(in), optional alpha, real(wp), intent(in), optional tolerance) private
Parameters
[out] self Instance of the Coulomb evaluator
[in] id Identity of each atom
[in,out] env Calculation environment
[in] lattice Lattice parameters
[in] boundarycond Boundary conditions for this evaluator
[in] rad Shell/Atomic hardnesses for each species
[in] num Atomic number for each id
[in] nshell Number of shell for each species
[in] alpha Convergence factor
[in] tolerance Tolerance for the Ewald sum
Definition at line 109 of file gaussian.f90.
    character(len=*), parameter :: source = 'coulomb_gaussian_initGaussianSmeared'
    type(TGaussianSmeared), intent(out) :: self
    integer, intent(in) :: id(:)
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: lattice(:, :)
    integer, intent(in) :: boundaryCond
    real(wp), intent(in) :: rad(:, :)
    integer, intent(in), optional :: num(:)
    integer, intent(in), optional :: nshell(:)
    real(wp), intent(in), optional :: alpha
    real(wp), intent(in), optional :: tolerance
    logical :: exitRun
    integer :: ii
    self%boundaryCondition = boundarycond
    self%natom = size(id, dim=1)
    call setupindextable(self%natom, self%itbl, id, num, nshell)
    if (present(num)) then
       allocate(self%rad(size(rad, dim=1), size(num)))
       do ii = 1, size(num)
          self%rad(:, ii) = rad(:, num(ii))
       end do
    else
       self%rad = rad
    end if
    call setupboundaryconditions(self, env, lattice, alpha, tolerance)