My Project: xtb_paramset Module Reference
xtb_paramset Module Reference
Functions/Subroutines
subroutine set_gfn1_parameter (xpar, globpar, xtbData)
subroutine set_gfn2_parameter (xpar, globpar, xtbData)
subroutine set_gfn0_parameter (xpar, globpar, xtbData)
subroutine use_parameterset (name, globpar, xtbData, exist)
subroutine setpair (gfn_method, pairParam)
integer function tmmetal (i)
Function/Subroutine Documentation
set_gfn0_parameter()
subroutine xtb_paramset::set_gfn0_parameter (type(scc_parameter), intent(inout) xpar, type(txtbparameter), intent(in) globpar, type(txtbdata), intent(inout) xtbData)
Definition at line 47 of file gfn_paramset.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_type_param
    !use gfn0_module
    use xtb_aoparam
    use xtb_disp_dftd4
    implicit none
    type(scc_parameter),intent(inout) :: xpar
    type(TxTBParameter), intent(in) :: globpar
    type(TxTBData), intent(inout) :: xtbData
References xtb_mctc_accuracy::wp.
set_gfn1_parameter()
subroutine xtb_paramset::set_gfn1_parameter (type(scc_parameter), intent(inout) xpar, type(txtbparameter), intent(in) globpar, type(txtbdata), intent(inout) xtbData)
Definition at line 28 of file gfn_paramset.f90.
    use xtb_disp_dftd3param
    implicit none
    type(scc_parameter),intent(inout) :: xpar
    type(TxTBParameter), intent(in) :: globpar
    type(TxTBData), intent(inout) :: xtbData
set_gfn2_parameter()
subroutine xtb_paramset::set_gfn2_parameter (type(scc_parameter), intent(inout) xpar, type(txtbparameter), intent(in) globpar, type(txtbdata), intent(inout) xtbData)
Definition at line 37 of file gfn_paramset.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_type_param
    use xtb_disp_dftd4
    implicit none
    type(scc_parameter),intent(inout) :: xpar
    type(TxTBParameter), intent(in) :: globpar
    type(TxTBData), intent(inout) :: xtbData
References xtb_mctc_accuracy::wp.
setpair()
subroutine xtb_paramset::setpair (integer gfn_method, real(wp), dimension(:, :), intent(inout) pairParam)
Definition at line 85 of file gfn_paramset.f90.
    real(wp), intent(inout) :: pairParam(:, :)
    integer gfn_method
    integer i,j,ii,jj
    real*8  kp(3)
    real*8  kparam
    integer tmgroup(3)
    logical notset
    if(gfn_method.eq.1)then
       kp(1)=1.1    ! 3d
       kp(2)=1.2    ! 4d
       kp(3)=1.2    ! 5d or 4f
    elseif(gfn_method.eq.0)then
       kp(1)=1.10
       kp(2)=1.10
       kp(3)=1.10
       kparam=0.9
       tmgroup=(/29,47,79/)
       do i=1,3
          do j=1,3
             ii=tmgroup(i)
             jj=tmgroup(j)
             pairparam(ii,jj)=kparam
             pairparam(jj,ii)=kparam
          enddo
       enddo
    elseif(gfn_method.gt.1)then
       kp(1)=1.   ! 3d
       kp(2)=1.   ! 4d
       kp(3)=1.   ! 5d or 4f
       !     write(*,'(''KAB for pair M(3d)-M(3d) :'',f8.4)')kp(1)
       !     write(*,'(''KAB for pair M(4d)-M(4d) :'',f8.4)')kp(2)
       !     write(*,'(''KAB for pair M(5d)-M(5d) :'',f8.4)')kp(3)
    endif
    do i=21,79
       do j=21,i
          ii=tmmetal(i)
          jj=tmmetal(j)
          !           metal-metal interaction
          notset=abs(pairparam(i,j)-1.0d0).lt.1.d-6 .and. &
             &             abs(pairparam(j,i)-1.0d0).lt.1.d-6
          if(ii.gt.0.and.jj.gt.0.and.notset) then
             pairparam(i,j)=0.5*(kp(ii)+kp(jj))
             pairparam(j,i)=0.5*(kp(ii)+kp(jj))
          endif
       enddo
    enddo
References tmmetal().
Referenced by xtb_readparam::readparam().
tmmetal()
integer function xtb_paramset::tmmetal (integer i)
Definition at line 137 of file gfn_paramset.f90.
    integer i,j
    j=0
    if(i.gt.20.and.i.lt.30) j=1
    if(i.gt.38.and.i.lt.48) j=2
    if(i.gt.56.and.i.lt.80) j=3
    tmmetal=j
Referenced by setpair().
use_parameterset()
subroutine xtb_paramset::use_parameterset (character(len=*), intent(in) name, type(txtbparameter), intent(out) globpar, type(txtbdata), intent(out) xtbData, logical, intent(out) exist)
Definition at line 59 of file gfn_paramset.f90.
    use xtb_aoparam, only : kpair
    implicit none
    character(len=*),intent(in) :: name
    logical,intent(out)  :: exist
    type(TxTBParameter), intent(out) :: globpar
    type(TxTBData), intent(out) :: xtbData
    exist = .false.
    select case(name)
    case('param_gfn0-xtb.txt')
       return
       globpar = gfn0globals
       call initgfn0(xtbdata)
    case('param_gfn1-xtb.txt')
       globpar = gfn1globals
       call initgfn1(xtbdata)
    case('param_gfn2-xtb.txt')
       globpar = gfn2globals
       call initgfn2(xtbdata)
    case default
       return
    end select
    exist = .true.
References xtb_xtb_gfn0::gfn0globals, xtb_xtb_gfn1::gfn1globals, xtb_xtb_gfn2::gfn2globals, xtb_aoparam::kpair, and true().
Referenced by xtb_main_setup::newxtbcalculator(), test_gfn0_sp(), test_gfn1_scc(), test_gfn2_scc(), and test_peeq_sp().