My Project: xtb_coulomb_ewald Module Reference
xtb_coulomb_ewald Module Reference
Implementation of Ewald summation specific tasks.
Data Types
interface getGTermGen
Returns the max. value of a term in the reciprocal space part of the Ewald.
Functions/Subroutines
pure real(wp) function, public ewaldmatpbc3d (vec, gTrans, qpc, volume, alpha, scale)
pure subroutine, public ewaldderivpbc3d_alp (vec, gTrans, qpc, volume, alpha, scale, dAmat, sigma)
pure subroutine, public ewaldderivpbc3d (vec, gTrans, qpc, volume, alpha, scale, dAmat, sigma)
subroutine, public getoptimalalpha (env, latVec, recVec, volume, tolerance, alpha)
Get optimal alpha-parameter for the Ewald summation by finding alpha, where.
subroutine, public getmaxg (env, alpha, volume, minValue, maxG)
Returns the longest reciprocal vector which gives a bigger contribution to.
subroutine, public getmaxr (env, alpha, minValue, maxR)
Returns the longest real space vector which gives a bigger contribution to.
pure real(wp) function diffrecreal (alpha, getGTerm, minG, minR, volume)
Returns the difference in the decrease of the real and reciprocal parts of the.
pure real(wp) function getgtermpbc3d (gg, alpha, vol)
Returns the max. value of a term in the reciprocal space part of the Ewald.
pure real(wp) function getrterm (rr, alpha)
Returns the max. value of a term in the real space part of the Ewald summation.
Variables
integer, parameter nsearchiter = 30
Nr. of max. bisection steps.
Detailed Description
Implementation of Ewald summation specific tasks.
Function/Subroutine Documentation
diffrecreal()
pure real(wp) function xtb_coulomb_ewald::diffrecreal (real(wp), intent(in) alpha, procedure(getgtermgen) getGTerm, real(wp), intent(in) minG, real(wp), intent(in) minR, real(wp), intent(in) volume) private
Returns the difference in the decrease of the real and reciprocal parts of the.
Parameters
[in] alpha Parameter for the Ewald summation
getgterm Procedure pointer to reciprocal routine
[in] ming Length of the shortest reciprocal space vector in the sum
[in] minr Length of the shortest real space vector in the sum
[in] volume Volume of the real space unit cell
Returns
Difference between changes in the two terms
Definition at line 439 of file ewald.f90.
    real(wp), intent(in) :: alpha
    procedure(getGTermGen) :: getGTerm
    real(wp), intent(in) :: minG
    real(wp), intent(in) :: minR
    real(wp), intent(in) :: volume
    real(wp) :: diff
    diff = ((getgterm(4.0_wp*ming, alpha, volume) &
       & - getgterm(5.0_wp*ming, alpha, volume))) &
       & - (getrterm(2.0_wp*minr, alpha) - getrterm(3.0_wp*minr, alpha))
References getrterm().
Referenced by getoptimalalpha().
ewaldderivpbc3d()
pure subroutine, public xtb_coulomb_ewald::ewaldderivpbc3d (real(wp), dimension(:), intent(in) vec, real(wp), dimension(:, :), intent(in) gTrans, real(wp), intent(in) qpc, real(wp), intent(in) volume, real(wp), intent(in) alpha, real(wp), intent(in) scale, real(wp), dimension(:), intent(out) dAmat, real(wp), dimension(:, :), intent(out) sigma)
Parameters
[in] vec Distance from i to WSC atom
[in] gtrans Reciprocal lattice
[in] qpc Pseudo-quadrupole charge
[in] volume Direct cell volume
[in] alpha Convergence factor
[in] scale Additional scaling factor
[out] damat Derivative of interaction matrix
[out] sigma Strain of interaction matrix
Definition at line 153 of file ewald.f90.
    real(wp),intent(in) :: vec(:)
    real(wp),intent(in) :: gTrans(:, :)
    real(wp), intent(in) :: qpc
    real(wp),intent(in) :: volume
    real(wp),intent(in) :: alpha
    real(wp), intent(in) :: scale
    real(wp),intent(out) :: dAmat(:)
    real(wp),intent(out) :: sigma(:, :)
    integer  :: iG
    real(wp) :: rik2, rik(3), dtmp, expterm, arg
    real(wp) :: fqpc, dS(3, 3)
    real(wp), parameter :: unity(3, 3) = reshape(&
       & [1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp], &
       & [3, 3])
    damat = 0.0_wp
    sigma = 0.0_wp
    fqpc = 2*qpc**2
    do ig = 1, size(gtrans, dim=2)
       rik = gtrans(:, ig)
       rik2 = dot_product(rik,rik)
       expterm = exp(-rik2/(4.0_wp*alpha**2))/rik2
       arg = dot_product(rik,vec)
       dtmp = -sin(arg) * expterm
       damat = damat + rik*dtmp
       ds = spread(rik,1,3)*spread(rik,2,3)
       sigma = sigma + 0.5_wp * expterm * cos(arg) * ( &
          & - unity * (1.0_wp + rik2*fqpc) &
          & + (2.0_wp/rik2 + 0.5_wp/alpha**2 + 0.5_wp*fqpc) * ds)
    end do
    damat = damat * 4.0_wp*pi/volume * scale
    sigma = sigma * 4.0_wp*pi/volume * scale
References xtb_mctc_constants::pi.
Referenced by xtb_eeq::get_coulomb_derivs::get_coulomb_derivs_3d(), xtb_coulomb_klopmanohno::getcoulombderivspbc3d(), xtb_coulomb_gaussian::getcoulombderivspbc3d(), and xtb_type_coulomb::getcoulombderivspbc3d().
ewaldderivpbc3d_alp()
pure subroutine, public xtb_coulomb_ewald::ewaldderivpbc3d_alp (real(wp), dimension(:), intent(in) vec, real(wp), dimension(:, :), intent(in) gTrans, real(wp), intent(in) qpc, real(wp), intent(in) volume, real(wp), intent(in) alpha, real(wp), intent(in) scale, real(wp), dimension(:), intent(out) dAmat, real(wp), dimension(:, :), intent(out) sigma)
Parameters
[in] vec Distance from i to WSC atom
[in] gtrans Reciprocal lattice
[in] qpc Pseudo-quadrupole charge
[in] volume Direct cell volume
[in] alpha Convergence factor
[in] scale Additional scaling factor
[out] damat Derivative of interaction matrix
[out] sigma Strain of interaction matrix
Definition at line 97 of file ewald.f90.
    real(wp),intent(in) :: vec(:)
    real(wp),intent(in) :: gTrans(:, :)
    real(wp), intent(in) :: qpc
    real(wp),intent(in) :: volume
    real(wp),intent(in) :: alpha
    real(wp), intent(in) :: scale
    real(wp),intent(out) :: dAmat(:)
    real(wp),intent(out) :: sigma(:, :)
    integer  :: iG
    real(wp) :: rik2, rik(3), dtmp, expterm, arg
    real(wp) :: fqpc, falp, dS(3, 3)
    real(wp), parameter :: unity(3, 3) = reshape(&
       & [1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp], &
       & [3, 3])
    damat = 0.0_wp
    sigma = 0.0_wp
    fqpc = 2*qpc**2
    falp = 2.0_wp/3.0_wp/(4.0_wp*alpha**2)
    do ig = 1, size(gtrans, dim=2)
       rik = gtrans(:, ig)
       rik2 = dot_product(rik,rik)
       expterm = exp(-rik2/(4.0_wp*alpha**2))/rik2
       arg = dot_product(rik,vec)
       dtmp = -sin(arg) * expterm
       damat = damat + rik*dtmp
       ds = spread(rik,1,3)*spread(rik,2,3)
       sigma = sigma + expterm * cos(arg) * ( &
          & - unity * (1.0_wp + rik2*falp + rik2*fqpc) &
          & + (2.0_wp/rik2 + 0.5_wp/alpha**2 + 0.5_wp*fqpc) * ds)
    end do
    damat = damat * 4.0_wp*pi/volume * scale
    sigma = sigma * 4.0_wp*pi/volume * scale
References xtb_mctc_constants::pi.
ewaldmatpbc3d()
pure real(wp) function, public xtb_coulomb_ewald::ewaldmatpbc3d (real(wp), dimension(:), intent(in) vec, real(wp), dimension(:, :), intent(in) gTrans, real(wp), intent(in) qpc, real(wp), intent(in) volume, real(wp), intent(in) alpha, real(wp), intent(in) scale)
Parameters
[in] vec Distance from i to WSC atom
[in] gtrans Reciprocal lattice
[in] qpc Pseudo-quadrupole charge
[in] volume Direct cell volume
[in] alpha Convergence factor
[in] scale Additional scaling factor
Returns
Element of interaction matrix
Definition at line 59 of file ewald.f90.
    real(wp), intent(in) :: vec(:)
    real(wp), intent(in) :: gTrans(:, :)
    real(wp), intent(in) :: qpc
    real(wp), intent(in) :: volume
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: scale
    real(wp) :: Amat
    integer :: iG
    real(wp) :: rik2, rik(3), expterm
    amat = 0.0_wp
    do ig = 1, size(gtrans, dim=2)
       rik(:) = gtrans(:, ig)
       rik2 = dot_product(rik, rik)
       expterm = exp(-rik2/(4.0_wp*alpha**2))/rik2
       amat = amat + cos(dot_product(rik, vec)) * expterm * (1.0_wp + 2*rik2*qpc**2)
    end do
    amat = amat * 4.0_wp*pi/volume * scale
References xtb_mctc_constants::pi.
Referenced by xtb_eeq::get_coulomb_matrix::get_coulomb_matrix_3d(), xtb_coulomb_klopmanohno::getcoulombmatrixpbc3d(), xtb_coulomb_gaussian::getcoulombmatrixpbc3d(), and xtb_type_coulomb::getcoulombmatrixpbc3d().
getgtermpbc3d()
pure real(wp) function xtb_coulomb_ewald::getgtermpbc3d (real(wp), intent(in) gg, real(wp), intent(in) alpha, real(wp), intent(in) vol) private
Returns the max. value of a term in the reciprocal space part of the Ewald.
Parameters
[in] gg Length of the reciprocal space vector
[in] alpha Parameter of the Ewald summation
[in] vol Volume of the real space unit cell
Returns
Reciprocal term
Definition at line 468 of file ewald.f90.
    real(wp), intent(in) :: gg
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: vol
    real(wp) :: gTerm
    gterm = 4.0_wp*pi*(exp(-0.25_wp*gg**2/(alpha**2))/(vol*gg**2))
References xtb_mctc_constants::pi.
Referenced by getmaxg(), and getoptimalalpha().
getmaxg()
subroutine, public xtb_coulomb_ewald::getmaxg (type(tenvironment), intent(inout) env, real(wp), intent(in) alpha, real(wp), intent(in) volume, real(wp), intent(in) minValue, real(wp) maxG)
Returns the longest reciprocal vector which gives a bigger contribution to.
Parameters
[in,out] env Calculation environment
[in] alpha Parameter of the ewald summation
[in] volume Volume of the unit cell
[in] minvalue Tolerance value
maxg Magnitude of reciprocal vector
Definition at line 298 of file ewald.f90.
    character(len=*), parameter :: source = 'coulomb_ewald_getMaxG'
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: volume
    real(wp), intent(in) :: minValue
    real(wp) :: maxG
    real(wp), parameter :: gInit = 1.0e-8_wp
    real(wp) :: xLeft, xRight, yLeft, yRight, yy
    integer :: iError, iIter
    character(len=100) :: errorString
    ierror = 0
    maxg = ginit
    yy = getgtermpbc3d(maxg, alpha, volume)
    do while (yy > minvalue .and. maxg <= huge(1.0_wp))
       maxg = 2.0_wp * maxg
       yy = getgtermpbc3d(maxg, alpha, volume)
    end do
    if (maxg > huge(1.0_wp)) then
       ierror = 1
    elseif (maxg == ginit) then
       ierror = 2
    end if
    if (ierror == 0) then
       xleft = 0.5_wp * maxg
       yleft = getgtermpbc3d(xleft, alpha, volume)
       xright = maxg
       yright = yy
       iiter = 1
       do while (yleft - yright > minvalue .and. iiter <= nsearchiter)
          maxg = 0.5_wp * (xleft + xright)
          yy = getgtermpbc3d(maxg, alpha, volume)
          if (yy >= minvalue) then
             xleft = maxg
             yleft = yy
          else
             xright = maxg
             yright = yy
          end if
          iiter = iiter + 1
       end do
       if (iiter > nsearchiter) then
          ierror = 3
       end if
    end if
    if (ierror /= 0) then
       call env%error('Failed to determine max. reciprocal lattice vector', source)
    end if
References getgtermpbc3d(), and nsearchiter.
Referenced by xtb_type_coulomb::setupboundaryconditions().
getmaxr()
subroutine, public xtb_coulomb_ewald::getmaxr (type(tenvironment), intent(inout) env, real(wp), intent(in) alpha, real(wp), intent(in) minValue, real(wp) maxR)
Returns the longest real space vector which gives a bigger contribution to.
Parameters
[in,out] env Calculation environment
[in] alpha Parameter of the ewald summation
[in] minvalue Tolerance value
maxr Magnitude of real space vector
Definition at line 369 of file ewald.f90.
    character(len=*), parameter :: source = 'coulomb_ewald_getMaxR'
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: alpha
    real(wp), intent(in) :: minValue
    real(wp) :: maxR
    real(wp), parameter :: rInit = 1.0e-8_wp
    real(wp) :: xLeft, xRight, yLeft, yRight, yy
    integer :: iError, iIter
    character(len=100) :: errorString
    ierror = 0
    maxr = rinit
    yy = getrterm(maxr, alpha)
    do while (yy > minvalue .and. maxr <= huge(1.0_wp))
       maxr = 2.0_wp * maxr
       yy = getrterm(maxr, alpha)
    end do
    if (maxr > huge(1.0_wp)) then
       ierror = 1
    elseif (maxr == rinit) then
       ierror = 2
    end if
    if (ierror == 0) then
       xleft = 0.5_wp * maxr
       yleft = getrterm(xleft, alpha)
       xright = maxr
       yright = yy
       iiter = 1
       do while (yleft - yright > minvalue .and. iiter <= nsearchiter)
          maxr = 0.5_wp * (xleft + xright)
          yy = getrterm(maxr, alpha)
          if (yy >= minvalue) then
             xleft = maxr
             yleft = yy
          else
             xright = maxr
             yright = yy
          end if
          iiter = iiter + 1
       end do
       if (iiter > nsearchiter) then
          ierror = 3
       end if
    end if
    if (ierror /= 0) then
       call env%error('Failed to determine max. real lattice vector', source)
    end if
References getrterm(), and nsearchiter.
Referenced by xtb_type_coulomb::setupboundaryconditions().
getoptimalalpha()
subroutine, public xtb_coulomb_ewald::getoptimalalpha (type(tenvironment), intent(inout) env, real(wp), dimension(:,:), intent(in) latVec, real(wp), dimension(:,:), intent(in) recVec, real(wp), intent(in) volume, real(wp), intent(in) tolerance, real(wp) alpha)
Get optimal alpha-parameter for the Ewald summation by finding alpha, where.
Parameters
[in,out] env Calculation environment
[in] latvec Lattice vectors
[in] recvec Reciprocal vectors
[in] volume Volume of the unit cell
[in] tolerance Tolerance for difference in real and rec. part
alpha Optimal alpha
Definition at line 210 of file ewald.f90.
    character(len=*), parameter :: source = 'coulomb_ewald_getOptimalAlpha'
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: latVec(:,:)
    real(wp), intent(in) :: recVec(:,:)
    real(wp), intent(in) :: volume
    real(wp), intent(in) :: tolerance
    real(wp) :: alpha
    real(wp) :: alphaLeft, alphaRight
    real(wp), parameter :: alphaInit = 1.0e-8_wp
    real(wp) :: minG, minR, diff
    integer :: iIter
    integer :: iError
    character(len=100) :: errorString
    ming = sqrt(minval(sum(recvec(:,:)**2, dim=1)))
    minr = sqrt(minval(sum(latvec(:,:)**2, dim=1)))
    ierror = 0
    alpha = alphainit
    diff = diffrecreal(alpha, getgtermpbc3d, ming, minr, volume)
    do while (diff < -tolerance .and. alpha <= huge(1.0_wp))
       alpha = 2.0_wp * alpha
       diff = diffrecreal(alpha, getgtermpbc3d, ming, minr, volume)
    end do
    if (alpha > huge(1.0_wp)) then
       ierror = 1
    elseif (alpha == alphainit) then
       ierror = 2
    end if
    if (ierror == 0) then
       alphaleft = 0.5_wp * alpha
       do while (diff < tolerance .and. alpha <= huge(1.0_wp))
          alpha = 2.0_wp * alpha
          diff = diffrecreal(alpha, getgtermpbc3d, ming, minr, volume)
       end do
       if (alpha > huge(1.0_wp)) then
          ierror = 3
       end if
    end if
    if (ierror == 0) then
       alpharight = alpha
       alpha = (alphaleft + alpharight) / 2.0
       iiter = 0
       diff = diffrecreal(alpha, getgtermpbc3d, ming, minr, volume)
       do while (abs(diff) > tolerance .and. iiter <= nsearchiter)
          if (diff < 0) then
             alphaleft = alpha
          else
             alpharight = alpha
          end if
          alpha = (alphaleft + alpharight) / 2.0
          diff = diffrecreal(alpha, getgtermpbc3d, ming, minr, volume)
          iiter = iiter + 1
       end do
       if (iiter > nsearchiter) then
          ierror = 4
       end if
    end if
    if (ierror /= 0) then
       !alpha = exp(-0.310104 * log(volume) + 0.786382) / 2.0
       call env%error('Failed to determine the optimal alpha for Ewald sum', source)
    end if
References diffrecreal(), getgtermpbc3d(), and nsearchiter.
Referenced by xtb_type_coulomb::setupboundaryconditions().
getrterm()
pure real(wp) function xtb_coulomb_ewald::getrterm (real(wp), intent(in) rr, real(wp), intent(in) alpha) private
Returns the max. value of a term in the real space part of the Ewald summation.
Parameters
[in] rr Length of the real space vector
[in] alpha Parameter of the Ewald summation
Returns
Real space term
Definition at line 489 of file ewald.f90.
    real(wp), intent(in) :: rr
    real(wp), intent(in) :: alpha
    real(wp) :: rTerm
    rterm = erfc(alpha*rr)/rr
Referenced by diffrecreal(), xtb_coulomb_klopmanohno::getcoulombmatrixpbc3d(), xtb_coulomb_gaussian::getcoulombmatrixpbc3d(), xtb_type_coulomb::getcoulombmatrixpbc3d(), and getmaxr().
Variable Documentation
nsearchiter
integer, parameter xtb_coulomb_ewald::nsearchiter = 30 private
Nr. of max. bisection steps.
Definition at line 33 of file ewald.f90.
    integer, parameter :: nSearchIter = 30
Referenced by getmaxg(), getmaxr(), and getoptimalalpha().