My Project: xtb_iniq Module Reference
xtb_iniq Module Reference
Functions/Subroutines
subroutine iniqcn (nat, nel, at, z, xyz, chrg, kchrg1, q, cn, version, verbose)
pure subroutine iniqcn_vtb (nat, nel, at, z, xyz, chrg, q, cn)
pure subroutine iniqcn_gfn1 (nat, nel, at, z, xyz, chrg, kchrg1, q, cn)
pure subroutine iniqcn_gfn2 (nat, nel, at, z, xyz, chrg, q, cn)
pure subroutine gasteiger_partition (nat, at, xyz, en, q)
Variables
integer, dimension(1:86), parameter, private metal = [ 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
Function/Subroutine Documentation
gasteiger_partition()
pure subroutine xtb_iniq::gasteiger_partition (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(in) en, real(wp), dimension(nat), intent(inout) q)
Definition at line 329 of file iniq.f90.
 !  get data from parameter modules
    use xtb_mctc_param, only : rcov => covalent_radius_d3
    implicit none
    integer, intent(in)    :: nat
    integer, intent(in)    :: at(nat)
    real(wp),intent(in)    :: xyz(3,nat)
    real(wp),intent(in)    :: en(nat)
    real(wp),intent(inout) :: q(nat)
    integer  :: i,j
    real(wp) :: tmp,r2,rav,den,rexp
    do i = 1, nat
       tmp = 0.0_wp
       do j = 1, nat
          if (i.eq.j) cycle
          r2 = sqrt(sum( (xyz(:,j) - xyz(:,i))**2 ))
          rav = 0.5_wp * ( rcov(at(i))+rcov(at(j)) )
          den = en(i) - en(j)
          rexp = (rav/r2)**6
          tmp = tmp + den*rexp
       enddo
       q(i) = q(i) + tmp
    enddo
Referenced by iniqcn_gfn1(), iniqcn_gfn2(), and iniqcn_vtb().
iniqcn()
subroutine xtb_iniq::iniqcn (integer, intent(in) nat, integer, intent(in) nel, integer, dimension(nat), intent(in) at, real(wp), dimension(nat), intent(in) z, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) chrg, real(wp), intent(in) kchrg1, real(wp), dimension(nat), intent(out) q, real(wp), dimension(nat), intent(out) cn, integer, intent(in) version, logical, intent(in), optional verbose)
Definition at line 51 of file iniq.f90.
    use, intrinsic :: iso_fortran_env, only : id => output_unit
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: nel
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: z(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: chrg
    real(wp),intent(in)  :: kchrg1
    real(wp),intent(out) :: q(nat)
    real(wp),intent(out) :: cn(nat)
    integer, intent(in)  :: version
    logical, intent(in),optional :: verbose
    integer  :: i
    real(wp) :: dipole(3)
    logical :: pr
    if (present(verbose)) then
       pr = verbose
    else
       pr = .false.
    endif
 !  print some header if requested
    if (pr) then
       write(id,'(a)')
       write(id,'(''doing Grimme-Gasteiger EN-charges'')')
    endif
 !  select the variant of Grimme-Gasteiger charges based on the version number
    if (version.le.0) then
       call iniqcn_vtb(nat,nel,at,z,xyz,chrg,q,cn)
    else if (version.eq.1) then
       if (pr) write(id,'(''using D3 CN'')')
       call iniqcn_gfn1(nat,nel,at,z,xyz,chrg,kchrg1,q,cn)
    else
       if (pr) write(id,'(''using GFN CN'')')
       call iniqcn_gfn2(nat,nel,at,z,xyz,chrg,q,cn)
    endif
 !  calculate the dipole moment of the guess charges if requested
    if (pr) then
       dipole = 0.0_wp
       do i = 1, nat
          dipole(1)=dipole(1)+xyz(1,i)*q(i)
          dipole(2)=dipole(2)+xyz(2,i)*q(i)
          dipole(3)=dipole(3)+xyz(3,i)*q(i)
       enddo
       write(id,'(1x,''sum q :'',1x,d14.7)') sum(q)
       write(id,'(1x,''point charge moment (au)'')')
       write(id,'(5x,''X'',7x,''Y'',7x,''Z'')')
       write(id,'(3f9.4,''  total (Debye): '',f8.3)') &
       &  dipole(1), dipole(2), dipole(3), &
       &  sqrt(sum(dipole**2))*2.5418_wp
    endif
References iniqcn_gfn1(), iniqcn_gfn2(), and iniqcn_vtb().
Referenced by xtb_main_setup::newwavefunction_(), and xtb_prog_main::xtbmain().
iniqcn_gfn1()
pure subroutine xtb_iniq::iniqcn_gfn1 (integer, intent(in) nat, integer, intent(in) nel, integer, dimension(nat), intent(in) at, real(wp), dimension(nat), intent(in) z, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) chrg, real(wp), intent(in) kchrg1, real(wp), dimension(nat), intent(out) q, real(wp), dimension(nat), intent(out) cn)
Definition at line 195 of file iniq.f90.
 !  get interface to ncoord
    use xtb_disp_ncoord, only : ncoord_d3
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: nel
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: z(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: chrg
    real(wp),intent(in)  :: kchrg1
    real(wp),intent(out) :: q(nat)
    real(wp),intent(out) :: cn(nat)
    integer :: i
    real(wp),allocatable :: ena(:)
 !  in case it is a single atom, quick return
    if (nat.eq.1) then
       q(1) = real(chrg,wp)
       cn(1) = 0.0_wp
       return
    endif
    allocate( ena(nat), source = 0.0_wp )
 !  get the coordination number
    call ncoord_d3(nat,at,xyz,cn)
 !  correct the CN with effective coordination numbers
    do i = 1, nat
       if (metal(at(i)).gt.0) then
          ena(i) = 0.0_wp
       else
          ena(i) = paulingen(at(i)) - kchrg1*sqrt(cn(i))
       endif
    enddo
 !  the neutral part, start from nuclear charges
    q = z
 !  now distribute the electrons ena dependent
    call gasteiger_partition(nat,at,xyz,ena,q)
 !  normalize to Nel
    q = q * (sum(z)-real(chrg,wp))/sum(z)
 !  make partial charges
    q = z - q
References gasteiger_partition(), metal, xtb_disp_ncoord::ncoord_d3(), xtb_param_paulingen::paulingen, and xtb_mctc_accuracy::wp.
Referenced by iniqcn().
iniqcn_gfn2()
pure subroutine xtb_iniq::iniqcn_gfn2 (integer, intent(in) nat, integer, intent(in) nel, integer, dimension(nat), intent(in) at, real(wp), dimension(nat), intent(in) z, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) chrg, real(wp), dimension(nat), intent(out) q, real(wp), dimension(nat), intent(out) cn)
Definition at line 264 of file iniq.f90.
 !  get interface to ncoord
    use xtb_disp_ncoord, only : ncoord_gfn
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: nel
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: z(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: chrg
    real(wp),intent(out) :: q(nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),parameter   :: kchrg2 = 0.2_wp
    integer :: i
    real(wp),allocatable :: ena(:)
 !  in case it is a single atom, quick return
    if (nat.eq.1) then
       q(1) = real(chrg,wp)
       cn(1) = 0.0_wp
       return
    endif
    allocate( ena(nat), source = 0.0_wp )
 !  get the coordination number
    call ncoord_gfn(nat,at,xyz,cn)
 !  correct the CN with effective coordination numbers
    do i = 1, nat
       if (metal(at(i)).gt.0) then
          ena(i) = kchrg2*sqrt(cn(i)) ! avoid to big q for metals
       else
          ena(i) = paulingen(at(i)) + kchrg2*sqrt(cn(i))
       endif
    enddo
 !  the neutral part, start from nuclear charges
    q = z
 !  now distribute the electrons ena dependent
    call gasteiger_partition(nat,at,xyz,ena,q)
 !  normalize to Nel
    q = q * (sum(z)-real(chrg,wp))/sum(z)
 !  make partial charges
    q = z - q
References gasteiger_partition(), metal, xtb_disp_ncoord::ncoord_gfn(), xtb_param_paulingen::paulingen, and xtb_mctc_accuracy::wp.
Referenced by iniqcn().
iniqcn_vtb()
pure subroutine xtb_iniq::iniqcn_vtb (integer, intent(in) nat, integer, intent(in) nel, integer, dimension(nat), intent(in) at, real(wp), dimension(nat), intent(in) z, real(wp), dimension(3,nat), intent(in) xyz, integer, intent(in) chrg, real(wp), dimension(nat), intent(out) q, real(wp), dimension(nat), intent(out) cn)
Definition at line 128 of file iniq.f90.
 !  get interface to ncoord
    use xtb_disp_ncoord, only : ncoord_d3
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: nel
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: z(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer, intent(in)  :: chrg
    real(wp),intent(out) :: q(nat)
    real(wp),intent(out) :: cn(nat)
    integer :: i
    real(wp),allocatable :: ena(:)
 !  in case it is a single atom, quick return
    if (nat.eq.1) then
       q(1) = real(chrg,wp)
       cn(1) = 0.0_wp
       return
    endif
    allocate( ena(nat), source = 0.0_wp )
 !  get the coordination number
    call ncoord_d3(nat,at,xyz,cn)
 !  uncorrected electronegativites
    do i = 1, nat
       ena(i) = paulingen(at(i))
       if (metal(at(i)).gt.0) cn(i) = 0.0_wp
    enddo
 !  the neutral part, start from nuclear charges
    q = z
 !  now distribute the electrons ena dependent
    call gasteiger_partition(nat,at,xyz,ena,q)
 !  normalize to Nel
    q = q * (sum(z)-real(chrg,wp))/sum(z)
 !  make partial charges
    q = z - q
References gasteiger_partition(), metal, xtb_disp_ncoord::ncoord_d3(), xtb_param_paulingen::paulingen, and xtb_mctc_accuracy::wp.
Referenced by iniqcn().
Variable Documentation
metal
integer, dimension(1:86), parameter, private xtb_iniq::metal = [ 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0] private
Definition at line 23 of file iniq.f90.
    integer, private, parameter :: metal(1:86) = [&
       & 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, &
       & 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, &
       & 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, &
       & 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, &
       & 1, 0, 0, 0, 0, 0]
Referenced by iniqcn_gfn1(), iniqcn_gfn2(), and iniqcn_vtb().