My Project: forpy_mod Module Reference
forpy_mod Module Reference
Data Types
type py_buffer
type pyobject
type pytypeobject
type py_complex
type pymethoddef
type pymoduledef_base
type pymoduledef
interface Py_Initialize
interface Py_IsInitialized
interface Py_Finalize
interface PyImport_ImportModule
interface PyRun_SimpleString
interface PyList_New
interface PyDict_New
interface PyList_Append
interface PyList_Sort
interface PyList_Reverse
interface PyList_Insert
interface PyLong_FromLongLong
interface PyLong_AsLongLongAndOverflow
interface Py_DecRef
interface Py_IncRef
interface PyObject_GetItem
interface PyObject_SetItem
interface PyObject_Length
interface PyObject_IsTrue
interface PyObject_Str
interface PySequence_SetItem
interface PySequence_GetItem
interface PyTuple_SetItem
interface PyTuple_New
interface PyLong_AsLongLong
interface PyFloat_FromDouble
interface PyFloat_AsDouble
interface PyComplex_FromDoubles
interface PyComplex_AsCComplex
interface PyErr_Occurred
interface PyErr_Print
interface PyErr_Clear
interface PyBytes_FromStringAndSize
interface PyBytes_FromString
interface PyBytes_AsString
interface PyObject_GetAttr
interface PyObject_SetAttr
interface PyObject_DelItem
interface PySequence_DelItem
interface PyObject_Call
interface PyMemoryView_FromBuffer
interface PyMemoryView_FromObject
interface PyObject_GetBuffer
interface PyBuffer_IsContiguous
interface PyBuffer_Release
interface PyObject_IsInstance
interface PyType_IsSubtype
interface PyBool_FromLong
interface PyUnicode_DecodeUTF8
interface PyUnicode_AsUTF8AndSize
interface PyEval_GetBuiltins
interface PyDict_GetItemString
interface PyErr_SetString
interface PyErr_GivenExceptionMatches
interface PySequence_Tuple
interface PySequence_List
interface PyDict_Clear
interface PyDict_Copy
interface PyDict_Items
interface PyDict_Keys
interface PyDict_Values
interface PyBuffer_FillContiguousStrides
interface PySequence_Contains
interface PySequence_Index
interface PySequence_Count
interface PyMapping_HasKey
interface PySequence_Concat
interface PySys_GetObject
interface PyModule_Create2
interface PyModule_AddObject
interface strcmp
interface box_value
interface unbox_value
interface tuple_from_array
type object
Type to represent an arbitrary Python object.
type type_py
Type that represents a "class object". In Python class objects have the type 'type' which we name type_py here.
type sequence
Abstract type that represents sequence objects. Elements of a sequence can be accessed by an index.
type mutablesequence
Abstract type that represents a sequence, whose items can be changed.
type immutablesequence
Abstract type that represents a sequence, whose items can not be changed.
type list
Type that corresponds to a Python list.
type mapping
Abstract type that represents a datastructure that maps keys to values.
type dict
type tuple
Type that corresponds to a Python tuple. Create with tuple_create.
interface tuple_create
Creates a tuple with a given number of items.
interface list_create
Creates a list. Create as empty list or from other object.
type bytes
Type corresponding to Python 'bytes'.
interface bytes_create
Creates a bytes object from Fortran character string or character array.
type str
Type corresponding to Python 'str' - Python's string type.
interface str_create
Creates a str object from Fortran character string or character array.
type unicode
Type corresponding to Python 2 'unicode' or Python 3 'str'.
interface unicode_create
Creates a unicode string from Fortran character string or character array.
type module_py
Type representing a Python module.
type nonetype
Type representing Python's 'None'. Create with NoneType_create.
interface call_py
Interface to call a Python objects (methods or other callables) Arguments (optional) have to be passed as tuple. Keyword arguments (optional) have to be passed as dict.
interface call_py_noret
Interface to call a Python objects (methods or other callables), ignoring the return value. Arguments (optional) have to be passed as tuple. Keyword arguments (optional) have to be passed as dict.
interface assign_py
Creates a new reference to an object. Python equivalent: lhs = rhs Do not forget to destroy lhs after use.
type ndarray
Type that represents a Numpy array.
interface ndarray_create
Create a ndarray from a Fortran array. The ndarray will be a copy of the Fortran array.
interface ndarray_create_nocopy
Create a ndarray wrapper for a Fortran array. NO copy is made, changes to the Fortran array affect the ndarray and vice versa.
interface ndarray_create_empty
Creates an empty ndarray of given shape. Array contains uninitialised values.
interface ndarray_create_zeros
Creates a ndarray of zeroes.
interface ndarray_create_ones
Creates a ndarray of ones.
interface cast
Casts/Transforms between Fortran and Python datatypes.
interface cast_nonstrict
Non-strict casts/transforms between Fortran and Python datatypes.
type pythonmethodtablestrings
just a helper type, not public
type pythonmethodtable
Only used for writing Python extension modules. Datastructure to hold table of methods of your Python extension module. Put exactly one instance at Fortran module level.
type pythonmodule
Only used for writing Python extension modules. Datastructure to hold information about your Python extension module. Put exactly one instance at Fortran module level.
Functions/Subroutines
integer(kind=c_int) function, public forpy_initialize (use_numpy)
Initialisation of forpy module. Must be called before using forpy.
integer(kind=c_int) function forpy_initialize_forpy_globals ()
integer(kind=c_int) function forpy_initialize_sys_argv ()
Sets sys.argv = [''], since some 3rd party Python modules require sys.argv[0] - before Python 3.8 sys.argv does not exist in embedded Python, see https://bugs.python.org/issue32573.
integer(kind=c_int) function forpy_initialize_numpy ()
integer(kind=c_int) function forpy_initialize_none ()
integer(kind=c_int) function forpy_initialize_float ()
integer(kind=c_int) function forpy_initialize_complex ()
integer(kind=c_int) function forpy_initialize_unicode ()
integer(kind=c_int) function forpy_initialize_bool ()
integer(kind=c_int) function forpy_initialize_exceptions ()
subroutine, public forpy_finalize ()
Frees resources used by Python interpreter. Call when finished using forpy.
logical function, public is_long (obj)
Checks if object is a Python long.
logical function, public is_list (obj)
Checks if object is a Python list.
logical function, public is_tuple (obj)
Checks if object is a Python tuple.
logical function, public is_bytes (obj)
Checks if object is a Python bytes.
logical function, public is_dict (obj)
Checks if object is a Python dict.
logical function, public is_float (obj)
Checks if object is a Python float.
logical function, public is_complex (obj)
Checks if object is a Python complex.
logical function, public is_bool (obj)
Checks if object is a Python bool.
logical function, public is_unicode (obj)
Checks if object is a Python unicode.
logical function is_short_int (obj)
logical function, public is_int (obj)
Checks if object is of integer Python type ('int' OR 'long')
logical function, public is_str (obj)
Checks if object is a Python str.
logical function, public is_none (obj)
Checks if object is a Python None.
logical function, public is_null (obj)
Returns true if object is a null-pointer internally. Object is not properly initialised then.
logical function, public is_ndarray (obj)
Checks if object is a Numpy array.
integer(kind=c_long) function check_tp_flags (py_obj, mask)
Helper for type checks.
integer(kind=c_int) function list_create_empty (r)
Creates an empty list. Python equivalent: r = [].
integer(kind=c_int) function list_create_object (r, obj)
Creates a list from given object if possible. Python equivalent: r = list(obj)
integer(kind=c_int) function tuple_create_int32 (r, len)
Creates a tuple with a given number of elements.
integer(kind=c_int) function tuple_create_int64 (r, len)
Creates a tuple with a given number of elements.
integer(kind=c_int) function tuple_create_object (r, obj)
integer(kind=c_int) function, public nonetype_create (r)
Creates a Python None.
integer(kind=c_int) function, public dict_create (r)
Creates an empty Python dictionary. Python: r = {}.
subroutine dict_clear (self)
integer(kind=c_int) function dict_copy (self, dest)
integer(kind=c_int) function dict_keys (self, keys)
integer(kind=c_int) function dict_items (self, items)
integer(kind=c_int) function dict_values (self, values)
integer(kind=c_int) function list_append_object (self, item)
integer(kind=c_int) function list_append_int32 (self, item)
integer(kind=c_int) function list_append_int64 (self, item)
integer(kind=c_int) function list_append_real32 (self, item)
integer(kind=c_int) function list_append_real64 (self, item)
integer(kind=c_int) function list_append_complex_real32 (self, item)
integer(kind=c_int) function list_append_complex_real64 (self, item)
integer(kind=c_int) function list_append_logical (self, item)
integer(kind=c_int) function list_append_char_1d (self, item)
integer(kind=c_int) function list_append_chars (self, item)
integer(kind=c_int) function list_copy (self, dest)
integer(kind=c_int) function list_sort (self)
integer(kind=c_int) function list_reverse (self)
integer(kind=c_int) function list_add (self, result_list, list_to_concatenate)
integer(kind=c_int) function list_insert_int32 (self, ind, item)
integer(kind=c_int) function list_delitem_int32 (self, ind)
integer(kind=c_int) function list_insert_int64 (self, ind, item)
integer(kind=c_int) function list_delitem_int64 (self, ind)
integer(kind=c_int) function sequence_getitem_int32_object (self, item, ind)
integer(kind=c_int) function sequence_getitem_int32_int32 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int32_int64 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int32_real32 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int32_real64 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int32_complex_real32 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int32_complex_real64 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int32_logical (self, item, ind)
integer(kind=c_int) function sequence_getitem_int32_char_1d (self, item, ind)
integer(kind=c_int) function sequence_getitem_int32_chars (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_object (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_int32 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_int64 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_real32 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_real64 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_complex_real32 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_complex_real64 (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_logical (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_char_1d (self, item, ind)
integer(kind=c_int) function sequence_getitem_int64_chars (self, item, ind)
integer(kind=c_int) function sequence_len_int32 (self, length)
integer(kind=c_int) function sequence_len_int64 (self, length)
integer(kind=c_int) function mapping_len_int32 (self, length)
integer(kind=c_int) function mapping_len_int64 (self, length)
integer(kind=c_int) function sequence_index_int32 (self, ind, item)
integer(kind=c_int) function sequence_count_int32 (self, the_count, item)
integer(kind=c_int) function sequence_index_int64 (self, ind, item)
integer(kind=c_int) function sequence_count_int64 (self, the_count, item)
integer(kind=c_int) function sequence_contains (self, contain_flag, item)
integer(kind=c_int) function mutablesequence_setitem_int32_object (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int32_int32 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int32_int64 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int32_real32 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int32_real64 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int32_complex_real32 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int32_complex_real64 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int32_logical (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int32_char_1d (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int32_chars (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_object (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_int32 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_int64 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_real32 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_real64 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_complex_real32 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_complex_real64 (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_logical (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_char_1d (self, ind, item)
integer(kind=c_int) function mutablesequence_setitem_int64_chars (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_int32 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_int64 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_real32 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_real64 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_complex_real32 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_complex_real64 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_logical (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_char_1d (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_chars (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_int32 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_int64 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_real32 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_real64 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_complex_real32 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_complex_real64 (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_logical (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_char_1d (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_chars (self, ind, item)
integer(kind=c_int) function tuple_setitem_int32_object (self, ind, item)
integer(kind=c_int) function tuple_setitem_int64_object (self, ind, item)
integer(kind=c_int) function tuple_add (self, result_tuple, tuple_to_concatenate)
integer(kind=c_int) function object_getattribute (self, attr, attr_name)
integer(kind=c_int) function object_setattr (self, attr_name, attr_value)
integer(kind=c_int) function object_delattr (self, attr_name)
type(c_ptr) function object_get_c_ptr (self)
Get C pointer to an object, needed for developing Python extensions.
subroutine object_destroy (self)
integer(kind=c_int) function mapping_getitem_object_object (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_object (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_int32 (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_int64 (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_real32 (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_real64 (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_complex_real32 (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_complex_real64 (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_logical (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_char_1d (self, item, key)
integer(kind=c_int) function mapping_getitem_int32_chars (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_object (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_int32 (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_int64 (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_real32 (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_real64 (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_complex_real32 (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_complex_real64 (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_logical (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_char_1d (self, item, key)
integer(kind=c_int) function mapping_getitem_int64_chars (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_object (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_int32 (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_int64 (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_real32 (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_real64 (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_complex_real32 (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_complex_real64 (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_logical (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_char_1d (self, item, key)
integer(kind=c_int) function mapping_getitem_chars_chars (self, item, key)
integer(kind=c_int) function mapping_setitem_object_object (self, key, item)
integer(kind=c_int) function mapping_delitem_object (self, key)
integer(kind=c_int) function mapping_setitem_int32_object (self, key, item)
integer(kind=c_int) function mapping_delitem_int32 (self, key)
integer(kind=c_int) function mapping_setitem_int32_int32 (self, key, item)
integer(kind=c_int) function mapping_setitem_int32_int64 (self, key, item)
integer(kind=c_int) function mapping_setitem_int32_real32 (self, key, item)
integer(kind=c_int) function mapping_setitem_int32_real64 (self, key, item)
integer(kind=c_int) function mapping_setitem_int32_complex_real32 (self, key, item)
integer(kind=c_int) function mapping_setitem_int32_complex_real64 (self, key, item)
integer(kind=c_int) function mapping_setitem_int32_logical (self, key, item)
integer(kind=c_int) function mapping_setitem_int32_char_1d (self, key, item)
integer(kind=c_int) function mapping_setitem_int32_chars (self, key, item)
integer(kind=c_int) function mapping_setitem_int64_object (self, key, item)
integer(kind=c_int) function mapping_delitem_int64 (self, key)
integer(kind=c_int) function mapping_setitem_int64_int32 (self, key, item)
integer(kind=c_int) function mapping_setitem_int64_int64 (self, key, item)
integer(kind=c_int) function mapping_setitem_int64_real32 (self, key, item)
integer(kind=c_int) function mapping_setitem_int64_real64 (self, key, item)
integer(kind=c_int) function mapping_setitem_int64_complex_real32 (self, key, item)
integer(kind=c_int) function mapping_setitem_int64_complex_real64 (self, key, item)
integer(kind=c_int) function mapping_setitem_int64_logical (self, key, item)
integer(kind=c_int) function mapping_setitem_int64_char_1d (self, key, item)
integer(kind=c_int) function mapping_setitem_int64_chars (self, key, item)
integer(kind=c_int) function mapping_setitem_chars_object (self, key, item)
integer(kind=c_int) function mapping_delitem_chars (self, key)
integer(kind=c_int) function mapping_setitem_chars_int32 (self, key, item)
integer(kind=c_int) function mapping_setitem_chars_int64 (self, key, item)
integer(kind=c_int) function mapping_setitem_chars_real32 (self, key, item)
integer(kind=c_int) function mapping_setitem_chars_real64 (self, key, item)
integer(kind=c_int) function mapping_setitem_chars_complex_real32 (self, key, item)
integer(kind=c_int) function mapping_setitem_chars_complex_real64 (self, key, item)
integer(kind=c_int) function mapping_setitem_chars_logical (self, key, item)
integer(kind=c_int) function mapping_setitem_chars_char_1d (self, key, item)
integer(kind=c_int) function mapping_setitem_chars_chars (self, key, item)
integer(kind=c_int) function mapping_contains (self, contain_flag, item)
integer(kind=c_int) function dict_get_object_object (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_object (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_int32 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_int64 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_real32 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_real64 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_complex_real32 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_complex_real64 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_logical (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_char_1d (self, item, key, default_value)
integer(kind=c_int) function dict_get_int32_chars (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_object (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_int32 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_int64 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_real32 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_real64 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_complex_real32 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_complex_real64 (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_logical (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_char_1d (self, item, key, default_value)
integer(kind=c_int) function dict_get_int64_chars (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_object (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_int32 (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_int64 (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_real32 (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_real64 (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_complex_real32 (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_complex_real64 (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_logical (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_char_1d (self, item, key, default_value)
integer(kind=c_int) function dict_get_chars_chars (self, item, key, default_value)
integer(kind=c_int) function dict_setdefault_object_object (self, the_value, key, default_value)
integer(kind=c_int) function dict_get_helper (self, item_ptr, key_ptr, default_value_ptr, setdefault)
integer(kind=c_int) function dict_get_helper2 (self, item_ptr, key_ptr)
integer(kind=c_int) function bytes_create_chars (r, string)
integer(kind=c_int) function bytes_create_char_1d (r, string)
integer(kind=c_int) function unicode_create_chars (r, string)
integer(kind=c_int) function unicode_create_char_1d (r, string)
integer(kind=c_int) function str_create_chars (r, string)
integer(kind=c_int) function str_create_char_1d (r, string)
integer(kind=c_int) function str_create_object (r, obj)
integer(kind=c_int) function, public import_py (mod_py, mod_name)
Import a Python module.
integer(kind=c_int) function call_py_attribute (return_value, obj, attr_name, args, kwargs)
Calling an object (method, function...) that is a member of another Python object (module,...).
integer(kind=c_int) function call_py_object (return_value, obj_to_call, args, kwargs)
Calling a Python object (method, function...).
integer(kind=c_int) function call_py_object_nokwargs (return_value, obj_to_call, args)
Python equivalent: return_value = obj_to_call(*args)
integer(kind=c_int) function call_py_object_noargs (return_value, obj_to_call)
Python equivalent: return_value = obj_to_call()
integer(kind=c_int) function call_py_object_only_kwargs (return_value, obj_to_call, kwargs)
Python equivalent: return_value = obj_to_call(**kwargs)
integer(kind=c_int) function call_py_noret_attribute (obj, attr_name, args, kwargs)
Python equivalent: obj.attr_name(*args, **kwargs)
integer(kind=c_int) function call_py_noret_object (obj_to_call, args, kwargs)
Python equivalent: obj.attr_name(*args, **kwargs)
integer(kind=c_int) function ndarray_create_nocopy_int32_1d (res, array)
integer(kind=c_int) function ndarray_create_int32_1d (res, array)
integer(kind=c_int) function get_data_int32_1d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_int64_1d (res, array)
integer(kind=c_int) function ndarray_create_int64_1d (res, array)
integer(kind=c_int) function get_data_int64_1d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_real32_1d (res, array)
integer(kind=c_int) function ndarray_create_real32_1d (res, array)
integer(kind=c_int) function get_data_real32_1d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_real64_1d (res, array)
integer(kind=c_int) function ndarray_create_real64_1d (res, array)
integer(kind=c_int) function get_data_real64_1d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_complex_real32_1d (res, array)
integer(kind=c_int) function ndarray_create_complex_real32_1d (res, array)
integer(kind=c_int) function get_data_complex_real32_1d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_complex_real64_1d (res, array)
integer(kind=c_int) function ndarray_create_complex_real64_1d (res, array)
integer(kind=c_int) function get_data_complex_real64_1d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_int32_2d (res, array)
integer(kind=c_int) function ndarray_create_int32_2d (res, array)
integer(kind=c_int) function get_data_int32_2d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_int64_2d (res, array)
integer(kind=c_int) function ndarray_create_int64_2d (res, array)
integer(kind=c_int) function get_data_int64_2d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_real32_2d (res, array)
integer(kind=c_int) function ndarray_create_real32_2d (res, array)
integer(kind=c_int) function get_data_real32_2d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_real64_2d (res, array)
integer(kind=c_int) function ndarray_create_real64_2d (res, array)
integer(kind=c_int) function get_data_real64_2d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_complex_real32_2d (res, array)
integer(kind=c_int) function ndarray_create_complex_real32_2d (res, array)
integer(kind=c_int) function get_data_complex_real32_2d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_complex_real64_2d (res, array)
integer(kind=c_int) function ndarray_create_complex_real64_2d (res, array)
integer(kind=c_int) function get_data_complex_real64_2d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_int32_3d (res, array)
integer(kind=c_int) function ndarray_create_int32_3d (res, array)
integer(kind=c_int) function get_data_int32_3d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_int64_3d (res, array)
integer(kind=c_int) function ndarray_create_int64_3d (res, array)
integer(kind=c_int) function get_data_int64_3d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_real32_3d (res, array)
integer(kind=c_int) function ndarray_create_real32_3d (res, array)
integer(kind=c_int) function get_data_real32_3d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_real64_3d (res, array)
integer(kind=c_int) function ndarray_create_real64_3d (res, array)
integer(kind=c_int) function get_data_real64_3d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_complex_real32_3d (res, array)
integer(kind=c_int) function ndarray_create_complex_real32_3d (res, array)
integer(kind=c_int) function get_data_complex_real32_3d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_complex_real64_3d (res, array)
integer(kind=c_int) function ndarray_create_complex_real64_3d (res, array)
integer(kind=c_int) function get_data_complex_real64_3d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_int32_4d (res, array)
integer(kind=c_int) function ndarray_create_int32_4d (res, array)
integer(kind=c_int) function get_data_int32_4d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_int64_4d (res, array)
integer(kind=c_int) function ndarray_create_int64_4d (res, array)
integer(kind=c_int) function get_data_int64_4d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_real32_4d (res, array)
integer(kind=c_int) function ndarray_create_real32_4d (res, array)
integer(kind=c_int) function get_data_real32_4d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_real64_4d (res, array)
integer(kind=c_int) function ndarray_create_real64_4d (res, array)
integer(kind=c_int) function get_data_real64_4d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_complex_real32_4d (res, array)
integer(kind=c_int) function ndarray_create_complex_real32_4d (res, array)
integer(kind=c_int) function get_data_complex_real32_4d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_complex_real64_4d (res, array)
integer(kind=c_int) function ndarray_create_complex_real64_4d (res, array)
integer(kind=c_int) function get_data_complex_real64_4d (self, ptr, order)
Get pointer to data of numpy array.
integer(kind=c_int) function ndarray_create_nocopy_helper (res, array_c_loc, array_shape, ndim, itemsize, format_c_string)
integer(kind=c_int) function ndarray_create_nocopy_helper_py2 (res, array_c_loc, array_shape, ndim, itemsize, dtype)
integer(kind=c_int) function ndarray_reshape_helper (reshaped_array, array, new_shape, order)
integer(kind=c_int) function get_data_helper (self, raw_ptr, shape_info, ndim, format_c_string, order)
Get pointer to data of numpy array.
integer(kind=c_int) function get_data_helper_check_dtype (buffer_format, format_c_string)
subroutine get_shape_info_helper (shape_info, shape_ptr, order)
integer(kind=c_int) function ndarray_transpose (self, transposed_array)
Return transpose of a ndarray.
integer(kind=c_int) function ndarray_copy (self, array_copy, order)
Returns copy of a ndarray.
logical function ndarray_is_ordered (self, order)
Checks if data of ndarray has a specific storage-order.
integer(kind=c_int) function ndarray_get_dtype_name (self, dtype_name)
Returns type string of ndarray.
integer(kind=c_int) function ndarray_ndim_int32 (self, ndim)
Returns dimensionality of ndarray (ndarray.ndim)
integer(kind=c_int) function ndarray_ndim_int64 (self, ndim)
Returns dimensionality of ndarray (ndarray.ndim)
integer(kind=c_int) function ndarray_create_empty_aint32 (array, a_shape, dtype, order)
integer(kind=c_int) function ndarray_create_empty_aint64 (array, a_shape, dtype, order)
integer(kind=c_int) function ndarray_create_empty_int32 (array, length, dtype, order)
integer(kind=c_int) function ndarray_create_empty_int64 (array, length, dtype, order)
integer(kind=c_int) function ndarray_create_zeros_aint32 (array, a_shape, dtype, order)
integer(kind=c_int) function ndarray_create_zeros_aint64 (array, a_shape, dtype, order)
integer(kind=c_int) function ndarray_create_zeros_int32 (array, length, dtype, order)
integer(kind=c_int) function ndarray_create_zeros_int64 (array, length, dtype, order)
integer(kind=c_int) function ndarray_create_ones_aint32 (array, a_shape, dtype, order)
integer(kind=c_int) function ndarray_create_ones_aint64 (array, a_shape, dtype, order)
integer(kind=c_int) function ndarray_create_ones_int32 (array, length, dtype, order)
integer(kind=c_int) function ndarray_create_ones_int64 (array, length, dtype, order)
integer(kind=c_int) function ndarray_create_special_impl_int32 (array, creator_function, a_shape, dtype, order)
integer(kind=c_int) function ndarray_create_special_getargs_int32 (args, a_shape)
integer(kind=c_int) function ndarray_create_special_helper_int32 (array, creator_function, a_shape, kwargs)
integer(kind=c_int) function tuple_from_array_int32 (tu, arr)
Helper function: create tuple from integer array.
integer(kind=c_int) function ndarray_create_special_impl_int64 (array, creator_function, a_shape, dtype, order)
integer(kind=c_int) function ndarray_create_special_getargs_int64 (args, a_shape)
integer(kind=c_int) function ndarray_create_special_helper_int64 (array, creator_function, a_shape, kwargs)
integer(kind=c_int) function tuple_from_array_int64 (tu, arr)
Helper function: create tuple from integer array.
integer(kind=c_int) function box_value_int32_as_long (obj, the_value)
integer(kind=c_int) function box_value_int64_as_long (obj, the_value)
integer(kind=c_int) function box_value_real32 (obj, the_value)
integer(kind=c_int) function box_value_real64 (obj, the_value)
integer(kind=c_int) function box_value_complex_real32 (obj, the_value)
integer(kind=c_int) function box_value_complex_real64 (obj, the_value)
integer(kind=c_int) function box_value_chars (obj, the_value)
integer(kind=c_int) function box_value_chars_as_bytestr (obj, the_value)
integer(kind=c_int) function box_value_chars_as_unicodestr (obj, the_value)
integer(kind=c_int) function box_value_char_1d (obj, the_value)
integer(kind=c_int) function box_value_char_1d_as_bytestr (obj, the_value)
integer(kind=c_int) function box_value_char_1d_as_unicodestr (obj, the_value)
integer(kind=c_int) function box_value_logical (obj, the_value)
integer(kind=c_int) function unbox_value_int32 (the_value, obj)
integer(kind=c_int) function unbox_value_int64 (the_value, obj)
integer(kind=c_int) function unbox_value_real32 (the_value, obj)
integer(kind=c_int) function unbox_value_real64 (the_value, obj)
integer(kind=c_int) function unbox_value_complex_real32 (the_value, obj)
integer(kind=c_int) function unbox_value_complex_real64 (the_value, obj)
integer(kind=c_int) function unbox_value_logical (the_value, obj)
integer(kind=c_int) function unbox_value_char_1d (the_value, obj)
integer(kind=c_int) function unbox_value_chars (the_value, obj)
subroutine char_1d_to_chars (inp, outp)
integer(kind=c_int) function cast_to_list (list_out, obj)
integer(kind=c_int) function cast_to_dict (dict_out, obj)
integer(kind=c_int) function cast_to_tuple (tuple_out, obj)
integer(kind=c_int) function cast_to_nonetype (NoneType_out, obj)
integer(kind=c_int) function cast_to_ndarray (ndarray_out, obj)
integer(kind=c_int) function cast_to_str (str_out, obj)
integer(kind=c_int) function cast_to_bytes (bytes_out, obj)
integer(kind=c_int) function cast_to_unicode (unicode_out, obj)
integer(kind=c_int) function cast_nonstrict_to_list (list_out, obj)
integer(kind=c_int) function cast_nonstrict_to_tuple (tuple_out, obj)
integer(kind=c_int) function cast_nonstrict_to_str (str_out, obj)
integer(kind=c_int) function cast_to_object (plain_obj, obj)
integer(kind=c_int) function cast_to_int32 (out_value, obj)
integer(kind=c_int) function cast_to_int32_flex (out_value, obj, strict)
integer(kind=c_int) function cast_nonstrict_to_int32 (out_value, obj)
integer(kind=c_int) function cast_to_int64 (out_value, obj)
integer(kind=c_int) function cast_to_int64_flex (out_value, obj, strict)
integer(kind=c_int) function cast_nonstrict_to_int64 (out_value, obj)
integer(kind=c_int) function cast_to_real32 (out_value, obj)
integer(kind=c_int) function cast_to_real32_flex (out_value, obj, strict)
integer(kind=c_int) function cast_nonstrict_to_real32 (out_value, obj)
integer(kind=c_int) function cast_to_real64 (out_value, obj)
integer(kind=c_int) function cast_to_real64_flex (out_value, obj, strict)
integer(kind=c_int) function cast_nonstrict_to_real64 (out_value, obj)
integer(kind=c_int) function cast_to_complex_real32 (out_value, obj)
integer(kind=c_int) function cast_to_complex_real32_flex (out_value, obj, strict)
integer(kind=c_int) function cast_nonstrict_to_complex_real32 (out_value, obj)
integer(kind=c_int) function cast_to_complex_real64 (out_value, obj)
integer(kind=c_int) function cast_to_complex_real64_flex (out_value, obj, strict)
integer(kind=c_int) function cast_nonstrict_to_complex_real64 (out_value, obj)
integer(kind=c_int) function cast_to_logical (out_value, obj)
integer(kind=c_int) function cast_to_logical_flex (out_value, obj, strict)
integer(kind=c_int) function cast_nonstrict_to_logical (out_value, obj)
integer(kind=c_int) function cast_to_chars (out_value, obj)
integer(kind=c_int) function cast_from_chars (obj, in_value)
integer(kind=c_int) function cast_from_char_1d (obj, in_value)
integer(kind=c_int) function cast_to_char_1d (out_value, obj)
integer(kind=c_int) function cast_nonstrict_to_chars (out_value, obj)
integer(kind=c_int) function cast_from_int32 (obj, in_value)
integer(kind=c_int) function cast_from_int64 (obj, in_value)
integer(kind=c_int) function cast_from_real32 (obj, in_value)
integer(kind=c_int) function cast_from_real64 (obj, in_value)
integer(kind=c_int) function cast_from_complex_real32 (obj, in_value)
integer(kind=c_int) function cast_from_complex_real64 (obj, in_value)
integer(kind=c_int) function cast_from_logical (obj, in_value)
subroutine assign_py_object (lhs, rhs)
Equivalent to the following Python code: lhs = rhs.
subroutine assign_py_list (lhs, rhs)
Equivalent to the following Python code: lhs = rhs.
subroutine assign_py_tuple (lhs, rhs)
Equivalent to the following Python code: lhs = rhs.
subroutine assign_py_dict (lhs, rhs)
Equivalent to the following Python code: lhs = rhs.
subroutine assign_py_ndarray (lhs, rhs)
Equivalent to the following Python code: lhs = rhs.
subroutine assign_py_type_py (lhs, rhs)
Equivalent to the following Python code: lhs = rhs.
subroutine assign_py_module_py (lhs, rhs)
Equivalent to the following Python code: lhs = rhs.
subroutine assign_py_nonetype (lhs, rhs)
Equivalent to the following Python code: lhs = rhs.
logical function, public exception_matches (exc)
Checks if a certain type of exception has occurred.
subroutine, public err_clear ()
Clears an exception.
subroutine, public err_print ()
Prints and clears exception. If no exception has occurred, does nothing.
logical function, public have_exception ()
returns .true. if an exception has occurred
subroutine, public raise_exception (exc_type, message)
raises an exception
type(c_ptr) function pythonmodule_init (self, module_name, doc_string, method_table)
integer(kind=c_int) function pythonmodule_add_object (self, object_name, obj)
add an object as a member to a module
subroutine pythonmethodtable_init (self, num_methods)
subroutine pythonmethodtable_add_method (self, method_name, doc_string, flags, method_funptr)
type(c_ptr) function pythonmethodtable_get (self)
subroutine, public unsafe_cast_from_c_ptr (obj, ptr)
Creates an [[object]] from a type(c_ptr), no type checks.
integer(kind=c_int) function, public print_py (obj, kwargs)
Python's print function.
integer(kind=c_int) function, public get_sys_path (paths)
Getting the list of module search paths: sys.path.
integer(kind=c_int) function, public run_string (string)
Run Python code that is given as string.
Variables
integer(kind=c_int), parameter, public no_numpy_error = 2_C_INT
integer(kind=c_int), parameter, public exception_error = -1_C_INT
integer(kind=c_int), parameter, public meth_varargs = 1_C_INT
integer(kind=c_int), parameter, public meth_keywords = 2_C_INT
integer(kind=c_int), parameter, public meth_noargs = 4_C_INT
integer(kind=c_int), parameter, public meth_o = 8_C_INT
integer, parameter, public py_ssize_t_kind = C_INTPTR_T
integer, save, private global_forpy_initialized = 0
type(c_ptr), save, private global_numpy_mod = C_NULL_PTR
type(c_ptr), save, private global_numpy_asarray_method = C_NULL_PTR
type(c_ptr), save, private global_py_nonestruct_ptr = C_NULL_PTR
type(c_ptr), save, private global_py_truestruct_ptr = C_NULL_PTR
type(c_ptr), save, private global_py_falsestruct_ptr = C_NULL_PTR
type(c_ptr), save, private global_numpy_ndarray_typeobj = C_NULL_PTR
type(c_ptr), save, private global_pyfloat_type_ptr = C_NULL_PTR
type(c_ptr), save, private global_pycomplex_type_ptr = C_NULL_PTR
type(c_ptr), save, private global_pybool_type_ptr = C_NULL_PTR
type(c_ptr), save, private global_pyunicode_type_ptr = C_NULL_PTR
type(type_py), save, public arithmeticerror
type(type_py), save, public assertionerror
type(type_py), save, public attributeerror
type(type_py), save, public baseexception
type(type_py), save, public buffererror
type(type_py), save, public byteswarning
type(type_py), save, public deprecationwarning
type(type_py), save, public eoferror
type(type_py), save, public environmenterror
type(type_py), save, public exception
type(type_py), save, public floatingpointerror
type(type_py), save, public futurewarning
type(type_py), save, public generatorexit
type(type_py), save, public ioerror
type(type_py), save, public importerror
type(type_py), save, public importwarning
type(type_py), save, public indentationerror
type(type_py), save, public indexerror
type(type_py), save, public keyerror
type(type_py), save, public keyboardinterrupt
type(type_py), save, public lookuperror
type(type_py), save, public memoryerror
type(type_py), save, public nameerror
type(type_py), save, public notimplementederror
type(type_py), save, public oserror
type(type_py), save, public overflowerror
type(type_py), save, public pendingdeprecationwarning
type(type_py), save, public referenceerror
type(type_py), save, public runtimeerror
type(type_py), save, public runtimewarning
type(type_py), save, public standarderror
type(type_py), save, public stopiteration
type(type_py), save, public syntaxerror
type(type_py), save, public syntaxwarning
type(type_py), save, public systemerror
type(type_py), save, public systemexit
type(type_py), save, public taberror
type(type_py), save, public typeerror
type(type_py), save, public unboundlocalerror
type(type_py), save, public unicodedecodeerror
type(type_py), save, public unicodeencodeerror
type(type_py), save, public unicodeerror
type(type_py), save, public unicodetranslateerror
type(type_py), save, public unicodewarning
type(type_py), save, public userwarning
type(type_py), save, public valueerror
type(type_py), save, public warning
type(type_py), save, public zerodivisionerror
Function/Subroutine Documentation
assign_py_dict()
subroutine forpy_mod::assign_py_dict (type(dict), intent(out) lhs, class(dict), intent(in) rhs) private
Equivalent to the following Python code: lhs = rhs.
do not forget to destroy lhs after usage
Definition at line 11541 of file forpy_mod.F90.
   type(dict), intent(out) :: lhs
   class(dict), intent(in) :: rhs
   lhs%py_object = rhs%py_object
   call py_incref(lhs%py_object)
assign_py_list()
subroutine forpy_mod::assign_py_list (type(list), intent(out) lhs, class(list), intent(in) rhs) private
Equivalent to the following Python code: lhs = rhs.
do not forget to destroy lhs after usage
Definition at line 11519 of file forpy_mod.F90.
   type(list), intent(out) :: lhs
   class(list), intent(in) :: rhs
   lhs%py_object = rhs%py_object
   call py_incref(lhs%py_object)
assign_py_module_py()
subroutine forpy_mod::assign_py_module_py (type(module_py), intent(out) lhs, class(module_py), intent(in) rhs) private
Equivalent to the following Python code: lhs = rhs.
do not forget to destroy lhs after usage
Definition at line 11574 of file forpy_mod.F90.
   type(module_py), intent(out) :: lhs
   class(module_py), intent(in) :: rhs
   lhs%py_object = rhs%py_object
   call py_incref(lhs%py_object)
assign_py_ndarray()
subroutine forpy_mod::assign_py_ndarray (type(ndarray), intent(out) lhs, class(ndarray), intent(in) rhs) private
Equivalent to the following Python code: lhs = rhs.
do not forget to destroy lhs after usage
Definition at line 11552 of file forpy_mod.F90.
   type(ndarray), intent(out) :: lhs
   class(ndarray), intent(in) :: rhs
   lhs%py_object = rhs%py_object
   call py_incref(lhs%py_object)
assign_py_nonetype()
subroutine forpy_mod::assign_py_nonetype (type(nonetype), intent(out) lhs, class(nonetype), intent(in) rhs) private
Equivalent to the following Python code: lhs = rhs.
do not forget to destroy lhs after usage
Definition at line 11585 of file forpy_mod.F90.
   type(NoneType), intent(out) :: lhs
   class(NoneType), intent(in) :: rhs
   lhs%py_object = rhs%py_object
   call py_incref(lhs%py_object)
assign_py_object()
subroutine forpy_mod::assign_py_object (type(object), intent(out) lhs, class(object), intent(in) rhs) private
Equivalent to the following Python code: lhs = rhs.
do not forget to destroy lhs after usage
Definition at line 11508 of file forpy_mod.F90.
   type(object), intent(out) :: lhs
   class(object), intent(in) :: rhs
   lhs%py_object = rhs%py_object
   call py_incref(lhs%py_object)
assign_py_tuple()
subroutine forpy_mod::assign_py_tuple (type(tuple), intent(out) lhs, class(tuple), intent(in) rhs) private
Equivalent to the following Python code: lhs = rhs.
do not forget to destroy lhs after usage
Definition at line 11530 of file forpy_mod.F90.
   type(tuple), intent(out) :: lhs
   class(tuple), intent(in) :: rhs
   lhs%py_object = rhs%py_object
   call py_incref(lhs%py_object)
assign_py_type_py()
subroutine forpy_mod::assign_py_type_py (type(type_py), intent(out) lhs, class(type_py), intent(in) rhs) private
Equivalent to the following Python code: lhs = rhs.
do not forget to destroy lhs after usage
Definition at line 11563 of file forpy_mod.F90.
   type(type_py), intent(out) :: lhs
   class(type_py), intent(in) :: rhs
   lhs%py_object = rhs%py_object
   call py_incref(lhs%py_object)
box_value_char_1d()
integer(kind=c_int) function forpy_mod::box_value_char_1d (type(c_ptr), intent(out) obj, character(kind=c_char), dimension(:), intent(in) the_value) private
Definition at line 10576 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   character(kind=C_CHAR), dimension(:), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
 #ifdef PYTHON2
   ierror = box_value_char_1d_as_bytestr(obj, the_value)
 #else
   ierror = box_value_char_1d_as_unicodestr(obj, the_value)
 #endif
box_value_char_1d_as_bytestr()
integer(kind=c_int) function forpy_mod::box_value_char_1d_as_bytestr (type(c_ptr), intent(out) obj, character(kind=c_char), dimension(:), intent(in) the_value) private
Definition at line 10589 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   character(kind=C_CHAR), dimension(:), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: length
   ierror = 0_c_int
   length = size(the_value)
   obj = pybytes_fromstringandsize(the_value, length)
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
box_value_char_1d_as_unicodestr()
integer(kind=c_int) function forpy_mod::box_value_char_1d_as_unicodestr (type(c_ptr), intent(out) obj, character(kind=c_char), dimension(:), intent(in) the_value) private
Definition at line 10608 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   character(kind=C_CHAR), dimension(:), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: length
   ierror = 0_c_int
   length = size(the_value)
   obj = pyunicode_decodeutf8(the_value, length, "strict" // c_null_char)
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
box_value_chars()
integer(kind=c_int) function forpy_mod::box_value_chars (type(c_ptr), intent(out) obj, character(kind=c_char, len=*), intent(in) the_value) private
Definition at line 10525 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   character(kind=C_CHAR, len=*), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
 #ifdef PYTHON2
   ierror = box_value_chars_as_bytestr(obj, the_value)
 #else
   ierror = box_value_chars_as_unicodestr(obj, the_value)
 #endif
box_value_chars_as_bytestr()
integer(kind=c_int) function forpy_mod::box_value_chars_as_bytestr (type(c_ptr), intent(out) obj, character(kind=c_char, len=*), intent(in) the_value) private
Definition at line 10538 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   character(kind=C_CHAR, len=*), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: length
   ierror = 0_c_int
   length = len(the_value)
   obj = pybytes_fromstringandsize(the_value, length)
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
box_value_chars_as_unicodestr()
integer(kind=c_int) function forpy_mod::box_value_chars_as_unicodestr (type(c_ptr), intent(out) obj, character(kind=c_char, len=*), intent(in) the_value) private
Definition at line 10557 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   character(kind=C_CHAR, len=*), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: length
   ierror = 0_c_int
   length = len(the_value)
   obj = pyunicode_decodeutf8(the_value, length, "strict" // c_null_char)
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
box_value_complex_real32()
integer(kind=c_int) function forpy_mod::box_value_complex_real32 (type(c_ptr), intent(out) obj, complex(kind=real32), intent(in) the_value) private
Definition at line 10496 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   complex(kind=real32), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   obj = pycomplex_fromdoubles(real(the_value, c_double), real(aimag(the_value), c_double))
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
box_value_complex_real64()
integer(kind=c_int) function forpy_mod::box_value_complex_real64 (type(c_ptr), intent(out) obj, complex(kind=real64), intent(in) the_value) private
Definition at line 10510 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   complex(kind=real64), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   obj = pycomplex_fromdoubles(real(the_value, c_double), real(aimag(the_value), c_double))
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
box_value_int32_as_long()
integer(kind=c_int) function forpy_mod::box_value_int32_as_long (type(c_ptr), intent(out) obj, integer(kind=int32), intent(in) the_value) private
Definition at line 10372 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   integer(kind=int32), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   integer(kind=C_LONG_LONG) :: tmp
   ierror = 0_c_int
   tmp = int(the_value, c_long_long)
   obj = pylong_fromlonglong(tmp)
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
box_value_int64_as_long()
integer(kind=c_int) function forpy_mod::box_value_int64_as_long (type(c_ptr), intent(out) obj, integer(kind=int64), intent(in) the_value) private
Definition at line 10391 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   integer(kind=int64), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   integer(kind=C_LONG_LONG) :: tmp
   ierror = 0_c_int
   tmp = int(the_value, c_long_long)
   obj = pylong_fromlonglong(tmp)
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
box_value_logical()
integer(kind=c_int) function forpy_mod::box_value_logical (type(c_ptr), intent(out) obj, logical, intent(in) the_value) private
Definition at line 10628 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   logical, intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   if (the_value) then
     obj = global_py_truestruct_ptr
     call py_incref(obj)
   else
     obj = global_py_falsestruct_ptr
     call py_incref(obj)
   endif
box_value_real32()
integer(kind=c_int) function forpy_mod::box_value_real32 (type(c_ptr), intent(out) obj, real(kind=real32), intent(in) the_value) private
Definition at line 10458 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   real(kind=real32), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   real(kind=c_double) :: tmp
   ierror = 0_c_int
   tmp = real(the_value, c_double)
   obj = pyfloat_fromdouble(tmp)
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
box_value_real64()
integer(kind=c_int) function forpy_mod::box_value_real64 (type(c_ptr), intent(out) obj, real(kind=real64), intent(in) the_value) private
Definition at line 10477 of file forpy_mod.F90.
   type(c_ptr), intent(out) :: obj
   real(kind=real64), intent(in) :: the_value
   integer(kind=C_INT) :: ierror
   real(kind=c_double) :: tmp
   ierror = 0_c_int
   tmp = real(the_value, c_double)
   obj = pyfloat_fromdouble(tmp)
   if (.not. c_associated(obj)) then
     ierror = exception_error
   endif
bytes_create_char_1d()
integer(kind=c_int) function forpy_mod::bytes_create_char_1d (type(bytes), intent(out) r, character(kind=c_char), dimension(:), intent(in) string) private
Definition at line 7003 of file forpy_mod.F90.
   type(bytes), intent(out) :: r
   character(kind=C_CHAR), dimension(:), intent(in) :: string
   integer(kind=C_INT) :: ierror
   ierror = box_value_char_1d_as_bytestr(r%py_object, string)
bytes_create_chars()
integer(kind=c_int) function forpy_mod::bytes_create_chars (type(bytes), intent(out) r, character(kind=c_char, len=*), intent(in) string) private
Definition at line 6995 of file forpy_mod.F90.
   type(bytes), intent(out) :: r
   character(kind=C_CHAR, len=*), intent(in) :: string
   integer(kind=C_INT) :: ierror
   ierror = box_value_chars_as_bytestr(r%py_object, string)
call_py_attribute()
integer(kind=c_int) function forpy_mod::call_py_attribute (type(object), intent(out) return_value, class(object), intent(in) obj, character(kind=c_char, len=*), intent(in) attr_name, class(tuple), intent(in), optional args, class(dict), intent(in), optional kwargs) private
Calling an object (method, function...) that is a member of another Python object (module,...).
Python equivalent: return_value = obj.attr_name(*args, **kwargs)
Definition at line 7089 of file forpy_mod.F90.
   type(object), intent(out) :: return_value
   class(object), intent(in) :: obj
   character(kind=C_CHAR, len=*), intent(in) :: attr_name
   class(tuple), intent(in), optional :: args
   class(dict), intent(in), optional :: kwargs
   integer(kind=C_INT) :: ierror
   type(object) :: obj_to_call
   ierror = obj%getattribute(obj_to_call, attr_name)
   if (ierror == 0) then
     if (present(kwargs) .and. present(args)) then
       ierror = call_py_object(return_value, obj_to_call, args, kwargs)
     elseif (present(args)) then
       ierror = call_py_object_nokwargs(return_value, obj_to_call, args)
     elseif (present(kwargs)) then
       ierror = call_py_object_only_kwargs(return_value, obj_to_call, kwargs)
     else
       ierror = call_py_object_noargs(return_value, obj_to_call)
     endif
     call obj_to_call%destroy()
   endif
call_py_noret_attribute()
integer(kind=c_int) function forpy_mod::call_py_noret_attribute (class(object), intent(in) obj, character(kind=c_char, len=*), intent(in) attr_name, class(tuple), intent(in), optional args, class(dict), intent(in), optional kwargs) private
Python equivalent: obj.attr_name(*args, **kwargs)
Definition at line 7191 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   character(kind=C_CHAR, len=*), intent(in) :: attr_name
   class(tuple), intent(in), optional :: args
   class(dict), intent(in), optional :: kwargs
   integer(kind=C_INT) :: ierror
   type(object) :: return_value
   if (present(kwargs) .and. present(args)) then
     ierror = call_py(return_value, obj, attr_name, args, kwargs)
   elseif (present(args)) then
     ierror = call_py(return_value, obj, attr_name, args)
   elseif (present(kwargs)) then
     ierror = call_py(return_value, obj, attr_name, kwargs=kwargs)
   else
     ierror = call_py(return_value, obj, attr_name)
   endif
   call return_value%destroy
call_py_noret_object()
integer(kind=c_int) function forpy_mod::call_py_noret_object (class(object), intent(in) obj_to_call, class(tuple), intent(in), optional args, class(dict), intent(in), optional kwargs) private
Python equivalent: obj.attr_name(*args, **kwargs)
Definition at line 7215 of file forpy_mod.F90.
   class(object), intent(in) :: obj_to_call
   class(tuple), intent(in), optional :: args
   class(dict), intent(in), optional :: kwargs
   integer(kind=C_INT) :: ierror
   type(object) :: return_value
   if (present(kwargs) .and. present(args)) then
     ierror = call_py(return_value, obj_to_call, args, kwargs)
   elseif (present(args)) then
     ierror = call_py(return_value, obj_to_call, args)
   elseif (present(kwargs)) then
     ierror = call_py(return_value, obj_to_call, kwargs=kwargs)
   else
     ierror = call_py(return_value, obj_to_call)
   endif
   call return_value%destroy
call_py_object()
integer(kind=c_int) function forpy_mod::call_py_object (type(object), intent(out) return_value, class(object), intent(in) obj_to_call, class(tuple), intent(in) args, class(dict), intent(in) kwargs) private
Calling a Python object (method, function...).
Python equivalent: return_value = obj_to_call(*args, **kwargs)
Definition at line 7120 of file forpy_mod.F90.
   type(object), intent(out) :: return_value
   class(object), intent(in) :: obj_to_call
   class(tuple), intent(in):: args
   class(dict), intent(in) :: kwargs
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: kw, args_ptr
   ierror = 0_c_int
   kw = kwargs%py_object
   args_ptr = args%py_object
   return_value%py_object = pyobject_call(obj_to_call%py_object, args_ptr, kw)
   if (.not. c_associated(return_value%py_object)) then
     ierror = exception_error
   endif
call_py_object_noargs()
integer(kind=c_int) function forpy_mod::call_py_object_noargs (type(object), intent(out) return_value, class(object), intent(in) obj_to_call) private
Python equivalent: return_value = obj_to_call()
Definition at line 7160 of file forpy_mod.F90.
   type(object), intent(out) :: return_value
   class(object), intent(in) :: obj_to_call
   integer(kind=C_INT) :: ierror
   type(tuple) :: args
   ierror = tuple_create(args, 0)
   if (ierror == 0) then
     ierror = call_py_object_nokwargs(return_value, obj_to_call, args)
     call args%destroy
   endif
call_py_object_nokwargs()
integer(kind=c_int) function forpy_mod::call_py_object_nokwargs (type(object), intent(out) return_value, class(object), intent(in) obj_to_call, class(tuple), intent(in) args) private
Python equivalent: return_value = obj_to_call(*args)
Definition at line 7144 of file forpy_mod.F90.
   type(object), intent(out) :: return_value
   class(object), intent(in) :: obj_to_call
   class(tuple), intent(in):: args
   integer(kind=C_INT) :: ierror
   type(dict) :: kwargs
   ierror = dict_create(kwargs)
   if (ierror == 0) then
     ierror = call_py_object(return_value, obj_to_call, args, kwargs)
     call kwargs%destroy
   endif
call_py_object_only_kwargs()
integer(kind=c_int) function forpy_mod::call_py_object_only_kwargs (type(object), intent(out) return_value, class(object), intent(in) obj_to_call, class(dict), intent(in) kwargs) private
Python equivalent: return_value = obj_to_call(**kwargs)
Definition at line 7175 of file forpy_mod.F90.
   type(object), intent(out) :: return_value
   class(object), intent(in) :: obj_to_call
   class(dict), intent(in) :: kwargs
   integer(kind=C_INT) :: ierror
   type(tuple) :: args
   ierror = tuple_create(args, 0)
   if (ierror == 0) then
     ierror = call_py_object(return_value, obj_to_call, args, kwargs)
     call args%destroy
   endif
cast_from_char_1d()
integer(kind=c_int) function forpy_mod::cast_from_char_1d (type(object), intent(out) obj, character(kind=c_char), dimension(:), intent(in) in_value) private
Definition at line 11396 of file forpy_mod.F90.
   type(object), intent(out) :: obj
   character(kind=C_CHAR), dimension(:), intent(in) :: in_value
   integer(kind=C_INT) :: ierror
   ierror = box_value(obj%py_object, in_value)
cast_from_chars()
integer(kind=c_int) function forpy_mod::cast_from_chars (type(object), intent(out) obj, character(kind=c_char, len=*), intent(in) in_value) private
Definition at line 11388 of file forpy_mod.F90.
   type(object), intent(out) :: obj
   character(kind=C_CHAR, len=*), intent(in) :: in_value
   integer(kind=C_INT) :: ierror
   ierror = box_value(obj%py_object, in_value)
cast_from_complex_real32()
integer(kind=c_int) function forpy_mod::cast_from_complex_real32 (type(object), intent(out) obj, complex(kind=real32), intent(in) in_value) private
Definition at line 11474 of file forpy_mod.F90.
   type(object), intent(out) :: obj
   complex(kind=real32), intent(in) :: in_value
   integer(kind=C_INT) :: ierror
   ierror = box_value(obj%py_object, in_value)
cast_from_complex_real64()
integer(kind=c_int) function forpy_mod::cast_from_complex_real64 (type(object), intent(out) obj, complex(kind=real64), intent(in) in_value) private
Definition at line 11482 of file forpy_mod.F90.
   type(object), intent(out) :: obj
   complex(kind=real64), intent(in) :: in_value
   integer(kind=C_INT) :: ierror
   ierror = box_value(obj%py_object, in_value)
cast_from_int32()
integer(kind=c_int) function forpy_mod::cast_from_int32 (type(object), intent(out) obj, integer(kind=int32), intent(in) in_value) private
Definition at line 11442 of file forpy_mod.F90.
   type(object), intent(out) :: obj
   integer(kind=int32), intent(in) :: in_value
   integer(kind=C_INT) :: ierror
   ierror = box_value(obj%py_object, in_value)
cast_from_int64()
integer(kind=c_int) function forpy_mod::cast_from_int64 (type(object), intent(out) obj, integer(kind=int64), intent(in) in_value) private
Definition at line 11450 of file forpy_mod.F90.
   type(object), intent(out) :: obj
   integer(kind=int64), intent(in) :: in_value
   integer(kind=C_INT) :: ierror
   ierror = box_value(obj%py_object, in_value)
cast_from_logical()
integer(kind=c_int) function forpy_mod::cast_from_logical (type(object), intent(out) obj, logical, intent(in) in_value) private
Definition at line 11490 of file forpy_mod.F90.
   type(object), intent(out) :: obj
   logical, intent(in) :: in_value
   integer(kind=C_INT) :: ierror
   ierror = box_value(obj%py_object, in_value)
cast_from_real32()
integer(kind=c_int) function forpy_mod::cast_from_real32 (type(object), intent(out) obj, real(kind=real32), intent(in) in_value) private
Definition at line 11458 of file forpy_mod.F90.
   type(object), intent(out) :: obj
   real(kind=real32), intent(in) :: in_value
   integer(kind=C_INT) :: ierror
   ierror = box_value(obj%py_object, in_value)
cast_from_real64()
integer(kind=c_int) function forpy_mod::cast_from_real64 (type(object), intent(out) obj, real(kind=real64), intent(in) in_value) private
Definition at line 11466 of file forpy_mod.F90.
   type(object), intent(out) :: obj
   real(kind=real64), intent(in) :: in_value
   integer(kind=C_INT) :: ierror
   ierror = box_value(obj%py_object, in_value)
cast_nonstrict_to_chars()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_chars (character(kind=c_char, len=:), intent(out), allocatable out_value, class(object), intent(in) obj) private
Definition at line 11417 of file forpy_mod.F90.
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: str_obj
   if (is_str(obj) .or. is_bytes(obj) .or. is_unicode(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
     return
   endif
   str_obj = pyobject_str(obj%py_object)
   if (.not. c_associated(str_obj)) then
     ierror = exception_error
     return
   endif
   ierror = unbox_value(out_value, str_obj)
   call py_decref(str_obj)
cast_nonstrict_to_complex_real32()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_complex_real32 (complex(kind=real32), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11297 of file forpy_mod.F90.
   complex(kind=real32), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = cast(out_value, obj, .false.)
cast_nonstrict_to_complex_real64()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_complex_real64 (complex(kind=real64), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11331 of file forpy_mod.F90.
   complex(kind=real64), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = cast(out_value, obj, .false.)
cast_nonstrict_to_int32()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_int32 (integer(kind=int32), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11161 of file forpy_mod.F90.
   integer(kind=int32), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = cast(out_value, obj, .false.)
cast_nonstrict_to_int64()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_int64 (integer(kind=int64), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11195 of file forpy_mod.F90.
   integer(kind=int64), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = cast(out_value, obj, .false.)
cast_nonstrict_to_list()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_list (type(list), intent(out) list_out, class(object), intent(in) obj) private
Definition at line 11080 of file forpy_mod.F90.
   type(list), intent(out) :: list_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_list(obj)) then
     ierror = 0_c_int
     list_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     ierror = list_create(list_out, obj)
   endif
cast_nonstrict_to_logical()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_logical (logical, intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11365 of file forpy_mod.F90.
   logical, intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = cast(out_value, obj, .false.)
cast_nonstrict_to_real32()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_real32 (real(kind=real32), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11229 of file forpy_mod.F90.
   real(kind=real32), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = cast(out_value, obj, .false.)
cast_nonstrict_to_real64()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_real64 (real(kind=real64), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11263 of file forpy_mod.F90.
   real(kind=real64), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = cast(out_value, obj, .false.)
cast_nonstrict_to_str()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_str (type(str), intent(out) str_out, class(object), intent(in) obj) private
Definition at line 11108 of file forpy_mod.F90.
   type(str), intent(out) :: str_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_str(obj)) then
     ierror = 0_c_int
     str_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     ierror = str_create(str_out, obj)
   endif
cast_nonstrict_to_tuple()
integer(kind=c_int) function forpy_mod::cast_nonstrict_to_tuple (type(tuple), intent(out) tuple_out, class(object), intent(in) obj) private
Definition at line 11094 of file forpy_mod.F90.
   type(tuple), intent(out) :: tuple_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_tuple(obj)) then
     ierror = 0_c_int
     tuple_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     ierror = tuple_create(tuple_out, obj)
   endif
cast_to_bytes()
integer(kind=c_int) function forpy_mod::cast_to_bytes (type(bytes), intent(out) bytes_out, class(object), intent(in) obj) private
Definition at line 11047 of file forpy_mod.F90.
   type(bytes), intent(out) :: bytes_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_bytes(obj)) then
     ierror = 0_c_int
     bytes_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     bytes_out%py_object = c_null_ptr
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to bytes.")
   endif
cast_to_char_1d()
integer(kind=c_int) function forpy_mod::cast_to_char_1d (character(kind=c_char), dimension(:), pointer out_value, class(object), intent(in) obj) private
Definition at line 11404 of file forpy_mod.F90.
   character(kind=C_CHAR), dimension(:), pointer :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_str(obj) .or. is_bytes(obj) .or. is_unicode(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to character(kind=C_CHAR), dimension(:), pointer.")
   endif
cast_to_chars()
integer(kind=c_int) function forpy_mod::cast_to_chars (character(kind=c_char, len=:), intent(out), allocatable out_value, class(object), intent(in) obj) private
Definition at line 11375 of file forpy_mod.F90.
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_str(obj) .or. is_bytes(obj) .or. is_unicode(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to character(kind=C_CHAR, len=:).")
   endif
cast_to_complex_real32()
integer(kind=c_int) function forpy_mod::cast_to_complex_real32 (complex(kind=real32), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11271 of file forpy_mod.F90.
   complex(kind=real32), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_complex(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to complex(kind=real32).")
   endif
cast_to_complex_real32_flex()
integer(kind=c_int) function forpy_mod::cast_to_complex_real32_flex (complex(kind=real32), intent(out) out_value, class(object), intent(in) obj, logical, intent(in) strict) private
Definition at line 11284 of file forpy_mod.F90.
   complex(kind=real32), intent(out) :: out_value
   class(object), intent(in) :: obj
   logical, intent(in) :: strict
   integer(kind=C_INT) :: ierror
   if (.not. strict) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = cast_to_complex_real32(out_value, obj)
   endif
cast_to_complex_real64()
integer(kind=c_int) function forpy_mod::cast_to_complex_real64 (complex(kind=real64), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11305 of file forpy_mod.F90.
   complex(kind=real64), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_complex(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to complex(kind=real64).")
   endif
cast_to_complex_real64_flex()
integer(kind=c_int) function forpy_mod::cast_to_complex_real64_flex (complex(kind=real64), intent(out) out_value, class(object), intent(in) obj, logical, intent(in) strict) private
Definition at line 11318 of file forpy_mod.F90.
   complex(kind=real64), intent(out) :: out_value
   class(object), intent(in) :: obj
   logical, intent(in) :: strict
   integer(kind=C_INT) :: ierror
   if (.not. strict) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = cast_to_complex_real64(out_value, obj)
   endif
cast_to_dict()
integer(kind=c_int) function forpy_mod::cast_to_dict (type(dict), intent(out) dict_out, class(object), intent(in) obj) private
Definition at line 10967 of file forpy_mod.F90.
   type(dict), intent(out) :: dict_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_dict(obj)) then
     ierror = 0_c_int
     dict_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     dict_out%py_object = c_null_ptr
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to dict.")
   endif
cast_to_int32()
integer(kind=c_int) function forpy_mod::cast_to_int32 (integer(kind=int32), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11135 of file forpy_mod.F90.
   integer(kind=int32), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_int(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to integer(kind=int32).")
   endif
cast_to_int32_flex()
integer(kind=c_int) function forpy_mod::cast_to_int32_flex (integer(kind=int32), intent(out) out_value, class(object), intent(in) obj, logical, intent(in) strict) private
Definition at line 11148 of file forpy_mod.F90.
   integer(kind=int32), intent(out) :: out_value
   class(object), intent(in) :: obj
   logical, intent(in) :: strict
   integer(kind=C_INT) :: ierror
   if (.not. strict) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = cast_to_int32(out_value, obj)
   endif
cast_to_int64()
integer(kind=c_int) function forpy_mod::cast_to_int64 (integer(kind=int64), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11169 of file forpy_mod.F90.
   integer(kind=int64), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_int(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to integer(kind=int64).")
   endif
cast_to_int64_flex()
integer(kind=c_int) function forpy_mod::cast_to_int64_flex (integer(kind=int64), intent(out) out_value, class(object), intent(in) obj, logical, intent(in) strict) private
Definition at line 11182 of file forpy_mod.F90.
   integer(kind=int64), intent(out) :: out_value
   class(object), intent(in) :: obj
   logical, intent(in) :: strict
   integer(kind=C_INT) :: ierror
   if (.not. strict) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = cast_to_int64(out_value, obj)
   endif
cast_to_list()
integer(kind=c_int) function forpy_mod::cast_to_list (type(list), intent(out) list_out, class(object), intent(in) obj) private
Definition at line 10951 of file forpy_mod.F90.
   type(list), intent(out) :: list_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_list(obj)) then
     ierror = 0_c_int
     list_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     list_out%py_object = c_null_ptr
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to list.")
   endif
cast_to_logical()
integer(kind=c_int) function forpy_mod::cast_to_logical (logical, intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11339 of file forpy_mod.F90.
   logical, intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_bool(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to logical.")
   endif
cast_to_logical_flex()
integer(kind=c_int) function forpy_mod::cast_to_logical_flex (logical, intent(out) out_value, class(object), intent(in) obj, logical, intent(in) strict) private
Definition at line 11352 of file forpy_mod.F90.
   logical, intent(out) :: out_value
   class(object), intent(in) :: obj
   logical, intent(in) :: strict
   integer(kind=C_INT) :: ierror
   if (.not. strict) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = cast_to_logical(out_value, obj)
   endif
cast_to_ndarray()
integer(kind=c_int) function forpy_mod::cast_to_ndarray (type(ndarray), intent(out) ndarray_out, class(object), intent(in) obj) private
Definition at line 11015 of file forpy_mod.F90.
   type(ndarray), intent(out) :: ndarray_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_ndarray(obj)) then
     ierror = 0_c_int
     ndarray_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     ndarray_out%py_object = c_null_ptr
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to ndarray.")
   endif
cast_to_nonetype()
integer(kind=c_int) function forpy_mod::cast_to_nonetype (type(nonetype), intent(out) NoneType_out, class(object), intent(in) obj) private
Definition at line 10999 of file forpy_mod.F90.
   type(NoneType), intent(out) :: NoneType_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_none(obj)) then
     ierror = 0_c_int
     nonetype_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     nonetype_out%py_object = c_null_ptr
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to NoneType.")
   endif
cast_to_object()
integer(kind=c_int) function forpy_mod::cast_to_object (type(object), intent(out) plain_obj, class(object), intent(in) obj) private
Definition at line 11123 of file forpy_mod.F90.
   type(object), intent(out) :: plain_obj
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   plain_obj%py_object = obj%py_object
   call py_incref(obj%py_object)
cast_to_real32()
integer(kind=c_int) function forpy_mod::cast_to_real32 (real(kind=real32), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11203 of file forpy_mod.F90.
   real(kind=real32), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_float(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to real(kind=real32).")
   endif
cast_to_real32_flex()
integer(kind=c_int) function forpy_mod::cast_to_real32_flex (real(kind=real32), intent(out) out_value, class(object), intent(in) obj, logical, intent(in) strict) private
Definition at line 11216 of file forpy_mod.F90.
   real(kind=real32), intent(out) :: out_value
   class(object), intent(in) :: obj
   logical, intent(in) :: strict
   integer(kind=C_INT) :: ierror
   if (.not. strict) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = cast_to_real32(out_value, obj)
   endif
cast_to_real64()
integer(kind=c_int) function forpy_mod::cast_to_real64 (real(kind=real64), intent(out) out_value, class(object), intent(in) obj) private
Definition at line 11237 of file forpy_mod.F90.
   real(kind=real64), intent(out) :: out_value
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_float(obj)) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to real(kind=real64).")
   endif
cast_to_real64_flex()
integer(kind=c_int) function forpy_mod::cast_to_real64_flex (real(kind=real64), intent(out) out_value, class(object), intent(in) obj, logical, intent(in) strict) private
Definition at line 11250 of file forpy_mod.F90.
   real(kind=real64), intent(out) :: out_value
   class(object), intent(in) :: obj
   logical, intent(in) :: strict
   integer(kind=C_INT) :: ierror
   if (.not. strict) then
     ierror = unbox_value(out_value, obj%py_object)
   else
     ierror = cast_to_real64(out_value, obj)
   endif
cast_to_str()
integer(kind=c_int) function forpy_mod::cast_to_str (type(str), intent(out) str_out, class(object), intent(in) obj) private
Definition at line 11031 of file forpy_mod.F90.
   type(str), intent(out) :: str_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_str(obj)) then
     ierror = 0_c_int
     str_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     str_out%py_object = c_null_ptr
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to str.")
   endif
cast_to_tuple()
integer(kind=c_int) function forpy_mod::cast_to_tuple (type(tuple), intent(out) tuple_out, class(object), intent(in) obj) private
Definition at line 10983 of file forpy_mod.F90.
   type(tuple), intent(out) :: tuple_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_tuple(obj)) then
     ierror = 0_c_int
     tuple_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     tuple_out%py_object = c_null_ptr
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to tuple.")
   endif
cast_to_unicode()
integer(kind=c_int) function forpy_mod::cast_to_unicode (type(unicode), intent(out) unicode_out, class(object), intent(in) obj) private
Definition at line 11063 of file forpy_mod.F90.
   type(unicode), intent(out) :: unicode_out
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   if (is_unicode(obj)) then
     ierror = 0_c_int
     unicode_out%py_object = obj%py_object
     call py_incref(obj%py_object)
   else
     unicode_out%py_object = c_null_ptr
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Could not cast to unicode.")
   endif
char_1d_to_chars()
subroutine forpy_mod::char_1d_to_chars (character(kind=c_char), dimension(:), intent(in) inp, character(kind=c_char, len=:), intent(inout), allocatable outp) private
Definition at line 10927 of file forpy_mod.F90.
   character(kind=C_CHAR), dimension(:), intent(in) :: inp
   character(kind=C_CHAR, len=:), allocatable, intent(inout) :: outp
   integer :: length, ii
   length = size(inp)
   if (allocated(outp)) then
     deallocate(outp)
   endif
   allocate(character(kind=C_CHAR, len=length) :: outp)
   do ii = 1, length
     outp(ii:ii) = inp(ii)
   enddo
check_tp_flags()
integer(kind=c_long) function forpy_mod::check_tp_flags (type(c_ptr), intent(in) py_obj, integer(kind=c_long), intent(in) mask) private
Helper for type checks.
Definition at line 2638 of file forpy_mod.F90.
   type(c_ptr), intent(in) :: py_obj
   integer(kind=C_LONG), intent(in) :: mask
   integer(kind=C_LONG) :: res
   type(PyObject), pointer :: obj_ptr
   type(PyTypeObject), pointer :: type_ptr
   call c_f_pointer(py_obj, obj_ptr)
   call c_f_pointer(obj_ptr%ob_type, type_ptr)
   res = iand(type_ptr%tp_flags, mask)
dict_clear()
subroutine forpy_mod::dict_clear (class(dict), intent(inout) self) private
Definition at line 2768 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   call pydict_clear(self%py_object)
dict_copy()
integer(kind=c_int) function forpy_mod::dict_copy (class(dict), intent(in) self, type(dict), intent(out) dest) private
Definition at line 2773 of file forpy_mod.F90.
   class(dict), intent(in) :: self
   type(dict), intent(out) :: dest
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   dest%py_object = pydict_copy(self%py_object)
   if (.not. c_associated(dest%py_object)) then
     ierror = exception_error
   endif
dict_create()
integer(kind=c_int) function, public forpy_mod::dict_create (type(dict), intent(out) r)
Creates an empty Python dictionary. Python: r = {}.
Parameters
[out] r The created empty dict
Returns
Error code, 0 on success
Definition at line 2754 of file forpy_mod.F90.
   type(dict), intent(out) :: r
   integer(kind=C_INT) :: ierror
   r%py_object = pydict_new()
   ierror = 0_c_int
   if (.not. c_associated(r%py_object)) then
     ierror = exception_error
   endif
dict_get_chars_char_1d()
integer(kind=c_int) function forpy_mod::dict_get_chars_char_1d (class(dict), intent(inout) self, character(kind=c_char), dimension(:), intent(out), pointer item, character(kind=c_char, len=*), intent(in) key, character(kind=c_char), dimension(:), intent(in), pointer default_value) private
Definition at line 6874 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   character(kind=C_CHAR), dimension(:), pointer, intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   character(kind=C_CHAR), dimension(:), pointer, intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_chars_chars()
integer(kind=c_int) function forpy_mod::dict_get_chars_chars (class(dict), intent(inout) self, character(kind=c_char, len=:), intent(out), allocatable item, character(kind=c_char, len=*), intent(in) key, character(kind=c_char, len=:), intent(in), allocatable default_value) private
Definition at line 6901 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   character(kind=C_CHAR, len=:), allocatable, intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_chars_complex_real32()
integer(kind=c_int) function forpy_mod::dict_get_chars_complex_real32 (class(dict), intent(inout) self, complex(kind=real32), intent(out) item, character(kind=c_char, len=*), intent(in) key, complex(kind=real32), intent(in) default_value) private
Definition at line 6793 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   complex(kind=real32), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   complex(kind=real32), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_chars_complex_real64()
integer(kind=c_int) function forpy_mod::dict_get_chars_complex_real64 (class(dict), intent(inout) self, complex(kind=real64), intent(out) item, character(kind=c_char, len=*), intent(in) key, complex(kind=real64), intent(in) default_value) private
Definition at line 6820 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   complex(kind=real64), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   complex(kind=real64), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_chars_int32()
integer(kind=c_int) function forpy_mod::dict_get_chars_int32 (class(dict), intent(inout) self, integer(kind=int32), intent(out) item, character(kind=c_char, len=*), intent(in) key, integer(kind=int32), intent(in) default_value) private
Definition at line 6685 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   integer(kind=int32), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=int32), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_chars_int64()
integer(kind=c_int) function forpy_mod::dict_get_chars_int64 (class(dict), intent(inout) self, integer(kind=int64), intent(out) item, character(kind=c_char, len=*), intent(in) key, integer(kind=int64), intent(in) default_value) private
Definition at line 6712 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   integer(kind=int64), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=int64), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_chars_logical()
integer(kind=c_int) function forpy_mod::dict_get_chars_logical (class(dict), intent(inout) self, logical, intent(out) item, character(kind=c_char, len=*), intent(in) key, logical, intent(in) default_value) private
Definition at line 6847 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   logical, intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   logical, intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_chars_object()
integer(kind=c_int) function forpy_mod::dict_get_chars_object (class(dict), intent(inout) self, type(object), intent(out) item, character(kind=c_char, len=*), intent(in) key, class(object), intent(in) default_value) private
Definition at line 6669 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   type(object), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   class(object), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror == 0_c_int) then
     ierror = dict_get_helper(self, item%py_object, key_ptr, default_value%py_object, .false.)
     call py_decref(key_ptr)
   endif
Referenced by forpy_mod::dict::get().
dict_get_chars_real32()
integer(kind=c_int) function forpy_mod::dict_get_chars_real32 (class(dict), intent(inout) self, real(kind=real32), intent(out) item, character(kind=c_char, len=*), intent(in) key, real(kind=real32), intent(in) default_value) private
Definition at line 6739 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   real(kind=real32), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   real(kind=real32), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_chars_real64()
integer(kind=c_int) function forpy_mod::dict_get_chars_real64 (class(dict), intent(inout) self, real(kind=real64), intent(out) item, character(kind=c_char, len=*), intent(in) key, real(kind=real64), intent(in) default_value) private
Definition at line 6766 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   real(kind=real64), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   real(kind=real64), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_helper()
integer(kind=c_int) function forpy_mod::dict_get_helper (class(dict), intent(inout) self, type(c_ptr), intent(out) item_ptr, type(c_ptr), intent(in) key_ptr, type(c_ptr), intent(in) default_value_ptr, logical, intent(in) setdefault) private
Definition at line 6944 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   type(c_ptr), intent(out) :: item_ptr
   type(c_ptr), intent(in) :: key_ptr
   type(c_ptr), intent(in) :: default_value_ptr
   logical, intent(in) :: setdefault
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   item_ptr = pyobject_getitem(self%py_object, key_ptr)
   if (.not. c_associated(item_ptr)) then
     !always return default value, when lookup fails
     item_ptr = default_value_ptr
     call py_incref(default_value_ptr)
     if (exception_matches(keyerror)) then
       call err_clear()
       if (setdefault) then
         ierror = pyobject_setitem(self%py_object, key_ptr, default_value_ptr)
       endif
     else
       ierror = exception_error
       return
     endif
   endif
dict_get_helper2()
integer(kind=c_int) function forpy_mod::dict_get_helper2 (class(dict), intent(inout) self, type(c_ptr), intent(out) item_ptr, type(c_ptr), intent(in) key_ptr) private
Definition at line 6973 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   type(c_ptr), intent(out) :: item_ptr
   type(c_ptr), intent(in) :: key_ptr
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   item_ptr = pyobject_getitem(self%py_object, key_ptr)
   if (.not. c_associated(item_ptr)) then
     if (exception_matches(keyerror)) then
       call err_clear()
     else
       ierror = exception_error
       return
     endif
   endif
dict_get_int32_char_1d()
integer(kind=c_int) function forpy_mod::dict_get_int32_char_1d (class(dict), intent(inout) self, character(kind=c_char), dimension(:), intent(out), pointer item, integer(kind=int32), intent(in) key, character(kind=c_char), dimension(:), intent(in), pointer default_value) private
Definition at line 6356 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   character(kind=C_CHAR), dimension(:), pointer, intent(out) :: item
   integer(kind=int32), intent(in) :: key
   character(kind=C_CHAR), dimension(:), pointer, intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int32_chars()
integer(kind=c_int) function forpy_mod::dict_get_int32_chars (class(dict), intent(inout) self, character(kind=c_char, len=:), intent(out), allocatable item, integer(kind=int32), intent(in) key, character(kind=c_char, len=:), intent(in), allocatable default_value) private
Definition at line 6383 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: item
   integer(kind=int32), intent(in) :: key
   character(kind=C_CHAR, len=:), allocatable, intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int32_complex_real32()
integer(kind=c_int) function forpy_mod::dict_get_int32_complex_real32 (class(dict), intent(inout) self, complex(kind=real32), intent(out) item, integer(kind=int32), intent(in) key, complex(kind=real32), intent(in) default_value) private
Definition at line 6275 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   complex(kind=real32), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   complex(kind=real32), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int32_complex_real64()
integer(kind=c_int) function forpy_mod::dict_get_int32_complex_real64 (class(dict), intent(inout) self, complex(kind=real64), intent(out) item, integer(kind=int32), intent(in) key, complex(kind=real64), intent(in) default_value) private
Definition at line 6302 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   complex(kind=real64), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   complex(kind=real64), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int32_int32()
integer(kind=c_int) function forpy_mod::dict_get_int32_int32 (class(dict), intent(inout) self, integer(kind=int32), intent(out) item, integer(kind=int32), intent(in) key, integer(kind=int32), intent(in) default_value) private
Definition at line 6167 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   integer(kind=int32), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=int32), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int32_int64()
integer(kind=c_int) function forpy_mod::dict_get_int32_int64 (class(dict), intent(inout) self, integer(kind=int64), intent(out) item, integer(kind=int32), intent(in) key, integer(kind=int64), intent(in) default_value) private
Definition at line 6194 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   integer(kind=int64), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=int64), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int32_logical()
integer(kind=c_int) function forpy_mod::dict_get_int32_logical (class(dict), intent(inout) self, logical, intent(out) item, integer(kind=int32), intent(in) key, logical, intent(in) default_value) private
Definition at line 6329 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   logical, intent(out) :: item
   integer(kind=int32), intent(in) :: key
   logical, intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int32_object()
integer(kind=c_int) function forpy_mod::dict_get_int32_object (class(dict), intent(inout) self, type(object), intent(out) item, integer(kind=int32), intent(in) key, class(object), intent(in) default_value) private
Definition at line 6151 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   type(object), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   class(object), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror == 0_c_int) then
     ierror = dict_get_helper(self, item%py_object, key_ptr, default_value%py_object, .false.)
     call py_decref(key_ptr)
   endif
Referenced by forpy_mod::dict::get().
dict_get_int32_real32()
integer(kind=c_int) function forpy_mod::dict_get_int32_real32 (class(dict), intent(inout) self, real(kind=real32), intent(out) item, integer(kind=int32), intent(in) key, real(kind=real32), intent(in) default_value) private
Definition at line 6221 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   real(kind=real32), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   real(kind=real32), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int32_real64()
integer(kind=c_int) function forpy_mod::dict_get_int32_real64 (class(dict), intent(inout) self, real(kind=real64), intent(out) item, integer(kind=int32), intent(in) key, real(kind=real64), intent(in) default_value) private
Definition at line 6248 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   real(kind=real64), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   real(kind=real64), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int64_char_1d()
integer(kind=c_int) function forpy_mod::dict_get_int64_char_1d (class(dict), intent(inout) self, character(kind=c_char), dimension(:), intent(out), pointer item, integer(kind=int64), intent(in) key, character(kind=c_char), dimension(:), intent(in), pointer default_value) private
Definition at line 6615 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   character(kind=C_CHAR), dimension(:), pointer, intent(out) :: item
   integer(kind=int64), intent(in) :: key
   character(kind=C_CHAR), dimension(:), pointer, intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int64_chars()
integer(kind=c_int) function forpy_mod::dict_get_int64_chars (class(dict), intent(inout) self, character(kind=c_char, len=:), intent(out), allocatable item, integer(kind=int64), intent(in) key, character(kind=c_char, len=:), intent(in), allocatable default_value) private
Definition at line 6642 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: item
   integer(kind=int64), intent(in) :: key
   character(kind=C_CHAR, len=:), allocatable, intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int64_complex_real32()
integer(kind=c_int) function forpy_mod::dict_get_int64_complex_real32 (class(dict), intent(inout) self, complex(kind=real32), intent(out) item, integer(kind=int64), intent(in) key, complex(kind=real32), intent(in) default_value) private
Definition at line 6534 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   complex(kind=real32), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   complex(kind=real32), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int64_complex_real64()
integer(kind=c_int) function forpy_mod::dict_get_int64_complex_real64 (class(dict), intent(inout) self, complex(kind=real64), intent(out) item, integer(kind=int64), intent(in) key, complex(kind=real64), intent(in) default_value) private
Definition at line 6561 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   complex(kind=real64), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   complex(kind=real64), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int64_int32()
integer(kind=c_int) function forpy_mod::dict_get_int64_int32 (class(dict), intent(inout) self, integer(kind=int32), intent(out) item, integer(kind=int64), intent(in) key, integer(kind=int32), intent(in) default_value) private
Definition at line 6426 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   integer(kind=int32), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=int32), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int64_int64()
integer(kind=c_int) function forpy_mod::dict_get_int64_int64 (class(dict), intent(inout) self, integer(kind=int64), intent(out) item, integer(kind=int64), intent(in) key, integer(kind=int64), intent(in) default_value) private
Definition at line 6453 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   integer(kind=int64), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=int64), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int64_logical()
integer(kind=c_int) function forpy_mod::dict_get_int64_logical (class(dict), intent(inout) self, logical, intent(out) item, integer(kind=int64), intent(in) key, logical, intent(in) default_value) private
Definition at line 6588 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   logical, intent(out) :: item
   integer(kind=int64), intent(in) :: key
   logical, intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int64_object()
integer(kind=c_int) function forpy_mod::dict_get_int64_object (class(dict), intent(inout) self, type(object), intent(out) item, integer(kind=int64), intent(in) key, class(object), intent(in) default_value) private
Definition at line 6410 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   type(object), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   class(object), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror == 0_c_int) then
     ierror = dict_get_helper(self, item%py_object, key_ptr, default_value%py_object, .false.)
     call py_decref(key_ptr)
   endif
Referenced by forpy_mod::dict::get().
dict_get_int64_real32()
integer(kind=c_int) function forpy_mod::dict_get_int64_real32 (class(dict), intent(inout) self, real(kind=real32), intent(out) item, integer(kind=int64), intent(in) key, real(kind=real32), intent(in) default_value) private
Definition at line 6480 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   real(kind=real32), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   real(kind=real32), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_int64_real64()
integer(kind=c_int) function forpy_mod::dict_get_int64_real64 (class(dict), intent(inout) self, real(kind=real64), intent(out) item, integer(kind=int64), intent(in) key, real(kind=real64), intent(in) default_value) private
Definition at line 6507 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   real(kind=real64), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   real(kind=real64), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_ptr, key_ptr
   ierror = box_value(key_ptr, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dict_get_helper2(self, item_ptr, key_ptr)
   if (c_associated(item_ptr) .and. ierror == 0_c_int) then
     ierror = unbox_value(item, item_ptr)
     call py_decref(item_ptr)
   else
     item = default_value
   endif
   call py_decref(key_ptr)
Referenced by forpy_mod::dict::get().
dict_get_object_object()
integer(kind=c_int) function forpy_mod::dict_get_object_object (class(dict), intent(inout) self, type(object), intent(out) item, class(object), intent(in) key, class(object), intent(in) default_value) private
Definition at line 6139 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   type(object), intent(out) :: item
   class(object), intent(in) :: key
   class(object), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   ierror = dict_get_helper(self, item%py_object, key%py_object, default_value%py_object, .false.)
Referenced by forpy_mod::dict::get().
dict_items()
integer(kind=c_int) function forpy_mod::dict_items (class(dict), intent(in) self, type(list), intent(out) items) private
Definition at line 2797 of file forpy_mod.F90.
   class(dict), intent(in) :: self
   type(list), intent(out) :: items
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   items%py_object = pydict_items(self%py_object)
   if (.not. c_associated(items%py_object)) then
     ierror = exception_error
   endif
dict_keys()
integer(kind=c_int) function forpy_mod::dict_keys (class(dict), intent(in) self, type(list), intent(out) keys) private
Definition at line 2785 of file forpy_mod.F90.
   class(dict), intent(in) :: self
   type(list), intent(out) :: keys
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   keys%py_object = pydict_keys(self%py_object)
   if (.not. c_associated(keys%py_object)) then
     ierror = exception_error
   endif
dict_setdefault_object_object()
integer(kind=c_int) function forpy_mod::dict_setdefault_object_object (class(dict), intent(inout) self, type(object), intent(out) the_value, class(object), intent(in) key, class(object), intent(in) default_value) private
Parameters
[out] the_value The value retrieved from the dict.
[in] key Key to retrieve value from.
[in] default_value Default value that is inserted into dict and returned., if key is not present.
Returns
Error code, 0 on success
Definition at line 6929 of file forpy_mod.F90.
   class(dict), intent(inout) :: self
   type(object), intent(out) :: the_value
   class(object), intent(in) :: key
   class(object), intent(in) :: default_value
   integer(kind=C_INT) :: ierror
   ierror = dict_get_helper(self, the_value%py_object, key%py_object, default_value%py_object, .true.)
dict_values()
integer(kind=c_int) function forpy_mod::dict_values (class(dict), intent(in) self, type(list), intent(out) values) private
Definition at line 2809 of file forpy_mod.F90.
   class(dict), intent(in) :: self
   type(list), intent(out) :: values
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   values%py_object = pydict_values(self%py_object)
   if (.not. c_associated(values%py_object)) then
     ierror = exception_error
   endif
err_clear()
subroutine, public forpy_mod::err_clear
Clears an exception.
No effect if no exception happened. Must be called after handling an exception, otherwise future forpy/Python operations can fail in strange ways.
Definition at line 11623 of file forpy_mod.F90.
   call pyerr_clear()
err_print()
subroutine, public forpy_mod::err_print
Prints and clears exception. If no exception has occurred, does nothing.
Definition at line 11628 of file forpy_mod.F90.
   type(c_ptr) :: err_obj
   err_obj = pyerr_occurred()
   ! check if there really is an error, otherwise call to PyErr_Print is fatal
   if (c_associated(err_obj)) then
     call pyerr_print()
   endif
exception_matches()
logical function, public forpy_mod::exception_matches (class(object), intent(in) exc)
Checks if a certain type of exception has occurred.
Example: flag = exception_matches(KeyError) Returns .false. if no exception has occurred.
Definition at line 11602 of file forpy_mod.F90.
   class(object), intent(in) :: exc
   logical :: is_match
   type(c_ptr) :: err_obj
   err_obj = pyerr_occurred()
   if (c_associated(err_obj) .and. c_associated(exc%py_object)) then
     is_match = (pyerr_givenexceptionmatches(err_obj, exc%py_object) == 1)
     return
   endif
   is_match = .false.
forpy_finalize()
subroutine, public forpy_mod::forpy_finalize
Frees resources used by Python interpreter. Call when finished using forpy.
Definition at line 2425 of file forpy_mod.F90.
   global_forpy_initialized = 0
   call py_decref(global_numpy_asarray_method)
   call py_decref(global_numpy_mod)
   global_numpy_asarray_method = c_null_ptr
   global_numpy_mod = c_null_ptr
   call py_finalize()
Referenced by prob_module::prob_func().
forpy_initialize()
integer(kind=c_int) function, public forpy_mod::forpy_initialize (logical, intent(in), optional use_numpy)
Initialisation of forpy module. Must be called before using forpy.
Parameters
[in] use_numpy Set to .false., if you do not need the array features of forpy powered by numpy. (Default: .true.)
Definition at line 1980 of file forpy_mod.F90.
   logical, optional, intent(in) :: use_numpy
   integer(kind=C_INT) :: ierror
   logical :: numpy_flag
   if (present(use_numpy)) then
     numpy_flag = use_numpy
   else
     numpy_flag = .true.
   endif
   ierror = 1_c_int
   if (py_isinitialized() == 0_c_int) then
     call py_initialize()
   endif
   ierror = 0_c_int
   if (global_forpy_initialized == 0) then
     ierror = forpy_initialize_forpy_globals()
     if (ierror == 0_c_int) then
       global_forpy_initialized = 1
     endif
   endif
   if (ierror == 0_c_int .and. numpy_flag &
       .and. .not. c_associated(global_numpy_mod)) then
     ierror = forpy_initialize_numpy()
   endif
References forpy_initialize_forpy_globals(), forpy_initialize_numpy(), global_forpy_initialized, global_numpy_mod, and true().
Referenced by prob_module::prob_func().
forpy_initialize_bool()
integer(kind=c_int) function forpy_mod::forpy_initialize_bool private
Definition at line 2232 of file forpy_mod.F90.
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: a_bool
   type(PyObject), pointer :: ptr
   a_bool = pybool_fromlong(0_c_long)
   if (.not. c_associated(a_bool)) then
     ierror = exception_error
     return
   endif
   call c_f_pointer(a_bool, ptr)
   global_pybool_type_ptr = ptr%ob_type
   global_py_falsestruct_ptr = a_bool
   call py_decref(a_bool)
   a_bool = pybool_fromlong(1_c_long)
   if (.not. c_associated(a_bool)) then
     ierror = exception_error
     return
   endif
   global_py_truestruct_ptr = a_bool
   call py_decref(a_bool)
   ierror = 0_c_int
Referenced by forpy_initialize_forpy_globals().
forpy_initialize_complex()
integer(kind=c_int) function forpy_mod::forpy_initialize_complex private
Definition at line 2184 of file forpy_mod.F90.
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: a_complex
   type(PyObject), pointer :: ptr
   a_complex = pycomplex_fromdoubles(1.0_c_double, 1.0_c_double)
   if (.not. c_associated(a_complex)) then
     ierror = exception_error
     return
   endif
   call c_f_pointer(a_complex, ptr)
   global_pycomplex_type_ptr = ptr%ob_type
   call py_decref(a_complex)
   ierror = 0_c_int
Referenced by forpy_initialize_forpy_globals().
forpy_initialize_exceptions()
integer(kind=c_int) function forpy_mod::forpy_initialize_exceptions private
Definition at line 2264 of file forpy_mod.F90.
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: tmp
   type(c_ptr) :: builtin_dict
   ierror = 0_c_int
   builtin_dict = pyeval_getbuiltins()
   if (.not. c_associated(builtin_dict)) then
     ierror = 1_c_int
     return
   endif
   tmp = pydict_getitemstring(builtin_dict, "ArithmeticError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   arithmeticerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "AssertionError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   assertionerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "AttributeError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   attributeerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "BaseException" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   baseexception%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "BufferError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   buffererror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "BytesWarning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   byteswarning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "DeprecationWarning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   deprecationwarning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "EOFError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   eoferror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "EnvironmentError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   environmenterror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "Exception" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   exception%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "FloatingPointError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   floatingpointerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "FutureWarning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   futurewarning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "GeneratorExit" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   generatorexit%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "IOError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   ioerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "ImportError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   importerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "ImportWarning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   importwarning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "IndentationError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   indentationerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "IndexError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   indexerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "KeyError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   keyerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "KeyboardInterrupt" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   keyboardinterrupt%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "LookupError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   lookuperror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "MemoryError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   memoryerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "NameError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   nameerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "NotImplementedError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   notimplementederror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "OSError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   oserror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "OverflowError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   overflowerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "PendingDeprecationWarning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   pendingdeprecationwarning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "ReferenceError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   referenceerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "RuntimeError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   runtimeerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "RuntimeWarning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   runtimewarning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "StandardError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   standarderror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "StopIteration" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   stopiteration%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "SyntaxError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   syntaxerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "SyntaxWarning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   syntaxwarning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "SystemError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   systemerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "SystemExit" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   systemexit%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "TabError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   taberror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "TypeError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   typeerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "UnboundLocalError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   unboundlocalerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "UnicodeDecodeError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   unicodedecodeerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "UnicodeEncodeError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   unicodeencodeerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "UnicodeError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   unicodeerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "UnicodeTranslateError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   unicodetranslateerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "UnicodeWarning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   unicodewarning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "UserWarning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   userwarning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "ValueError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   valueerror%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "Warning" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   warning%py_object = tmp
   tmp = pydict_getitemstring(builtin_dict, "ZeroDivisionError" // c_null_char)
   if (.not. c_associated(tmp)) then; call pyerr_clear(); endif
   zerodivisionerror%py_object = tmp
References arithmeticerror, assertionerror, attributeerror, baseexception, buffererror, byteswarning, deprecationwarning, environmenterror, eoferror, exception, floatingpointerror, futurewarning, generatorexit, importerror, importwarning, indentationerror, indexerror, ioerror, keyboardinterrupt, keyerror, lookuperror, memoryerror, nameerror, notimplementederror, oserror, overflowerror, pendingdeprecationwarning, referenceerror, runtimeerror, runtimewarning, standarderror, stopiteration, syntaxerror, syntaxwarning, systemerror, systemexit, taberror, typeerror, unboundlocalerror, unicodedecodeerror, unicodeencodeerror, unicodeerror, unicodetranslateerror, unicodewarning, userwarning, valueerror, warning, and zerodivisionerror.
Referenced by forpy_initialize_forpy_globals().
forpy_initialize_float()
integer(kind=c_int) function forpy_mod::forpy_initialize_float private
Definition at line 2163 of file forpy_mod.F90.
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: a_float
   type(PyObject), pointer :: ptr
   a_float = pyfloat_fromdouble(1.0_c_double)
   if (.not. c_associated(a_float)) then
     ierror = exception_error
     return
   endif
   call c_f_pointer(a_float, ptr)
   global_pyfloat_type_ptr = ptr%ob_type
   call py_decref(a_float)
   ierror = 0_c_int
Referenced by forpy_initialize_forpy_globals().
forpy_initialize_forpy_globals()
integer(kind=c_int) function forpy_mod::forpy_initialize_forpy_globals private
Definition at line 2012 of file forpy_mod.F90.
   integer(kind=C_INT) :: ierror
   ! Initialise Python's None object
   ierror = forpy_initialize_none()
   if (ierror /= 0) then
     return
   endif
   ierror = forpy_initialize_float()
   if (ierror /= 0) then
     return
   endif
   ierror = forpy_initialize_complex()
   if (ierror /= 0) then
     return
   endif
   ierror = forpy_initialize_bool()
   if (ierror /= 0) then
     return
   endif
   ierror = forpy_initialize_unicode()
   if (ierror /= 0) then
     return
   endif
   ierror = forpy_initialize_exceptions()
   if (ierror /= 0) then
     return
   endif
   ierror = forpy_initialize_sys_argv()
   if (ierror /= 0) then
     return
   endif
References forpy_initialize_bool(), forpy_initialize_complex(), forpy_initialize_exceptions(), forpy_initialize_float(), forpy_initialize_none(), forpy_initialize_sys_argv(), and forpy_initialize_unicode().
Referenced by forpy_initialize().
forpy_initialize_none()
integer(kind=c_int) function forpy_mod::forpy_initialize_none private
Definition at line 2118 of file forpy_mod.F90.
   integer(kind=C_INT) :: ierror
   type(list) :: li
   type(tuple) :: args
   type(dict) :: kwargs
   type(object) :: none_obj
   ! A bit hacky: use return value of the following python expression
   ! to get pointer to the singleton None-object (_Py_NoneStruct):
   ! The expression is: [].sort()
   ierror = list_create(li)
   if (ierror /= 0) then
     return
   endif
   ierror = tuple_create(args, 0)
   if (ierror /= 0) then
     call li%destroy()
     return
   endif
   ierror = dict_create(kwargs)
   if (ierror /= 0) then
     call li%destroy()
     call args%destroy()
     return
   endif
   ierror = call_py_attribute(none_obj, li, "sort", args, kwargs)
   if (ierror == 0 .and. c_associated(none_obj%py_object)) then
     global_py_nonestruct_ptr = none_obj%py_object
     call none_obj%destroy()
   endif
   call li%destroy()
   call args%destroy()
   call kwargs%destroy()
   ierror = 0_c_int
Referenced by forpy_initialize_forpy_globals().
forpy_initialize_numpy()
integer(kind=c_int) function forpy_mod::forpy_initialize_numpy private
Definition at line 2065 of file forpy_mod.F90.
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: asarray_str
   type(c_ptr) :: ndarray_str
   ! Initialisation of Numpy
   global_numpy_mod = pyimport_importmodule(c_char_"numpy" // c_null_char)
   if (.not. c_associated(global_numpy_mod)) then
     ierror = no_numpy_error
     call err_clear
     return
   else
     ! TODO: exception checks?
     ierror = box_value(asarray_str, "asarray")
     if (.not. c_associated(asarray_str)) then
       ierror = no_numpy_error
       call err_clear
       return
     else
       global_numpy_asarray_method = pyobject_getattr(global_numpy_mod, asarray_str)
       call py_decref(asarray_str)
       if (.not. c_associated(global_numpy_asarray_method)) then
         ierror = no_numpy_error ! Something's wrong with numpy... but might use Python without numpy
         call err_clear
       endif
     endif
   endif
   ! Get the numpy.ndarray type-object
   if (ierror == 0) then
     ierror = box_value(ndarray_str, "ndarray")
     if (ierror /= 0) then
       return
     endif
     global_numpy_ndarray_typeobj = pyobject_getattr(global_numpy_mod, ndarray_str)
     call py_decref(ndarray_str)
     if (.not. c_associated(global_numpy_asarray_method)) then
       ierror = no_numpy_error ! No Numpy...
       call err_clear
     endif
   endif
Referenced by forpy_initialize().
forpy_initialize_sys_argv()
integer(kind=c_int) function forpy_mod::forpy_initialize_sys_argv private
Sets sys.argv = [''], since some 3rd party Python modules require sys.argv[0] - before Python 3.8 sys.argv does not exist in embedded Python, see https://bugs.python.org/issue32573.
Definition at line 2055 of file forpy_mod.F90.
   integer(kind=C_INT) :: ierror
   ! there also exist C-API functions to set sys.argv, but they involve wchar_t
   ! which iso_c_binding does not support and that has platform dep. size
   ierror = pyrun_simplestring(import sys" // C_NEW_LINE // &
                               "if not hasattr(sys, 'argv') or sys.argv==[]:" // C_NEW_LINE // &
                               "  sys.argv=['']" // C_NEW_LINE // C_NULL_CHAR)
Referenced by forpy_initialize_forpy_globals().
forpy_initialize_unicode()
integer(kind=c_int) function forpy_mod::forpy_initialize_unicode private
Definition at line 2204 of file forpy_mod.F90.
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: a_unicode
   type(PyObject), pointer :: ptr
   character(kind=C_CHAR), dimension(1) :: a
   character(kind=C_CHAR), dimension(7) :: b
   a = [c_null_char]
   b = ['s','t','r','i','c','t', c_null_char]
   ! fix for PGI compiler: pgi does not like if a and b are
   ! string literals in this function call
   a_unicode = pyunicode_decodeutf8(a, 0_py_ssize_t_kind, b)
   if (.not. c_associated(a_unicode)) then
     ierror = exception_error
     return
   endif
   call c_f_pointer(a_unicode, ptr)
   global_pyunicode_type_ptr = ptr%ob_type
   call py_decref(a_unicode)
   ierror = 0_c_int
Referenced by forpy_initialize_forpy_globals().
get_data_complex_real32_1d()
integer(kind=c_int) function forpy_mod::get_data_complex_real32_1d (class(ndarray), intent(in) self, complex(kind=real32), dimension(:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 7622 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   complex(kind=real32), dimension(:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "Zf" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_complex_real32_2d()
integer(kind=c_int) function forpy_mod::get_data_complex_real32_2d (class(ndarray), intent(in) self, complex(kind=real32), dimension(:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8126 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   complex(kind=real32), dimension(:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "Zf" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_complex_real32_3d()
integer(kind=c_int) function forpy_mod::get_data_complex_real32_3d (class(ndarray), intent(in) self, complex(kind=real32), dimension(:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8630 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   complex(kind=real32), dimension(:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "Zf" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_complex_real32_4d()
integer(kind=c_int) function forpy_mod::get_data_complex_real32_4d (class(ndarray), intent(in) self, complex(kind=real32), dimension(:,:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 9134 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   complex(kind=real32), dimension(:,:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "Zf" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_complex_real64_1d()
integer(kind=c_int) function forpy_mod::get_data_complex_real64_1d (class(ndarray), intent(in) self, complex(kind=real64), dimension(:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 7706 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   complex(kind=real64), dimension(:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "Zd" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_complex_real64_2d()
integer(kind=c_int) function forpy_mod::get_data_complex_real64_2d (class(ndarray), intent(in) self, complex(kind=real64), dimension(:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8210 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   complex(kind=real64), dimension(:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "Zd" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_complex_real64_3d()
integer(kind=c_int) function forpy_mod::get_data_complex_real64_3d (class(ndarray), intent(in) self, complex(kind=real64), dimension(:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8714 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   complex(kind=real64), dimension(:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "Zd" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_complex_real64_4d()
integer(kind=c_int) function forpy_mod::get_data_complex_real64_4d (class(ndarray), intent(in) self, complex(kind=real64), dimension(:,:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 9218 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   complex(kind=real64), dimension(:,:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "Zd" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_helper()
integer(kind=c_int) function forpy_mod::get_data_helper (class(ndarray), intent(in) self, type(c_ptr), intent(out) raw_ptr, integer(kind=py_ssize_t_kind), dimension(ndim), intent(out) shape_info, integer, intent(in) ndim, character(kind=c_char, len=*), intent(in), target format_c_string, character(kind=c_char), intent(in) order) private
Get pointer to data of numpy array.
Definition at line 9473 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   type(c_ptr), intent(out) :: raw_ptr
   integer, intent(in) :: ndim
   integer(kind=PY_SSIZE_T_KIND), dimension(ndim), intent(out) :: shape_info
   character(kind=C_CHAR, len=*), target, intent(in) :: format_c_string
   character(kind=C_CHAR), intent(in) :: order
   integer(kind=C_INT) :: ierror, flag
   type(Py_buffer) :: buffer
   integer(kind=PY_SSIZE_T_KIND), dimension(:), pointer :: shape_ptr
   integer :: shape_info_shape(1)
   character(kind=C_CHAR) :: detected_order
   character(kind=C_CHAR,len=60) :: error_message
   ! order can have values 'C', 'F' or 'A'
   if (index('CFA', order) == 0) then
     ierror = exception_error
     call raise_exception(valueerror, "ndarray%get_data: order parameter must be 'F', 'C' or 'A'")
     return
   endif
   shape_info_shape(1) = ndim
   ! raises BufferError exception if array is not contiguous, Python 2: ValueError
   ierror = pyobject_getbuffer(self%py_object, buffer, 156_c_int) !flags (PyBUF_FORMAT | PyBUF_ANY_CONTIGUOUS) - we need the format info and PyBUF_FORMAT alone gives error
   if (ierror /= 0) then
     if (exception_matches(buffererror) .or. exception_matches(valueerror)) then ! make error message more informative
       call err_clear
       call raise_exception(buffererror, "forpy: ndarray with non-contiguous data. Fortran or C-order needed: try to copy array")
     endif
     return
   endif
   detected_order = 'N'
   flag = pybuffer_iscontiguous(buffer, 'F')
   if (flag == 1_c_int) then
     detected_order = 'F'
   else
     flag = pybuffer_iscontiguous(buffer, 'C')
     if (flag == 1_c_int) then
       detected_order = 'C'
     endif
   endif
   if ((detected_order == 'N') .or. (ndim > 1 .and. order /= 'A' .and. order /= detected_order)) then
     ierror = exception_error
     if (order=='F') then
       error_message = "forpy: expected Fortran-ordered array"
     elseif (order=='C') then
       error_message = "forpy: expected C-ordered array"
     else
       error_message = "forpy: expected contiguous array"
     endif
     call pybuffer_release(buffer)
     call raise_exception(buffererror, error_message)
     return
   endif
   if (buffer%ndim /= ndim) then
     ierror = exception_error
     write(error_message,fmt="('forpy: expected array of rank ',I1,', got array of rank ',I1)") ndim, buffer%ndim
     call pybuffer_release(buffer)
     call raise_exception(typeerror, error_message)
     return
   endif
   !get shape info
   call c_f_pointer(buffer%shape, shape_ptr, shape=shape_info_shape)
   !check if correct format
   if (associated(shape_ptr)) then
     if (get_data_helper_check_dtype(buffer%format, format_c_string) /= 0) then
       ierror = exception_error
       call pybuffer_release(buffer)
       call raise_exception(typeerror, "forpy: ndarray%get_data - datatype of data pointer is incompatible with ndarray")
       return
     endif
   else
     ierror = exception_error
     call pybuffer_release(buffer)
     call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     return
   endif
   raw_ptr = buffer%buf
   call get_shape_info_helper(shape_info, shape_ptr, detected_order)
   call pybuffer_release(buffer)
get_data_helper_check_dtype()
integer(kind=c_int) function forpy_mod::get_data_helper_check_dtype (type(c_ptr), intent(in) buffer_format, character(kind=c_char, len=*), intent(in), target format_c_string) private
Definition at line 9567 of file forpy_mod.F90.
   type(c_ptr), intent(in) :: buffer_format
   character(kind=C_CHAR, len=*), target, intent(in) :: format_c_string
   character(kind=C_CHAR, len=2), target :: format_code
   integer(kind=C_INT) :: flag
   flag = 1_c_int
   ! the Python buffer format codes corresponding to int32 and int64 are systems dependent...
   if (format_c_string == "i" // c_null_char) then  ! buffer type compatible with int32 requested
     if (int32 == c_int) then
       format_code = "i" // c_null_char
       flag = strcmp(buffer_format, c_loc(format_code))
     endif
     if (flag /= 0) then
       if (int32 == c_long) then
         format_code = "l" // c_null_char
         flag = strcmp(buffer_format, c_loc(format_code))
       endif
     endif
     return
   endif
   if (format_c_string == "l" // c_null_char) then  ! buffer type compatible with int64 requested
     if (int64 == c_long) then
       format_code = "l" // c_null_char
       flag = strcmp(buffer_format, c_loc(format_code))
     endif
     if (flag /= 0) then
       if (int64 == c_long_long) then
         format_code = "q" // c_null_char
         flag = strcmp(buffer_format, c_loc(format_code))
       endif
     endif
     if (flag /= 0) then
       if (int64 == c_int) then
         format_code = "i" // c_null_char
         flag = strcmp(buffer_format, c_loc(format_code))
       endif
     endif
     return
   endif
   ! this handles all the non-integer cases
   flag = strcmp(buffer_format, c_loc(format_c_string))
get_data_int32_1d()
integer(kind=c_int) function forpy_mod::get_data_int32_1d (class(ndarray), intent(in) self, integer(kind=int32), dimension(:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 7286 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int32), dimension(:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "i" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_int32_2d()
integer(kind=c_int) function forpy_mod::get_data_int32_2d (class(ndarray), intent(in) self, integer(kind=int32), dimension(:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 7790 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int32), dimension(:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "i" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_int32_3d()
integer(kind=c_int) function forpy_mod::get_data_int32_3d (class(ndarray), intent(in) self, integer(kind=int32), dimension(:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8294 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int32), dimension(:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "i" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_int32_4d()
integer(kind=c_int) function forpy_mod::get_data_int32_4d (class(ndarray), intent(in) self, integer(kind=int32), dimension(:,:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8798 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int32), dimension(:,:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "i" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_int64_1d()
integer(kind=c_int) function forpy_mod::get_data_int64_1d (class(ndarray), intent(in) self, integer(kind=int64), dimension(:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 7370 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int64), dimension(:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "l" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_int64_2d()
integer(kind=c_int) function forpy_mod::get_data_int64_2d (class(ndarray), intent(in) self, integer(kind=int64), dimension(:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 7874 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int64), dimension(:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "l" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_int64_3d()
integer(kind=c_int) function forpy_mod::get_data_int64_3d (class(ndarray), intent(in) self, integer(kind=int64), dimension(:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8378 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int64), dimension(:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "l" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_int64_4d()
integer(kind=c_int) function forpy_mod::get_data_int64_4d (class(ndarray), intent(in) self, integer(kind=int64), dimension(:,:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8882 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int64), dimension(:,:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "l" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_real32_1d()
integer(kind=c_int) function forpy_mod::get_data_real32_1d (class(ndarray), intent(in) self, real(kind=real32), dimension(:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 7454 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   real(kind=real32), dimension(:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "f" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_real32_2d()
integer(kind=c_int) function forpy_mod::get_data_real32_2d (class(ndarray), intent(in) self, real(kind=real32), dimension(:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 7958 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   real(kind=real32), dimension(:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "f" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_real32_3d()
integer(kind=c_int) function forpy_mod::get_data_real32_3d (class(ndarray), intent(in) self, real(kind=real32), dimension(:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8462 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   real(kind=real32), dimension(:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "f" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_real32_4d()
integer(kind=c_int) function forpy_mod::get_data_real32_4d (class(ndarray), intent(in) self, real(kind=real32), dimension(:,:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8966 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   real(kind=real32), dimension(:,:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "f" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_real64_1d()
integer(kind=c_int) function forpy_mod::get_data_real64_1d (class(ndarray), intent(in) self, real(kind=real64), dimension(:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 7538 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   real(kind=real64), dimension(:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "d" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_real64_2d()
integer(kind=c_int) function forpy_mod::get_data_real64_2d (class(ndarray), intent(in) self, real(kind=real64), dimension(:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8042 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   real(kind=real64), dimension(:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "d" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_real64_3d()
integer(kind=c_int) function forpy_mod::get_data_real64_3d (class(ndarray), intent(in) self, real(kind=real64), dimension(:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 8546 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   real(kind=real64), dimension(:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "d" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_data_real64_4d()
integer(kind=c_int) function forpy_mod::get_data_real64_4d (class(ndarray), intent(in) self, real(kind=real64), dimension(:,:,:,:), intent(out), pointer ptr, character(kind=c_char), intent(in), optional order) private
Get pointer to data of numpy array.
Raises BufferError, if array is not contiguous (does not have the required Fortran or C storage order) Raises TypeError, if Fortran pointer datatype is not compatible with numpy datatype.
Parameters
[out] ptr Pointer to the numerical data of the Fortran array.
[in] order Only retrieve data, when ndarray has certain order.
If 'F' (default), only retrieve the data when the ndarray has Fortran storage order. If 'C', only retrieve the data when the ndarray has C storage order. ATTENTION: The data, the pointer points to, then will be the transpose of the array. If 'A' accept Fortran or C order. If C, the data will be transposed.
Returns
Error code, 0 on success
Definition at line 9050 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   real(kind=real64), dimension(:,:,:,:), pointer, intent(out) :: ptr
   character(kind=C_CHAR), optional, intent(in) :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(c_ptr) :: raw_ptr
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), dimension(NDIM) :: shape_info
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   nullify(ptr)
   ierror = get_data_helper(self, raw_ptr, shape_info, ndim, "d" // c_null_char, the_order)
   if (ierror == 0_c_int) then
     call c_f_pointer(raw_ptr, ptr, shape=shape_info)
     if (.not. associated(ptr)) then
       ierror = exception_error
       call raise_exception(runtimeerror, "forpy: Could not determine shape of ndarray")
     endif
   endif
Referenced by forpy_mod::ndarray::get_data().
get_shape_info_helper()
subroutine forpy_mod::get_shape_info_helper (integer(kind=py_ssize_t_kind), dimension(:), intent(out) shape_info, integer(kind=py_ssize_t_kind), dimension(:), intent(in) shape_ptr, character(kind=c_char), intent(in) order) private
Definition at line 9616 of file forpy_mod.F90.
   integer(kind=PY_SSIZE_T_KIND), dimension(:), intent(out) :: shape_info
   integer(kind=PY_SSIZE_T_KIND), dimension(:), intent(in) :: shape_ptr
   character(kind=C_CHAR), intent(in) :: order
   integer ii, length
   if (order == 'F') then
     shape_info = shape_ptr
   elseif (order == 'C') then ! C-order: reverse shape information ("transpose")
     length = size(shape_info)
     do ii = 1, length
       shape_info(ii) = shape_ptr(length-ii+1)
     enddo
   endif
get_sys_path()
integer(kind=c_int) function, public forpy_mod::get_sys_path (type(list), intent(out) paths)
Getting the list of module search paths: sys.path.
Can be used to append additional directories, where modules shall be searched
Parameters
[out] paths Output: list of module search paths
Returns
Error code, 0 on success
Definition at line 11853 of file forpy_mod.F90.
   type(list), intent(out) :: paths
   integer(kind=C_INT) :: ierror
   type(object) :: tmp
   tmp%py_object = pysys_getobject("path" // c_null_char)
   ierror = cast(paths, tmp)
   ! not destroying tmp, because PySys_GetObject returns borrowed reference
have_exception()
logical function, public forpy_mod::have_exception
returns .true. if an exception has occurred
Definition at line 11638 of file forpy_mod.F90.
   logical :: have_exception
   type(c_ptr) :: err_obj
   err_obj = pyerr_occurred()
   have_exception = c_associated(err_obj)
import_py()
integer(kind=c_int) function, public forpy_mod::import_py (type(module_py), intent(out) mod_py, character(kind=c_char, len=*), intent(in) mod_name)
Import a Python module.
Module must be in Python module search path. The search path can be set via the environment variable PYTHONPATH or by manipulating the list of paths retrieved by using [[get_sys_path]].
Parameters
[out] mod_py The imported module
[in] mod_name Name of the module to import. Name can include dots "."
Returns
Error code, 0 on success.
Definition at line 7069 of file forpy_mod.F90.
   type(module_py), intent(out) :: mod_py
   character(kind=C_CHAR, len=*), intent(in) :: mod_name
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   mod_py%py_object = pyimport_importmodule(trim(mod_name) // c_null_char)
   if (.not. c_associated(mod_py%py_object)) then
     ierror = exception_error
   endif
Referenced by prob_module::prob_func().
is_bool()
logical function, public forpy_mod::is_bool (class(object), intent(in) obj)
Checks if object is a Python bool.
Parameters
[in] obj The object to check.
Definition at line 2516 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   type(PyObject), pointer :: obj_ptr
   if (.not. (c_associated(obj%py_object) .and. c_associated(global_pybool_type_ptr))) then
     is_bool = .false.
     return
   endif
   call c_f_pointer(obj%py_object, obj_ptr)
   is_bool = c_associated(global_pybool_type_ptr, obj_ptr%ob_type)
   if (.not. is_bool) then
     is_bool = (pytype_issubtype(obj_ptr%ob_type, global_pybool_type_ptr) /= 0) ! Check if subtype
   endif
is_bytes()
logical function, public forpy_mod::is_bytes (class(object), intent(in) obj)
Checks if object is a Python bytes.
Parameters
[in] obj The object to check.
Definition at line 2463 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   is_bytes = (check_tp_flags(obj%py_object, ishft(1_c_long, 27)) /= 0)
is_complex()
logical function, public forpy_mod::is_complex (class(object), intent(in) obj)
Checks if object is a Python complex.
Parameters
[in] obj The object to check.
Definition at line 2498 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   type(PyObject), pointer :: obj_ptr
   if (.not. (c_associated(obj%py_object) .and. c_associated(global_pycomplex_type_ptr))) then
     is_complex = .false.
     return
   endif
   call c_f_pointer(obj%py_object, obj_ptr)
   is_complex = c_associated(global_pycomplex_type_ptr, obj_ptr%ob_type)
   if (.not. is_complex) then
     is_complex = (pytype_issubtype(obj_ptr%ob_type, global_pycomplex_type_ptr) /= 0) ! Check if subtype
   endif
is_dict()
logical function, public forpy_mod::is_dict (class(object), intent(in) obj)
Checks if object is a Python dict.
Parameters
[in] obj The object to check.
Definition at line 2471 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   is_dict = (check_tp_flags(obj%py_object, ishft(1_c_long, 29)) /= 0)
is_float()
logical function, public forpy_mod::is_float (class(object), intent(in) obj)
Checks if object is a Python float.
Parameters
[in] obj The object to check.
Definition at line 2480 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   type(PyObject), pointer :: obj_ptr
   if (.not. (c_associated(obj%py_object) .and. c_associated(global_pyfloat_type_ptr))) then
     is_float = .false.
     return
   endif
   call c_f_pointer(obj%py_object, obj_ptr)
   is_float = c_associated(global_pyfloat_type_ptr, obj_ptr%ob_type)
   if (.not. is_float) then
     is_float = (pytype_issubtype(obj_ptr%ob_type, global_pyfloat_type_ptr) /= 0) ! Check if subtype
   endif
is_int()
logical function public forpy_mod::is_int (class(object), intent(in) obj)
Checks if object is of integer Python type ('int' OR 'long')
Checks if object is a Python int.
Parameters
[in] obj The object to check.
Definition at line 2560 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   is_int = is_short_int(obj)
   if (.not. is_int) then
     is_int = is_long(obj)
   endif
is_list()
logical function, public forpy_mod::is_list (class(object), intent(in) obj)
Checks if object is a Python list.
Parameters
[in] obj The object to check.
Definition at line 2447 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   is_list = (check_tp_flags(obj%py_object, ishft(1_c_long, 25)) /= 0)
is_long()
logical function, public forpy_mod::is_long (class(object), intent(in) obj)
Checks if object is a Python long.
Parameters
[in] obj The object to check.
Definition at line 2439 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   is_long = (check_tp_flags(obj%py_object, ishft(1_c_long, 24)) /= 0)
is_ndarray()
logical function, public forpy_mod::is_ndarray (class(object), intent(in) obj)
Checks if object is a Numpy array.
Parameters
[in] obj The object to check.
Definition at line 2609 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: res
   type(c_ptr) :: err_obj
   if (.not. c_associated(global_numpy_ndarray_typeobj)) then
     is_ndarray = .false.
     return
   endif
   res = pyobject_isinstance(obj%py_object, global_numpy_ndarray_typeobj)
   ! if res==-1 then exception is set by PyObject_IsInstance
   ! clear the exception and return false
   if (res == -1_c_int) then
     is_ndarray = .false.
       err_obj = pyerr_occurred()
       if (c_associated(err_obj)) then
         call pyerr_clear()
       endif
     return
   endif
   is_ndarray = (res == 1)
is_none()
logical function, public forpy_mod::is_none (class(object), intent(in) obj)
Checks if object is a Python None.
Parameters
[in] obj The object to check.
Definition at line 2593 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   is_none = c_associated(obj%py_object) .and. c_associated(global_py_nonestruct_ptr, obj%py_object)
is_null()
logical function, public forpy_mod::is_null (class(object), intent(in) obj)
Returns true if object is a null-pointer internally. Object is not properly initialised then.
Parameters
[in] obj The object to check.
Definition at line 2601 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   is_null = (.not. c_associated(obj%py_object))
is_short_int()
logical function forpy_mod::is_short_int (class(object), intent(in) obj) private
Definition at line 2553 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   is_short_int = (check_tp_flags(obj%py_object, ishft(1_c_long, 23)) /= 0)
is_str()
logical function, public forpy_mod::is_str (class(object), intent(in) obj)
Checks if object is a Python str.
Parameters
[in] obj The object to check.
Definition at line 2582 of file forpy_mod.F90.
   class(object), intent(in) :: obj
 #ifdef PYTHON2
   is_str = is_bytes(obj)
 #else
   is_str = is_unicode(obj)
 #endif
is_tuple()
logical function, public forpy_mod::is_tuple (class(object), intent(in) obj)
Checks if object is a Python tuple.
Parameters
[in] obj The object to check.
Definition at line 2455 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   is_tuple = (check_tp_flags(obj%py_object, ishft(1_c_long, 26)) /= 0)
is_unicode()
logical function, public forpy_mod::is_unicode (class(object), intent(in) obj)
Checks if object is a Python unicode.
Parameters
[in] obj The object to check.
Definition at line 2534 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   type(PyObject), pointer :: obj_ptr
   if (.not. (c_associated(obj%py_object) .and. c_associated(global_pyunicode_type_ptr))) then
     is_unicode = .false.
     return
   endif
   call c_f_pointer(obj%py_object, obj_ptr)
   is_unicode = c_associated(global_pyunicode_type_ptr, obj_ptr%ob_type)
   if (.not. is_unicode) then
     is_unicode = (pytype_issubtype(obj_ptr%ob_type, global_pyunicode_type_ptr) /= 0) ! Check if subtype
   endif
list_add()
integer(kind=c_int) function forpy_mod::list_add (class(list), intent(inout) self, type(list), intent(out) result_list, class(list), intent(in) list_to_concatenate) private
Definition at line 2988 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   type(list), intent(out) :: result_list
   class(list), intent(in) :: list_to_concatenate
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   result_list%py_object = pysequence_concat(self%py_object, list_to_concatenate%py_object)
   if (.not. c_associated(result_list%py_object)) then
     ierror = exception_error
   endif
list_append_char_1d()
integer(kind=c_int) function forpy_mod::list_append_char_1d (class(list), intent(inout) self, character(kind=c_char), dimension(:), intent(in) item) private
Definition at line 2934 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   character(kind=C_CHAR), dimension(:), intent(in) :: item
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   if (ierror == 0_c_int) then
     ierror = pylist_append(self%py_object, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::list::append().
list_append_chars()
integer(kind=c_int) function forpy_mod::list_append_chars (class(list), intent(inout) self, character(kind=c_char, len=*), intent(in) item) private
Definition at line 2949 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: item
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   if (ierror == 0_c_int) then
     ierror = pylist_append(self%py_object, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::list::append().
list_append_complex_real32()
integer(kind=c_int) function forpy_mod::list_append_complex_real32 (class(list), intent(inout) self, complex(kind=real32), intent(in) item) private
Definition at line 2889 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   complex(kind=real32), intent(in) :: item
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   if (ierror == 0_c_int) then
     ierror = pylist_append(self%py_object, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::list::append().
list_append_complex_real64()
integer(kind=c_int) function forpy_mod::list_append_complex_real64 (class(list), intent(inout) self, complex(kind=real64), intent(in) item) private
Definition at line 2904 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   complex(kind=real64), intent(in) :: item
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   if (ierror == 0_c_int) then
     ierror = pylist_append(self%py_object, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::list::append().
list_append_int32()
integer(kind=c_int) function forpy_mod::list_append_int32 (class(list), intent(inout) self, integer(kind=int32), intent(in) item) private
Definition at line 2829 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   integer(kind=int32), intent(in) :: item
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   if (ierror == 0_c_int) then
     ierror = pylist_append(self%py_object, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::list::append().
list_append_int64()
integer(kind=c_int) function forpy_mod::list_append_int64 (class(list), intent(inout) self, integer(kind=int64), intent(in) item) private
Definition at line 2844 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   integer(kind=int64), intent(in) :: item
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   if (ierror == 0_c_int) then
     ierror = pylist_append(self%py_object, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::list::append().
list_append_logical()
integer(kind=c_int) function forpy_mod::list_append_logical (class(list), intent(inout) self, logical, intent(in) item) private
Definition at line 2919 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   logical, intent(in) :: item
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   if (ierror == 0_c_int) then
     ierror = pylist_append(self%py_object, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::list::append().
list_append_object()
integer(kind=c_int) function forpy_mod::list_append_object (class(list), intent(inout) self, class(object), intent(in) item) private
Definition at line 2821 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   class(object), intent(in) :: item
   integer(kind=C_INT) :: ierror
   ierror = pylist_append(self%py_object, item%py_object)
Referenced by forpy_mod::list::append().
list_append_real32()
integer(kind=c_int) function forpy_mod::list_append_real32 (class(list), intent(inout) self, real(kind=real32), intent(in) item) private
Definition at line 2859 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   real(kind=real32), intent(in) :: item
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   if (ierror == 0_c_int) then
     ierror = pylist_append(self%py_object, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::list::append().
list_append_real64()
integer(kind=c_int) function forpy_mod::list_append_real64 (class(list), intent(inout) self, real(kind=real64), intent(in) item) private
Definition at line 2874 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   real(kind=real64), intent(in) :: item
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   if (ierror == 0_c_int) then
     ierror = pylist_append(self%py_object, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::list::append().
list_copy()
integer(kind=c_int) function forpy_mod::list_copy (class(list), intent(in) self, type(list), intent(out) dest) private
Definition at line 2965 of file forpy_mod.F90.
   class(list), intent(in) :: self
   type(list), intent(out) :: dest
   integer(kind=C_INT) :: ierror
   ierror = list_create(dest, self)
list_create_empty()
integer(kind=c_int) function forpy_mod::list_create_empty (type(list), intent(out) r) private
Creates an empty list. Python equivalent: r = [].
Parameters
[out] r the freshly created empty list
Returns
Error code, 0 on success
Definition at line 2653 of file forpy_mod.F90.
   type(list), intent(out) :: r
   integer(kind=C_INT) :: ierror
   r%py_object = pylist_new(0_py_ssize_t_kind)
   ierror = 0_c_int
   if (.not. c_associated(r%py_object)) then
     ierror = exception_error
   endif
list_create_object()
integer(kind=c_int) function forpy_mod::list_create_object (type(list), intent(out) r, class(object), intent(in) obj) private
Creates a list from given object if possible. Python equivalent: r = list(obj)
Parameters
[out] r the freshly created list
[in] obj object to create list from
Returns
Error code, 0 on success
Definition at line 2668 of file forpy_mod.F90.
   type(list), intent(out) :: r
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   r%py_object = pysequence_list(obj%py_object)
   if (.not. c_associated(r%py_object)) then
     ierror = exception_error
   endif
list_delitem_int32()
integer(kind=c_int) function forpy_mod::list_delitem_int32 (class(list), intent(inout) self, integer(kind=int32), intent(in) ind) private
Definition at line 3013 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_tmp
   ind_tmp = int(ind, py_ssize_t_kind)
   ierror = pysequence_delitem(self%py_object, ind_tmp)
Referenced by forpy_mod::list::delitem().
list_delitem_int64()
integer(kind=c_int) function forpy_mod::list_delitem_int64 (class(list), intent(inout) self, integer(kind=int64), intent(in) ind) private
Definition at line 3036 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_tmp
   ind_tmp = int(ind, py_ssize_t_kind)
   ierror = pysequence_delitem(self%py_object, ind_tmp)
Referenced by forpy_mod::list::delitem().
list_insert_int32()
integer(kind=c_int) function forpy_mod::list_insert_int32 (class(list), intent(inout) self, integer(kind=int32), intent(in) ind, class(object), intent(in) item) private
Definition at line 3001 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   class(object), intent(in) :: item
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_tmp
   ind_tmp = int(ind, py_ssize_t_kind)
   ierror = pylist_insert(self%py_object, ind_tmp, item%py_object)
Referenced by forpy_mod::list::insert().
list_insert_int64()
integer(kind=c_int) function forpy_mod::list_insert_int64 (class(list), intent(inout) self, integer(kind=int64), intent(in) ind, class(object), intent(in) item) private
Definition at line 3024 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   class(object), intent(in) :: item
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_tmp
   ind_tmp = int(ind, py_ssize_t_kind)
   ierror = pylist_insert(self%py_object, ind_tmp, item%py_object)
Referenced by forpy_mod::list::insert().
list_reverse()
integer(kind=c_int) function forpy_mod::list_reverse (class(list), intent(inout) self) private
Definition at line 2980 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   integer(kind=C_INT) :: ierror
   ierror = pylist_reverse(self%py_object)
list_sort()
integer(kind=c_int) function forpy_mod::list_sort (class(list), intent(inout) self) private
Definition at line 2973 of file forpy_mod.F90.
   class(list), intent(inout) :: self
   integer(kind=C_INT) :: ierror
   ierror = pylist_sort(self%py_object)
mapping_contains()
integer(kind=c_int) function forpy_mod::mapping_contains (class(mapping), intent(in) self, logical, intent(out) contain_flag, class(object), intent(in) item) private
Definition at line 6122 of file forpy_mod.F90.
   class(Mapping), intent(in) :: self
   logical, intent(out) :: contain_flag
   class(object), intent(in) :: item
   integer(kind=C_INT) :: ierror
   integer(kind=C_INT) :: cont
   ierror = 0_c_int
   ! returns 0 if item not contained, 1 if contained
   ! in contrast to PySequence_Contains this never fails
   ! we want to have the same call signature as with sequence objects
   ! therefore we have ierror=0 as return value
   cont = pymapping_haskey(self%py_object, item%py_object)
   contain_flag = (cont == 1_c_int)
mapping_delitem_chars()
integer(kind=c_int) function forpy_mod::mapping_delitem_chars (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5860 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT):: ierror
   type(c_ptr) :: ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = pyobject_delitem(self%py_object, ind_py)
   call py_decref(ind_py)
Referenced by forpy_mod::mapping::delitem().
mapping_delitem_int32()
integer(kind=c_int) function forpy_mod::mapping_delitem_int32 (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key) private
Definition at line 5300 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT):: ierror
   type(c_ptr) :: ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = pyobject_delitem(self%py_object, ind_py)
   call py_decref(ind_py)
Referenced by forpy_mod::mapping::delitem().
mapping_delitem_int64()
integer(kind=c_int) function forpy_mod::mapping_delitem_int64 (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key) private
Definition at line 5580 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT):: ierror
   type(c_ptr) :: ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = pyobject_delitem(self%py_object, ind_py)
   call py_decref(ind_py)
Referenced by forpy_mod::mapping::delitem().
mapping_delitem_object()
integer(kind=c_int) function forpy_mod::mapping_delitem_object (class(mapping), intent(inout) self, class(object), intent(in) key) private
Definition at line 5272 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   class(object), intent(in) :: key
   integer(kind=C_INT):: ierror
   ierror = pyobject_delitem(self%py_object, key%py_object)
Referenced by forpy_mod::mapping::delitem().
mapping_getitem_chars_char_1d()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_char_1d (class(mapping), intent(inout) self, character(kind=c_char), dimension(:), intent(out), pointer item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5209 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR), dimension(:), pointer, intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_chars_chars()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_chars (class(mapping), intent(inout) self, character(kind=c_char, len=:), intent(out), allocatable item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5235 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_chars_complex_real32()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_complex_real32 (class(mapping), intent(inout) self, complex(kind=real32), intent(out) item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5131 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   complex(kind=real32), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_chars_complex_real64()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_complex_real64 (class(mapping), intent(inout) self, complex(kind=real64), intent(out) item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5157 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   complex(kind=real64), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_chars_int32()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_int32 (class(mapping), intent(inout) self, integer(kind=int32), intent(out) item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5027 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_chars_int64()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_int64 (class(mapping), intent(inout) self, integer(kind=int64), intent(out) item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5053 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_chars_logical()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_logical (class(mapping), intent(inout) self, logical, intent(out) item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5183 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   logical, intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_chars_object()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_object (class(mapping), intent(inout) self, type(object), intent(out) item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5005 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   type(object), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item%py_object = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item%py_object)) then
     ierror = exception_error
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_chars_real32()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_real32 (class(mapping), intent(inout) self, real(kind=real32), intent(out) item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5079 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   real(kind=real32), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_chars_real64()
integer(kind=c_int) function forpy_mod::mapping_getitem_chars_real64 (class(mapping), intent(inout) self, real(kind=real64), intent(out) item, character(kind=c_char, len=*), intent(in) key) private
Definition at line 5105 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   real(kind=real64), intent(out) :: item
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_char_1d()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_char_1d (class(mapping), intent(inout) self, character(kind=c_char), dimension(:), intent(out), pointer item, integer(kind=int32), intent(in) key) private
Definition at line 4697 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR), dimension(:), pointer, intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_chars()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_chars (class(mapping), intent(inout) self, character(kind=c_char, len=:), intent(out), allocatable item, integer(kind=int32), intent(in) key) private
Definition at line 4723 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_complex_real32()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_complex_real32 (class(mapping), intent(inout) self, complex(kind=real32), intent(out) item, integer(kind=int32), intent(in) key) private
Definition at line 4619 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   complex(kind=real32), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_complex_real64()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_complex_real64 (class(mapping), intent(inout) self, complex(kind=real64), intent(out) item, integer(kind=int32), intent(in) key) private
Definition at line 4645 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   complex(kind=real64), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_int32()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_int32 (class(mapping), intent(inout) self, integer(kind=int32), intent(out) item, integer(kind=int32), intent(in) key) private
Definition at line 4515 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_int64()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_int64 (class(mapping), intent(inout) self, integer(kind=int64), intent(out) item, integer(kind=int32), intent(in) key) private
Definition at line 4541 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_logical()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_logical (class(mapping), intent(inout) self, logical, intent(out) item, integer(kind=int32), intent(in) key) private
Definition at line 4671 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   logical, intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_object()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_object (class(mapping), intent(inout) self, type(object), intent(out) item, integer(kind=int32), intent(in) key) private
Definition at line 4493 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   type(object), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item%py_object = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item%py_object)) then
     ierror = exception_error
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_real32()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_real32 (class(mapping), intent(inout) self, real(kind=real32), intent(out) item, integer(kind=int32), intent(in) key) private
Definition at line 4567 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   real(kind=real32), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int32_real64()
integer(kind=c_int) function forpy_mod::mapping_getitem_int32_real64 (class(mapping), intent(inout) self, real(kind=real64), intent(out) item, integer(kind=int32), intent(in) key) private
Definition at line 4593 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   real(kind=real64), intent(out) :: item
   integer(kind=int32), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_char_1d()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_char_1d (class(mapping), intent(inout) self, character(kind=c_char), dimension(:), intent(out), pointer item, integer(kind=int64), intent(in) key) private
Definition at line 4953 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR), dimension(:), pointer, intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_chars()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_chars (class(mapping), intent(inout) self, character(kind=c_char, len=:), intent(out), allocatable item, integer(kind=int64), intent(in) key) private
Definition at line 4979 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_complex_real32()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_complex_real32 (class(mapping), intent(inout) self, complex(kind=real32), intent(out) item, integer(kind=int64), intent(in) key) private
Definition at line 4875 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   complex(kind=real32), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_complex_real64()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_complex_real64 (class(mapping), intent(inout) self, complex(kind=real64), intent(out) item, integer(kind=int64), intent(in) key) private
Definition at line 4901 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   complex(kind=real64), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_int32()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_int32 (class(mapping), intent(inout) self, integer(kind=int32), intent(out) item, integer(kind=int64), intent(in) key) private
Definition at line 4771 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_int64()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_int64 (class(mapping), intent(inout) self, integer(kind=int64), intent(out) item, integer(kind=int64), intent(in) key) private
Definition at line 4797 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_logical()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_logical (class(mapping), intent(inout) self, logical, intent(out) item, integer(kind=int64), intent(in) key) private
Definition at line 4927 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   logical, intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_object()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_object (class(mapping), intent(inout) self, type(object), intent(out) item, integer(kind=int64), intent(in) key) private
Definition at line 4749 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   type(object), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item%py_object = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item%py_object)) then
     ierror = exception_error
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_real32()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_real32 (class(mapping), intent(inout) self, real(kind=real32), intent(out) item, integer(kind=int64), intent(in) key) private
Definition at line 4823 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   real(kind=real32), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_int64_real64()
integer(kind=c_int) function forpy_mod::mapping_getitem_int64_real64 (class(mapping), intent(inout) self, real(kind=real64), intent(out) item, integer(kind=int64), intent(in) key) private
Definition at line 4849 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   real(kind=real64), intent(out) :: item
   integer(kind=int64), intent(in) :: key
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   item_py = pyobject_getitem(self%py_object, ind_py)
   call py_decref(ind_py) !don't need index anymore
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_getitem_object_object()
integer(kind=c_int) function forpy_mod::mapping_getitem_object_object (class(mapping), intent(inout) self, type(object), intent(out) item, class(object), intent(in) key) private
Definition at line 4479 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   type(object), intent(out) :: item
   class(object), intent(in) :: key
   integer(kind=C_INT) :: ierror
   item%py_object = pyobject_getitem(self%py_object, key%py_object)
   if (.not. c_associated(item%py_object)) then
     ierror = exception_error
   endif
Referenced by forpy_mod::mapping::getitem().
mapping_len_int32()
integer(kind=c_int) function forpy_mod::mapping_len_int32 (class(mapping), intent(in) self, integer(kind=int32), intent(out) length) private
Definition at line 3515 of file forpy_mod.F90.
   class(Mapping), intent(in) :: self
   integer(kind=int32), intent(out) :: length
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: length_tmp
   ierror = 0_c_int
   length_tmp = pyobject_length(self%py_object)
   length = int(length_tmp, int32)
   ! TODO: overflow check
   if (length_tmp == -1_py_ssize_t_kind) then
     ierror = exception_error
   endif
Referenced by forpy_mod::mapping::len().
mapping_len_int64()
integer(kind=c_int) function forpy_mod::mapping_len_int64 (class(mapping), intent(in) self, integer(kind=int64), intent(out) length) private
Definition at line 3533 of file forpy_mod.F90.
   class(Mapping), intent(in) :: self
   integer(kind=int64), intent(out) :: length
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: length_tmp
   ierror = 0_c_int
   length_tmp = pyobject_length(self%py_object)
   length = int(length_tmp, int64)
   ! TODO: overflow check
   if (length_tmp == -1_py_ssize_t_kind) then
     ierror = exception_error
   endif
Referenced by forpy_mod::mapping::len().
mapping_setitem_chars_char_1d()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_char_1d (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, character(kind=c_char), dimension(:), intent(in) item) private
Definition at line 6067 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   character(kind=C_CHAR), dimension(:), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_chars_chars()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_chars (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, character(kind=c_char, len=*), intent(in) item) private
Definition at line 6094 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   character(kind=C_CHAR, len=*), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_chars_complex_real32()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_complex_real32 (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, complex(kind=real32), intent(in) item) private
Definition at line 5986 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   complex(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_chars_complex_real64()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_complex_real64 (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, complex(kind=real64), intent(in) item) private
Definition at line 6013 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   complex(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_chars_int32()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_int32 (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, integer(kind=int32), intent(in) item) private
Definition at line 5878 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=int32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_chars_int64()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_int64 (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, integer(kind=int64), intent(in) item) private
Definition at line 5905 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   integer(kind=int64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_chars_logical()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_logical (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, logical, intent(in) item) private
Definition at line 6040 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   logical, intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_chars_object()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_object (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, class(object), intent(in) item) private
Definition at line 5841 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   class(object), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   ierror = pyobject_setitem(self%py_object, ind_py, item%py_object)
   call py_decref(ind_py)
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_chars_real32()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_real32 (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, real(kind=real32), intent(in) item) private
Definition at line 5932 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   real(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_chars_real64()
integer(kind=c_int) function forpy_mod::mapping_setitem_chars_real64 (class(mapping), intent(inout) self, character(kind=c_char, len=*), intent(in) key, real(kind=real64), intent(in) item) private
Definition at line 5959 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: key
   real(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_char_1d()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_char_1d (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, character(kind=c_char), dimension(:), intent(in) item) private
Definition at line 5507 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   character(kind=C_CHAR), dimension(:), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_chars()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_chars (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, character(kind=c_char, len=*), intent(in) item) private
Definition at line 5534 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   character(kind=C_CHAR, len=*), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_complex_real32()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_complex_real32 (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, complex(kind=real32), intent(in) item) private
Definition at line 5426 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   complex(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_complex_real64()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_complex_real64 (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, complex(kind=real64), intent(in) item) private
Definition at line 5453 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   complex(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_int32()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_int32 (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, integer(kind=int32), intent(in) item) private
Definition at line 5318 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   integer(kind=int32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_int64()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_int64 (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, integer(kind=int64), intent(in) item) private
Definition at line 5345 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   integer(kind=int64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_logical()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_logical (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, logical, intent(in) item) private
Definition at line 5480 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   logical, intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_object()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_object (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, class(object), intent(in) item) private
Definition at line 5281 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   class(object), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   ierror = pyobject_setitem(self%py_object, ind_py, item%py_object)
   call py_decref(ind_py)
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_real32()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_real32 (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, real(kind=real32), intent(in) item) private
Definition at line 5372 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   real(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int32_real64()
integer(kind=c_int) function forpy_mod::mapping_setitem_int32_real64 (class(mapping), intent(inout) self, integer(kind=int32), intent(in) key, real(kind=real64), intent(in) item) private
Definition at line 5399 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int32), intent(in) :: key
   real(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_char_1d()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_char_1d (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, character(kind=c_char), dimension(:), intent(in) item) private
Definition at line 5787 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   character(kind=C_CHAR), dimension(:), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_chars()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_chars (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, character(kind=c_char, len=*), intent(in) item) private
Definition at line 5814 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   character(kind=C_CHAR, len=*), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_complex_real32()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_complex_real32 (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, complex(kind=real32), intent(in) item) private
Definition at line 5706 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   complex(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_complex_real64()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_complex_real64 (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, complex(kind=real64), intent(in) item) private
Definition at line 5733 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   complex(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_int32()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_int32 (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, integer(kind=int32), intent(in) item) private
Definition at line 5598 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   integer(kind=int32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_int64()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_int64 (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, integer(kind=int64), intent(in) item) private
Definition at line 5625 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   integer(kind=int64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_logical()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_logical (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, logical, intent(in) item) private
Definition at line 5760 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   logical, intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_object()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_object (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, class(object), intent(in) item) private
Definition at line 5561 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   class(object), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: ind_py
   ierror = box_value(ind_py, key)
   if (ierror /= 0) then
     return
   endif
   ierror = pyobject_setitem(self%py_object, ind_py, item%py_object)
   call py_decref(ind_py)
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_real32()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_real32 (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, real(kind=real32), intent(in) item) private
Definition at line 5652 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   real(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_int64_real64()
integer(kind=c_int) function forpy_mod::mapping_setitem_int64_real64 (class(mapping), intent(inout) self, integer(kind=int64), intent(in) key, real(kind=real64), intent(in) item) private
Definition at line 5679 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   integer(kind=int64), intent(in) :: key
   real(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py, ind_py
   ierror = box_value(ind_py, key)
   if (ierror == 0_c_int) then
     ierror = box_value(item_py, item)
     if (ierror /= 0) then
       call py_decref(ind_py)
       return
     endif
   endif
   if (ierror == 0_c_int) then
     ierror = pyobject_setitem(self%py_object, ind_py, item_py)
     call py_decref(item_py)
     call py_decref(ind_py)
   endif
Referenced by forpy_mod::mapping::setitem().
mapping_setitem_object_object()
integer(kind=c_int) function forpy_mod::mapping_setitem_object_object (class(mapping), intent(inout) self, class(object), intent(in) key, class(object), intent(in) item) private
Definition at line 5262 of file forpy_mod.F90.
   class(Mapping), intent(inout) :: self
   class(object), intent(in) :: key
   class(object), intent(in) :: item
   integer(kind=C_INT):: ierror
   ierror = pyobject_setitem(self%py_object, key%py_object, item%py_object)
Referenced by forpy_mod::mapping::setitem().
mutablesequence_setitem_int32_char_1d()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_char_1d (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, character(kind=c_char), dimension(:), intent(in) item) private
Definition at line 3785 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   character(kind=C_CHAR), dimension(:), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int32_chars()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_chars (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, character(kind=c_char, len=*), intent(in) item) private
Definition at line 3803 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   character(kind=C_CHAR, len=*), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int32_complex_real32()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_complex_real32 (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, complex(kind=real32), intent(in) item) private
Definition at line 3731 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   complex(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int32_complex_real64()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_complex_real64 (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, complex(kind=real64), intent(in) item) private
Definition at line 3749 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   complex(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int32_int32()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_int32 (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, integer(kind=int32), intent(in) item) private
Definition at line 3659 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   integer(kind=int32), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int32_int64()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_int64 (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, integer(kind=int64), intent(in) item) private
Definition at line 3677 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   integer(kind=int64), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int32_logical()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_logical (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, logical, intent(in) item) private
Definition at line 3767 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   logical, intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int32_object()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_object (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, class(object), intent(in) item) private
Definition at line 3645 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   class(object), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item%py_object)
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int32_real32()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_real32 (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, real(kind=real32), intent(in) item) private
Definition at line 3695 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   real(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int32_real64()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int32_real64 (class(mutablesequence), intent(inout) self, integer(kind=int32), intent(in) ind, real(kind=real64), intent(in) item) private
Definition at line 3713 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   real(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_char_1d()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_char_1d (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, character(kind=c_char), dimension(:), intent(in) item) private
Definition at line 3961 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   character(kind=C_CHAR), dimension(:), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_chars()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_chars (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, character(kind=c_char, len=*), intent(in) item) private
Definition at line 3979 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   character(kind=C_CHAR, len=*), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_complex_real32()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_complex_real32 (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, complex(kind=real32), intent(in) item) private
Definition at line 3907 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   complex(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_complex_real64()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_complex_real64 (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, complex(kind=real64), intent(in) item) private
Definition at line 3925 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   complex(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_int32()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_int32 (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, integer(kind=int32), intent(in) item) private
Definition at line 3835 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   integer(kind=int32), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_int64()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_int64 (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, integer(kind=int64), intent(in) item) private
Definition at line 3853 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   integer(kind=int64), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_logical()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_logical (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, logical, intent(in) item) private
Definition at line 3943 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   logical, intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_object()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_object (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, class(object), intent(in) item) private
Definition at line 3821 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   class(object), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item%py_object)
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_real32()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_real32 (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, real(kind=real32), intent(in) item) private
Definition at line 3871 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   real(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
mutablesequence_setitem_int64_real64()
integer(kind=c_int) function forpy_mod::mutablesequence_setitem_int64_real64 (class(mutablesequence), intent(inout) self, integer(kind=int64), intent(in) ind, real(kind=real64), intent(in) item) private
Definition at line 3889 of file forpy_mod.F90.
   class(MutableSequence), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   real(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   if (ierror == 0) then
     ierror = pysequence_setitem(self%py_object, ind_py_ssize_t, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::mutablesequence::setitem().
ndarray_copy()
integer(kind=c_int) function forpy_mod::ndarray_copy (class(ndarray), intent(in) self, type(ndarray), intent(out) array_copy, character(kind=c_char), intent(in), optional order) private
Returns copy of a ndarray.
order (optional) can be 'F', 'C', 'A' or 'K' (default is 'F' - in numpy it is 'C')
Definition at line 9652 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   type(ndarray), intent(out) :: array_copy
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR) :: the_order
   type(object) :: retval
   type(tuple) :: args
   if (.not. present(order)) then
     the_order = 'F'
   else
     the_order = order
   endif
   ierror = tuple_create(args, 1_py_ssize_t_kind)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = args%setitem(0_py_ssize_t_kind, the_order)
   if (ierror == 0_c_int) then
     ierror = call_py(retval, self, "copy", args)
   endif
   call args%destroy
   if (ierror == 0_c_int) then
     ierror = cast(array_copy, retval)
     call retval%destroy
   endif
ndarray_create_complex_real32_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_complex_real32_1d (type(ndarray), intent(out) res, complex(kind=real32), dimension(:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 7597 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   complex(kind=real32), dimension(:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   complex(kind=real32), dimension(:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "complex64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_complex_real32_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_complex_real32_2d (type(ndarray), intent(out) res, complex(kind=real32), dimension(:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8101 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   complex(kind=real32), dimension(:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   complex(kind=real32), dimension(:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "complex64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_complex_real32_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_complex_real32_3d (type(ndarray), intent(out) res, complex(kind=real32), dimension(:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8605 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   complex(kind=real32), dimension(:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   complex(kind=real32), dimension(:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "complex64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_complex_real32_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_complex_real32_4d (type(ndarray), intent(out) res, complex(kind=real32), dimension(:,:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 9109 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   complex(kind=real32), dimension(:,:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   complex(kind=real32), dimension(:,:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "complex64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_complex_real64_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_complex_real64_1d (type(ndarray), intent(out) res, complex(kind=real64), dimension(:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 7681 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   complex(kind=real64), dimension(:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   complex(kind=real64), dimension(:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "complex128")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_complex_real64_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_complex_real64_2d (type(ndarray), intent(out) res, complex(kind=real64), dimension(:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8185 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   complex(kind=real64), dimension(:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   complex(kind=real64), dimension(:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "complex128")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_complex_real64_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_complex_real64_3d (type(ndarray), intent(out) res, complex(kind=real64), dimension(:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8689 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   complex(kind=real64), dimension(:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   complex(kind=real64), dimension(:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "complex128")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_complex_real64_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_complex_real64_4d (type(ndarray), intent(out) res, complex(kind=real64), dimension(:,:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 9193 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   complex(kind=real64), dimension(:,:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   complex(kind=real64), dimension(:,:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "complex128")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_empty_aint32()
integer(kind=c_int) function forpy_mod::ndarray_create_empty_aint32 (type(ndarray), intent(out) array, integer(kind=int32), dimension(:), intent(in) a_shape, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting ndarray.
[in] a_shape Shape of ndarray to create.
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F')
Returns
Error code, 0 on success
Definition at line 9817 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int32), dimension(:), intent(in) :: a_shape
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "empty", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int32(array, "empty", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "empty", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int32(array, "empty", a_shape, "", "F")
     endif
   endif
ndarray_create_empty_aint64()
integer(kind=c_int) function forpy_mod::ndarray_create_empty_aint64 (type(ndarray), intent(out) array, integer(kind=int64), dimension(:), intent(in) a_shape, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting ndarray.
[in] a_shape Shape of ndarray to create.
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F')
Returns
Error code, 0 on success
Definition at line 9845 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int64), dimension(:), intent(in) :: a_shape
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "empty", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int64(array, "empty", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "empty", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int64(array, "empty", a_shape, "", "F")
     endif
   endif
ndarray_create_empty_int32()
integer(kind=c_int) function forpy_mod::ndarray_create_empty_int32 (type(ndarray), intent(out) array, integer(kind=int32), intent(in) length, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting one dimensional ndarray.
[in] length Number of elements in ndarray
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F'). In case of 1D array not relevant.
Returns
Error code, 0 on success
Definition at line 9874 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int32), intent(in) :: length
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   integer(kind=int32) :: a_shape(1)
   a_shape(1) = length
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "empty", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int32(array, "empty", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "empty", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int32(array, "empty", a_shape, "", "F")
     endif
   endif
ndarray_create_empty_int64()
integer(kind=c_int) function forpy_mod::ndarray_create_empty_int64 (type(ndarray), intent(out) array, integer(kind=int64), intent(in) length, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting one dimensional ndarray.
[in] length Number of elements in ndarray
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F'). In case of 1D array not relevant.
Returns
Error code, 0 on success
Definition at line 9905 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int64), intent(in) :: length
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   integer(kind=int64) :: a_shape(1)
   a_shape(1) = length
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "empty", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int64(array, "empty", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "empty", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int64(array, "empty", a_shape, "", "F")
     endif
   endif
ndarray_create_int32_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_int32_1d (type(ndarray), intent(out) res, integer(kind=int32), dimension(:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 7261 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   integer(kind=int32), dimension(:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer(kind=int32), dimension(:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "int32")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_int32_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_int32_2d (type(ndarray), intent(out) res, integer(kind=int32), dimension(:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 7765 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   integer(kind=int32), dimension(:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer(kind=int32), dimension(:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "int32")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_int32_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_int32_3d (type(ndarray), intent(out) res, integer(kind=int32), dimension(:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8269 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   integer(kind=int32), dimension(:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer(kind=int32), dimension(:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "int32")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_int32_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_int32_4d (type(ndarray), intent(out) res, integer(kind=int32), dimension(:,:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8773 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   integer(kind=int32), dimension(:,:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer(kind=int32), dimension(:,:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "int32")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_int64_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_int64_1d (type(ndarray), intent(out) res, integer(kind=int64), dimension(:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 7345 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   integer(kind=int64), dimension(:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer(kind=int64), dimension(:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "int64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_int64_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_int64_2d (type(ndarray), intent(out) res, integer(kind=int64), dimension(:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 7849 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   integer(kind=int64), dimension(:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer(kind=int64), dimension(:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "int64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_int64_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_int64_3d (type(ndarray), intent(out) res, integer(kind=int64), dimension(:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8353 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   integer(kind=int64), dimension(:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer(kind=int64), dimension(:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "int64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_int64_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_int64_4d (type(ndarray), intent(out) res, integer(kind=int64), dimension(:,:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8857 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   integer(kind=int64), dimension(:,:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer(kind=int64), dimension(:,:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "int64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_nocopy_complex_real32_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_complex_real32_1d (type(ndarray), intent(out) res, complex(kind=real32), dimension(:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7575 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   complex(kind=real32), dimension(:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "Zf" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "complex64")
 #endif
ndarray_create_nocopy_complex_real32_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_complex_real32_2d (type(ndarray), intent(out) res, complex(kind=real32), dimension(:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8079 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   complex(kind=real32), dimension(:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "Zf" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "complex64")
 #endif
ndarray_create_nocopy_complex_real32_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_complex_real32_3d (type(ndarray), intent(out) res, complex(kind=real32), dimension(:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8583 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   complex(kind=real32), dimension(:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "Zf" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "complex64")
 #endif
ndarray_create_nocopy_complex_real32_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_complex_real32_4d (type(ndarray), intent(out) res, complex(kind=real32), dimension(:,:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 9087 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   complex(kind=real32), dimension(:,:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "Zf" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "complex64")
 #endif
ndarray_create_nocopy_complex_real64_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_complex_real64_1d (type(ndarray), intent(out) res, complex(kind=real64), dimension(:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7659 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   complex(kind=real64), dimension(:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 16_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "Zd" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "complex128")
 #endif
ndarray_create_nocopy_complex_real64_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_complex_real64_2d (type(ndarray), intent(out) res, complex(kind=real64), dimension(:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8163 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   complex(kind=real64), dimension(:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 16_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "Zd" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "complex128")
 #endif
ndarray_create_nocopy_complex_real64_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_complex_real64_3d (type(ndarray), intent(out) res, complex(kind=real64), dimension(:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8667 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   complex(kind=real64), dimension(:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 16_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "Zd" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "complex128")
 #endif
ndarray_create_nocopy_complex_real64_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_complex_real64_4d (type(ndarray), intent(out) res, complex(kind=real64), dimension(:,:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 9171 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   complex(kind=real64), dimension(:,:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 16_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "Zd" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "complex128")
 #endif
ndarray_create_nocopy_helper()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_helper (type(ndarray), intent(inout) res, type(c_ptr), intent(in) array_c_loc, integer(kind=py_ssize_t_kind), dimension(ndim), intent(in), target array_shape, integer, intent(in) ndim, integer(kind=py_ssize_t_kind) itemsize, character(kind=c_char, len=*), intent(in), target format_c_string) private
Definition at line 9257 of file forpy_mod.F90.
   type(ndarray), intent(inout) :: res
   type(c_ptr), intent(in) :: array_c_loc
   integer, intent(in) :: ndim
   integer(kind=PY_SSIZE_T_KIND), target, dimension(ndim), intent(in) :: array_shape
   integer(kind=PY_SSIZE_T_KIND) :: itemsize
   character(kind=C_CHAR, len=*), target, intent(in) :: format_c_string
   integer(kind=C_INT) :: ierror
   type(Py_buffer) :: buffer
   integer(kind=PY_SSIZE_T_KIND), target, dimension(ndim) :: strides
   integer(kind=PY_SSIZE_T_KIND) :: length
   type(c_ptr) :: mem_view
   type(c_ptr) :: args
   integer :: ii
   !TODO: check if numpy was successfully imported
   ierror = 0_c_int
   res%py_object = c_null_ptr
   length = 1
   do ii = 1, ndim
     length = length * array_shape(ii)
   enddo
   ! calculate the strides assuming Fortran-order
   call pybuffer_fillcontiguousstrides(int(ndim, kind=c_int), c_loc(array_shape), c_loc(strides), itemsize, 'F')
   buffer%buf = array_c_loc
   buffer%obj = c_null_ptr
   buffer%len = length * itemsize
   buffer%itemsize = itemsize
   buffer%readonly = 0_c_int
   buffer%ndim = int(ndim, c_int)
   buffer%format = c_loc(format_c_string)
   buffer%shape = c_loc(array_shape)
   buffer%strides = c_loc(strides)
   buffer%suboffsets = c_null_ptr
 #ifdef PYTHON2
   buffer%smalltable = 0_py_ssize_t_kind
 #endif
   buffer%internal = c_null_ptr
   mem_view = pymemoryview_frombuffer(buffer)
   if (.not. c_associated(mem_view)) then
     ierror = -1_c_int
     return
   endif
   args = pytuple_new(1_py_ssize_t_kind)
   if (c_associated(args)) then
     ierror = pytuple_setitem(args, 0_py_ssize_t_kind, mem_view) ! steals reference to mem_view even if it fails
     if (ierror /= 0_c_int) then
       call py_decref(args)
       return
     endif
     res%py_object = pyobject_call(global_numpy_asarray_method, args, c_null_ptr)
     call py_decref(args)
     if (.not. c_associated(res%py_object)) then
       ierror = -1_c_int
     endif
   else ! .not. c_associated(args)
     call py_decref(mem_view)
     ierror = -1_c_int
   endif
ndarray_create_nocopy_helper_py2()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_helper_py2 (type(ndarray), intent(inout) res, type(c_ptr), intent(in) array_c_loc, integer(kind=py_ssize_t_kind), dimension(ndim), intent(in), target array_shape, integer, intent(in) ndim, integer(kind=py_ssize_t_kind) itemsize, character(kind=c_char, len=*), intent(in), target dtype) private
Definition at line 9336 of file forpy_mod.F90.
   type(ndarray), intent(inout) :: res
   type(c_ptr), intent(in) :: array_c_loc
   integer, intent(in) :: ndim
   integer(kind=PY_SSIZE_T_KIND), target, dimension(ndim), intent(in) :: array_shape
   integer(kind=PY_SSIZE_T_KIND) :: itemsize
   character(kind=C_CHAR, len=*), target, intent(in) :: dtype
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: length
   type(c_ptr) :: buffer_obj
   type(module_py) :: numpy
   type(tuple) :: args
   type(object) :: retval
   type(object) :: buffer
   type(ndarray) :: reshaped_array
   integer :: ii
   ierror = -1_c_int
   res%py_object = c_null_ptr
   length = 1
   do ii = 1, ndim
     length = length * array_shape(ii)
   enddo
   buffer_obj = pybuffer_fromreadwritememory(array_c_loc, length*itemsize)
   if (.not. c_associated(buffer_obj)) then
     return
   endif
   buffer%py_object = buffer_obj
   ierror = tuple_create(args, 2_py_ssize_t_kind)
   if (ierror /= 0_c_int) then
     call buffer%destroy
     return
   endif
   ierror = args%setitem(0_py_ssize_t_kind, buffer)
   if (ierror /= 0_c_int) then
     call args%destroy
     call buffer%destroy
     return
   endif
   ierror = args%setitem(1_py_ssize_t_kind, dtype)
   if (ierror /= 0_c_int) then
     call args%destroy
     call buffer%destroy
     return
   endif
   numpy%py_object = global_numpy_mod
   ierror = call_py(retval, numpy, "frombuffer", args)
   call args%destroy
   call buffer%destroy
   if (ierror == 0_c_int) then
     res%py_object = retval%py_object
   else
     call retval%destroy
     return
   endif
   if (ndim > 1) then
     ierror = ndarray_reshape_helper(reshaped_array, res, array_shape, 'F')
     call res%destroy
     if (ierror == 0_c_int) then
       res%py_object = reshaped_array%py_object
     else
       res%py_object = c_null_ptr
     endif
   endif
ndarray_create_nocopy_int32_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_int32_1d (type(ndarray), intent(out) res, integer(kind=int32), dimension(:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7239 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   integer(kind=int32), dimension(:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 4_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "i" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "int32")
 #endif
ndarray_create_nocopy_int32_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_int32_2d (type(ndarray), intent(out) res, integer(kind=int32), dimension(:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7743 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   integer(kind=int32), dimension(:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 4_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "i" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "int32")
 #endif
ndarray_create_nocopy_int32_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_int32_3d (type(ndarray), intent(out) res, integer(kind=int32), dimension(:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8247 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   integer(kind=int32), dimension(:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 4_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "i" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "int32")
 #endif
ndarray_create_nocopy_int32_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_int32_4d (type(ndarray), intent(out) res, integer(kind=int32), dimension(:,:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8751 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   integer(kind=int32), dimension(:,:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 4_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "i" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "int32")
 #endif
ndarray_create_nocopy_int64_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_int64_1d (type(ndarray), intent(out) res, integer(kind=int64), dimension(:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7323 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   integer(kind=int64), dimension(:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "l" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "int64")
 #endif
ndarray_create_nocopy_int64_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_int64_2d (type(ndarray), intent(out) res, integer(kind=int64), dimension(:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7827 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   integer(kind=int64), dimension(:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "l" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "int64")
 #endif
ndarray_create_nocopy_int64_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_int64_3d (type(ndarray), intent(out) res, integer(kind=int64), dimension(:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8331 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   integer(kind=int64), dimension(:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "l" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "int64")
 #endif
ndarray_create_nocopy_int64_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_int64_4d (type(ndarray), intent(out) res, integer(kind=int64), dimension(:,:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8835 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   integer(kind=int64), dimension(:,:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "l" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "int64")
 #endif
ndarray_create_nocopy_real32_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_real32_1d (type(ndarray), intent(out) res, real(kind=real32), dimension(:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7407 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   real(kind=real32), dimension(:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 4_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "f" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "float32")
 #endif
ndarray_create_nocopy_real32_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_real32_2d (type(ndarray), intent(out) res, real(kind=real32), dimension(:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7911 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   real(kind=real32), dimension(:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 4_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "f" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "float32")
 #endif
ndarray_create_nocopy_real32_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_real32_3d (type(ndarray), intent(out) res, real(kind=real32), dimension(:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8415 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   real(kind=real32), dimension(:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 4_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "f" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "float32")
 #endif
ndarray_create_nocopy_real32_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_real32_4d (type(ndarray), intent(out) res, real(kind=real32), dimension(:,:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8919 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   real(kind=real32), dimension(:,:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 4_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "f" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "float32")
 #endif
ndarray_create_nocopy_real64_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_real64_1d (type(ndarray), intent(out) res, real(kind=real64), dimension(:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7491 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   real(kind=real64), dimension(:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 1
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "d" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "float64")
 #endif
ndarray_create_nocopy_real64_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_real64_2d (type(ndarray), intent(out) res, real(kind=real64), dimension(:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 7995 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   real(kind=real64), dimension(:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 2
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "d" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "float64")
 #endif
ndarray_create_nocopy_real64_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_real64_3d (type(ndarray), intent(out) res, real(kind=real64), dimension(:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 8499 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   real(kind=real64), dimension(:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 3
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "d" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "float64")
 #endif
ndarray_create_nocopy_real64_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_nocopy_real64_4d (type(ndarray), intent(out) res, real(kind=real64), dimension(:,:,:,:), intent(in), target array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array The Fortran array to wrap as ndarray. NO copy is made. Changes to the ndarray affect the Fortran array and vice versa. MUST be a contiguous array (this is not checked).
Returns
Error code, 0 on success
Definition at line 9003 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   ! Note: can not use the F2008 CONTIGUOUS attribute here, because a
   ! temporary copy of array could be created with limited lifetime.
   real(kind=real64), dimension(:,:,:,:), target, intent(in) :: array
   integer(kind=C_INT) :: ierror
   integer, parameter :: NDIM = 4
   integer(kind=PY_SSIZE_T_KIND), parameter :: ITEMSIZE = 8_py_ssize_t_kind
 #ifndef PYTHON2
   ierror = ndarray_create_nocopy_helper(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "d" // c_null_char)
 #else
   ierror = ndarray_create_nocopy_helper_py2(res, c_loc(array), shape(array, kind=py_ssize_t_kind), ndim, itemsize, "float64")
 #endif
ndarray_create_ones_aint32()
integer(kind=c_int) function forpy_mod::ndarray_create_ones_aint32 (type(ndarray), intent(out) array, integer(kind=int32), dimension(:), intent(in) a_shape, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting ndarray.
[in] a_shape Shape of ndarray to create.
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F')
Returns
Error code, 0 on success
Definition at line 10055 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int32), dimension(:), intent(in) :: a_shape
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "ones", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int32(array, "ones", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "ones", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int32(array, "ones", a_shape, "", "F")
     endif
   endif
ndarray_create_ones_aint64()
integer(kind=c_int) function forpy_mod::ndarray_create_ones_aint64 (type(ndarray), intent(out) array, integer(kind=int64), dimension(:), intent(in) a_shape, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting ndarray.
[in] a_shape Shape of ndarray to create.
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F')
Returns
Error code, 0 on success
Definition at line 10083 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int64), dimension(:), intent(in) :: a_shape
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "ones", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int64(array, "ones", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "ones", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int64(array, "ones", a_shape, "", "F")
     endif
   endif
ndarray_create_ones_int32()
integer(kind=c_int) function forpy_mod::ndarray_create_ones_int32 (type(ndarray), intent(out) array, integer(kind=int32), intent(in) length, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting one dimensional ndarray.
[in] length Number of elements in ndarray
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F'). In case of 1D array not relevant.
Returns
Error code, 0 on success
Definition at line 10112 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int32), intent(in) :: length
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   integer(kind=int32) :: a_shape(1)
   a_shape(1) = length
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "ones", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int32(array, "ones", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "ones", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int32(array, "ones", a_shape, "", "F")
     endif
   endif
ndarray_create_ones_int64()
integer(kind=c_int) function forpy_mod::ndarray_create_ones_int64 (type(ndarray), intent(out) array, integer(kind=int64), intent(in) length, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting one dimensional ndarray.
[in] length Number of elements in ndarray
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F'). In case of 1D array not relevant.
Returns
Error code, 0 on success
Definition at line 10143 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int64), intent(in) :: length
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   integer(kind=int64) :: a_shape(1)
   a_shape(1) = length
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "ones", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int64(array, "ones", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "ones", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int64(array, "ones", a_shape, "", "F")
     endif
   endif
ndarray_create_real32_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_real32_1d (type(ndarray), intent(out) res, real(kind=real32), dimension(:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 7429 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   real(kind=real32), dimension(:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   real(kind=real32), dimension(:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "float32")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_real32_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_real32_2d (type(ndarray), intent(out) res, real(kind=real32), dimension(:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 7933 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   real(kind=real32), dimension(:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   real(kind=real32), dimension(:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "float32")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_real32_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_real32_3d (type(ndarray), intent(out) res, real(kind=real32), dimension(:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8437 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   real(kind=real32), dimension(:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   real(kind=real32), dimension(:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "float32")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_real32_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_real32_4d (type(ndarray), intent(out) res, real(kind=real32), dimension(:,:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8941 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   real(kind=real32), dimension(:,:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   real(kind=real32), dimension(:,:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "float32")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_real64_1d()
integer(kind=c_int) function forpy_mod::ndarray_create_real64_1d (type(ndarray), intent(out) res, real(kind=real64), dimension(:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 7513 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   real(kind=real64), dimension(:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   real(kind=real64), dimension(:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "float64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_real64_2d()
integer(kind=c_int) function forpy_mod::ndarray_create_real64_2d (type(ndarray), intent(out) res, real(kind=real64), dimension(:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8017 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   real(kind=real64), dimension(:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   real(kind=real64), dimension(:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "float64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_real64_3d()
integer(kind=c_int) function forpy_mod::ndarray_create_real64_3d (type(ndarray), intent(out) res, real(kind=real64), dimension(:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 8521 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   real(kind=real64), dimension(:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   real(kind=real64), dimension(:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "float64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_real64_4d()
integer(kind=c_int) function forpy_mod::ndarray_create_real64_4d (type(ndarray), intent(out) res, real(kind=real64), dimension(:,:,:,:), intent(in) array) private
Parameters
[out] res The resulting ndarray (in Fortran storage order).
[in] array Create a new ndarray with a copy of the data given in 'array'
Returns
Error code, 0 on success
Definition at line 9025 of file forpy_mod.F90.
   type(ndarray), intent(out) :: res
   real(kind=real64), dimension(:,:,:,:), intent(in) :: array
   integer(kind=C_INT) :: ierror
   real(kind=real64), dimension(:,:,:,:), pointer :: ptr
   ierror = ndarray_create_empty(res, shape(array, kind=py_ssize_t_kind), "float64")
   if (ierror /= 0_c_int) return
   ierror = res%get_data(ptr)
   if (ierror /= 0_c_int) then
     call res%destroy
     res%py_object = c_null_ptr
     return
   endif
   ptr = array
ndarray_create_special_getargs_int32()
integer(kind=c_int) function forpy_mod::ndarray_create_special_getargs_int32 (type(tuple), intent(out) args, integer(kind=int32), dimension(:), intent(in) a_shape) private
Definition at line 10205 of file forpy_mod.F90.
   type(tuple), intent(out) :: args
   integer(kind=int32), dimension(:), intent(in) :: a_shape
   integer(kind=C_INT) :: ierror
   type(tuple) :: shape_tuple
   ierror = tuple_from_array_int32(shape_tuple, a_shape)
   if (ierror /= 0_c_int) return
   ierror = tuple_create(args, 1_py_ssize_t_kind)
   if (ierror /= 0_c_int) then
     call shape_tuple%destroy
     return
   endif
   ierror = args%setitem(0_py_ssize_t_kind, shape_tuple)
   call shape_tuple%destroy
ndarray_create_special_getargs_int64()
integer(kind=c_int) function forpy_mod::ndarray_create_special_getargs_int64 (type(tuple), intent(out) args, integer(kind=int64), dimension(:), intent(in) a_shape) private
Definition at line 10302 of file forpy_mod.F90.
   type(tuple), intent(out) :: args
   integer(kind=int64), dimension(:), intent(in) :: a_shape
   integer(kind=C_INT) :: ierror
   type(tuple) :: shape_tuple
   ierror = tuple_from_array_int64(shape_tuple, a_shape)
   if (ierror /= 0_c_int) return
   ierror = tuple_create(args, 1_py_ssize_t_kind)
   if (ierror /= 0_c_int) then
     call shape_tuple%destroy
     return
   endif
   ierror = args%setitem(0_py_ssize_t_kind, shape_tuple)
   call shape_tuple%destroy
ndarray_create_special_helper_int32()
integer(kind=c_int) function forpy_mod::ndarray_create_special_helper_int32 (type(ndarray), intent(out) array, character(kind=c_char, len=*), intent(in) creator_function, integer(kind=int32), dimension(:), intent(in) a_shape, type(dict), intent(in) kwargs) private
Definition at line 10225 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   character(kind=C_CHAR, len=*), intent(in) :: creator_function
   integer(kind=int32), dimension(:), intent(in) :: a_shape
   type(dict), intent(in) :: kwargs
   integer(kind=C_INT) :: ierror
   type(tuple) :: args
   type(object) :: retval
   type(module_py) :: numpy_mod
   ierror = ndarray_create_special_getargs_int32(args, a_shape)
   if (ierror /= 0_c_int) return
   numpy_mod%py_object = global_numpy_mod
   ierror = call_py(retval, numpy_mod, creator_function, args, kwargs)
   if (ierror == 0_c_int) then
     ierror = cast(array, retval)
     call retval%destroy
   endif
   call args%destroy
ndarray_create_special_helper_int64()
integer(kind=c_int) function forpy_mod::ndarray_create_special_helper_int64 (type(ndarray), intent(out) array, character(kind=c_char, len=*), intent(in) creator_function, integer(kind=int64), dimension(:), intent(in) a_shape, type(dict), intent(in) kwargs) private
Definition at line 10322 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   character(kind=C_CHAR, len=*), intent(in) :: creator_function
   integer(kind=int64), dimension(:), intent(in) :: a_shape
   type(dict), intent(in) :: kwargs
   integer(kind=C_INT) :: ierror
   type(tuple) :: args
   type(object) :: retval
   type(module_py) :: numpy_mod
   ierror = ndarray_create_special_getargs_int64(args, a_shape)
   if (ierror /= 0_c_int) return
   numpy_mod%py_object = global_numpy_mod
   ierror = call_py(retval, numpy_mod, creator_function, args, kwargs)
   if (ierror == 0_c_int) then
     ierror = cast(array, retval)
     call retval%destroy
   endif
   call args%destroy
ndarray_create_special_impl_int32()
integer(kind=c_int) function forpy_mod::ndarray_create_special_impl_int32 (type(ndarray), intent(out) array, character(kind=c_char, len=*), intent(in) creator_function, integer(kind=int32), dimension(:), intent(in) a_shape, character(kind=c_char, len=*), intent(in) dtype, character(kind=c_char), intent(in) order) private
Definition at line 10175 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   character(kind=C_CHAR, len=*), intent(in) :: creator_function
   integer(kind=int32), dimension(:), intent(in) :: a_shape
   character(kind=C_CHAR, len=*), intent(in) :: dtype
   character(kind=C_CHAR), intent(in) :: order
   integer(kind=C_INT) :: ierror
   type(dict) :: kwargs
   ierror = dict_create(kwargs)
   if (ierror /= 0_c_int) return
   if (len(dtype) > 0) then
     ierror = kwargs%setitem("dtype", dtype)
     if (ierror /= 0_c_int) then
       call kwargs%destroy
       return
     endif
   endif
   ierror = kwargs%setitem("order", order)
   if (ierror == 0_c_int) then
     ierror = ndarray_create_special_helper_int32(array, creator_function, a_shape, kwargs)
   endif
   call kwargs%destroy
ndarray_create_special_impl_int64()
integer(kind=c_int) function forpy_mod::ndarray_create_special_impl_int64 (type(ndarray), intent(out) array, character(kind=c_char, len=*), intent(in) creator_function, integer(kind=int64), dimension(:), intent(in) a_shape, character(kind=c_char, len=*), intent(in) dtype, character(kind=c_char), intent(in) order) private
Definition at line 10272 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   character(kind=C_CHAR, len=*), intent(in) :: creator_function
   integer(kind=int64), dimension(:), intent(in) :: a_shape
   character(kind=C_CHAR, len=*), intent(in) :: dtype
   character(kind=C_CHAR), intent(in) :: order
   integer(kind=C_INT) :: ierror
   type(dict) :: kwargs
   ierror = dict_create(kwargs)
   if (ierror /= 0_c_int) return
   if (len(dtype) > 0) then
     ierror = kwargs%setitem("dtype", dtype)
     if (ierror /= 0_c_int) then
       call kwargs%destroy
       return
     endif
   endif
   ierror = kwargs%setitem("order", order)
   if (ierror == 0_c_int) then
     ierror = ndarray_create_special_helper_int64(array, creator_function, a_shape, kwargs)
   endif
   call kwargs%destroy
ndarray_create_zeros_aint32()
integer(kind=c_int) function forpy_mod::ndarray_create_zeros_aint32 (type(ndarray), intent(out) array, integer(kind=int32), dimension(:), intent(in) a_shape, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting ndarray.
[in] a_shape Shape of ndarray to create.
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F')
Returns
Error code, 0 on success
Definition at line 9936 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int32), dimension(:), intent(in) :: a_shape
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "zeros", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int32(array, "zeros", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "zeros", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int32(array, "zeros", a_shape, "", "F")
     endif
   endif
ndarray_create_zeros_aint64()
integer(kind=c_int) function forpy_mod::ndarray_create_zeros_aint64 (type(ndarray), intent(out) array, integer(kind=int64), dimension(:), intent(in) a_shape, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting ndarray.
[in] a_shape Shape of ndarray to create.
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F')
Returns
Error code, 0 on success
Definition at line 9964 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int64), dimension(:), intent(in) :: a_shape
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "zeros", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int64(array, "zeros", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "zeros", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int64(array, "zeros", a_shape, "", "F")
     endif
   endif
ndarray_create_zeros_int32()
integer(kind=c_int) function forpy_mod::ndarray_create_zeros_int32 (type(ndarray), intent(out) array, integer(kind=int32), intent(in) length, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting one dimensional ndarray.
[in] length Number of elements in ndarray
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F'). In case of 1D array not relevant.
Returns
Error code, 0 on success
Definition at line 9993 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int32), intent(in) :: length
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   integer(kind=int32) :: a_shape(1)
   a_shape(1) = length
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "zeros", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int32(array, "zeros", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int32(array, "zeros", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int32(array, "zeros", a_shape, "", "F")
     endif
   endif
ndarray_create_zeros_int64()
integer(kind=c_int) function forpy_mod::ndarray_create_zeros_int64 (type(ndarray), intent(out) array, integer(kind=int64), intent(in) length, character(kind=c_char, len=*), intent(in), optional dtype, character(kind=c_char), intent(in), optional order) private
Parameters
[out] array The resulting one dimensional ndarray.
[in] length Number of elements in ndarray
[in] dtype numpy.dtype of ndarray (default: 'float')
[in] order Storage order: 'F' (Fortran) or 'C' (default: 'F'). In case of 1D array not relevant.
Returns
Error code, 0 on success
Definition at line 10024 of file forpy_mod.F90.
   type(ndarray), intent(out) :: array
   integer(kind=int64), intent(in) :: length
   character(kind=C_CHAR, len=*), intent(in), optional :: dtype
   character(kind=C_CHAR), intent(in), optional :: order
   integer(kind=C_INT) :: ierror
   integer(kind=int64) :: a_shape(1)
   a_shape(1) = length
   if (present(dtype)) then
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "zeros", a_shape, dtype, order)
     else
       ! Fortran order as default, in contrast to numpy
       ierror = ndarray_create_special_impl_int64(array, "zeros", a_shape, dtype, "F")
     endif
   else
     if (present(order)) then
       ierror = ndarray_create_special_impl_int64(array, "zeros", a_shape, "", order)
     else
       ierror = ndarray_create_special_impl_int64(array, "zeros", a_shape, "", "F")
     endif
   endif
ndarray_get_dtype_name()
integer(kind=c_int) function forpy_mod::ndarray_get_dtype_name (class(ndarray), intent(in) self, character(kind=c_char, len=:), intent(out), allocatable dtype_name) private
Returns type string of ndarray.
corresponds to Python's ndarray.dtype.name property
Definition at line 9754 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: dtype_name
   integer(kind=C_INT) :: ierror
   type(object) :: dtype, dname
   ierror = self%getattribute(dtype, "dtype")
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = dtype%getattribute(dname, "name")
   if (ierror /= 0_c_int) then
     call dtype%destroy
     return
   endif
   ierror = cast(dtype_name, dname)
   call dtype%destroy
   call dname%destroy
ndarray_is_ordered()
logical function forpy_mod::ndarray_is_ordered (class(ndarray), intent(in) self, character(kind=c_char), intent(in) order) private
Checks if data of ndarray has a specific storage-order.
order can be 'F' (Fortran-order), 'C' (C-order), 'A' (Fortran- or C-order)
Definition at line 9689 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   character(kind=C_CHAR), intent(in) :: order
   logical :: is_ordered
   type(object) :: retval, flags
   integer(kind=C_INT) :: ierror
   logical :: c_ordered, fortran_ordered, check_c, check_f
   is_ordered = .false.
   c_ordered = .false.
   fortran_ordered = .false.
   if (have_exception()) return
   ierror = self%getattribute(flags, "flags")
   if (ierror /= 0_c_int) then
     call err_clear
     return
   endif
   check_f = (order == 'F') .or. (order == 'A')
   if (check_f) then
     ierror = flags%getattribute(retval, "f_contiguous")
     if (ierror /= 0_c_int) then
       call flags%destroy
       call err_clear
       return
     endif
     ierror = cast(fortran_ordered, retval)
     call retval%destroy
     if (ierror /= 0_c_int) then
       call flags%destroy
       call err_clear
       return
     endif
   endif
   check_c = (order == 'C') .or. (order == 'A' .and. .not. fortran_ordered)
   if (check_c) then
     ierror = flags%getattribute(retval, "c_contiguous")
     if (ierror /= 0_c_int) then
       call flags%destroy
       call err_clear
       return
     endif
     ierror = cast(c_ordered, retval)
     call retval%destroy
     if (ierror /= 0_c_int) then
       call flags%destroy
       call err_clear
       return
     endif
   endif
   call flags%destroy
   is_ordered = fortran_ordered .or. c_ordered
ndarray_ndim_int32()
integer(kind=c_int) function forpy_mod::ndarray_ndim_int32 (class(ndarray), intent(in) self, integer(kind=int32), intent(out) ndim) private
Returns dimensionality of ndarray (ndarray.ndim)
Parameters
[out] ndim Output: dimensionality of array.
Definition at line 9778 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int32), intent(out) :: ndim
   integer(kind=C_INT) :: ierror
   type(object) :: ndim_obj
   ierror = self%getattribute(ndim_obj, "ndim")
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = cast(ndim, ndim_obj)
   call ndim_obj%destroy
Referenced by forpy_mod::ndarray::ndim().
ndarray_ndim_int64()
integer(kind=c_int) function forpy_mod::ndarray_ndim_int64 (class(ndarray), intent(in) self, integer(kind=int64), intent(out) ndim) private
Returns dimensionality of ndarray (ndarray.ndim)
Parameters
[out] ndim Output: dimensionality of array.
Definition at line 9796 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   integer(kind=int64), intent(out) :: ndim
   integer(kind=C_INT) :: ierror
   type(object) :: ndim_obj
   ierror = self%getattribute(ndim_obj, "ndim")
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = cast(ndim, ndim_obj)
   call ndim_obj%destroy
Referenced by forpy_mod::ndarray::ndim().
ndarray_reshape_helper()
integer(kind=c_int) function forpy_mod::ndarray_reshape_helper (type(ndarray), intent(out) reshaped_array, class(ndarray), intent(in) array, integer(kind=py_ssize_t_kind), dimension(:), intent(in) new_shape, character(kind=c_char), intent(in) order) private
Definition at line 9413 of file forpy_mod.F90.
   type(ndarray), intent(out) :: reshaped_array
   class(ndarray), intent(in) :: array
   integer(kind=PY_SSIZE_T_KIND), dimension(:), intent(in) :: new_shape
   character(kind=C_CHAR), intent(in) :: order
   integer(kind=C_INT) :: ierror
   type(tuple) :: args
   type(dict) :: kwargs
   type(tuple) :: new_shape_tuple
   type(object) :: retval
   reshaped_array%py_object = c_null_ptr
   ierror = tuple_from_array(new_shape_tuple, new_shape)
   if (ierror /= 0_c_int) then
     return
   endif
   ierror = tuple_create(args, 1_py_ssize_t_kind)
   if (ierror /= 0_c_int) then
     call new_shape_tuple%destroy
     return
   endif
   ierror = args%setitem(0_py_ssize_t_kind, new_shape_tuple)
   if (ierror /= 0_c_int) then
     call args%destroy
     call new_shape_tuple%destroy
     return
   endif
   ierror = dict_create(kwargs)
   if (ierror /= 0_c_int) then
     call args%destroy
     call new_shape_tuple%destroy
     return
   endif
   ierror = kwargs%setitem("order", order)
   if (ierror /= 0_c_int) then
     call kwargs%destroy
     call args%destroy
     call new_shape_tuple%destroy
     return
   endif
   ierror = call_py(retval, array, "reshape", args, kwargs)
   if (ierror == 0_c_int) then
     ierror = cast(reshaped_array, retval)
     call retval%destroy
   endif
   call kwargs%destroy
   call args%destroy
   call new_shape_tuple%destroy
ndarray_transpose()
integer(kind=c_int) function forpy_mod::ndarray_transpose (class(ndarray), intent(in) self, type(ndarray), intent(out) transposed_array) private
Return transpose of a ndarray.
Definition at line 9634 of file forpy_mod.F90.
   class(ndarray), intent(in) :: self
   type(ndarray), intent(out) :: transposed_array
   integer(kind=C_INT) :: ierror
   type(object) :: retval
   ierror = call_py(retval, self, "transpose")
   if (ierror == 0_c_int) then
     ierror = cast(transposed_array, retval)
     call retval%destroy
   endif
nonetype_create()
integer(kind=c_int) function, public forpy_mod::nonetype_create (type(nonetype), intent(out) r)
Creates a Python None.
Parameters
[out] r The created None
Returns
Error code, 0 on success
Definition at line 2741 of file forpy_mod.F90.
   type(NoneType), intent(out) :: r
   integer(kind=C_INT) :: ierror
   r%py_object = global_py_nonestruct_ptr
   call py_incref(global_py_nonestruct_ptr)
   ierror = 0_c_int
object_delattr()
integer(kind=c_int) function forpy_mod::object_delattr (class(object), intent(inout) self, character(kind=c_char, len=*), intent(in) attr_name) private
Definition at line 4453 of file forpy_mod.F90.
   class(object), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: attr_name
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: attr_name_str
   ierror = box_value(attr_name_str, attr_name)
   if (ierror == 0_c_int) then
     ierror = pyobject_setattr(self%py_object, attr_name_str, c_null_ptr)
     call py_decref(attr_name_str)
   endif
object_destroy()
subroutine forpy_mod::object_destroy (class(object), intent(inout) self) private
Definition at line 4474 of file forpy_mod.F90.
   class(object), intent(inout) :: self
   call py_decref(self%py_object)
object_get_c_ptr()
type(c_ptr) function forpy_mod::object_get_c_ptr (class(object), intent(in) self) private
Get C pointer to an object, needed for developing Python extensions.
Definition at line 4468 of file forpy_mod.F90.
   class(object), intent(in) :: self
   type(c_ptr) :: r
   r = self%py_object
object_getattribute()
integer(kind=c_int) function forpy_mod::object_getattribute (class(object), intent(in) self, type(object), intent(out) attr, character(kind=c_char, len=*), intent(in) attr_name) private
Definition at line 4414 of file forpy_mod.F90.
   class(object), intent(in) :: self
   type(object), intent(out) :: attr
   character(kind=C_CHAR, len=*), intent(in) :: attr_name
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: attr_name_str
   ierror = box_value(attr_name_str, attr_name)
   if (ierror == 0_c_int) then
     attr%py_object = pyobject_getattr(self%py_object, attr_name_str)
   else
     return
   endif
   call py_decref(attr_name_str)
   if (.not. c_associated(attr%py_object)) then
     ierror = exception_error
   endif
object_setattr()
integer(kind=c_int) function forpy_mod::object_setattr (class(object), intent(inout) self, character(kind=c_char, len=*), intent(in) attr_name, class(object), intent(in) attr_value) private
Definition at line 4437 of file forpy_mod.F90.
   class(object), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: attr_name
   class(object), intent(in) :: attr_value
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: attr_name_str
   ierror = box_value(attr_name_str, attr_name)
   if (ierror == 0_c_int) then
     ierror = pyobject_setattr(self%py_object, attr_name_str, attr_value%py_object)
     call py_decref(attr_name_str)
   endif
print_py()
integer(kind=c_int) function, public forpy_mod::print_py (class(object), intent(in) obj, class(dict), intent(in), optional kwargs)
Python's print function.
Parameters
[in] obj Object to print.
[in] kwargs Optional dict of keyword arguments
Returns
Error code, 0 on success
Definition at line 11810 of file forpy_mod.F90.
   class(object), intent(in) :: obj
   class(dict), intent(in), optional :: kwargs
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: builtin_dict, tmp
   type(object) :: print_fun
   type(tuple) :: args
   builtin_dict = pyeval_getbuiltins() ! borrowed ref - do not decref
   if (.not. c_associated(builtin_dict)) then
     ierror = exception_error
     return
   endif
   tmp = pydict_getitemstring(builtin_dict, "print" // c_null_char) !borrowed ref
   print_fun%py_object = tmp
   ierror = tuple_create(args, 1)
   if (ierror /= 0_c_int) return
   ierror = args%setitem(0, obj)
   if (ierror /= 0_c_int) then
     call args%destroy
   endif
   if (present(kwargs)) then
     ierror = call_py_noret(print_fun, args, kwargs)
   else
     ierror = call_py_noret(print_fun, args)
   endif
   call args%destroy
   ! do not destroy print_fun: borrowed ref
pythonmethodtable_add_method()
subroutine forpy_mod::pythonmethodtable_add_method (class(pythonmethodtable), intent(inout) self, character(kind=c_char, len=*), intent(in) method_name, character(kind=c_char, len=*), intent(in) doc_string, integer(kind=c_int), intent(in) flags, type(c_funptr), intent(in) method_funptr) private
Parameters
[in] method_name Name of the Python method.
[in] doc_string Doc string for the Python method
[in] flags Controls which kind of arguments the Python method shall take.
use flags=METH_VARARGS if method shall take only arguments. use flags=METH_KWARGS if method shall take only keyword args. use flags=METH_VARARGS+METH_KWARGS if method shall take both arguments and keyword args. use flags=METH_NOARGS if method shall take no arguments.
Parameters
[in] method_funptr Function pointer to the Fortran implementation of the method.
Use C_FUNLOC(<Fortran function>) to get method_funptr The Fortran function must take "TYPE(c_ptr), VALUE" arguments (number depends on what arguments it takes) and have a type(c_ptr) return value. E. g. if flags=METH_VARARGS+METH_KWARGS, one needs 3 arguments (1st arg: module c_ptr, 2nd: arguments c_ptr, 3rd: kwargs c_ptr) use [[unsafe_cast_from_c_ptr]] to cast 2nd argument to a tuple and 3rd argument to a dict. The function must return a Python object type(c_ptr). Use objectget_c_ptr() to retrieve the c_ptr from a forpy object.
Definition at line 11736 of file forpy_mod.F90.
   class(PythonMethodTable), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: method_name
   character(kind=C_CHAR, len=*), intent(in) :: doc_string
   integer(kind=C_INT), intent(in) :: flags
   type(c_funptr), intent(in) :: method_funptr
   integer :: ind
   type(c_ptr) :: method_name_loc, doc_string_loc
   if (self%method_count >= self%num_methods) then
     call raise_exception(importerror, "forpy: Could not add method. Increase num_methods in PythonMethodTable%init")
     return
   endif
   ind = self%method_count + 1
   allocate(character(kind=C_CHAR,len=len(method_name)+1) :: self%strings(ind)%method_name)
   self%strings(ind)%method_name = method_name // c_null_char
   allocate(character(kind=C_CHAR,len=len(doc_string)+1) :: self%strings(ind)%doc_string)
   self%strings(ind)%doc_string = doc_string // c_null_char
   method_name_loc = c_loc(self%strings(ind)%method_name)
   doc_string_loc = c_loc(self%strings(ind)%doc_string)
   self%methods(ind) = pymethoddef(method_name_loc, method_funptr, flags, doc_string_loc)
   self%method_count = self%method_count + 1
pythonmethodtable_get()
type(c_ptr) function forpy_mod::pythonmethodtable_get (class(pythonmethodtable), intent(in) self) private
Definition at line 11785 of file forpy_mod.F90.
   class(PythonMethodTable), intent(in) :: self
   type(c_ptr) :: m
   m = c_loc(self%methods)
pythonmethodtable_init()
subroutine forpy_mod::pythonmethodtable_init (class(pythonmethodtable), intent(inout) self, integer, intent(in) num_methods) private
Parameters
[in] num_methods The number of methods your Python module shall have.
Definition at line 11715 of file forpy_mod.F90.
   class(PythonMethodTable), intent(inout) :: self
   integer, intent(in) :: num_methods
   integer :: ii
   self%num_methods = num_methods
   self%method_count = 0
   ! These are never deallocated
   ! not a big problem, since "de-importing" modules in Python is unusual and
   ! sometimes impossible. There exist kind of a finish method, so this could be a TODO
   allocate(self%methods(num_methods+1)) !need extra space for sentinel entry
   allocate(self%strings(num_methods))
   do ii = 1, num_methods + 1
     ! at the end of methods array there has to be this sentinel value
     ! just to be safe, initialise complete method array with it
     self%methods(ii) = pymethoddef(c_null_ptr, c_null_funptr, 0_c_int, c_null_ptr)
   enddo
pythonmodule_add_object()
integer(kind=c_int) function forpy_mod::pythonmodule_add_object (class(pythonmodule), intent(inout) self, character(kind=c_char, len=*), intent(in) object_name, class(object), intent(in) obj) private
add an object as a member to a module
Parameters
[in] object_name Name of the module member. It can be accessed by module_name.object_name in Python.
[in] obj The object to add as a member to the module.
Returns
Error code, 0 on success.
Definition at line 11702 of file forpy_mod.F90.
   class(PythonModule), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: object_name
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   call py_incref(obj%py_object)  !PyModule_AddObject steals a reference
   ierror = pymodule_addobject(self%module_ptr, object_name // c_null_char, obj%py_object)
pythonmodule_init()
type(c_ptr) function forpy_mod::pythonmodule_init (class(pythonmodule), intent(inout) self, character(kind=c_char, len=*), intent(in) module_name, character(kind=c_char, len=*), intent(in) doc_string, type(pythonmethodtable), intent(in) method_table) private
Parameters
[in] module_name Name of the Python extension module.
[in] doc_string Doc string for the Python extension module.
[in] method_table Table of methods of the Python extension module.
Definition at line 11661 of file forpy_mod.F90.
   class(PythonModule), intent(inout) :: self
   character(kind=C_CHAR, len=*), intent(in) :: module_name
   character(kind=C_CHAR, len=*), intent(in) :: doc_string
   type(PythonMethodTable), intent(in) :: method_table
   type(c_ptr) :: module_ptr
   integer(kind=C_INT), parameter :: PYTHON_API_VERSION = 1013_c_int !api-version is 1013 since 2006 and still is in 2018
   module_ptr = c_null_ptr
   self%module_ptr = c_null_ptr
   allocate(self%module_def) ! never deallocated, for reasons given in PythonMethodTable_init
   self%module_def = pymoduledef(pymoduledef_base(1_py_ssize_t_kind, c_null_ptr, c_null_ptr, &
                                                  0_py_ssize_t_kind, c_null_ptr), &
                                c_null_ptr, c_null_ptr, -1_py_ssize_t_kind, c_null_ptr, c_null_ptr, &
                                c_null_funptr, c_null_funptr, c_null_funptr)
   allocate(character(kind=C_CHAR,len=len(module_name)+1) :: self%module_name)
   self%module_name = module_name // c_null_char
   allocate(character(kind=C_CHAR,len=len(doc_string)+1) :: self%doc_string)
   self%doc_string = doc_string // c_null_char
   self%module_def%m_methods = method_table%get_method_table()
   self%module_def%m_name = c_loc(self%module_name)
   self%module_def%m_doc = c_loc(self%doc_string)
 #ifndef PYTHON2
   module_ptr = pymodule_create2(c_loc(self%module_def), python_api_version)
 #else
   module_ptr = py_initmodule4(self%module_name, self%module_def%m_methods, self%doc_string, c_null_ptr, python_api_version)
 #endif
   self%module_ptr = module_ptr
raise_exception()
subroutine, public forpy_mod::raise_exception (class(object), intent(in) exc_type, character(kind=c_char, len=*), intent(in) message)
raises an exception
Parameters
[in] exc_type The exception to raise.
Example: call raise_exception(ValueError, "bad value")
Definition at line 11647 of file forpy_mod.F90.
   class(object), intent(in) :: exc_type
   character(kind=C_CHAR, len=*), intent(in) :: message
   call pyerr_setstring(exc_type%py_object, message // c_null_char)
run_string()
integer(kind=c_int) function, public forpy_mod::run_string (character(kind=c_char, len=*), intent(in) string)
Run Python code that is given as string.
Parameters
[in] string Python code to run.
Returns
Error code, 0 on success
Definition at line 11867 of file forpy_mod.F90.
   character(kind=C_CHAR, len=*), intent(in) :: string
   integer(kind=C_INT) :: ierror
   integer :: length
   length = len(string)
   ! check if null-byte is at and of string, if not append it, which can
   ! be expensive
   if (string(length:length) == c_null_char) then
     ierror = pyrun_simplestring(string)
   else
     ierror = pyrun_simplestring(string // c_null_char)
   endif
sequence_contains()
integer(kind=c_int) function forpy_mod::sequence_contains (class(sequence), intent(in) self, logical, intent(out) contain_flag, class(object), intent(in) item) private
Definition at line 3629 of file forpy_mod.F90.
   class(sequence), intent(in) :: self
   logical, intent(out) :: contain_flag
   class(object), intent(in) :: item
   integer(kind=C_INT) :: ierror
   ! returns -1 on error, 0 if item not contained, 1 if contained
   ierror = pysequence_contains(self%py_object, item%py_object)
   contain_flag = (ierror == 1_c_int)
   if (contain_flag) then
     ierror = 0_c_int
   endif
sequence_count_int32()
integer(kind=c_int) function forpy_mod::sequence_count_int32 (class(sequence), intent(in) self, integer(kind=int32), intent(out) the_count, class(object), intent(in) item) private
Definition at line 3571 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int32), intent(out) :: the_count
   class(object), intent(in) :: item
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: the_count_tmp
   ierror = 0_c_int
   the_count_tmp = pysequence_count(self%py_object, item%py_object)
   the_count = int(the_count_tmp, int32)
   ! TODO: overflow check
   if (the_count_tmp == -1_py_ssize_t_kind) then
     ierror = exception_error
   endif
Referenced by forpy_mod::sequence::count().
sequence_count_int64()
integer(kind=c_int) function forpy_mod::sequence_count_int64 (class(sequence), intent(in) self, integer(kind=int64), intent(out) the_count, class(object), intent(in) item) private
Definition at line 3609 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int64), intent(out) :: the_count
   class(object), intent(in) :: item
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: the_count_tmp
   ierror = 0_c_int
   the_count_tmp = pysequence_count(self%py_object, item%py_object)
   the_count = int(the_count_tmp, int64)
   ! TODO: overflow check
   if (the_count_tmp == -1_py_ssize_t_kind) then
     ierror = exception_error
   endif
Referenced by forpy_mod::sequence::count().
sequence_getitem_int32_char_1d()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_char_1d (class(sequence), intent(in) self, character(kind=c_char), dimension(:), intent(out), pointer item, integer(kind=int32), intent(in) ind) private
Definition at line 3219 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   character(kind=C_CHAR), dimension(:), pointer, intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int32_chars()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_chars (class(sequence), intent(in) self, character(kind=c_char, len=:), intent(out), allocatable item, integer(kind=int32), intent(in) ind) private
Definition at line 3241 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int32_complex_real32()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_complex_real32 (class(sequence), intent(in) self, complex(kind=real32), intent(out) item, integer(kind=int32), intent(in) ind) private
Definition at line 3153 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   complex(kind=real32), intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int32_complex_real64()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_complex_real64 (class(sequence), intent(in) self, complex(kind=real64), intent(out) item, integer(kind=int32), intent(in) ind) private
Definition at line 3175 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   complex(kind=real64), intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int32_int32()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_int32 (class(sequence), intent(in) self, integer(kind=int32), intent(out) item, integer(kind=int32), intent(in) ind) private
Definition at line 3065 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int32), intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int32_int64()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_int64 (class(sequence), intent(in) self, integer(kind=int64), intent(out) item, integer(kind=int32), intent(in) ind) private
Definition at line 3087 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int64), intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int32_logical()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_logical (class(sequence), intent(in) self, logical, intent(out) item, integer(kind=int32), intent(in) ind) private
Definition at line 3197 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   logical, intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int32_object()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_object (class(sequence), intent(inout) self, type(object), intent(out) item, integer(kind=int32), intent(in) ind) private
Definition at line 3048 of file forpy_mod.F90.
   class(Sequence), intent(inout) :: self
   type(object), intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item%py_object = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item%py_object)) then
     ierror = exception_error
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int32_real32()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_real32 (class(sequence), intent(in) self, real(kind=real32), intent(out) item, integer(kind=int32), intent(in) ind) private
Definition at line 3109 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   real(kind=real32), intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int32_real64()
integer(kind=c_int) function forpy_mod::sequence_getitem_int32_real64 (class(sequence), intent(in) self, real(kind=real64), intent(out) item, integer(kind=int32), intent(in) ind) private
Definition at line 3131 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   real(kind=real64), intent(out) :: item
   integer(kind=int32), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_char_1d()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_char_1d (class(sequence), intent(in) self, character(kind=c_char), dimension(:), intent(out), pointer item, integer(kind=int64), intent(in) ind) private
Definition at line 3434 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   character(kind=C_CHAR), dimension(:), pointer, intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_chars()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_chars (class(sequence), intent(in) self, character(kind=c_char, len=:), intent(out), allocatable item, integer(kind=int64), intent(in) ind) private
Definition at line 3456 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_complex_real32()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_complex_real32 (class(sequence), intent(in) self, complex(kind=real32), intent(out) item, integer(kind=int64), intent(in) ind) private
Definition at line 3368 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   complex(kind=real32), intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_complex_real64()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_complex_real64 (class(sequence), intent(in) self, complex(kind=real64), intent(out) item, integer(kind=int64), intent(in) ind) private
Definition at line 3390 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   complex(kind=real64), intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_int32()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_int32 (class(sequence), intent(in) self, integer(kind=int32), intent(out) item, integer(kind=int64), intent(in) ind) private
Definition at line 3280 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int32), intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_int64()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_int64 (class(sequence), intent(in) self, integer(kind=int64), intent(out) item, integer(kind=int64), intent(in) ind) private
Definition at line 3302 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int64), intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_logical()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_logical (class(sequence), intent(in) self, logical, intent(out) item, integer(kind=int64), intent(in) ind) private
Definition at line 3412 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   logical, intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_object()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_object (class(sequence), intent(inout) self, type(object), intent(out) item, integer(kind=int64), intent(in) ind) private
Definition at line 3263 of file forpy_mod.F90.
   class(Sequence), intent(inout) :: self
   type(object), intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item%py_object = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item%py_object)) then
     ierror = exception_error
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_real32()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_real32 (class(sequence), intent(in) self, real(kind=real32), intent(out) item, integer(kind=int64), intent(in) ind) private
Definition at line 3324 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   real(kind=real32), intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_getitem_int64_real64()
integer(kind=c_int) function forpy_mod::sequence_getitem_int64_real64 (class(sequence), intent(in) self, real(kind=real64), intent(out) item, integer(kind=int64), intent(in) ind) private
Definition at line 3346 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   real(kind=real64), intent(out) :: item
   integer(kind=int64), intent(in) :: ind
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   type(c_ptr) :: item_py
   ierror = 0_c_int
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   item_py = pysequence_getitem(self%py_object, ind_py_ssize_t)
   if (.not. c_associated(item_py)) then
     ierror = exception_error
   else
     ierror = unbox_value(item, item_py)
     call py_decref(item_py)
   endif
Referenced by forpy_mod::sequence::getitem().
sequence_index_int32()
integer(kind=c_int) function forpy_mod::sequence_index_int32 (class(sequence), intent(in) self, integer(kind=int32), intent(out) ind, class(object), intent(in) item) private
Definition at line 3552 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int32), intent(out) :: ind
   class(object), intent(in) :: item
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_tmp
   ierror = 0_c_int
   ind_tmp = pysequence_index(self%py_object, item%py_object)
   ind = int(ind_tmp, int32)
   ! TODO: overflow check
   if (ind_tmp == -1_py_ssize_t_kind) then
     ierror = exception_error
   endif
Referenced by forpy_mod::sequence::index().
sequence_index_int64()
integer(kind=c_int) function forpy_mod::sequence_index_int64 (class(sequence), intent(in) self, integer(kind=int64), intent(out) ind, class(object), intent(in) item) private
Definition at line 3590 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int64), intent(out) :: ind
   class(object), intent(in) :: item
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_tmp
   ierror = 0_c_int
   ind_tmp = pysequence_index(self%py_object, item%py_object)
   ind = int(ind_tmp, int64)
   ! TODO: overflow check
   if (ind_tmp == -1_py_ssize_t_kind) then
     ierror = exception_error
   endif
Referenced by forpy_mod::sequence::index().
sequence_len_int32()
integer(kind=c_int) function forpy_mod::sequence_len_int32 (class(sequence), intent(in) self, integer(kind=int32), intent(out) length) private
Definition at line 3479 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int32), intent(out) :: length
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: length_tmp
   ierror = 0_c_int
   length_tmp = pyobject_length(self%py_object)
   length = int(length_tmp, int32)
   ! TODO: overflow check
   if (length_tmp == -1_py_ssize_t_kind) then
     ierror = exception_error
   endif
Referenced by forpy_mod::sequence::len().
sequence_len_int64()
integer(kind=c_int) function forpy_mod::sequence_len_int64 (class(sequence), intent(in) self, integer(kind=int64), intent(out) length) private
Definition at line 3497 of file forpy_mod.F90.
   class(Sequence), intent(in) :: self
   integer(kind=int64), intent(out) :: length
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: length_tmp
   ierror = 0_c_int
   length_tmp = pyobject_length(self%py_object)
   length = int(length_tmp, int64)
   ! TODO: overflow check
   if (length_tmp == -1_py_ssize_t_kind) then
     ierror = exception_error
   endif
Referenced by forpy_mod::sequence::len().
str_create_char_1d()
integer(kind=c_int) function forpy_mod::str_create_char_1d (type(str), intent(out) r, character(kind=c_char), dimension(:), intent(in) string) private
Definition at line 7039 of file forpy_mod.F90.
   type(str), intent(out) :: r
   character(kind=C_CHAR), dimension(:), intent(in) :: string
   integer(kind=C_INT) :: ierror
 #ifdef PYTHON2
   ierror = box_value_char_1d_as_bytestr(r%py_object, string)
 #else
   ierror = box_value_char_1d_as_unicodestr(r%py_object, string)
 #endif
str_create_chars()
integer(kind=c_int) function forpy_mod::str_create_chars (type(str), intent(out) r, character(kind=c_char, len=*), intent(in) string) private
Definition at line 7027 of file forpy_mod.F90.
   type(str), intent(out) :: r
   character(kind=C_CHAR, len=*), intent(in) :: string
   integer(kind=C_INT) :: ierror
 #ifdef PYTHON2
   ierror = box_value_chars_as_bytestr(r%py_object, string)
 #else
   ierror = box_value_chars_as_unicodestr(r%py_object, string)
 #endif
str_create_object()
integer(kind=c_int) function forpy_mod::str_create_object (type(str), intent(out) r, class(object), intent(in) obj) private
Definition at line 7051 of file forpy_mod.F90.
   type(str), intent(out) :: r
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   r%py_object = pyobject_str(obj%py_object)
   if (.not. c_associated(r%py_object)) then
     ierror = exception_error
   endif
tuple_add()
integer(kind=c_int) function forpy_mod::tuple_add (class(tuple), intent(inout) self, type(tuple), intent(out) result_tuple, class(tuple), intent(inout) tuple_to_concatenate) private
Definition at line 4401 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   type(tuple), intent(out) :: result_tuple
   class(tuple), intent(inout) :: tuple_to_concatenate
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   result_tuple%py_object = pysequence_concat(self%py_object, tuple_to_concatenate%py_object)
   if (.not. c_associated(result_tuple%py_object)) then
     ierror = exception_error
   endif
tuple_create_int32()
integer(kind=c_int) function forpy_mod::tuple_create_int32 (type(tuple), intent(out) r, integer(kind=int32), intent(in) len) private
Creates a tuple with a given number of elements.
Parameters
[out] r the freshly created tuple
[in] len Number of items in tuple
Returns
Error code, 0 on success
Definition at line 2685 of file forpy_mod.F90.
   type(tuple), intent(out) :: r
   integer(kind=int32), intent(in) :: len
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: tmp
   tmp = int(len, py_ssize_t_kind)
   r%py_object = pytuple_new(tmp)
   ierror = 0_c_int
   if (.not. c_associated(r%py_object)) then
     ierror = exception_error
   endif
tuple_create_int64()
integer(kind=c_int) function forpy_mod::tuple_create_int64 (type(tuple), intent(out) r, integer(kind=int64), intent(in) len) private
Creates a tuple with a given number of elements.
Parameters
[out] r the freshly created tuple
[in] len Number of items in tuple
Returns
Error code, 0 on success
Definition at line 2705 of file forpy_mod.F90.
   type(tuple), intent(out) :: r
   integer(kind=int64), intent(in) :: len
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: tmp
   tmp = int(len, py_ssize_t_kind)
   r%py_object = pytuple_new(tmp)
   ierror = 0_c_int
   if (.not. c_associated(r%py_object)) then
     ierror = exception_error
   endif
tuple_create_object()
integer(kind=c_int) function forpy_mod::tuple_create_object (type(tuple), intent(out) r, class(object), intent(in) obj) private
Parameters
[out] r the created tuple
Definition at line 2725 of file forpy_mod.F90.
   type(tuple), intent(out) :: r
   class(object), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   ierror = 0_c_int
   r%py_object = pysequence_tuple(obj%py_object)
   if (.not. c_associated(r%py_object)) then
     ierror = exception_error
   endif
tuple_from_array_int32()
integer(kind=c_int) function forpy_mod::tuple_from_array_int32 (type(tuple), intent(out) tu, integer(kind=int32), dimension(:), intent(in) arr) private
Helper function: create tuple from integer array.
Definition at line 10252 of file forpy_mod.F90.
   type(tuple), intent(out) :: tu
   integer(kind=int32), dimension(:), intent(in) :: arr
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ii, ndim
   ndim = size(arr, kind=py_ssize_t_kind)
   ierror = tuple_create(tu, ndim)
   if (ierror /= 0_c_int) return
   do ii = 1, ndim
     ierror = tu%setitem(ii-1, arr(ii))
     if (ierror /= 0_c_int) then
       call tu%destroy
       return
     endif
   enddo
tuple_from_array_int64()
integer(kind=c_int) function forpy_mod::tuple_from_array_int64 (type(tuple), intent(out) tu, integer(kind=int64), dimension(:), intent(in) arr) private
Helper function: create tuple from integer array.
Definition at line 10349 of file forpy_mod.F90.
   type(tuple), intent(out) :: tu
   integer(kind=int64), dimension(:), intent(in) :: arr
   integer(kind=C_INT) :: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ii, ndim
   ndim = size(arr, kind=py_ssize_t_kind)
   ierror = tuple_create(tu, ndim)
   if (ierror /= 0_c_int) return
   do ii = 1, ndim
     ierror = tu%setitem(ii-1, arr(ii))
     if (ierror /= 0_c_int) then
       call tu%destroy
       return
     endif
   enddo
tuple_setitem_int32_char_1d()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_char_1d (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, character(kind=c_char), dimension(:), intent(in) item) private
Definition at line 4141 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   character(kind=C_CHAR), dimension(:), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int32_chars()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_chars (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, character(kind=c_char, len=*), intent(in) item) private
Definition at line 4161 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   character(kind=C_CHAR, len=*), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int32_complex_real32()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_complex_real32 (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, complex(kind=real32), intent(in) item) private
Definition at line 4081 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   complex(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int32_complex_real64()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_complex_real64 (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, complex(kind=real64), intent(in) item) private
Definition at line 4101 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   complex(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int32_int32()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_int32 (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, integer(kind=int32), intent(in) item) private
Definition at line 4001 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   integer(kind=int32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int32_int64()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_int64 (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, integer(kind=int64), intent(in) item) private
Definition at line 4021 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   integer(kind=int64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int32_logical()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_logical (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, logical, intent(in) item) private
Definition at line 4121 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   logical, intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int32_object()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_object (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, class(object), intent(in) item) private
Definition at line 4362 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   class(object), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   ! therefore must increase ref-count of item
   call py_incref(item%py_object)
   ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item%py_object)
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int32_real32()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_real32 (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, real(kind=real32), intent(in) item) private
Definition at line 4041 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   real(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int32_real64()
integer(kind=c_int) function forpy_mod::tuple_setitem_int32_real64 (class(tuple), intent(inout) self, integer(kind=int32), intent(in) ind, real(kind=real64), intent(in) item) private
Definition at line 4061 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int32), intent(in) :: ind
   real(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_char_1d()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_char_1d (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, character(kind=c_char), dimension(:), intent(in) item) private
Definition at line 4321 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   character(kind=C_CHAR), dimension(:), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_chars()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_chars (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, character(kind=c_char, len=*), intent(in) item) private
Definition at line 4341 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   character(kind=C_CHAR, len=*), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_complex_real32()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_complex_real32 (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, complex(kind=real32), intent(in) item) private
Definition at line 4261 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   complex(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_complex_real64()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_complex_real64 (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, complex(kind=real64), intent(in) item) private
Definition at line 4281 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   complex(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_int32()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_int32 (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, integer(kind=int32), intent(in) item) private
Definition at line 4181 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   integer(kind=int32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_int64()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_int64 (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, integer(kind=int64), intent(in) item) private
Definition at line 4201 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   integer(kind=int64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_logical()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_logical (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, logical, intent(in) item) private
Definition at line 4301 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   logical, intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_object()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_object (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, class(object), intent(in) item) private
Definition at line 4381 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   class(object), intent(in) :: item
   integer(kind=C_INT):: ierror
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   ! therefore must increase ref-count of item
   call py_incref(item%py_object)
   ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item%py_object)
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_real32()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_real32 (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, real(kind=real32), intent(in) item) private
Definition at line 4221 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   real(kind=real32), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
tuple_setitem_int64_real64()
integer(kind=c_int) function forpy_mod::tuple_setitem_int64_real64 (class(tuple), intent(inout) self, integer(kind=int64), intent(in) ind, real(kind=real64), intent(in) item) private
Definition at line 4241 of file forpy_mod.F90.
   class(tuple), intent(inout) :: self
   integer(kind=int64), intent(in) :: ind
   real(kind=real64), intent(in) :: item
   integer(kind=C_INT):: ierror
   type(c_ptr) :: item_py
   integer(kind=PY_SSIZE_T_KIND) :: ind_py_ssize_t
   ierror = box_value(item_py, item)
   ind_py_ssize_t = int(ind, py_ssize_t_kind)
   !tuple: must use PyTuple_SetItem
   !PyTuple_SetItem steals a reference - in contrast to PyObject_SetItem
   if (ierror == 0) then
     ierror = pytuple_setitem(self%py_object, ind_py_ssize_t, item_py)
     ! note: no need for Py_DecRef since reference is stolen
   endif
Referenced by forpy_mod::tuple::setitem().
unbox_value_char_1d()
integer(kind=c_int) function forpy_mod::unbox_value_char_1d (character(kind=c_char), dimension(:), intent(out), pointer the_value, type(c_ptr), intent(in) obj) private
Definition at line 10831 of file forpy_mod.F90.
   character(kind=C_CHAR), pointer, dimension(:), intent(out) :: the_value
   type(c_ptr), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   type(c_ptr) :: char_ptr
   integer(PY_SSIZE_T_KIND) :: length(1)
   logical :: obj_is_bytes
   type(object) :: dummy_obj ! just to be able to use is_bytes and is_unicode
   ierror = 0_c_int
   dummy_obj%py_object = obj
   obj_is_bytes = is_bytes(dummy_obj)
   if (obj_is_bytes) then
     char_ptr = pybytes_asstring(obj)
   elseif (is_unicode(dummy_obj)) then
 #ifndef PYTHON2
     !C-API-function not available in PY2
     char_ptr = pyunicode_asutf8andsize(obj, length(1))
 #else
     char_ptr = c_null_ptr
     call raise_exception(typeerror, "forpy: cast of unicode object to character array not supported when using Python 2")
 #endif
   else
     char_ptr = c_null_ptr
   endif
   if (.not. c_associated(char_ptr)) then
     ierror = exception_error
     if (.not. have_exception()) then
       call raise_exception(typeerror, "forpy: Cannot cast to character array")
     endif
     return
   endif
   if (obj_is_bytes) then
     length(1) = pyobject_length(obj)
   endif
   if (length(1) == -1_py_ssize_t_kind) then
     ierror = exception_error
     call raise_exception(typeerror, "forpy: Cannot cast to character array")
     return
   endif
   ! length 0 strings also seem to work
   call c_f_pointer(char_ptr, the_value, length)
unbox_value_chars()
integer(kind=c_int) function forpy_mod::unbox_value_chars (character(kind=c_char, len=:), intent(out), allocatable the_value, type(c_ptr), intent(in) obj) private
Definition at line 10886 of file forpy_mod.F90.
   character(kind=C_CHAR, len=:), allocatable, intent(out) :: the_value
   type(c_ptr), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   character(kind=C_CHAR), dimension(:), pointer :: char_ptr
   ierror = unbox_value_char_1d(char_ptr, obj)
   if (ierror == 0_c_int) then
     call char_1d_to_chars(char_ptr, the_value)
   endif
unbox_value_complex_real32()
integer(kind=c_int) function forpy_mod::unbox_value_complex_real32 (complex(kind=real32), intent(out) the_value, type(c_ptr), intent(in) obj) private
Definition at line 10768 of file forpy_mod.F90.
   complex(kind=real32), intent(out) :: the_value
   type(c_ptr), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   type(Py_complex) :: tmp
   type(c_ptr) :: err_obj
   ierror = 0_c_int
   tmp = pycomplex_asccomplex(obj) !this handles objects with __complex__ method correctly
   the_value = cmplx(tmp%real_part, tmp%imag_part, kind=real32)
   if (tmp%real_part == -1.0_c_double) then
     err_obj = pyerr_occurred()
     if (c_associated(err_obj)) then
       ierror = exception_error
       return
     endif
   endif
unbox_value_complex_real64()
integer(kind=c_int) function forpy_mod::unbox_value_complex_real64 (complex(kind=real64), intent(out) the_value, type(c_ptr), intent(in) obj) private
Definition at line 10791 of file forpy_mod.F90.
   complex(kind=real64), intent(out) :: the_value
   type(c_ptr), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   type(Py_complex) :: tmp
   type(c_ptr) :: err_obj
   ierror = 0_c_int
   tmp = pycomplex_asccomplex(obj) !this handles objects with __complex__ method correctly
   the_value = cmplx(tmp%real_part, tmp%imag_part, kind=real64)
   if (tmp%real_part == -1.0_c_double) then
     err_obj = pyerr_occurred()
     if (c_associated(err_obj)) then
       ierror = exception_error
       return
     endif
   endif
unbox_value_int32()
integer(kind=c_int) function forpy_mod::unbox_value_int32 (integer(kind=int32), intent(out) the_value, type(c_ptr), intent(in) obj) private
Definition at line 10646 of file forpy_mod.F90.
   integer(kind=int32), intent(out) :: the_value
   type(c_ptr), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   integer(kind=C_LONG_LONG) :: tmp
   integer :: overflow
   type(c_ptr) :: err_obj
   ierror = 0_c_int
   tmp = pylong_aslonglongandoverflow(obj, overflow)
   the_value = int(tmp, int32)
   if (tmp == -1_c_long_long) then
     if (overflow == 0) then
       err_obj = pyerr_occurred()
       if (c_associated(err_obj)) then
         ierror = exception_error
         return
       endif
     else
       ierror = exception_error
       call raise_exception(overflowerror, "int too big to convert")
       return
     endif
   endif
   if (huge(the_value) < huge(tmp)) then
     if (tmp > huge(the_value) .or. tmp < -huge(the_value)) then
       if (tmp /= (-huge(the_value) - 1)) then
         ierror = exception_error
         call raise_exception(overflowerror, "int too large for Fortran integer(kind=int32)")
       endif
     endif
   endif
unbox_value_int64()
integer(kind=c_int) function forpy_mod::unbox_value_int64 (integer(kind=int64), intent(out) the_value, type(c_ptr), intent(in) obj) private
Definition at line 10684 of file forpy_mod.F90.
   integer(kind=int64), intent(out) :: the_value
   type(c_ptr), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   integer(kind=C_LONG_LONG) :: tmp
   integer :: overflow
   type(c_ptr) :: err_obj
   ierror = 0_c_int
   tmp = pylong_aslonglongandoverflow(obj, overflow)
   the_value = int(tmp, int64)
   if (tmp == -1_c_long_long) then
     if (overflow == 0) then
       err_obj = pyerr_occurred()
       if (c_associated(err_obj)) then
         ierror = exception_error
         return
       endif
     else
       ierror = exception_error
       call raise_exception(overflowerror, "int too big to convert")
       return
     endif
   endif
   if (huge(the_value) < huge(tmp)) then
     if (tmp > huge(the_value) .or. tmp < -huge(the_value)) then
       if (tmp /= (-huge(the_value) - 1)) then
         ierror = exception_error
         call raise_exception(overflowerror, "int too large for Fortran integer(kind=int64)")
       endif
     endif
   endif
unbox_value_logical()
integer(kind=c_int) function forpy_mod::unbox_value_logical (logical, intent(out) the_value, type(c_ptr), intent(in) obj) private
Definition at line 10815 of file forpy_mod.F90.
   logical, intent(out) :: the_value
   type(c_ptr), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   the_value = .false.
   ierror = pyobject_istrue(obj)
   if (ierror /= -1_c_int) then
     the_value = (ierror == 1_c_int)
     ierror = 0_c_int
   endif
unbox_value_real32()
integer(kind=c_int) function forpy_mod::unbox_value_real32 (real(kind=real32), intent(out) the_value, type(c_ptr), intent(in) obj) private
Definition at line 10723 of file forpy_mod.F90.
   real(kind=real32), intent(out) :: the_value
   type(c_ptr), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   real(kind=c_double) :: tmp
   type(c_ptr) :: err_obj
   ierror = 0_c_int
   tmp = pyfloat_asdouble(obj)
   the_value = real(tmp, real32)
   if (tmp == -1.0_c_double) then
     err_obj = pyerr_occurred()
     if (c_associated(err_obj)) then
       ierror = exception_error
       return
     endif
   endif
unbox_value_real64()
integer(kind=c_int) function forpy_mod::unbox_value_real64 (real(kind=real64), intent(out) the_value, type(c_ptr), intent(in) obj) private
Definition at line 10745 of file forpy_mod.F90.
   real(kind=real64), intent(out) :: the_value
   type(c_ptr), intent(in) :: obj
   integer(kind=C_INT) :: ierror
   real(kind=c_double) :: tmp
   type(c_ptr) :: err_obj
   ierror = 0_c_int
   tmp = pyfloat_asdouble(obj)
   the_value = real(tmp, real64)
   if (tmp == -1.0_c_double) then
     err_obj = pyerr_occurred()
     if (c_associated(err_obj)) then
       ierror = exception_error
       return
     endif
   endif
unicode_create_char_1d()
integer(kind=c_int) function forpy_mod::unicode_create_char_1d (type(unicode), intent(out) r, character(kind=c_char), dimension(:), intent(in) string) private
Definition at line 7019 of file forpy_mod.F90.
   type(unicode), intent(out) :: r
   character(kind=C_CHAR), dimension(:), intent(in) :: string
   integer(kind=C_INT) :: ierror
   ierror = box_value_char_1d_as_unicodestr(r%py_object, string)
unicode_create_chars()
integer(kind=c_int) function forpy_mod::unicode_create_chars (type(unicode), intent(out) r, character(kind=c_char, len=*), intent(in) string) private
Definition at line 7011 of file forpy_mod.F90.
   type(unicode), intent(out) :: r
   character(kind=C_CHAR, len=*), intent(in) :: string
   integer(kind=C_INT) :: ierror
   ierror = box_value_chars_as_unicodestr(r%py_object, string)
unsafe_cast_from_c_ptr()
subroutine, public forpy_mod::unsafe_cast_from_c_ptr (class(object), intent(out) obj, type(c_ptr), intent(in) ptr)
Creates an [[object]] from a type(c_ptr), no type checks.
use with care, use only for developing Python extensions created object 'obj' has to be cleaned up by calling objdestroy
Parameters
[out] obj The created Python object.
[in] ptr C pointer to cast from
Definition at line 11795 of file forpy_mod.F90.
   class(object), intent(out) :: obj
   type(c_ptr), intent(in) :: ptr
   call py_incref(ptr)
   obj%py_object = ptr
Variable Documentation
arithmeticerror
type(type_py), save, public forpy_mod::arithmeticerror
Definition at line 1870 of file forpy_mod.F90.
 type(type_py), public, save :: ArithmeticError
Referenced by forpy_initialize_exceptions().
assertionerror
type(type_py), save, public forpy_mod::assertionerror
Definition at line 1871 of file forpy_mod.F90.
 type(type_py), public, save :: AssertionError
Referenced by forpy_initialize_exceptions().
attributeerror
type(type_py), save, public forpy_mod::attributeerror
Definition at line 1872 of file forpy_mod.F90.
 type(type_py), public, save :: AttributeError
Referenced by forpy_initialize_exceptions().
baseexception
type(type_py), save, public forpy_mod::baseexception
Definition at line 1873 of file forpy_mod.F90.
 type(type_py), public, save :: BaseException
Referenced by forpy_initialize_exceptions().
buffererror
type(type_py), save, public forpy_mod::buffererror
Definition at line 1874 of file forpy_mod.F90.
 type(type_py), public, save :: BufferError
Referenced by forpy_initialize_exceptions().
byteswarning
type(type_py), save, public forpy_mod::byteswarning
Definition at line 1875 of file forpy_mod.F90.
 type(type_py), public, save :: BytesWarning
Referenced by forpy_initialize_exceptions().
deprecationwarning
type(type_py), save, public forpy_mod::deprecationwarning
Definition at line 1876 of file forpy_mod.F90.
 type(type_py), public, save :: DeprecationWarning
Referenced by forpy_initialize_exceptions().
environmenterror
type(type_py), save, public forpy_mod::environmenterror
Definition at line 1878 of file forpy_mod.F90.
 type(type_py), public, save :: EnvironmentError
Referenced by forpy_initialize_exceptions().
eoferror
type(type_py), save, public forpy_mod::eoferror
Definition at line 1877 of file forpy_mod.F90.
 type(type_py), public, save :: EOFError
Referenced by forpy_initialize_exceptions().
exception
type(type_py), save, public forpy_mod::exception
Definition at line 1879 of file forpy_mod.F90.
 type(type_py), public, save :: Exception
Referenced by forpy_initialize_exceptions().
exception_error
integer(kind=c_int), parameter, public forpy_mod::exception_error = -1_C_INT
Definition at line 61 of file forpy_mod.F90.
 integer(kind=C_INT), public, parameter :: EXCEPTION_ERROR = -1_c_int
floatingpointerror
type(type_py), save, public forpy_mod::floatingpointerror
Definition at line 1880 of file forpy_mod.F90.
 type(type_py), public, save :: FloatingPointError
Referenced by forpy_initialize_exceptions().
futurewarning
type(type_py), save, public forpy_mod::futurewarning
Definition at line 1881 of file forpy_mod.F90.
 type(type_py), public, save :: FutureWarning
Referenced by forpy_initialize_exceptions().
generatorexit
type(type_py), save, public forpy_mod::generatorexit
Definition at line 1882 of file forpy_mod.F90.
 type(type_py), public, save :: GeneratorExit
Referenced by forpy_initialize_exceptions().
global_forpy_initialized
integer, save, private forpy_mod::global_forpy_initialized = 0 private
Definition at line 75 of file forpy_mod.F90.
 integer, private, save :: global_forpy_initialized = 0
Referenced by forpy_initialize().
global_numpy_asarray_method
type(c_ptr), save, private forpy_mod::global_numpy_asarray_method = C_NULL_PTR private
Definition at line 77 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_numpy_asarray_method = c_null_ptr
global_numpy_mod
type(c_ptr), save, private forpy_mod::global_numpy_mod = C_NULL_PTR private
Definition at line 76 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_numpy_mod = c_null_ptr
Referenced by forpy_initialize().
global_numpy_ndarray_typeobj
type(c_ptr), save, private forpy_mod::global_numpy_ndarray_typeobj = C_NULL_PTR private
Definition at line 87 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_numpy_ndarray_typeobj = c_null_ptr
global_py_falsestruct_ptr
type(c_ptr), save, private forpy_mod::global_py_falsestruct_ptr = C_NULL_PTR private
Definition at line 85 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_Py_FalseStruct_ptr = c_null_ptr
global_py_nonestruct_ptr
type(c_ptr), save, private forpy_mod::global_py_nonestruct_ptr = C_NULL_PTR private
Definition at line 81 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_Py_NoneStruct_ptr = c_null_ptr
global_py_truestruct_ptr
type(c_ptr), save, private forpy_mod::global_py_truestruct_ptr = C_NULL_PTR private
Definition at line 84 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_Py_TrueStruct_ptr = c_null_ptr
global_pybool_type_ptr
type(c_ptr), save, private forpy_mod::global_pybool_type_ptr = C_NULL_PTR private
Definition at line 93 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_pybool_type_ptr = c_null_ptr
global_pycomplex_type_ptr
type(c_ptr), save, private forpy_mod::global_pycomplex_type_ptr = C_NULL_PTR private
Definition at line 92 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_pycomplex_type_ptr = c_null_ptr
global_pyfloat_type_ptr
type(c_ptr), save, private forpy_mod::global_pyfloat_type_ptr = C_NULL_PTR private
Definition at line 91 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_pyfloat_type_ptr = c_null_ptr
global_pyunicode_type_ptr
type(c_ptr), save, private forpy_mod::global_pyunicode_type_ptr = C_NULL_PTR private
Definition at line 94 of file forpy_mod.F90.
 type(c_ptr), private, save :: global_pyunicode_type_ptr = c_null_ptr
importerror
type(type_py), save, public forpy_mod::importerror
Definition at line 1884 of file forpy_mod.F90.
 type(type_py), public, save :: ImportError
Referenced by forpy_initialize_exceptions().
importwarning
type(type_py), save, public forpy_mod::importwarning
Definition at line 1885 of file forpy_mod.F90.
 type(type_py), public, save :: ImportWarning
Referenced by forpy_initialize_exceptions().
indentationerror
type(type_py), save, public forpy_mod::indentationerror
Definition at line 1886 of file forpy_mod.F90.
 type(type_py), public, save :: IndentationError
Referenced by forpy_initialize_exceptions().
indexerror
type(type_py), save, public forpy_mod::indexerror
Definition at line 1887 of file forpy_mod.F90.
 type(type_py), public, save :: IndexError
Referenced by forpy_initialize_exceptions().
ioerror
type(type_py), save, public forpy_mod::ioerror
Definition at line 1883 of file forpy_mod.F90.
 type(type_py), public, save :: IOError
Referenced by forpy_initialize_exceptions().
keyboardinterrupt
type(type_py), save, public forpy_mod::keyboardinterrupt
Definition at line 1889 of file forpy_mod.F90.
 type(type_py), public, save :: KeyboardInterrupt
Referenced by forpy_initialize_exceptions().
keyerror
type(type_py), save, public forpy_mod::keyerror
Definition at line 1888 of file forpy_mod.F90.
 type(type_py), public, save :: KeyError
Referenced by forpy_initialize_exceptions().
lookuperror
type(type_py), save, public forpy_mod::lookuperror
Definition at line 1890 of file forpy_mod.F90.
 type(type_py), public, save :: LookupError
Referenced by forpy_initialize_exceptions().
memoryerror
type(type_py), save, public forpy_mod::memoryerror
Definition at line 1891 of file forpy_mod.F90.
 type(type_py), public, save :: MemoryError
Referenced by forpy_initialize_exceptions().
meth_keywords
integer(kind=c_int), parameter, public forpy_mod::meth_keywords = 2_C_INT
Definition at line 65 of file forpy_mod.F90.
 integer(kind=C_INT), public, parameter :: METH_KEYWORDS = 2_c_int
meth_noargs
integer(kind=c_int), parameter, public forpy_mod::meth_noargs = 4_C_INT
Definition at line 66 of file forpy_mod.F90.
 integer(kind=C_INT), public, parameter :: METH_NOARGS = 4_c_int
meth_o
integer(kind=c_int), parameter, public forpy_mod::meth_o = 8_C_INT
Definition at line 67 of file forpy_mod.F90.
 integer(kind=C_INT), public, parameter :: METH_O = 8_c_int
meth_varargs
integer(kind=c_int), parameter, public forpy_mod::meth_varargs = 1_C_INT
Definition at line 64 of file forpy_mod.F90.
 integer(kind=C_INT), public, parameter :: METH_VARARGS = 1_c_int
nameerror
type(type_py), save, public forpy_mod::nameerror
Definition at line 1892 of file forpy_mod.F90.
 type(type_py), public, save :: NameError
Referenced by forpy_initialize_exceptions().
no_numpy_error
integer(kind=c_int), parameter, public forpy_mod::no_numpy_error = 2_C_INT
Definition at line 60 of file forpy_mod.F90.
 integer(kind=C_INT), public, parameter :: NO_NUMPY_ERROR = 2_c_int
notimplementederror
type(type_py), save, public forpy_mod::notimplementederror
Definition at line 1893 of file forpy_mod.F90.
 type(type_py), public, save :: NotImplementedError
Referenced by forpy_initialize_exceptions().
oserror
type(type_py), save, public forpy_mod::oserror
Definition at line 1894 of file forpy_mod.F90.
 type(type_py), public, save :: OSError
Referenced by forpy_initialize_exceptions().
overflowerror
type(type_py), save, public forpy_mod::overflowerror
Definition at line 1895 of file forpy_mod.F90.
 type(type_py), public, save :: OverflowError
Referenced by forpy_initialize_exceptions().
pendingdeprecationwarning
type(type_py), save, public forpy_mod::pendingdeprecationwarning
Definition at line 1896 of file forpy_mod.F90.
 type(type_py), public, save :: PendingDeprecationWarning
Referenced by forpy_initialize_exceptions().
py_ssize_t_kind
integer, parameter, public forpy_mod::py_ssize_t_kind = C_INTPTR_T
Definition at line 69 of file forpy_mod.F90.
 integer, public, parameter :: PY_SSIZE_T_KIND = c_intptr_t
Referenced by forpy_mod::PyBuffer_FillContiguousStrides::pybuffer_fillcontiguousstrides(), forpy_mod::PyBytes_FromStringAndSize::pybytes_fromstringandsize(), forpy_mod::PyList_Insert::pylist_insert(), forpy_mod::PyList_New::pylist_new(), forpy_mod::PyModule_AddObject::pymodule_addobject(), forpy_mod::PyObject_Length::pyobject_length(), forpy_mod::PySequence_Count::pysequence_count(), forpy_mod::PySequence_DelItem::pysequence_delitem(), forpy_mod::PySequence_GetItem::pysequence_getitem(), forpy_mod::PySequence_Index::pysequence_index(), forpy_mod::PySequence_SetItem::pysequence_setitem(), forpy_mod::PyTuple_New::pytuple_new(), forpy_mod::PyTuple_SetItem::pytuple_setitem(), forpy_mod::PyUnicode_AsUTF8AndSize::pyunicode_asutf8andsize(), and forpy_mod::PyUnicode_DecodeUTF8::pyunicode_decodeutf8().
referenceerror
type(type_py), save, public forpy_mod::referenceerror
Definition at line 1897 of file forpy_mod.F90.
 type(type_py), public, save :: ReferenceError
Referenced by forpy_initialize_exceptions().
runtimeerror
type(type_py), save, public forpy_mod::runtimeerror
Definition at line 1898 of file forpy_mod.F90.
 type(type_py), public, save :: RuntimeError
Referenced by forpy_initialize_exceptions().
runtimewarning
type(type_py), save, public forpy_mod::runtimewarning
Definition at line 1899 of file forpy_mod.F90.
 type(type_py), public, save :: RuntimeWarning
Referenced by forpy_initialize_exceptions().
standarderror
type(type_py), save, public forpy_mod::standarderror
Definition at line 1900 of file forpy_mod.F90.
 type(type_py), public, save :: StandardError
Referenced by forpy_initialize_exceptions().
stopiteration
type(type_py), save, public forpy_mod::stopiteration
Definition at line 1901 of file forpy_mod.F90.
 type(type_py), public, save :: StopIteration
Referenced by forpy_initialize_exceptions().
syntaxerror
type(type_py), save, public forpy_mod::syntaxerror
Definition at line 1902 of file forpy_mod.F90.
 type(type_py), public, save :: SyntaxError
Referenced by forpy_initialize_exceptions().
syntaxwarning
type(type_py), save, public forpy_mod::syntaxwarning
Definition at line 1903 of file forpy_mod.F90.
 type(type_py), public, save :: SyntaxWarning
Referenced by forpy_initialize_exceptions().
systemerror
type(type_py), save, public forpy_mod::systemerror
Definition at line 1904 of file forpy_mod.F90.
 type(type_py), public, save :: SystemError
Referenced by forpy_initialize_exceptions().
systemexit
type(type_py), save, public forpy_mod::systemexit
Definition at line 1905 of file forpy_mod.F90.
 type(type_py), public, save :: SystemExit
Referenced by forpy_initialize_exceptions().
taberror
type(type_py), save, public forpy_mod::taberror
Definition at line 1906 of file forpy_mod.F90.
 type(type_py), public, save :: TabError
Referenced by forpy_initialize_exceptions().
typeerror
type(type_py), save, public forpy_mod::typeerror
Definition at line 1907 of file forpy_mod.F90.
 type(type_py), public, save :: TypeError
Referenced by forpy_initialize_exceptions().
unboundlocalerror
type(type_py), save, public forpy_mod::unboundlocalerror
Definition at line 1908 of file forpy_mod.F90.
 type(type_py), public, save :: UnboundLocalError
Referenced by forpy_initialize_exceptions().
unicodedecodeerror
type(type_py), save, public forpy_mod::unicodedecodeerror
Definition at line 1909 of file forpy_mod.F90.
 type(type_py), public, save :: UnicodeDecodeError
Referenced by forpy_initialize_exceptions().
unicodeencodeerror
type(type_py), save, public forpy_mod::unicodeencodeerror
Definition at line 1910 of file forpy_mod.F90.
 type(type_py), public, save :: UnicodeEncodeError
Referenced by forpy_initialize_exceptions().
unicodeerror
type(type_py), save, public forpy_mod::unicodeerror
Definition at line 1911 of file forpy_mod.F90.
 type(type_py), public, save :: UnicodeError
Referenced by forpy_initialize_exceptions().
unicodetranslateerror
type(type_py), save, public forpy_mod::unicodetranslateerror
Definition at line 1912 of file forpy_mod.F90.
 type(type_py), public, save :: UnicodeTranslateError
Referenced by forpy_initialize_exceptions().
unicodewarning
type(type_py), save, public forpy_mod::unicodewarning
Definition at line 1913 of file forpy_mod.F90.
 type(type_py), public, save :: UnicodeWarning
Referenced by forpy_initialize_exceptions().
userwarning
type(type_py), save, public forpy_mod::userwarning
Definition at line 1914 of file forpy_mod.F90.
 type(type_py), public, save :: UserWarning
Referenced by forpy_initialize_exceptions().
valueerror
type(type_py), save, public forpy_mod::valueerror
Definition at line 1915 of file forpy_mod.F90.
 type(type_py), public, save :: ValueError
Referenced by forpy_initialize_exceptions().
warning
type(type_py), save, public forpy_mod::warning
Definition at line 1916 of file forpy_mod.F90.
 type(type_py), public, save :: Warning
Referenced by forpy_initialize_exceptions().
zerodivisionerror
type(type_py), save, public forpy_mod::zerodivisionerror
Definition at line 1917 of file forpy_mod.F90.
 type(type_py), public, save :: ZeroDivisionError
Referenced by forpy_initialize_exceptions().