My Project: xtb_topology Module Reference
xtb_topology Module Reference
Compare and generate topological information from wavefunctions.
Functions/Subroutines
subroutine, public checktopology (unit, mol, wbo, verbosity)
subroutine, public makebondtopology (topo, mol, wbo)
subroutine, public comparebondtopology (unit, topo1, topo2, mol, verbosity, match)
subroutine topologytoneighbourlist (topo, neighList, mol)
Detailed Description
Compare and generate topological information from wavefunctions.
Function/Subroutine Documentation
checktopology()
subroutine, public xtb_topology::checktopology (integer, intent(in) unit, type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) wbo, integer, intent(in) verbosity)
Definition at line 36 of file topology.f90.
    integer, intent(in) :: unit
    type(TMolecule), intent(in) :: mol
    real(wp), intent(in) :: wbo(:, :)
    integer, intent(in) :: verbosity
    character(len=:), allocatable :: fname
    type(TMolecule) :: copy
    integer :: ich, ftype
    logical :: match
    ! CT files have some limits:
    ! bail out if we encounter a structure not suitable for this format
    if (mol%npbc /= 0 .or. mol%n > 999) return
    copy = mol
    call makebondtopology(copy%bonds, mol, wbo)
    call comparebondtopology(unit, mol%bonds, copy%bonds, mol, verbosity, match)
    if (.not.match .and. len(copy%bonds) > 0) then
       ! prefer molfiles, except the input has been SDF
       if (mol%ftype /= filetype%sdf) then
          ftype = filetype%molfile
       else
          ftype = mol%ftype
       end if
       call generatefilename(fname, 'xtbtopo', '', ftype)
       call open_file(ich, fname, 'w')
       if (verbosity > 0 .and. len(mol%bonds) > 0) then
          write(unit, '("Writing corrected topology to", 1x, a)') fname
       else
          write(unit, '("Writing topology from bond orders to", 1x, a)') fname
       end if
       call writemolecule(copy, ich, format=ftype)
       call close_file(ich)
    end if
References close_file(), comparebondtopology(), xtb_mctc_filetypes::filetype, xtb_mctc_filetypes::generatefilename(), makebondtopology(), open_file(), and xtb_io_writer::writemolecule().
Referenced by xtb_propertyoutput::main_property().
comparebondtopology()
subroutine, public xtb_topology::comparebondtopology (integer, intent(in) unit, type(ttopology), intent(in) topo1, type(ttopology), intent(in) topo2, type(tmolecule), intent(in) mol, integer, intent(in) verbosity, logical, intent(out) match)
Definition at line 121 of file topology.f90.
    integer, intent(in) :: unit
    type(TTopology), intent(in) :: topo1
    type(TTopology), intent(in) :: topo2
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: verbosity
    logical, intent(out) :: match
    type(TNeighbourList) :: neighList1, neighList2
    integer :: iat, neigh
    match = len(topo1) == len(topo2)
    if (.not.match .and. verbosity > 0) then
       write(unit, '("Topologies differ in total number of bonds")')
    end if
    if (match .or. verbosity > 1) then
       call topologytoneighbourlist(topo1, neighlist1, mol)
       call topologytoneighbourlist(topo2, neighlist2, mol)
       match = match .and. all(neighlist1%neighs == neighlist2%neighs)
       if (.not.match .and. verbosity > 0) then
          write(unit, '("Topologies differ in number of bonds")')
       end if
       if (match .or. verbosity > 1) then
          neigh = min(ubound(neighlist1%iNeigh, 1), ubound(neighlist2%iNeigh, 1))
          match = match .and. all(neighlist1%iNeigh(:neigh, :) &
             & == neighlist2%iNeigh(:neigh, :))
          if (.not.match .and. verbosity > 0) then
             write(unit, '("Topologies differ in connectivity")')
          end if
          if (match .or. verbosity > 1) then
             match = match .and. all(nint(neighlist1%weight(:neigh, :)) &
                & == nint(neighlist2%weight(:neigh, :)))
             if (.not.match .and. verbosity > 0) then
                write(unit, '("Topologies differ in bond orders")')
             end if
          end if
       end if
    end if
References topologytoneighbourlist().
Referenced by checktopology().
makebondtopology()
subroutine, public xtb_topology::makebondtopology (type(ttopology), intent(out) topo, type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) wbo)
Definition at line 81 of file topology.f90.
    type(TTopology), intent(out) :: topo
    type(TMolecule), intent(in) :: mol
    real(wp), intent(in) :: wbo(:, :)
    real(wp), parameter :: wbothr = 0.3_wp
    integer :: iat, jat
    call topo%allocate(size=len(mol), order=3)
    do iat = 1, len(mol)
       do jat = 1, iat-1
          associate(w => wbo(jat, iat))
             if (any(mol%at(iat) == [6, 7, 8]) .and. any(mol%at(jat) == [6, 7, 8])) then
                if (w > wbothr .and. w <= 1.2_wp) then
                   call topo%push_back([jat, iat, 1])
                else if (w > 1.5_wp .and. w <= 2.3_wp) then
                   call topo%push_back([jat, iat, 2])
                else if (w > 2.3_wp) then
                   call topo%push_back([jat, iat, 3])
                else if (w > 1.2_wp .and. w <= 1.5_wp) then
                   call topo%push_back([jat, iat, 4])
                end if
             else
                if (w > wbothr .and. w <= 1.3_wp) then
                   call topo%push_back([jat, iat, 1])
                else if (w > 1.3_wp .and. w <= 2.3_wp) then
                   call topo%push_back([jat, iat, 2])
                else if (w > 2.3_wp) then
                   call topo%push_back([jat, iat, 3])
                end if
             end if
          end associate
       end do
    end do
Referenced by checktopology().
topologytoneighbourlist()
subroutine xtb_topology::topologytoneighbourlist (type(ttopology), intent(in) topo, type(tneighbourlist), intent(out) neighList, type(tmolecule), intent(in) mol) private
Definition at line 174 of file topology.f90.
    type(TTopology), intent(in) :: topo
    type(TMolecule), intent(in) :: mol
    type(TNeighbourList), intent(out) :: neighList
    integer :: iBond(3)
    integer :: mNeigh
    integer :: ii, iat, jat
    real(wp) :: r2
    call init(neighlist, len(mol))
    mneigh = ubound(neighlist%iNeigh, dim=1)
    neighlist%neighs(:) = 0
    neighlist%iNeigh(:, :) = 0
    neighlist%dist2(:, :) = 0.0_wp
    neighlist%weight(:, :) = 0.0_wp
    do iat = 1, len(mol)
       neighlist%iNeigh(0, iat) = iat
       neighlist%weight(0, iat) = 1.0_wp
       neighlist%coords(:, iat) = mol%xyz(:, iat)
       neighlist%image(iat) = iat
       neighlist%trans(iat) = 1
    end do
    do ii = 1, len(topo)
       call topo%get_item(ii, ibond)
       iat = min(ibond(1), ibond(2))
       jat = max(ibond(1), ibond(2))
       r2 = sum((neighlist%coords(:, iat) - neighlist%coords(:, jat))**2)
       neighlist%neighs(iat) = neighlist%neighs(iat) + 1
       if (neighlist%neighs(iat) > mneigh) then
          mneigh = 2*mneigh
          call resizeneigh(mneigh, neighlist%iNeigh, neighlist%dist2, &
             & neighlist%weight)
       end if
       neighlist%iNeigh(neighlist%neighs(iat), iat) = jat
       neighlist%dist2(neighlist%neighs(iat), iat) = r2
       neighlist%weight(neighlist%neighs(iat), iat) = ibond(3)
    end do
    call neighlist%sort
Referenced by comparebondtopology().