My Project: xtb_type_environment Module Reference
xtb_type_environment Module Reference
Calculation environment.
Data Types
type tmessage
Wrapper for characters.
type tenvironment
Calculation environment.
interface init
Constructor for the calculation environment.
interface resize
Overloaded resize interface.
Functions/Subroutines
subroutine initenvironment (self, strict)
Construct the calculation environment.
subroutine check (self, terminate)
subroutine checkpoint (self, message)
Check status of calculation environment.
subroutine show (self, message, isError)
Check status of calculation environment.
subroutine getlog (self, message)
Check status of calculation environment.
subroutine terminaterun (self, message, code)
subroutine error (self, message, source)
Create and push back a new error to the message log.
subroutine warning (self, message, source)
Create and push back a new error to the message log.
subroutine rescue (self, message, source)
Catch errors and continue.
subroutine resizemessage (var, n)
Reallocate message list.
Variables
integer, parameter initialsize = 20
Initial size of the message log.
Detailed Description
Calculation environment.
Function/Subroutine Documentation
check()
subroutine xtb_type_environment::check (class(tenvironment), intent(in) self, logical, intent(out) terminate) private
Parameters
[in] self Calculation environment
[out] terminate Recommendation for terminating run
Definition at line 162 of file environment.f90.
    class(TEnvironment), intent(in) :: self
    logical, intent(out) :: terminate
    terminate = any(self%log(:self%nLog)%error)
Referenced by identify_point_group().
checkpoint()
subroutine xtb_type_environment::checkpoint (class(tenvironment), intent(inout) self, character(len=*), intent(in) message) private
Check status of calculation environment.
Parameters
[in,out] self Calculation environment
[in] message Message in case of error
Recommendation for terminating run
Definition at line 176 of file environment.f90.
    class(TEnvironment), intent(inout) :: self
    character(len=*), intent(in) :: message
    logical :: terminate
    integer :: iLog
    call self%check(terminate)
    if (terminate) then
       call self%terminate(message)
    end if
error()
subroutine xtb_type_environment::error (class(tenvironment), intent(inout) self, character(len=*), intent(in) message, character(len=*), intent(in), optional source) private
Create and push back a new error to the message log.
Parameters
[in,out] self Calculation environment
[in] message Error message
[in] source Source of the error message
Definition at line 298 of file environment.f90.
    class(TEnvironment), intent(inout) :: self
    character(len=*), intent(in) :: message
    character(len=*), intent(in), optional :: source
    if (self%nLog >= size(self%log)) then
       call resize(self%log)
    end if
    self%nLog = self%nLog + 1
    if (present(source)) then
       self%log(self%nLog) = tmessage(.true., source // ": " // message)
    else
       self%log(self%nLog) = tmessage(.true., message)
    end if
References true().
getlog()
subroutine xtb_type_environment::getlog (class(tenvironment), intent(inout) self, character(len=:), intent(out), allocatable message) private
Check status of calculation environment.
Parameters
[in,out] self Calculation environment
[out] message Message in case of error
Definition at line 236 of file environment.f90.
    class(TEnvironment), intent(inout) :: self
    character(len=:), allocatable, intent(out) :: message
    integer :: iLog
    logical :: isError0
    character(len=512) :: buffer
    message = ''
    if (self%nLog > 0) then
       do ilog = self%nLog, 1, -1
          write(buffer, '("-", i0, "-", 1x, a)') ilog, self%log(ilog)%message
          deallocate(self%log(ilog)%message)
          if (len_trim(message) > 0) then
             message = message // new_line('a') // trim(buffer)
          else
             message = trim(buffer)
          end if
       end do
       self%nLog = 0
    end if
initenvironment()
subroutine xtb_type_environment::initenvironment (type(tenvironment), intent(out) self, logical, intent(in), optional strict) private
Construct the calculation environment.
Parameters
[out] self Calculation environment
[in] strict Handle warnings as errors
Definition at line 122 of file environment.f90.
    type(TEnvironment), intent(out) :: self
    logical, intent(in), optional :: strict
    integer :: err
    self%unit = stdout
    self%nLog = 0
    allocate(self%log(initialsize))
    call rdarg(0, self%whoami, err)
    call rdvar('HOSTNAME', self%hostname, err)
    call rdvar('HOME', self%home, err)
    call rdvar('PATH', self%path, err)
    call rdvar('XTBHOME', self%xtbhome, err)
    if (.not.allocated(self%xtbhome)) self%xtbhome = ''
    if (err /= 0 .or. len(self%xtbhome) <= 0) then
       self%xtbhome = self%home
    end if
    call rdvar('XTBPATH', self%xtbpath, err)
    if (.not.allocated(self%xtbpath)) self%xtbpath = ''
    if (err /= 0 .or. len(self%xtbpath) <= 0) then
       self%xtbpath = self%xtbhome
    end if
    if (present(strict)) then
       self%strict = strict
    else
       self%strict = .false.
    end if
    call init_(self%io)
rescue()
subroutine xtb_type_environment::rescue (class(tenvironment), intent(inout) self, character(len=*), intent(in) message, character(len=*), intent(in), optional source) private
Catch errors and continue.
Parameters
[in,out] self Calculation environment
[in] message Error message
[in] source Source of the error message
Definition at line 350 of file environment.f90.
    class(TEnvironment), intent(inout) :: self
    character(len=*), intent(in) :: message
    character(len=*), intent(in), optional :: source
    integer :: iLog
    do ilog = 1, self%nLog
       self%log(ilog)%error = self%strict
    end do
    call self%warning(message, source)
resizemessage()
subroutine xtb_type_environment::resizemessage (type(tmessage), dimension(:), intent(inout), allocatable var, integer, intent(in), optional n) private
Reallocate message list.
Parameters
[in,out] var Message list
[in] n Desired size
Definition at line 373 of file environment.f90.
    type(TMessage), allocatable, intent(inout) :: var(:)
    integer, intent(in), optional :: n
    type(TMessage), allocatable :: tmp(:)
    integer :: length, currentLength
    currentlength = size(var)
    if (currentlength > 0) then
       if (present(n)) then
          if (n <= currentlength) return
          length = n
       else
          length = currentlength + currentlength/2 + 1
       endif
       allocate(tmp(length))
       tmp(:currentlength) = var(:currentlength)
       deallocate(var)
       call move_alloc(tmp, var)
    else
       if (present(n)) then
          length = n
       else
          length = 64
       endif
       allocate(var(length))
    endif
show()
subroutine xtb_type_environment::show (class(tenvironment), intent(inout) self, character(len=*), intent(in) message, logical, intent(in), optional isError) private
Check status of calculation environment.
Parameters
[in,out] self Calculation environment
[in] message Message in case of error
[in] iserror Recommendation for terminating run
Definition at line 199 of file environment.f90.
    class(TEnvironment), intent(inout) :: self
    character(len=*), intent(in) :: message
    logical, intent(in), optional :: isError
    integer :: iLog
    logical :: isError0
    if (self%nLog > 0) then
       if (present(iserror)) then
          iserror0 = iserror
       else
          call self%check(iserror0)
       end if
       if (iserror0) then
          write(self%unit, '(72("#"), /, "[ERROR]", 1x, a)') message
       else
          write(self%unit, '(72("#"), /, "[WARNING]", 1x, a)') message
       end if
       do ilog = self%nLog, 1, -1
          write(self%unit, '("-", i0, "-", 1x, a)') ilog, self%log(ilog)%message
          deallocate(self%log(ilog)%message)
       end do
       write(self%unit, '(72("#"))')
       self%nLog = 0
    end if
terminaterun()
subroutine xtb_type_environment::terminaterun (class(tenvironment), intent(inout) self, character(len=*), intent(in) message, integer, intent(in), optional code) private
Parameters
[in,out] self Calculation environment
[in] message Message in case of error
[in] code Exit code for termination
Definition at line 266 of file environment.f90.
    class(TEnvironment), intent(inout) :: self
    character(len=*), intent(in) :: message
    integer, intent(in), optional :: code
    interface
       subroutine terminate(code)
          integer, intent(in) :: code
       end subroutine terminate
    end interface
    call self%error(message)
    call self%show("Program stopped due to fatal error", .true.)
    if (present(code)) then
       call terminate(code)
    else
       call terminate(1)
    end if
References terminate(), and true().
warning()
subroutine xtb_type_environment::warning (class(tenvironment), intent(inout) self, character(len=*), intent(in) message, character(len=*), intent(in), optional source) private
Create and push back a new error to the message log.
Parameters
[in,out] self Calculation environment
[in] message Error message
[in] source Source of the error message
Definition at line 324 of file environment.f90.
    class(TEnvironment), intent(inout) :: self
    character(len=*), intent(in) :: message
    character(len=*), intent(in), optional :: source
    if (self%nLog >= size(self%log)) then
       call resize(self%log)
    end if
    self%nLog = self%nLog + 1
    if (present(source)) then
       self%log(self%nLog) = tmessage(self%strict, source // ": " // message)
    else
       self%log(self%nLog) = tmessage(self%strict, message)
    end if
Variable Documentation
initialsize
integer, parameter xtb_type_environment::initialsize = 20 private
Initial size of the message log.
Definition at line 115 of file environment.f90.
    integer, parameter :: initialSize = 20
Referenced by xtb_type_environment::init::initenvironment().