My Project: xtb_solv_sasa Module Reference
xtb_solv_sasa Module Reference
Non-polar solvent accessible surface area model.
Functions/Subroutines
pure subroutine, public compute_numsa (nat, nnsas, nnlists, xyz, vdwsa, wrp, trj2, angWeight, angGrid, sasa, dsdrt)
pure subroutine compute_w_sp (nat, nnlists, trj2, vdwsa, xyza, iat, nno, xyzp, sasap, grds, nni, grdi)
Variables
real(wp), parameter w = 0.3_wp*aatoau
Smoothing dielectric function parameters.
real(wp), parameter w3 = w*(w*w)
real(wp), parameter ah0 = 0.5_wp
real(wp), parameter ah1 = 3._wp/(4.0_wp*w)
real(wp), parameter ah3 = -1._wp/(4.0_wp*w3)
real(wp), parameter tolsesp =1.e-6_wp
real space cut-offs
Detailed Description
Non-polar solvent accessible surface area model.
Function/Subroutine Documentation
compute_numsa()
pure subroutine, public xtb_solv_sasa::compute_numsa (integer, intent(in) nat, integer, dimension(:), intent(in) nnsas, integer, dimension(:, :), intent(in) nnlists, real(wp), dimension(:, :), intent(in) xyz, real(wp), dimension(:), intent(in) vdwsa, real(wp), dimension(:), intent(in) wrp, real(wp), dimension(:, :), intent(in) trj2, real(wp), dimension(:), intent(in) angWeight, real(wp), dimension(:, :), intent(in) angGrid, real(wp), dimension(:), intent(out) sasa, real(wp), dimension(:, :, :), intent(out) dsdrt)
Parameters
[in] nat Number of atoms
[in] nnsas Number of neighbours to consider
[in] nnlists Neighbourlist
[in] xyz Cartesian coordinates
[in] vdwsa Van-der-Waals radii including probe radius of solvent
[in] wrp Radial weights for the numerical integration
[in] trj2 Radial smoothing function
[in] angweight Angular weights for the numerical integration
[in] anggrid Angular grid for each atom
[out] sasa Surface area for each atom, including surface tension
[out] dsdrt Derivative of surface area w.r.t. cartesian coordinates
Definition at line 40 of file sasa.f90.
    integer, intent(in) :: nat
    integer, intent(in) :: nnsas(:)
    integer, intent(in) :: nnlists(:, :)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in) :: vdwsa(:)
    real(wp), intent(in) :: wrp(:)
    real(wp), intent(in) :: trj2(:, :)
    real(wp), intent(in) :: angWeight(:)
    real(wp), intent(in) :: angGrid(:, :)
    real(wp), intent(out) :: sasa(:)
    real(wp), intent(out) :: dsdrt(:, :, :)
    integer iat,jat
    integer ip,jj,nnj,nnk
    real(wp) rsas,sasai
    real(wp) xyza(3),xyzp(3),sasap
    real(wp) wr,wsa,drjj(3)
    integer :: nno
    real(wp), allocatable :: grds(:,:)
    real(wp), allocatable :: grads(:,:)
    integer :: nni
    integer, allocatable :: grdi(:)
    sasa(:) = 0.0_wp
    dsdrt(:, :, :) = 0.0_wp
    allocate(grads(3,nat), source = 0.0_wp)
    do iat = 1, nat
       rsas = vdwsa(iat)
       ! allocate space for the gradient storage
       nno=nnsas(iat)
       allocate(grds(3,nno))
       allocate(grdi(nno))
       ! initialize storage
       grads = 0.0_wp
       sasai = 0.0_wp
       ! atomic position
       xyza(:)=xyz(:,iat)
       ! radial atomic weight
       wr=wrp(iat)
       ! loop over grid points
       do ip=1, size(anggrid, 2)
          ! grid point position
          xyzp(:) = xyza(:) + rsas*anggrid(1:3,ip)
          ! atomic surface function at the grid point
          call compute_w_sp(nat,nnlists,trj2,vdwsa, &
             &              xyz,iat,nno,xyzp,sasap,grds,nni,grdi)
          if(sasap.gt.tolsesp) then
             ! numerical quadrature weight
             wsa = angweight(ip)*wr*sasap
             ! accumulate the surface area
             sasai = sasai + wsa
             ! accumulate the surface gradient
             do jj = 1, nni
                nnj = grdi(jj)
                drjj(:) = wsa*grds(:,jj)
                grads(:,iat)=grads(:,iat)+drjj(:)
                grads(:,nnj)=grads(:,nnj)-drjj(:)
             enddo
          endif
       enddo
       deallocate(grds)
       deallocate(grdi)
       sasa(iat) = sasai
       dsdrt(:,:,iat) = grads
    enddo
References compute_w_sp(), and tolsesp.
Referenced by xtb_solv_gbsa::update().
compute_w_sp()
pure subroutine xtb_solv_sasa::compute_w_sp (integer, intent(in) nat, integer, dimension(nat,nat), intent(in) nnlists, real(wp), dimension(2,nat), intent(in) trj2, real(wp), dimension(nat), intent(in) vdwsa, real(wp), dimension(3,nat), intent(in) xyza, integer, intent(in) iat, integer, intent(in) nno, real(wp), dimension(3), intent(in) xyzp, real(wp), intent(out) sasap, real(wp), dimension(3,nno), intent(out) grds, integer, intent(out) nni, integer, dimension(nno), intent(out) grdi) private
Definition at line 143 of file sasa.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: nnlists(nat,nat)
    integer, intent(in)  :: iat
    integer, intent(in)  :: nno
    integer, intent(out) :: nni
    real(wp),intent(in)  :: xyza(3,nat)
    real(wp),intent(in)  :: xyzp(3)
    real(wp),intent(out) :: sasap
    real(wp),intent(out) :: grds(3,nno)
    integer, intent(out) :: grdi(nno)
    real(wp),intent(in)  :: trj2(2,nat)
    real(wp),intent(in)  :: vdwsa(nat)
    integer  :: i,ia
    real(wp) :: tj(3),tj2,sqtj
    real(wp) :: uj,uj3,ah3uj2
    real(wp) :: sasaij,dsasaij
    ! initialize storage
    nni=0
    sasap=1.0_wp
    do i = 1, nno
       ia = nnlists(i,iat)
       ! compute the distance to the atom
       tj(:)=xyzp(:)-xyza(:,ia)
       tj2=tj(1)*tj(1)+tj(2)*tj(2)+tj(3)*tj(3)
       ! if within the outer cut-off compute
       if(tj2.lt.trj2(2,ia)) then
          if(tj2.le.trj2(1,ia)) then
             sasap=0.0_wp
             return
          else
             sqtj = sqrt(tj2)
             uj = sqtj - vdwsa(ia)
             ah3uj2 = ah3*uj*uj
             dsasaij = ah1+3.0_wp*ah3uj2
             sasaij =  ah0+(ah1+ah3uj2)*uj
             ! accumulate the molecular surface
             sasap = sasap*sasaij
             ! compute the gradient wrt the neighbor
             dsasaij = dsasaij/(sasaij*sqtj)
             nni=nni+1
             grdi(nni)=ia
             grds(:,nni) = dsasaij*tj(:)
          endif
          ! check if the point is already buried
 !        if(sasap.lt.tolsesp) return
       endif
    enddo
References ah0, ah1, and ah3.
Referenced by compute_numsa().
Variable Documentation
ah0
real(wp), parameter xtb_solv_sasa::ah0 = 0.5_wp private
Definition at line 30 of file sasa.f90.
    real(wp), parameter :: ah0 = 0.5_wp
Referenced by compute_w_sp().
ah1
real(wp), parameter xtb_solv_sasa::ah1 = 3._wp/(4.0_wp*w) private
Definition at line 31 of file sasa.f90.
    real(wp), parameter :: ah1 = 3._wp/(4.0_wp*w)
Referenced by compute_w_sp().
ah3
real(wp), parameter xtb_solv_sasa::ah3 = -1._wp/(4.0_wp*w3) private
Definition at line 32 of file sasa.f90.
    real(wp), parameter :: ah3 = -1._wp/(4.0_wp*w3)
Referenced by compute_w_sp().
tolsesp
real(wp), parameter xtb_solv_sasa::tolsesp =1.e-6_wp private
real space cut-offs
Definition at line 35 of file sasa.f90.
    real(wp), parameter :: tolsesp=1.e-6_wp
Referenced by compute_numsa().
w
real(wp), parameter xtb_solv_sasa::w = 0.3_wp*aatoau private
Smoothing dielectric function parameters.
Definition at line 28 of file sasa.f90.
    real(wp), parameter :: w = 0.3_wp*aatoau
w3
real(wp), parameter xtb_solv_sasa::w3 = w*(w*w) private
Definition at line 29 of file sasa.f90.
    real(wp), parameter :: w3 = w*(w*w)