My Project: xtb_xtb_calculator Module Reference
xtb_xtb_calculator Module Reference
Extended tight binding calculator.
Data Types
interface generate_wsc
type txtbcalculator
Calculator interface for xTB based methods.
Functions/Subroutines
subroutine singlepoint (self, env, mol, chk, printlevel, restart, energy, gradient, sigma, hlgap, results)
subroutine print_gfn0_results (iunit, res, verbose, lsolv)
subroutine print_gfn1_results (iunit, res, verbose, lsolv)
subroutine print_gfn2_results (iunit, res, verbose, lsolv)
subroutine writeinfo (self, unit, mol)
Variables
character(len= *), parameter, private outfmt = '(9x,"::",1x,a,f23.12,1x,a,1x,"::")'
Detailed Description
Extended tight binding calculator.
Function/Subroutine Documentation
print_gfn0_results()
subroutine xtb_xtb_calculator::print_gfn0_results (integer, intent(in) iunit, type(scc_results), intent(in) res, logical, intent(in) verbose, logical, intent(in) lsolv) private
Definition at line 258 of file calculator.f90.
    use xtb_type_data
    integer, intent(in) :: iunit ! file handle (usually output_unit=6)
    type(scc_results),    intent(in) :: res
    logical,intent(in) :: verbose,lsolv
    write(iunit,outfmt) "H0 energy         ", res%e_elec, "Eh   "
    write(iunit,outfmt) "repulsion energy  ", res%e_rep,  "Eh   "
    write(iunit,outfmt) "electrostat energy", res%e_es,   "Eh   "
    write(iunit,outfmt) "-> Gsolv          ", res%g_solv, "Eh   "
    !write(iunit,outfmt) "   -> Gborn       ", res%g_born, "Eh   " ! not saved
    write(iunit,outfmt) "   -> Gsasa       ", res%g_sasa, "Eh   "
    !write(iunit,outfmt) "   -> Ghb         ", res%g_hb,   "Eh   " ! not saved
    write(iunit,outfmt) "   -> Gshift      ", res%g_shift,"Eh   "
    write(iunit,outfmt) "dispersion energy ", res%e_disp, "Eh   "
    write(iunit,outfmt) "short-range corr. ", res%e_xb,   "Eh   "
References outfmt.
Referenced by singlepoint().
print_gfn1_results()
subroutine xtb_xtb_calculator::print_gfn1_results (integer, intent(in) iunit, type(scc_results), intent(in) res, logical, intent(in) verbose, logical, intent(in) lsolv)
Definition at line 275 of file calculator.f90.
    use xtb_type_data
    integer, intent(in) :: iunit ! file handle (usually output_unit=6)
    type(scc_results),    intent(in) :: res
    logical,intent(in) :: verbose,lsolv
    write(iunit,outfmt) "SCC energy        ", res%e_elec, "Eh   "
    write(iunit,outfmt) "-> electrostatic  ", res%e_es,   "Eh   "
    if (lsolv) then
    write(iunit,outfmt) "-> Gsolv          ", res%g_solv, "Eh   "
    write(iunit,outfmt) "   -> Gborn       ", res%g_born, "Eh   "
    write(iunit,outfmt) "   -> Gsasa       ", res%g_sasa, "Eh   "
    write(iunit,outfmt) "   -> Ghb         ", res%g_hb,   "Eh   "
    write(iunit,outfmt) "   -> Gshift      ", res%g_shift,"Eh   "
    endif
    write(iunit,outfmt) "repulsion energy  ", res%e_rep,  "Eh   "
    write(iunit,outfmt) "dispersion energy ", res%e_disp, "Eh   "
    write(iunit,outfmt) "halogen bond corr.", res%e_xb,   "Eh   "
References outfmt.
Referenced by singlepoint().
print_gfn2_results()
subroutine xtb_xtb_calculator::print_gfn2_results (integer, intent(in) iunit, type(scc_results), intent(in) res, logical, intent(in) verbose, logical, intent(in) lsolv)
Definition at line 294 of file calculator.f90.
    use xtb_type_data
    integer, intent(in) :: iunit ! file handle (usually output_unit=6)
    type(scc_results),    intent(in) :: res
    logical,intent(in) :: verbose,lsolv
    write(iunit,outfmt) "SCC energy        ", res%e_elec, "Eh   "
    write(iunit,outfmt) "-> isotropic ES   ", res%e_es,   "Eh   "
    write(iunit,outfmt) "-> anisotropic ES ", res%e_aes,  "Eh   "
    write(iunit,outfmt) "-> anisotropic XC ", res%e_axc,  "Eh   "
    write(iunit,outfmt) "-> dispersion     ", res%e_disp, "Eh   "
    if (lsolv) then
    write(iunit,outfmt) "-> Gsolv          ", res%g_solv, "Eh   "
    write(iunit,outfmt) "   -> Gborn       ", res%g_born, "Eh   "
    write(iunit,outfmt) "   -> Gsasa       ", res%g_sasa, "Eh   "
    write(iunit,outfmt) "   -> Ghb         ", res%g_hb,   "Eh   "
    write(iunit,outfmt) "   -> Gshift      ", res%g_shift,"Eh   "
    endif
    write(iunit,outfmt) "repulsion energy  ", res%e_rep,  "Eh   "
References outfmt.
Referenced by singlepoint().
singlepoint()
subroutine xtb_xtb_calculator::singlepoint (class(txtbcalculator), intent(inout) self, type(tenvironment), intent(inout) env, type(tmolecule), intent(inout) mol, type(trestart), intent(inout) chk, integer, intent(in) printlevel, logical, intent(in) restart, real(wp), intent(out) energy, real(wp), dimension(:, :), intent(out) gradient, real(wp), dimension(:, :), intent(out) sigma, real(wp), intent(out) hlgap, type(scc_results), intent(out) results) private
Parameters
[in,out] self Calculator instance
[in,out] env Computational environment
[in,out] mol Molecular structure data
[in,out] chk Wavefunction data
[in] printlevel Print level for IO
[in] restart Restart from previous results
[out] energy Total energy
[out] gradient Molecular gradient
[out] sigma Strain derivatives
[out] hlgap HOMO-LUMO gap
[out] results Detailed results
Definition at line 96 of file calculator.f90.
    character(len=*), parameter :: source = 'xtb_calculator_singlepoint'
    class(TxTBCalculator), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(inout) :: mol
    type(TRestart), intent(inout) :: chk
    integer, intent(in) :: printlevel
    logical, intent(in) :: restart
    real(wp), intent(out) :: energy
    real(wp), intent(out) :: gradient(:, :)
    real(wp), intent(out) :: sigma(:, :)
    real(wp), intent(out) :: hlgap
    type(scc_results), intent(out) :: results
    class(TSolvation), allocatable :: solvation
    type(TBorn), allocatable :: gbsa
    integer :: i,ich
    integer :: mode_sp_run = 1
    real(wp) :: efix
    logical :: inmol
    logical, parameter :: ccm = .true.
    logical :: exitRun
    call mol%update
    if (mol%npbc > 0) call generate_wsc(mol,mol%wsc)
    energy = 0.0_wp
    gradient(:, :) = 0.0_wp
    sigma(:, :) = 0.0_wp
    hlgap = 0.0_wp
    efix = 0.0_wp
    ! ------------------------------------------------------------------------
    !  actual calculation
    select case(self%xtbData%level)
    case(1, 2)
       if (allocated(self%solvation)) then
          call newsolvationmodel(self%solvation, env, solvation, mol%at)
       end if
       call scf(env,mol,chk%wfn,self%basis,self%pcem,self%xtbData,solvation, &
          &   hlgap,self%etemp,self%maxiter,printlevel,restart,.true., &
          &   self%accuracy,energy,gradient,results)
    case(0)
       if (allocated(self%solvation)) then
          allocate(gbsa)
          call newbornmodel(self%solvation, env, gbsa, mol%at)
       end if
       call peeq &
          & (env,mol,chk%wfn,self%basis,self%xtbData,gbsa,hlgap,self%etemp, &
          &  printlevel,.true.,ccm,self%accuracy,energy,gradient,sigma,results)
    end select
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Electronic structure method terminated", source)
       return
    end if
    ! ------------------------------------------------------------------------
    !  post processing of gradient and energy
    ! point charge embedding gradient file
    if (allocated(pcem_grad) .and. self%pcem%n > 0) then
       call open_file(ich,pcem_grad,'w')
       do i=1,self%pcem%n
          write(ich,'(3f12.8)')self%pcem%grd(1:3,i)
       enddo
       call close_file(ich)
    endif
    ! ------------------------------------------------------------------------
    !  various external potentials
    call constrain_pot(potset,mol%n,mol%at,mol%xyz,gradient,efix)
    call constrpot   (mol%n,mol%at,mol%xyz,gradient,efix)
    call cavity_egrad(mol%n,mol%at,mol%xyz,efix,gradient)
    if (prob_flag) then
       call prob_metadynamic (metaset,mol%n,mol%at,mol%xyz,efix,gradient)
       call prob_metadynamic (rmsdset,mol%n,mol%at,mol%xyz,efix,gradient)
    else
       call metadynamic (metaset,mol%n,mol%at,mol%xyz,efix,gradient)
       call metadynamic (rmsdset,mol%n,mol%at,mol%xyz,efix,gradient)
    end if
    ! ------------------------------------------------------------------------
    !  fixing of certain atoms
    !  print*,abs(efix/etot)
    energy = energy + efix
    results%e_total = energy
    results%gnorm = norm2(gradient)
    if (fixset%n.gt.0) then
       do i=1, fixset%n
          !print*,i,fixset%atoms(i)
          gradient(1:3,fixset%atoms(i))=0
       enddo
    endif
    if (printlevel.ge.2) then
       ! start with summary header
       if (.not.silent) then
          write(env%unit,'(9x,53(":"))')
          write(env%unit,'(9x,"::",21x,a,21x,"::")') "SUMMARY"
       endif
       write(env%unit,'(9x,53(":"))')
       write(env%unit,outfmt) "total energy      ", results%e_total,"Eh   "
       if (.not.silent.and.allocated(self%solvation)) then
          write(env%unit,outfmt) "total w/o Gsasa/hb", &
             &  results%e_total-results%g_sasa-results%g_hb-results%g_shift, "Eh   "
       endif
       write(env%unit,outfmt) "gradient norm     ", results%gnorm,  "Eh/a0"
       write(env%unit,outfmt) "HOMO-LUMO gap     ", results%hl_gap, "eV   "
       if (.not.silent) then
          if (verbose) then
             write(env%unit,'(9x,"::",49("."),"::")')
             write(env%unit,outfmt) "HOMO orbital eigv.", chk%wfn%emo(chk%wfn%ihomo),  "eV   "
             write(env%unit,outfmt) "LUMO orbital eigv.", chk%wfn%emo(chk%wfn%ihomo+1),"eV   "
          endif
          write(env%unit,'(9x,"::",49("."),"::")')
          if (self%xtbData%level.eq.2) call print_gfn2_results(env%unit,results,verbose,allocated(self%solvation))
          if (self%xtbData%level.eq.1) call print_gfn1_results(env%unit,results,verbose,allocated(self%solvation))
          if (self%xtbData%level.eq.0) call print_gfn0_results(env%unit,results,verbose,allocated(self%solvation))
          write(env%unit,outfmt) "add. restraining  ", efix,       "Eh   "
          write(env%unit,outfmt) "total charge      ", sum(chk%wfn%q), "e    "
          if (verbose) then
             write(env%unit,'(9x,"::",49("."),"::")')
             write(env%unit,outfmt) "atomisation energy", results%e_atom, "Eh   "
          endif
       endif
       write(env%unit,'(9x,53(":"))')
       write(env%unit,'(a)')
    endif
References xtb_sphereparam::cavity_egrad(), close_file(), xtb_constrainpot::constrain_pot(), constrpot(), xtb_fixparam::fixset, xtb_metadynamic::metadynamic(), xtb_fixparam::metaset, xtb_solv_model::newbornmodel(), xtb_solv_model::newsolvationmodel(), open_file(), outfmt, xtb_setparam::pcem_grad, xtb_peeq::peeq(), xtb_scanparam::potset, print_gfn0_results(), print_gfn1_results(), print_gfn2_results(), prob_module::prob_flag, prob_module::prob_metadynamic(), xtb_fixparam::rmsdset, xtb_scf::scf(), xtb_setparam::silent, true(), and xtb_setparam::verbose.
writeinfo()
subroutine xtb_xtb_calculator::writeinfo (class(txtbcalculator), intent(in) self, integer, intent(in) unit, type(tmolecule), intent(in) mol)
Parameters
[in] self Calculator instance
[in] unit Unit for I/O
[in] mol Molecular structure data
Definition at line 315 of file calculator.f90.
    class(TxTBCalculator), intent(in) :: self
    integer, intent(in) :: unit
    type(TMolecule), intent(in) :: mol
    call self%xtbData%writeInfo(unit, mol%at)
    if (allocated(self%solvation)) then
       call info(self%solvation, unit)
    end if
References xtb_solv_model::info().
Variable Documentation
outfmt
character(len=*), parameter, private xtb_xtb_calculator::outfmt = '(9x,"::",1x,a,f23.12,1x,a,1x,"::")' private
Definition at line 89 of file calculator.f90.
    character(len=*),private,parameter :: outfmt = &
       '(9x,"::",1x,a,f23.12,1x,a,1x,"::")'
Referenced by print_gfn0_results(), print_gfn1_results(), print_gfn2_results(), and singlepoint().