My Project: xtb_restart Module Reference
xtb_restart Module Reference
Functions/Subroutines
subroutine, public readrestart (env, wfx, fname, n, at, gfn_method, success, verbose)
subroutine, public read_restart_gff (env, fname, n, version, success, verbose, topo)
subroutine, public writerestart (env, wfx, fname, gfn_method)
subroutine, public write_restart_gff (env, fname, nat, version, topo)
Function/Subroutine Documentation
read_restart_gff()
subroutine, public xtb_restart::read_restart_gff (type(tenvironment), intent(inout) env, character(len=*), intent(in) fname, integer, intent(in) n, integer, intent(in) version, logical, intent(out) success, logical, intent(in) verbose, type(tgfftopology), intent(inout) topo)
Definition at line 88 of file restart.f90.
    use xtb_gfnff_param
    use xtb_gfnff_topology, only : tgfftopology
    implicit none
    character(len=*), parameter :: source = 'restart_read_restart_gff'
    type(TEnvironment), intent(inout) :: env
    type(TGFFTopology), intent(inout) :: topo
    character(len=*),intent(in) :: fname
    integer,intent(in)  :: n
    integer,intent(in)  :: version
    logical,intent(out) :: success
    logical,intent(in)  :: verbose
    integer(i8) :: iver8,nat8
    integer :: ich ! file handle
    integer :: err
    logical :: exist
    success = .false.
    call open_binary(ich,fname,'r')
    if (ich.ne.-1) then
       !read the first byte, which identify the calculation specs
       read(ich,iostat=err) iver8,nat8
       if(err.eq.0) then
          if (iver8.ne.int(version,i8).and.verbose) &
             &  call env%warning('Version number missmatch in restart file.',source)
          if (nat8.ne.n.and.verbose) then
             call env%warning('Atom number missmatch in restart file.',source)
             success=.false.
             call close_file(ich)
             return
          else if (iver8.eq.int(version)) then
             success = .true.
             read(ich) topo%nbond,topo%nangl,topo%ntors,topo%nhb1,topo%nhb2,topo%nxb,topo%nathbH,topo%nathbAB,  &
                     & topo%natxbAB,topo%nbatm,topo%nfrag,topo%nsystem,topo%maxsystem
             read(ich) topo%nbond_blist,topo%nbond_vbond,topo%nangl_alloc,topo%ntors_alloc,topo%bond_hb_nr,topo%b_max
             call gfnff_param_alloc(topo, n)
             if (.not.allocated(topo%ispinsyst)) allocate( topo%ispinsyst(n,topo%maxsystem), source = 0 )
             if (.not.allocated(topo%nspinsyst)) allocate( topo%nspinsyst(topo%maxsystem), source = 0 )
             read(ich) topo%nb,topo%bpair,topo%blist,topo%alist, &
                & topo%tlist,topo%b3list,topo%hblist1,topo%hblist2, &
                & topo%hblist3,topo%fraglist,topo%hbatHl,topo%hbatABl, &
                & topo%xbatABl,topo%ispinsyst,topo%nspinsyst,topo%bond_hb_AH, &
                & topo%bond_hb_B,topo%bond_hb_Bn,topo%nr_hb
             read(ich) topo%vbond,topo%vangl,topo%vtors,topo%chieeq, &
                & topo%gameeq,topo%alpeeq,topo%alphanb,topo%qa, &
                & topo%q,topo%xyze0,topo%zetac6,&
                & topo%qfrag,topo%hbbas,topo%hbaci
          else
             if (verbose) &
                call env%warning("Dimension missmatch in restart file.",source)
             success = .false.
          endif
       else
          if (verbose) &
             call env%warning("Dimension missmatch in restart file.",source)
          success = .false.
       endif
       call close_file(ich)
    endif
References close_file(), xtb_gfnff_param::gfnff_param_alloc(), xtb_mctc_accuracy::i8, open_binary(), and true().
Referenced by xtb_gfnff_setup::gfnff_setup().
readrestart()
subroutine, public xtb_restart::readrestart (type(tenvironment), intent(inout) env, type(twavefunction), intent(inout) wfx, character(len=*), intent(in) fname, integer, intent(in) n, integer, dimension(n), intent(in) at, integer, intent(in) gfn_method, logical, intent(out) success, logical, intent(in) verbose)
Definition at line 32 of file restart.f90.
    character(len=*), parameter :: source = 'restart_readRestart'
    type(TEnvironment), intent(inout) :: env
    type(TWavefunction),intent(inout) :: wfx
    character(len=*),intent(in) :: fname
    integer,intent(in)  :: n
    integer,intent(in)  :: at(n)
    integer,intent(in)  :: gfn_method
    logical,intent(out) :: success
    logical,intent(in)  :: verbose
    integer(i8) :: iver8,idum8,n8,nshell8,nel8,nopen8
    integer :: ich ! file handle
    integer :: err
    logical :: exist
    success = .false.
    call open_binary(ich,fname,'r')
    if (ich.ne.-1) then
       ! read the first 48 byte, which identify the calculation specs
       read(ich,iostat=err) iver8,idum8,n8,nshell8,nel8,nopen8
       if(err.eq.0) then
          if (iver8.ne.int(gfn_method,i8).and.verbose) &
             &  call env%warning('Version number missmatch in restart file.', source)
          if (nel8.ne.int(wfx%nel,i8).and.verbose) &
             &  call env%warning('Number of electron missmatch in restart file.', source)
          if (nopen8.ne.int(wfx%nopen,i8).and.verbose) &
             &  call env%warning('Multiplicity missmatch in restart file.', source)
          if ((n8.eq.int(wfx%n,i8)).and.(nshell8.eq.int(wfx%nshell,i8))) then
             success = .true.
             read(ich) wfx%qsh
             if (verbose) &
             write(stdout,'("q/qsh data taken from xtbrestart")')
             if ((gfn_method.gt.1).and.(iver8.gt.1)) then
 !              read dipole and qpole CAMM
                read(ich) wfx%dipm
                read(ich) wfx%qp
                if (verbose) &
                write(stdout,'("CAMM data taken from xtbrestart")')
             endif
          else
             if (verbose) &
             call env%warning('Dimension missmatch in restart file.', source)
             success = .false.
          endif
       else
          if (verbose) &
          call env%warning("Dimension missmatch in restart file.", source)
          success = .false.
       end if
       call close_file(ich)
    end if
References close_file(), xtb_mctc_accuracy::i8, open_binary(), and true().
Referenced by xtb_prog_main::xtbmain().
write_restart_gff()
subroutine, public xtb_restart::write_restart_gff (type(tenvironment), intent(inout) env, character(len=*), intent(in) fname, integer, intent(in) nat, integer, intent(in) version, type(tgfftopology), intent(in) topo)
Definition at line 174 of file restart.f90.
    use xtb_gfnff_param
    use xtb_gfnff_topology, only : tgfftopology
    implicit none
    type(TEnvironment), intent(inout) :: env
    type(TGFFTopology), intent(in) :: topo
    character(len=*),intent(in) :: fname
    integer,intent(in)  :: nat
    integer,intent(in)  :: version
    integer :: ich ! file handle
    call open_binary(ich,fname,'w')
    !Dimensions
    write(ich) int(version,i8),int(nat,i8)
    write(ich) topo%nbond,topo%nangl,topo%ntors,   &
             & topo%nhb1,topo%nhb2,topo%nxb,topo%nathbH,topo%nathbAB,topo%natxbAB,topo%nbatm,topo%nfrag,topo%nsystem,  &
             & topo%maxsystem
    write(ich) topo%nbond_blist,topo%nbond_vbond,topo%nangl_alloc,topo%ntors_alloc,topo%bond_hb_nr,topo%b_max
    !Arrays Integers
    write(ich) topo%nb,topo%bpair,topo%blist,topo%alist,topo%tlist,topo%b3list,topo%hblist1,topo%hblist2,topo%hblist3, &
       & topo%fraglist,topo%hbatHl,topo%hbatABl,topo%xbatABl,topo%ispinsyst,topo%nspinsyst,             &
       & topo%bond_hb_AH,topo%bond_hb_B,topo%bond_hb_Bn,topo%nr_hb
    !Arrays Reals
    write(ich) topo%vbond,topo%vangl,topo%vtors,topo%chieeq,topo%gameeq,topo%alpeeq,topo%alphanb,topo%qa,topo%q,       &
       & topo%xyze0,topo%zetac6,topo%qfrag,topo%hbbas,topo%hbaci
    call close_file(ich)
References close_file(), xtb_mctc_accuracy::i8, and open_binary().
Referenced by xtb_gfnff_setup::gfnff_setup().
writerestart()
subroutine, public xtb_restart::writerestart (type(tenvironment), intent(inout) env, type(twavefunction), intent(inout) wfx, character(len=*), intent(in) fname, integer, intent(in) gfn_method)
Definition at line 153 of file restart.f90.
    type(TEnvironment), intent(inout) :: env
    type(TWavefunction),intent(inout) :: wfx
    character(len=*),intent(in) :: fname
    integer,intent(in)  :: gfn_method
    integer :: ich ! file handle
    call open_binary(ich,fname,'w')
    write(ich) int(gfn_method,i8),int(gfn_method,i8), &
       int(wfx%n,i8),int(wfx%nshell,i8), &
       int(wfx%nel,i8),int(wfx%nopen,i8)
    write(ich) wfx%qsh
    if (gfn_method.gt.1) then
       write(ich) wfx%dipm
       write(ich) wfx%qp
    endif
    call close_file(ich)
References close_file(), xtb_mctc_accuracy::i8, and open_binary().
Referenced by xtb_prog_main::xtbmain().