My Project: xtb_grad_core Module Reference
xtb_grad_core Module Reference
Functions/Subroutines
pure subroutine dshellpoly (iPoly, jPoly, iRad, jRad, rab2, xyz1, xyz2, rf, dxyz)
Variables
integer, dimension(20), parameter, private mmm =(/1,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4/)
Function/Subroutine Documentation
dshellpoly()
pure subroutine xtb_grad_core::dshellpoly (real(wp), intent(in) iPoly, real(wp), intent(in) jPoly, real(wp), intent(in) iRad, real(wp), intent(in) jRad, real(wp), intent(in) rab2, real(wp), dimension(3), intent(in) xyz1, real(wp), dimension(3), intent(in) xyz2, real(wp), intent(out) rf, real(wp), dimension(3), intent(out) dxyz)
Definition at line 40 of file grad_core.f90.
    !$acc routine seq
    real(wp), intent(in)  :: iPoly,jPoly
    real(wp), intent(in)  :: iRad,jRad
    real(wp), intent(in)  :: rab2
    real(wp), intent(out) :: dxyz(3),rf
    real(wp), intent(in)  :: xyz1(3),xyz2(3)
    real(wp) :: rab,k1,k2,rr,r,a,dum,rf1,rf2,dx,dy,dz
    real(wp) :: t14,t15,t17,t22,t20,t23,t10,t11,t35,t13
    a=0.5            ! R^a dependence 0.5 in GFN1
    dx=xyz1(1)-xyz2(1)
    dy=xyz1(2)-xyz2(2)
    dz=xyz1(3)-xyz2(3)
    rab=sqrt(rab2)
    ! this sloppy conv. factor has been used in development, keep it
    r=irad+jrad
    rr=rab/r
    k1=ipoly*0.01_wp
    k2=jpoly*0.01_wp
    t14 = rr**a
    t15 = k1*t14
    t17 = 1.0_wp/rab2
    t22 = rr**a
    t23 = k2*t22
    rf=(1.0_wp+t15)*(1.0_wp+k2*t22)
    dxyz(:)=(t15*(1.0_wp+t23)+(1.0_wp+t15)*k2*t22)*a*t17*[dx,dy,dz]
Referenced by xtb_xtb_hamiltonian::build_dsdqh0(), xtb_xtb_hamiltonian_gpu::build_dsdqh0_gpu(), xtb_xtb_hamiltonian::build_dsdqh0_noreset(), xtb_peeq::ccm_build_dsh0(), and xtb_peeq::pbc_build_dsh0().
Variable Documentation
mmm
integer, dimension(20), parameter, private xtb_grad_core::mmm =(/1,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4/) private
Definition at line 33 of file grad_core.f90.
    integer, private, parameter :: mmm(20)=(/1,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4/)
Referenced by xtb_scf::scf().