My Project: xtb_mctc_filetools Module Reference
xtb_mctc_filetools Module Reference
Data Types
type filelog
Functions/Subroutines
subroutine init_filelist (maxfiles)
subroutine reallocate_filelist
subroutine push_file (unit, name, status)
subroutine pop_file (unit, status)
Variables
type(filelog), dimension(:), allocatable filelist
integer nfiles = 0
Function/Subroutine Documentation
init_filelist()
subroutine xtb_mctc_filetools::init_filelist (integer, intent(in) maxfiles)
Definition at line 117 of file mctc_filetools.f90.
    integer,intent(in) :: maxfiles
    nfiles = 0
    if (allocated(filelist)) deallocate(filelist)
    allocate( filelist(maxfiles) )
References filelist, and nfiles.
Referenced by mctc_init().
pop_file()
subroutine xtb_mctc_filetools::pop_file (integer, intent(in) unit, character(len=1), intent(in), optional status)
Definition at line 155 of file mctc_filetools.f90.
    implicit none
    integer,intent(in) :: unit
    character(len=1),intent(in),optional :: status
    logical :: found
    integer :: i
    found = .false.
    do i = 1, nfiles
       found = unit.eq.filelist(i)%unit .and. filelist(i)%open
       if (found) then
          if (present(status)) filelist(i)%status = status
          filelist(i)%open = .false.
          exit
       endif
    enddo
References filelist, and nfiles.
push_file()
subroutine xtb_mctc_filetools::push_file (integer, intent(in) unit, character(len=*), intent(in) name, character(len=1), intent(in) status)
Definition at line 135 of file mctc_filetools.f90.
    implicit none
    character(len=*),intent(in)  :: name
    character(len=1),intent(in)  :: status
    integer,         intent(in)  :: unit
    character(len=:),allocatable :: tmp
    nfiles = nfiles + 1
    if (nfiles .gt. size(filelist,1)) call reallocate_filelist
    filelist(nfiles)%name = name
    filelist(nfiles)%status = status
    filelist(nfiles)%unit = unit
    if (status.eq.'d' .or. status.eq.'t') then
       filelist(nfiles)%open = .false.
    else
       filelist(nfiles)%open = .true.
    endif
References filelist, nfiles, reallocate_filelist(), and true().
reallocate_filelist()
subroutine xtb_mctc_filetools::reallocate_filelist
Definition at line 124 of file mctc_filetools.f90.
    integer :: current_size,new_size
    type(filelog),allocatable :: tmplist(:)
    current_size = size(filelist,1)
    new_size = current_size+current_size/2+1
    allocate( tmplist(new_size) )
    tmplist(:current_size) = filelist
    deallocate( filelist )
    call move_alloc(tmplist,filelist)
References filelist.
Referenced by push_file().
Variable Documentation
filelist
type(filelog), dimension(:), allocatable xtb_mctc_filetools::filelist
Definition at line 112 of file mctc_filetools.f90.
 type(filelog),allocatable :: filelist(:)
Referenced by init_filelist(), pop_file(), push_file(), and reallocate_filelist().
nfiles
integer xtb_mctc_filetools::nfiles = 0
Definition at line 113 of file mctc_filetools.f90.
 integer :: nfiles = 0
Referenced by init_filelist(), pop_file(), and push_file().