My Project: xtb_io_writer Module Reference
xtb_io_writer Module Reference
TODO.
Functions/Subroutines
subroutine, public writemolecule (self, unit, format, energy, gnorm, number)
Detailed Description
TODO.
Function/Subroutine Documentation
writemolecule()
subroutine, public xtb_io_writer::writemolecule (class(tmolecule), intent(in) self, integer, intent(in) unit, integer, intent(in), optional format, real(wp), intent(in), optional energy, real(wp), intent(in), optional gnorm, integer, intent(in), optional number)
Definition at line 40 of file writer.f90.
    class(TMolecule), intent(in) :: self
    integer, intent(in) :: unit
    integer, intent(in), optional :: format
    real(wp), intent(in), optional :: energy
    real(wp), intent(in), optional :: gnorm
    integer, intent(in), optional :: number
    character(len=:), allocatable :: comment_line
    character(len=20) :: energy_line
    character(len=20) :: gnorm_line
    integer :: ftype
    if (present(format)) then
       ftype = format
    else
       ftype = self%ftype
    endif
    comment_line = ''
    if (present(energy)) then
       write(energy_line, '(f20.12)') energy
       comment_line = comment_line // " energy: " // trim(adjustl(energy_line))
    endif
    if (present(gnorm)) then
       write(gnorm_line, '(f20.12)') gnorm
       comment_line = comment_line // " gnorm: " // trim(adjustl(gnorm_line))
    endif
    comment_line = comment_line // " xtb: " // version
    select case(ftype)
    case(filetype%xyz)
       call writemoleculexyz(self, unit, trim(comment_line))
    case(filetype%tmol)
       call writemoleculecoord(self, unit)
    case(filetype%molfile)
       call writemoleculemolfile(self, unit, trim(comment_line))
    case(filetype%sdf)
       call writemoleculesdf(self, unit, energy, gnorm)
    case(filetype%vasp)
       call writemoleculevasp(self, unit, trim(comment_line))
    case(filetype%gen)
       call writemoleculegenformat(self, unit, trim(comment_line))
    case(filetype%gaussian)
       call writemoleculegaussianexternal(self, unit)
    case(filetype%pdb)
       if (present(number)) then
          call writemoleculepdb(self, unit, number)
       else
          call writemoleculepdb(self, unit)
       endif
    end select
    ! Flush file so that the output file can be visualized during optimization
    flush(unit)
References xtb_mctc_filetypes::filetype, xtb_io_writer_turbomole::writemoleculecoord(), xtb_io_writer_gaussian::writemoleculegaussianexternal(), xtb_io_writer_genformat::writemoleculegenformat(), xtb_io_writer_ctfile::writemoleculemolfile(), xtb_io_writer_pdb::writemoleculepdb(), xtb_io_writer_ctfile::writemoleculesdf(), xtb_io_writer_vasp::writemoleculevasp(), and xtb_io_writer_xyz::writemoleculexyz().
Referenced by xtb_biaspath::bias_path(), xtb_topology::checktopology(), xtb_hessian::distort(), xtb_relaxation_engine::fire(), xtb_relaxation_engine::inertial_relax(), xtb_relaxation_engine::l_ancopt(), xtb_relaxation_engine::lbfgs_relax(), xtb_dynamic::md(), xtb_mdoptim::mdopt(), xtb_optimizer::relax(), xtb_scan::relaxed_scan(), xtb_extern_orca::runorca(), xtb_screening::screen(), and xtb_prog_main::xtbmain().