My Project: xtb_type_neighbourlist Module Reference
xtb_type_neighbourlist Module Reference
Static neighbour list implementation.
Data Types
type tneighbourlist
Static neighbour list.
interface init
Initialize neighbour list.
Functions/Subroutines
subroutine initneighbourlist (self, nAtom)
Initialize neighbour list.
subroutine generate (self, env, coords0, cutoff, latPoint, symmetric)
Generate neighbour list.
subroutine generatesequential (self, env, coords0, cutoff, latPoint, symmetric)
Generate neighbour list in serial.
subroutine update (self, coords0, cellVec)
Update neighbour list with new coordinates.
subroutine sort (self)
Sort neighbours for all atom by distance.
pure subroutine getneighsall (self, neighs, cutoff)
Get all neighbours for a given cutoff.
elemental subroutine getneighsone (self, neighs, iatom, cutoff)
Get neighbour for a given cutoff.
subroutine, public resizeimage (mImage, image, trans, coords)
Reallocate arrays which depends on the maximal nr. of all atoms.
subroutine, public resizeneigh (mNeigh, iNeigh, dist2, weight)
Reallocate array which depends on the maximal nr. of neighbours.
Variables
integer, parameter, public initialnumberofneighbours = 40
Initial number of neighbours.
Detailed Description
Static neighbour list implementation.
Based on the implementation used in DFTB+ (see module dftbp_periodic there)
Function/Subroutine Documentation
generate()
subroutine xtb_type_neighbourlist::generate (class(tneighbourlist), intent(inout) self, type(tenvironment), intent(inout) env, real(wp), dimension(:, :), intent(in) coords0, real(wp), intent(in) cutoff, real(wp), dimension(:, :), intent(in) latPoint, logical, intent(in) symmetric) private
Generate neighbour list.
Parameters
[in,out] self Instance of the neighbour list
[in,out] env Computation environment
[in] coords0 Folded coordinates of the atoms inside the unit cell
[in] cutoff Realspace cutoff for the generation of neighbours
[in] latpoint Lattice points for all supercells within the cutoff
[in] symmetric Generate a symmetric map
Definition at line 121 of file neighbourlist.f90.
    class(TNeighbourList), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: coords0(:, :)
    real(wp), intent(in) :: cutoff
    real(wp), intent(in) :: latPoint(:, :)
    logical, intent(in) :: symmetric
    call generatesequential(self, env, coords0, cutoff, latpoint, symmetric)
    call self%sort
References generatesequential().
generatesequential()
subroutine xtb_type_neighbourlist::generatesequential (class(tneighbourlist), intent(inout) self, type(tenvironment), intent(inout) env, real(wp), dimension(:, :), intent(in) coords0, real(wp), intent(in) cutoff, real(wp), dimension(:, :), intent(in) latPoint, logical, intent(in) symmetric) private
Generate neighbour list in serial.
Parameters
[in,out] self Instance of the neighbour list
[in,out] env Computation environment
[in] coords0 Folded coordinates of the atoms inside the unit cell
[in] cutoff Realspace cutoff for the generation of neighbours
[in] latpoint Lattice points for all supercells within the cutoff
[in] symmetric Generate a symmetric map
Number of atoms in the central cell
Number of translations to consider
Capacity of the atom related arrays
Capacity of the neighbour related arrays
Index of the current image
Quadratic cutoff
Get dimensions for the generator loop
Get initial capacities
Set the value of the cutoff
Initialize neighbour list with distances from every atom to itself
Generate position of image
Calculate distance between atoms in cell and the image
New atom in range found, add image to list
Check for particular close distance
Small distances between the atom and itself are okay
Definition at line 149 of file neighbourlist.f90.
    character(len=*), parameter :: source = 'type_neighbourlist_generateSerial'
    class(TNeighbourList), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: coords0(:, :)
    real(wp), intent(in) :: cutoff
    real(wp), intent(in) :: latPoint(:, :)
    logical, intent(in) :: symmetric
    integer :: nAtom
    integer :: nTrans
    integer :: mImage
    integer :: mNeigh
    integer :: nImage
    real(wp) :: cutoff2
    integer :: iTr, iAt, iAtOld, jAt, jAtEnd
    real(wp) :: ri(3), dist2, trans(3)
    natom = size(self%neighs, dim=1)
    ntrans = size(latpoint, dim=2)
    mimage = size(self%coords, dim=2)
    mneigh = ubound(self%iNeigh, dim=1)
    self%cutoff = cutoff
    cutoff2 = cutoff**2
    self%neighs(:) = 0
    self%iNeigh(:, :) = 0
    self%dist2(:, :) = 0.0_wp
    self%weight(:, :) = 0.0_wp
    do iat = 1, natom
       self%iNeigh(0, iat) = iat
       self%weight(0, iat) = 1.0_wp
    end do
    nimage = 0
    lptrans: do itr = 1, ntrans
       trans(:) = latpoint(:, itr)
       iatold = 0
       lpiat: do iat = 1, natom
          ri(:) = coords0(:, iat) + trans(:)
          if (symmetric) then
             jatend = natom
          else
             jatend = iat
          end if
          lpjat: do jat = 1, jatend
             dist2 = sum((coords0(:, jat) - ri(:))**2)
             if (dist2 > cutoff2) then
                cycle lpjat
             end if
             if (iat /= iatold) then
                nimage = nimage + 1
                if (nimage > mimage) then
                   mimage = 2*mimage
                   call resizeimage(mimage, self%image, self%trans, self%coords)
                end if
                self%coords(:, nimage) = ri(:)
                self%image(nimage) = iat
                self%trans(nimage) = itr
                iatold = iat
             end if
             if (dist2 < minneighdist2) then
                if (itr == 1 .and. iat == jat) then
                   cycle lpjat
                else
                   call env%error("Very close distance found", source)
                end if
             end if
             self%neighs(jat) = self%neighs(jat) + 1
             if (self%neighs(jat) > mneigh) then
                mneigh = 2*mneigh
                call resizeneigh(mneigh, self%iNeigh, self%dist2, self%weight)
             end if
             self%iNeigh(self%neighs(jat), jat) = nimage
             self%dist2(self%neighs(jat), jat) = dist2
             self%weight(self%neighs(jat), jat) = 1.0_wp
          end do lpjat
       end do lpiat
    end do lptrans
    call resizeimage(nimage, self%image, self%trans, self%coords)
References xtb_mctc_thresholds::minneighdist2, resizeimage(), and resizeneigh().
Referenced by generate().
getneighsall()
pure subroutine xtb_type_neighbourlist::getneighsall (class(tneighbourlist), intent(in) self, integer, dimension(:), intent(out) neighs, real(wp), intent(in), optional cutoff) private
Get all neighbours for a given cutoff.
Parameters
[in] self Instance of the neighbour list
[in] cutoff Realspace cutoff radius
[out] neighs Number of neighbour.
Definition at line 347 of file neighbourlist.f90.
    class(TNeighbourList), intent(in) :: self
    real(wp), intent(in), optional :: cutoff
    integer, intent(out) :: neighs(:)
    integer :: iatom
    real(wp) :: cutoff0
    if (present(cutoff)) then
       cutoff0 = min(cutoff, self%cutoff)
    else
       cutoff0 = self%cutoff
    end if
    do concurrent(iatom = 1:size(neighs))
       call self%getNeighs(neighs(iatom), iatom, cutoff0)
    end do
Referenced by xtb_type_neighbourlist::tneighbourlist::getneighs().
getneighsone()
elemental subroutine xtb_type_neighbourlist::getneighsone (class(tneighbourlist), intent(in) self, integer, intent(out) neighs, integer, intent(in) iatom, real(wp), intent(in), optional cutoff) private
Get neighbour for a given cutoff.
Parameters
[in] self Instance of the neighbour list
[in] iatom Atom of interest.
[in] cutoff Realspace cutoff radius
[out] neighs Number of neighbour.
Definition at line 375 of file neighbourlist.f90.
    class(TNeighbourList), intent(in) :: self
    integer, intent(in) :: iatom
    real(wp), intent(in), optional :: cutoff
    integer, intent(out) :: neighs
    real(wp) :: cutoff2
    if (present(cutoff)) then
       cutoff2 = min(cutoff, self%cutoff)**2
    else
       cutoff2 = self%cutoff**2
    endif
    call bisectsearch(neighs, self%dist2(1:self%neighs(iatom), iatom), &
       & cutoff2, tolsamedist2)
References xtb_mctc_thresholds::tolsamedist2.
Referenced by xtb_type_neighbourlist::tneighbourlist::getneighs().
initneighbourlist()
subroutine xtb_type_neighbourlist::initneighbourlist (type(tneighbourlist), intent(out) self, integer, intent(in) nAtom) private
Initialize neighbour list.
Parameters
[out] self Instance of the neighbour list
[in] natom Number of atoms in the system
Definition at line 98 of file neighbourlist.f90.
    type(TNeighbourList), intent(out) :: self
    integer, intent(in) :: nAtom
    allocate(self%neighs(natom))
    allocate(self%image(natom))
    allocate(self%coords(3, natom))
    allocate(self%trans(natom))
    allocate(self%iNeigh(0:initialnumberofneighbours, natom))
    allocate(self%dist2(0:initialnumberofneighbours, natom))
    allocate(self%weight(0:initialnumberofneighbours, natom))
    self%cutoff = -1.0_wp
resizeimage()
subroutine, public xtb_type_neighbourlist::resizeimage (integer, intent(in) mImage, integer, dimension(:), intent(inout), allocatable image, integer, dimension(:), intent(inout), allocatable trans, real(wp), dimension(:, :), intent(inout), allocatable coords)
Reallocate arrays which depends on the maximal nr. of all atoms.
Parameters
[in] mimage Maximum number of new atoms
[in,out] image Array mapping images of atoms to originals in the central cell
[in,out] trans Index of unit cell containing atom
[in,out] coords Coordinates of all atoms (actual and image)
Definition at line 404 of file neighbourlist.f90.
    integer, intent(in) :: mImage
    integer, allocatable, intent(inout) :: image(:)
    integer, allocatable, intent(inout) :: trans(:)
    real(wp), allocatable, intent(inout) :: coords(:, :)
    integer :: nImage
    integer, allocatable :: iTmp(:)
    real(wp), allocatable :: rTmp(:, :)
    nimage = min(size(image), mimage)
    call move_alloc(image, itmp)
    allocate(image(mimage))
    image(:) = 0
    image(:nimage) = itmp(:nimage)
    itmp(:) = trans(:)
    deallocate(trans)
    allocate(trans(mimage))
    trans(:nimage) = itmp(:nimage)
    call move_alloc(coords, rtmp)
    allocate(coords(3, mimage))
    coords(:, :nimage) = rtmp(:, :nimage)
Referenced by xtb_type_wignerseitzcell::generate(), and generatesequential().
resizeneigh()
subroutine, public xtb_type_neighbourlist::resizeneigh (integer, intent(in) mNeigh, integer, dimension(:, :), intent(inout), allocatable iNeigh, real(wp), dimension(:,:), intent(inout), allocatable dist2, real(wp), dimension(:,:), intent(inout), allocatable weight)
Reallocate array which depends on the maximal nr. of neighbours.
Parameters
[in] mneigh Maximum number of new atoms
[in,out] ineigh List of neighbours
[in,out] dist2 Square of distances between atoms
[in,out] weight Weights for all neighbours
Definition at line 442 of file neighbourlist.f90.
    integer, intent(in) :: mNeigh
    integer, allocatable, intent(inout) :: iNeigh(:, :)
    real(wp), allocatable, intent(inout) :: dist2(:,:)
    real(wp), allocatable, intent(inout) :: weight(:,:)
    integer :: nNeigh, nAtom
    integer, allocatable :: iTmp(:,:)
    real(wp), allocatable :: rTmp(:,:)
    nneigh = ubound(ineigh, dim=1)
    natom = size(ineigh, dim=2)
    call move_alloc(ineigh, itmp)
    allocate(ineigh(0:mneigh, natom))
    ineigh(:,:) = 0
    ineigh(:nneigh, :natom) = itmp
    call move_alloc(dist2, rtmp)
    allocate(dist2(0:mneigh, natom))
    dist2(:,:) = 0.0_wp
    dist2(:nneigh, :natom) = rtmp
    rtmp(:,:) = weight
    deallocate(weight)
    allocate(weight(0:mneigh, natom))
    weight(:,:) = 0.0_wp
    weight(:nneigh, :natom) = rtmp
Referenced by xtb_type_wignerseitzcell::generate(), and generatesequential().
sort()
subroutine xtb_type_neighbourlist::sort (class(tneighbourlist), intent(inout) self) private
Sort neighbours for all atom by distance.
Parameters
[in,out] self Instance of the neighbour list
Definition at line 322 of file neighbourlist.f90.
    class(TNeighbourList), intent(inout) :: self
    integer, allocatable :: indx(:)
    integer :: nAtom, mNeigh, iAt, nn
    natom = size(self%neighs, dim=1)
    mneigh = ubound(self%iNeigh, dim=1)
    allocate(indx(mneigh))
    do iat = 1, natom
       nn = self%neighs(iat)
       call indexheapsort(indx(1:nn), self%dist2(1:nn, iat), tolsamedist2)
       self%iNeigh(1:nn, iat) = self%iNeigh(indx(:nn), iat)
       self%dist2(1:nn, iat) = self%dist2(indx(:nn), iat)
       self%weight(1:nn, iat) = self%weight(indx(:nn), iat)
    end do
References xtb_mctc_sort::indexheapsort(), and xtb_mctc_thresholds::tolsamedist2.
update()
subroutine xtb_type_neighbourlist::update (class(tneighbourlist), intent(inout) self, real(wp), dimension(:, :), intent(in) coords0, real(wp), dimension(:, :), intent(in) cellVec) private
Update neighbour list with new coordinates.
Parameters
[in,out] self Initialized instance on exit
[in] cellvec Absolute coordinates of the shifted super cells
[in] coords0 Coordinates of atoms (folded into unit cell, if periodic)
Number of atoms in the system
Maximum number of atom without reallocation
Update the coordinates of all images
Update neighbour list for all atoms
Sort neighbour lists
Definition at line 276 of file neighbourlist.f90.
    class(TNeighbourList), intent(inout) :: self
    real(wp), intent(in) :: cellVec(:, :)
    real(wp), intent(in) :: coords0(:, :)
    integer :: nAtom
    integer :: nImage
    integer :: iAt, iAtf, jAt, iTr, iNeigh
    real(wp) :: vec(3)
    natom = size(self%neighs, dim=1)
    nimage = size(self%coords, dim=2)
    do iat = 1, nimage
       iatf = self%image(iat)
       itr = self%trans(iat)
       self%coords(:, iat) = coords0(:, iatf) + cellvec(:, itr)
    end do
    do iat = 1, natom
       do ineigh = 1, self%neighs(iat)
          jat = self%iNeigh(ineigh, iat)
          vec(:) = self%coords(:, iat) - self%coords(:, jat)
          self%dist2(ineigh, iat) = sum(vec**2)
       end do
    end do
    call self%sort
Variable Documentation
initialnumberofneighbours
integer, parameter, public xtb_type_neighbourlist::initialnumberofneighbours = 40
Initial number of neighbours.
Definition at line 91 of file neighbourlist.f90.
    integer, parameter :: initialNumberOfNeighbours = 40
Referenced by xtb_type_neighbourlist::init::initneighbourlist(), and xtb_type_wignerseitzcell::init::initwignerseitzcell().