My Project: xtb_disp_ncoord Module Reference
xtb_disp_ncoord Module Reference
Data Types
interface get_d3_cn
interface get_erf_cn
interface get_d4_cn
interface get_gfn_cn
Functions/Subroutines
pure subroutine ncoord_d3_driver (mol, cn, dcndr, thr)
pure subroutine ncoord_gfn_driver (mol, cn, dcndr, thr)
pure subroutine ncoord_erf_driver (mol, cn, dcndr, dcndL, thr)
pure subroutine ncoord_d4_driver (mol, cn, dcndr, dcndL, thr)
pure subroutine ncoord_d3 (nat, at, xyz, cn, thr)
original D3 type coordination number from 2010
pure subroutine dncoord_d3 (nat, at, xyz, cn, dcndr, thr)
pure subroutine pbc_dncoord_d3 (nat, at, xyz, lat, cn, dcndr, dcndL, thr)
pure subroutine ncoord_erf (nat, at, xyz, cn, thr)
pure subroutine dncoord_erf (nat, at, xyz, cn, dcndr, thr)
pure subroutine ncoord_d4 (nat, at, xyz, cn, thr)
pure subroutine dncoord_d4 (nat, at, xyz, cn, dcndr, thr)
pure subroutine pbc_ncoord_d4 (nat, at, xyz, lat, cn, thr)
pure subroutine pbc_dncoord_d4 (nat, at, xyz, lat, cn, dcndr, dcndL, thr)
pure subroutine ncoord_gfn (nat, at, xyz, cn, thr)
pure subroutine dncoord_gfn (nat, at, xyz, cn, dcndr, thr)
pure subroutine pbc_erfcoord (nat, at, xyz, lat, cn, thr)
pure subroutine pbc_derfcoord (nat, at, xyz, lat, cn, dcndr, dcndL, thr)
subroutine dncoord_logcn (n, cn, dcndr, dcndL, cn_max)
cutoff function for large coordination numbers
pure elemental real(wp) function log_cn_cut (cn, cnmax)
pure elemental real(wp) function dlog_cn_cut (cn, cnmax)
pure elemental real(wp) function erf_count (k, r, r0)
pure elemental real(wp) function derf_count (k, r, r0)
pure elemental real(wp) function exp_count (k, r, r0)
pure elemental real(wp) function dexp_count (k, r, r0)
Variables
real(wp), parameter, private cnthr = 1600.0_wp
real(wp), parameter k1 = 16.0_wp
real(wp), parameter k2 = 4.0_wp/3.0_wp
real(wp), parameter ka =10.0_wp
real(wp), parameter kb =20.0_wp
real(wp), parameter r_shift =2.0_wp
real(wp), parameter k4 =4.10451_wp
real(wp), parameter k5 =19.08857_wp
real(wp), parameter k6 =2*11.28174_wp**2
real(wp), parameter kn =7.50_wp
real(wp), parameter kr =0.25_wp
real(wp), parameter ke =0.05_wp
integer, parameter, private max_elem = 118
real(wp), dimension(max_elem), parameter, private rad = (/ 0.32,0.46, 1.20,0.94,0.77,0.75,0.71,0.63,0.64,0.67, 1.40,1.25,1.13,1.04,1.10,1.02,0.99,0.96, 1.76,1.54, 1.33,1.22,1.21,1.10,1.07,1.04,1.00,0.99,1.01,1.09, 1.12,1.09,1.15,1.10,1.14,1.17, 1.89,1.67, 1.47,1.39,1.32,1.24,1.15,1.13,1.13,1.08,1.15,1.23, 1.28,1.26,1.26,1.23,1.32,1.31, 2.09,1.76, 1.62,1.47,1.58,1.57,1.56,1.55,1.51, 1.52,1.51,1.50,1.49,1.49,1.48,1.53, 1.46,1.37,1.31,1.23,1.18,1.16,1.11,1.12,1.13,1.32, 1.30,1.30,1.36,1.31,1.38,1.42, 2.01,1.81, 1.67,1.58,1.52,1.53,1.54,1.55,1.49, 1.49,1.51,1.51,1.48,1.50,1.56,1.58, 1.45,1.41,1.34,1.29,1.27,1.21,1.16,1.15,1.09,1.22, 1.22,1.29,1.46,1.58,1.48,1.41 /)
real(wp), dimension(max_elem), parameter rcov = 4.0_wp/3.0_wp*rad/0.52917726_wp
real(wp), dimension(max_elem), parameter en = (/ 2.20,3.00, 0.98,1.57,2.04,2.55,3.04,3.44,3.98,4.50, 0.93,1.31,1.61,1.90,2.19,2.58,3.16,3.50, 0.82,1.00, 1.36,1.54,1.63,1.66,1.55,1.83,1.88,1.91,1.90,1.65, 1.81,2.01,2.18,2.55,2.96,3.00, 0.82,0.95, 1.22,1.33,1.60,2.16,1.90,2.20,2.28,2.20,1.93,1.69, 1.78,1.96,2.05,2.10,2.66,2.60, 0.79,0.89, 1.10,1.12,1.13,1.14,1.15,1.17,1.18, 1.20,1.21,1.22,1.23,1.24,1.25,1.26, 1.27,1.30,1.50,2.36,1.90,2.20,2.20,2.28,2.54,2.00, 1.62,2.33,2.02,2.00,2.20,2.20, 1.50,1.50, 1.50,1.50,1.50,1.50,1.50,1.50,1.50, 1.50,1.50,1.50,1.50,1.50,1.50,1.50, 1.50,1.50,1.50,1.50,1.50,1.50,1.50,1.50,1.50,1.50, 1.50,1.50,1.50,1.50,1.50,1.50 /)
Function/Subroutine Documentation
derf_count()
pure elemental real(wp) function xtb_disp_ncoord::derf_count (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0)
Definition at line 1169 of file ncoord.f90.
    use xtb_mctc_constants
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    count = -k/sqrtpi/r0*exp(-k**2*(r-r0)**2/r0**2)
References xtb_mctc_constants::sqrtpi.
Referenced by xtb_disp_ncoord::get_d4_cn::dncoord_d4(), xtb_disp_ncoord::get_erf_cn::dncoord_erf(), pbc_derfcoord(), and xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4().
dexp_count()
pure elemental real(wp) function xtb_disp_ncoord::dexp_count (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0)
Definition at line 1186 of file ncoord.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    real(wp) :: expterm
    expterm=exp(-k*(r0/r-1._wp))
    count = (-k*r0*expterm)/(r**2*((expterm+1._wp)**2))
Referenced by xtb_disp_ncoord::get_d3_cn::dncoord_d3(), and pbc_dncoord_d3().
dlog_cn_cut()
pure elemental real(wp) function xtb_disp_ncoord::dlog_cn_cut (real(wp), intent(in) cn, real(wp), intent(in) cnmax)
Definition at line 1154 of file ncoord.f90.
    real(wp), intent(in) :: cn
    real(wp), intent(in) :: cnmax
    real(wp) :: dcnpdcn
    dcnpdcn = exp(cnmax)/(exp(cnmax) + exp(cn))
Referenced by dncoord_logcn().
dncoord_d3()
pure subroutine xtb_disp_ncoord::dncoord_d3 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), intent(in), optional thr)
Definition at line 331 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i, j
    real(wp) :: r, r2, rij(3)
    real(wp) :: rcovij
    real(wp) :: expterm
    real(wp) :: dtmp, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0._wp
    dcndr = 0._wp
    do i = 1, nat
       do j = 1, i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(at(i))+rcov(at(j)))
          tmp = exp_count(k1,r,rcovij)
          dtmp = dexp_count(k1,r,rcovij)
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
          dcndr(:,i,i)=-dtmp*rij/r + dcndr(:,i,i) ! FIXME
          dcndr(:,j,j)= dtmp*rij/r + dcndr(:,j,j) ! FIXME
          dcndr(:,i,j)= dtmp*rij/r
          dcndr(:,j,i)=-dtmp*rij/r
       enddo
    enddo
Referenced by xtb_disp_ncoord::get_d3_cn::ncoord_d3_driver(), and xtb_scf::scf().
dncoord_d4()
pure subroutine xtb_disp_ncoord::dncoord_d4 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), intent(in), optional thr)
Definition at line 631 of file ncoord.f90.
    use xtb_mctc_constants
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i, j, ia, ja
    real(wp) :: r, r2, rij(3)
    real(wp) :: rcovij,den
    real(wp) :: dtmp, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0._wp
    dcndr = 0._wp
    do i = 1, nat
       ia = at(i)
       do j = 1, i-1
          ja = at(j)
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(ia)+rcov(ja))
          den=k4*exp(-(abs((en(ia)-en(ja)))+ k5)**2/k6 )
          tmp = den * erf_count(kn,r,rcovij)
          dtmp = den * derf_count(kn,r,rcovij)
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
          dcndr(:,i,i)=-dtmp*rij/r + dcndr(:,i,i)
          dcndr(:,j,j)= dtmp*rij/r + dcndr(:,j,j)
          dcndr(:,i,j)=-dtmp*rij/r
          dcndr(:,j,i)= dtmp*rij/r
       enddo
    enddo
Referenced by xtb_disp_ncoord::get_d4_cn::ncoord_d4_driver().
dncoord_erf()
pure subroutine xtb_disp_ncoord::dncoord_erf (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), intent(in), optional thr)
Definition at line 519 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: r,r2,rij(3)
    real(wp) :: rcovij
    real(wp) :: dtmp,tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0._wp
    dcndr = 0._wp
    do i = 1, nat
       do j = 1, i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(at(i))+rcov(at(j)))
          tmp = erf_count(kn,r,rcovij)
          dtmp = derf_count(kn,r,rcovij)
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
          dcndr(:,i,i)= dtmp*rij/r + dcndr(:,i,i)
          dcndr(:,j,j)=-dtmp*rij/r + dcndr(:,j,j)
          dcndr(:,i,j)= dtmp*rij/r
          dcndr(:,j,i)=-dtmp*rij/r
       enddo
    enddo
Referenced by xtb_disp_ncoord::get_erf_cn::ncoord_erf_driver().
dncoord_gfn()
pure subroutine xtb_disp_ncoord::dncoord_gfn (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), intent(in), optional thr)
Definition at line 900 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i, j, ia, ja
    real(wp) :: r, r2, rij(3)
    real(wp) :: rcovij
    real(wp) :: expterm1, expterm2
    real(wp) :: dtmp, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0._wp
    dcndr = 0._wp
    do i = 1, nat
       ia = at(i)
       do j = 1, i-1
          ja = at(j)
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(ia)+rcov(ja))
          expterm1=exp(-ka*(rcovij/r-1._wp))
          expterm2=exp(-kb*((rcovij+r_shift)/r-1._wp))
          tmp = 1._wp/(1._wp+expterm1)/(1._wp+expterm2)
          dtmp = (-ka*rcovij*expterm1) &
          &  /(r2*((expterm1+1._wp)**2))/(1._wp+expterm2) &
          &  + (-kb*(rcovij+r_shift)*expterm2) &
          &  /(r2*((expterm2+1._wp)**2))/(1._wp+expterm1)
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
          dcndr(:,i,i)=-dtmp*rij/r + dcndr(:,i,i)
          dcndr(:,j,j)= dtmp*rij/r + dcndr(:,j,j)
          dcndr(:,i,j)= dtmp*rij/r
          dcndr(:,j,i)=-dtmp*rij/r
       enddo
    enddo
Referenced by xtb_disp_ncoord::get_gfn_cn::ncoord_gfn_driver(), and xtb_scf::scf().
dncoord_logcn()
subroutine xtb_disp_ncoord::dncoord_logcn (integer, intent(in) n, real(wp), dimension(n), intent(inout) cn, real(wp), dimension(3,n,n), intent(inout), optional dcndr, real(wp), dimension(3,3,n), intent(inout), optional dcndL, real(wp), intent(in), optional cn_max)
cutoff function for large coordination numbers
Parameters
[in] n number of atoms
[in,out] cn on input coordination number, on output modified CN
[in,out] dcndr on input derivative of CN w.r.t. cartesian coordinates,
[in,out] dcndl on input derivative of CN w.r.t. strain deformation,
[in] cn_max maximum CN (not strictly obeyed)
Definition at line 1102 of file ncoord.f90.
    implicit none
    integer, intent(in) :: n
    real(wp), intent(inout) :: cn(n)
    !  on output derivative of modified CN
    real(wp), intent(inout), optional :: dcndr(3,n,n)
    !  on output derivative of modified CN
    real(wp), intent(inout), optional :: dcndL(3,3,n)
    real(wp), intent(in), optional :: cn_max
    !  local
    real(wp) :: cnmax
    real(wp) :: dcnpdcn
    integer  :: i
    if (present(cn_max)) then
       cnmax = max(cn_max,0.0_wp)
    else
       cnmax = 4.5_wp
    endif
    if (present(dcndl)) then
       do i = 1, n
          dcnpdcn = dlog_cn_cut(cn(i),cnmax)
          dcndl(:,:,i) = dcnpdcn*dcndl(:,:,i)
       enddo
    endif
    if (present(dcndr)) then
       do i = 1, n
          dcnpdcn = dlog_cn_cut(cn(i),cnmax)
          dcndr(:,:,i) = dcnpdcn*dcndr(:,:,i)
       enddo
    endif
    do i = 1, n
       cn(i) = log_cn_cut(cn(i),cnmax)
    enddo
References dlog_cn_cut(), and log_cn_cut().
erf_count()
pure elemental real(wp) function xtb_disp_ncoord::erf_count (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0)
Definition at line 1161 of file ncoord.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    count = 0.5_wp * (1.0_wp + erf(-k*(r-r0)/r0))
Referenced by xtb_disp_ncoord::get_d4_cn::dncoord_d4(), xtb_disp_ncoord::get_erf_cn::dncoord_erf(), xtb_disp_ncoord::get_d4_cn::ncoord_d4(), xtb_disp_ncoord::get_erf_cn::ncoord_erf(), pbc_derfcoord(), xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4(), pbc_erfcoord(), and xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4().
exp_count()
pure elemental real(wp) function xtb_disp_ncoord::exp_count (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0)
Definition at line 1178 of file ncoord.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    count =1.0_wp/(1.0_wp+exp(-k*(r0/r-1.0_wp)))
Referenced by xtb_disp_ncoord::get_d3_cn::dncoord_d3(), xtb_disp_ncoord::get_d3_cn::ncoord_d3(), xtb_disp_ncoord::get_gfn_cn::ncoord_gfn(), and pbc_dncoord_d3().
log_cn_cut()
pure elemental real(wp) function xtb_disp_ncoord::log_cn_cut (real(wp), intent(in) cn, real(wp), intent(in) cnmax)
Definition at line 1147 of file ncoord.f90.
    real(wp), intent(in) :: cn
    real(wp), intent(in) :: cnmax
    real(wp) :: cnp
    cnp = log(1.0_wp + exp(cnmax)) - log(1.0_wp + exp(cnmax - cn))
Referenced by dncoord_logcn().
ncoord_d3()
pure subroutine xtb_disp_ncoord::ncoord_d3 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
original D3 type coordination number from 2010
Definition at line 280 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, tmp, r2
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn = 0.0_wp
    do i = 1, nat
       do j = 1, i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
 !        covalent distance in bohr
          rco=rcov(at(j)) + rcov(at(i))
 !        counting function exponential has a better long-range
 !        behavior than MHGs inverse damping
          tmp=exp_count(k1,r,rco)
          cn(i)=cn(i)+tmp
          cn(j)=cn(j)+tmp
       enddo
    enddo
Referenced by abcdisp(), gdisp(), xtb_iniq::iniqcn_gfn1(), xtb_iniq::iniqcn_vtb(), xtb_disp_ncoord::get_d3_cn::ncoord_d3_driver(), pocketscan(), and xtb_prog_main::xtbmain().
ncoord_d3_driver()
pure subroutine xtb_disp_ncoord::ncoord_d3_driver (type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:,:,:), intent(out), optional dcndr, real(wp), intent(in), optional thr)
Parameters
[in] mol molecular structure information
[out] cn coordination number
[out] dcndr derivative of coordination number w.r.t. nuclear positions
[in] thr quadratic distance threshold for sum termination
Definition at line 138 of file ncoord.f90.
    use xtb_type_molecule
    implicit none
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out), optional :: dcndr(:,:,:)
    real(wp), intent(in), optional :: thr
    real(wp) :: cn_thr
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
 !   if (mol%npbc > 0) then
 !      if (present(dcndr).and.present(dcndL)) then
 !      else
 !      endif
 !   else
       if (present(dcndr)) then
          call dncoord_d3(mol%n,mol%at,mol%xyz,cn,dcndr,cn_thr)
       else
          call ncoord_d3(mol%n,mol%at,mol%xyz,cn,cn_thr)
       endif
 !   endif
ncoord_d4()
pure subroutine xtb_disp_ncoord::ncoord_d4 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
Definition at line 575 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, rr, r2, xn, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn = 0._wp
    do i=1,nat
       do j=1,i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
 !        covalent distance in bohr
          rco=rcov(at(j)) + rcov(at(i))
          rr=rco/r
          den=k4*exp(-(abs((en(at(i))-en(at(j))))+ k5)**2/k6 )
 !        counting function exponential has a better long-range
 !        behavior than MHGs inverse damping
          !tmp = den/(1.d0+exp(-k1*(rr-1.0d0)))
 !        error function has an even better long range behavior
          tmp = den * erf_count(kn,r,rco)
          cn(i)=cn(i)+tmp
          cn(j)=cn(j)+tmp
       enddo
    enddo
Referenced by xtb_xtb_dispersion::init::initdispersion(), xtb_disp_ncoord::get_d4_cn::ncoord_d4_driver(), xtb_propertyoutput::print_molpol(), and xtb_scf::scf().
ncoord_d4_driver()
pure subroutine xtb_disp_ncoord::ncoord_d4_driver (type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:,:,:), intent(out), optional dcndr, real(wp), dimension(:,:,:), intent(out), optional dcndL, real(wp), intent(in), optional thr)
Parameters
[in] mol molecular structure information
[out] cn coordination number
[out] dcndr derivative of coordination number w.r.t. nuclear positions
[out] dcndl derivative of coordination number w.r.t. lattice vectors
[in] thr quadratic distance threshold for sum termination
Definition at line 241 of file ncoord.f90.
    use xtb_type_molecule
    implicit none
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out), optional :: dcndr(:,:,:)
    real(wp), intent(out), optional :: dcndL(:,:,:)
    real(wp), intent(in), optional :: thr
    real(wp) :: cn_thr
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    if (mol%npbc > 0) then
       if (present(dcndr).and.present(dcndl)) then
          call pbc_dncoord_d4(mol%n,mol%at,mol%xyz,mol%lattice,cn,dcndr,dcndl,cn_thr)
       else
          call pbc_ncoord_d4(mol%n,mol%at,mol%xyz,mol%lattice,cn,cn_thr)
       endif
    else
       if (present(dcndr)) then
          call dncoord_d4(mol%n,mol%at,mol%xyz,cn,dcndr,cn_thr)
       else
          call ncoord_d4(mol%n,mol%at,mol%xyz,cn,cn_thr)
       endif
    endif
ncoord_erf()
pure subroutine xtb_disp_ncoord::ncoord_erf (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
Definition at line 469 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, rr, r2, tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn = 0.0_wp
    do i = 1, nat
       do j = 1, i-1
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
 !        covalent distance in bohr
          rco=rcov(at(j)) + rcov(at(i))
 !        error function has an even better long range behavior
          tmp = erf_count(kn,r,rco)
          cn(i)=cn(i)+tmp
          cn(j)=cn(j)+tmp
       enddo
    enddo
Referenced by xtb_propertyoutput::main_freq(), xtb_disp_ncoord::get_erf_cn::ncoord_erf_driver(), xtb_main_setup::newwavefunction_(), print_geosum(), and xtb_prog_main::xtbmain().
ncoord_erf_driver()
pure subroutine xtb_disp_ncoord::ncoord_erf_driver (type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:,:,:), intent(out), optional dcndr, real(wp), dimension(:,:,:), intent(out), optional dcndL, real(wp), intent(in), optional thr)
Parameters
[in] mol molecular structure information
[out] cn coordination number
[out] dcndr derivative of coordination number w.r.t. nuclear positions
[out] dcndl derivative of coordination number w.r.t. lattice vectors
[in] thr quadratic distance threshold for sum termination
Definition at line 204 of file ncoord.f90.
    use xtb_type_molecule
    implicit none
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out), optional :: dcndr(:,:,:)
    real(wp), intent(out), optional :: dcndL(:,:,:)
    real(wp), intent(in), optional :: thr
    real(wp) :: cn_thr
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    if (mol%npbc > 0) then
       if (present(dcndr).and.present(dcndl)) then
          call pbc_derfcoord(mol%n,mol%at,mol%xyz,mol%lattice,cn,dcndr,dcndl,cn_thr)
       else
          call pbc_erfcoord(mol%n,mol%at,mol%xyz,mol%lattice,cn,cn_thr)
       endif
    else
       if (present(dcndr)) then
          call dncoord_erf(mol%n,mol%at,mol%xyz,cn,dcndr,cn_thr)
       else
          call ncoord_erf(mol%n,mol%at,mol%xyz,cn,cn_thr)
       endif
    endif
ncoord_gfn()
pure subroutine xtb_disp_ncoord::ncoord_gfn (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
Definition at line 843 of file ncoord.f90.
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i, j, ia, ja
    real(wp) :: r, r2, rij(3)
    real(wp) :: rcovij
    real(wp) :: expterm1, expterm2
    real(wp) :: tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0.0_wp
    do i = 1, nat
       ia = at(i)
       do j = 1, i-1
          ja = at(j)
          rij = xyz(:,j) - xyz(:,i)
          r2  = sum( rij**2 )
          if (r2.gt.cn_thr) cycle
          r = sqrt(r2)
          rcovij=(rcov(ia)+rcov(ja))
          expterm1=exp_count(ka,r,rcovij)
          expterm2=exp_count(kb,r,rcovij+r_shift)
          tmp = expterm1*expterm2
          cn(i) = cn(i) + tmp
          cn(j) = cn(j) + tmp
       enddo
    enddo
Referenced by xtb_iniq::iniqcn_gfn2(), xtb_disp_ncoord::get_gfn_cn::ncoord_gfn_driver(), and xtb_prog_main::xtbmain().
ncoord_gfn_driver()
pure subroutine xtb_disp_ncoord::ncoord_gfn_driver (type(tmolecule), intent(in) mol, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:,:,:), intent(out), optional dcndr, real(wp), intent(in), optional thr)
Parameters
[in] mol molecular structure information
[out] cn coordination number
[out] dcndr derivative of coordination number w.r.t. nuclear positions
[in] thr quadratic distance threshold for sum termination
Definition at line 171 of file ncoord.f90.
    use xtb_type_molecule
    implicit none
    type(TMolecule), intent(in) :: mol
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out), optional :: dcndr(:,:,:)
    real(wp), intent(in), optional :: thr
    real(wp) :: cn_thr
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
 !   if (mol%npbc > 0) then
 !      if (present(dcndr).and.present(dcndL)) then
 !      else
 !      endif
 !   else
       if (present(dcndr)) then
          call dncoord_gfn(mol%n,mol%at,mol%xyz,cn,dcndr,cn_thr)
       else
          call ncoord_gfn(mol%n,mol%at,mol%xyz,cn,cn_thr)
       endif
 !   endif
pbc_derfcoord()
pure subroutine xtb_disp_ncoord::pbc_derfcoord (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3,3), intent(in) lat, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), dimension(3,3,nat), intent(out) dcndL, real(wp), intent(in), optional thr)
Definition at line 1023 of file ncoord.f90.
    use xtb_mctc_constants
    use xtb_pbc_tools
    use xtb_pbc, only : get_realspace_cutoff
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(in)  :: lat(3,3)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(out) :: dcndL(3,3,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j,tx,ty,tz
    real(wp) :: rij(3), r, rco, den, rr, r2, t(3)
    integer  :: rep_cn(3)
    real(wp) :: tmp,dtmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    call get_realspace_cutoff(lat,cn_thr,rep_cn)
    cn = 0.0_wp
    dcndr = 0.0_wp
    dcndl = 0.0_wp
    do i = 1, nat
       do j = 1, i-1 ! loop over all atoms for PBC case
          do concurrent(tx = -rep_cn(1):rep_cn(1), &
                &       ty = -rep_cn(2):rep_cn(2), &
                &       tz = -rep_cn(3):rep_cn(3))
             t = tx*lat(:,1) + ty*lat(:,2) + tz*lat(:,3)
             rij = xyz(:,j) - xyz(:,i) + t
             r2  = sum(rij**2)
             if (r2.gt.cn_thr) cycle
             r=sqrt(r2)
 !           covalent distance in bohr
             rco=rcov(at(j)) + rcov(at(i))
             tmp=erf_count(kn,r,rco)
             dtmp = derf_count(kn,r,rco)
             cn(i)=cn(i) + tmp
             cn(j)=cn(j) + tmp
             dcndr(:,i,i)= dtmp*rij/r + dcndr(:,i,i)
             dcndr(:,j,j)=-dtmp*rij/r + dcndr(:,j,j)
             dcndr(:,i,j)= dtmp*rij/r + dcndr(:,i,j)
             dcndr(:,j,i)=-dtmp*rij/r + dcndr(:,j,i)
             dcndl(:,:,j)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,j)
             dcndl(:,:,i)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,i)
          enddo
       enddo
       do concurrent(tx = -rep_cn(1):rep_cn(1), &
             &       ty = -rep_cn(2):rep_cn(2), &
             &       tz = -rep_cn(3):rep_cn(3), &
             &       tx.ne.0 .or. ty.ne.0 .or. tz.ne.0)
          t = tx*lat(:,1) + ty*lat(:,2) + tz*lat(:,3)
          rij = t
          r2  = sum(rij**2)
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
 !        covalent distance in bohr
          rco=2*rcov(at(i))
          tmp=erf_count(kn,r,rco)
          dtmp = derf_count(kn,r,rco)
          cn(i)=cn(i) + tmp
          dcndl(:,:,i)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,i)
       enddo
    enddo
References cnthr, derf_count(), erf_count(), xtb_pbc::get_realspace_cutoff(), kn, xtb_pbc_tools::outer_prod_3x3(), and rcov.
Referenced by xtb_disp_ncoord::get_erf_cn::ncoord_erf_driver().
pbc_dncoord_d3()
pure subroutine xtb_disp_ncoord::pbc_dncoord_d3 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3,3), intent(in) lat, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), dimension(3,3,nat), intent(out) dcndL, real(wp), intent(in), optional thr)
Definition at line 379 of file ncoord.f90.
    use xtb_mctc_constants
    use xtb_pbc_tools
    use xtb_pbc, only : get_realspace_cutoff
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(in)  :: lat(3,3)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(out) :: dcndL(3,3,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j,tx,ty,tz
    real(wp) :: rij(3), r, rco, den, rr, r2, t(3)
    integer  :: rep_cn(3)
    real(wp) :: tmp,dtmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    call get_realspace_cutoff(lat,cn_thr,rep_cn)
    cn = 0.0_wp
    dcndr = 0.0_wp
    dcndl = 0.0_wp
    do i = 1, nat
       do j = 1, i-1 ! loop over all atoms for PBC case
          do concurrent(tx = -rep_cn(1):rep_cn(1), &
                &       ty = -rep_cn(2):rep_cn(2), &
                &       tz = -rep_cn(3):rep_cn(3))
             t = tx*lat(:,1) + ty*lat(:,2) + tz*lat(:,3)
             rij = xyz(:,j) - xyz(:,i) + t
             r2  = sum(rij**2)
             if (r2.gt.cn_thr) cycle
             r=sqrt(r2)
 !           covalent distance in bohr
             rco=rcov(at(j)) + rcov(at(i))
             tmp=exp_count(k1,r,rco)
             dtmp = dexp_count(k1,r,rco)
             cn(i)=cn(i) + tmp
             cn(j)=cn(j) + tmp
             dcndr(:,i,i)= dtmp*rij/r + dcndr(:,i,i)
             dcndr(:,j,j)=-dtmp*rij/r + dcndr(:,j,j)
             dcndr(:,i,j)= dtmp*rij/r + dcndr(:,i,j)
             dcndr(:,j,i)=-dtmp*rij/r + dcndr(:,j,i)
             dcndl(:,:,j)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,j)
             dcndl(:,:,i)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,i)
          enddo
       enddo
       do concurrent(tx = -rep_cn(1):rep_cn(1), &
             &       ty = -rep_cn(2):rep_cn(2), &
             &       tz = -rep_cn(3):rep_cn(3), &
             &       tx.ne.0 .or. ty.ne.0 .or. tz.ne.0)
          t = tx*lat(:,1) + ty*lat(:,2) + tz*lat(:,3)
          rij = t
          r2  = sum(rij**2)
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
 !        covalent distance in bohr
          rco=2*rcov(at(i))
          tmp=exp_count(k1,r,rco)
          dtmp = dexp_count(k1,r,rco)
          cn(i)=cn(i) + tmp
          dcndl(:,:,i)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,i)
       enddo
    enddo
References cnthr, dexp_count(), exp_count(), xtb_pbc::get_realspace_cutoff(), k1, xtb_pbc_tools::outer_prod_3x3(), and rcov.
pbc_dncoord_d4()
pure subroutine xtb_disp_ncoord::pbc_dncoord_d4 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3,3), intent(in) lat, real(wp), dimension(nat), intent(out) cn, real(wp), dimension(3,nat,nat), intent(out) dcndr, real(wp), dimension(3,3,nat), intent(out) dcndL, real(wp), intent(in), optional thr)
Definition at line 750 of file ncoord.f90.
    use xtb_mctc_constants
    use xtb_pbc_tools
    use xtb_pbc, only : get_realspace_cutoff
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer              :: rep_cn(3)
    integer              :: tx,ty,tz
    real(wp)             :: t(3)
    real(wp),intent(in)  :: lat(3,3)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(out) :: dcndr(3,nat,nat)
    real(wp),intent(out) :: dcndL(3,3,nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, r2, xn, tmp, dtmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0.0_wp
    dcndr = 0.0_wp
    dcndl = 0.0_wp
    call get_realspace_cutoff(lat,cn_thr,rep_cn)
    do i=1,nat
       do j=1,i-1
          do concurrent(tx = -rep_cn(1):rep_cn(1), &
                &       ty = -rep_cn(2):rep_cn(2), &
                &       tz = -rep_cn(3):rep_cn(3))
             t = [tx,ty,tz]
             rij = xyz(:,j) - xyz(:,i) + matmul(lat,t)
             r2  = sum(rij**2)
             if (r2.gt.cn_thr) cycle
             r=sqrt(r2)
             ! covalent distance in bohr
             rco=rcov(at(j)) + rcov(at(i))
             den=k4*exp(-(abs((en(at(i))-en(at(j))))+ k5)**2/k6 )
             tmp = den * erf_count(kn,r,rco)
             dtmp = den * derf_count(kn,r,rco)
             cn(i)=cn(i)+tmp
             cn(j)=cn(j)+tmp
             dcndr(:,i,i)=-dtmp*rij/r + dcndr(:,i,i)
             dcndr(:,j,j)= dtmp*rij/r + dcndr(:,j,j)
             dcndr(:,i,j)=-dtmp*rij/r + dcndr(:,i,j)
             dcndr(:,j,i)= dtmp*rij/r + dcndr(:,j,i)
             dcndl(:,:,j)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,j)
             dcndl(:,:,i)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,i)
          enddo
       enddo
       do concurrent(tx = -rep_cn(1):rep_cn(1), &
             &       ty = -rep_cn(2):rep_cn(2), &
             &       tz = -rep_cn(3):rep_cn(3))
          ! avoid self interaction
          if ((tx.eq.0).and.(ty.eq.0).and.(tz.eq.0)) cycle
          t = [tx,ty,tz]
          rij = matmul(lat,t)
          r2  = sum(rij**2)
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
          ! covalent distance in bohr
          rco=2*rcov(at(i))
          den=k4*exp(-k5**2/k6)
          tmp = den * erf_count(kn,r,rco)
          dtmp = den * derf_count(kn,r,rco)
          cn(i)=cn(i)+tmp
          dcndl(:,:,i)= dtmp*outer_prod_3x3(rij,rij)/r + dcndl(:,:,i)
       enddo
    enddo
Referenced by xtb_disp_ncoord::get_d4_cn::ncoord_d4_driver().
pbc_erfcoord()
pure subroutine xtb_disp_ncoord::pbc_erfcoord (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3,3), intent(in) lat, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
Definition at line 955 of file ncoord.f90.
    use xtb_pbc, only : get_realspace_cutoff
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    real(wp),intent(in)  :: lat(3,3)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j,tx,ty,tz
    real(wp) :: rij(3), r, rco, den, rr, r2, t(3)
    integer  :: rep_cn(3)
    real(wp) :: tmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    call get_realspace_cutoff(lat,cn_thr,rep_cn)
    cn = 0.0_wp
    do i = 1, nat
       do j = 1, i-1 ! loop over all atoms for PBC case
          do concurrent(tx = -rep_cn(1):rep_cn(1), &
                &       ty = -rep_cn(2):rep_cn(2), &
                &       tz = -rep_cn(3):rep_cn(3))
             ! avoid self interaction
             if ((j.eq.i).and.(tx.eq.0).and.(ty.eq.0).and.(tz.eq.0)) cycle
             t = tx*lat(:,1) + ty*lat(:,2) + tz*lat(:,3)
             rij = xyz(:,j) - xyz(:,i) + t
             r2  = sum(rij**2)
             if (r2.gt.cn_thr) cycle
             r=sqrt(r2)
 !           covalent distance in bohr
             rco=rcov(at(j)) + rcov(at(i))
             tmp=erf_count(kn,r,rco)
             cn(i)=cn(i) + tmp
             cn(j)=cn(j) + tmp
          enddo
       enddo
       do concurrent(tx = -rep_cn(1):rep_cn(1), &
             &       ty = -rep_cn(2):rep_cn(2), &
             &       tz = -rep_cn(3):rep_cn(3), &
             &       tx.ne.0 .or. ty.ne.0 .or. tz.ne.0)
          t = tx*lat(:,1) + ty*lat(:,2) + tz*lat(:,3)
          rij = t
          r2  = sum(rij**2)
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
 !        covalent distance in bohr
          rco=2*rcov(at(i))
          tmp=erf_count(kn,r,rco)
          cn(i)=cn(i) + tmp
       enddo
    enddo
References cnthr, erf_count(), xtb_pbc::get_realspace_cutoff(), kn, and rcov.
Referenced by xtb_disp_ncoord::get_erf_cn::ncoord_erf_driver().
pbc_ncoord_d4()
pure subroutine xtb_disp_ncoord::pbc_ncoord_d4 (integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(3,3), intent(in) lat, real(wp), dimension(nat), intent(out) cn, real(wp), intent(in), optional thr)
Definition at line 682 of file ncoord.f90.
    use xtb_mctc_constants
    use xtb_pbc_tools
    use xtb_pbc, only : get_realspace_cutoff
    implicit none
    integer, intent(in)  :: nat
    integer, intent(in)  :: at(nat)
    real(wp),intent(in)  :: xyz(3,nat)
    integer              :: rep_cn(3)
    integer              :: tx,ty,tz
    real(wp)             :: t(3)
    real(wp),intent(in)  :: lat(3,3)
    real(wp),intent(out) :: cn(nat)
    real(wp),intent(in),optional :: thr
    real(wp) :: cn_thr
    integer  :: i,j
    real(wp) :: rij(3), r, rco, den, r2, xn, tmp, dtmp
    if (present(thr)) then
       cn_thr = thr
    else
       cn_thr = cnthr
    endif
    cn  = 0.0_wp
    call get_realspace_cutoff(lat,cn_thr,rep_cn)
    do i=1,nat
       do j=1,i-1
          do concurrent(tx = -rep_cn(1):rep_cn(1), &
                &       ty = -rep_cn(2):rep_cn(2), &
                &       tz = -rep_cn(3):rep_cn(3))
             t = [tx,ty,tz]
             rij = xyz(:,j) - xyz(:,i) + matmul(lat,t)
             r2  = sum(rij**2)
             if (r2.gt.cn_thr) cycle
             r=sqrt(r2)
             ! covalent distance in bohr
             rco=rcov(at(j)) + rcov(at(i))
             den=k4*exp(-(abs((en(at(i))-en(at(j))))+ k5)**2/k6 )
             tmp = den * erf_count(kn,r,rco)
             cn(i)=cn(i)+tmp
             cn(j)=cn(j)+tmp
          enddo
       enddo
       do concurrent(tx = -rep_cn(1):rep_cn(1), &
             &       ty = -rep_cn(2):rep_cn(2), &
             &       tz = -rep_cn(3):rep_cn(3), &
             &       tx.ne.0 .or. ty.ne.0 .or. tz.ne.0)
          t = [tx,ty,tz]
          rij = matmul(lat,t)
          r2  = sum(rij**2)
          if (r2.gt.cn_thr) cycle
          r=sqrt(r2)
          ! covalent distance in bohr
          rco=2*rcov(at(i))
          den=k4*exp(-k5**2/k6 )
          tmp = den * erf_count(kn,r,rco)
          cn(i)=cn(i)+tmp
       enddo
    enddo
Referenced by xtb_disp_ncoord::get_d4_cn::ncoord_d4_driver().
Variable Documentation
cnthr
real(wp), parameter, private xtb_disp_ncoord::cnthr = 1600.0_wp private
Definition at line 46 of file ncoord.f90.
    real(wp),private,parameter :: cnthr = 1600.0_wp
Referenced by xtb_disp_ncoord::get_d3_cn::dncoord_d3(), xtb_disp_ncoord::get_d4_cn::dncoord_d4(), xtb_disp_ncoord::get_erf_cn::dncoord_erf(), xtb_disp_ncoord::get_gfn_cn::dncoord_gfn(), xtb_disp_ncoord::get_d3_cn::ncoord_d3(), xtb_disp_ncoord::get_d3_cn::ncoord_d3_driver(), xtb_disp_ncoord::get_d4_cn::ncoord_d4(), xtb_disp_ncoord::get_d4_cn::ncoord_d4_driver(), xtb_disp_ncoord::get_erf_cn::ncoord_erf(), xtb_disp_ncoord::get_erf_cn::ncoord_erf_driver(), xtb_disp_ncoord::get_gfn_cn::ncoord_gfn(), xtb_disp_ncoord::get_gfn_cn::ncoord_gfn_driver(), pbc_derfcoord(), pbc_dncoord_d3(), xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4(), pbc_erfcoord(), and xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4().
en
real(wp), dimension(max_elem), parameter xtb_disp_ncoord::en = (/ 2.20,3.00, 0.98,1.57,2.04,2.55,3.04,3.44,3.98,4.50, 0.93,1.31,1.61,1.90,2.19,2.58,3.16,3.50, 0.82,1.00, 1.36,1.54,1.63,1.66,1.55,1.83,1.88,1.91,1.90,1.65, 1.81,2.01,2.18,2.55,2.96,3.00, 0.82,0.95, 1.22,1.33,1.60,2.16,1.90,2.20,2.28,2.20,1.93,1.69, 1.78,1.96,2.05,2.10,2.66,2.60, 0.79,0.89, 1.10,1.12,1.13,1.14,1.15,1.17,1.18, 1.20,1.21,1.22,1.23,1.24,1.25,1.26, 1.27,1.30,1.50,2.36,1.90,2.20,2.20,2.28,2.54,2.00, 1.62,2.33,2.02,2.00,2.20,2.20, 1.50,1.50, 1.50,1.50,1.50,1.50,1.50,1.50,1.50, 1.50,1.50,1.50,1.50,1.50,1.50,1.50, 1.50,1.50,1.50,1.50,1.50,1.50,1.50,1.50,1.50,1.50, 1.50,1.50,1.50,1.50,1.50,1.50 /)
Definition at line 90 of file ncoord.f90.
    real(wp),parameter :: en(max_elem) = (/ &
    & 2.20,3.00, & ! H,He
    & 0.98,1.57,2.04,2.55,3.04,3.44,3.98,4.50, & ! Li-Ne
    & 0.93,1.31,1.61,1.90,2.19,2.58,3.16,3.50, & ! Na-Ar
    & 0.82,1.00, & ! K,Ca
    &           1.36,1.54,1.63,1.66,1.55,1.83,1.88,1.91,1.90,1.65, & ! Sc-Zn
    &           1.81,2.01,2.18,2.55,2.96,3.00, & ! Ga-Kr
    & 0.82,0.95, & ! Rb,Sr
    &           1.22,1.33,1.60,2.16,1.90,2.20,2.28,2.20,1.93,1.69, & ! Y-Cd
    &           1.78,1.96,2.05,2.10,2.66,2.60, & ! In-Xe
    & 0.79,0.89, & ! Cs,Ba
    &      1.10,1.12,1.13,1.14,1.15,1.17,1.18, & ! La-Eu
    &      1.20,1.21,1.22,1.23,1.24,1.25,1.26, & ! Gd-Yb
    &           1.27,1.30,1.50,2.36,1.90,2.20,2.20,2.28,2.54,2.00, & ! Lu-Hg
    &           1.62,2.33,2.02,2.00,2.20,2.20, & ! Tl-Rn
    ! only dummies below
    & 1.50,1.50, & ! Fr,Ra
    &      1.50,1.50,1.50,1.50,1.50,1.50,1.50, & ! Ac-Am
    &      1.50,1.50,1.50,1.50,1.50,1.50,1.50, & ! Cm-No
    &           1.50,1.50,1.50,1.50,1.50,1.50,1.50,1.50,1.50,1.50, & ! Rf-Cn
    &           1.50,1.50,1.50,1.50,1.50,1.50 /) ! Nh-Og
Referenced by xtb_disp_ncoord::get_d4_cn::dncoord_d4(), xtb_disp_ncoord::get_d4_cn::ncoord_d4(), xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4(), and xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4().
k1
real(wp), parameter xtb_disp_ncoord::k1 = 16.0_wp
Definition at line 48 of file ncoord.f90.
    real(wp),parameter :: k1 = 16.0_wp
Referenced by xtb_disp_ncoord::get_d3_cn::dncoord_d3(), xtb_disp_ncoord::get_d3_cn::ncoord_d3(), and pbc_dncoord_d3().
k2
real(wp), parameter xtb_disp_ncoord::k2 = 4.0_wp/3.0_wp
Definition at line 49 of file ncoord.f90.
    real(wp),parameter :: k2 = 4.0_wp/3.0_wp
k4
real(wp), parameter xtb_disp_ncoord::k4 =4.10451_wp
Definition at line 55 of file ncoord.f90.
    real(wp),parameter :: k4=4.10451_wp
Referenced by xtb_disp_ncoord::get_d4_cn::dncoord_d4(), xtb_disp_ncoord::get_d4_cn::ncoord_d4(), xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4(), and xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4().
k5
real(wp), parameter xtb_disp_ncoord::k5 =19.08857_wp
Definition at line 56 of file ncoord.f90.
    real(wp),parameter :: k5=19.08857_wp
Referenced by xtb_disp_ncoord::get_d4_cn::dncoord_d4(), xtb_disp_ncoord::get_d4_cn::ncoord_d4(), xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4(), and xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4().
k6
real(wp), parameter xtb_disp_ncoord::k6 =2*11.28174_wp**2
Definition at line 57 of file ncoord.f90.
    real(wp),parameter :: k6=2*11.28174_wp**2
Referenced by xtb_disp_ncoord::get_d4_cn::dncoord_d4(), xtb_disp_ncoord::get_d4_cn::ncoord_d4(), xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4(), and xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4().
ka
real(wp), parameter xtb_disp_ncoord::ka =10.0_wp
Definition at line 51 of file ncoord.f90.
    real(wp),parameter :: ka=10.0_wp
Referenced by xtb_disp_ncoord::get_gfn_cn::dncoord_gfn(), and xtb_disp_ncoord::get_gfn_cn::ncoord_gfn().
kb
real(wp), parameter xtb_disp_ncoord::kb =20.0_wp
Definition at line 52 of file ncoord.f90.
    real(wp),parameter :: kb=20.0_wp
Referenced by xtb_disp_ncoord::get_gfn_cn::dncoord_gfn(), and xtb_disp_ncoord::get_gfn_cn::ncoord_gfn().
ke
real(wp), parameter xtb_disp_ncoord::ke =0.05_wp
Definition at line 61 of file ncoord.f90.
    real(wp),parameter :: ke=0.05_wp
kn
real(wp), parameter xtb_disp_ncoord::kn =7.50_wp
Definition at line 59 of file ncoord.f90.
    real(wp),parameter :: kn=7.50_wp
Referenced by xtb_disp_ncoord::get_d4_cn::dncoord_d4(), xtb_disp_ncoord::get_erf_cn::dncoord_erf(), xtb_disp_ncoord::get_d4_cn::ncoord_d4(), xtb_disp_ncoord::get_erf_cn::ncoord_erf(), pbc_derfcoord(), xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4(), pbc_erfcoord(), and xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4().
kr
real(wp), parameter xtb_disp_ncoord::kr =0.25_wp
Definition at line 60 of file ncoord.f90.
    real(wp),parameter :: kr=0.25_wp
max_elem
integer, parameter, private xtb_disp_ncoord::max_elem = 118 private
Definition at line 63 of file ncoord.f90.
    integer,private,parameter :: max_elem = 118
r_shift
real(wp), parameter xtb_disp_ncoord::r_shift =2.0_wp
Definition at line 53 of file ncoord.f90.
    real(wp),parameter :: r_shift=2.0_wp
Referenced by xtb_disp_ncoord::get_gfn_cn::dncoord_gfn(), and xtb_disp_ncoord::get_gfn_cn::ncoord_gfn().
rad
real(wp), dimension(max_elem), parameter, private xtb_disp_ncoord::rad = (/ 0.32,0.46, 1.20,0.94,0.77,0.75,0.71,0.63,0.64,0.67, 1.40,1.25,1.13,1.04,1.10,1.02,0.99,0.96, 1.76,1.54, 1.33,1.22,1.21,1.10,1.07,1.04,1.00,0.99,1.01,1.09, 1.12,1.09,1.15,1.10,1.14,1.17, 1.89,1.67, 1.47,1.39,1.32,1.24,1.15,1.13,1.13,1.08,1.15,1.23, 1.28,1.26,1.26,1.23,1.32,1.31, 2.09,1.76, 1.62,1.47,1.58,1.57,1.56,1.55,1.51, 1.52,1.51,1.50,1.49,1.49,1.48,1.53, 1.46,1.37,1.31,1.23,1.18,1.16,1.11,1.12,1.13,1.32, 1.30,1.30,1.36,1.31,1.38,1.42, 2.01,1.81, 1.67,1.58,1.52,1.53,1.54,1.55,1.49, 1.49,1.51,1.51,1.48,1.50,1.56,1.58, 1.45,1.41,1.34,1.29,1.27,1.21,1.16,1.15,1.09,1.22, 1.22,1.29,1.46,1.58,1.48,1.41 /) private
Definition at line 67 of file ncoord.f90.
    real(wp),private,parameter :: rad(max_elem) = (/  &
    & 0.32,0.46, & ! H,He
    & 1.20,0.94,0.77,0.75,0.71,0.63,0.64,0.67, & ! Li-Ne
    & 1.40,1.25,1.13,1.04,1.10,1.02,0.99,0.96, & ! Na-Ar
    & 1.76,1.54, & ! K,Ca
    &           1.33,1.22,1.21,1.10,1.07,1.04,1.00,0.99,1.01,1.09, & ! Sc-Zn
    &           1.12,1.09,1.15,1.10,1.14,1.17, & ! Ga-Kr
    & 1.89,1.67, & ! Rb,Sr
    &           1.47,1.39,1.32,1.24,1.15,1.13,1.13,1.08,1.15,1.23, & ! Y-Cd
    &           1.28,1.26,1.26,1.23,1.32,1.31, & ! In-Xe
    & 2.09,1.76, & ! Cs,Ba
    &      1.62,1.47,1.58,1.57,1.56,1.55,1.51, & ! La-Eu
    &      1.52,1.51,1.50,1.49,1.49,1.48,1.53, & ! Gd-Yb
    &           1.46,1.37,1.31,1.23,1.18,1.16,1.11,1.12,1.13,1.32, & ! Lu-Hg
    &           1.30,1.30,1.36,1.31,1.38,1.42, & ! Tl-Rn
    & 2.01,1.81, & ! Fr,Ra
    &      1.67,1.58,1.52,1.53,1.54,1.55,1.49, & ! Ac-Am
    &      1.49,1.51,1.51,1.48,1.50,1.56,1.58, & ! Cm-No
    &           1.45,1.41,1.34,1.29,1.27,1.21,1.16,1.15,1.09,1.22, & ! Lr-Cn
    &           1.22,1.29,1.46,1.58,1.48,1.41 /) ! Nh-Og
rcov
real(wp), dimension(max_elem), parameter xtb_disp_ncoord::rcov = 4.0_wp/3.0_wp*rad/0.52917726_wp
Definition at line 87 of file ncoord.f90.
    real(wp),parameter :: rcov(max_elem) = 4.0_wp/3.0_wp*rad/0.52917726_wp
Referenced by xtb_disp_ncoord::get_d3_cn::dncoord_d3(), xtb_disp_ncoord::get_d4_cn::dncoord_d4(), xtb_disp_ncoord::get_erf_cn::dncoord_erf(), xtb_disp_ncoord::get_gfn_cn::dncoord_gfn(), xtb_disp_ncoord::get_d3_cn::ncoord_d3(), xtb_disp_ncoord::get_d4_cn::ncoord_d4(), xtb_disp_ncoord::get_erf_cn::ncoord_erf(), xtb_disp_ncoord::get_gfn_cn::ncoord_gfn(), pbc_derfcoord(), pbc_dncoord_d3(), xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4(), pbc_erfcoord(), and xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4().