My Project: xtb_gfnff_mrec Module Reference
xtb_gfnff_mrec Module Reference
Functions/Subroutines
subroutine, public mrecgff (nat, nb, molcount, molvec)
recursive subroutine mrecgff2 (nb, i, taken, nat, bond, molvec, molcnt)
Function/Subroutine Documentation
mrecgff()
subroutine, public xtb_gfnff_mrec::mrecgff (integer nat, integer, dimension(20,nat) nb, integer molcount, integer, dimension(nat) molvec)
Definition at line 22 of file mrec.f90.
       ! molcount: number of total fragments (increased during search)
       ! nat: overall number of atoms
       ! molvec: assignment vector of atom to fragment
       implicit none
       integer nat,molvec(nat),i,j,molcount,nb(20,nat)
       real*8, allocatable:: bond(:,:)
       logical,allocatable:: taken(:)
       allocate(taken(nat),bond(nat,nat))
       bond=0
       do i=1,nat
          do j=1,nb(20,i)
             bond(i,nb(j,i))=1
             bond(nb(j,i),i)=1
          enddo
       enddo
       molvec=0
       molcount=1
       taken=.false.
       do i=1,nat
        if(.not.taken(i)) then
          molvec(i)=molcount
          taken(i)=.true.
          call mrecgff2(nb,i,taken,nat,bond,molvec,molcount)
          molcount=molcount+1
       endif
       enddo
       molcount=molcount-1
References mrecgff2(), and true().
Referenced by xtb_gfnff_fraghess::fragmentize(), and xtb_gfnff_ini::gfnff_ini().
mrecgff2()
recursive subroutine xtb_gfnff_mrec::mrecgff2 (integer, dimension(20,nat) nb, integer i, logical, dimension(nat) taken, integer nat, real*8, dimension(nat,nat) bond, integer, dimension(nat) molvec, integer molcnt) private
Definition at line 53 of file mrec.f90.
       implicit none
       integer i,nat, molcnt,molvec(nat),j,icn,k,nb(20,nat)
       real*8 bond(nat,nat)
       logical taken(nat)
       icn=nb(20,i)
       do k=1,icn
          j=maxloc(bond(:,i),1)
          bond(j,i)=0
          if (i .eq. j) cycle
          if (.not.taken(j)) then
             molvec(j)=molcnt
             taken(j)=.true.
             call mrecgff2(nb,j,taken,nat,bond,molvec,molcnt)
          endif
       enddo
References true().
Referenced by mrecgff().