My Project: xtb_api_environment Module Reference
xtb_api_environment Module Reference
API for dealing with the calculation environment.
Data Types
type venvironment
Void pointer to calculation environment.
Functions/Subroutines
type(c_ptr) function, public newenvironment_api ()
Create new xtb calculation environment object.
subroutine, public delenvironment_api (venv)
Delete a xtb calculation environment object.
integer(c_int) function, public checkenvironment_api (venv)
Check current status of calculation environment.
subroutine, public showenvironment_api (venv, charptr)
Show and empty error stack.
subroutine, public setoutput_api (venv, charptr)
Bind output from this environment.
subroutine, public releaseoutput_api (venv)
Release output unit from this environment.
subroutine, public setverbosity_api (venv, verbosity)
Set verbosity of calculation output.
subroutine, public geterror_api (venv, charptr, buffersize)
Set verbosity of calculation output.
Detailed Description
API for dealing with the calculation environment.
Function/Subroutine Documentation
checkenvironment_api()
integer(c_int) function, public xtb_api_environment::checkenvironment_api (type(c_ptr), value venv)
Check current status of calculation environment.
Definition at line 80 of file environment.f90.
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    integer(c_int) :: status
    logical :: exitRun
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       call env%ptr%check(exitrun)
       if (exitrun) then
          status = 1
       else
          status = 0
       end if
    end if
References xtb_api_utils::checkglobalenv().
delenvironment_api()
subroutine, public xtb_api_environment::delenvironment_api (type(c_ptr), intent(inout) venv)
Delete a xtb calculation environment object.
Definition at line 62 of file environment.f90.
    type(c_ptr), intent(inout) :: venv
    type(VEnvironment), pointer :: env
    call releaseoutput_api(venv)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       deallocate(env)
       venv = c_null_ptr
    end if
References xtb_api_utils::checkglobalenv(), and releaseoutput_api().
geterror_api()
subroutine, public xtb_api_environment::geterror_api (type(c_ptr), value venv, character(kind=c_char), dimension(*), intent(inout) charptr, integer(c_int), intent(in), optional buffersize)
Set verbosity of calculation output.
Definition at line 207 of file environment.f90.
    character(len=*), parameter :: source = 'xtb_api_getError'
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    character(kind=c_char), intent(inout) :: charptr(*)
    character(len=:, kind=c_char), allocatable :: buffer
    integer(c_int), intent(in), optional :: buffersize
    logical :: exitRun
    integer :: maxLength
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (present(buffersize)) then
          maxlength = buffersize
       else
          maxlength = huge(maxlength) - 2
       end if
       call env%ptr%check(exitrun)
       if (exitrun) then
          call env%ptr%getLog(buffer)
          if (len(buffer) > 0) then
             call f_c_character(buffer, charptr, maxlength)
          end if
       end if
    end if
References xtb_api_utils::checkglobalenv(), and xtb_api_utils::f_c_character().
newenvironment_api()
type(c_ptr) function, public xtb_api_environment::newenvironment_api
Create new xtb calculation environment object.
Definition at line 46 of file environment.f90.
    type(VEnvironment), pointer :: env
    type(c_ptr) :: venv
    call checkglobalenv
    allocate(env)
    call init(env%ptr)
    env%verbosity = 1
    venv = c_loc(env)
References xtb_api_utils::checkglobalenv().
releaseoutput_api()
subroutine, public xtb_api_environment::releaseoutput_api (type(c_ptr), value venv)
Release output unit from this environment.
Definition at line 161 of file environment.f90.
    character(len=*), parameter :: source = 'xtb_api_releaseOutput'
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    integer :: stat
    character(len=512) :: message
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.any(env%ptr%unit /= [-1, stdout, stderr])) then
          close(unit=env%ptr%unit, iostat=stat, iomsg=message)
          if (stat /= 0) then
             call env%ptr%error(trim(message), source)
          end if
       end if
    end if
References xtb_api_utils::checkglobalenv().
Referenced by delenvironment_api(), and setoutput_api().
setoutput_api()
subroutine, public xtb_api_environment::setoutput_api (type(c_ptr), value venv, character(kind=c_char), dimension(*), intent(in) charptr)
Bind output from this environment.
Definition at line 127 of file environment.f90.
    character(len=*), parameter :: source = 'xtb_api_setOutput'
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    character(kind=c_char), intent(in) :: charptr(*)
    character(len=:, kind=c_char), allocatable :: filename
    integer :: stat
    character(len=512) :: message
    call c_f_character(charptr, filename)
    call releaseoutput_api(venv)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (filename == c_char_'-' .or. filename == c_char_'STDOUT') then
          env%ptr%unit = stdout
       else if (filename == c_char_'STDERR') then
          env%ptr%unit = stderr
       else
          open(file=filename, newunit=env%ptr%unit, iostat=stat, iomsg=message)
          if (stat /= 0) then
             call env%ptr%error(trim(message), source)
          end if
       end if
    end if
References xtb_api_utils::c_f_character(), xtb_api_utils::checkglobalenv(), and releaseoutput_api().
setverbosity_api()
subroutine, public xtb_api_environment::setverbosity_api (type(c_ptr), value venv, integer, value verbosity)
Set verbosity of calculation output.
Definition at line 185 of file environment.f90.
    character(len=*), parameter :: source = 'xtb_api_setVerbosity'
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    integer, value :: verbosity
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.any(verbosity /= [0_c_int, 1_c_int, 2_c_int])) then
          call env%ptr%warning("Verbosity specified is out of range", source)
       end if
       env%verbosity = verbosity
    end if
References xtb_api_utils::checkglobalenv().
showenvironment_api()
subroutine, public xtb_api_environment::showenvironment_api (type(c_ptr), value venv, character(kind=c_char), dimension(*), intent(in), optional charptr)
Show and empty error stack.
Definition at line 103 of file environment.f90.
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    character(kind=c_char), intent(in), optional :: charptr(*)
    character(len=:, kind=c_char), allocatable :: message
    if (present(charptr)) then
       call c_f_character(charptr, message)
    else
       message = ''
    end if
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       call env%ptr%show(message)
    end if
References xtb_api_utils::c_f_character(), and xtb_api_utils::checkglobalenv().