My Project: xtb_aoparam Module Reference
xtb_aoparam Module Reference
Data Types
type tb_parameter
Variables
integer, parameter, public max_elem = 118
integer, parameter, public max_sh = 10
character, parameter flag = '$'
character, parameter space = ' '
character, parameter equal = '='
character, parameter hash = '#'
character, parameter dot = '.'
character(len= *), parameter flag_end = '$end'
real(wp), dimension(max_elem), public en = pauling_en
real(wp), dimension(max_elem), public mc
real(wp), dimension(max_elem), public rad = covalent_radius_2010 * autoaa
real(wp), dimension(max_elem), public gam = chemical_hardness
real(wp), dimension(max_elem), public gam3
real(wp), dimension(max_elem), public alp0
real(wp), dimension(max_elem, 10), public wll
real(wp), dimension(2, max_elem), public rep
real(wp), dimension(4, max_elem), public polyr
real(wp), dimension(max_elem), public cxb
real(wp), dimension(max_elem), public eeqkcn
real(wp), dimension(max_elem), public kqat2
real(wp), dimension(10, max_elem), public ao_exp
real(wp), dimension(10, max_elem), public ao_lev
real(wp), dimension(0:2, max_elem), public lpar
real(wp), dimension(max_elem, max_elem), public kpair
real(wp), dimension(0:2, max_elem), public kcnat
real(wp), dimension(3, max_elem), public kqat
real(wp), dimension(max_elem), public radaes = covalent_radius_d3
real(wp), dimension(max_elem), public eeqen
real(wp), dimension(max_elem), public dpolc
real(wp), dimension(max_elem), public qpolc
integer, dimension(10, max_elem), public ao_pqn
integer, dimension(10, max_elem), public ao_l
integer, dimension(max_elem), public ao_n
integer, dimension(10, max_elem), public ao_typ
integer, dimension(max_elem), public metal
integer, dimension(max_elem), public cnval
character(len=30), dimension(max_elem), public timestp
Variable Documentation
alp0
real(wp), dimension(max_elem), public xtb_aoparam::alp0
Definition at line 69 of file aoparam.f90.
    real(wp), public :: alp0(max_elem)
ao_exp
real(wp), dimension(10,max_elem), public xtb_aoparam::ao_exp
Definition at line 76 of file aoparam.f90.
    real(wp), public :: ao_exp(10,max_elem)
Referenced by gfn0_prparam(), gfn1_prparam(), and gfn2_prparam().
ao_l
integer, dimension(10,max_elem), public xtb_aoparam::ao_l
Definition at line 87 of file aoparam.f90.
    integer, public  :: ao_l(10,max_elem)
Referenced by gfn0_prparam(), gfn1_prparam(), and gfn2_prparam().
ao_lev
real(wp), dimension(10,max_elem), public xtb_aoparam::ao_lev
Definition at line 77 of file aoparam.f90.
    real(wp), public :: ao_lev(10,max_elem)
Referenced by gfn0_prparam(), gfn1_prparam(), and gfn2_prparam().
ao_n
integer, dimension(max_elem), public xtb_aoparam::ao_n
Definition at line 88 of file aoparam.f90.
    integer, public  :: ao_n(max_elem)
Referenced by gfn0_prparam(), gfn1_prparam(), and gfn2_prparam().
ao_pqn
integer, dimension(10,max_elem), public xtb_aoparam::ao_pqn
Definition at line 86 of file aoparam.f90.
    integer, public  :: ao_pqn(10,max_elem)
Referenced by gfn0_prparam(), gfn1_prparam(), and gfn2_prparam().
ao_typ
integer, dimension(10,max_elem), public xtb_aoparam::ao_typ
Definition at line 89 of file aoparam.f90.
    integer, public  :: ao_typ(10,max_elem)
cnval
integer, dimension(max_elem), public xtb_aoparam::cnval
Definition at line 91 of file aoparam.f90.
    integer, public  :: cnval(max_elem)
cxb
real(wp), dimension(max_elem), public xtb_aoparam::cxb
Definition at line 73 of file aoparam.f90.
    real(wp), public :: cxb(max_elem)
dot
character, parameter xtb_aoparam::dot = '.' private
Definition at line 61 of file aoparam.f90.
    character, parameter :: dot = '.'
Referenced by rotate_atom(), and rotate_reflect_atom().
dpolc
real(wp), dimension(max_elem), public xtb_aoparam::dpolc
Definition at line 84 of file aoparam.f90.
    real(wp), public :: dpolc(max_elem)
eeqen
real(wp), dimension(max_elem), public xtb_aoparam::eeqen
Definition at line 83 of file aoparam.f90.
    real(wp), public :: eeqEN(max_elem)
eeqkcn
real(wp), dimension(max_elem), public xtb_aoparam::eeqkcn
Definition at line 74 of file aoparam.f90.
    real(wp), public :: eeqkcn(max_elem)
en
real(wp), dimension(max_elem), public xtb_aoparam::en = pauling_en
Definition at line 64 of file aoparam.f90.
    real(wp), public :: en(max_elem) = pauling_en
Referenced by gfn0_prparam(), gfn1_prparam(), and gfn2_prparam().
equal
character, parameter xtb_aoparam::equal = '=' private
Definition at line 59 of file aoparam.f90.
    character, parameter :: equal = '='
flag
character, parameter xtb_aoparam::flag = '$'
Definition at line 57 of file aoparam.f90.
    character, parameter :: flag = '$'
flag_end
character(len=*), parameter xtb_aoparam::flag_end = '$end' private
Definition at line 62 of file aoparam.f90.
    character(len=*), parameter :: flag_end = '$end'
gam
real(wp), dimension(max_elem), public xtb_aoparam::gam = chemical_hardness
Definition at line 67 of file aoparam.f90.
    real(wp), public :: gam(max_elem) = chemical_hardness
Referenced by gfn0_prparam(), gfn1_prparam(), and gfn2_prparam().
gam3
real(wp), dimension(max_elem), public xtb_aoparam::gam3
Definition at line 68 of file aoparam.f90.
    real(wp), public :: gam3(max_elem)
Referenced by gfn0_prparam(), gfn1_prparam(), and gfn2_prparam().
hash
character, parameter xtb_aoparam::hash = '#' private
Definition at line 60 of file aoparam.f90.
    character, parameter :: hash = '#'
kcnat
real(wp), dimension(0:2,max_elem), public xtb_aoparam::kcnat
Definition at line 80 of file aoparam.f90.
    real(wp), public :: kcnat(0:2,max_elem)
kpair
real(wp), dimension(max_elem,max_elem), public xtb_aoparam::kpair
Definition at line 79 of file aoparam.f90.
    real(wp), public :: kpair(max_elem,max_elem)
Referenced by xtb_paramset::use_parameterset().
kqat
real(wp), dimension(3,max_elem), public xtb_aoparam::kqat
Definition at line 81 of file aoparam.f90.
    real(wp), public :: kqat(3,max_elem)
kqat2
real(wp), dimension(max_elem), public xtb_aoparam::kqat2
Definition at line 75 of file aoparam.f90.
    real(wp), public :: kqat2(max_elem)
lpar
real(wp), dimension(0:2,max_elem), public xtb_aoparam::lpar
Definition at line 78 of file aoparam.f90.
    real(wp), public :: lpar(0:2,max_elem)
max_elem
integer, parameter, public xtb_aoparam::max_elem = 118
Definition at line 27 of file aoparam.f90.
    integer, public, parameter :: max_elem = 118
max_sh
integer, parameter, public xtb_aoparam::max_sh = 10
Definition at line 28 of file aoparam.f90.
    integer, public, parameter :: max_sh = 10
mc
real(wp), dimension(max_elem), public xtb_aoparam::mc
Definition at line 65 of file aoparam.f90.
    real(wp), public :: mc(max_elem)
metal
integer, dimension(max_elem), public xtb_aoparam::metal
Definition at line 90 of file aoparam.f90.
    integer, public  :: metal(max_elem)
polyr
real(wp), dimension(4,max_elem), public xtb_aoparam::polyr
Definition at line 72 of file aoparam.f90.
    real(wp), public :: polyr(4,max_elem)
qpolc
real(wp), dimension(max_elem), public xtb_aoparam::qpolc
Definition at line 85 of file aoparam.f90.
    real(wp), public :: qpolc(max_elem)
rad
real(wp), dimension(max_elem), public xtb_aoparam::rad = covalent_radius_2010 * autoaa
Definition at line 66 of file aoparam.f90.
    real(wp), public :: rad(max_elem) = covalent_radius_2010 * autoaa
radaes
real(wp), dimension(max_elem), public xtb_aoparam::radaes = covalent_radius_d3
Definition at line 82 of file aoparam.f90.
    real(wp), public :: radaes(max_elem) = covalent_radius_d3
Referenced by gfn2_prparam().
rep
real(wp), dimension(2,max_elem), public xtb_aoparam::rep
Definition at line 71 of file aoparam.f90.
    real(wp), public :: rep(2,max_elem)
space
character, parameter xtb_aoparam::space = ' ' private
Definition at line 58 of file aoparam.f90.
    character, parameter :: space = ' '
timestp
character(len=30), dimension(max_elem), public xtb_aoparam::timestp
Definition at line 92 of file aoparam.f90.
    character(len=30), public :: timestp(max_elem)
Referenced by gfn0_prparam(), gfn1_prparam(), and gfn2_prparam().
wll
real(wp), dimension(max_elem,10), public xtb_aoparam::wll
Definition at line 70 of file aoparam.f90.
    real(wp), public :: wll(max_elem,10)