My Project: xtb_disp_coordinationnumber Module Reference
xtb_disp_coordinationnumber Module Reference
TODO.
Data Types
interface getcoordinationnumber
type tcntypeenum
Possible counting functions for calculating coordination numbers.
interface countingFunction
Abstract interface for the counting function (and its derivative)
Functions/Subroutines
subroutine getcoordinationnumberwrap (env, mol, cf, cn, dcndr, dcndL, cutoff)
Geometric fractional coordination number, supports both error function.
subroutine getcoordinationnumbernl (mol, neighs, neighlist, cf, cn, dcndr, dcndL)
Geometric fractional coordination number, supports both error function.
subroutine ncoordneighs (mol, neighs, neighlist, kcn, cfunc, dfunc, enscale, rcov, en, cn, dcndr, dcndL)
Actual implementation of the coordination number, takes a generic counting.
subroutine getcoordinationnumberlp (mol, trans, cutoff, cf, cn, dcndr, dcndL)
Geometric fractional coordination number, supports both error function.
subroutine ncoordlatp (mol, trans, cutoff, kcn, cfunc, dfunc, enscale, rcov, en, cn, dcndr, dcndL)
Actual implementation of the coordination number, takes a generic counting.
pure real(wp) function erfcount (k, r, r0)
Error function counting function for coordination number contributions.
pure real(wp) function derfcount (k, r, r0)
Derivative of the counting function w.r.t. the distance.
pure real(wp) function expcount (k, r, r0)
Exponential counting function for coordination number contributions.
pure real(wp) function dexpcount (k, r, r0)
Derivative of the counting function w.r.t. the distance.
pure real(wp) function gfncount (k, r, r0)
Exponential counting function for coordination number contributions.
pure real(wp) function dgfncount (k, r, r0)
Derivative of the counting function w.r.t. the distance.
pure subroutine, public cutcoordinationnumber (nAtom, cn, dcndr, dcndL, maxCN)
Cutoff function for large coordination numbers.
elemental real(wp) function cutcn (cn, cut)
Cutting function for the coordination number.
elemental real(wp) function dcutcn (cn, cut)
Derivative of the cutting function w.r.t. coordination number.
Variables
type(tcntypeenum), parameter, public cntype = TCNTypeEnum()
Enumerator for different coordination number types.
real(wp), parameter k4 =4.10451_wp
Parameter for electronegativity scaling.
real(wp), parameter k5 =19.08857_wp
Parameter for electronegativity scaling.
real(wp), parameter k6 =2*11.28174_wp**2
Parameter for electronegativity scaling.
Detailed Description
TODO.
Function/Subroutine Documentation
cutcn()
elemental real(wp) function xtb_disp_coordinationnumber::cutcn (real(wp), intent(in) cn, real(wp), intent(in) cut) private
Cutting function for the coordination number.
Parameters
[in] cn Current coordination number.
[in] cut Cutoff for the CN, this is not the maximum value.
Returns
Cuting function vlaue
Definition at line 617 of file coordinationnumber.f90.
    real(wp), intent(in) :: cn
    real(wp), intent(in) :: cut
    real(wp) :: cnp
    cnp = log(1.0_wp + exp(cut)) - log(1.0_wp + exp(cut - cn))
Referenced by cutcoordinationnumber().
cutcoordinationnumber()
pure subroutine, public xtb_disp_coordinationnumber::cutcoordinationnumber (integer, intent(in) nAtom, real(wp), dimension(:), intent(inout) cn, real(wp), dimension(:, :, :), intent(inout), optional dcndr, real(wp), dimension(:, :, :), intent(inout), optional dcndL, real(wp), intent(in), optional maxCN)
Cutoff function for large coordination numbers.
Parameters
[in] natom number of atoms
[in,out] cn on input coordination number, on output modified CN
[in,out] dcndr on input derivative of CN w.r.t. cartesian coordinates, on output derivative of modified CN
[in,out] dcndl on input derivative of CN w.r.t. strain deformation, on output derivative of modified CN
[in] maxcn maximum CN (not strictly obeyed)
Definition at line 567 of file coordinationnumber.f90.
    integer, intent(in) :: nAtom
    real(wp), intent(inout) :: cn(:)
    real(wp), intent(inout), optional :: dcndr(:, :, :)
    real(wp), intent(inout), optional :: dcndL(:, :, :)
    real(wp), intent(in), optional :: maxCN
    real(wp) :: cnmax
    integer :: iAt
    if (present(maxcn)) then
       cnmax = maxcn
    else
       cnmax = 4.5_wp
    end if
    if (cnmax <= 0.0_wp) return
    if (present(dcndl)) then
       do iat = 1, natom
          dcndl(:, :, iat) = dcndl(:, :, iat) * dcutcn(cn(iat), cnmax)
       end do
    end if
    if (present(dcndr)) then
       do iat = 1, natom
          dcndr(:, :, iat) = dcndr(:, :, iat) * dcutcn(cn(iat), cnmax)
       end do
    end if
    do iat = 1, natom
       cn(iat) = cutcn(cn(iat), cnmax)
    end do
References cutcn(), and dcutcn().
Referenced by xtb_peeq::peeq(), test_dftd4_pbc3d_latticepoints(), test_dftd4_pbc3d_neighbourlist(), and test_eeq_ewald().
dcutcn()
elemental real(wp) function xtb_disp_coordinationnumber::dcutcn (real(wp), intent(in) cn, real(wp), intent(in) cut) private
Derivative of the cutting function w.r.t. coordination number.
Parameters
[in] cn Current coordination number.
[in] cut Cutoff for the CN, this is not the maximum value.
Returns
Derivative of the cutting function
Definition at line 634 of file coordinationnumber.f90.
    real(wp), intent(in) :: cn
    real(wp), intent(in) :: cut
    real(wp) :: dcnpdcn
    dcnpdcn = exp(cut)/(exp(cut) + exp(cn))
Referenced by cutcoordinationnumber().
derfcount()
pure real(wp) function xtb_disp_coordinationnumber::derfcount (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0) private
Derivative of the counting function w.r.t. the distance.
Parameters
[in] k Steepness of the counting function.
[in] r Current distance.
[in] r0 Cutoff radius.
Definition at line 466 of file coordinationnumber.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp), parameter :: sqrtpi = sqrt(pi)
    real(wp) :: count
    count = -k/sqrtpi/r0*exp(-k**2*(r-r0)**2/r0**2)
References xtb_mctc_constants::pi.
Referenced by xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp(), and xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl().
dexpcount()
pure real(wp) function xtb_disp_coordinationnumber::dexpcount (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0) private
Derivative of the counting function w.r.t. the distance.
Parameters
[in] k Steepness of the counting function.
[in] r Current distance.
[in] r0 Cutoff radius.
Definition at line 506 of file coordinationnumber.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    real(wp) :: expterm
    expterm = exp(-k*(r0/r-1._wp))
    count = (-k*r0*expterm)/(r**2*((expterm+1._wp)**2))
Referenced by dgfncount(), xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp(), and xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl().
dgfncount()
pure real(wp) function xtb_disp_coordinationnumber::dgfncount (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0) private
Derivative of the counting function w.r.t. the distance.
Parameters
[in] k Steepness of the counting function.
[in] r Current distance.
[in] r0 Cutoff radius.
Definition at line 547 of file coordinationnumber.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    count = dexpcount(k, r, r0) * expcount(2*k, r, r0+2) &
       &  + expcount(k, r, r0) * dexpcount(2*k, r, r0+2)
References dexpcount(), and expcount().
Referenced by xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp(), and xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl().
erfcount()
pure real(wp) function xtb_disp_coordinationnumber::erfcount (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0) private
Error function counting function for coordination number contributions.
Parameters
[in] k Steepness of the counting function.
[in] r Current distance.
[in] r0 Cutoff radius.
Definition at line 447 of file coordinationnumber.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    count = 0.5_wp * (1.0_wp + erf(-k*(r-r0)/r0))
Referenced by xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp(), and xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl().
expcount()
pure real(wp) function xtb_disp_coordinationnumber::expcount (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0) private
Exponential counting function for coordination number contributions.
Parameters
[in] k Steepness of the counting function.
[in] r Current distance.
[in] r0 Cutoff radius.
Definition at line 487 of file coordinationnumber.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    count =1.0_wp/(1.0_wp+exp(-k*(r0/r-1.0_wp)))
Referenced by dgfncount(), xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp(), xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl(), and gfncount().
getcoordinationnumberlp()
subroutine xtb_disp_coordinationnumber::getcoordinationnumberlp (type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) trans, real(wp), intent(in) cutoff, integer, intent(in) cf, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:, :, :), intent(out) dcndr, real(wp), dimension(:, :, :), intent(out) dcndL) private
Geometric fractional coordination number, supports both error function.
Parameters
[in] mol Molecular structure information
[in] trans Lattice points
[in] cutoff Real space cutoff
[in] cf Coordination number type (by counting function)
[out] cn Error function coordination number
[out] dcndr Derivative of the CN with respect to the Cartesian coordinates
[out] dcndl Derivative of the CN with respect to strain deformations
Definition at line 302 of file coordinationnumber.f90.
    type(TMolecule), intent(in) :: mol
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(in) :: cutoff
    integer, intent(in) :: cf
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out) :: dcndr(:, :, :)
    real(wp), intent(out) :: dcndL(:, :, :)
    real(wp), parameter :: kcn_exp = 16.0_wp
    real(wp), parameter :: kcn_erf = 7.5_wp
    real(wp), parameter :: kcn_gfn = 10.0_wp
    select case(cf)
    case(cntype%exp)
       call ncoordlatp(mol, trans, cutoff, kcn_exp, expcount, dexpcount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%erf)
       call ncoordlatp(mol, trans, cutoff, kcn_erf, erfcount, derfcount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%cov)
       call ncoordlatp(mol, trans, cutoff, kcn_erf, erfcount, derfcount, &
          & .true., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%gfn)
       call ncoordlatp(mol, trans, cutoff, kcn_gfn, gfncount, dgfncount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    end select
getcoordinationnumbernl()
subroutine xtb_disp_coordinationnumber::getcoordinationnumbernl (type(tmolecule), intent(in) mol, integer, dimension(:), intent(in) neighs, type(tneighbourlist), intent(in) neighlist, integer, intent(in) cf, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:, :, :), intent(out) dcndr, real(wp), dimension(:, :, :), intent(out) dcndL) private
Geometric fractional coordination number, supports both error function.
Parameters
[in] mol Molecular structure information
[in] neighs Number of interacting neighbours
[in] neighlist Neighbourlist
[in] cf Coordination number type (by counting function)
[out] cn Error function coordination number
[out] dcndr Derivative of the CN with respect to the Cartesian coordinates
[out] dcndl Derivative of the CN with respect to strain deformations
Definition at line 159 of file coordinationnumber.f90.
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: neighs(:)
    type(TNeighbourList), intent(in) :: neighlist
    integer, intent(in) :: cf
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out) :: dcndr(:, :, :)
    real(wp), intent(out) :: dcndL(:, :, :)
    real(wp), parameter :: kcn_exp = 16.0_wp
    real(wp), parameter :: kcn_erf = 7.5_wp
    real(wp), parameter :: kcn_gfn = 10.0_wp
    select case(cf)
    case(cntype%exp)
       call ncoordneighs(mol, neighs, neighlist, kcn_exp, expcount, dexpcount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%erf)
       call ncoordneighs(mol, neighs, neighlist, kcn_erf, erfcount, derfcount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%cov)
       call ncoordneighs(mol, neighs, neighlist, kcn_erf, erfcount, derfcount, &
          & .true., covalentradd3, paulingen, cn, dcndr, dcndl)
    case(cntype%gfn)
       call ncoordneighs(mol, neighs, neighlist, kcn_gfn, gfncount, dgfncount, &
          & .false., covalentradd3, paulingen, cn, dcndr, dcndl)
    end select
getcoordinationnumberwrap()
subroutine xtb_disp_coordinationnumber::getcoordinationnumberwrap (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, integer, intent(in) cf, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:, :, :), intent(out) dcndr, real(wp), dimension(:, :, :), intent(out) dcndL, real(wp), intent(in), optional cutoff) private
Geometric fractional coordination number, supports both error function.
Parameters
[in,out] env Computational Environment
[in] mol Molecular structure information
[in] cf Coordination number type (by counting function)
[out] cn Error function coordination number
[out] dcndr Derivative of the CN with respect to the Cartesian coordinates
[out] dcndl Derivative of the CN with respect to strain deformations
[in] cutoff Real space cutoff for the coordination number
Initialize lattice point generator, this might fail
Generate a new batch of lattice points
Actual call to the lattice point version of the CN evaluation
Definition at line 101 of file coordinationnumber.f90.
    character(len=*), parameter :: source = &
       & 'disp_coordinationnumber_getCoordinationNumberWrap'
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: cf
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out) :: dcndr(:, :, :)
    real(wp), intent(out) :: dcndL(:, :, :)
    real(wp), intent(in), optional :: cutoff
    logical :: exitRun
    real(wp) :: rCutoff
    real(wp), allocatable :: trans(:, :)
    type(TLatticePoint) :: latp
    if (present(cutoff)) then
       rcutoff = cutoff
    else
       rcutoff = 40.0_wp
    end if
    call init_(latp, env, mol, rcutoff)
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Setup of lattice point generator failed", source)
       return
    end if
    call latp%getLatticePoints(trans, rcutoff)
    call getcoordinationnumber(mol, trans, rcutoff, cf, cn, dcndr, dcndl)
gfncount()
pure real(wp) function xtb_disp_coordinationnumber::gfncount (real(wp), intent(in) k, real(wp), intent(in) r, real(wp), intent(in) r0) private
Exponential counting function for coordination number contributions.
Parameters
[in] k Steepness of the counting function.
[in] r Current distance.
[in] r0 Cutoff radius.
Definition at line 528 of file coordinationnumber.f90.
    real(wp), intent(in) :: k
    real(wp), intent(in) :: r
    real(wp), intent(in) :: r0
    real(wp) :: count
    count = expcount(k, r, r0) * expcount(2*k, r, r0+2)
References expcount().
Referenced by xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp(), and xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl().
ncoordlatp()
subroutine xtb_disp_coordinationnumber::ncoordlatp (type(tmolecule), intent(in) mol, real(wp), dimension(:, :), intent(in) trans, real(wp), intent(in) cutoff, real(wp), intent(in) kcn, procedure(countingfunction) cfunc, procedure(countingfunction) dfunc, logical, intent(in) enscale, real(wp), dimension(:), intent(in) rcov, real(wp), dimension(:), intent(in) en, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:, :, :), intent(out) dcndr, real(wp), dimension(:, :, :), intent(out) dcndL) private
Actual implementation of the coordination number, takes a generic counting.
Parameters
[in] mol Molecular structure information
[in] trans Lattice points
[in] cutoff Real space cutoff
cfunc Function implementing the counting function
dfunc Function implementing the derivative of counting function w.r.t. distance
[in] enscale Use a covalency criterium by Pauling EN's
[in] kcn Steepness of counting function
[in] rcov Covalent radius
[in] en Electronegativity
[out] cn Error function coordination number.
[out] dcndr Derivative of the CN with respect to the Cartesian coordinates.
[out] dcndl Derivative of the CN with respect to strain deformations.
Definition at line 349 of file coordinationnumber.f90.
    type(TMolecule), intent(in) :: mol
    real(wp), intent(in) :: trans(:, :)
    real(wp), intent(in) :: cutoff
    procedure(countingFunction) :: cfunc
    procedure(countingFunction) :: dfunc
    logical, intent(in) :: enscale
    real(wp), intent(in) :: kcn
    real(wp), intent(in) :: rcov(:)
    real(wp), intent(in) :: en(:)
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out) :: dcndr(:, :, :)
    real(wp), intent(out) :: dcndL(:, :, :)
    integer :: iat, jat, ati, atj, itr
    real(wp) :: r2, r1, rc, rij(3), countf, countd(3), stress(3, 3), den, cutoff2
    cn = 0.0_wp
    dcndr = 0.0_wp
    dcndl = 0.0_wp
    cutoff2 = cutoff**2
    !$omp parallel do default(none) private(den) shared(enscale, rcov, en)&
    !$omp reduction(+:cn, dcndr, dcndL) shared(mol, kcn, trans, cutoff2) &
    !$omp private(jat, itr, ati, atj, r2, rij, r1, rc, countf, countd, stress)
    do iat = 1, len(mol)
       ati = mol%at(iat)
       do jat = 1, iat
          atj = mol%at(jat)
          if (enscale) then
             den = k4*exp(-(abs(en(ati)-en(atj)) + k5)**2/k6)
          else
             den = 1.0_wp
          end if
          do itr = 1, size(trans, dim=2)
             rij = mol%xyz(:, iat) - (mol%xyz(:, jat) + trans(:, itr))
             r2 = sum(rij**2)
             if (r2 > cutoff2 .or. r2 < 1.0e-12_wp) cycle
             r1 = sqrt(r2)
             rc = rcov(ati) + rcov(atj)
             countf = den * cfunc(kcn, r1, rc)
             countd = den * dfunc(kcn, r1, rc) * rij/r1
             cn(iat) = cn(iat) + countf
             if (iat /= jat) then
                cn(jat) = cn(jat) + countf
             end if
             dcndr(:, iat, iat) = dcndr(:, iat, iat) + countd
             dcndr(:, jat, jat) = dcndr(:, jat, jat) - countd
             dcndr(:, iat, jat) = dcndr(:, iat, jat) + countd
             dcndr(:, jat, iat) = dcndr(:, jat, iat) - countd
             stress = spread(countd, 1, 3) * spread(rij, 2, 3)
             dcndl(:, :, iat) = dcndl(:, :, iat) + stress
             if (iat /= jat) then
                dcndl(:, :, jat) = dcndl(:, :, jat) + stress
             end if
          end do
       end do
    end do
    !$omp end parallel do
References k4, k5, and k6.
Referenced by xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp().
ncoordneighs()
subroutine xtb_disp_coordinationnumber::ncoordneighs (type(tmolecule), intent(in) mol, integer, dimension(:), intent(in) neighs, type(tneighbourlist), intent(in), target neighlist, real(wp), intent(in) kcn, procedure(countingfunction) cfunc, procedure(countingfunction) dfunc, logical, intent(in) enscale, real(wp), dimension(:), intent(in) rcov, real(wp), dimension(:), intent(in) en, real(wp), dimension(:), intent(out) cn, real(wp), dimension(:, :, :), intent(out) dcndr, real(wp), dimension(:, :, :), intent(out) dcndL) private
Actual implementation of the coordination number, takes a generic counting.
Parameters
[in] mol Molecular structure information
[in] neighs Number of interacting neighbours
[in] neighlist Neighbourlist
cfunc Function implementing the counting function
dfunc Function implementing the derivative of counting function w.r.t. distance
[in] enscale Use a covalency criterium by Pauling EN's
[in] kcn Steepness of counting function
[in] rcov Covalent radius
[in] en Electronegativity
[out] cn Error function coordination number
[out] dcndr Derivative of the CN with respect to the Cartesian coordinates
[out] dcndl Derivative of the CN with respect to strain deformations
Definition at line 206 of file coordinationnumber.f90.
    type(TMolecule), intent(in) :: mol
    integer, intent(in) :: neighs(:)
    type(TNeighbourList), target, intent(in) :: neighlist
    procedure(countingFunction) :: cfunc
    procedure(countingFunction) :: dfunc
    logical, intent(in) :: enscale
    real(wp), intent(in) :: kcn
    real(wp), intent(in) :: rcov(:)
    real(wp), intent(in) :: en(:)
    real(wp), intent(out) :: cn(:)
    real(wp), intent(out) :: dcndr(:, :, :)
    real(wp), intent(out) :: dcndL(:, :, :)
    integer :: iat, jat, ati, atj, ij, img
    real(wp) :: r2, r1, rc, rij(3), countf, countd(3), stress(3, 3), den
    cn = 0.0_wp
    dcndr = 0.0_wp
    dcndl = 0.0_wp
    !$omp parallel do default(none) private(den) shared(enscale, rcov, en)&
    !$omp reduction(+:cn, dcndr, dcndL) shared(mol, kcn, neighlist, neighs) &
    !$omp private(ij, img, jat, ati, atj, r2, rij, r1, rc, countf, countd, stress)
    do iat = 1, len(mol)
       ati = mol%at(iat)
       do ij = 1, neighs(iat)
          img = neighlist%iNeigh(ij, iat)
          r2 = neighlist%dist2(ij, iat)
          rij = neighlist%coords(:, iat) - neighlist%coords(:, img)
          jat = neighlist%image(img)
          atj = mol%at(jat)
          r1 = sqrt(r2)
          rc = rcov(ati) + rcov(atj)
          if (enscale) then
             den = k4*exp(-(abs(en(ati)-en(atj)) + k5)**2/k6)
          else
             den = 1.0_wp
          endif
          countf = den * cfunc(kcn, r1, rc)
          countd = den * dfunc(kcn, r1, rc) * rij/r1
          cn(iat) = cn(iat) + countf
          if (iat /= jat) then
             cn(jat) = cn(jat) + countf
          endif
          dcndr(:, iat, iat) = dcndr(:, iat, iat) + countd
          dcndr(:, jat, jat) = dcndr(:, jat, jat) - countd
          dcndr(:, iat, jat) = dcndr(:, iat, jat) + countd
          dcndr(:, jat, iat) = dcndr(:, jat, iat) - countd
          stress = spread(countd, 1, 3) * spread(rij, 2, 3)
          dcndl(:, :, iat) = dcndl(:, :, iat) + stress
          if (iat /= jat) then
             dcndl(:, :, jat) = dcndl(:, :, jat) + stress
          endif
       enddo
    enddo
    !$omp end parallel do
References k4, k5, and k6.
Referenced by xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl().
Variable Documentation
cntype
type(tcntypeenum), parameter, public xtb_disp_coordinationnumber::cntype = TCNTypeEnum()
Enumerator for different coordination number types.
Definition at line 62 of file coordinationnumber.f90.
    type(TCNTypeEnum), parameter :: cnType = tcntypeenum()
Referenced by xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumberlp(), xtb_disp_coordinationnumber::getcoordinationnumber::getcoordinationnumbernl(), xtb_peeq::peeq(), xtb_scf::scf(), test_dftd3_pbc3d_latticepoints(), test_dftd3_pbc3d_neighbourlist(), test_dftd3_pbc3d_threebody_latp(), test_dftd3_pbc3d_threebody_neighs(), test_dftd4_pbc3d_latticepoints(), test_dftd4_pbc3d_neighbourlist(), test_dftd4_pbc3d_threebody_latp(), test_dftd4_pbc3d_threebody_neighs(), test_eeq_ewald(), test_eeq_model_gbsa(), test_eeq_model_salt(), test_eeq_water(), test_ncoord_pbc3d_latticepoints(), and test_ncoord_pbc3d_neighbourlist().
k4
real(wp), parameter xtb_disp_coordinationnumber::k4 =4.10451_wp private
Parameter for electronegativity scaling.
Definition at line 87 of file coordinationnumber.f90.
    real(wp),parameter :: k4=4.10451_wp
Referenced by ncoordlatp(), and ncoordneighs().
k5
real(wp), parameter xtb_disp_coordinationnumber::k5 =19.08857_wp private
Parameter for electronegativity scaling.
Definition at line 90 of file coordinationnumber.f90.
    real(wp),parameter :: k5=19.08857_wp
Referenced by ncoordlatp(), and ncoordneighs().
k6
real(wp), parameter xtb_disp_coordinationnumber::k6 =2*11.28174_wp**2 private
Parameter for electronegativity scaling.
Definition at line 93 of file coordinationnumber.f90.
    real(wp),parameter :: k6=2*11.28174_wp**2
Referenced by ncoordlatp(), and ncoordneighs().