My Project: xtb_type_molecule Module Reference
xtb_type_molecule Module Reference
molecular structure information
Data Types
interface tmolecule
Molecular structure information.
interface init
interface len
Functions/Subroutines
subroutine initmolecule (mol, at, sym, xyz, chrg, uhf, lattice, pbc)
Constructor for the molecular structure type.
subroutine initmoleculenumbers (mol, at, xyz, chrg, uhf, lattice, pbc)
Constructor for the molecular structure type.
subroutine initmoleculesymbols (mol, sym, xyz, chrg, uhf, lattice, pbc)
Constructor for the molecular structure type.
type(tmolecule) function, public new_molecule_api (n, at, xyz, chrg, uhf, lattice, pbc)
Constructor for the molecular structure type, compatible with C input.
integer pure elemental function mol_length (self)
obtain number of atoms for molecular structure
subroutine allocate_molecule (self, n)
constructor for molecular structure
subroutine deallocate_molecule (self)
deconstructor for molecular structure
subroutine update (self)
subroutine mol_calculate_distances (self)
calculates all distances for molecular structures and minimum
subroutine mol_set_nuclear_charge (self)
get all nuclear charges
subroutine mol_set_atomic_masses (self)
get all nuclear charges
subroutine wrap_back (self)
wrap cartesian coordinates back into cell
pure real(wp) function, dimension(3) center_of_geometry (self)
pure subroutine shift_to_center_of_geometry (self)
pure real(wp) function molecular_mass (self)
pure real(wp) function, dimension(3) center_of_mass (self)
pure subroutine shift_to_center_of_mass (self)
pure real(wp) function, dimension(3) moments_of_inertia (self)
pure real(wp) function, dimension(3) rotational_constants (self)
pure subroutine align_to_principal_axes (self, break_symmetry)
Detailed Description
molecular structure information
Function/Subroutine Documentation
align_to_principal_axes()
pure subroutine xtb_type_molecule::align_to_principal_axes (class(tmolecule), intent(inout) self, logical, intent(in), optional break_symmetry)
Parameters
[in,out] self molecular structure information
Definition at line 665 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_math, only : eigvec3x3, matdet3x3
    use xtb_pbc_tools
    implicit none
    class(TMolecule),intent(inout) :: self
    logical, optional, intent(in)    :: break_symmetry
    real(wp) :: moments(3),det
    real(wp) :: center(3),atmass,inertia(3,3),axes(3,3)
    real(wp) :: x,x2,y,y2,z,z2
    integer  :: i,iat
    ! currently not supported
    if (self%npbc > 0) then
       return
    endif
    center = self%center_of_mass()
    inertia(:, :) = 0.0_wp
    if (present(break_symmetry)) then
       if (break_symmetry) then
          inertia(1,1) = 1.0e-10_wp
          inertia(1,2) = 2.0e-10_wp
          inertia(2,2) = 3.0e-10_wp
          inertia(1,3) = 4.0e-10_wp
          inertia(2,3) = 5.0e-10_wp
          inertia(3,3) = 6.0e-10_wp
       end if
    endif
    do iat = 1, self%n
       atmass = self%atmass(iat)
       x = self%xyz(1,iat)-center(1); x2 = x**2
       y = self%xyz(2,iat)-center(2); y2 = y**2
       z = self%xyz(3,iat)-center(3); z2 = z**2
       inertia(1,1) = inertia(1,1) + atmass * (y2+z2)
       inertia(1,2) = inertia(1,2) - atmass * x*y
       inertia(2,2) = inertia(2,2) + atmass * (x2+z2)
       inertia(1,3) = inertia(1,3) - atmass * x*z
       inertia(2,3) = inertia(2,3) - atmass * y*z
       inertia(3,3) = inertia(3,3) + atmass * (x2+y2)
    enddo
    call eigvec3x3(inertia,moments,axes)
    det = matdet3x3(axes)
    if (det < 0) axes(:,1) = -axes(:,1)
    call coord_trafo(self%n,axes,self%xyz)
References xtb_mctc_math::eigvec3x3(), xtb_mctc_math::matdet3x3(), and xtb_mctc_accuracy::wp.
allocate_molecule()
subroutine xtb_type_molecule::allocate_molecule (class(tmolecule), intent(inout) self, integer, intent(in) n) private
constructor for molecular structure
Parameters
[in,out] self molecular structure information
Definition at line 405 of file molecule.f90.
    implicit none
    class(TMolecule),intent(inout) :: self
    integer,intent(in) :: n
    call self%deallocate
    self%n = n
    allocate( self%id(n),          source = 0 )
    allocate( self%at(n),          source = 0 )
    allocate( self%sym(n),         source = '    ' )
    allocate( self%xyz(3,n),       source = 0.0_wp )
    allocate( self%abc(3,n),       source = 0.0_wp )
    allocate( self%dist(n,n),      source = 0.0_wp )
    allocate( self%atmass(n),      source = 0.0_wp )
    allocate( self%z(n),           source = 0.0_wp )
    allocate( self%cn(n),          source = 0.0_wp )
center_of_geometry()
pure real(wp) function, dimension(3) xtb_type_molecule::center_of_geometry (class(tmolecule), intent(in) self)
Parameters
[in] self molecular structure information
Definition at line 556 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    class(TMolecule),intent(in) :: self
    real(wp) :: center(3)
    integer  :: idir
    center = 0.0_wp
    do idir = 1, 3
       if (.not.self%pbc(idir)) &
          center(idir) = sum(self%xyz(idir,:))
    enddo
    center = center/real(self%n,wp)
References xtb_mctc_accuracy::wp.
center_of_mass()
pure real(wp) function, dimension(3) xtb_type_molecule::center_of_mass (class(tmolecule), intent(in) self)
Parameters
[in] self molecular structure information
Definition at line 591 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    class(TMolecule),intent(in) :: self
    real(wp) :: center(3)
    integer  :: idir
    center = 0.0_wp
    do idir = 1, 3
       if (.not.self%pbc(idir)) &
          center(idir) = sum(self%atmass*self%xyz(idir,:))
    enddo
    center = center/sum(self%atmass)
References xtb_mctc_accuracy::wp.
deallocate_molecule()
subroutine xtb_type_molecule::deallocate_molecule (class(tmolecule), intent(inout) self) private
deconstructor for molecular structure
Parameters
[in,out] self molecular structure information
Definition at line 423 of file molecule.f90.
    implicit none
    class(TMolecule),intent(inout) :: self
    self%n = 0
    self%nId = 0
    self%pbc = .false.
    self%chrg = 0.0_wp
    self%uhf = 0
    self%lattice = 0.0_wp
    if (allocated(self%id))     deallocate(self%id)
    if (allocated(self%at))     deallocate(self%at)
    if (allocated(self%sym))    deallocate(self%sym)
    if (allocated(self%xyz))    deallocate(self%xyz)
    if (allocated(self%abc))    deallocate(self%abc)
    if (allocated(self%dist))   deallocate(self%dist)
    if (allocated(self%atmass)) deallocate(self%atmass)
    if (allocated(self%z))      deallocate(self%z)
    if (allocated(self%cn))     deallocate(self%cn)
    if (allocated(self%pdb))    deallocate(self%pdb)
    if (allocated(self%sdf))    deallocate(self%sdf)
    if (allocated(self%name))   deallocate(self%name)
    call self%bonds%deallocate
    call self%frag%deallocate
    call self%info%deallocate
initmolecule()
subroutine xtb_type_molecule::initmolecule (type(tmolecule), intent(out) mol, integer, dimension(:), intent(in) at, character(len=*), dimension(:), intent(in) sym, real(wp), dimension(:, :), intent(in) xyz, real(wp), intent(in), optional chrg, integer, intent(in), optional uhf, real(wp), dimension(3, 3), intent(in), optional lattice, logical, dimension(3), intent(in), optional pbc) private
Constructor for the molecular structure type.
Definition at line 196 of file molecule.f90.
    interface
       subroutine generate_wsc(mol,wsc)
          import :: tmolecule, tb_wsc
          type(TMolecule), intent(inout) :: mol
          type(tb_wsc),    intent(inout) :: wsc
       end subroutine generate_wsc
    end interface
    type(TMolecule), intent(out) :: mol
    integer, intent(in) :: at(:)
    character(len=*), intent(in) :: sym(:)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in), optional :: chrg
    integer, intent(in), optional :: uhf
    real(wp), intent(in), optional :: lattice(3, 3)
    logical, intent(in), optional :: pbc(3)
    integer, allocatable :: id(:)
    character(len=symbolLength), allocatable :: sTmp(:)
    integer :: nAt, nId, iAt, iId
    nat = min(size(at, dim=1), size(xyz, dim=2), size(sym, dim=1))
    call mol%allocate(nat)
    if (present(lattice)) then
       mol%lattice = lattice
    else
       mol%lattice = 0.0_wp
    end if
    if (present(pbc)) then
       mol%pbc = pbc
       mol%npbc = count(pbc)
       if (any(pbc)) then
          mol%boundaryCondition = boundarycondition%pbc3d
       else
          mol%boundaryCondition = boundarycondition%cluster
       end if
    else
       if (present(lattice)) then
          mol%boundaryCondition = boundarycondition%pbc3d
          mol%pbc = .true.
          mol%npbc = 3
       else
          mol%boundaryCondition = boundarycondition%cluster
          mol%pbc = .false.
          mol%npbc = 0
       end if
    end if
    call getidentity(mol%nId, mol%id, sym)
    mol%at(:) = at(:nat)
    mol%sym(:) = sym(:nat)
    mol%xyz(:, :) = xyz(:, :nat)
    if (present(chrg)) then
       mol%chrg = chrg
    else
       mol%chrg = 0
    end if
    if (present(uhf)) then
       mol%uhf = uhf
    else
       mol%uhf = 0
    end if
    call mol%set_nuclear_charge
    call mol%set_atomic_masses
    call mol%update
    call generate_wsc(mol, mol%wsc)
initmoleculenumbers()
subroutine xtb_type_molecule::initmoleculenumbers (type(tmolecule), intent(out) mol, integer, dimension(:), intent(in) at, real(wp), dimension(:, :), intent(in) xyz, real(wp), intent(in), optional chrg, integer, intent(in), optional uhf, real(wp), dimension(3, 3), intent(in), optional lattice, logical, dimension(3), intent(in), optional pbc) private
Constructor for the molecular structure type.
Definition at line 277 of file molecule.f90.
    type(TMolecule), intent(out) :: mol
    integer, intent(in) :: at(:)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in), optional :: chrg
    integer, intent(in), optional :: uhf
    real(wp), intent(in), optional :: lattice(3, 3)
    logical, intent(in), optional :: pbc(3)
    character(len=4), allocatable :: sym(:)
    integer :: nAt
    nat = min(size(at, dim=1), size(xyz, dim=2))
    allocate(sym(nat))
    sym(:) = tosymbol(at(:nat))
    call init(mol, at, sym, xyz, chrg, uhf, lattice, pbc)
initmoleculesymbols()
subroutine xtb_type_molecule::initmoleculesymbols (type(tmolecule), intent(out) mol, character(len=*), dimension(:), intent(in) sym, real(wp), dimension(:, :), intent(in) xyz, real(wp), intent(in), optional chrg, integer, intent(in), optional uhf, real(wp), dimension(3, 3), intent(in), optional lattice, logical, dimension(3), intent(in), optional pbc) private
Constructor for the molecular structure type.
Definition at line 300 of file molecule.f90.
    type(TMolecule), intent(out) :: mol
    character(len=*), intent(in) :: sym(:)
    real(wp), intent(in) :: xyz(:, :)
    real(wp), intent(in), optional :: chrg
    integer, intent(in), optional :: uhf
    real(wp), intent(in), optional :: lattice(3, 3)
    logical, intent(in), optional :: pbc(3)
    integer, allocatable :: at(:)
    integer :: nAt
    nat = min(size(sym, dim=1), size(xyz, dim=2))
    allocate(at(nat))
    at(:) = tonumber(sym(:nat))
    call init(mol, at, sym, xyz, chrg, uhf, lattice, pbc)
mol_calculate_distances()
subroutine xtb_type_molecule::mol_calculate_distances (class(tmolecule), intent(inout) self)
calculates all distances for molecular structures and minimum
Parameters
[in,out] self molecular structure information
Definition at line 469 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_pbc_tools
    implicit none
    class(TMolecule),intent(inout) :: self
    integer :: i,j
    if (self%npbc > 0) then
       do i = 1, self%n
          do j = 1, i-1
             self%dist(j,i) = minimum_image_distance(.false.,self%abc(:,i), &
                &              self%abc(:,j),self%lattice,self%pbc)
             self%dist(i,j) = self%dist(j,i)
          enddo
          self%dist(j,i) = minimum_image_distance(.true.,self%abc(:,i), &
             &              self%abc(:,i),self%lattice,self%pbc)
       enddo
    else
       do i = 1, self%n
          do j = 1, i-1
             self%dist(j,i) = sqrt(sum((self%xyz(:,j)-self%xyz(:,i))**2))
             self%dist(i,j) = self%dist(j,i)
          enddo
          self%dist(i,i) = 0.0_wp
       enddo
    endif
References xtb_pbc_tools::minimum_image_distance(), true(), and xtb_mctc_accuracy::wp.
mol_length()
integer pure elemental function xtb_type_molecule::mol_length (class(tmolecule), intent(in) self)
obtain number of atoms for molecular structure
Parameters
[in] self molecular structure information
Definition at line 398 of file molecule.f90.
    class(TMolecule),intent(in) :: self
    length = self%n
mol_set_atomic_masses()
subroutine xtb_type_molecule::mol_set_atomic_masses (class(tmolecule), intent(inout) self) private
get all nuclear charges
Parameters
[in,out] self molecular structure information
Definition at line 535 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_param
    implicit none
    class(TMolecule),intent(inout) :: self
    self%atmass = atomic_mass(self%at)
References xtb_mctc_accuracy::wp.
mol_set_nuclear_charge()
subroutine xtb_type_molecule::mol_set_nuclear_charge (class(tmolecule), intent(inout) self)
get all nuclear charges
Parameters
[in,out] self molecular structure information
Definition at line 497 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    class(TMolecule),intent(inout) :: self
    integer :: i
    do i = 1, self%n
       self%z(i) = real(self%at(i),wp) - real(ncore(self%at(i)))
       if (self%at(i) > 57 .and. self%at(i) < 72) self%z(i) = 3.0_wp
    enddo
 contains
 pure elemental integer function ncore(at)
   integer,intent(in) :: at
   if(at.le.2)then
      ncore=0
   elseif(at.le.10)then
      ncore=2
   elseif(at.le.18)then
      ncore=10
   elseif(at.le.29)then   !zn
      ncore=18
   elseif(at.le.36)then
      ncore=28
   elseif(at.le.47)then
      ncore=36
   elseif(at.le.54)then
      ncore=46
   elseif(at.le.71)then
      ncore=54
   elseif(at.le.79)then
      ncore=68
   elseif(at.le.86)then
      ncore=78
   endif
 end function ncore
References ncore(), and xtb_mctc_accuracy::wp.
molecular_mass()
pure real(wp) function xtb_type_molecule::molecular_mass (class(tmolecule), intent(in) self)
Parameters
[in] self molecular structure information
Definition at line 583 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    class(TMolecule),intent(in) :: self
    real(wp) :: molmass
    molmass = sum(self%atmass)
References xtb_mctc_accuracy::wp.
moments_of_inertia()
pure real(wp) function, dimension(3) xtb_type_molecule::moments_of_inertia (class(tmolecule), intent(in) self)
Parameters
[in] self molecular structure information
Definition at line 617 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_math, only : eigval3x3
    implicit none
    class(TMolecule),intent(in) :: self
    real(wp) :: moments(3)
    real(wp) :: center(3),atmass,inertia(3,3),work(9),tmp(3,3)
    real(wp) :: x,x2,y,y2,z,z2
    integer  :: iat,info
    ! currently not supported
    if (self%npbc > 0) then
       moments = -1.0_wp
       return
    endif
    center = self%center_of_mass()
    inertia(:, :) = 0.0_wp
    do iat = 1, self%n
       atmass = self%atmass(iat)
       x = self%xyz(1,iat)-center(1); x2 = x**2
       y = self%xyz(2,iat)-center(2); y2 = y**2
       z = self%xyz(3,iat)-center(3); z2 = z**2
       inertia(1,1) = inertia(1,1) + atmass * (y2+z2)
       inertia(1,2) = inertia(1,2) - atmass * x*y
       inertia(2,2) = inertia(2,2) + atmass * (x2+z2)
       inertia(1,3) = inertia(1,3) - atmass * x*z
       inertia(2,3) = inertia(2,3) - atmass * y*z
       inertia(3,3) = inertia(3,3) + atmass * (x2+y2)
    enddo
    call eigval3x3(inertia, moments)
References xtb_mctc_math::eigval3x3(), and xtb_mctc_accuracy::wp.
new_molecule_api()
type(tmolecule) function, public xtb_type_molecule::new_molecule_api (integer(c_int), intent(in) n, integer(c_int), dimension(n), intent(in) at, real(c_double), dimension(3, n), intent(in) xyz, real(c_double), intent(in), optional, target chrg, integer(c_int), intent(in), optional, target uhf, real(c_double), dimension(3, 3), intent(in), optional, target lattice, logical(c_bool), dimension(3), intent(in), optional, target pbc)
Constructor for the molecular structure type, compatible with C input.
Definition at line 323 of file molecule.f90.
    use iso_c_binding
    use xtb_mctc_symbols, only : tosymbol
    integer(c_int), intent(in) :: n
    integer(c_int), intent(in) :: at(n)
    real(c_double), intent(in) :: xyz(3, n)
    real(c_double), intent(in), target, optional :: chrg
    integer(c_int), intent(in), target, optional :: uhf
    real(c_double), intent(in), target, optional :: lattice(3, 3)
    logical(c_bool), intent(in), target, optional :: pbc(3)
    integer :: i
    call mol%allocate(n)
    if (c_associated(c_loc(lattice))) then
       mol%lattice = lattice
    else
       mol%lattice = 0.0_wp
    end if
    if (c_associated(c_loc(pbc))) then
       mol%pbc = pbc
       mol%npbc = count(pbc)
       if (any(pbc)) then
          mol%boundaryCondition = boundarycondition%pbc3d
       else
          mol%boundaryCondition = boundarycondition%cluster
       end if
    else
       if (c_associated(c_loc(lattice))) then
          mol%boundaryCondition = boundarycondition%pbc3d
          mol%pbc = .true.
          mol%npbc = 3
       else
          mol%boundaryCondition = boundarycondition%cluster
          mol%pbc = .false.
          mol%npbc = 0
       end if
    end if
    mol%at = at
    do i = 1, n
       mol%sym(i) = tosymbol(at(i))
    end do
    call getidentity(mol%nId, mol%id, mol%at)
    mol%xyz = xyz
    if (c_associated(c_loc(chrg))) then
       mol%chrg = chrg
    else
       mol%chrg = 0
    end if
    if (c_associated(c_loc(uhf))) then
       mol%uhf = uhf
    else
       mol%uhf = 0
    end if
    call mol%set_nuclear_charge
    call mol%set_atomic_masses
    call mol%update
    call generate_wsc(mol, mol%wsc)
rotational_constants()
pure real(wp) function, dimension(3) xtb_type_molecule::rotational_constants (class(tmolecule), intent(in) self)
Parameters
[in] self molecular structure information
Definition at line 652 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_la
    implicit none
    class(TMolecule),intent(in) :: self
    real(wp) :: moments(3)
    real(wp) :: rotational_constants(3)
    moments = self%moments_of_inertia()
    rotational_constants = 0.5_wp/[moments(3), moments(2), moments(1)]
References xtb_mctc_accuracy::wp.
shift_to_center_of_geometry()
pure subroutine xtb_type_molecule::shift_to_center_of_geometry (class(tmolecule), intent(inout) self)
Parameters
[in,out] self molecular structure information
Definition at line 571 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    class(TMolecule),intent(inout) :: self
    real(wp) :: center(3)
    integer  :: iat
    center = self%center_of_geometry()
    do iat = 1, self%n
       self%xyz(:,iat) = self%xyz(:,iat) - center
    enddo
References xtb_mctc_accuracy::wp.
shift_to_center_of_mass()
pure subroutine xtb_type_molecule::shift_to_center_of_mass (class(tmolecule), intent(inout) self)
Parameters
[in,out] self molecular structure information
Definition at line 605 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    class(TMolecule),intent(inout) :: self
    real(wp) :: center(3)
    integer  :: iat
    center = self%center_of_mass()
    do iat = 1, self%n
       self%xyz(:,iat) = self%xyz(:,iat) - center
    enddo
References xtb_mctc_accuracy::wp.
update()
subroutine xtb_type_molecule::update (class(tmolecule), intent(inout) self) private
Parameters
[in,out] self molecular structure information
Definition at line 449 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_pbc_tools
    implicit none
    class(TMolecule),intent(inout) :: self
    if (self%npbc > 0) then
       call dlat_to_cell(self%lattice,self%cellpar)
       call dlat_to_rlat(self%lattice,self%rec_lat)
       self%volume = dlat_to_dvol(self%lattice)
       call self%wrap_back
    endif
    call self%calculate_distances
References xtb_pbc_tools::dlat_to_cell(), xtb_pbc_tools::dlat_to_dvol(), xtb_pbc_tools::dlat_to_rlat(), and xtb_mctc_accuracy::wp.
Referenced by xtb_relaxation_engine::fire().
wrap_back()
subroutine xtb_type_molecule::wrap_back (class(tmolecule), intent(inout) self)
wrap cartesian coordinates back into cell
Parameters
[in,out] self molecular structure information
Definition at line 547 of file molecule.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_pbc_tools
    implicit none
    class(TMolecule),intent(inout) :: self
    call xyz_to_abc(self%n,self%lattice,self%xyz,self%abc,self%pbc)
    call abc_to_xyz(self%n,self%lattice,self%abc,self%xyz)
References xtb_pbc_tools::abc_to_xyz(), xtb_mctc_accuracy::wp, and xtb_pbc_tools::xyz_to_abc().