My Project: xtb_mctc_symbols Module Reference
xtb_mctc_symbols Module Reference
Handle conversion between element symbols and atomic numbers.
Data Types
interface getidentity
Get chemical identity.
Functions/Subroutines
elemental subroutine, public symboltonumber (number, symbol)
Convert element symbol to atomic number.
elemental subroutine, public numbertosymbol (symbol, number)
Convert atomic number to element symbol.
elemental subroutine, public numbertolcsymbol (symbol, number)
Convert atomic number to element symbol.
elemental integer function, public tonumber (symbol)
Convert element symbol to atomic number.
elemental character(len=2) function, public tosymbol (number)
Convert atomic number to element symbol.
elemental character(len=2) function, public tolcsymbol (number)
Convert atomic number to element symbol.
subroutine getidentitynumber (nId, identity, number)
Get chemical identity from a list of atomic numbers.
subroutine getidentitysymbol (nId, identity, symbol)
Get chemical identity from a list of element symbols.
pure integer function findsymbol (list, symbol)
Find element symbol in an unordered list, all entries are required to be unique.
integer function findnumber (list, number)
Find atomic number in an unordered list, all entries are required to be unique.
pure subroutine appendsymbol (list, nList, symbol)
Append an element symbol to an unsorted list, to ensure no dublicates search for the element symbol first.
pure subroutine appendnumber (list, nList, number)
Append an atomic number to an unsorted list, to ensure no dublicates search for the atomic number first.
Variables
integer, parameter, public symbollength = 4
Maximum allowed length of element symbols.
character(len=2), dimension(118), parameter pse = [ 'H ','He', 'Li','Be','B ','C ','N ','O ','F ','Ne', 'Na','Mg','Al','Si','P ','S ','Cl','Ar', 'K ','Ca', 'Sc','Ti','V ','Cr','Mn','Fe','Co','Ni','Cu','Zn', 'Ga','Ge','As','Se','Br','Kr', 'Rb','Sr', 'Y ','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd', 'In','Sn','Sb','Te','I ','Xe', 'Cs','Ba', 'La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb', 'Lu','Hf','Ta','W ','Re','Os','Ir','Pt','Au','Hg', 'Tl','Pb','Bi','Po','At','Rn', 'Fr','Ra', 'Ac','Th','Pa','U ','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No', 'Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn', 'Nh','Fl','Mc','Lv','Ts','Og' ]
Periodic system of elements.
character(len=2), dimension(118), parameter lcpse = [ 'h ','he', 'li','be','b ','c ','n ','o ','f ','ne', 'na','mg','al','si','p ','s ','cl','ar', 'k ','ca', 'sc','ti','v ','cr','mn','fe','co','ni','cu','zn', 'ga','ge','as','se','br','kr', 'rb','sr', 'y ','zr','nb','mo','tc','ru','rh','pd','ag','cd', 'in','sn','sb','te','i ','xe', 'cs','ba','la', 'ce','pr','nd','pm','sm','eu','gd','tb','dy','ho','er','tm','yb', 'lu','hf','ta','w ','re','os','ir','pt','au','hg', 'tl','pb','bi','po','at','rn', 'fr','ra','ac', 'th','pa','u ','np','pu','am','cm','bk','cf','es','fm','md','no', 'lr','rf','db','sg','bh','hs','mt','ds','rg','cn', 'nh','fl','mc','lv','ts','og' ]
Lower case version of the periodic system of elements.
integer, parameter offset = iachar('a') - iachar('A')
ASCII offset between lowercase and uppercase letters.
Detailed Description
Handle conversion between element symbols and atomic numbers.
Function/Subroutine Documentation
appendnumber()
pure subroutine xtb_mctc_symbols::appendnumber (integer, dimension(:), intent(inout), allocatable list, integer, intent(inout) nList, integer, intent(in) number) private
Append an atomic number to an unsorted list, to ensure no dublicates search for the atomic number first.
Parameters
[in,out] list List of atomic number
[in,out] nlist Current occupied size of list
[in] number Atomic number
Definition at line 345 of file symbols.f90.
    integer, allocatable, intent(inout) :: list(:)
    integer, intent(inout) :: nList
    integer, intent(in) :: number
    if (nlist >= size(list)) then
       call resize(list)
    end if
    nlist = nlist + 1
    list(nlist) = number
References list().
Referenced by xtb_mctc_symbols::getidentity::getidentitynumber().
appendsymbol()
pure subroutine xtb_mctc_symbols::appendsymbol (character(len=*), dimension(:), intent(inout), allocatable list, integer, intent(inout) nList, character(len=*), intent(in) symbol) private
Append an element symbol to an unsorted list, to ensure no dublicates search for the element symbol first.
Parameters
[in,out] list List of element symbols
[in,out] nlist Current occupied size of list
[in] symbol Elements symbol
Definition at line 322 of file symbols.f90.
    character(len=*), allocatable, intent(inout) :: list(:)
    integer, intent(inout) :: nList
    character(len=*), intent(in) :: symbol
    if (nlist >= size(list)) then
       call resize(list)
    end if
    nlist = nlist + 1
    list(nlist) = symbol
References list().
Referenced by xtb_mctc_symbols::getidentity::getidentitysymbol().
findnumber()
integer function xtb_mctc_symbols::findnumber (integer, dimension(:), intent(in) list, integer, intent(in) number) private
Find atomic number in an unordered list, all entries are required to be unique.
Parameters
[in] list List of atomic numbers
[in] number Atomic number
Returns
Position of the number in list if found, otherwise zero
Definition at line 297 of file symbols.f90.
    integer, intent(in) :: list(:)
    integer, intent(in) :: number
    integer :: position
    integer :: iNum
    position = 0
    do inum = 1, size(list)
       if (number == list(inum)) then
          position = inum
          exit
       end if
    end do
References list().
Referenced by xtb_mctc_symbols::getidentity::getidentitynumber().
findsymbol()
pure integer function xtb_mctc_symbols::findsymbol (character(len=*), dimension(:), intent(in) list, character(len=*), intent(in) symbol) private
Find element symbol in an unordered list, all entries are required to be unique.
Parameters
[in] list List of element symbols
[in] symbol Element symbol
Returns
Position of the symbol in list if found, otherwise zero
Definition at line 273 of file symbols.f90.
    character(len=*), intent(in) :: list(:)
    character(len=*), intent(in) :: symbol
    integer :: position
    integer :: iSym
    position = 0
    do isym = 1, size(list)
       if (symbol == list(isym)) then
          position = isym
          exit
       end if
    end do
References list().
Referenced by xtb_mctc_symbols::getidentity::getidentitysymbol().
getidentitynumber()
subroutine xtb_mctc_symbols::getidentitynumber (integer, intent(out) nId, integer, dimension(:), intent(out) identity, integer, dimension(:), intent(in) number) private
Get chemical identity from a list of atomic numbers.
Parameters
[out] nid Number of unique species
[in] number Ordinal numbers
[out] identity Chemical identity
Definition at line 213 of file symbols.f90.
    integer, intent(out) :: nId
    integer, intent(in) :: number(:)
    integer, intent(out) :: identity(:)
    integer, allocatable :: iTmp(:)
    integer :: nAt, iAt, iId
    nat = size(identity)
    allocate(itmp(nat))
    nid = 0
    do iat = 1, nat
       iid = findnumber(itmp(:nid), number(iat))
       if (iid == 0) then
          call appendnumber(itmp, nid, number(iat))
          iid = nid
       end if
       identity(iat) = iid
    end do
getidentitysymbol()
subroutine xtb_mctc_symbols::getidentitysymbol (integer, intent(out) nId, integer, dimension(:), intent(out) identity, character(len=symbollength), dimension(:), intent(in) symbol) private
Get chemical identity from a list of element symbols.
Parameters
[out] nid Number of unique species
[in] symbol Element symbols
[out] identity Chemical identity
Definition at line 243 of file symbols.f90.
    integer, intent(out) :: nId
    character(len=symbolLength), intent(in) :: symbol(:)
    integer, intent(out) :: identity(:)
    character(len=symbolLength), allocatable :: sTmp(:)
    integer :: nAt, iAt, iId
    nat = size(identity)
    allocate(stmp(nat))
    nid = 0
    do iat = 1, nat
       iid = findsymbol(stmp(:nid), symbol(iat))
       if (iid == 0) then
          call appendsymbol(stmp, nid, symbol(iat))
          iid = nid
       end if
       identity(iat) = iid
    end do
numbertolcsymbol()
elemental subroutine, public xtb_mctc_symbols::numbertolcsymbol (character(len=2), intent(out) symbol, integer, intent(in) number)
Convert atomic number to element symbol.
Parameters
[in] number Atomic number
[out] symbol Element symbol
Definition at line 153 of file symbols.f90.
    integer, intent(in) :: number
    character(len=2), intent(out) :: symbol
    if (number <= 0 .or. number > size(lcpse)) then
       symbol = '--'
    else
       symbol = lcpse(number)
    endif
References lcpse.
Referenced by tolcsymbol().
numbertosymbol()
elemental subroutine, public xtb_mctc_symbols::numbertosymbol (character(len=2), intent(out) symbol, integer, intent(in) number)
Convert atomic number to element symbol.
Parameters
[in] number Atomic number
[out] symbol Element symbol
Definition at line 135 of file symbols.f90.
    integer, intent(in) :: number
    character(len=2), intent(out) :: symbol
    if (number <= 0 .or. number > size(pse)) then
       symbol = '--'
    else
       symbol = pse(number)
    endif
References pse.
Referenced by tosymbol().
symboltonumber()
elemental subroutine, public xtb_mctc_symbols::symboltonumber (integer, intent(out) number, character(len=*), intent(in) symbol)
Convert element symbol to atomic number.
Parameters
[in] symbol Element symbol
[out] number Atomic number
Definition at line 90 of file symbols.f90.
    character(len=*), intent(in) :: symbol
    integer, intent(out) :: number
    character(len=2) :: lcSymbol
    integer :: i, j, k, l
    number = 0
    lcsymbol = '  '
    k = 0
    do j = 1, len_trim(symbol)
       if (k > 2) exit
       l = iachar(symbol(j:j))
       if (k >= 1 .and. l == iachar(' ')) exit
       if (k >= 1 .and. l == 9) exit
       if (l >= iachar('A') .and. l <= iachar('Z')) l = l + offset
       if (l >= iachar('a') .and. l <= iachar('z')) then
          k = k+1
          lcsymbol(k:k) = achar(l)
       endif
    enddo
    do i = 1, size(lcpse)
       if (lcsymbol == lcpse(i)) then
          number = i
          exit
       endif
    enddo
    if (number == 0) then
       select case(lcsymbol)
       case('d ', 't ')
          number = 1
       end select
    end if
References lcpse, and offset.
Referenced by tonumber().
tolcsymbol()
elemental character(len=2) function, public xtb_mctc_symbols::tolcsymbol (integer, intent(in) number)
Convert atomic number to element symbol.
Parameters
[in] number Atomic number
Returns
Element symbol
Definition at line 199 of file symbols.f90.
    integer,intent(in) :: number
    character(len=2) :: symbol
    call numbertolcsymbol(symbol, number)
References numbertolcsymbol().
Referenced by write_tm_basis(), and xtb_printout::writecosmofile().
tonumber()
elemental integer function, public xtb_mctc_symbols::tonumber (character(len=*), intent(in) symbol)
Convert element symbol to atomic number.
Parameters
[in] symbol Element symbol
Returns
Atomic number
Definition at line 171 of file symbols.f90.
    character(len=*), intent(in) :: symbol
    integer :: number
    call symboltonumber(number, symbol)
References symboltonumber().
Referenced by xtb_param_atomicmass::getatomicmass::getatomicmasssymbol(), xtb_param_atomicrad::getatomicrad::getatomicradsymbol(), xtb_param_covalentradd3::getcovalentradd3::getcovalentradd3symbol(), xtb_param_paulingen::getpaulingen::getpaulingensymbol(), xtb_param_sqrtzr4r2::getsqrtzr4r2::getsqrtzr4r2symbol(), xtb_param_vdwradd3::getvanderwaalsradd3::getvanderwaalsradd3symbol(), xtb_type_molecule::init::initmoleculesymbols(), xtb_io_reader_turbomole::readmoleculecoord(), xtb_io_reader_genformat::readmoleculegenformat(), xtb_io_reader_ctfile::readmoleculemolfile(), xtb_io_reader_pdb::readmoleculepdb(), xtb_io_reader_vasp::readmoleculevasp(), and xtb_io_reader_xyz::readmoleculexyz().
tosymbol()
elemental character(len=2) function, public xtb_mctc_symbols::tosymbol (integer, intent(in) number)
Convert atomic number to element symbol.
Parameters
[in] number Atomic number
Returns
Element symbol
Definition at line 185 of file symbols.f90.
    integer,intent(in) :: number
    character(len=2) :: symbol
    call numbertosymbol(symbol, number)
References numbertosymbol().
Referenced by xtb_fixparam::fix_info(), geosum(), xtb_type_molecule::init::initmoleculenumbers(), xtb_local::local(), xtb_modef::modefollow(), xtb_type_molecule::tmolecule::new_molecule_api(), pocketscan(), xtb_scanparam::pot_info(), print_angles(), print_distances(), print_elem_dist(), print_torsions(), printmold(), printumold(), xtb_disp_dftd4::prmolc6(), xtb_extern_mopac::runmopac(), xtb_extern_orca::runorca(), xtb_dynamic::wrc(), xtb_printout::writecosmofile(), xtb_io_writer_genformat::writemoleculegenformat(), wrtm(), and zmatpr().
Variable Documentation
lcpse
character(len=2), dimension(118), parameter xtb_mctc_symbols::lcpse = [ 'h ','he', 'li','be','b ','c ','n ','o ','f ','ne', 'na','mg','al','si','p ','s ','cl','ar', 'k ','ca', 'sc','ti','v ','cr','mn','fe','co','ni','cu','zn', 'ga','ge','as','se','br','kr', 'rb','sr', 'y ','zr','nb','mo','tc','ru','rh','pd','ag','cd', 'in','sn','sb','te','i ','xe', 'cs','ba','la', 'ce','pr','nd','pm','sm','eu','gd','tb','dy','ho','er','tm','yb', 'lu','hf','ta','w ','re','os','ir','pt','au','hg', 'tl','pb','bi','po','at','rn', 'fr','ra','ac', 'th','pa','u ','np','pu','am','cm','bk','cf','es','fm','md','no', 'lr','rf','db','sg','bh','hs','mt','ds','rg','cn', 'nh','fl','mc','lv','ts','og' ] private
Lower case version of the periodic system of elements.
Definition at line 62 of file symbols.f90.
    character(len=2), parameter :: lcPse(118) = [ &
       & 'h ','he', &
       & 'li','be','b ','c ','n ','o ','f ','ne', &
       & 'na','mg','al','si','p ','s ','cl','ar', &
       & 'k ','ca', &
       & 'sc','ti','v ','cr','mn','fe','co','ni','cu','zn', &
       &           'ga','ge','as','se','br','kr', &
       & 'rb','sr', &
       & 'y ','zr','nb','mo','tc','ru','rh','pd','ag','cd', &
       &           'in','sn','sb','te','i ','xe', &
       & 'cs','ba','la', &
       & 'ce','pr','nd','pm','sm','eu','gd','tb','dy','ho','er','tm','yb', &
       & 'lu','hf','ta','w ','re','os','ir','pt','au','hg', &
       &           'tl','pb','bi','po','at','rn', &
       & 'fr','ra','ac', &
       & 'th','pa','u ','np','pu','am','cm','bk','cf','es','fm','md','no', &
       & 'lr','rf','db','sg','bh','hs','mt','ds','rg','cn', &
       &           'nh','fl','mc','lv','ts','og' ]
Referenced by numbertolcsymbol(), and symboltonumber().
offset
integer, parameter xtb_mctc_symbols::offset = iachar('a') - iachar('A') private
ASCII offset between lowercase and uppercase letters.
Definition at line 83 of file symbols.f90.
    integer, parameter :: offset = iachar('a') - iachar('A')
Referenced by symboltonumber().
pse
character(len=2), dimension(118), parameter xtb_mctc_symbols::pse = [ 'H ','He', 'Li','Be','B ','C ','N ','O ','F ','Ne', 'Na','Mg','Al','Si','P ','S ','Cl','Ar', 'K ','Ca', 'Sc','Ti','V ','Cr','Mn','Fe','Co','Ni','Cu','Zn', 'Ga','Ge','As','Se','Br','Kr', 'Rb','Sr', 'Y ','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd', 'In','Sn','Sb','Te','I ','Xe', 'Cs','Ba', 'La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb', 'Lu','Hf','Ta','W ','Re','Os','Ir','Pt','Au','Hg', 'Tl','Pb','Bi','Po','At','Rn', 'Fr','Ra', 'Ac','Th','Pa','U ','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No', 'Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn', 'Nh','Fl','Mc','Lv','Ts','Og' ] private
Periodic system of elements.
Definition at line 41 of file symbols.f90.
    character(len=2), parameter :: pse(118) = [ &
       & 'H ','He', &
       & 'Li','Be','B ','C ','N ','O ','F ','Ne', &
       & 'Na','Mg','Al','Si','P ','S ','Cl','Ar', &
       & 'K ','Ca', &
       & 'Sc','Ti','V ','Cr','Mn','Fe','Co','Ni','Cu','Zn', &
       &           'Ga','Ge','As','Se','Br','Kr', &
       & 'Rb','Sr', &
       & 'Y ','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd', &
       &           'In','Sn','Sb','Te','I ','Xe', &
       & 'Cs','Ba', &
       & 'La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb', &
       & 'Lu','Hf','Ta','W ','Re','Os','Ir','Pt','Au','Hg', &
       &           'Tl','Pb','Bi','Po','At','Rn', &
       & 'Fr','Ra', &
       & 'Ac','Th','Pa','U ','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No', &
       & 'Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn', &
       &           'Nh','Fl','Mc','Lv','Ts','Og' ]
Referenced by numbertosymbol().
symbollength
integer, parameter, public xtb_mctc_symbols::symbollength = 4
Maximum allowed length of element symbols.
Definition at line 37 of file symbols.f90.
    integer, parameter :: symbolLength = 4