My Project: test_hessian Module Reference
test_hessian Module Reference
Functions/Subroutines
subroutine, public run_hessian_test (arg)
subroutine test_gfn1_hessian
subroutine test_gfn2_hessian
Function/Subroutine Documentation
run_hessian_test()
subroutine, public test_hessian::run_hessian_test (character(len=*), intent(in) arg)
Definition at line 40 of file hessian.f90.
    character(len=*), intent(in) :: arg
    select case(arg)
    case("gfn1")
       call test_gfn1_hessian
    case("gfn2")
       call test_gfn2_hessian
    end select
References test_gfn1_hessian(), and test_gfn2_hessian().
Referenced by peeq_tester().
test_gfn1_hessian()
subroutine test_hessian::test_gfn1_hessian private
Definition at line 52 of file hessian.f90.
    integer, parameter :: nat = 3
    real(wp),parameter :: thr = 1.0e-7_wp
    character(len=*), parameter :: sym(nat) = ["O", "H", "H"]
    real(wp), parameter :: xyz(3, nat) = reshape([&
       & 0.00000000000000_wp,    0.00000000034546_wp,    0.18900383618455_wp, &
       & 0.00000000000000_wp,    1.45674735348811_wp,   -0.88650486059828_wp, &
       &-0.00000000000000_wp,   -1.45674735383357_wp,   -0.88650486086986_wp],&
       & shape(xyz))
    real(wp), parameter :: dipgrad_ref(3, 3*nat) = reshape([ &
       & -1.013452580143e+00_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       & -2.398345095286e-15_wp, -5.801057146788e-01_wp,  4.440892098501e-10_wp, &
       &  1.886892359658e-11_wp,  1.204196255680e-09_wp, -7.199230668276e-01_wp, &
       &  5.067262901419e-01_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       & -5.168463665021e-11_wp,  2.908278878443e-01_wp,  7.276368485520e-02_wp, &
       &  0.000000000000e+00_wp,  1.594757638403e-01_wp,  3.599430671297e-01_wp, &
       &  5.067262899828e-01_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       &  1.887034647398e-11_wp,  2.908278878482e-01_wp, -7.276368718667e-02_wp, &
       &  3.527704322735e-11_wp, -1.594757620026e-01_wp,  3.599430659085e-01_wp],&
       &  shape(dipgrad_ref))
    real(wp), parameter :: hessian_ref(3*nat, 3*nat) = reshape([ &
       &  9.642724315145e-05_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       & -4.821349241637e-05_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       & -4.821375073506e-05_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       & -1.193695511930e-16_wp,  6.543286738602e-01_wp, -1.383245460448e-09_wp, &
       &  2.351384649776e-16_wp, -3.271643375731e-01_wp,  2.415080663264e-01_wp, &
       & -1.157689137746e-16_wp, -3.271643362758e-01_wp, -2.415080649501e-01_wp, &
       & -7.979405595065e-11_wp, -8.671336189204e-10_wp,  3.969567976825e-01_wp, &
       &  9.617770183336e-11_wp,  1.933148104688e-01_wp, -1.984783990326e-01_wp, &
       & -1.638364588271e-11_wp, -1.933148095978e-01_wp, -1.984783986206e-01_wp, &
       & -1.362023380178e-03_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       &  4.418957886947e-05_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       &  1.317833801308e-03_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       & -4.323271238214e-11_wp, -3.270692709850e-01_wp,  1.934196079808e-01_wp, &
       &  4.723871392038e-11_wp,  3.486669886682e-01_wp, -2.174287435611e-01_wp, &
       & -4.006001538234e-12_wp, -2.159771769511e-02_wp,  2.400913555821e-02_wp, &
       &  0.000000000000e+00_wp,  2.414357451224e-01_wp, -1.984817451162e-01_wp, &
       &  0.000000000000e+00_wp, -2.173769120375e-01_wp,  1.883863080853e-01_wp, &
       &  0.000000000000e+00_wp, -2.405883308764e-02_wp,  1.009543702395e-02_wp, &
       & -1.362023712098e-03_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       &  1.317833873830e-03_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       &  4.418983826786e-05_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       & -7.979413971062e-11_wp, -3.270692701994e-01_wp, -1.934196070410e-01_wp, &
       &  9.617754838868e-11_wp, -2.159771765280e-02_wp, -2.400913556735e-02_wp, &
       & -1.638340867806e-11_wp,  3.486669878673e-01_wp,  2.174287426208e-01_wp, &
       & -1.828072800336e-11_wp, -2.414357440668e-01_wp, -1.984817441066e-01_wp, &
       &  2.446948471031e-11_wp,  2.405883338662e-02_wp,  1.009543671832e-02_wp, &
       & -6.188756706950e-12_wp,  2.173769106779e-01_wp,  1.883863073862e-01_wp],&
       &  shape(hessian_ref))
    real(wp), parameter :: step = 1.0e-6_wp
    type(TMolecule) :: mol
    type(TRestart) :: chk
    type(TEnvironment) :: env
    type(scc_results) :: res
    type(TxTBCalculator) :: calc
    integer :: i,j
    real(wp) :: energy, sigma(3, 3)
    real(wp) :: hl_gap
    real(wp),allocatable :: gradient(:,:), dipgrad(:,:), hessian(:,:)
    call init(env)
    call init(mol, sym, xyz)
    allocate(gradient(3,mol%n), dipgrad(3,3*mol%n), hessian(3*mol%n,3*mol%n))
    energy = 0.0_wp
    gradient = 0.0_wp
    call newxtbcalculator(env, mol, calc, method=1)
    call newwavefunction(env, mol, calc, chk)
    call calc%singlepoint(env, mol, chk, 2, .false., energy, gradient, sigma, &
       & hl_gap, res)
    dipgrad = 0.0_wp
    hessian = 0.0_wp
    ! omp parallel default(shared)
    call numdiff2(env, mol, chk, calc, step, hessian, dipgrad)
    ! omp end parallel
    do i = 1, size(dipgrad_ref, 2)
       do j = 1, size(dipgrad_ref, 1)
          call assert_close(dipgrad(j, i), dipgrad_ref(j, i), thr)
       end do
    end do
    do i = 1, size(hessian_ref, 2)
       do j = 1, size(hessian_ref, 1)
          call assert_close(hessian(j, i), hessian_ref(j, i), thr)
       end do
    end do
    call terminate(afail)
References assertion::afail, xtb_main_setup::newwavefunction(), xtb_main_setup::newxtbcalculator(), and terminate().
Referenced by run_hessian_test().
test_gfn2_hessian()
subroutine test_hessian::test_gfn2_hessian private
Definition at line 149 of file hessian.f90.
    integer, parameter :: nat = 3
    real(wp),parameter :: thr = 1.0e-7_wp
    character(len=*), parameter :: sym(nat) = ["O", "H", "H"]
    real(wp), parameter :: xyz(3, nat) = reshape([&
       & 0.00000000000000_wp,   -0.00000000077760_wp,    0.18829790750029_wp, &
       & 0.00000000000000_wp,    1.45987612440076_wp,   -0.88615189669760_wp, &
       &-0.00000000000000_wp,   -1.45987612362316_wp,   -0.88615189608629_wp],&
       & shape(xyz))
    real(wp), parameter :: dipgrad_ref(3, 3*nat) = reshape([ &
       & -8.113137336986e-01_wp,  5.356654180818e-10_wp,  0.000000000000e+00_wp, &
       & -4.581749290942e-11_wp, -4.121161465351e-01_wp, -4.996003610813e-10_wp, &
       &  5.570500822590e-16_wp, -7.377395210573e-10_wp, -4.838787099892e-01_wp, &
       &  4.056480094735e-01_wp, -2.200999955020e-09_wp,  1.665334536938e-09_wp, &
       & -3.988074658262e-11_wp,  2.055752062158e-01_wp,  9.503822412382e-02_wp, &
       & -3.969738621316e-11_wp,  1.480698268022e-01_wp,  2.434252440731e-01_wp, &
       &  4.056480099166e-01_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       & -6.052638931112e-11_wp,  2.055752051281e-01_wp, -9.503822262502e-02_wp, &
       &  1.674180515478e-11_wp, -1.480698285344e-01_wp,  2.434252415195e-01_wp],&
       &  shape(dipgrad_ref))
    real(wp), parameter :: hessian_ref(3*nat, 3*nat) = reshape([ &
       & -1.939578553890e-05_wp,  6.507635536734e-12_wp,  2.039452049081e-10_wp, &
       &  9.697594542869e-06_wp,  5.901447950110e-11_wp, -1.346714623499e-10_wp, &
       &  9.698190996037e-06_wp, -6.773553072603e-11_wp, -7.145569943037e-11_wp, &
       & -1.648255831783e-11_wp,  6.121988089582e-01_wp,  2.181719702902e-09_wp, &
       &  1.784659444500e-11_wp, -3.060994033735e-01_wp,  2.258521490017e-01_wp, &
       & -1.364036127169e-12_wp, -3.060994055863e-01_wp, -2.258521511869e-01_wp, &
       &  1.330615415687e-14_wp,  2.485255512685e-09_wp,  3.998109489554e-01_wp, &
       & -1.478661148333e-14_wp,  1.841542843085e-01_wp, -1.999054737643e-01_wp, &
       &  1.480457326447e-15_wp, -1.841542867939e-01_wp, -1.999054751878e-01_wp, &
       & -1.071178290455e-02_wp,  6.630362607819e-11_wp, -1.553932763715e-10_wp, &
       &  5.182610736054e-05_wp, -3.686287386451e-11_wp,  1.200855549981e-10_wp, &
       &  1.065995679719e-02_wp, -2.949707535518e-11_wp,  3.970551643549e-11_wp, &
       & -2.623112661213e-11_wp, -3.057148399989e-01_wp,  1.833996998222e-01_wp, &
       &  2.414732886753e-11_wp,  3.392228251096e-01_wp, -2.044438914287e-01_wp, &
       &  2.083797744602e-12_wp, -3.350798510988e-02_wp,  2.104419160463e-02_wp, &
       & -2.832253701727e-11_wp,  2.256129456682e-01_wp, -1.999899521472e-01_wp, &
       &  2.493748844816e-11_wp, -2.048926309476e-01_wp,  1.834977735563e-01_wp, &
       &  3.385048569112e-12_wp, -2.072031472126e-02_wp,  1.649217859268e-02_wp, &
       & -1.071178231982e-02_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       &  1.065995680557e-02_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       &  5.182551425220e-05_wp,  0.000000000000e+00_wp,  0.000000000000e+00_wp, &
       & -4.798341604929e-11_wp, -3.057148423748e-01_wp, -1.833997022848e-01_wp, &
       &  5.114468347305e-11_wp, -3.350798504577e-02_wp, -2.104419155262e-02_wp, &
       & -3.161267423758e-12_wp,  3.392228274191e-01_wp,  2.044438938336e-01_wp, &
       &  2.174439509959e-11_wp, -2.256129480723e-01_wp, -1.999899531846e-01_wp, &
       & -1.789465301866e-11_wp,  2.072031483689e-02_wp,  1.649217845321e-02_wp, &
       & -3.849742080923e-12_wp,  2.048926332339e-01_wp,  1.834977747311e-01_wp],&
       &  shape(hessian_ref))
    real(wp), parameter :: step = 1.0e-6_wp
    type(TMolecule) :: mol
    type(TRestart) :: chk
    type(TEnvironment) :: env
    type(scc_results) :: res
    type(TxTBCalculator) :: calc
    integer :: i,j
    real(wp) :: energy, sigma(3, 3)
    real(wp) :: hl_gap
    real(wp),allocatable :: gradient(:,:), dipgrad(:,:), hessian(:,:)
    call init(env)
    call init(mol, sym, xyz)
    allocate(gradient(3,mol%n), dipgrad(3,3*mol%n), hessian(3*mol%n,3*mol%n))
    energy = 0.0_wp
    gradient = 0.0_wp
    call newxtbcalculator(env, mol, calc, method=2)
    call newwavefunction(env, mol, calc, chk)
    call calc%singlepoint(env, mol, chk, 2, .false., energy, gradient, sigma, &
       & hl_gap, res)
    dipgrad = 0.0_wp
    hessian = 0.0_wp
    ! omp parallel default(shared)
    call numdiff2(env, mol, chk, calc, step, hessian, dipgrad)
    ! omp end parallel
    do i = 1, size(dipgrad_ref, 2)
       do j = 1, size(dipgrad_ref, 1)
          call assert_close(dipgrad(j, i), dipgrad_ref(j, i), thr)
       end do
    end do
    do i = 1, size(hessian_ref, 2)
       do j = 1, size(hessian_ref, 1)
          call assert_close(hessian(j, i), hessian_ref(j, i), thr)
       end do
    end do
    call terminate(afail)
References assertion::afail, xtb_main_setup::newwavefunction(), xtb_main_setup::newxtbcalculator(), and terminate().
Referenced by run_hessian_test().