My Project: xtb_api_molecule Module Reference
xtb_api_molecule Module Reference
API for dealing with molecular structure data.
Data Types
type vmolecule
Void pointer to molecular structure data.
Functions/Subroutines
type(c_ptr) function, public newmolecule_api (venv, natoms, numbers, positions, charge, uhf, lattice, periodic)
subroutine, public delmolecule_api (vmol)
subroutine, public updatemolecule_api (venv, vmol, positions, lattice)
Variables
integer, parameter maxelem = 118
Maximum accepted atomic number, actual calculator might accept less.
Detailed Description
API for dealing with molecular structure data.
Function/Subroutine Documentation
delmolecule_api()
subroutine, public xtb_api_molecule::delmolecule_api (type(c_ptr), intent(inout) vmol)
Definition at line 96 of file molecule.f90.
    type(c_ptr), intent(inout) :: vmol
    type(VMolecule), pointer :: mol
    if (c_associated(vmol)) then
       call c_f_pointer(vmol, mol)
       call checkglobalenv
       deallocate(mol)
       vmol = c_null_ptr
    end if
References xtb_api_utils::checkglobalenv().
newmolecule_api()
type(c_ptr) function, public xtb_api_molecule::newmolecule_api (type(c_ptr), value venv, integer(c_int), intent(in) natoms, integer(c_int), dimension(natoms), intent(in) numbers, real(c_double), dimension(3, natoms), intent(in) positions, real(c_double), intent(in) charge, integer(c_int), intent(in) uhf, real(c_double), dimension(3, 3), intent(in) lattice, logical(c_bool), dimension(3), intent(in) periodic)
Definition at line 45 of file molecule.f90.
    character(len=*), parameter :: source = 'xtb_api_newMolecule'
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    integer(c_int), intent(in) :: natoms
    integer(c_int), intent(in) :: numbers(natoms)
    real(c_double), intent(in) :: positions(3, natoms)
    real(c_double), intent(in) :: charge
    integer(c_int), intent(in) :: uhf
    real(c_double), intent(in) :: lattice(3, 3)
    logical(c_bool), intent(in) :: periodic(3)
    type(VMolecule), pointer :: mol
    type(c_ptr) :: vmol
    integer(c_int) :: status
    vmol = c_null_ptr
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (natoms <= 0) then
          call env%ptr%error("Number of atoms must be positive", source)
          return
       end if
       if (any(numbers <= 0) .or. any(numbers > maxelem)) then
          call env%ptr%error("Invalid atomic number present", source)
          return
       end if
       allocate(mol)
       mol%ptr = tmolecule(natoms, numbers, positions, charge, uhf, &
          & lattice, periodic)
       status = verifymolecule(mol%ptr)
       if (status /= 0_c_int) then
          deallocate(mol)
          call env%ptr%error("Could not generate molecular structure", source)
          return
       end if
       vmol = c_loc(mol)
    end if
References xtb_api_utils::checkglobalenv(), maxelem, and xtb_api_utils::verifymolecule().
updatemolecule_api()
subroutine, public xtb_api_molecule::updatemolecule_api (type(c_ptr), value venv, type(c_ptr), value vmol, real(c_double), dimension(3, *), intent(in) positions, real(c_double), dimension(3, 3), intent(in), optional lattice)
Definition at line 112 of file molecule.f90.
    character(len=*), parameter :: source = 'xtb_api_updateMolecule'
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vmol
    type(VMolecule), pointer :: mol
    real(c_double), intent(in) :: positions(3, *)
    real(c_double), intent(in), optional :: lattice(3, 3)
    real(wp) :: latvecs(3, 3)
    integer(c_int) :: status
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vmol)) then
          call env%ptr%error("Molecular structure data is not allocated", source)
          return
       end if
       call c_f_pointer(vmol, mol)
       if (mol%ptr%n <= 0 .or. mol%ptr%nid <= 0 .or. .not.allocated(mol%ptr%at) &
          & .or. .not.allocated(mol%ptr%id) .or. .not.allocated(mol%ptr%xyz)) then
          call env%ptr%error("Invalid molecular structure data provided", source)
          return
       end if
       mol%ptr%xyz(:, :) = positions(1:3, 1:mol%ptr%n)
       if (present(lattice)) then
          mol%ptr%lattice(:, :) = lattice(1:3, 1:3)
       end if
       call mol%ptr%update
       status = verifymolecule(mol%ptr)
       if (status /= 0_c_int) then
          call env%ptr%error("Could not update molecular structure", source)
          return
       end if
    end if
References xtb_api_utils::checkglobalenv(), and xtb_api_utils::verifymolecule().
Variable Documentation
maxelem
integer, parameter xtb_api_molecule::maxelem = 118 private
Maximum accepted atomic number, actual calculator might accept less.
Definition at line 39 of file molecule.f90.
    integer, parameter :: maxElem = 118
Referenced by newmolecule_api().