My Project: xtb_lineardep Module Reference
xtb_lineardep Module Reference
Functions/Subroutines
subroutine cholesky (iunit, printl, ndim, A, fail)
subroutine renorm (ndim, A)
subroutine canorthog (iunit, ndim, S, X, newdim, printl, fail)
subroutine canorthog2 (ndim, S, U, ssq, fail)
subroutine sorteigen (ndim, s, U)
subroutine lidepcut (iunit, ndim, s, U, sisq, newdim, printl)
subroutine buildtrafox (ndim, ssq, U, sisq, newdim, X)
subroutine orthgsolve (full, ndim, cutdim, ihomo, acc, H, S, X, P, e, fail)
subroutine orthgsolve2 (full, ndim, cutdim, ihomo, acc, H, S, X, P, e, fail)
Variables
logical orthog = .false.
Function/Subroutine Documentation
buildtrafox()
subroutine xtb_lineardep::buildtrafox (integer, intent(in) ndim, real(wp), dimension(ndim), intent(in) ssq, real(wp), dimension(ndim,ndim), intent(in) U, real(wp), dimension(ndim), intent(in) sisq, integer, intent(in) newdim, real(wp), dimension(ndim,ndim), intent(out) X)
Definition at line 423 of file lidep.f90.
     implicit none
    !---
     integer,intent(in)     :: ndim
     integer,intent(in)     :: newdim
     real(wp),intent(in)    :: ssq(ndim)
     real(wp),intent(in)    :: U(ndim,ndim)
     real(wp),intent(in)    :: sisq(ndim)
     real(wp),intent(out)   :: X(ndim,ndim)
    !---
     integer :: i,j,k,l
    !---
     x=0.0d0
     do i=1,ndim
      do j=1,newdim
       x(i,j)=u(i,j) * sisq(j)
      enddo
     enddo
    !---
     return
Referenced by canorthog().
canorthog()
subroutine xtb_lineardep::canorthog (integer, intent(in) iunit, integer, intent(in) ndim, real(wp), dimension(ndim,ndim), intent(in) S, real(wp), dimension(ndim,ndim), intent(out) X, integer, intent(out) newdim, logical, intent(in) printl, logical, intent(out) fail)
Definition at line 162 of file lidep.f90.
     implicit none
    !---
     integer,intent(in)   :: iunit
     integer,intent(in)   :: ndim
     real(wp),intent(in)  :: S(ndim,ndim)
     real(wp),intent(out) :: X(ndim,ndim)
     logical,intent(out)  :: fail
     integer,intent(out)  :: newdim
     logical,intent(in)   :: printl
    !---
     integer :: i
     real(wp),allocatable :: U(:,:)
     real(wp),allocatable :: ssq(:)
     real(wp),allocatable :: sisq(:)
     real(wp),allocatable :: P(:,:),P2(:,:)
    !---
     allocate(u(ndim,ndim),ssq(ndim),sisq(ndim))
     fail=.false.
     x=0.0d0
    !--- diagonalize overlap and get eigenvectors U and eigenvalues s
     if(printl) &
     & write(iunit,'(2x,a)',advance='no')'Diagonalization of the Overlap   ...'
     call canorthog2(ndim,s,u,ssq,fail)
     if(fail)then
        if(printl) write(iunit,'(2x,a)')'failed.'
        return
     else
       if(printl) write(iunit,'(2x,a)')'done.'
     endif
    !--- restructure U and ssq
     call sorteigen(ndim,ssq,u)
    !--- cut-off small eigenvalues and build the inverse square root s**(-1/2)
     newdim=ndim
     call lidepcut(iunit,ndim,ssq,u,sisq,newdim,printl)
     !call prmat(6,e,nbf,1,"eigenvalues")
     !call prmat(6,U,ndim,ndim,"U")
    !--- sanity check stuff
     !newdim=ndim
     !do i=1,ndim
     !   sisq(i)=1.0d0 / sqrt(ssq(i))
     !enddo
    !--- get X and its new dimensions
     if(printl) &
     & write(iunit,'(2x,a)',advance='no')'Building transformation matrix X ...'
     call buildtrafox(ndim,ssq,u,sisq,newdim,x)
     !call prmat(6,X,ndim,ndim,"X")
     if(printl) then
      write(iunit,'(2x,a)')'done.'
      write(iunit,'(a)')
     endif
    !--- more sanity check stuff
     !call prmat(6,X,ndim,ndim,"Trafo X")
     !allocate(P(ndim,ndim),P2(ndim,ndim))
     !call gemm('N','N',ndim,newdim,ndim,1.0d0,S,ndim,X,ndim,0.0d0,P,ndim)
     !call gemm('T','N',ndim,ndim,newdim,1.0d0,X,ndim,P,ndim,0.0d0,P2,ndim)
     !call prmat(6,P2,ndim,ndim,"X**T*S*X")
     !deallocate(P2,P)
     !stop
     deallocate(sisq,ssq,u)
     return
References buildtrafox(), canorthog2(), lidepcut(), and sorteigen().
Referenced by xtb_peeq::peeq().
canorthog2()
subroutine xtb_lineardep::canorthog2 (integer, intent(in) ndim, real(wp), dimension(ndim,ndim), intent(in) S, real(wp), dimension(ndim,ndim), intent(out) U, real(wp), dimension(ndim), intent(out) ssq, logical, intent(out) fail)
Definition at line 245 of file lidep.f90.
     implicit none
    !---
     integer,intent(in)   :: ndim
     real(wp),intent(in)  :: S(ndim,ndim)
     real(wp),intent(out) :: U(ndim,ndim)
     real(wp),intent(out) :: ssq(ndim)
     logical,intent(out)  :: fail
    !---
     integer :: ierr
     integer :: lwork
     real(wp),dimension(1) :: wdim
     real(wp),allocatable  :: work(:)
    !---
     fail=.false.
     u=s
     ssq=0.0d0
    !--- determine optimal work space
    !--- only calculates the optimal size of the 'work' array
     call lapack_syev('v','l',ndim,u,ndim,ssq,wdim,-1,ierr)
     if(ierr /= 0)then
        fail=.true.
        return
     endif
     lwork=int(wdim(1))
     allocate(work(lwork))
    !--- diagonalize overlap s = U**T*S*U
     call lapack_syev('v','l',ndim,u,ndim,ssq,work,lwork,ierr)
     if(ierr /= 0)then
        fail=.true.
        return
     endif
     !!write(iunit,*) ssq
     return
References true().
Referenced by canorthog().
cholesky()
subroutine xtb_lineardep::cholesky (integer, intent(in) iunit, logical, intent(in) printl, integer, intent(in) ndim, real(wp), dimension(ndim,ndim), intent(in) A, logical, intent(out) fail)
Definition at line 64 of file lidep.f90.
     implicit none
   !---
     integer,intent(in)  :: iunit
     integer,intent(in)  :: ndim
     real(wp),intent(in) :: A(ndim,ndim)
     logical,intent(out) :: fail
     logical,intent(in)  :: printl
   !---
     integer :: ierr
     real(wp),allocatable  :: U(:,:)
     if(printl) &
     & write(iunit,'(2x,a)',advance='no')'Checking positiv definite overlap ...'
   !---
     allocate(u(ndim,ndim))
     fail=.false.
     u=a
     call dpotrf('U',ndim,u,ndim,ierr) !LAPACK routine  A = U**T*U
                                       !on input U=A, retruns U
     if(printl) then
       write(iunit,'(2x,a)')'done.'
       write(iunit,*)
     endif
     if(ierr /= 0) then
       fail=.true.
       if(printl)then
       write(iunit,'(a)') '**** WARNING ****'
       write(iunit,'(a)') ' Cholesky factorization of the overlap failed!'
       write(iunit,'(a)') ' It is possible that there are near linear dependecies in the basis.'
       write(iunit,'(a)') ' Therefore PEEQ will work with an orthogonal basis by using'
       write(iunit,'(a)') ' canonical orthogonalization.'
       write(iunit,'(a)') '**** WARNING ****'
       write(iunit,'(a)')
       endif
     endif
     deallocate(u)
     return
References true().
Referenced by xtb_peeq::peeq().
lidepcut()
subroutine xtb_lineardep::lidepcut (integer, intent(in) iunit, integer, intent(in) ndim, real(wp), dimension(ndim), intent(inout) s, real(wp), dimension(ndim,ndim), intent(inout) U, real(wp), dimension(ndim), intent(out) sisq, integer, intent(out) newdim, logical, intent(in) printl)
Definition at line 353 of file lidep.f90.
     implicit none
    !---
     integer,intent(in)     :: iunit
     integer,intent(in)     :: ndim
     real(wp),intent(inout) :: s(ndim)
     real(wp),intent(inout) :: U(ndim,ndim)
     real(wp),intent(out)   :: sisq(ndim)
     integer,intent(out)    :: newdim
     logical,intent(in)     :: printl
    !---
     integer  :: i,j,imax
     real(wp) :: eigen
     real(wp) :: ehig,elow
    !---
     !lidethr=1.0d-4
     sisq=0.0d0
     newdim=ndim
    !--- min and max eigenvalues of the overlap
     ehig = s(1)
     elow = s(ndim)
    !--- cut eigenvalues and eigenvectors that are below the predefined threshold
     if(printl) &
     & write(iunit,'(2x,a)',advance='no')'Cutting off small eigenvalues    ...'
     do i=1,ndim
       eigen = s(i)
       if(eigen > lidethr) then
         eigen = sqrt(eigen)
         s(i) = eigen
         sisq(i) = 1.0d0 / eigen
       else
         s(i) = 0.0d0
         sisq(i) = 0.0d0
         u(1:ndim,i) = 0.0d0
         newdim=newdim-1
       endif
     enddo
     if(printl)then
     write(iunit,'(2x,a)')'done.'
    !--- some printout
     write(iunit,'(2x,a)')'Maximum eigenvalues of the overlap:'
     write(iunit,'(4x,a,f10.4)')'Largest eigenvalue              : ',ehig
     write(iunit,'(4x,a,f10.4)')'Smallest eigenvalue             : ',elow
     write(iunit,'(2x,a,e14.4)')'Eigenvalue cut-off threshold      : ',lidethr
     write(iunit,'(2x,a,i6)')   'Initial number of eigenvectors    : ',ndim
     write(iunit,'(2x,a,i6)')   'Removed eigenvectors              : ',ndim-newdim
     write(iunit,'(2x,a,i6)')   'Number of remaining eigenvectors  : ',newdim
     write(iunit,'(4x,a,f10.4)')'New smallest eigenvalue         : ',s(newdim)**2
     endif
    !---
     return
References xtb_setparam::lidethr.
Referenced by canorthog().
orthgsolve()
subroutine xtb_lineardep::orthgsolve (logical, intent(in) full, integer, intent(in) ndim, integer, intent(in) cutdim, integer, intent(in) ihomo, real(wp), intent(in) acc, real(wp), dimension(ndim,ndim), intent(inout) H, real(wp), dimension(ndim,ndim), intent(in) S, real(wp), dimension(ndim,ndim), intent(inout) X, real(wp), dimension(ndim,ndim), intent(out) P, real(wp), dimension(ndim), intent(out) e, logical, intent(out) fail)
Definition at line 473 of file lidep.f90.
    implicit none
    integer, intent(in)   :: ndim
    integer, intent(in)   :: cutdim
    logical, intent(in)   :: full
    integer, intent(in)   :: ihomo
    real(wp),intent(inout):: H(ndim,ndim)
    real(wp),intent(in)   :: S(ndim,ndim)
    real(wp),intent(inout):: X(ndim,ndim)
    real(wp),intent(out)  :: P(ndim,ndim)
    real(wp),intent(out)  :: e(ndim)
    real(wp),intent(in)   :: acc
    logical, intent(out)  :: fail
    integer :: i,j,info,lwork,liwork,nfound,iu
    integer :: nbf,xbf
    integer, allocatable :: iwork(:),ifail(:)
    real(wp),allocatable :: aux  (:)
    real(wp),allocatable :: Haux(:,:),Paux(:,:)
    fail =.false.
   !--- DIAG IN ORTHOGONAL BASIS WITH X=U*s^-1/2 TRAFO
     nbf = ndim
     xbf = cutdim
     lwork  = 1 + 6*nbf + 2*nbf**2
     allocate (aux(lwork))
   !--- calculate F'=X**T*F*X
     call blas_gemm('n','n',nbf,xbf,nbf,1.0d0,h,nbf,x,nbf,0.0d0,p,nbf)
     call blas_gemm('t','n',xbf,xbf,nbf,1.0d0,x,nbf,p,nbf,0.0d0,h,xbf)
   !--- Caluclate C' and  from F'*C' = C'*
     call lapack_syev('v','u',xbf,h,xbf,e,aux,lwork,info)
     if(info.ne.0)then
        fail=.true.
        return
     endif
   !--- calculate C = X*C'
     p=0.0d0
     call blas_gemm('N','N',nbf,xbf,xbf,1.0d0,x,nbf,h,xbf,0.0d0,p,nbf)
     h=p
     deallocate(aux)
     return
References true().
orthgsolve2()
subroutine xtb_lineardep::orthgsolve2 (logical, intent(in) full, integer, intent(in) ndim, integer, intent(in) cutdim, integer, intent(in) ihomo, real(wp), intent(in) acc, real(wp), dimension(ndim,ndim), intent(inout) H, real(wp), dimension(ndim,ndim), intent(in) S, real(wp), dimension(ndim,ndim), intent(inout) X, real(wp), dimension(ndim,ndim), intent(out) P, real(wp), dimension(ndim), intent(out) e, logical, intent(out) fail)
Definition at line 520 of file lidep.f90.
    implicit none
    integer, intent(in)   :: ndim
    integer, intent(in)   :: cutdim
    logical, intent(in)   :: full
    integer, intent(in)   :: ihomo
    real(wp),intent(inout):: H(ndim,ndim)
    real(wp),intent(in)   :: S(ndim,ndim)
    real(wp),intent(inout):: X(ndim,ndim)
    real(wp),intent(out)  :: P(ndim,ndim)
    real(wp),intent(out)  :: e(ndim)
    real(wp),intent(in)   :: acc
    logical, intent(out)  :: fail
    integer :: i,j,info,lwork,liwork,nfound,iu
    integer :: nbf,xbf
    integer, allocatable :: iwork(:),ifail(:)
    real(wp),allocatable :: aux  (:)
    real(wp),allocatable :: Haux(:,:),Paux(:,:),Xaux(:,:)
    fail =.false.
   !--- DIAG IN ORTHOGONAL BASIS WITH X=U*s^-1/2 TRAFO
     nbf = ndim
     xbf = cutdim
     lwork  = 1 + 6*nbf + 2*nbf**2
     allocate (aux(lwork))
   !--- calculate F'=X**T*F*X
     allocate(xaux(nbf,xbf),paux(nbf,xbf))
     xaux=x(:,1:xbf)
     call blas_gemm('n','n',nbf,xbf,nbf,1.0d0,h,nbf,xaux,nbf,0.0d0,paux,nbf)
     allocate(haux(xbf,xbf))
     call blas_gemm('t','n',xbf,xbf,nbf,1.0d0,xaux,nbf,paux,nbf,0.0d0,haux,xbf)
   !--- Caluclate C' and  from F'*C' = C'*
     call lapack_syev('v','u',xbf,haux,xbf,e,aux,lwork,info)
     !call prmat(6,e,nbf,1,"eigenvalues")
     if(info.ne.0)then
        fail=.true.
        return
     endif
   !--- calculate C = X*C'
     p=0.0d0
     call blas_gemm('N','N',nbf,xbf,xbf,1.0d0,xaux,nbf,haux,xbf,0.0d0,p,nbf)
     h=p
     deallocate(haux,paux,xaux)
     deallocate(aux)
     return
References true().
Referenced by xtb_peeq::peeq().
renorm()
subroutine xtb_lineardep::renorm (integer, intent(in) ndim, real(wp), dimension(ndim,ndim), intent(inout) A)
Definition at line 118 of file lidep.f90.
     implicit none
   !---
     integer,intent(in)  :: ndim
     real(wp),intent(inout) :: A(ndim,ndim)
   !---
     integer :: ierr,i,j,k,l
     !do i=1,ndim
     !   A(:,i)=A(:,i)/A(i,i)
     !enddo
     do i=1,ndim
       do j=1,i-1
         a(i,j)=a(i,j)/a(i,i)
         a(j,i)=a(i,j)
       enddo
     enddo
     return
Referenced by xtb_peeq::peeq().
sorteigen()
subroutine xtb_lineardep::sorteigen (integer, intent(in) ndim, real(wp), dimension(ndim), intent(inout) s, real(wp), dimension(ndim,ndim), intent(inout) U)
Definition at line 301 of file lidep.f90.
     implicit none
    !---
     integer,intent(in)     :: ndim
     real(wp),intent(inout) :: s(ndim)
     real(wp),intent(inout) :: U(ndim,ndim)
    !---
     integer  :: i,j,k,l,imax
     real(wp) :: smax
     real(wp) :: Umax
    !---
     imax=ndim-1
     do i=1,imax
       smax=s(i)
       k=i
       l=i+1
       do j=l,ndim
          if(s(j).le.smax) cycle
          k=j
          smax=s(j)
       enddo
       umax=s(i)
       s(i)=s(k)
       s(k)=umax
       do j=1,ndim
          umax=u(j,i)
          u(j,i)=u(j,k)
          u(j,k)=umax
       enddo
     enddo
   !---
     return
Referenced by canorthog().
Variable Documentation
orthog
logical xtb_lineardep::orthog = .false.
Definition at line 41 of file lidep.f90.
    logical  :: orthog = .false.       ! global logical if the orthogonal basis should be used
Referenced by xtb_peeq::peeq().