My Project: xtb_api_results Module Reference
xtb_api_results Module Reference
API for dealing with the calculation results.
Data Types
type vresults
Void pointer to wavefunction and result objects.
Functions/Subroutines
type(c_ptr) function, public newresults_api ()
Create new singlepoint results object.
subroutine, public delresults_api (vres)
Delete singlepoint results object.
type(c_ptr) function, public copyresults_api (vold)
Create copy from a singlepoint results object.
subroutine, public getenergy_api (venv, vres, dptr)
Query singlepoint results object for energy.
subroutine, public getgradient_api (venv, vres, dptr)
Query singlepoint results object for gradient.
subroutine, public getvirial_api (venv, vres, dptr)
Query singlepoint results object for virial.
subroutine, public getdipole_api (venv, vres, dptr)
Query singlepoint results object for dipole moment.
subroutine, public getcharges_api (venv, vres, dptr)
Query singlepoint results object for partial charges.
subroutine, public getbondorders_api (venv, vres, dptr)
Query singlepoint results object for bond orders.
subroutine, public getnao_api (venv, vres, iptr)
Query singlepoint results object for bond orders.
subroutine, public getorbitaleigenvalues_api (venv, vres, dptr)
Query singlepoint results object for orbital energies.
subroutine, public getorbitaloccupations_api (venv, vres, dptr)
Query singlepoint results object for occupation numbers.
subroutine, public getorbitalcoefficients_api (venv, vres, dptr)
Query singlepoint results object for orbital coefficients.
Detailed Description
API for dealing with the calculation results.
Function/Subroutine Documentation
copyresults_api()
type(c_ptr) function, public xtb_api_results::copyresults_api (type(c_ptr), value vold)
Create copy from a singlepoint results object.
Definition at line 82 of file results.f90.
    type(VResults), pointer :: res
    type(c_ptr) :: vres
    type(VResults), pointer :: old
    type(c_ptr), value :: vold
    vres = c_null_ptr
    if (c_associated(vold)) then
       call c_f_pointer(vold, old)
       call checkglobalenv
       allocate(res, source=old)
       vres = c_loc(res)
    end if
References xtb_api_utils::checkglobalenv().
delresults_api()
subroutine, public xtb_api_results::delresults_api (type(c_ptr), intent(inout) vres)
Delete singlepoint results object.
Definition at line 65 of file results.f90.
    type(c_ptr), intent(inout) :: vres
    type(VResults), pointer :: res
    call checkglobalenv
    if (c_associated(vres)) then
       call c_f_pointer(vres, res)
       deallocate(res)
       vres = c_null_ptr
    end if
References xtb_api_utils::checkglobalenv().
getbondorders_api()
subroutine, public xtb_api_results::getbondorders_api (type(c_ptr), value venv, type(c_ptr), value vres, real(c_double), dimension(*), intent(inout) dptr)
Query singlepoint results object for bond orders.
Definition at line 263 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getBondOrders"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    real(c_double), intent(inout) :: dptr(*)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (.not.allocated(res%chk)) then
          call env%ptr%error("Bond orders are not available in results", source)
          return
       end if
       dptr(1:size(res%chk%wfn%wbo)) = reshape(res%chk%wfn%wbo, [size(res%chk%wfn%wbo)])
    end if
References xtb_api_utils::checkglobalenv().
getcharges_api()
subroutine, public xtb_api_results::getcharges_api (type(c_ptr), value venv, type(c_ptr), value vres, real(c_double), dimension(*), intent(inout) dptr)
Query singlepoint results object for partial charges.
Definition at line 231 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getCharges"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    real(c_double), intent(inout) :: dptr(*)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (.not.allocated(res%chk)) then
          call env%ptr%error("Partial charges are not available in results", source)
          return
       end if
       dptr(1:size(res%chk%wfn%q)) = res%chk%wfn%q
    end if
References xtb_api_utils::checkglobalenv().
getdipole_api()
subroutine, public xtb_api_results::getdipole_api (type(c_ptr), value venv, type(c_ptr), value vres, real(c_double), dimension(3), intent(inout) dptr)
Query singlepoint results object for dipole moment.
Definition at line 199 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getDipole"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    real(c_double), intent(inout) :: dptr(3)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (.not.allocated(res%dipole)) then
          call env%ptr%error("Dipole moment is not available in results", source)
          return
       end if
       dptr(1:3) = res%dipole
    end if
References xtb_api_utils::checkglobalenv().
getenergy_api()
subroutine, public xtb_api_results::getenergy_api (type(c_ptr), value venv, type(c_ptr), value vres, real(c_double), intent(inout) dptr)
Query singlepoint results object for energy.
Definition at line 103 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getEnergy"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    real(c_double), intent(inout) :: dptr
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (.not.allocated(res%energy)) then
          call env%ptr%error("Energy is not available in results", source)
          return
       end if
       dptr = res%energy
    end if
References xtb_api_utils::checkglobalenv().
getgradient_api()
subroutine, public xtb_api_results::getgradient_api (type(c_ptr), value venv, type(c_ptr), value vres, real(c_double), dimension(3, *), intent(inout) dptr)
Query singlepoint results object for gradient.
Definition at line 135 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getGradient"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    real(c_double), intent(inout) :: dptr(3, *)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (.not.allocated(res%gradient)) then
          call env%ptr%error("Gradient is not available in results", source)
          return
       end if
       dptr(1:3, 1:size(res%gradient, 2)) = res%gradient
    end if
References xtb_api_utils::checkglobalenv().
getnao_api()
subroutine, public xtb_api_results::getnao_api (type(c_ptr), value venv, type(c_ptr), value vres, integer(c_int), intent(inout) iptr)
Query singlepoint results object for bond orders.
Definition at line 295 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getNao"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    integer(c_int), intent(inout) :: iptr
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (allocated(res%chk)) then
          iptr = res%chk%wfn%nao
       else
          iptr = 0
       end if
    end if
References xtb_api_utils::checkglobalenv().
getorbitalcoefficients_api()
subroutine, public xtb_api_results::getorbitalcoefficients_api (type(c_ptr), value venv, type(c_ptr), value vres, real(c_double), dimension(*), intent(inout) dptr)
Query singlepoint results object for orbital coefficients.
Definition at line 392 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getOrbitalCoefficients"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    real(c_double), intent(inout) :: dptr(*)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (.not.allocated(res%chk)) then
          call env%ptr%error("Orbital coefficients are not available in results", &
             & source)
          return
       end if
       dptr(1:size(res%chk%wfn%C)) = reshape(res%chk%wfn%C, [size(res%chk%wfn%C)])
    end if
References xtb_api_utils::checkglobalenv().
getorbitaleigenvalues_api()
subroutine, public xtb_api_results::getorbitaleigenvalues_api (type(c_ptr), value venv, type(c_ptr), value vres, real(c_double), dimension(*), intent(inout) dptr)
Query singlepoint results object for orbital energies.
Definition at line 326 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getOrbitalEigenvalues"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    real(c_double), intent(inout) :: dptr(*)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (.not.allocated(res%chk)) then
          call env%ptr%error("Orbital eigenvalues are not available in results", &
             & source)
          return
       end if
       dptr(1:size(res%chk%wfn%emo)) = res%chk%wfn%emo * evtoau
    end if
References xtb_api_utils::checkglobalenv(), and xtb_mctc_convert::evtoau.
getorbitaloccupations_api()
subroutine, public xtb_api_results::getorbitaloccupations_api (type(c_ptr), value venv, type(c_ptr), value vres, real(c_double), dimension(*), intent(inout) dptr)
Query singlepoint results object for occupation numbers.
Definition at line 359 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getOrbitalOccupations"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    real(c_double), intent(inout) :: dptr(*)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (.not.allocated(res%chk)) then
          call env%ptr%error("Occupation numbers are not available in results", &
             & source)
          return
       end if
       dptr(1:size(res%chk%wfn%focc)) = res%chk%wfn%focc
    end if
References xtb_api_utils::checkglobalenv().
getvirial_api()
subroutine, public xtb_api_results::getvirial_api (type(c_ptr), value venv, type(c_ptr), value vres, real(c_double), dimension(3, 3), intent(inout) dptr)
Query singlepoint results object for virial.
Definition at line 167 of file results.f90.
    character(len=*), parameter :: source = "xtb_api_getVirial"
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    real(c_double), intent(inout) :: dptr(3, 3)
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vres)) then
          call env%ptr%error("Results object is not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       if (.not.allocated(res%sigma)) then
          call env%ptr%error("Virial is not available in results", source)
          return
       end if
       dptr(1:3, 1:3) = res%sigma
    end if
References xtb_api_utils::checkglobalenv().
newresults_api()
type(c_ptr) function, public xtb_api_results::newresults_api
Create new singlepoint results object.
Definition at line 51 of file results.f90.
    type(VResults), pointer :: res
    type(c_ptr) :: vres
    call checkglobalenv
    allocate(res)
    vres = c_loc(res)
References xtb_api_utils::checkglobalenv().