My Project: xtb_mctc_thresholds Module Reference
xtb_mctc_thresholds Module Reference
Numerical thresholds shared between multiple algorithms.
Variables
real(wp), parameter tolsamedist = 1.0e-5_wp
Tolerance for atomic distances.
real(wp), parameter tolsamedist2 = tolSameDist**2
Tolerance for atomic square distances.
real(wp), parameter minneighdist = 1.0e-2_wp
Minimal distance between neighbours.
real(wp), parameter minneighdist2 = minNeighDist**2
Minimal square distance between neighbours.
Detailed Description
Numerical thresholds shared between multiple algorithms.
Variable Documentation
minneighdist
real(wp), parameter xtb_mctc_thresholds::minneighdist = 1.0e-2_wp
Minimal distance between neighbours.
Definition at line 32 of file thresholds.f90.
    real(wp), parameter :: minNeighDist = 1.0e-2_wp
minneighdist2
real(wp), parameter xtb_mctc_thresholds::minneighdist2 = minNeighDist**2
Minimal square distance between neighbours.
Definition at line 35 of file thresholds.f90.
    real(wp), parameter :: minNeighDist2 = minneighdist**2
Referenced by xtb_type_wignerseitzcell::generate(), and xtb_type_neighbourlist::generatesequential().
tolsamedist
real(wp), parameter xtb_mctc_thresholds::tolsamedist = 1.0e-5_wp
Tolerance for atomic distances.
Definition at line 26 of file thresholds.f90.
    real(wp), parameter :: tolSameDist = 1.0e-5_wp
tolsamedist2
real(wp), parameter xtb_mctc_thresholds::tolsamedist2 = tolSameDist**2
Tolerance for atomic square distances.
Definition at line 29 of file thresholds.f90.
    real(wp), parameter :: tolSameDist2 = tolsamedist**2
Referenced by xtb_type_wignerseitzcell::generate(), xtb_type_latticepoint::generatepbc3d(), xtb_type_latticepoint::getlatticepoints(), xtb_type_neighbourlist::getneighsone(), and xtb_type_neighbourlist::sort().