My Project: xtb_gfnff_shake Module Reference
xtb_gfnff_shake Module Reference
Functions/Subroutines
subroutine init_shake (nat, at, xyz, topo)
subroutine do_shake (nat, xyzo, xyz, velo, acc, mass, tstep)
Variables
integer shake_mode
integer ncons = 0
integer nconsu = 0
integer, dimension(:,:), allocatable conslist
real *8, dimension(:), allocatable distcons
real *8, dimension(:,:), allocatable dro
real *8, dimension(:,:), allocatable dr
integer, parameter maxcyc = 5000
real *8, parameter tolshake = 1.d-6
Function/Subroutine Documentation
do_shake()
subroutine xtb_gfnff_shake::do_shake (integer nat, real*8, dimension(3,nat) xyzo, real*8, dimension(3,nat) xyz, real*8, dimension(3,nat) velo, real*8, dimension(3,nat) acc, real*8, dimension(nat) mass, real*8 tstep)
Definition at line 60 of file shake_module.f90.
        implicit none
        integer nat
        real*8 xyzo(3,nat),xyz(3,nat),velo(3,nat),acc(3,nat),mass(nat)
        real*8 virsh(3),tstep
        real*8 xyzt(3,nat)
        real*8 vel(3)
        integer i,icyc
        integer iat,jat
        logical conv
        real*8 maxdev
        real*8 r, dev,dist,denom
        real*8 gcons, rmi, rmj
        real*8 tau1,tau2
        integer jmaxdev
         conv = .false.
         icyc = 0
         xyzt = xyz
         tau1 = 1.d0/tstep
         tau2 = tau1*tau1
         do i = 1, ncons
          iat = conslist(1,i)
          jat = conslist(2,i)
          dro(1:3,i) = xyzo(1:3,iat) - xyzo(1:3,jat)
         enddo
 !100     continue
         do  while (.not.conv.and.icyc.le.maxcyc) !goto 100
           maxdev = 0.d0
           do i = 1, ncons
            iat = conslist(1,i)
            jat = conslist(2,i)
            dr(1:3,i) = xyzt(1:3,iat) - xyzt(1:3,jat)
            dr(4,i)   = dr(1,i)**2 + dr(2,i)**2 + dr(3,i)**2
            dist = distcons(i)
            dev = abs(dr(4,i) - dist) / dist
            if(dev.gt.maxdev) then
             maxdev = dev
             jmaxdev = i
            endif
           enddo
           if(maxdev.lt.tolshake) conv = .true.
           if(.not.conv) then
            do i = 1, ncons
             iat = conslist(1,i)
             jat = conslist(2,i)
             dist = distcons(i)
             rmi = 1.d0/mass(iat)
             rmj = 1.d0/mass(jat)
             denom = 2.d0*(rmi+rmj)*(dr(1,i)*dro(1,i)+dr(2,i)*dro(2,i)+&
      &                              dr(3,i)*dro(3,i))
             gcons = (dist-dr(4,i))/denom
             xyzt(1:3,iat) = xyzt(1:3,iat) + rmi*gcons*dro(1:3,i)
             xyzt(1:3,jat) = xyzt(1:3,jat) - rmj*gcons*dro(1:3,i)
            enddo
           endif
           icyc = icyc + 1
         end do
         !if(.not.conv.and.icyc.le.maxcyc) goto 100
         if(conv) then
          velo = velo + (xyzt-xyz)*tau1
          acc  = acc  + (xyzt-xyz)*tau2
          xyz  = xyzt
         else
          write(*,*)'SHAKE did not converge! maxdev=',maxdev
          !if(maxdev.gt.1.d-3) stop 'SHAKE error too large'
         endif
        return
References conslist, distcons, dr, dro, maxcyc, ncons, tolshake, and true().
init_shake()
subroutine xtb_gfnff_shake::init_shake (integer nat, integer, dimension(nat) at, real*8, dimension(3,nat) xyz, type(tgfftopology), intent(in) topo)
Definition at line 32 of file shake_module.f90.
        use xtb_gfnff_topology, only : tgfftopology
        implicit none
        type(TGFFTopology), intent(in) :: topo
        integer :: nat,at(nat)
        real*8  :: xyz(3,nat)
        real*8  :: wbo(nat,nat)
        integer :: iat,jat,i,j,jmin
        real*8  :: minrij,rij,wthr
        real*8  :: drij(3)
        integer list(nat*(nat+1)/2),lin,ij
       ncons  = topo%nbond
       allocate(conslist(2,ncons),distcons(ncons),&
      &         dro(3,ncons),dr(4,ncons))
       conslist(1:2,1:ncons)=topo%blist(1:2,1:ncons)
       do i = 1, ncons
          iat = conslist(1,i)
          jat = conslist(2,i)
          drij(1:3) = xyz(1:3,iat) - xyz(1:3,jat)
          distcons(i) = drij(1)**2 + drij(2)**2 + drij(3)**2
       enddo
       return
References conslist, distcons, dr, dro, and ncons.
Referenced by xtb_prog_main::xtbmain().
Variable Documentation
conslist
integer, dimension(:,:), allocatable xtb_gfnff_shake::conslist
Definition at line 23 of file shake_module.f90.
        integer, allocatable :: conslist(:,:)
Referenced by do_shake(), and init_shake().
distcons
real*8, dimension(:), allocatable xtb_gfnff_shake::distcons
Definition at line 24 of file shake_module.f90.
        real*8,  allocatable :: distcons(:)
Referenced by do_shake(), and init_shake().
dr
real*8, dimension (:,:), allocatable xtb_gfnff_shake::dr
Definition at line 26 of file shake_module.f90.
        real*8,  allocatable :: dr(:,:)
Referenced by do_shake(), and init_shake().
dro
real*8, dimension(:,:), allocatable xtb_gfnff_shake::dro
Definition at line 25 of file shake_module.f90.
        real*8,  allocatable :: dro(:,:)
Referenced by do_shake(), and init_shake().
maxcyc
integer, parameter xtb_gfnff_shake::maxcyc = 5000
Definition at line 27 of file shake_module.f90.
        integer, parameter :: maxcyc = 5000
Referenced by do_shake().
ncons
integer xtb_gfnff_shake::ncons = 0
Definition at line 21 of file shake_module.f90.
        integer :: ncons = 0
Referenced by do_shake(), and init_shake().
nconsu
integer xtb_gfnff_shake::nconsu = 0
Definition at line 22 of file shake_module.f90.
        integer :: nconsu = 0
shake_mode
integer xtb_gfnff_shake::shake_mode
Definition at line 20 of file shake_module.f90.
        integer :: shake_mode
tolshake
real*8, parameter xtb_gfnff_shake::tolshake = 1.d-6
Definition at line 28 of file shake_module.f90.
        real*8, parameter :: tolshake = 1.d-6
Referenced by do_shake().