My Project: xtb_kopt Module Reference
xtb_kopt Module Reference
Functions/Subroutines
subroutine get_kopt (metaset, env, restart, mol, chk, calc, egap, et, maxiter, maxcycle, optlev, etot, g, sigma, acc)
subroutine get_rmsd (calc, env, restart, mol, chk, egap, et, maxiter, maxcycle, optlev, etot, g, sigma, rmsdval)
Function/Subroutine Documentation
get_kopt()
subroutine xtb_kopt::get_kopt (type(metadyn_setvar), intent(inout) metaset, type(tenvironment), intent(inout) env, logical, intent(in) restart, type(tmolecule), intent(inout) mol, type(trestart), intent(inout) chk, class(tcalculator), intent(inout) calc, real(wp), intent(inout) egap, real(wp), intent(in) et, integer, intent(in) maxiter, integer, intent(in) maxcycle, integer, intent(in) optlev, real(wp), intent(inout) etot, real(wp), dimension(3,mol%n), intent(inout) g, real(wp), dimension(3,3), intent(inout) sigma, real(wp), intent(in) acc)
Definition at line 39 of file getkopt.f90.
   implicit none
 ! Dummy -----------------------------------------------------------------------
   class(TCalculator),intent(inout)            :: calc
   type(metadyn_setvar),intent(inout)          :: metaset
   type(TEnvironment),intent(inout)            :: env
   type(TMolecule),intent(inout)               :: mol
   type(TRestart),intent(inout)                :: chk
   integer,intent(in)                          :: maxiter
   integer,intent(in)                          :: maxcycle
   integer,intent(in)                          :: optlev
   real(wp),intent(inout)                      :: etot
   real(wp),intent(in)                         :: et
   real(wp),intent(in)                         :: acc
   real(wp),intent(inout)                      :: egap
   real(wp),intent(inout)                      :: g(3,mol%n)
   real(wp),intent(inout)                      :: sigma(3,3)
   logical,intent(in)                          :: restart
 ! Stack -----------------------------------------------------------------------
   type(TMolecule)                             :: tmol
   integer                                     :: i
   integer                                     :: idum
   real(wp)                                    :: current_rmsd
   real(wp)                                    :: kopt
   real(wp)                                    :: kbias
   real(wp)                                    :: ax,cx
   logical                                     :: fail
 !! ========================================================================
   call generic_header(env%unit,"Optimal kpush determination",49,10)
 !------------------------------------------------------------------------------
 ! copy input coordinates
   tmol=mol
 ! set kopt boundaries
   ax         =0.0_wp
   cx         =0.005_wp*(dble(mol%n)/(target_rmsd+0.01_wp))
   kbias = ax
   metaset%factor = -kbias
   call get_rmsd( &
                  & calc,env,restart,mol,chk,egap,et,maxiter,maxcycle,optlev,&
                  & etot,g,sigma,current_rmsd)
   write(env%unit,Å'("target rmsd /         ",f9.6)') target_rmsd
   write(env%unit,'("unbiased initial rmsd  ",f9.6)') current_rmsd
   write(env%unit,*)
   write(env%unit,'("iter. min.        max.        rmsd       kpush")')
   if ( current_rmsd.gt.target_rmsd ) then
      do i = 1,10
         mol=tmol
         kbias = 0.5_wp * (cx +ax)
         metaset%factor = -kbias
         call get_rmsd( &
                        & calc,env,restart,mol,chk,egap,et,maxiter,maxcycle,optlev,&
                        & etot,g,sigma,current_rmsd)
         write(*,'(i2,4f12.6)') i,&
         &ax,cx,current_rmsd,metaset%factor(metaset%nstruc)
         if ( current_rmsd.gt.target_rmsd ) then
            ax = kbias
         else
            cx = kbias
         end if
         if ( abs(current_rmsd-target_rmsd) .lt. 1.0d-3 ) exit
      end do
   end if
   kopt = kbias
   metaset%factor = -kopt
   write(env%unit,'("final kpush: ",f9.6)') -kopt
References generic_header(), get_rmsd(), and xtb_setparam::target_rmsd.
get_rmsd()
subroutine xtb_kopt::get_rmsd (class(tcalculator), intent(inout) calc, type(tenvironment), intent(inout) env, logical, intent(in) restart, type(tmolecule), intent(inout) mol, type(trestart), intent(inout) chk, real(wp), intent(inout) egap, real(wp), intent(in) et, integer, intent(in) maxiter, integer, intent(in) maxcycle, integer, intent(in) optlev, real(wp), intent(inout) etot, real(wp), dimension(3,mol%n), intent(inout) g, real(wp), dimension(3,3), intent(inout) sigma, real(wp), intent(out) rmsdval)
Definition at line 111 of file getkopt.f90.
   implicit none
 ! Dummy -----------------------------------------------------------------------
   class(TCalculator),intent(inout)            :: calc
   type(TEnvironment),intent(inout)            :: env
   type(TMolecule),intent(inout)               :: mol
   type(TRestart),intent(inout)                :: chk
   integer,intent(in)                          :: maxiter
   integer,intent(in)                          :: maxcycle
   integer,intent(in)                          :: optlev
   real(wp),intent(inout)                      :: etot
   real(wp),intent(in)                         :: et
   real(wp),intent(out)                        :: rmsdval
   real(wp),intent(inout)                      :: egap
   real(wp),intent(inout)                      :: g(3,mol%n)
   real(wp),intent(inout)                      :: sigma(3,3)
   logical,intent(in)                          :: restart
 ! Stack -----------------------------------------------------------------------
   type(TMolecule)                             :: tmol
   integer                                     :: idum
   real(wp)                                    :: U(3,3)
   real(wp)                                    :: x_center(3),y_center(3)
   real(wp),allocatable                        :: grad(:,:)
   logical                                     :: fail
 !------------------------------------------------------------------------------
 ! save input geometry
   tmol=mol
 !------------------------------------------------------------------------------
 ! geometry optimization
   call geometry_optimization &
       &     (env,mol,chk,calc,   &
       &      egap,etemp,maxiter,maxcycle,etot,g,sigma,optlev,.false.,.true.,fail)
   allocate( grad(3,mol%n), source = 0.0_wp )
   call rmsd(mol%n,mol%xyz,tmol%xyz,1,u,x_center,y_center,rmsdval,.true.,grad)
   rmsdval=rmsdval*autoaa
References xtb_mctc_convert::autoaa, xtb_setparam::etemp, xtb_geoopt::geometry_optimization(), xtb_lsrmsd::rmsd(), and true().
Referenced by get_kopt().