My Project: xtb_param_sqrtzr4r2 Module Reference
xtb_param_sqrtzr4r2 Module Reference
Atomic r4/r2 expectation values.
Data Types
interface getsqrtzr4r2
Get r4/r2 expectation value for a species.
Functions/Subroutines
elemental real(wp) function getsqrtzr4r2symbol (symbol)
Get r4/r2 expectation value for species with a given symbol.
elemental real(wp) function getsqrtzr4r2number (number)
Get r4/r2 expectation value for species with a given atomic number.
Variables
integer, parameter, private max_elem = 118
real(wp), dimension(max_elem), parameter r4overr2 = [ 8.0589_wp, 3.4698_wp, 29.0974_wp,14.8517_wp,11.8799_wp, 7.8715_wp, 5.5588_wp, 4.7566_wp, 3.8025_wp, 3.1036_wp, 26.1552_wp,17.2304_wp,17.7210_wp,12.7442_wp, 9.5361_wp, 8.1652_wp, 6.7463_wp, 5.6004_wp, 29.2012_wp,22.3934_wp, 19.0598_wp,16.8590_wp,15.4023_wp,12.5589_wp,13.4788_wp, 12.2309_wp,11.2809_wp,10.5569_wp,10.1428_wp, 9.4907_wp, 13.4606_wp,10.8544_wp, 8.9386_wp, 8.1350_wp, 7.1251_wp, 6.1971_wp, 30.0162_wp,24.4103_wp, 20.3537_wp,17.4780_wp,13.5528_wp,11.8451_wp,11.0355_wp, 10.1997_wp, 9.5414_wp, 9.0061_wp, 8.6417_wp, 8.9975_wp, 14.0834_wp,11.8333_wp,10.0179_wp, 9.3844_wp, 8.4110_wp, 7.5152_wp, 32.7622_wp,27.5708_wp, 23.1671_wp,21.6003_wp,20.9615_wp,20.4562_wp,20.1010_wp,19.7475_wp,19.4828_wp, 15.6013_wp,19.2362_wp,17.4717_wp,17.8321_wp,17.4237_wp,17.1954_wp,17.1631_wp, 14.5716_wp,15.8758_wp,13.8989_wp,12.4834_wp,11.4421_wp, 10.2671_wp, 8.3549_wp, 7.8496_wp, 7.3278_wp, 7.4820_wp, 13.5124_wp,11.6554_wp,10.0959_wp, 9.7340_wp, 8.8584_wp, 8.0125_wp, 29.8135_wp,26.3157_wp, 19.1885_wp,15.8542_wp,16.1305_wp,15.6161_wp,15.1226_wp,16.1576_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 5.4929_wp, 6.7286_wp, 6.5144_wp,10.9169_wp,10.3600_wp, 9.4723_wp, 8.6641_wp ]
integer, private idum
real(wp), dimension(max_elem), parameter, public sqrtzr4r2 = sqrt(0.5_wp*(r4Overr2*[(sqrt(real(idum,wp)),idum=1,max_elem)]))
Detailed Description
Atomic r4/r2 expectation values.
Function/Subroutine Documentation
getsqrtzr4r2number()
elemental real(wp) function xtb_param_sqrtzr4r2::getsqrtzr4r2number (integer, intent(in) number) private
Get r4/r2 expectation value for species with a given atomic number.
Parameters
[in] number Atomic number
Returns
r4/r2 expectation value
Definition at line 90 of file sqrtzr4r2.f90.
    integer, intent(in) :: number
    real(wp) :: mass
    if (number > 0 .and. number <= size(sqrtzr4r2, dim=1)) then
       mass = sqrtzr4r2(number)
    else
       mass = -1.0_wp
    end if
getsqrtzr4r2symbol()
elemental real(wp) function xtb_param_sqrtzr4r2::getsqrtzr4r2symbol (character(len=*), intent(in) symbol) private
Get r4/r2 expectation value for species with a given symbol.
Parameters
[in] symbol Element symbol
Returns
r4/r2 expectation value
Definition at line 76 of file sqrtzr4r2.f90.
    character(len=*), intent(in) :: symbol
    real(wp) :: mass
    mass = getsqrtzr4r2(tonumber(symbol))
Variable Documentation
idum
integer, private xtb_param_sqrtzr4r2::idum private
Definition at line 67 of file sqrtzr4r2.f90.
    integer, private :: idum
max_elem
integer, parameter, private xtb_param_sqrtzr4r2::max_elem = 118 private
Definition at line 34 of file sqrtzr4r2.f90.
    integer, private, parameter :: max_elem = 118
r4overr2
real(wp), dimension(max_elem), parameter xtb_param_sqrtzr4r2::r4overr2 = [ 8.0589_wp, 3.4698_wp, 29.0974_wp,14.8517_wp,11.8799_wp, 7.8715_wp, 5.5588_wp, 4.7566_wp, 3.8025_wp, 3.1036_wp, 26.1552_wp,17.2304_wp,17.7210_wp,12.7442_wp, 9.5361_wp, 8.1652_wp, 6.7463_wp, 5.6004_wp, 29.2012_wp,22.3934_wp, 19.0598_wp,16.8590_wp,15.4023_wp,12.5589_wp,13.4788_wp, 12.2309_wp,11.2809_wp,10.5569_wp,10.1428_wp, 9.4907_wp, 13.4606_wp,10.8544_wp, 8.9386_wp, 8.1350_wp, 7.1251_wp, 6.1971_wp, 30.0162_wp,24.4103_wp, 20.3537_wp,17.4780_wp,13.5528_wp,11.8451_wp,11.0355_wp, 10.1997_wp, 9.5414_wp, 9.0061_wp, 8.6417_wp, 8.9975_wp, 14.0834_wp,11.8333_wp,10.0179_wp, 9.3844_wp, 8.4110_wp, 7.5152_wp, 32.7622_wp,27.5708_wp, 23.1671_wp,21.6003_wp,20.9615_wp,20.4562_wp,20.1010_wp,19.7475_wp,19.4828_wp, 15.6013_wp,19.2362_wp,17.4717_wp,17.8321_wp,17.4237_wp,17.1954_wp,17.1631_wp, 14.5716_wp,15.8758_wp,13.8989_wp,12.4834_wp,11.4421_wp, 10.2671_wp, 8.3549_wp, 7.8496_wp, 7.3278_wp, 7.4820_wp, 13.5124_wp,11.6554_wp,10.0959_wp, 9.7340_wp, 8.8584_wp, 8.0125_wp, 29.8135_wp,26.3157_wp, 19.1885_wp,15.8542_wp,16.1305_wp,15.6161_wp,15.1226_wp,16.1576_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 5.4929_wp, 6.7286_wp, 6.5144_wp,10.9169_wp,10.3600_wp, 9.4723_wp, 8.6641_wp ] private
Definition at line 43 of file sqrtzr4r2.f90.
    real(wp), parameter :: r4Overr2(max_elem) = [  &
    &  8.0589_wp, 3.4698_wp, & ! H,He
    & 29.0974_wp,14.8517_wp,11.8799_wp, 7.8715_wp, 5.5588_wp, 4.7566_wp, 3.8025_wp, 3.1036_wp, & ! Li-Ne
    & 26.1552_wp,17.2304_wp,17.7210_wp,12.7442_wp, 9.5361_wp, 8.1652_wp, 6.7463_wp, 5.6004_wp, & ! Na-Ar
    & 29.2012_wp,22.3934_wp, & ! K,Ca
    &         19.0598_wp,16.8590_wp,15.4023_wp,12.5589_wp,13.4788_wp, & ! Sc-
    &         12.2309_wp,11.2809_wp,10.5569_wp,10.1428_wp, 9.4907_wp, & ! -Zn
    &                 13.4606_wp,10.8544_wp, 8.9386_wp, 8.1350_wp, 7.1251_wp, 6.1971_wp, & ! Ga-Kr
    & 30.0162_wp,24.4103_wp, & ! Rb,Sr
    &         20.3537_wp,17.4780_wp,13.5528_wp,11.8451_wp,11.0355_wp, & ! Y-
    &         10.1997_wp, 9.5414_wp, 9.0061_wp, 8.6417_wp, 8.9975_wp, & ! -Cd
    &                 14.0834_wp,11.8333_wp,10.0179_wp, 9.3844_wp, 8.4110_wp, 7.5152_wp, & ! In-Xe
    & 32.7622_wp,27.5708_wp, & ! Cs,Ba
    &         23.1671_wp,21.6003_wp,20.9615_wp,20.4562_wp,20.1010_wp,19.7475_wp,19.4828_wp, & ! La-Eu
    &         15.6013_wp,19.2362_wp,17.4717_wp,17.8321_wp,17.4237_wp,17.1954_wp,17.1631_wp, & ! Gd-Yb
    &         14.5716_wp,15.8758_wp,13.8989_wp,12.4834_wp,11.4421_wp, & ! Lu-
    &         10.2671_wp, 8.3549_wp, 7.8496_wp, 7.3278_wp, 7.4820_wp, & ! -Hg
    &                 13.5124_wp,11.6554_wp,10.0959_wp, 9.7340_wp, 8.8584_wp, 8.0125_wp, & ! Tl-Rn
    & 29.8135_wp,26.3157_wp, & ! Fr,Ra
    &         19.1885_wp,15.8542_wp,16.1305_wp,15.6161_wp,15.1226_wp,16.1576_wp, 0.0000_wp, & ! Ac-Am
    &          0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, & ! Cm-No
    &          0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, & ! Lr-
    &          0.0000_wp, 0.0000_wp, 0.0000_wp, 0.0000_wp, 5.4929_wp, & ! -Cn
    &                  6.7286_wp, 6.5144_wp,10.9169_wp,10.3600_wp, 9.4723_wp, 8.6641_wp ] ! Nh-Og
sqrtzr4r2
real(wp), dimension(max_elem), parameter, public xtb_param_sqrtzr4r2::sqrtzr4r2 = sqrt(0.5_wp*(r4Overr2*[(sqrt(real(idum,wp)),idum=1,max_elem)]))
Definition at line 68 of file sqrtzr4r2.f90.
    real(wp), parameter :: sqrtZr4r2(max_elem) = &
    &  sqrt(0.5_wp*(r4Overr2*[(sqrt(real(idum,wp)),idum=1,max_elem)]))
Referenced by xtb_disp_dftd4::build_wdispmat(), xtb_disp_dftd3::d3_atm_gradient::d3_atm_gradient_latp(), xtb_disp_dftd3::d3_atm_gradient::d3_atm_gradient_neigh(), xtb_disp_dftd3::d3_gradient::d3_full_gradient_latp(), xtb_disp_dftd3::d3_gradient::d3_full_gradient_neigh(), xtb_disp_dftd3::d3_gradient::d3_gradient_latp(), xtb_disp_dftd3::d3_gradient::d3_gradient_neigh(), xtb_disp_dftd4::d4_atm_gradient::d4_atm_gradient_latp(), xtb_disp_dftd4::d4_atm_gradient::d4_atm_gradient_neigh(), xtb_disp_dftd4::d4_gradient::d4_full_gradient_latp(), xtb_disp_dftd4::d4_gradient::d4_full_gradient_neigh(), xtb_disp_dftd4::d4_gradient::d4_gradient_latp(), xtb_disp_dftd4::d4_gradient::d4_gradient_neigh(), xtb_param_sqrtzr4r2::getsqrtzr4r2::getsqrtzr4r2number(), xtb_gfnff_eg::gfnff_eg(), xtb_gfnff_param::gfnff_set_param(), and xtb_disp_dftd4::mdisp().