My Project: xtb_mctc_filetypes Module Reference
xtb_mctc_filetypes Module Reference
Supported file types in this program.
Data Types
interface getfiletype
Generate file type from file name.
type tfiletypeenum
Possible file types.
Functions/Subroutines
integer function getfiletypefromname (name)
Generate file type from file name.
integer function getfiletypefrommetainfo (basename, extension)
Generate file type from file name.
subroutine, public generatefilemetainfo (Name, path, basename, extension)
Split file name into path, basename and extension.
subroutine, public generatefilename (fname, basename, extension, ftype)
Variables
type(tfiletypeenum), parameter, public filetype = TFileTypeEnum()
File type enumerator.
integer, parameter defaultfiletype = fileType%tmol
Default file type.
Detailed Description
Supported file types in this program.
Function/Subroutine Documentation
generatefilemetainfo()
subroutine, public xtb_mctc_filetypes::generatefilemetainfo (character(len=*), intent(in) Name, character(len=:), intent(out), allocatable path, character(len=:), intent(out), allocatable basename, character(len=:), intent(out), allocatable extension)
Split file name into path, basename and extension.
Parameters
[in] name File name
[out] path Path to the file, empty if no path found in name
[out] basename Base name of the file
[out] extension Extension of the file name, empty if no extension present
Definition at line 140 of file filetypes.f90.
    character(len=*), intent(in) :: name
    character(len=:), allocatable, intent(out) :: path
    character(len=:), allocatable, intent(out) :: basename
    character(len=:), allocatable, intent(out) :: extension
    integer :: iDot, iSlash
    idot = index(name, '.', back=.true.)
    islash = index(name, '/', back=.true.)
    ! When given a name like "Gau-3333.Ein", the basename should be "Gau-3333",
    ! so if there is no '/', we assume there is an implicit './' at the
    ! beginning of name.
    if (islash > 0) then
       path = name(:islash)
    else
       path = ''
    endif
    if (idot > islash .and. idot > 0) then
       extension = name(idot+1:)
    else ! means point is somewhere in the path or absent
       idot = len(name)+1
       extension = ''
    endif
    if (idot > islash) then
       basename = name(islash+1:idot-1)
    else
       basename = ''
    endif
References true().
Referenced by xtb_mctc_filetypes::getfiletype::getfiletypefromname(), and xtb_prog_main::xtbmain().
generatefilename()
subroutine, public xtb_mctc_filetypes::generatefilename (character(len=:), intent(out), allocatable fname, character(len=*), intent(in) basename, character(len=*), intent(in) extension, integer, intent(in) ftype)
Definition at line 185 of file filetypes.f90.
    character(len=:), allocatable, intent(out) :: fname
    character(len=*), intent(in) :: basename
    character(len=*), intent(in) :: extension
    integer, intent(in) :: ftype
    if (len(basename) > 0) then
       fname = basename
    else
       fname = 'xtb'
    endif
    if (len(extension) > 0) then
       fname = fname//'.'//extension
    else
       select case(ftype)
       case(filetype%xyz)
          fname = fname//'.xyz'
       case(filetype%tmol)
          fname = fname//'.coord'
       case(filetype%molfile)
          fname = fname//'.mol'
       case(filetype%sdf)
          fname = fname//'.sdf'
       case(filetype%vasp)
          fname = fname//'.poscar'
       case(filetype%pdb)
          fname = fname//'.pdb'
       case(filetype%gen)
          fname = fname//'.gen'
       case(filetype%gaussian)
          fname = fname//'.ein'
       end select
    endif
References filetype.
Referenced by xtb_topology::checktopology(), xtb_hessian::distort(), and xtb_prog_main::xtbmain().
getfiletypefrommetainfo()
integer function xtb_mctc_filetypes::getfiletypefrommetainfo (character(len=*), intent(in) basename, character(len=*), intent(in) extension) private
Generate file type from file name.
Parameters
[in] basename File name
[in] extension File extension
Returns
File type
Definition at line 93 of file filetypes.f90.
    character(len=*), intent(in) :: basename
    character(len=*), intent(in) :: extension
    integer :: ftype
    ftype = defaultfiletype
    if (len(basename) > 0) then
       select case(tolowercase(basename))
       case('coord')
          ftype = filetype%tmol
       case('poscar', 'contcar')
          ftype = filetype%vasp
       end select
    endif
    if (len(extension) > 0) then
       select case(tolowercase(extension))
       case('coord', 'tmol')
          ftype = filetype%tmol
       case('xyz')
          ftype = filetype%xyz
       case('mol')
          ftype = filetype%molfile
       case('sdf')
          ftype = filetype%sdf
       case('poscar', 'contcar', 'vasp')
          ftype = filetype%vasp
       case('pdb')
          ftype = filetype%pdb
       case('gen')
          ftype = filetype%gen
       case('ein')
          ftype = filetype%gaussian
       end select
    end if
getfiletypefromname()
integer function xtb_mctc_filetypes::getfiletypefromname (character(len=*), intent(in) name) private
Generate file type from file name.
Parameters
[in] name File name
Returns
File type
Definition at line 75 of file filetypes.f90.
    character(len=*), intent(in) :: name
    integer :: ftype
    character(len=:), allocatable :: basename, extension, path
    call generatefilemetainfo(name, path, basename, extension)
    ftype = getfiletype(basename, extension)
Variable Documentation
defaultfiletype
integer, parameter xtb_mctc_filetypes::defaultfiletype = fileType%tmol private
Default file type.
Definition at line 68 of file filetypes.f90.
    integer, parameter :: defaultFileType = filetype%tmol
Referenced by xtb_mctc_filetypes::getfiletype::getfiletypefrommetainfo().
filetype
type(tfiletypeenum), parameter, public xtb_mctc_filetypes::filetype = TFileTypeEnum()
File type enumerator.
Definition at line 65 of file filetypes.f90.
    type(TFileTypeEnum), parameter :: fileType = tfiletypeenum()
Referenced by xtb_biaspath::bias_path(), xtb_test_molstock::bug332(), xtb_topology::checktopology(), xtb_relaxation_engine::fire(), generatefilename(), xtb_mctc_filetypes::getfiletype::getfiletypefrommetainfo(), xtb_gfnff_setup::gfnff_input(), xtb_relaxation_engine::l_ancopt(), xtb_dynamic::md(), xtb_mdoptim::mdopt(), xtb_prog_thermo::parsearguments(), xtb_test_molstock::pdb_4qxx(), xtb_io_reader::readhessian(), xtb_io_reader::readmolecule(), xtb_optimizer::relax(), xtb_scan::relaxed_scan(), xtb_extern_orca::runorca(), xtb_screening::screen(), test_geometry_reader_file_coord_caf2_3d(), test_geometry_reader_file_coord_camgco_3d(), test_geometry_reader_file_coord_general_0d(), test_geometry_reader_file_gen(), test_geometry_reader_file_pdb_4qxx(), test_geometry_reader_file_pdb_4qxx_noh(), test_geometry_reader_file_poscar_sio2_3d(), test_geometry_reader_file_sdf_benzen_hquery(), test_geometry_reader_file_sdf_h2o(), test_geometry_reader_file_sdf_h2o_flat(), test_geometry_reader_file_xmol_water_0d(), test_geometry_reader_molfile_benzen(), test_geometry_reader_molfile_benzen_flat(), xtb_io_writer::writemolecule(), xtb_prog_main::xtbmain(), and xtb_prog_thermo::xtbthermo().