My Project: xtb_prog_thermo Module Reference
xtb_prog_thermo Module Reference
Thermodynamic functions and hessian post processing.
Functions/Subroutines
subroutine, public xtbthermo (env, argParser)
Main program of the thermo submodule.
subroutine preigf (unit, freq, scale)
subroutine parsearguments (env, args, ftype, massWeighted)
Parse command line arguments.
subroutine thermoheader (unit)
Header for this submodule.
subroutine thermohelp (unit)
Detailed Description
Thermodynamic functions and hessian post processing.
Function/Subroutine Documentation
parsearguments()
subroutine xtb_prog_thermo::parsearguments (type(tenvironment) env, type(targparser) args, integer, intent(out) ftype, logical, intent(out) massWeighted) private
Parse command line arguments.
Parameters
env Calculation environment
args Command line argument parser
[out] ftype File type of the hessian
[out] massweighted Hessian is already mass weighted
Definition at line 168 of file thermo.f90.
    character(len=*), parameter :: source = "prog_thermo_parseArguments"
    type(TEnvironment) :: env
    type(TArgParser) :: args
    integer, intent(out) :: ftype
    logical, intent(out) :: massWeighted
    integer :: nFlags
    character(len=:), allocatable :: flag, sec
    ftype = filetype%tmol
    massweighted = .false.
    nflags = args%countFlags()
    call args%nextFlag(flag)
    do while(allocated(flag))
       if (len(flag) > 2 .and. flag(1:1) == '-' .and. flag(1:2) /= '--') then
          call env%warning("the use of '"//flag//"' is discouraged, "// &
             & "please use '-"//flag//"' next time", source)
          flag = '-'//flag
       end if
       select case(flag)
       case default
          call env%warning("Unknown option '"//flag//"' provided", source)
       case('--help', '-h')
          call thermohelp(env%unit)
          call terminate(0)
       case('--dftb+')
          ftype = filetype%gen
       case('--turbomole')
          ftype = filetype%tmol
          massweighted = .true.
       case('--scale')
          call args%nextArg(sec)
          if (allocated(sec)) then
             call set_thermo(env, 'scale', sec)
          else
             call env%error("Freq. scaling factor missing", source)
          end if
       case('--sthr')
          call args%nextArg(sec)
          if (allocated(sec)) then
             call set_thermo(env, 'sthr', sec)
          else
             call env%error("Rotor cutoff is missing", source)
          end if
       case('--ithr')
          call args%nextArg(sec)
          if (allocated(sec)) then
             call set_thermo(env, 'imagthr','-'//sec)
          else
             call env%error("Imaginary cutoff is missing", source)
          end if
       case('--desy')
          call args%nextArg(sec)
          if (allocated(sec)) then
             call set_symmetry(env,'desy',sec)
          else
             call env%error("Threshold for symmetry recognition missing", source)
          end if
       case('--temp')
          call args%nextArg(sec)
          if (allocated(sec)) then
             call set_thermo(env, 'temp', sec)
          else
             call env%error("Temperature in K is missing", source)
          end if
       end select
       call args%nextFlag(flag)
    end do
References xtb_mctc_filetypes::filetype, xtb_setmod::set_symmetry(), xtb_setmod::set_thermo(), terminate(), thermohelp(), and true().
Referenced by xtbthermo().
preigf()
subroutine xtb_prog_thermo::preigf (integer, intent(in) unit, real(wp), dimension(:), intent(in) freq, real(wp), intent(in) scale) private
Definition at line 144 of file thermo.f90.
    real(wp), intent(in) :: freq(:)
    real(wp), intent(in) :: scale
    integer, intent(in) :: unit
    integer, parameter :: nRows = 6
    integer :: ntimes, nrest, i, j, n2, k
    ntimes = size(freq)/nrows
    nrest = mod(size(freq), nrows)
    if (ntimes.eq.0) nrest = size(freq)
    j = 1
    n2 = nrows
    do k = 1, ntimes
       write(unit,'("eigval :",3x,10f9.2)') (freq(i)*scale,i=j,n2)
       j = j + nrows
       n2 = n2 + nrows
    end do
    if (nrest.gt.0.or.ntimes.eq.0) then
       write(unit,'("eigval :",3x,10f9.2)') (freq(i)*scale,i=j,j+nrest-1)
    end if
thermoheader()
subroutine xtb_prog_thermo::thermoheader (integer, intent(in) unit) private
Header for this submodule.
Parameters
[in] unit IO unit
Definition at line 262 of file thermo.f90.
    integer, intent(in) :: unit
    write(unit,'(a)') &
       "      -----------------------------------------------------------",&
       "     |                   =====================                   |",&
       "     |                        T H E R M O                        |",&
       "     |                   =====================                   |",&
       "     |                         S. Ehlert                         |",&
       "     |          Mulliken Center for Theoretical Chemistry        |",&
       "     |                    University of Bonn                     |",&
       "      -----------------------------------------------------------",""
    write(unit,'(3x,"*",*(1x,a))') &
       & "xtb-thermo version", version, "compiled by", author, "on", date
    write(unit,'(a)')
Referenced by xtbthermo().
thermohelp()
subroutine xtb_prog_thermo::thermohelp (integer, intent(in) unit) private
Parameters
[in] unit IO unit
Definition at line 283 of file thermo.f90.
    integer, intent(in) :: unit
    write(unit, '(a)') &
    "Usage: xtb thermo [options] <geometry> [hessian]", &
    "",&
    "<geometry> may be provided as any valid input to xtb", &
    "the [hessian] file is read and processed depending on the selected options,", &
    "the default format is a non-massweighted Turbomole hessian file", &
    "",&
    "Options",&
    "",&
    "   --sthr REAL         Rotor cutoff for RRHO partition function in rcm",&
    "",&
    "   --ithr REAL         Imag. freq. cutoff for RRHO in rcm",&
    "                       enter a positive value, the sign will be inverted",&
    "",&
    "   --scale REAL        Frequency scaling factor for RRHO",&
    "",&
    "   --desy REAL         Threshold for symmetry recognition",&
    "",&
    "   --temp REAL[,...]   Temperature for thermodynamic functions in K,",&
    "                       takes a comma separated list of temperatures",&
    "",&
    "   --dftb+             Read a DFTB+ hessian.out file, implies projection",&
    "",&
    "   --turbomole         Read a Turbomole Hessian file",&
    "                       use this only when $nomw is not present in control",&
    "",&
    "Output Conventions:",&
    "",&
    "total energies are given in atomic units (Eh), frequencies in reciprocal cm",&
    "",&
    "More information can be obtained at https://xtb-docs.readthedocs.io/",&
    ""
Referenced by parsearguments(), and xtbthermo().
xtbthermo()
subroutine, public xtb_prog_thermo::xtbthermo (type(tenvironment), intent(inout) env, type(targparser), intent(inout) argParser)
Main program of the thermo submodule.
Parameters
[in,out] env Calculation environment
[in,out] argparser Commandline argument parser
Molecular structure data
Determine the file type for processing in the reader
Generate the reader by connecting the file to the instance
Process the file to obtain the molecular structure data
Close the file, we are done with it here
Print an informative banner
print current time
Also store a copy of the atomic masses in amu in global storage
Definition at line 45 of file thermo.f90.
    character(len=*), parameter :: source = "prog_thermo"
    type(TEnvironment), intent(inout) :: env
    type(TArgParser), intent(inout) :: argParser
    type(TMolecule) :: mol
    type(TReader) :: reader
    character(len=:), allocatable :: file
    real(wp), allocatable :: freq(:), hessian(:, :)
    real(wp) :: htot, gtot, zp
    integer :: nFiles, ftype, hFormat, nimag
    logical :: massWeighted
    call parsearguments(env, argparser, hformat, massweighted)
    nfiles = argparser%countFiles()
    if (nfiles == 0) then
       call env%error("No input file given, so there is nothing to do", source)
       call thermohelp(env%unit)
    end if
    if (nfiles > 2) then
       call env%error("Multiple input files present, aborting", source)
    end if
    call env%checkpoint("Command line argument parsing failed")
    call argparser%nextFile(file)
    ftype = getfiletype(file)
    call reader%open(file)
    call readmolecule(env, mol, reader%unit, ftype)
    call reader%close
    call env%checkpoint("Could not read geometry from '"//file//"'")
    call thermoheader(env%unit)
    call prdate('S')
    atmass = mol%atmass * autoamu
    call argparser%nextFile(file)
    allocate(freq(3*mol%n))
    if (allocated(file)) then
       allocate(hessian(3*mol%n, 3*mol%n))
       call reader%open(file)
       call readhessian(env, mol, hessian, reader, format=hformat)
       call reader%close
       if (.not.massweighted) then
          call massweighthessian(hessian, mol%atmass)
       end if
       if (hformat == filetype%gen) then
          call projecthessian(hessian, mol, .true., .true.)
       end if
       call diaghessian(env, hessian, freq)
       call preigf(env%unit, freq, autorcm)
       call env%checkpoint("Could not read hessian from '"//file//"'")
    else
       freq(:) = -1.0_wp
    end if
    freq(:) = freq * autorcm
    call print_thermo(env%unit,mol%n, size(freq), mol%at, mol%xyz, freq, 0.0_wp, &
       & htot, gtot, nimag, .true., zp)
    write(env%unit,'(a)')
    write(env%unit,'(72("-"))')
    call stop_timing_run
    call stop_timing(1)
    call prdate('E')
    write(env%unit,'(72("-"))')
    call prtiming(1,'total')
    write(env%unit,'(a)')
    call terminate(0)
References xtb_splitparam::atmass, xtb_mctc_convert::autoamu, xtb_mctc_convert::autorcm, xtb_freq_utils::diaghessian(), xtb_mctc_filetypes::filetype, xtb_freq_utils::massweighthessian(), parsearguments(), xtb_mctc_timings::prdate(), preigf(), xtb_propertyoutput::print_thermo(), xtb_freq_project::projecthessian(), xtb_mctc_timings::prtiming(), xtb_io_reader::readhessian(), xtb_io_reader::readmolecule(), xtb_mctc_timings::stop_timing(), xtb_mctc_timings::stop_timing_run(), terminate(), thermoheader(), thermohelp(), and true().
Referenced by xtb_prog_primary().