My Project: xtb_api_version Module Reference
xtb_api_version Module Reference
Defines the API version for xtb.
Functions/Subroutines
integer(c_int) function, public getapiversion_api ()
Variables
integer(c_int), parameter apimajor = 1
integer(c_int), parameter apiminor = 0
integer(c_int), parameter apipatch = 0
Detailed Description
Defines the API version for xtb.
Function/Subroutine Documentation
getapiversion_api()
integer(c_int) function, public xtb_api_version::getapiversion_api
Definition at line 34 of file version.f90.
    integer(c_int) :: version
    version = 10000_c_int * apimajor + 100_c_int * apiminor + apipatch
References apimajor, apiminor, and apipatch.
Variable Documentation
apimajor
integer(c_int), parameter xtb_api_version::apimajor = 1 private
Definition at line 26 of file version.f90.
    integer(c_int), parameter :: apiMajor = 1
Referenced by getapiversion_api().
apiminor
integer(c_int), parameter xtb_api_version::apiminor = 0 private
Definition at line 27 of file version.f90.
    integer(c_int), parameter :: apiMinor = 0
Referenced by getapiversion_api().
apipatch
integer(c_int), parameter xtb_api_version::apipatch = 0 private
Definition at line 28 of file version.f90.
    integer(c_int), parameter :: apiPatch = 0
Referenced by getapiversion_api().