My Project: xtb_freq_io Module Reference
xtb_freq_io Module Reference
Functions/Subroutines
subroutine, public writehessianout (fname, hessian)
Write the second derivative matrix.
subroutine, public wrhess (nat3, h, fname)
subroutine, public rdhess (nat3, h, fname)
subroutine, public write_tm_vibspectrum (ich, n3, freq, ir_int)
subroutine, public g98fake2 (fname, n, at, xyz, freq, red_mass, ir_int, u2)
subroutine, public g98fake (fname, n, at, xyz, freq, u2)
Function/Subroutine Documentation
g98fake()
subroutine, public xtb_freq_io::g98fake (character(len=*), intent(in) fname, integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension(3*n), intent(in) freq, real(wp), dimension(3*n,3*n), intent(in) u2)
Definition at line 238 of file io.f90.
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    real(wp),intent(in)  :: freq(3*n)
    real(wp),intent(in)  :: xyz(3,n)
    real(wp),intent(in)  :: u2(3*n,3*n)
    character(len=*),intent(in) :: fname
    integer  :: gu,i,j,ka,kb,kc,la,lb,k
    character(len=2) :: irrep
    real(wp),allocatable :: u(:,:)
    real(wp),allocatable :: red_mass(:)
    real(wp),allocatable :: force   (:)
    real(wp),allocatable :: ir_int  (:)
    real(wp),allocatable :: f2      (:)
    real(wp) :: zero
    allocate( u(3*n,3*n), red_mass(3*n), force(3*n), ir_int(3*n), f2(3*n), &
              source = 0.0_wp )
    irrep='a'
    red_mass=99.0
    force   =99.0
    ir_int  =99.0
    zero    =0.0
    k=0
    do i=1,3*n
       if(abs(freq(i)).gt.1.d-1)then
          k=k+1
          u(1:3*n,k)=u2(1:3*n,i)
          f2(k)=freq(i)
       endif
    enddo
    gu=55
    call open_file(gu,fname,'w')
    write (gu,'('' Entering Gaussian System'')')
    write (gu,'('' *********************************************'')')
    write (gu,'('' Gaussian 98:'')')
    write (gu,'('' frequency output generated by the xtb code'')')
    write (gu,'('' *********************************************'')')
    write (gu,*) '                        Standard orientation:'
    write (gu,*) '---------------------------------------------', &
       & '-----------------------'
    write (gu,*) ' Center     Atomic     Atomic', &
       & '              Coordinates (Angstroms)'
    write (gu,*) ' Number     Number      Type ', &
       & '             X           Y           Z'
    write (gu,*) '-----------------------', &
       & '---------------------------------------------'
    j=0
    do i=1,n
       write(gu,111) i,at(i),j,xyz(1:3,i)*0.52917726
    enddo
    write (gu,*) '----------------------', &
       & '----------------------------------------------'
    write (gu,*) '    1 basis functions        1 primitive gaussians'
    write (gu,*) '    1 alpha electrons        1 beta electrons'
    write (gu,*)
    111 format(i5,i11,i14,4x,3f12.6)
    write (gu,*) 'Harmonic frequencies (cm**-1), IR intensities',⁻¹' (km*mol),'
    write (gu,*) 'Raman scattering activities (A**4/amu),', &
       & ' Raman depolarization ratios,'
    write (gu,*) 'reduced masses (AMU), force constants (mDyne/A)', &
       & ' and normal coordinates:'
    ka=1
    kc=3
    60  kb=min0(kc,k)
    write (gu,100) (j,j=ka,kb)
    write (gu,105) (irrep,j=ka,kb)
    write (gu,110) ' Frequencies --',(f2(j),j=ka,kb)
    write (gu,110) ' Red. masses --',(red_mass(j),j=ka,kb)
    write (gu,110) ' Frc consts  --',(force(j),j=ka,kb)
    write (gu,110) ' IR Inten    --',(ir_int(j),j=ka,kb)
    write (gu,110) ' Raman Activ --',(zero,j=ka,kb)
    write (gu,110) ' Depolar     --',(zero,j=ka,kb)
    write (gu,*)'Atom AN      X      Y      Z        X      Y', &
       & '      Z        X      Y      Z'
    la=1
    70  lb=n
    do  i=la,lb
       write (gu,130) i,at(i), (u(i*3-2,j),  u(i*3-1,j),  u(i*3  ,j),j=ka,kb)
    enddo
    if (lb.eq.n) go to 90
    go to 70
    90  if (kb.eq.k) then
       return
    endif
    ka=kc+1
    kc=kc+3
    go to 60
    100 format (3(20x,i3))
    105 format (3x,3(18x,a5))
    110 format (a15,f11.4,12x,f11.4,12x,f11.4)
    130 format (2i4,3(2x,3f7.2))
    write(gu,'(''end of file'')')
    call close_file(gu)
    return
References close_file(), and open_file().
g98fake2()
subroutine, public xtb_freq_io::g98fake2 (character(len=*), intent(in) fname, integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension(3*n), intent(in) freq, real(wp), dimension(3*n), intent(in) red_mass, real(wp), dimension (3*n), intent(in) ir_int, real(wp), dimension(3*n,3*n), intent(in) u2)
Definition at line 129 of file io.f90.
    integer, intent(in)  :: n
    integer, intent(in)  :: at(n)
    real(wp),intent(in)  :: freq(3*n)
    real(wp),intent(in)  :: xyz(3,n)
    real(wp),intent(in)  :: u2(3*n,3*n)
    character(len=*),intent(in) :: fname
    real(wp),intent(in)  :: red_mass(3*n)
    real(wp),intent(in)  :: ir_int  (3*n)
    integer  :: gu,i,j,ka,kb,kc,la,lb,k
    character(len=2) :: irrep
    real(wp),allocatable :: u(:,:)
    real(wp),allocatable :: red(:)
    real(wp),allocatable :: f2 (:)
    real(wp),allocatable :: ir (:)
    real(wp) :: zero
    allocate( u(3*n,3*n), red(3*n), f2(3*n), ir(3*n), source = 0.0_wp )
    irrep='a'
    zero    =0.0
    k=0
    do i=1,3*n
       if(abs(freq(i)).gt.1.d-1)then
          k=k+1
          u(1:3*n,k)=u2(1:3*n,i)
          f2(k)=freq(i)
          ir(k)=ir_int(i)
          red(k)=red_mass(i)
       endif
    enddo
    gu=55
    call open_file(gu,fname,'w')
    write (gu,'('' Entering Gaussian System'')')
    write (gu,'('' *********************************************'')')
    write (gu,'('' Gaussian 98:'')')
    write (gu,'('' frequency output generated by the xtb code'')')
    write (gu,'('' *********************************************'')')
    write (gu,*) '                        Standard orientation:'
    write (gu,*) '---------------------------------------------', &
       & '-----------------------'
    write (gu,*) ' Center     Atomic     Atomic', &
       & '              Coordinates (Angstroms)'
    write (gu,*) ' Number     Number      Type ', &
       & '             X           Y           Z'
    write (gu,*) '-----------------------', &
       & '---------------------------------------------'
    j=0
    do i=1,n
       write(gu,111) i,at(i),j,xyz(1:3,i)*0.52917726
    enddo
    write (gu,*) '----------------------', &
       & '----------------------------------------------'
    write (gu,*) '    1 basis functions        1 primitive gaussians'
    write (gu,*) '    1 alpha electrons        1 beta electrons'
    write (gu,*)
    111 format(i5,i11,i14,4x,3f12.6)
    write (gu,*) 'Harmonic frequencies (cm**-1), IR intensities', &
       & ⁻¹' (km*mol),'
    write (gu,*) 'Raman scattering activities (A**4/amu),', &
       & ' Raman depolarization ratios,'
    write (gu,*) 'reduced masses (AMU), force constants (mDyne/A)', &
       & ' and normal coordinates:'
    ka=1
    kc=3
    60  kb=min0(kc,k)
    write (gu,100) (j,j=ka,kb)
    write (gu,105) (irrep,j=ka,kb)
    write (gu,110) ' Frequencies --',(f2(j),j=ka,kb)
    write (gu,110) ' Red. masses --',(red(j),j=ka,kb)
    write (gu,110) ' Frc consts  --',(zero,j=ka,kb)
    write (gu,110) ' IR Inten    --',(ir(j),j=ka,kb)
    write (gu,110) ' Raman Activ --',(zero,j=ka,kb)
    write (gu,110) ' Depolar     --',(zero,j=ka,kb)
    write (gu,*)'Atom AN      X      Y      Z        X      Y', &
       & '      Z        X      Y      Z'
    la=1
    70  lb=n
    do  i=la,lb
       write (gu,130) i,at(i), (u(i*3-2,j),  u(i*3-1,j),  u(i*3  ,j),j=ka,kb)
    enddo
    if (lb.eq.n) go to 90
    go to 70
    90  if (kb.eq.k) then
       return
    endif
    ka=kc+1
    kc=kc+3
    go to 60
    100 format (3(20x,i3))
    105 format (3x,3(18x,a5))
    110 format (a15,f11.4,12x,f11.4,12x,f11.4)
    130 format (2i4,3(2x,3f7.2))
    write(gu,'(''end of file'')')
    call close_file(gu)
    return
References close_file(), and open_file().
rdhess()
subroutine, public xtb_freq_io::rdhess (integer, intent(in) nat3, real(wp), dimension(nat3,nat3), intent(out) h, character(len=*), intent(in) fname)
Definition at line 79 of file io.f90.
    integer, intent(in)  :: nat3
    real(wp),intent(out) :: h(nat3,nat3)
    character(len=*),intent(in) :: fname
    integer  :: iunit,i,j,mincol,maxcol
    character(len=5)  :: adum
    character(len=80) :: a80
    !     write(*,*) 'Reading Hessian <',trim(fname),'>'
    call open_file(iunit,fname,'r')
    50  read(iunit,'(a)')a80
    if(index(a80,'$hessian').ne.0)then
       do i=1,nat3
          maxcol = 0
          200       mincol = maxcol + 1
          maxcol = min(maxcol+5,nat3)
          read(iunit,*)(h(j,i),j=mincol,maxcol)
          if (maxcol.lt.nat3) goto 200
       enddo
       call close_file(iunit)
       goto 300
    endif
    goto 50
    300 return
References close_file(), and open_file().
wrhess()
subroutine, public xtb_freq_io::wrhess (integer, intent(in) nat3, real(wp), dimension(nat3*(nat3+1)/2), intent(in) h, character(len=*), intent(in) fname)
Definition at line 54 of file io.f90.
    integer, intent(in) :: nat3
    real(wp),intent(in) :: h(nat3*(nat3+1)/2)
    character(len=*),intent(in) :: fname
    integer iunit,i,j,mincol,maxcol,k
    character(len=5)  :: adum
    character(len=80) :: a80
    adum='   '
    call open_file(iunit,fname,'w')
    a80='$hessian'
    write(iunit,'(a)')a80
    do i=1,nat3
       maxcol = 0
       k=0
       200    mincol = maxcol + 1
       k=k+1
       maxcol = min(maxcol+5,nat3)
       write(iunit,'(a5,5f15.10)')adum,(h(lin(i,j)),j=mincol,maxcol)
       if (maxcol.lt.nat3) goto 200
    enddo
    call close_file(iunit)
References close_file(), lin(), and open_file().
Referenced by xtb_hessian::numhess().
write_tm_vibspectrum()
subroutine, public xtb_freq_io::write_tm_vibspectrum (integer, intent(in) ich, integer, intent(in) n3, real(wp), dimension(n3), intent(in) freq, real(wp), dimension(n3), intent(in) ir_int)
Definition at line 107 of file io.f90.
    integer, intent(in)  :: ich ! file handle
    integer, intent(in)  :: n3
    real(wp),intent(in)  :: freq(n3)
    real(wp),intent(in)  :: ir_int(n3)
    integer  :: i
    real(wp) :: thr=0.01_wp
    write(ich,'("$vibrational spectrum")')
    write(ich,'("#  mode     symmetry     wave number   IR intensity    selection rules")')
    write(ich,⁻¹'("#                         cm**(-1)      (km*mol)       IR     RAMAN")')
    do i = 1, n3
       if (abs(freq(i)).lt.thr) then
         write(ich,'(i6,9x,    f18.2,f16.5,7x," - ",5x," - ")') &
          i,freq(i),0.0_wp
       else
         write(ich,'(i6,8x,"a",f18.2,f16.5,7x,"YES",5x,"YES")') &
          i,freq(i),ir_int(i)
       endif
    enddo
    write(ich,'("$end")')
writehessianout()
subroutine, public xtb_freq_io::writehessianout (character(len=*), intent(in) fname, real(wp), dimension(:,:), intent(in) hessian)
Write the second derivative matrix.
Parameters
[in] fname File name
[in] hessian Dynamical (Hessian) matrix
Format string for energy second derivative matrix
Definition at line 32 of file io.f90.
    character(len=*), intent(in) :: fname
    real(wp), intent(in) :: hessian(:,:)
    character(len=*), parameter :: fmt = '(4f16.10)'
    integer :: ii, id
    call open_file(id, fname, 'w')
    do ii = 1, size(hessian, dim=2)
       write(id, fmt) hessian(:, ii)
    end do
    call close_file(id)
References close_file(), and open_file().
Referenced by xtb_hessian::numhess().