My Project: xtb_solv_state Module Reference
xtb_solv_state Module Reference
Define reference states of solution.
Data Types
type tsolutionstateenum
Possible reference states for the solution.
Functions/Subroutines
pure real(wp) function, public getstateshift (state, temperature, density, molecularMass)
Variables
type(tsolutionstateenum), parameter, public solutionstate = TSolutionStateEnum()
Actual solvation state enumerator.
real(wp), parameter refdensity = 1.0e-3_wp
real(wp), parameter refmolecularmass = 1.0_wp
real(wp), parameter idealgasmolvolume = 24.79_wp
real(wp), parameter ambienttemperature = 298.15_wp
Detailed Description
Define reference states of solution.
Function/Subroutine Documentation
getstateshift()
pure real(wp) function, public xtb_solv_state::getstateshift (integer, intent(in) state, real(wp), intent(in) temperature, real(wp), intent(in) density, real(wp), intent(in) molecularMass)
Parameters
[in] state Reference state
[in] temperature Temperature of the solution
[in] density Mass density of the solvent
[in] molecularmass Molecular mass of the solvent
Returns
Resulting shift to the solvation free energy
Definition at line 55 of file state.f90.
    integer, intent(in) :: state
    real(wp), intent(in) :: temperature
    real(wp), intent(in) :: density
    real(wp), intent(in) :: molecularMass
    real(wp) :: freeEnergyShift
    select case(state)
    case default
       freeenergyshift = 0.0_wp
    case(solutionstate%reference)
       freeenergyshift = temperature * boltzmann &
          & * (log(idealgasmolvolume * temperature / ambienttemperature) &
          & + log(density/refdensity * refmolecularmass/molecularmass))
    case(solutionstate%mol1bar)
       freeenergyshift = temperature * boltzmann &
          & * log(idealgasmolvolume * temperature / ambienttemperature)
    end select
References ambienttemperature, idealgasmolvolume, refdensity, refmolecularmass, and solutionstate.
Referenced by xtb_solv_model::init::initsolvmodel().
Variable Documentation
ambienttemperature
real(wp), parameter xtb_solv_state::ambienttemperature = 298.15_wp private
Definition at line 49 of file state.f90.
    real(wp), parameter :: ambientTemperature = 298.15_wp ! * Boltzman
Referenced by getstateshift().
idealgasmolvolume
real(wp), parameter xtb_solv_state::idealgasmolvolume = 24.79_wp private
Definition at line 48 of file state.f90.
    real(wp), parameter :: idealGasMolVolume = 24.79_wp
Referenced by getstateshift().
refdensity
real(wp), parameter xtb_solv_state::refdensity = 1.0e-3_wp private
Definition at line 46 of file state.f90.
    real(wp), parameter :: refDensity = 1.0e-3_wp ! kg__au/(1.0e10_wp*AA__Bohr)**3
Referenced by getstateshift().
refmolecularmass
real(wp), parameter xtb_solv_state::refmolecularmass = 1.0_wp private
Definition at line 47 of file state.f90.
    real(wp), parameter :: refMolecularMass = 1.0_wp ! amu__au
Referenced by getstateshift().
solutionstate
type(tsolutionstateenum), parameter, public xtb_solv_state::solutionstate = TSolutionStateEnum()
Actual solvation state enumerator.
Definition at line 43 of file state.f90.
    type(TSolutionStateEnum), parameter :: solutionState = tsolutionstateenum()
Referenced by getstateshift(), xtb_solv_model::info(), xtb_prog_main::parsearguments(), xtb_api_calculator::setsolvent_api(), test_eeq_model_gbsa(), and test_eeq_model_salt().