My Project: prob_module Module Reference
prob_module Module Reference
Functions/Subroutines
subroutine prob_metadynamic (metavar, nat, at, xyz, ebias, g)
subroutine prob_func ()
Variables
integer prob_c
logical prob_flag = .false.
real(8) prob_a
real(8) prob_l
real(8) prob_inv_l
Function/Subroutine Documentation
prob_func()
subroutine prob_module::prob_func
Definition at line 233 of file prob_mod.f90.
         write(*,*) "prob_func call! success!"
Referenced by xtb_prog_main::parsearguments().
prob_metadynamic()
subroutine prob_module::prob_metadynamic (type(metadyn_setvar), intent(in) metavar, integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), intent(inout) ebias, real(wp), dimension(3,nat), intent(inout) g)
Definition at line 19 of file prob_mod.f90.
        use xtb_mctc_accuracy, only : wp
        use xtb_type_setvar
        use xtb_lsrmsd
        use forpy_mod
        implicit none
        type(metadyn_setvar),intent(in) :: metavar
        integer, intent(in)    :: nat
        integer, intent(in)    :: at(nat)
        real(wp),intent(in)    :: xyz(3,nat)
        real(wp),intent(inout) :: ebias
        real(wp),intent(inout) :: g(3,nat)
        real(wp),allocatable   :: xyzref(:,:),grad(:,:),xyzdup(:,:)
        real(wp) :: U(3,3), x_center(3), y_center(3)
        real(wp) :: etmp,rmsdval,e
        integer  :: i,j,k,iref,iat
       !  integer :: ierror
       !  type(module_py) :: opt
       !  type(ndarray) :: nd_c, nd_b_ub, nd_A_ub, nd_x
       !  type(object) :: retval, attr
       !  type(tuple) :: args
       !  real(dp) :: c(2) = [-300._dp, -500._dp]
       !  real(dp) :: b_ub(3) = [170._dp, 150._dp, 180._dp]
       !  real(dp) :: A_ub(3,2)
       !  real(dp), dimension(:), pointer :: x
       !  real(dp) :: objective_fun_value
       !  type(module_py) :: pymod
       !  type(list) :: paths
       !  type(tuple) :: argsval
       !  type(object) :: returnval
       !  A_ub(1,1) = 1.0_dp
       !  A_ub(2,1) = 1.0_dp
       !  A_ub(3,1) = 0.0_dp
       !  A_ub(1,2) = 2.0_dp
       !  A_ub(2,2) = 1.0_dp
       !  A_ub(3,2) = 3.0_dp
       !  ierror = forpy_initialize()
       !  ierror = import_py(opt, "scipy.optimize")
       !  ierror = ndarray_create(nd_c, c)
       !  ierror = ndarray_create(nd_b_ub, b_ub)
       !  ierror = ndarray_create(nd_A_ub, A_ub)
       !  ierror = tuple_create(args, 3)
       !  ierror = args%setitem(0, nd_c)
       !  ierror = args%setitem(1, nd_A_ub)
       !  ierror = args%setitem(2, nd_b_ub)
       !  ierror = call_py(retval, opt, "linprog", args)
       !  ierror = retval%getattribute(attr, "x")
       !  ierror = cast(nd_x, attr)
       !  ierror = nd_x%get_data(x)
       !  call attr%destroy
       !  ierror = retval%getattribute(attr, "fun")
       !  ierror = cast(objective_fun_value, attr)
       !  call attr%destroy
       !  ierror = get_sys_path(paths)
       !  ierror = paths%append(".")
       !  ierror = import_py(pymod, "pymodule")
       !  ierror = tuple_create(argsval, 1)
       !  ierror = argsval%setitem(0, nd_c)
       !  ierror = call_py(returnval, pymod, "initialize", argsval)
       !  call pymod%destroy
       !  call paths%destroy
       !  call argsval%destroy
       !  call returnval%destroy
       !  print *, "Solution: x = ", x
       !  print *, "Valueee of objective function: fun = ", objective_fun_value
       !  call retval%destroy
       !  call args%destroy
       !  call nd_c%destroy
       !  call nd_b_ub%destroy
       !  call nd_A_ub%destroy
       !  call nd_x%destroy
       !  call opt%destroy
       !  call forpy_finalize()
        prob_inv_l =  1.0d0/prob_l
        if(metavar%nstruc < 1 ) return
       if (prob_flag) then
          if (metavar%nat == 0) then
             allocate( xyzref(3,nat), grad(3,nat),source = 0.0_wp )
             !$omp parallel default(none) &
             !$omp shared(metavar,nat,xyz, prob_a, prob_l, prob_inv_l) & ! omp shared(metavar,nat,xyz)
             !$omp private(grad,xyzref,U,x_center,y_center,rmsdval,e,etmp) &
             !$omp reduction(+:ebias,g)
             !$omp do schedule(dynamic)
             do iref = 1, metavar%nstruc
                grad = 0.0_wp
                xyzref = metavar%xyz(:,:,iref)
                call rmsd(nat,xyz,xyzref,1,u,x_center,y_center,rmsdval, &
                         .true.,grad)
                ! e = metavar%factor(iref) * exp(-metavar%width(iref) * rmsdval**2)    !<-----------------
                e =  prob_a*prob_inv_l*exp(-1.73205_wp * rmsdval * prob_inv_l) * (prob_l + 1.73205_wp*rmsdval)
                ebias = ebias + e
                ! etmp = -2.0_wp * metavar%width(iref) * e * rmsdval
                etmp = 1.73205_wp * prob_a * prob_inv_l * exp(-1.73205_wp * rmsdval * prob_inv_l) - 1.73205_wp * prob_inv_l * e
                g = g + etmp*grad
             enddo
             !$omp enddo
             !$omp end parallel
          else
             allocate( xyzref(3,metavar%nat), xyzdup(3,metavar%nat), grad(3,metavar%nat) )
             !$omp parallel default(none) &
             !$omp shared(metavar,nat,xyz, prob_a, prob_l, prob_inv_l) & ! omp shared(metavar,nat,xyz)
             !$omp private(grad,xyzref,xyzdup,U,x_center,y_center,rmsdval,e,etmp,i,iat) &
             !$omp reduction(+:ebias,g)
             !$omp do schedule(dynamic)
             do iref = 1, metavar%nstruc
                grad = 0.0_wp
                do i = 1, metavar%nat
                   iat = metavar%atoms(i)
                   xyzref(:,i) = metavar%xyz(:,iat,iref)
                   xyzdup(:,i) = xyz(:,iat)
                enddo
                call rmsd(metavar%nat,xyzdup,xyzref,1,u,x_center,y_center,rmsdval, &
                         .true.,grad)
                ! e = metavar%factor(iref) * exp(-metavar%width(iref) * rmsdval**2)  !<----------------
                e =  prob_a*prob_inv_l*exp(-1.73205_wp * rmsdval * prob_inv_l) * (prob_l + 1.73205_wp*rmsdval)
                ebias = ebias + e
                ! etmp = -2.0_wp * metavar%width(iref) * e * rmsdval
                etmp = 1.73205_wp * prob_a * prob_inv_l * exp(-1.73205_wp * rmsdval * prob_inv_l) - 1.73205_wp * prob_inv_l * e
                do i = 1, metavar%nat
                   iat = metavar%atoms(i)
                   g(:,iat) = g(:,iat) + etmp*grad(:,i)
                enddo
             enddo
             !$omp enddo
             !$omp end parallel
             deallocate( xyzdup )
          endif
          deallocate( xyzref, grad )
       else
          if (metavar%nat == 0) then
             allocate( xyzref(3,nat), grad(3,nat),source = 0.0_wp )
             !$omp parallel default(none) &
             !$omp shared(metavar,nat,xyz) &
             !$omp private(grad,xyzref,U,x_center,y_center,rmsdval,e,etmp) &
             !$omp reduction(+:ebias,g)
             !$omp do schedule(dynamic)
             do iref = 1, metavar%nstruc
                grad = 0.0_wp
                xyzref = metavar%xyz(:,:,iref)
                call rmsd(nat,xyz,xyzref,1,u,x_center,y_center,rmsdval, &
                         .true.,grad)
                e = metavar%factor(iref) * exp(-metavar%width(iref) * rmsdval**2)
                ebias = ebias + e
                etmp = -2.0_wp * metavar%width(iref) * e * rmsdval
                g = g + etmp*grad
             enddo
             !$omp enddo
             !$omp end parallel
          else
             allocate( xyzref(3,metavar%nat), xyzdup(3,metavar%nat), grad(3,metavar%nat) )
             !$omp parallel default(none) &
             !$omp shared(metavar,nat,xyz) &
             !$omp private(grad,xyzref,xyzdup,U,x_center,y_center,rmsdval,e,etmp,i,iat) &
             !$omp reduction(+:ebias,g)
             !$omp do schedule(dynamic)
             do iref = 1, metavar%nstruc
                grad = 0.0_wp
                do i = 1, metavar%nat
                   iat = metavar%atoms(i)
                   xyzref(:,i) = metavar%xyz(:,iat,iref)
                   xyzdup(:,i) = xyz(:,iat)
                enddo
                call rmsd(metavar%nat,xyzdup,xyzref,1,u,x_center,y_center,rmsdval, &
                         .true.,grad)
                e = metavar%factor(iref) * exp(-metavar%width(iref) * rmsdval**2)
                ebias = ebias + e
                etmp = -2.0_wp * metavar%width(iref) * e * rmsdval
                do i = 1, metavar%nat
                   iat = metavar%atoms(i)
                   g(:,iat) = g(:,iat) + etmp*grad(:,i)
                enddo
             enddo
             !$omp enddo
             !$omp end parallel
             deallocate( xyzdup )
          endif
          deallocate( xyzref, grad )
       end if
       !  write(stdout,*) "Calling prob_metadynamic()..."
       !  print *, 'Call prob_metadynamic()...'
References prob_a, prob_flag, prob_inv_l, prob_l, xtb_lsrmsd::rmsd(), true(), and xtb_mctc_accuracy::wp.
Referenced by constrhess(), xtb_dynamic::md(), xtb_hessian::numhess_rmsd(), xtb_gfnff_calculator::singlepoint(), xtb_type_dummycalc::singlepoint(), and xtb_xtb_calculator::singlepoint().
Variable Documentation
prob_a
real(8) prob_module::prob_a
Definition at line 13 of file prob_mod.f90.
     real(8) :: prob_a, prob_l, prob_inv_l
Referenced by xtb_prog_main::parsearguments(), and prob_metadynamic().
prob_c
integer prob_module::prob_c
Definition at line 10 of file prob_mod.f90.
     integer :: prob_c
prob_flag
logical prob_module::prob_flag = .false.
Definition at line 11 of file prob_mod.f90.
     logical :: prob_flag = .false.
Referenced by constrhess(), xtb_dynamic::md(), xtb_hessian::numhess_rmsd(), xtb_prog_main::parsearguments(), prob_metadynamic(), xtb_gfnff_calculator::singlepoint(), xtb_type_dummycalc::singlepoint(), and xtb_xtb_calculator::singlepoint().
prob_inv_l
real(8) prob_module::prob_inv_l
Definition at line 13 of file prob_mod.f90.
Referenced by prob_metadynamic().
prob_l
real(8) prob_module::prob_l
Definition at line 13 of file prob_mod.f90.
Referenced by xtb_prog_main::parsearguments(), and prob_metadynamic().