My Project: xtb_mctc_sort Module Reference
xtb_mctc_sort Module Reference
Implements sorting algorithms.
Functions/Subroutines
pure subroutine, public indexheapsort (indx, array, tolerance)
Real case heap sort returning an index.
Detailed Description
Implements sorting algorithms.
Function/Subroutine Documentation
indexheapsort()
pure subroutine, public xtb_mctc_sort::indexheapsort (integer, dimension(:), intent(out) indx, real(wp), dimension(:), intent(in) array, real(wp), intent(in), optional tolerance)
Real case heap sort returning an index.
Parameters
[out] indx Indexing array on return
[in] array Array of values to be sorted
[in] tolerance Tolerance for equality of two elements
Definition at line 32 of file sort.f90.
    integer, intent(out) :: indx(:)
    real(wp), intent(in) :: array(:)
    real(wp), intent(in), optional :: tolerance
    integer :: n, ir, ij, il, ii
    integer :: indxTmp
    real(wp) :: arrayTmp, tol
    !:ASSERT(size(array)==size(indx))
    if (present(tolerance)) then
       tol = tolerance
    else
       tol = epsilon(0.0_wp)
    end if
    do ii = 1, size(indx)
       indx(ii) = ii
    end do
    n = size(array)
    if (n <= 1) return
    il = n/2 + 1
    ir = n
    do
       if (il > 1) then
          il = il - 1
          indxtmp = indx(il)
          arraytmp = array(indxtmp)
       else
          indxtmp = indx(ir)
          arraytmp = array(indxtmp)
          indx(ir) = indx(1)
          ir = ir - 1
          if (ir < 1) then
             indx(1) = indxtmp
             return
          end if
       end if
       ii = il
       ij = 2 * il
       do while (ij <= ir)
          if (ij < ir) then
             if (array(indx(ij)) < array(indx(ij+1)) - tol) then
                ij = ij + 1
             end if
          end if
          if(arraytmp < array(indx(ij)) - tol) then
             indx(ii) = indx(ij)
             ii = ij
             ij = 2*ij
          else
             ij = ir + 1
          end if
       end do
       indx(ii)=indxtmp
    end do
Referenced by xtb_type_wignerseitzcell::generate(), xtb_type_latticepoint::generatepbc3d(), and xtb_type_neighbourlist::sort().