My Project: xtb_readin Module Reference
xtb_readin Module Reference
Data Types
interface getvalue
Functions/Subroutines
character(len=:) function, allocatable xfind (name)
subroutine strip_line (in, line, err)
subroutine mirror_line (in, out, line, err)
character(len=:) function, allocatable find_new_name (fname)
logical function getintvalue (env, val, dum)
logical function getrealvalue (env, val, dum)
logical function getboolvalue (env, val, dum)
logical function getintarray (env, val, dum)
logical function getrealarray (env, val, dum)
pure elemental integer function bool2int (bool)
pure character(len=:) function, allocatable bool2string (bool)
logical function getlistvalue (env, val, dum, n)
subroutine readlog (fname, nat, at, xyz, nstruc)
Variables
character, parameter, private flag = '$'
character, parameter, private space = ' '
character, parameter, private equal = '='
character, parameter, private hash = '#'
character, parameter, private dot = '.'
character, parameter, private comma = ','
character, parameter, private minus = '-'
character(len= *), parameter, private flag_end = '$end'
Function/Subroutine Documentation
bool2int()
pure elemental integer function xtb_readin::bool2int (logical, intent(in) bool)
Definition at line 253 of file readin.f90.
    logical,intent(in) :: bool
    integer :: int
    if (bool) then
       int = 1
    else
       int = 0
    endif
Referenced by xtb_setmod::write_set_embedding(), xtb_setmod::write_set_gfn(), xtb_setmod::write_set_md(), xtb_setmod::write_set_opt(), xtb_setmod::write_set_siman(), and xtb_setmod::write_set_write().
bool2string()
pure character(len=:) function, allocatable xtb_readin::bool2string (logical, intent(in) bool)
Definition at line 263 of file readin.f90.
    logical,intent(in) :: bool
    character(len=:),allocatable :: string
    if (bool) then
       string = 'true'
    else
       string = 'false'
    endif
Referenced by xtb_optimizer::ancopt(), xtb_extern_mopac::checkmopac(), xtb_extern_orca::checkorca(), xtb_peeq::peeq(), xtb_propertyoutput::print_thermo(), xtb_scf::scf(), xtb_setmod::write_set_embedding(), xtb_setmod::write_set_gbsa(), xtb_setmod::write_set_gfn(), xtb_setmod::write_set_md(), xtb_setmod::write_set_opt(), xtb_setmod::write_set_siman(), and xtb_setmod::write_set_write().
find_new_name()
character(len=:) function, allocatable xtb_readin::find_new_name (character(len=*), intent(in) fname)
Definition at line 128 of file readin.f90.
    character(len=*),intent(in)  :: fname
    character(len=:),allocatable :: newname
    character(len=5) :: dum ! five digit number must be enough
    character,parameter :: hash = '#'
    character,parameter :: dot = '.'
    integer :: i,idot
    logical :: exist
    idot = index(fname,dot)
    i = 0
    do
       i = i+1
       write(dum,'(i0)') i
       if (idot == 1) then
          newname = dot//hash//trim(dum)//fname
       else
          newname = hash//trim(dum)//dot//fname
       endif
       inquire(file=newname,exist=exist)
       if (.not.exist) return
    enddo
References dot, and hash.
Referenced by xtb_setmod::rdcontrol(), and xtb_constrain_param::read_userdata().
getboolvalue()
logical function xtb_readin::getboolvalue (type(tenvironment), intent(inout) env, character(len=*), intent(in) val, logical, intent(out) dum)
Definition at line 191 of file readin.f90.
    implicit none
    character(len=*), parameter :: source = 'readin_getBoolValue'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: val
    logical,intent(out) :: dum
    logical :: status
    select case(val)
    case('Y','y','Yes','yes','T','t','true','True','1')
       status = .true.
       dum = .true.
    case('N','n','No','no','F','f','false','False','0')
       status = .true.
       dum = .false.
    case default
       call env%warning('could not parse '''//val//'''',source)
       status = .false.
    end select
getintarray()
logical function xtb_readin::getintarray (type(tenvironment), intent(inout) env, character(len=*), intent(in) val, integer, dimension(:), intent(out) dum)
Definition at line 213 of file readin.f90.
    implicit none
    character(len=*), parameter :: source = 'readin_getIntArray'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: val
    integer,intent(out) :: dum(:)
    integer :: i,err
    logical :: status
 !  call value(val,dum,ios=err)
    read(val,*,iostat=err) (dum(i),i=1,size(dum,1))
    if (err.eq.0) then
       status = .true.
    else
       call env%warning('could not parse '''//val//'''',source)
       status = .false.
    endif
getintvalue()
logical function xtb_readin::getintvalue (type(tenvironment), intent(inout) env, character(len=*), intent(in) val, integer, intent(out) dum)
Definition at line 153 of file readin.f90.
    implicit none
    character(len=*), parameter :: source = 'readin_getIntValue'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: val
    integer,intent(out) :: dum
    integer :: err
    logical :: status
 !  call value(val,dum,ios=err)
    read(val,*,iostat=err) dum
    if (err.eq.0) then
       status = .true.
    else
       call env%warning('could not parse '''//val//'''',source)
       status = .false.
    endif
getlistvalue()
logical function xtb_readin::getlistvalue (type(tenvironment), intent(inout) env, character(len=*), intent(in) val, integer, dimension(:), intent(out) dum, integer, intent(out) n)
Definition at line 273 of file readin.f90.
    implicit none
    character(len=*), parameter :: source = 'readin_getListValue'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: val
    integer,intent(out) :: dum(:)
    integer,intent(out) :: n
    integer :: i,j,k,l,err
    logical :: status
    i = index(val,minus)
    if (i.eq.0) then
       read(val,*,iostat=err) dum(1)
       if (err.ne.0) then
          call env%warning('could not parse '''//val//'''',source)
          status = .false.
          return
       endif
       n = 1
       status = .true.
    else
       read(val(:i-1),*,iostat=err) j
       if (err.ne.0) then
          call env%warning('could not parse '''//val(:i-1)//''' in '''//val//'''',source)
          status = .false.
          return
       endif
       read(val(i+1:),*,iostat=err) k
       if (err.ne.0) then
          call env%warning('could not parse '''//val(i+1:)//''' in '''//val//'''',source)
          status = .false.
          return
       endif
       if (k.lt.j) then
          call env%warning('end is lower than start in list '''//val//'''',source)
          status = .false.
          return
       endif
       if ((k-j).gt.size(dum,1)) then
          call env%warning('too many list items in '''//val//'''',source)
          status = .false.
          return
       endif
       n = 0
       do i = j, k
          n = n+1
          dum(n) = i
       enddo
       status = .true.
    endif
References minus, and true().
Referenced by xtb_constrain_param::set_split(), and xtb_constrain_param::set_wall().
getrealarray()
logical function xtb_readin::getrealarray (type(tenvironment), intent(inout) env, character(len=*), intent(in) val, real(wp), dimension(:), intent(out) dum)
Definition at line 233 of file readin.f90.
    implicit none
    character(len=*), parameter :: source = 'readin_getRealArray'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: val
    real(wp),intent(out) :: dum(:)
    integer :: i,err
    logical :: status
 !  call value(val,dum,ios=err)
    read(val,*,iostat=err) (dum(i),i=1,size(dum,1))
    if (err.eq.0) then
       status = .true.
    else
       call env%warning('could not parse '''//val//'''',source)
       status = .false.
    endif
getrealvalue()
logical function xtb_readin::getrealvalue (type(tenvironment), intent(inout) env, character(len=*), intent(in) val, real(wp), intent(out) dum)
Definition at line 172 of file readin.f90.
    implicit none
    character(len=*), parameter :: source = 'readin_getRealValue'
    type(TEnvironment), intent(inout) :: env
    character(len=*),intent(in) :: val
    real(wp),intent(out) :: dum
    integer :: err
    logical :: status
 !  call value(val,dum,ios=err)
    read(val,*,iostat=err) dum
    if (err.eq.0) then
       status = .true.
    else
       call env%warning('could not parse '''//val//'''',source)
       status = .false.
    endif
mirror_line()
subroutine xtb_readin::mirror_line (integer, intent(in) in, integer, intent(in) out, character(len=:), intent(out), allocatable line, integer, intent(out) err)
Definition at line 100 of file readin.f90.
    use xtb_mctc_systools, only : getline
    implicit none
    integer,intent(in)  :: in
    integer,intent(in)  :: out
    character(len=:),allocatable,intent(out) :: line
    integer,intent(out) :: err
    integer :: ic
    call getline(in,line,iostat=err)
    if (err.ne.0) return
 !  now write the line to the copy, we write what we read, not what we see
 !  if (out.ne.-1) write(out,'(a)') trim(line)
 !  check for comment characters
    ic = index(line,hash)
    if (ic.eq.1) then
       line = ''
       return
    else if (ic.gt.1) then
       line = line(:ic-1)
    endif
 !  now write the line to the copy, we write what we see, not what we read
    if (out.ne.-1) write(out,'(a)') trim(line)
 !  strip line from space, but after printing
    line = trim(adjustl(line))
References xtb_mctc_systools::getline(), and hash.
Referenced by xtb_setmod::rdblock(), and xtb_setmod::rdsetbl().
readlog()
subroutine xtb_readin::readlog (character(len=*), intent(in) fname, integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat,nstruc), intent(out) xyz, integer, intent(inout) nstruc)
Definition at line 325 of file readin.f90.
    use xtb_mctc_convert
    use xtb_mctc_systools
    implicit none
    character(len=*),intent(in) :: fname
    integer, intent(in)    :: nat
    integer, intent(in)    :: at(nat)
    real(wp),intent(out)   :: xyz(3,nat,nstruc)
    integer, intent(inout) :: nstruc
    character(len=:),allocatable :: line
    real(wp) :: floats(3),f
    character(len=80)  :: strings(3)
    integer  :: j,k,cs,cf,ncheck
    integer  :: ich ! file handle
    integer  :: idum,i,err
    call open_file(ich,fname,'r')
    if (ich.eq.-1) then
       call raise('E',"Could not find '"//fname//"'!")
    endif
    j = 0
    read_struc: do
       read(ich,*,iostat=err) idum
       if (err /= 0) exit read_struc
       if (idum /= nat) then
          call raise('E',"Atom number missmatch in '"//fname//"'!")
       endif
       if (j .ge. nstruc) exit read_struc
       read(ich,'(a)')
       if (err /= 0) exit read_struc
       do i = 1, nat
          call getline(ich,line,err)
          if (err /= 0) exit read_struc
          call readline(line,floats,strings,cs,cf)
          xyz(:,i,j+1)=floats*aatoau
       enddo
       j = j+1
    enddo read_struc
    nstruc = j
    call close_file(ich)
References xtb_mctc_convert::aatoau, close_file(), xtb_mctc_systools::getline(), open_file(), raise(), and readline().
Referenced by xtb_metadynamic::load_metadynamic().
strip_line()
subroutine xtb_readin::strip_line (integer, intent(in) in, character(len=:), intent(out), allocatable line, integer, intent(out) err)
Definition at line 73 of file readin.f90.
    use xtb_mctc_systools, only : getline
    implicit none
    integer,intent(in)  :: in
    character(len=:),allocatable,intent(out) :: line
    integer,intent(out) :: err
    integer :: ic
    call getline(in,line,iostat=err)
    if (err.ne.0) return
 !  check for comment characters
    ic = index(line,hash)
    if (ic.eq.1) then
       line = ''
       return
    else if (ic.gt.1) then
       line = line(:ic-1)
    endif
    line = trim(adjustl(line))
References xtb_mctc_systools::getline(), and hash.
Referenced by xtb_extern_orca::checkorca(), xtb_embedding::read_pcem(), and xtb_readparam::readparam().
xfind()
character(len=:) function, allocatable xtb_readin::xfind (character(len=*), intent(in) name)
Definition at line 53 of file readin.f90.
    use xtb_mctc_systools, only : rdpath
    use xtb_setparam, only : xenv
    character(len=*),intent(in)  :: name
    character(len=:),allocatable :: fname
    character(len=:),allocatable :: dum
    logical :: exist
    call rdpath(xenv%path,name,dum,exist)
    if (exist) then
       fname = dum
    else
       fname = name
    endif
References xtb_mctc_systools::rdpath(), and xtb_setparam::xenv.
Referenced by xtb_gfnff_convert::struc_convert(), and xtb_prog_main::xtbmain().
Variable Documentation
comma
character, parameter, private xtb_readin::comma = ',' private
Definition at line 29 of file readin.f90.
    character,private,parameter :: comma = ','
dot
character, parameter, private xtb_readin::dot = '.' private
Definition at line 28 of file readin.f90.
    character,private,parameter :: dot = '.'
Referenced by find_new_name().
equal
character, parameter, private xtb_readin::equal = '=' private
Definition at line 26 of file readin.f90.
    character,private,parameter :: equal = '='
flag
character, parameter, private xtb_readin::flag = '$' private
Definition at line 24 of file readin.f90.
    character,private,parameter :: flag = '$'
Referenced by xtb_io_reader_turbomole::readmoleculecoord().
flag_end
character(len=*), parameter, private xtb_readin::flag_end = '$end' private
Definition at line 31 of file readin.f90.
    character(len=*),private,parameter :: flag_end = '$end'
hash
character, parameter, private xtb_readin::hash = '#' private
Definition at line 27 of file readin.f90.
    character,private,parameter :: hash = '#'
Referenced by find_new_name(), mirror_line(), and strip_line().
minus
character, parameter, private xtb_readin::minus = '-' private
Definition at line 30 of file readin.f90.
    character,private,parameter :: minus = '-'
Referenced by getlistvalue().
space
character, parameter, private xtb_readin::space = ' ' private
Definition at line 25 of file readin.f90.
    character,private,parameter :: space = ' '