My Project: xtb_mctc_constants Module Reference
xtb_mctc_constants Module Reference
Variables
real(wp), parameter, public pi = 3.1415926535897932384626433832795029_wp
real(wp), parameter, public pi4 = 3.1415926535897932384626433832795029_wp*4._wp
real(wp), parameter, public sqrtpi = sqrt(pi)
real(wp), parameter, public twopi = 2.0_wp * pi
real(wp), parameter, public fourpi = 4.0_wp * pi
real(wp), parameter, public pihalf = 0.5_wp * pi
real(wp), parameter, public twothirdpi = 2.0_wp * pi / 3.0_wp
real(wp), parameter, public kb = 3.166808578545117e-06_wp
real(wp), parameter, public lightspeed = 137.0359990740_wp
Variable Documentation
fourpi
real(wp), parameter, public xtb_mctc_constants::fourpi = 4.0_wp * pi
Definition at line 29 of file mctc_constants.f90.
    real(wp),public,parameter :: fourpi = 4.0_wp * pi
Referenced by xtb_solv_model::paramtomodel(), and xtb_propertyoutput::print_gbsa_info().
kb
real(wp), parameter, public xtb_mctc_constants::kb = 3.166808578545117e-06_wp
Definition at line 35 of file mctc_constants.f90.
    real(wp),public,parameter :: kB = 3.166808578545117e-06_wp
Referenced by xtb_sphereparam::cavity_egrad(), xtb_scc_core::fermismear(), xtb_sphereparam::logfermi_cavity::logfermi_cavity_all(), xtb_sphereparam::logfermi_cavity::logfermi_cavity_frag(), xtb_sphereparam::logfermi_cavity::logfermi_cavity_list(), xtb_dynamic::md(), xtb_thermo::oldthermo(), xtb_sphereparam::polynomial_cavity::polynomial_cavity_all(), xtb_sphereparam::polynomial_cavity::polynomial_cavity_frag(), xtb_sphereparam::polynomial_cavity::polynomial_cavity_list(), xtb_propertyoutput::print_thermo_sthr_ts(), and xtb_thermo::thermodyn().
lightspeed
real(wp), parameter, public xtb_mctc_constants::lightspeed = 137.0359990740_wp
Definition at line 37 of file mctc_constants.f90.
    real(wp),public,parameter :: lightspeed = 137.0359990740_wp
pi
real(wp), parameter, public xtb_mctc_constants::pi = 3.1415926535897932384626433832795029_wp
Definition at line 22 of file mctc_constants.f90.
    real(wp),public,parameter :: pi = 3.1415926535897932384626433832795029_wp
Referenced by xtb_gfnff_eg::abhgfnff_eg3(), xtb_gfnff_eg::abhgfnff_eg3_add(), xtb_gfnff_eg::abhgfnff_eg3_mul(), xtb_solv_gbsa::addbornderiv(), xtb_solv_kernel::addbornderivsaltstill(), xtb_solv_kernel::addbornderivstill(), xtb_solv_kernel::addbornmatsaltstill(), xtb_solv_kernel::addbornmatstill(), xtb_basis::atovlp(), xtb_modelhessian::bend2(), xtb_xtb_hamiltonian_gpu::build_dsdqh0_gpu(), xtb_xtb_hamiltonian_gpu::build_sdqh0_gpu(), xtb_peeq::ccm_build_dsh0(), xtb_scanparam::constrain_all_angles(), xtb_scanparam::constrain_all_torsions(), xtb_constrainpot::constrain_dihedral(), constrallangles(), constralltors(), constrpot(), xtb_disp_coordinationnumber::derfcount(), xtb_aespot::dsint(), xtb_gfnff_eg::egbend(), xtb_gfnff_eg::egbend_nci(), xtb_gfnff_eg::egbend_nci_mul(), xtb_gfnff_eg::egtors(), xtb_gfnff_eg::egtors_nci(), xtb_gfnff_eg::egtors_nci_mul(), xtb_coulomb_ewald::ewaldderivpbc3d(), xtb_coulomb_ewald::ewaldderivpbc3d_alp(), xtb_coulomb_ewald::ewaldmatpbc3d(), xtb_coulomb_klopmanohno::getcoulombderivspbc3d(), xtb_coulomb_gaussian::getcoulombderivspbc3d(), xtb_type_coulomb::getcoulombderivspbc3d(), xtb_coulomb_klopmanohno::getcoulombmatrixpbc3d(), xtb_coulomb_gaussian::getcoulombmatrixpbc3d(), xtb_type_coulomb::getcoulombmatrixpbc3d(), xtb_coulomb_ewald::getgtermpbc3d(), xtb_gfnff_ini::gfnff_ini(), xtb_thermo::lnqrot(), xtb_local::local(), xtb_dynamic::md(), xtb_modelhessian::mh_lindh_outofp(), xtb_modelhessian::mh_lindh_torsion(), xtb_modelhessian::mh_swart_outofp(), xtb_modelhessian::mh_swart_torsion(), xtb_thermo::oldthermo(), xtb_modelhessian::outofp2(), xtb_peeq::pbc_build_dsh0(), xtb_scanparam::pot_info(), print_angles(), print_pbcsum(), xtb_propertyoutput::print_thermo_sthr_ts(), print_torsions(), xtb_io_reader_turbomole::readmoleculecoord(), xtb_hessian::rotmol(), xtb_intgrad::sdqint_gpu(), xtb_constrain_param::set_constr(), xtb_constrain_param::set_scan(), xtb_type_coulomb::setupboundaryconditions(), test_coulomb_gaussian_pbc3d(), test_coulomb_gfn1_pbc3d(), test_coulomb_gfn2_pbc3d(), test_coulomb_point_pbc3d(), test_repulsion_pbc3d(), xtb_thermo::thermodyn(), xtb_modelhessian::trsn2(), xtb_basic_geo::valijkl(), xtb_setmod::write_set_constrain(), xtb_setmod::write_set_scan(), and zmatpr().
pi4
real(wp), parameter, public xtb_mctc_constants::pi4 = 3.1415926535897932384626433832795029_wp*4._wp
Definition at line 23 of file mctc_constants.f90.
    real(wp),public,parameter :: pi4 = 3.1415926535897932384626433832795029_wp*4._wp
pihalf
real(wp), parameter, public xtb_mctc_constants::pihalf = 0.5_wp * pi
Definition at line 31 of file mctc_constants.f90.
    real(wp),public,parameter :: pihalf = 0.5_wp * pi
sqrtpi
real(wp), parameter, public xtb_mctc_constants::sqrtpi = sqrt(pi)
Definition at line 25 of file mctc_constants.f90.
    real(wp),public,parameter ::  sqrtpi  = sqrt(pi)
Referenced by xtb_intgrad::build_kab(), xtb_disp_ncoord::derf_count(), xtb_eeq::eeq_chrgeq::eeq_chrgeq_core(), xtb_eeq::eeq_ewald_3d_dir(), xtb_eeq::eeq_ewald_dx_3d_dir(), xtb_eeq::get_coulomb_derivs::get_coulomb_derivs_0d(), xtb_eeq::get_coulomb_derivs::get_coulomb_derivs_3d(), xtb_coulomb_gaussian::getcoulombderivscluster(), xtb_coulomb_gaussian::getcoulombmatrixcluster(), xtb_coulomb_gaussian::getcoulombmatrixpbc3d(), xtb_coulomb_klopmanohno::getrderiv(), xtb_coulomb_gaussian::getrderiv(), xtb_type_coulomb::getrderiv(), xtb_coulomb_klopmanohno::getrterm(), xtb_coulomb_gaussian::getrterm(), xtb_type_coulomb::getrterm(), xtb_gfnff_eg::gfnff_eg(), xtb_eeq::goedecker_chrgeq(), test_coulomb_gaussian_cluster(), test_coulomb_gaussian_pbc3d(), test_coulomb_gfn1_pbc3d(), test_coulomb_gfn2_pbc3d(), test_coulomb_point_pbc3d(), test_repulsion_cluster(), and test_repulsion_pbc3d().
twopi
real(wp), parameter, public xtb_mctc_constants::twopi = 2.0_wp * pi
Definition at line 27 of file mctc_constants.f90.
    real(wp),public,parameter :: twopi = 2.0_wp * pi
Referenced by xtb_thermo::oldthermo().
twothirdpi
real(wp), parameter, public xtb_mctc_constants::twothirdpi = 2.0_wp * pi / 3.0_wp
Definition at line 33 of file mctc_constants.f90.
    real(wp),public,parameter :: twothirdpi = 2.0_wp * pi / 3.0_wp
Referenced by xtb_mctc_math::eigval3x3().