My Project: xtb_onetri Module Reference
xtb_onetri Module Reference
Functions/Subroutines
subroutine, public onetri (ity, s, s1, array, n, ival)
Function/Subroutine Documentation
onetri()
subroutine, public xtb_onetri::onetri (integer, intent(in) ity, real(wp), dimension(*), intent(in) s, real(wp), dimension(*), intent(inout) s1, real(wp), dimension(n,ival), intent(in) array, integer, intent(in) n, integer, intent(in) ival)
Definition at line 28 of file onetri.f90.
    !     ******designed for abelian groups only******
    !
    !     calling sequence:
    !     ity       =1 sym ao
    !               =-1 anti sym ao
    !     s         input property matrix over ao's
    !     s1        transformed integrals on output
    !     s2        scratch arrays large enough to hold a square matrix
    !     array     mo matrix over so's
    !     n         linear dimension of arrays
    !     bernd hess, university of bonn, january 1991
    integer, intent(in) :: n
    integer, intent(in) :: ity
    integer, intent(in) :: ival
    real(wp), intent(in) :: s(*)
    real(wp), intent(inout) :: s1(*)
    real(wp), intent(in) :: array(n,ival)
    real(wp) :: s2(n,n)
    external :: dsymm, dgemm ! can't use wrappers due to change of leading dim
    !
    !     determine if we have an antisymmetric integral
    if (ity /= -1) then
       !
       !     blow up symmetric matrix s
       call blowsy(ity,s,s1,n)
       !
       !     transformation of s
       call dsymm('l','l',n,ival,1.d0,s1,n,array,n,0.d0,s2,n)
       call dgemm('t','n',ival,ival,n,1.d0,array,n,s2,n,0.d0,s1,ival)
    else
       !
       !     blow up anti-symmetric matrix s
       call blowsy(ity,s,s1,n)
       !
       !     transformation of s
       call dgemm('n','n',n,ival,n,1.d0,s1,n,array,n,0.d0,s2,n)
       call dgemm('t','n',ival,ival,n,1.d0,array,n,s2,n,0.d0,s1,ival)
    end if
References xtb_blowsy::blowsy().
Referenced by xtb_hlex::hlex(), and xtb_local::local().