My Project: xtb_geoopt Module Reference
xtb_geoopt Module Reference
Functions/Subroutines
subroutine geometry_optimization (env, mol, wfn, calc, egap, et, maxiter, maxcycle_in, etot, g, sigma, tight, pr, initial_sp, fail)
Function/Subroutine Documentation
geometry_optimization()
subroutine xtb_geoopt::geometry_optimization (type(tenvironment), intent(inout) env, type(tmolecule), intent(inout) mol, type(trestart), intent(inout) wfn, class(tcalculator), intent(inout) calc, real(wp), intent(inout) egap, real(wp), intent(in) et, integer, intent(in) maxiter, integer, intent(in) maxcycle_in, real(wp), intent(inout) etot, real(wp), dimension(3,mol%n), intent(inout) g, real(wp), dimension(3,3), intent(inout) sigma, integer, intent(in) tight, logical, intent(in) pr, logical, intent(in) initial_sp, logical, intent(out) fail)
Parameters
[in,out] env Calculation environment
Definition at line 21 of file geoopt_driver.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_io, only : stdout
    use xtb_type_molecule
    use xtb_type_restart
    use xtb_type_calculator
    use xtb_type_data
    use xtb_optimizer
    use xtb_relaxation_engine
    use xtb_single
    use xtb_setparam
    implicit none
    character(len=*), parameter :: source = 'xtb_geoopt'
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(inout) :: mol
    integer, intent(in)    :: tight
    integer, intent(in)    :: maxiter
    integer, intent(in)    :: maxcycle_in
    type(TRestart),intent(inout) :: wfn
    class(TCalculator), intent(inout) :: calc
    real(wp),intent(inout) :: etot
    real(wp),intent(in)    :: et
    real(wp),intent(inout) :: egap
    real(wp),intent(inout) :: g(3,mol%n)
    real(wp),intent(inout) :: sigma(3,3)
    logical, intent(in)    :: pr
    logical, intent(out)   :: fail
    logical, intent(in)    :: initial_sp
    type(scc_results) :: res
    logical :: final_sp, exitRun
    integer :: printlevel
    integer :: ilog
    final_sp = pr
    if (pr) then
       call delete_file('NOT_CONVERGED')
       call delete_file('.xtboptok')
       printlevel = 2
    else
       printlevel = 0
    endif
    if (.not.allocated(opt_logfile)) then
       call open_file(ilog,'xtbopt.log','w')
    else
       if (opt_logfile == '-') then
          ilog = stdout
       else
          call open_file(ilog,opt_logfile,'w')
          if (pr) write(stdout,'(/,a)') &
             "Optimization log is written to '"//opt_logfile//"'"
       endif
    endif
    call mol%update
    if (initial_sp) then
       call singlepoint &
          &(env,mol,wfn,calc, &
          & egap,et,maxiter,printlevel-1,.false.,.false.,1.0_wp,etot,g,sigma,res)
    endif
    select case(opt_engine)
    case(p_engine_rf)
       call ancopt &
          &(env,ilog,mol,wfn,calc, &
          & egap,et,maxiter,maxcycle_in,etot,g,sigma,tight,pr,fail)
       ! required since ANCopt might perform an untracked displacement
       final_sp = .true.
    case(p_engine_lbfgs)
       call l_ancopt &
          &(env,ilog,mol,wfn,calc, &
          & tight,maxcycle_in,etot,egap,g,sigma,printlevel,fail)
    case(p_engine_inertial)
       call fire &
          &(env,ilog,mol,wfn,calc, &
          & tight,maxcycle_in,etot,egap,g,sigma,printlevel,fail)
    end select
    if (pr) then
       if (fail) then
          call touch_file('NOT_CONVERGED')
          call env%warning("Geometry optimization did not converge", source)
       else
          call touch_file('.xtboptok')
       endif
    end if
    call env%check(exitrun)
    if (exitrun) then
       call env%rescue("Trying to recover from failed geometry optimization", source)
       fail = .true.
    end if
    if (pr.and.pr_finalstruct) then
       write(env%unit,'(''================'')')
       write(env%unit,*) 'final structure:'
       write(env%unit,'(''================'')')
       call writemolecule(mol, env%unit)
    endif
    if (pr.and.pr_geosum) call geosum(mol%n,mol%at,mol%xyz)
    if (final_sp) then
       if (pr) call generic_header(env%unit,'Final Singlepoint',49,10)
       call singlepoint &
          &(env,mol,wfn,calc, &
          & egap,et,maxiter,printlevel,.false.,.false.,1.0_wp,etot,g,sigma,res)
    endif
    if (ilog .ne.stdout) call close_file(ilog)
References xtb_optimizer::ancopt(), close_file(), delete_file(), xtb_relaxation_engine::fire(), generic_header(), geosum(), xtb_relaxation_engine::l_ancopt(), open_file(), xtb_setparam::opt_engine, xtb_setparam::opt_logfile, xtb_setparam::p_engine_inertial, xtb_setparam::p_engine_lbfgs, xtb_setparam::p_engine_rf, xtb_setparam::pr_finalstruct, xtb_setparam::pr_geosum, touch_file(), true(), and xtb_mctc_accuracy::wp.
Referenced by xtb_kopt::get_rmsd(), xtb_mdoptim::mdopt(), xtb_modef::modefollow(), xtb_scan::relaxed_scan(), xtb_screening::screen(), xtb_gfnff_convert::struc_convert(), and xtb_prog_main::xtbmain().