My Project: xtb_api_interface Module Reference
xtb_api_interface Module Reference
Actual calculation interface.
Functions/Subroutines
subroutine, public singlepoint_api (venv, vmol, vcalc, vres)
Detailed Description
Actual calculation interface.
Function/Subroutine Documentation
singlepoint_api()
subroutine, public xtb_api_interface::singlepoint_api (type(c_ptr), value venv, type(c_ptr), value vmol, type(c_ptr), value vcalc, type(c_ptr), value vres)
Definition at line 41 of file interface.f90.
    character(len=*), parameter :: source = 'xtb_api_singlepoint'
    type(c_ptr), value :: venv
    type(VEnvironment), pointer :: env
    type(c_ptr), value :: vmol
    type(VMolecule), pointer :: mol
    type(c_ptr), value :: vcalc
    type(VCalculator), pointer :: calc
    type(c_ptr), value :: vres
    type(VResults), pointer :: res
    type(scc_results) :: spRes
    if (c_associated(venv)) then
       call c_f_pointer(venv, env)
       call checkglobalenv
       if (.not.c_associated(vmol)) then
          call env%ptr%error("Molecular structure data is not allocated", source)
          return
       end if
       call c_f_pointer(vmol, mol)
       if (.not.c_associated(vcalc)) then
          call env%ptr%error("Singlepoint calculator is not allocated", source)
          return
       end if
       call c_f_pointer(vcalc, calc)
       if (.not.allocated(calc%ptr)) then
          call env%ptr%error("No calculator loaded for single point", &
             & source)
          return
       end if
       if (.not.c_associated(vres)) then
          call env%ptr%error("Calculation results are not allocated", source)
          return
       end if
       call c_f_pointer(vres, res)
       ! check cache, automatically invalidate missmatched data
       if (allocated(res%chk)) then
          select type(xtb => calc%ptr)
          type is(txtbcalculator)
             if (res%chk%wfn%n /= mol%ptr%n .or. res%chk%wfn%n /= xtb%basis%n .or. &
                & res%chk%wfn%nao /= xtb%basis%nao .or. &
                & res%chk%wfn%nshell /= xtb%basis%nshell) then
                deallocate(res%chk)
             end if
          end select
       end if
       if (.not.allocated(res%chk)) then
          allocate(res%chk)
          ! in case of a new wavefunction cache we have to perform an initial guess
          select type(xtb => calc%ptr)
          type is(txtbcalculator)
             call newwavefunction(env%ptr, mol%ptr, xtb, res%chk)
          end select
       end if
       if (.not.allocated(res%energy)) then
          allocate(res%energy)
       end if
       if (.not.allocated(res%egap)) then
          allocate(res%egap)
       end if
       if (allocated(res%gradient)) then
          if (any(shape(res%gradient) /= [3, mol%ptr%n])) then
             call env%ptr%warning("Shape missmatch in gradient, reallocating", source)
             deallocate(res%gradient)
          end if
       end if
       if (.not.allocated(res%gradient)) then
          allocate(res%gradient(3, mol%ptr%n))
       end if
       if (allocated(res%sigma)) then
          if (any(shape(res%sigma) /= [3, 3])) then
             call env%ptr%warning("Shape missmatch in virial, reallocating", source)
             deallocate(res%sigma)
          end if
       end if
       if (.not.allocated(res%sigma)) then
          allocate(res%sigma(3, 3))
       end if
       call calc%ptr%singlepoint(env%ptr, mol%ptr, res%chk, env%verbosity, .true., &
          & res%energy, res%gradient, res%sigma, res%egap, spres)
       ! invalidate cache for properties not produced in GFN-FF
       select type(gfnff => calc%ptr)
       type is(tgffcalculator)
          deallocate(res%chk)
          deallocate(res%egap)
          deallocate(res%sigma)
       end select
       res%dipole = spres%dipole
    end if
References xtb_api_utils::checkglobalenv(), xtb_main_setup::newwavefunction(), and true().