My Project: xtb_approxrab Module Reference
xtb_approxrab Module Reference
Functions/Subroutines
pure subroutine, public pbc_approx_rab (n, at, xyz, cn, dcndr, dcndL, nsrb, srblist, shift, rab, drabdr, drabdL)
pure subroutine, public approx_bonds (n, at, xyz, cn, bonds, shift)
pure subroutine, public approx_rab (n, at, xyz, cn, dcndr, nsrb, srblist, shift, rab, grab)
pure elemental integer function itr (i)
Variables
real(wp), dimension(86), private cnfak
real(wp), dimension(86), private r0
real(wp), dimension(86), private en
real(wp), dimension(4, 2), private p
Function/Subroutine Documentation
approx_bonds()
pure subroutine, public xtb_approxrab::approx_bonds (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension(n), intent(in) cn, integer, dimension(n,n), intent(out) bonds, real(wp), intent(in) shift)
Definition at line 151 of file approxrab.f90.
    implicit none
    ! intent in
    integer,                  intent(in) :: n
    integer,  dimension(n),   intent(in) :: at
    real(wp), dimension(3,n), intent(in) :: xyz
    real(wp), dimension(n),   intent(in) :: cn
    real(wp),                 intent(in) :: shift
    ! intent inout
    integer,  dimension(n,n), intent(out) :: bonds
    ! local variable
    integer :: i,j,k,m
    integer :: iat,jat,ati,atj
    integer :: ir,jr
    real(wp) :: ra,rb
    real(wp) :: den
    real(wp) :: k1,k2
    real(wp) :: ff,tmp
    real(wp) :: r2,rab,rij(3)
    bonds = 0
    do i = 1, n
       bonds(i,i) = ceiling(cn(i))
       do j = 1, i-1
          rij = xyz(:,i) - xyz(:,j)
          r2 = sum(rij**2)
          if (r2.gt.200.0_wp) cycle
          ati = at(i)
          atj = at(j)
          ir = itr(ati)
          jr = itr(atj)
          ra=r0(ati)+cnfak(ati)*cn(i)+shift
          rb=r0(atj)+cnfak(atj)*cn(j)+shift
          den=abs(en(ati) - en(atj))
          k1=0.005_wp*(p(ir,1) + p(jr,1))
          k2=0.005_wp*(p(ir,2) + p(jr,2))
          ff=1.0_wp - k1*den - k2*den**2
          ! save distances => rab
          rab = ((ra + rb)*ff)**2
          if (r2 < rab) then
             bonds(i,j) = 1
             bonds(j,i) = 1
          endif
       enddo ! k
    enddo ! k
References cnfak, en, itr(), p, and r0.
Referenced by print_geosum().
approx_rab()
pure subroutine, public xtb_approxrab::approx_rab (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension(n), intent(in) cn, real(wp), dimension(3,n,n), intent(in) dcndr, integer, intent(in) nsrb, integer, dimension(2,nsrb), intent(in) srblist, real(wp), intent(in) shift, real(wp), dimension(nsrb), intent(out) rab, real(wp), dimension(3,n,nsrb), intent(out) grab)
Definition at line 200 of file approxrab.f90.
    implicit none
    ! intent in
    integer,                    intent(in) :: n
    integer,                    intent(in) :: nsrb
    integer, dimension(n),      intent(in) :: at
    integer, dimension(2,nsrb), intent(in) :: srblist
    real(wp), dimension(3,n),   intent(in) :: xyz
    real(wp), dimension(n),     intent(in) :: cn
    real(wp), dimension(3,n,n), intent(in) :: dcndr
    real(wp), intent(in) :: shift
    ! intent inout
    real(wp), dimension(nsrb),     intent(out) :: rab
    real(wp), dimension(3,n,nsrb), intent(out) :: grab
    ! local variable
    integer :: i,j,k,m
    integer :: iat,jat,ati,atj
    integer :: ir,jr
    real(wp) :: ra,rb
    real(wp) :: den
    real(wp) :: k1,k2
    real(wp) :: ff
    rab  = 0.0_wp
    grab = 0.0_wp
    do concurrent(k = 1:nsrb)
       ! enroll srblist
       i = srblist(1,k)
       j = srblist(2,k)
       ati = at(i)
       atj = at(j)
       ir = itr(ati)
       jr = itr(atj)
       ra=r0(ati)+cnfak(ati)*cn(i)+shift
       rb=r0(atj)+cnfak(atj)*cn(j)+shift
       den=abs(en(ati) - en(atj))
       k1=0.005_wp*(p(ir,1) + p(jr,1))
       k2=0.005_wp*(p(ir,2) + p(jr,2))
       ff=1.0_wp - k1*den - k2*den**2
       ! save distances => rab
       rab(k) = (ra + rb)*ff
       ! save gradient => grab
       do m = 1, n
          grab(:,m,k)=ff*(cnfak(ati)*dcndr(:,m,i)&
             &          + cnfak(atj)*dcndr(:,m,j))
       enddo ! m
    enddo ! k
References cnfak, en, itr(), p, and r0.
itr()
pure elemental integer function xtb_approxrab::itr (integer, intent(in) i) private
Definition at line 252 of file approxrab.f90.
    implicit none
    integer, intent(in) :: i
    itr = 0
    if(i.gt.0.and.i.le.2) then
       itr = 1
    elseif(i.gt.2.and.i.le.10) then
       itr = 2
    elseif(i.gt.10.and.i.le.18) then
       itr = 3
    elseif(i.gt.18) then
       itr = 4
    endif
    return
Referenced by approx_bonds(), approx_rab(), and pbc_approx_rab().
pbc_approx_rab()
pure subroutine, public xtb_approxrab::pbc_approx_rab (integer, intent(in) n, integer, dimension(n), intent(in) at, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension(n), intent(in) cn, real(wp), dimension(3,n,n), intent(in) dcndr, real(wp), dimension(3,3,n), intent(in) dcndL, integer, intent(in) nsrb, integer, dimension(2,nsrb), intent(in) srblist, real(wp), intent(in) shift, real(wp), dimension(nsrb), intent(out) rab, real(wp), dimension(3,n,nsrb), intent(out) drabdr, real(wp), dimension(3,3,nsrb), intent(out) drabdL)
Definition at line 98 of file approxrab.f90.
    implicit none
    ! intent in
    integer,                    intent(in) :: n
    integer,                    intent(in) :: nsrb
    integer, dimension(n),      intent(in) :: at
    integer, dimension(2,nsrb), intent(in) :: srblist
    real(wp), dimension(3,n),   intent(in) :: xyz
    real(wp), dimension(n),     intent(in) :: cn
    real(wp), dimension(3,n,n), intent(in) :: dcndr
    real(wp), dimension(3,3,n), intent(in) :: dcndL
    real(wp), intent(in) :: shift
    ! intent inout
    real(wp), dimension(nsrb),     intent(out) :: rab
    real(wp), dimension(3,n,nsrb), intent(out) :: drabdr
    real(wp), dimension(3,3,nsrb), intent(out) :: drabdL
    ! local variable
    integer :: i,j,k,m
    integer :: iat,jat,ati,atj
    integer :: ir,jr
    real(wp) :: ra,rb
    real(wp) :: den
    real(wp) :: k1,k2
    real(wp) :: ff
    rab  = 0.0_wp
    drabdr = 0.0_wp
    drabdl = 0.0_wp
    do concurrent(k = 1:nsrb)
       ! enroll srblist
       i = srblist(1,k)
       j = srblist(2,k)
       ati = at(i)
       atj = at(j)
       ir = itr(ati)
       jr = itr(atj)
       ra=r0(ati)+cnfak(ati)*cn(i)+shift
       rb=r0(atj)+cnfak(atj)*cn(j)+shift
       den=abs(en(ati) - en(atj))
       k1=0.005_wp*(p(ir,1) + p(jr,1))
       k2=0.005_wp*(p(ir,2) + p(jr,2))
       ff=1.0_wp - k1*den - k2*den**2
       ! save distances => rab
       rab(k) = (ra + rb)*ff
       ! save gradient => drabdr
       drabdr(:,:,k) = ff*(cnfak(ati)*dcndr(:,:,i) + cnfak(atj)*dcndr(:,:,j))
       drabdl(:,:,k) = ff*(cnfak(ati)*dcndl(:,:,i) + cnfak(atj)*dcndl(:,:,j))
    enddo ! k
References cnfak, en, itr(), p, and r0.
Referenced by xtb_peeq::dsrb_grad().
Variable Documentation
cnfak
real(wp), dimension(86), private xtb_approxrab::cnfak private
Definition at line 25 of file approxrab.f90.
   real(wp),private, dimension(86) :: cnfak
Referenced by approx_bonds(), approx_rab(), and pbc_approx_rab().
en
real(wp), dimension(86), private xtb_approxrab::en private
Definition at line 27 of file approxrab.f90.
   real(wp),private, dimension(86) :: en
Referenced by approx_bonds(), approx_rab(), xtb_peeq::dsrb_grad(), and pbc_approx_rab().
p
real(wp), dimension(4,2), private xtb_approxrab::p private
Definition at line 28 of file approxrab.f90.
   real(wp),private, dimension(4,2):: p
Referenced by approx_bonds(), approx_rab(), init_ultimate_plane(), and pbc_approx_rab().
r0
real(wp), dimension(86), private xtb_approxrab::r0 private
Definition at line 26 of file approxrab.f90.
   real(wp),private, dimension(86) :: r0
Referenced by approx_bonds(), approx_rab(), and pbc_approx_rab().