My Project: xtb_printout Module Reference
xtb_printout Module Reference
Functions/Subroutines
subroutine writecosmofile (np, pa, espe, fname, nat, at, xyz, atom_weight)
subroutine setup_summary (iunit, n, fname, xcontrol, wfx, xrc, exist)
Function/Subroutine Documentation
setup_summary()
subroutine xtb_printout::setup_summary (integer, intent(in) iunit, integer, intent(in) n, character(len=*), intent(in) fname, character(len=*), intent(in) xcontrol, type(twavefunction), intent(in) wfx, character(len=*), intent(in) xrc, logical, intent(in) exist)
Definition at line 59 of file printout.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_global, only : persistentenv
    use xtb_mctc_systools
    use xtb_type_wavefunction
    use xtb_setparam
    !$ use omp_lib
    implicit none
    type(TWavefunction),intent(in) :: wfx
    integer, intent(in) :: iunit
    character(len=*),intent(in) :: xrc
    character(len=*),intent(in) :: xcontrol
    character(len=*),intent(in) :: fname
    integer :: i,l,err
    integer,intent(in) :: n
    logical,intent(in) :: exist
    real(wp) :: dum5
    character(len=:),allocatable :: cdum
    write(iunit,'(a)')
    call generic_header(iunit,'Calculation Setup',49,10)
    write(iunit,'(a)')
    if (allocated(cdum)) deallocate(cdum)
    call get_command(length=l)
    allocate( character(len=l) :: cdum )
    call get_command(cdum)
    write(iunit,'(10x,a,":",1x,a)') 'program call               ',cdum
    call rdvar('HOSTNAME',cdum,err)
    if (err.eq.0) &
       write(iunit,'(10x,a,":",1x,a)') 'hostname                   ',cdum
    if (allocated(persistentenv%io%namespace)) &
       write(iunit,'(10x,a,":",1x,a)') 'calculation namespace      ',persistentenv%io%namespace
    ! ----------------------------------------------------------------------
    !  print the home and path to check if there are set correctly
    write(iunit,'(10x,a,":",1x,a)') 'coordinate file            ',fname
    if (verbose) then
       write(iunit,'(10x,a,":",1x,a)') 'xtbhome directory          ',xenv%home
       write(iunit,'(10x,a,":",1x,a)') 'path for xtb               ',xenv%path
       write(iunit,'(10x,a,":",1x,a)') 'xcontrol input file        ',xcontrol
       if (exist) &
          write(iunit,'(10x,a,":",1x,a)') 'global configurations file ',xrc
    endif
    ! ----------------------------------------------------------------------
    !  technical data
    !$omp parallel
    !$omp master
    !$ write(iunit,'(10x,a,":",6x,i16)') 'omp threads                ',omp_get_num_threads()
    !$omp end master
    !$omp end parallel
    ! ----------------------------------------------------------------------
    !  print more specific calculation data
    write(iunit,'(10x,a,":",6x,i16)')   'number of atoms            ',n
    write(iunit,'(10x,a,":",6x,i16)')   'number of electrons        ',wfx%nel
    write(iunit,'(10x,a,":",6x,i16)')   'charge                     ',ichrg
    write(iunit,'(10x,a,":",6x,f16.1)') 'spin                       ',0.5_wp*wfx%nopen
    call random_number(dum5)
    write(iunit,'(10x,a,":",6x,f16.14)') 'first test random number   ',dum5
    if (verbose) then
       write(iunit,'(10x,a,":",12x,"0x",z8)') 'a pointer address          ',real(dum5,sp)
       write(iunit,'(10x,a,":",6x,z16)') 'random memory content      ',dum5
    endif
    if (veryverbose) then
       write(iunit,'(10x,a,":",20x,a)') 'is this your card?         ',🃓""
       write(iunit,'(10x,a,":",15x,"so true")')'this was released?         '
    endif
    write(iunit,'(a)')
References generic_header(), xtb_setparam::ichrg, xtb_mctc_global::persistentenv, xtb_mctc_systools::rdvar(), xtb_setparam::verbose, xtb_setparam::veryverbose, xtb_mctc_accuracy::wp, and xtb_setparam::xenv.
Referenced by xtb_prog_main::xtbmain().
writecosmofile()
subroutine xtb_printout::writecosmofile (integer, intent(in) np, real(wp), dimension(3,np), intent(in) pa, real(wp), dimension(np), intent(in) espe, character(len=*), intent(in) fname, integer, intent(in) nat, integer, dimension(nat), intent(in) at, real(wp), dimension(3,nat), intent(in) xyz, real(wp), dimension(2,np), intent(in) atom_weight)
Definition at line 25 of file printout.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_convert, only : autoaa
    use xtb_mctc_symbols, only : tolcsymbol, tosymbol
    implicit none
    integer, intent(in)             :: np
    real(wp), intent(in)            :: pa(3,np)
    real(wp), intent(in)            :: espe(np)
    integer, intent(in)             :: at(nat)
    real(wp), intent(in)            :: xyz(3,nat)
    integer, intent(in)             :: nat
    character(len=*),intent(in)     :: fname
    real(wp),intent(in)             :: atom_weight(2,np)
    logical                         :: exist
    integer                         :: id, i
    call open_file(id,fname,'w')
    write(id,'(a)') '$coord_car'
    write(id,'(a,/,a)') '!BIOSYM archive 3','coordinates from COSMO calculation'
    do i=1,nat
       write(id,'("X1",1x,3f22.14,1x,"COSM 1",1x,a,1x,a,1x,"0.000")')&
          xyz(:,i)*autoaa,tolcsymbol(at(i)),tosymbol(at(i))
    enddo
    write(id,'(a)') 'end'
    write(id,'(a)') '$segment_information'
    do i=1,np
       write(id,'(2x,i5,2x,i0,4f22.14,1x,f22.14,1x,f22.14,1x,"0.000")')&
          i,int(atom_weight(1,i)), pa(:,i)*autoaa,espe(i)/10, &
          atom_weight(2,i)*100,espe(i)/10
    enddo
    call close_file(id)
References xtb_mctc_convert::autoaa, close_file(), open_file(), xtb_mctc_symbols::tolcsymbol(), xtb_mctc_symbols::tosymbol(), and xtb_mctc_accuracy::wp.
Referenced by esp::espplot().