My Project: xtb_io_reader_xyz Module Reference
xtb_io_reader_xyz Module Reference
Functions/Subroutines
subroutine, public readmoleculexyz (mol, unit, status, iomsg)
Variables
logical, parameter debug = .false.
Function/Subroutine Documentation
readmoleculexyz()
subroutine, public xtb_io_reader_xyz::readmoleculexyz (class(tmolecule), intent(out) mol, integer, intent(in) unit, logical, intent(out) status, character(len=:), intent(out), allocatable iomsg)
Definition at line 37 of file xyz.f90.
    class(TMolecule), intent(out) :: mol
    integer, intent(in) :: unit
    logical, intent(out) :: status
    character(len=:), allocatable, intent(out) :: iomsg
    integer  :: ii, n, iat
    character(len=symbolLength), allocatable :: sym(:)
    real(wp), allocatable :: xyz(:, :)
    real(wp) :: x, y, z
    real(wp) :: conv
    character(len=:),allocatable :: message
    character(len=:),allocatable :: line
    character(len=symbolLength) :: chdum
    integer  :: err
    status = .false.
    conv = aatoau
    read(unit,*,iostat=err) n
    if (err.ne.0) then
       iomsg = "Could not read number of atoms, check format!"
       return
    endif
    if (n.lt.1) then
       iomsg = "Found no atoms, cannot work without atoms!"
       return
    endif
    allocate(sym(n))
    allocate(xyz(3, n))
    ! drop next record
    read(unit,'(a)')
    ii = 0
    do while (ii < n)
       call getline(unit,line,err)
       if (is_iostat_end(err)) exit
       if (err.ne.0) then
          iomsg = "Could not read geometry from Xmol file"
          return
       endif
       if (debug) print'(">",a)',line
       read(line,*,iostat=err) chdum, x, y, z
       if (err.ne.0) then
          iomsg = "Could not parse coordinates from Xmol file"
          return
       endif
       if (debug) print'("->",a)',chdum
       if (debug) print'("->",3g0)',x, y, z
       iat = tonumber(chdum)
       if (debug) print'("->",g0)',iat
       if (iat > 0) then
          ii = ii+1
          sym(ii) = trim(chdum)
          xyz(:,ii) = [x, y, z]*conv
       else
          iomsg = "Unknown element symbol: '"//trim(chdum)//"'"
          return
       endif
    enddo
    if (ii.ne.n) then
       iomsg = "Atom number missmatch in Xmol file"
       return
    endif
    call init(mol, sym, xyz)
    status = .true.
References xtb_mctc_convert::aatoau, debug, xtb_mctc_symbols::tonumber(), and true().
Referenced by xtb_io_reader::readmolecule().
Variable Documentation
debug
logical, parameter xtb_io_reader_xyz::debug = .false. private
Definition at line 31 of file xyz.f90.
    logical, parameter :: debug = .false.
Referenced by readmoleculexyz().