My Project: xtb_type_iohandler Module Reference
xtb_type_iohandler Module Reference
Data Types
type tfilestatusenum
interface tfilehandle
type tiohandler
interface init
Functions/Subroutines
subroutine initiohandler (self, namespace)
elemental type(tfilehandle) function initfilehandle (name, status, unit, open)
subroutine getname (self, file, filename)
subroutine pushback (self, fileHandle)
subroutine findunit (self, unit, pos)
subroutine list (self, unit)
subroutine readfile (self, unit, file, iostat)
subroutine writefile (self, unit, file, iostat)
subroutine readbinary (self, unit, file, iostat)
subroutine writebinary (self, unit, file, iostat)
subroutine touchfile (self, file, iostat)
subroutine closefile (self, unit, iostat, remove)
subroutine deletefile (self, file, iostat)
Variables
type(tfilestatusenum), parameter filestatus = TFileStatusEnum()
Function/Subroutine Documentation
closefile()
subroutine xtb_type_iohandler::closefile (class(tiohandler), intent(inout) self, integer, intent(in) unit, integer, intent(out), optional iostat, logical, intent(in), optional remove) private
Definition at line 393 of file iohandler.f90.
    class(TIOHandler), intent(inout) :: self
    integer, intent(in) :: unit
    integer, intent(out), optional :: iostat
    logical, intent(in), optional :: remove
    integer :: pos, error
    logical :: delete
    if (present(remove)) then
       delete = remove
    else
       delete = .false.
    end if
    error = 0
    call self%findUnit(unit, pos)
    !$omp critical(io)
    if (pos > 0) then
       if (delete) then
          close(unit, iostat=error, status='delete')
       else
          close(unit, iostat=error)
       end if
       if (error == 0) then
          self%log(pos)%open = .false.
          if (delete) then
             self%log(pos)%status = filestatus%deleted
          end if
       end if
    else
       error = 1
    end if
    !$omp end critical(io)
    if (present(iostat)) then
       iostat = error
    end if
References filestatus.
deletefile()
subroutine xtb_type_iohandler::deletefile (class(tiohandler), intent(inout) self, character(len=*), intent(in) file, integer, intent(out), optional iostat) private
Definition at line 436 of file iohandler.f90.
    class(TIOHandler), intent(inout) :: self
    character(len=*), intent(in) :: file
    integer, intent(out), optional :: iostat
    character(len=:), allocatable :: name
    integer :: unit
    logical :: exist
    integer :: error
    unit = -1
    error = 0
    call self%getName(file, name)
    !$omp critical(io)
    inquire(file=name, exist=exist)
    if (exist) then
       open(file=name, newunit=unit, status='old', iostat=error)
       if (error == 0) then
          call self%pushBack(tfilehandle(name, filestatus%deleted, unit, .false.))
          close(unit, status='delete', iostat=error)
       end if
    else
       error = 1
    end if
    !$omp end critical(io)
    if (present(iostat)) then
       iostat = error
    end if
References filestatus.
findunit()
subroutine xtb_type_iohandler::findunit (class(tiohandler), intent(in) self, integer, intent(in) unit, integer, intent(out) pos) private
Definition at line 153 of file iohandler.f90.
    class(TIOHandler), intent(in) :: self
    integer, intent(in) :: unit
    integer, intent(out) :: pos
    integer :: i
    pos = 0
    do i = 1, self%count
       if (self%log(i)%open .and. self%log(i)%unit == unit) then
          pos = i
          exit
       end if
    end do
getname()
subroutine xtb_type_iohandler::getname (class(tiohandler), intent(inout) self, character(len=*), intent(in) file, character(len=:), intent(out), allocatable filename) private
Definition at line 112 of file iohandler.f90.
    class(TIOHandler), intent(inout) :: self
    character(len=*), intent(in) :: file
    character(len=:), allocatable, intent(out) :: filename
    if (allocated(self%namespace)) then
       if (index(file, '/') == 0) then
          if (file(1:1) == '.') then
             filename = '.'//self%namespace//file
          else
             filename = self%namespace//'.'//file
          end if
       else
          filename = file
       end if
    else
       filename = file
    end if
initfilehandle()
elemental type(tfilehandle) function xtb_type_iohandler::initfilehandle (character(len=*), intent(in) name, integer, intent(in) status, integer, intent(in) unit, logical, intent(in) open) private
Definition at line 97 of file iohandler.f90.
    character(len=*), intent(in) :: name
    integer, intent(in) :: status
    integer, intent(in) :: unit
    logical, intent(in) :: open
    type(TFileHandle) :: self
    self%name = name
    self%status = status
    self%unit = unit
    self%open = open
initiohandler()
subroutine xtb_type_iohandler::initiohandler (type(tiohandler), intent(out) self, character(len=*), intent(in), optional namespace) private
Definition at line 84 of file iohandler.f90.
    type(TIOHandler), intent(out) :: self
    character(len=*), intent(in), optional :: namespace
    if (present(namespace)) then
       self%namespace = namespace
    end if
    self%count = 0
    allocate(self%log(20))
list()
subroutine xtb_type_iohandler::list (class(tiohandler), intent(in) self, integer, intent(in) unit) private
Definition at line 170 of file iohandler.f90.
    class(TIOHandler), intent(in) :: self
    integer, intent(in) :: unit
    character(len=8) :: status
    integer :: i
    if (self%count > 0) then
       write(unit,'(1x,"unit",2x,"open",3x,"action",5x,"filename")')
    end if
    do i = 1, self%count
       select case(self%log(i)%status)
       case(filestatus%readin);   status = "read    "
       case(filestatus%written);  status = "written "
       case(filestatus%deleted);  status = "deleted "
       case(filestatus%replaced); status = "replaced"
       case(filestatus%created);  status = "created "
       case default;              status = "unknown "
       end select
       if (self%log(i)%open) then
          write(unit,'(i5,1x,a5,1x,":",1x,a8,3x,a)') &
             & abs(self%log(i)%unit), "true", status, self%log(i)%name
       else
          write(unit,'(i5,1x,a5,1x,":",1x,a8,3x,a)') &
             & abs(self%log(i)%unit), "false", status, self%log(i)%name
       end if
    end do
References filestatus.
pushback()
subroutine xtb_type_iohandler::pushback (class(tiohandler), intent(inout) self, type(tfilehandle), intent(in) fileHandle) private
Definition at line 134 of file iohandler.f90.
    class(TIOHandler), intent(inout) :: self
    type(TFileHandle), intent(in) :: fileHandle
    type(TFileHandle), allocatable :: tmp(:)
    integer :: n
    self%count = self%count + 1
    if (self%count > size(self%log)) then
       n = size(self%log)
       call move_alloc(self%log, tmp)
       allocate(self%log(n + n/2 + 1))
       self%log(1:n) = tmp
       deallocate(tmp)
    end if
    self%log(self%count) = filehandle
readbinary()
subroutine xtb_type_iohandler::readbinary (class(tiohandler), intent(inout) self, integer, intent(out) unit, character(len=*), intent(in) file, integer, intent(out), optional iostat) private
Definition at line 280 of file iohandler.f90.
    class(TIOHandler), intent(inout) :: self
    integer, intent(out) :: unit
    character(len=*), intent(in) :: file
    integer, intent(out), optional :: iostat
    character(len=:), allocatable :: name
    logical :: exist
    integer :: error
    unit = -1
    error = 0
    call self%getName(file, name)
    !$omp critical(io)
    inquire(file=name, exist=exist)
    if (exist) then
       open(file=name, newunit=unit, status='old', action='read', &
          & form='unformatted', iostat=error)
       if (error == 0) then
          call self%pushBack(tfilehandle(name, filestatus%readin, unit, .true.))
       else
          unit = -1
       end if
    else
       inquire(file=file, exist=exist)
       if (exist) then
          open(file=file, newunit=unit, status='old', action='read', &
             & form='unformatted', iostat=error)
          if (error == 0) then
             call self%pushBack(tfilehandle(file, filestatus%readin, unit, .true.))
          else
             unit = -1
          end if
       else
          error = 1
       end if
    end if
    !$omp end critical(io)
    if (present(iostat)) then
       iostat = error
    end if
References filestatus, and true().
readfile()
subroutine xtb_type_iohandler::readfile (class(tiohandler), intent(inout) self, integer, intent(out) unit, character(len=*), intent(in) file, integer, intent(out), optional iostat) private
Definition at line 200 of file iohandler.f90.
    class(TIOHandler), intent(inout) :: self
    integer, intent(out) :: unit
    character(len=*), intent(in) :: file
    integer, intent(out), optional :: iostat
    character(len=:), allocatable :: name
    logical :: exist
    integer :: error
    unit = -1
    error = 0
    call self%getName(file, name)
    !$omp critical(io)
    inquire(file=name, exist=exist)
    if (exist) then
       open(file=name, newunit=unit, status='old', action='read', iostat=error)
       if (error == 0) then
          call self%pushBack(tfilehandle(name, filestatus%readin, unit, .true.))
       else
          unit = -1
       end if
    else
       inquire(file=file, exist=exist)
       if (exist) then
          open(file=file, newunit=unit, status='old', action='read', iostat=error)
          if (error == 0) then
             call self%pushBack(tfilehandle(file, filestatus%readin, unit, .true.))
          else
             unit = -1
          end if
       else
          error = 1
       end if
    end if
    !$omp end critical(io)
    if (present(iostat)) then
       iostat = error
    end if
References filestatus, and true().
touchfile()
subroutine xtb_type_iohandler::touchfile (class(tiohandler), intent(inout) self, character(len=*), intent(in) file, integer, intent(out), optional iostat) private
Definition at line 362 of file iohandler.f90.
    class(TIOHandler), intent(inout) :: self
    character(len=*), intent(in) :: file
    integer, intent(out), optional :: iostat
    character(len=:), allocatable :: name
    integer :: unit, error
    logical :: exist
    error = 0
    call self%getName(file, name)
    !$omp critical(io)
    inquire(file=name, exist=exist)
    if (exist) then
       error = 1
    else
       open(file=name, newunit=unit, status='new', iostat=error)
       if (error == 0) then
          call self%pushBack(tfilehandle(name, filestatus%created, unit, .false.))
          close(unit, iostat=error)
       end if
    end if
    !$omp end critical(io)
    if (present(iostat)) then
       iostat = error
    end if
References filestatus.
writebinary()
subroutine xtb_type_iohandler::writebinary (class(tiohandler), intent(inout) self, integer, intent(out) unit, character(len=*), intent(in) file, integer, intent(out), optional iostat) private
Definition at line 327 of file iohandler.f90.
    class(TIOHandler), intent(inout) :: self
    integer, intent(out) :: unit
    character(len=*), intent(in) :: file
    integer, intent(out), optional :: iostat
    character(len=:), allocatable :: name
    logical :: exist
    integer :: error
    unit = -1
    error = 0
    call self%getName(file, name)
    !$omp critical(io)
    inquire(file=name, exist=exist)
    open(file=name, newunit=unit, action='write', form='unformatted', iostat=error)
    if (error == 0) then
       if (exist) then
          call self%pushBack(tfilehandle(name, filestatus%replaced, unit, .true.))
       else
          call self%pushBack(tfilehandle(name, filestatus%written, unit, .true.))
       end if
    else
       unit = -1
    end if
    !$omp end critical(io)
    if (present(iostat)) then
       iostat = error
    end if
References filestatus, and true().
writefile()
subroutine xtb_type_iohandler::writefile (class(tiohandler), intent(inout) self, integer, intent(out) unit, character(len=*), intent(in) file, integer, intent(out), optional iostat) private
Definition at line 245 of file iohandler.f90.
    class(TIOHandler), intent(inout) :: self
    integer, intent(out) :: unit
    character(len=*), intent(in) :: file
    integer, intent(out), optional :: iostat
    character(len=:), allocatable :: name
    logical :: exist
    integer :: error
    unit = -1
    error = 0
    call self%getName(file, name)
    !$omp critical(io)
    inquire(file=name, exist=exist)
    open(file=name, newunit=unit, action='write', iostat=error)
    if (error == 0) then
       if (exist) then
          call self%pushBack(tfilehandle(name, filestatus%replaced, unit, .true.))
       else
          call self%pushBack(tfilehandle(name, filestatus%written, unit, .true.))
       end if
    else
       unit = -1
    end if
    !$omp end critical(io)
    if (present(iostat)) then
       iostat = error
    end if
References filestatus, and true().
Variable Documentation
filestatus
type(tfilestatusenum), parameter xtb_type_iohandler::filestatus = TFileStatusEnum() private
Definition at line 36 of file iohandler.f90.
    type(TFileStatusEnum), parameter :: fileStatus = tfilestatusenum()
Referenced by closefile(), deletefile(), list(), readbinary(), readfile(), touchfile(), writebinary(), and writefile().