My Project: xtb_type_identitymap Module Reference
xtb_type_identitymap Module Reference
Implementation of a map from element symbols/atomic numbers to ids.
Data Types
type tatomicmap
Maps an identity to all its atoms.
type tidentitymap
Map from element symbols to identity.
interface init
Initialize identity map.
Functions/Subroutines
subroutine initidentitymapfrommolecule (self, mol)
Initialize identity map from molecular structure data.
subroutine initidentitymapfromarrays (self, id, sym, num)
Initialize identity map from at atomic numbers and element symbols.
subroutine writeinfo (self, unit)
subroutine serializeatomicmap (list, string, separator, delimiter)
pure logical function hassymbol (self, sym)
Check if element symbol maps to atoms.
pure logical function hasnumber (self, num)
Check if atomic number maps to atoms.
subroutine getindexsymbol (self, indx, sym)
Get indices for an unique element symbol.
subroutine getindexnumber (self, indx, num)
Get indices for a certain atomic number.
subroutine setrealwithsymbol (self, array, sym, val)
Set value in an array using an unique element symbol.
subroutine setrealwithnumber (self, array, num, val)
Set value in an array using the atomic number.
Detailed Description
Implementation of a map from element symbols/atomic numbers to ids.
Function/Subroutine Documentation
getindexnumber()
subroutine xtb_type_identitymap::getindexnumber (class(tidentitymap), intent(in) self, integer, dimension(:), intent(out), allocatable indx, integer, intent(in) num) private
Get indices for a certain atomic number.
Parameters
[in] self Instance of the map
[out] indx Indices for all selected atoms
[in] num Atomic number
Definition at line 323 of file identitymap.f90.
    class(TIdentityMap), intent(in) :: self
    integer, allocatable, intent(out) :: indx(:)
    integer, intent(in) :: num
    integer :: nAt, iId, newSize
    integer, allocatable :: pos(:)
    nat = 0
    do iid = 1, size(self%num)
       if (self%num(iid) == num) then
          newsize = nat + size(self%map(iid)%pos)
          if (newsize >= size(pos)) then
             call resize(pos, newsize)
          end if
          pos(nat+1:newsize) = self%map(iid)%pos
       end if
    end do
    if (nat > 0) then
       call move_alloc(pos, indx)
    end if
Referenced by xtb_type_identitymap::tidentitymap::get().
getindexsymbol()
subroutine xtb_type_identitymap::getindexsymbol (class(tidentitymap), intent(in) self, integer, dimension(:), intent(out), allocatable indx, character(len=*), intent(in) sym) private
Get indices for an unique element symbol.
Parameters
[in] self Instance of the map
[out] indx Indices for all selected atoms
[in] sym Element symbol
Definition at line 299 of file identitymap.f90.
    class(TIdentityMap), intent(in) :: self
    integer, allocatable, intent(out) :: indx(:)
    character(len=*), intent(in) :: sym
    integer :: iId
    do iid = 1, size(self%sym)
       if (self%sym(iid) == sym) then
          indx = self%map(iid)%pos
          exit
       end if
    end do
Referenced by xtb_type_identitymap::tidentitymap::get().
hasnumber()
pure logical function xtb_type_identitymap::hasnumber (class(tidentitymap), intent(in) self, integer, intent(in) num) private
Check if atomic number maps to atoms.
Parameters
[in] self Instance of the map
[in] num Atomic number
Returns
Number is present
Definition at line 282 of file identitymap.f90.
    class(TIdentityMap), intent(in) :: self
    integer, intent(in) :: num
    logical :: exist
    exist = any(self%num == num)
Referenced by xtb_type_identitymap::tidentitymap::has().
hassymbol()
pure logical function xtb_type_identitymap::hassymbol (class(tidentitymap), intent(in) self, character(len=*), intent(in) sym) private
Check if element symbol maps to atoms.
Parameters
[in] self Instance of the map
[in] sym Element symbol
Returns
Symbol is present
Definition at line 265 of file identitymap.f90.
    class(TIdentityMap), intent(in) :: self
    character(len=*), intent(in) :: sym
    logical :: exist
    exist = any(self%sym == sym)
Referenced by xtb_type_identitymap::tidentitymap::has().
initidentitymapfromarrays()
subroutine xtb_type_identitymap::initidentitymapfromarrays (type(tidentitymap), intent(out) self, integer, dimension(:), intent(in) id, character(len=symbollength), dimension(:), intent(in) sym, integer, dimension(:), intent(in) num) private
Initialize identity map from at atomic numbers and element symbols.
Parameters
[out] self Instance of the map
[in] id Atomic numbers for each id
[in] num Atomic numbers for each atom
[in] sym Element symbols for each atom
Definition at line 112 of file identitymap.f90.
    type(TIdentityMap), intent(out) :: self
    integer, intent(in) :: id(:)
    integer, intent(in) :: num(:)
    character(len=symbolLength), intent(in) :: sym(:)
    integer :: nAt, nId
    integer :: iId, iAt, thisAt, initialSize, nMp
    integer, allocatable :: pos(:)
    nat = size(id)
    nid = maxval(id)
    allocate(self%map(nid))
    allocate(self%num(nid))
    allocate(self%sym(nid))
    initialsize = nat / nid + 1
    allocate(pos(initialsize))
    do iid = 1, nid
       pos = 0
       nmp = 0
       thisat = 0
       do iat = 1, nat
          if (id(iat) == iid) then
             if (thisat == 0) thisat = iat
             if (nmp >= size(pos)) then
                call resize(pos)
             end if
             nmp = nmp + 1
             pos(nmp) = iat
          end if
       end do
       self%num(iid) = num(thisat)
       self%sym(iid) = sym(thisat)
       allocate(self%map(iid)%pos(nmp))
       self%map(iid)%pos(:) = pos(:nmp)
    end do
initidentitymapfrommolecule()
subroutine xtb_type_identitymap::initidentitymapfrommolecule (type(tidentitymap), intent(out) self, type(tmolecule), intent(in) mol) private
Initialize identity map from molecular structure data.
Parameters
[out] self Instance of the map
[in] mol Molecular structure data
Definition at line 98 of file identitymap.f90.
    type(TIdentityMap), intent(out) :: self
    type(TMolecule), intent(in) :: mol
    call init(self, mol%id, mol%sym, mol%at)
serializeatomicmap()
subroutine xtb_type_identitymap::serializeatomicmap (integer, dimension(:), intent(in) list, character(len=:), intent(out), allocatable string, character(len=*), intent(in), optional separator, character(len=*), intent(in), optional delimiter) private
Parameters
[in] list Instance of an atomic map
[out] string Serialized form of the atomic map
[in] separator Separator for list
[in] delimiter Separator for list
Definition at line 203 of file identitymap.f90.
    integer, intent(in) :: list(:)
    character(len=:), allocatable, intent(out) :: string
    character(len=*), intent(in), optional :: separator
    character(len=*), intent(in), optional :: delimiter
    integer :: ii, jj, kk
    character(len=64) :: buffer
    character(len=:), allocatable :: sep, del
    if (present(separator)) then
       sep = separator
    else
       sep = ', '
    end if
    if (present(delimiter)) then
       del = delimiter
    else
       del = '-'
    end if
    string = ''
    jj = list(1)
    kk = jj
    do ii = 2, size(list)
       if (jj+1 == list(ii)) then
          jj = jj+1
       else
          if (jj-kk == 0) then
             write(buffer, '(i0)') jj
          else if (jj-kk == 1) then
             write(buffer, '(i0,a,i0)') kk, del, jj
          else
             write(buffer, '(i0,a,i0)') kk, sep, jj
          end if
          string = string // trim(buffer) // del
          jj = list(ii)
          kk = jj
       end if
    end do
    if (jj-kk == 0) then
       write(buffer, '(i0)') jj
    else if (jj-kk == 1) then
       write(buffer, '(i0,a,i0)') kk, del, jj
    else
       write(buffer, '(i0,a,i0)') kk, sep, jj
    end if
    string = string // trim(buffer)
Referenced by writeinfo().
setrealwithnumber()
subroutine xtb_type_identitymap::setrealwithnumber (class(tidentitymap), intent(in) self, real(wp), dimension(:), intent(inout) array, integer, intent(in) num, real(wp), intent(in) val) private
Set value in an array using the atomic number.
Parameters
[in] self Instance of the map
[in,out] array Instance of the array
[in] num Atomic number
[in] val Value to set
Definition at line 382 of file identitymap.f90.
    class(TIdentityMap), intent(in) :: self
    real(wp), intent(inout) :: array(:)
    integer, intent(in) :: num
    real(wp), intent(in) :: val
    integer :: iId
    do iid = 1, size(self%num)
       if (self%num(iid) == num) then
          array(self%map(iid)%pos) = val
       end if
    end do
Referenced by xtb_type_identitymap::tidentitymap::set().
setrealwithsymbol()
subroutine xtb_type_identitymap::setrealwithsymbol (class(tidentitymap), intent(in) self, real(wp), dimension(:), intent(inout) array, character(len=*), intent(in) sym, real(wp), intent(in) val) private
Set value in an array using an unique element symbol.
Parameters
[in] self Instance of the map
[in,out] array Instance of the array
[in] sym Element symbol
[in] val Value to set
Definition at line 356 of file identitymap.f90.
    class(TIdentityMap), intent(in) :: self
    real(wp), intent(inout) :: array(:)
    character(len=*), intent(in) :: sym
    real(wp), intent(in) :: val
    integer :: iId
    do iid = 1, size(self%sym)
       if (self%sym(iid) == sym) then
          array(self%map(iid)%pos) = val
       end if
    end do
Referenced by xtb_type_identitymap::tidentitymap::set().
writeinfo()
subroutine xtb_type_identitymap::writeinfo (class(tidentitymap), intent(in) self, integer, intent(in) unit) private
Parameters
[in] self Instance of the map
[in] unit Unit for I/O
Definition at line 163 of file identitymap.f90.
    class(TIdentityMap), intent(in) :: self
    integer, intent(in) :: unit
    integer :: iId, iStart, iEnd, iDel
    character(len=:), allocatable :: list
    write(unit, '(a5,1x,a4,1x,a4,3x,a5)') "ID", "Z", "sym.", "atoms"
    do iid = 1, size(self%sym)
       write(unit, '(i5,1x,i4,1x,a4,3x)', advance='no') &
          & iid, self%num(iid), self%sym(iid)
       call serializeatomicmap(self%map(iid)%pos, list, '-', ', ')
       istart = 1
       iend = min(60, len(list))
       do while(istart <= len(list))
          if (iend >= len(list)) then
             idel = iend
          else
             idel = index(list(istart:iend), ' ', back=.true.) + istart - 2
             if (idel < istart) then
                idel = index(list(iend:), ' ') + iend - 2
                if (idel == iend - 2) idel = len(list)
             end if
          end if
          write(unit, '(a)') list(istart:idel)
          istart = idel+1
          iend = min(istart+60, len(list))
          if (istart < len(list)) then
             write(unit, '(17x)', advance='no')
          end if
       end do
    end do
References serializeatomicmap(), and true().