My Project: xtb_pbc_tools Module Reference
xtb_pbc_tools Module Reference
helper tools for periodic boundary conditions
Data Types
interface coord_trafo
Functions/Subroutines
pure subroutine cell_to_dlat (cellpar, lattice)
convert cell parameters to direct lattice
pure subroutine cell_to_rlat (cellpar, rec_lat)
convert cell parameters to reciprocal lattice
pure subroutine dlat_to_cell (lattice, cellpar)
convert direct lattice to cell parameters
pure subroutine dlat_to_rlat (lattice, rec_lat)
convert direct lattice to cell parameters
pure real(wp) function, dimension(3) cross (a, b)
implements the cross/vector product between two 3D vectors
pure real(wp) function mat_det_3x3 (a)
determinat of 3×3 matrix
pure real(wp) function, dimension(3, 3) mat_inv_3x3 (a)
Performs a direct calculation of the inverse of a 3×3 matrix.
pure real(wp) function cell_to_dvol (cellpar)
calculate the cell volume from the cell parameters
pure real(wp) function dlat_to_dvol (lattice)
calculate the cell volume from the direct lattice
pure real(wp) function dvol_to_rvol (dvol)
inverts volume of direct unit cell
pure subroutine abc_to_xyz (n, dlat, abc, xyz)
transform from fractional coordinates into cartesian coordinates
pure subroutine xyz_to_abc (n, dlat, xyz, abc, pbc)
transform from cartesian coordinates into fractional coordinates
pure elemental real(wp) function shift_back_abc (in)
shift back fractional coordinates into the range [0,1)
pure subroutine coord_trafo_12 (dim, trafo, coord1, coord2)
transform from one coordinate system into another
pure subroutine coord_trafo_inplace (dim, trafo, coord)
transform from one coordinate system into another
pure real(wp) function minimum_image_distance (lsame, fi, fj, dlat, lpbc)
calculate distance between to atoms under minimum image convention
pure real(wp) function, dimension(3) get_center_dlat (dlat)
calculate center of unit cell
pure real(wp) function, dimension(3, 3) outer_prod_3x3 (a, b)
pure subroutine latgrad_to_sigma (latgrad, lattice, sigma)
pure subroutine sigma_to_latgrad (sigma, inv_lat, latgrad)
Variables
real(wp), parameter tpi = 2.0_wp*pi
Detailed Description
helper tools for periodic boundary conditions
Function/Subroutine Documentation
abc_to_xyz()
pure subroutine xtb_pbc_tools::abc_to_xyz (integer, intent(in) n, real(wp), dimension(3,3), intent(in) dlat, real(wp), dimension(3,n), intent(in) abc, real(wp), dimension(3,n), intent(out) xyz)
transform from fractional coordinates into cartesian coordinates
Definition at line 217 of file pbc_tools.f90.
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: dlat(3,3)
    real(wp),intent(in)  :: abc(3,n)
    real(wp),intent(out) :: xyz(3,n)
    call coord_trafo(n,dlat,abc,xyz)
Referenced by xtb_io_reader_turbomole::readmoleculecoord(), xtb_io_reader_genformat::readmoleculegenformat(), and xtb_type_molecule::wrap_back().
cell_to_dlat()
pure subroutine xtb_pbc_tools::cell_to_dlat (real(wp), dimension(6), intent(in) cellpar, real(wp), dimension(3,3), intent(out) lattice)
convert cell parameters to direct lattice
Parameters
[in] cellpar cell parameters
[out] lattice direct lattice
Definition at line 40 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in)  :: cellpar(6)
    real(wp),intent(out) :: lattice(3,3)
    real(wp)             :: dvol
    dvol = cell_to_dvol(cellpar)
    associate( alen => cellpar(1), blen => cellpar(2), clen => cellpar(3), &
       &       alp  => cellpar(4), bet  => cellpar(5), gam  => cellpar(6) )
    lattice(1,1) = alen
    lattice(2,1) = 0.0_wp
    lattice(3,1) = 0.0_wp
    lattice(3,2) = 0.0_wp
    lattice(1,2) = blen*cos(gam)
    lattice(2,2) = blen*sin(gam)
    lattice(1,3) = clen*cos(bet)
    lattice(2,3) = clen*(cos(alp) - cos(bet)*cos(gam))/sin(gam);
    lattice(3,3) = dvol/(alen*blen*sin(gam))
    end associate
References cell_to_dvol().
Referenced by xtb_io_reader_turbomole::readmoleculecoord(), and test_pbc_tools_convert().
cell_to_dvol()
pure real(wp) function xtb_pbc_tools::cell_to_dvol (real(wp), dimension(6), intent(in) cellpar)
calculate the cell volume from the cell parameters
Parameters
[in] cellpar cell parameters
Definition at line 179 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in) :: cellpar(6)
    real(wp)            :: vol2
    real(wp)            :: dvol
    associate( alen => cellpar(1), blen => cellpar(2), clen => cellpar(3), &
       &       alp  => cellpar(4), bet  => cellpar(5), gam  => cellpar(6) )
    vol2 = 1.0_wp - cos(alp)**2 - cos(bet)**2 - cos(gam)**2 &
       & + 2.0_wp*cos(alp)*cos(bet)*cos(gam)
    dvol = sqrt(abs(vol2))*alen*blen*clen
    ! return negative volume instead of imaginary one (means bad cell parameters)
    if (vol2 < 0.0_wp) dvol = -dvol ! this should not happen, but who knows...
    end associate
Referenced by cell_to_dlat(), cell_to_rlat(), and test_pbc_tools_convert().
cell_to_rlat()
pure subroutine xtb_pbc_tools::cell_to_rlat (real(wp), dimension(6), intent(in) cellpar, real(wp), dimension(3,3), intent(out) rec_lat)
convert cell parameters to reciprocal lattice
Parameters
[in] cellpar cell parameters
[out] rec_lat reciprocal lattice
Definition at line 66 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in)  :: cellpar(6)
    real(wp),intent(out) :: rec_lat(3,3)
    real(wp)             :: dvol
    dvol = cell_to_dvol(cellpar)
    associate( alen => cellpar(1), blen => cellpar(2), clen => cellpar(3), &
       &       alp  => cellpar(4), bet  => cellpar(5), gam  => cellpar(6) )
    rec_lat(1,1) = tpi/alen
    rec_lat(1,2) = 0.0_wp
    rec_lat(1,3) = 0.0_wp
    rec_lat(2,1) =-tpi*cos(gam)/(alen*sin(gam))
    rec_lat(2,2) = tpi/(blen*sin(gam))
    rec_lat(2,3) = 0.0_wp
    rec_lat(3,1) = tpi*(cos(gam)*cos(alp) - cos(bet))*blen*clen/(dvol*sin(gam))
    rec_lat(3,2) = tpi*(cos(gam)*cos(bet) - cos(alp))*alen*clen/(dvol*sin(gam))
    rec_lat(3,3) = tpi*sin(gam)*alen*blen/dvol
    end associate
References cell_to_dvol(), and tpi.
Referenced by test_pbc_tools_convert().
coord_trafo_12()
pure subroutine xtb_pbc_tools::coord_trafo_12 (integer, intent(in) dim, real(wp), dimension(3,3), intent(in) trafo, real(wp), dimension(3,dim), intent(in) coord1, real(wp), dimension(3,dim), intent(out) coord2)
transform from one coordinate system into another
Definition at line 269 of file pbc_tools.f90.
    implicit none
    integer, intent(in)  :: dim
    real(wp),intent(in)  :: trafo(3,3)
    real(wp),intent(in)  :: coord1(3,dim)
    real(wp),intent(out) :: coord2(3,dim)
    integer i
    coord2 = 0.0_wp
    do concurrent(i = 1:dim)
       coord2(:,i) = matmul(trafo,coord1(:,i))
    enddo
coord_trafo_inplace()
pure subroutine xtb_pbc_tools::coord_trafo_inplace (integer, intent(in) dim, real(wp), dimension(3,3), intent(in) trafo, real(wp), dimension(3,dim), intent(inout) coord)
transform from one coordinate system into another
Definition at line 286 of file pbc_tools.f90.
    implicit none
    integer, intent(in)    :: dim
    real(wp),intent(in)    :: trafo(3,3)
    real(wp),intent(inout) :: coord(3,dim)
    real(wp) :: tmp(3)
    integer i
    do concurrent(i = 1:dim)
       tmp = coord(:,i)
       coord(:,i) = matmul(trafo,tmp)
    enddo
cross()
pure real(wp) function, dimension(3) xtb_pbc_tools::cross (real(wp), dimension(3), intent(in) a, real(wp), dimension(3), intent(in) b)
implements the cross/vector product between two 3D vectors
Definition at line 129 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in) :: a(3)
    real(wp),intent(in) :: b(3)
    real(wp)            :: c(3)
    c(1)=a(2)*b(3)-b(2)*a(3)
    c(2)=a(3)*b(1)-b(3)*a(1)
    c(3)=a(1)*b(2)-b(1)*a(2)
dlat_to_cell()
pure subroutine xtb_pbc_tools::dlat_to_cell (real(wp), dimension(3,3), intent(in) lattice, real(wp), dimension(6), intent(out) cellpar)
convert direct lattice to cell parameters
Parameters
[in] lattice direct lattice
[out] cellpar cell parameters
Definition at line 92 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in)  :: lattice(3,3)
    real(wp),intent(out) :: cellpar(6)
    associate( alen => cellpar(1), blen => cellpar(2), clen => cellpar(3), &
       &       alp  => cellpar(4), bet  => cellpar(5), gam  => cellpar(6) )
    alen = norm2(lattice(:,1))
    blen = norm2(lattice(:,2))
    clen = norm2(lattice(:,3))
    alp = acos(dot_product(lattice(:,2),lattice(:,3))/(blen*clen))
    bet = acos(dot_product(lattice(:,1),lattice(:,3))/(alen*clen))
    gam = acos(dot_product(lattice(:,1),lattice(:,2))/(alen*blen))
    end associate
Referenced by test_pbc_tools_convert(), and xtb_type_molecule::update().
dlat_to_dvol()
pure real(wp) function xtb_pbc_tools::dlat_to_dvol (real(wp), dimension(3,3), intent(in) lattice)
calculate the cell volume from the direct lattice
Parameters
[in] lattice direct lattice
Definition at line 199 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in) :: lattice(3,3)
    real(wp)            :: dvol
    dvol = abs(mat_det_3x3(lattice))
References mat_det_3x3().
Referenced by test_pbc_tools_convert(), and xtb_type_molecule::update().
dlat_to_rlat()
pure subroutine xtb_pbc_tools::dlat_to_rlat (real(wp), dimension(3,3), intent(in) lattice, real(wp), dimension(3,3), intent(out) rec_lat)
convert direct lattice to cell parameters
Parameters
[in] lattice direct lattice
[out] rec_lat reciprocal lattice
Definition at line 113 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in)  :: lattice(3,3)
    real(wp),intent(out) :: rec_lat(3,3)
 !  real(wp)             :: dvol
    rec_lat = tpi*transpose(mat_inv_3x3(lattice))
 !  alternative implementation
 !  dvol = dlat_volume(lattice)
 !  associate( a => lattice(:,1), b => lattice(:,2), c => lattice(:,3) )
 !     rec_lat(:,1) = tpi*cross(b,c)/dvol
 !     rec_lat(:,2) = tpi*cross(c,a)/dvol
 !     rec_lat(:,3) = tpi*cross(a,b)/dvol
 !  end associate
References mat_inv_3x3(), and tpi.
Referenced by test_pbc_tools_convert(), and xtb_type_molecule::update().
dvol_to_rvol()
pure real(wp) function xtb_pbc_tools::dvol_to_rvol (real(wp), intent(in) dvol)
inverts volume of direct unit cell
Parameters
[in] dvol direct volume
Returns
reciprocal volume
Definition at line 209 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in) :: dvol
    real(wp)            :: rvol
    rvol = tpi**3/dvol
References tpi.
get_center_dlat()
pure real(wp) function, dimension(3) xtb_pbc_tools::get_center_dlat (real(wp), dimension(3,3), intent(in) dlat)
calculate center of unit cell
Definition at line 362 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in) :: dlat(3,3)
    real(wp) :: center(3)
    real(wp) :: half(3)
    half = 0.5_wp
    center = matmul(dlat,half)
Referenced by test_pbc_tools_convert().
latgrad_to_sigma()
pure subroutine xtb_pbc_tools::latgrad_to_sigma (real(wp), dimension(3,3), intent(in) latgrad, real(wp), dimension(3,3), intent(in) lattice, real(wp), dimension(3,3), intent(out) sigma)
Definition at line 382 of file pbc_tools.f90.
    implicit none
    real(wp), intent(in) :: latgrad(3,3)
    real(wp), intent(in) :: lattice(3,3)
    real(wp), intent(out) :: sigma(3,3)
    integer :: i,j,k
    sigma = 0.0_wp
    do i = 1, 3
       do j = 1, 3
          do k = 1,3
             sigma(i,j) = sigma(i,j) + latgrad(i,k)*lattice(j,k)
          enddo
       enddo
    enddo
mat_det_3x3()
pure real(wp) function xtb_pbc_tools::mat_det_3x3 (real(wp), dimension(3,3), intent(in) a)
determinat of 3×3 matrix
Definition at line 140 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in) :: a(3,3)
    real(wp)            :: det
    det =  a(1,1)*a(2,2)*a(3,3)  &
       & - a(1,1)*a(2,3)*a(3,2)  &
       & - a(1,2)*a(2,1)*a(3,3)  &
       & + a(1,2)*a(2,3)*a(3,1)  &
       & + a(1,3)*a(2,1)*a(3,2)  &
       & - a(1,3)*a(2,2)*a(3,1)
Referenced by dlat_to_dvol(), and mat_inv_3x3().
mat_inv_3x3()
pure real(wp) function, dimension(3,3) xtb_pbc_tools::mat_inv_3x3 (real(wp), dimension(3,3), intent(in) a)
Performs a direct calculation of the inverse of a 3×3 matrix.
Parameters
[in] a Matrix
Returns
Inverse matrix
Definition at line 157 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in) :: a(3,3)
    real(wp)            :: b(3,3)
    real(wp)            :: detinv
   ! Calculate the inverse determinant of the matrix
   detinv = 1.0_wp/mat_det_3x3(a)
   ! Calculate the inverse of the matrix
   b(1,1) = +detinv * (a(2,2)*a(3,3) - a(2,3)*a(3,2))
   b(2,1) = -detinv * (a(2,1)*a(3,3) - a(2,3)*a(3,1))
   b(3,1) = +detinv * (a(2,1)*a(3,2) - a(2,2)*a(3,1))
   b(1,2) = -detinv * (a(1,2)*a(3,3) - a(1,3)*a(3,2))
   b(2,2) = +detinv * (a(1,1)*a(3,3) - a(1,3)*a(3,1))
   b(3,2) = -detinv * (a(1,1)*a(3,2) - a(1,2)*a(3,1))
   b(1,3) = +detinv * (a(1,2)*a(2,3) - a(1,3)*a(2,2))
   b(2,3) = -detinv * (a(1,1)*a(2,3) - a(1,3)*a(2,1))
   b(3,3) = +detinv * (a(1,1)*a(2,2) - a(1,2)*a(2,1))
References mat_det_3x3().
Referenced by dlat_to_rlat(), xtb_relaxation_engine::fire(), xtb_relaxation_engine::inertial_relax(), test_peeq_api(), test_peeq_api_srb(), xtb_io_writer_turbomole::writegradlattturbomole(), and xyz_to_abc().
minimum_image_distance()
pure real(wp) function xtb_pbc_tools::minimum_image_distance (logical, intent(in) lsame, real(wp), dimension(3), intent(in) fi, real(wp), dimension(3), intent(in) fj, real(wp), dimension(3,3), intent(in) dlat, logical, dimension(3), intent(in) lpbc)
calculate distance between to atoms under minimum image convention
Definition at line 303 of file pbc_tools.f90.
    implicit none
    logical, intent(in) :: lsame
    real(wp),intent(in) :: fi(3)
    real(wp),intent(in) :: fj(3)
    real(wp),intent(in) :: dlat(3,3)
    logical, intent(in) :: lpbc(3)
    real(wp) :: dist
    real(wp) :: fij(3),tfij(3),rij(3),tmp
    integer  :: rep(3),tx,ty,tz,idir
    logical  :: first
    fij = fi - fj
    if (lsame) then
       do idir = 1, 3
          if (lpbc(idir)) then
             rep(idir) = 1
          else
             rep(idir) = 0
          endif
       enddo
       first = .true.
       dist  = 0.0_wp
       tmp   = 0.0_wp
       do tx = -rep(1),rep(1)
          do ty = -rep(2),rep(2)
             do tz = -rep(3),rep(3)
                if (tx==0 .and. ty==0 .and. tz==0) cycle
                tfij = fij + [tx, ty, tz]
                rij = matmul(dlat,tfij)
                tmp = norm2(rij)
                if (first) then
                   dist = tmp
                   first = .false.
                else
                   dist = min(dist,tmp)
                endif
             enddo
          enddo
       enddo
    else
       do idir = 1, 3
          if (lpbc(idir)) fij(idir) = fij(idir) - idnint(fij(idir))
       enddo
       rij = matmul(dlat,fij)
       dist = norm2(rij)
    endif
References true().
Referenced by xtb_type_molecule::mol_calculate_distances().
outer_prod_3x3()
pure real(wp) function, dimension(3,3) xtb_pbc_tools::outer_prod_3x3 (real(wp), dimension(3), intent(in) a, real(wp), dimension(3), intent(in) b)
Definition at line 374 of file pbc_tools.f90.
    real(wp),intent(in) :: a(3),b(3)
    real(wp) :: c(3,3)
    c(1,1) = a(1)*b(1); c(2,1) = a(2)*b(1); c(3,1) = a(3)*b(1)
    c(1,2) = a(1)*b(2); c(2,2) = a(2)*b(2); c(3,2) = a(3)*b(2)
    c(1,3) = a(1)*b(3); c(2,3) = a(2)*b(3); c(3,3) = a(3)*b(3)
Referenced by xtb_peeq::drep_grad(), xtb_eeq::eeq_ewald_dx_3d_dir(), xtb_disp_ncoord::pbc_derfcoord(), xtb_disp_ncoord::pbc_dncoord_d3(), and xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4().
shift_back_abc()
pure elemental real(wp) function xtb_pbc_tools::shift_back_abc (real(wp), intent(in) in)
shift back fractional coordinates into the range [0,1)
Parameters
[in] in fractional coordinate in (-∞,+∞)
Returns
fractional coordinate in [0,1)
Definition at line 254 of file pbc_tools.f90.
    implicit none
    real(wp),intent(in) :: in
    real(wp)            :: out
    real(wp),parameter  :: p_pbc_eps = 1.0e-14_wp
    out = in
    if(in < (0.0_wp - p_pbc_eps)) &
       out = in + real(ceiling(-in),wp)
    if(in > (1.0_wp + p_pbc_eps)) &
       out = in - real(floor( in),wp)
    if (abs(in - 1.0_wp) < p_pbc_eps) &
       out = in - 1.0_wp
Referenced by xyz_to_abc().
sigma_to_latgrad()
pure subroutine xtb_pbc_tools::sigma_to_latgrad (real(wp), dimension(3,3), intent(in) sigma, real(wp), dimension(3,3), intent(in) inv_lat, real(wp), dimension(3,3), intent(out) latgrad)
Definition at line 401 of file pbc_tools.f90.
    implicit none
    real(wp), intent(in) :: sigma(3,3)
    real(wp), intent(in) :: inv_lat(3,3)
    real(wp), intent(out) :: latgrad(3,3)
    integer :: i,j,k
    latgrad(1,1) = sigma(1,1)*inv_lat(1,1) + sigma(1,2)*inv_lat(1,2) + sigma(1,3)*inv_lat(1,3)
    latgrad(1,2) = sigma(1,1)*inv_lat(2,1) + sigma(1,2)*inv_lat(2,2) + sigma(1,3)*inv_lat(2,3)
    latgrad(1,3) = sigma(1,1)*inv_lat(3,1) + sigma(1,2)*inv_lat(3,2) + sigma(1,3)*inv_lat(3,3)
    latgrad(2,1) = sigma(2,1)*inv_lat(1,1) + sigma(2,2)*inv_lat(1,2) + sigma(2,3)*inv_lat(1,3)
    latgrad(2,2) = sigma(2,1)*inv_lat(2,1) + sigma(2,2)*inv_lat(2,2) + sigma(2,3)*inv_lat(2,3)
    latgrad(2,3) = sigma(2,1)*inv_lat(3,1) + sigma(2,2)*inv_lat(3,2) + sigma(2,3)*inv_lat(3,3)
    latgrad(3,1) = sigma(3,1)*inv_lat(1,1) + sigma(3,2)*inv_lat(1,2) + sigma(3,3)*inv_lat(1,3)
    latgrad(3,2) = sigma(3,1)*inv_lat(2,1) + sigma(3,2)*inv_lat(2,2) + sigma(3,3)*inv_lat(2,3)
    latgrad(3,3) = sigma(3,1)*inv_lat(3,1) + sigma(3,2)*inv_lat(3,2) + sigma(3,3)*inv_lat(3,3)
Referenced by xtb_relaxation_engine::fire(), xtb_relaxation_engine::inertial_relax(), test_peeq_api(), test_peeq_api_srb(), and xtb_io_writer_turbomole::writegradlattturbomole().
xyz_to_abc()
pure subroutine xtb_pbc_tools::xyz_to_abc (integer, intent(in) n, real(wp), dimension(3,3), intent(in) dlat, real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension(3,n), intent(out) abc, logical, dimension(3), intent(in) pbc)
transform from cartesian coordinates into fractional coordinates
Definition at line 229 of file pbc_tools.f90.
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: dlat(3,3)
    real(wp),intent(in)  :: xyz(3,n)
    real(wp),intent(out) :: abc(3,n)
    logical, intent(in)  :: pbc(3)
    real(wp)             :: invlat(3,3)
    real(wp)             :: tmp(3)
    integer              :: iat,idir
    ! note that this is not the reciprocal lattice
    invlat = mat_inv_3x3(dlat)
    do iat = 1, n
       tmp = matmul(invlat,xyz(:,iat))
       do idir = 1, 3
          if (pbc(idir)) &
             tmp(idir) = shift_back_abc(tmp(idir))
       enddo
       abc(:,iat) = tmp
    enddo
References mat_inv_3x3(), and shift_back_abc().
Referenced by xtb_type_molecule::wrap_back().
Variable Documentation
tpi
real(wp), parameter xtb_pbc_tools::tpi = 2.0_wp*pi
Definition at line 30 of file pbc_tools.f90.
    real(wp),parameter :: tpi = 2.0_wp*pi
Referenced by cell_to_rlat(), dlat_to_rlat(), and dvol_to_rvol().