My Project: xtb_io_reader_vasp Module Reference
xtb_io_reader_vasp Module Reference
Functions/Subroutines
subroutine, public readmoleculevasp (mol, unit, status, iomsg)
Variables
logical, parameter debug = .false.
Function/Subroutine Documentation
readmoleculevasp()
subroutine, public xtb_io_reader_vasp::readmoleculevasp (type(tmolecule), intent(out) mol, integer, intent(in) unit, logical, intent(out) status, character(len=:), intent(out), allocatable iomsg)
Definition at line 40 of file vasp.f90.
    type(TMolecule),intent(out) :: mol
    integer,intent(in) :: unit
    logical, intent(out) :: status
    character(len=:), allocatable, intent(out) :: iomsg
    real(wp) :: lattice(3,3)
    integer, allocatable :: ncount(:)
    logical              :: selective=.false. ! Selective dynamics
    logical              :: cartesian=.true.  ! Cartesian or direct
    integer :: natoms
    real(wp) :: ddum,latvec(3)
    real(wp) xx(10),scalar
    real(wp) :: coord(3)
    character(len=:),allocatable :: line
    character(len=2*symbolLength) :: args(256),args2(256)
    real(wp), allocatable :: xyz(:, :)
    character(len=symbolLength), allocatable :: sym(:)
    integer i,j,k,nn,ntype,ntype2,atnum,i_dummy1,i_dummy2,ncheck
    integer :: iat, idum, err
    status = .false.
    lattice=0
    ncheck=0
    ntype=0
    ! first line contains the symbols of different atom types
    call getline(unit,line,err)
    if (err.ne.0) then
       iomsg = "Could not read POSCAR"
       return
    endif
    if (debug) print'(">",a)',line
    call parse(line,' ',args,ntype)
    ! this line contains the global scaling factor,
    call getline(unit,line,err)
    if (err.ne.0) then
       iomsg = "Could not read POSCAR"
       return
    endif
    if (debug) print'(">",a)',line
    read(line,*,iostat=err) ddum
    if (err.ne.0) then
       iomsg = "Could not read POSCAR"
       return
    endif
    ! the Ang->au conversion is included in the scaling factor
    if (debug) print'("->",g0)',ddum
    scalar = ddum*aatoau
    ! reading the lattice constants
    do i=1,3
       call getline(unit,line,err)
       if (err.ne.0) then
          iomsg = "Could not read lattice from POSCAR"
          return
       endif
       if (debug) print'("->",a)',line
       read(line,*,iostat=err) latvec
       if (err.ne.0) then
          iomsg = "Could not read lattice from POSCAR"
          return
       endif
       lattice(:,i) = latvec * scalar
    enddo
    ! Either here are the numbers of each element,
    ! or (>vasp.5.1) here are the element symbols
    call getline(unit,line,err)
    if (err.ne.0) then
       iomsg = "Could not read POSCAR"
       return
    endif
    if (debug) print'(">",a)',line
    ! try to read first element
    read(line,*,iostat=err) idum
    ! CONTCAR files have additional Element line here since vasp.5.1
    if (err.ne.0) then
       call parse(line,' ',args,ntype)
       call getline(unit,line,err)
       if (debug) print'("->",a)',line
       if (err.ne.0) then
          iomsg = "Could not read POSCAR"
          return
       endif
    endif
    call parse(line,' ',args2,nn)
    if (nn.ne.ntype) then
       iomsg = 'Error reading number of atomtypes'
       return
    endif
    allocate(ncount(nn), source = 0)
    ncheck = 0
    do i = 1, nn
       read(args2(i), *, iostat=err) ncount(i)
       iat = tonumber(args(i))
       if (iat < 1 .or. ncount(i) < 1) then
          iomsg = 'unknown element.'
          return
       endif
    enddo
    natoms = sum(ncount)
    allocate(sym(natoms))
    allocate(xyz(3, natoms))
    k = 0
    do i = 1, nn
       do j = 1, ncount(i)
          k = k+1
          sym(k) = trim(args(i))
       enddo
    enddo
    call getline(unit, line, err)
    if (err.ne.0) then
       iomsg = "Could not read POSCAR"
       return
    endif
    if (debug) print'(">",a)', line
    line=adjustl(line)
    if (line(:1).eq.'s' .or. line(:1).eq.'S') then
       selective = .true.
       call getline(unit,line,err)
       if (debug) print'("->",a)', line
       if (err.ne.0) then
          iomsg = "Could not read POSCAR"
          return
       endif
       line = adjustl(line)
    endif
    cartesian=(line(:1).eq.'c' .or. line(:1).eq.'C' .or. &
       &       line(:1).eq.'k' .or. line(:1).eq.'K')
    do i = 1, natoms
       call getline(unit, line, err)
       if (err.ne.0) then
          iomsg = "Could not read geometry from POSCAR"
          return
       endif
       if (debug) print'("-->",a)',line
       read(line, *, iostat=err) coord
       if (err.ne.0) then
          iomsg = "Could not read geometry from POSCAR"
          return
       endif
       if (cartesian) then
          xyz(:,i) = coord*scalar
       else
          xyz(:,i) = matmul(lattice, coord)
       endif
    enddo
    call init(mol, sym, xyz, lattice=lattice)
    ! save information about this POSCAR for later
    mol%vasp = vasp_info(scale=ddum, selective=selective, cartesian=cartesian)
    status = .true.
References xtb_mctc_convert::aatoau, debug, xtb_mctc_systools::getline(), xtb_mctc_strings::parse(), xtb_mctc_symbols::tonumber(), and true().
Referenced by xtb_io_reader::readmolecule().
Variable Documentation
debug
logical, parameter xtb_io_reader_vasp::debug = .false. private
Definition at line 34 of file vasp.f90.
    logical, parameter :: debug = .false.
Referenced by readmoleculevasp().