My Project: xtb_mdoptim Module Reference
xtb_mdoptim Module Reference
Functions/Subroutines
subroutine, public mdopt (env, mol, chk, calc, egap, et, maxiter, epot, grd, sigma)
Function/Subroutine Documentation
mdopt()
subroutine, public xtb_mdoptim::mdopt (type(tenvironment), intent(inout) env, type(tmolecule), intent(inout) mol, type(trestart), intent(inout) chk, class(tcalculator), intent(inout) calc, real(wp) egap, real(wp) et, integer maxiter, real(wp) epot, real(wp), dimension(3,mol%n), intent(inout) grd, real(wp), dimension(3,3), intent(inout) sigma)
Parameters
[in,out] env Calculation environment
Definition at line 40 of file mdoptim.f90.
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(inout) :: mol
    type(TRestart),intent(inout) :: chk
    class(TCalculator), intent(inout) :: calc
    integer  :: icall,maxiter
    real(wp) :: epot,et,egap
    real(wp), intent(inout) :: grd(3,mol%n)
    real(wp), intent(inout) :: sigma(3,3)
    type(scc_results) :: res
    real(wp),allocatable :: xyznew(:,:,:), eread(:)
    real(wp) :: e,angtoau
    parameter(angtoau=1.0d0/0.529177260d0)
    integer i,j,iz1,iz2,nall,ol
    character(80) atmp
    logical ex, fail
    integer ich
    write(*,*)
    write(*,'(7x,''======================================='')')
    write(*,'(7x,''|              M D O P T              |'')')
    write(*,'(7x,''|    optimizations along trajectory   |'')')
    write(*,'(7x,''======================================='')')
    write(*,*)
    write(*,*)'skipping interval            :',skip_md
    write(*,*)'opt level                    :',optset%optlev
    atmp='xtb.trj'
    call cqpath_read_pathfile_parameter(atmp,iz1,iz2,nall)
    if(iz2.ne.mol%n) call env%terminate('read error in mdopt')
    allocate(xyznew(3,mol%n,nall),eread(nall))
    call cqpath_read_pathfile(atmp,iz1,iz2,nall,xyznew,mol%at,eread)
    write(*,*)'total number of points on trj:',nall
    write(*,*)'total number of optimizations:',nall/skip_md
    call open_file(ich,'xtb_ensemble.xyz','w')
    j   =0
    do i=1,nall
       j = j +1
       if(mod(j,skip_md).eq.0)then
          mol%xyz=xyznew(:,:,i)*angtoau
          call geometry_optimization &
             &      (env, mol,chk,calc, &
             &       egap,etemp,maxscciter,optset%maxoptcycle,epot,grd,sigma, &
             &       optset%optlev,.false.,.true.,fail)
          if(.not.fail)then
             call writemolecule(mol, ich, filetype%xyz, energy=epot)
          endif
       endif
    enddo
    call close_file(ich)
References chk(), close_file(), xtb_cqpath::cqpath_read_pathfile(), xtb_cqpath::cqpath_read_pathfile_parameter(), xtb_setparam::etemp, xtb_mctc_filetypes::filetype, xtb_geoopt::geometry_optimization(), xtb_setparam::maxscciter, open_file(), xtb_setparam::optset, xtb_setparam::skip_md, true(), and xtb_io_writer::writemolecule().
Referenced by xtb_prog_main::xtbmain().