My Project: xtb_type_atomlist Module Reference
xtb_type_atomlist Module Reference
implemenation of a list of atoms
Data Types
interface tatomlist
interface len
interface size
interface assignment(=)
Functions/Subroutines
pure type(tatomlist) function atomlist_from_logicals (list, truth, delimiter, skip)
pure type(tatomlist) function atomlist_from_integers (list, truth, delimiter, skip)
pure type(tatomlist) function atomlist_from_string (list, truth, delimiter, skip)
subroutine from_defaults (self)
pure elemental subroutine atomlist_switch_truth (self)
pure elemental subroutine atomlist_set_truth (self, truth)
pure elemental logical function atomlist_get_truth (self)
pure elemental logical function atomlist_get_error (self)
subroutine atomlist_write_formatted (self, unit, iotype, v_list, iostat, iomsg)
subroutine atomlist_read_formatted (self, unit, iotype, v_list, iostat, iomsg)
integer pure elemental function atomlist_size (self)
integer pure elemental function atomlist_length (self)
pure subroutine atomlist_add_integer (self, item)
pure subroutine atomlist_add_integers (self, list)
pure subroutine atomlist_add_logicals (self, list)
pure subroutine atomlist_remove_integer (self, item)
pure subroutine atomlist_remove_integers (self, list)
pure subroutine atomlist_remove_logicals (self, list)
pure subroutine list_assign_atomlist (list, self)
pure subroutine string_assign_atomlist (string, self)
pure subroutine atomlist_assign_logicals (self, list)
pure subroutine atomlist_assign_integers (self, list)
pure subroutine atomlist_assign_string (self, string)
pure subroutine atomlist_parse_string (self, string)
pure subroutine atomlist_resize (self, n)
subroutine atomlist_gather_int (self, array, selected)
subroutine atomlist_gather_real (self, array, selected)
subroutine atomlist_gather_real_2d (self, array, selected, dim)
subroutine atomlist_scatter_real_2d (self, reduced, array, dim, scale)
pure elemental subroutine atomlist_destroy (self)
pure elemental subroutine atomlist_finalizer (self)
Variables
character, parameter p_delimiter = ','
character, parameter p_skip = '-'
Detailed Description
implemenation of a list of atoms
Function/Subroutine Documentation
atomlist_add_integer()
pure subroutine xtb_type_atomlist::atomlist_add_integer (class(tatomlist), intent(inout) self, integer, intent(in) item) private
Definition at line 227 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    integer, intent(in) :: item
    integer :: i
    call self%resize(item)
    self%list(item) = .not.self%default
atomlist_add_integers()
pure subroutine xtb_type_atomlist::atomlist_add_integers (class(tatomlist), intent(inout) self, integer, dimension(:), intent(in) list) private
Definition at line 235 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    integer, intent(in) :: list(:)
    integer :: i
    call self%resize(maxval(list))
    do i = 1, size(list)
       self%list(list(i)) = .not.self%default
    enddo
References list().
atomlist_add_logicals()
pure subroutine xtb_type_atomlist::atomlist_add_logicals (class(tatomlist), intent(inout) self, logical, dimension(:), intent(in) list) private
Definition at line 245 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    logical, intent(in) :: list(:)
    integer :: i
    call self%resize(size(list))
    self%list(:size(list)) = list .or. self%list(:size(list))
References list().
atomlist_assign_integers()
pure subroutine xtb_type_atomlist::atomlist_assign_integers (class(tatomlist), intent(inout) self, integer, dimension(:), intent(in) list) private
Definition at line 335 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    integer, intent(in) :: list(:)
    integer :: i
    call self%resize(maxval(list))
    do i = 1, size(list)
       self%list(list(i)) = .not.self%default
    enddo
atomlist_assign_logicals()
pure subroutine xtb_type_atomlist::atomlist_assign_logicals (class(tatomlist), intent(inout) self, logical, dimension(:), intent(in) list) private
Definition at line 328 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    logical, intent(in) :: list(:)
    call self%resize(size(list))
    self%list = list
atomlist_assign_string()
pure subroutine xtb_type_atomlist::atomlist_assign_string (class(tatomlist), intent(inout) self, character(len=*), intent(in) string) private
Definition at line 345 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    character(len=*), intent(in) :: string
    character(len=:), allocatable :: buffer
    integer, allocatable :: list(:)
    integer :: pos, last, n
    last = 0
    do
       pos = index(string(last+1:), self%delimiter)
       if (pos > 0) then
          call self%parse(string(last+1:last+pos-1))
          if (self%error) exit
          last = last+pos
       else
          call self%parse(string(last+1:))
          exit
       endif
    enddo
atomlist_destroy()
pure elemental subroutine xtb_type_atomlist::atomlist_destroy (class(tatomlist), intent(inout) self) private
Definition at line 512 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    if (allocated(self%list)) deallocate(self%list)
atomlist_finalizer()
pure elemental subroutine xtb_type_atomlist::atomlist_finalizer (type(tatomlist), intent(inout) self) private
Definition at line 517 of file atomlist.f90.
    type(TAtomList), intent(inout) :: self
    call self%destroy
Referenced by xtb_type_atomlist::tatomlist::atomlist_finalizer().
atomlist_from_integers()
pure type(tatomlist) function xtb_type_atomlist::atomlist_from_integers (integer, dimension(:), intent(in) list, logical, intent(in), optional truth, character, intent(in), optional delimiter, character, intent(in), optional skip) private
Definition at line 104 of file atomlist.f90.
    integer, intent(in) :: list(:)
    logical, intent(in), optional :: truth
    character, intent(in), optional :: delimiter, skip
    type(TAtomList) :: self
    if (present(truth)) self%default = .not.truth
    if (present(delimiter)) self%delimiter = delimiter
    if (present(skip)) self%skip = skip
    call self%new(list)
Referenced by xtb_type_atomlist::tatomlist::atomlist_finalizer().
atomlist_from_logicals()
pure type(tatomlist) function xtb_type_atomlist::atomlist_from_logicals (logical, dimension(:), intent(in) list, logical, intent(in), optional truth, character, intent(in), optional delimiter, character, intent(in), optional skip) private
Definition at line 93 of file atomlist.f90.
    logical, intent(in) :: list(:)
    logical, intent(in), optional :: truth
    character, intent(in), optional :: delimiter, skip
    type(TAtomList) :: self
    if (present(truth)) self%default = .not.truth
    if (present(delimiter)) self%delimiter = delimiter
    if (present(skip)) self%skip = skip
    call self%new(list)
Referenced by xtb_type_atomlist::tatomlist::atomlist_finalizer().
atomlist_from_string()
pure type(tatomlist) function xtb_type_atomlist::atomlist_from_string (character(len=*), intent(in) list, logical, intent(in), optional truth, character, intent(in), optional delimiter, character, intent(in), optional skip) private
Definition at line 115 of file atomlist.f90.
    character(len=*), intent(in) :: list
    logical, intent(in), optional :: truth
    character, intent(in), optional :: delimiter, skip
    type(TAtomList) :: self
    if (present(truth)) self%default = .not.truth
    if (present(delimiter)) self%delimiter = delimiter
    if (present(skip)) self%skip = skip
    call self%new(list)
Referenced by xtb_type_atomlist::tatomlist::atomlist_finalizer().
atomlist_gather_int()
subroutine xtb_type_atomlist::atomlist_gather_int (class(tatomlist), intent(in) self, integer, dimension(:), intent(in) array, integer, dimension(:), intent(out), allocatable selected) private
Definition at line 429 of file atomlist.f90.
    class(TAtomList), intent(in) :: self
    integer, intent(in) :: array(:)
    integer, allocatable, intent(out) :: selected(:)
    selected = pack(array, mask=self%list.neqv.self%default)
atomlist_gather_real()
subroutine xtb_type_atomlist::atomlist_gather_real (class(tatomlist), intent(in) self, real(wp), dimension(:), intent(in) array, real(wp), dimension(:), intent(out), allocatable selected) private
Definition at line 436 of file atomlist.f90.
    class(TAtomList), intent(in) :: self
    real(wp), intent(in) :: array(:)
    real(wp), allocatable, intent(out) :: selected(:)
    selected = pack(array, mask=self%list.neqv.self%default)
atomlist_gather_real_2d()
subroutine xtb_type_atomlist::atomlist_gather_real_2d (class(tatomlist), intent(in) self, real(wp), dimension(:,:), intent(in) array, real(wp), dimension(:,:), intent(out), allocatable selected, integer, intent(in), optional dim) private
Definition at line 443 of file atomlist.f90.
    class(TAtomList), intent(in) :: self
    real(wp), intent(in) :: array(:,:)
    integer, intent(in), optional :: dim
    real(wp), allocatable, intent(out) :: selected(:,:)
    integer :: selected_dim, i, j
    if (present(dim)) then
       selected_dim = dim
    else
       selected_dim = 2
    endif
    if (selected_dim == 1) then
       allocate(selected(len(self), size(array, 2)), source=0.0_wp)
       j = 0
       do i = 1, min(size(array, 1), size(self))
          if (self%list(i).neqv.self%default) then
             j = j+1
             selected(j,:) = array(i,:)
          endif
       enddo
    else
       allocate(selected(size(array, 1), len(self)), source=0.0_wp)
       j = 0
       do i = 1, min(size(array, 2), size(self))
          if (self%list(i).neqv.self%default) then
             j = j+1
             selected(:,j) = array(:,i)
          endif
       enddo
    endif
atomlist_get_error()
pure elemental logical function xtb_type_atomlist::atomlist_get_error (class(tatomlist), intent(in) self) private
Definition at line 147 of file atomlist.f90.
    class(TAtomList), intent(in) :: self
    logical :: error
    error = self%error
atomlist_get_truth()
pure elemental logical function xtb_type_atomlist::atomlist_get_truth (class(tatomlist), intent(in) self) private
Definition at line 141 of file atomlist.f90.
    class(TAtomList), intent(in) :: self
    logical :: truth
    truth = .not.self%default
atomlist_length()
integer pure elemental function xtb_type_atomlist::atomlist_length (class(tatomlist), intent(in) self) private
Definition at line 218 of file atomlist.f90.
    class(TAtomList), intent(in) :: self
    if (allocated(self%list)) then
       atomlist_length = count(self%list.neqv.self%default)
    else
       atomlist_length = 0
    endif
Referenced by xtb_type_atomlist::len::atomlist_length().
atomlist_parse_string()
pure subroutine xtb_type_atomlist::atomlist_parse_string (class(tatomlist), intent(inout) self, character(len=*), intent(in) string) private
Definition at line 367 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    character(len=*),intent(in) :: string
    integer :: pos, item, begin, last, err
    pos = index(string,self%skip)
    if (pos.eq.0) then
       read(string,*,iostat=err) item
       if (err.ne.0) then
          self%error = .false.
          return
       endif
       call self%add(item)
    else
       read(string(:pos-1),*,iostat=err) begin
       if (err.ne.0) then
          self%error = .false.
          return
       endif
       read(string(pos+1:),*,iostat=err) last
       if (err.ne.0) then
          self%error = .false.
          return
       endif
       if (last.lt.begin) then
          self%error = .false.
          return
       endif
       do item = begin, last
          call self%add(item)
       enddo
    endif
atomlist_read_formatted()
subroutine xtb_type_atomlist::atomlist_read_formatted (class(tatomlist), intent(inout) self, integer, intent(in) unit, character(len=*), intent(in) iotype, integer, dimension(:), intent(in) v_list, integer, intent(out) iostat, character(len=*), intent(inout) iomsg) private
Definition at line 165 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    integer, intent(in) :: unit
    character(len=*), intent(in) :: iotype
    integer, intent(in) :: v_list(:)
    integer, intent(out) :: iostat
    character(len=*), intent(inout) :: iomsg
    character(len=:), allocatable :: string
    call get_line(unit, string, iostat)
    call self%new(string)
 contains
 subroutine get_line(unit, line, iostat)
    use, intrinsic :: iso_fortran_env, only : iostat_eor
    integer, intent(in) :: unit
    character(len=:), allocatable, intent(out) :: line
    integer, intent(out), optional :: iostat
    integer, parameter :: buffersize = 256
    character(len=buffersize) :: buffer
    integer :: size
    integer :: err
    line = ''
    do
       read(unit,'(a)',advance='no',iostat=err,size=size)  &
       &    buffer
       if (err.gt.0) then
          if (present(iostat)) iostat=err
          return ! an error occurred
       endif
       line = line // buffer(:size)
       if (err.lt.0) then
          if (err.eq.iostat_eor) err = 0
          if (present(iostat)) iostat=err
          return
       endif
    enddo
 end subroutine get_line
References get_line().
atomlist_remove_integer()
pure subroutine xtb_type_atomlist::atomlist_remove_integer (class(tatomlist), intent(inout) self, integer, intent(in) item) private
Definition at line 253 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    integer, intent(in) :: item
    integer :: i
    call self%resize(item)
    self%list(item) = self%default
atomlist_remove_integers()
pure subroutine xtb_type_atomlist::atomlist_remove_integers (class(tatomlist), intent(inout) self, integer, dimension(:), intent(in) list) private
Definition at line 261 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    integer, intent(in) :: list(:)
    integer :: i
    call self%resize(maxval(list))
    do i = 1, size(list)
       self%list(list(i)) = self%default
    enddo
References list().
atomlist_remove_logicals()
pure subroutine xtb_type_atomlist::atomlist_remove_logicals (class(tatomlist), intent(inout) self, logical, dimension(:), intent(in) list) private
Definition at line 271 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    logical, intent(in) :: list(:)
    integer :: i
    call self%resize(size(list))
    self%list(:size(list)) = list .and. self%list(:size(list))
References list().
atomlist_resize()
pure subroutine xtb_type_atomlist::atomlist_resize (class(tatomlist), intent(inout) self, integer, intent(in), optional n) private
Definition at line 402 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    integer, intent(in), optional :: n
    logical, allocatable :: list(:)
    integer :: length, current_length
    current_length = size(self)
    if (current_length > 0) then
       if (present(n)) then
          if (n <= current_length) return
          length = n
       else
          length = current_length + current_length/2 + 1
       endif
       allocate(list(length), source=self%default)
       list(:current_length) = self%list(:current_length)
       deallocate(self%list)
       call move_alloc(list, self%list)
    else
       if (present(n)) then
          length = n
       else
          length = 64
       endif
       allocate(self%list(length), source=self%default)
    endif
References list().
atomlist_scatter_real_2d()
subroutine xtb_type_atomlist::atomlist_scatter_real_2d (class(tatomlist), intent(in) self, real(wp), dimension(:,:), intent(in) reduced, real(wp), dimension(:,:), intent(inout) array, integer, intent(in), optional dim, real(wp), intent(in), optional scale) private
Definition at line 475 of file atomlist.f90.
    class(TAtomList), intent(in) :: self
    real(wp), intent(inout) :: array(:,:)
    integer, intent(in), optional :: dim
    real(wp), intent(in), optional :: scale
    real(wp), intent(in) :: reduced(:,:)
    integer :: selected_dim, i, j
    real(wp) :: alpha
    if (present(dim)) then
       selected_dim = dim
    else
       selected_dim = 2
    endif
    if (present(scale)) then
       alpha = scale
    else
       alpha = 0.0_wp
    endif
    if (selected_dim == 1) then
       j = 0
       do i = 1, min(size(array, 1), size(self))
          if (self%list(i).neqv.self%default) then
             j = j+1
             array(i,:) = reduced(j,:) + alpha * array(i,:)
          endif
       enddo
    else
       j = 0
       do i = 1, min(size(array, 2), size(self))
          if (self%list(i).neqv.self%default) then
             j = j+1
             array(:,i) = reduced(:,j) + alpha * array(:,i)
          endif
       enddo
    endif
atomlist_set_truth()
pure elemental subroutine xtb_type_atomlist::atomlist_set_truth (class(tatomlist), intent(inout) self, logical, intent(in) truth) private
Definition at line 135 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    logical, intent(in) :: truth
    self%default = .not.truth
atomlist_size()
integer pure elemental function xtb_type_atomlist::atomlist_size (class(tatomlist), intent(in) self) private
Definition at line 209 of file atomlist.f90.
    class(TAtomList), intent(in) :: self
    if (allocated(self%list)) then
       atomlist_size = size(self%list)
    else
       atomlist_size = 0
    endif
Referenced by xtb_type_atomlist::size::atomlist_size().
atomlist_switch_truth()
pure elemental subroutine xtb_type_atomlist::atomlist_switch_truth (class(tatomlist), intent(inout) self) private
Definition at line 130 of file atomlist.f90.
    class(TAtomList), intent(inout) :: self
    self%default = .not.self%default
atomlist_write_formatted()
subroutine xtb_type_atomlist::atomlist_write_formatted (class(tatomlist), intent(in) self, integer, intent(in) unit, character(len=*), intent(in) iotype, integer, dimension(:), intent(in) v_list, integer, intent(out) iostat, character(len=*), intent(inout) iomsg) private
Definition at line 153 of file atomlist.f90.
    class(TAtomList), intent(in) :: self
    integer, intent(in) :: unit
    character(len=*), intent(in) :: iotype
    integer, intent(in) :: v_list(:)
    integer, intent(out) :: iostat
    character(len=*), intent(inout) :: iomsg
    character(len=:), allocatable :: buffer
    call self%to_string(buffer)
    write(unit, '(a)', iostat=iostat, iomsg=iomsg) buffer
from_defaults()
subroutine xtb_type_atomlist::from_defaults (class(tatomlist), intent(out) self) private
Definition at line 126 of file atomlist.f90.
    class(TAtomList), intent(out) :: self
Referenced by xtb_type_atomlist::tatomlist::new().
list_assign_atomlist()
pure subroutine xtb_type_atomlist::list_assign_atomlist (integer, dimension(:), intent(out), allocatable list, class(tatomlist), intent(in) self) private
Definition at line 279 of file atomlist.f90.
    integer, allocatable, intent(out) :: list(:)
    class(TAtomList), intent(in) :: self
    integer :: i, j
    allocate(list(len(self)), source=0)
    j = 0
    do i = 1, size(self)
       if (self%list(i).neqv.self%default) then
          j = j+1
          list(j) = i
       endif
    enddo
string_assign_atomlist()
pure subroutine xtb_type_atomlist::string_assign_atomlist (character(len=:), intent(out), allocatable string, class(tatomlist), intent(in) self) private
Definition at line 293 of file atomlist.f90.
    character(len=:), allocatable, intent(out) :: string
    class(TAtomList), intent(in) :: self
    character(len=10) :: buffer
    integer :: i, last
    logical :: state, first
    last = -1
    first = .true.
    state = .not.self%default
    do i = 1, size(self)
       if (state.eqv.self%list(i)) then
          state = .not.state
          if (state.eqv.self%default) then
             last = i
             write(buffer,'(i0)') i
             if (first) then
                first = .false.
                string = trim(buffer)
             else
                string = string // self%delimiter // trim(buffer)
             endif
          else
             if (i-1 .ne. last) then
                write(buffer,'(i0)') i-1
                string = string // self%skip // trim(buffer)
             endif
          endif
       endif
    enddo
    if (state.eqv.self%default .and.last.ne.size(self)) then
       write(buffer,'(i0)') size(self)
       string = string // self%skip // trim(buffer)
    endif
Variable Documentation
p_delimiter
character, parameter xtb_type_atomlist::p_delimiter = ',' private
Definition at line 26 of file atomlist.f90.
    character, parameter :: p_delimiter = ','
p_skip
character, parameter xtb_type_atomlist::p_skip = '-' private
Definition at line 27 of file atomlist.f90.
    character, parameter :: p_skip = '-'