My Project: xtb_pbc Module Reference
xtb_pbc Module Reference
Functions/Subroutines
pure subroutine get_realspace_cutoff (lat, rthr, tau_max)
real(wp) function volume (lat)
subroutine xyz_to_abc (xyz, abc, lat, n)
pure subroutine inv_cell (x, a)
subroutine abc_to_xyz (abc, xyz, lat, n)
pure subroutine get_translation (t1, t2, t3, xyz, abc, out)
pure real *8 function mdet3 (a)
pure real *8 function, dimension(3, 3) minv3 (a)
pure logical function sametest (v)
Function/Subroutine Documentation
abc_to_xyz()
subroutine xtb_pbc::abc_to_xyz (real(wp), dimension(3,n), intent(in) abc, real(wp), dimension(3,n), intent(out) xyz, real(wp), dimension(3,3), intent(in) lat, integer, intent(in) n)
Definition at line 141 of file pbc.f90.
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: abc(3,n)
    real(wp),intent(in)  :: lat(3,3)
    real(wp),intent(out) :: xyz(3,n)
    integer i,j,k
    xyz(:,:n)=0.0_wp
    do i=1,n
       do j=1,3
          do k=1,3
             xyz(j,i)=xyz(j,i)+lat(j,k)*abc(k,i)
          enddo !k
       enddo !j
    enddo !i
get_realspace_cutoff()
pure subroutine xtb_pbc::get_realspace_cutoff (real(wp), dimension(3,3), intent(in) lat, real(wp), intent(in) rthr, integer, dimension(3), intent(out) tau_max)
Definition at line 31 of file pbc.f90.
    implicit none
    real(wp),intent(in)  :: rthr
    real(wp),intent(in)  :: lat(3,3)
    integer, intent(out) :: tau_max(3)
    real(wp) :: r_cutoff
    real(wp) :: normx(3),normy(3),normz(3)
    real(wp) :: cos10,cos21,cos32
    r_cutoff=sqrt(rthr)
 !  write(*,*) 'lat',lat
    ! find normal to the plane...
    call crossproduct(lat(:,2),lat(:,3),normx)
    call crossproduct(lat(:,3),lat(:,1),normy)
    call crossproduct(lat(:,1),lat(:,2),normz)
 !  write(*,*) 'normy',normy
    ! ...normalize it...
    normx=normx/norm2(normx)
    normy=normy/norm2(normy)
    normz=normz/norm2(normz)
 !  write(*,*) 'normy_',normy
    ! cos angles between normals and lattice vectors
    cos10=sum(normx*lat(:,1))
    cos21=sum(normy*lat(:,2))
    cos32=sum(normz*lat(:,3))
 !  write(*,*) 'cos32',cos32
 !  tau_max(1)=abs(2*r_cutoff/cos10)
 !  tau_max(2)=abs(2*r_cutoff/cos21)
 !  tau_max(3)=abs(2*r_cutoff/cos32)
    tau_max(1)=ceiling(abs(r_cutoff/cos10))
    tau_max(2)=ceiling(abs(r_cutoff/cos21))
    tau_max(3)=ceiling(abs(r_cutoff/cos32))
 contains
 pure subroutine crossproduct(a,b,c)
    implicit none
    real(wp),intent(in)  :: a(3),b(3)
    real(wp),intent(out) :: c(3)
    real(wp) :: x,y,z
    x=a(2)*b(3)-b(2)*a(3)
    y=a(3)*b(1)-b(3)*a(1)
    z=a(1)*b(2)-b(1)*a(2)
    c=(/x,y,z/)
 end subroutine crossproduct
References crossproduct().
Referenced by xtb_peeq::drep_grad(), xtb_disp_ncoord::pbc_derfcoord(), xtb_disp_ncoord::pbc_dncoord_d3(), xtb_disp_ncoord::get_d4_cn::pbc_dncoord_d4(), xtb_disp_ncoord::pbc_erfcoord(), xtb_disp_ncoord::get_d4_cn::pbc_ncoord_d4(), and test_pbc_tools_cutoff().
get_translation()
pure subroutine xtb_pbc::get_translation (integer, intent(in) t1, integer, intent(in) t2, integer, intent(in) t3, real(wp), dimension(3), intent(in) xyz, real(wp), dimension(3,3), intent(in) abc, real(wp), dimension(3), intent(inout) out)
Definition at line 161 of file pbc.f90.
   implicit none
   integer,  intent(in)  :: t1,t2,t3
   real(wp), intent(in)  :: xyz(3)
   real(wp), intent(in)  :: abc(3,3)
   real(wp), intent(inout) :: out(3)
   out=0.0_wp
   out(1)=(xyz(1)+t1*abc(1,1)+t2*abc(1,2)+t3*abc(1,3))
   out(2)=(xyz(2)+t2*abc(2,1)+t2*abc(2,2)+t3*abc(2,3))
   out(3)=(xyz(3)+t3*abc(3,1)+t2*abc(3,2)+t3*abc(3,3))
inv_cell()
pure subroutine xtb_pbc::inv_cell (real(wp), dimension(3,3), intent(in) x, real(wp), dimension(3,3), intent(out) a)
Definition at line 116 of file pbc.f90.
    implicit none
    real(wp),intent(in)  :: x(3,3) !unitcell vectors in direct space
    real(wp),intent(out) :: a(3,3) !unitcell vectors in reciprocal space
    real(wp) :: det
    a=0.0_wp
    det=x(1,1)*x(2,2)*x(3,3)+x(1,2)*x(2,3)*x(3,1)+x(1,3)*x(2,1)* &
    &   x(3,2)-x(1,3)*x(2,2)*x(3,1)-x(1,2)*x(2,1)*x(3,3)-x(1,1)* &
    &   x(2,3)*x(3,2)
 !  write(*,*)'Det:',det
    a(1,1)=x(2,2)*x(3,3)-x(2,3)*x(3,2)
    a(2,1)=x(2,3)*x(3,1)-x(2,1)*x(3,3)
    a(3,1)=x(2,1)*x(3,2)-x(2,2)*x(3,1)
    a(1,2)=x(1,3)*x(3,2)-x(1,2)*x(3,3)
    a(2,2)=x(1,1)*x(3,3)-x(1,3)*x(3,1)
    a(3,2)=x(1,2)*x(3,1)-x(1,1)*x(3,2)
    a(1,3)=x(1,2)*x(2,3)-x(1,3)*x(2,2)
    a(2,3)=x(1,3)*x(2,1)-x(1,1)*x(2,3)
    a(3,3)=x(1,1)*x(2,2)-x(1,2)*x(2,1)
    a=a/det
Referenced by xyz_to_abc().
mdet3()
pure real*8 function xtb_pbc::mdet3 (real*8, dimension(3,3), intent(in) a)
Definition at line 173 of file pbc.f90.
   !! determinant of 3x3 matrix
   implicit none
   real*8, intent(in)  :: a(3,3)
   real*8 :: det
   det =   a(1,1)*a(2,2)*a(3,3)  &
        - a(1,1)*a(2,3)*a(3,2)  &
        - a(1,2)*a(2,1)*a(3,3)  &
        + a(1,2)*a(2,3)*a(3,1)  &
        + a(1,3)*a(2,1)*a(3,2)  &
        - a(1,3)*a(2,2)*a(3,1)
minv3()
pure real*8 function, dimension(3,3) xtb_pbc::minv3 (real*8, dimension(3,3), intent(in) a)
Definition at line 187 of file pbc.f90.
   !! http://fortranwiki.org/fortran/show/Matrix+inversion
   !! Performs a direct calculation of the inverse of a 3×3 matrix.
   real*8, intent(in) :: a(3,3)   !! Matrix
   real*8             :: b(3,3)   !! Inverse matrix
   real*8             :: detinv
   ! Calculate the inverse determinant of the matrix
   detinv = 1/(a(1,1)*a(2,2)*a(3,3) - a(1,1)*a(2,3)*a(3,2)&
        - a(1,2)*a(2,1)*a(3,3) + a(1,2)*a(2,3)*a(3,1)&
        + a(1,3)*a(2,1)*a(3,2) - a(1,3)*a(2,2)*a(3,1))
   ! Calculate the inverse of the matrix
   b(1,1) = +detinv * (a(2,2)*a(3,3) - a(2,3)*a(3,2))
   b(2,1) = -detinv * (a(2,1)*a(3,3) - a(2,3)*a(3,1))
   b(3,1) = +detinv * (a(2,1)*a(3,2) - a(2,2)*a(3,1))
   b(1,2) = -detinv * (a(1,2)*a(3,3) - a(1,3)*a(3,2))
   b(2,2) = +detinv * (a(1,1)*a(3,3) - a(1,3)*a(3,1))
   b(3,2) = -detinv * (a(1,1)*a(3,2) - a(1,2)*a(3,1))
   b(1,3) = +detinv * (a(1,2)*a(2,3) - a(1,3)*a(2,2))
   b(2,3) = -detinv * (a(1,1)*a(2,3) - a(1,3)*a(2,1))
   b(3,3) = +detinv * (a(1,1)*a(2,2) - a(1,2)*a(2,1))
sametest()
pure logical function xtb_pbc::sametest (real*8, dimension(3), intent(in) v)
Definition at line 211 of file pbc.f90.
   implicit none
   real*8, intent(in) ::v(3)
   real*8 ::l
   real*8, parameter :: s=1.0e-9
   sametest=.false.
   l=sqrt(dot_product(v,v))
   if (l<=s) sametest=.true.
References true().
volume()
real(wp) function xtb_pbc::volume (real(wp), dimension(3,3), intent(in) lat)
Definition at line 81 of file pbc.f90.
    implicit none
    real(wp),intent(in) ::lat(3,3)
    real(wp) :: det
    det=lat(1,1)*lat(2,2)*lat(3,3)+lat(1,2)*lat(2,3)*lat(3,1) + &
    &   lat(1,3)*lat(2,1)*lat(3,2)-lat(1,3)*lat(2,2)*lat(3,1) - &
    &   lat(1,2)*lat(2,1)*lat(3,3)-lat(1,1)*lat(2,3)*lat(3,2)
    volume=abs(det)
xyz_to_abc()
subroutine xtb_pbc::xyz_to_abc (real(wp), dimension(3,n), intent(in) xyz, real(wp), dimension(3,n), intent(out) abc, real(wp), dimension(3,3), intent(in) lat, integer, intent(in) n)
Definition at line 92 of file pbc.f90.
    implicit none
    integer, intent(in)  :: n
    real(wp),intent(in)  :: xyz(3,n)
    real(wp),intent(in)  :: lat(3,3)
    real(wp),intent(out) :: abc(3,n)
    real(wp) :: lat_1(3,3)
    integer  :: i,j,k
    call inv_cell(lat,lat_1)
    abc(:,:n)=0.0d0
    do i=1,n
       do j=1,3
          do k=1,3
             abc(j,i)=abc(j,i)+lat_1(j,k)*xyz(k,i)
          enddo !k
          abc(j,i)=mod(abc(j,i),1.0_wp)
       enddo !j
    enddo !i
References inv_cell().