My Project: xtb_xtb_eeq Module Reference
xtb_xtb_eeq Module Reference
Implementation of the electronegativity equilibration model.
Data Types
type tenequilibration
Electronegativity equilibration model.
interface init
Initialize equilibration model.
interface solve
Interface to a solver for linear systems.
Functions/Subroutines
subroutine initenequilibrationatomic (self, env, chi, kcn, gam, num)
Initialize equilibration model form parameters.
subroutine initenequilibration (self, env, chi, kcn, gam, num)
Initialize equilibration model form parameters.
subroutine chargeequilibration (self, env, mol, coulomb, cn, dcndr, dcndL, energy, gradient, sigma, qat, qsh, dqdr, dqdL)
subroutine solve_sysv (env, mat, rhs, vec)
subroutine solve_sytri (env, mat, rhs, vec)
subroutine invert_sytri (env, mat)
Detailed Description
Implementation of the electronegativity equilibration model.
Function/Subroutine Documentation
chargeequilibration()
subroutine xtb_xtb_eeq::chargeequilibration (class(tenequilibration), intent(inout) self, type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, class(tcoulomb), intent(inout) coulomb, real(wp), dimension(:), intent(in) cn, real(wp), dimension(:, :, :), intent(in) dcndr, real(wp), dimension(:, :, :), intent(in) dcndL, real(wp), intent(inout), optional energy, real(wp), dimension(:, :), intent(inout), optional gradient, real(wp), dimension(:, :), intent(inout), optional sigma, real(wp), dimension(:), intent(out), optional qat, real(wp), dimension(:), intent(out), optional qsh, real(wp), dimension(:, :, :), intent(out), optional dqdr, real(wp), dimension(:, :, :), intent(out), optional dqdL) private
Parameters
[in,out] self Instance of the equilibration model
[in,out] env Calculation environment
[in] mol Molecular structure data
[in,out] coulomb Instance of the Coulomb evaluator
[in] cn Coordination number
[in] dcndr Derivative of the coordination number w.r.t. Cartesian coordinates
[in] dcndl Derivative of the coordination number w.r.t. strain derivatives
[in,out] energy Electrostatic energy
[in,out] gradient Molecular gradient
[in,out] sigma Strain derivatives
[out] qat Atomic partial charges
[out] qsh Shell-resolved partial charges
[out] dqdr Derivative of the partial charges w.r.t. Cartesian coordinates
[out] dqdl Derivative of the partial charges w.r.t. strain derivatives
Definition at line 240 of file eeq.f90.
    character(len=*), parameter :: source = 'xtb_eeq_chargeEquilibration'
    class(TENEquilibration), intent(inout) :: self
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    class(TCoulomb), intent(inout) :: coulomb
    real(wp), intent(in) :: cn(:)
    real(wp), intent(in) :: dcndr(:, :, :)
    real(wp), intent(in) :: dcndL(:, :, :)
    real(wp), intent(inout), optional :: energy
    real(wp), intent(inout), optional :: gradient(:, :)
    real(wp), intent(inout), optional :: sigma(:, :)
    real(wp), intent(out), optional :: qat(:)
    real(wp), intent(out), optional :: qsh(:)
    real(wp), intent(out), optional :: dqdr(:, :, :)
    real(wp), intent(out), optional :: dqdL(:, :, :)
    real(wp), allocatable :: jmat(:, :), inv(:, :)
    real(wp), allocatable :: djdr(:, :, :), djdtr(:, :), djdL(:, :, :)
    real(wp), allocatable :: xvec(:), qvec(:), dxdcn(:), shift(:)
    real(wp), allocatable :: dxdr(:, :, :), dxdL(:, :, :)
    logical :: deriv, response, exitRun
    integer :: nsh, ndim
    integer :: iat, ish, ii, iid
    real(wp) :: tmp
    deriv = present(gradient) .or. present(sigma)
    response = present(dqdr) .or. present(dqdl)
    nsh = sum(coulomb%itbl(2, :))
    ndim = nsh + 1
    allocate(jmat(ndim, ndim))
    allocate(xvec(ndim))
    allocate(qvec(ndim))
    allocate(dxdcn(nsh))
    call coulomb%getCoulombMatrix(mol, jmat)
    do iat = 1, mol%n
       ii = coulomb%itbl(1, iat)
       iid = mol%id(iat)
       do ish = 1, coulomb%itbl(2, iat)
          tmp = self%kcn(ish, iid) / (sqrt(cn(iat)) + 1.0e-14_wp)
          xvec(ii+ish) = -self%chi(ish, iid) + tmp*cn(iat)
          dxdcn(ii+ish) = 0.5_wp*tmp
          jmat(ii+ish, ii+ish) = jmat(ii+ish, ii+ish) + self%gam(ish, iid)
          jmat(ii+ish, ndim) = 1.0_wp
          jmat(ndim, ii+ish) = 1.0_wp
       end do
    end do
    xvec(ndim) = mol%chrg
    jmat(ndim, ndim) = 0.0_wp
    inv = jmat
    if (response) then
       call self%invert_lineq(env, inv, xvec, qvec)
    else
       call self%solve_lineq(env, inv, xvec, qvec)
    end if
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Solving linear equations failed", source)
       return
    end if
    if (present(qat)) then
       qat(:) = 0.0_wp
       do iat = 1, mol%n
          ii = coulomb%itbl(1, iat)
          do ish = 1, coulomb%itbl(2, iat)
             qat(iat) = qat(iat) + qvec(ii+ish)
          end do
       end do
    end if
    if (present(qsh)) then
       qsh(:) = qvec(:nsh)
    end if
    if (present(energy)) then
       shift = xvec
       call mctc_symv(jmat, qvec, shift, alpha=0.5_wp, beta=-1.0_wp)
       energy = energy + mctc_dot(qvec, shift)
    end if
    if (deriv .or. response) then
       allocate(djdr(3, mol%n, ndim))
       allocate(djdtr(3, ndim))
       allocate(djdl(3, 3, ndim))
       allocate(dxdr(3, mol%n, ndim))
       allocate(dxdl(3, 3, ndim))
       call coulomb%getCoulombDerivs(mol, qvec, djdr, djdtr, djdl)
       do iat = 1, mol%n
          ii = coulomb%itbl(1, iat)
          do ish = 1, coulomb%itbl(2, iat)
             dxdr(:, :, ii+ish) = -dxdcn(ii+ish)*dcndr(:, :, iat)
             dxdl(:, :, ii+ish) = -dxdcn(ii+ish)*dcndl(:, :, iat)
          end do
       end do
       dxdr(:, :, ndim) = 0.0_wp
       dxdl(:, :, ndim) = 0.0_wp
       if (present(gradient)) then
          call contract(djdr, qvec, gradient, beta=1.0_wp)
          call contract(dxdr, qvec, gradient, beta=1.0_wp)
       end if
       if (present(sigma)) then
          call contract(djdl, qvec, sigma, beta=1.0_wp)
          call contract(dxdl, qvec, sigma, beta=1.0_wp)
       end if
       if (response) then
          do iat = 1, mol%n
             ii = coulomb%itbl(1, iat)
             do ish = 1, coulomb%itbl(2, iat)
                djdr(:, iat, ii+ish) = djdr(:, iat, ii+ish) + djdtr(:, ii+ish)
             end do
          end do
          if (present(dqdr)) then
             dqdr(:, :, :) = 0.0_wp
             call contract(djdr, inv(:, :nsh), dqdr, alpha=-1.0_wp, beta=0.0_wp)
             call contract(dxdr, inv(:, :nsh), dqdr, alpha=-1.0_wp, beta=1.0_wp)
          end if
          if (present(dqdl)) then
             dqdl(:, :, :) = 0.0_wp
             call contract(djdl, inv(:, :nsh), dqdl, alpha=-2.0_wp, beta=0.0_wp)
             call contract(dxdl, inv(:, :nsh), dqdl, alpha=-1.0_wp, beta=1.0_wp)
          end if
       end if
    end if
initenequilibration()
subroutine xtb_xtb_eeq::initenequilibration (type(tenequilibration), intent(out) self, type(tenvironment), intent(inout) env, real(wp), dimension(:, :), intent(in) chi, real(wp), dimension(:, :), intent(in), optional kcn, real(wp), dimension(:, :), intent(in), optional gam, integer, dimension(:), intent(in), optional num) private
Initialize equilibration model form parameters.
Parameters
[out] self Instance of the equilibration model
[in,out] env Calculation environment
[in] chi Electronegativity of each species
[in] kcn Coordination number dependence of each species
[in] gam Chemical hardness of each species
[in] num Atomic number for each id
Definition at line 166 of file eeq.f90.
    character(len=*), parameter :: source = 'xtb_eeq_initENEquilibration'
    type(TENEquilibration), intent(out) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: chi(:, :)
    real(wp), intent(in), optional :: kcn(:, :)
    real(wp), intent(in), optional :: gam(:, :)
    integer, intent(in), optional :: num(:)
    integer :: ii
    if (present(num)) then
       allocate(self%chi(size(chi, dim=1), size(num)))
       do ii = 1, size(num)
          self%chi(:, ii) = chi(:, num(ii))
       end do
    else
       self%chi = chi
    end if
    self%solve_lineq => solve_sysv
    self%invert_lineq => solve_sytri
    if (present(kcn)) then
       if (any(shape(kcn) /= shape(chi))) then
          call env%error("Cannot initialize CN dependence of EN", source)
          allocate(self%kcn(size(self%chi, 1), size(self%chi, 2)))
          self%kcn(:, :) = 0.0_wp
       else
          if (present(num)) then
             allocate(self%kcn(size(kcn, dim=1), size(num)))
             do ii = 1, size(num)
                self%kcn(:, ii) = kcn(:, num(ii))
             end do
          else
             self%kcn = kcn
          end if
       end if
    end if
    if (present(gam)) then
       if (any(shape(gam) /= shape(chi))) then
          call env%error("Cannot initialize chemical hardness", source)
          allocate(self%gam(size(self%chi, 1), size(self%chi, 2)))
          self%gam(:, :) = 0.0_wp
       else
          if (present(num)) then
             allocate(self%gam(size(gam, dim=1), size(num)))
             do ii = 1, size(num)
                self%gam(:, ii) = gam(:, num(ii))
             end do
          else
             self%gam = gam
          end if
       end if
    end if
initenequilibrationatomic()
subroutine xtb_xtb_eeq::initenequilibrationatomic (type(tenequilibration), intent(out) self, type(tenvironment), intent(inout) env, real(wp), dimension(:), intent(in) chi, real(wp), dimension(:), intent(in), optional kcn, real(wp), dimension(:), intent(in), optional gam, integer, dimension(:), intent(in), optional num) private
Initialize equilibration model form parameters.
Parameters
[out] self Instance of the equilibration model
[in,out] env Calculation environment
[in] chi Electronegativity of each species
[in] kcn Coordination number dependence of each species
[in] gam Chemical hardness of each species
[in] num Atomic number for each id
Definition at line 91 of file eeq.f90.
    character(len=*), parameter :: source = 'xtb_eeq_initENEquilibrationAtomic'
    type(TENEquilibration), intent(out) :: self
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(in) :: chi(:)
    real(wp), intent(in), optional :: kcn(:)
    real(wp), intent(in), optional :: gam(:)
    integer, intent(in), optional :: num(:)
    integer :: ii
    if (present(num)) then
       allocate(self%chi(1, size(num)))
       do ii = 1, size(num)
          self%chi(1, ii) = chi(num(ii))
       end do
    else
       self%chi = reshape(chi, [1, size(chi)])
    end if
    self%solve_lineq => solve_sysv
    self%invert_lineq => solve_sytri
    if (present(kcn)) then
       if (any(shape(kcn) /= shape(chi))) then
          call env%error("Cannot initialize CN dependence of EN", source)
          allocate(self%kcn(1, size(self%chi)))
          self%kcn(:, :) = 0.0_wp
       else
          if (present(num)) then
             allocate(self%kcn(1, size(num)))
             do ii = 1, size(num)
                self%kcn(1, ii) = kcn(num(ii))
             end do
          else
             self%kcn = reshape(kcn, [1, size(kcn)])
          end if
       end if
    end if
    if (present(gam)) then
       if (any(shape(gam) /= shape(chi))) then
          call env%error("Cannot initialize chemical hardness", source)
          allocate(self%gam(1, size(self%chi)))
          self%gam(:, :) = 0.0_wp
       else
          if (present(num)) then
             allocate(self%gam(1, size(num)))
             do ii = 1, size(num)
                self%gam(1, ii) = gam(num(ii))
             end do
          else
             self%gam = reshape(gam, [1, size(gam)])
          end if
       end if
    end if
invert_sytri()
subroutine xtb_xtb_eeq::invert_sytri (type(tenvironment), intent(inout) env, real(wp), dimension(:, :), intent(inout) mat) private
Parameters
[in,out] env Calculation environment
Definition at line 487 of file eeq.f90.
    character(len=*), parameter :: source = 'xtb_eeq_sytri'
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(inout) :: mat(:, :)
    integer :: ii, jj
    integer :: lwork, ndim, info
    real(wp) :: test(1)
    real(wp), allocatable :: work(:)
    integer, allocatable :: ipiv(:)
    ndim = size(mat, dim=1)
    if (size(mat, dim=2) < ndim) then
       call env%error("A not so carefully crafted algorithm did mess up", source)
       return
    end if
    allocate(ipiv(ndim))
    ! assume work space query, set best value to test after first dsytrf call
    call lapack_sytrf('L', ndim, mat, ndim, ipiv, test, -1, info)
    lwork = int(test(1))
    allocate(work(lwork))
    ! Bunch-Kaufman factorization A = L*D*L**T
    call lapack_sytrf('L', ndim, mat, ndim, ipiv, work, lwork, info)
    if(info > 0)then
       call env%error('Bunch-Kaufman factorization failed', source)
       return
    endif
    ! A from factorized L matrix, save lower part of A in matrix
    ! matrix is overwritten with lower triangular part of A
    call lapack_sytri('L', ndim, mat, ndim, ipiv, work, info)
    if (info > 0) then
       call env%error('Bunch-Kaufman inversion failed', source)
       return
    endif
    ! symmetrizes A matrix from lower triangular part of inverse matrix
    do ii = 1, ndim
       do jj = ii+1, ndim
          mat(ii,jj) = mat(jj,ii)
       enddo
    enddo
Referenced by solve_sytri().
solve_sysv()
subroutine xtb_xtb_eeq::solve_sysv (type(tenvironment), intent(inout) env, real(wp), dimension(:, :), intent(inout) mat, real(wp), dimension(:), intent(in) rhs, real(wp), dimension(:), intent(out), target vec) private
Parameters
[in,out] env Calculation environment
Definition at line 409 of file eeq.f90.
    character(len=*), parameter :: source = 'xtb_eeq_sysv'
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(inout) :: mat(:, :)
    real(wp), intent(in) :: rhs(:)
    real(wp), intent(out), target :: vec(:)
    integer :: lwork, ndim, info
    real(wp), pointer :: ptr(:, :)
    real(wp) :: test(1)
    real(wp), allocatable :: work(:)
    integer, allocatable :: ipiv(:)
    ndim = size(mat, dim=1)
    if (size(mat, dim=2) < ndim .or. size(vec) < ndim .or. size(rhs) < ndim) then
       call env%error("A not so carefully crafted algorithm did mess up", source)
       return
    end if
    vec(:ndim) = rhs(:ndim)
    allocate(ipiv(ndim))
    ptr(1:ndim, 1:1) => vec(1:ndim)
    ! assume work space query, set best value to test after first dsysv call
    call dsysv('l', ndim, 1, mat, ndim, ipiv, ptr, ndim, test, -1, info)
    lwork = int(test(1))
    allocate(work(lwork))
    call dsysv('l', ndim, 1, mat, ndim, ipiv, ptr, ndim, work, lwork, info)
    if (info > 0) then
       call env%error("LAPACK linear equation solver failed", source)
       return
    end if
Referenced by xtb_xtb_eeq::init::initenequilibration(), and xtb_xtb_eeq::init::initenequilibrationatomic().
solve_sytri()
subroutine xtb_xtb_eeq::solve_sytri (type(tenvironment), intent(inout) env, real(wp), dimension(:, :), intent(inout) mat, real(wp), dimension(:), intent(in) rhs, real(wp), dimension(:), intent(out), target vec) private
Parameters
[in,out] env Calculation environment
Definition at line 454 of file eeq.f90.
    character(len=*), parameter :: source = 'xtb_eeq_sytri'
    type(TEnvironment), intent(inout) :: env
    real(wp), intent(inout) :: mat(:, :)
    real(wp), intent(in) :: rhs(:)
    real(wp), intent(out), target :: vec(:)
    integer :: ndim
    logical :: exitRun
    ndim = size(mat, dim=1)
    if (size(mat, dim=2) < ndim .or. size(vec) < ndim .or. size(rhs) < ndim) then
       call env%error("A not so carefully crafted algorithm did mess up", source)
       return
    end if
    call invert_sytri(env, mat)
    call env%check(exitrun)
    if (exitrun) return
    call mctc_symv(mat, rhs, vec)
References invert_sytri().
Referenced by xtb_xtb_eeq::init::initenequilibration(), and xtb_xtb_eeq::init::initenequilibrationatomic().