My Project: xtb_main_setup Module Reference
xtb_main_setup Module Reference
TODO.
Functions/Subroutines
subroutine, public newcalculator (env, mol, calc, fname, restart, accuracy)
subroutine, public newxtbcalculator (env, mol, calc, fname, method, accuracy)
subroutine, public newgffcalculator (env, mol, calc, fname, restart, version)
subroutine, public newwavefunction (env, mol, calc, chk)
subroutine newwavefunction_ (env, mol, calc, wfn)
subroutine, public addsolvationmodel (env, calc, input)
Detailed Description
TODO.
Function/Subroutine Documentation
addsolvationmodel()
subroutine, public xtb_main_setup::addsolvationmodel (type(tenvironment), intent(inout) env, class(tcalculator), intent(inout) calc, type(tsolvinput), intent(in) input)
Definition at line 325 of file setup.f90.
    type(TEnvironment), intent(inout) :: env
    class(TCalculator), intent(inout) :: calc
    type(TSolvInput), intent(in) :: input
    integer :: level
    level = 0
    select type(calc)
    type is(txtbcalculator)
       level = calc%xtbData%level
    end select
    if (allocated(input%solvent)) then
       calc%lSolv = input%solvent /= 'none' .and. input%solvent /= 'gas' &
          & .and. input%solvent /= 'vac'
    else
       calc%lSolv = .false.
    end if
    if (calc%lSolv) then
       allocate(calc%solvation)
       call init(calc%solvation, env, input, level)
    endif
Referenced by xtb_main_defaults::initdefaults(), xtb_api_calculator::setsolvent_api(), test_gfn0_mindless_solvation(), test_gfn1_mindless_solvation(), test_gfn1gbsa_api(), test_gfn2_dmetal(), test_gfn2_mindless_solvation(), test_gfn2_pcem_api(), test_gfn2gbsa_api(), test_gfn2salt_api(), test_gfnff_gbsa(), test_gfnff_mindless_solvation(), test_gfnff_pdb(), test_gfnff_scaleup(), test_gfnff_sdf(), and test_ipea_indole().
newcalculator()
subroutine, public xtb_main_setup::newcalculator (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, class(tcalculator), intent(out), allocatable calc, character(len=*), intent(in) fname, logical, intent(in) restart, real(wp), intent(in) accuracy)
Definition at line 53 of file setup.f90.
    character(len=*), parameter :: source = 'main_setup_newCalculator'
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    class(TCalculator), allocatable, intent(out) :: calc
    character(len=*), intent(in) :: fname
    logical, intent(in) :: restart
    real(wp), intent(in) :: accuracy
    type(TxTBCalculator), allocatable :: xtb
    type(TGFFCalculator), allocatable :: gfnff
    logical :: exitRun
    select case(mode_extrun)
    case default
       call env%error("Unknown calculator type", source)
    case(p_ext_eht, p_ext_xtb)
       allocate(xtb)
       call newxtbcalculator(env, mol, xtb, fname, gfn_method, accuracy)
       call env%check(exitrun)
       if (exitrun) then
          call env%error("Could not construct new calculator", source)
          return
       end if
       call move_alloc(xtb, calc)
    case(p_ext_gfnff)
       allocate(gfnff)
       call newgffcalculator(env, mol, gfnff, fname, restart)
       call env%check(exitrun)
       if (exitrun) then
          call env%error("Could not construct new calculator", source)
          return
       end if
       call move_alloc(gfnff, calc)
    case(p_ext_qmdff, p_ext_orca, p_ext_turbomole, p_ext_mopac)
       allocate(tdummycalculator :: calc)
       calc%accuracy = accuracy
    end select
References xtb_setparam::gfn_method, xtb_setparam::mode_extrun, newgffcalculator(), newxtbcalculator(), xtb_setparam::p_ext_eht, xtb_setparam::p_ext_gfnff, xtb_setparam::p_ext_mopac, xtb_setparam::p_ext_orca, xtb_setparam::p_ext_qmdff, xtb_setparam::p_ext_turbomole, and xtb_setparam::p_ext_xtb.
Referenced by xtb_prog_main::xtbmain().
newgffcalculator()
subroutine, public xtb_main_setup::newgffcalculator (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, type(tgffcalculator), intent(out) calc, character(len=*), intent(in) fname, logical, intent(in) restart, integer, intent(in), optional version)
Obtain the parameter file
Definition at line 209 of file setup.f90.
    use xtb_gfnff_param
    use xtb_gfnff_setup, only : gfnff_setup
    use xtb_disp_dftd4, only : newd3model
    character(len=*), parameter :: source = 'main_setup_newGFFCalculator'
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    type(TGFFCalculator), intent(out) :: calc
    character(len=*), intent(in) :: fname
    logical, intent(in) :: restart
    integer, intent(in), optional :: version
    type(TxTBParameter) :: globpar
    integer :: ich
    logical :: exist, okbas
    logical :: exitRun
    if (present(version)) then
       calc%version = version
    else
       calc%version = gffversion%angewChem2020_1
    end if
    call calc%topo%zero
    calc%update = .true.
    ! global accuracy factor similar to acc in xtb used in SCF
    calc%accuracy = 0.1_wp
    if (mol%n > 10000) then
       calc%accuracy = 2.0_wp
    end if
    call open_file(ich, fname, 'r')
    exist = ich /= -1
    if (exist) then
       call gfnff_read_param(ich, calc%param)
       call close_file(ich)
    else ! no parameter file, try to load internal version
       call gfnff_load_param(calc%version, calc%param, exist)
       if (.not.exist) then
          call env%error('Parameter file '//fname//' not found!', source)
          return
       end if
    endif
    call newd3model(calc%topo%dispm, mol%n, mol%at)
    call gfnff_setup(env, verbose, restart, mol, &
       & calc%gen, calc%param, calc%topo, calc%accuracy, calc%version)
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Could not create force field calculator", source)
       return
    end if
References close_file(), xtb_gfnff_param::gffversion, xtb_gfnff_param::gfnff_load_param(), xtb_gfnff_param::gfnff_read_param(), xtb_gfnff_setup::gfnff_setup(), xtb_disp_dftd4::newd3model(), open_file(), true(), and xtb_setparam::verbose.
Referenced by xtb_api_calculator::loadgfnff_api(), newcalculator(), xtb_gfnff_convert::struc_convert(), test_gfnff_gbsa(), test_gfnff_hb(), test_gfnff_mindless_basic(), test_gfnff_mindless_solvation(), test_gfnff_pdb(), test_gfnff_scaleup(), test_gfnff_sdf(), test_gfnff_sp(), and xtb_prog_topology::xtbtopology().
newwavefunction()
subroutine, public xtb_main_setup::newwavefunction (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, type(txtbcalculator), intent(in) calc, type(trestart), intent(inout) chk)
Definition at line 274 of file setup.f90.
    type(TEnvironment), intent(inout) :: env
    type(TRestart), intent(inout) :: chk
    type(TxTBCalculator), intent(in) :: calc
    type(TMolecule), intent(in) :: mol
    call newwavefunction_(env, mol, calc, chk%wfn)
References chk(), and newwavefunction_().
Referenced by xtb_api_interface::singlepoint_api(), test_gfn0_api(), test_gfn0_api_srb(), test_gfn0_mindless_basic(), test_gfn0_mindless_solvation(), test_gfn1_api(), test_hessian::test_gfn1_hessian(), test_gfn1_mindless_basic(), test_gfn1_mindless_solvation(), test_gfn1_pbc3d(), test_gfn1_pcem_api(), test_gfn1_xb(), test_gfn1gbsa_api(), test_gfn2_api(), test_gfn2_dmetal(), test_hessian::test_gfn2_hessian(), test_gfn2_mindless_basic(), test_gfn2_mindless_solvation(), test_gfn2_pcem_api(), test_gfn2gbsa_api(), test_gfn2salt_api(), test_ipea_indole(), test_peeq_api(), and test_peeq_api_srb().
newwavefunction_()
subroutine xtb_main_setup::newwavefunction_ (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, type(txtbcalculator), intent(in) calc, type(twavefunction), intent(inout) wfn) private
Definition at line 282 of file setup.f90.
    character(len=*), parameter :: source = 'main_setup_newWavefunction'
    type(TEnvironment), intent(inout) :: env
    type(TWavefunction), intent(inout) :: wfn
    type(TxTBCalculator), intent(in) :: calc
    type(TMolecule), intent(in) :: mol
    real(wp), allocatable :: cn(:)
    type(chrg_parameter) :: chrgeq
    logical :: exitRun
    allocate(cn(mol%n))
    call wfn%allocate(mol%n,calc%basis%nshell,calc%basis%nao)
    wfn%nel = idint(sum(mol%z)) - nint(mol%chrg)
    wfn%nopen = mol%uhf
    if(wfn%nopen == 0 .and. mod(wfn%nel,2) /= 0) wfn%nopen=1
    if (mol%npbc > 0) then
       wfn%q = mol%chrg/real(mol%n,wp)
    else
       if (guess_charges.eq.p_guess_gasteiger) then
          call iniqcn(mol%n,wfn%nel,mol%at,mol%z,mol%xyz,nint(mol%chrg),1.0_wp, &
             & wfn%q,cn,calc%xtbData%level,.true.)
       else if (guess_charges.eq.p_guess_goedecker) then
          call new_charge_model_2019(chrgeq,mol%n,mol%at)
          call ncoord_erf(mol%n,mol%at,mol%xyz,cn)
          call eeq_chrgeq(mol,env,chrgeq,cn,wfn%q)
          call env%check(exitrun)
          if (exitrun) then
             call env%rescue("EEQ guess failed, falling back to SAD guess", source)
             wfn%q = mol%chrg/real(mol%n,wp)
          end if
       else
          wfn%q = mol%chrg/real(mol%n,wp)
       end if
    end if
    call iniqshell(calc%xtbData,mol%n,mol%at,mol%z,calc%basis%nshell, &
       & wfn%q,wfn%qsh,calc%xtbData%level)
References xtb_setparam::guess_charges, xtb_iniq::iniqcn(), xtb_scc_core::iniqshell(), xtb_disp_ncoord::ncoord_erf(), xtb_chargemodel::new_charge_model_2019(), xtb_setparam::p_guess_gasteiger, xtb_setparam::p_guess_goedecker, and true().
Referenced by newwavefunction().
newxtbcalculator()
subroutine, public xtb_main_setup::newxtbcalculator (type(tenvironment), intent(inout) env, type(tmolecule), intent(in) mol, type(txtbcalculator), intent(out) calc, character(len=*), intent(in), optional fname, integer, intent(in), optional method, real(wp), intent(in), optional accuracy)
Obtain the parameter file
set up the basis set for the tb-Hamiltonian
check for external point charge field
Definition at line 109 of file setup.f90.
    character(len=*), parameter :: source = 'main_setup_newXTBCalculator'
    type(TEnvironment), intent(inout) :: env
    type(TMolecule), intent(in) :: mol
    type(TxTBCalculator), intent(out) :: calc
    integer, intent(in), optional :: method
    real(wp), intent(in), optional :: accuracy
    character(len=*), intent(in), optional :: fname
    character(len=:), allocatable :: filename
    type(TxTBParameter) :: globpar
    integer :: ich
    logical :: exist, okbas
    logical :: exitRun
    if (present(fname)) then
       filename = fname
    else
       if (present(method)) then
          select case(method)
          case(0)
             call rdpath(env%xtbpath, 'param_gfn0-xtb.txt', filename, exist)
             if (.not.exist) filename = 'param_gfn0-xtb.txt'
          case(1)
             call rdpath(env%xtbpath, 'param_gfn1-xtb.txt', filename, exist)
             if (.not.exist) filename = 'param_gfn1-xtb.txt'
          case(2)
             call rdpath(env%xtbpath, 'param_gfn2-xtb.txt', filename, exist)
             if (.not.exist) filename = 'param_gfn2-xtb.txt'
          end select
       end if
    end if
    if (.not.allocated(filename)) then
       call env%error("No parameter file or parametrisation info provided", source)
       return
    end if
    if (present(accuracy)) then
       calc%accuracy = accuracy
    else
       calc%accuracy = 1.0_wp
    end if
    calc%etemp = 300.0_wp
    calc%maxiter = 250
    allocate(calc%xtbData)
    call open_file(ich, filename, 'r')
    exist = ich /= -1
    if (exist) then
       call readparam(env, ich, globpar, calc%xtbData, .true.)
       call close_file(ich)
    else ! no parameter file, check if we have one compiled into the code
       call use_parameterset(filename, globpar, calc%xtbData, exist)
       if (.not.exist) then
          call env%error('Parameter file '//filename//' not found!', source)
          return
       end if
    endif
    if (present(method)) then
       if (method /= calc%xtbData%level) then
          call env%error("Requested method does not match loaded method", source)
          return
       end if
    end if
    call env%check(exitrun)
    if (exitrun) then
       call env%error("Could not load parameters", source)
       return
    end if
    allocate(calc%basis)
    call newbasisset(calc%xtbData, mol%n, mol%at, calc%basis, okbas)
    if (.not.okbas) then
       call env%error('basis set could not be setup completely', source)
       return
    end if
    if (allocated(pcem_file)) then
       call open_file(ich, pcem_file, 'r')
       if (ich /= -1) then
          call read_pcem(ich, env, calc%pcem, calc%xtbData%coulomb)
          call close_file(ich)
       end if
    end if
References close_file(), xtb_basis::newbasisset(), open_file(), xtb_setparam::pcem_file, xtb_mctc_systools::rdpath(), xtb_embedding::read_pcem(), xtb_readparam::readparam(), true(), and xtb_paramset::use_parameterset().
Referenced by xtb_api_calculator::loadgfn0xtb_api(), xtb_api_calculator::loadgfn1xtb_api(), xtb_api_calculator::loadgfn2xtb_api(), newcalculator(), test_gfn0_api(), test_gfn0_api_srb(), test_gfn0_mindless_basic(), test_gfn0_mindless_solvation(), test_gfn1_api(), test_hessian::test_gfn1_hessian(), test_gfn1_mindless_basic(), test_gfn1_mindless_solvation(), test_gfn1_pbc3d(), test_gfn1_pcem_api(), test_gfn1_xb(), test_gfn1gbsa_api(), test_gfn2_api(), test_gfn2_dmetal(), test_hessian::test_gfn2_hessian(), test_gfn2_mindless_basic(), test_gfn2_mindless_solvation(), test_gfn2_pcem_api(), test_gfn2gbsa_api(), test_gfn2salt_api(), test_ipea_indole(), test_peeq_api(), and test_peeq_api_srb().