My Project: src/prog/primary.f90 File Reference
primary.f90 File Reference
Functions/Subroutines
program xtb_prog_primary
The primary driver for the xtb program package.
subroutine getrunmode (argParser, runMode)
start by initializing the MCTC library
Function/Subroutine Documentation
getrunmode()
subroutine xtb_prog_primary::getrunmode (type(targparser), intent(inout) argParser, integer, intent(out) runMode)
start by initializing the MCTC library
Initialize calculation environment Initialize argument parser from command line Get the requested run mode Select the correct submodule to run Run the main program Run the info submodule Run the thermo submodule Run the thermo submodule
Parameters
[in,out] argparser Command line argument parser
[out] runmode Requested run mode
First command line argument
Initialize run mode with default submodule
Get first argument
Check if we have a command line argument
Get the identifier of the submodule
In case of an invalid identifier, we reset the parser and use the default
Definition at line 73 of file primary.f90.
    type(TArgParser), intent(inout) :: argParser
    integer, intent(out) :: runMode
    character(len=:), allocatable :: argument
    runmode = xtbsubmodule%main
    call argparser%nextArg(argument)
    if (allocated(argument)) then
       runmode = getsubmodule(argument)
       if (runmode == xtbsubmodule%invalid) then
          call argparser%reset
          runmode = xtbsubmodule%main
       end if
    end if
References xtb_prog_submodules::getsubmodule(), and xtb_prog_submodules::xtbsubmodule.
Referenced by xtb_prog_primary().
xtb_prog_primary()
program xtb_prog_primary
The primary driver for the xtb program package.
Definition at line 19 of file primary.f90.
References getrunmode(), true(), xtb_prog_info::xtbinfo(), xtb_prog_submodules::xtbsubmodule, xtb_prog_thermo::xtbthermo(), and xtb_prog_topology::xtbtopology().