My Project: src/main/property.F90 File Reference
property.F90 File Reference
Modules
module xtb_propertyoutput
Functions/Subroutines
subroutine xtb_propertyoutput::write_energy (iunit, sccres, frqres, hess)
subroutine xtb_propertyoutput::write_energy_gff (iunit, sccres, frqres, hess)
subroutine xtb_propertyoutput::main_property (iunit, env, mol, wfx, basis, xtbData, res, solvModel, acc)
subroutine xtb_propertyoutput::main_cube (lverbose, mol, wfx, basis, res)
subroutine xtb_propertyoutput::main_freq (iunit, mol, wfx, res)
subroutine xtb_propertyoutput::print_charges (ifile, n, q)
subroutine xtb_propertyoutput::print_mulliken (iunit, n, at, sym, xyz, z, nao, S, P, aoat2, lao2)
subroutine xtb_propertyoutput::print_wbofile (iunit, n, wbo, thr)
subroutine xtb_propertyoutput::print_wiberg (iunit, n, at, sym, wbo, thr)
subroutine wibsort (ncent, imo, imem, qmo)
subroutine xtb_propertyoutput::print_wbo_fragment (iunit, n, at, wbo, thr)
subroutine mrec (molcount, cn, bond, n, at, molvec)
recursive subroutine neighbours (i, cn, at, taken, n, bond, molvec, molcnt)
subroutine xtb_propertyoutput::print_molpol (iunit, n, at, sym, xyz, q, wf, g_a, g_c, dispm)
subroutine xtb_propertyoutput::print_dipole (iunit, n, at, xyz, z, nao, P, dpint)
subroutine xtb_propertyoutput::print_spin_population (iunit, n, at, sym, nao, focca, foccb, S, C, aoat2, lao2)
subroutine xtb_propertyoutput::print_fod_population (iunit, ifile, n, at, sym, nao, S, C, etemp, emo, ihomoa, ihomob, aoat2, lao2)
subroutine xtb_propertyoutput::print_thermo (iunit, nat, nvib_in, at, xyz, freq, etot, htot, gtot, nimag, pr, zp)
subroutine xtb_propertyoutput::print_thermo_sthr_lnq (iunit, nvib, vibs, avmom, sthr, temp)
subroutine xtb_propertyoutput::print_thermo_sthr_ts (iunit, nvib, vibs, avmom_si, sthr_rcm, temp)
subroutine xtb_propertyoutput::print_gbsa_info (iunit, sym, gbsa)
subroutine print_orbital_eigenvalues (iunit, wfn, range)
subroutine write_line (iorb, focc, emo, ihomo)
Function/Subroutine Documentation
mrec()
subroutine print_wbo_fragment::mrec (integer, intent(inout) molcount, integer, dimension(n), intent(in) cn, real(wp), dimension(n,n), intent(inout) bond, integer, intent(in) n, integer, dimension(n), intent(in) at, integer, dimension(n), intent(inout) molvec)
Definition at line 704 of file property.F90.
       ! molcount: number of total fragments (increased during search)
       ! xyz: overall Cart. coordinates
       ! n: overall number of atoms
       ! at: atomic number array
       ! molvec: assignment vector of atom to fragment
       implicit none
       integer, intent(in)    :: cn(n)
       integer, intent(in)    :: n,at(n)
       integer, intent(inout) :: molvec(n),molcount
       real(wp),intent(inout) :: bond(n,n)
       logical, allocatable   :: taken(:)
       integer :: i
       allocate( taken(n) )
       molvec=0
       molcount=1
       taken=.false.
       do i=1,n
        if(.not.taken(i)) then
          molvec(i)=molcount
          taken(i)=.true.
          call neighbours(i,cn,at,taken,n,bond,molvec,molcount)
          molcount=molcount+1
       endif
       enddo
       molcount=molcount-1
References neighbours(), and true().
neighbours()
recursive subroutine print_wbo_fragment::neighbours (integer, intent(in) i, integer, dimension(n), intent(in) cn, integer, dimension(n), intent(in) at, logical, dimension(n), intent(inout) taken, integer, intent(in) n, real(wp), dimension(n,n), intent(inout) bond, integer, dimension(n), intent(inout) molvec, integer, intent(inout) molcnt)
Definition at line 732 of file property.F90.
       implicit none
       integer, intent(in)    :: cn(n)
       real(wp),intent(inout) :: bond(n,n)
       integer, intent(in)    :: i,n,at(n)
       integer, intent(inout) :: molcnt,molvec(n)
       logical, intent(inout) :: taken(n)
       integer :: j,icn,k
       icn=cn(i)
       do k=1,icn
          j=maxloc(bond(:,i),1)
          bond(j,i)=0
          if (i .eq. j) cycle
          if (.not.taken(j)) then
             molvec(j)=molcnt
             taken(j)=.true.
             call neighbours(j,cn,at,taken,n,bond,molvec,molcnt)
          endif
       enddo
References neighbours(), and true().
print_orbital_eigenvalues()
subroutine print_orbital_eigenvalues (integer, intent(in) iunit, type(twavefunction), intent(in) wfn, integer, intent(in) range)
Definition at line 1270 of file property.F90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_convert
    use xtb_type_wavefunction
    implicit none
    integer, intent(in) :: iunit
    integer, intent(in) :: range
    type(TWavefunction),intent(in) :: wfn
    character(len=*),parameter :: hlfmt = '(    a24,f21.7,1x,"Eh",f18.4,1x,"eV")'
    integer :: maxorb,minorb,iorb
    real(wp) :: gap
    minorb = max(wfn%ihomoa - (range+1), 1)
    maxorb = min(wfn%ihomoa +  range, wfn%nao)
    gap = wfn%emo(wfn%ihomoa+1) - wfn%emo(wfn%ihomoa)
    write(iunit,'(a)')
    write(iunit,'(a10,a14,a21,a21)') "#","Occupation","Energy/Eh","Energy/eV"
    write(iunit,'(6x,61("-"))')
    if (minorb .gt. 1) then
       call write_line(1,wfn%focc,wfn%emo,wfn%ihomo)
       if (minorb .gt. 2) &
          write(iunit,'(a10,a14,a21,a21)') "...","...","...","..."
    endif
    do iorb = minorb,maxorb
       call write_line(iorb,wfn%focc,wfn%emo,wfn%ihomo)
    enddo
    if (maxorb .lt. wfn%nao) then
       if (maxorb .lt. wfn%nao-1) then
          if (wfn%focc(maxorb) > 1.0e-7_wp) then
             write(iunit,'(a10,a14,a21,a21)') "...","...","...","..."
          else
             write(iunit,'(a10,a14,a21,a21)') "...",   "","...","..."
          endif
       endif
       call write_line(wfn%nao,wfn%focc,wfn%emo,wfn%ihomo)
    endif
    write(iunit,'(6x,61("-"))')
    write(iunit,hlfmt) "HL-Gap",gap*evtoau,gap
    write(iunit,hlfmt) "Fermi-level",(wfn%efa+wfn%efb)/2*evtoau,(wfn%efa+wfn%efb)/2
 contains
 subroutine write_line(iorb,focc,emo,ihomo)
    integer, intent(in) :: iorb
    integer, intent(in) :: ihomo
    real(wp),intent(in) :: focc(:)
    real(wp),intent(in) :: emo (:)
    character(len=*),parameter :: mofmt = '(i10,f14.4,f21.7,f21.4)'
    character(len=*),parameter :: vofmt = '(i10,14x,  f21.7,f21.4)'
    if (focc(iorb) < 1.0e-7_wp) then
       write(iunit,vofmt,advance='no') iorb,             emo(iorb)*evtoau, emo(iorb)
    else
       write(iunit,mofmt,advance='no') iorb, focc(iorb), emo(iorb)*evtoau, emo(iorb)
    endif
    if (iorb == ihomo) then
       write(iunit,'(1x,"(HOMO)")')
    elseif (iorb == ihomo+1) then
       write(iunit,'(1x,"(LUMO)")')
    else
       write(iunit,'(a)')
    endif
 end subroutine write_line
References xtb_mctc_convert::evtoau, xtb_mctc_accuracy::wp, and write_line().
Referenced by xtb_propertyoutput::main_property(), xtb_peeq::peeq(), and xtb_scf::scf().
wibsort()
subroutine print_wiberg::wibsort (integer ncent, integer imo, integer, dimension(ncent) imem, real(wp), dimension(ncent,ncent) qmo)
Definition at line 625 of file property.F90.
    implicit none
    integer  :: ncent
    integer  :: imo
    real(wp) :: qmo(ncent,ncent)
    integer  :: imem(ncent)
    integer  :: ii,i,j,k,ihilf
    real(wp) :: pp
    do ii = 2,ncent
       i = ii - 1
       k = i
       pp= qmo(imo,i)
       do j = ii, ncent
          if (qmo(imo,j) .lt. pp) cycle
          k = j
          pp=qmo(imo,j)
       enddo
       if (k .eq. i) cycle
       qmo(imo,k) = qmo(imo,i)
       qmo(imo,i) = pp
       ihilf=imem(i)
       imem(i)=imem(k)
       imem(k)=ihilf
    enddo
Referenced by xtb_propertyoutput::print_wiberg().
write_line()
subroutine print_orbital_eigenvalues::write_line (integer, intent(in) iorb, real(wp), dimension(:), intent(in) focc, real(wp), dimension (:), intent(in) emo, integer, intent(in) ihomo)
Definition at line 1311 of file property.F90.
    integer, intent(in) :: iorb
    integer, intent(in) :: ihomo
    real(wp),intent(in) :: focc(:)
    real(wp),intent(in) :: emo (:)
    character(len=*),parameter :: mofmt = '(i10,f14.4,f21.7,f21.4)'
    character(len=*),parameter :: vofmt = '(i10,14x,  f21.7,f21.4)'
    if (focc(iorb) < 1.0e-7_wp) then
       write(iunit,vofmt,advance='no') iorb,             emo(iorb)*evtoau, emo(iorb)
    else
       write(iunit,mofmt,advance='no') iorb, focc(iorb), emo(iorb)*evtoau, emo(iorb)
    endif
    if (iorb == ihomo) then
       write(iunit,'(1x,"(HOMO)")')
    elseif (iorb == ihomo+1) then
       write(iunit,'(1x,"(LUMO)")')
    else
       write(iunit,'(a)')
    endif
References xtb_mctc_convert::evtoau.
Referenced by print_orbital_eigenvalues().