My Project: src/qpot.f90 File Reference
qpot.f90 File Reference
Functions/Subroutines
subroutine qpotini (natoms, iat, xyz)
subroutine countfix (nat, nfix, fname)
subroutine rdfix (nat, n, xyz, iat, fname, fixed)
subroutine getf (line, fix)
subroutine fixmetal (n, iat, xyz)
subroutine neighbor (natoms, xyz, iz, nb)
Function/Subroutine Documentation
countfix()
subroutine countfix (integer nat, integer nfix, character(40) fname)
Definition at line 52 of file qpot.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_strings, only : lowercase
    implicit none
    real(wp) xx(10)
    integer n,nn,j,nat,k,nfix
    character(128) line
    character(40) fname
    logical fixed(nat),f
    integer :: ich
    call open_file(ich,fname,'r')
    n=0
    fixed=.false.
    100 read(ich,'(a)',end=300)line
    if(index(line,'$user').ne.0)goto 200
    if(index(line,'$red' ).ne.0)goto 200
    if(index(line,'$end' ).ne.0)goto 200
    call readl(line,xx,nn)
    if(nn.ne.3) goto 100
    n=n+1
    line = lowercase(line)
    call getf(line,f)
    if(f)then
       fixed(n)=.true.
    endif
    goto 100
    200 continue
    nfix=count(fixed)
    call close_file(ich)
    return
    300 continue
    call raise('e','internal error in countfix')
References close_file(), getf(), xtb_mctc_strings::lowercase(), open_file(), raise(), readl(), true(), and xtb_mctc_accuracy::wp.
fixmetal()
subroutine fixmetal (integer n, integer, dimension(n) iat, real(wp), dimension(3,n) xyz)
Definition at line 161 of file qpot.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_fixparam
    implicit none
    integer n,iat(n),nb(0:20,n),nn,ifix(n)
    real(wp) xyz(3,n)
    integer i,j,k
    call neighbor(n,xyz,iat,nb)
    ifix=1
    do i=1,n
       if(iat(i).gt.57.and.iat(i).lt.72)then
          nn=nb(20,i)
          ifix(i)=0
          do j=1,nn
             k=nb(j,i)
             ifix(k)=0
          enddo
       endif
    enddo
    fixset%n=0
    do i=1,n
       if(ifix(i).eq.1)then
          fixset%n=fixset%n+1
          fixset%atoms(fixset%n)=i
       endif
    enddo
References xtb_fixparam::fixset, neighbor(), and xtb_mctc_accuracy::wp.
getf()
subroutine getf (character(*) line, logical fix)
Definition at line 131 of file qpot.f90.
    implicit none
    character(*) line
    CHARACTER(3) e
    logical fix
    integer i,j,k,l,n
    e='   '
    k=1
    fix=.false.
    DO j=1,len(line)
       if (k.gt.2)exit
       n=ichar(line(j:j))
       if(len_trim(e).ge.1 .and. n.eq.ichar(' '))exit!break if space after elem. symbol
       if(len_trim(e).ge.1 .and. n.eq.9)exit !break if tab after elem. symbol
       if(n.ge.ichar('a') .and. n.le.ichar('z') )then
          e(k:k)=line(j:j)
          k=k+1
       endif
    enddo
    if(j.eq.len(line))then
       return
    else
       do i=j,len(line)
          n=ichar(line(i:i))
          if (n.eq.ichar('f'))fix=.true.
       enddo
    endif
References true().
Referenced by countfix(), and rdfix().
neighbor()
subroutine neighbor (integer natoms, real(wp), dimension(3,*) xyz, integer, dimension(*) iz, integer, dimension(0:20,*) nb)
Definition at line 194 of file qpot.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    integer iz(*),natoms,nb(0:20,*)
    real(wp)  xyz(3,*)
    logical da
    integer iat,i,j,k,nn,ni
    real(wp) dx,dy,dz,r,damp,xn,rr,rco,r2,f,pi,a1
    real(wp) rad(94)
    data rad / &
       & 0.32d0,0.37d0,1.30d0,0.99d0,0.84d0,0.75d0,0.71d0,0.64d0,0.60d0, &
       & 0.62d0,1.60d0,1.40d0,1.24d0,1.14d0,1.09d0,1.04d0,1.00d0,1.01d0, &
       & 2.00d0,1.74d0,1.59d0,1.48d0,1.44d0,1.30d0,1.29d0,1.24d0,1.18d0, &
       & 1.17d0,1.22d0,1.20d0,1.23d0,1.20d0,1.20d0,1.18d0,1.17d0,1.16d0, &
       & 2.15d0,1.90d0,1.76d0,1.64d0,1.56d0,1.46d0,1.38d0,1.36d0,1.34d0, &
       & 1.30d0,1.36d0,1.40d0,1.42d0,1.40d0,1.40d0,1.37d0,1.36d0,1.36d0, &
       & 2.38d0,2.06d0,1.94d0,1.84d0,1.90d0,1.88d0,1.86d0,1.85d0,1.83d0, &
       & 1.82d0,1.81d0,1.80d0,1.79d0,1.77d0,1.77d0,1.78d0,1.74d0,1.64d0, &
       & 1.58d0,1.50d0,1.41d0,1.36d0,1.32d0,1.30d0,1.30d0,1.32d0,1.44d0, &
       & 1.45d0,1.50d0,1.42d0,1.48d0,1.46d0,2.42d0,2.11d0,2.01d0,1.90d0, &
       & 1.84d0,1.83d0,1.80d0,1.80d0 /
    do i=1,natoms
       f=1.3
       k=0
       100    do iat=1,natoms
          if(iat.ne.i)then
             dx=xyz(1,iat)-xyz(1,i)
             dy=xyz(2,iat)-xyz(2,i)
             dz=xyz(3,iat)-xyz(3,i)
             r2=dx*dx+dy*dy+dz*dz
             r=sqrt(r2)*0.52917726
             rco=rad(iz(i))+rad(iz(iat))
             if(r.lt.f*rco)then
                k=k+1
                nb(k,i)=iat
             endif
          endif
       enddo
       if(k.lt.1.and.f.lt.1.5)then
          f=f*1.1
          goto 100
       endif
       nb(20,i)=k
    enddo
References xtb_mctc_accuracy::wp.
Referenced by constrallangles(), constralltors(), fixmetal(), and xtb_dynamic::md().
qpotini()
subroutine qpotini (integer natoms, integer, dimension(natoms) iat, real(wp), dimension(3,natoms) xyz)
Definition at line 18 of file qpot.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_setparam
    use xtb_fixparam
    implicit none
    integer natoms,iat(natoms)
    real(wp) xyz(3,natoms)
    integer i,j,k,nread,at(natoms)
    real(wp) xyzf(3,natoms),rij(3)
    character(80) fname,a80
    logical ex
    if(fixset%n.eq.0)then
       write(*,*)'no old-style atom pair restraining (fixing) potential'
    else
       !       calculate distance matrix for fixed atoms
       k=0
       do i=1,fixset%n
          do j=1,i-1
             k=k+1
             rij=xyz(:,fixset%atoms(j))-xyz(:,fixset%atoms(i))
             fixset%val(k)=sqrt(sum(rij*rij))
          enddo
       enddo
       write(*,'(a,i5,a,F10.4)')'# fixed atoms:',fixset%n,' FC:',fixset%fc
       fixset%fc=fixset%fc/(fixset%n-1)
       write(*,'(a,F10.4)')'Final FC :',fixset%fc
       write(*,'(a,F10.0)')'exponent :',fixset%expo
       write(*,'(''fixed atoms'',15I5)')fixset%atoms(1:fixset%n)
    endif
References xtb_fixparam::fixset, and xtb_mctc_accuracy::wp.
rdfix()
subroutine rdfix (integer nat, integer n, real(wp), dimension(3,*) xyz, integer, dimension(nat) iat, character(40) fname, integer, dimension(*) fixed)
Definition at line 88 of file qpot.f90.
    use xtb_mctc_accuracy, only : wp
    use xtb_mctc_strings, only : lowercase
    implicit none
    real(wp) xyz(3,*), xx(10)
    integer nat,iat(nat),n,nn,j,k,fixed(*)
    character(128) line
    character(40) fname
    logical f
    integer :: ich
    write(*,'(''Reading '',A,'' ...'')') trim(fname)
    call open_file(ich,fname,'r')
    n=0
    k=0
 10 read(ich,'(a)',end=20)line
    if(index(line,'$user').ne.0)goto 30
    if(index(line,'$red' ).ne.0)goto 30
    if(index(line,'$end' ).ne.0)goto 30
    call readl(line,xx,nn)
    if(nn.ne.3) goto 10
    n=n+1
    xyz(1,n)=xx(1)
    xyz(2,n)=xx(2)
    xyz(3,n)=xx(3)
    line = lowercase(line)
    call elem(line,j)
    call getf(line,f)
    if(f)then
       k=k+1
       fixed(k)=n  !save the array position of fixed atoms
    endif
    !        if(j.eq.0) error stop 'error reading element symbol'
    !        iat(n)=j
    goto 10
 20 continue
    call close_file(ich)
    call raise('e','internal error in rdfix')
 30 call close_file(ich)
    return
References close_file(), elem(), getf(), xtb_mctc_strings::lowercase(), open_file(), raise(), readl(), and xtb_mctc_accuracy::wp.