My Project: src/qsort.f90 File Reference
qsort.f90 File Reference
Functions/Subroutines
recursive subroutine qsort (a, first, last, ind)
recursive subroutine qqsort (a, first, last)
Function/Subroutine Documentation
qqsort()
recursive subroutine qqsort (real(wp), dimension(*) a, integer first, integer last)
Definition at line 46 of file qsort.f90.
    use xtb_mctc_accuracy, only : wp
   implicit none
   real(wp) :: a(*), x, t
   integer  :: first, last
   integer  :: i, j, ii
   x = a( (first+last) / 2 )
   i = first
   j = last
   do
      do while (a(i) < x)
         i=i+1
      end do
      do while (x < a(j))
         j=j-1
      end do
      if (i >= j) exit
      t = a(i);  a(i) = a(j);  a(j) = t
      i=i+1
      j=j-1
   end do
   if (first < i-1) call qqsort(a, first, i-1)
   if (j+1 < last)  call qqsort(a, j+1, last)
References xtb_mctc_accuracy::wp.
qsort()
recursive subroutine qsort (real(wp), dimension(*) a, integer first, integer last, integer, dimension(*) ind)
Definition at line 18 of file qsort.f90.
    use xtb_mctc_accuracy, only : wp
   implicit none
   real(wp) :: a(*), x, t
   integer  :: ind(*)
   integer  :: first, last
   integer  :: i, j, ii
   x = a( (first+last) / 2 )
   i = first
   j = last
   do
      do while (a(i) < x)
         i=i+1
      end do
      do while (x < a(j))
         j=j-1
      end do
      if (i >= j) exit
      t = a(i);  a(i) = a(j);  a(j) = t
      ii=ind(i); ind(i) = ind(j);  ind(j) = ii
      i=i+1
      j=j-1
   end do
   if (first < i-1) call qsort(a, first, i-1, ind)
   if (j+1 < last)  call qsort(a, j+1, last, ind)
References xtb_mctc_accuracy::wp.
Referenced by xtb_local::atomneigh(), xtb_detrotra::detrotra4(), xtb_detrotra::detrotra8(), xtb_local::lmoneigh(), locmode(), xtb_intmodes::makenabc(), sort_symmetry_elements(), and wrmodef().