My Project: src/readl.f90 File Reference
readl.f90 File Reference
Functions/Subroutines
subroutine readl (a1, x, n)
real(wp) function readaa (a, istart, iend, iend2)
Function/Subroutine Documentation
readaa()
real(wp) function readaa (character(*) a, istart, iend, iend2)
Definition at line 37 of file readl.f90.
    use xtb_mctc_accuracy, only : wp
    implicit real(wp) (a-h,o-z)
    real(wp) readaa
    character(*) a
    nine=ichar('9')
    izero=ichar('0')
    minus=ichar('-')
    idot=ichar('.')
    nd=ichar('D')
    ne=ichar('E')
    ibl=ichar(' ')
    iend=0
    iend2=0
    idig=0
    c1=0
    c2=0
    one=1.d0
    x = 1.d0
    nl=len(a)
    do j=istart,nl-1
       n=ichar(a(j:j))
       m=ichar(a(j+1:j+1))
       if(n.le.nine.and.n.ge.izero .or.n.eq.idot)goto 20
       if(n.eq.minus.and.(m.le.nine.and.m.ge.izero &
          & .or. m.eq.idot)) goto 20
    enddo
    readaa=0.d0
    return
    20  continue
    iend=j
    do i=j,nl
       n=ichar(a(i:i))
       if(n.le.nine.and.n.ge.izero) then
          idig=idig+1
          if (idig.gt.10) goto 60
          c1=c1*10+n-izero
       elseif(n.eq.minus.and.i.eq.j) then
          one=-1.d0
       elseif(n.eq.idot) then
          goto 40
       else
          goto 60
       endif
    enddo
    40  continue
    idig=0
    do ii=i+1,nl
       n=ichar(a(ii:ii))
       if(n.le.nine.and.n.ge.izero) then
          idig=idig+1
          if (idig.gt.10) goto 60
          c2=c2*10+n-izero
          x = x /10
       elseif(n.eq.minus.and.ii.eq.i) then
          x=-x
       else
          goto 60
       endif
    enddo
    !
    ! put the pieces together
    !
    60  continue
    readaa= one * ( c1 + c2 * x)
    do j=iend,nl
       n=ichar(a(j:j))
       iend2=j
       if(n.eq.ibl)return
       if(n.eq.nd .or. n.eq.ne) goto 57
    enddo
    return
    57  c1=0.0d0
    one=1.0d0
    do i=j+1,nl
       n=ichar(a(i:i))
       iend2=i
       if(n.eq.ibl)goto 70
       if(n.le.nine.and.n.ge.izero) c1=c1*10.0d0+n-izero
       if(n.eq.minus)one=-1.0d0
    enddo
    61  continue
    70  readaa=readaa*10**(one*c1)
    return
References xtb_mctc_accuracy::wp.
Referenced by readl().
readl()
subroutine readl (character(*) a1, dimension(*) x, n)
Definition at line 19 of file readl.f90.
    use xtb_mctc_accuracy, only : wp
    implicit real(wp) (a-h,o-z)
    character(*) a1
    dimension x(*)
    i=0
    is=1
    10  i=i+1
    x(i)=readaa(a1,is,ib,ie)
    if(ib.gt.0 .and. ie.gt.0) then
       is=ie
       goto 10
    endif
    n=i-1
    return
References readaa(), and xtb_mctc_accuracy::wp.
Referenced by countfix(), xtb_cqpath::cqpath_read_pathfile(), xtb_gfnff_param::gfnff_read_param(), rdfix(), rdsdf(), xtb_qmdff::rdsolvff(), rdtm(), rdxyz(), and xtb_extern_mopac::runmopac().