My Project: src/readl2.f90 File Reference
readl2.f90 File Reference
Functions/Subroutines
subroutine cutline (line, floats, strings)
subroutine checktype (field, num, str, ty)
Function/Subroutine Documentation
checktype()
subroutine checktype (character(len=*) field, real(wp) num, character(len=*) str, integer ty)
Definition at line 69 of file readl2.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    character(len=*) field,str
    real(wp) num
    integer i,e,ty
    logical is_num
    ty=99
    str=''
    is_num=.false.
    read(field,'(F10.5)',iostat=e)num !cast string on real and get error code; 0 means success.
    if(e.eq.0)is_num=.true.
    if(is_num)then
       if(index(field,'.').ne.0) then  !check for integer/real
          read(field,'(F30.16)')num
          ty=0
       else                       !if integer, add .0 to string; otherwise cast to real does not work
          str=trim(field)//'.0'
          read(str,'(F30.16)')num
          str=''
          ty=0
       endif
    else
       str=field
       ty=1
    endif
References true(), and xtb_mctc_accuracy::wp.
Referenced by cutline(), and readline().
cutline()
subroutine cutline (character(len=128) line, real(wp), dimension(*) floats, character(len=80), dimension(3) strings)
Definition at line 19 of file readl2.f90.
    use xtb_mctc_accuracy, only : wp
    implicit none
    real(wp) floats(*),num
    character(len=128) line,str,stmp
    character(len=80) strings(3)
    character(len=1) digit
    integer i,ty,cs,cf
    stmp=''
    cs=1
    cf=1
    strings(:)=''
    do i=1,len(trim(line))
       digit=line(i:i)
       if(digit.ne.' '.and.digit.ne.char(9)) then  !should exclude tabstops and blanks, 9 is ascii code for tab
          stmp=trim(stmp)//trim(digit)
       elseif(stmp.ne.'')then
          call checktype(stmp,num,str,ty)      !get type of string, 0=number, 1=character
          if(ty.eq.0) then
             floats(cf)=num
             cf=cf+1
          elseif(ty.eq.1) then
             strings(cs)=trim(str)
             cs=cs+1
          else
             write(*,*)'Problem in checktype, must abort'
             exit
          endif
          stmp=''
       endif
       if(i.eq.len(trim(line))) then  !special case: end of line
          call checktype(stmp,num,str,ty)
          if(ty.eq.0) then
             floats(cf)=num
             cf=cf+1
          elseif(ty.eq.1) then
             strings(cs)=trim(str)
             cs=cs+1
          else
             write(*,*)'Problem in checktype, must abort'
             exit
          endif
          stmp=''
       endif
    enddo
References checktype(), and xtb_mctc_accuracy::wp.