My Project: src/read_gfn_param.f90 File Reference
read_gfn_param.f90 File Reference
Modules
module xtb_readparam
Functions/Subroutines
subroutine xtb_readparam::readparam (env, iunit, globpar, xtbData, initialize)
subroutine read_info
subroutine read_globpar
subroutine gfn_globpar (key, val, globpar)
subroutine read_pairpar
subroutine read_elempar
subroutine gfn_elempar (key, val, iz)
logical function maingroup (i)
Function/Subroutine Documentation
gfn_elempar()
subroutine readparam::gfn_elempar (character(len=*), intent(in) key, character(len=*), intent(in) val, integer, intent(in) iz)
Definition at line 495 of file read_gfn_param.f90.
    use xtb_mctc_strings
    use xtb_readin
    implicit none
    character(len=*), intent(in) :: key, val
    integer, intent(in) :: iz
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    integer :: i, ii
    integer :: idum
    real(wp) :: ddum
    select case(key)
    case default
       call env%warning("Unknown key '"//key//"' for '"//flag//"Z'")
    case('ao')
       !print'(a,":",a)',key,val
       if (mod(len(val),2).eq.0) then
          nshell(iz) = len(val)/2
          do i = 1, nshell(iz)
             ii = 2*i-1
             !print*,i,ii,val(ii:ii),val(ii+1:ii+1)
             if (getvalue(env,val(ii:ii),idum)) then
                principalquantumnumber(i,iz) = idum
                select case(val(ii+1:ii+1))
                case('s'); angshell(i,iz) = 0
                case('p'); angshell(i,iz) = 1
                case('d'); angshell(i,iz) = 2
                case('f'); angshell(i,iz) = 3
                case('g'); angshell(i,iz) = 4
                case('S'); angshell(i,iz) = 0
                end select
             endif
          enddo
       endif
    case('lev')
       call parse(val,space,argv,narg)
       if (narg .eq. nshell(iz)) then
          do i = 1, nshell(iz)
             if (getvalue(env,trim(argv(i)),ddum)) selfenergy(i,iz) = ddum
          enddo
       endif
    case('exp')
       call parse(val,space,argv,narg)
       if (narg .eq. nshell(iz)) then
          do i = 1, nshell(iz)
             if (getvalue(env,trim(argv(i)),ddum)) slaterexponent(i,iz) = ddum
          enddo
       endif
    case('en');  if (getvalue(env,val,ddum)) electronegativity(iz)    = ddum
    case('gam'); if (getvalue(env,val,ddum)) atomichardness(iz)   = ddum
    case('xi');  if (getvalue(env,val,ddum)) eeqen(iz) = ddum
    case('alpg'); if (getvalue(env,val,ddum)) chargewidth(iz)   = ddum
    case('gam3');  if (getvalue(env,val,ddum)) thirdorderatom(iz)    = ddum * 0.1_wp
    case('kappa'); if (getvalue(env,val,ddum)) eeqkcn(iz)  = ddum
    case('cxb');   if (getvalue(env,val,ddum)) halogenbond(iz) = ddum * 0.1_wp
    case('kqat2'); if (getvalue(env,val,ddum)) kqat2(iz)   = ddum
    case('dpol');  if (getvalue(env,val,ddum)) dipkernel(iz)   = ddum * 0.01_wp
    case('qpol');  if (getvalue(env,val,ddum)) quadkernel(iz)   = ddum * 0.01_wp
    case('repa');  if (getvalue(env,val,ddum)) repalpha(iz)   = ddum
    case('repb');  if (getvalue(env,val,ddum)) repzeff(iz)   = ddum
    case('polys'); if (getvalue(env,val,ddum)) shellpoly(1,iz) = ddum
    case('polyp'); if (getvalue(env,val,ddum)) shellpoly(2,iz) = ddum
    case('polyd'); if (getvalue(env,val,ddum)) shellpoly(3,iz) = ddum
    case('polyf'); if (getvalue(env,val,ddum)) shellpoly(4,iz) = ddum
    case('lpars'); if (getvalue(env,val,ddum)) shellhardness(1,iz)  = ddum * 0.1_wp
    case('lparp'); if (getvalue(env,val,ddum)) shellhardness(2,iz)  = ddum * 0.1_wp
    case('lpard'); if (getvalue(env,val,ddum)) shellhardness(3,iz)  = ddum * 0.1_wp
    case('lparf'); if (getvalue(env,val,ddum)) shellhardness(4,iz)  = ddum * 0.1_wp
    case('kcns');  if (getvalue(env,val,ddum)) kcnat(0,iz) = ddum * 0.1_wp
    case('kcnp');  if (getvalue(env,val,ddum)) kcnat(1,iz) = ddum * 0.1_wp
    case('kcnd');  if (getvalue(env,val,ddum)) kcnat(2,iz) = ddum * 0.1_wp
    case('kqs');   if (getvalue(env,val,ddum)) kqat(0,iz)  = ddum
    case('kqp');   if (getvalue(env,val,ddum)) kqat(1,iz)  = ddum
    case('kqd');   if (getvalue(env,val,ddum)) kqat(2,iz)  = ddum
    end select
References xtb_mctc_strings::parse().
Referenced by read_elempar().
gfn_globpar()
subroutine readparam::gfn_globpar (character(len=*), intent(in) key, character(len=*), intent(in) val, type(txtbparameter), intent(inout) globpar)
Definition at line 364 of file read_gfn_param.f90.
    use xtb_readin, only : getvalue
    implicit none
    character(len=*), intent(in) :: key, val
    type(TxTBParameter), intent(inout) :: globpar
    real(wp) :: ddum
    select case(key)
    case default
       call env%warning("Unknown key '"//key//"' for '"//flag//"globpar'")
    case('kexp'); if (getvalue(env,val,ddum)) kexp = ddum
    case('kexplight'); if (getvalue(env,val,ddum)) kexplight = ddum
    case('ks'); if (getvalue(env,val,ddum)) globpar%kshell(0) = ddum
    case('kp'); if (getvalue(env,val,ddum)) globpar%kshell(1) = ddum
    case('kd'); if (getvalue(env,val,ddum)) globpar%kshell(2) = ddum
    case('kf'); if (getvalue(env,val,ddum)) globpar%kshell(3) = ddum
    case('ksp'); if (getvalue(env,val,ddum)) globpar%ksp = ddum
    case('ksd'); if (getvalue(env,val,ddum)) globpar%ksd = ddum
    case('kpd'); if (getvalue(env,val,ddum)) globpar%kpd = ddum
    case('kdiff'); if (getvalue(env,val,ddum)) globpar%kdiff = ddum
    case('kdiffa'); if (getvalue(env,val,ddum)) globpar%kdiffa = ddum
    case('kdiffb'); if (getvalue(env,val,ddum)) globpar%kdiffb = ddum
    case('ens'); if (getvalue(env,val,ddum)) globpar%enshell(0) = ddum
    case('enp'); if (getvalue(env,val,ddum)) globpar%enshell(1) = ddum
    case('end'); if (getvalue(env,val,ddum)) globpar%enshell(2) = ddum
    case('enf'); if (getvalue(env,val,ddum)) globpar%enshell(3) = ddum
    case('enscale'); if (getvalue(env,val,ddum)) globpar%enshell = ddum
    case('enscale4'); if (getvalue(env,val,ddum)) globpar%enscale4 = ddum
    case('renscale'); if (getvalue(env,val,ddum)) globpar%renscale = ddum
    case('cns'); if (getvalue(env,val,ddum)) globpar%cnshell(:, 0) = ddum
    case('cnp'); if (getvalue(env,val,ddum)) globpar%cnshell(:, 1) = ddum
    case('cnd'); if (getvalue(env,val,ddum)) globpar%cnshell(:, 2) = ddum
    case('cnf'); if (getvalue(env,val,ddum)) globpar%cnshell(:, 3) = ddum
    case('cnd1'); if (getvalue(env,val,ddum)) globpar%cnshell(1, 2) = ddum
    case('cnd2'); if (getvalue(env,val,ddum)) globpar%cnshell(2, 2) = ddum
    case('gam3s'); if (getvalue(env,val,ddum)) globpar%gam3shell(:, 0) = ddum
    case('gam3p'); if (getvalue(env,val,ddum)) globpar%gam3shell(:, 1) = ddum
    case('gam3d'); if (getvalue(env,val,ddum)) globpar%gam3shell(:, 2) = ddum
    case('gam3f'); if (getvalue(env,val,ddum)) globpar%gam3shell(:, 3) = ddum
    case('gam3d1'); if (getvalue(env,val,ddum)) globpar%gam3shell(1, 2) = ddum
    case('gam3d2'); if (getvalue(env,val,ddum)) globpar%gam3shell(2, 2) = ddum
    case('srbshift'); if (getvalue(env,val,ddum)) globpar%srbshift = ddum
    case('srbpre'); if (getvalue(env,val,ddum)) globpar%srbpre = ddum
    case('srbexp'); if (getvalue(env,val,ddum)) globpar%srbexp = ddum
    case('srbken'); if (getvalue(env,val,ddum)) globpar%srbken = ddum
    case('wllscal'); if (getvalue(env,val,ddum)) globpar%wllscal = ddum
    case('ipeashift'); if (getvalue(env,val,ddum)) globpar%ipeashift = ddum
    case('gscal'); if (getvalue(env,val,ddum)) globpar%gscal = ddum
    case('zcnf'); if (getvalue(env,val,ddum)) globpar%zcnf = ddum
    case('tscal'); if (getvalue(env,val,ddum)) globpar%tscal = ddum
    case('kcn'); if (getvalue(env,val,ddum)) globpar%kcn = ddum
    case('fpol'); if (getvalue(env,val,ddum)) globpar%fpol = ddum
    case('ken'); if (getvalue(env,val,ddum)) globpar%ken = ddum
    case('lshift'); if (getvalue(env,val,ddum)) globpar%lshift = ddum
    case('lshifta'); if (getvalue(env,val,ddum)) globpar%lshifta = ddum
    case('split'); if (getvalue(env,val,ddum)) globpar%split = ddum
    case('zqf'); if (getvalue(env,val,ddum)) globpar%zqf = ddum
    case('alphaj'); if (getvalue(env,val,ddum)) globpar%alphaj = ddum
    case('kexpo'); if (getvalue(env,val,ddum)) globpar%kexpo = ddum
    case('dispa'); if (getvalue(env,val,ddum)) globpar%dispa = ddum
    case('dispb'); if (getvalue(env,val,ddum)) globpar%dispb = ddum
    case('dispc'); if (getvalue(env,val,ddum)) globpar%dispc = ddum
    case('dispatm'); if (getvalue(env,val,ddum)) globpar%dispatm = ddum
    case('a1'); if (getvalue(env,val,ddum)) disp%a1 = ddum
    case('a2'); if (getvalue(env,val,ddum)) disp%a2 = ddum
    case('s6'); if (getvalue(env,val,ddum)) disp%s6 = ddum
    case('s8'); if (getvalue(env,val,ddum)) disp%s8 = ddum
    case('s9'); if (getvalue(env,val,ddum)) disp%s9 = ddum
    case('xbdamp'); if (getvalue(env,val,ddum)) globpar%xbdamp = ddum
    case('xbrad'); if (getvalue(env,val,ddum)) globpar%xbrad = ddum
    case('aesdmp3'); if (getvalue(env,val,ddum)) globpar%aesdmp3 = ddum
    case('aesdmp5'); if (getvalue(env,val,ddum)) globpar%aesdmp5 = ddum
    case('aesshift'); if (getvalue(env,val,ddum)) globpar%aesshift = ddum
    case('aesexp'); if (getvalue(env,val,ddum)) globpar%aesexp = ddum
    case('aesrmax'); if (getvalue(env,val,ddum)) globpar%aesrmax = ddum
    end select
Referenced by read_globpar().
maingroup()
logical function maingroup (integer i)
Definition at line 577 of file read_gfn_param.f90.
       integer i
       logical main_group(107)
       data main_group /&
      &  2*.true.,&                              ! H  - He
      &  8*.true.,&                              ! Li - Ne
      &  8*.true.,&                              ! Na - Ar
      &  2*.true., 9*.false., 7*.true.,&         ! K  - Kr
      &  2*.true., 9*.false., 7*.true.,&         ! Rb - Xe
      &  2*.true.,23*.false., 7*.true.,&         ! Cs - Rn
      & 21*.true.                               / ! Fr - Tv
       maingroup = main_group(i)
References true().
read_elempar()
subroutine readparam::read_elempar
Definition at line 466 of file read_gfn_param.f90.
    use xtb_mctc_strings
    use xtb_readin
    implicit none
    character(len=:), allocatable :: key, val
    integer :: iz, ie
    if (getvalue(env,line(4:5),iz)) then
       timestp(iz) = line(7:len_trim(line))
       do
          call getline(iunit,line,err)
          if (debug) print'("->",a)',line
          if (err.ne.0) exit
          if (index(line,flag).gt.0) exit
          ie = index(line,equal)
          if (line.eq.'') cycle ! skip empty lines
          if (ie.eq.0) cycle
          key = lowercase(trim(line(:ie-1)))
          val = trim(adjustl(line(ie+1:)))
          call gfn_elempar(key,val,iz)
       enddo
    else
       call getline(iunit,line,err)
    endif
References gfn_elempar(), and xtb_mctc_strings::lowercase().
Referenced by xtb_readparam::readparam().
read_globpar()
subroutine readparam::read_globpar
Definition at line 342 of file read_gfn_param.f90.
    implicit none
    character(len=:), allocatable :: key, val
    integer :: ie
    do
       call getline(iunit,line,err)
       if (debug) print'("->",a)',line
       if (err.ne.0) exit
       if (index(line,flag).gt.0) exit
       ie = index(line,space)
       if (line.eq.'') cycle ! skip empty lines
       if (ie.eq.0) cycle
       key = trim(line(:ie-1))
       val = trim(adjustl(line(ie+1:)))
       call gfn_globpar(key,val,globpar)
    enddo
References gfn_globpar().
Referenced by xtb_readparam::readparam().
read_info()
subroutine readparam::read_info
Definition at line 312 of file read_gfn_param.f90.
    use xtb_readin, only : getvalue
    character(len=:), allocatable :: key, val
    integer :: ie, idum
    do
       call getline(iunit,line,err)
       if (debug) print'("->",a)',line
       if (err.ne.0) exit
       if (index(line,flag).gt.0) exit
       ie = index(line,space)
       if (line.eq.'') cycle ! skip empty lines
       if (ie.eq.0) cycle
       key = trim(line(:ie-1))
       val = trim(adjustl(line(ie+1:)))
       select case(key)
       case default
          call env%warning("Unknown key '"//key//"' for '"//flag//"info'")
       case('level')
          if (getvalue(env,val,idum)) level = idum
       case('name')
          xtbdata%name = val
       case('doi')
          xtbdata%doi = val
       end select
    enddo
Referenced by xtb_readparam::readparam().
read_pairpar()
subroutine readparam::read_pairpar
Definition at line 441 of file read_gfn_param.f90.
    use xtb_mctc_strings
    use xtb_readin, only : getvalue
    implicit none
    integer  :: narg
    character(len=p_str_length),dimension(p_arg_length) :: argv
    integer  :: iAt,jAt
    real(wp) :: ddum
    do
       call getline(iunit,line,err)
       if (debug) print'("->",a)',line
       if (err.ne.0) exit
       if (index(line,flag).gt.0) exit
       call parse(line,space,argv,narg)
       if (narg .ne. 3) cycle
       if (getvalue(env,trim(argv(1)),iat) .and. &
          &getvalue(env,trim(argv(2)),jat) .and. &
          &getvalue(env,trim(argv(3)),ddum)) then
             kpair(iat,jat) = ddum
             kpair(jat,iat) = ddum
       endif
    enddo
References xtb_mctc_strings::parse().
Referenced by xtb_readparam::readparam().