My Project: src/gfnff/shortest_distance.f90 File Reference
shortest_distance.f90 File Reference
Functions/Subroutines
real *4 function shortest_distance (nspin, start, goal, neighbours, input_distances, visited, precessor)
Function/Subroutine Documentation
shortest_distance()
real*4 function shortest_distance (integer, intent(in) nspin, integer, intent(in) start, integer, intent(in) goal, integer, dimension(20,nspin), intent(in) neighbours, real*4, dimension(nspin*(nspin+1)/2), intent(in) input_distances, logical, dimension(nspin), intent(out) visited, integer, dimension(nspin), intent(out) precessor)
Definition at line 23 of file shortest_distance.f90.
     implicit none
     !Dummy Arguments:
     integer, intent(in) :: nspin
     integer, intent(in) :: start
     integer, intent(in) :: goal
     integer, intent(in) :: neighbours(20,nspin)
     real*4,  intent(in) :: input_distances(nspin*(nspin+1)/2)
     logical, intent(out):: visited(nspin)
     integer, intent(out):: precessor(nspin)
     integer lin
     !Stack:
     integer:: current
     integer:: neighbour
     integer:: i_neighbours
     real*4:: alt_dist
     real*4:: distance(nspin)
     !logical:: visited(nspin)
     precessor = 0
     distance = huge(distance)
     distance(start) = 0
     visited = .false.
     do while (all(visited) == .false.) !as long there are unvisited nodes
         current = minloc(distance,1, .not. visited)
         !Abort if Fragments are not connected:
         if (distance(current) == huge(distance)) then
             shortest_distance = huge(distance)
             return
         end if ! distance(current) == huge(distance)
         visited(current) = .true.
         if (current == goal) then
             shortest_distance = distance(goal)
             !route to target found
             do while (precessor(current) /= 0)
                 current = precessor(current)
             end do ! End loop: while precessor(current) /= 0
             exit
         else
             !loop over all neighbours of current atom
             do i_neighbours = 1, neighbours(20,current)
                 neighbour = neighbours(i_neighbours,current)
                 if (visited(neighbour) == .false.) then
                     !distanzupdate
                     alt_dist = distance(current) + input_distances(lin(current,neighbour))
                     if ((alt_dist < distance(neighbour))) then
                         distance(neighbour) = alt_dist
                         precessor(neighbour) = current
                     end if ! (alt_dist < distance(neighbour))
                 endif !(visited(neighbour))
             end do ! End Loop over  i_neighbours from 1 to all_Atoms(current)%n_neighbours
         endif
     end do ! End loop: while sum(visited) /= 0
         !initialize
     shortest_distance = distance(goal)
References lin(), neighbours(), shortest_distance(), and true().