My Project: forpy_mod::sequence Type Reference
forpy_mod::sequence Type Reference
Abstract type that represents sequence objects. Elements of a sequence can be accessed by an index.
Public Member Functions
generic, public len => sequence_len_int32
Get the length of the object (number of elements).
generic, public count => sequence_count_int32
generic, public index => sequence_index_int32
Get the first index of a value.
generic, public getitem => sequence_getitem_int32_object
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_int32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_int64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_complex_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_complex_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_logical
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_char_1d
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_chars
Get item at a certain index.
generic, public len => sequence_len_int64
Get the length of the object (number of elements).
generic, public count => sequence_count_int64
generic, public index => sequence_index_int64
Get the first index of a value.
generic, public getitem => sequence_getitem_int64_object
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_int32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_int64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_complex_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_complex_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_logical
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_char_1d
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_chars
Get item at a certain index.
procedure, public contains => sequence_contains
Checks if a given item is contained in the sequence.
Public Member Functions inherited from forpy_mod::object
procedure, public destroy => object_destroy
Call to allow for freeing of resources of this object.
procedure, public getattribute => object_getattribute
Get value of an attribute of this object.
procedure, public setattr => object_setattr
Set value of an attribute of this object.
procedure, public delattr => object_delattr
Delete an attribute of this object.
procedure, public get_c_ptr => object_get_c_ptr
Get c_ptr representation of this object. For development of Python extension modules.
Private Member Functions
procedure, private sequence_len_int32
procedure, private sequence_count_int32
procedure, private sequence_index_int32
procedure, private sequence_getitem_int32_object
procedure, private sequence_getitem_int32_int32
procedure, private sequence_getitem_int32_int64
procedure, private sequence_getitem_int32_real32
procedure, private sequence_getitem_int32_real64
procedure, private sequence_getitem_int32_complex_real32
procedure, private sequence_getitem_int32_complex_real64
procedure, private sequence_getitem_int32_logical
procedure, private sequence_getitem_int32_char_1d
procedure, private sequence_getitem_int32_chars
procedure, private sequence_len_int64
procedure, private sequence_count_int64
procedure, private sequence_index_int64
procedure, private sequence_getitem_int64_object
procedure, private sequence_getitem_int64_int32
procedure, private sequence_getitem_int64_int64
procedure, private sequence_getitem_int64_real32
procedure, private sequence_getitem_int64_real64
procedure, private sequence_getitem_int64_complex_real32
procedure, private sequence_getitem_int64_complex_real64
procedure, private sequence_getitem_int64_logical
procedure, private sequence_getitem_int64_char_1d
procedure, private sequence_getitem_int64_chars
Detailed Description
Abstract type that represents sequence objects. Elements of a sequence can be accessed by an index.
Definition at line 892 of file forpy_mod.F90.
Member Function/Subroutine Documentation
contains()
procedure, public forpy_mod::sequence::contains
Checks if a given item is contained in the sequence.
Definition at line 980 of file forpy_mod.F90.
count() [1/2]
generic, public forpy_mod::sequence::count
Definition at line 898 of file forpy_mod.F90.
References forpy_mod::sequence_count_int32().
count() [2/2]
generic, public forpy_mod::sequence::count
Definition at line 940 of file forpy_mod.F90.
References forpy_mod::sequence_count_int64().
getitem() [1/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 931 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_char_1d().
getitem() [2/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 934 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_chars().
getitem() [3/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 922 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_complex_real32().
getitem() [4/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 925 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_complex_real64().
getitem() [5/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 910 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_int32().
getitem() [6/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 913 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_int64().
getitem() [7/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 928 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_logical().
getitem() [8/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 907 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_object().
getitem() [9/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 916 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_real32().
getitem() [10/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 919 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int32_real64().
getitem() [11/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 973 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_char_1d().
getitem() [12/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 976 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_chars().
getitem() [13/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 964 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_complex_real32().
getitem() [14/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 967 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_complex_real64().
getitem() [15/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 952 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_int32().
getitem() [16/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 955 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_int64().
getitem() [17/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 970 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_logical().
getitem() [18/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 949 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_object().
getitem() [19/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 958 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_real32().
getitem() [20/20]
generic, public forpy_mod::sequence::getitem
Get item at a certain index.
Definition at line 961 of file forpy_mod.F90.
References forpy_mod::sequence_getitem_int64_real64().
index() [1/2]
generic, public forpy_mod::sequence::index
Get the first index of a value.
Definition at line 903 of file forpy_mod.F90.
References forpy_mod::sequence_index_int32().
index() [2/2]
generic, public forpy_mod::sequence::index
Get the first index of a value.
Definition at line 945 of file forpy_mod.F90.
References forpy_mod::sequence_index_int64().
len() [1/2]
generic, public forpy_mod::sequence::len
Get the length of the object (number of elements).
Definition at line 896 of file forpy_mod.F90.
References forpy_mod::sequence_len_int32().
len() [2/2]
generic, public forpy_mod::sequence::len
Get the length of the object (number of elements).
Definition at line 938 of file forpy_mod.F90.
References forpy_mod::sequence_len_int64().
sequence_count_int32()
procedure, private forpy_mod::sequence::sequence_count_int32 private
Definition at line 897 of file forpy_mod.F90.
sequence_count_int64()
procedure, private forpy_mod::sequence::sequence_count_int64 private
Definition at line 939 of file forpy_mod.F90.
sequence_getitem_int32_char_1d()
procedure, private forpy_mod::sequence::sequence_getitem_int32_char_1d private
Definition at line 929 of file forpy_mod.F90.
sequence_getitem_int32_chars()
procedure, private forpy_mod::sequence::sequence_getitem_int32_chars private
Definition at line 932 of file forpy_mod.F90.
sequence_getitem_int32_complex_real32()
procedure, private forpy_mod::sequence::sequence_getitem_int32_complex_real32 private
Definition at line 920 of file forpy_mod.F90.
sequence_getitem_int32_complex_real64()
procedure, private forpy_mod::sequence::sequence_getitem_int32_complex_real64 private
Definition at line 923 of file forpy_mod.F90.
sequence_getitem_int32_int32()
procedure, private forpy_mod::sequence::sequence_getitem_int32_int32 private
Definition at line 908 of file forpy_mod.F90.
sequence_getitem_int32_int64()
procedure, private forpy_mod::sequence::sequence_getitem_int32_int64 private
Definition at line 911 of file forpy_mod.F90.
sequence_getitem_int32_logical()
procedure, private forpy_mod::sequence::sequence_getitem_int32_logical private
Definition at line 926 of file forpy_mod.F90.
sequence_getitem_int32_object()
procedure, private forpy_mod::sequence::sequence_getitem_int32_object private
Definition at line 905 of file forpy_mod.F90.
sequence_getitem_int32_real32()
procedure, private forpy_mod::sequence::sequence_getitem_int32_real32 private
Definition at line 914 of file forpy_mod.F90.
sequence_getitem_int32_real64()
procedure, private forpy_mod::sequence::sequence_getitem_int32_real64 private
Definition at line 917 of file forpy_mod.F90.
sequence_getitem_int64_char_1d()
procedure, private forpy_mod::sequence::sequence_getitem_int64_char_1d private
Definition at line 971 of file forpy_mod.F90.
sequence_getitem_int64_chars()
procedure, private forpy_mod::sequence::sequence_getitem_int64_chars private
Definition at line 974 of file forpy_mod.F90.
sequence_getitem_int64_complex_real32()
procedure, private forpy_mod::sequence::sequence_getitem_int64_complex_real32 private
Definition at line 962 of file forpy_mod.F90.
sequence_getitem_int64_complex_real64()
procedure, private forpy_mod::sequence::sequence_getitem_int64_complex_real64 private
Definition at line 965 of file forpy_mod.F90.
sequence_getitem_int64_int32()
procedure, private forpy_mod::sequence::sequence_getitem_int64_int32 private
Definition at line 950 of file forpy_mod.F90.
sequence_getitem_int64_int64()
procedure, private forpy_mod::sequence::sequence_getitem_int64_int64 private
Definition at line 953 of file forpy_mod.F90.
sequence_getitem_int64_logical()
procedure, private forpy_mod::sequence::sequence_getitem_int64_logical private
Definition at line 968 of file forpy_mod.F90.
sequence_getitem_int64_object()
procedure, private forpy_mod::sequence::sequence_getitem_int64_object private
Definition at line 947 of file forpy_mod.F90.
sequence_getitem_int64_real32()
procedure, private forpy_mod::sequence::sequence_getitem_int64_real32 private
Definition at line 956 of file forpy_mod.F90.
sequence_getitem_int64_real64()
procedure, private forpy_mod::sequence::sequence_getitem_int64_real64 private
Definition at line 959 of file forpy_mod.F90.
sequence_index_int32()
procedure, private forpy_mod::sequence::sequence_index_int32 private
Definition at line 901 of file forpy_mod.F90.
sequence_index_int64()
procedure, private forpy_mod::sequence::sequence_index_int64 private
Definition at line 943 of file forpy_mod.F90.
sequence_len_int32()
procedure, private forpy_mod::sequence::sequence_len_int32 private
Definition at line 894 of file forpy_mod.F90.
sequence_len_int64()
procedure, private forpy_mod::sequence::sequence_len_int64 private
Definition at line 936 of file forpy_mod.F90.
The documentation for this type was generated from the following file:
prob_files/forpy_mod.F90