My Project: forpy_mod::list Type Reference
forpy_mod::list Type Reference
Type that corresponds to a Python list.
Public Member Functions
generic, public append => list_append_object
Append an item at the end of a list.
procedure, public copy => list_copy
Creates a copy of a list.
procedure, public sort => list_sort
Sorts the list.
procedure, public reverse => list_reverse
Reverses a list.
procedure, public add => list_add
Concatenates another list at the end of a list.
generic, public insert => list_insert_int32
Inserts item at given index.
generic, public delitem => list_delitem_int32
Deletes item at given index from list.
generic, public insert => list_insert_int64
Inserts item at given index.
generic, public delitem => list_delitem_int64
Deletes item at given index from list.
generic, public append => list_append_int32
Append an item at the end of a list.
generic, public append => list_append_int64
Append an item at the end of a list.
generic, public append => list_append_real32
Append an item at the end of a list.
generic, public append => list_append_real64
Append an item at the end of a list.
generic, public append => list_append_complex_real32
Append an item at the end of a list.
generic, public append => list_append_complex_real64
Append an item at the end of a list.
generic, public append => list_append_logical
Append an item at the end of a list.
generic, public append => list_append_char_1d
Append an item at the end of a list.
generic, public append => list_append_chars
Append an item at the end of a list.
Public Member Functions inherited from forpy_mod::mutablesequence
generic, public setitem => mutablesequence_setitem_int32_object
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_int32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_int64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_real32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_real64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_complex_real32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_complex_real64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_logical
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_char_1d
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_chars
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_object
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_int32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_int64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_real32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_real64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_complex_real32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_complex_real64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_logical
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_char_1d
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_chars
Set an item at a given index.
Public Member Functions inherited from forpy_mod::sequence
generic, public len => sequence_len_int32
Get the length of the object (number of elements).
generic, public count => sequence_count_int32
generic, public index => sequence_index_int32
Get the first index of a value.
generic, public getitem => sequence_getitem_int32_object
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_int32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_int64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_complex_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_complex_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_logical
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_char_1d
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_chars
Get item at a certain index.
generic, public len => sequence_len_int64
Get the length of the object (number of elements).
generic, public count => sequence_count_int64
generic, public index => sequence_index_int64
Get the first index of a value.
generic, public getitem => sequence_getitem_int64_object
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_int32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_int64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_complex_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_complex_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_logical
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_char_1d
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_chars
Get item at a certain index.
procedure, public contains => sequence_contains
Checks if a given item is contained in the sequence.
Public Member Functions inherited from forpy_mod::object
procedure, public destroy => object_destroy
Call to allow for freeing of resources of this object.
procedure, public getattribute => object_getattribute
Get value of an attribute of this object.
procedure, public setattr => object_setattr
Set value of an attribute of this object.
procedure, public delattr => object_delattr
Delete an attribute of this object.
procedure, public get_c_ptr => object_get_c_ptr
Get c_ptr representation of this object. For development of Python extension modules.
Private Member Functions
procedure, private list_append_object
procedure, private list_insert_int32
procedure, private list_delitem_int32
procedure, private list_insert_int64
procedure, private list_delitem_int64
procedure, private list_append_int32
procedure, private list_append_int64
procedure, private list_append_real32
procedure, private list_append_real64
procedure, private list_append_complex_real32
procedure, private list_append_complex_real64
procedure, private list_append_logical
procedure, private list_append_char_1d
procedure, private list_append_chars
Detailed Description
Type that corresponds to a Python list.
Definition at line 1054 of file forpy_mod.F90.
Member Function/Subroutine Documentation
add()
procedure, public forpy_mod::list::add
Concatenates another list at the end of a list.
Definition at line 1067 of file forpy_mod.F90.
append() [1/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1105 of file forpy_mod.F90.
References forpy_mod::list_append_char_1d().
append() [2/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1108 of file forpy_mod.F90.
References forpy_mod::list_append_chars().
append() [3/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1096 of file forpy_mod.F90.
References forpy_mod::list_append_complex_real32().
append() [4/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1099 of file forpy_mod.F90.
References forpy_mod::list_append_complex_real64().
append() [5/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1084 of file forpy_mod.F90.
References forpy_mod::list_append_int32().
append() [6/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1087 of file forpy_mod.F90.
References forpy_mod::list_append_int64().
append() [7/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1102 of file forpy_mod.F90.
References forpy_mod::list_append_logical().
append() [8/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1058 of file forpy_mod.F90.
References forpy_mod::list_append_object().
append() [9/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1090 of file forpy_mod.F90.
References forpy_mod::list_append_real32().
append() [10/10]
generic, public forpy_mod::list::append
Append an item at the end of a list.
Definition at line 1093 of file forpy_mod.F90.
References forpy_mod::list_append_real64().
copy()
procedure, public forpy_mod::list::copy
Creates a copy of a list.
Definition at line 1061 of file forpy_mod.F90.
delitem() [1/2]
generic, public forpy_mod::list::delitem
Deletes item at given index from list.
Definition at line 1074 of file forpy_mod.F90.
References forpy_mod::list_delitem_int32().
delitem() [2/2]
generic, public forpy_mod::list::delitem
Deletes item at given index from list.
Definition at line 1080 of file forpy_mod.F90.
References forpy_mod::list_delitem_int64().
insert() [1/2]
generic, public forpy_mod::list::insert
Inserts item at given index.
Definition at line 1071 of file forpy_mod.F90.
References forpy_mod::list_insert_int32().
insert() [2/2]
generic, public forpy_mod::list::insert
Inserts item at given index.
Definition at line 1077 of file forpy_mod.F90.
References forpy_mod::list_insert_int64().
list_append_char_1d()
procedure, private forpy_mod::list::list_append_char_1d private
Definition at line 1103 of file forpy_mod.F90.
list_append_chars()
procedure, private forpy_mod::list::list_append_chars private
Definition at line 1106 of file forpy_mod.F90.
list_append_complex_real32()
procedure, private forpy_mod::list::list_append_complex_real32 private
Definition at line 1094 of file forpy_mod.F90.
list_append_complex_real64()
procedure, private forpy_mod::list::list_append_complex_real64 private
Definition at line 1097 of file forpy_mod.F90.
list_append_int32()
procedure, private forpy_mod::list::list_append_int32 private
Definition at line 1082 of file forpy_mod.F90.
list_append_int64()
procedure, private forpy_mod::list::list_append_int64 private
Definition at line 1085 of file forpy_mod.F90.
list_append_logical()
procedure, private forpy_mod::list::list_append_logical private
Definition at line 1100 of file forpy_mod.F90.
list_append_object()
procedure, private forpy_mod::list::list_append_object private
Definition at line 1056 of file forpy_mod.F90.
list_append_real32()
procedure, private forpy_mod::list::list_append_real32 private
Definition at line 1088 of file forpy_mod.F90.
list_append_real64()
procedure, private forpy_mod::list::list_append_real64 private
Definition at line 1091 of file forpy_mod.F90.
list_delitem_int32()
procedure, private forpy_mod::list::list_delitem_int32 private
Definition at line 1072 of file forpy_mod.F90.
list_delitem_int64()
procedure, private forpy_mod::list::list_delitem_int64 private
Definition at line 1078 of file forpy_mod.F90.
list_insert_int32()
procedure, private forpy_mod::list::list_insert_int32 private
Definition at line 1069 of file forpy_mod.F90.
list_insert_int64()
procedure, private forpy_mod::list::list_insert_int64 private
Definition at line 1075 of file forpy_mod.F90.
reverse()
procedure, public forpy_mod::list::reverse
Reverses a list.
Definition at line 1065 of file forpy_mod.F90.
sort()
procedure, public forpy_mod::list::sort
Sorts the list.
Definition at line 1063 of file forpy_mod.F90.
The documentation for this type was generated from the following file:
prob_files/forpy_mod.F90