My Project: xtb_type_molecule::tmolecule Interface Reference
xtb_type_molecule::tmolecule Interface Reference
Molecular structure information.
Private Member Functions
procedure allocate => allocate_molecule
procedure deallocate => deallocate_molecule
procedure calculate_distances => mol_calculate_distances
procedure set_nuclear_charge => mol_set_nuclear_charge
procedure set_atomic_masses => mol_set_atomic_masses
procedure update
procedure wrap_back
procedure center_of_geometry
procedure center_of_mass
procedure shift_to_center_of_geometry
procedure shift_to_center_of_mass
procedure moments_of_inertia
procedure align_to_principal_axes
type(tmolecule) function new_molecule_api (n, at, xyz, chrg, uhf, lattice, pbc)
Constructor for the molecular structure type, compatible with C input.
Private Attributes
integer n = 0
Number of atoms.
integer nid = 0
Number of unique species.
real(wp) chrg = 0.0_wp
Total charge.
integer uhf = 0
Number of unpaired electrons.
logical, dimension(3) pbc = .false.
Periodic dimensions.
integer npbc = 0
Periodicity of system.
integer boundarycondition = boundaryCondition%cluster
Boundary condition for this structure.
character(len=symbollength), dimension(:), allocatable sym
Element symbols.
integer, dimension(:), allocatable at
Ordinal numbers.
integer, dimension(:), allocatable id
Chemical identity.
real(wp), dimension(:,:), allocatable xyz
Cartesian coordinates in bohr.
real(wp), dimension(:,:), allocatable abc
Fractional coordinates.
real(wp), dimension(:,:), allocatable dist
Interatomic distances.
real(wp), dimension(:), allocatable atmass
Atomic masses in amu.
real(wp), dimension(:), allocatable z
Nuclear charges.
real(wp), dimension(:), allocatable cn
Coordination number.
real(wp), dimension(6) cellpar = 0.0_wp
Cell parameters.
real(wp), dimension(3, 3) lattice = 0.0_wp
Direct lattice parameters.
real(wp), dimension(3, 3) rec_lat = 0.0_wp
Reciprocal lattice parameters.
real(wp) volume = 0.0_wp
Volume of unit cell.
type(tb_wsc) wsc
Wigner–Seitz cell.
integer ftype = 0
File type of the input.
character(len=:), allocatable name
type(ttopology) bonds
type(tfragments) frag
type(pdb_data), dimension(:), allocatable pdb
PDB specific information about residues and chains.
type(sdf_data), dimension(:), allocatable sdf
SDF specific information about atom types.
type(vasp_info) vasp = vasp_info()
VASP specific information about input type.
type(turbo_info) turbo = turbo_info()
Turbomole specific information about input type.
type(struc_info) struc = struc_info()
Specific information about input structure.
type(tb_buffer) info
Raw input buffer.
Detailed Description
Molecular structure information.
Definition at line 52 of file molecule.f90.
Member Function/Subroutine Documentation
align_to_principal_axes()
procedure xtb_type_molecule::tmolecule::align_to_principal_axes private
Definition at line 170 of file molecule.f90.
allocate()
procedure xtb_type_molecule::tmolecule::allocate private
Definition at line 146 of file molecule.f90.
calculate_distances()
procedure xtb_type_molecule::tmolecule::calculate_distances private
Definition at line 150 of file molecule.f90.
center_of_geometry()
procedure xtb_type_molecule::tmolecule::center_of_geometry private
Definition at line 160 of file molecule.f90.
center_of_mass()
procedure xtb_type_molecule::tmolecule::center_of_mass private
Definition at line 162 of file molecule.f90.
deallocate()
procedure xtb_type_molecule::tmolecule::deallocate private
Definition at line 148 of file molecule.f90.
moments_of_inertia()
procedure xtb_type_molecule::tmolecule::moments_of_inertia private
Definition at line 168 of file molecule.f90.
new_molecule_api()
type(tmolecule) function xtb_type_molecule::tmolecule::new_molecule_api (integer(c_int), intent(in) n, integer(c_int), dimension(n), intent(in) at, real(c_double), dimension(3, n), intent(in) xyz, real(c_double), intent(in), optional, target chrg, integer(c_int), intent(in), optional, target uhf, real(c_double), dimension(3, 3), intent(in), optional, target lattice, logical(c_bool), dimension(3), intent(in), optional, target pbc) private
Constructor for the molecular structure type, compatible with C input.
Definition at line 323 of file molecule.f90.
    use iso_c_binding
    use xtb_mctc_symbols, only : tosymbol
    integer(c_int), intent(in) :: n
    integer(c_int), intent(in) :: at(n)
    real(c_double), intent(in) :: xyz(3, n)
    real(c_double), intent(in), target, optional :: chrg
    integer(c_int), intent(in), target, optional :: uhf
    real(c_double), intent(in), target, optional :: lattice(3, 3)
    logical(c_bool), intent(in), target, optional :: pbc(3)
    integer :: i
    call mol%allocate(n)
    if (c_associated(c_loc(lattice))) then
       mol%lattice = lattice
    else
       mol%lattice = 0.0_wp
    end if
    if (c_associated(c_loc(pbc))) then
       mol%pbc = pbc
       mol%npbc = count(pbc)
       if (any(pbc)) then
          mol%boundaryCondition = boundarycondition%pbc3d
       else
          mol%boundaryCondition = boundarycondition%cluster
       end if
    else
       if (c_associated(c_loc(lattice))) then
          mol%boundaryCondition = boundarycondition%pbc3d
          mol%pbc = .true.
          mol%npbc = 3
       else
          mol%boundaryCondition = boundarycondition%cluster
          mol%pbc = .false.
          mol%npbc = 0
       end if
    end if
    mol%at = at
    do i = 1, n
       mol%sym(i) = tosymbol(at(i))
    end do
    call getidentity(mol%nId, mol%id, mol%at)
    mol%xyz = xyz
    if (c_associated(c_loc(chrg))) then
       mol%chrg = chrg
    else
       mol%chrg = 0
    end if
    if (c_associated(c_loc(uhf))) then
       mol%uhf = uhf
    else
       mol%uhf = 0
    end if
    call mol%set_nuclear_charge
    call mol%set_atomic_masses
    call mol%update
    call generate_wsc(mol, mol%wsc)
References xtb_mctc_boundaryconditions::boundarycondition, generate_wsc(), xtb_mctc_symbols::tosymbol(), and true().
set_atomic_masses()
procedure xtb_type_molecule::tmolecule::set_atomic_masses private
Definition at line 154 of file molecule.f90.
set_nuclear_charge()
procedure xtb_type_molecule::tmolecule::set_nuclear_charge private
Definition at line 152 of file molecule.f90.
shift_to_center_of_geometry()
procedure xtb_type_molecule::tmolecule::shift_to_center_of_geometry private
Definition at line 164 of file molecule.f90.
shift_to_center_of_mass()
procedure xtb_type_molecule::tmolecule::shift_to_center_of_mass private
Definition at line 166 of file molecule.f90.
update()
procedure xtb_type_molecule::tmolecule::update private
Definition at line 156 of file molecule.f90.
wrap_back()
procedure xtb_type_molecule::tmolecule::wrap_back private
Definition at line 158 of file molecule.f90.
Member Data Documentation
abc
real(wp), dimension(:,:), allocatable xtb_type_molecule::tmolecule::abc private
Fractional coordinates.
Definition at line 88 of file molecule.f90.
       real(wp),allocatable :: abc(:,:)
at
integer, dimension(:), allocatable xtb_type_molecule::tmolecule::at private
Ordinal numbers.
Definition at line 79 of file molecule.f90.
       integer, allocatable :: at(:)
atmass
real(wp), dimension(:), allocatable xtb_type_molecule::tmolecule::atmass private
Atomic masses in amu.
Definition at line 94 of file molecule.f90.
       real(wp),allocatable :: atmass(:)
bonds
type(ttopology) xtb_type_molecule::tmolecule::bonds private
Definition at line 122 of file molecule.f90.
       type(TTopology) :: bonds
boundarycondition
integer xtb_type_molecule::tmolecule::boundarycondition = boundaryCondition%cluster private
Boundary condition for this structure.
Definition at line 73 of file molecule.f90.
       integer  :: boundaryCondition = boundarycondition%cluster
cellpar
real(wp), dimension(6) xtb_type_molecule::tmolecule::cellpar = 0.0_wp private
Cell parameters.
Definition at line 103 of file molecule.f90.
       real(wp) :: cellpar(6) = 0.0_wp
chrg
real(wp) xtb_type_molecule::tmolecule::chrg = 0.0_wp private
Total charge.
Definition at line 61 of file molecule.f90.
       real(wp) :: chrg = 0.0_wp
cn
real(wp), dimension(:), allocatable xtb_type_molecule::tmolecule::cn private
Coordination number.
Definition at line 100 of file molecule.f90.
       real(wp),allocatable :: cn(:)
dist
real(wp), dimension(:,:), allocatable xtb_type_molecule::tmolecule::dist private
Interatomic distances.
Definition at line 91 of file molecule.f90.
       real(wp),allocatable :: dist(:,:)
frag
type(tfragments) xtb_type_molecule::tmolecule::frag private
Definition at line 124 of file molecule.f90.
       type(TFragments) :: frag
ftype
integer xtb_type_molecule::tmolecule::ftype = 0 private
File type of the input.
Definition at line 118 of file molecule.f90.
       integer  :: ftype = 0
id
integer, dimension(:), allocatable xtb_type_molecule::tmolecule::id private
Chemical identity.
Definition at line 82 of file molecule.f90.
       integer, allocatable :: id(:)
info
type(tb_buffer) xtb_type_molecule::tmolecule::info private
Raw input buffer.
Definition at line 142 of file molecule.f90.
       type(tb_buffer) :: info
lattice
real(wp), dimension(3,3) xtb_type_molecule::tmolecule::lattice = 0.0_wp private
Direct lattice parameters.
Definition at line 106 of file molecule.f90.
       real(wp) :: lattice(3,3) = 0.0_wp
n
integer xtb_type_molecule::tmolecule::n = 0 private
Number of atoms.
Definition at line 55 of file molecule.f90.
       integer  :: n = 0
name
character(len=:), allocatable xtb_type_molecule::tmolecule::name private
Definition at line 120 of file molecule.f90.
       character(len=:), allocatable :: name
nid
integer xtb_type_molecule::tmolecule::nid = 0 private
Number of unique species.
Definition at line 58 of file molecule.f90.
       integer  :: nId = 0
npbc
integer xtb_type_molecule::tmolecule::npbc = 0 private
Periodicity of system.
Definition at line 70 of file molecule.f90.
       integer  :: npbc = 0
pbc
logical, dimension(3) xtb_type_molecule::tmolecule::pbc = .false. private
Periodic dimensions.
Definition at line 67 of file molecule.f90.
       logical  :: pbc(3) = .false.
pdb
type(pdb_data), dimension(:), allocatable xtb_type_molecule::tmolecule::pdb private
PDB specific information about residues and chains.
Definition at line 127 of file molecule.f90.
       type(pdb_data), allocatable :: pdb(:)
rec_lat
real(wp), dimension(3,3) xtb_type_molecule::tmolecule::rec_lat = 0.0_wp private
Reciprocal lattice parameters.
Definition at line 109 of file molecule.f90.
       real(wp) :: rec_lat(3,3) = 0.0_wp
sdf
type(sdf_data), dimension(:), allocatable xtb_type_molecule::tmolecule::sdf private
SDF specific information about atom types.
Definition at line 130 of file molecule.f90.
       type(sdf_data), allocatable :: sdf(:)
struc
type(struc_info) xtb_type_molecule::tmolecule::struc = struc_info() private
Specific information about input structure.
Definition at line 139 of file molecule.f90.
       type(struc_info) :: struc = struc_info()
sym
character(len=symbollength), dimension(:), allocatable xtb_type_molecule::tmolecule::sym private
Element symbols.
Definition at line 76 of file molecule.f90.
       character(len=symbolLength), allocatable :: sym(:)
turbo
type(turbo_info) xtb_type_molecule::tmolecule::turbo = turbo_info() private
Turbomole specific information about input type.
Definition at line 136 of file molecule.f90.
       type(turbo_info) :: turbo = turbo_info()
uhf
integer xtb_type_molecule::tmolecule::uhf = 0 private
Number of unpaired electrons.
Definition at line 64 of file molecule.f90.
       integer  :: uhf = 0
vasp
type(vasp_info) xtb_type_molecule::tmolecule::vasp = vasp_info() private
VASP specific information about input type.
Definition at line 133 of file molecule.f90.
       type(vasp_info) :: vasp = vasp_info()
volume
real(wp) xtb_type_molecule::tmolecule::volume = 0.0_wp private
Volume of unit cell.
Definition at line 112 of file molecule.f90.
       real(wp) :: volume = 0.0_wp
wsc
type(tb_wsc) xtb_type_molecule::tmolecule::wsc private
Wigner–Seitz cell.
Definition at line 115 of file molecule.f90.
       type(tb_wsc) :: wsc
xyz
real(wp), dimension(:,:), allocatable xtb_type_molecule::tmolecule::xyz private
Cartesian coordinates in bohr.
Definition at line 85 of file molecule.f90.
       real(wp),allocatable :: xyz(:,:)
z
real(wp), dimension(:), allocatable xtb_type_molecule::tmolecule::z private
Nuclear charges.
Definition at line 97 of file molecule.f90.
       real(wp),allocatable :: z(:)
The documentation for this interface was generated from the following file:
src/type/molecule.f90