My Project: xtb_type_atomlist::tatomlist Interface Reference
xtb_type_atomlist::tatomlist Interface Reference
Private Member Functions
generic new => from_integers, from_logicals, from_string, from_defaults
procedure, non_overridable from_defaults
procedure, private from_integers => atomlist_assign_integers
procedure, private from_logicals => atomlist_assign_logicals
procedure, private from_string => atomlist_assign_string
procedure, pass(self) to_string => string_assign_atomlist
procedure, pass(self) to_list => list_assign_atomlist
procedure switch_truth => atomlist_switch_truth
procedure set_truth => atomlist_set_truth
procedure get_truth => atomlist_get_truth
procedure get_error => atomlist_get_error
generic remove => remove_integer, remove_integers, remove_logicals
procedure, private remove_integer => atomlist_remove_integer
procedure, private remove_integers => atomlist_remove_integers
procedure, private remove_logicals => atomlist_remove_logicals
generic add => add_integer, add_integers, add_logicals, add_string
procedure, private add_integer => atomlist_add_integer
procedure, private add_integers => atomlist_add_integers
procedure, private add_logicals => atomlist_add_logicals
procedure, private add_string => atomlist_assign_string
procedure, private parse => atomlist_parse_string
procedure resize => atomlist_resize
generic gather => gather_int, gather_real, gather_real_2d
procedure, private gather_int => atomlist_gather_int
procedure, private gather_real => atomlist_gather_real
procedure, private gather_real_2d => atomlist_gather_real_2d
generic scatter => scatter_real_2d
procedure, private scatter_real_2d => atomlist_scatter_real_2d
procedure destroy => atomlist_destroy
final atomlist_finalizer
pure type(tatomlist) function atomlist_from_logicals (list, truth, delimiter, skip)
pure type(tatomlist) function atomlist_from_integers (list, truth, delimiter, skip)
pure type(tatomlist) function atomlist_from_string (list, truth, delimiter, skip)
Private Attributes
logical, dimension(:), allocatable list
logical default = .false.
character delimiter = p_delimiter
character skip = p_skip
logical error = .false.
Detailed Description
Definition at line 29 of file atomlist.f90.
Member Function/Subroutine Documentation
add()
generic xtb_type_atomlist::tatomlist::add private
Definition at line 52 of file atomlist.f90.
add_integer()
procedure, private xtb_type_atomlist::tatomlist::add_integer private
Definition at line 53 of file atomlist.f90.
add_integers()
procedure, private xtb_type_atomlist::tatomlist::add_integers private
Definition at line 54 of file atomlist.f90.
add_logicals()
procedure, private xtb_type_atomlist::tatomlist::add_logicals private
Definition at line 55 of file atomlist.f90.
add_string()
procedure, private xtb_type_atomlist::tatomlist::add_string private
Definition at line 56 of file atomlist.f90.
atomlist_finalizer()
final xtb_type_atomlist::tatomlist::atomlist_finalizer final private
Definition at line 66 of file atomlist.f90.
References xtb_type_atomlist::atomlist_finalizer(), xtb_type_atomlist::atomlist_from_integers(), xtb_type_atomlist::atomlist_from_logicals(), and xtb_type_atomlist::atomlist_from_string().
atomlist_from_integers()
pure type(tatomlist) function xtb_type_atomlist::tatomlist::atomlist_from_integers (integer, dimension(:), intent(in) list, logical, intent(in), optional truth, character, intent(in), optional delimiter, character, intent(in), optional skip) private
Definition at line 104 of file atomlist.f90.
    integer, intent(in) :: list(:)
    logical, intent(in), optional :: truth
    character, intent(in), optional :: delimiter, skip
    type(TAtomList) :: self
    if (present(truth)) self%default = .not.truth
    if (present(delimiter)) self%delimiter = delimiter
    if (present(skip)) self%skip = skip
    call self%new(list)
References list().
atomlist_from_logicals()
pure type(tatomlist) function xtb_type_atomlist::tatomlist::atomlist_from_logicals (logical, dimension(:), intent(in) list, logical, intent(in), optional truth, character, intent(in), optional delimiter, character, intent(in), optional skip) private
Definition at line 93 of file atomlist.f90.
    logical, intent(in) :: list(:)
    logical, intent(in), optional :: truth
    character, intent(in), optional :: delimiter, skip
    type(TAtomList) :: self
    if (present(truth)) self%default = .not.truth
    if (present(delimiter)) self%delimiter = delimiter
    if (present(skip)) self%skip = skip
    call self%new(list)
References list().
atomlist_from_string()
pure type(tatomlist) function xtb_type_atomlist::tatomlist::atomlist_from_string (character(len=*), intent(in) list, logical, intent(in), optional truth, character, intent(in), optional delimiter, character, intent(in), optional skip) private
Definition at line 115 of file atomlist.f90.
    character(len=*), intent(in) :: list
    logical, intent(in), optional :: truth
    character, intent(in), optional :: delimiter, skip
    type(TAtomList) :: self
    if (present(truth)) self%default = .not.truth
    if (present(delimiter)) self%delimiter = delimiter
    if (present(skip)) self%skip = skip
    call self%new(list)
References list().
destroy()
procedure xtb_type_atomlist::tatomlist::destroy private
Definition at line 65 of file atomlist.f90.
from_defaults()
procedure, non_overridable xtb_type_atomlist::tatomlist::from_defaults private
Definition at line 38 of file atomlist.f90.
from_integers()
procedure, private xtb_type_atomlist::tatomlist::from_integers private
Definition at line 39 of file atomlist.f90.
from_logicals()
procedure, private xtb_type_atomlist::tatomlist::from_logicals private
Definition at line 40 of file atomlist.f90.
from_string()
procedure, private xtb_type_atomlist::tatomlist::from_string private
Definition at line 41 of file atomlist.f90.
gather()
generic xtb_type_atomlist::tatomlist::gather private
Definition at line 59 of file atomlist.f90.
gather_int()
procedure, private xtb_type_atomlist::tatomlist::gather_int private
Definition at line 60 of file atomlist.f90.
gather_real()
procedure, private xtb_type_atomlist::tatomlist::gather_real private
Definition at line 61 of file atomlist.f90.
gather_real_2d()
procedure, private xtb_type_atomlist::tatomlist::gather_real_2d private
Definition at line 62 of file atomlist.f90.
get_error()
procedure xtb_type_atomlist::tatomlist::get_error private
Definition at line 47 of file atomlist.f90.
get_truth()
procedure xtb_type_atomlist::tatomlist::get_truth private
Definition at line 46 of file atomlist.f90.
new()
generic xtb_type_atomlist::tatomlist::new private
Definition at line 36 of file atomlist.f90.
References xtb_type_atomlist::from_defaults().
parse()
procedure, private xtb_type_atomlist::tatomlist::parse private
Definition at line 57 of file atomlist.f90.
remove()
generic xtb_type_atomlist::tatomlist::remove private
Definition at line 48 of file atomlist.f90.
remove_integer()
procedure, private xtb_type_atomlist::tatomlist::remove_integer private
Definition at line 49 of file atomlist.f90.
remove_integers()
procedure, private xtb_type_atomlist::tatomlist::remove_integers private
Definition at line 50 of file atomlist.f90.
remove_logicals()
procedure, private xtb_type_atomlist::tatomlist::remove_logicals private
Definition at line 51 of file atomlist.f90.
resize()
procedure xtb_type_atomlist::tatomlist::resize private
Definition at line 58 of file atomlist.f90.
scatter()
generic xtb_type_atomlist::tatomlist::scatter private
Definition at line 63 of file atomlist.f90.
scatter_real_2d()
procedure, private xtb_type_atomlist::tatomlist::scatter_real_2d private
Definition at line 64 of file atomlist.f90.
set_truth()
procedure xtb_type_atomlist::tatomlist::set_truth private
Definition at line 45 of file atomlist.f90.
switch_truth()
procedure xtb_type_atomlist::tatomlist::switch_truth private
Definition at line 44 of file atomlist.f90.
to_list()
procedure, pass(self) xtb_type_atomlist::tatomlist::to_list private
Definition at line 43 of file atomlist.f90.
to_string()
procedure, pass(self) xtb_type_atomlist::tatomlist::to_string private
Definition at line 42 of file atomlist.f90.
Member Data Documentation
default
logical xtb_type_atomlist::tatomlist::default = .false. private
Definition at line 31 of file atomlist.f90.
       logical :: default = .false.
delimiter
character xtb_type_atomlist::tatomlist::delimiter = p_delimiter private
Definition at line 32 of file atomlist.f90.
       character :: delimiter = p_delimiter
error
logical xtb_type_atomlist::tatomlist::error = .false. private
Definition at line 34 of file atomlist.f90.
       logical :: error = .false.
list
logical, dimension(:), allocatable xtb_type_atomlist::tatomlist::list private
Definition at line 30 of file atomlist.f90.
       logical, allocatable :: list(:)
skip
character xtb_type_atomlist::tatomlist::skip = p_skip private
Definition at line 33 of file atomlist.f90.
       character :: skip = p_skip
The documentation for this interface was generated from the following file:
src/type/atomlist.f90