My Project: xtb_type_reader::treader Type Reference
xtb_type_reader::treader Type Reference
Wrapper for reading from Fortran units.
Private Member Functions
generic open => openunit, openfile
Connect reader.
procedure, private openunit
Connect reader to unit.
procedure, private openfile
Connect reader to file.
generic read => readline, readinteger
Read from unit.
procedure, private readline
Read entire record from line.
procedure, private readinteger
Read an integer from a record.
generic close => closeunit
Close unit in reader.
procedure closeunit
Close connected unit.
Private Attributes
integer unit = -1
Connected unit.
Detailed Description
Wrapper for reading from Fortran units.
Definition at line 33 of file reader.F90.
Member Function/Subroutine Documentation
close()
generic xtb_type_reader::treader::close private
Close unit in reader.
Definition at line 59 of file reader.F90.
References xtb_type_reader::closeunit().
closeunit()
procedure xtb_type_reader::treader::closeunit private
Close connected unit.
Definition at line 63 of file reader.F90.
open()
generic xtb_type_reader::treader::open private
Connect reader.
Definition at line 41 of file reader.F90.
References xtb_type_reader::openfile(), and xtb_type_reader::openunit().
openfile()
procedure, private xtb_type_reader::treader::openfile private
Connect reader to file.
Definition at line 47 of file reader.F90.
openunit()
procedure, private xtb_type_reader::treader::openunit private
Connect reader to unit.
Definition at line 44 of file reader.F90.
read()
generic xtb_type_reader::treader::read private
Read from unit.
Definition at line 50 of file reader.F90.
References xtb_type_reader::readinteger(), and readline().
readinteger()
procedure, private xtb_type_reader::treader::readinteger private
Read an integer from a record.
Definition at line 56 of file reader.F90.
readline()
procedure, private xtb_type_reader::treader::readline private
Read entire record from line.
Definition at line 53 of file reader.F90.
Member Data Documentation
unit
integer xtb_type_reader::treader::unit = -1 private
Connected unit.
Definition at line 36 of file reader.F90.
       integer :: unit = -1
The documentation for this type was generated from the following file:
src/type/reader.F90