My Project: forpy_mod::mutablesequence Type Reference
forpy_mod::mutablesequence Type Reference
Abstract type that represents a sequence, whose items can be changed.
Public Member Functions
generic, public setitem => mutablesequence_setitem_int32_object
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_int32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_int64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_real32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_real64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_complex_real32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_complex_real64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_logical
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_char_1d
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int32_chars
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_object
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_int32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_int64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_real32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_real64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_complex_real32
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_complex_real64
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_logical
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_char_1d
Set an item at a given index.
generic, public setitem => mutablesequence_setitem_int64_chars
Set an item at a given index.
Public Member Functions inherited from forpy_mod::sequence
generic, public len => sequence_len_int32
Get the length of the object (number of elements).
generic, public count => sequence_count_int32
generic, public index => sequence_index_int32
Get the first index of a value.
generic, public getitem => sequence_getitem_int32_object
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_int32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_int64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_complex_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_complex_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_logical
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_char_1d
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_chars
Get item at a certain index.
generic, public len => sequence_len_int64
Get the length of the object (number of elements).
generic, public count => sequence_count_int64
generic, public index => sequence_index_int64
Get the first index of a value.
generic, public getitem => sequence_getitem_int64_object
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_int32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_int64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_complex_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_complex_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_logical
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_char_1d
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_chars
Get item at a certain index.
procedure, public contains => sequence_contains
Checks if a given item is contained in the sequence.
Public Member Functions inherited from forpy_mod::object
procedure, public destroy => object_destroy
Call to allow for freeing of resources of this object.
procedure, public getattribute => object_getattribute
Get value of an attribute of this object.
procedure, public setattr => object_setattr
Set value of an attribute of this object.
procedure, public delattr => object_delattr
Delete an attribute of this object.
procedure, public get_c_ptr => object_get_c_ptr
Get c_ptr representation of this object. For development of Python extension modules.
Private Member Functions
procedure, private mutablesequence_setitem_int32_object
procedure, private mutablesequence_setitem_int32_int32
procedure, private mutablesequence_setitem_int32_int64
procedure, private mutablesequence_setitem_int32_real32
procedure, private mutablesequence_setitem_int32_real64
procedure, private mutablesequence_setitem_int32_complex_real32
procedure, private mutablesequence_setitem_int32_complex_real64
procedure, private mutablesequence_setitem_int32_logical
procedure, private mutablesequence_setitem_int32_char_1d
procedure, private mutablesequence_setitem_int32_chars
procedure, private mutablesequence_setitem_int64_object
procedure, private mutablesequence_setitem_int64_int32
procedure, private mutablesequence_setitem_int64_int64
procedure, private mutablesequence_setitem_int64_real32
procedure, private mutablesequence_setitem_int64_real64
procedure, private mutablesequence_setitem_int64_complex_real32
procedure, private mutablesequence_setitem_int64_complex_real64
procedure, private mutablesequence_setitem_int64_logical
procedure, private mutablesequence_setitem_int64_char_1d
procedure, private mutablesequence_setitem_int64_chars
Detailed Description
Abstract type that represents a sequence, whose items can be changed.
Definition at line 984 of file forpy_mod.F90.
Member Function/Subroutine Documentation
mutablesequence_setitem_int32_char_1d()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_char_1d private
Definition at line 1010 of file forpy_mod.F90.
mutablesequence_setitem_int32_chars()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_chars private
Definition at line 1013 of file forpy_mod.F90.
mutablesequence_setitem_int32_complex_real32()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_complex_real32 private
Definition at line 1001 of file forpy_mod.F90.
mutablesequence_setitem_int32_complex_real64()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_complex_real64 private
Definition at line 1004 of file forpy_mod.F90.
mutablesequence_setitem_int32_int32()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_int32 private
Definition at line 989 of file forpy_mod.F90.
mutablesequence_setitem_int32_int64()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_int64 private
Definition at line 992 of file forpy_mod.F90.
mutablesequence_setitem_int32_logical()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_logical private
Definition at line 1007 of file forpy_mod.F90.
mutablesequence_setitem_int32_object()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_object private
Definition at line 986 of file forpy_mod.F90.
mutablesequence_setitem_int32_real32()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_real32 private
Definition at line 995 of file forpy_mod.F90.
mutablesequence_setitem_int32_real64()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int32_real64 private
Definition at line 998 of file forpy_mod.F90.
mutablesequence_setitem_int64_char_1d()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_char_1d private
Definition at line 1040 of file forpy_mod.F90.
mutablesequence_setitem_int64_chars()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_chars private
Definition at line 1043 of file forpy_mod.F90.
mutablesequence_setitem_int64_complex_real32()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_complex_real32 private
Definition at line 1031 of file forpy_mod.F90.
mutablesequence_setitem_int64_complex_real64()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_complex_real64 private
Definition at line 1034 of file forpy_mod.F90.
mutablesequence_setitem_int64_int32()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_int32 private
Definition at line 1019 of file forpy_mod.F90.
mutablesequence_setitem_int64_int64()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_int64 private
Definition at line 1022 of file forpy_mod.F90.
mutablesequence_setitem_int64_logical()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_logical private
Definition at line 1037 of file forpy_mod.F90.
mutablesequence_setitem_int64_object()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_object private
Definition at line 1016 of file forpy_mod.F90.
mutablesequence_setitem_int64_real32()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_real32 private
Definition at line 1025 of file forpy_mod.F90.
mutablesequence_setitem_int64_real64()
procedure, private forpy_mod::mutablesequence::mutablesequence_setitem_int64_real64 private
Definition at line 1028 of file forpy_mod.F90.
setitem() [1/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1012 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_char_1d().
setitem() [2/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1015 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_chars().
setitem() [3/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1003 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_complex_real32().
setitem() [4/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1006 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_complex_real64().
setitem() [5/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 991 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_int32().
setitem() [6/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 994 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_int64().
setitem() [7/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1009 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_logical().
setitem() [8/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 988 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_object().
setitem() [9/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 997 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_real32().
setitem() [10/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1000 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int32_real64().
setitem() [11/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1042 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_char_1d().
setitem() [12/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1045 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_chars().
setitem() [13/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1033 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_complex_real32().
setitem() [14/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1036 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_complex_real64().
setitem() [15/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1021 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_int32().
setitem() [16/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1024 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_int64().
setitem() [17/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1039 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_logical().
setitem() [18/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1018 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_object().
setitem() [19/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1027 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_real32().
setitem() [20/20]
generic, public forpy_mod::mutablesequence::setitem
Set an item at a given index.
Definition at line 1030 of file forpy_mod.F90.
References forpy_mod::mutablesequence_setitem_int64_real64().
The documentation for this type was generated from the following file:
prob_files/forpy_mod.F90