My Project: forpy_mod::dict Type Reference
forpy_mod::dict Type Reference
Public Member Functions
procedure, public clear => dict_clear
Removes all key-value pairs from dictionary.
procedure, public copy => dict_copy
Creates a copy of dict.
procedure, public keys => dict_keys
Creates a list of a dict's keys.
procedure, public items => dict_items
Creates a list of a dict's key-value pairs.
procedure, public values => dict_values
Creates a list of a dict's values.
generic, public get => dict_get_object_object
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_object
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_int32
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_int64
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_real32
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_real64
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_complex_real32
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_complex_real64
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_logical
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_char_1d
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int32_chars
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_object
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_int32
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_int64
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_real32
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_real64
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_complex_real32
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_complex_real64
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_logical
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_char_1d
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_int64_chars
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_object
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_int32
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_int64
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_real32
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_real64
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_complex_real32
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_complex_real64
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_logical
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_char_1d
Get value at a given key. If key does not exist, return a default value.
generic, public get => dict_get_chars_chars
Get value at a given key. If key does not exist, return a default value.
procedure, public setdefault => dict_setdefault_object_object
Get value at a given key. If key does not exist, set value at key to default value and return default.
Public Member Functions inherited from forpy_mod::mapping
generic, public getitem => mapping_getitem_object_object
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_object_object
Inserts value at given key. Sets value if key already exists.
generic, public delitem => mapping_delitem_object
Delete key-value pair with given key.
generic, public getitem => mapping_getitem_int32_object
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_object
Inserts value at given key. Sets value if key already exists.
generic, public delitem => mapping_delitem_int32
generic, public getitem => mapping_getitem_int32_int32
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_int32
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int32_int64
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_int64
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int32_real32
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_real32
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int32_real64
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_real64
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int32_complex_real32
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_complex_real32
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int32_complex_real64
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_complex_real64
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int32_logical
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_logical
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int32_char_1d
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_char_1d
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int32_chars
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int32_chars
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int64_object
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_object
Inserts value at given key. Sets value if key already exists.
generic, public delitem => mapping_delitem_int64
generic, public getitem => mapping_getitem_int64_int32
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_int32
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int64_int64
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_int64
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int64_real32
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_real32
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int64_real64
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_real64
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int64_complex_real32
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_complex_real32
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int64_complex_real64
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_complex_real64
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int64_logical
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_logical
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int64_char_1d
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_char_1d
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_int64_chars
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_int64_chars
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_chars_object
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_object
Inserts value at given key. Sets value if key already exists.
generic, public delitem => mapping_delitem_chars
generic, public getitem => mapping_getitem_chars_int32
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_int32
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_chars_int64
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_int64
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_chars_real32
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_real32
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_chars_real64
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_real64
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_chars_complex_real32
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_complex_real32
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_chars_complex_real64
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_complex_real64
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_chars_logical
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_logical
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_chars_char_1d
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_char_1d
Inserts value at given key. Sets value if key already exists.
generic, public getitem => mapping_getitem_chars_chars
Get value at a given key. KeyError if key does not exist.
generic, public setitem => mapping_setitem_chars_chars
Inserts value at given key. Sets value if key already exists.
generic, public len => mapping_len_int32
Get number of key-value pairs.
generic, public len => mapping_len_int64
Get number of key-value pairs.
procedure, public mapping_contains
Checks if key is contained in datastructure.
Public Member Functions inherited from forpy_mod::object
procedure, public destroy => object_destroy
Call to allow for freeing of resources of this object.
procedure, public getattribute => object_getattribute
Get value of an attribute of this object.
procedure, public setattr => object_setattr
Set value of an attribute of this object.
procedure, public delattr => object_delattr
Delete an attribute of this object.
procedure, public get_c_ptr => object_get_c_ptr
Get c_ptr representation of this object. For development of Python extension modules.
Private Member Functions
procedure, private dict_get_object_object
procedure, private dict_get_int32_object
procedure, private dict_get_int32_int32
procedure, private dict_get_int32_int64
procedure, private dict_get_int32_real32
procedure, private dict_get_int32_real64
procedure, private dict_get_int32_complex_real32
procedure, private dict_get_int32_complex_real64
procedure, private dict_get_int32_logical
procedure, private dict_get_int32_char_1d
procedure, private dict_get_int32_chars
procedure, private dict_get_int64_object
procedure, private dict_get_int64_int32
procedure, private dict_get_int64_int64
procedure, private dict_get_int64_real32
procedure, private dict_get_int64_real64
procedure, private dict_get_int64_complex_real32
procedure, private dict_get_int64_complex_real64
procedure, private dict_get_int64_logical
procedure, private dict_get_int64_char_1d
procedure, private dict_get_int64_chars
procedure, private dict_get_chars_object
procedure, private dict_get_chars_int32
procedure, private dict_get_chars_int64
procedure, private dict_get_chars_real32
procedure, private dict_get_chars_real64
procedure, private dict_get_chars_complex_real32
procedure, private dict_get_chars_complex_real64
procedure, private dict_get_chars_logical
procedure, private dict_get_chars_char_1d
procedure, private dict_get_chars_chars
Detailed Description
Definition at line 1327 of file forpy_mod.F90.
Member Function/Subroutine Documentation
clear()
procedure, public forpy_mod::dict::clear
Removes all key-value pairs from dictionary.
Definition at line 1330 of file forpy_mod.F90.
copy()
procedure, public forpy_mod::dict::copy
Creates a copy of dict.
Definition at line 1332 of file forpy_mod.F90.
dict_get_chars_char_1d()
procedure, private forpy_mod::dict::dict_get_chars_char_1d private
Definition at line 1427 of file forpy_mod.F90.
dict_get_chars_chars()
procedure, private forpy_mod::dict::dict_get_chars_chars private
Definition at line 1430 of file forpy_mod.F90.
dict_get_chars_complex_real32()
procedure, private forpy_mod::dict::dict_get_chars_complex_real32 private
Definition at line 1418 of file forpy_mod.F90.
dict_get_chars_complex_real64()
procedure, private forpy_mod::dict::dict_get_chars_complex_real64 private
Definition at line 1421 of file forpy_mod.F90.
dict_get_chars_int32()
procedure, private forpy_mod::dict::dict_get_chars_int32 private
Definition at line 1406 of file forpy_mod.F90.
dict_get_chars_int64()
procedure, private forpy_mod::dict::dict_get_chars_int64 private
Definition at line 1409 of file forpy_mod.F90.
dict_get_chars_logical()
procedure, private forpy_mod::dict::dict_get_chars_logical private
Definition at line 1424 of file forpy_mod.F90.
dict_get_chars_object()
procedure, private forpy_mod::dict::dict_get_chars_object private
Definition at line 1403 of file forpy_mod.F90.
dict_get_chars_real32()
procedure, private forpy_mod::dict::dict_get_chars_real32 private
Definition at line 1412 of file forpy_mod.F90.
dict_get_chars_real64()
procedure, private forpy_mod::dict::dict_get_chars_real64 private
Definition at line 1415 of file forpy_mod.F90.
dict_get_int32_char_1d()
procedure, private forpy_mod::dict::dict_get_int32_char_1d private
Definition at line 1367 of file forpy_mod.F90.
dict_get_int32_chars()
procedure, private forpy_mod::dict::dict_get_int32_chars private
Definition at line 1370 of file forpy_mod.F90.
dict_get_int32_complex_real32()
procedure, private forpy_mod::dict::dict_get_int32_complex_real32 private
Definition at line 1358 of file forpy_mod.F90.
dict_get_int32_complex_real64()
procedure, private forpy_mod::dict::dict_get_int32_complex_real64 private
Definition at line 1361 of file forpy_mod.F90.
dict_get_int32_int32()
procedure, private forpy_mod::dict::dict_get_int32_int32 private
Definition at line 1346 of file forpy_mod.F90.
dict_get_int32_int64()
procedure, private forpy_mod::dict::dict_get_int32_int64 private
Definition at line 1349 of file forpy_mod.F90.
dict_get_int32_logical()
procedure, private forpy_mod::dict::dict_get_int32_logical private
Definition at line 1364 of file forpy_mod.F90.
dict_get_int32_object()
procedure, private forpy_mod::dict::dict_get_int32_object private
Definition at line 1343 of file forpy_mod.F90.
dict_get_int32_real32()
procedure, private forpy_mod::dict::dict_get_int32_real32 private
Definition at line 1352 of file forpy_mod.F90.
dict_get_int32_real64()
procedure, private forpy_mod::dict::dict_get_int32_real64 private
Definition at line 1355 of file forpy_mod.F90.
dict_get_int64_char_1d()
procedure, private forpy_mod::dict::dict_get_int64_char_1d private
Definition at line 1397 of file forpy_mod.F90.
dict_get_int64_chars()
procedure, private forpy_mod::dict::dict_get_int64_chars private
Definition at line 1400 of file forpy_mod.F90.
dict_get_int64_complex_real32()
procedure, private forpy_mod::dict::dict_get_int64_complex_real32 private
Definition at line 1388 of file forpy_mod.F90.
dict_get_int64_complex_real64()
procedure, private forpy_mod::dict::dict_get_int64_complex_real64 private
Definition at line 1391 of file forpy_mod.F90.
dict_get_int64_int32()
procedure, private forpy_mod::dict::dict_get_int64_int32 private
Definition at line 1376 of file forpy_mod.F90.
dict_get_int64_int64()
procedure, private forpy_mod::dict::dict_get_int64_int64 private
Definition at line 1379 of file forpy_mod.F90.
dict_get_int64_logical()
procedure, private forpy_mod::dict::dict_get_int64_logical private
Definition at line 1394 of file forpy_mod.F90.
dict_get_int64_object()
procedure, private forpy_mod::dict::dict_get_int64_object private
Definition at line 1373 of file forpy_mod.F90.
dict_get_int64_real32()
procedure, private forpy_mod::dict::dict_get_int64_real32 private
Definition at line 1382 of file forpy_mod.F90.
dict_get_int64_real64()
procedure, private forpy_mod::dict::dict_get_int64_real64 private
Definition at line 1385 of file forpy_mod.F90.
dict_get_object_object()
procedure, private forpy_mod::dict::dict_get_object_object private
Definition at line 1340 of file forpy_mod.F90.
get() [1/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1429 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_char_1d().
get() [2/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1432 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_chars().
get() [3/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1420 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_complex_real32().
get() [4/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1423 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_complex_real64().
get() [5/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1408 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_int32().
get() [6/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1411 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_int64().
get() [7/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1426 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_logical().
get() [8/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1405 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_object().
get() [9/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1414 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_real32().
get() [10/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1417 of file forpy_mod.F90.
References forpy_mod::dict_get_chars_real64().
get() [11/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1369 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_char_1d().
get() [12/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1372 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_chars().
get() [13/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1360 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_complex_real32().
get() [14/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1363 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_complex_real64().
get() [15/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1348 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_int32().
get() [16/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1351 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_int64().
get() [17/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1366 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_logical().
get() [18/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1345 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_object().
get() [19/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1354 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_real32().
get() [20/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1357 of file forpy_mod.F90.
References forpy_mod::dict_get_int32_real64().
get() [21/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1399 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_char_1d().
get() [22/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1402 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_chars().
get() [23/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1390 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_complex_real32().
get() [24/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1393 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_complex_real64().
get() [25/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1378 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_int32().
get() [26/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1381 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_int64().
get() [27/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1396 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_logical().
get() [28/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1375 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_object().
get() [29/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1384 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_real32().
get() [30/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1387 of file forpy_mod.F90.
References forpy_mod::dict_get_int64_real64().
get() [31/31]
generic, public forpy_mod::dict::get
Get value at a given key. If key does not exist, return a default value.
Definition at line 1342 of file forpy_mod.F90.
References forpy_mod::dict_get_object_object().
items()
procedure, public forpy_mod::dict::items
Creates a list of a dict's key-value pairs.
Definition at line 1336 of file forpy_mod.F90.
keys()
procedure, public forpy_mod::dict::keys
Creates a list of a dict's keys.
Definition at line 1334 of file forpy_mod.F90.
setdefault()
procedure, public forpy_mod::dict::setdefault
Get value at a given key. If key does not exist, set value at key to default value and return default.
Definition at line 1435 of file forpy_mod.F90.
values()
procedure, public forpy_mod::dict::values
Creates a list of a dict's values.
Definition at line 1338 of file forpy_mod.F90.
The documentation for this type was generated from the following file:
prob_files/forpy_mod.F90