My Project: forpy_mod::tuple Type Reference
forpy_mod::tuple Type Reference
Type that corresponds to a Python tuple. Create with tuple_create.
Public Member Functions
generic, public setitem => tuple_setitem_int32_object
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int32_int32
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int32_int64
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int32_real32
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int32_real64
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int32_complex_real32
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int32_complex_real64
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int32_logical
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int32_char_1d
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int32_chars
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_object
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_int32
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_int64
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_real32
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_real64
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_complex_real32
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_complex_real64
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_logical
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_char_1d
Sets item at given index. One must set all items before use of tuple.
generic, public setitem => tuple_setitem_int64_chars
Sets item at given index. One must set all items before use of tuple.
procedure, public add => tuple_add
Concatenates tuples.
Public Member Functions inherited from forpy_mod::sequence
generic, public len => sequence_len_int32
Get the length of the object (number of elements).
generic, public count => sequence_count_int32
generic, public index => sequence_index_int32
Get the first index of a value.
generic, public getitem => sequence_getitem_int32_object
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_int32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_int64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_complex_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_complex_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_logical
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_char_1d
Get item at a certain index.
generic, public getitem => sequence_getitem_int32_chars
Get item at a certain index.
generic, public len => sequence_len_int64
Get the length of the object (number of elements).
generic, public count => sequence_count_int64
generic, public index => sequence_index_int64
Get the first index of a value.
generic, public getitem => sequence_getitem_int64_object
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_int32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_int64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_complex_real32
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_complex_real64
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_logical
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_char_1d
Get item at a certain index.
generic, public getitem => sequence_getitem_int64_chars
Get item at a certain index.
procedure, public contains => sequence_contains
Checks if a given item is contained in the sequence.
Public Member Functions inherited from forpy_mod::object
procedure, public destroy => object_destroy
Call to allow for freeing of resources of this object.
procedure, public getattribute => object_getattribute
Get value of an attribute of this object.
procedure, public setattr => object_setattr
Set value of an attribute of this object.
procedure, public delattr => object_delattr
Delete an attribute of this object.
procedure, public get_c_ptr => object_get_c_ptr
Get c_ptr representation of this object. For development of Python extension modules.
Private Member Functions
procedure, private tuple_setitem_int32_object
procedure, private tuple_setitem_int32_int32
procedure, private tuple_setitem_int32_int64
procedure, private tuple_setitem_int32_real32
procedure, private tuple_setitem_int32_real64
procedure, private tuple_setitem_int32_complex_real32
procedure, private tuple_setitem_int32_complex_real64
procedure, private tuple_setitem_int32_logical
procedure, private tuple_setitem_int32_char_1d
procedure, private tuple_setitem_int32_chars
procedure, private tuple_setitem_int64_object
procedure, private tuple_setitem_int64_int32
procedure, private tuple_setitem_int64_int64
procedure, private tuple_setitem_int64_real32
procedure, private tuple_setitem_int64_real64
procedure, private tuple_setitem_int64_complex_real32
procedure, private tuple_setitem_int64_complex_real64
procedure, private tuple_setitem_int64_logical
procedure, private tuple_setitem_int64_char_1d
procedure, private tuple_setitem_int64_chars
Detailed Description
Type that corresponds to a Python tuple. Create with tuple_create.
Definition at line 1439 of file forpy_mod.F90.
Member Function/Subroutine Documentation
add()
procedure, public forpy_mod::tuple::add
Concatenates tuples.
Definition at line 1503 of file forpy_mod.F90.
setitem() [1/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1467 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_char_1d().
setitem() [2/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1470 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_chars().
setitem() [3/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1458 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_complex_real32().
setitem() [4/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1461 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_complex_real64().
setitem() [5/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1446 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_int32().
setitem() [6/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1449 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_int64().
setitem() [7/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1464 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_logical().
setitem() [8/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1443 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_object().
setitem() [9/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1452 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_real32().
setitem() [10/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1455 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int32_real64().
setitem() [11/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1497 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_char_1d().
setitem() [12/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1500 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_chars().
setitem() [13/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1488 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_complex_real32().
setitem() [14/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1491 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_complex_real64().
setitem() [15/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1476 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_int32().
setitem() [16/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1479 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_int64().
setitem() [17/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1494 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_logical().
setitem() [18/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1473 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_object().
setitem() [19/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1482 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_real32().
setitem() [20/20]
generic, public forpy_mod::tuple::setitem
Sets item at given index. One must set all items before use of tuple.
Definition at line 1485 of file forpy_mod.F90.
References forpy_mod::tuple_setitem_int64_real64().
tuple_setitem_int32_char_1d()
procedure, private forpy_mod::tuple::tuple_setitem_int32_char_1d private
Definition at line 1465 of file forpy_mod.F90.
tuple_setitem_int32_chars()
procedure, private forpy_mod::tuple::tuple_setitem_int32_chars private
Definition at line 1468 of file forpy_mod.F90.
tuple_setitem_int32_complex_real32()
procedure, private forpy_mod::tuple::tuple_setitem_int32_complex_real32 private
Definition at line 1456 of file forpy_mod.F90.
tuple_setitem_int32_complex_real64()
procedure, private forpy_mod::tuple::tuple_setitem_int32_complex_real64 private
Definition at line 1459 of file forpy_mod.F90.
tuple_setitem_int32_int32()
procedure, private forpy_mod::tuple::tuple_setitem_int32_int32 private
Definition at line 1444 of file forpy_mod.F90.
tuple_setitem_int32_int64()
procedure, private forpy_mod::tuple::tuple_setitem_int32_int64 private
Definition at line 1447 of file forpy_mod.F90.
tuple_setitem_int32_logical()
procedure, private forpy_mod::tuple::tuple_setitem_int32_logical private
Definition at line 1462 of file forpy_mod.F90.
tuple_setitem_int32_object()
procedure, private forpy_mod::tuple::tuple_setitem_int32_object private
Definition at line 1441 of file forpy_mod.F90.
tuple_setitem_int32_real32()
procedure, private forpy_mod::tuple::tuple_setitem_int32_real32 private
Definition at line 1450 of file forpy_mod.F90.
tuple_setitem_int32_real64()
procedure, private forpy_mod::tuple::tuple_setitem_int32_real64 private
Definition at line 1453 of file forpy_mod.F90.
tuple_setitem_int64_char_1d()
procedure, private forpy_mod::tuple::tuple_setitem_int64_char_1d private
Definition at line 1495 of file forpy_mod.F90.
tuple_setitem_int64_chars()
procedure, private forpy_mod::tuple::tuple_setitem_int64_chars private
Definition at line 1498 of file forpy_mod.F90.
tuple_setitem_int64_complex_real32()
procedure, private forpy_mod::tuple::tuple_setitem_int64_complex_real32 private
Definition at line 1486 of file forpy_mod.F90.
tuple_setitem_int64_complex_real64()
procedure, private forpy_mod::tuple::tuple_setitem_int64_complex_real64 private
Definition at line 1489 of file forpy_mod.F90.
tuple_setitem_int64_int32()
procedure, private forpy_mod::tuple::tuple_setitem_int64_int32 private
Definition at line 1474 of file forpy_mod.F90.
tuple_setitem_int64_int64()
procedure, private forpy_mod::tuple::tuple_setitem_int64_int64 private
Definition at line 1477 of file forpy_mod.F90.
tuple_setitem_int64_logical()
procedure, private forpy_mod::tuple::tuple_setitem_int64_logical private
Definition at line 1492 of file forpy_mod.F90.
tuple_setitem_int64_object()
procedure, private forpy_mod::tuple::tuple_setitem_int64_object private
Definition at line 1471 of file forpy_mod.F90.
tuple_setitem_int64_real32()
procedure, private forpy_mod::tuple::tuple_setitem_int64_real32 private
Definition at line 1480 of file forpy_mod.F90.
tuple_setitem_int64_real64()
procedure, private forpy_mod::tuple::tuple_setitem_int64_real64 private
Definition at line 1483 of file forpy_mod.F90.
The documentation for this type was generated from the following file:
prob_files/forpy_mod.F90