My Project: forpy_mod::ndarray Type Reference
forpy_mod::ndarray Type Reference
Type that represents a Numpy array.
Public Member Functions
generic, public get_data => get_data_int32_1d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_int64_1d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_real32_1d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_real64_1d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_complex_real32_1d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_complex_real64_1d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_int32_2d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_int64_2d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_real32_2d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_real64_2d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_complex_real32_2d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_complex_real64_2d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_int32_3d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_int64_3d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_real32_3d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_real64_3d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_complex_real32_3d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_complex_real64_3d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_int32_4d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_int64_4d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_real32_4d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_real64_4d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_complex_real32_4d
Retrieve a Fortran pointer to the array data.
generic, public get_data => get_data_complex_real64_4d
Retrieve a Fortran pointer to the array data.
procedure, public transpose => ndarray_transpose
Transpose the array.
procedure, public copy => ndarray_copy
Create a copy (with its own data) of the ndarray.
procedure, public is_ordered => ndarray_is_ordered
Checks if the array has Fortran or C storage order (contiguous array)
procedure, public get_dtype_name => ndarray_get_dtype_name
Get numpy.dtype type identifier of the array. Python equivalent: self.dtype.name.
generic, public ndim => ndarray_ndim_int32
Get dimension of array.
generic, public ndim => ndarray_ndim_int64
Get dimension of array.
Public Member Functions inherited from forpy_mod::object
procedure, public destroy => object_destroy
Call to allow for freeing of resources of this object.
procedure, public getattribute => object_getattribute
Get value of an attribute of this object.
procedure, public setattr => object_setattr
Set value of an attribute of this object.
procedure, public delattr => object_delattr
Delete an attribute of this object.
procedure, public get_c_ptr => object_get_c_ptr
Get c_ptr representation of this object. For development of Python extension modules.
Private Member Functions
procedure, private get_data_int32_1d
procedure, private get_data_int64_1d
procedure, private get_data_real32_1d
procedure, private get_data_real64_1d
procedure, private get_data_complex_real32_1d
procedure, private get_data_complex_real64_1d
procedure, private get_data_int32_2d
procedure, private get_data_int64_2d
procedure, private get_data_real32_2d
procedure, private get_data_real64_2d
procedure, private get_data_complex_real32_2d
procedure, private get_data_complex_real64_2d
procedure, private get_data_int32_3d
procedure, private get_data_int64_3d
procedure, private get_data_real32_3d
procedure, private get_data_real64_3d
procedure, private get_data_complex_real32_3d
procedure, private get_data_complex_real64_3d
procedure, private get_data_int32_4d
procedure, private get_data_int64_4d
procedure, private get_data_real32_4d
procedure, private get_data_real64_4d
procedure, private get_data_complex_real32_4d
procedure, private get_data_complex_real64_4d
procedure, private ndarray_ndim_int32
procedure, private ndarray_ndim_int64
Detailed Description
Type that represents a Numpy array.
Definition at line 1595 of file forpy_mod.F90.
Member Function/Subroutine Documentation
copy()
procedure, public forpy_mod::ndarray::copy
Create a copy (with its own data) of the ndarray.
Definition at line 1672 of file forpy_mod.F90.
get_data() [1/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1611 of file forpy_mod.F90.
References forpy_mod::get_data_complex_real32_1d().
get_data() [2/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1629 of file forpy_mod.F90.
References forpy_mod::get_data_complex_real32_2d().
get_data() [3/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1647 of file forpy_mod.F90.
References forpy_mod::get_data_complex_real32_3d().
get_data() [4/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1665 of file forpy_mod.F90.
References forpy_mod::get_data_complex_real32_4d().
get_data() [5/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1614 of file forpy_mod.F90.
References forpy_mod::get_data_complex_real64_1d().
get_data() [6/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1632 of file forpy_mod.F90.
References forpy_mod::get_data_complex_real64_2d().
get_data() [7/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1650 of file forpy_mod.F90.
References forpy_mod::get_data_complex_real64_3d().
get_data() [8/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1668 of file forpy_mod.F90.
References forpy_mod::get_data_complex_real64_4d().
get_data() [9/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1599 of file forpy_mod.F90.
References forpy_mod::get_data_int32_1d().
get_data() [10/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1617 of file forpy_mod.F90.
References forpy_mod::get_data_int32_2d().
get_data() [11/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1635 of file forpy_mod.F90.
References forpy_mod::get_data_int32_3d().
get_data() [12/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1653 of file forpy_mod.F90.
References forpy_mod::get_data_int32_4d().
get_data() [13/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1602 of file forpy_mod.F90.
References forpy_mod::get_data_int64_1d().
get_data() [14/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1620 of file forpy_mod.F90.
References forpy_mod::get_data_int64_2d().
get_data() [15/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1638 of file forpy_mod.F90.
References forpy_mod::get_data_int64_3d().
get_data() [16/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1656 of file forpy_mod.F90.
References forpy_mod::get_data_int64_4d().
get_data() [17/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1605 of file forpy_mod.F90.
References forpy_mod::get_data_real32_1d().
get_data() [18/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1623 of file forpy_mod.F90.
References forpy_mod::get_data_real32_2d().
get_data() [19/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1641 of file forpy_mod.F90.
References forpy_mod::get_data_real32_3d().
get_data() [20/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1659 of file forpy_mod.F90.
References forpy_mod::get_data_real32_4d().
get_data() [21/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1608 of file forpy_mod.F90.
References forpy_mod::get_data_real64_1d().
get_data() [22/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1626 of file forpy_mod.F90.
References forpy_mod::get_data_real64_2d().
get_data() [23/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1644 of file forpy_mod.F90.
References forpy_mod::get_data_real64_3d().
get_data() [24/24]
generic, public forpy_mod::ndarray::get_data
Retrieve a Fortran pointer to the array data.
Definition at line 1662 of file forpy_mod.F90.
References forpy_mod::get_data_real64_4d().
get_data_complex_real32_1d()
procedure, private forpy_mod::ndarray::get_data_complex_real32_1d private
Definition at line 1609 of file forpy_mod.F90.
get_data_complex_real32_2d()
procedure, private forpy_mod::ndarray::get_data_complex_real32_2d private
Definition at line 1627 of file forpy_mod.F90.
get_data_complex_real32_3d()
procedure, private forpy_mod::ndarray::get_data_complex_real32_3d private
Definition at line 1645 of file forpy_mod.F90.
get_data_complex_real32_4d()
procedure, private forpy_mod::ndarray::get_data_complex_real32_4d private
Definition at line 1663 of file forpy_mod.F90.
get_data_complex_real64_1d()
procedure, private forpy_mod::ndarray::get_data_complex_real64_1d private
Definition at line 1612 of file forpy_mod.F90.
get_data_complex_real64_2d()
procedure, private forpy_mod::ndarray::get_data_complex_real64_2d private
Definition at line 1630 of file forpy_mod.F90.
get_data_complex_real64_3d()
procedure, private forpy_mod::ndarray::get_data_complex_real64_3d private
Definition at line 1648 of file forpy_mod.F90.
get_data_complex_real64_4d()
procedure, private forpy_mod::ndarray::get_data_complex_real64_4d private
Definition at line 1666 of file forpy_mod.F90.
get_data_int32_1d()
procedure, private forpy_mod::ndarray::get_data_int32_1d private
Definition at line 1597 of file forpy_mod.F90.
get_data_int32_2d()
procedure, private forpy_mod::ndarray::get_data_int32_2d private
Definition at line 1615 of file forpy_mod.F90.
get_data_int32_3d()
procedure, private forpy_mod::ndarray::get_data_int32_3d private
Definition at line 1633 of file forpy_mod.F90.
get_data_int32_4d()
procedure, private forpy_mod::ndarray::get_data_int32_4d private
Definition at line 1651 of file forpy_mod.F90.
get_data_int64_1d()
procedure, private forpy_mod::ndarray::get_data_int64_1d private
Definition at line 1600 of file forpy_mod.F90.
get_data_int64_2d()
procedure, private forpy_mod::ndarray::get_data_int64_2d private
Definition at line 1618 of file forpy_mod.F90.
get_data_int64_3d()
procedure, private forpy_mod::ndarray::get_data_int64_3d private
Definition at line 1636 of file forpy_mod.F90.
get_data_int64_4d()
procedure, private forpy_mod::ndarray::get_data_int64_4d private
Definition at line 1654 of file forpy_mod.F90.
get_data_real32_1d()
procedure, private forpy_mod::ndarray::get_data_real32_1d private
Definition at line 1603 of file forpy_mod.F90.
get_data_real32_2d()
procedure, private forpy_mod::ndarray::get_data_real32_2d private
Definition at line 1621 of file forpy_mod.F90.
get_data_real32_3d()
procedure, private forpy_mod::ndarray::get_data_real32_3d private
Definition at line 1639 of file forpy_mod.F90.
get_data_real32_4d()
procedure, private forpy_mod::ndarray::get_data_real32_4d private
Definition at line 1657 of file forpy_mod.F90.
get_data_real64_1d()
procedure, private forpy_mod::ndarray::get_data_real64_1d private
Definition at line 1606 of file forpy_mod.F90.
get_data_real64_2d()
procedure, private forpy_mod::ndarray::get_data_real64_2d private
Definition at line 1624 of file forpy_mod.F90.
get_data_real64_3d()
procedure, private forpy_mod::ndarray::get_data_real64_3d private
Definition at line 1642 of file forpy_mod.F90.
get_data_real64_4d()
procedure, private forpy_mod::ndarray::get_data_real64_4d private
Definition at line 1660 of file forpy_mod.F90.
get_dtype_name()
procedure, public forpy_mod::ndarray::get_dtype_name
Get numpy.dtype type identifier of the array. Python equivalent: self.dtype.name.
Definition at line 1676 of file forpy_mod.F90.
is_ordered()
procedure, public forpy_mod::ndarray::is_ordered
Checks if the array has Fortran or C storage order (contiguous array)
Definition at line 1674 of file forpy_mod.F90.
ndarray_ndim_int32()
procedure, private forpy_mod::ndarray::ndarray_ndim_int32 private
Definition at line 1678 of file forpy_mod.F90.
ndarray_ndim_int64()
procedure, private forpy_mod::ndarray::ndarray_ndim_int64 private
Definition at line 1679 of file forpy_mod.F90.
ndim() [1/2]
generic, public forpy_mod::ndarray::ndim
Get dimension of array.
Definition at line 1681 of file forpy_mod.F90.
References forpy_mod::ndarray_ndim_int32().
ndim() [2/2]
generic, public forpy_mod::ndarray::ndim
Get dimension of array.
Definition at line 1683 of file forpy_mod.F90.
References forpy_mod::ndarray_ndim_int64().
transpose()
procedure, public forpy_mod::ndarray::transpose
Transpose the array.
Definition at line 1670 of file forpy_mod.F90.
The documentation for this type was generated from the following file:
prob_files/forpy_mod.F90