My Project: xtb_type_identitymap::tidentitymap Type Reference
xtb_type_identitymap::tidentitymap Type Reference
Map from element symbols to identity.
Private Member Functions
procedure writeinfo
Write informative printout for the map.
generic has => hassymbol, hasnumber
Check if symbol or number maps to atoms.
procedure, private hassymbol
Check if element symbol maps to atoms.
procedure, private hasnumber
Check if atomic number maps to atoms.
generic get => getindexsymbol, getindexnumber
Get indices.
procedure, private getindexsymbol
Get indices for an unique element symbol.
procedure, private getindexnumber
Get indices for a certain atomic number.
generic set => setrealwithsymbol, setrealwithnumber
Setter functions in atomic arrays.
procedure, private setrealwithsymbol
Set value in an array using an unique element symbol.
procedure, private setrealwithnumber
Set value in an array using the atomic number.
Private Attributes
integer, dimension(:), allocatable num
Atomic numbers for each id.
character(len=symbollength), dimension(:), allocatable sym
Element symbols for each id.
type(tatomicmap), dimension(:), allocatable map
Maps from id to its atoms.
Detailed Description
Map from element symbols to identity.
Definition at line 40 of file identitymap.f90.
Member Function/Subroutine Documentation
get()
generic xtb_type_identitymap::tidentitymap::get private
Get indices.
Definition at line 67 of file identitymap.f90.
References xtb_type_identitymap::getindexnumber(), and xtb_type_identitymap::getindexsymbol().
getindexnumber()
procedure, private xtb_type_identitymap::tidentitymap::getindexnumber private
Get indices for a certain atomic number.
Definition at line 73 of file identitymap.f90.
getindexsymbol()
procedure, private xtb_type_identitymap::tidentitymap::getindexsymbol private
Get indices for an unique element symbol.
Definition at line 70 of file identitymap.f90.
has()
generic xtb_type_identitymap::tidentitymap::has private
Check if symbol or number maps to atoms.
Definition at line 58 of file identitymap.f90.
References xtb_type_identitymap::hasnumber(), and xtb_type_identitymap::hassymbol().
hasnumber()
procedure, private xtb_type_identitymap::tidentitymap::hasnumber private
Check if atomic number maps to atoms.
Definition at line 64 of file identitymap.f90.
hassymbol()
procedure, private xtb_type_identitymap::tidentitymap::hassymbol private
Check if element symbol maps to atoms.
Definition at line 61 of file identitymap.f90.
set()
generic xtb_type_identitymap::tidentitymap::set private
Setter functions in atomic arrays.
Definition at line 76 of file identitymap.f90.
References set(), xtb_type_identitymap::setrealwithnumber(), and xtb_type_identitymap::setrealwithsymbol().
setrealwithnumber()
procedure, private xtb_type_identitymap::tidentitymap::setrealwithnumber private
Set value in an array using the atomic number.
Definition at line 82 of file identitymap.f90.
setrealwithsymbol()
procedure, private xtb_type_identitymap::tidentitymap::setrealwithsymbol private
Set value in an array using an unique element symbol.
Definition at line 79 of file identitymap.f90.
writeinfo()
procedure xtb_type_identitymap::tidentitymap::writeinfo private
Write informative printout for the map.
Definition at line 55 of file identitymap.f90.
Member Data Documentation
map
type(tatomicmap), dimension(:), allocatable xtb_type_identitymap::tidentitymap::map private
Maps from id to its atoms.
Definition at line 50 of file identitymap.f90.
       type(TAtomicMap), allocatable :: map(:)
num
integer, dimension(:), allocatable xtb_type_identitymap::tidentitymap::num private
Atomic numbers for each id.
Definition at line 44 of file identitymap.f90.
       integer, allocatable :: num(:)
sym
character(len=symbollength), dimension(:), allocatable xtb_type_identitymap::tidentitymap::sym private
Element symbols for each id.
Definition at line 47 of file identitymap.f90.
       character(len=symbolLength), allocatable :: sym(:)
The documentation for this type was generated from the following file:
src/type/identitymap.f90