My Project: TESTSUITE/tests_peeq.f90 File Reference
tests_peeq.f90 File Reference
Functions/Subroutines
program peeq_tester
Function/Subroutine Documentation
peeq_tester()
program peeq_tester
Definition at line 1 of file tests_peeq.f90.
References mctc_init(), raise(), xtb_mctc_systools::rdarg(), test_hessian::run_hessian_test(), terminate(), test_atomlist(), test_axis(), test_class_molecule_axis_trafo(), test_class_molecule_mic_distances(), test_coulomb_gaussian_cluster(), test_coulomb_gaussian_pbc3d(), test_coulomb_gfn1_cluster(), test_coulomb_gfn1_pbc3d(), test_coulomb_gfn2_cluster(), test_coulomb_gfn2_pbc3d(), test_coulomb_point_cluster(), test_coulomb_point_pbc3d(), test_dftd3_pbc3d_latticepoints(), test_dftd3_pbc3d_neighbourlist(), test_dftd3_pbc3d_threebody_latp(), test_dftd3_pbc3d_threebody_neighs(), test_dftd4_pbc3d_latticepoints(), test_dftd4_pbc3d_neighbourlist(), test_dftd4_pbc3d_threebody_latp(), test_dftd4_pbc3d_threebody_neighs(), test_eeq_ewald(), test_eeq_model_gbsa(), test_eeq_model_hbond(), test_eeq_model_salt(), test_eeq_water(), test_geometry_reader_file_coord_c_1d(), test_geometry_reader_file_coord_c_2d(), test_geometry_reader_file_coord_caf2_3d(), test_geometry_reader_file_coord_camgco_3d(), test_geometry_reader_file_coord_general_0d(), test_geometry_reader_file_gen(), test_geometry_reader_file_pdb_4qxx(), test_geometry_reader_file_pdb_4qxx_noh(), test_geometry_reader_file_poscar_sio2_3d(), test_geometry_reader_file_sdf_benzen_hquery(), test_geometry_reader_file_sdf_h2o(), test_geometry_reader_file_sdf_h2o_flat(), test_geometry_reader_file_xmol_water_0d(), test_geometry_reader_molfile_benzen(), test_geometry_reader_molfile_benzen_flat(), test_gfn0_api(), test_gfn0_api_srb(), test_gfn0_mindless_basic(), test_gfn0_mindless_solvation(), test_gfn0_sp(), test_gfn1_api(), test_gfn1_mindless_basic(), test_gfn1_mindless_solvation(), test_gfn1_pbc3d(), test_gfn1_pcem_api(), test_gfn1_scc(), test_gfn1_xb(), test_gfn1gbsa_api(), test_gfn2_api(), test_gfn2_dmetal(), test_gfn2_mindless_basic(), test_gfn2_mindless_solvation(), test_gfn2_pcem_api(), test_gfn2_scc(), test_gfn2gbsa_api(), test_gfn2salt_api(), test_gfnff_gbsa(), test_gfnff_hb(), test_gfnff_mindless_basic(), test_gfnff_mindless_solvation(), test_gfnff_pdb(), test_gfnff_scaleup(), test_gfnff_sdf(), test_gfnff_sp(), test_ipea_indole(), test_latticepoint_pbc3d(), test_ncoord_pbc3d_latticepoints(), test_ncoord_pbc3d_neighbourlist(), test_pbc_tools_convert(), test_pbc_tools_cutoff(), test_peeq_api(), test_peeq_api_srb(), test_peeq_sp(), test_print_thermo(), test_repulsion_cluster(), test_repulsion_pbc3d(), test_symmetry_c20(), test_symmetry_li8(), test_symmetry_pcl3(), test_symmetry_water(), test_thermo_calc(), test_wigner_seitz_0d(), test_wigner_seitz_3d(), true(), and xtb_mctc_accuracy::wp.