My Project: src/timing.f90 File Reference
timing.f90 File Reference
Functions/Subroutines
subroutine timing (t, w)
subroutine prtime (io, tt, ww, string)
Function/Subroutine Documentation
prtime()
subroutine prtime (integer io, real(wp) tt, real(wp) ww, character(len=*), intent(in) string)
Definition at line 28 of file timing.f90.
    use xtb_mctc_accuracy, only : wp
    integer  :: io
    real(wp) :: ww,tt,t,tsec,wsec
    integer  :: tday,thour,tmin
    integer  :: wday,whour,wmin
    character(len=*),intent(in) :: string
    t=tt
    tday=idint(t/86400)
    t=t-tday*86400
    thour=idint(t/3600)
    t=t-thour*3600
    tmin=idint(t/60)
    t=t-60*tmin
    tsec=t
    t=ww
    wday=idint(t/86400)
    t=t-wday*86400
    whour=idint(t/3600)
    t=t-whour*3600
    wmin=idint(t/60)
    t=t-60*wmin
    wsec=t
    if(tday.ne.0)then
       write(io,2 )trim(string),tday,thour,tmin,tsec
       write(io,20)trim(string),wday,whour,wmin,wsec
       return
    endif
    if(thour.ne.0)then
       write(io,3 )trim(string),thour,tmin,tsec
       write(io,30)trim(string),whour,wmin,wsec
       return
    endif
    if(tmin .ne.0)then
       write(io,4 )trim(string),tmin,tsec
       write(io,40)trim(string),wmin,wsec
       return
    endif
    write(io,5 )trim(string),tsec
    write(io,50)trim(string),wsec
    return
  2    format('cpu  time for ',a,2x,i3,' d',i3,' h',i3,' m',f5.1,' s')
  3    format('cpu  time for ',a,2x,i3,' h',i3,' m',f5.1,' s')
  4    format('cpu  time for ',a,2x,i3,' m',f5.1,' s')
  5    format('cpu  time for ',a,2x,f6.2,' s')
  20   format('wall time for ',a,2x,i3,' d',i3,' h',i3,' m',f5.1,' s')
  30   format('wall time for ',a,2x,i3,' h',i3,' m',f5.1,' s')
  40   format('wall time for ',a,2x,i3,' m',f5.1,' s')
  50   format('wall time for ',a,2x,f6.2,' s')
References xtb_mctc_accuracy::wp.
Referenced by xtb_cube::cube(), and xtb_local::local().
timing()
subroutine timing (real(wp) t, real(wp) w)
Definition at line 18 of file timing.f90.
    use xtb_mctc_accuracy, only : wp
    real(wp) :: t,w
    integer :: time_count,time_rate,time_max
    call system_clock(time_count,time_rate,time_max)
    call cpu_time(t)
    w = real(time_count,wp)/real(time_rate,wp)
References xtb_mctc_accuracy::wp.
Referenced by xtb_type_timer::allocate_timer(), xtb_cube::cube(), esp::espplot(), xtb_type_timer::get_timer(), xtb_local::local(), xtb_dynamic::md(), xtb_freq_numdiff::numdiff2::numdiff2_all(), xtb_freq_numdiff::numdiff2::numdiff2_list(), xtb_type_timer::start_timing(), and xtb_type_timer::stop_timing().