My Project: include/xtb.h File Reference
xtb.h File Reference
#include <stdbool.h>
Macros
#define XTB_API_ENTRY
#define XTB_API_CALL
#define XTB_API_SUFFIX__VERSION_1_0_0
#define XTB_API_VERSION 10000
Define proprocessor to allow to check for specific API features.
#define XTB_VERSION_6_3_0 1
#define XTB_VERSION_6_3_1 1
#define XTB_VERSION_6_3_2 1
#define XTB_VERSION_6_3_3 1
#define XTB_VERBOSITY_FULL 2
Possible print levels for API calls.
#define XTB_VERBOSITY_MINIMAL 1
#define XTB_VERBOSITY_MUTED 0
Typedefs
typedef struct _xtb_TEnvironment * xtb_TEnvironment
Calculation environment class.
typedef struct _xtb_TMolecule * xtb_TMolecule
Molecular structure data class.
typedef struct _xtb_TCalculator * xtb_TCalculator
Single point calculator class.
typedef struct _xtb_TResults * xtb_TResults
Single point results class.
Functions
XTB_API_ENTRY int XTB_API_CALL xtb_getAPIVersion () XTB_API_SUFFIX__VERSION_1_0_0
Returns API version as 10000 * major + 100 * minor + 1 * patch.
XTB_API_ENTRY xtb_TEnvironment XTB_API_CALL xtb_newEnvironment (void) XTB_API_SUFFIX__VERSION_1_0_0
Create new xtb calculation environment object.
XTB_API_ENTRY void XTB_API_CALL xtb_delEnvironment (xtb_TEnvironment *) XTB_API_SUFFIX__VERSION_1_0_0
Delete a xtb calculation environment object.
XTB_API_ENTRY int XTB_API_CALL xtb_checkEnvironment (xtb_TEnvironment) XTB_API_SUFFIX__VERSION_1_0_0
Check current status of calculation environment.
XTB_API_ENTRY void XTB_API_CALL xtb_showEnvironment (xtb_TEnvironment, const char *) XTB_API_SUFFIX__VERSION_1_0_0
Show and empty error stack.
XTB_API_ENTRY void XTB_API_CALL xtb_getError (xtb_TEnvironment, char *, const int *) XTB_API_SUFFIX__VERSION_1_0_0
Return and empty error stack.
XTB_API_ENTRY void XTB_API_CALL xtb_setOutput (xtb_TEnvironment, const char *) XTB_API_SUFFIX__VERSION_1_0_0
Bind output from this environment.
XTB_API_ENTRY void XTB_API_CALL xtb_releaseOutput (xtb_TEnvironment) XTB_API_SUFFIX__VERSION_1_0_0
Release output unit from this environment.
XTB_API_ENTRY void XTB_API_CALL xtb_setVerbosity (xtb_TEnvironment, int) XTB_API_SUFFIX__VERSION_1_0_0
Set verbosity of calculation output.
XTB_API_ENTRY xtb_TMolecule XTB_API_CALL xtb_newMolecule (xtb_TEnvironment, const int *, const int *, const double *, const double *, const int *, const double *, const bool *) XTB_API_SUFFIX__VERSION_1_0_0
Create new molecular structure data (quantities in Bohr)
XTB_API_ENTRY void XTB_API_CALL xtb_delMolecule (xtb_TMolecule *) XTB_API_SUFFIX__VERSION_1_0_0
Delete molecular structure data.
XTB_API_ENTRY void XTB_API_CALL xtb_updateMolecule (xtb_TEnvironment, xtb_TMolecule, const double *, const double *) XTB_API_SUFFIX__VERSION_1_0_0
Update coordinates and lattice parameters (quantities in Bohr)
XTB_API_ENTRY xtb_TCalculator XTB_API_CALL xtb_newCalculator (void) XTB_API_SUFFIX__VERSION_1_0_0
Create new calculator object.
XTB_API_ENTRY void XTB_API_CALL xtb_delCalculator (xtb_TCalculator *) XTB_API_SUFFIX__VERSION_1_0_0
Delete calculator object.
XTB_API_ENTRY void XTB_API_CALL xtb_loadGFN0xTB (xtb_TEnvironment, xtb_TMolecule, xtb_TCalculator, char *) XTB_API_SUFFIX__VERSION_1_0_0
Load GFN0-xTB calculator.
XTB_API_ENTRY void XTB_API_CALL xtb_loadGFN1xTB (xtb_TEnvironment, xtb_TMolecule, xtb_TCalculator, char *) XTB_API_SUFFIX__VERSION_1_0_0
Load GFN1-xTB calculator.
XTB_API_ENTRY void XTB_API_CALL xtb_loadGFN2xTB (xtb_TEnvironment, xtb_TMolecule, xtb_TCalculator, char *) XTB_API_SUFFIX__VERSION_1_0_0
Load GFN2-xTB calculator.
XTB_API_ENTRY void XTB_API_CALL xtb_loadGFNFF (xtb_TEnvironment, xtb_TMolecule, xtb_TCalculator, char *) XTB_API_SUFFIX__VERSION_1_0_0
Load GFN-FF calculator.
XTB_API_ENTRY void XTB_API_CALL xtb_setSolvent (xtb_TEnvironment, xtb_TCalculator, char *, int *, double *, int *) XTB_API_SUFFIX__VERSION_1_0_0
Add a solvation model to calculator (requires loaded parametrisation)
XTB_API_ENTRY void XTB_API_CALL xtb_releaseSolvent (xtb_TEnvironment, xtb_TCalculator) XTB_API_SUFFIX__VERSION_1_0_0
Unset the solvation model.
XTB_API_ENTRY void XTB_API_CALL xtb_setExternalCharges (xtb_TEnvironment, xtb_TCalculator, int *, int *, double *, double *) XTB_API_SUFFIX__VERSION_1_0_0
Add a external charge potential to calculator (only supported in GFN1/2-xTB)
XTB_API_ENTRY void XTB_API_CALL xtb_releaseExternalCharges (xtb_TEnvironment, xtb_TCalculator) XTB_API_SUFFIX__VERSION_1_0_0
Unset the external charge potential.
XTB_API_ENTRY void XTB_API_CALL xtb_setAccuracy (xtb_TEnvironment, xtb_TCalculator, double) XTB_API_SUFFIX__VERSION_1_0_0
Set numerical accuracy of calculator in the range of 1000 to 0.0001.
XTB_API_ENTRY void XTB_API_CALL xtb_setMaxIter (xtb_TEnvironment, xtb_TCalculator, int) XTB_API_SUFFIX__VERSION_1_0_0
Set maximum number of iterations for self-consistent TB calculators.
XTB_API_ENTRY void XTB_API_CALL xtb_setElectronicTemp (xtb_TEnvironment, xtb_TCalculator, double) XTB_API_SUFFIX__VERSION_1_0_0
Set electronic temperature for level filling in tight binding calculators in K.
XTB_API_ENTRY void XTB_API_CALL xtb_singlepoint (xtb_TEnvironment, xtb_TMolecule, xtb_TCalculator, xtb_TResults) XTB_API_SUFFIX__VERSION_1_0_0
Perform singlepoint calculation.
XTB_API_ENTRY xtb_TResults XTB_API_CALL xtb_newResults (void) XTB_API_SUFFIX__VERSION_1_0_0
Create new singlepoint results object.
XTB_API_ENTRY void XTB_API_CALL xtb_delResults (xtb_TResults *) XTB_API_SUFFIX__VERSION_1_0_0
Delete singlepoint results object.
XTB_API_ENTRY xtb_TResults XTB_API_CALL xtb_copyResults (xtb_TResults) XTB_API_SUFFIX__VERSION_1_0_0
Create copy from a singlepoint results object.
XTB_API_ENTRY void XTB_API_CALL xtb_getEnergy (xtb_TEnvironment, xtb_TResults, double *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for energy in Hartree.
XTB_API_ENTRY void XTB_API_CALL xtb_getGradient (xtb_TEnvironment, xtb_TResults, double *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for gradient in Hartree / Bohr.
XTB_API_ENTRY void XTB_API_CALL xtb_getVirial (xtb_TEnvironment, xtb_TResults, double *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for virial in Hartree.
XTB_API_ENTRY void XTB_API_CALL xtb_getDipole (xtb_TEnvironment, xtb_TResults, double *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for dipole in e Bohr.
XTB_API_ENTRY void XTB_API_CALL xtb_getCharges (xtb_TEnvironment, xtb_TResults, double *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for partial charges in e.
XTB_API_ENTRY void XTB_API_CALL xtb_getBondOrders (xtb_TEnvironment, xtb_TResults, double *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for bond orders.
XTB_API_ENTRY void XTB_API_CALL xtb_getNao (xtb_TEnvironment, xtb_TResults, int *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for the number of basis functions.
XTB_API_ENTRY void XTB_API_CALL xtb_getOrbitalEigenvalues (xtb_TEnvironment, xtb_TResults, double *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for orbital energies in Hartree [nao].
XTB_API_ENTRY void XTB_API_CALL xtb_getOrbitalOccupations (xtb_TEnvironment, xtb_TResults, double *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for occupation numbers [nao].
XTB_API_ENTRY void XTB_API_CALL xtb_getOrbitalCoefficients (xtb_TEnvironment, xtb_TResults, double *) XTB_API_SUFFIX__VERSION_1_0_0
Query singlepoint results object for orbital coefficients [nao][nao].
Macro Definition Documentation
XTB_API_CALL
#define XTB_API_CALL
Definition at line 21 of file xtb.h.
XTB_API_ENTRY
#define XTB_API_ENTRY
Definition at line 20 of file xtb.h.
XTB_API_SUFFIX__VERSION_1_0_0
#define XTB_API_SUFFIX__VERSION_1_0_0
Definition at line 22 of file xtb.h.
XTB_API_VERSION
#define XTB_API_VERSION 10000
Define proprocessor to allow to check for specific API features.
Definition at line 25 of file xtb.h.
XTB_VERBOSITY_FULL
#define XTB_VERBOSITY_FULL 2
Possible print levels for API calls.
Definition at line 32 of file xtb.h.
XTB_VERBOSITY_MINIMAL
#define XTB_VERBOSITY_MINIMAL 1
Definition at line 33 of file xtb.h.
XTB_VERBOSITY_MUTED
#define XTB_VERBOSITY_MUTED 0
Definition at line 34 of file xtb.h.
XTB_VERSION_6_3_0
#define XTB_VERSION_6_3_0 1
Definition at line 26 of file xtb.h.
XTB_VERSION_6_3_1
#define XTB_VERSION_6_3_1 1
Definition at line 27 of file xtb.h.
XTB_VERSION_6_3_2
#define XTB_VERSION_6_3_2 1
Definition at line 28 of file xtb.h.
XTB_VERSION_6_3_3
#define XTB_VERSION_6_3_3 1
Definition at line 29 of file xtb.h.
Typedef Documentation
xtb_TCalculator
typedef struct _xtb_TCalculator* xtb_TCalculator
Single point calculator class.
Definition at line 53 of file xtb.h.
xtb_TEnvironment
typedef struct _xtb_TEnvironment* xtb_TEnvironment
Calculation environment class.
Definition at line 47 of file xtb.h.
xtb_TMolecule
typedef struct _xtb_TMolecule* xtb_TMolecule
Molecular structure data class.
Definition at line 50 of file xtb.h.
xtb_TResults
typedef struct _xtb_TResults* xtb_TResults
Single point results class.
Definition at line 56 of file xtb.h.
Function Documentation
xtb_checkEnvironment()
XTB_API_ENTRY int XTB_API_CALL xtb_checkEnvironment (xtb_TEnvironment)
Check current status of calculation environment.
Referenced by main().
xtb_copyResults()
XTB_API_ENTRY xtb_TResults XTB_API_CALL xtb_copyResults (xtb_TResults)
Create copy from a singlepoint results object.
xtb_delCalculator()
XTB_API_ENTRY void XTB_API_CALL xtb_delCalculator (xtb_TCalculator *)
Delete calculator object.
Referenced by main().
xtb_delEnvironment()
XTB_API_ENTRY void XTB_API_CALL xtb_delEnvironment (xtb_TEnvironment *)
Delete a xtb calculation environment object.
Referenced by main().
xtb_delMolecule()
XTB_API_ENTRY void XTB_API_CALL xtb_delMolecule (xtb_TMolecule *)
Delete molecular structure data.
Referenced by main().
xtb_delResults()
XTB_API_ENTRY void XTB_API_CALL xtb_delResults (xtb_TResults *)
Delete singlepoint results object.
Referenced by main().
xtb_getAPIVersion()
XTB_API_ENTRY int XTB_API_CALL xtb_getAPIVersion ()
Returns API version as 10000 * major + 100 * minor + 1 * patch.
Referenced by main().
xtb_getBondOrders()
XTB_API_ENTRY void XTB_API_CALL xtb_getBondOrders (xtb_TEnvironment , xtb_TResults , double *)
Query singlepoint results object for bond orders.
Referenced by main().
xtb_getCharges()
XTB_API_ENTRY void XTB_API_CALL xtb_getCharges (xtb_TEnvironment , xtb_TResults , double *)
Query singlepoint results object for partial charges in e.
Referenced by main().
xtb_getDipole()
XTB_API_ENTRY void XTB_API_CALL xtb_getDipole (xtb_TEnvironment , xtb_TResults , double *)
Query singlepoint results object for dipole in e Bohr.
Referenced by main().
xtb_getEnergy()
XTB_API_ENTRY void XTB_API_CALL xtb_getEnergy (xtb_TEnvironment , xtb_TResults , double *)
Query singlepoint results object for energy in Hartree.
Referenced by main().
xtb_getError()
XTB_API_ENTRY void XTB_API_CALL xtb_getError (xtb_TEnvironment , char * , const int *)
Return and empty error stack.
Referenced by main().
xtb_getGradient()
XTB_API_ENTRY void XTB_API_CALL xtb_getGradient (xtb_TEnvironment , xtb_TResults , double *)
Query singlepoint results object for gradient in Hartree / Bohr.
xtb_getNao()
XTB_API_ENTRY void XTB_API_CALL xtb_getNao (xtb_TEnvironment , xtb_TResults , int *)
Query singlepoint results object for the number of basis functions.
xtb_getOrbitalCoefficients()
XTB_API_ENTRY void XTB_API_CALL xtb_getOrbitalCoefficients (xtb_TEnvironment , xtb_TResults , double *)
Query singlepoint results object for orbital coefficients [nao][nao].
xtb_getOrbitalEigenvalues()
XTB_API_ENTRY void XTB_API_CALL xtb_getOrbitalEigenvalues (xtb_TEnvironment , xtb_TResults , double *)
Query singlepoint results object for orbital energies in Hartree [nao].
xtb_getOrbitalOccupations()
XTB_API_ENTRY void XTB_API_CALL xtb_getOrbitalOccupations (xtb_TEnvironment , xtb_TResults , double *)
Query singlepoint results object for occupation numbers [nao].
xtb_getVirial()
XTB_API_ENTRY void XTB_API_CALL xtb_getVirial (xtb_TEnvironment , xtb_TResults , double *)
Query singlepoint results object for virial in Hartree.
xtb_loadGFN0xTB()
XTB_API_ENTRY void XTB_API_CALL xtb_loadGFN0xTB (xtb_TEnvironment , xtb_TMolecule , xtb_TCalculator , char *)
Load GFN0-xTB calculator.
xtb_loadGFN1xTB()
XTB_API_ENTRY void XTB_API_CALL xtb_loadGFN1xTB (xtb_TEnvironment , xtb_TMolecule , xtb_TCalculator , char *)
Load GFN1-xTB calculator.
xtb_loadGFN2xTB()
XTB_API_ENTRY void XTB_API_CALL xtb_loadGFN2xTB (xtb_TEnvironment , xtb_TMolecule , xtb_TCalculator , char *)
Load GFN2-xTB calculator.
Referenced by main().
xtb_loadGFNFF()
XTB_API_ENTRY void XTB_API_CALL xtb_loadGFNFF (xtb_TEnvironment , xtb_TMolecule , xtb_TCalculator , char *)
Load GFN-FF calculator.
xtb_newCalculator()
XTB_API_ENTRY xtb_TCalculator XTB_API_CALL xtb_newCalculator (void)
Create new calculator object.
Referenced by main().
xtb_newEnvironment()
XTB_API_ENTRY xtb_TEnvironment XTB_API_CALL xtb_newEnvironment (void)
Create new xtb calculation environment object.
Referenced by main().
xtb_newMolecule()
XTB_API_ENTRY xtb_TMolecule XTB_API_CALL xtb_newMolecule (xtb_TEnvironment , const int * , const int * , const double * , const double * , const int * , const double * , const bool *)
Create new molecular structure data (quantities in Bohr)
Referenced by main().
xtb_newResults()
XTB_API_ENTRY xtb_TResults XTB_API_CALL xtb_newResults (void)
Create new singlepoint results object.
Referenced by main().
xtb_releaseExternalCharges()
XTB_API_ENTRY void XTB_API_CALL xtb_releaseExternalCharges (xtb_TEnvironment , xtb_TCalculator)
Unset the external charge potential.
xtb_releaseOutput()
XTB_API_ENTRY void XTB_API_CALL xtb_releaseOutput (xtb_TEnvironment)
Release output unit from this environment.
xtb_releaseSolvent()
XTB_API_ENTRY void XTB_API_CALL xtb_releaseSolvent (xtb_TEnvironment , xtb_TCalculator)
Unset the solvation model.
xtb_setAccuracy()
XTB_API_ENTRY void XTB_API_CALL xtb_setAccuracy (xtb_TEnvironment , xtb_TCalculator , double)
Set numerical accuracy of calculator in the range of 1000 to 0.0001.
Referenced by main().
xtb_setElectronicTemp()
XTB_API_ENTRY void XTB_API_CALL xtb_setElectronicTemp (xtb_TEnvironment , xtb_TCalculator , double)
Set electronic temperature for level filling in tight binding calculators in K.
Referenced by main().
xtb_setExternalCharges()
XTB_API_ENTRY void XTB_API_CALL xtb_setExternalCharges (xtb_TEnvironment , xtb_TCalculator , int * , int * , double * , double *)
Add a external charge potential to calculator (only supported in GFN1/2-xTB)
xtb_setMaxIter()
XTB_API_ENTRY void XTB_API_CALL xtb_setMaxIter (xtb_TEnvironment , xtb_TCalculator , int)
Set maximum number of iterations for self-consistent TB calculators.
Referenced by main().
xtb_setOutput()
XTB_API_ENTRY void XTB_API_CALL xtb_setOutput (xtb_TEnvironment , const char *)
Bind output from this environment.
xtb_setSolvent()
XTB_API_ENTRY void XTB_API_CALL xtb_setSolvent (xtb_TEnvironment , xtb_TCalculator , char * , int * , double * , int *)
Add a solvation model to calculator (requires loaded parametrisation)
Referenced by main().
xtb_setVerbosity()
XTB_API_ENTRY void XTB_API_CALL xtb_setVerbosity (xtb_TEnvironment , int)
Set verbosity of calculation output.
Referenced by main().
xtb_showEnvironment()
XTB_API_ENTRY void XTB_API_CALL xtb_showEnvironment (xtb_TEnvironment , const char *)
Show and empty error stack.
Referenced by main().
xtb_singlepoint()
XTB_API_ENTRY void XTB_API_CALL xtb_singlepoint (xtb_TEnvironment , xtb_TMolecule , xtb_TCalculator , xtb_TResults)
Perform singlepoint calculation.
Referenced by main().
xtb_updateMolecule()
XTB_API_ENTRY void XTB_API_CALL xtb_updateMolecule (xtb_TEnvironment , xtb_TMolecule , const double * , const double *)
Update coordinates and lattice parameters (quantities in Bohr)